### ISSUE TITLE
get rid of radio buttons in ion-select popover.

### ISSUE THREAD

**Issue by jaufgang** [ionic-team/ionic-framework#12310]
This applies for ionic 2+

`<ion-select>` displays its list using radio buttons when the popover interface is selected.    Radio boxes don't really add anything here and look ugly, especially for android (iOS looks ok because the radio boxes don't display anything for unselected items).  

It makes sense to use radio buttons for the Alert interface because the user can select and item and then change their selection before hitting the "ok" button.  The popover interface doesn't have an "ok" button so the radio boxes really don't seem to belong there.  

The action-sheet interface doesn't have radio buttons, so it seems that there is no reason the popover interface needs to have them.

**Comment by brandyscarney** [comment]
I agree with this. We should match the [Material Design spec](https://material.io/guidelines/components/menus.html#menus-behavior):

<img src="https://storage.googleapis.com/material-design/publish/material_v_11/assets/0Bzhp5Z4wHba3Y3dpRUd5MmxxdFU/components_menus_behavior2.png">

Adding to my to-do list for Ionic 4.x. Thanks!

**Comment by hitendramalviya** [comment]
Any workaround for ionic 3 I am trying to hide through display: none; it is not working at all.

**Comment by markhoward02** [comment]
I put this CSS in my app.scss and it hid the radio buttons.

.radio .radio-icon {
  display: none;
}

**Comment by raajmayukh** [comment]
The best solution for this is put these lines in variable.scss and it hides radio buttons for entire app to match material design;

`$radio-md-icon-width: 0;
$radio-md-icon-height:0;
$radio-md-icon-border-width:0;
$radio-md-icon-border-radius:0;`

**Comment by ebinezerp** [comment]
Still radio button are appearing ? Any solution for this.

**Comment by WildSunLove** [comment]
Coming upon this as well. Would be great to have a way to remove these other than adjusting global css variables lol

**Comment by DatScreamer** [comment]
> I agree with this. We should match the [Material Design spec](https://material.io/guidelines/components/menus.html#menus-behavior):
> 
> ![](https://camo.githubusercontent.com/c95495def9e211efbf0b0143ec94ef52aafa41ff/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f6d6174657269616c2d64657369676e2f7075626c6973682f6d6174657269616c5f765f31312f6173736574732f30427a6870355a34774862613359336470525564354d6d78786446552f636f6d706f6e656e74735f6d656e75735f6265686176696f72322e706e67)
> 
> Adding to my to-do list for Ionic 4.x. Thanks!

Why hasn't this been done yet?

**Comment by brandyscarney** [comment]
While we would love to fix every issue, there are almost 800 issues reported at the time of this comment and issues without workarounds get higher priority. It's not ideal but it is possible to use CSS to hide the radio in Ionic 4, see this Codepen: https://codepen.io/brandyscarney/pen/qBBoNNb

 We always welcome PRs for getting issues prioritized faster. Thanks!

**Comment by mayankkataria** [comment]
Why is that code not working in my case? I can't even style any ionic component. Am i missing something?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This was resolved via https://github.com/ionic-team/ionic-framework/pull/23474, and this update will be available in Ionic Framework v6 beta 2.
