### ISSUE TITLE
New Refresher Input: position

### ISSUE THREAD

**Issue by nathan-hammernik** [ionic-team/ionic-framework#14214]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**

Refresher only allows you to pull-down making the only obvious placement to be at the top of ion-content.

**Expected behavior:**

Similar to the way I can position infinite scroll at either the top or the bottom, I would I would like to optionally position the refresher at either the top or the bottom of the ion-content. When positioned at the bottom I would expect to swipe upwards to trigger the refresh.

`<ion-refresher position="top">
    <ion-refresher-content></ion-refresher-content>
</ion-refresher>`

`<ion-refresher position="bottom">
    <ion-refresher-content></ion-refresher-content>
</ion-refresher>`

`<ion-refresher [position]="myPosition">
    <ion-refresher-content></ion-refresher-content>
</ion-refresher>`

**Comment by Jahrenski** [comment]
I would also allow to set a different parent than ion-content to reside into.
This would allow you to display the pulling effect in a specific area wherever you need it to be.

**Comment by 7freaks-otte** [comment]
Are there any plans to implement this? This would make it possible to add a refresher to the bottom of a chat, similar to the one the slack app uses. ion-infinite-scroll is a possible workaround but it is triggered every time the user scrolls to the most recent chat message and not only on intentional swipe up to refresh.

**Comment by jmadelaine** [comment]
Yes, it's a bit frustrating that the refresher translates the direct child of `ion-content`. It should render inside its parent, not just at the top of the content.

**Comment by liamdebeasi** [comment]
Thanks for the issue! At the moment, we have no plans to add a `position` feature for `ion-refresher`.

The primary use case provided here is for chat apps, but we are unable to find any examples of chat apps that implement this behavior. Additionally, there has not been a lot of community support for this feature. If this is a feature developers would like to see get added, I recommend opening a new issue (or replying to this thread) with a use case/example app to help us better understand the problems that this feature would solve.

For now, I am going to close this. Thank you!
