### ISSUE TITLE
FR sub menu functionality to support responsive desktop apps

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-framework#14238]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Current behavior:**
For now there is now possibility to have a classical sub menu like on desktop apps, I know on mobile apps a submenu is a simple ModalPage. But to have a more desktop apps friendly ionic eco system, we need also sub menus, this is also in the MD specification
https://material.io/guidelines/components/menus.html#menus-usage
![image](https://user-images.githubusercontent.com/3778892/37949099-7da93694-3193-11e8-831b-468b61ba5ec0.png)

also most of googles browser apps like google contacts use sub menus
![image](https://user-images.githubusercontent.com/3778892/37949159-b6596770-3193-11e8-833e-92703a188e4c.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This nested/submenu functionality has been added to Ionic Framework v6 via nested `ion-popover` components.

See https://github.com/ionic-team/ionic-framework/blob/next/BETA.md for steps on getting started with the Framework v6 beta.

Info on how to use nested popovers can be found on our v6 beta documentation: https://beta.ionicframework.com/docs/api/popover#nested-popovers
