### ISSUE TITLE
v4: iOS toolbar buttons need more padding in overlays 

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-framework#14373]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**
[x] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Here is our toolbar buttons in a modal:

<img width="908" alt="screen shot 2018-04-23 at 3 14 05 pm" src="https://user-images.githubusercontent.com/6577830/39148146-8fa8e0d4-4709-11e8-839b-e3e3d73a4a69.png">

Native iOS popover:

<img src="https://user-images.githubusercontent.com/6577830/39148216-b71ad1f4-4709-11e8-99de-221a39bc0259.png">

Native iOS modal:

<img src="https://user-images.githubusercontent.com/6577830/39148244-ccdcaec2-4709-11e8-90af-c73be4480aed.PNG">

Relevant Links:

https://developer.apple.com/ios/human-interface-guidelines/views/popovers/
https://developer.apple.com/ios/human-interface-guidelines/app-architecture/modality/

**Comment by liamdebeasi** [comment]
Closing in favor of https://github.com/ionic-team/ionic-framework/issues/22778.
