### ISSUE TITLE
FR: for new dashboard component using ion-grid on v4

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-framework#14728]
**Describe the Feature Request**
We love the new ion-grid in v4 which from having a first look is great.

We already used the old grid to do a responsive dashboard, but there are some limitations on it.

Our requirements as for any dashboard are:
1) responsive screen adaptation which is already of `size-{breakpoings}="*"`
2) keep same order of widgets for different screen sizes, which you can simple to with offset-`{breakpoints}="*"`
3) keep same margin between all widgets on all screen sizes without unused space per column view, and that's the point!

This is a dashboard example from material.io
![image](https://user-images.githubusercontent.com/3778892/42382655-49efa5b2-8135-11e8-8308-c25939a234d0.png)

The order of the widgets are 1. Marketing, 2. Conversion 537, 3. Conversion 432,1M, 4. Sales, 5. Users, 6. Avg. session and so on...
In this case 1 + 2 are in the first "row" and 3 + 4 are on the second "row". If the screen is wider you can have 1 + 2 + 3 in the first "row" and 4 + 5 + 6 in the second "row". This nothing magical.

But as you can see the 2. card is much more longer then the 1. card, using the ion-grid the 3. card is placed under 1. card  but on bottom of card 2. keeping a big space between card 1 and 3.

We can handle this by using more columns on top of the grid list, but this would be much more difficult to mantain.

Perhaps we can already resolve all this problems with your grid, or with flexbox out of the box?

If not, we think having a real dashboard component which will keep in mind many aspects could be very very useful for many of us and for sure very powerful.

Something like that is very very very powerfull

https://haltu.github.io/muuri/

**Comment by liamdebeasi** [comment]
Thanks for the issue! The team is reviewing feature requests to evaluate if they would be good fits for Ionic Framework. At the moment, we have no plans to add a dashboard component.

Our reasoning is that this layout can be achieved using [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout). CSS Grid is a powerful addition to CSS that allows developers to create fluid grid systems such as the one that was requested here.

I am going to close this. Thank you!
