### ISSUE TITLE
[Ionic v4] Popover viewport center positioning

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-framework#15036]
**Ionic Info**
@ionic/angular: "4.0.0-beta.1"

**Level**
Nice to have I think but I could live without the following feature request too ;)

**Describe the Feature Request**
When no event is provided, the `Popover` will be positioned in the center of the viewport. To achieve this, the element `div.popover-content` will be created/set with `top` and `left` attributes

With this feature request I would suggest not to "position" the `Popover` in the center of the viewport but to "justify" it in the in the center of the viewport 

To achieve this I overwrite the following css

    ion-popover {
      div.popover-content {
          top: 50% !important;
          left: 50% !important;
          transform: translate(-50%, -50%) !important;
    }

**Proposal solution**
a. I think it would maybe make more sense per default when no event are provided to have the popover and its content justified in the center in the viewport and not positioned

b. If you don't think that's a good idea, could at least the `top` and `left` attributes not being added to the element itself but to a style property in oder to let us redefined these without having to use the keyword `!important`

**Screenshot**

<img width="1042" alt="capture d ecran 2018-08-04 a 08 29 26" src="https://user-images.githubusercontent.com/16886711/43673286-9970fc98-97c0-11e8-8f3a-659b35044116.png">

**Comment by snitin8994** [comment]
Can I work on this?

**Comment by prithvihv** [comment]
hey could i look into this ?

**Comment by jhkirkley** [comment]
In progress..

**Comment by bowenliang123** [comment]
still got the same problem while using 4.0beta17

**Comment by alphagamer7** [comment]
![Screen Shot 2019-04-04 at 6 25 17 PM](https://user-images.githubusercontent.com/17358908/55562571-d7514980-5711-11e9-9f84-1f9962ca3621.png)

Got same issue for ion -select interface popover when clicking on the pop over it gets shown elsewhere, any idea on how to fix this ?

**Comment by brandyscarney** [comment]
@alphagamer7 That is a different issue than the one reported. It's hard to help without seeing any code but it looks like you have a custom select. I would make sure that the select has `position: relative` applied to it. If you believe this is an issue with Ionic and not custom code, please create a new issue with steps to easily reproduce. Thank you!

**Comment by aida29** [comment]
Hi,  Can i get the code?

**Comment by florianmaxim** [comment]
@brandyscarney Why has this never been implemented? What were the arguments against this proposal? Still running into this in 2020...

**Comment by brandyscarney** [comment]
@florianmaxim There haven't been any arguments. The issue is labeled as a feature request & help wanted, meaning it's something that can be added but our team hasn't had the bandwidth to look into it. We are happy to take a look at a pull request if anyone wants to work on adding this. I can re-add the help wanted label which will add a comment on how to contribute. 🙂

**Comment by somq** [comment]
Absolute positioning also result in false positioning in some cases.

I experienced a popover being placed down to the view only at first app open (a refresh would place it properly).
I guess this is due to the dynamic calculation of top property.

**Comment by hemangshah** [comment]
@somq , I am facing the similar issue where it shows the popup at wrong position on first time. Any idea? The select is a component which rendered in DOM and from where I try to show a popup on a click event.

**Comment by somq** [comment]
@hemangshah Honestly I'm not really sure the solution I chose because it was quite some time ago, but I think I directly modified the style using the popover object.

```ts
const popover = await this.popoverController.create({ ... })
popover.style.cssText = '--width: 73vw;'
```

Hope this helps!

**Comment by igarciadev** [comment]
Thank you @somq 

> @hemangshah Honestly I'm not really sure the solution I chose because it was quite some time ago, but I think I directly modified the style using the popover object.
> 
> ```ts
> const popover = await this.popoverController.create({ ... })
> popover.style.cssText = '--width: 73vw;'
> ```
> 
> Hope this helps!

Thank you @somq , this works for me!

**Comment by peterpeterparker** [comment]
I opened this not that necessary feature request >3 years ago. I guess we are all now use to it and therefore I close it.
