### ISSUE TITLE
bug: angular, swipe back while page transitioning causes back navigation to break

### ISSUE THREAD

**Issue by sandy9git** [ionic-team/ionic-framework#15154]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.3
   @angular-devkit/schematics : 0.7.3
   @angular/cli               : 6.1.3
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.4

System:

   NodeJS : v8.11.3 (/usr/local/bin/node)
   npm    : 6.3.0
   OS     : macOS High Sierra
```

**Describe the Bug**
Navigating quickly few times between parent and child route causes the app to hang

**Steps to Reproduce**
1. Get the code from https://github.com/sandy9git/ionic-4-routes
2. Run the app
3. Navigate quickly few times by clicking on a event in the list and then back button on the next page
4. App stops responding

**Related Code**
https://github.com/sandy9git/ionic-4-routes
You can also check the blog and comments https://medium.com/@sandipmann/routing-in-ionic-4-84cb052cbe51

**Expected Behavior**
App shouldn't hang

**Additional Context**

**Comment by karvannan-thi** [comment]
Yeah, the same problem. In PWA when navigation back, the page will freeze until click somewhere

**Comment by talismandev** [comment]
Hello, guys ! I think, I have similar problem. 
It happened only in ios system, when I sometimes started to navigate quickly, the app became frozen and not respond. 

What would you recommend (what tool to use) to catch it and deal with it ?

**Comment by pipoa** [comment]
I got It happened only in ios system too, 
My case is swipe back parent> enter child view > swipe back .. > enter ... hangs
after hangs, back button is no longer response

**Comment by capc0** [comment]
just to add up: it does not only break back navigation, but also tab navigation.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23125, and a fix will be available in an upcoming release of Ionic Framework.
