### ISSUE TITLE
[Ionic v4.0.0-beta.3] Application Colors with Var

### ISSUE THREAD

**Issue by matthew-valenti** [ionic-team/ionic-framework#15229]
# Bug Report

**Ionic Info**
```
Ionic:
   ionic (Ionic CLI)          : 4.1.0 (C:\Users\matth\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

System:
   NodeJS : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm    : 5.6.0
   OS     : Windows 10
```

**Describe the Bug**
Application color variables do NOT work with var e.g. var(--ion-tabbar-background-color);
Layered color variables do work with var e.g. background-color: var(--ion-color-light);

It's unclear if this is a bug or expected behavior. But it would be nice to be able to use application variables in this way.

Application color variables are documented here:
https://beta.ionicframework.com/docs/theming/advanced/#color-language
```
--ion-backdrop-color
--ion-overlay-background-color
--ion-background-color
--ion-border-color
--ion-box-shadow-color
--ion-text-color
--ion-tabbar-background-color
--ion-tabbar-border-color
--ion-tabbar-text-color
--ion-tabbar-text-color-active
--ion-toolbar-background-color
--ion-toolbar-border-color
--ion-toolbar-color-active
--ion-toolbar-color-inactive
--ion-toolbar-text-color
--ion-item-background-color
--ion-item-background-color-active
--ion-item-border-color
--ion-item-text-color
--ion-placeholder-text-color
```

**Steps to Reproduce**
1. Create a new Ionic 4 blank project.
2. Add the following to the bottom of /src/theme/variables.scss:
```
ion-content {
    background-color: var(--ion-tabbar-background-color);
}
```
3. Background color does not change.

**Expected Behavior**
In example, above ion-content background displays as gray i.e. value of variable --ion-tabbar-background-color

**Comment by brandyscarney** [comment]
@ionic-team/framework We should discuss this.

**Comment by brandyscarney** [comment]
I discussed this with @manucorporat and we decided it would be helpful if we could provide some themes in the starters that could be changed, for example this could be commented out:

```
// uncomment to import default theme
// @import “./theme/default.css”;
```

and that could contain something like the following:

```
:root {
  --ion-background-color: #fff;
  --ion-text-color: #000;
  ...
}

.ios {
  --ion-border-color: #dedede;
  ...
}

.md {
  --ion-border-color: #c1c4cd;
  ...
}
```

We could also have a dark theme made available, or do something like this:

```
/* Light mode */
@import "./theme/default.css";

/* Dark mode */
@media (prefers-color-scheme: dark) {
  @import "./theme/dark.css";
}
```

I'm going to move this issue to the backlog as something to keep in mind, but the workaround exists to set the variables in your app, like so: https://raw.githubusercontent.com/ionic-team/ionic/master/core/src/themes/test/css-variables/css/oceanic.css

<details>

```
:root {
  --ion-backdrop-color: #1b2b34;
  --ion-overlay-background-color: #142129;

  --ion-background-color: #1b2b34;
  --ion-background-color-rgb: 27,43,52;
  --ion-background-color-step-50: #26363e;
  --ion-background-color-step-100: #324048;
  --ion-background-color-step-150: #3d4b52;
  --ion-background-color-step-200: #49555d;
  --ion-background-color-step-250: #546067;
  --ion-background-color-step-300: #5f6b71;
  --ion-background-color-step-350: #6b757b;
  --ion-background-color-step-400: #768085;
  --ion-background-color-step-450: #828a8f;
  --ion-background-color-step-500: #8d959a;
  --ion-background-color-step-550: #98a0a4;
  --ion-background-color-step-600: #a4aaae;
  --ion-background-color-step-650: #afb5b8;
  --ion-background-color-step-700: #bbbfc2;
  --ion-background-color-step-750: #c6cacc;
  --ion-background-color-step-800: #d1d5d6;
  --ion-background-color-step-850: #dddfe1;
  --ion-background-color-step-900: #e8eaeb;
  --ion-background-color-step-950: #f4f4f5;
  --ion-background-color-step-1000: #fff;

  --ion-border-color: #1b2b34;
  --ion-box-shadow-color: #000;

  --ion-text-color: #fff;
  --ion-text-color-rgb: 255,255,255;
  --ion-text-color-step-50: #f4f4f5;
  --ion-text-color-step-100: #e8eaeb;
  --ion-text-color-step-150: #dddfe1;
  --ion-text-color-step-200: #d1d5d6;
  --ion-text-color-step-250: #c6cacc;
  --ion-text-color-step-300: #bbbfc2;
  --ion-text-color-step-350: #afb5b8;
  --ion-text-color-step-400: #a4aaae;
  --ion-text-color-step-450: #98a0a4;
  --ion-text-color-step-500: #8d959a;
  --ion-text-color-step-550: #828a8f;
  --ion-text-color-step-600: #768085;
  --ion-text-color-step-650: #6b757b;
  --ion-text-color-step-700: #5f6b71;
  --ion-text-color-step-750: #546067;
  --ion-text-color-step-800: #49555d;
  --ion-text-color-step-850: #3d4b52;
  --ion-text-color-step-900: #324048;
  --ion-text-color-step-950: #26363e;
  --ion-text-color-step-1000: #1b2b34;

  --ion-tab-bar-background: #343d46;
  --ion-tab-bar-background-focused: #293039;
  --ion-tab-bar-color: #a7adba;
  --ion-tab-bar-color-activated: #549ee7;

  --ion-toolbar-background: #343d46;
  --ion-toolbar-color: #a7adba;
  --ion-toolbar-color-activated: var(--ion-color-primary);

  --ion-item-background: #343d46;
  --ion-item-background-activated: #232b34;
}
```

</details>

**Comment by paulstelzer** [comment]
@brandyscarney Is a dark mode really possible at the moment? I tried to make a dark mode design, but could not set the font color of ion-label and co.

The background of ion-item is no problem (here we have --ion-item-background). But for the ion-label we do not have such a css variable. So this is my current approach:

```
:root {
  .dark-mode {
    --ion-background-color: #000;
  }
}

.dark-mode {
  ion-label {
        --color: #fff !important;
  }
}
```

![chrome_2018-11-21_22-43-50](https://user-images.githubusercontent.com/20501666/48869860-f395bf00-edde-11e8-916d-088c03f5773f.jpg)
![chrome_2018-11-21_22-43-57](https://user-images.githubusercontent.com/20501666/48869863-f55f8280-edde-11e8-8a9a-7f66459c3faf.jpg)

**Comment by liamdebeasi** [comment]
Hi everyone,

With the upcoming [Ionic 8 release](https://ionic.io/blog/announcing-the-ionic-8-beta) we will be providing built-in themes for developers to import as suggested in https://github.com/ionic-team/ionic-framework/issues/15229#issuecomment-438740563. Developers will be able to use the global application vars to override these themes. I am going to close this, but let me know if there are any questions.
