### ISSUE TITLE
Add support for focusNext() to Input class

### ISSUE THREAD

**Issue by naveedahmed1** [ionic-team/ionic-framework#15365]
# Feature Request

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.9.1
   npm               : 5.5.1
```

**Describe the Feature Request**
In older version of Ionic there was a class `TextInput` with method `focusNext()`, which was very helpful in setting focus to next input element.

Using that, we were able to set focus to next input when the user press Enter key.

In Ionic 4, it seems that the class `TextInput` has been changed and replaced by `Input` class, which doesn't have `focusNext()` method.

It would be great, if this could be added back to the Input class.

**Comment by Jahrenski** [comment]
Also need the setBlur() !!!

**Comment by naveedahmed1** [comment]
Any update on this? Without this the forms are almost useless, since user has to tap each field to set focus which is very annoying.

**Comment by developer-macrew** [comment]
Any update on this?

**Comment by jongbonga** [comment]
@naveedahmed1 I'm actually looking for `TextInput` documentation for older version but cannot find it. can someone direct me to it please

**Comment by kestrel97** [comment]
Any updates on this?

**Comment by cyrilfr** [comment]
This feature would really improve the way you can provide a good flow to your users.

**Comment by liamdebeasi** [comment]
Hi everyone,

I spoke with the team, and we do not have plans to implement this feature at the moment. One of the challenges with this feature is that it's hard to know what the next focusable interactive should be since developers can use other form controls (such as ones from different UI libraries) with Ionic. Additionally, developers are able to change the focus order using `tabindex`. We think this is a detail best left up to the implementer using the existing `setFocus` API.
