### ISSUE TITLE
[4.0.0-beta.6] Use strong types for overlay returns, document `values` wrapper as breaking change

### ISSUE THREAD

**Issue by FdezRomero** [ionic-team/ionic-framework#15375]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.5
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v8.11.1 (/usr/local/Cellar/node@8/8.11.1/bin/node)
   npm    : 6.4.0
   OS     : macOS High Sierra
```

**Describe the Bug**
Some overlay components like Alert now return the values wrapped in a `values` object inside the `data` object. This property should be added to the overlay return type.

Input data used to be returned as `data.name` vs. the current `data.values.name`, so this should also be documented in the **breaking changes**.

**Steps to Reproduce**
See related code below.

**Related Code**
```ts
const alert = await this.alertCtrl.create({
  header: `What's your name?`,
  inputs: [{
    name: 'name',
    type: 'text'
  }],
  buttons: [
    {
      text: 'Cancel',
      role: 'cancel'
    },
    {
      text: 'OK'
    }
  ]
});

await alert.present();

const { data, role } = await alert.onDidDismiss();

// The name used to be returned in `data.name`
console.log(`Your name is ${data.values.name}`);
```

**Expected Behavior**
`data` to have the `values` property defined in its interface, and the change to be documented in the breaking changes.

**Additional Context**
Already discussed with @manucorporat in the ionic-friends channel: https://ionicteam.slack.com/archives/G044S7JA1/p1535565531000100

**Comment by liamdebeasi** [comment]
Thanks for the issue. The `onWillDismiss` and `onDidDismiss` methods are now strongly typed: https://github.com/ionic-team/ionic-framework/blob/5676bab31614200bc07229e3720a9d2f34029925/core/src/components/alert/alert.tsx#L310

I am going to close this as the original issue has been resolved. Please update to the latest version of Ionic to receive a fix for this. If you are still running into problems, please open a new issue. Thanks!
