### ISSUE TITLE
iOS Navigation Animations Inconsistent

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#15411]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
~/Projects/Issues/ionic-playground (master): ionic info
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)          : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.4
   @angular-devkit/schematics : 0.7.4
   @angular/cli               : 6.1.4
   @ionic/ng-toolkit          : 1.0.6
   @ionic/schematics-angular  : 1.0.5

System:

   NodeJS : v9.8.0 (/usr/local/Cellar/node/9.8.0/bin/node)
   npm    : 6.4.0
   OS     : macOS High Sierra
```

**Describe the Bug**
Navigation animations do not work in iOS, but do work for MD.

**Steps to Reproduce**
1. clone and build the sample app
1. run in chrome, open dev tools, toggle open the device toolbar
1. choose an Android device and refresh
1. click on "Child Page" link and note that MD nav works fine
1. click on "go home" link
1. choose iOS device and refresh
1. repeat nav from above and note that there is no animation, tough the "go home" click seems to delay for it... 

NOTE: if you refresh while on second page, everything works fine.

**Related Code**
https://github.com/plampy/ionic-playground

**Expected Behavior**
Animation works in iOS.

**Additional Context**
NOTE: second.page just defines an outlet. Refactoring this a bit as such alleviates the issue:
- https://github.com/kensodemann/ionic-playground/tree/childPageWithChildOutlet
- https://github.com/kensodemann/ionic-playground/tree/removeSecondOutlet

However, that is also a fundamental change to how the OP has architected their app. Still getting info on use case from the community member.

**Comment by kensodemann** [comment]
Updated sample project to beta.15 and the issue still exist: https://github.com/kensodemann/ionic-playground

NOTE: be sure to test by starting with the "home" route. If you reload while on "second" route the issue does not exist.

**Comment by kensodemann** [comment]
Testing this using beta.16 and verified that it is still an issue. If anything, the issue is worse in that now animations also do not fire for either MD or iOS. Also, prior, animations would sometimes fire for iOS. Notably, if you refreshed while the second page was displayed.

This seems to perhaps be because of this change: https://github.com/ionic-team/ionic/commit/d9172b7

**Comment by kensodemann** [comment]
Upgraded my sample application to use Ionic v4 GA release and this can verify that this is still an issue in the released version.

**Comment by marcusgraf** [comment]
Is there any update or workaround on this?

**Comment by kensodemann** [comment]
Upgraded my sample application to use Ionic v4.8.1 and can verify that this is still an issue in the latest version.
