### ISSUE TITLE
Manipulate picker columns with mouse scroll wheel

### ISSUE THREAD

**Issue by WhatsThatItsPat** [ionic-team/ionic-framework#15505]
# Feature Request

**Describe the Feature Request**
Add the ability to manipulate picker columns with the mouse scroll wheel. The dials are hard to use on desktop when using a mouse. You can click through them two steps at a time, or you can awkwardly click and drag them.

**Additional Context**
[Also mentioned here](https://github.com/ionic-team/ionic/issues/15500#issuecomment-419439908), but thought it deserved its own issue.

**Comment by thomaslecoeur** [comment]
For now, I've been detecting the platform and display the IonDatetime component or an IonInput type="date", which is way more user friendly than the scrollable panel.

```
{isPlatform('mobile') ? (
  <IonDatetime
    onIonChange={(e) => console.log(new Date(e.detail.value!))}
  />
) : (
  <IonInput
    type="date"
    onIonChange={(e) => {
      console.log(new Date(e.detail.value!));
    }}
  />
)}
```

**Comment by liamdebeasi** [comment]
Hi everyone,

I am going to roll this into https://github.com/ionic-team/ionic-framework/issues/24905. We have a new picker that we are using internally with `ion-datetime`. We would like to use this as the basis for the inline picker. One of the benefits of this picker is it can be manipulated with a mouse scroll wheel, which should resolve the issue reported here. Please follow the linked thread for updates.
