### ISSUE TITLE
Picker: Add cascading columns support to IonPicker component.

### ISSUE THREAD

**Issue by netsesame2** [ionic-team/ionic-framework#15710]
Current IonPicker component, just as acting in IonDatetime component, can support multi columns, however, each column is standalone, which has no relationship with others.

In fact, cascading relationship between columns sometimes is very common. 
For example, when we choose country | city | address, such choosing action is suitable for Picker UI. 

We can find some good solutions from other JS package to support cascading issues, but we hope it can be supported in ionic's own component.

https://github.com/raychenfj/ion-multi-picker 
##which now does not support V4
![image](https://github.com/raychenfj/ion-multi-picker/raw/master/img/dependent.gif?raw=true)

https://didi.github.io/cube-ui/example/#/cascade-picker

To realize it, it is very sample. Just emit a change event when user scroll one column end, and then offer an API method, to allow user update some column data. Sure, if all of these can be configured, it will be better.

Thanks for your great jobs.

**Comment by mhartington** [comment]
Sounds like a nice feature! If you would like to submit a PR to add support for this, we would gladly accept it.

**Comment by netsesame2** [comment]
Honest to say, I hope can help. 
However, I really don't know how to edit the npm source code and debug in my App. 
I've got some help that I can fork and pull, but it is too complex. In addition, it seems need to use stencil to do so.

**Comment by mikeruto** [comment]
@netsesame2 so what alternatives do we have right now ?

**Comment by netsesame2** [comment]
@mikeruto PickerController seems support now.

**Comment by mikeruto** [comment]
Oh nice! Thanks @netsesame2

**Comment by qhanw** [comment]
Is there no concrete solution yet?

**Comment by liamdebeasi** [comment]
Thanks for the request. Each picker column is designed to act independently of other columns by default. As a result, we do not plan to implement this behavior in Ionic. However, we are adding a new inline picker in Ionic 8 with APIs that will make the requested behavior easier to implement in applications. As part of this work, each column will now emit an `ionChange` event. Developers can use this event to update other column data as the value of one column changes. The work required to add this was completed in https://github.com/ionic-team/ionic-framework/pull/28689, so I am going to close this.
