### ISSUE TITLE
[IONIC 4.4.0] Fast navigation, scroll jump.

### ISSUE THREAD

**Issue by Yomyer** [ionic-team/ionic-framework#15726]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.11
   @angular-devkit/core       : 0.8.2
   @angular-devkit/schematics : 0.8.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.1.1, (and 13 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
The problem is complicated to explain. 
 
We have a nav and on the first page we have a list with 200 elements (can be a virtualscroll).  When we click on an element we go to the next page with the back option.

When we click on the back button, we go back to the main view and with the scroll correctly positioned where we left it before and then scroll.

Error: If we go too fast does the scroll and then positions by programming the scroll which gives a jump and gives a sense of error.

It is nonsense but gives bad experience to the user :)

Greetings and thanks

**Comment by mhartington** [comment]
Hi there! Can you provide a sample project and push it to github? Kind of hard to debug this without a test case

**Comment by Yomyer** [comment]
I've seen what also happens with the ionic-conference-app example, so it'll be easier.

The problem is that if you have scroll in the nav, when you go back to the previous page and scroll fast this one when it has finished the transition returns to the previous position. In the example I think you can see it.

Greetings.

![img_6826 trim](https://user-images.githubusercontent.com/6996160/46274276-2945c680-c559-11e8-80e0-f5a626083a3a.gif)

**Comment by Yomyer** [comment]
Hello, I see it's still happening in the latest version of IONIC 4.4.0. The truth is that for a fast user gives a bad experience. Can be deactivated in any way if the user scrolls?

Thank you.

**Comment by liamdebeasi** [comment]
Hey there,

Since this issue was opened there have been several fixes to scrolling in WebKit (the engine that powers Safari and WKWebView) on iOS. More recently, the WebKit team fixed an issue similar to the scroll jumping behavior you are describing in your original post.

I strongly recommend updating to the latest version of Ionic Framework and iOS as I believe this issue has been resolved. If you are still running into issues, please open a new issue. Thank you!
