### ISSUE TITLE
[ionic.12] preventDefault() or cancel dismiss() in ionModalWillDismiss

### ISSUE THREAD

**Issue by Yomyer** [ionic-team/ionic-framework#15848]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.2
   @angular-devkit/schematics : 0.8.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.1.1, (and 14 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255
```

**Describe the Bug**
I can't cancel the modal dismiss. We need this to show a "SAFE THAT WANTS TO CLOSE THE MODAL" dialog without closing the modal.

I can control the closing with an event (click) on the X-blades. But not when you click on the backdrop or use ESC.

```
modal.addEventListener('ionModalWillDismiss', (event: any) => {
      console.log('works'); //shows the message when closing the modal using modal.dismiss() 
      event.preventDefault(); //does not block the closing of the modal when using dismiss, i.e. it closes it when it should stop the event.
});
```

Thanks ;)

**Comment by ryaa** [comment]
Until this one is fixed I implemented the below workaround:
1) add backdropDismiss: true to create modal dialog options (to prevent esc or backdrop tap to close the dialog)
2) in the modal dialog component use the below (to prevent the android back button to close the dialog)

```
  public ionViewDidEnter() {
    this.backButtonSubscription = this.platform.backButton
      .subscribeWithPriority(9999, () => {
        // Run your logic to decide either to close or not
      });
  }

  public ionViewDidLeave() {
    if (this.backButtonSubscription && !this.backButtonSubscription.closed) {
      this.backButtonSubscription.unsubscribe();
    }
  }
```

I will test it more but it seems to be working on my Android device

**Comment by plchampigny** [comment]
Why is this removed from backlog? This isn't a wanted feature? We would really that to be implemented. We can't enable the backdrop dismiss because of this problem. Sometimes when a user click escape, back button on android or click in the backdrop with data in a form, this shouldn't be dismissing the modal right away, the user could have made this by error.

**Comment by nvonsternberg** [comment]
Same as pichampigny, I want to keep modal backdrop close functionality, but prevent the user from closing it on accident. We are working with a (brand new) tablet which seems to be extremely sensitive and having metastability issues. Having the ability to detect and cancel an accidental or spurious modal close seems like a reasonable and desirable feature request.

**Comment by sean-perkins** [comment]
Here is an alternative workaround based on Ionic 4 on this specific issue.

1. Get the modal element's instance in the `ionViewDidEnter` life cycle hook on your modal component.
```
async ionViewDidEnter() {
        const modal = await this.modalCtrl.getTop();
}
```

2. Next you're going to query the `ion-backdrop` from inside the modal and apply overrides for both a clickable state (mouse over style) and to bind to the click event.

```
async ionViewDidEnter() {
        const modal = await this.modalCtrl.getTop();
        const backdrop = modal.querySelector('ion-backdrop') as HTMLIonBackdropElement;
        backdrop.classList.add('clickable');
        backdrop.onclick = () => {
            // TODO perform your checks and then run this.modalCtrl.dismiss()
        };
    }
```

Our clickable class for reference:
```
.clickable {
   cursor: pointer;
}
```

3. When you're opening your modal, explicitly state that back drop dismiss is `false`.

```
backdropDismiss: false,
```


You're basically manually controlling the close of the modal, but this allows you to perform whatever safety checks or prevent logic you may need.

![518540f3b5225b93e807f3bb73203e73](https://user-images.githubusercontent.com/13732623/66425024-bcbb9e00-e9dc-11e9-91d3-9727fd6df537.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to merge this thread with https://github.com/ionic-team/ionic-framework/issues/22297 as both features are very similar.

The Ionic Team's position on this is that having a `canDismiss` feature that returns `true` if the overlay can dismiss is a very valuable feature, especially for modals. This feature would allow developers to require an action prior to the modal being dismissed or prompt the user to save their work to avoid data loss.

Please follow https://github.com/ionic-team/ionic-framework/issues/22297 for updates on this issue. Thank you!
