### ISSUE TITLE
Cannot redefine property: queue

### ISSUE THREAD

**Issue by joewoodhouse** [ionic-team/ionic-framework#15957]
# Support Question

I'm trying to build a library of webcomponents that uses `@ionic/core` for e.g. ion-grid etc.

The library of webcomponents itself builds and runs fine, so long as I `import "@ionic/core"` somewhere in the source.

However, when I then build this project for distribution, and attempt to include it in my own ionic(4) project, I get:

"Cannot redefine property: queue"

I'm pretty sure this comes from both my library and my project including the `ionic-global.ts` file (https://github.com/ionic-team/ionic/blob/45b46b4695322b1e315b2efe2d8adb9242445ed4/core/src/global/ionic-global.ts)

I would assume that only my project should be importing/running this file, and my library should not. How do I stop this from happening? I've tried to look at example projects like `ionic-pwa-elements` but that doesn't actually import "@ionic/core" as it only needs to use the modal controller.

There was an issue raised against the PWA toolkit related to this that was closed, but it didn't give any details https://github.com/ionic-team/ionic-pwa-toolkit/issues/73

**Comment by joewoodhouse** [comment]
Both the project and the library are closed source unfortunately.

**Comment by joewoodhouse** [comment]
It should be pretty easy to recreate though I hope, and quite a common use-case. If you take the `ionic-pwa-elements` and add `import '@ionic/core'` into any tsx file, you should see the same thing when you build the project. If you search the build files, you'll see that the contents of ionic-global.ts is in there.

**Comment by cbyte** [comment]
I have exactly the same problem. I created an components npm module which uses Ionic components to use in another project that uses Ionic components and the own component module. This fails into giving me the same error `Uncaught (in promise) TypeError: Cannot redefine property: queue
,` when executing twice the `defineCustomElements` method.

**Comment by joewoodhouse** [comment]
@jthoms1 any progress with this?

**Comment by yupengfei** [comment]
We encountered this bug too, it can be recurred in android 6.0, but in higher version like 7.0, everything is OK.

**Comment by yupengfei** [comment]
https://github.com/yupengfei/pie_android_not_display 
If this app is opened in PC or higher version of Android, everything is OK, but under Android 6.0, the pie would not show.

**Comment by fketchakeu** [comment]
I'm having the same issue. For example, this causes
`TypeError: Cannot redefine property: queue` :

```
import { defineCustomElements as definePWAElements } from '@ionic/pwa-elements/dist/loader';
import { defineCustomElements as defineIonicElements } from '@ionic/core/loader';

(async () => {
  await definePWAElements(window);
  await defineIonicElements(window);
})();

// "@ionic/pwa-elements": "1.0.2"
// "@ionic/core": "4.3.0"
```
