### ISSUE TITLE
[ionic v4] service proxy configuration not working

### ISSUE THREAD

**Issue by aperrot42** [ionic-team/ionic-framework#16233]
# Bug Report

**Ionic Info**

```
✔ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-beta.15
   @angular-devkit/build-angular : 0.8.6
   @angular-devkit/schematics    : 0.8.6
   @angular/cli                  : 6.2.6
   @ionic/angular-toolkit        : 1.1.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v8.10.0 (/usr/bin/node)
   npm    : 3.5.2
   OS     : Linux 4.15
```

**Describe the Bug**
proxy setting in ionic.config.json is not working.

**Steps to Reproduce**

 1. Start a ionic v4 project based on an official template :
```
ionic start myProj tabs
cd my myProj
```

2. Change the `ionic.config.json` file and add a proxies key as described in https://ionicframework.com/docs/cli/configuring.html#service-proxies 
```json
 "proxies":[{
      "path": "/about",
      "proxyUrl": "https://www.google.com/about/"
  }]
```

3. Modify the link in `myProj/src/app/home/home.page.html` to make the link point to /about (instead of "https://ionicframework.com/docs") :

```html
  <p>If you get lost, the <a target="_blank" rel="noopener" href="/about">docs</a> will be your guide.</p>
```

4. Run the app and try the link, it will not work.

```bash
ionic serve
```

**Related Code**

**Expected Behavior**
I expect the application to navigate to https://google.com/about

**Additional Context**

Note that for Ionic v3 this configuration works as expected.

**Comment by shatfield** [comment]
I am seeing this problem as well.

**Comment by furlongce** [comment]
Thanks, but the problem is not with our understanding of Angular. We're all using proxy.conf.json.. It works with Ionic V3, but not V4. It works in a web browser, but not on a device.

**Comment by GordoRank** [comment]
I have the same problem.  My proxy.config.json file works fine in browser but not on Android.

**Comment by ac3ju** [comment]
OK with ionic serve, but not with RUN ios / android / browser

**Comment by yyonggithub** [comment]
error!
![2018-12-14 19 15 23](https://user-images.githubusercontent.com/13831861/50000583-eed6bc00-ffd4-11e8-964e-6edbdf46fd9b.png)
![2018-12-14 19 15 59](https://user-images.githubusercontent.com/13831861/50000585-f1391600-ffd4-11e8-9b8f-7b799bcd40b9.png)

**Comment by dwaldrum** [comment]
Anyone figure this out? Can proxy with ionic serve too, but not run, which makes testing with a backend on the device difficult.

Anyone know of a workaround?

**Comment by moleisking** [comment]
I am getting the same issue too.

**Comment by joelcogen** [comment]
Worked for me using the doc here: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md

Namely, moving the config to `proxy.conf.json` and adding `"proxyConfig": "proxy.conf.json"` to `angular.json`.

**Comment by mollaie** [comment]
hi
I setup angular proxy and it's working fine on web, but when I published my app on android the proxy does not work and I'm facing with error 404, 
this is my proxy code : 
`{
  "/Api": {
    "target": "my-host-address/Api",
    "changeOrigin": true,
    "secure": false,
    "logLevel": "debug",
    "headers":{
      "DeviceId":"1066",
      "LanguageId":"1",
      "ClientVersion":"1.0",
      "PlatformId":"3",
      "Content-Type":"application/json"
    },
    "pathRewrite": {"^/Api" : "http://my-host-address"}
   }
}`

any one has idea ??

**Comment by codewithtushar** [comment]
Not working for me, getting below error. 

MacBook-Pro:secure_crm Tushar$ ionic serve
> ng run app:serve --host=0.0.0.0 --port=8100
[ng] Schema validation failed with the following errors:
[ng]   Data path "" should NOT have additional properties(proxyConfig).

[ERROR] ng has unexpectedly closed (exit code 1).
        
        The Ionic CLI will exit. Please check any output above for error details.

**Comment by godenji** [comment]
The comment [here](https://github.com/ionic-team/ionic/issues/16233#issuecomment-461407853) points to how to correctly setup proxy config in Ionic v4. However, as others have mentioned in this thread, something has broken for native builds in latest Ionic + Angular, perhaps related to `angular-schematics` (?).

For example, `ionic cordova run android -l` fails with the OP's error message. This worked previously, in my case it seems to be related to the switch from `ng-toolkit` to `angular-toolkit`.

**Comment by godenji** [comment]
If I remove the `proxyConfig` line from below `angular.json` config then that "fixes" the issue in the sense that the Android build will compile, but it's useless since the local dev proxy to the API server isn't present so the app doesn't work in dev mode.
```
"ionic-cordova-serve": {
  "builder": "@ionic/angular-toolkit:cordova-serve",
    "options": {
    "cordovaBuildTarget": "app:ionic-cordova-build",
    "devServerTarget": "app:serve",
    "proxyConfig": "proxy.conf.json"
  }
}
```

**Comment by georgechr** [comment]
> Not working for me, getting below error.
> 
> MacBook-Pro:secure_crm Tushar$ ionic serve
> 
> > ng run app:serve --host=0.0.0.0 --port=8100
> > [ng] Schema validation failed with the following errors:
> > [ng]   Data path "" should NOT have additional properties(proxyConfig).
> 
> [ERROR] ng has unexpectedly closed (exit code 1).
> 
> ```
>     The Ionic CLI will exit. Please check any output above for error details.
> ```

There seems to be an issue with the latest version of ionic/angular-toolkit for this. I had the same issue, then downgraded and everything was working again

**Comment by georgechr** [comment]
Is this going to get fixed? It's really getting in the way of updating our dependencies.

**Comment by mmmmyers** [comment]
Is there a workaround for this? proxyConfig is working on web builds but still not working on compiled ios or android apps :(

ionic CLI 4.10.3
@angular/core": “7.2.15”
@ionic/angular": “4.4.0”

**Comment by sahyun1** [comment]
@georgechr can you tell me which version you downgraded to?

**Comment by zevlio** [comment]
Same problem here, any updates ?

**Comment by sahyun1** [comment]
I end up using native plugin

**Comment by zevlio** [comment]
yes but then you cannot see your requests by inspecting your device... Not nice for debug...

**Comment by sahyun1** [comment]
@zevlio couldn't agree more

**Comment by ranafeb14** [comment]
Ionic:

   Ionic CLI                     : 5.0.2 (/home/user/.nvm/versions/node/v11.12.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.7
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 11 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.5


facing same issue with ionic 5.0.2. Any alternate solution ?

**Comment by marleyiam** [comment]
I'm struggling to death with this. Does someone had overcoming such issue lately by any instance ?

**Comment by marleyiam** [comment]
Well... since I need to move forward I did do job by going native with https://ionicframework.com/docs/native/http.

By doing so, no more CORS issues.

BUT, obviously life is not that easy, I had problems about inject HTTP library.

After some headache I could going further by running:
- npm i @ionic-native/http@beta --save
- npm i @ionic-native/core@beta --save

Why beta? at this point I no longer care.

Hope it can help someone else.

**Comment by SimMue** [comment]
Our company is facing the same problem.

We developed several ionic v3 apps and heavily used the proxy-configuration for development purposes (VSCode + Cordova-Extension with live-reload = true)
Now we would like to upgrade some apps to ionic v4 but can't due to this restriction. This slows down our development process as we need many different native components in our apps and have to test the apps directly on the device.

Hopefully this get fixed ASAP

**Comment by maiconm** [comment]
i'm facing this problem too...

**Comment by leonicoletti** [comment]
I also face the same issue.

**Comment by villarin** [comment]
> If I remove the `proxyConfig` line from below `angular.json` config then that "fixes" the issue in the sense that the Android build will compile, but it's useless since the local dev proxy to the API server isn't present so the app doesn't work in dev mode.
> 
> ```
> "ionic-cordova-serve": {
>   "builder": "@ionic/angular-toolkit:cordova-serve",
>     "options": {
>     "cordovaBuildTarget": "app:ionic-cordova-build",
>     "devServerTarget": "app:serve",
>     "proxyConfig": "proxy.conf.json"
>   }
> }
> ```

Thanks for this one. It gave me the clue I needed. But probably more suited for the ionic serve target.
`  "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build",
            "proxyConfig": "proxy.conf.json"
          },`

**Comment by htejwani** [comment]
Any update on this as it is not working with cordova/android device?

**Comment by mansurov1024** [comment]
It still not working..

**Comment by sebastiendelorme** [comment]
You can try this: 

For example, if you want to get data from this URL: https://domain.com/api/v5/

Edit `proxy.conf.json` file like tihs:
```
{
  "/v5": {
    "target": "https://domain.com/api/",
    "changeOrigin": true,
    "secure": true,
    "logLevel": "debug"
  }
}
```

Then, edit `Angular.json`:
```
"serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build",
            **"proxyConfig": "proxy.conf.json"**
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            },
            "ci": {
              "progress": false
            }
          }
        },
```

Run the app with:
`ionic serve -- --proxy-config proxy.conf.json`

If you want to get data from https://domain.com/api/v5/xxx, you need to write:
`this.http.get('v5/xxx')`

**Comment by SnpDeveloper** [comment]
I am following this thread for quite a long time?

A summary from my end too:

When I run in device as live reload it works since serve uses proxy.conf.json

ionic cordova run android -l

Same, if I run "ionic cordova run android" it gives 404 / unknown error.

I am not sure how can we deploy apps using ionic when people are struggling with basic http request not working in devices? Please correct me if I am missing any thing fundamental?

**Comment by Crazy-kun** [comment]
I just create a new project with ionic v5 to develop the PWA application, but a can’t do it without API requests to my backend locally. This is a basic feature, why it’s not working?

**Comment by ethanbrooks** [comment]
Just another person having the same issue with Ionic v5 who is hopping to see this resolved. ;-)

**Comment by arafathnihar** [comment]
I am getting the same issue too.

**Comment by hamza-talba** [comment]
there is no way to make ionic 4 work with proxy unless you using capacitor instead of cordova.
in capacitor.config.json add server property.
 
 "server": {
    "hostname":"example.com", //here you can put your server domain name 
    "androidScheme": "https"
  },

for more information :
https://capacitor.ionicframework.com/docs/basics/configuring-your-app/#common-configuration

**Comment by muhamedkarajic** [comment]
Can someone solve this, I was trying this proxy.conf.json approach it's setting my proxy to domain.com I think cause it's https but when i try to do it with localhost it's not working. I tried to put secure: false... but nothing seems to work.

**Comment by muhamedkarajic** [comment]
> You can try this:
> 
> For example, if you want to get data from this URL: https://domain.com/api/v5/
> 
> Edit `proxy.conf.json` file like tihs:
> 
> ```
> {
>   "/v5": {
>     "target": "https://domain.com/api/",
>     "changeOrigin": true,
>     "secure": true,
>     "logLevel": "debug"
>   }
> }
> ```
> 
> Then, edit `Angular.json`:
> 
> ```
> "serve": {
>           "builder": "@angular-devkit/build-angular:dev-server",
>           "options": {
>             "browserTarget": "app:build",
>             "proxyConfig": "proxy.conf.json"
>           },
>           "configurations": {
>             "production": {
>               "browserTarget": "app:build:production"
>             },
>             "ci": {
>               "progress": false
>             }
>           }
>         },
> ```
> 
> Run the app with:
> `ionic serve -- --proxy-config proxy.conf.json`
> 
> If you want to get data from https://domain.com/api/v5/xxx, you need to write:
> `this.http.get('v5/xxx')`

This is working partly so it's probably possible to make this a working version.

**Comment by muhamedkarajic** [comment]
Hello, by creating proxy.conf.json and running ionic serve the proxy is added automatically.

Here is a sample on how the proxy needs to look like. I hope this helps someone:

{
  "/api": {
    "target": "http://localhost:53875/",
    "changeOrigin": true,
    "secure": false,
    "logLevel": "debug"
  }
}

**Comment by htejwani** [comment]
> Hello, by creating proxy.conf.json and running ionic serve the proxy is added automatically.
> 
> Here is a sample on how the proxy needs to look like. I hope this helps someone:
> 
> {
> "/api": {
> "target": "http://localhost:53875/",
> "changeOrigin": true,
> "secure": false,
> "logLevel": "debug"
> }
> }

**Comment by tatianilima** [comment]
Same problem here with ionic 5, proxy not working

**Comment by greaterking** [comment]
What @muhamedkarajic mentioned above is the only thing that currently works.
I used this article as reference.

1. create a file called **proxy.conf.json** in root of project
2. update the angular.json around the section where the serve command is defined
```
...
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build",
     --> "proxyConfig": "proxy.conf.json" <-- add this line
          },
          "configurations": {
...
 
```
3. run `ionic serve` and thats it ...it will automatically use the proxy json file without the use of any flags
  
I could not get anything to work using ionic.config.json...wasted a lot of time on this so hopefully this will help others. There is no reason why this shouldn't work right out of the gate as making calls from local is pretty much how a lo of us start, build, and test our projects..just saying.

reference:
https://www.leonelngande.com/how-i-used-ionic-4-cli-proxy-to-redirect-api-requests-and-avoid-cors-errors/

**Comment by marracuene** [comment]
Having a similar issue.  proxy.conf.json is fine for dev but not for prod.   Cross-linking to a post I put on Ionic forum about this.
https://forum.ionicframework.com/t/cors-issue-while-shaping-working-web-app-into-a-native-ionic-app-for-android-w-capacitor/195697

**Comment by LuisManuel1983** [comment]
Ok so, I really tried this to work but proxies simple are not working in Ionic. I'm trying to see pdf files in Ionic using [ng2-pdf-viewer](https://github.com/VadimDez/ng2-pdf-viewer) and the domain where I want to extract the pdf files has a cors issue and I don't have access to that server

I followed the messages of @sebastiendelorme @muhamedkarajic & @greaterking but here is what I see:


My proxy.conf.json:
`
{
   "/files": {
        "target": "https://www.my-pdf-page.com/files/",
        "changeOrigin": true,
        "secure": false,
        "logLevel": "debug"
    }
}
`

When I do Ionic serve this is what I see

> [ng] [HPM] Proxy created: /files  ->  https://www.my-pdf-page.com/files/
> [ng] [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]

But when I do a get for example to this: http://localhost:8100/files/2019_Annual_Report.pdf
![image](https://user-images.githubusercontent.com/16975334/98953231-cf06e600-24d2-11eb-810e-775fbf32f78a.png)

I get an 404 even though in the terminal console I can see this:

> [ng] [HPM] GET /files/2019_Annual_Report.pdf -> https://www.my-pdf-page.com/files/

I even tried runnig ionic serve -- --proxy-config proxy.conf.json and still the same problem

So yeah... Hope this gets fixed some day. The work around for us was building a proxy on our backend that looks for the pdf and then serves it to the app

**Comment by tofra** [comment]
@LuisManuel1983 try changing the target in proxy.conf.json to "https://www.my-pdf-page.com"

**Comment by LuisManuel1983** [comment]
OMG dude @tofra Thank you so much, that finally did it

For anyone else that reads this, the trick that did for me is that, is for example you want to access something at:

https://www.my-pdf-page.com/files/pdfs/demo.pdf

Then the proxy should be

"/files/pdfs": {
        "target": "https://www.my-pdf-page.com",
        "changeOrigin": true,
        "secure": false,
        "logLevel": "debug"
    }

And the url to make the call from your code should be "/files/pdfs/demo.pdf"

**Comment by darkoandreev** [comment]
Hello everyone,
I think the issue still exists for native devices. I'm trying to send requests from my iOS simulator and I'm getting the following error:
![image](https://user-images.githubusercontent.com/20442015/103142751-ab5dcf00-4711-11eb-8098-61dd60c1363a.png)

I'm using `proxy.conf.json` file described in Angular official guide and I'm setting a path to proxy config file in `angular.json`. I also tried to configure the proxy in `ionic.config.json`, but still no successful request.
My assumptions are that there is a bug in Ionic framework with proxy configuration on native devices.

**proxy.conf.json**
```
{
  "/api": {
    "target": "http://localhost:8080/api",
    "secure": false,
    "pathRewrite": {
      "^/api": ""
    }
  }
}
```

**ionic.config.json**
```
  "proxies": [
    {
      "path": "/api",
      "proxyUrl": "http://localhost:8080/api"
    }
  ]
```

**Comment by caomca** [comment]
On the latest version of Angular, Google deprecated the @angular/HTTP and move to @Angular/common/http. The only option available to do REST calls is using the HttpClient library that implements the XmlHttpRequest protocol. This protocol will trigger the CORS issues in many requests. 

1. If your application will be deployed only on mobile I suggest you use the Ionic Native HTTP plugin (https://ionicframework.com/docs/native/http). This will never give you a CORS issue based on the native implementation that is a series of HTTP calls and not a XmlHttRequest. 
2. For web application you will need to work with your server/services team to add the @CrossOrigin(origins = "http://localhost:4200") annotation to your services. If you are behind a gateway you will need to do some more configuration in the gateway to make sure these annotations work property. 
3. The client proxy setup will only work on the web and not on mobile and is not a reliable production solution. Remove the proxyConfig from you angular.json file. Create a proxy.config.json on your root and pass the config path during the ionic serve -- --proxy-config proxy.config.json

**Comment by sandhuvijay87** [comment]
Any update to this issue??
I am using Ionic 5 + Angular 11. Proxies sre working fine on web browser but not working on device.
Its been two days and I am still searching for the solution.
Or the wrapper around ionic native http and angular httpclient can solve this issue?

**Comment by mcasami-frit** [comment]
> ¿Alguna actualización de este problema?
> Estoy usando Ionic 5 + Angular 11. Los proxies funcionan bien en el navegador web pero no en el dispositivo.
> Han pasado dos días y todavía estoy buscando la solución.
> ¿O la envoltura alrededor de http nativo iónico y httpclient angular puede resolver este problema?

Did you find any solution? Thanks
