### ISSUE TITLE
feat: Translate the Time Period (am/pm) in `ion-datetime`

### ISSUE THREAD

**Issue by troydcthompson** [ionic-team/ionic-framework#16279]
# Bug Report

**Ionic Info**
```
@ionic/core@4.0.0-beta.15

Ionic: 

   ionic (Ionic CLI) : 4.2.1 (/Users/troydcthompson/.nvm/versions/node/v8.9.4/lib/node_modules/ionic)

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelistedplugins (0 plugins total)

System:

   ios-deploy : 2.0.0
   NodeJS     : v8.9.4 (/Users/troydcthompson/.nvm/versions/node/v8.9.4/bin/node)
   npm        : 6.4.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.3 Build version 9E145
```

**Describe the Bug**
There isn't a way to translate the am/pm time period in ion-datetime, whereas we can translate the cancelText, doneText, monthShortName, etc.

**Steps to Reproduce**
1. Implement i[on-datetime,](https://beta.ionicframework.com/docs/api/datetime/) 
2. Enter cancelText, doneText, monthShortName variables
3. Try to enter "A" or timePeriod

**Related Code**
Same issue as found on this  [Ionic Forum Question](https://forum.ionicframework.com/t/translate-the-time-period-am-pm-in-ion-datetime/113280)

**Expected Behavior**
Expect to have a variable for the am/pm variables that we can translate

**Comment by troydcthompson** [comment]
?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25389, and this feature will be available in an upcoming minor release of Ionic.
