### ISSUE TITLE
bug: segment button does not truncate long text correctly

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-framework#16532]
**Ionic Info**

Ionic-angular v4-beta.17

**Describe the Bug**
Ionic-Angular v4-beta.17 doesn't handle correctly long text in `ion-segment-button`. It seems that no max width applies and therefore that no ellipsis would be displayed.

**Steps to Reproduce**
1. Git clone https://github.com/peterpeterparker/ionic-segment-texxt
2. cd ionic-segment-texxt
3. nom install
4. ionic serve

**Related Code**
https://github.com/peterpeterparker/ionic-segment-texxt

**Expected Behavior**
As previously, I would expect that long text would be trimmed to the max width of the `ion-segment-button` and display with `ellipsis`

**Additional Context**

<img width="346" alt="capture d ecran 2018-11-30 a 08 34 30" src="https://user-images.githubusercontent.com/16886711/49275301-2c870100-f47b-11e8-878c-dc8b95bf3af6.png">

**Comment by manucorporat** [comment]
Hey David! can you submit a PR? let me know if you need any assistance!

**Comment by peterpeterparker** [comment]
@manucorporat I wish but, not joking, I didn't figure out how to solves it properly 🤔

**Comment by brandyscarney** [comment]
Thanks! I was able to reproduce this. I'm not sure of the *best* solution right now without looking into it more, but as a temporary fix you can add the following:

```
ion-segment-button ion-label {
  max-width: 100px;
  overflow: hidden;
}
```

See this codepen here: https://codepen.io/brandyscarney/pen/aQPQaz?ionic:mode=ios

Note: make sure you are wrapping your segment text in an `ion-label` and if you are placing icons on the top it needs to have the `layout="icon-top"` property added to look the best. This is something I want to look into fixing (the requirement to set the layout) but I haven't had a chance to yet.

@camwiegert do you have any ideas on this? Maybe something with label changed in the shuffle?

**Comment by peterpeterparker** [comment]
thx a lot @brandyscarney, your solution works just fine right now 👍 don't know why I was trying so hard to use `span` 😂

p.s.: in my app, I had to do the following for a `ion-segment` I use inside an `ion-content`, if that could help someone too:

```
ion-segment-button {
    width: calc(100% / 4);

    ion-label {
        max-width: calc(90vw / 4);
    }
}
```

**Comment by matthewdenobrega** [comment]
@brandyscarney I've done some digging on this, and the fundamental problem is that the segment-button uses a column flex layout - so you need to do text ellipsis on a row of a column layout (ion-segment-button), which is a child of a row layout (ion-segment), which is determining the widths of the ion-segment-buttons. Text-ellipsis is a pain at the best of times but I can't see how to get that to work.

I've got it working by switching ion-segment-button to display: block (which I imagine has other implications, but works in my test layout), and adding overflow: hidden to ::slotted(ion-label) (which I think should have been there anyway).

I'm happy to submit a PR, but thought it was worth checking as it's not the cleanest solve. I don't see why a column layout would be critical for segment-button, but I don't have a lot of context. Alternatively if anyone has a way of doing ellipsis on the row of a column layout within a wrapping row layout I'd be interested to see it.

**Comment by liamdebeasi** [comment]
Hi everyone,

This was fixed in https://github.com/ionic-team/ionic-framework/pull/27457 and will be available in an upcoming minor release of Ionic 7.
