### ISSUE TITLE
[4.0.0-beta.17] Respect html in action sheet buttons

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic-framework#16718]
# Feature Request

**Ionic version:**
[x] **4.BETA.17**

**Describe the Feature Request**
We would like the ability to use html tags inside actionsheet buttons. This would allow us to make it look a bit nicer and having a main text and subtext etc.

**Describe Preferred Solution**
Enable use of html in actionsheet buttons. The text param could still be used for that.

**Describe Alternatives**
A alternative could be a extra param next to text but this would also be a bit limiting

**Comment by RHinderiks** [comment]
Is there any news on when/if this will be added ?

**Comment by Schwankenson** [comment]
Would like to see this feature, too. Are there plans?

**Comment by liamdebeasi** [comment]
Thanks for the feature. I think this can be solved via https://github.com/ionic-team/ionic-framework/issues/18067.
