### ISSUE TITLE
[4.0.0-beta.19] Navigate back in tabs highlight bug

### ISSUE THREAD

**Issue by amitairos** [ionic-team/ionic-framework#16786]
# Bug Report

**Ionic version:**
4.0.0-beta.19

**Current behavior:**
When I choose a tab, it highlights the text/icon, and the other unselected tabs are grayed out. However, when I press the back button and navigate to a previous tab, the selected tab gets highlighted, but the previous tab stays highlighted

**Expected behavior:**
Previous tab should be grayed out

**Steps to reproduce:**
See explanation

**Related code:**
```<ion-tabs #tabs>
  <ion-tab-bar slot="bottom" color="secondary" selected-tab="home">
    <ion-tab-button tab="home">
      <ion-icon name="home"></ion-icon>
      <ion-label>home</ion-label>
    </ion-tab-button>
    <ion-tab-button tab="search">
      <ion-icon name="search"></ion-icon>
      <ion-label>search</ion-label>
    </ion-tab-button>
    <ion-tab-button tab="library" >
      <ion-icon src="/assets/ic_books.svg"></ion-icon>
      <ion-label>library</ion-label>
    </ion-tab-button>
  </ion-tab-bar>
</ion-tabs>
```
Routes:
```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'home',
        children: [
          {
            path: '',
            loadChildren: '../home/home.module#HomePageModule'
          },
        ]
      },
      {
        path: 'library',
        children: [
          {
            path: '',
            loadChildren: '../library/library.module#LibraryPageModule'
          },
        ]

      },
  {
    path: '',
    redirectTo: '/tabs/home',
    pathMatch: 'full'
  },
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by manucorporat** [comment]
Can you share your markup and routes?

**Comment by amitairos** [comment]
@manucorporat Updated with code

**Comment by amitairos** [comment]
@manucorporat Tried. No difference.

**Comment by manucorporat** [comment]
I can’t reproduce the issue, could you submit a repo that reproduces the issue?

**Comment by amitairos** [comment]
@manucorporat Perhaps you tried it on the web? On the web it doesn't happen, only on the phone

**Comment by kuccilim** [comment]
This issue only appear on android physical back button, but I'm not sure is it caused by code.

Had tried with `history.back()` and `NavController.goBack()`, both method will made the tab bar highlighted. (navigated tab and previous tab)

Step to reproduce:
1. create project with ionic starter tabs.
2. ionic cordova run android.
3. hit on physical back button.

```javascript  
@HostListener('document:ionBackButton', ['$event'])
  private overrideHardwareBackAction($event: any) {
    $event.detail.register(100, async () => {
       // this.nav.goBack();
       // history.back();
    });
  }
```

**Comment by colonelpopcorn** [comment]
I was able to get a similar bug with the cordova-deeplinks plugin. To reproduce on the deeplinks plugin:

1. Open app on route A
2. Pause app and open gmail or other app with deeplink you can open/click/touch
3. Open deeplink to route C
4. Notice that both route c and route a  are still highlighted

Not sure if it's related, but I didn't want to open another bug when this one sounded similar.
