### ISSUE TITLE
side menu border with split pane isn't correct color

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-framework#16792]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
The border between the split pane menu & content appears grey.

**Expected behavior:**
The border between the split pane menu & content needs to have transparency and be on top of the content.

**Steps to reproduce:**
Navigate to any split pane example: http://localhost:3333/src/components/split-pane/test/basic

The current color is 

```
1px solid var(--ion-item-border-color, var(--ion-border-color, var(--ion-color-step-150, rgba(0, 0, 0, 0.13))))
```

So this isn't an issue with rgba not being used.

<img width="1383" alt="screen shot 2018-12-17 at 5 39 28 pm" src="https://user-images.githubusercontent.com/6577830/50120409-6b5eda00-0223-11e9-9fe7-37de0a1ac77e.png">

**Comment by brandyscarney** [comment]
Note that modifying the split pane to be under the menu "fixes" it (this is obviously not the correct solution):

<img width="1385" alt="screen shot 2018-12-17 at 5 43 19 pm" src="https://user-images.githubusercontent.com/6577830/50120380-4d917500-0223-11e9-81a1-70506f197389.png">

**Comment by liamdebeasi** [comment]
Discussed with Brandy, and this is working as intended. The sidemenu does not overlap the main content, so the border is not going to take on the color of the content. Additionally, the current behavior aligns with Material Design's drawer component: https://material-components.github.io/material-components-web-catalog/#/component/drawer
