### ISSUE TITLE
put ion-refresher in sub element，icon and text will not show

### ISSUE THREAD

**Issue by qy8502** [ionic-team/ionic-framework#16811]
[4.0.0-beta.19]
when i put ion-refresher in  ion-content element, it will work. but when i put ion-refresher in other element (not first child in ion-content)，it will show an empty block without icon and text when you drap down. 

```
<ion-content>
......
<div>
<ion-refresher>
            <ion-refresher-content>
            </ion-refresher-content>
        </ion-refresher>
</div>
......
</ion-content>
```

it also not work in sub custom component.

```
<ion-content>
<aaa></aaa>
</ion-content>

```
aaa.component.html
```

<ion-refresher>
            <ion-refresher-content>
            </ion-refresher-content>
        </ion-refresher>

......
```

**Comment by paulstelzer** [comment]
Thanks for your issue! If you put it inside a child element could you test the following if this works:

```
ion-refresher { 
 z-index: 0;
}
```

Put this inside your global.scss or your component.scss

**Comment by qy8502** [comment]
> Thanks for your issue! If you put it inside a child element could you test the following if this works. Put this inside your global.scss or your component.scss:
> 
> ```
> ion-refresher { 
>  z-index: 0;
> }
> ```
> The reason that it's not working in a child element is the latest fix to set the z-index to -1. If you now drag the ion-content downwards, the ion-refresher will become visible. if you put it inside a child element, it will not work.

yes, i tryed it. but the position of ion-refresher is not right , it under the top border of the ion-content ，not above it. it is still write empty block on top of ion-content

**Comment by cannocan** [comment]
the same, have you solved it?
`
ion-refresher { position: relative;
}
`

**Comment by cannocan** [comment]
the same
```
ion-refresher { 
 z-index: 1;
}
```
![image](https://user-images.githubusercontent.com/7322048/51913242-0b0dab80-2411-11e9-9699-ee99e28989fd.png)

I only can  solved it by 
```
ion-refresher {
 position: relative;
}
```
but the refresher will scoll, not original

![image](https://user-images.githubusercontent.com/7322048/51913124-cbdf5a80-2410-11e9-9718-05f8e2bca117.png)

will  the next version be fixed (if it is a bug)?
or have a better way to solve this?

**Comment by qy8502** [comment]
sorry, no better way to solve this. except to put it out of child component .

**Comment by cannocan** [comment]
> sorry, no better way to solve this. except to put it out of child component .

But when use a custom component, it only can be a child component.
Hope this can be fixed in the future.

**Comment by nomdal** [comment]
Is there any update on this? Any easier way to use the ion-refresher as a sub-component?

**Comment by yahmez00** [comment]
I'm also experiencing this issue, when in a sub-component the 'refresh arrow' will sit below where it is supposed to.

**Comment by peterrobertz** [comment]
+1
