### ISSUE TITLE
An issue in ionic-tabs component

### ISSUE THREAD

**Issue by ganjse** [ionic-team/ionic-framework#16878]
**Ionic version:**
[x] **4.x**

**Current behavior:**

If we apply child routing on the tab page, then it is not assigned `tab-selected` class when we click on the profile `ion-tab-button`. If we go to another tab and return to the profile tab, then `tab-selected` class appears. Also, when we go to the child profile route (e.g Profile Settings), then `tab-selected` class disappears again.

**Expected behavior:**

When we click on the profile `ion-tab-button` the button always becomes active by adding the `tab-selected` class. When we go to any child route, the button stays active (class does not disappear).

**Steps to reproduce:**
1. Create app via `tabs starter`;
2. Add tab page with child routes (`<ion-router-outlet></ion-router-outlet>`);
3. After start application go from Tab One to the added tab.

**Related code:**

**tabs.page.html**

```
  <ion-tabs color="primary">
    <ion-tab-bar slot="bottom">
 <ion-tab-button tab="tab1">
   <ion-icon name="flash"></ion-icon>
   <ion-label>Tab One</ion-label>
 </ion-tab-button>

 <ion-tab-button tab="tab2">
   <ion-icon name="apps"></ion-icon>
   <ion-label>Tab Two</ion-label>
 </ion-tab-button>

 <ion-tab-button tab="tab3">
   <ion-icon name="send"></ion-icon>
   <ion-label>Tab Three</ion-label>
 </ion-tab-button>

      <ion-tab-button tab="profile">
        <div class="icon-profile"></div>
      </ion-tab-button>
    </ion-tab-bar>
  </ion-tabs>
```

**tabs.router.module**

```
const routes: Routes = [
 {
   path: 'tabs',
   component: TabsPage,
   children: [
     {
       path: 'tab1',
       children: [
         {
           path: '',
           loadChildren: '../tab1/tab1.module#Tab1PageModule'
         }
       ]
     },
     {
       path: 'tab2',
       children: [
         {
           path: '',
           loadChildren: '../tab2/tab2.module#Tab2PageModule'
         }
       ]
     },
     {
       path: 'tab3',
       children: [
         {
           path: '',
           loadChildren: '../tab3/tab3.module#Tab3PageModule'
         }
       ]
     },  
    {
        path: 'profile',
        children: [
          {
            path: '',
            loadChildren: './profile/profile.module#ProfileModule',
          },
        ],
      },
     {
       path: '',
       redirectTo: '/tabs/tab1',
       pathMatch: 'full'
     }
   ]
 },
 {
   path: '',
   redirectTo: '/tabs/tab1',
   pathMatch: 'full'
 }
];

```

**profile.router.module**

```

const routes: Routes = [
  {
    path: '',
    component: ProfilePage,
    children: [
      {
        path: '',
        loadChildren: './profile-view/profile-view.module#ProfileViewModule',
      },
      {
        path: 'settings',
        loadChildren: './profile-settings/profile-settings.module#ProfileSettingsModule',
      },
    ],
  },
];

```

**Ionic info:** 

Ionic:

  ionic (Ionic CLI)             : 4.6.0 (/usr/local/lib/node_modules/ionic)
  Ionic Framework               : @ionic/angular 4.0.0-rc.0
  @angular-devkit/build-angular : 0.10.6
  @angular-devkit/schematics    : 0.8.7
  @angular/cli                  : 7.1.4
  @ionic/angular-toolkit        : 1.1.0

Capacitor:

  capacitor (Capacitor CLI) : 1.0.0-beta.11
  @capacitor/core           : 1.0.0-beta.11

System:

  NodeJS : v10.12.0 (/usr/local/bin/node)
  npm    : 6.5.0
  OS     : macOS Mojave

**Comment by paulstelzer** [comment]
Thanks for your issue! This is related to Angular that the root of subpages gets a highlight. At the moment this is the default behaviour. I don't know what is better: highlight only if it's the exact page or (like it's now) also highlight if it's a subpage of the root page. @manucorporat what do you think?

**Comment by ganjse** [comment]
@paulstelzer Also, I want to clarify you a point. Now one of the subpages has empty  `path` and it is, in fact, a tab page by default. Imho, it’s quite logical to set button as selected when that subpage route is activated. Current behaviour, when the tab button is highlighted only after its second switching, does not look valid.

**Comment by kunalkakkad** [comment]
Hello,
Any update on this issue?

As I am facing the similar issue where I am directly calling child route on tab click so page is loading correctly but it is not showing active tab.

Kindly acknowledge any workaround ASAP.

Thanks,
Kunal Kakkad
