### ISSUE TITLE
[4.0.0-rc.0] iOS: ion-refresher not working after page change

### ISSUE THREAD

**Issue by soumyanildas** [ionic-team/ionic-framework#16886]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
ion-refresher works for the first time visiting the page. Once we go to some other pages and come back, the ion-refresher doesn't work anymore on iOS. Works as intended on Android.

**Expected behavior:**
ion-refresher should work after page changes

**Ionic info:** 

```
Ionic:

   ionic (Ionic CLI)             : 4.2.1
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.7.0-rc.3
   @angular-devkit/schematics    : 0.7.0-rc.3
   @angular/cli                  : 6.2.3
   @ionic/angular-toolkit        : not installed

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 16 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.2 Build version 9C40b
```

**Comment by yang22zhang** [comment]
I also have this problem. Have you solved it?

**Comment by DasCode94** [comment]
> 
> 
> I also have this problem. Have you solved it?

No, I haven't been able to solve it yet.

**Comment by jfluig** [comment]
I experience a similar issue on both Android an IOS with the Taps.
1-2 Pages remain the ion-refresher function. The others loose it after the revisit.

**Comment by kinggolf** [comment]
BTW - ionRefresh event emitter works, so the pull-to-refresh functionality is still present.

**Comment by kinggolf** [comment]
FYI - by adding `style="z-index: 0;"` to ion-content tag as below, ion-refresher works properly throughout my app for all platforms, iOS, Safari, Android, & Chrome with V4.0.0-rc.2.
```
    <ion-content class="icviewa" style="z-index: 0;">
      <ion-refresher (ionRefresh)="uLbds($event)">
        <ion-refresher-content></ion-refresher-content>
      </ion-refresher>
```
The ion-refresher works properly, per this [issue](https://github.com/ionic-team/ionic/issues/16254), which triggered the ion-refresher css to change.

**Comment by AMRALAA10** [comment]
I'm not gonna say anything new here, @kinggolf fix worked for me just in case you are coping better to put this on your scss 

    ion-content {
        z-index: 0;
    }

**Comment by maxtacco** [comment]
@AMRALAA10, z-index still doesn't work. I have an app that uses tabs and ion-refresher stops working after some navigation.

**Comment by neontuna** [comment]
Having the same issue - z-index fix didn't help.  This seems more pronounced on tabbed pages.

**Comment by buuug7** [comment]
look this [comment](https://github.com/ionic-team/ionic/issues/18112#issuecomment-505443305), I think it will solve your problem @neontuna  @maxtacco

**Comment by JianhuisHuang** [comment]
> Having the same issue - z-index fix didn't help. This seems more pronounced on tabbed pages.

My problem is the same as yours. Have you solved? @neontuna  Thx.

**Comment by hardslk** [comment]
I have also same problem with tabs.
