### ISSUE TITLE
Add Roboto font for MD mode

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/ionic-framework#16938]

**Comment by paulstelzer** [comment]
I would not integrate Roboto on MD mode by default. I like it small and so a font will blow it up. I would suggest to add it to the global.scss like the other imports:

```
@import "~@ionic/angular/css/core.css";
@import "~@ionic/angular/css/normalize.css";
@import "~@ionic/angular/css/structure.css";
@import "~@ionic/angular/css/typography.css";
@import "~@ionic/angular/css/padding.css";
@import "~@ionic/angular/css/float-elements.css";
@import "~@ionic/angular/css/text-alignment.css";
@import "~@ionic/angular/css/text-transformation.css";
@import "~@ionic/angular/css/flex-utils.css";
```

And then I would add another import. So every developer can decide, if he want to add roboto or not.

If someone uses vue or another package, there should be the same possibility of course

**Comment by adamdbradley** [comment]
wip: https://github.com/ionic-team/ionic/pull/15507/files

**Comment by liamdebeasi** [comment]
We have opted to focus on having Ionic Framework apps use the system fonts built into each device so we do not need to ship a copy of Roboto in each app.
