### ISSUE TITLE
New Component Request: Accordion List in Ionic

### ISSUE THREAD

**Issue by kumarmanishc** [ionic-team/ionic-framework#17094]
Thanks Ionic team for your tremendous job for revolution in technology.
But I am expecting an UI behavior of Bootstrap in Ionic Updated Version.
For Now we are creating custom according section in Ionic App.

Please make me suggest if It already there in Ionic.

Thank You :)

**Comment by AndreasGassmann** [comment]
Is this feature still planned? I could really use it in one of our projects.

I could give it a try and open a PR for it if this is generally something that you are willing to merge back.

**Comment by DwieDima** [comment]
Heres a sample accordion list from ios 14 reminder app

![ezgif com-gif-maker](https://user-images.githubusercontent.com/26873275/105499408-b92b5380-5cc1-11eb-82d8-9a258e998c9c.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22865, and this feature will be available in the next major release of Ionic Framework.

See these tweets for some sneak previews!

https://twitter.com/benjsperry/status/1352314728824102916
https://twitter.com/LiamDeBeasi/status/1364670529861537793
