### ISSUE TITLE
Upon each Ionic release provide plunker or stackblitz link

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic-framework#17090]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Upon each ionic release provide a plunker or stackblitz link of the new development environment for Angular and Javascript that devs can fork. Include as part of changelog or a sticky in this forums. For the following reasons:

1. Devs can fork the current environments and use it to report on bugs for simpler bug replication hence speeding up the process for Ionic dev's or community to determine the issue.  
2. Devs can have a reference point to check there packages, general code eg packages and scripts etc files are in alignment/up to date upon for each release.

**Comment by paulstelzer** [comment]
I think it's a good idea to have a default plunker / stackblitz, but not updated for every release. For point 2 you have the starter packages who are updated regulary, so it's not needed to update them for every release.

I think this is coming after v4 release

**Comment by bkarv** [comment]
Thanks for the consideration

**Comment by brandyscarney** [comment]
To update this issue, we do have Ionic working with Stackblitz now as of `4.7.0`: https://stackblitz.com/edit/ionic-v4-angular-tabs

I am thinking we should have an issue created with a short overview of how to create a reproduction case and sticky it for reference.

**Comment by sean-perkins** [comment]
Hello and thank you for this feature request! 

Ionic now offers component playground examples for many of our components (more being released each sprint) and includes a Stackblitz environment for Javascript, Angular, React and Vue 🎉 

These examples always use the latest released version of Ionic. 

Here is an example for reference: https://ionicframework.com/docs/api/datetime#basic-usage

**Comment by bkarv** [comment]
Thank you so much this is a great a add on!
