### ISSUE TITLE
[v4, core, feature] Option to keep Fab open

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-framework#17284]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
It would be cool to have an option to keep a Fab opened even if an action (= click) has been performed

For example:

```
<ion-fab vertical="bottom" horizontal="end" slot="fixed" id="navigation">
        <ion-fab-button>
            <ion-icon name="apps"></ion-icon>
        </ion-fab-button>
        <ion-fab-list side="top">
            <ion-fab-button onclick="a()"><ion-icon name="clipboard"></ion-icon></ion-fab-button>
            <ion-fab-button onclick="b()"><ion-icon name="help"></ion-icon></ion-fab-button>
        </ion-fab-list>
    </ion-fab>
```

This above Fab is displayed with icon `apps`. Once clicked, it will display the Fab list. Once either button with icons `clipboard` or `help` will be clicked, the all group will be closed and the button with icon `apps` will be displayed again.

This last step is the one I would like to have optional, keeping the Fab open, the Fab lists displayed.

**Workaround**

The current workaround I know to keep the Fab open is too pass the UI Event to the action in order to stop the propagation of the event

```
<ion-fab vertical="bottom" horizontal="end" slot="fixed">
     <ion-fab-button>
          <ion-icon name="apps"></ion-icon>
     </ion-fab-button>
     <ion-fab-list side="start">
          <ion-fab-button color="medium" onClick={(e: UIEvent) => this.arrowNextSlide(e)}>
               <ion-icon name="arrow-forward"></ion-icon>
          </ion-fab-button>
     </ion-fab-list>
</ion-fab>
 
     private async arrowNextSlide(e: UIEvent) {
        e.stopPropagation();

        await this.nextSlide(true);
    }
```

**Comment by centogram** [comment]
You probably do not need to add this as a feature.  Ceasing propagation can be done with a reusable directive pretty easily.  For example: 

```
import { Directive, HostListener } from '@angular/core';

@Directive({
  selector: '[click-stop-propagation]'
})
export class ClickStopPropagationDirective {

  @HostListener("click", ["$event"])
  public onClick(event: any): void {
    event.stopPropagation();
  }
}
```

Then in your fab you can just add the click-stop-propagation to any button you do not wish the onclick to propagate.  To use your example:

```
<ion-fab vertical="bottom" horizontal="end" slot="fixed">
     <ion-fab-button>
          <ion-icon name="apps"></ion-icon>
     </ion-fab-button>
     <ion-fab-list side="start">
          <ion-fab-button color="medium" click-stop-propagation onClick="nextSlide(true)">
               <ion-icon name="arrow-forward"></ion-icon>
          </ion-fab-button>
     </ion-fab-list>
</ion-fab>
```

**Comment by liamdebeasi** [comment]
Hey @peterpeterparker,

Thanks for opening an issue and apologies for the delay. The team is reviewing previously opened feature requests. Is this a feature you still need in Ionic? If so, do you have a use case for this feature?

**Comment by peterpeterparker** [comment]
haha I don't even remember in which app I noticed this feature request 🤣. let's close it. If anyone needs this, feel free to comment for reopening.
