### ISSUE TITLE
Detect the element that is receiving the focus on ionBlur

### ISSUE THREAD

**Issue by StriderRanger** [ionic-team/ionic-framework#17363]
**Ionic version:** (check one with "x")
[ ] 1.x (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] 2.x
[] 3.x
[X] 4.x

**I'm submitting a ...** (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
$event.relatedTarget is null upon an _ionBlur_ event

**Expected behavior:**
$event.relatedTarget should contain the element that is receiving the focus upon an _ionBlur_ event

**Steps to reproduce:**

**Related code:**
```
@Directive({
  selector: '[my-directive]',
  host: {
    //...
    '(ionBlur)': 'onBlur($event)'
  }
})
export class MyCustomDirective implements OnInit {
    //...
    onBlur($event) {
        console.log(event) // This logs a CustomEvent that contains information only about the element that losing the focus
        console.log(event.relatedTarget) // This logs undefined
    }
    //...
}
```
I am using this diective with an `ion-input`:
`<ion-input my-directive></ion-input>`

**Comment by paulstelzer** [comment]
Thanks for your issue! Can you add a repo so we can test it - Your parameter is $event, but you only log event. So a repo would be great to see it in action

**Comment by datawaslost** [comment]
I've encountered this same error (missing relatedTarget) in a simpler way, without any custom directive:

`<ion-textarea (ionBlur)="onBlur($event)"></ion-textarea>`

```
    onBlur(event) {
        console.log(event) // This logs a CustomEvent that contains information only about the element that losing the focus
        console.log(event.relatedTarget) // This logs undefined
    }
```

**Comment by dhruvilpatelpor** [comment]
This is for IONIC 5 it will give you value like this.
```
<ion-textarea (ionBlur)="onBlur($event)"></ion-textarea>

    onBlur(event) {
        console.log(event.srcElement.firstElementChild.value)  // get anything from ion-textarea when focus will change   }
```

**Comment by datawaslost** [comment]
This issue is about getting the element that is receiving the focus when the textarea is blurred (relatedTarget), not the textarea element itself (srcElement).

**Comment by liamdebeasi** [comment]
Thanks for the issue. We can definitely add this. Here is how you would use it:

```javascript
ionInput.addEventListener('ionBlur', (ev) => { // or you can do this via an event binding if you are using Angular
  const newFocusInput = ev.detail.relatedTarget;
});
```

The `detail` property in the event gives you access to the native blur/focus event that the browser emits.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/21777, and a fix will be available in an upcoming release of Ionic Framework.
