### ISSUE TITLE
ion-select scrollbar on chrome on windows

### ISSUE THREAD

**Issue by sante85** [ionic-team/ionic-framework#17397]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
scrollbar not appear
**Expected behavior:**
scrollbar must be showed

**Related code:**
```
 <ion-select class="font-size-18" [(ngModel)]="selectedLang" (ionChange)="changeLang()">
          <ion-select-option value="it"><span class="flag-icon flag-icon-it"></span>Italiano</ion-select-option>
          <ion-select-option value="en"><span class="flag-icon flag-icon-en"></span>English</ion-select-option>
          <ion-select-option value="es"><span class="flag-icon flag-icon-es"></span>Espanol</ion-select-option>
          <ion-select-option value="fr"><span class="flag-icon flag-icon-fr"></span>Francais</ion-select-option>
          <ion-select-option value="de"><span class="flag-icon flag-icon-de"></span>German</ion-select-option>
          <ion-select-option value="pt"><span class="flag-icon flag-icon-pt"></span>Portuguese</ion-select-option>
          <ion-select-option value="ru"><span class="flag-icon flag-icon-ru"></span>Russian</ion-select-option>
          <ion-select-option value="ja"><span class="flag-icon flag-icon-ja"></span>Japanese</ion-select-option>
        </ion-select>
```

**Other information:**

**Ionic info:** 
 ionic (Ionic CLI)             : 4.10.1 (C:\Users\sante\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.13.0
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.0
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.1, (and 5 other plugins)

System:

   Android SDK Tools : 26.0.2 (C:\Users\sante\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

**Comment by sante85** [comment]
scrollbar not appears, and final user not think can do scroll.

**Comment by sante85** [comment]
example link
https://ionicframework.com/docs/api/select/
if you select ios or md in preview and open select of months, it not scroll

**Comment by jonathan-chin** [comment]
experiencing the same thing on Mac, using Chrome

**Comment by Jay031** [comment]
> experiencing the same thing on Mac, using Chrome
> 
> here's my hotfix css:
> 
> ```
> .alert-checkbox-group::-webkit-scrollbar {
>     width: 1em;
>     display: block !important;
> }
> 
> .alert-checkbox-group::-webkit-scrollbar-track {
>     -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
> }
> 
> .alert-checkbox-group::-webkit-scrollbar-thumb {
>     background-color: darkgrey;
>     outline: 1px solid slategrey;
> }
> ```

In his case it would be: .alert-radio-group instead of checkbox.
Just had the same problem, thank you for sharing this CSS!

**Comment by nikolayr1** [comment]
Had the same issue. @jonathan-chin @Jay031 thank you for your helpfull comments. I've added this css to global.scss file to fix the issue.
`.alert-radio-group::-webkit-scrollbar,
.alert-checkbox-group::-webkit-scrollbar {
  width: 1em;
  display: block !important;
}

.alert-radio-group::-webkit-scrollbar-track,
.alert-checkbox-group::-webkit-scrollbar-track {
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

.alert-radio-group::-webkit-scrollbar-thumb,
.alert-checkbox-group::-webkit-scrollbar-thumb {
  background-color: darkgrey;
  outline: 1px solid slategrey;
}`

**Comment by paulstelzer** [comment]
I can confirm this issue! I think this is a design decision @brandyscarney

**Comment by starlleytk** [comment]
> experiencing the same thing on Mac, using Chrome
> 
> here's my hotfix css:
> 
> ```
> .alert-checkbox-group::-webkit-scrollbar {
>     width: 1em;
>     display: block !important;
> }
> 
> .alert-checkbox-group::-webkit-scrollbar-track {
>     -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
> }
> 
> .alert-checkbox-group::-webkit-scrollbar-thumb {
>     background-color: darkgrey;
>     outline: 1px solid slategrey;
> }
> ```
A long time i have this issue. Thanks!
This save my day work!

**Comment by manu2504** [comment]
Same issue, and adding action sheet css for those who would use `<ion-select interface="action-sheet" ...`

```
/*
 * Add scroll bar to select options
 * cf. https://github.com/ionic-team/ionic/issues/17397#issuecomment-496092852
 */
.action-sheet-group::-webkit-scrollbar,
.alert-radio-group::-webkit-scrollbar,
.alert-checkbox-group::-webkit-scrollbar {
  width: 1em;
  display: block !important;
}

.action-sheet-group::-webkit-scrollbar-track,
.alert-radio-group::-webkit-scrollbar-track,
.alert-checkbox-group::-webkit-scrollbar-track {
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
  box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

.action-sheet-group::-webkit-scrollbar-thumb,
.alert-radio-group::-webkit-scrollbar-thumb,
.alert-checkbox-group::-webkit-scrollbar-thumb {
  background-color: darkgrey;
  outline: 1px solid slategrey;
}
```

**Comment by dodongphure** [comment]
I found default ionic css is like this
```
.alert-checkbox-group.sc-ion-alert-md::-webkit-scrollbar,
.alert-radio-group.sc-ion-alert-md::-webkit-scrollbar,
.alert-message.sc-ion-alert-md::-webkit-scrollbar {
    display: none;
}
```
So the simplest solution is
```
.alert-checkbox-group.sc-ion-alert-md::-webkit-scrollbar,
.alert-radio-group.sc-ion-alert-md::-webkit-scrollbar,
.alert-message.sc-ion-alert-md::-webkit-scrollbar {
    display: block;
}
```
will show the default scrollbar, then can continue to style it if needed.
