### ISSUE TITLE
use component as directive

### ISSUE THREAD

**Issue by jtushar53** [ionic-team/ionic-framework#17478]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
use some component as directives like ion-ripple-effect, ion-row, ion-col, etc.

**Describe Preferred Solution**
Currently have to wrap up the element in for example 
```
<ion-ripple-effect>

</ion-ripple-effect>
```

it can be used something like below
<div ion-ripple-effect></div>
**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by brandyscarney** [comment]
Are you looking to have this added to an Angular project? 

I don't think this is something that we will be adding, but I've marked it as a feature request for now.

**Comment by jtushar53** [comment]
Yes i am, i have a project which have div all over the place. Using flex-layout as the layout engine. 
It would have been great to have something like  

<div ion-ripple-effect>
</div>

instead of 

<ion-ripple-effect>
<div></div>
</ion-ripple-effect>

**Comment by sean-perkins** [comment]
Thanks for this feature request! We do not plan to support components as directives in the Angular package. This is a less common practice and does not align with our examples/snippets/docs for usage. 

Based on the age of this feature request, we do not see enough community interest to warrant supporting it. 

Thanks again! I am going to close this feature request.
