### ISSUE TITLE
ionic-datetime does not support clearing the value set

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#17482]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

ionic-datetime does not support clearing the value once it is set

**Expected behavior:**

Allow clearing the datetime value set

**Steps to reproduce:**

Here is the ionic-datetime demo - see https://ionicframework.com/docs/api/datetime
It is not possible to clear/reset the value

Please see the issue for Ionic 3 https://github.com/ionic-team/ionic/issues/11961

**Comment by bkarv** [comment]
You can create custom picker option with your own options. Only thing you will have handle the save function and convert the date. See below.

```
<ion-datetime [pickerOptions]="customPickerOptions" [(ngModel)]="value">
      </ion-datetime>
```

```
set below function your init.


 setCustomerPickerOptions(): void {
this.customPickerOptions = {
      buttons: [{
        text: 'Cancel',
        role:'cancel',
        handler: () => console.log('Clicked Save!')
      },{
        text: 'Clear',
        handler: () => {this.value = null}
      }, {
        text: 'Save',
        handler: (data) => {
          console.log('Data', data);
          if (this.elementType === 'DATETIME') {            
            let year: string = data.year.text;
            let month: string = data.month.value < 10 ? '0' + data.month.value.toString(): data.month.value.toString();
            let day: string = data.day.text;
            let hour: string = data.hour.text;
            let minute: string = data.minute.text;
            this.value = year + '-' + month + '-' + day +'T' + hour + ':' + minute + ':00Z';
          }
          if (this.elementType === 'DATE') {            
            let year: string = data.year.text;
            let month: string = data.month.value < 10 ? '0' + data.month.value.toString(): data.month.value.toString();
            let day: string = data.day.text;
            this.value = year + '-' + month + '-' + day;
          }
          if (this.elementType === 'TIME') {    
            let hour: string = data.hour.text;
            let minute: string = data.minute.text;
            this.value = hour + ':' + minute;
          }
        }
      }]
}
```

**Comment by ciekawy** [comment]
Ideally I'd like to add a clear button to existing ones.

**Comment by ciekawy** [comment]
considering private methods it seems like currently there is no option to extend existing behavior with clear button...

**Comment by brandyscarney** [comment]
This is definitely something we can add via a `role` to the button. Will add it to our board, thanks!

**Comment by Et3rnal** [comment]
@bkarv 
```
let month: string = data.month.value < 10 ? '0' + data.month.value.toString(): data.month.value.toString();
```
I had issue where month and day numbers get swaped if the day is single digit, I have a feeling this bit has something to do with that? unfournity I decided to remove my `pickerOptions` and implment clear in diffrent way.

If this is the case I think its a bug and it should be fix @brandyscarney

**Comment by SwenVogel** [comment]
Hi, we have the same issue and struggeling with clearing an ion-datetime value. Currently we are using extra buttons in the user interface. The suggestion from "ciekawy"

> Ideally I'd like to add a clear button to existing ones."

seems like an good solution for me.

One more solution would be the addition of an "**clearInput**" property as in ion-input.
In this case two more attributes would make sense: "**clearText**" for the button label customization and "**ionClear**" for an clear event.

This seems to me like the most ionic streamlined solution.

**Comment by SwenVogel** [comment]
I would also like to add that the problem also exists in the ionic 5.x release.

**Comment by nickwinger** [comment]
+1

**Comment by John361** [comment]
+1 for a default ion-datetime with a clear button
I just think that it is ugly to redefine all buttons for just a clear button and not really normal for a framework (that I love :heart:)

**Comment by DouglasLapsley** [comment]
bkarv's solution worked for me, but definitely a +1 on adding this as a picker role.

**Comment by Neurogitmeister** [comment]
In Ionic React project `this` pupolar solution somehow didn't work out of the box (pun intended) (I am using _@nxtend/ionic-react_ for generating React code for NX):
```
const pickerOptions = {
  buttons: [
    {
       text: "Clear",
       handler: () => this.value = undefined; // Error: cannot set property 'value' of 'undefined'.
    },
    ...
  ]
}
```
Maybe this has to do with me using React FC over CC that avoids binding `this` at all, I'm not experienced enough to tell, but iIm here to share some neat trick for overcoming **_both_** _Clear_ action problem and having to reimplement _Done_ action:
```
const Foo = () => {

  const startMomentRef = useRef<HTMLIonDatetimeElement>(null);
  const endMomentRef = useRef<HTMLIonDatetimeElement>(null);

  const pickerOptions = (target: HTMLIonDatetimeElement | null) => ({
    buttons: [
      {
        text: 'Cancel',
        role: 'cancel',
      },
      {
        text: 'Clear',
        role: 'clear',
        handler: () => (target ? (target.value = undefined) : undefined),
      },
      {
        text: 'Done',
        role: 'done',
        handler: e => (target ? (target.value = e) : undefined),
      },
    ],
  });

  return(
    <>
      <IonDatetime
            ref={startMomentRef}
            placeholder="Start day"
            pickerOptions={pickerOptions(startMomentRef.current)}
            ...
      />
      <IonDatetime
            ref={endMomentRef}
            placeholder="End day"
            pickerOptions={pickerOptions(endMomentRef.current)}
            ...
      />
    </>
  )
}
```
Here I am reusing the same options for multiple pickers and they all work just fine.

If you have any suggestions on why IonDatetime isn't picking up on `this` as valid reference and how to maybe "fix it", please tell!

**Comment by NiklasMerz** [comment]
I quickly hacked together a PR. Let me know if this is done correctly and how to add tests for it.

**Comment by NiklasMerz** [comment]
The new `ion-datetime` is now in beta. Any plans on this one again?

**Comment by willmartindev** [comment]
Hey everyone, this feature has been added and will be available in the next beta release of Ionic Framework v6. 🎉 

- `ion-datetime` now accepts a `showClearButton: boolean` prop that will render a "Clear" button alongside the default "Done" and "Cancel" buttons when true. 
- The text of the clear button can be modified using the `clearText: string` prop.

Any feedback on this change, the new `ion-datetime`, or Ionic Framework v6 overall are always welcome and helpful. Thanks!
