### ISSUE TITLE
Not possible to add something other than text in ion-select-option

### ISSUE THREAD

**Issue by maeisdev** [ionic-team/ionic-framework#17519]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

ion-select-option excludes everything except text

**Expected behavior:**

Possibility to add something other than text in ion-select-option, eg. flag icon, custom html elements.

**Steps to reproduce:**

Create ion-select and try to add as option, eg. ion-icon.

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 
   Ionic Framework               : @ionic/angular 4.0.1
   @angular-devkit/build-angular : 0.13.1
   @angular-devkit/schematics    : 7.3.1
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.4.0

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.17
   @capacitor/core           : 1.0.0-beta.17```

**Comment by marcjulian** [comment]
Custom html elements would be awesome!

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/18067 as it is the same request.
