### ISSUE TITLE
@ionic/vue feat: need a way to subscribe to hardware back button

### ISSUE THREAD

**Issue by jvervaeren** [ionic-team/ionic-framework#17603]
Hi all,

At the moment it seems that the Android back button is not working as intended as nothing happens when pressing it.
It seems there is no hook, for Vue users, to subscribe to the event the back button throws as opposed to the Angular implementation side (as reported and solved here: [https://github.com/ionic-team/ionic/issues/14803](https://github.com/ionic-team/ionic/issues/14803))
Is it possible to include this asap?

This is hindering development on an application I am currently creating and of course, hinders the use of Ionic v4 with the Vue framework for other users.

Expected behavior:
Android back button throws event that Vue platform users can subscribe to.

**Comment by sahakyan-dev** [comment]
Here is a temporary workaround
`import { Plugins } from '@capacitor/core'`
`Plugins.App.addListener('backButton', function() {
  // Your code here
});`

**Comment by liamdebeasi** [comment]
Thanks! This has been fixed and will be available in Ionic Vue 0.4.0. We recently released a new Ionic Vue beta built with Vue 3. For more information, please see: https://ionicframework.com/blog/announcing-the-new-ionic-vue-beta/

**Comment by liamdebeasi** [comment]
Hi everyone,

This has been released as part of Ionic Vue 0.4.0. Please open a new GitHub issue for any additional bugs you find. Thanks!

Upgrade:

```
npm i @ionic/vue@0.4.0 @ionic/vue-router@0.4.0
```
