### ISSUE TITLE
DataSource and Data Grid for Ionic 4

### ISSUE THREAD

**Issue by BenHayat** [ionic-team/ionic-framework#17629]
Once in the production, Ionic 4 will be holding a very special place between the developer layer and framework layer (AG, React and Vue). This spacial UI layer, the UI components is where most of the developers will be depending on for building large Line of Business application.
My humble request to team is, to provide a rich DataGrid/Table as part of the components. And other Chart components using the following DataSource component.

Secondly I suggest that Ionic creates a "DataSource" component that all Ionic component can use this "DataSource" component as their Data Source, and we, as developers can point the "Datasource" component to different sources, i.e. Firebase Firestore or REST API source or Mobile/Desktop DB (IndexedDB or SQLite or etc.) or simply an array of data. This way the data source can change at design or runtime, but it will not affect the components, as they are connected to one source of data, the "DataSource" component

**Comment by ajonp** [comment]
This has always been a comment for Ionic to add a grid, but it makes sense to also add the dataquery like in KendoUI. I am going to start building this out in Stencil and see where I get 😁
https://www.telerik.com/kendo-angular-ui/components/grid/

**Comment by liamdebeasi** [comment]
Hi everyone,

The team does not have plans to implement this at the moment. The main reason is adding a data grid would require significant resources to complete, and we are unable to allocate those resources right now. We recommend using 3rd party solutions like https://www.telerik.com/kendo-angular-ui/components/grid/ if developers need data grids in their apps.

I am going to close this, but please let me know if there are any questions. Thanks!
