### ISSUE TITLE
Named auxiliary outlet not acting as expeced

### ISSUE THREAD

**Issue by amanitequeen** [ionic-team/ionic-framework#17713]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When I put a page in a named outlet, only the header shows, and the content has no height. when I check the component associated with outlet, it shows "EmptyOutletComponent"

console
```
//master outlet
ƒ CardComponent() {
    }
//detail outlet
f EmptyOutletComponent() {
    }
```

**Expected behavior:**
The page content should display correctly 

**Steps to reproduce:**
- start sample ionic blank project
- add a page with given html
- place component html as in the code below
- place code below in component.ts
- ionic serve, with a large enough window to activate split view
- same result as the image below

**Related code:**

html of page inserted in named outlet
```
<ion-header>
    <ion-toolbar color=primary>
        <ion-title>button page</ion-title>
    </ion-toolbar>
</ion-header>
<ion-content padding>
    <ion-item>
        <ion-label>This is the button page</ion-label>
        <ion-button slot="end">a button</ion-button>
    </ion-item>
</ion-content>
```

app component html
```
<ion-app>
  <!-- this is will hold the split pane -->
  <ion-content>
    <ion-split-pane when="md" #splitpane>
      <ion-router-outlet #masterNav></ion-router-outlet>
    
      <ion-router-outlet main name="detailNav" #detailNav></ion-router-outlet>
    </ion-split-pane>

  </ion-content>

</ion-app>
```

app component ts
```
import { Component, ViewChild } from '@angular/core';
import { Platform, IonRouterOutlet, NavController } from '@ionic/angular';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html'
})
export class AppComponent {
  toggle: boolean = true;
  @ViewChild('detailNav', { read: IonRouterOutlet })detailNav: IonRouterOutlet;
  @ViewChild('masterNav', { read: IonRouterOutlet })masterNav: IonRouterOutlet;

  constructor(
    private platform: Platform,
    public navCtrl: NavController
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.navCtrl.navigateForward([{ outlets: { detailNav : ['button'], primary: ["card"] } }]).then(() => {
        this.detailNav.activatedRoute.url.subscribe((url) => { console.log(url); } );
        console.log(this.masterNav.activatedRoute.component);
        console.log(this.detailNav.activatedRoute.component);
      });
    });
  }
}
```

**Other information:**
![image](https://user-images.githubusercontent.com/20946809/53971871-0b7b1f80-40fe-11e9-9cfc-611d32d3a1d1.png)

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\laurine.wermann\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.0
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\laurine.wermann\AppData\Local\Android\sdk)
   NodeJS            : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.7.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue with us! Would you be able to provide a repository with the code required to reproduce this issue? Thanks!

**Comment by amanitequeen** [comment]
I don't use github for my source and because of this issue I can't provide a stackbliz : https://github.com/ionic-team/ionic/issues/16354

All the code you need is there you can start with a blank project and copy the code I gave. There is only app component and two pages (and a route to these pages that's the only code I didn't gave)

**Comment by amanitequeen** [comment]
Here is a test repo, you just have to download it and launch
https://github.com/amanitequeen/test

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the follow up. If you put the following in both your `button` and `card` CSS files, can you verify whether or not this resolves the issue?

```
:host {
  height: 100%;
}
```

Thanks!

**Comment by amanitequeen** [comment]
Hello, 

I already put this css as a temporary workaround for the height and it works for that problem (I added it in global.scss so it could solve for all pages). but there is still the problem where "this.detailNav.activatedRoute.component" returns "EmptyOutletComponent" instead of the component (here it should return the buttonPage, like it does for master outlet returning CardPage).

Do you reproduce the problem with the github repo I gave ?

(btw, sorry for bad english i'm French)

**Comment by liamdebeasi** [comment]
Hi there,

We will investigate the EmptyOutletComponent scenario. If the code you provided works as a temporary workaround, then that's fine. The code I provided was just an example you could use.

Thanks!

**Comment by amanitequeen** [comment]
Thank you ! 

Sadly I didn't find a workaround for the EmptyOutletComponent scenario, let me now if you find a solution =)

**Comment by liamdebeasi** [comment]
Hi everyone,

I can confirm that Ionic does not currently support auxiliary/named outlets at the moment. There are a few open threads regarding this topic, so I'd like to consolidate these issues into https://github.com/ionic-team/ionic-framework/issues/18845 so there is a single source of truth for updates on this issue. I am going to merge this with the linked issue, but let me know if you have questions.
