### ISSUE TITLE
Input and textarea label focus 

### ISSUE THREAD

**Issue by o-t-w** [ionic-team/ionic-framework#17764]
Expected behaviour for labels is that they should focus their associated form element. This is the behaviour of the native browser `input` and `textarea` labels. This feels like a big UX fail from Ionic. Seeing as their is no obvious _box_ for the user to click on to start typing, having the label create focus is extra important as the user is likely to try to click the label.

**Comment by Spinnenzunge** [comment]
Probably related to https://github.com/ionic-team/ionic/issues/17694

**Comment by nascarjake** [comment]
+1 on this - hope this is introduced soon
