### ISSUE TITLE
[4.1.1] Ion-checkbox's internal button does not have an accessible name

### ISSUE THREAD

**Issue by shreeshbhat** [ionic-team/ionic-framework#17796]
# Bug Report

**Ionic version:**
[x] **4.1.1**

**Current behavior:**
 Ion-checkbox's button does not have an accessible name.

**Expected behavior:**
Ion-checkbox should allow a prop named aria-label and set it on Ion-checkbox's internal button.

**Steps to reproduce:**
Use Ion-checkbox in a simple html and run Lighthouse Audit from Chrome.
It shows the following error for accessibility : 

1. Buttons do not have an accessible name
When a button doesn't have an accessible name, screen readers announce it as "button", making it unusable for users who rely on screen readers.

Failing Elements
`<button type="button"></button>`

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI) : 4.3.1

System:

   NodeJS : v8.12.0
   npm    : 6.9.0
   OS     : macOS Sierra
```

**Comment by shreeshbhat** [comment]
I would like to pick this up as this is a beginner friendly fix.
To fix this, I will add a Prop named aria-label in ion-checkbox and assign it to the button used in the component.
Also, I can default it to name prop.
The changes are similar to how it is handled in ion-icon.
https://github.com/ionic-team/ionic/blob/4.1.x/core/src/components/icon/readme.md
If this approach sounds good, I will make the change and raise a PR this weekend.

**Comment by shawnm0705** [comment]
Same as <ion-select>, the internal button generated from ion-select also doesn't have aria-label
