### ISSUE TITLE
react IonInput doesnt dispatch onChange event

### ISSUE THREAD

**Issue by tonypee** [ionic-team/ionic-framework#17936]
"@ionic/react": "^0.0.5",

It is common for component libraries to expect form elements to take  'value' and 'onChange'  properties. For example using rc-form you cannot wrap the IonInput since it doesnt use onChange as expected. 

When piping the onIonChange to rc-form. I tried piping the onIonChange to onChange, and that caused an unexpected blur on key press. 

This seems to go against the (semi) standard for form elements

```
({onChange, ...props}) => <IonInput onIonChange={onChange} {...props} />) 
```

**Comment by obedm503** [comment]
Having the same issue when working with formik. `onBlur`, `onIonBlur`, and `onIonChange` are all dispatched correctly

**Comment by vpuonti** [comment]
Same issue. Fallback is to use `onInput`.

**Comment by calendee** [comment]
See #18452 for working examples of this issue.  I'm on the fence about whether Ionic should support the usual React event properties.

**Comment by tirthaguha** [comment]
> Having the same issue when working with formik. `onBlur`, `onIonBlur`, and `onIonChange` are all dispatched correctly

@obedm503 How did you get formik to work for you? its a nightmare to make it work with `ioninputs`.

**Comment by obedm503** [comment]
@tirthaguha this is what I did

```ts
function TextField ({ name }) {
  const { setFieldTouched, setFieldValue, values } = useFormikContext<any>();

  // use custom handlers to use ionic's events
  const onBlur = React.useCallback(
    (e: CustomEvent) => {
      const ionInput = e.currentTarget;
      if (!ionInput) {
        return;
      }
      setFieldTouched(name, true);
    },
    [setFieldTouched, name],
  );
  const onChange = React.useCallback(
    async (e: CustomEvent<InputChangeEventDetail>) => {
      const ionInput = e.currentTarget;
      if (!ionInput) {
        return;
      }
      const input = await ionInput.getInputElement();
      setFieldValue(name, input.value);
    },
    [setFieldValue, name],
  );

  return (
    <Field name={name}>
      {() => (
        <IonInput
          value={values[name]}
          name={name}
          onIonBlur={onBlur}
          onIonChange={onChange}
        />
      )}
    </Field>
  );
};
```

**Comment by deepakjha14** [comment]
well i am not sure but how about this,

```
<IonInput
                id="ionemail"
                name="ionemail"
                type="email"
                //onIonChange={inputFunction}
                onIonChange={(e:any)=>{
                    console.log(e);
                    formik.values.email = e.detail.value;
                    formik.handleChange(e);
                }}
                value={formik.values.email}
            />
```

**Comment by tirthaguha** [comment]
@deepakjha14 the way you're working, it becomes a bit of hardcoding, where we are hardcoding formik values to it. 

```
<IonInput
                id="ionemail"
                name="ionemail"
                type="email"
                //onIonChange={inputFunction}
                onIonChange={(e:any)=>{ 
                    console.log(e);
                    formik.values.email = e.detail.value; // we are forcing it to pick formiks values 
                    formik.handleChange(e); // and manually triggering formik's event.
                }}
                value={formik.values.email} 
            />
```
It would be difficult to generalise it. I'll have rewrite the ionChange event if my input type changes from `email` to `password`. 
```formik.values.password = e.detail.value```, and then set manually to ```value={formik.values.password}```

So probably not a preferred method

-----------

where as @obedm503 has a way where he's retaining the properties of ionInput but just mapping normal textinput events to ionEvents.  
```
<IonInput
          value={values[name]}
          name={name}
          onIonBlur={onBlur}
          onIonChange={onChange}
        />
```
Now, if the type changes from email to password, it doesn't matter. in fact, I would have proposed wrapping the ionInput in the following way

```
const CustomInput = ({
  onChange,
  onBlur,
  onFocus,
  onInput,
  ...extraProps
}: PropTypes) => {
  const ionEventList = {
    // Without the following, we need defaultProps for IonEvents
    ...(onChange && { onIonChange: onChange }),
    ...(onBlur && { onIonBlur: onBlur }),
    ...(onFocus && { onIonFocus: onFocus }),
    ...(onInput && { onIonInput: onInput }),
  };
  
  // MaxLength may not work, refer https://stackoverflow.com/questions/18510845/maxlength-ignored-for-input-type-number-in-chrome
  return (
    <IonInput
      {...ionEventList}
      {...extraProps}
    />
  );
};
```

**Comment by k3b0** [comment]
@obedm503 First of all thanks for the solution above. Saved me a lot of frustration and helped me a lot. I just wondered if you are having an issue with the tab behaviour of your forms now?

I've implemented what you did and now the setFieldTouched seems to override the default tabbing between inputs. Wondering if it's expected or not?

**Comment by obedm503** [comment]
@k3b0 just tested using tab navigation in my login page. everything seems to work as expected. Can you give more detail on "setFieldTouched seems to override the default tabbing between inputs"?

**Comment by benedictjohannes** [comment]
It's quite a pain to work with the custom made Ionic directly, where `onIonInput` is not always fired for all types, while you need `onIonChange` for others.

After numerous trial and error, here's a fairly opinionated implementation.

```javascript
import React from 'react'
import { IonInput, IonItem, IonLabel } from '@ionic/react'
// SCSS to your heart's desire
// .validationMessage {
//     display: none;
//     &.error {
//         display: block;
//         font-size: 0.8rem;
//         color: #ff3333;
//     }
// }

const defaultLabelProps = { position: 'floating' }
const defaultInputProps = {}
const IonicInput = ({
    labelText,
    labelProps = {},
    inputProps = {},
    type,
    name,
    values,
    touched,
    errors,
    setFieldValue,
    setFieldTouched,
}) => {
    const blurHandler = (e) => {
        setFieldValue(name, e.target.value)
        setFieldTouched(name)
    }
    const focusHandler = e => {
        setFieldTouched(name)
    }
    const changeHandler = e => {
        const usedValue = type!=='password' && e.target && e.target.value ? e.target.value : e.detail.value
        setFieldValue(name, usedValue)
        setFieldTouched(name)
    }
    const inputHandler = e => {
        setFieldValue(name, e.target.value)
    }
    return (
        <div>
            <IonItem className={errors && errors.email && touched.email ? 'ion-invalid' : ''}>
                <IonLabel {...{ ...defaultLabelProps, ...labelProps }}>{labelText}</IonLabel>
                <IonInput
                    type={type}
                    name={name}
                    value={values[name]}
                    onIonBlur={blurHandler}
                    onIonChange={changeHandler}
                    onIonFocus={focusHandler}
                    onIonInput={inputHandler}
                    {...{ ...defaultInputProps, ...inputProps }}
                />
            </IonItem>
            <div className={`validationMessage ${errors && errors[name] && touched[name] ? 'error' : ''}`}>
                {errors[name]}
            </div>
        </div>
    )
}

export default IonicInput

// USAGE 
//    <IonicInput
//          name='pass'
//          type='password'
//          label='Your Password'
//          { ...formikProps}
//    />
```

**Comment by liamdebeasi** [comment]
Hi everyone,

In Ionic 7 we are reworking how `ionChange` and `ionInput` are fired to better align with the native browser `change` and `input` events. This issue should be resolved with those changes.

We plan on having a public beta period where developers can test Ionic 7 and provide feedback. Since the work required to resolve this issue has been complete, I am going to close this. Let me know if there are any questions.
