### ISSUE TITLE
bug: Ionic 4 – Keyboard scroll view when ion-input is focused android

### ISSUE THREAD

**Issue by Kishor-Kumar-Namdeo** [ionic-team/ionic-framework#18023]
# Bug Report

**Ionic version:**
ionic 4 

**Current behavior:**

when i interact with app first time and focus on input keyboard open but view not scroll to top then again close app and reopen then its work fine 
**Expected behavior:**

should be focus on input and scroll view above keyboard in first time app open

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Can you provide a repository with the code required to reproduce this issue? Also can you provide the output of running `ionic info`? 

Thanks!

**Comment by Kishor-Kumar-Namdeo** [comment]
ionic info:-
Ionic:


   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 7.1.4, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview
 3.1.2, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-sim           : 7.0.0
   NodeJS            : v10.15.0 (/usr/local/Cellar/node@10/10.15.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125

**Comment by Kishor-Kumar-Namdeo** [comment]
please help...

**Comment by liamdebeasi** [comment]
Hi @Kishor-Kumar-Namdeo,

I was able to reproduce this issue in Android 5 and 6. Looks like above that seems to work fine. Thanks for the issue! We will continue to look into it.

**Comment by Aingeru72** [comment]
Try to delete the (ionFocus) method if you use them. Also try to config IonModule.forRoot() at app.module.ts with scrollAssist and/or autoFocusAssist properties.

**Comment by MaykelLlanes** [comment]
> Try to delete the (ionFocus) method if you use them. Also try to config IonModule.forRoot() at app.module.ts with scrollAssist and/or autoFocusAssist properties.

Excuse me I just want to make a clarification so that it does not create confusion, the property `autoFocusAssist ` does not exist in `IonicConfig interface` at least in **Ionic 4.6.0**. 
Greetings!!!.

**Comment by srikantkritya** [comment]
@MaykelLlanes Have you found the solution for this i have the same issue

Thank you

**Comment by liamdebeasi** [comment]
Hi everyone,

Does this issue still reproduce in the latest version of Ionic 6?
