### ISSUE TITLE
bug:  item sliding conflict with menu slides

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic-framework#18048]
# Bug Report

**Ionic version:**
[x] **4.2.1-dev.201904102020.52e5a8d**

**Current behavior:**
 item sliding blocking menu slides event

![1555400238995](https://user-images.githubusercontent.com/34495831/56193053-5e7fb500-6062-11e9-9ecc-7ac5ddd84921.gif)

**Expected behavior:**
menu can appear by sliding

**Steps to reproduce:**
[ionic-conference-app](https://github.com/ionic-team/ionic-conference-app)

**Related code:**

```
```

**Other information:**

**Ionic info:**

```
```

**Comment by martijnlutgens** [comment]
I can confirm that this issue still exists in ionic 4.4.0. When using a sliding items list you cannot drag the menu out....

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a reply. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
