### ISSUE TITLE
bug: can-go-back class is set on swipe back (affects ion-back-button and ion-menu-button visibility)

### ISSUE THREAD

**Issue by 7freaks-otte** [ionic-team/ionic-framework#18074]
# Bug Report

**Ionic version:**

[x] **4.2.0**

**Current behavior:**

When swiping back to the previous page the class `can-go-back` is not properly set on the `ion-page` element. This results in the `ion-back-button` being rendered and the `ion-menu-button` being hidden on root pages. Tapping the back button instead sets the class correctly.

**Workaround**
As I have pages that can either be the root page of a tab or a child page or even a modal page, I cannot simply remove the buttons from my markup. As a workaround until this is fixed I optionally inject `IonRouterOutlet` to detect if the page is part of the normal navigation (null if in a modal) and if the page can go back on `ionViewDidEnter` since this is fired after swiping is finished and can tell for sure if the page canGoBack or not.

```
@ViewChild(IonContent) _content: any;

constructor(@Optional() private outlet: IonRouterOutlet) { ... }

ionViewDidEnter() {
    let canGoBack = !!(this.outlet && this.outlet.canGoBack());
    if (this._content && this._content.el && this._content.el.parentNode) {
        canGoBack ? this._content.el.parentNode.classList.add('can-go-back') : this._content.el.parentNode.classList.remove('can-go-back');
    }
}
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue. Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by 7freaks-otte** [comment]
Hi @liamdebeasi,

just take the plain conference app, and navigate to the `http://localhost:8100/app/tabs/schedule` page. (I use Chrome with Chrome inspector in mobile view to be able to swipe back in the browser and still inspect the DOM.)

The `<page-schedule>` element has just `class="ion-page"`. This is correct as it is the root page of this tab. When you click on the first appointment and then on the "< Back"-Button everything stays the same. This is correct as well.

But if you tap on the first appointment again and then drag the page to the right to go back to the schedule, you will see that the `<page-schedule>` element receives `class="ion-page can-go-back"` which is wrong since it is the root page of this tab.

It seems to me, that the code which is checking `outlet.canGoBack()` to add/remove the CSS class `can-go-back` in order to automagically hide`<ion-menu-button>` and show `<ion-back-button>` is checking this while the touch swipe back is still in progress and the outlet does not yet know if the swipe will be released on the previous "page-schedule" or if it drops back to the "page-session-detail". 

This should be done (or at least checked again) after the page has actually transitioned.

(Un)fortunately a user can't see the effect in the Conference app but in my case the root page of the tab needs to have an `<ion-back-button>` as it could as well be shown as a subpage (depends on how the user navigates).

Thanks for having at look at this issue.
Michael

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue was resolved during Ionic v4/v5, but the issue was never closed out. Updating to the latest version of Ionic v5 causes this issue to no longer reproduce, so I am going to close this thread out.

If you encounter any additional problems, please open a new issue and include a code reproduction. Thank you!
