### ISSUE TITLE
feat: increase ion-checkbox icon size

### ISSUE THREAD

**Issue by gangadharjannu** [ionic-team/ionic-framework#18078]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Customise the checkbox `check` icon size.

Right now we can't customise the check icon size. The only options is to increase the overall size of the checkbox instead of increasing the icon size.
![untitled (2)](https://user-images.githubusercontent.com/7323026/56418720-14801480-6298-11e9-95b7-bb4ea0ce9df5.png)

**Describe Preferred Solution**
Would be nice to provide `prop` similar to below:   
`@prop --icon-size: Size of the checkbox icon`

**Comment by liamdebeasi** [comment]
Thanks for the issue. This functionality has been added through the `mark` CSS Shadow Part. This part allows developers to target the checkmark icon to customize it through CSS:

```css
ion-checkbox::part(mark) {
  stroke-width: 6px;
}
```

Please see https://ionicframework.com/docs/api/checkbox#css-shadow-parts for more information.
