### ISSUE TITLE
feat: Use arrows to change day/month/year HH:SS in datetime

### ISSUE THREAD

**Issue by trakhimenok** [ionic-team/ionic-framework#18122]
# Feature Request

**Ionic version:**

[x] **4.3.0**

**Describe the Feature Request**

Currently `ion-datetime` control is accessible through keyboard in non optimal way. To change day/month user should use `TAB` key to go to target value and then press `space` key to select it.

The issue with this is that if user needs to change just value in 2nd column (s)he needs to `TAB` skip all the values in 1st one (e.g. 31 days for example). This is very daunting experience. It's also does not help that while tab-jumping though values the current column is not scrolled so user can't see currently focused item when it's out of visible window.

**Describe Preferred Solution**

The better solution would be to use left-right keys to change current columns and up-down keys to navigate values. The space still can be used to select focused value to be current.

The tab key should be used/reserved to navigation between controls. So when in datetime control and `tab` pressed the datetime should close and next control should get focus.

**Describe Alternatives**

Also it would be super cool to support entering date with number keys.

**Related Code**

http://plnkr.co/edit/li6pVumtGoVGrhjTbAqg?p=preview

**Additional Context**

**Comment by alex-steinberg** [comment]
What is the plan for making ion-datetime accessible? I am not able to use it at all in my PWA or in the [docs demo](https://ionicframework.com/docs/api/picker). Are there non-standard shortcuts I can use? Many thanks.

**Comment by corneil** [comment]
Most of Ionic is really awesome but the date picker doesn't match up.
What is wrong with [https://material.io/components/date-pickers](https://material.io/components/date-pickers) this kind of date picker? Expanding this to provide for a time as well is very easy.

**Comment by willmartindev** [comment]
Thanks for the issue! `ion-datetime` has revamped keyboard navigation coming out in Framework v6.
