### ISSUE TITLE
bug: ion card flickering and data is incorrect while in infinite scroll

### ISSUE THREAD

**Issue by tmk1991** [ionic-team/ionic-framework#18222]
# Bug Report

**Ionic version:**
[x] **Angular 4.3.1**

**Current behavior:**

1. When cards are in an infinite scroll, all cards in the view have corders flicker from rounded to square.

2. Within an ion card, I have observables with async pipe that are presenting the wrong information for the given card. They show data from another card previously shown in the list. 

**Expected behavior:**
Cards shouldn't flicker.

Data shown should match the respective item.

**Steps to reproduce:**

Cards in the custom component have the following subscriptions within them.
`<!-- <ion-card> ..... <ion-card-header  *ngIf="let profile of profile$ | async"> ... -->`

**Related code:**

```
<ion-virtual-scroll
  [items]="infinite$ | async"
  [itemHeight]="itemHeight"
  [trackBy]="trackByIdx"
>
  <div *virtualItem="let d">
    <!-- i.e. <ion-card> ..... <ion-card-header  *ngIf="let profile of profile$ | async"> ... -->
    <!-- nonetheless some custom component. here I propagate out to the parent component/page -->
    <ng-container *ngTemplateOutlet="child; context: { doc: d }"></ng-container>
  </div>
</ion-virtual-scroll>
```

**Comment by narhc8** [comment]
Having same issue with ion-virtual-scroll..it just wont stop flickering or stuttering

**Comment by nickstucko** [comment]
I'm not using virtual scroll, but I can confirm my ion-cards on ios are flickering from rounded corners to square corners. Anyone else seeing this? Happy to provide a sample repository if necessary.

**Comment by DouglasLapsley** [comment]
I am having the same issue.  Version 4.6.2.

**Comment by michaelins** [comment]
My ion-cards on ios are flickering from rounded corners to square corners when I put them into ion-slides as the content of a ion-slide

**Comment by omardoma** [comment]
Same issue here
