### ISSUE TITLE
bug: hardwareBackButton config option not working as expected

### ISSUE THREAD

**Issue by ramoncarreras** [ionic-team/ionic-framework#18237]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
'hardwareBackButton' option described [here](https://ionicframework.com/docs/utilities/config#config-options) is not working.

**Expected behavior:**
Android hardware back button must be disabled.

**Related code:**

```
@NgModule({
    declarations: [
        AppComponent,
    ],
    entryComponents: [],
    imports: [
        BrowserModule,
        IonicModule.forRoot({
            hardwareBackButton: false,
        }),
        AppRoutingModule,
    ],
    providers: [
        SplashScreen,
        StatusBar,      
        {provide: RouteReuseStrategy, useClass: IonicRouteStrategy},
    ],
    bootstrap: [AppComponent],
})
```

**Ionic info:**
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/ramon.carreras/.nvm/versions/node/v8.15.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/ramon.carreras/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v8.15.1 (/Users/ramon.carreras/.nvm/versions/node/v8.15.1/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by jbagaresgaray** [comment]
any news of this issue?

**Comment by fer-fullstackdev** [comment]
Any new with this? 
I need to use this function urgently.....

**Comment by fer-fullstackdev** [comment]
Hey @jbagaresgaray 
Were you able to solve this issue?

**Comment by ramoncarreras** [comment]
This is a temporary workaround:

![image](https://user-images.githubusercontent.com/8972852/59741171-7c3be700-926a-11e9-94d0-452763dd5593.png)

**Comment by fer-fullstackdev** [comment]
@ramoncarreras 
How to make it enabled again then?
I need to enable it on special page and disable on other page.

**Comment by ramoncarreras** [comment]
![image](https://user-images.githubusercontent.com/8972852/59756463-0b0c2c00-928a-11e9-982f-84c2b8681118.png)

![image](https://user-images.githubusercontent.com/8972852/59756484-17908480-928a-11e9-8eaa-c2ae46b64e7f.png)

![image](https://user-images.githubusercontent.com/8972852/59756496-1fe8bf80-928a-11e9-9c60-a57d75aedf81.png)

**Comment by rrath-edr** [comment]
I tried the work around and its not working. Is this issue fixed?

**Comment by fernandomeridamatilla** [comment]
hello, i tried workaruound too and its not workings :(

**Comment by jackbayliss** [comment]
@fernandomeridamatilla  @rrath-edr  @fer-fullstackdev 

An actual workaround that seems to work for me on @ionic/angular 4.6.2 is : 

`
document.addEventListener("backbutton",function(e)  {
        console.log("disable back button")
      }, false);
`

![image](https://user-images.githubusercontent.com/13621738/63092453-b91a1680-bf59-11e9-990f-e396df16857b.png)

Code taken from cordova docs : [here](https://cordova.apache.org/docs/en/9.x/cordova/events/events.html#backbutton)

Seems to work on any page other than my initial first page.

**Comment by loonix** [comment]
any updates on this issue?

**Comment by jackie-d** [comment]
This article explain the solution on Ionic 5 (and 4.6+ too I think). 

https://www.damirscorner.com/blog/posts/20191122-CustomizingAndroidBackButtonInIonic4.html

**Comment by dodomui** [comment]
`if (this.platform.is('android')) {
      this.platform.backButton.subscribeWithPriority(9999, () => {
        console.log('back priority');
      });`

Tried this code, but unable to manage the android button at all, any idea what's wrong?

**Comment by jackie-d** [comment]
> `if (this.platform.is('android')) { this.platform.backButton.subscribeWithPriority(9999, () => { console.log('back priority'); });`
> 
> Tried this code, but unable to manage the android button at all, any idea what's wrong?

- What issue are you experimenting? Do you get any error in console? Can you see the console info message?

**Comment by GroupeBEL** [comment]
Hello
any news of this issue? still having the same problem

**Comment by GroupeBEL** [comment]
Ionic 5 / angular 9 or 10
this solution worked for me

```
    document.addEventListener("backbutton",function(e) {
      // Do nothing
    }, false);
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is that `hardwareBackButton: false` only disables the event listeners in Ionic Framework. The webview's default hardware back button behavior is to navigate back, which these event listeners blocked. By setting this config option, you are allowing the webview's default hardware back button behavior to happen again.

The documentation is not very clear on this, so I need to check with the team to see if this is the expected behavior.

**Comment by liamdebeasi** [comment]
Can you try the following dev build and let me know if it resolves the issue?

**Angular**
```
npm install @ionic/angular@5.6.0-dev.202011232116.155f2ae
```

**React**
```
npm install @ionic/react@5.6.0-dev.202011232116.155f2ae @ionic/react-router@5.6.0-dev.202011232116.155f2ae
```

**Vue**
```
npm install @ionic/vue@5.6.0-dev.202011232116.155f2ae @ionic/vue-router@5.6.0-dev.202011232116.155f2ae
```

**Stencil/Vanilla JavaScript**
```
npm install @ionic/core@5.6.0-dev.202011232116.155f2ae
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22555, and a fix will be available in an upcoming release of Ionic Framework.
