### ISSUE TITLE
bug: ion-input type="date" wrong height if empty

### ISSUE THREAD

**Issue by Spinnenzunge** [ionic-team/ionic-framework#18267]
# Bug Report
The default height of ion-input type="date" without value is too small. Should be the same height with or without value.

**Ionic version:**

[x] **4.4.0**

**Current behavior:**
If ion-input has no value, the default height is too small. It "grows" if you enter a value which makes the UI look bad.

**Expected behavior:**
ion-input height is the same with or without value

**Related code:**
```
<ion-item no-padding>
    <ion-label position="stacked">Date</ion-label>
    <ion-input type="date"></ion-input>
</ion-item>
```

**Other information:**
![bug_input_date_size](https://user-images.githubusercontent.com/11189008/57615570-4d03cd00-757c-11e9-8ce8-b72c18fe3380.gif)

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.1, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/pascalgraf/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.14.1 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

```

**Comment by Spinnenzunge** [comment]
I know I could use ion-datetime, nonetheless I think this could be an easy fix with a min-height default. I prefer to use input over ion-datetime for keyboard toolbar next prev functionality (which does not yet work but is another bug already reported)

**Comment by safaiyeh** [comment]
Hello! I would like to work on this, just forked the repo locally to check it out.

**Comment by cerkiner** [comment]
@safaiyeh any update on this?

**Comment by liamdebeasi** [comment]
Hey there,

Does this issue still reproduce on the latest version of Ionic?

**Comment by Spinnenzunge** [comment]
I just checked it quickly in my Project and it does not seem like it
