### ISSUE TITLE
bug: ion-datetime does not start with current time if there are multiple date time fields

### ISSUE THREAD

**Issue by ThomasPinna** [ionic-team/ionic-framework#18291]
# Bug Report

**Ionic version:**
[x] **4.10.1**

**Current behavior:**
Given a component that 2 ion-datetime fields, binded to different values, both values being `null`

When you try and set the value for the first date-time field at time x, it will propose time x as initial value.

When you then try and set the value for the second date-time field at time y, it will propose time x as initial value. 

**Expected behavior:**

When selecting 

**Steps to reproduce:**

build a page with two ionic datetime pickers

```html
<ion-datetime 
    displayFormat="DD/MMM/YYYY HH:mm"
    pickerFormat="DD/MMM/YYYY HH:mm"
    [(ngModel)]="value"
>
<ion-datetime 
    displayFormat="DD/MMM/YYYY HH:mm"
    pickerFormat="DD/MMM/YYYY HH:mm"
    [(ngModel)]="value2"
>
```

![image](https://user-images.githubusercontent.com/6748737/57864551-5f8c3980-77fc-11e9-9972-6fa2ce03afac.png)

**Other information:**

/

**Ionic info:**

```Ionic:

   ionic (Ionic CLI)             : 4.10.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, windows 6.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.3, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   NodeJS            : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! Can you provide some clarification around the problem you are seeing? I am not entirely sure what you mean by `When you try and set the value for the first date-time field at time x, it will propose time x as initial value.`.

Any code examples you have, along with expected outcomes and actual outcomes would be great!

Thanks!

**Comment by ThomasPinna** [comment]
Hi Liam!

What I meant is:

> When I press on the first datetime formfield at 16u59, it will open the datetimepicker with 16u59 as initial value. 

Anyway, meanwhile I don't think the issue is related to there being 2 datetime fields, but rather because of the initial time being loaded at the wrong moment.

how you can reproduce it:

- create a variable in your `component.ts` as follows `starttime=null`
- then, in your `component.html` you add a datetimefield that is bound to this variable
```
<ion-datetime 
    displayFormat="DD/MMM/YYYY HH:mm"
    pickerFormat="DD/MMM/YYYY HH:mm"
    [(ngModel)]="starttime"
>
```

- Now, if you load the component (by running `ionic serve` and navigating to the correct page), you will see that the input field does not contain a value.

- If you press on the datetime field, you will see a datetimepicker coming up with the current time set as default. Let's call the moment we do this `t1`.

- However, if you cancel and wait a minute, and you press again on the datetime field, it will not show the current time, it will instead show `t1`, where you would expect this to be updated to the current time.

This leads me to suspect that the datetime picker sets the current time when the component is created, instead of when it is loaded?

**Comment by ThomasPinna** [comment]
I have created a temporary work around. It is not perfect since it requires changing the model temporary, but it seems to work

in `component.html`
```
<ion-datetime 
    displayFormat="DD/MMM/YYYY HH:mm"
    pickerFormat="DD/MMM/YYYY HH:mm"
    [(ngModel)]="field.starttime"
    (ngModelChange)="mark_as_never_been_null(field); "
    (click)="set_date_if_null(input)"
    (ionCancel)="revert_date_on_cancel(input)"
>
```
in `component.ts`
```
time_was_null = new Set();

set_date_if_null(field) {
    if (field.starttime === null) {
        this.time_was_null.add(field.id);
        const now = new Date();
        field.starttime = now.toISOString();
    }
}

revert_date_on_cancel(field) {
    if (this.time_was_null.has(field.id)) {
            this.time_was_null.delete(field.id);
            field.starttime = null;
    }
}

mark_as_never_been_null(field) {
    this.time_was_null.delete(field.id);
}
```

In this workaround, the datetimefield needs to be an attribute of an other object that some form of unique identification
