### ISSUE TITLE
bug: ion-chip descender clipping

### ISSUE THREAD

**Issue by andy-rash-brandt** [ionic-team/ionic-framework#18313]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

[Descenders](https://en.wikipedia.org/wiki/Descender) get cut off when inside an ion-chip.

**Expected behavior:**

The ion-chip should wholly contain the text inside, descenders and all.

**Steps to reproduce:**

Create an ion-list composed of ion-items. Inside each ion-item, place an ion-chip with an ion-label with text containing descenders (e.g. 'Service Agreement', 'Inside Support').

**Related code:**

See the sample project hosted [here](https://github.com/andy-rash/IonChipExample).

**Other information:**

See screenshots hosted on imgur [here](https://imgur.com/a/FIuEHJH).

**Ionic info:**

```
user@users-Mac-mini:ProposalTrackerMockup master ✗ 3h46m ▲ △ ◒ ➜ ionic info

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/Users/user/.nvm/versions/node/v11.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/user/Documents/SDKs/Android)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v11.15.0 (/Users/user/.nvm/versions/node/v11.15.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! We will look into this. Looks like this is related to https://github.com/ionic-team/ionic/issues/16422.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26729, and a fix will be available in an upcoming release of Ionic Framework.
