### ISSUE TITLE
bug: Cannot CSS on conditional readonly ion-input

### ISSUE THREAD

**Issue by ix-xerri** [ionic-team/ionic-framework#18334]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

 Cannot CSS on conditional readonly ion-input
**Expected behavior:**

 Have a proper css selector

**Steps to reproduce:**

I have a conditional readonly selector with the following code:
`<ion-input formControlName="testNumber" type="number" placeholder="Test reference number" readonly="{{ isEdit }}"></ion-input>`

However the css selector has to be ion-input:[ng-reflect-readonly="true"] not ion-input:[readonly="true"]

**Other information:**

**Ionic info:**

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v10.15.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! I was able to reproduce this issue. As an alternative, you can do:

```
<ion-input formControlName="testNumber" type="number" placeholder="Test reference number" [attr.readonly]="isEdit"></ion-input>
```

and then target the `ion-input` using `ion-input[readonly="true"]`.

Thanks!

**Comment by liamdebeasi** [comment]
Thanks for the report. I took a closer look, and this does not appear to be a bug in Ionic. This appears to be how Angular is designed to work. I recommend using `attr.readonly` instead as I noted in https://github.com/ionic-team/ionic-framework/issues/18334#issuecomment-494827676. I am going to close this, but let me know if you have questions.
