### ISSUE TITLE
bug: some elements like ion-header won't work with elm-lang

### ISSUE THREAD

**Issue by ciekawy** [ionic-team/ionic-framework#18444]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Trying to use ionic with elm-lang may lead to `"Cannot read property 'childNodes' of undefined"` for some elements like `ion-header` due to the fact that underlying VDOM changes which makes elm-lang unable to track the reference.

**Expected behavior:**

predictable error-less behaviour for all `ion` elements

**Steps to reproduce:**

try to use `ion-header` in elm app.

**Related code:**

A sample application via GitHub: https://github.com/ciekawy/diegy

it's enough to use `Ion.header` around this place and run the app to see the error. `https://github.com/ciekawy/diegy/blob/master/src/Main.elm#L192`

**Other information:**

while there is definitely some conflict in the approach, it would be great to figure out a solution together with elm-lang community.

Corresponding report on the elm-lang side can be found here https://discourse.elm-lang.org/t/web-components-interop-childnode-issues/3730

**Ionic info:**

```
$ ionic info

Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/Users/szymon/.nvm/versions/node/v10.13.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, browser 5.0.4, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 17 other plugins)

System:

   ios-deploy : 2.0.0
   ios-sim    : 8.0.1
   NodeJS     : v10.13.0 (/Users/szymon/.nvm/versions/node/v10.13.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001
```

**Comment by clojj** [comment]
https://github.com/ionic-team/ionic/blob/master/core/src/components/header/header.tsx

I guess it's because `ion-header` uses `hostData()` and thereby interferes with the DOM that Elm needs to have full control over.. ?

**Comment by ciekawy** [comment]
That seems exactly to be an issue. As that was just a research on my side to combine ionic with elm I may not be able to work on a PR in the near future. At least it it defined well enough so hopefully someone may get interested soon to unlock another awesome language to be used with ionic ;)

**Comment by LKlemens** [comment]
Hi, 
I would like to start elm app on ionic framework. 
Is there any workaround for this issue now?
