### ISSUE TITLE
bug: Wrong positioning in Web/Android ion-fab horizonal="start/end"

### ISSUE THREAD

**Issue by theunreal** [ionic-team/ionic-framework#18552]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
I have ion-fab with horizonal="start".
In WEB - it appearsin the start of my app (RTL).
In Android - its appearsin the end of my app.

Same for <ion-fab-list slot="start/end">. it appears in different position in Web and Android.

**Expected behavior:**
slot="start" and slot="end" should be in the same place wether the platform is web or android.

**Steps to reproduce:**
This will open in different positions in web and android:
<ion-fab-list side="end">
 <ion-fab-button>B1</ion-fab-button>
</ion-fab-list>

**Ionic info:**

```
Ionic 4
Capacitor 1.0
cordova android 7.1.4
cordova CLI 9/.0/0
Ionic CLI 5.0.0
Ionic 4.4.2
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
