### ISSUE TITLE
bug: ionic-virtual-scroll does not update its content

### ISSUE THREAD

**Issue by carlosnewmusic** [ionic-team/ionic-framework#18557]
# Bug Report

**Ionic version:**
[x] **4.5~4.6**

**Current behavior:**
![image](https://user-images.githubusercontent.com/19379457/59600434-71197780-9101-11e9-8f0e-bb4bb1e27d00.png)
![image](https://user-images.githubusercontent.com/19379457/59599024-d5d2d300-90fd-11e9-9289-c1302aa75317.png)

**Expected behavior:**
when there is no data the ionic-virtual-scroll should be updated, disappearing, not leaving the last used ionic-virtual-scroll 
![image](https://user-images.githubusercontent.com/19379457/59600526-aaea7e00-9101-11e9-984b-a580a52aeb3c.png)
![image](https://user-images.githubusercontent.com/19379457/59599937-14698d00-9100-11e9-9bc0-14e044923e31.png)

**Other information:**
reference to closed but not fixed errors
[#15194](https://github.com/ionic-team/ionic/issues/15194)
[#14696](https://github.com/ionic-team/ionic/issues/14696)

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.0.2 (C:\Users\Administrador\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 0.2.5

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue! Can you provide a repository with the code required to reproduce this issue?

Thanks!

**Comment by lincolnthree** [comment]
Hey @carlosnewmusic ,

Not sure you have this as an option, but consider using a 3rd party virtual-scroller component? The ionic component has been plagued with bugs for years:

https://github.com/rintoj/ngx-virtual-scroller

I use this one and it solves a number of problems including not being able to style scrollbars in Ionic 4.

**Comment by carlosnewmusic** [comment]
> Thanks for the issue! Can you provide a repository with the code required to reproduce this issue?
> 
> Thanks!

https://pastebin.com/Y8CYNjMc

**Comment by liamdebeasi** [comment]
@carlosnewmusic,

How are you updating the virtual scroll content? Can you provide your TypeScript code?

**Comment by carlosnewmusic** [comment]
with a variable array called "dato" that is as observable, part of the code in your mail

**Comment by elvisgraho** [comment]
Fix: https://github.com/ionic-team/ionic/issues/19381#issuecomment-638066352
