### ISSUE TITLE
bug: fast navigation between main and tabs outlet breaks tabs outlet

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic-framework#18618]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When navigating to a page via the root outlet and then going back rather quick any page that will be navigated to via the router-outlet of ion-tabs will break (angular template expressions, structural directives, etc. are not evaluated).
When repeating the process nice and slow everything works as expected.

**Expected behavior:**

Fast navigation should not bring the ion-router-outlet in a race condition.

**Steps to reproduce:**

- clone sample application, `npm i`, `ionic serve`

In the sample application:

1. Keep "Simulate fast navigation" enabled
2. Click "Navigate via root outlet"
3. Back navigation is triggered
4. Click "Navigate via tab outlet"
5. Page is empty, but three cards should be rendered (`*ngFor` structural directive not evaluated)
6. Disable "Simulate fast navigation"
7. Click "Navigate via root outlet"
8. Click "Back"
9. Click "Navigate via tab outlet"
10. Page is rendered as intended

**Related code:**

[A sample application via GitHub](https://github.com/DavidStrausz/ionic-nav-bug)

**Other information:**

- It does not matter if you run the sample app in the browser or on the device. 
- Note that components without any binding, template expressions, structural directives are rendered just fine
- The simulate fast navigation option is just a helper for testing, the problem also occurs if the back navigation is not triggered in the code (e.g. navigate and directly swipe back, hit a button in the toolbar twice accedentially).

- Maybe related: #17825 

![example-gif](https://user-images.githubusercontent.com/7592254/60110647-b9bdda00-976c-11e9-9a82-94bc76ae44ea.gif)

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\<User>\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Users\<User>\AppData\Local\Android\sdk)
   NodeJS            : v12.3.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue was resolved during Ionic v4/v5, but the issue was never closed out. Updating to the latest version of Ionic v5 causes this issue to no longer reproduce, so I am going to close this thread out.

If you encounter any additional problems, please open a new issue and include a code reproduction. Thank you!
