### ISSUE TITLE
bug: www folder is missing with ionic react app using cordova plugin 

### ISSUE THREAD

**Issue by sandsuma** [ionic-team/ionic-framework#18623]
**Ionic version:**
ionic 4.0

**Current behavior:**

I am trying to create a ionic react app, using my custom cordova plugin.
I use https://ionicframework.com/blog/ionic-cli-v5-brings-react-beta-support/ to create the app. After adding cordova plugin and running ionic build/cordova prepare for ios the www folder is empty.
compared to ionic react app, if i create app for target angular it fills www folder correctly.

**Expected behavior:**
ionic build/cordova prepare should add desired file including index.html to www folder which is not happening fo rreact-ionic app.

**Steps to reproduce:**
```ionic start myApp --type=react```
```ionic cordova plugin list``` 
```ionic cordova plugin add cordova-plugin-custom ``` => add cordova dependencies
```ionic cordova platform ios ``` => add www folder but empty
```ionic cordova build ios```
```ionic cordova prepare ios``` => www folder is still empty
```ionic cordova run ios```  => throws an error saying www/index.html not found.

**Other information:**
If I execute same steps as above except first line as ```ionic start myApp --type=angular```, it shows www folder correctly including index.html  and works fine.

Ionic:

   Ionic CLI       : 5.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 0.0.5

Cordova:

   Cordova CLI       : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 4 other plugins)

Utility:

   cordova-res : 0.5.1
   native-run  : 0.2.7

System:

   NodeJS : v8.10.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.2.1 Build version 10E1001

**Comment by SalathielGenese** [comment]
Not sure I got here (I mean this page) b/c I had the same issue -10mins. ago.

I fixed it by changing `webDir` in **./capacitor.config.json** from `"www"` to `"build"` (to match react build folder)

**Comment by SalathielGenese** [comment]
I was following these steps -
https://capacitor.ionicframework.com/docs/guides/ionic-framework-app

**Comment by sandsuma** [comment]
@SalathielGenese I am not using capacitor, instead using cordova plugins.

**Comment by stubclan** [comment]
@sandsuma Was this ever solved? I'm running into same issue while trying to add platform in capacitor. Since its a react app, there's no www folder. I tried changing webDir to src but src folder only has index.tsx which throws another error. 

Any help is appreciated. THank you!

**Comment by kensodemann** [comment]
@stubclan - React builds to a `build` directory, not a `www` directory, use set `webDir` to that in your `capacitor.config.json` like this:

```
{
  "appId": "com.kensodemann.myweather",
  "appName": "my-weather-app",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "build",
  "cordova": {}
}
```

**Comment by kensodemann** [comment]
@sandsuma - `@ionic/react` only supports Capacitor out of the box. You could probably get it to work with Cordova, but it wasn't really designed that way.

OTOH, Capacitor _does_ support most plugins. Check here to see if the plugins you want to use are listed as incompatible:
https://capacitor.ionicframework.com/docs/cordova/known-incompatible-plugins

In some cases, they may just be superseded by Capacitor APIs, in which case, use the Capacitor APIs rather than the Cordova plugins. In most cases, though, you can use the plugins.

If you really really really want to try to get Cordova to work, React builds to the `build` directory, and not the `www` directory, so you will probably have to set the content option in the `config.xml`: https://cordova.apache.org/docs/en/latest/config_ref/#content

There is probably a bunch of other stuff you need to do though as well.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a reply. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
