### ISSUE TITLE
history.push causes fresh page load when navigating - Ionic v4 react js/capacitor 

### ISSUE THREAD

**Issue by TravelPaddy** [ionic-team/ionic-framework#18627]
**Ionic version:**
Ionic v4 using react js and capacitor

**The Issue**
I want to make a very short and simple front-end only demo app so i thought i'd give the ionic react a try. I'm more comfortable with react js than angular.

I have a completely new Ionic react app with the sidemenu integrated. The issue i'm having is that the router reloads the page when navigating and i haven't started coding yet

I'm using google chrome responsive mobile view to view my app. I didn't think ionic serve would run here.

**Steps To Reproduce**
npm install ionic -g cordova
ionic start myApp --type=react
npm install --save @capacitor/core @capacitor/cli
npx cap init
npx cap add android // when trying to run this i had to manually create a "www" folder and
                                     it failed again, then i had to create an index.html folder
npm run start

**My Code**
```
      <IonList>
        {appPages.map((appPage, index) => {
          return (
            <IonMenuToggle key={index}>
              <IonItem routerDirection="root" onClick={(e) => {
                  e.preventDefault(); //i included this line to try and salvage the situation
                  history.push(appPage.url)
                }
              }>
                <IonIcon slot="start" name={appPage.icon} />
                <IonLabel>{appPage.title}</IonLabel>
              </IonItem>
            </IonMenuToggle>
          );
        })}
      </IonList>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Does this issue still happen with the latest version of Ionic React?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a reply. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
