### ISSUE TITLE
bug: ion-slide loop doesn't work to the right

### ISSUE THREAD

**Issue by ilprima** [ionic-team/ionic-framework#18657]
# Bug Report

**Ionic version:**

[x] **4.6**

**Current behavior:**

The loop works to the left but not to the right, it adds 2 slides to the right after the last one and stop to scroll.

**Steps to reproduce:**

Put loop:true in the options of the ion-slides

**Related code:**

```
<ion-slides  [options]="slideOpts3">
                <ion-slide class="loadingSlide">
                    <i class="fas fa-spinner fa-spin"></i>
                </ion-slide>
                <ion-slide class="loadingSlide">
                    <i class="fas fa-spinner fa-spin"></i>
                </ion-slide>
</ion-slides>
```
with
```
    slideOpts3 = {
        slidesPerView: 2.8,
        loop: true
    };
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
