### ISSUE TITLE
bug: IonLoading error when isOpen prop is true to early

### ISSUE THREAD

**Issue by topcatcreatives** [ionic-team/ionic-framework#18674]
# Bug Report

**Ionic version:**
@ionic/react@0.0.6-3

**Current behavior:**
Awesome to be using the new Ionic React. 

I was hoping to use IonLoading in a component where I make an action call via Redux to an API http request in the componentDidMount() hook. The IonLoading simply responds to isLoading prop coming back from the subscribed Redux store in the component.

I am specifying IonLoading as follows in my component
<IonLoading
    	isOpen={ this.props.isLoading }
    	message={ 'Loading' }
    	onDidDismiss={ () => console.log('dismiss') }
/>

I am getting the following error on console:
chunk-3db74fda.js:63 Uncaught (in promise) TypeError: element.componentOnReady is not a function
Somewhere in the ionic core it leads to this line
getAppRoot(doc).appendChild(element);
  return element.componentOnReady();
}

If I wrap the action call in a timeout to say 3 seconds things work.

Also, if I don't specify the onDidDismiss prop I get the following error too:
index.js:102 Uncaught TypeError: Cannot read property 'call' of undefined

Also after trying to fix the above with a setTimeout, every now and then the IonLoading doesnt dismiss when the prop being passed to isOpen switches back to false.

**Expected behavior:**
I was hoping isOpen would respond to a boolean prop, and hide/show the IonLoading UI component.

If this is not how the component is meant to be used i.e a duration is required etc, then it would be good if it could be adapted to this situation. Or I could be missing something here, if so, apologies for raising the issue.

**Steps to reproduce:**
Use IonLoading in a component where isOpen is initially set to true, or set to true in componentDidMount.

**Comment by jesobreira** [comment]
Might this and #19064 be related?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a reply. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
