### ISSUE TITLE
bug: [LoadingController] - Loading modal doesn't hide if dismiss is called when page is in the background

### ISSUE THREAD

**Issue by eduardoRoth** [ionic-team/ionic-framework#18678]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
If you create and present a loading controller modal, it'll show without problem, but if you dismiss it when the tab or page is in the background (for example, looking at other tab in Chrome), the dismiss function won't work.

**Expected behavior:**
dismiss function should hide the loading modal all the times.

**Steps to reproduce:**
1.  Create a loading controller modal
2. Present it
3. Set to hide after a couple of seconds (or with another function), needs to be automatically.
4. Quickly, change browser or tab so the ionic app became an inactive one.
5. Return after your dismiss conditions have been met
6. Check that the loading modal is still there

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.1 (/Users/eduardoroth/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.800.4
   @angular-devkit/schematics    : 8.0.4
   @angular/cli                  : 8.0.4
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : 0.5.1 
   native-run  : 0.2.7 

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.9.2
   OS     : macOS Mojave
```

**Comment by joelmeaders** [comment]
I'm having a similar issue, but when dismiss is called before the page is rendered because the HTTP calls finish too fast. Most prominent in test environments and low usage periods.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
