### ISSUE TITLE
feat: fallback route for ion-router

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-framework#18687]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Following up on #17423, we'd like the option to set a fallback/default route in case none of the routes is matching, e. g. to implement a "404 - Not Found" handling. The original request was closed but the provided "solution" is useless when not using Angular (e. g. in a Stencil app).

**Describe Preferred Solution**

On the Stencil website (which is using `stencil-router`) the solution is to [have a route without a `url`](https://github.com/ionic-team/stencil-site/blob/1c09451575929c579f7500a0f1967811a8bc664a/src/components/app-root/app-root.tsx#L106) (which I tried with an `ion-route` but didn't work, and neither did an `ion-route` with `url="*"`).

```tsx
<ion-router >
  <ion-route url="/foo" component="page-foo" />
  <ion-route url="/bar" component="page-bar" />
  <ion-route component="page-404" />
</ion-router>
```

**Describe Alternatives**

Could add a property to `ion-router` that allows to set a component to render if no route was matched, e. g.

```tsx
<ion-router noMatch="page-404">
  <ion-route url="/foo" component="page-foo" />
  <ion-route url="/bar" component="page-bar" />
</ion-router>
```

Possible names for that prop I can think of: `noMatch`, `default`, `fallback`.

Alternatively, there could be an `ion-fallback-route` component?

And yet another alternative: emit an event `ionRouteNoMatch` or similar (already suggested in the original issue), so we can at least handle this in some way.

**Additional Context**

The approach of having a route without `url` is also what React Router does (https://reacttraining.com/react-router/web/example/no-match), and I think it's the most intuitive.

Are you open to a PR for this?

**Comment by corysmc** [comment]
+1
Response from @paulstelzer in the original post
>>>Thanks for the issue! This is not needed to be add to Ionic because you can do this with Angular Routing. Just add a wildcard and set it to your 404 page component.

Ionic can be used in vanilla js so relying solely on angular router isn’t a long term solution

**Comment by paulstelzer** [comment]
@corysmc good point, you are right

**Comment by PurpleEdge2214** [comment]
Also waiting for 404 redirect option.

In addition to this, using the default pwa ionic stencil app, the router matches...

`http://localhost:3333/profile/somename/anything`

...I don't think it should? The route specifies...

`<ion-route url="/profile/:name" component="app-profile" />`

...there is no second property.

**Comment by cpro90** [comment]
Hi,

we just went away from Angular using StencilJS and native JS alongside with Ionic. I see this routing feature does not exist so far. We also facing problems with stencil router; so it would be nice using ion-route with a fallback feature.

Will there be a solution in the nearer future?

**Comment by codyburleson** [comment]
I also need this badly. I've been building a solution with Ionic and Stencil only (no additional framework like Angular) and this is currently my only show-stopper for go-live. This issue has been open for 157 days and it's not even assigned to anyone. For those seeking a pure platform-standard web components approach, this leaves a significant gap. Can you please reconsider the importance of this issue?

**Comment by fmflame** [comment]
I used the ion-route-redirect and route comparisons to workaround this issue if this can help you out.

**Comment by simonhaenisch** [comment]
@fmflame do you mean you're repeating all your routes like

```html
<ion-router>
  <ion-route url="/one" component="page-one" />
  <ion-route url="/two" component="page-two" />
  <ion-route url="/three" component="page-three" />
  <ion-route url="/404" component="page-404" />

  <ion-route-redirect from="/one" to="/one" />
  <ion-route-redirect from="/two" to="/two" />
  <ion-route-redirect from="/three" to="/three" />
  <ion-route-redirect from="*" to="/404" />
</ion-router>
```

This is quite unfeasible for us though.

**Comment by simonhaenisch** [comment]
For some reason I didn't think of this yesterday, but it's quite easy to avoid all this repetition:

```tsx
import { FunctionalComponent } from '@stencil/core';
import { JSX } from '@ionic/core';

export const Route: FunctionalComponent<JSX.IonRoute> = props => [
  <ion-route {...props} />,
  <ion-route-redirect from={props.url} to={props.url} />,
];
```

```tsx
import { Route } from './route';

<ion-router>
  <Route url="/one" component="page-one" />
  <Route url="/two" component="page-two" />
  <Route url="/three" component="page-three" />

  <ion-route-redirect from="*" to="/404" />
</ion-router>
```

That seems like a feasible work-around, might actually try it out at some point.

**Comment by badpenguin** [comment]
The funny thing is that stencil-router support fallback by just removing the url parameter.
In Ionic + Stencil i succeeded for the moment using:
```
<ion-route url=":any" component="app-404"/>
```

**Comment by codyburleson** [comment]
> The funny thing is that stencil-router support fallback by just removing the url parameter.
> In Ionic + Stencil i succeeded for the moment using:
> 
> ```
> <ion-route url=":any" component="app-404"/>
> ```

Awesome! I tested this and it works for me too. In my opinion, in fact, this is perfectly sufficient. I'm not sure why the issue couldn't be closed with this being documented as the way to do it.

**Comment by vicb** [comment]
This feature is still not implemented in v5.

I would love to have it - I can help implementing it if we can agree on a design.

(Or if `url=":any"` should be the way to go I can contribute some docs).

**Comment by simonhaenisch** [comment]
We have something like this now which works very well for us:

```tsx
<ion-router>
  <ion-route url="/" component="page-login" />

  // ... all the page routes and redirects

  <ion-route url=":pathname" component="page-404" />
</ion-router>
```

---

Re your points:

> 2\. `url=":any"` does not catch the root path

I don't really get why you'd want to catch the root path... like why would you ever want the root path to show a 404 page? IMO the root path should be the entry point into your app and if it doesn't have a route then it should redirect to a route (i. e. `<ion-route-redirect from="/" to="/my-entry-route" />`). I don't think I've ever seen a website that shows a 404 when you open it.

> 1. you have to specify a component. My use case is to do a redirect in `beforeEnter`

So maybe you're trying to redirect `/` to your app using `beforeEnter`? Why not use `<ion-route-redirect>`? The `to` can be dynamic, e. g. `<ion-route-redirect from="/" to={user ? '/home' : '/login'} />`, and you can also add `<ion-route-redirect>` components into the DOM dynamically, if you want to add more redirect rules.

`ion-router` is a component-based router, i. e. the API requires you to add elements into the DOM. Maybe what you're looking for is [https://github.com/ionic-team/stencil-router-v2](stencil-router-v2) which is a functional approach to routing that doesn't require any DOM elements (all the provided components are functional).

---

Closing this now because I'd say this is working well enough. But yeah docs for it could probably be improved.

**Comment by brendensoares** [comment]
This shouldn't be closed without a resolution. It seems the consensus is that the `:any` option works and just needs some docs. Can we keep this open until the docs are merged into the appropriate repo?

**Comment by simonhaenisch** [comment]
@brendensoares there is a resolution to the issue at hand. Docs are a separate concern, so feel free to open an issue in the [ionic-docs](https://github.com/ionic-team/ionic-docs) repo.

**Comment by vicb** [comment]
Thanks for you answer @simonhaenisch 

> like why would you ever want the root path to show a 404 page?

You probably have been confused by the `<ion-route component="app-404"/>` that I copy pasted from a previous message in this thread. 

My message is more about the issue in general "fallback route for ion-router". What I do want to do is a redirect.

> `<ion-route-redirect from="/" to={user ? '/home' : '/login'} />`

This doesn't work for me because such a redirect would not trigger the `beforeEnter` hooks of the target hook. 
I would say it's probably a bug in the router.

(It might be related to #22936).

> Closing this now because I'd say this is working well enough. But yeah docs for it could probably be improved.

I would have closed this issue:

First because this should probably be documented inline in the component which is in this repo.

And second I think it's worth discussing if `url=":any"` should be the default. As of today and especially with the lack of documentation, I wouldn't be surprised that most usage of the router fail when an unknown route is passed to an ionic application.
