### ISSUE TITLE
bug: Vuex not working with ion-modal

### ISSUE THREAD

**Issue by Livijn** [ionic-team/ionic-framework#18727]
When using `this.$ionic.modalController` to launch a modal, the component's `this.$store` isn't set.

Here is the error thrown by `this.$store.state`:

> TypeError: Cannot read property 'state' of undefined

**Comment by Livijn** [comment]
Right now a workaround is doing this:

When launching the modal:

    this.$ionic.modalController
          .create({
            component: BrowseFilter,
            componentProps: {
              store: this.$store,
            }
          })

In the Modal component:

    props: {
      store: Object,
    },
    created() {
      if (this.store) {
        this.$store = this.store;
      }
    },

**Comment by sotisoti** [comment]
Same goes to vue-i18n, eg: `this.$t('message.hello', { msg: 'hello' })` cannot be used in a modal:

`"TypeError: Cannot read property '_t' of undefined"`

**Comment by Livijn** [comment]
I think it applies to basically all libs. I solved by importing those in the modal component.

    
    import store from '../store';
    import router from '../router';
    export default {
        store,
        router,
        // ...
    }
