### ISSUE TITLE
bug: IonRouterOutlet not keeping track of reused page url after navigateBack

### ISSUE THREAD

**Issue by plchampigny** [ionic-team/ionic-framework#18747]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
When using a custom reuse strategy on a page, navigating in the same component (with url changes) then navigating forward another page then backward to the same page causes a reload of the 1st page. Here's an example of the routes:

1. /view/2019-01-02 (ViewPage)
2. /view/2019-01-03 (ViewPage (reused and updates handled in component))
3. /edit/123 (nav forward to EditPage)
4. /view/2019-01-03 (nav backward to ViewPage)

Since StackController haven't been notified that the url has changed for that view, ionic router outlet thinks it must create the new view.
(see https://github.com/ionic-team/ionic/blob/f060db5fe6971381c4460ec7ff66f9db0e7bedae/angular/src/directives/navigation/stack-controller.ts#L47)

**Expected behavior:**
When a page is reused and it's url changes, stackcontroller should update it's url value

**Steps to reproduce:**

1. Create 2 pages (View and Edit)
2. Handle ViewPage routing manually by overriding ionicreusestrategy and make sure that view handles its own routing
3. Do the previously described steps
4. The view should be recreated after navigate back

**Related code:**

I fixed it on my side using a hack in my page:

```
this.route.paramMap.subscribe((params) => {
      const ctrl = (this.routerOutlet as any).stackCtrl;
      if (ctrl) {
        const existing = ctrl.views.find(vw => vw.url.startsWith(`/view/${oldDate}`));
        if (existing) {
          existing.url = this.router.url;
        }
      }
});

```

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Cactus\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.1
   @angular-devkit/build-angular : 0.800.6
   @angular-devkit/schematics    : 8.1.0
   @angular/cli                  : 8.1.0
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.5, (and 17 other plugins)

System:

   NodeJS : v12.6.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
