### ISSUE TITLE
bug: passed NavParams override Component properties

### ISSUE THREAD

**Issue by acran** [ionic-team/ionic-framework#18765]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When passing params to `IonNav.push()` the values of the passed params are merged with the properties of the component, silently overriding any existing property values - even private ones.

**Expected behavior:**
Navigating to a component with `IonNav.push()` should not mess with the component properties but additional data should be passed as `NavParams` only.

**Steps to reproduce:**
Navigate to a component with `IonNav-push()` passing additional params, e.g. 
```typescript
this.nav.push(NavComponent, {privateParam: 'overriden value from NavParams'});
```
Check the value of the component property in the constructor and on `ngOnInit` of the component to see that they're different when they shouldn't be:
```typescript
constructor() {
  console.log(this.privateParam); // "initial value from class"
}

ngOnInit() {
  console.log(this.privateParam); // "overriden value from NavParams"
}
```

**Related code:**
This is a minimal example code to reproduce the problem:
```typescript
@Component({
  selector: 'app-root',
  template: '<ion-app><ion-nav></ion-nav></ion-app>'
})
export class AppComponent implements OnInit {
  @ViewChild(IonNav) nav: IonNav;

  ngOnInit() {
    this.nav.push(NavComponent, {privateParam: 'overriden value from NavParams'});
  }
}

@Component({
  template: 'Value of privateParam is {{ privateParam | json }}'
})
export class NavComponent implements OnInit {
  private privateParam = 'initial value from class';

  constructor() {
    console.log(this.privateParam); // "initial value from class"
  }

  ngOnInit() {
    console.log(this.privateParam); // "overriden value from NavParams"
  }
}
```
You can clone and run the [full example](https://github.com/acran/ionic-NavParams-override-example) with:
```bash
git clone https://github.com/acran/ionic-NavParams-override-example.git
cd ionic-NavParams-override-example/
npm install
npx ionic serve
```

**Other information:**
Replacing the private property with getters and setters I was able to track down the cause for this behavior to this line of code: 
https://github.com/ionic-team/ionic/blob/f1eeed1c915f6b27022352aa03b0879fe158e4e9/angular/src/providers/angular-delegate.ts#L88-L90

I'm not completely sure if this behavior is intended. Coming from Ionic v3 this is for sure unexpected since the [docs for v3](https://ionicframework.com/docs/v3/api/navigation/NavController/#push) do not mention any such behavior.
Unfortunately the [docs for `IonNav` in v4 ](https://ionicframework.com/docs/api/nav) are very sparse and do not provide much information or examples on how to correctly use it. So if this _is_ intended behavior it needs to be documented more detailed.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.2 (/usr/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v8.15.1 (/usr/bin/node)
   npm    : 6.4.1
   OS     : Linux 5.1
```

**Comment by JeramieHallyburton** [comment]
I agree with need for documentation if that is the case but I use this mechanism heavily throughout our codebase and would want the behaviour preserved. 

It's useful for shared components that are created by modals as well as placed directly in templates.

I can create properties that are decorated with @Input() and receive values from the parent template and also have those properties populated from the additional data object passed into ModalController create() without the need for additional code that checks the NavParams.

**Comment by evgeniyefimov** [comment]
This behavior is really unexpected and I don't want that something mutates my components implicitly. We retrieve NavParams explicitly in facade services and we've already had few issues with this, when NavParams unexpectedly override some our properties in components which may be passed changed from facade.

**Comment by sean-perkins** [comment]
I don't believe this is an issue with Ionic specifically. Ionic is assigning the object values you pass to component props, to the component class instance. 

Typescript's `private` modifier is just syntax sugar that is removed when transpiled to JavaScript. When Ionic is assigning these values, there is no way to infer if they are private members of your class.

I would offer two recommendations here:
1. You are in control of what component properties you are passing through. Don't pass properties that you know to be private in your application. Only pass controlled values.
2. Make use of private class members with the JavaScript syntax.

```ts
class MyComponent {
  #somePrivateVariable = 'initial value';
}
```

With this syntax, when you try to explicitly state that key when constructing component props, TypeScript will warn you that you are not allowed to do this.

Also when trying to force the value to be assigned by doing something similar to:
```
componentProps = {
 ['#somePrivateVariable']: 'updated value'
}
```

Attempting to assign to that property will be ignored/not applied when we write the component properties.
