### ISSUE TITLE
bug: ion-select with floating label pushed to bottom of ion-item, unlike ion-input and ion-datetime

### ISSUE THREAD

**Issue by RobbHerman** [ionic-team/ionic-framework#18779]
# Bug Report

**Ionic version:**

[x] **4.6.2**

**Current behavior:**
When building a form with ion-select, the select box is pushed to the bottom of the ion-item when using a floating label.

![localhost_8100_profile-add(Pixel 2 XL)](https://user-images.githubusercontent.com/44446950/61140192-998e5a80-a490-11e9-9051-d10455bc1441.png)

**Expected behavior:**
The selection box should be centered vertically similar to ion-input and ion-datetime

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I was able to reproduce this on latest: https://codepen.io/brandyscarney/pen/zYxRVyj?editors=1100
