### ISSUE TITLE
Ionic 4 lab uses incorrect platform

### ISSUE THREAD

**Issue by mebibou** [ionic-team/ionic-framework#18785]
**Description:**
When using the "device" view in Chrome, and selecting an iPhone device for example, the result of `platform.platforms()` will give:
```
["iphone", "ios", "mobile", "mobileweb"]
```
And equivalent when selecting an Android device.

But when using `ionic serve --lab`, the platform list is always `["desktop"]` for whichever device you select.

**Steps to Reproduce:**
Use something like this in a page:
```html
<ion-header>
  <ion-toolbar>
    <ion-title>Page</ion-title>
    <ion-buttons *ngIf="platform.is('ios')" slot="end">
      <ion-button>Add</ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```
where `platform` comes from `constructor(platform: Platform)` in the controller. If you open `ionic serve --lab`, the button in the iOS device will not appear

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 5.2.2 (/.nvm/versions/node/v10.1.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.5 (update available: 0.2.7)

System:

   NodeJS : v10.1.0 (./.nvm/versions/node/v10.1.0/bin/node)
   npm    : 6.10.0
   OS     : macOS Mojave
```

**Other Information:**

I am using `"@ionic/lab": "2.0.6"`

**Comment by dwieeb** [comment]
@brandyscarney Can we mock the return value of`.platforms()` via a query parameter config option?

`?ionic:mode=ios&ionic:platforms=iphone,ios,mobile,mobileweb` for example

**Comment by brandyscarney** [comment]
@dwieeb Yes we should be able to, I believe we will have to add the platforms to the config and then check for it.

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently deprecated Ionic Lab in favor of using the mobile device emulation features provided by browser developer tooling. Please see https://ionicframework.com/docs/developing/previewing for instructions on how to get started with this tooling. I am going to close this, but let me know if there are any questions.
