### ISSUE TITLE
feat: Add support for custom animations with React

### ISSUE THREAD

**Issue by jotceg** [ionic-team/ionic-framework#18815]
# Feature Request

**Ionic version:**

[x] **4.6.2**

**Describe the Feature Request**

So I'd like to use some custom animations with IonRouterOutler in React, but it seems like it's not currently possible. I know there are some built in animations in IonRouterOutler already but there's no possibility to replace them with your own.

**Describe Preferred Solution**

It would be nice to have similar API to what Ionic offers for Angular (animated and animation props where we can customize the behavior of animations). It can accept animations from react-spring library for example. Also it would be nice to have the possibility to manipulate them with the state property of React Router's history.push function, for example:

`history.push('/home', {  animation: either some CSS or react-spring animation for example  })`;

An example implementation of that:

*Home.tsx*

`
import React from 'react';
    
import { useSpring } from 'react-spring';

export default function() {
    const swipe = useSpring({
        from: {
            position: 'absolute',
            left: '0px',
            top: '0px'
        },
        to: {
            left: '100%'
        }
    });

    function nav() {
        history.push('/app', { animation: swipe });
    };

    return <IonButton onClick={nav}>Click me</IonButton>
}

// then IonRouterOutlet:

...ionRouterOutlet code
// location prop from react-router
if (location.state.animation) {
    return animation.map(({ item, key, props }) => item && <IonRouterOutlet style={props} key={key}>...</IonRouterOutlet>) // this is like react-spring works
};
`

**Describe Alternatives**

There is also a possibility to just include some default animations in IonReactOutlet but let the user specify which animation to use with props for example, eg.

`<IonRouterOutlet swipe>...</IonRouterOutlet>`;

and also add support for manipulating them via history.push of react router's api. The possible implementation of it is that react router pushes (router.push) with some state (router.push('/someroute', { ...props }) and then IonRouterOutlet takes that and performs given animation
**Related Code**

**Additional Context**
The example implementation is the one I've included above.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework currently has support for custom animations using our Ionic Animations utility. You can use the `animation` property in `IonRouterOutlet` to change the animation per-outlet, or you can use the `routerAnimation` property on components such as `IonButton` to do a per-page animation. Any component that supports `routerLink` also supports `routerAnimation`.

Here is an example:

```jsx
const myAnimation = (baseEl, options) => {  
  // animation logic in here
}

...

<IonButton routerLink="/page" routerAnimation={myAnimation}>Click Me</IonButton>
```

Example with IonRouterOutlet:
```jsx
const myAnimation = (baseEl, options) => {  
  // animation logic in here
}

...

<IonRouterOutlet animation={myAnimation}></IonRouterOutlet>
```

You can also set this in your config to override animations across your entire app: 

```javascript
import { setupConfig } from '@ionic/react';

const myAnimation = (baseEl, options) => {  
  // animation logic in here
}

setupConfig({
  navAnimation: myAnimation
});
```

For examples on how to write animations using Ionic Animations, please see https://ionicframework.com/docs/utilities/animations

Also check out this guide to see how to use animations with other Ionic Framework components: https://ionicframework.com/docs/utilities/animations#overriding-ionic-component-animations

Thanks!
