### ISSUE TITLE
bug: on iOS when input is focused and keyboard opened scroll does not work correctly

### ISSUE THREAD

**Issue by zikosichi** [ionic-team/ionic-framework#18826]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When you focus the input on the DOM and keyboard opens the scroll behaves incorrectly. 
After reaching the bottom of `ion-content` you can still scroll down and the entire document is shifted up. Please see the video for better understanding. 

This happens for both native inputs and ion inputs. 

**Expected behavior:**
The scroll should work when the keyboard is visible.

**Steps to reproduce:**
Add a text input on the DOM -> focus -> When the keyboard opens on iOS try to scroll

**VIDEO** - https://streamable.com/q6tsq

**Other information:**
Only happens on iOS

**Comment by drugoi7** [comment]
Same problem here.
Form is pushed up and hided behind the header.

**Comment by qriandiere** [comment]
Same issue here.
When focusing on an input, content get pushed up and get hidden.

**Comment by Boosten** [comment]
Are you using fullscreen=true on ion-content?

**Comment by qriandiere** [comment]
I get the issue with both fullscreen values.

**Comment by 2manoj1** [comment]
same issue happening in ios 13.7 with ionic/angular 5.3.1. angular 10+, capacitor - 2.4.0. any update how to fix this issue? on Keyboard show its hide the input box (chat message input box) on keypress its positions the input box.

**Comment by liamdebeasi** [comment]
Hi everyone,

Does this issue reproduce on the latest version of Ionic 6? We also have additional input + scrolling improvements coming in Ionic 7. There is a dev build in https://github.com/ionic-team/ionic-framework/issues/18532#issuecomment-1230857454 if anyone is interested in testing that as well.
