### ISSUE TITLE
bug: Prod Build PWA Errors when deployed to subdirectory

### ISSUE THREAD

**Issue by Snickdx** [ionic-team/ionic-framework#18862]
# Bug Report

**Ionic version:**
[x] **4.6.2**

**Current behavior:**
Reloading pages and navigating directly to routes result in 404.  Urls for images and other pages exclude the sub directory (base-href) resulting in 404s.

**Steps to reproduce:**
1. create ionic starter-app
2. add "  <base href="./">" to index.html
3. $ionic build --prod --base-href=./starter"
4. Deploy ionic starter-app to a subdirectory a web server root. 
5. Visit app and reload.
6. Copy and paste any route into a browser tab.
7.Visit server/subdirectory/index.html on browser, View 404's for routes that link to images.

Running application 
[demo](https://nmendez.app/starter)

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.2.2 (C:\Users\snick\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10


```

**Comment by Snickdx** [comment]
Error still persists in v4.11.7

**Comment by hecmtz** [comment]
Is this solved or any solution related to this?

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is related to the server that serves up the web content, not Ionic. We recommend following https://ionicframework.com/docs/angular/pwa for instructions on how to deploy a PWA with Ionic.

For any other issues, please open a new thread. Thank you!
