### ISSUE TITLE
bug: 4.6.x, use dot inside number type ion-input empty this input

### ISSUE THREAD

**Issue by JPegue** [ionic-team/ionic-framework#18864]
# Bug Report

**Ionic version:**

[x] **4.6.x**

**Current behavior:**

When i use dot inside number type ion-input this input is empty. 
ex: I can't enter "32.5" inside ion-input.

**Expected behavior:**

Enter "32.5" without clear input. it works with @ionic/angular 4.5.0

**Steps to reproduce:**

1. create new ionic project
2. add ion-input type number inside home.page.html

https://github.com/JPegue/ion-input-number-example

**Related code:**

```
<ion-input id="real-number" type="number"></ion-input>
```

![c16DsbfXwJ](https://user-images.githubusercontent.com/5878202/61740457-f80be080-ad8e-11e9-850d-c73aba381b26.gif)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\jerom\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

```

**Comment by brandyscarney** [comment]
Thanks for the issue! Is there a specific browser or device this occurs on? I can't reproduce it with the sample project on Chrome or Safari.

**Comment by JPegue** [comment]
I used chrome 75.0.3770.142 on windows and chrome 75.0.3770.143 on android device

**Comment by PowerMogli** [comment]
We have the same problem. Dot clears the input. We are using ionic 4 with Angular 8.

**Comment by StefanoGroenland** [comment]
Same issue with Ionic v4 and Angular 7.2.15

**Comment by BoveFabio** [comment]
We experience the same issue in Safari (Version 13.1.2 (15609.3.5.1.3)) with @ionic/react 5.2.3.

**Comment by brandyscarney** [comment]
I am still unable to reproduce this issue. I've tried using the project attached in the original issue, a new Ionic Angular (v5.3.1) project and a new Ionic React (v5.3.1) project. Tested across multiple browsers including Chrome and Firefox on Windows.

The only way it was reproduced was by double tapping the period on an Android device, but that doesn't appear to happen in the attached gif.

If anyone is still running into this please attach a sample project with exact steps to reproduce, including which browser/device. Thank you!

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
