### ISSUE TITLE
bug: ionTabsWillChange fires after tab has changed.

### ISSUE THREAD

**Issue by masimplo** [ionic-team/ionic-framework#18900]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Calling a function on `ionTabsWillChange` event emission. Adding a breakpoint on that function is hit after the tab is changed. From the code it seams that `ionTabsWillChange` and `ionTabsDidChange` are fired together:

```
  onPageSelected(detail: StackEvent) {
    const stackId = detail.enteringView.stackId;
    if (detail.tabSwitch && stackId !== undefined) {
      if (this.tabBar) {
        this.tabBar.selectedTab = stackId;
      }
      this.ionTabsWillChange.emit({ tab: stackId });
      this.ionTabsDidChange.emit({ tab: stackId });
    }
  }
```

https://github.com/ionic-team/ionic/blob/6929bb817cff5e4ac3eb266e7aca45173c361789/angular/src/directives/navigation/ion-tabs.ts#L64

**Expected behavior:**

`ionTabsWillChange` should fire right before the tab is changed.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by amandaesmith3** [comment]
This has (at last!) been resolved via https://github.com/ionic-team/ionic-framework/pull/24910, and the fix will be available in a future release of Ionic 👍
