### ISSUE TITLE
bug: ERROR Error: Outlet is not activated

### ISSUE THREAD

**Issue by meanstack-perficient** [ionic-team/ionic-framework#18999]
# Bug Report

**Ionic version:**
$ ionic info
       
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (/Users/***/Library/Android/sdk)
   NodeJS            : v10.11.0 (/Users/***/.nvm/versions/node/v10.11.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave

**Current behavior:**
App attempts to boot and quits during boot with exception

```
vendor.js:77185 ERROR Error: Outlet is not activated
    at Object.get [as component] (http://localhost:8100/vendor.js:148394:23)
    at http://localhost:8100/vendor.js:164556:9
    at Array.forEach (<anonymous>)
    at deepFreeze (http://localhost:8100/vendor.js:164553:33)
    at http://localhost:8100/vendor.js:164559:7
    at Array.forEach (<anonymous>)
    at deepFreeze (http://localhost:8100/vendor.js:164553:33)
    at http://localhost:8100/vendor.js:164559:7
    at Array.forEach (<anonymous>)
    at deepFreeze (http://localhost:8100/vendor.js:164553:33)
```

ion-router-outlet isn't offering any advisory action within the runtime

does order matter when loading modules and structuring the router 
if so where is this documented

**Expected behavior:**
App should boot

**Steps to reproduce:**
Our app is large, uses NgRX (which boots fine) and runs fine

we do not have a hello world size `plunker/stackblitz` to show anything

lots of modules are lazy loaded no eager load

main app uses      ` <ion-router-outlet main></ion-router-outlet>`

we have a tabs component and home component 

our APP uses relative nested routes with regard to this

`/tabs/home`

so I am wondering to what extent do relative routes have to play in this since the app attempts to go directly to the relative route on boot but the modules and their respective router-outlets are not instantiated at the time

so we get to the HOME `module/component `thru the TABS `module/component`

nothing worked when they were lazyloaded

both are eager loaded now to try and isolate the race async loading and outlet setup at runtime

HOME component uses   `<router-outlet></router-outlet>`

the app comes up but again an area of code crashed and is inoperable due to this timing race condition of loading and router-outlet setup on app boot

we are willing to try anything to remedy

please advise

**Comment by liamdebeasi** [comment]
Thanks for the issue. Issues with relative routing in Angular were resolved during Ionic v4/v5, but the issue was never closed out. Updating to the latest version of Ionic v5 should fix these issues, so I am going to close this thread out.

If you encounter any additional problems, please open a new issue and include a code reproduction. Thank you!
