### ISSUE TITLE
bug: <ion-select> Angular data binding not working with [value]="null"

### ISSUE THREAD

**Issue by reed-lawrence** [ionic-team/ionic-framework#19013]
package.json versions:
@ionic/angular: 4.7.1
@angular/core: 8.1.2

Exmaple: 
```
    <ion-item *ngFor="let user of sharing.PermissionsList">
      <ion-{{user.Email}}</ion-label>
      <ion-select [(ngModel)]="user.AccessLevel">
        <ion-select-option [value]="null">None
        </ion-select-option>
        <ion-select-option [value]="'r'">Read only</ion-select-option>
        <ion-select-option [value]="'rw'">Read & Write</ion-select-option>
      </ion-select>
    </ion-item>
```

The above code works great for the two values specified as strings. But the null value will not appear selected. 

The data binding does work in applying null to the object parameter, and will reflect it properly when the `<ion-select>` changed the value to null. However, when the value is set in javascript, it does not reflect the proper `<ion-select-option>` that should correspond to the `[value]="null"`. Instead the `<ion-select>` appears blank, with nothing selected upon prompting it.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
