### ISSUE TITLE
bug: Every browser refresh generates a new style SHA value makes supporting CSP impossible

### ISSUE THREAD

**Issue by BorntraegerMarc** [ionic-team/ionic-framework#19029]
# Bug Report

**Ionic version:**

[x] **4.7.1**

**Current behavior:**

Building my webpage normally with `ng build` and have a strict CSP installed. Now every time I refresh the web page there is a different SHA value the browser want's to see added to the CSP policy:
![Screenshot 2019-08-07 at 19 06 33](https://user-images.githubusercontent.com/7549295/62642919-09381e00-b947-11e9-834a-cc8823d8fa98.png)

Here are some values that the browser already requested:
```
'sha256-8czihmr3J9Ewj2VDRiFGlvIZIYG6JvlBKrmH89O9AtE='
'sha256-K1nN0SmcMAe+eiDEcr8ntN53OkzV/GMKThe0LuBI/R8='
```

Could someone shed some light why there is a new SHA value with every page refresh?

**Expected behavior:**

No SHA value for style CSP changes.

**Steps to reproduce:**

Generate new ionic 4 project with stencil.

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 5.2.3 (/Users/borntsch/.nvm/versions/node/v8.13.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-webview 2.4.1, (and 23 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/borntsch/Library/Android/sdk)
   ios-sim           : 7.0.0
   NodeJS            : v8.13.0 (/Users/borntsch/.nvm/versions/node/v8.13.0/bin/node)
   npm               : 6.10.2
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by BorntraegerMarc** [comment]
It is still reproducible in ionic v5.

To reproduce:
- Create new starter project with ionic CLI
- Set the `Content-Security-Policy "default-src 'self'; style-src 'self';"`

Now you will see the error

If you set the it to `Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline';"` then it works.

In my opinion we should be able to build ionic apps without running having security issues. Having an `unsafe-inline` CSP is considered bad practice.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. The styles that are being applied appear to be related to Angular component styles, not Ionic Framework styles. I verified this using a blank Angular application with no Ionic Framework dependency included.

I recommend looking at https://angular.io/guide/security#content-security-policy to see if they have any suggestions for how to use the stricter CSP settings with Angular apps.
