### ISSUE TITLE
Fluent Design Components on Windows

### ISSUE THREAD

**Issue by LasseRosenow** [ionic-team/ionic-framework#19037]
It would be great if ionic components could implement the fluent design system if running on  windows.

This already was an issue years ago : #11620 

Back then it was said fluent design would need to settle a bit.
So a lot of time past since then and the fluent design system and it is quite stable now.

So whats your plan on that?

**Comment by liamdebeasi** [comment]
Nothing to announce yet, but we are investigating. 🙂

**Comment by SeanWong24** [comment]
Is there any updates now?

**Comment by liamdebeasi** [comment]
Hi everyone,

The team has decided not to implement Fluent Design in Ionic. There are two reasons for our decision:

1. We feel there is more value in enabling developers to build themes that match their own custom branding than another external design system. For example, an app like Spotify has its own branding yet still follows base iOS/Android patterns. This is something we are actively investigating for Ionic.
2. This feature would require a big effort to implement, and there is not enough support from the community at the moment.

I am going to close this issue. Thank you!
