### ISSUE TITLE
slides with scrollbar enabled and additional options does not render correctly

### ISSUE THREAD

**Issue by vincekd** [ionic-team/ionic-framework#19034]
# Bug Report

**Ionic version:**
[x] **4.7.1**

**Current behavior:**
If you use the slides component with `scrollbar="true"` and `options="{scrollbar: {...} }"`,  a scrollbar element appears but is non-functional.

**Expected behavior:**
The options should be passed correctly while maintaining default behavior when not overriden.

**Steps to reproduce:**

1. Create a page that uses the slides component that uses a scrollbar: `<ion-slides scrollbar="true" [options]="slidesOptions"> ... </ion-slides>`
2. In page component, set `slidesOptions = { scrollbar: { } }`.
3. Observe that a scrollbar div shows up, but does not function as a scrollbar and does not track the current slide.

**Related code:**

In component:
```
  public sliderOptions = {
    // FIXME: this doesn't show the scroller
    scrollbar: {
      // don't even need to have any options
    },
  };
```

In html:
```
      <ion-slides [options]="sliderOptions" scrollbar="true">
        <ion-slide *ngFor="let slide of slides">
          <ion-card>
            <ion-card-header>
              <ion-card-title>{{ slide.name }}</ion-card-title>
            </ion-card-header>
            <ion-card-content>
              {{ slide.content }}
            </ion-card-content>
          </ion-card>
        </ion-slide>
      </ion-slides>
```

**Other information:**

**Ionic info:**

```
 > ionic info

Ionic:

   Ionic CLI                     : 5.2.3 (/home/vince/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 10 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/home/vince/Android/Sdk/)
   NodeJS            : v11.15.0 (/usr/bin/node)
   npm               : 6.10.2
   OS                : Linux 5.2

```

**Comment by vincekd** [comment]
After playing around, this can be fixed by passing the `el: ".swiper-scrollbar"` option to scrollbar configuration. However, this is still not expected behavior.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
