### ISSUE TITLE
bug: ion-content scrolls when ion-footer expands

### ISSUE THREAD

**Issue by Livijn** [ionic-team/ionic-framework#19067]
# Bug Report

**Ionic version:**
[x] **4.6.2**

**Current behavior:**
When the content of an `ion-footer` expands, the respective `ion-content` scrolls the same amount as the height difference.
https://gyazo.com/2e606a59a774dbd7c2ca4b4af84712ef

> document.querySelector("#main-content > div > div > div > ion-tab > ion-router-outlet > div > ion-footer").offsetHeight
> 55
> document.querySelector("#main-content > div > div > div > ion-tab > ion-router-outlet > div > ion-content").shadowRoot.querySelector("div").scrollTop
> 124
> document.querySelector("#main-content > div > div > div > ion-tab > ion-router-outlet > div > ion-content").shadowRoot.querySelector("div").scrollTop
> 181
> document.querySelector("#main-content > div > div > div > ion-tab > ion-router-outlet > div > ion-footer").offsetHeight
> 97

**Expected behavior:**
The scroll of `ion-content` shouldn't be affected.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
