### ISSUE TITLE
bug: AlertController not allowing multiple input types

### ISSUE THREAD

**Issue by UltimateGemini** [ionic-team/ionic-framework#19089]
# Bug Report

**Ionic version:**
Latest

**Current behavior:**
AlertController is not allowing different types of inputs at the same time. (e.g..text with checkbox)

**Expected behavior:**
To allow checkbox, text, url, date, number input types to be mixed.

**Steps to reproduce:**
Add AlertController to TS file.

**Related code:**
```
const alert = await this.alertController.create({
      header: 'Test',
      message: 'testing',
      inputs: [
        {
          name: 'name1',
          type: 'text',
          placeholder: 'Placeholder 1'
        },
        {
          name: 'checkbox1',
          type: 'checkbox',
          label: 'Checkbox 1',
        }
      ]
```

[StackBlitz Demo](https://stackblitz.com/edit/ionic-v4-angular-blank-template)

**Comment by NiklasMerz** [comment]
This seems a feature request. Per documentation alerts are not designed to allow that:

>Radios, checkboxes and text inputs are all accepted, but they cannot be mixed. For example, an alert could have all radio button inputs, or all checkbox inputs, but the same alert cannot mix radio and checkbox inputs. Do note however, different types of "text" inputs can be mixed, such as url, email, text, textarea etc. If you require a complex form UI which doesn't fit within the guidelines of an alert then we recommend building the form within a modal instead.

https://ionicframework.com/docs/api/alert#inputs

**Comment by UltimateGemini** [comment]
Im pretty sure that wasn't in the docs a year ago when i was working on this. Thanks for the reply.. a year later.

**Comment by NiklasMerz** [comment]
I just came across this issue too right now
