### ISSUE TITLE
bug: ion-infinite-scroll is not working with popover

### ISSUE THREAD

**Issue by iampavanarora** [ionic-team/ionic-framework#19114]
# Bug Report

**Ionic version:**
[x] **4.7.0**

**Current behaviour:**
infinite-scroll is not working in ionic popover it just take an place in elements its proper working in pages and modals but its not working in popover
**Expected behaviour:**
Needs to works in popovers like it works in modals and page

**Steps to reproduce:**
Just simply place ion-infinite-scroll and open popover it black space but yet not working

```
insert short code snippets here
    <ion-list>
            <ion-item *ngFor="let test of testdata"
                (click)="setSelected(test)">
                    {{test.name}}
            </ion-item>
        </ion-list>
        <ion-infinite-scroll threshold="50px" (ionInfinite)="loadMoreData($event)">
            <ion-infinite-scroll-content
            loadingSpinner="crescent"
            loadingText="Plese Wait...">
            </ion-infinite-scroll-content>
        </ion-infinite-scroll>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? I tried using the code you provided, but the infinite scroll component fired as expected.

**Comment by iampavanarora** [comment]
@liamdebeasi  here is the repo url for check this issue
https://github.com/iampavanarora/ionic-4

**Comment by pawan-logiciel** [comment]
@liamdebeasi any update on this?

**Comment by iampavanarora** [comment]
@liamdebeasi  any update on this ?

**Comment by tajinder-logiciel** [comment]
@liamdebeasi any update regarding this,I am also getting this issue

**Comment by sapabg** [comment]
Same here. The event does not get triggered when I reach the bottom.

**Comment by liamdebeasi** [comment]
Apologies for the delay. I was able to reproduce this issue using the repo provided. We will look into a fix for this. Thanks!

**Comment by Yermo** [comment]
FWIW, the same seems to be happening in an ion-modal.

**Comment by PabloHernanVila** [comment]
Is there any workaround for making ion-infinite-scroll work inside a ion-popover?

**Comment by JunaidAlam36** [comment]
still nothing on this?? I am facing same issue... ionInfinite is not event triggered in ion modal at end of the list... using ionic version 5+

**Comment by PabloHernanVila** [comment]
It seems that it's not supported to use ion-infinite inside pop-over or modals.

**Comment by kt-at-cbx** [comment]
Sad. I am also getting this issue.

> 
> 
> It seems that it's not supported to use ion-infinite inside pop-over or modals.

Is there any workaround to achieve infinite scroll in popover or modals?

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am no longer able to reproduce this issue on the latest version of Ionic using the GitHub repo provided in https://github.com/ionic-team/ionic-framework/issues/19114#issuecomment-522848523.

I am going to close this for now. If this is still a bug, please provide a new reproduction that we can use to verify this behavior.
