### ISSUE TITLE
bug:   Infinite scroll does not trigger when using smaller page size

### ISSUE THREAD

**Issue by granthoff1107** [ionic-team/ionic-framework#19142]
I have a component which handles infinite scroll for different Items

    <ion-list>
      <div *ngIf="!config?.isSliding">
        <ng-template *ngFor="let entity of entityList" [ngTemplateOutlet]="template" [ngTemplateOutletContext]="{entity: entity}">
        </ng-template>
      </div>
    </ion-list>
    <ion-refresher (ionRefresh)="refresh($event)">
        <ion-refresher-content pullingIcon="arrow-dropdown" pullingText="Pull to refresh"
                                  refreshingSpinner="circles" refreshingText="Refreshing...">
        </ion-refresher-content>
    </ion-refresher>
    <ion-infinite-scroll threshold="10%" *ngIf="!config?.isReverse && !isPagingComplete" 
      (ionInfinite)="loadData($event)" position="bottom">
        <ion-infinite-scroll-content 
          loadingSpinner="bubbles"
          loadingText="Loading more data">
        </ion-infinite-scroll-content>
    </ion-infinite-scroll>

If I make a request for a page of items that is smaller than the viewport, the Infinite scroll stops working.  In Ionic 3 I solved this issue by checking the height of this list.

    assureInfiniteScrollIsPopulated() {

        if (this.isPagingComplete) {
            return;
        }

        // Do this after the dom is rendered
        setTimeout(() => {
            const scrollContent = this.elementRef.nativeElement.closest('.scroll-content');

            if (!scrollContent) {
                return;
            }

            if (!this.isVScrollable(scrollContent)) {
                this.getNextPage();
            }
        });
    }

    isVScrollable(nativeElement: any) {
        return nativeElement.scrollHeight > nativeElement.clientHeight;
    }

They've removed the scroll-content class and there is nothing really meaningful to filter on.

How can I ensure the list is populated?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
