### ISSUE TITLE
bug: content jumps when starting ion-refresher on iOS

### ISSUE THREAD

**Issue by brenofontes90** [ionic-team/ionic-framework#19163]
**Ionic version:**
[x] **4.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
When starting a pull to refresh on iOS, the content makes a little "jump" before the refresher is activated [See video: https://trello-attachments.s3.amazonaws.com/54308dfb59159a4c354acea4/5d4f7dc1dd180f14d67595e4/0654f0e619cbd093ae6fcf7efe7e706a/video.mov].

**Expected behavior:**
Smooth transition without the jump.

**Steps to reproduce:**
1. Insert an ion-refresher in a page with content in it.
2. Build on iOS Device or Simulator.
3. Start pulling to refresh slowly.
4. See that the content makes a little jump before the refresher appears

**Other information:**
It probably happens because the movement starts as a bounce and only after that becomes a pull-to-refresh.

**Ionic info:** 
```
Ionic:

   Ionic CLI                     : 5.2.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/breno/Library/Android/sdk/)
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by cbleu** [comment]
Yes same comportement here and also reproductible on ios with command:
`ion serve --devapp`

**Comment by eternityBUG** [comment]
I had the same problem

**Comment by liamdebeasi** [comment]
Thanks for the issue. I will look into what may be the cause of this behavior.

**Comment by eternityBUG** [comment]
> Thanks for the issue. I will look into what may be the cause of this behavior.

Is there any progress

**Comment by AhSem** [comment]
Having the same issue. Any workaround?

**Comment by eternityBUG** [comment]
Has the investigation begun

**Comment by Jgarcia4377** [comment]
There is some progress? I encountered the same problem

**Comment by simion** [comment]
Having the same issue :(

**Comment by austinhutchison** [comment]
I'm also having issues with iOS ion-refresher. here's another video [link](https://trello-attachments.s3.amazonaws.com/5b57427249acbb15738f64b1/5eb865c592bf292ba8834576/c4ee741e6c5d3ac2abce06a16055e343/RPReplay_Final1589142887.mov)

I've edited some of the available properties but I haven't been able to fix. I'm in the process of upgrading from v3 to v5 and this is an element that seems to have taken a step back (same implementation on my v3 codebase)

**Comment by bobrosoft** [comment]
Ye, see the same annoying glitch on iOS :((

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by austinhutchison** [comment]
The refresher works a bit better if you avoid using the `translucent` property, which is set by default on the Tabs starter template. It's not perfect but it's significantly better.
