### ISSUE TITLE
bug: Position of ionic select dropdown is not proper in mobile device on orientation

### ISSUE THREAD

**Issue by shyam-santra** [ionic-team/ionic-framework#19190]
# Bug Report

**Ionic version: 4.7.0

**Current behavior:**

    We are using < ion - select > and < ion - select - option > as 
    ** Related code:
<ion-select class="searchbar-dropdown__sortby"[(ngModel)] = "selectedSortOption" interface = "popover"(ionChange) = "updateSearchBySortCriteria()" >
    <ion-select-option value="{{ sortOption }}" *ngFor="let sortOption of sortByDropdownOptions">
        {{ sortOption }}
    </ion-select-option>
</ion-select>

**Steps to reproduce:

1) Keep iOS device in Landscape mode 
2) Now, select the first option from Sort by field 
3) Notice the Sort by options shows at proper placed below sort by field 
4) Now, rotate / move iOS device in Portrait mode 
5) Notice the Sort by options position
This is how it behave: https://www.screencast.com/t/ARVp4wigCi

**Expected behavior:**
The dropdown option should positioned to it earlier position

**Comment by paulstelzer** [comment]
Thanks for your issue! I can confirm this issue. The reason fpr this behaviour is that Ionic not recalculate the position after resizing the window. On my apps, I close all dropdowns / popover on resize. ANother solution would be a recalculating on resize

**Comment by shyam-santra** [comment]
Any update on fix from ionic?
