### ISSUE TITLE
bug: IonButton's classes don't react to slot changes.

### ISSUE THREAD

**Issue by farsadx** [ionic-team/ionic-framework#19200]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
While toggling between ``icon-only`` and ``start`` slot of an ``ion-button`` in runtime, element classes won't change to represent to the current state of the button.

**Expected behavior:**
The ``button-has-icon-only`` should be removed while switching the icon's slot to ``start`` and added back while switching back to ``icon-only``.

**Steps to reproduce:**

1. Create an empty component and write a basic button like this:
```
<ion-button (click)="iconOnly != iconOnly;">
    <ion-icon [slot]="iconOnly ? 'icon-only' : 'start'" icon="logo-ionic"></ion-icon>
    <ion-label *ngIf="!iconOnly">Icon</ion-label>
</ion-button>
```
2. In the components definition file add this:
```
protected iconOnly: boolean = false;
```
3. Try to toggle it and check out inspector for ``button-has-icon-only`` class.

**Other information:**
To overcome the situation, I've bound the ``button-has-icon-only`` class to the variable, but It'd be much better if it'd handled by the framework.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/usr/local/Cellar/node@10/10.16.3/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by paulstelzer** [comment]
Thanks for your issue! I tried it and you are right, the class of the ion-button is not changed because it will not be triggered if the ion icon is changed inside. I don't know if this is by design, but @manucorporat or @liamdebeasi can tell you more :)

**Comment by farsadx** [comment]
Thanks for replying @paulstelzer,
Is there any updates on this matter?!
@manucorporat @liamdebeasi
