### ISSUE TITLE
bug: ionic Vue/@0.0.9 build is not working

### ISSUE THREAD

**Issue by Sacrekin** [ionic-team/ionic-framework#19211]
I have an Ionic/vue boilerplate app testing several UI components. Works great in dev mode but the built version generates errors (see Chrome message in image attached)

Versions:
"dependencies": {
    "@ionic/core": "^4.6.2",
    "@ionic/vue": "^0.0.9",
    "axios": "^0.19.0",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3"
  }

At execution, Chrome displays the following error:  Resource interpreted as Stylesheet but transferred with MIME type text/html
![image](https://user-images.githubusercontent.com/30285648/63870039-7aed1000-c9b9-11e9-95c8-a40f74552ded.png)

**Comment by brandyscarney** [comment]
Thanks for the issue. We have been working on a new beta for Vue with support for Vue 3. We'll have a blog out soon with steps to run it.
