### ISSUE TITLE
bug: ion-spinner moving when position absolute (possible regression)

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-framework#19247]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
When setting a position absolute to the `ion-spinner` won't hold in place as it used to but is now moving slowly to the right.

**Expected behavior:**
Spinner stays in place even with absolute positioning

**Possible regression:**
Ionic v.4.7.1 -> all good, spinner stays in place
Ionic v4.8.1 -> spinner is moving

**Related code:**

```
<ion-content>
    <ion-spinner color="primary"></ion-spinner>
</ion-content>
```

```
ion-spinner {
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
}
```

**Other information:**

I observed the behavior in an Angular app as well in a Stencil PWA, therefore I would say it's a core issue.

**Screenshot:**

<img width="568" alt="Capture d’écran 2019-09-01 à 13 17 44" src="https://user-images.githubusercontent.com/16886711/64075630-f5b87280-ccba-11e9-9ee8-aa1a13f84393.png">

**Comment by brandyscarney** [comment]
Thanks for the issue! I was able to reproduce this in core as well: https://codepen.io/brandyscarney/pen/VwZRBro

**Comment by amandaesmith3** [comment]
This has (finally!) been resolved, via https://github.com/ionic-team/ionic-framework/pull/24643. The fix will be available in a future release of Ionic 👍 It turns out that this was exclusive to the `circular` type spinner, and was triggered by adding `transform`, rather than `position: absolute`.

**Comment by peterpeterparker** [comment]
Super cool! Thanks @amandaesmith3
