### ISSUE TITLE
bug: infinite-scroll not work well，loadData cann‘t fire again

### ISSUE THREAD

**Issue by 18929156966** [ionic-team/ionic-framework#19261]
html：
<ion-infinite-scroll threshold="50px" id="infinite-scroll" (ionInfinite)="loadData($event)">
          <ion-infinite-scroll-content loading-spinner="bubbles" loading-text="Loading more data...">
          </ion-infinite-scroll-content>
        </ion-infinite-scroll>

ts：
loadData(event){
    setTimeout(() =>{
      this.list = this.list.concat(this.users.slice(0,20))
      event.target.complete();
    },500)  
  }

**Comment by 18929156966** [comment]
"@angular/cli": "8.3.2",
"@ionic/angular": "^4.7.4",

**Comment by leoshuaige** [comment]
Had the same problem, I also don't know how to solve, when returning from other pages infiniteScroll is no work, when I leave the list page, I set up this. InfiniteScroll. Disabled = false; But it doesn't work, right

**Comment by leoshuaige** [comment]
Had the same problem, I also don't know how to solve, when returning from other pages infiniteScroll is no work, when I leave the list page, I set up this. InfiniteScroll. Disabled = false; But it doesn't work, right

**Comment by tomavanc** [comment]
Same here. 

**Steps to reproduce**
1. Go to page with `<ion-infinite-scroll>`: **ionInfinite** is triggered
2. Navigate to other page, then come back to page with `<ion-infinite-scroll>`
3. **ionInfinite** is not triggered anymore

**Info**

  Ionic CLI                     : 5.2.8 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.803.3
   @angular-devkit/schematics    : 8.3.3
   @angular/cli                  : 8.3.3
   @ionic/angular-toolkit        : 2.0.0

**Comment by sagrawal31** [comment]
I'm facing the same issue with `Ionic 4.10.0`

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.

**Comment by tomavanc** [comment]
@liamdebeasi I relooked into the scroll problem, please have a look

**ISSUE** 
Page A on Tab 1 has the infinite scroll implemented. You load all items, so the `disabled` property is set to true.
When navigating through the tabbar exclusively from Tab 1 to Tab 2 for example and then coming back to Tab 1, the `disabled` property is still set to **true**. So the infinite scroll won't work. If you navigate by a click event with the router.navigate and then come back to Page A, the `disabled` property is reset to **false** like it is supposed to.

**WORKAROUND** 
Set the `disabled` property to false every time you enter the page:

```html
<ion-infinite-scroll #infiniteScroll>
</ion-infinite-scroll>
```

```typescript
@ViewChild('infiniteScroll') infiniteScroll: IonInfiniteScroll;

ionViewWillEnter() {
  this.infiniteScroll.disabled = false;
}
```

**Comment by liamdebeasi** [comment]
@tomavanc Can you please provide this as a full repo? Code snippets are usually not enough to reproduce issues like these.
