### ISSUE TITLE
Long pressing ion-tab-button doesn't navigate but set the button to active

### ISSUE THREAD

**Issue by kdfemi** [ionic-team/ionic-framework#19263]
**Ionic version:**

[x] **4.10.3**

**I'm submitting a ...** 

[x ] bug report
[ ] feature request

**Current behavior:**

Long pressing ion-tab-button set the button color to active but doesn't navigate once released. The tab before the long press is still opened and also have the active color, that means there are two tabs with active color..
**Expected behavior:**

The tab should either switch to the newly long pressed tab or the current one should still be active ignoring the long pressed tab and only one single active color should be present.  
**Steps to reproduce:**

Create a tab view with four tab-buttons long press any tab button that is currently not active for about 5 secs then release.

**Ionic info:** 

```
Ionic:
   ionic (Ionic CLI)             : 4.10.3 (C:\Users\*****\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
