### ISSUE TITLE
bug: 4.9.0 - Swipe back navigation broken on iOS

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/ionic-framework#19293]
# Bug Report

**Ionic version:**
[x] **4.9.0**

**Current behavior:**
Router Navigation with the swipe back gesture is broken on iOS.
When swiping back, there will be no transition - once the gesture ends, the screen will flash and rebuild - finally the previous page will appear - or the navigation will just skip N number of sites! This may also be related to #18455

**Expected behavior:**
Seamless and smooth swipe back navigation on iOS with proper transitions.

**Steps to reproduce:**
- Generate the ionic conference starter
- Upgrade to Ionic 4.9.0
- Swipe around and notice the issue

**Related code:**

No code necessary, can be generated using the conference starter.

**Other information:**
This seems to be part of some bigger navigation issue (together with Angular?).
Issue #18455 seems to be related, as one effect (skipping of pages) can also be triggered by double tapping the back button.
This may also break the app completely with scroll views locking up.
Notice that swipe to go back behaves especially weird if there are Angular Route Guards in place (CanActivate...)

![IonicBrokenNav](https://user-images.githubusercontent.com/819238/64460391-91524480-d0fa-11e9-8e0c-9c75a875d067.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/Users/Wilk/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.1
   @angular/cli                  : 8.1.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 5 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 25.2.2 (/Users/Wilk/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/Users/Wilk/.nvm/versions/node/v10.16.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I think this might also be related to https://github.com/ionic-team/ionic/issues/18879 though I am not 100% certain.

We will look into this and update this thread when we have more information.

**Comment by wilk-polarny** [comment]
Another weird thing is: on earlier versions (such as 4.2.1, not sure about other versions) - when you tried to swipe back to a page without being allowed to (guard (canactivate)being set), the transition wouldn't happen, but lifecycle events would still fire for the page which was about to be visited.
What happened next was that you could always see a translucent, rendered version of the page (with the previous nav fail due to the guard) inbetween any page changes (forward/backward). Kind of like a ghost haunting the navigation stack ;)

**Comment by lincolnthree** [comment]
Seems related to: https://github.com/ionic-team/ionic/issues/18181

**Comment by lincolnthree** [comment]
Also: https://github.com/ionic-team/ionic/issues/17277

**Comment by lincolnthree** [comment]
@liamdebeasi I can reproduce this in my app consistently. It's huge though. Tons of code. I can't share it publicly but I'll try to trim it down.


![](https://media.giphy.com/media/hScCYZsZ6Zmz3EyZk1/giphy.gif)

**Comment by lincolnthree** [comment]
Here's an interesting thing though. I actually have "swipeEnabled = false" set in the template. It does not seem to do anything, which is another problem. This leads to some interesting transitions on android...

**Comment by lincolnthree** [comment]
![](https://media.giphy.com/media/eMOINTdZfLqhB7vRqv/giphy.gif)

**Comment by wilk-polarny** [comment]
@lincolnthree , see #19330 regarding swipe to go back and deactivation. The property name changed and needs to be applied to the router outlet you are using. (Only if you're using the old nav stack, the property in the root module will work).
If you use tabs, you will need to manually set the property, as the according router outlet is not being declared by you anymore since a few versions ago when the team refactored tab related code.

@liamdebeasi This looks like a bit more than janky animations:

In my gif example, the view will navigate back two sites instead of one, ending up on the tutorial screen of the conference app.

```
  ionViewWillEnter() {
    this.storage.get('ion_did_tutorial').then(res => {
      if (res === true) {
        this.router.navigateByUrl('/app/tabs/schedule');
      }
    });
```

... on the tutorial page will also not be triggered. When combining this with angular route guards instead (which is usually the way to go), trying to swipe back on a site will leave the routing system in an inconsistent state (a problem for us since 4.x) - e.g. displaying a page which you are not on according to the router.

**Comment by C-racker** [comment]
+1

**Comment by wilk-polarny** [comment]
@liamdebeasi , were there any changes since 4.9.0 to the swipeback feature?

It would be generally nice to have more control about whether swiping back should be possible or not on specific pages and swipeback should not cause any weirdness when Angular route gards prevent navigation (especially together with tabs).

Do you need a repro for the specific issues, or is "swipeback" already being tracked by the team?

**Comment by wilk-polarny** [comment]
@liamdebeasi , swipeback kinda worked in the latest 4.x, but seems to be broken again in 5.x.

when navigating using `navigateByUrl('/login', { replaceUrl: true })` I am still able to swipe back to the previous page, although `replaceUrl: true` should remove the history. If a guard prevents the navigation, the router will instead skip the page and navigate to the one before the one whose guard denied the navigation. Could you guys take a look at that?

**Comment by wilk-polarny** [comment]
Ok, I did some more digging, tracing and debugging. I think I have nailed it down.

@liamdebeasi , here is a minimal Ionic5 repro: https://github.com/wilk-polarny/ReproIonic19293/tree/master

This is what the constellation looks like:

- App starts, navigates to `""`
- `""` redirects to `init-page`
- `init-page` routes to `onboarding`, guarded by `NeverActivateGuard` which in this case redirects to `app`

Together, it looks like this:
`""` --> `init-page` --> `onboarding` --> `app`

- Notice, that `init-page` gets created, but never destroyed.
- When navigating back using the swipeback gesture, Ionic will navigate back to the still not destroyed app root.

- This will work with any page which has not been destroyed for some reason. Ionic will also skip guarded pages and navigate to the earliest non destroyed page when swiping back.

This is all I can do so far - can someone please dig a little deeper? I would understand why this happens, and whether this is some angular quirk or an Ionic bug.

**Comment by lincolnthree** [comment]
For me, this occurs because the built-in ionic components are not where the animation/transition expects them to be. I have a custom page-wrapper component that handles layout on multiple device form factors, and due to this nesting, ionic cannot find the correct elements when constructing the flow.

This is how I've worked around it, using a custom css selector to choose the correct elements to animate, as specified in https://github.com/ionic-team/ionic/issues/18181:

````
    if (!contentEl && enteringToolBarEls.length === 0 && headerEls.length === 0) {
      enteringContentAnimation.addElement(enteringEl.querySelector(':scope > my-custom-component, :scope > .ion-page, :scope > ion-nav, :scope > ion-tabs')!);  // REVIEW
    } else {
````
