### ISSUE TITLE
bug: iOS nav toolbar transition from tabbed to non-tabbed page is incorrect

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic-framework#19372]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

When ios and android sideslip, if the background color is set on the top, the top is not completely filled in when sideslip, which makes it look bad

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
ion-toolbar {
  --background: #faa;
}
```

**Other information:**

![bug1](https://user-images.githubusercontent.com/20217449/65016825-cad74b00-d957-11e9-9dfa-5dfc05ce06f2.png)

![bug1](https://user-images.githubusercontent.com/20217449/65016793-b09d6d00-d957-11e9-9c6e-9df67347d359.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue. The cutoff is actually just the edge of the entering page (the page with the tabs at the bottom). One thing you might want to try is setting the background color of the toolbar for the leaving page as well.

Can you try that and let me know if it resolves your issue?

**Comment by C-racker** [comment]
> Thanks for the issue. The cutoff is actually just the edge of the entering page (the page with the tabs at the bottom). One thing you might want to try is setting the background color of the toolbar for the leaving page as well.
> 
> Can you try that and let me know if it resolves your issue?

Thanks for your reply, 
I added the test1 page and set the background color of the `ion-toolbar`. Now I still have problems with the skid.

`test1.page.ts`
```
ion-toolbar {
  --background: #faa;
}
```
gif:
![bug2](https://user-images.githubusercontent.com/20217449/65096037-14767300-d9f6-11e9-946f-9d414bd6bafb.gif)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. The reason this is happening is because you are transitioning between router contexts. On the initial page you have a tabs router context, and then you are transitioning to another router context (you can tell you are switching contexts because the tabbar is not on the second page). If you were to transition between pages within a router context this would not occur.

I will check with the team to see if this is a bug or expected functionality. I will post an update here when I have more info.

**Comment by liamdebeasi** [comment]
I spoke with the team regarding this, and it does seem to be a bug. The fix for this does not appear to be straightforward, so I don't have a timeline of when this will be done. I will be sure to post an update here when I have more to share. Thanks!

**Comment by C-racker** [comment]
> I spoke with the team regarding this, and it does seem to be a bug. The fix for this does not appear to be straightforward, so I don't have a timeline of when this will be done. I will be sure to post an update here when I have more to share. Thanks!

Thanks for looking forward to good results :)

**Comment by bolivir** [comment]
Noticed the same issue happening on ionic 5, in the browser its a black overlay and on an mobile device its an white overlay thats gets shown.

**Comment by liamdebeasi** [comment]
Hi everyone,

I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/26736 which has a bit more context as to why this bug is occurring. Please follow that thread for updates. Thanks!
