### ISSUE TITLE
feat: ion-datetime Can you add custom text

### ISSUE THREAD

**Issue by C-racker** [ionic-team/ionic-framework#19397]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

https://github.com/ionic-team/ionic/issues/14843
I saw a suggestion before, but it was turned off. I need the same thing as him. Can I implement this feature in ionic4

**Describe Preferred Solution**

**Describe Alternatives**

The result is perfect
![最终效果](https://user-images.githubusercontent.com/20217449/65319071-64f5f800-dbd1-11e9-8262-c91ea86b0a1a.png)

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. With Ionic 6 we introduced a new calendar-style picker that does not use a wheel, so this does not appear to be needed at the moment.

We are looking to add support for selecting dates with a wheel in https://github.com/ionic-team/ionic-framework/issues/23981. However, we would like to keep the behavior close to what native does. As a result, we do not have plans to support custom labels on the values in the wheel.

If you are looking to show a picker that acts more like a timer or a countdown, we recommend using `ion-picker`. `ion-picker` allows you to have your values display like `1hr 40mins` which may be more suitable for your use case. Please see https://ionicframework.com/docs/api/picker for an example of how to use `ion-picker`.

I am going to close this. Thank you!
