### ISSUE TITLE
bug: Gesture animations not working on iOS 11

### ISSUE THREAD

**Issue by jsitu** [ionic-team/ionic-framework#19405]
# Bug Report

**Ionic version:**

**4.9.1**

**Current behavior:**

I scaffolded the side menu template project with Ionic cli,  installed Capacitor and run the app in a real device (iPhone 8 plus). The side menu transition works if I tap on the menu icon on the top left. But if I tried to swipe from left to right, the transition doesn't work, which makes it difficult to know when the menu is activated or not. Sometimes the side menu is invisible even I swipe from left to right, so frustrating. The OS version is 11.4.1.

See the video recording below:
https://drive.google.com/file/d/1GD-5mVrF-Ljdo5Jm0QU4czdK3Q5dZfoD/view?usp=sharing

**Expected behavior:**

The side menu animation transition should work with swiping from left to right. 

**Steps to reproduce:**

1. Scaffold the new app with the side menu template
2. Install Capacitor cli and core
3. Run the app in a real device via XCode
4. Swipe left to right in the main home page

**Comment by yzedayyash** [comment]
same issue here!

**Comment by AboodAyyash** [comment]
same issue here!

**Comment by liamdebeasi** [comment]
Thanks for the issue. Which version of Ionic are you seeing this on?

**Comment by yzedayyash** [comment]
Almost all versions, i tried from 4.5 to 5.3 and get same issue

**Comment by jsitu** [comment]
@liamdebeasi this is my local config:

<img width="406" alt="Screen Shot 2019-09-24 at 10 35 06 AM" src="https://user-images.githubusercontent.com/3535345/65521374-21440c80-deb7-11e9-91df-e794dc7d5f78.png">

**Comment by liamdebeasi** [comment]
Which version of iOS are you seeing this on? I am not able to reproduce this on a sidemenu starter with a device running iOS 13.

**Comment by jsitu** [comment]
I'm on iOS 11.4.1, iPhone 8 plus.

**Comment by yzedayyash** [comment]
@liamdebeasi 
sorry my ionic/angular version is  4.7.0
and i tried to run the application on IOS 12 and 13

**Comment by liamdebeasi** [comment]
@jsitu I can reproduce the issue you are describing. Unfortunately this looks like a Safari bug: https://bugs.webkit.org/show_bug.cgi?id=141008

This appears to have been resolved in newer version of iOS. I am investigating more to see if there are any workarounds we can apply.

**Comment by liamdebeasi** [comment]
@yzedayyash Can you update to the latest version of Ionic and try again? If it still doesn't work, please provide some steps to reproduce.

**Comment by liamdebeasi** [comment]
@jsitu I dug into this a big more. Looks like the bug in Safari was indeed fixed starting with iOS 12.0, so for the most part iOS users will not run into this issue.

**Comment by jsitu** [comment]
@liamdebeasi Ok, but when I developed with Ionic 3, it doesn't have this issue though. I have an old project with below config:
```
Ionic CLI 4.2.1
Ionic Angular 3.9.6
@ionic/app-scripts 3.2.0
```

**Comment by liamdebeasi** [comment]
We made some changes under the hood to animations in v4. Ionic 3 is using an older animation system.

**Comment by jsitu** [comment]
Thanks @liamdebeasi hopefully you guys can come up with a solution that can solve it, some of our users are still using old OS and we want to leverage Capacitor in Ionic 4.

**Comment by liamdebeasi** [comment]
Can you try installing Ionic 4.7.4 and see if that works? There were some changes introduced in 4.8 that might be causing issues as well.

**Comment by jsitu** [comment]
@liamdebeasi do you mean downgrading `ionic-angular` to 4.7.4?

**Comment by liamdebeasi** [comment]
Yeah, so try `npm install @ionic/angular@4.7.4`

**Comment by jsitu** [comment]
@liamdebeasi that works for me, thanks. What's special in 4.7.4 that 4.9.1 doesn't have?

**Comment by C-racker** [comment]
> Yeah, so try `npm install @ionic/angular@4.7.4`

4.7.4 can indeed solve the problem, but the subsequent bug fixes can not be applied to this version, so we need to ensure the latest 4.11.x. Is there any way to make the latest version support ios11.x, because more people use these devices
