### ISSUE TITLE
feat: Hide Tabs on sub-pages

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ionic-team/ionic-framework#19427]
# Feature Request
Recommended Approach to hide tabs programmatically.

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**

There is no proper way to hide tab-bar in Ionic v4.

There is this tutorial: https://medium.com/@JordanBenge/ionic-4-hiding-showing-tabs-on-certain-pages-31cf2380a5db

But with this the content moves up or down resulting in jerks and bad user experience.

If Ionic Team can give a recommended way to achieve this into docs, it will be very helpful for many developers.

**Describe Preferred Solution**
May be a similar approach like the tutorial but with smoother results.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you able to just not make the pages children of your tabs component? For example, you would have `/tabs/tab1 ---> /childPage`.

**Comment by ASHFAQPATWARI** [comment]
@liamdebeasi I already have subpages and i can navigate to them. 
For eg:
 1. I have tab called /categories
2. I can navigate to /categories/1
3. I want the tabs to be hidden on the childpage

Basically you can say a way to achive `tabsHideOnSubPages` functionality of v3 with v4.

**Comment by patrick-entinux** [comment]
When I want the tabs to be hidden on some child page, I would set the route for that other page to be a 'regular' page, not a child of the tab page. For example:

```typescript
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      {
        path: 'categories',
        component: CategoriesPage,
      },
      {
        path: 'settings',
        component: SettingsPage,
      },
    ],
  },
  {
    path: 'categories/:id',
    component: CategoryDetailsPage,
  },
];
```

Then from /categories page, you could have a link like:

```html
<a routerLink="/categories/1">Details for Category 1</a>
```

And the tabs can transition away with the rest of the previous page.

However, this method has some gotcha's with toolbar background colors too: https://github.com/ionic-team/ionic/issues/19372

**Comment by ASHFAQPATWARI** [comment]
@patrick-entinux Well this is one of the thing which can be tried but I believe there must be a way to hide tabs as well. Setting routes like above seems more of a hack.

**Comment by mirkonasato** [comment]
Would like an approach that works with React as well, not just Angular.

**Comment by fr3fou** [comment]
Any news on this with Ionic 6 right around the corner? This really is a crucial feature imo

**Comment by indraraj26** [comment]
We had this option in ionic2/3 `tabsHideOnSubPages="true"`
Route
```
 {
    path: '',
    children: [
      {
        path: '',
        component: ProfilePage, //tabs/profile
        pathMatch: 'full', 
      },
      {
        path: 'password-change',
        component: Components.PasswordChangeComponent, // tabs/profile/contact-us
      }
]
}
```

When i will visit `tabs/profile/contact-us` i want tabs to hide

**Comment by iKrishnaSahu** [comment]
> Hope this is not intruding, but just want to add an alternative method. When I want the tabs to be hidden on some child page, I would set the route for that other page to be a 'regular' page, not a child of the tab page. For example:
> 
> ```ts
> const routes: Routes = [
>   {
>     path: 'tabs',
>     component: TabsPage,
>     children: [
>       {
>         path: 'categories',
>         component: CategoriesPage,
>       },
>       {
>         path: 'settings',
>         component: SettingsPage,
>       },
>     ],
>   },
>   {
>     path: 'categories/:id',
>     component: CategoryDetailsPage,
>   },
> ];
> ```
> 
> Then from /categories page, you could have a link like:
> 
> ```
> <a routerLink="/categories/1">Details for Category 1</a>
> ```
> 
> And the tabs can transition away with the rest of the previous page.
> 
> However, this method has some gotcha's with toolbar background colors too: #19372

This workaround works fines. But I encountered an issue with this approach.
 Once we come back to tab layout again i.e. from `categories/:id` to `categories`, It is not firing `ionViewWillEnter` and `ionViewDidEnter` events in `CategoriesPage` component.

Any updates on this issue?

**Comment by liamdebeasi** [comment]
Hi everyone,

I spoke with the team, and we are not looking to add the requested feature at this time. The tab bar is designed to be shown on all tab pages (even child tab pages) to allow users to quickly navigate to the root of the tab. This behavior aligns with tabs in native iOS and Android applications. As a workaround, you can hide the tab bar by navigating to routes that are not children of tabs. I am going to close this, but let me know if there are any questions.
