### ISSUE TITLE
feat: DateTime desktop improvements 

### ISSUE THREAD

**Issue by heinzburgstaller** [ionic-team/ionic-framework#19423]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

The Ionic DateTime picker component is not well suited for Desktop.

**Describe Preferred Solution**

On Desktop you have a finer degree of selection. Ionic should check if it runs in a desktop environment therefore displaying a better date input (with time). Make use of keyboard and scroll wheel.

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by kerosin** [comment]
possible duplicate: https://github.com/ionic-team/ionic/issues/15505

**Comment by heinzburgstaller** [comment]
@brandyscarney The date input component is still unusable in a desktop browser. Have a look at this approach https://www.npmjs.com/package/@codaline-io/ionic-datepicker

**Comment by jase88** [comment]
Another Stencil Datepicker component: https://github.com/duetds/date-picker

**Comment by puku0x** [comment]
Calendar picker has been merged! https://github.com/ionic-team/ionic-framework/pull/23325

**Comment by skotturi** [comment]
How can we use/test this?

**Comment by liamdebeasi** [comment]
Thanks for the issue! In Framework v6 we will be shipping a new calendar-style date picker that has desktop support. Be sure to check out https://ionic.io/ioniconf for more information on when you can start testing it.

**Comment by heinzburgstaller** [comment]
> Thanks for the issue! In Framework v6 we will be shipping a new calendar-style date picker that has desktop support. Be sure to check out https://ionic.io/ioniconf for more information on when you can start testing it.

Is there a teaser screenshot or a screencast anywhere for a sneak preview?

**Comment by jase88** [comment]
On twitter there are some sneak previews:
https://twitter.com/benjsperry/status/1393250260827389959
https://twitter.com/benjsperry/status/1395815427121586185
https://twitter.com/LiamDeBeasi/status/1398323097133096964

**Comment by liamdebeasi** [comment]
(The iOS time picker in those demos will be updated for iOS 15 before Framework v6 ships)
