### ISSUE TITLE
bug: Params in router aren't shared in child routes

### ISSUE THREAD

**Issue by marksyzm** [ionic-team/ionic-framework#19438]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Params don't propagate to child routes in `ion-route`:
```jsx
<ion-route component="app-dashboard" url="/dashboard/:hostname">
   <ion-route component="app-start" />
</ion-route>
```

**Expected behavior:**
URL should be available or made available via `rootParams` in an `ion-nav` element perhaps? Props should be populated in the child element via the route params. So any child components attached to a child route should inherit its parent route props.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
