### ISSUE TITLE
bug: ES2015 export does not replace documentFragmentChildren in loop

### ISSUE THREAD

**Issue by wodka** [ionic-team/ionic-framework#19442]
# Bug Report

**Ionic version:**

[x] **4.9.0**

**Current behavior:**

The screenshot is from the built file in www/common-es2015...

![image](https://user-images.githubusercontent.com/385731/65586636-c547b980-df84-11e9-8116-75d8d1254112.png)

https://github.com/ionic-team/ionic/blob/master/core/src/utils/sanitization/index.ts#L55

**Expected behavior:**

during the build the for reference should also be replaced

**Steps to reproduce:**

create an empty ionic project, `ionic build --prod` and take a look at the common-es2015 file

**Related code:**

From /core/src/utils/sanitization/index.ts
```
    const documentFragmentChildren = getElementChildren(documentFragment);

    /* tslint:disable-next-line */
    for (let childIndex = 0; childIndex < documentFragmentChildren.length; childIndex++) {
      sanitizeElement(documentFragmentChildren[childIndex]);
    }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (/usr/local/Cellar/node@10/10.16.0/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave

```

**Comment by wodka** [comment]
Just updated the following packages, same error / same problem

```
+ codelyzer@5.1.1
+ @angular/pwa@0.803.5
+ @ionic/angular@4.9.1
+ @ionic-native/splash-screen@5.14.0
+ @ionic-native/status-bar@5.14.0
+ @ionic-native/core@5.14.0
```

**Comment by wodka** [comment]
@manucorporat sadly this does not work - the error now just changed to dfChildren

```
for (let n = 0; n < dfChildren.length; n++)
   o(dfChildren[n]);
```

**Comment by wodka** [comment]
for now I changed the tsconfig.json target to es5 -> this skips the es2015 build

**Comment by manucorporat** [comment]
i am so confused then

**Comment by manucorporat** [comment]
Seems like a bug in webpack/terser/angular of somekind

**Comment by manucorporat** [comment]
Maybe related with https://github.com/terser/terser/issues/452

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
