### ISSUE TITLE
bug: ion-reorder-group broken when iterating custom components.

### ISSUE THREAD

**Issue by marpstar** [ionic-team/ionic-framework#19447]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

See previous issue that was closed: https://github.com/ionic-team/ionic/issues/7425

I'm trying to use `ion-reorder-group`. Previously I was iterating with `ion-item-sliding` for my child elements and everything worked fine.  I refactored my code so that the `ion-item-sliding` and all descendant nodes are part of a new component `cg-layer-select-item`. 

When I click and drag the `ion-reorder` component, I do not see my custom element "lift" itself out of the collection and begin the reordering process. If I drag my finger and *try* to move the item anyway, it tends to end up at the end of my `ion-reorder-group`, with the reorder event `detail` looking like ` { from: 1, to: 10 } ` where `10` is the last slot in the group.

**Expected behavior:**

I expect to be able to reliably reorder custom components with full animation support. 

**Steps to reproduce:**

Sample app: https://stackblitz.com/edit/ionic-v4-angular-tabs-a5ezqv

Note there are TWO `ion-list`s with a direct child `ion-reorder-group`. The difference between the two is that one uses `ion-item` as a child, the other a custom component. The `ion-item` version works fine, but the custom component version does not. 

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.0
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26289, and a fix will be available in an upcoming release of Ionic Framework.
