### ISSUE TITLE
bug: Error when over-rolling in Picker

### ISSUE THREAD

**Issue by TheColdVoid** [ionic-team/ionic-framework#19485]
# Bug Report

**Ionic version:**
5.2.3

**Current behavior:**
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/10008227/65812175-fda1fe80-e1f5-11e9-9def-7c0e57521cbd.png">
When I use Picker, when I scroll up in the pop-up Picker, I get an error:
`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`
`ion-datetime_3-ios.entry.js:1392 [Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
push../node_modules/@ionic/core/dist/esm-es5/ion-datetime_3-ios.entry.js.class_3.onStart @ ion-datetime_3-ios.entry.js:1392
onStart @ ion-datetime_3-ios.entry.js:1229
fireOnStart @ index-624eea58.js:509
tryToCapturePan @ index-624eea58.js:503
pointerDown @ index-624eea58.js:449
handleTouchStart @ index-624eea58.js:247`
**Expected behavior:**
No error in console

**Steps to reproduce:**
1. Write a simple sample program to open the picker
2. Open Chrome, open the Developer Console, and click Toggle Device toolbar
3. Select the Emulated device for iPhone6plus
4. Open the picker and scroll down the picker until it crosses the border
5. Error reproduction
**Related code:**

**Other information:**
It is worth noting that after testing, this bug will only appear when the computer is set up with Emulated Device for iPhone (I set up iPhone6 plus). Under Safari, everything works fine. Chrome does not seem to appear when it is not equipped with Emulated Device. The problem, Android and iOS actual machines will not have this problem. And this problem only appears when setting the Picker style to iOS style.The chrome version I am using is 77.0 (64 bit).
**Ionic info:**

Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.9.0 (/usr/local/Cellar/node/10.9.0/bin/node)
   npm        : 6.5.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by SergioSuarezDev** [comment]
Same issue here using https://ionicframework.com/docs/api/datetime

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
