### ISSUE TITLE
bug: ion-tab-bar slot not working with Angular binding

### ISSUE THREAD

**Issue by soramister** [ionic-team/ionic-framework#19484]
# Bug Report

**Ionic version:**

[x] **4.5.0**

**Current behavior:**

When assigning a variable to position the tab bar to top or bottom, the tab bar does not position correctly

**Expected behavior:**

For example, setting the slot position to top from a variable in a component, the tab bar should be on the top.

**Steps to reproduce:**

<ion-tab-bar [slot]="tabSlotPosition"> in the template and tabSlotPosition set to 'top' in the component.

**Related code:**

**Other information:**

If I set the value hard coded in the code, it works normally. For example:
<ion-tab-bar slot="top">

**Ionic info:**

Ionic:

   Ionic CLI                     : 5.4.1 (/Users/jeremie/.nvm/versions/node/v11.1.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.6 (update available: 0.2.8)

System:

   Android SDK Tools : 26.1.1 (/Users/jeremie/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v11.1.0 (/Users/jeremie/.nvm/versions/node/v11.1.0/bin/node)
   npm               : 6.10.3
   OS                : macOS Mojave
   Xcode             : Xcode 11.0 Build version 11A420a

**Comment by Muji86** [comment]
Was there a solution to this?

**Comment by jsandler18** [comment]
+1 I am also experiencing this issue.

**Comment by phiamo** [comment]
same issue here

**Comment by razfriman** [comment]
Same

**Comment by arramanenka** [comment]
Same

**Comment by Ross-Rawlins** [comment]
Same

**Comment by gr99t** [comment]
Still an issue in 5.5.4

As a workaround I am binding a CSS class to the ion-tab-bar:

```html
<ion-tab-bar [class.top-bar]="isTop" [slot]="isTop ? 'top' : 'bottom'">
```

CSS:
```css
.top-bar {
   position: absolute;
   left: 0;
   right: 0;
}
```

**Comment by Blamax** [comment]
> Still an issue in 5.5.4
> 
> As a workaround I am binding a CSS class to the ion-tab-bar:
> 
> ```
> <ion-tab-bar [class.top-bar]="isTop" [slot]="isTop ? 'top' : 'bottom'">
> ```
> 
> CSS:
> 
> ```css
> .top-bar {
>    position: absolute;
>    left: 0;
>    right: 0;
> }
> ```

unfortunately, this messes with other bars due to absolute positioning.

**Comment by juanAFernandez** [comment]
Same problem. A simple nasty workaround, duplicate the code (one with `bottom` and the other one with `top`  and add a *ngIf.

**Comment by Saqib92** [comment]
Still facing this issue.

**Comment by Abrarss** [comment]
still facing the same issue

**Comment by gongAll** [comment]
a lot of people are commenting this issue.

PLEASE bump it instead of commenting it so that it goes up on the priority list.

Cheers.

**Comment by EarlTilluck** [comment]
The reason binding doesn't work:  
Basically the `<ion-tabs>` element is a flexbox with `flex-direction: column`, 
Inside this, there are two elements: the `<ion-tab-bar>` and a div with the class `tabs-inner`  
If `slot="top"` is set, then the tab-bar will be placed first inside the `ion-tabs` with the `tabs-inner` div below it, and vica versa for `slot="bottom"`.  
When you change the value of slot, nothing happens, the elements remain in the same order in the document.


#### My workaround: 
when you want the tab-bar at the top, change the css order value
to -1

#### css:
```
.top-menu {
  // this tells the flex container to place this item first
  order: -1;
}
```

#### html
```
<ion-tab-bar slot="bottom" [ngClass]=" condition? 'top-menu' : '' ">
```

This method keeps the original design format and should not lead to conflicts elsewhere.

**Comment by gog1withme** [comment]
It may not be relevant to others, but still posting it here. This may help someone.

I generated my ionic solution using aws-amplify and after spending few hours I found that "~@aws-amplify/ui-angular/theme.css" is causing the issue with slot 'bottom' (<ion-tab-bar slot="bottom">).

After removing the theme ui-angular/theme.css import everthig works fine.

Note: If some of your app components are using the style from "~@aws-amplify/ui-angular/theme.css" then you may need to apply some custom CSS on them.

**Comment by sean-perkins** [comment]
Hello everyone 👋 

Here is a dev-build to experiment with, if anyone would like to test:

```
npm install @ionic/angular@7.0.11-dev.11685631370.18980633
```

**Comment by liamdebeasi** [comment]
Thanks for the report. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27582, and a fix will be available in an upcoming minor release of Ionic Framework.
