### ISSUE TITLE
bug: <IonPopover> 'event' prop type not compatible with emitted events from Ionic components

### ISSUE THREAD

**Issue by ebk46** [ionic-team/ionic-framework#19490]
# Bug Report

**Ionic version:**
[x] **ionic/react 4.10.0-rc.3**

**Current behavior:**
In 4.10.0-rc.3 the emitted event types were changed. However, the IonPopover prop 'event' is still typed as 'Event', making it incompatible with any emitted event from Ionic components (missing properties from Event). 

**Expected behavior:**
A MouseEvent emitted from a component's onClick should be compatible with the 'event' prop on IonPopover.

**Steps to reproduce:**
See related code.

**Related code:**
In this example, there will be a TypeScript error on the 'event' prop of <IonPopover> because Event is missing properties from the event emitted from <IonButton>. 
```
type ButtonClickEvent = React.MouseEvent<HTMLIonButtonElement, MouseEvent>;

const [clickEvent, setClickEvent] = useState<ButtonClickEvent | undefined>(undefined);

const handleClick = (e: ButtonClickEvent): void => {
  const clickEvent = {...e};
  setClickEvent(clickEvent);
};

// This 'onClick' will emit React.MouseEvent<HTMLIonButtonElement, MouseEvent>
<IonButton onClick={handleClick}>
  Click Me
</IonButton

// This 'event' prop expects Event
<IonPopover 
  isOpen={Boolean(clickEvent)} 
  event={clickEvent} 
  onDidDismiss={(): void => setClickEvent(undefined)} />
  <IonItem>
    Popover Content
  </IonItem>
</IonPopover>
```

**Other information:**
For now, the only solution has been to save the event as 'any'.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.1 (/Users/evan/.config/yarn/global/node_modules/ionic)
   Ionic Framework : @ionic/react 4.10.0-rc.3

Capacitor:

   Capacitor CLI   : 1.2.1
   @capacitor/core : 1.2.1

Utility:

   cordova-res : 0.6.0
   native-run  : not installed

System:

   NodeJS : v12.6.0 (/usr/local/Cellar/node/12.6.0/bin/node)
   npm    : not installed
   OS     : macOS High Sierra
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
