### ISSUE TITLE
feat: disabled chip

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-framework#19510]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Make it possible to disable chips.

**Describe Preferred Solution**

Add a `disabled` prop that disables the `:hover` styles (background-color, cursor, ...) and ripple.

<img src="https://user-images.githubusercontent.com/3410759/65967685-537ade80-e462-11e9-95c8-6bc27aeb9ed5.gif" width="243">

**Related Code**

https://codepen.io/simonhaenisch/pen/bGbPzOm

**Additional Context**

https://material.io/components/chips/ has examples for disabled chips in various categories.

**Comment by br1ghtt** [comment]
Working on a pull request.
In my opinion a chip in disabled state should have the following  behavior:
A disbaled chip is not activatable, has a different alpha channel for the background, text and outline. It also has no hover effect an the cursor is not shown.

**Comment by simonhaenisch** [comment]
@br1ghtt did you see the https://material.io/components/chips/ link? There's examples there of the disabled chips and what they should look/behave like.

**Comment by Yohandah** [comment]
I am in need of this as well.

I am putting a "remove" icon into a chip and I want just the icon to have a button behavior, not the whole chip (ripple, cursor).

```
<ion-chip>
  <ion-label>text</ion-label>
  <!-- I just want this icon to be "clickable", not the whole chip -->
  <ion-icon name="close" (click)="someFunction()"></ion-icon>
</ion-chip>
```

Something I don't understand as well is that in the Ionic example when clicking a chip there is no ripple effect (https://ionicframework.com/docs/api/chip), but creating a new fresh project and adding a default ion-chip will have the behavior.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/20658, and the feature will be available in an upcoming release of Ionic Framework.
