### ISSUE TITLE
bug: Ionic components wipe out parent component styles in Firefox / Safari

### ISSUE THREAD

**Issue by DesignByOnyx** [ionic-team/ionic-framework#19534]
# Bug Report

**Ionic version:**
[x] 4.10.0
**Update:** I can confirm that the issue was introduced in 4.7.0 and does not exist in 4.6.2. This should be the same issue as #19121 

**Current behavior:**
We are building a component library with Stencil and we are using Ionic components within this component library. When we integrate our components into an Ionic/Vue app, the styles for our custom components will get wiped out by ionic component styles (Firefox/Safari only).

**Chrome:**
![chrome](https://github.com/DesignByOnyx/ionic-vue-shadow-styles-bug/blob/master/screenshots/chrome.png?raw=true)
**Firefox / Safari:**
![firefox/safari](https://github.com/DesignByOnyx/ionic-vue-shadow-styles-bug/blob/master/screenshots/firefox.png?raw=true)

**Expected behavior:**
Components should render the same in all evergreen browsers.

**Steps to reproduce:**
- create a stencil component which uses shadow: true and custom styles
- use an ionic component somewhere within the render function
    - note: the issue only happens with ionic components which use shadow: false (eg. ion-list)
- integrate the component into a Vue app which uses @ionic/vue

**Related code:**
https://github.com/DesignByOnyx/ionic-vue-shadow-styles-bug

This may be related to the issue described in https://github.com/ionic-team/ionic/issues/19121. We are observing a very similar scenario where style tags from nested ionic components wipe out other style tags from sibling/parent components.

**Ionic info:**

```
Ionic:
   Ionic CLI : 5.4.2

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v10.15.3
   npm    : 6.4.1
   OS     : Linux 5.0
```

**Comment by DesignByOnyx** [comment]
I can confirm that this bug was introduced in v4.7.0 and that the problem does not exist in v4.6.2.

**Comment by GuilhermeBCC** [comment]
@liamdebeasi 

Would you know of any bugs in Stencil style injection?

Please, I'm stuck in version 4.6.2.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This issue was resolved during Ionic v5, but the issue was never closed out. Updating to the latest version of Ionic v5 causes this issue to no longer reproduce, so I am going to close this thread out. The main issue here appeared to be related to multiple versions of Ionic and Stencil being installed, but updating both packages to the latest version fixes the issue on my end.

If you encounter any additional problems, please open a new issue and include a code reproduction. Thank you!
