### ISSUE TITLE
bug: ion-router direction detection not in sync with stack

### ISSUE THREAD

**Issue by DavidWiesner** [ionic-team/ionic-framework#19565]
# Bug Report

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Current behavior:**
I have problem related to the router and the hardware/browser back button in a ionic-stencil app. The bug is also reproducible in your sample stencil conference app. 

1. clone and run (Ionic Stencil Conference App)[https://github.com/ionic-team/ionic-stencil-conference-app]
2. scroll schedule list click on one item
3. click the browser back button
4. back transition to the list (to the same list position)
5. click one item another time
6. click the browser back button 
7. **unexpected:** no back transition and page is "reloaded" to the top of the list 

Here are the console logs in debug mode for the steps:

1. `[ion-router] route changed ["schedule"]`
2. `[ion-router] URL pushed -> updating nav /schedule/session/11 forward`and `[ion-router] route changed (3) ["schedule", "session", "11"]`
3. `[ion-router] URL changed -> update nav ["schedule"] forward` **why "forward" direction?**
4. `[ion-router] route changed ["schedule"]`
5. `[ion-router] URL pushed -> updating nav /schedule/session/8 forward` and `[ion-router] route changed (3) ["schedule", "session", "8"]`
6. `[ion-router] URL changed -> update nav ["schedule"] root` **now its "root" direction. on the previous back button interaction it was "forward"**
7.  `[ion-router] route changed ["schedule"]`

In the logs you will see two problems:

1. the direction detection should not change when doing the same navigation steps
2. on both hardware/browser back button navigation the detected direction should be "back" 

**Expected behavior:**
- there should be always a back transition while navigating back in the history stack
- the direction detection should be "back" when navigate back in the history stack

**Steps to reproduce:**
1. `git clone https://github.com/ionic-team/ionic-stencil-conference-app.git`
2. `npm install`
3. `npm start`
4. Steps 2-7 from **Current behavior**

**Related code:**
- I think the problem is in the `Router` the `lastState` is only set in `Router::historyDirection`
https://github.com/ionic-team/ionic/blob/dea1c2635d20115c9906ccfa83c500c0d56468a6/core/src/components/router/router.tsx#L160-L179
- when the window history `popstate` event gets fired and handled in `Router::onPopState `

https://github.com/ionic-team/ionic/blob/dea1c2635d20115c9906ccfa83c500c0d56468a6/core/src/components/router/router.tsx#L72-L78

The `lastState` should be updated every time the navigation stack has changed. 

### Update:
May I did not understand the concept of direction detection at all, but the state seems not be a good indicator at all to get a direction from. Because the state counter is [always increased in `Router::setPath`](https://github.com/ionic-team/ionic/blob/dea1c2635d20115c9906ccfa83c500c0d56468a6/core/src/components/router/router.tsx#L267-L270), also if you going backward by e.g.: `ion-back-button`. 
 
**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)  : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : not installed
   @ionic/app-scripts : not installed

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS            : v10.15.3 (/usr/local/Cellar/node@10/10.15.3/bin/node)
   npm               : 6.4.1
```

**Comment by Scan0815** [comment]
Hi,
I have the same problem.

`
"@stencil/core": "1.8.1"
"@ionic/core": "^5.0.0-beta.2",
`

if i push the hardware back key the state and lastState have the same count in historyDirection function.

If i change the code of ion-router to:
  if (state > lastState) { 
     return ROUTER_INTENT_FORWARD; 
   } else if (state **<=** lastState) { 
     return ROUTER_INTENT_BACK; 
   } else { 
     return ROUTER_INTENT_NONE; 
   } 
It will work fine.

Hope this will help. 
Thx for Ionic / stencil i love it :)

**Comment by Scan0815** [comment]
https://github.com/ionic-team/ionic/pull/20383

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
