### ISSUE TITLE
bug:  ion-checkbox is blank only appear if checked (Only Tablet )

### ISSUE THREAD

**Issue by Cerik2005** [ionic-team/ionic-framework#19577]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

 ion-checkbox is blank only appear if checked (only in Tablet )
Android Version 6.0.1
SM-T705M
800 x 1280
![Screenshot_2019-10-08-10-43-24](https://user-images.githubusercontent.com/3900919/66401556-b8ca5480-e9b9-11e9-810b-84789d7f648b.png)

**Expected behavior:**

 ion-checkbox box must appear checked or not checked 

**Steps to reproduce:**

Create a ion-item with a checkbox at start with a label 

**Related code:**

```
<ion-item href="https://ionicframework.com/docs/">
<ion-checkbox slot="start" ></ion-checkbox>
<ion-label>Ionic Documentation</ion-label>
</ion-item>
```

**Other information:**

Android Version 6.0.1
SM-T705M
800 x 1280

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.1 (C:\Users\xxxx
![Screenshot_2019-10-08-10-43-24](https://user-images.githubusercontent.com/3900919/66401471-96d0d200-e9b9-11e9-974d-fd1daf5ac2a5.png)
\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.10.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.2
   OS     : Windows 10

```

**Comment by ChiSamurai** [comment]
Same here... it is somehow related to the Android System WebView version. We recognized this behavior on Android 6.0.1, WebView Version >= 75 (74.0.3729.157 is not affected by this problem).

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\xxx\v10.14.1\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.1, (and 9 other plugins)

System:

   NodeJS : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

At our app not only the unchecked Checkboxes are invisible but the ion-card elements have a grey background - see screenshot (don't mind the black rectangles).

![Screenshot_20191023-111102](https://user-images.githubusercontent.com/5371400/67377731-67f45780-f586-11e9-8674-bb36de5a1993.png)

**Comment by ChiSamurai** [comment]
@Cerik2005 : Doing some research I found that comment which seems like a fix for exactly this issue: https://github.com/ionic-team/ionic/pull/19602#issuecomment-545546892
I had no time yet to check it, but maybe it will help you?!

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
