### ISSUE TITLE
feat: update ion-input design to match new material design text fields

### ISSUE THREAD

**Issue by matheusgomes1** [ionic-team/ionic-framework#19619]
**Describe the Feature Request**
The Material Design has an excelent design for inputs. See https://material.io/components/text-fields/.

**Comment by adrm** [comment]
To be clear, Material Design no longer features the input design shipped in Ionic 4 and now it only allows filled or outlined fields. This support is important, and is becoming a sure-fire way to distinguish a native app from an Ionic hybrid app.

**Comment by adrm** [comment]
Hi! Is this update to material inputs addressed in ionic v5? Thanks!

**Comment by brendensoares** [comment]
If Material Design is already a mode in Ionic Framework, why wasn't this very common component completed to match the MD specs?

More importantly, when is it planned to be completed?

PS - Ionic Framework appeared to be such a productivity boost with all of its many MD/iOS web components, but this one `ion-input` component has caused me a lot of trouble trying to figure out a solution. I could do without action sheets, FABs, etc, but an input is critical.

**Comment by brendensoares** [comment]
https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield

this should be helpful in the mean time

**Comment by willmartindev** [comment]
These changes will be available in Framework v6 🎉
