### ISSUE TITLE
bug: input-shims doesn't work

### ISSUE THREAD

**Issue by ETXIN** [ionic-team/ionic-framework#19611]
# Bug Report

**Ionic version:**

[x] **4.9.x** / **4.10.x**

**Current behavior:**
'registerInput' will not execute. 
Document couldn't get the 'ionInputDidLoad' event.

**Expected behavior:**
ion-input dispatch event needs 'bubbles', or in document dispatch event like 'disconnectedCallback'.

**Related code:**
https://github.com/ionic-team/ionic/blob/f742dc5519a08871fc484802ed2b71625cfd01c6/core/src/utils/input-shims/input-shims.ts#L78-L80
https://github.com/ionic-team/ionic/blob/f742dc5519a08871fc484802ed2b71625cfd01c6/core/src/components/input/input.tsx#L221-L229
https://github.com/ionic-team/ionic/blob/f742dc5519a08871fc484802ed2b71625cfd01c6/core/src/components/input/input.tsx#L231-L237

**Other information:**
Why not use ``this.ionInputDidLoad.emit(this.el);`` and ``this.ionInputDidUnload.emit(this.el);`` ?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue? We've been seeing reports of this, but without a reproduction we are unable to fix this issue.

**Comment by liamdebeasi** [comment]
Hey there,

Are you still able to reproduce this using the latest version of Ionic? I am not able to reproduce this issue locally.
