### ISSUE TITLE
feat: decoupling datetime picker from ion-datetime input

### ISSUE THREAD

**Issue by jase88** [ionic-team/ionic-framework#19642]
# Feature Request

**Ionic version:**
[x] **4.x** 

**Describe the Feature Request**
Currently it is only possible to use a datetime picker with a ion-datetime input field. The generation of a datetime picker is binded to this component.

This feature request is about decoupling the logic from the ion-datetime component and move it to a separate controller, e.g. **ion-datetime-picker-controller**.

This would make it possible to open a datetime picker without a input element (currently only possible with a hidden DOM element). Another benefit of pulling out logic from this component is its size (~670 locs).

**Describe Preferred Solution**
- a new controller which can create datetime picker instances

**Describe Alternatives**
- alternatively expose methods to create datetime picker cleverly from ion-datetime input component

**Related Code**
pseudo code
```
const dateTimeController = document.querySelector('ion-datetime-picker-controller');
const picker = await dateTimeController.create({
value: new Date(),
buttons: [
  {
	text: 'Cancel',
	role: 'cancel'
  },
  {
	text: 'Confirm',
	handler: (value) => {
	  console.log(`Got Value ${value}`);
	}
  }
]
});
await picker.present();
```

**Additional Context**

**Comment by roman-rr** [comment]
@kerosin 
You can create ion-picker and fill it with dates. Isn't fit to your needs?

**Comment by kerosin** [comment]
@roman-rr
It is not about dates but about datetimes.
The current ion-datetime offers slots on the picker for days, months, years, hours, minutes, seconds, ampm etc depending on configuration.

**Comment by roman-rr** [comment]
@kerosin 
Check multi-column picker https://ionicframework.com/docs/api/picker
You can create slots with columns

**Comment by kerosin** [comment]
Yep, this is internally already done on the [ion-datetime](https://ionicframework.com/docs/api/datetime) component, see [here](https://github.com/ionic-team/ionic/blob/master/core/src/components/datetime/datetime.tsx#L339-L404)

This feature request is more about refactoring/exposing stuff that is already there to enable
generating datetime pickers (without a input field).

**Comment by liamdebeasi** [comment]
You are referring to being able to use ion-datetime inline like this, correct?

![IMG_6269](https://user-images.githubusercontent.com/2721089/66752108-a55a3600-ee5e-11e9-8be0-aec4878a8260.PNG)

**Comment by kerosin** [comment]
hm not necessary inline in a fieldset, but as picker/popup.

Imagine a alert dialog and after the user confirms this dialog a picker opens up to enter a datetime.

**Comment by roman-rr** [comment]
@kerosin i did solve it on this way: 

**Template**
```
<ion-datetime #datetimePicker (ionChange)="writeValue($event.detail.value)"></ion-datetime>
```
**SCSS**
```
ion-datetime {
    display: none;
}
```
**TS**
```
@ViewChild('datetimePicker', { read: ElementRef, static: false}) private pickerDate: ElementRef;
constructor() {}

openPicker() {
      this.pickerDate.nativeElement.click();
}

writeValue(value: any) { 
      console.log('Picked', value);
}
```

In other words - you click to hidden <ion-datetime> for call datepicker dialog.

**Comment by corysmc** [comment]
You can also hide the ion-datetime by adding a hidden attribute, then open it with:

```document.querySelector('ion-datetime').open()```

https://ionicframework.com/docs/api/datetime#methods

**Comment by nicobytes** [comment]
I think this issue is related: https://github.com/ionic-team/ionic-docs/issues/711

**Comment by nicobytes** [comment]
Hello!

It would be great use ion-picker like a component. Like this:

![Group 1](https://user-images.githubusercontent.com/7611944/77557777-855c8300-6e90-11ea-94c9-87c1efd9043f.png)

**Comment by indraraj26** [comment]
when are we getting this?

**Comment by LorenzStierlin** [comment]
Is this still ongoing? This is a knockout criterion for ionic to be honest... the current possibilites are far away from having a native look and feel especially for iOS

**Comment by liamdebeasi** [comment]
Hi everyone,

As part of our Ionic 6 release we revamped our `ion-datetime` component to be decoupled from the datetime input. This means that you can use the datetime component inline in your template, in a popover, in a modal, etc. This gives developers more flexibility with how to customize and present the datetime component.

I will note that the datetime picker in Ionic 6 uses the new calendar style and does not use the wheel picker style. We have an open feature request to add the wheel style in https://github.com/ionic-team/ionic-framework/issues/23981. We also have plans to revamp the `ion-picker` component so that it can be used inline just like the datetime component. I do not have a timeline on #23981 or the picker revamp, but the datetime revamp is available now in the Ionic 6 beta (see https://github.com/ionic-team/ionic-framework/blob/next/BETA.md to get started)

I am going to close this since the original issue has been resolved in the Ionic 6 beta. Thank you!
