### ISSUE TITLE
feat: Add ability to override platform detection methods 

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-framework#19737]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

The platform detection methods Ionic provides cover most use cases; however, it is not going to be possible for us to reasonably detect 100% of all devices correctly. This is particularly true for off brand Android devices that do not conform to a standard when it comes to identifying themselves on the web.

It would be good for us to allow users to override our own methods with their custom methods in case they need to handle those specific edge cases in their apps.

**Describe Preferred Solution**

The easiest way to do this is to let developers customize the `PLATFORMS_MAP` object: https://github.com/ionic-team/ionic/blob/master/core/src/utils/platform.ts#L118

I see two options for doing this:

1. Expose a function (tentatively) called `setPlatformDetection(platform: Platform, callback: any)`. This function will allow users to provide a platform and a detection function. Usage is as follows:

```javascript
import { setPlatformDetection } from '@ionic/core';

const customAndroidFunction = (win: Window) => {
  return window.someExample === true;
}

setPlatformDetection('android', customAndroidFunction);
```
(Note: The `any` type will be replaced with the appropriate function type once that is determined)

2. Opt for a config approach where developers specify this on app start. Ionic Angular usage is as follows:

```javascript
...

IonicModule.forRoot({
  'platformDetection': {
    'android': customAndroidFunction
  }
});

...
```
After discussing with the team, I am leaning more towards option 2. I can see things getting a bit messy if users override the platform detection using option 1 _after_ the app has already been initialized. 

**Additional Context**

We might also want to consider exposing the `testUserAgent` and `matchMedia` functions that Ionic uses internally. I could see those being helpful when customizing the platform detection functions.

**Comment by willmartindev** [comment]
This feature has been added and will be available in the next beta release of Ionic Framework v6. 🥳
