### ISSUE TITLE
bug: iOS background scrolls when action-sheet is present

### ISSUE THREAD

**Issue by omardoma** [ionic-team/ionic-framework#19746]
# Bug Report

**Ionic version:**
**4.10.3**

**Current behavior:**
On iOS, if an action sheet is presented and you try to swipe the page up or down from exactly the sheet's visible area, the backgrounded content scrolls and doesn't respect the overlay backdrop.

**Expected behavior:**
Background shouldn't scroll if an action sheet is present.

**Steps to reproduce:**

![Screen Recording 2019-10-24 at 7 49 49 PM](https://user-images.githubusercontent.com/25301162/67512272-b8f47080-f698-11e9-8c66-e994dec54c82.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.3
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 17 other plugins)

Utility:

   cordova-res : 0.8.0 
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   Android SDK Tools : 26.1.1 (/Users/omardoma/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/Cellar/node@10/10.16.3/bin/node)
   npm               : 6.12.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.1 Build version 11A1027
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I was able to reproduce this on iOS 12, but not on iOS 13. I believe the fix is here: https://github.com/ionic-team/ionic/blob/master/core/src/css/core.scss#L28-L31 but it needs some additional testing with `ion-modal`.

**Comment by omardoma** [comment]
I see, thanks for replying, its not a major blocker for me at the moment, will keep an eye on the changelog.

Best of luck!

**Comment by liamdebeasi** [comment]
Hey there,

With the release of Ionic 6 we no longer support iOS 12. This issue does not reproduce on iOS 13 or newer, so I recommend updating to the latest version of iOS. I am going to close this issue. Thanks for the report!
