### ISSUE TITLE
feat: enable ssr for react

### ISSUE THREAD

**Issue by IljaDaderko** [ionic-team/ionic-framework#19795]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I was playing with idea of replacing react-scripts with nextjs and one big blocker is usage of `window` in react project. There are 2 areas where `window` is undefined

1. in ionicons, I already submitted pr there to safeguard (https://github.com/ionic-team/ionicons/pull/735)
2. In this project, mainly around `history` and `location` and helper functions like `getPlatformsCore` and `isPlatformCore`

**Describe Preferred Solution**

Since ssr efforts are being made on angular side and @ionic/core I think we should also unblock this for react projects? I think almost all `history` and `location` related usage of window can be replaced to not return / do anything if window is undefined, but I am not sure how to handle platform check code coming from core, so I opened this issue to start a discussion, I don't mind working on this if someone can help me in this area.

**Related Code**

- [ ] https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/index.ts#L52
- [ ] https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/navigation/IonBackButton.tsx#L25
- [ ] https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/utils/index.tsx#L21
- [ ] https://github.com/ionic-team/ionic/blob/master/packages/react/src/components/utils/index.tsx#L25
- [ ] https://github.com/ionic-team/ionic/blob/master/packages/react/src/contexts/NavContext.ts#L20
- [ ] https://github.com/ionic-team/ionic/blob/master/packages/react/src/contexts/NavContext.ts#L22
- [ ] https://github.com/ionic-team/ionic/blob/master/packages/react/src/contexts/NavContext.ts#L25
- [ ] ? https://github.com/ionic-team/ionic/blob/master/packages/react/src/globals.ts#L1

**Comment by wis** [comment]
I think your links are outdated because they're not permalinks, was you first link to this line line? (permalink):
https://github.com/ionic-team/ionic/blob/b5310effe3f9b47459f22221da1853a55dbb0279/packages/react/src/components/index.ts#L35
this function call and function call in the line under it  (`loader.defineCustomElements(window);`)
cause next js ssr to fail, so I commented them and got next js ssr to work.

**Comment by ianldgs** [comment]
I'm doing some research around Stencil and SSR and the obvious place to look at was ionic. Besides the unguarded usages of `window`, wouldn't SSR render just the `<web-component>` tag then, when hydrated, wouldn't react error out because the final is different from the server?
