### ISSUE TITLE
bug: use 'npm run build' to build ionic/core, but failed

### ISSUE THREAD

**Issue by rensuiran** [ionic-team/ionic-framework#19794]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

```
Use 'npm run build' to build ionic/core, but get this:
[ ERROR ]  TypeError: Cannot read property 'tagName' of undefined at cmps.map.c
           (D:\ionic-master\core\node_modules\@stencil\core\dist\compiler\index.js:3867:21) at
           Array.map (<anonymous>) at createEntryModule
           (D:\ionic-master\core\node_modules\@stencil\core\dist\compiler\index.js:3867:10) at
           Array.map (<anonymous>) at generateEntryModules
           (D:\ionic-master\core\node_modules\@stencil\core\dist\compiler\index.js:3856:41) at build
           (D:\ionic-master\core\node_modules\@stencil\core\dist\compiler\index.js:15957:9)
```

**Expected behavior:**

**Steps to reproduce:**

1.Download ionic-master
2.npm install
3.Build for release (npm run build)

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:
   Ionic CLI : 5.4.4

Utility:
   cordova-res : not installed
   native-run  : 0.2.9

System:
   NodeJS : v12.4.0
   npm    : 6.12.1
   OS     : Windows 10
```

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you provide more details to reproduce? What directory are you running these commands in? The build for the core components would be in `ionic/core/` but if you're building at a top level you may need to run `npm i` in each package directory:

```
core
docs
angular
packages/react
packages/react-router
```

**Comment by rensuiran** [comment]
I'm running in the ``` ionic/core ``` directory.  I try to build at a top level, and run ```npm i``` in each package directory,  but still get the same result.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue? If so, can you please provide some more steps to reproduce?
