### ISSUE TITLE
bug: <ion-slides> with different slide heights

### ISSUE THREAD

**Issue by AOUNT** [ionic-team/ionic-framework#19811]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

A slider with different heights of slides will have its smaller slides filled with blank spaces at the bottom (when using ion-infinite-scroll)

**Expected behavior:**

Each slide should be at its exact height, not the height of the tallest one.

**Steps to reproduce:**

Create a slider with some slides of different height.

**Related code:**

      <ion-segment (ionChange)="segmentChanged($event)" [(ngModel)]="segment" 
      color="warning">
      </ion-segment>

     <ion-slides [options]="slidesOpts" #slides (ionSlideDidChange)="slideChanged()">
     ...
     </ion-slides>

      // manage witching between tabs

      async segmentChanged() {
        await this.slider.slideTo(this.segment);
      }

      async slideChanged() {
        this.segment = await this.slider.getActiveIndex();
      }

```
insert short code snippets here
```

**Other information:**

this fix is no longer working because there is no _slides in V4
https://github.com/ionic-team/ionic/issues/10690

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by hellokingdom** [comment]
I too would like to know if ionic have plans for allowing variable content height in slides. As we can only use a single ion-content you can't replicate the common pattern in Android of tabs that can swipe and scroll at the same time.

**Comment by HarshitChhipa** [comment]
@hellokingdom and @AOUNT This can be done by using autoHeight: true, in options.
