### ISSUE TITLE
feat: Add ability to disable ion-select OK button when there is no selection

### ISSUE THREAD

**Issue by pjc2007** [ionic-team/ionic-framework#19826]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Disable select OK button until there is a selection.

Currently, when I invoke a select with no selected value, the user can still tap OK to close the 

**Describe Preferred Solution**
To have the OK button disabled when there is no current selection (either optional or by default), and then enable if the user does make a selection. If a selected value is passed, then  the OK button can be enabled from the start.

Would also like to be able to do this with an alert (via AlertController).

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. The team reviewed this request, and this is not something we are looking to add to Ionic at this time. Select overlays such as `ion-alert` are best used for simple selections given the small size of the dialog. As a result, any validation (such as ensuring a user has selected a value) should be handled outside of `ion-select`.

If you need any advanced validation/constraints we recommend using `ion-modal` to create a custom dialog: https://ionicframework.com/docs/api/modal#custom-dialogs This will allow you to fully customize the selection process as well as give users a larger dialog to select data from. Thank you!
