### ISSUE TITLE
bug: ion-searchbar looses autocapitalize after setFocus()

### ISSUE THREAD

**Issue by ejerskov** [ionic-team/ionic-framework#19827]
**Ionic version:**
[x] **4.x**

**Current behavior:**
When writing in the ion-searchbar the first time, the first letter is correctly capitalized. Afterwards when using setFocus() on the ion-searchbar the capitalization disappears and all letters are now lowercased.

**Expected behavior:**
Expects the input to have the first letter capitalized after using setFocus()

**Steps to reproduce:**

- Use ion-searchbar
- Submit from the input, clear it and then use setFocus()
- See that the first letter-capitalization has disappeared

```
this.searchbar.value = '';
this.searchbar.setFocus();
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.4
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 10 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : 0.2.9 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Catalina
   Xcode      : Xcode 11.1 Build version 11A1027

```

**Comment by ejerskov** [comment]
Bump?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
