### ISSUE TITLE
feat: configurable default icon for ion-item detail-icon via forRoot

### ISSUE THREAD

**Issue by pablomaurer** [ionic-team/ionic-framework#19906]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
A new config property to set the default icon for `detail-icon` on `<ion-item>`. Just as it works for setting the `default icon` for `<ion-menu-button>`

See -> https://ionicframework.com/docs/utilities/config

**Describe Preferred Solution**
Add new config property

**Comment by amandaesmith3** [comment]
Thanks for the issue, I wanted to circle back around to this. Currently, `ion-item` has a `detailIcon` prop that lets you customize this ([docs](https://ionicframework.com/docs/api/item#detailicon)). If setting this on every instance of `ion-item` is troublesome, you could create a custom component that wraps `ion-item` and sets the icon automatically by default. I know it's been a while, but does this resolve your concern? If not, could you give more details on your use case?
