### ISSUE TITLE
bug: Some devices ex: Nexus 5X not work but works in another model !!

### ISSUE THREAD

**Issue by incapdns** [ionic-team/ionic-framework#19922]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
Modal not working in Nexus 5X [Android < 8], example: Android 5.1.1 the modal is invisible, but when i use LDPlayer android 5.1.1 the APK works fine.
Example APK hosted: https://appetize.io/app/e9bq0wpkueg8k15cm2q9yan63w
Important note: If you "choose" android 8 or later (in Nexus 5x) the APK will works (example above appetize)
Example code: Any code that contains "modal".

Device tested: Nexus 5X
Version android: 4.4 - 7.1

**Expected behavior:**
Fix this problem

**Steps to reproduce:**
Create an project using "modal", emulate in Genymotion (or other emulator like Android Studio) the device Nexus 5X with this version of android: 4.4 or 7.1 (< 8)

**Related code:**
import { Component } from '@angular/core';
import { ModalController } from '@ionic/angular';
import { ModalPage } from '../modal/modal.page';

@Component({
  selector: 'modal-example',
  templateUrl: 'modal-example.html',
  styleUrls: ['./modal-example.css']
})
export class ModalExample {
  constructor(public modalController: ModalController) {

  }

  async presentModal() {
    const modal = await this.modalController.create({
      component: ModalPage
    });
    return await modal.present();
  }
}
-->

**Other information:**
In Developer Tools no errors is showed (only the modal is 100% invisible)

**Ionic info:**

Ionic:
   Ionic CLI                     : 5.4.5 (C:\Users\Lucas\AppData\Roaming\npm\nod
e_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic
-webview 4.1.3, (and 9 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.2.9

System:

   Android SDK Tools : 26.1.1 (C:\Users\Lucas\AppData\Local\Android)
   NodeJS            : v12.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.12.0
   OS                : Windows 7

**Comment by incapdns** [comment]
I'm this code to: "resolve" the problem:
.md .modal-wrapper, .wp .modal-wrapper {
   opacity: 1 !important;
}

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as we do not recommend using Android emulators to test your Ionic apps. The main reason is that many of these emulators come with very outdated versions of the webview that we no longer support with no way of updating them. This is less of an issue on emulators with Android 7+ as sometimes you can update the webview.

If this is still an issue on a physical Android device running Android 5.0+ please reply here and I will be happy to take another look. Thanks!
