### ISSUE TITLE
feat: Ion-range no option to customize the snap or range-tick class

### ISSUE THREAD

**Issue by ahaneef29** [ionic-team/ionic-framework#19934]
# Feature Request

**Ionic version:**
Ionic:

   Ionic CLI                     : 5.2.3 (C:\Users\User\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.4

System:

   Android SDK Tools : 26.1.1 (E:\AndroidSDK)
   NodeJS            : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.13.0
   OS                : Windows 10

**Describe the Feature Request**

I'm trying to achieve below design using ion-range, i cant able to modify range-tick class or snap.
is any other way to achieve ?

**Describe Preferred Solution**

**Additional Context**

![range](https://user-images.githubusercontent.com/10325179/69051538-183a6c00-0a1e-11ea-93c3-f5f7335eab8a.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this feature has been added to the Framework through the use of CSS Shadow Parts.

```css
ion-range::part(tick) {
  background: green;
}
```

See https://ionicframework.com/docs/api/range#css-shadow-parts for a full list of parts.
