### ISSUE TITLE
Accessibility ion-list

### ISSUE THREAD

**Issue by stevenbriscoeca** [ionic-team/ionic-framework#19939]
I was wondering if there was any reason not adding roles to the ion list here : 
https://ionicframework.com/docs/api/list
```
  <ion-list>
    <ion-item>
      <ion-label>Pokémon Yellow</ion-label>
    </ion-item>
    <ion-item>
      <ion-label>Mega Man X</ion-label>
    </ion-item>
    <ion-item>
      <ion-label>The Legend of Zelda</ion-label>
    </ion-item>
    <ion-item>
      <ion-label>Pac-Man</ion-label>
    </ion-item>
    <ion-item>
      <ion-label>Super Mario World</ion-label>
    </ion-item>
  </ion-list>
```

would become 
```
  <ion-list role="list">
    <ion-item role="listitem">
      <ion-label>Pokémon Yellow</ion-label>
    </ion-item>
    <ion-item role="listitem">
      <ion-label>Mega Man X</ion-label>
    </ion-item>
    <ion-item role="listitem">
      <ion-label>The Legend of Zelda</ion-label>
    </ion-item>
    <ion-item role="listitem">
      <ion-label>Pac-Man</ion-label>
    </ion-item>
    <ion-item role="listitem">
      <ion-label>Super Mario World</ion-label>
    </ion-item>
  </ion-list>
```

Because NVDA, JAWS and Voiceover will not understand those custom element and will not call them as a list.

**Comment by amymarsh4work** [comment]
Hi! I've contributed accessibility enhancements to Ionic in the past. This seems like a reasonable request, and sounds like you've done some testing and research on it already. I think I could help making the changes and submitting a pull request. LMK if you're interested.

**Comment by AccessToAll** [comment]
Hi,
With adding roles it work for JAWS and VoiceOver but still not working for talkBack.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25336, and a fix will be available in an upcoming release of Ionic Framework.
