### ISSUE TITLE
feat: Expose "form" attribute on inner button of ion-button

### ISSUE THREAD

**Issue by mattsteve** [ionic-team/ionic-framework#19959]
# Feature Request

**Ionic version:**
[x] 4.11.4

**Describe the Feature Request**
[HTML buttons have a form attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-form) that allows you to attach a button to a form that it is not a descendant of. This is useful, for example, if putting a submit button in an `ion-footer` where the form is inside the `ion-content` of a page.

**Describe Preferred Solution**
When specifying `<ion-button form="formId">`, the form attribute should be proxied to the button inside the `<ion-button>`'s shadow DOM.

**Describe Alternatives**
No sane alternatives are available in terms of appeasing form accessibility. Forms are required to have at least one submit input/button attached to them per WAI-ARIA 2 spec. Only real way around this is putting a submit button inside the form which is hidden by styles in such a way that it is still accessible to screen readers (tabbable). Then, proxy the click from the external button in the `<ion-footer>` to the hidden button inside the form. This is a big hack.

**Related Code**
`<ion-button form="formId">`

**Comment by Ananasr** [comment]
Any update on this feature please?

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this in favor of a newer issue for the same bug: https://github.com/ionic-team/ionic-framework/issues/21194
