### ISSUE TITLE
bug: tapping the label should activate the toggle action

### ISSUE THREAD

**Issue by ShaggyDude** [ionic-team/ionic-framework#19994]
I have seen this as a debated issue but there should be an option for this to work properly for all platforms. Apple is wrong on this one and It should be an option.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you describe your issue a bit more? I'm not quite sure what you are referring to.

**Comment by ShaggyDude** [comment]
On a web page you can wrap your input in a label or use the 'for' attribute to make your label txt clickable as well as clicking on the actual toggle in this case. To me a toggle is just another input and I expect to be able to click either the toggle itself OR the label txt. Codepen example here https://codepen.io/ShaggyDude/pen/QWwNNjy .

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/25570.
