### ISSUE TITLE
bug: angular, isAnimating() not defined on menu controller provider

### ISSUE THREAD

**Issue by nogamenofun98** [ionic-team/ionic-framework#20053]
**Ionic version:**
4.11.5

**Current behavior:**
when i import menu controller into a page component, i saw from the official ionic website listed got a method to detect is the menu animating or not. [Link to Doc](https://ionicframework.com/docs/api/menu-controller)

![image](https://user-images.githubusercontent.com/9070825/70522025-4c1b3400-1b7b-11ea-8ac5-b99147a5a564.png)

but i couldn't find the method when writing code, IDE prompting method not found during compile and browser also say method not found.

**Expected behavior:**
it should be able to find the method and return the menu is animating or not.

**Steps to reproduce:**
1) just import the menu controller in any module, and write like ```this.menu.isAnimating()```, it will show not found error

**Related code:**

**Ionic info:**

![image](https://user-images.githubusercontent.com/9070825/70522265-c21f9b00-1b7b-11ea-95c7-aa5880b76a48.png)

![image](https://user-images.githubusercontent.com/9070825/70522244-b8963300-1b7b-11ea-8baa-8a8ef38de93c.png)

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)             : 4.11.0 (C:\Users\oks\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 5 other plugins)

System:

   NodeJS : v10.15.3 (D:\Program\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by thetaPC** [comment]
Thanks for the issue! This has been resolved via PR https://github.com/ionic-team/ionic-framework/pull/28618 and will be available in an upcoming release of Ionic.
