### ISSUE TITLE
feat: Add Progress bar radius property

### ISSUE THREAD

**Issue by Fdom92** [ionic-team/ionic-framework#20062]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
The ion progress bar component is not easy to customize the border radius of the inner progress bar. We can easily modify the outer progress bar radius, but not the inner one.

**Describe Preferred Solution**
Be able to adjust the inner radius with CSS Properties

**Describe Alternatives**
Would be awesome to have a CSS Property like --inner-progress-radius to be able to adjust the radius easily

**Comment by pritamsoni-hsr** [comment]
@Fdom92 you can modify the source code after build and change transform:scaleX(e) to width:calc(e*100%), then you can add radius to .progress class

@liamdebeasi using above method when progress bar's width doesn't change very frequently, having an extra prop `dynamic` = true or false can specify whether to use scaleX or width

**Comment by kensodemann** [comment]
I am working with someone who is also having this issue. Interestingly, [this sample](https://github.com/kensodemann/issue-progress-bar) works fine on Chrome with standard light-dom styling but fails on Safari (and also on iOS then of course).
