### ISSUE TITLE
bug: Multiple clear icons in searchbar

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/ionic-framework#20083]
When using the ion-searchbar like so, `<ion-searchbar id="main-search" show-cancel-button="never" animated></ion-searchbar>`

There are 2 clear icons shown like this when typing into the searchbar like this:

![Screenshot from 2019-12-12 19-43-16](https://user-images.githubusercontent.com/1165845/70846694-e6cc8900-1e81-11ea-8d57-0db041addcd5.png)

After digging in, I understood that one of the icons was given by the browser because input type="search" is being used by ionic with inputmode as search thereby the browser gives a default clearing icon by itself.

In addition to this, Ionic also adds a clear icon when using searchbar making it 2 clear icons.

In any case, only one clear icon must be displayed. Any ideas on how I can go ahead with this?

Currently, I am solving this by explicitly setting the type as text like this:

```
<ion-searchbar id="main-search" inputmode="search" type="text" show-cancel-button="never" animated></ion-searchbar>
```

Thanks.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Which browser/version are you seeing this in?

**Comment by tvvignesh** [comment]
@liamdebeasi Google Chrome - Version 79.0.3945.79 (Official Build) (64-bit) when running in browser via capacitor.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Are you testing this on an Android device? If so, which model/version?

**Comment by tvvignesh** [comment]
@liamdebeasi I remember getting this error in the browser (when running serving the app directly from www folder). Don't remember if the same occured in the android device.

**Comment by liamdebeasi** [comment]
Which OS are you running? I'm running Chrome 79 on macOS and am not seeing this additional clear button.

**Comment by tvvignesh** [comment]
@liamdebeasi Ubuntu 19.10

Details:
```
Linux vignesh-predator 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
