### ISSUE TITLE
feat: declarative ion-modal (angular)

### ISSUE THREAD

**Issue by evgeniyefimov** [ionic-team/ionic-framework#20117]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

Make an option to open a modal window in template. It will allow devs to work with modals in a reactive way, Ionic for React is already working like this. Right now modal can be opened only programmatically with modal controller, it makes inconvenient to controlling modal state in reactive angular applications and reacting on data changes with OnPush. Also there is no way to pass template to the modal controller, only component's class.

**Describe Preferred Solution**

Would be great if we will be able to do things like this:
```
<ion-content>
      <ion-modal [isOpen]=showModal>
        <p>This is modal content</p>
        <ion-button (click)=setShowModal(false)>Close Modal</ion-button>
      </ion-modal>
      <ion-button (click)=setShowModal(true)>Show Modal</ion-button>
 </ion-content>
```

**Comment by mark-at-tusksoft** [comment]
Another case to make is similar to an issue we are currently experiencing.
[Related SO article](https://stackoverflow.com/questions/66991523/how-to-eagerly-load-ion-modal-in-angular-10)
Just to summarize, we want to pop a modal if the network goes down. If the network goes down and a modal hasn't been popped previously, the dependent scripts have not been loaded either.

While the current 'solution' works in non-production, the moment AOT tries to compile templates, the builder fails to resolve `ion-modal`.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23341, and you will be able to use modals declaratively in Ionic Framework v6. We will have updated docs that show you how to do this.
