### ISSUE TITLE
bug: Framework delegate is missing when using setRoot

### ISSUE THREAD

**Issue by tvvignesh** [ionic-team/ionic-framework#20114]
Hi. I am trying to clear the navigation stack like below but I get an error when doing so.

```
let navhome: any = document.querySelector('ion-nav');
  navhome.setRoot({
    component: 'my-component',
  });
```

**The error:**

```
Uncaught (in promise) Error: framework delegate is missing
    at r (p-a2dd86d8.js:1)
    at k.init (p-dncgxadq.entry.js:1)
    at E.runTransition (p-dncgxadq.entry.js:1)
    at E.nextTrns (p-dncgxadq.entry.js:1)
    at E.runTransition (p-dncgxadq.entry.js:1)
```

I am using IONIC 4 - Vanilla JS running in Capacitor.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this still an issue with the latest version of Ionic Framework? If so, please provide a repo with the code required to reproduce this issue.
