### ISSUE TITLE
side menu not working on android device(oppo) version 6.0.1 but working on chrome

### ISSUE THREAD

**Issue by kumarideepika** [ionic-team/ionic-framework#20120]
**Ionic version:**

[x] **4.x**

**I'm submitting a ...** 

[ ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```
Here is my code

<ion-app>
    <ion-split-pane>
        <ion-menu type="overlay">
          <ion-header style="background-color: #00afe8;">
            <div align="center">
              <img src="../assets/imgs/priority.svg" alt="">
            </div>
          </ion-header>
          <ion-content>
            <ion-list>
              <ion-menu-toggle auto-hide="false" *ngFor="let p of appPages">
                <ion-item [routerDirection]="'root'" [routerLink]="[p.url]">
                  <ion-icon style="color:#00afe8;" slot="start" [name]="p.icon"></ion-icon>
                  <ion-label>
                    {{p.title}}
                  </ion-label>
                </ion-item>
              </ion-menu-toggle>
            </ion-list>
          </ion-content>
        </ion-menu>
        <ion-router-outlet main></ion-router-outlet>
      </ion-split-pane>
</ion-app>

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```
please help me out

**Comment by kumarideepika** [comment]
<ion-app>
    <ion-split-pane>
        <ion-menu type="overlay">
          <ion-header style="background-color: #00afe8;">
            <div align="center">
              <img src="../assets/imgs/priority.svg" alt="">
            </div>
          </ion-header>
          <ion-content>
            <ion-list>
              <ion-menu-toggle auto-hide="false" *ngFor="let p of appPages">
                <ion-item [routerDirection]="'root'" [routerLink]="[p.url]">
                  <ion-icon style="color:#00afe8;" slot="start" [name]="p.icon"></ion-icon>
                  <ion-label>
                    {{p.title}}
                  </ion-label>
                </ion-item>
              </ion-menu-toggle>
            </ion-list>
          </ion-content>
        </ion-menu>
        <ion-router-outlet main></ion-router-outlet>
      </ion-split-pane>
</ion-app>

**Comment by indraraj26** [comment]
Hi,

Can you build this project : https://github.com/ionic-team/ionic-conference-app and run into your device.

**Comment by emaklakov** [comment]
Hi,

I build this project : https://github.com/ionic-team/ionic-conference-app and run my device. Android 5.1, Android 5.0, Android 4.4.4

When I click on the menu:
Error: Uncaught TypeError: undefined is not a functionion-menu_4-md.entry.js:140 push../node_modules/@ionic/core/dist/esm/ion-menu_4-md.entry.js.class_1.onBackdropClickcore-feeeff0d.js:1461 (anonymous function)

**Comment by kumarideepika** [comment]
Yes have the same issue

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
