### ISSUE TITLE
Tests: failing during `npm run test` with ECONNREFUSED

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-framework#20136]
The following command is failing `npm run test` on multiple tests in core due to this error:

```
 FAIL  src/components/infinite-scroll/test/basic/e2e.ts
  ● infinite-scroll: basic
    Failed: ErrorEvent {
      "error": [Error: connect ECONNREFUSED 127.0.0.1:58353],
      "message": "connect ECONNREFUSED 127.0.0.1:58353",
      "target": WebSocket {
```

It is possibly related to this issue: https://github.com/facebook/jest/issues/1939
Another related issue: https://github.com/puppeteer/puppeteer/issues/4958

And this may be needed too: https://github.com/ionic-team/stencil/issues/1726

Investigating the cause, but this is a blocker to our release process.

**Comment by brandyscarney** [comment]
Updating the versions for Stencil's jest & puppeteer dependencies seems to fix it, still testing more.

**Comment by brandyscarney** [comment]
This isn't fixed, we just commented it out: https://github.com/ionic-team/ionic-framework/blob/bcbe8cbb8de86a0310bc61b05c6a1bb54ce11df0/.scripts/common.js#L161-L165

**Comment by liamdebeasi** [comment]
Closing as we are migrating our E2E tests to use Playwright.
