### ISSUE TITLE
ionic react android error Map is not defined

### ISSUE THREAD

**Issue by eevin** [ionic-team/ionic-framework#20138]
ionic start myApp blank --type=react
ionic integrations enable capacitor
ionic build
ionic cap add android
ionic cap open android
use android studio build apk

ERROR: Map is not defined

the Logcat info:
01-03 09:43:15.455 18130-18179/io.ionic.starter D/OpenGLRenderer: Enabling debug mode 0
01-03 09:43:15.485 18130-18159/io.ionic.starter D/Capacitor: Handling local request: http://localhost/
01-03 09:43:15.555 18130-18130/io.ionic.starter I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1e77d56d time:16673361
01-03 09:43:15.555 18130-18130/io.ionic.starter W/Capacitor/Console: File: http://localhost/ - Line 977 - Msg: The key "viewport-fit" is not recognized and ignored.
01-03 09:43:15.555 18130-18159/io.ionic.starter D/Capacitor: Handling local request: http://localhost/static/css/10.5a97a233.chunk.css
01-03 09:43:15.565 18130-18159/io.ionic.starter D/Capacitor: Handling local request: http://localhost/static/css/main.437a334f.chunk.css
01-03 09:43:15.565 18130-18159/io.ionic.starter D/Capacitor: Handling local request: http://localhost/static/js/runtime-main.54e96c29.js
01-03 09:43:15.565 18130-18159/io.ionic.starter D/Capacitor: Handling local request: http://localhost/static/js/10.2e74d449.chunk.js
01-03 09:43:15.565 18130-18159/io.ionic.starter D/Capacitor: Handling local request: http://localhost/static/js/main.38de95d4.chunk.js
01-03 09:43:15.695 18130-18130/io.ionic.starter E/Capacitor/Console: File: http://localhost/ - Line 359 - Msg: ReferenceError: Map is not defined
01-03 09:43:15.695 18130-18188/io.ionic.starter E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught ReferenceError: Map is not defined","url":"http://localhost/static/js/10.2e74d449.chunk.js","line":1,"col":69,"errorObject":"{}"}}
01-03 09:43:15.705 18130-18130/io.ionic.starter E/Capacitor/Console: File: http://localhost/static/js/10.2e74d449.chunk.js - Line 1 - Msg: Uncaught ReferenceError: Map is not defined
01-03 09:43:15.705 18130-18159/io.ionic.starter D/Capacitor: Handling local request: http://localhost/assets/icon/favicon.png
01-03 09:43:15.705 18130-18173/io.ionic.starter I/chromium: [INFO:SkUtilsArm.cpp(179)] Device supports ARM NEON instructions!
01-03 09:43:18.415 18130-18130/io.ionic.starter D/Capacitor: SplashScreen was automatically hidden after the launch timeout. You should call `SplashScreen.hide()` as soon as your web app is loaded (or increase the timeout).Read more at https://capacitor.ionicframework.com/docs/apis/splash-screen/#hiding-the-splash-screen
01-03 09:43:18.735 18130-18130/io.ionic.starter E/ViewRootImpl: sendUserActionEvent() mView == null
01-03 09:44:02.925 18130-18130/io.ionic.starter D/Capacitor: App paused
01-03 09:44:03.015 18130-18130/io.ionic.starter D/Capacitor/Plugin/App: Firing change: true
01-03 09:44:03.015 18130-18130/io.ionic.starter V/Capacitor/Plugin/App: Notifying listeners for event appStateChange
01-03 09:44:03.015 18130-18130/io.ionic.starter D/Capacitor/Plugin/App: No listeners found for event appStateChange
01-03 09:44:03.025 18130-18130/io.ionic.starter E/Capacitor/Plugin/Browser: Error binding to custom tabs service

**Comment by liamdebeasi** [comment]
Thanks for the issue. What device are you testing this on?

**Comment by eevin** [comment]
@liamdebeasi Android 5.0, SM-N9009

**Comment by eevin** [comment]
index.tsx add 
import 'react-app-polyfill/ie9';
import 'react-app-polyfill/stable'

host-report-errors.js Error:
Unhandled promise rejection TypeError {stack: (...), message: "Cannot read property 'get' of undefined"}message: "Cannot read property 'get' of undefined"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: Error

**Comment by derekleiro** [comment]
Anything on this? It seems android 5.0 is not supported
