### ISSUE TITLE
bug: Ion-content prevents sliding of carousel

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [ionic-team/ionic-framework#20175]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
`ion-content` prevents sliding of carousel (embla-carousel). Sometimes, when scroll events from ion-content and the carousel library, cancel touchmove event similar as #15256 happens.
when said carousel is outside `ion-content`, it works correctly.
**Expected behavior:**

Carousel should slide

**Steps to reproduce:**

1. Open Blitz below. try to slide horizontally the first slider. Should not slide.
2. Open Blitz below. try to slide horizontally the second slider. Should slide.

**Related code:**

Here is a [blitz](https://stackblitz.com/edit/ionic-v4-angular-tabs-duwtuq) illustrating two carousels, one inside `ion-content`, and the other outside `ion-content`.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.10.0
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.11.3
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```

EDIT: Further reproductions of said library in typescript and angular projects. **Also Stackblitz template v4 is not stable**

- [Typescript Blitz Starter](https://stackblitz.com/edit/typescript-embla)

- [Angular 8 Blitz Starter](https://stackblitz.com/edit/angular-embla)

**Comment by cmer4** [comment]
For me both sliders (inside / outside) do not work actually (Chrome 78)

**Comment by tiagomsmagalhaes** [comment]
@cmer4 you have to make an edit in order to reload. Ionic v4 blitz it's not very stable. after a reload an error occurs in the console
