### ISSUE TITLE
feat: add border css variable to range component

### ISSUE THREAD

**Issue by guilhermeanselmo2** [ionic-team/ionic-framework#20183]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I'd like to have a border with different color than the filling in the range component. For both knobs, active bars and "inactive" bars

**Describe Preferred Solution**

For this, a border variable for the knob, active and inactive bar is needed

**Describe Alternatives**

**Related Code**

I believe just adding the borders variables and setting them to none should be enough

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. This functionality should now be possible through the use of CSS shadow parts on `ion-range`:

```css
ion-range::part(bar),
ion-range::part(bar-active),
ion-range::part(knob) {
  border: 2px solid red;
}
```

Here is a live example: https://codepen.io/liamdebeasi/pen/gOvGZXv

The range component also has other shadow parts that you may be interested in: https://ionicframework.com/docs/api/range#css-shadow-parts

I am going to close this. Thanks!
