### ISSUE TITLE
bug: ion-textarea autogrow shows scrollbars on zoom change

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic-framework#20186]
# Bug Report

**Ionic version:**
[x] **4.11.7**

**Current behavior:**
When I use ion-textarea as per documentation ie (within in an ion-item). If I have a long text value and autoGrow active. When I change the zoom in the browser scroll bars shows because  there is a slight text overflow. This happens with the **transform** method as well. Below is a gif
![autogrow](https://user-images.githubusercontent.com/10624315/72211642-eaa40780-3522-11ea-9466-20e63d710a9a.gif)
. 

**Expected behavior/Possible Solution:**
Autogrow to re-adjust for 'transform' and zoom method so scroll bars not shown. Or better yet is there a way to execute autogrow refresh manually  ie through view child? This way we can do it programatically as detecting zoom/transform within ion-textarea might be very difficult.

Note simply hiding textarea->scrollbars (eg overflow:hidden) is not a suitable option as in some examples when there is a wordwrap it will create new line on zoom and cutoff some of the text.

**Steps to reproduce:**
Insert code below on page. Then simple zoom in and out using browser.

```
<ion-content color="dark">
  <ion-card style="width: 300px;">
    <ion-item>
      <ion-label position="stacked">
        Autogrow Zoom Test
      </ion-label>
      <ion-textarea autoGrow value="this is a long sentence to demonstrate the autogrow issue when zoom is activated which is cause the scroll bar to show"></ion-textarea>
    </ion-item>
  </ion-card>
</ion-content>
```

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.3.21
   @angular/cli                  : 8.3.21
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, browser 5.0.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 9 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.9.1
   NodeJS     : v10.10.0 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Mojave
```

**Comment by Sukaato** [comment]
La scrollbar est visible dès que le textarea à l'attribut `autoGrow` , cela affecte aussi la taille par défaut. Le problème se produit uniquement quand le textarea est place dans un `ion-item`
![bug-autoGrow-textarea](https://user-images.githubusercontent.com/44368476/149672491-16900ac0-4096-4bc5-9482-c722ae84b4b4.PNG)


```
Ionic:

   Ionic CLI              : 6.17.1 (C:\Users\Sukaato\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/core ^6.0.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.10.0 (C:\Logiciels\nodeJS\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

```

**Comment by amandaesmith3** [comment]
Hi folks, I know it's been a while since this was first posted but I wanted to circle back around to it. I'm unable to reproduce the issue on the latest version of Ionic (6.0.7) using the code from the original post, but @Sukaato it looks like you were able to reproduce on Ionic 6. Could you check if the issue persists on the latest version, and if so, create a starter app replicating the issue and post a link here?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
