### ISSUE TITLE
bug: range does not work when document is rtl but component is forced to ltr

### ISSUE THREAD

**Issue by ashishgehlot** [ionic-team/ionic-framework#20201]
Hello Devs, 

I was trying to use ion-slider for RTL application but its not working as expected. In LTR mode its working fine. In RTL mode, Knob gets stick in right side and can not change by dragging also value change appears in reverse mode like Dragging from Right to left but animate from left to right.

Here I am adding Codepen project to where I reproduced this issue. Hope it will help you to understand issue. 
[https://codepen.io/ashishgehlot95/pen/RwNBbpr?editors=1010]

**Comment by brandyscarney** [comment]
Thanks for the issue! The codepen you added is using a very old version of Ionic, please make sure you're using latest, which is `4.11.8` at the time of this writing. Also, I believe you need to add the `dir` on the `html` element: https://codepen.io/brandyscarney/pen/gObjgzK?editors=1010

@abennouna could you confirm this?

**Comment by abennouna** [comment]
The range issue has been solved in a previous version of Ionic (4.0.2).

I understand that the pen demonstrates an issue when using the `dir=rtl` on the ion-range element itself.

As a matter of fact, the RTL fix involved checking the direction on the document itself, and does not account for other parent elements, or the slider itself.

So if this is a mixed-direction document, that may be an issue.

**Comment by ashishgehlot** [comment]
Yes, I am using mixed-direction. 

<html dir="rtl"> 

<ion-range min="1000" max="2000" mode="ios" step="100" pin="true" dir="ltr" snaps="true" ticks="true" color="secondary"></ion-range>

If I remove dir attribute from ion-range works fine but with attribute it breaks .

https://codepen.io/ashishgehlot95/pen/mdyajMd?editors=1010

**Comment by ashishgehlot** [comment]
Any update on this issue ?

**Comment by FahmiChaar** [comment]
Any option to force component direction to LTR when my app direction is RTL ?

**Comment by 3zzy** [comment]
Its still broken :(

**Comment by sean-perkins** [comment]
Hello everyone :wave: this has been fixed in #24597 and will be available in the next release of Ionic.
