### ISSUE TITLE
feat: make select change event detail interface generic

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-framework#20220]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**

It would be helpful if the `SelectChangeEventDetail` interface would be generic, so that the type of the `value` property can be typed.

**Describe Preferred Solution**

```ts
interface SelectChangeEventDetail<T = any> {
  value: T;
  // ...
}
```

```tsx
const onSelectValueChange = (e: CustomEvent<SelectChangeEventDetail<number[]>>) => 
  foo(e.detail.value); // <-- this is a number array now, instead of `any`

<ion-select onIonChange={onSelectValueChange} />
```

**Describe Alternatives**

🤷🏻‍♂️

**Additional Context**

I'm not actually aware what types of values the `<ion-select-option>` can be used with, but it definitely works with strings and numbers (and arrays of either if `multiple` is set).

**Edit:** According to the docs you can even have [objects as values](https://ionicframework.com/docs/api/select#objects-as-values) (nice!) which means this generic interface would be really helpful. I can make a PR once you agree that this is a good idea!

**Comment by brandyscarney** [comment]
Thank you for the issue! Sorry for the late reply. I think this is a good idea. We had something similar added here: https://github.com/ionic-team/ionic/pull/21393

**Comment by simonhaenisch** [comment]
@brandyscarney mind having a look at my PR? 😬

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/21514, and will be available in an upcoming release of Ionic Framework.
