### ISSUE TITLE
bug: Month Switch in ion-date time number of date not change in picker

### ISSUE THREAD

**Issue by RAJKUMAR26GITHUB** [ionic-team/ionic-framework#20250]
# Bug Report

**Ionic version:**

[x] **4.20**

**Current behavior:**
      Initially facing the issue in 4.12.0 then go google to find the solution many blogs are suggested to upgrade the ionic version 4.20 so i am update my ionic version 4.12.0 into 4.20. After that update same problem is occur. While switching from March to February, date column not changed and still showing upto 31.

**Expected behavior:**
      If I switch from March to February its needs show the date column 28 or 29 days based on the year.

**Steps to reproduce:**
    step-1:open the picker.
    step-2:Then switch month March to February
    step-3:see the date column changes not occur(Showing date more than 28)

**Related code:**

      <ion-datetime max="2050" displayFormat="{{appUtility.userDateTimePickerFormat}}"  pickerFormat="{{appUtility.userDateTimePickerFormat}}"></ion-datetime>

[Ionic App.zip](https://github.com/ionic-team/ionic/files/4090455/Ionic.App.zip)

insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this issue as it was resolved in Ionic Framework v4.2.0. The version numbers you mentioned refer to the version of the Ionic CLI, not Ionic Framework which is probably why you were still running into this issue. I recommend updating the latest version of Ionic Framework to receive this fix:

```
npm install @ionic/angular@latest
```
