### ISSUE TITLE
feat: Rail Navigation

### ISSUE THREAD

**Issue by seanaguinaga** [ionic-team/ionic-framework#20272]
# Feature Request

**Ionic version:**

[x] **4.x** 5+ 

Co-opting Google's notion of "ambient-computing", I think that Ionic should fill-out the tablet section of the mobile, tablet, desktop triangle with some touch-specific, but larger screen-focused UI elements - covering all of the various form-factors we have today.

If you view the video below, you can see how an app would ideally transition between these three form-factors. 

https://twitter.com/i/status/1220093364424470528

This rail component:

![EO6jEHuUwAIRkSx](https://user-images.githubusercontent.com/15254340/72999900-e2668a80-3db4-11ea-8d45-d47dbd746bbc.jpg)

Is something I think Ionic needs.

I know Apple still thinks that a blown-up phone UI with a persistent side-menu is sufficient for their tablets, but I don't agree.

Basing this component off of the tab-bar makes the most sense to me, but the side-menu would word as well.

**Any ideas on how we could add this to Ionic/should we?**

Flutter will supposedly be publishing guidelines on this very soon.

**Comment by wilk-polarny** [comment]
Looks like an extended collapsable master view (list) inside of a split view. It should be impossible to build something using available Ionic components as a base. based on the screen resolution you could introduce a second collapsed state in addition to the hidden one (hamburger) where you collapse down to the icons of the list components.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. This should already be possible with Ionic Framework using the split-pane and side-menu.

Here is an example: https://codepen.io/liamdebeasi/pen/QWwoNbZ

Note that I am using Ionic 5 in this example, but something similar should be possible already with Ionic 4. Would something like this fit your use case?

**Comment by seanaguinaga** [comment]
That looks great!

And this would only be available between screen sizes 576> and < 992? 

If we think about iPads and tablets, should the platform be detected and a rail shown instead of a plain-old list, as you would see on a desktop? Or does Ionic feel that split-pane, list on the left, detail on the right, is sufficient? 

I use  the usual split-pane on my current app and it's not very "touch-y" or "tablet-y". 

Building in a more adaptive split-pane with more variability and form-factory specific slots may be best going forward?

**Comment by brandyscarney** [comment]
I took Liam's Codepen and made some adjustments based on how Material Design puts the rail system under the header. There are some issues where the content isn't considering the header height, and the larger menu is sometimes not enabled at the same time. I think this would be something good for us to support in Ionic.

Here's my Codepen: https://codepen.io/brandyscarney/full/eYmXWVm

Editor View: https://codepen.io/brandyscarney/pen/eYmXWVm

**Comment by seanaguinaga** [comment]
That looks great! 

https://twitter.com/i/status/1220093364424470528 and https://material.io/design/material-studies/reply.html#layout are the goal.  (find section for grid system)

As a developer who uses Ionic and is an outsider to Ionic's inner workings this makes the most DX sense to me:

![image](https://user-images.githubusercontent.com/15254340/73138566-d1b64e80-4018-11ea-8a13-e7b1ba8b7f62.png)

Notice fictional component names.

If IonLayout was a plug and play, composable box and we could add things to it's edges (slots) like the IonTabList and IonTabButton, this would be very powerful. Obviously it's a lot of work, but I'd like to help if possible.

Prescribed UI elements are useful, but we also don't want every app to look the same and repositioning alone gives lots of cool permutations.

**Comment by seanaguinaga** [comment]
FYI: Flutter has got one:

https://pub.dev/packages/navigation_rail#-readme-tab-

https://rodydavis.github.io/navigation_rail/#/

**Comment by jchri853** [comment]
> I took Liam's Codepen and made some adjustments based on how Material Design puts the rail system under the header. There are some issues where the content isn't considering the header height, and the larger menu is sometimes not enabled at the same time. I think this would be something good for us to support in Ionic.
> 
> Here's my Codepen: https://codepen.io/brandyscarney/full/eYmXWVm
> 
> Editor View: https://codepen.io/brandyscarney/pen/eYmXWVm

@brandyscarney Thanks for making this Codepen! I am using the latest Ionic Angular (
5.3.2) and the rail menu doesn't appear in Safari, In fact if you run this codepen in Safari, it wont show either. Safari 14. Any ideas?

**Comment by seanaguinaga** [comment]
@jchri853 there are some issues with ionic in safari 14, not just this one! Not sure what is going on
