### ISSUE TITLE
bug: select on IonTabs results in undefined error

### ISSUE THREAD

**Issue by RHinderiks** [ionic-team/ionic-framework#20340]
[x] **5..0.0-rc.1**

**Current behavior:**
Calling select on a reference to IonTabs results in a undefined error

core.js:6014 ERROR TypeError: Cannot read property 'getActiveStackId' of undefined
    at IonTabs.select (ionic-angular.js:2754)
    at SafeSubscriber._next (tabs.page.ts:65)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at BehaviorSubject._subscribe (BehaviorSubject.js:14)
    at BehaviorSubject._trySubscribe (Observable.js:42)
    at BehaviorSubject._trySubscribe (Subject.js:81)
    at BehaviorSubject.subscribe (Observable.js:28)

**Expected behavior:**
No error being thrown

**Steps to reproduce:**
See example code

**Related code:**
```
@ViewChild('tabs', { static: true, read: IonTabs }) private tabsRef: IonTabs;

ngOnInit(){
    this.tabsRef.select(index);
}
```

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.0.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0-rc.1
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.3.23
   @angular/cli                  : 8.3.23
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 24 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.6

System:

   Android SDK Tools : 26.1.1 (/Users/rh/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.7.0 (/Users/rh/.nvm/versions/node/v12.7.0/bin/node)
   npm               : 6.10.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

**Comment by NikolaPeevski** [comment]
@RHinderiks can you  give a little more clarification about the issue, here is an example tab project that selects random tabs using the function you mentioned https://github.com/NikolaPeevski/tabby

**Comment by RHinderiks** [comment]
This is still an issue, running latest ionic, latest angular, latest typescript etc.

**Comment by Josutoral** [comment]
This is still an issue, running latest ionic, latest angular, latest typescript etc.

**Comment by liamdebeasi** [comment]
Hi everyone,

I'm not able to reproduce this issue, so it appears to have been resolved. If you are still running into problems selecting tabs, please open a new issue and include a reproduction. Thanks!
