### ISSUE TITLE
bug: checkbox state is toggled to opposite value

### ISSUE THREAD

**Issue by ConciseConstructs** [ionic-team/ionic-framework#20346]
# Bug Report

**Ionic version:**
@ionic-native/core": "5.0.0"

**Current behavior:**
When a page loads with ion-checkbox(s) rendered from an NgFor loop, on first attempt clicking the checkbox the state is not toggled to the opposite boolean value and the UI becomes out of sync displaying the opposite state of the checkbox.

**Expected behavior:**
When a page loads with checkboxes rendered from an NgFor loop, clicking the checkbox will toggle it's state to the opposite boolean value and display accordingly on the UI.

**Steps to reproduce:**
Code is below:

**Related code:**
HTML:
```
<ion-item *ngFor="let option of options">
      <ion-label>{{ option.name }}</ion-label>
      <ion-checkbox #checkboxReference 
          (click)="onCheckBoxClick(option, checkboxReference)" 
          [checked]="option.selected" >
      </ion-checkbox>
</ion-item>

```
TYPESCRIPT:
```
export class Whatever { 
  constructor() {
    this.options = [
      { id: 1, name: 'Option 1', selected: false },
      { id: 2, name: 'Option 2', selected: false },
      { id: 3, name: 'Option 3', selected: false },
      { id: 4, name: 'Option 4', selected: false }
    ] 
  }

  onCheckBoxClick(option, checkboxReference) {
    option.selected = !option.selected
    console.log('checkboxReference.checked:', checkboxReference.checked)
  }

}

```
**Other information:**
CURRENT WORKAROUND:
```
onCheckBoxClick(option, checkboxReference) {
    this.options = JSON.parse(JSON.stringify(this.options)) // Creates a new variable, not a reference
    option = this.options.find(optionItem => optionItem.id === option.id)
    option.selected = !option.selected
    console.log('checkboxReference.checked:', checkboxReference.checked)
  }

```
**Ionic info:**
Ionic:

   Ionic CLI                     : 5.4.14 (C:\Users\B_Dee\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.1.2
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 2.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10

**Comment by NikolaPeevski** [comment]
@ConciseConstructs A much simpler workaround ,as stated in the [docs](https://ionicframework.com/docs/api/checkbox) is to use `[(ngModel)]` and have something like the following:

Template:

`     
<ion-item *ngFor="let option of options; let i = index">
    <ion-label>{{ option.name }}</ion-label>
    <ion-checkbox #checkboxReference 
        [(ngModel)]="option.selected"
        (ionChange)="changeFunction($event)"
        (click)="onCheckBoxClick(i)"
         >
    </ion-checkbox>
  </ion-item>`

Component:

`
changeFunction(event){
    console.log(event);
    }
  
onCheckBoxClick(index) {
    console.log(this.options[index].selected === false);
    console.log(this.options);
  }`

ionChange will always return the accurate value under the details property and ngModel will correctly change the correct options entry's selected property.

**Comment by liamdebeasi** [comment]
Hi everyone,

We recently introduced a fix in the Ionic 7 beta that should resolve this issue. The problem here is that programmatically updating the checkbox causes `ionChange` to fire, which causes your code to toggle the state of the checkbox again. In Ionic 7, `ionChange` only fires as a result of user-generated actions. This means that programmatically updating the checkbox will no longer cause `ionChange` to fire, resolving this issue.

You can read more about the Ionic 7 beta here: https://ionic.io/blog/announcing-the-ionic-7-beta
We have a guide for updating to the Ionic 7 beta on our docs: https://ionicframework.com/docs/v7/updating/7-0

The work to resolve this has been completed, so I am going to close this. Let me know if there are any questions. Thanks!
