### ISSUE TITLE
[Animations] feat: expand ways of doing CSS-oriented animations

### ISSUE THREAD

**Issue by marksyzm** [ionic-team/ionic-framework#20394]
# Feature Request

Will this support animation of props both on built-in and custom DOM elements? I will need things like `element.scrollLeft` alterations in order for this to compete with GSAP. GSAP uses CSS as a secondary animation part that plugs into the library. Otherwise this is great of course for animating DOM elements. I understand this is a request that is outside of the CSS spec but I wonder how this might be crossed over.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Can you provide an example of what you are trying to do?

**Comment by liamdebeasi** [comment]
I took a closer look at this. I think doing smooth scrolling is better handled by native browser APIs than by an animation library. For simple use cases, CSS `scroll-behavior: smooth` should be fine. If you need a JS-based approach, you can use `window.scroll` or `window.scrollBy`. 

See https://css-tricks.com/snippets/jquery/smooth-scrolling/ for more information. There is also a polyfill for browsers that don't support smooth scrolling natively.

Does this work for your usecase?

**Comment by marksyzm** [comment]
It’s not just for this use case; it’s really for any object’s value at all. For example, a video player’s volume control or the number of elements added to a page at what rate via a Bézier curve. It’s worth a look at what GSAP is structured like as it’s not just CSS oriented.

**Comment by marksyzm** [comment]
You’ll see CSS is a plug-in for GSAP here: https://greensock.com/gsap-plugins/

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Yeah, Ionic Animations is focused mostly on animating elements in the DOM, not really arbitrary properties. The one exception to that would be scroll-based animations, but you can already do that using `progressStart`, `progressStep`, and `progressEnd`.

I'd be interested in finding more ways to support CSS-based animations beyond just keyframes. I think there's a potential for some really cool animations here.

I'll keep this open as a feature request but change the title to focus more on the CSS aspect of this. Thanks for the suggestions! If you have any more related to this feel free to post follow ups.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is not something we are looking to implement at this time. Ionic Animations is focused on animating DOM elements via Web Animations/CSS Animations, so animating arbitrary properties does not really fit in the scope of this project.
