### ISSUE TITLE
Bug: (iOS 13) closing keyboard re-focuses input on click event on other elements than ion-button

### ISSUE THREAD

**Issue by NisStrom** [ionic-team/ionic-framework#20393]
**Ionic version:**
[x] **4.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
The bug only occurs on iOS 13 Devices. When clicking in an ion-input or ion-searchbar, the keyboard opens. After closing the keyboard programmtically or on tablets with the specific button, when the user clicks on an ionic element which handles a click even other than ion-button the input is re-focused again. In some cases the click event is then executed shortly after but in the case that the input is outside the router-provider where the click happens,
the keyboard might open again and the click event is not executed. 

**Expected behavior:**
Click events should be executed without re-focusing the previous input.

**Steps to reproduce:**
1. run the sample app on an iOS device.
2. Enter something into the searchbar and klick enter on the keyboard -> the keyboard gets hidden 
3. In the page that got loaded unter the searchbar click on the button -> Error: the search bar is getting focused again, the navigation to the second test page is not executed.
4. Klick on the button again -> The navigation works correctly and the second test page is displayed.

**Related code:**
Sample Application here: https://github.com/NisStrom/ios13

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am unable to run your sample application. I am getting the following error:

`error TS2305: Module '"/Users/liamdebeasi/Ionic/ios13/node_modules/@angular/compiler/compiler"' has no exported member 'JitEvaluator'.`

Can you please verify your app configuration?

**Comment by NisStrom** [comment]
it should build now. Had the wrong angular version in package.json.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I tested it out and it looks like the `Keyboard.hide` method does not properly blur the `ion-searchbar` which is why tapping anywhere seems to focus the searchbar again. 

I was not able to reproduce this on iOS 12, so it is possible that this is either a bug in the keyboard plugin, or a bug on iOS 13.

As an alternative, I would recommend using `event.target.blur()` in your `onInput` method instead. This will ensure that a) the keyboard is hidden and b) the searchbar is properly blurred.

**Comment by NisStrom** [comment]
The workaround works partially but the problem still exists when the user closes the keyboard manually (which is possible only on iPad).  And it happens not only for ion-searchbar but also for every ion-input.

**Comment by liamdebeasi** [comment]
Ok I'm going to take a closer look. It's possible that the keyboard plugin needs to be updated.
