### ISSUE TITLE
bug: ion-slides bound [pager] will not reappear when switching from `false` to `true`

### ISSUE THREAD

**Issue by wilk-polarny** [ionic-team/ionic-framework#20403]
# Bug Report

**Ionic version:**
[x] **4.11.3**

**Current behavior:**
When binding the `pager` directive if an `ion-slides` component to a variable, the pager will disappear if the variable changes to `false`, but not reappear when the bound value changes to `true` again.

**Expected behavior:**
I should be able to enable and disable the page indicator programmatically and it should hide and reappear properly.

**Steps to reproduce:**
- Create an `<ion-slides>` with some slide elements and bind `[pager]="someVar"`.
- Set someVar to **`true`** by default
- Observe the **pager being visible**
- Change the bound value programmatically to **`false`**.
- Observe the pager **disappearing as expected**.
- Change the bound value programmatically to **`true`** again.
- Observe the pager **not re-appearing**, which to me is unexpected behaviour

**Related code:**

Based on the Ionic 4 Tab sample Stackblitz and the Ionic 4 conference app I have created the following example:
https://stackblitz.com/edit/ionic-v4-angular-tabs-hbeqta

**Other information:**
![ionicpager](https://user-images.githubusercontent.com/819238/73988691-ba922d80-4943-11ea-890a-a151a761b59c.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.15 (/Users/Wilk/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.9
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/Users/Wilk/.nvm/versions/node/v10.16.3/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504
```

**Comment by wilk-polarny** [comment]
Is the pager even supposed to be dynamically enabled and disabled?
I tried to call `update()` on the slides, but that did not help either. Neither did changing the pager var via `ViewChild` injection of the `<ion-slides>` component.

**Comment by liamdebeasi** [comment]
Yeah it does not seem like the inputs here are meant to be reactive. For now, what you could probably do is hide/show the pagination using `display: none`.

**Comment by wilk-polarny** [comment]
Thanks, I'll check whether a hack will do. The pager component is only a `<div>` with some swiperjs classes on it (depending on whether it is being shown or not). I'll try to to somehow obtain a valid elementref for the pager in Angular, which should to the trick together with setting the style via the Angular Renderer.

**Comment by mattsteve** [comment]
I was just about to log this bug.

**Comment by wilk-polarny** [comment]
Yea, just confirmed, a quick and dirty hack for Angular would be to get the `<div>` element by its css class `swiper-pagination` and to set its `display`style via Angulars `Renderer2` back and forth from `none` to `block`.

**Comment by mattsteve** [comment]
Actually, I found a pretty clean solution for Vue, just manipulate the component's key with the same logic that is used to change the "pager" attribute. This forces the entire component to be re-rendered each time pager is set to true or false.

Example:

```
<ion-slides :pager="pages.length > 1 ? true : false" :key="pages.length">
```

I don't know if there's an equivalent concept of Vue's "keys" in Angular 2+.

**Comment by wilk-polarny** [comment]
> This forces the entire component to be re-rendered each time pager is set to true or false.

Hmm, wouldn't redrawing/recreating the component be quite heavy on the performance? Especially of the slide content needs to be recreated (which is what I guess is happening). Also, won't you lose your current slide index?

**Comment by mattsteve** [comment]
@wilk-polarny I don't see any noticeable performance impacts. In my case, a framework-friendly solution is better than manual DOM manipulation to prevent bugs from future ionic/swiper updates.

As far as slide index goes, binding the current slide index to the component's model and passing it into the "initialSlide" attribute of the swiper fixes this.

**Comment by NikolaPeevski** [comment]
@liamdebeasi Still trying to understand how components and Stencil works exactly, you might have better understanding of how https://github.com/ionic-team/ionic/blob/master/core/src/components/slides/slides.tsx works. The issue, from what I can see is that the pagination gets created once the state goes from false to true but it is not properly populated.

Here it is an example when the initial state is true for pager:
![image](https://user-images.githubusercontent.com/14194863/74217566-7073b980-4c6d-11ea-8382-3fa064bc3a7b.png)

And here it is when it goes to false and back to true:
![image](https://user-images.githubusercontent.com/14194863/74217593-808b9900-4c6d-11ea-922c-e1b60f5cfb5f.png)

It  seems it either doesn't link properly to swiper or the saved state in 'paginationEl' is not set for the children/ not set at all. I didn't see that it gets assigned anywhere in the slides.tsx file, but then again I am still learning how these things work exactly.

**Comment by wilk-polarny** [comment]
Any news? Are there plans to make the pagination dynamic/reactive? Just checking by :)

**Comment by elvisgraho** [comment]
The issue is still relevant for me (Angular)

**Comment by HillaryBautista** [comment]
In NikolaPeevski's problem, initializing the variable slideOptions in ionViewWillEnter work for me

**Comment by srinivasmerugu** [comment]
The actual problem stated by @wilk-polarny is still present for me as well . Could you please accept this bug.

**Comment by wilk-polarny** [comment]
@srinivasmerugu , you can work around this by directly manipulating the visibility (CSS) of the DOM element. It's less of an ionic bug but more of a feature request for the underlying SwiperJS - I guess the Ionic team can make that thing reactive, though.
