### ISSUE TITLE
bug: Ionic 5 / Angular 9: ion-item-option needs to be clicked twice

### ISSUE THREAD

**Issue by NePheus** [ionic-team/ionic-framework#20502]
Please see the referred ticket for more information, that got unfortunately closed without a solution.

This issue still exists. Im not 100% sure, but I think its only occuring in Chrome on Android. I cant reproduce it on my desktop browsers.

```
<ion-item-sliding>
    <ion-item>
        // ...
    </ion-item>
    <ion-item-options side="end">
        <ion-item-option (click)="clickFunc()">
            <ion-icon slot="icon-only" name="add"</ion-icon>
        </ion-item-option>
    </ion-item-options>
</ion-item-sliding>
```
#19564

**Comment by liamdebeasi** [comment]
Thanks for the issue. What device are you testing this on?

**Comment by NePheus** [comment]
The problem occurs in my case on a samsung galaxy s7 edge on android chrome 80.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Are you able to provide a repo with the code required to reproduce this issue? From what I remember with the issue you linked to, I was not able to reproduce the issue with a code snippet, so a full reproduction would be really helpful. Thanks!

**Comment by NePheus** [comment]
I just searched for the first stackblitz example and the problem occurs:
https://stackblitz.com/edit/ionic-v4-angular-tabs-2bfhcu?file=src%2Fapp%2Ftab1%2Ftab1.page.html

**Comment by edocbuhtig** [comment]
@NePheus wondering how did you manage to plugin in v9.x Angular core in ionic v5.0 when they say the starters [running angular core 8.x] are still waiting for that change - https://github.com/ionic-team/ionic/issues/20509

**Comment by kensodemann** [comment]
@edocbuhtig - you can upgrade Angular to v9 in your own project if you want. You just follow the standard Angular upgrade process. The starters are not updated yet because there are still some outstanding bugs with that, some on the Ionic end, some on the Angular end.

I, though, have updated several demo apps to Ionic v5 and NG 9 without issue. Whether or not you would have an issue all depends on what you are using and how.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I was able to reproduce this -- I will mark this as a bug.

**Comment by edocbuhtig** [comment]
@kensodemann - Thanks for the response, though, i have tried upgrading Ionic@angular successfully with this command `npm i @ionic/angular@latest --save` but, upgrading an individual projects Angular core from 8.1 to 9.x was a trouble using `ng update` within Ionic app, and i ran into cli issues one after another like `Your global Angular CLI version (9.0.2) is greater than your local
version (8.1.3). The local Angular CLI version is used.`. Not sure if there is single CLI command to update both, ionic@angular + Angular Core at one go.

**Comment by kensodemann** [comment]
@edocbuhtig - Please use our [forum](https://forum.ionicframework.com) or our [slack channel](https://ionicworldwide.herokuapp.com/) for further inquiry along these, as it is a support request not an issue with the Framework and is also off-topic for this issue.

I was only pointing out to you that you could indeed use NG 9 with your Ionic v5 app in case you wanted to help replicate or debug this issue.

**Comment by slaughac** [comment]
I'm having the same issue. Putting a (click) on the ion-item works fine in chrome when debugging. When running on iPhone or simulator I have to tap the item 3 times to fire the click event.

Ionic:

   Ionic CLI                     : 6.10.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.2
   @capacitor/core : 2.1.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina

**Comment by HriBB** [comment]
Having the same issue. Issue only appears in `Device Mode` when Chrome developer tools are open. In a desktop environment, it works every time.

```sh
$ ionic info

Ionic:

   Ionic CLI       : 6.12.1 (/home/bojan/.nvm/versions/node/v14.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.4.3 (/home/bojan/www/balvanija/node_modules/@ionic/react)

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2 (/home/bojan/www/balvanija/node_modules/@capacitor/core)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.0 (/home/bojan/.nvm/versions/node/v14.15.0/bin/node)
   npm    : 6.14.8
   OS     : Linux 5.8
```

**Comment by liamdebeasi** [comment]
Hi everyone,

Is anyone still able to reproduce this issue? I tested this on reproduction provided in https://github.com/ionic-team/ionic-framework/issues/20502#issuecomment-587323998 and am no longer able to reproduce the reported behavior.
