### ISSUE TITLE
bug: Selecting undefined in ion-select causes its value to become a string

### ISSUE THREAD

**Issue by lorenzodallavecchia** [ionic-team/ionic-framework#20722]
# Bug Report

**Ionic version:**

[x] **5.0.4**

**Current behavior:**

When the selected value is `undefined`, the underlying value becomes equal to the *label* of the selected option (a string!)

**Expected behavior:**

The value of the field should be `undefined`.

**Steps to reproduce:**

1. Visit the attached StackBlitz repro.
2. Select *Undefined option* in the Ionic select.

Note how the underlying value becomes the **string** `"Undefined option"`.

**Related code:**

https://stackblitz.com/edit/angular-b4nt6c

**Comment by indraraj26** [comment]
Hi @lorenzodallavecchia , 

if you change this in native it will give you same output as you are getting for ion-select. It is because of [ngValue] you are getting typeof undefined. We need look into ngValue what angular is doing behind the scene. 

```
<select [(ngModel)]="fieldValue">
  <option *ngFor="let opt of options" [value]="opt.value">
    {{ opt.label }}
  </option>
</select>
```

We need to alter something here @liamdebeasi 
```
var getOptionValue = function (el) {
    var value = el.value;
  // We need to change something here
    return (value === undefined)
        ? el.textContent || ''
        : value;
};
```

**Comment by lorenzodallavecchia** [comment]
Thanks for looking into it @indraraj26.

Yes, I am aware that `ngValue` does the trick, but that's exactly why I started using it in some layouts. A typical need for me is to include an "empty option" in the select box, and its reasonable value is `null` or `undefined`. AFAIK, `ngValue` was introduced precisely to deal with those nullish values.

**Comment by lorenzodallavecchia** [comment]
I read the documentation of the [directive behind ngValue](https://angular.io/api/forms/NgSelectOption). Basically it seems that it extends the capabilities of `select` to any object, beyond just selecting strings.

`ion-select` seems to already handle object types pretty well, They are also [mentioned in Ionic documentation](https://ionicframework.com/docs/api/select#object-value-references).
The problem seems to be only in the logic of the selection pop-up.
