### ISSUE TITLE
bug: ion-select shows the labels of selected nullish option

### ISSUE THREAD

**Issue by lorenzodallavecchia** [ionic-team/ionic-framework#20723]
# Bug Report

**Ionic version:**

[x] **5.0.4**

**Current behavior:**

When the underlying value of a `ion-select` is `null` or `undefined`, it shows only the placeholder. However, when an option having such a value is selected manually, its label is shown.

**Expected behavior:**

The select box should never show the label of `null` or `undefined` options, even when they are selected manually. This is also in line with the behavior of `mat-select` in Angular Material.

**Steps to reproduce:**

1. Visit the attached StackBlitz repro.
2. Use the *native* select box to select *Undefined option* or *Null option*. Note how the Ionic select keeps showing the placeholder.
3. In Ionic select, selec *Undefined option* or *Null option*. In both cases, the label stays visible after selecting.

**Related code:**

https://stackblitz.com/edit/angular-b4nt6c

**Comment by indraraj26** [comment]
This one is really strange, if i change [ngValue] of select native to [value], It select nothing at ion-select.

**Comment by lorenzodallavecchia** [comment]
@indraraj26 AFAICT `ngValue` is what enables using objects as options. Angular for some reason requires it, while `ion-select` (and Material) support objects out of the box using `value`.

Also this bug may be related to #20722 (a problem in the select pop-up). I was unsure about reporting them together so I opened two issues to avoid mixing things.
