### ISSUE TITLE
feat: IonReorder - Add custom index (order: X)

### ISSUE THREAD

**Issue by graphefruit** [ionic-team/ionic-framework#20731]
# Feature Request
Add the possibility for the coder to use ion-reorder as custom - ui possibility.

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
The IonReorder feature actualy supports to drag & drop elements and fires the new index.
It needs to be stored somewhere and the array needs to be sorted for this new indexes.

**Describe Preferred Solution**
The problem is, that if you have fixed HTML, and you want to give the user the possibility to define their own workflow, I needed to do many magic, and be taken back to: display flex and order principles.

Add the developer the possibility to 
```<ion-reorder order="1"></ion-reorder>```
```<ion-reorder [order]="myCustomValue"></ion-reorder>```

And Ionic supports this in behind while adding the flex params.
Also the values should be updated if the user drags and drops. 

**Related Code**
My actual related code to use this: 
```
<div style="display:flex; flex-direction: column;">

    <ion-item [style.order]="settings.somwherestored.order1">
      <ion-label floating>XYZ</ion-label>
      <ion-input type="text" [(ngModel)]="mymodel"></ion-input>
    </ion-item>
   <ion-item [style.order]="settings.somwherestored.order2">
      <ion-label floating>Another input</ion-label>
      <ion-input type="text" [(ngModel)]="myothermodel"></ion-input>
    </ion-item>
</div>
```

And in settings the user has the possibility to set the order:
```

      <ion-reorder-group (ionItemReorder)="reorder_brew($event)" disabled="false">
        <ion-item *ngFor="let index of brewOrders">
          <ion-label>
            {{index.label | translate}}
          </ion-label>
          <ion-reorder slot="end"></ion-reorder>
        </ion-item>
      </ion-reorder-group>

  public reorder_brew(ev: any) {

    // Slice item to the right index
    this.brewOrders.splice(ev.detail.to, 0, this.brewOrders.splice(ev.detail.from, 1)[0]);
   // Count up to the new indexes now.
    let count: number = 0;
    for (const order of this.brewOrders) {
      order.number = count;

      this.settings.brew_order[order.enum] = order.number;
      count++;
    }
    ev.detail.complete();
    // save somewhere in settings
    this.saveSettings();
  }
```
Happy to hear back from you.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide more details regarding this feature? A use case would be very helpful here.

**Comment by graphefruit** [comment]
Sure, my use case:
I wrote an app for coffee enthusiasts.
This app provides the possibility to track all kinds of parameters like brewing temperature, the coffee bean which is brewed, with which equipment etc.

Each user has a different workflow, some uses portafilters, some users hand brewers and therefore they need to change the worfklow (the sequence of their steps)
Some need to boil water first, then bloom the coffee and then start pouring.
In a portafilter, you grind first your coffee and then you have a pre infusion time and so on.

Therefore the customer needs a custom workflow for himself. 
Settings:
![image](https://user-images.githubusercontent.com/6260244/76319889-24557c80-62e0-11ea-98c3-5eefe494f7be.png)
The individual brew:
![image](https://user-images.githubusercontent.com/6260244/76319943-39caa680-62e0-11ea-8678-5a333d75b781.png)


The problem here is, that its fixed HTML-Inputs which are already inside the app, so I needed to change the CSS with flex and order attributes.
I hope I made it clearer to you, else please ask again :)

**Comment by graphefruit** [comment]
Any feedback for this request? You asked for a use case :)

**Comment by liamdebeasi** [comment]
Apologies for the delay in response. I am not sure I fully understand the issue you are running in to. What do you mean by "fixed HTML-inputs"?

When using `ion-reorder-group` you can provide your array to the `complete` method, and Ionic Framework will reorder the array for you, so you should not need to manually specify `order` or perform a `splice`.

**Comment by graphefruit** [comment]
Hi @liamdebeasi, thanks for your feedback.

Let me try to clearify that feature.

```
<ion-reorder-group (ionItemReorder)="doReorder($event)" disabled="false">
 <ion-item>
    <ion-label floating>Input 1</ion-label>
     <ion-input  ....></ion-input>
      <ion-reorder slot="start"></ion-reorder>
  </ion-item>
 <ion-item>
    <ion-label floating>Input 2</ion-label>
     <ion-input  ....></ion-input>
       <ion-reorder slot="start"></ion-reorder>
  </ion-item>
 <ion-item>
    <ion-label floating>Input 3</ion-label>
     <ion-input  ....></ion-input>
       <ion-reorder slot="start"></ion-reorder>
  </ion-item>
 <ion-item>
    <ion-label floating>Input 4</ion-label>
     <ion-input  ....></ion-input>
       <ion-reorder slot="start"></ion-reorder>
  </ion-item>

</ion-reorder-group>
```

This is a fixed html, in a ion-reorder group.
I'ld like now to have the possibility that the user changes this order maybe into:

- 4
- 2
- 1
- 3 

This is just temporary possible.
When he restarts the app, this sorting is not saved.
Because you cant render the inputs like an array with all of these events.
So after restarting the app, the sort order looks again like: 

- 1
- 2
- 3
- 4 

So therefore there should a solution to provide an own index, where the framework already sorts the items on start.
E.g. like: 
 ```
<ion-item index="4">
```

This is needed if you want to provide the possibility that a user can define his own input-workflow.
We're not talking about array-data which you can store and render with an `*ngFor`

I hope this use case is better understandable now.

Thanks in advance

**Comment by graphefruit** [comment]
Any news here?
Thanks

**Comment by graphefruit** [comment]
Bump: @liamdebeasi - Thanks for response

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay.

I did some investigation, and this behavior is already possible in Ionic. I made a code example that you can follow: https://codepen.io/liamdebeasi/pen/yLvNEKj

The important part here is that even though your data is not being rendered in an `ngFor`, it still needs to be represented in some kind of data structure. Without the data structure, it will be difficult to restore the item order when restarting the app.

The IonReorderGroup's `complete` method will automatically sort that data structure for you. From there, you will need to re-append the item elements in the newly sorted order.

Using the `order` CSS property is not recommended as it creates a disconnect between the visual presentation of content and the actual DOM order. This can negatively impact users who use assistive technologies such as screen readers as they will not have access to the correct reading order. For more information, please see https://developer.mozilla.org/en-US/docs/Web/CSS/order#accessibility_concerns.

I am going to close this. Thanks!

**Comment by graphefruit** [comment]
Hello @liamdebeasi 
Thanks for your effort and time here!

This solution for me is the half of the side.
For my use case I'd like to save this changes persistent which in your sample is not possible.
When app or website is refreshed or closed and reopend, the rearrange will be resetted.

This is mainly because I want the user to have an custom workflow which they can save on their side
