### ISSUE TITLE
bug: Router links not working after visiting URL containing tabs (ReactJS)

### ISSUE THREAD

**Issue by asaurer** [ionic-team/ionic-framework#20774]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

I have an overview page containing a list in which each item is using `routerLink` to point to a detail page. This detail page uses `IonTabs` to display tabs. Each tab displays a header toolbar with a back button. When clicking on the back button the overview page is shown again but all links except the one clicked before do not update content, the URL is changed though.

Not entirely sure if this is a bug or if I missed something in the setup. I used the same setup as the Conference App. It also could be related to ReactRouter.

**Expected behavior:**

After navigating back, all links should work and open the detail page again.

**Steps to reproduce:**

Open StackBlitz below > click on an event > click the back icon in the header > click on a different event > content does not update

**Related code:**
StackBlitz: https://stackblitz.com/edit/react-ts-udwyev

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.16 (~/.nvm/versions/node/v12.16.1/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 5.0.5

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (~/.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
```

**Comment by asaurer** [comment]
could this be related to #20753

**Comment by elylucas** [comment]
Hi @asaurer,

We have a dev release that should fix this issue. If you can, could you try to install it and let us know if it fixes the issue and if you run into any others? To install it run:

`npm i @ionic/react@5.3.0-dev.202006222125.df37029 @ionic/react-router@5.3.0-dev.202006222125.df37029`

If all goes good this should be available in the next Ionic release.

Thanks!
