### ISSUE TITLE
bug: ionic 5 refresher not working inside sidemenu (mobile MD mode)

### ISSUE THREAD

**Issue by michielcrabbe96** [ionic-team/ionic-framework#20832]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
 I have an `ion-refresher` implemented inside the `ion-content` of an `ion-menu`. When I'm in mobile MD mode the refresher doesn't appear. However when the screen is large enough that the `ion-split-pane` kicks in and the menu stays visible, then the `ion-refresher` works.

**Expected behavior:**
The `ion-refresher` to appear in mobile MD mode inside a sidemenu.

**Steps to reproduce:**
In a new ionic (sidemenu) project, put an `ion-refresher` inside the `ion-content` of an `ion-menu`. When you open the menu in a mobile MD context, try to swipe down to trigger the `ion-refresher`. You will see the `ion-refresher` doesn't appear.

**Related code:**
StackBlitz: [https://stackblitz.com/edit/ionic-v5-angular-sidemenu-refresher](https://stackblitz.com/edit/ionic-v5-angular-sidemenu-refresher) 

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.2.2 (/Users/michiel/.nvm/versions/node/v12.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.3.0) : 0.2.9

System:

   NodeJS : v12.13.0 (/Users/michiel/.nvm/versions/node/v12.13.0/bin/node)
   npm    : 6.14.2
   OS     : macOS Catalina
```

**Comment by telmaco** [comment]
Same here! I thought I was going crazy XD

**Comment by hamakiri** [comment]
Any news on this or a workaround?

**Comment by maocop** [comment]
the error cotinue help

**Comment by michielcrabbe96** [comment]
A possible workaround is to use the iOS refresher version.
`<ion-refresher slot="fixed" mode="ios" (ionRefresh)="refreshNotifications($event)">
      <ion-refresher-content></ion-refresher-content>
    </ion-refresher>`

You'll probably also wanna change the refreshingSpinner attribute on the refresher content.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22446, and a fix will be available in an upcoming release of Ionic Framework.
