### ISSUE TITLE
bug: ion-segment color binding is not working on md

### ISSUE THREAD

**Issue by jeroenklein** [ionic-team/ionic-framework#20831]
# Bug Report

**Ionic version:**
[x] **5.0.5**

**Current behavior:**
The `ion-segment` color binding in V5 on `md` is not working. The color is not changing and the displaying color is always `primary`. `ios` appears to work as expected.

**Expected behavior:**
With V4 the `ion-segment` color binding is working.

**Steps to reproduce:**
```
<ion-segment [color]="segment" [(ngModel)]="segment">
      <ion-segment-button value="danger">
        Danger
      </ion-segment-button>
      <ion-segment-button value="success">
        Success
      </ion-segment-button>
</ion-segment>
```

**Related code:**

https://stackblitz.com/edit/ionic-5-segment-color-binding-bug

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22405, and a fix will be available in an upcoming release of Ionic Framework.
