### ISSUE TITLE
bug: <ion-img> does not work in chrome v51-57

### ISSUE THREAD

**Issue by promotorov** [ionic-team/ionic-framework#20845]
# Bug Report

**Ionic version:**
Ionic version 5;

**Current behavior:**
ion-img  does not pass src prop to inner img and do not display image

**Expected behavior:**
display image

**Steps to reproduce:**
android emulator with chrome version 51

It happens because in chrome v.51-57 'isIntersecting' property was not implemented and the returned value was always 'undefined'.  

**How to fix**
replace current code
![image](https://user-images.githubusercontent.com/18381389/77257538-23c8c880-6c86-11ea-9a53-f19143cf2925.png) 
with
![image](https://user-images.githubusercontent.com/18381389/77257846-e36a4a00-6c87-11ea-9d7c-d871db3eefab.png)

**Comment by liamdebeasi** [comment]
Thanks for the report. The latest version of Ionic v6 supports Chrome 60+: https://ionicframework.com/docs/reference/browser-support#desktop-browsers.

I am going to close this since we no longer support Chrome v51-v57. Let me know if you have any questions.
