### ISSUE TITLE
bug: ion-datetime triggers ionChange on load

### ISSUE THREAD

**Issue by jeydsamy** [ionic-team/ionic-framework#20873]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

ion-datetime is triggering ionChange on page load

**Expected behavior:**

ion-datetime should trigger ionChange only after user changes the date/time

**Steps to reproduce:**

A sample application via GitHub
https://github.com/jeydsamy/ionic-datetime-sample
1. Clone project from git, npm install and run with ionic serve
2. Navigate between tabs, console will print "Date Changed!" even when it is not changed.

**Comment by jeydsamy** [comment]
@liamdebeasi Can I please get an answer on this?

**Comment by liamdebeasi** [comment]
Thanks for the issue. I was able to reproduce this behavior. Seems similar to https://github.com/ionic-team/ionic/issues/19204.

**Comment by jeya-duraisamy** [comment]
Yes, it is similar to #19204. Thanks for looking into it @liamdebeasi

**Comment by jeya-duraisamy** [comment]
@liamdebeasi Sorry if it is too soon, any idea when this might be fixed?

**Comment by sean-perkins** [comment]
Hello everyone, we have an open RFC that proposes a change to `ionChange` that would help alleviate this issue. 

Please take a moment to review and let us know your thoughts: https://github.com/ionic-team/ionic-framework/discussions/25532

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26083, and a fix will be available in an upcoming release of Ionic Framework. Please note that this fix requires a breaking change, so it is being targeted for the Ionic 7.0 release. Please feel free to continue testing the dev build, and let me know if you have any questions.
