### ISSUE TITLE
bug: VirtualScroll is resizing while out of view 

### ISSUE THREAD

**Issue by PatrykJankowski** [ionic-team/ionic-framework#20919]
**Ionic version:**
[x] **5.0.7**

**Current behavior:**
When changing tab or navigate to a different page than the one containing a virtual scroll component, virtual scroll is still running and specifically the part that listens for window resize events. When you resize the window in the other screen for some reason (open keyboard, change orientation, resize browser), that event is triggered in virtual scroll and tries to re-calculate the virtual scroll component. 

**Expected behavior:**
Virtual scroll shouldn't be rendered again.

**Steps to reproduce:**
- create virtual scroll with list of items in one tab
- go to another tab and open keyboard by clicking on a input
- close the keyboard and go to previous tab
- you can see that virtual scroll is rendering again and you can't see a few first items (and can't scroll up to see them)

**Other information:**
There was the same bug in the past in Ionic 3: https://github.com/ionic-team/ionic/pull/13143

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?

**Comment by PatrykJankowski** [comment]
Yes, I have just created an app to demonstrate this bug.
You can find it here: https://github.com/PatrykJankowski/IonicVirtualScrollBug.git

Run it on Android with Capacitor, go to second tab, click on search bar, close the keybord and go to the first tab again.

**Comment by 7freaks-otte** [comment]
I experience the same issue. It seems to me that the VirtualScroll cannot determine the correct item height while out of view as the first items are all translated to top 0px and this overlapping.

**Comment by 7freaks-otte** [comment]
As a temporary fix I use this:
```
ionViewWillEnter() {
    window.dispatchEvent(new Event('resize')); //temporary virtual scroll fix
}
```

**Comment by lincolnthree** [comment]
Also experiencing this issue here as well.

**Comment by pitamash** [comment]
Ensure before virtual-scroll is ion-list and if the list is inside other elements like ion-slide or card or div and not ion-content, add another ion content.


`<ion-content>
    <ion-card> 
         <ion-content>
            <ion-list>
               <ion-virtual-scroll>
                        
                </ion-virtual-scroll>
             </ion-list>
        </ion-content>`
   </ion-cord>
</ion-content>`

**Comment by pitamash** [comment]
Ensure before virtual-scroll is ion-list and if the list is inside other elements like ion-slide or card or div and not ion-content, add another ion content.


`<ion-content>
    <ion-card> 
         <ion-content>
            <ion-list>
               <ion-virtual-scroll>
                        
                </ion-virtual-scroll>
             </ion-list>
        </ion-content>
   </ion-cord>
</ion-content>`

**Comment by pitamash** [comment]
Ensure before virtual-scroll is ion-list and if the list is inside other elements like ion-slide or card or div and not ion-content, add another ion content. 
```
`<ion-content>
    <ion-card> 
         <ion-content>
            <ion-list>
               <ion-virtual-scroll>
                        
                </ion-virtual-scroll>
             </ion-list>
        </ion-content>
   </ion-cord>
</ion-content>`
```

**Comment by achakra21** [comment]
> window.dispatchEvent(new Event('resize'));

I checked it's working.. Thanks for your time

**Comment by GosuMania** [comment]
> ionViewWillEnter() {
>     window.dispatchEvent(new Event('resize')); //temporary virtual scroll fix
> }

i add it in my TS, but i have this error in console : 
`super-tab_3.entry.js:116 Uncaught TypeError: Cannot read property 'reindexTabs' of undefined
    at SuperTabsComponent.onWindowResize (super-tab_3.entry.js:116)
    at index-a34c410e.js:50
    at DealsListPage.ionViewWillEnter (deals-list.page.ts:115)
    at HTMLElement.handler (ionic-angular.js:2403)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28497)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    at invokeTask (zone-evergreen.js:1621)`
    
    Can u help me? i use Super-tab, is it the problem?

**Comment by 7freaks-otte** [comment]
This seems to be a bug in Supertab. Without further checking it seems to subscribe to the resize-event before the component is fully initialised. You just don‘t notice usually as it is very rarely that the component is initialised the very same moment the window is resized.

You can only try to move the scrollfix to `ionViewDidEnter` or delay it with setTimeout

**Comment by webberig** [comment]
> window.dispatchEvent(new Event('resize'));

This is not a very good solution because the list jumps back to the top. I have the same problem in my app when a user uses the native share feature. When you come back, the virtual-scroll content looks garbled.
Triggering a resize event makes the content repaint, but you are back to the top of the list.

**Comment by lincolnthree** [comment]
This also happens on initial render for me in some places. The list starts completely condensed at the top, then "figured it out" and extends down to full height.

**Comment by JoelAH** [comment]
Hi, any word on this?
