### ISSUE TITLE
feat: use infinite-scroll with grid or any custom container

### ISSUE THREAD

**Issue by Rehan1579** [ionic-team/ionic-framework#20981]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Currently, i'm working on a client's project where i need to use `infinite-scroll` but i'm unable to do so. I have a page where i got upper section 30% filled with filter controls (like search, sort etc) and remaining 70% page contains the grid. I cannot let my page scroll as i need full view, therefore i need `infinite-scroll` with grid, but it seems to work only with page. 

It would be great to have this thing done.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. What you described should already be possible with `ion-infinite-scroll`. If it is not working, it might be a bug in `ion-infinite-scroll`. Can you provide a repo with the code required to reproduce thie issue?

**Comment by Rehan1579** [comment]
> Thanks for the feature request. What you described should already be possible with `ion-infinite-scroll`. If it is not working, it might be a bug in `ion-infinite-scroll`. Can you provide a repo with the code required to reproduce this issue?

**Comment by Rehan1579** [comment]
oh, sorry, i accidentally closed the issue. i just created a project, please have a look, hope it helps.

[https://stackblitz.com/edit/ionic-v4-angular-tabs-dpk9gu?embed=1&file=src/app/tab1/tab1.page.html](url)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. The infinite scroll component looks to use the dimensions of `ion-content`, so you would likely need to move your card outside of `ion-content` in order to "block" 300px of the height. From there, you can remove the `<div style="height: calc(100% - 220px); overflow: auto;">` element.

Can you give that a try and let me know if it works?

**Comment by Rehan1579** [comment]
Yes, i worked the way you said and it solves the problem for now.

But shouldn't `ion-infinite-scroll` needs to be flexible enough, so that i don't need to put everything outside the `ion-content` except for my `infinite-scroll` ?

I mean, `ion-content` suppose to contain everything except for `ion-header` and `ion-footer` and that's how its in DOC, Isn't it ?

**Comment by liamdebeasi** [comment]
Yeah it should probably let you provide a custom reference element rather than assuming you are using `ion-content`. I will mark this as a feature request.

**Comment by Rehan1579** [comment]
I was also working with `ion-virtual-scroll` and found it had the same problem like `infinite-scroll`.
Should i also provide a repo for this too, or create a new issue ?

**Comment by liamdebeasi** [comment]
Hey there,

We added support to Ionic that lets you use `ion-infinite-scroll` in any scrollable content through the use of the `ion-content-scroll-host` class. The intended usage here is with virtual scroll containers, but you can use it in any scrollable container.

We have usage docs here: https://ionicframework.com/docs/api/infinite-scroll#usage-with-virtual-scroll

In the StackBlitz you provided you would add the `ion-content-scroll-host` class to the div that is commented out, and then disable scrolling on the `ion-content` using `scrollY="false"`.
