### ISSUE TITLE
feat: add bottom drawer

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21039]
# Feature Request

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Describe the Feature Request**
Please add a PopUp Footer like on Facebook or Slack

**Describe Preferred Solution**
Creating a Component (for Angular, React, Vue and JS) with a Pop-up Footer (See image)

**Describe Alternatives**
No Alternative yet.

**Related Code**
[https://jsfiddle.net/yznuotav/](https://jsfiddle.net/yznuotav/) It only works on Mobile (Or DevTools with Simulation)

**Additional Context**
[
![image](https://user-images.githubusercontent.com/36629890/79254951-cd663880-7e85-11ea-8312-8ddc35531a26.png)
](url)

**Comment by roman-rr** [comment]
@BerkeAras 
I made especially for ionic applications, and do regular updates. 
https://github.com/roman-rr/cupertino-pane

Have also pull request with ion-drawer component which i guess will be merged if have many requests
#20408

**Comment by BerkeAras** [comment]
Oh my god, that looks so great! Thanks! You’ve got a GitHub Star!!!

**Comment by HansKrywaa** [comment]
Any Updates to this? I really really want this Feature and i'm not that happy with the existing cupertino-pane.

**Comment by BerkeAras** [comment]
No updates at the moment. Why dont you like it?

**Comment by HansKrywaa** [comment]
I wrote down some things here: https://github.com/roman-rr/cupertino-pane/issues/41

**Comment by roman-rr** [comment]
Thank you for issues @HansKrywaa
I will review your requests in plugin repo.

**Comment by BerkeAras** [comment]
With the release of iOS 14 at the WWDC bottom drawer are much more used.
Now it is in much more apps, or the homescreen.
I think, bottom drawers should be a part of ionic.

**Comment by HansKrywaa** [comment]
Milestone 😍💪🏼 @BerkeAras

**Comment by lincolnthree** [comment]
Wow @BerkeAras - This is impressive. Seriously I rarely see such a well-implemented/smooth animation with touch support. 

@liamdebeasi I'm sure you've thought of this already, but this could approach even be used to enhance the action-sheet such that it uses touch support to dismiss.

I known I don't get a vote in this, but this gets two of my votes.

**Comment by liamdebeasi** [comment]
Thanks! This is something we are actively working on.

**Comment by BerkeAras** [comment]
That is not my code. Thanks to @roman-rr for the great project

**Comment by EinfachHans** [comment]
@lincolnthree it's currently planned for Version `5.4.0`

**Comment by BerkeAras** [comment]
@liamdebeasi Is there an estimated date for the version 5.4.0?

**Comment by lincolnthree** [comment]
@BerkeAras That's like asking a PHD-candidate when they are going to be finished with their dissertation 🤣

**Comment by BerkeAras** [comment]
> @BerkeAras That's like asking a PHD-candidate when they are going to be finished with their dissertation 🤣 (Not to poke too much fun, I know we'd all like to know, but it's not always easy to answer those questions! Hehe)

😂

**Comment by EinfachHans** [comment]
@liamdebeasi If there is a Branch, where i can test and support this feature, would be great to support you with this!

**Comment by DwieDima** [comment]
> @liamdebeasi If there is a Branch, where i can test and support this feature, would be great to support you with this!

Yes there is [one.](https://github.com/ionic-team/ionic-framework/tree/feat-sheet-modal)

**Comment by BerkeAras** [comment]
@liamdebeasi why did the milestone changed to 5.5.0?

**Comment by EinfachHans** [comment]
@BerkeAras because 5.4.0 is already released (Vue Release) and it's not included^^

**Comment by BerkeAras** [comment]
> @BerkeAras because 5.4.0 is already released (Vue Release) and it's not included^^

Oh, okay, thanks!

**Comment by EinfachHans** [comment]
@liamdebeasi i just checked the feature branch and want to continue the work to help you. Is there a deeper Reason why this isn't a own Component? Think this will be good to devide the necessary sheet options from the default ones.

**Comment by EinfachHans** [comment]
Is this still planed for V6? 😊

**Comment by liamdebeasi** [comment]
Yes.

**Comment by BerkeAras** [comment]
Yeah, i fell into depression because this was not introduced with v6 🥲

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23828, and this will be available in an upcoming release of Ionic v6.

**Comment by EinfachHans** [comment]
Amazing! Will love to test 😊

**Comment by lincolnthree** [comment]
YESSSS!!!! Let's GOOOOOO!!!!!! :D :D :D 🎆

**Comment by leejustin** [comment]
AMAZING!!

**Comment by Nazirovich** [comment]
URAAAAA !!!! thank youuu 😍💪🏼
