### ISSUE TITLE
feat: allow to change min-width of ion-segment-button

### ISSUE THREAD

**Issue by slevy85** [ionic-team/ionic-framework#21105]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
I would like to change the min-width of a ion-segment-button, and now there is hard-coded value on .button-native (90px for md and 70px for ios) that prevents any changes from outside.

When I change min-width on ion-segment-button it only changes the width of the container, but `.button-native` stays larger, which causes the icon to be uncentered and also the ripple effect becomes wrong :
```
ion-segment-button {
    min-width: 48px;
}
```

**Describe Preferred Solution**
Adding variable `--min-width` to ion-segment-button and use it for `.button-native` would resolve this.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe your use case? The MD spec sets a fixed minimum width so text does not get cut off (same thing with iOS). If the buttons extend out of the visible area the `ion-segment` be set to `scrollable="true"`.

**Comment by cmaas** [comment]
> Thanks for the issue. Can you please describe your use case? The MD spec sets a fixed minimum width so text does not get cut off (same thing with iOS). If the buttons extend out of the visible area the `ion-segment` be set to `scrollable="true"`.

Same issue here. I have a row with segment buttons. They are basically single letters A B C D E F (more than 3). On a small screen (360x480 for example), it's impossible to have the segment buttons next to each other. Scrolling is just bad UI and I don't see why this shouldn't be configurable.

I added this to my `app.css`, but it seems to only make a small difference for the iOS theme:

```
ion-segment-button {
    min-width: auto !important;
}
```

Here is what it looks like on iOS:

<img width="341" alt="Bildschirmfoto 2020-04-28 um 12 36 22" src="https://user-images.githubusercontent.com/6094364/80477996-22f21900-894d-11ea-8ba2-93710a5953e4.png">

And this is Android:

<img width="383" alt="Bildschirmfoto 2020-04-28 um 12 36 07" src="https://user-images.githubusercontent.com/6094364/80478009-28e7fa00-894d-11ea-8fa9-0a8ea5101f5c.png">

IMHO, no reason to have this huge padding around the buttons.

Interesting tidbit: My code above used to work for the Android theme as well, but it doesn't anymore. Not sure which ionic/core version broke it.

**Comment by cmaas** [comment]
@liamdebeasi Culprit is this line:

https://github.com/ionic-team/ionic/blob/fa9ddc91bc9fefc2bb247cfe7511384f77335476/core/src/components/segment-button/segment-button.md.scss#L48

Hardcoded min-width for `.button-native` in md-style. No equivalent exists in the ios-stylesheet. No way to override this unfortunately. It'd be great if this could be changed, because this line effectively limits `ion-segment` to 3-4 items next to each other on smaller displays.

**Comment by renatonagliati** [comment]
Tip to decrease the ion-segment-button width and have an MD-like appearance (while this request is not implemented):

HTML:
` <ion-segment id="ion-segment-reduced" color="light" mode="ios" scrollable>
    <ion-segment-button value="1">
      <ion-icon class="ion-no-margin" color="primary" name="person-circle"></ion-icon>
      <ion-label class="ion-no-margin ion-text-wrap">Button 1</ion-label>
    </ion-segment-button>
  </ion-segment>`

SCSS:
`#ion-segment-reduced ion-segment-button {
    --padding-start: 0px !important;
    --padding-end: 0px !important;
    --border-radius: 0px !important;
    --indicator-box-shadow: none !important;
    --border-color: transparent !important;
}`

**Comment by leono286** [comment]
I agree on "scrolling is just bad UI" when you only have some icons and just 6 items to show. In my case scrolling is not required whatsoever. Any fix/workaround on this?

**Comment by SvenBudak** [comment]
Any news on this?

**Comment by Eraldo** [comment]
I am also interested in overwriting some default styles.
Is there a general issue for this, since https://github.com/ionic-team/ionic/issues/21490 has been closed down in favour of this issue?

**Comment by liamdebeasi** [comment]
Can everyone try the following dev build, and let me know if it resolves the issue?

Ionic Angular:
`npm i @ionic/angular@5.3.0-dev.202007101438.1156d5c`

Ionic React
`npm i @ionic/react@5.3.0-dev.202007101438.1156d5c`

Using this dev build, you should be able to set `min-width` directly on the host `ion-segment-button`:

```css
ion-segment-button {
  min-width: auto;
}
```

**Comment by geckse** [comment]
This indeed worked! Thank you @liamdebeasi! 🎉
Tested it for ionic/angular.

The "Feed" Segment is now shorter than the 90px default min-width by changing the ion-segment-button min-width to auto, as suggested. 
![image](https://user-images.githubusercontent.com/12199921/87227930-3afb0580-c39e-11ea-9ec7-80d815c55393.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/21722, and a fix will be available in an upcoming release of Ionic Framework.
