### ISSUE TITLE
feat: IonCheckbox property to NOT render full size cover button in IonItem

### ISSUE THREAD

**Issue by jamiechong** [ionic-team/ionic-framework#21169]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I'm struggling/fighting with how an IonCheckbox inside an IonItem renders an absolutely positioned, full size (100% w & h) `<button>` element within its `shadow-root`. I'm trying to combine the IonItem `button` and `detail` properties with an IonCheckbox in the `start` slot. But the checkbox is taking over the item. Furthermore, but kind of unrelated, if the IonCheckbox is `disabled={true}` then my entire IonItem looks disabled too. This automatic tight coupling is interfering with my ability to get the UX I want. Please give me the ability to turn this off. 

**Describe Preferred Solution**

There are 2 solutions: 
1. Provide a new property that lets me disable the automatic button overlay: 
```
<IonCheckbox disableCoverButton={true} />
```
2. Add a CSS variable that I can use to hide the button:
```
ion-checkbox {
  --cover-button-display: none
}
```

**Describe Alternatives**

There have been other issues related to how the IonCheckbox cover button interferes with other UI components inside an IonItem: #20521 #19590 #15850 #17832

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide your use case for this feature?

**Comment by jamiechong** [comment]
@liamdebeasi  Basically I want to have an `IonCheckbox` inside an `IonItem` and have it act independently of the item. If I disable the checkbox, I don't want my entire item disabled. And if I tap on the content within the item, I don't want it to toggle the checkbox. Their tight coupling is great by default, but I'd like the option to make the 2 components ignore each other. 
 
Perhaps it's just a matter of documentation to understand better how the 2 components relate to each other and the side effects they have on each other. But for me who's new to Ionic, the UX magic is unexpected to me (although convenient for most cases).

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with `ion-checkbox`. This issue is fixed when using that new syntax. We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new checkbox syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
