### ISSUE TITLE
feat: add infinite scroll start and end positions

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21185]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

i want horizontal ion infinite scroll to load next data in cards.

**Describe Preferred Solution**

Probably we need to add one wrap element ion-horizontal-scroll inside that there will be an ion-infinite-scroll

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by indraraj26** [comment]
any plans to add this in 6

**Comment by liamdebeasi** [comment]
Hi there,

There has not been much community support for this feature since it was opened, so we do not plan on implementing the requested feature at this time. I am going to close this, but let me know if you have any questions.
