### ISSUE TITLE
bug: back-button not displayed if the page is wrapped.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#21263]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
The `<ion-back-button>` is not displayed if the page is wrapped in a custom component. Maybe not a bug, but an unexpected behavior. We should find a solution.

**Expected behavior:**
The back-button and other page behaviors should work. Maybe it only works if there is a `ion-header` and `ion-content` close to the component inside of the router-outlet.

**Steps to reproduce:**
Just have an app with page router navigation. Nothing special build. 
But I created a wrapper for the pages for DRY reasons. 
I don't want the same code in every page. Esp. the 2-part header. (collapse-condense header).
Anyway... Here's some code:

**Related code:**

**page.component.html**

```html
<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title>{{ title }}</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">{{ title }}</ion-title>
    </ion-toolbar>
  </ion-header>

  <div id="container">
    <ng-content></ng-content>
  </div>
</ion-content>
```

**page.component.ts**

```ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-page',
  templateUrl: './page.component.html'
})
export class PageComponent {
  @Input() title = '';
}
```

**some.page.html**

```html
<app-page [title]="title">
  <div>My Page</div>
</app-page>
```

**some.page.ts**

```ts
import { Component} from '@angular/core';

@Component({
  selector: 'app-some-page',
  templateUrl: './some.page.html'
})
export class SomePage {
  title = 'My Page';
}
```

I've tested it. It works if I unwrap the `app-page`.
So I think it's a selector issue to the `ion-header` like `A > B`? but idk.
What's the logic of the back-button? When hide or show?
The alternative is that Ionic brings a build in page component. What do you think about?
Because a page always looks the same. Header and Body. Maybe with options to hide the header, etc. ...

No Stackblitz demo? Yes :( But I'm working on it. I can't promise it. How to create an Ionic 5 app in Stackblitz? I hope the code above is enough. Otherwise I append the code here as zip.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.8.0 (...\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.2

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide the reproduction as a GitHub repo and include the link to it here?

**Comment by infacto** [comment]
https://github.com/infacto/demo-page-back

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I was able to reproduce this issue.

As a temporary workaround you can put the following CSS in `global.scss`:

```css
.can-go-back ion-header ion-back-button {
  display: block;
}
```

Our code uses `.can-go-back > ion-header ion-back-button` which requires the ion-header to be a direct child of the element with `.can-go-back`. Since you are wrapping your page the ion-header is never a direct child of the element with `.can-go-back`.

**Comment by infacto** [comment]
As I suspected. Thanks. Another issue is the page height. Currently fixed by adding `display: contents` to the page component `:host`. Just for someone who is interested in this.
