### ISSUE TITLE
bug: IonTab fail to render after rendered the second IonTab and the page totally freez

### ISSUE THREAD

**Issue by gine** [ionic-team/ionic-framework#21336]
# Bug Report

**Ionic version:**
[x] @ionic/react  **5.1.0 and 5.1.1** 

I haven't tested other version.

**Current behavior:**

On mine application i have a main router that work with a left side menu and two router, one for each page where IonTab is present.

The application is redirected to the first page "event" where the IonTab and the IonPage is rendered. 

When i move to the other page "event2" by left side menu and then i return to the first page "event" by side menu the IonTab stuck with "event2" IonTab.

**Expected behavior:**
I aspect that the IonTab change every time i change page.

**Steps to reproduce:**

-  Go to stackblitz[1] you will see the page "event" with the correct IonTab
-  Click on menu icon and click on event2 item, you will see  the correct IonTab
-  Click on menu icon and click on event item, here you will see the "event2" IonTab and not the "event" IonTab

**Related code:**

[1] https://stackblitz.com/edit/react-ts-7tzn8l

**Ionic other info:**
- The page totally freez
- If you try to start directly to /event2 and then go to /event doesn't work too

**Ionic info:**
No error is present on debug and on compiler.

**Comment by elylucas** [comment]
Hi @gine 

We have a dev release that should fix this issue. If you can, could you try to install it and let us know if it fixes the issue and if you run into any others? To install it run:

`npm i @ionic/react@5.3.0-dev.202006222125.df37029 @ionic/react-router@5.3.0-dev.202006222125.df37029`

Also, you might need to update your Redirect's from `<Redirect from="..." to=".." />` to `<Route path="..." render={() => <Redirect to="..." />} />` as the Redirect tag by itself will only redirect the page once when used outside of a switch (and you IonRouterOutlet doesn't support switches).

If all goes good this should be available in the next Ionic release.

Thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am no longer able to reproduce this issue using the latest version of Ionic 6. I am going to close this. Please open a new issue if you run into any other problems. Thanks!
