### ISSUE TITLE
bug: ion-fab overlaps iPhone status bar

### ISSUE THREAD

**Issue by LekisS** [ionic-team/ionic-framework#21346]
# Bug Report

**Ionic version:**

**5.1.1**

**Current behavior:**

When I put an `ion-fab` with `slot="fixed"`, the FAB icons overlap the iOS status bar.

**Expected behavior:**

The FAB icons should be positioned lower to avoid overlapping the iOS status bar.

**Steps to reproduce:**

- Create a blank page with `ion-content`
- Put a `ion-fab` button directly in it with `slot="fixed"`
- Build on iOS 13.4.x (reproduced on iPhone 6S, iPhone X, iPhone 11)

**Related code:**

```
<ion-content has-bouncing="false">
  <ion-fab vertical="top" horizontal="start" slot="fixed">
    <ion-menu-button>
      <ion-fab-button color="secondary" size="small">
          <img src="../../assets/icons/menu.svg">
        </ion-fab-button>
    </ion-menu-button>
  </ion-fab>
  <ion-fab vertical="top" horizontal="end" slot="fixed">
    <ion-fab-button size="small">
      <img src="../../assets/icons/filter.svg">
    </ion-fab-button>
  </ion-fab>
  </ion-fab>
</ion-content>
```

**Other information:**

Screenshot on an iPhone 6S with iOS 13.4.1 :

![bug](https://user-images.githubusercontent.com/28733/82470553-d02bfd00-9ac5-11ea-8f2a-28318e11b236.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.9.2 (/Users/tom/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.13.1
   native-run                             : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/tom/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.20.1 (/Users/tom/.nvm/versions/node/v10.20.1/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.4.1 Build version 11E503a
```

**Comment by elvisgraho** [comment]
Did you use css property "zoom" or "transform scale" on the button?

**Comment by LekisS** [comment]
No 😞 should I?

**Comment by elvisgraho** [comment]
> No 😞 should I?

No

**Comment by liamdebeasi** [comment]
Hi everyone,

We do not automatically apply safe area padding to the FAB because we cannot always accurately detect when the safe area is needed/desired. However, we recently added documentation that shows how to have the FAB account for the status bar and other safe area padding: https://ionicframework.com/docs/api/fab#safe-area

I am going to close this, but let me know if there are any questions.
