### ISSUE TITLE
bug: Collapsible ion-titles disappear from ion-header Toolbar

### ISSUE THREAD

**Issue by roccosiffredi** [ionic-team/ionic-framework#21420]
# Bug Report

**Ionic version:**
[x] **5.1.0**

**Current behavior:**
Large ion-titles nested in a collapsible ion-header (such as the example from the ion-toolbar ionic documentation) suddenly disappear after navigating to a sub-page and coming back from that page, leaving only the toolbar, slot=start buttons, and slot=end buttons.

**Expected behavior:**
Large ion-titles nested in a toolbar from a collapsible ion-header should still be visible even after navigating to another page and coming back from that page.

**Steps to reproduce:**
Set a collapsible header with a toolbar in a tab page following ionic documentation at "https://ionicframework.com/docs/api/toolbar" and the source code at "https://github.com/ionic-team/ionic-docs/blob/master/src/demos/api/toolbar/index.html".
Place a button-type div or ion-item content in the said page.
Build App via Capacitor with ```ionic cap open android``` to Android Studio.
Navigate to a sub-page and navigate back to parent page. 
Large ion-titles from all tab-bar pages are not visible anymore.

**Related code:**

A sample application via GitHub:
https://github.com/roccosiffredi/Large_ion-icon_Bug

**Sample code:**

```
<ion-header mode=ios [translucent]="true">
  <ion-toolbar>
    <ion-title>
      Tab 1
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header mode=ios collapse="condense">
    <ion-toolbar>
      <ion-title size="large">Tab 1</ion-title>
    </ion-toolbar>
  </ion-header>

<ion-item type=button (click)="openContent()">
      <ion-avatar slot="start">
        <!-- <img src="./avatar-yoda.png"> -->
      </ion-avatar>
      <ion-label>
        <h2>Yoda</h2>
        <h3>Size matters not</h3>
        <p>Do or do not. There is no try...</p>
      </ion-label>
    </ion-item>
  </ion-list>

</ion-content>
```

**Other information:**

![yes](https://user-images.githubusercontent.com/54003736/83528817-db315500-a4e9-11ea-9307-d3004a593a3d.png)

**Ionic info:**

```Ionic:

   Ionic CLI                     : 6.5.0 (C:\Users\Christopher\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.2
   @capacitor/core : 2.0.2

Utility:

   cordova-res : not installed
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.2
   @capacitor/core : 2.0.2

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   NodeJS : v12.9.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.2
   OS     : Windows 10
```

**Comment by roccosiffredi** [comment]
Issue still present

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!

**Comment by liamdebeasi** [comment]
Thanks for the reproduction. Can you please provide some additional steps to reproduce? I am unable to reproduce the issue using the steps provided.

**Comment by roccosiffredi** [comment]
IMPORTANT: This seems to be triggered when the fourth item in the ion-list is visited and after having refreshed the page.

Steps related to the specific reproduction provided are as follow: 
- Start the app using ionic serve
- Scroll to activate collapsable header.
- Title "Tab 1" is shrinked to smaller size but still apparent.
- Open ion-items entitled "CLICK ME" that are nested in an ion-list.
- This brings to content page entitled "extras".
- Navigate back to Home Page.
- The "Tab 1" is either shrinked to smaller size or is not apparent anymore.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I still am unable to reproduce the issue. What device/version are you seeing this issue on?

**Comment by roccosiffredi** [comment]
Hi, thanks for the quick reply!
I understand the problem now. The bug seems to happen when the device used is android but the modes for the headers are defined to ```mode=ios```. This indeed does not happen to iOS devices when Inspect Element is used in Chrome. I thought it was possible to use this mode for material devices as well, if one happened to prefer iOS over material design.

**Comment by liamdebeasi** [comment]
It should work on Android devices in newer versions of Chrome. What version of Chrome are you testing this on?

**Comment by sylwester-** [comment]
If I could join the conversation with some potentially helpful insights. Looking at the example from the documentation: [Collapsible Large Titles](https://ionicframework.com/docs/api/title#collapsible-large-titles), running code included there

`<ion-header translucent="true">
  <ion-toolbar>
    <ion-buttons collapse="true" slot="end">
      <ion-button>Click Me</ion-button>
    </ion-buttons>
    <ion-title>Settings</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content fullscreen="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-buttons collapse="true" slot="end">
        <ion-button>Click Me</ion-button>
      </ion-buttons>
      <ion-title size="large">Settings</ion-title>
    </ion-toolbar>
    <ion-toolbar>
      <ion-searchbar></ion-searchbar>
    </ion-toolbar>
  </ion-header>

  ...

</ion-content>`

highlights the issues. 
In Chrome, when switching between iOS and Android devices in device toolbar, if you add mode="ios" header is gone on Android - please refresh the page when you switch to Android. 

Also, even without adding mode="ios" the code from the documentation, does not support both iOS and Android. `<ion-searchbar></ion-searchbar>` is not visible at all on Android, which might be considered a correct behaviour, however, there is no easy way that would allow you have collapsable search bar on iOS and also, at minimum visible on Android - does not even have to be collapsable.
