### ISSUE TITLE
bug: Visuals not good on Chrome when passwords is saved

### ISSUE THREAD

**Issue by akvalibra** [ionic-team/ionic-framework#21437]
### ion-label is overlaped with ion-input when email and passwords is saved

```
form [formGroup]="authForm">
   <ion-item lines="none">
     <ion-label position="stacked">Е-пошта</ion-label>
      <ion-input formControlName="email" type="email" placeholder="Внесете е-пошта" [class.invalid]="!authForm.controls['email'].valid &&
      authForm.controls['email'].touched">
</ion-input>
</ion-item>
```

**Chrome without saved credentials**
![image](https://user-images.githubusercontent.com/8169630/83810928-35ccdb80-a6b9-11ea-98e9-5a13e80707e4.png)

**Chrome with saved credentials**
![image](https://user-images.githubusercontent.com/8169630/83810817-0c13b480-a6b9-11ea-9cd9-fb1402d59361.png)

**Firefox with saved credentials**
![image](https://user-images.githubusercontent.com/8169630/83810992-48dfab80-a6b9-11ea-9682-42dfd320a489.png)

**Ionic version:**
    "@angular/common": "~9.1.6",
    "@ionic-native/core": "^5.0.7",
    "@ionic/angular": "^5.0.0",

**Comment by akvalibra** [comment]
login.page.html

```
<ion-header>
    <ion-toolbar color="primary">
        <ion-title>Auth page</ion-title>
    </ion-toolbar>
</ion-header>

<ion-content class="ion-padding">
    <ion-row>
        <ion-col size="12" size-sm="10" offset-sm="1" size-md="8" offset-md="2" size-lg="6" offset-lg="3" size-xl="4"
                 offset-xl="4">

                 <ion-card>
                <ion-card-header>
                    <ion-card-title class="ion-text-center">Your Account</ion-card-title>
                </ion-card-header>

                <ion-card-content>

                    <ion-item lines="none">
                        <ion-label position="stacked">Email</ion-label>
                        <ion-input type="text" placeholder="Email" name="username"
                                   [(ngModel)]="credentials.username"></ion-input>
                    </ion-item>

                    <ion-item lines="none">
                        <ion-label position="stacked">Password</ion-label>
                        <ion-input type="password" placeholder="Password" name="password" [(ngModel)]="credentials.password">
                        </ion-input>
                    </ion-item>

                    <ion-button (click)="login()" expand="block">Login</ion-button>
                </ion-card-content>
            </ion-card>
        </ion-col>
    </ion-row>
</ion-content>

```
![image](https://user-images.githubusercontent.com/8169630/83884607-678b8400-a745-11ea-9d1f-3318ee635c4f.png)

After saving passwords input box is filled with email and password and is much bigger than usual input box

![image](https://user-images.githubusercontent.com/8169630/83884989-044e2180-a746-11ea-8f7d-112b5e411550.png)

**Comment by liamdebeasi** [comment]
Can you please provide this as a full repo? Code snippets usually are not enough for us to reproduce the issue.

**Comment by akvalibra** [comment]
@liamdebeasi I think this is Chrome specific behaviour (Windows). They put background blue color on input with autofil 

![image](https://user-images.githubusercontent.com/8169630/83941467-ce637880-a7eb-11ea-9241-0d2dcda49f14.png)


I have found post
https://support.google.com/docs/thread/4024179?hl=en

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Do you have a repo I can use to reproduce this issue?

**Comment by akvalibra** [comment]
@liamdebeasi Yes. Nothing special but work for the purpose

https://github.com/akvalibra/TestLogin


![image](https://user-images.githubusercontent.com/8169630/84043356-73c24c00-a9a6-11ea-8096-d27ea8104c59.png)

**Comment by liamdebeasi** [comment]
Hey there, it looks like there was already an issue opened for this so I am going to merge the two. We will track progress on https://github.com/ionic-team/ionic-framework/issues/18141. Thanks!
