### ISSUE TITLE
bug: ion-menu: cannot click on button right away after a swipe open

### ISSUE THREAD

**Issue by Wykks** [ionic-team/ionic-framework#21459]
# Bug Report

**Ionic version:**

[x] **5.1.1**

**Current behavior:**
When opening **with a swipe** the menu you cannot use the button inside the menu right away.

**Expected behavior:**
When opening a menu with a swipe, we should be able to click on the menu button right away. It works fine when opening the menu with a button.

**Steps to reproduce:**
You can reproduce the issue with the conference app https://github.com/ionic-team/ionic-conference-app (pwa mode)
Just open the menu **with a swipe** and click on any button. It does nothing if you're too fast.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am unable to reproduce this behavior. Can you provide some clarified steps to reproduce?

**Comment by Wykks** [comment]
I guess a gif is better than words:
![Peek 2020-06-08 22-40](https://user-images.githubusercontent.com/1236069/84078387-227f8000-a9d9-11ea-89cc-a71b216c8680.gif)

First try, too fast. Second try, I wait and it works.

(Same behavior on mobile, it's not caused by chrome device emulation)

**Comment by liamdebeasi** [comment]
What device are you testing this on? I am still unable to reproduce the issue.

**Comment by Wykks** [comment]
Chromium Version 83.0.4103.97

Also on a OnePlus 6 with Brave

**Comment by liamdebeasi** [comment]
Hmm ok I tested this on Chrome 83 and cannot reproduce the issue. Are you able to provide any other info that may help me?

**Comment by Wykks** [comment]
Okay that's interesting... I actually cannot reproduce the issue with Firefox desktop and Firefox on mobile..
So it's seem to be very specific to chromium (and brave too).

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I am unable to reproduce this issue on Chrome mobile on Android either (Chrome 83 on Android). Does this issue reproduce in a blank Ionic starter app?

**Comment by Wykks** [comment]
Yep. 
ionic start test
sidemenu blank project. 
ionic serve --host=0.0.0.0

On android chrome 83.0.4103.96

swipe left to right, touch (which doesn't change page), swipe right to left

![bug](https://user-images.githubusercontent.com/1236069/84082591-6629b800-a9e0-11ea-9774-3d57d8259593.gif)

**Comment by liamdebeasi** [comment]
I was able to reproduce this behavior. At first glance, it appears to be a Chrome behavior, so I am not sure there is much we can do to get around it. I will take a closer look though.

**Comment by indraraj26** [comment]
Hi Team,

Any news on this bug or workaround?

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I have tested this again with Chrome 101 and am no longer able to reproduce the issue. It seems that this was a bug in Chrome that has since been resolved.

We recommend updating to the latest version of Chrome/Android WebView to receive this fix. Thanks!
