### ISSUE TITLE
bug: ion-toast wrapping wrong when using <b> inside with default --whitespace

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/ionic-framework#21486]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

Some time ago I opened an issue which led to the implementation of the `--whitespace` css variable on ion-toast: https://github.com/ionic-team/ionic/issues/20727

The variable defaults to `pre-wrap`. This can lead to a "display bug" which I described in the mentioned issue. The problem is that in most cases the developer won't even know that this bug exists as it only appears on specific screen sizes/breakpoints. So he won't change the `--white-space` variable.

**Expected behavior:**

Please consider to update the default value to `--white-space: normal` in the next major release of Ionic as it is much more natural behavior. 

**Steps to reproduce:**

See my other issue for a visual explanation: https://github.com/ionic-team/ionic/issues/20727

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/22866.
