### ISSUE TITLE
bug: `spellcheck` property should use an enumerated string

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-framework#21516]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Property spellcheck uses a boolean type

**Expected behavior:**

Match the MDN spec for spellcheck https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

**Steps to reproduce:**

**Related code:**

```tsx
  /**
   * If `true`, the element will have its spelling and grammar checked.
   */
  @Prop() spellcheck = false;
```

becomes

```tsx
  /**
   * If `"true"`, the element will have its spelling and grammar checked.
   */
  @Prop() spellcheck = 'false';
```

**Comment by willmartindev** [comment]
Talked with the team and decided to close this as won't fix for now.

TypeScript's `HTMLElement.spellcheck` expects a boolean, and that is what the Stencil component is extending from when defining the component's types.
