### ISSUE TITLE
bug: cannot set box-shadow on menu when split pane is visible

### ISSUE THREAD

**Issue by NisStrom** [ionic-team/ionic-framework#21530]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:*
box-shadow of ion-menu inside ion-split-pane cannot be styled because the local css rule uses !important and can therefore not be overwritten. This could be the case in other ionic components as well.

**Expected behavior:**
CSS Rules of slotted content should not be marked with !important. Otherwise those rules cannot not be overwritten from outside.

**Related code:**
`:host(.split-pane-visible) ::slotted(.split-pane-side),
:host(.split-pane-visible) ::slotted(.split-pane-main) {
  @include position(0, 0, 0, 0);

  position: relative;

  /* stylelint-disable-next-line declaration-no-important */
  box-shadow: none !important;
  z-index: 0;
}`

**Other information:**

**Comment by liamdebeasi** [comment]
Thanks for the issue. What is the issue you are running into? The box shadow on a menu should not be set on the parent menu anyways (looks like that code is old).

**Comment by NisStrom** [comment]
Since you have refactored 'ion-split' pane to make use of shadow DOM,  the child 'ion-menu' is projected into a DOM element outside of shadow DOM. One would expect, that this element could be styled. That works basically, but as stated, 'box-shadow' is  always overwritten to be 'none'.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. The box shadow is applied to `.menu-inner`, not the root element, so you should be using something like CSS Shadow Parts to apply the box shadow.

Are you able to do something like this in your application? https://codepen.io/liamdebeasi/pen/ZEQeZao

**Comment by NisStrom** [comment]
The issue in the codepen project is still there:
![image](https://user-images.githubusercontent.com/15994669/85295222-e4d22b00-b49f-11ea-95ff-486c62e3b239.png)

The visible shadows are not for ion-menu but for ion-toolbar. Goal wold be that the shadow is separating the menu vertically to the navigation.

**Comment by liamdebeasi** [comment]
Ah, so you are trying to get the shadow to appear when the menu and content are both displayed?

**Comment by NisStrom** [comment]
Yes. 

You can see, that both 'box-shadow' and 'transform' cannot be custom styled because they are !important.

**Comment by Deitsch** [comment]
Any updates on this?

**Comment by capc0** [comment]
ran into the same issue.

**Comment by MatthiasWerning** [comment]
Bumping this issue since I'm running into exactly the same problem. It wouldn't be a problem if the property would be without "important!".

Since the property is applied to the shadow root, overriding is no longer possible.

**Comment by Mehedi50200** [comment]
still having same issue i tried for two days but with solution including shadow parts.  I am trying to put subtle shadow with margins  on side nav content. the margin part is doable but however shadow is not working at all. 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/31216496/149259701-dd2b2659-e5f8-4c2e-8c2f-d83cbb40e155.png">

**Comment by nadavhalfon** [comment]
Any updates?

**Comment by julianpoy** [comment]
Can confirm also having issues with the styling of shadows on split-pane.

**Comment by JSalram** [comment]
Any updates yet?

**Comment by Sulorb** [comment]
As mentionned in the codepen, the solution is to put this in the CSS:

`ion-menu::part(container) {
  box-shadow: 10px 10px 10px #FFF;
}
`

**Comment by samir4055** [comment]
still have a same issue

**Comment by samir4055** [comment]
**problem is here** , if i **disabled** default box-shadow it should be work but how can i remove this property i don't no


![image](https://github.com/ionic-team/ionic-framework/assets/103503433/7ea56816-145b-49af-aee3-540a7eba0e88)
![image](https://github.com/ionic-team/ionic-framework/assets/103503433/c73e31f2-08cd-4445-b8cf-8ff1832d935a)

**Comment by JoeCoppola-HIA** [comment]
We are also experiencing this issue, is there any update?
