### ISSUE TITLE
bug: Duplicate ids for text area and input fields

### ISSUE THREAD

**Issue by saivishnutammineni** [ionic-team/ionic-framework#21542]
# Bug Report
Duplicate ids are generated for input and text area labels.
**Ionic version:**
[X] **4.x**
[] **5.x**

**Current behavior:**
Duplicate ids are generated for labels for input and text area tags.

**Expected behavior:**
Labels ids generated should be unique.

**Steps to reproduce:**

1. add an ionic input field and a label for it (enclosed in ion-item)
2. add an ionic textarea and a label for it (enclosed in ion-item)
3. the ids generated will be same for the labels

**Related code:**

**Other information:**
Checked the source code of these elements and the issue seems to be due to how the id is calculated in text area

the input id is calculated as...
![image](https://user-images.githubusercontent.com/51150765/84745269-f7e18880-afd1-11ea-921a-fc98a10ed57d.png)

the textarea id is calculated as

![image](https://user-images.githubusercontent.com/51150765/84745400-20698280-afd2-11ea-8af1-eded1a4b4e26.png)

So the input in the id for textarea should be textarea

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22074, and a fix will be available in an upcoming release of Ionic Framework.
