### ISSUE TITLE
bug: Issue due to Empty button when the clearInput property is used

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#21549]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When `clearInput` property in ion-input for allowing the option to user to clear the input, this adds an empty button.

Screen reader won’t be able to read this and the tab navigation doesn’t focus the button. 

Refer to item 3 in the document shared in Slack for further details.
https://ionicteam.slack.com/archives/C7CGXAVTL/p1592319616186200

**Comment by liamdebeasi** [comment]
Closing. An `aria-label` was added to the clear button in v5.2.2. Not being able to tab to the clear button is the correct behavior and matches what browsers do for `input type="search"`. See the following CodePen in Chrome for an example: https://codepen.io/anon/pen/kjyAF.

**Comment by kensodemann** [comment]
@liamdebeasi - the model being followed here was more along what Google does:

1. https://www.google.com/
1. start typing in the one thing on the page... and an X appears to the right
1. press Tab
1. hit enter
1. input is now cleared

Do we have an easy way to set up that kind of behavior with our input component with a `clearInput`?

**Comment by liamdebeasi** [comment]
Hmm I think I like that behavior better. I will reopen and we can add this to Ionic.

**Comment by liamdebeasi** [comment]
Fixed via https://github.com/ionic-team/ionic/pull/21633.

**Comment by kensodemann** [comment]
@liamdebeasi - one part of how this works I find troubling from an a11y perspective is that once you do the following you are not back at the input ready for re-entery:

1. tab into input
1. type some random text
1. tab into clear button
1. return

At that point, I expect to be back at the input ready to enter more text, but I am ???? I am actually not entirely sure what is active at that point, but I cannot type more text.
