### ISSUE TITLE
feat: Aurelia 2 Integration

### ISSUE THREAD

**Issue by brandonseydel** [ionic-team/ionic-framework#21603]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Full support for Aurelia 2

**Describe Preferred Solution**

Would like Aurelia 2 to be supported by the Ionic team or at least direct link to docs and acknowledgment of an open source solution.

**Describe Alternatives**

Open source alternative that has ionic links / docs hosted on their site.

**Related Code**

https://github.com/brandonseydel/aurelia-ionic 
*I have a lot more to be released back into the open source after app release.*

**Additional Context**

Developer on the Aurelia team making core integrations with multiple platforms as well.  Couple things left for full coverage of components including tests and router animations.

**Comment by brandonseydel** [comment]
@liamdebeasi is there some type of steps that you would need to be taken in order to get this to happen?  Aurelia 2 is launching this month in alpha so I have some time to button everything up.

**Comment by liamdebeasi** [comment]
As it stands now, Ionic components should work with Aurelia 2 out of the box. There would likely need to be work regarding any routing solutions (tabs, url navigation, router outlets, etc).

We also need to gauge interest amongst the community to see if this is something we should build out. We are a small team with limited resources, so having people add a 👍 reaction to the post is a good way of indicating interest.

**Comment by brandonseydel** [comment]
@liamdebeasi yes it does just work and I have built out all the things you mention already on my private application.  I am on the AU2 team and we would be able to support it or help if you want to consume the open source.

**Comment by jrgcubano** [comment]
@liamdebeasi @brandonseydel I would love to be able to use Aurelia with Ionic (from the generators, the website, etc). I think it's the perfect mix. Please, do not let this issue die.

**Comment by brandonseydel** [comment]
just released au2 with ionic on trade exchange app check it out if you want.

**Comment by liamdebeasi** [comment]
Thanks! Is it on the app store?

Also, I spoke with the team regarding Aurelia integration. Right now, we are focused on shipping Ionic Vue so it does not seem likely that we can take on this effort soon. That being said, I will keep this issue open to gauge the community's interest.

**Comment by brandonseydel** [comment]
@liamdebeasi yes Trade Exchange is the app

**Comment by liamdebeasi** [comment]
Hi everyone,

The team has decided not to add an official Aurelia 2 integration. This feature would require a big effort to implement, and there is not enough support from the community at the moment. Ionic components should work in Aurelia 2 applications. However, form and routing integrations are missing.

I am going to close this issue. Thank you!
