### ISSUE TITLE
bug: ion-toolbar component rendering bug in version 5.1.1 and later

### ISSUE THREAD

**Issue by jorgio-castello** [ionic-team/ionic-framework#21622]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x** (Bug started to appear in 5.1.1)

**Current behavior:**

Since Ionic / Anguar 5.1.1 and subsequent versions, the ion-toolbar component in iOS applications has been disappearing / re-appearing following NavBar button clicks occurring within the same ion-header container. The NavBar buttons fetch data and render it within the content container. Our best guess is that the button clicks / state changes are triggering a collapse in the ion-toolbar height, or removing the ion-toolbar from view entirely. 

[Video of unexpected Behavior as seen in 5.1.1](https://youtu.be/Ews_jHxy9EM)
[Video of unexpected Behavior as seen in 5.2.2](https://youtu.be/fIHQ78DM1tY)

**Expected behavior:**

In Ionic / Angular 5.1.0, the ion-toolbar behaves as expected. Nav bar buttons clicks can occur and there are no changes to the sizing / view of the ion-toolbar component.

[Video of Expected Behavior as seen in 5.1.0](https://www.youtube.com/watch?v=VXyk-XpVdss&feature=youtu.be)

**Steps to reproduce:**

The following <ion-header> behaves as expected in Ionic/Angular 5.1.0 within our application, but it does not behave as expected in version 5.1.1 and later releases. 

```
<ion-header>
  <ion-toolbar>
    <ion-buttons *ngIf="! hideBack" slot="start">
      <ion-back-button [defaultHref]="backDefaultHref"></ion-back-button>
    </ion-buttons>
    <ion-buttons *ngIf="showForward" slot="end">
      <ion-button color="light">
        <ion-text class="text-transform-none">Done</ion-text>
      </ion-button>
    </ion-buttons>
    <ion-menu-toggle *ngIf="hideMenu !== 'yes'">
      <ion-button fill="clear">
        <ion-icon name="menu" size="large"></ion-icon>
      </ion-button>
    </ion-menu-toggle>
    <ion-title *ngIf="title">{{ title }}</ion-title>
    <ion-buttons slot="end">
      <app-quick-cart *ngIf="hideCart !== 'yes'"></app-quick-cart>
    </ion-buttons>
  </ion-toolbar>

  <app-nav-segment *ngIf="navSection === NavSection.items">
    <a #a routerLink="/itemA">Item A</a>
    <a #a routerLink="/itemB" >Item B</a>
    <a #a routerLink="/itemC">Item C</a>
    <a #a routerLink="/itemD">Item D</a>
    <a #a routerLink="/itemE">Item E</a>
  </app-nav-segment>

  <app-nav-segment *ngIf="navSection === NavSection.account">
    <a #a routerLink="/itemA">Item A</a>
    <a #a routerLink="/itemB" >Item B</a>
    <a #a routerLink="/itemC">Item C</a>
    <a #a routerLink="/itemD">Item D</a>
    <a #a routerLink="/itemE">Item E</a>
  </app-nav-segment>
</ion-header>
```

We really appreciate you having a look at this and look forward to receiving any info / advice you have for us on how we can resolve this issue. If you have any follow up questions, let me know.

**Comment by jorgio-castello** [comment]
Just wanted to comment for reference on the issue, the page transition issue was resolved with the following:
```
IonicModule.forRoot({ experimentalTransitionShadow: false }),
```

After disabling the experimentalTransitionShadow, the behavior of the page transitions returned to normal.

Thank you

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
