### ISSUE TITLE
bug: Ion Slides dynamically added items are aligned to the extreme right

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/ionic-framework#21620]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
I am loading a couple of gif images from Giphy's API, I am populating an ion-slide component with the resulting response which works fine albeit that the user has to swipe back left to get to the first slide in the results, ideally the slides would automatically start from the left hand side.

**Expected behavior:**
as mentioned above

**Related code:**
these are my options
```
    sliderOptions = {
        slidesPerView: 2.5,
        observer: true,
        loop: true,
        centeredSlides: false,
        observeParents: true,
        simulateTouch : true,
        loopFillGroupWithBlank: false,
        grabCursor: true      
      }

// calling my service which returns an observable like so, then populating giphyGifs to the ngfor in the template
  this.giphy.searchGifs("nice dog").subscribe( res => this.giphyGifs = res.data.map( (giph: any) => giph.images.downsized.url )  )              


// template is like so, initially its hidden and the user has to click a button to display it, potentially this causes the wrong alignment
  <div [hidden]="!showGiphControls" >
        <ion-slides 
        pager="false"
        [options]="sliderOptions">
          <ion-slide
          *ngFor="let item of giphyGifs;  let x=index"
          [ngStyle]="{'background-image': 'url('+ item +')'}"
          [attr.data-img]="x">
          </ion-slide>   
      </ion-slides>        
      <ion-searchbar class="gifSearchBar" #giphySearch></ion-searchbar>     
  </div>  


```

Ive had this issue for a while but thought I would report as I noticed this regarding RTL alignment https://github.com/ionic-team/ionic/issues/17012 maybe they are related

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
