### ISSUE TITLE
bug: history goBack in wrong direction if it was pushed with state

### ISSUE THREAD

**Issue by ChristineXYS** [ionic-team/ionic-framework#21639]
# Bug Report

**Ionic version:**
6.8.0

**Current behavior:**
history push a page with state, then push another one. When go back, the animation direction is wrong.

**Expected behavior:**
work as normal mobile's push/pop direction.

**Steps to reproduce:**
Assume we have page 1 pushing to page 2, page 2 pushing to page 3. The issue happens in this pseudo code:
In page 1:
history.push({
pathname: "page2",
state: {value:1}
});
In page 2:
history.push("page 3");

When navigate back from page 3 to page 2 using history.goBack(); , you can clearly see the action is PUSH instead of POP.

The bug is page 2 was pushed with a state, thus in your code, although setState {direction: "back"} previously, in the end it was replaced by the state {value: 1}, making wrong animation direction.

It can be visible by console.log every history in each page and check the location.state.

Please fix it as soon as possible, which causing push/pop nearly not usable in mobile.

**Related code:**

https://github.com/ChristineXYS/ionicreact-navigation-bug

**Other information:**

**Ionic info:**
Ionic:

   Ionic CLI       : 6.10.0 (/Users/baochristine/.nvm/versions/node/v13.12.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.2.2

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.3.0

System:

   NodeJS : v13.12.0 (/Users/baochristine/.nvm/versions/node/v13.12.0/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina

  ─────────────────────────────────────────────────

**Comment by elvisgraho** [comment]
I had the same issue. The fix that works 100% is to have a service for header that sets the back button href programatically.

```html
          <ion-back-button [defaultHref]="variableDerivedFromService" text=" ">
          </ion-back-button>
```

**Comment by elylucas** [comment]
Hi @chrisgriffith 

We have a dev release that should fix this issue. If you can, could you try to install it and let us know if it fixes the issue and if you run into any others? To install it run:

`npm i @ionic/react@5.3.0-dev.202006291715.9e74f80 @ionic/react-router@5.3.0-dev.202006291715.9e74f80`

If all goes good this should be available in the next Ionic release.

Thanks!
