### ISSUE TITLE
IonInput autofocus only works the first time

### ISSUE THREAD

**Issue by danaugrs** [ionic-team/ionic-framework#21634]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Explanation:**

Adding `autofocus={true}` to an `IonInput` autofocus the input only the first time the page is viewed. I expected it to autofocus the input every time the page is viewed.

**Other information:**

I'm using Ionic with React.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.10.1 (C:\Users\Daniel\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.2.2

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.16.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

**Comment by danaugrs** [comment]
Here's a reproducible example based on the `blank` starter template with only minor modifications (i.e. adding an `IonInput` with `autofocus={true}` on a second page): https://github.com/danaugrs/ionic-autofocus-bug

**Comment by dexster** [comment]
This happened to me in plain JS as well. It focused the first time only.

Here's a reproducible example (this never focused, even on first load)
[https://jsbin.com/jadosag/edit?html,js,output](url)

**Comment by mhjam** [comment]
Can confirm this behavior occurs with the Angular flavor, too.
After some research, it looks to me that the only thing that Ionic is doing is setting the `autofocus` attribute on the native `textarea` element. This cannot work, for reasons that are explained e.g. in https://stackoverflow.com/a/25734205/1004651 (tl;dr: the HTML attribute only works once after page load and only on the first element with that attribute - nothing that suits an SPA).

What I ended up doing was writing a custom directive that makes this attribute work as expected:

```typescript
@Directive({
    // tslint:disable-next-line:directive-selector
    selector: 'ion-input[autofocus], ion-textarea[autofocus]'
})
export class AutoFocusDirective {
    constructor(private el: ElementRef) {
        const ionEl = this.el.nativeElement as { getInputElement: () => Promise<HTMLElement> };
        ionEl.getInputElement().then((focusElement) => {
            setTimeout(() => focusElement.focus(), 500);
        });
    }
}
```
