### ISSUE TITLE
feat: auto dismissible Fab List

### ISSUE THREAD

**Issue by lriostavira** [ionic-team/ionic-framework#21666]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

I've run into trying to have an ion fab list being dismissible. Adding an onBlur event and closing the fab here is a bit flakey, especially because the icon takes most of the space and the button never recieves focus.

**Describe Preferred Solution**

adding an attribute to the IonFab component such as, dismissable=true and default could be either true or false

**Describe Alternatives**

an alternative is adding onBlur event and calling close within.

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Fab List components already auto dismiss when selecting a button. Can you please clarify the feature you are requesting?
