### ISSUE TITLE
bug: ion-nav canGoBack can return incorrect value during transitions

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic-framework#21668]
# Bug Report

**Ionic version:**
[x] **5.2.3**

**Current behavior:**
When calling `nav.canGoBack()` it can return an incorrect value if navigation is in progress.

For example, if the following code is used:

```tsx
const canGoBack = await nav.canGoBack();
if (canGoBack) return nav.pop();
```

If this code is called multiple times quickly then you get a result where `canGoBack` is true but there is an error during `pop()`.  The following appears in the console:

```
You can't remove all the pages in the navigation stack. nav.pop() is probably called too many times. 
Nav {ionNavWillLoad: {…}, ionNavWillChange: {…}, ionNavDidChange: {…}, transInstr: Array(1), animationEnabled: true, …} 

Uncaught (in promise) Error: navigation stack needs at least one root page
    at Nav.postViewInit (p-56c309e2.entry.js:644)
    at Nav.runTransition (p-56c309e2.entry.js:506)
    at Nav.nextTrns (p-56c309e2.entry.js:489)
    at Nav.runTransition (p-56c309e2.entry.js:538)
```

There is a workaround in `ion-back-button` that uses the `skipIfBusy` option to ignore overlapping calls but this does not work in situations where application logic is using the `canGoBack` value.  For example, if you want to have a button that goes back if the user is in a stack or displays the home page if not in a navigation stack.

`canGoBack` should detect the impact of in-progress changes so that it can correctly indicate whether `pop` is available.

Other `ion-nav` methods may have similar issues where they do not reflect in-progress changes to the stack.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
