### ISSUE TITLE
feat: Ionic 5 React IonMenu should animate to closed when disabled while onscreen

### ISSUE THREAD

**Issue by danaugrs** [ionic-team/ionic-framework#21675]
There is currently no way to have a menu linking to a page such that the menu is correctly disabled while on that page.
This is not an esoteric feature - many top apps do this e.g. Twitter when clicking *anything* on the menu.
The closest way to accomplish this is to disable the menu when the user clicks the link/button (on the menu) that leads to the page. But that causes the menu to disappear instantly. There is currently no way to make the menu close animation execute and only then disable the menu AFAIK. In fact it would be nice for the menu to be disabled while it's closing.

I'm not sure what the best solution is but here are the most straightforward options.

1) I'd imagine that in 99% of cases developers don't want the menu to instantly disappear when disabling the menu while it's onscreen but instead would like the menu to perform its close animation (with everything inside the menu disabled/unclickable). If a developer does indeed want to disable the menu while it's onscreen and have it disappear immediately they can easily do that by rendering the `IonMenu` component conditionally. Therefore the solution would be for the `IonMenu` to perform its close animation if its `disabled` prop changes to `true` and the menu is open. I think this is the best option.

2) Add callbacks for when the menu has fully closed or fully opened, possibly inside `menuController`. The existing `open`/`close` async functions in `menuController` are somewhat misleading as they give the impression that the promises they return will only be fulfilled when the menu has indeed opened/closed. Maybe we can modify `menuController` to make that the behavior.

What do the devs think?

**Ionic info:**

```
Ionic:

   Ionic CLI : 6.10.1

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.16.2
   npm    : 6.14.4
   OS     : Windows 10

```

**Comment by elylucas** [comment]
Hi @danaugrs,

Could you provide a repo that reproduces the issue?

Thanks

**Comment by danaugrs** [comment]
While building an example I improved my understanding of the problem(s).
I hadn't considered the non-mobile case where the menu is always visible in an `IonSplitPane`.
In that case (when the page is wide enough) the menu should be enabled on the page.
**Therefore the behavior I really want is to make the menu undraggable into view while on a certain page.**
There is a `draggable` prop on the React `IonMenu` but it doesn't work (and is [undocumented](https://ionicframework.com/docs/api/menu)).

So [here's a repo](https://github.com/danaugrs/ionic-menu-bug) with [two commits](https://github.com/danaugrs/ionic-menu-bug/commits/master), each exemplifying one issue:

1) The `draggable` prop on `IonMenu` doesn't work. The latest commit https://github.com/danaugrs/ionic-menu-bug/commit/7a10cef930f50126f142b957125d88ce684e3f19 exemplifies this. This is definitely the most pressing issue.

2) The menu disappears immediately when disabled while onscreen instead of animating to closed (the original issue). The first commit https://github.com/danaugrs/ionic-menu-bug/commit/17337181eaa269e4b4d4bc2387f9f7592b90f4e2 exemplifies this. This might not be a real problem.
