### ISSUE TITLE
bug: Can't control ion-fab state manually

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#21678]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

I wanna be able to control the ion-fab state and its children (activated or not) programmatically.

Right now, when binding a click event to a ion-fab, it doesn't override the default behavior resulting in not be able to control the activated property programmatically.

I am in need of this to enable the fab on hover on desktop, and on click on touchscreens ...

**Expected behavior:**

We should be able to control the ion-fab and its children (lists and fab) programmatically with a .open() / .close() (there is a close function but no open why is that ?) function or with the activated property

**Steps to reproduce:**

- Add a ion-fab with a ion-fab-button and a ion-fab-list
- Bind the activated property of ion-fab to a variable
- Bind the click event of the main ion-fab-button to a function that switch the value of the binded variable

You can also try to bind the variable to another button and it will enter in conflict with the main fab button and resulting in a wrong value for the activated variable

**Related code:**

https://stackblitz.com/edit/ionic-v5-bug-fab-visible-toggle

**Comment by amandaesmith3** [comment]
Thanks for the issue! I know it's been a while, but I wanted to circle back to this with a potential fix in case you or anyone else monitoring this issue still needs it.

I noticed that the code from your Stackblitz still replicates the issue on the latest version of Ionic. However, I was able to control the fab without conflicts by directly toggling the `activated` property:

```html
<ion-button (click)="toggleFab()">toggle</ion-button>
<ion-fab #fab> ... </ion-fab>
```

```ts
export class AppComponent {
  @ViewChild('fab') fab;

  constructor() {}

  toggleFab() {
    this.fab.activated = !this.fab.activated;
  }
}
```

Could you let me know if this solves your use case? Thanks!

**Comment by amandaesmith3** [comment]
`activated` should be defined, yes. Here's a repo I set up to showcase both strategies on the latest Ionic version: https://github.com/amandaesmith3/sandbox-ionic-angular/tree/fab

I'll dig into the issue with toggling `showFab` and let you know when I have more to share there :eyes: While testing, I noticed that wrapping the switch in a `raf` also fixes things: `requestAnimationFrame(() => this.showFab = !this.showFab);`
