### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Elardzhi** [ionic-team/ionic-framework#21685]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
In Ionic-React ```onIonModalDidPresent``` event is not fired on IonModal when it is opened

**Expected behavior:**
```onIonModalDidPresent``` is fired on opening IonModal according to Ionic docs

Found that ```onDidPresent``` is fired instead. So looks like a bug

**Comment by Elardzhi** [comment]
```
<IonModal                      
    onDidPresent={() => {           //Ionic bug, must be "onIonModalDidPresent"
           console.log('this will be called');
    }}
    onIonModalDidPresent={() => {
           console.log('this won't be called');
    }}
>
</IonModal>
```

**Comment by liamdebeasi** [comment]
Can you please provide a complete GitHub repo? Code snippets are usually not enough to reproduce the issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
