### ISSUE TITLE
feat: open ion-select manually with view child

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21683]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I would like to open ion-select in a programmatic manner.

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Can you please clarify what you are trying to achieve?

**Comment by indraraj26** [comment]
Example:
i am having country, state and city select dropdown, if person pick country from dropdown i would like to open state dropdown automatically with that i will save user click on app.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. This is already possible in Ionic Framework. You can use the `open` method on the state `ion-select` to programmatically open it up when selecting a country.

For more information, please see https://ionicframework.com/docs/api/select#methods.
