### ISSUE TITLE
bug: per-page transition not working on swipe to go back

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/ionic-framework#21692]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Using the back button works fine. But if I use swipe to go back it uses the default transition.

**Expected behavior:**

The custom transition should also work when using swipe to go back.

**Steps to reproduce:**

For this example I used the android transition on an iOS App as custom per-page transition. 
On button click: Custom transition works
On back button click: Custom transition works
On swipe to go back: Custom transition doesn't work. It falls back to the default iOS transition  

Video preview: https://streamable.com/7vnoq3
Sample project: https://github.com/mariusbolik/ionic-custom-page-transition

**Related code:**

```ts
async openPage() {
  await this.navController.navigateForward('/about', {
    animation: mdTransitionAnimation
  });
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build, and let me know if it resolves the issue?

`npm i @ionic/angular@5.3.0-dev.202007081515.c171ccb`

**Comment by mariusbolik** [comment]
Hey Liam!
Thank you for the fast response! Sadly there are still problems.
I updated the sample App.

If you open Page 1 which uses the default transition, everything works fine. If you open page 2 which uses the custom transition, it also works. But if you open Page 1 again, the entering transition works, but the back transition wich should be the default transition is overwritten by custom page transition from Page 2.

**Comment by liamdebeasi** [comment]
Thanks! I fixed that issue. Here is an updated dev build:

`npm i @ionic/angular@5.3.0-dev.202007081746.1eab581`

**Comment by mariusbolik** [comment]
Works perfectly! Thank you very much!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/21706, and a fix will be available in an upcoming release of Ionic Framework.
