### ISSUE TITLE
bug: ion-card default iOS dark mode styling issue

### ISSUE THREAD

**Issue by simonbarker** [ionic-team/ionic-framework#21694]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
ion-card seems to have no styling for iOS dark mode and is basically invisible. See screenshot on this forum post https://forum.ionicframework.com/t/is-this-really-what-ion-card-should-look-like-in-ios-dark-mode/192298/3

**Expected behavior:**
Lighter grey for card background like Andriod.

**Steps to reproduce:**
Add a default style card and set Chrome render mode to prefers dark, or run on iOS device with system dark mode enabled.

**Related code:**

My current workaround. Style doesn't cascade to child ion-list so this becomes a faff on larger component templates.
```
this.prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

<ion-card [ngClass]="{ 'dark-mode-background': prefersDark}">

.dark-mode-background {
  background-color: #1E1E1E;
}

```

**Other information:**
Raising this issue as per Mike Haringtons request on the forum post

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.9.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.803.27
   @angular-devkit/schematics    : 8.3.27
   @angular/cli                  : 8.3.27
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.3.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
As a temporary CSS-only workaround you can add the following styles to your `globals.scss` file:

```css
@media (prefers-color-scheme: dark) {
  ion-card {
    --background: #1E1E1E;
  }
}
```

**Comment by simonbarker** [comment]
Ah, nice that's better than littering my template with ngClass checks etc

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/21756, and a fix will be available in an upcoming release of Ionic Framework.

Once Ionic Framework v5.3.0 ships, developers will be able to upgrade their dark mode themes:

`.ios body` class in `variables.scss`:

```css
--ion-card-background: #1c1c1d;
```

`.md body` class in `variables.scss`:

```css
--ion-card-background: #1e1e1e;
```
