### ISSUE TITLE
bug: animations are slow and linear on iOS 14

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21702]
# Bug Report

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Current behavior:**

Animations like page transitions, modal transitions, action-sheet transitions, ... are very slow and linear on iOS 14. That is **not** a iOS 14 Bug, because it does not happen on native apps. It happens on Ionic 4/5.

**Expected behavior:**
Animations should not be so slow.

**Steps to reproduce:**
Try an animation on iOS 14 (Beta 1/2).

**Video:**
![RPReplay_Final1594202096 2](https://user-images.githubusercontent.com/36629890/86905716-c5c7d000-c112-11ea-9f55-be93abb89b25.gif)

**Comment by sebaferreras** [comment]
This seems to be a duplicate of [https://github.com/ionic-team/ionic-framework/issues/21613](https://github.com/ionic-team/ionic-framework/issues/21613)

**Comment by BerkeAras** [comment]
@sebaferreras Oh, im so sorry! Thanks for your fast answer.

**Comment by BerkeAras** [comment]
**Closed, because duplicate**
