### ISSUE TITLE
bug: reverse engineering

### ISSUE THREAD

**Issue by MedZghal** [ionic-team/ionic-framework#21710]
I have a question, i'am using ionic in my production apps, it help me a lot, but  today , i received a email  from a hacker , that can  make a reverse engineering of my app, and he send me a video with my app in serve mode  !!!! , i know that reverse engineering , can get only the android code "java files" !!! , but i saw my serve in his browser!!! it's possible from my android apk , he can get my ionic source code not only my build !!!!!

**Comment by wilk-polarny** [comment]
You know how a web app works, right? All of the HTML+CSS and transpiled+minified js files can be simply extracted out of an app. It's basically just CTRL-C, CTRL-V.

**Comment by liamdebeasi** [comment]
Closing as this is not really a bug in Ionic Framework. This is true of mobile apps in general, not just Ionic apps. While often challenging and time consuming, it is possible to reverse engineer parts of an app. As a result, you should never store secret information in the code such as passwords or private keys.
