### ISSUE TITLE
bug: unable to make text selection

### ISSUE THREAD

**Issue by younny** [ionic-team/ionic-framework#21712]
# Bug Report

**Ionic version:**

[] **4.x**
[X] **5.x**

**Current behavior:**
Unable to make text selection on ionic epubjs view. (Press and hold doesn't make any text selection.)
Only happenes latest iOS 13.4 and 13.5 with latest model devices (iPhone XR/11/11 pro, latest ipad)

**Expected behavior:**
Text is selected and user able to use copy or some other features.

**Steps to reproduce:**
- Open ionic app which renders epubjs view.
- Press and hold to select text

**Other information:**

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.1
   Ionic Framework               : @ionic/angular 4.8.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.0
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.0, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/dooyounggi/Library/Android/Sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.10.0 (/Users/dooyounggi/.nvm/versions/node/v10.10.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 11.5 Build version 11E608c
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
