### ISSUE TITLE
Vue js integration is abandoned ? :( feat: 

### ISSUE THREAD

**Issue by jbty** [ionic-team/ionic-framework#21713]
It would be great to be able to use ionic with Vue js in production ! Vue js is more popular than react on github 
and so much more pleasant to use (in my opinion)

**Comment by mavyfaby** [comment]
I agree, but you can achieve this by creating a vue project and add `@ionic/core` and `@modus/ionic-vue` manually.

**Comment by puku0x** [comment]
ICYMI
https://ionicframework.com/ioniconf#talks

It will be available on late summer or early fall.

**Comment by liamdebeasi** [comment]
We are currently working on Ionic Vue integration. We hope to have it available late summer or early fall. See the Ioniconf Keynote for more information: https://ionicframework.com/ioniconf/#keynote.

**Comment by jbty** [comment]
Great news ! Have a nice day

**Comment by aaronksaunders** [comment]
> @mavyfaby  add `@ionic/core` and `@modus/ionic-vue` manually.

I wouldn't recommend using `@modus/ionic-vue`
