### ISSUE TITLE
feat: haptic feeback on inputs

### ISSUE THREAD

**Issue by pritamsoni-hsr** [ionic-team/ionic-framework#21727]
# Feature Request

**Ionic version:**

[x] **@ionic/react 5.2.3**

**Describe the Feature Request**

Haptic feedback on inputs like toggle, range and haptic strength on ion-picker.
Having a custom extra prop to specify haptic strength on all inputs would be really awesome.

**Describe Preferred Solution**

just normally add the haptic feedback's code for picker to other elements. (or make a haptic class)

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. Haptics are already provided on these types of components as long as the haptic plugin is included in your Cordova/Capacitor application bundle. With Capacitor this should be included by default.
