### ISSUE TITLE
bug: IonBackdrop not covering entire IonContent and Content can be scrolled.

### ISSUE THREAD

**Issue by pritamsoni-hsr** [ionic-team/ionic-framework#21729]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.2.3**

**Current behavior:**

Enabling IonBackdrop doesn't cover the entire screen (content) and the list items on the content can be scrolled after ionbackdrop.

**Expected behavior:**

interaction with content should not be allowed when backdrop is visible.

**Steps to reproduce:**

```ts
let [state, setstate] = useState(false);
...
return(
<IonContent>
...
{
       state && <IonBackdrop tappable={false} visible={true} stopPropagation={true}/>
}
<IonList>
{ 
       Array(20).fill(0).map((e,idx) => <IonItem key={idx}> <IonLabel> Bar {idx} </IonLabel> </IonItem>
}
</IonList>
<p onClick={()=> setstate(true)}> Click Me</p>
....
</IonContent>

)
```
**Related code:**

```
setting {position:fixed} does solve the problem
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
