### ISSUE TITLE
bug: ion-radio-group does not follow a11y best practices

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#21743]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

ion-radio-group doesn't follow wai aria practices. As a result the user will have to use the tab key itself to navigate between the group and the radio buttons with in the list.

**Expected behavior:**
The aria practice example is provided in the link below :

https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/radio/radio-1/radio-1.html#:~:text=The%20role%3D%22radio%22%20attribute,tabindex%3D%22%2D1%22%20.

Essentially:

- tabs should move between `ion-radio-group`s
- if a radio button is "on" that one should be selected when the group is tabbed into
- if no button is "on" the first button should be selected when the group is tabbed into
- arrows should be used to navigate within the group, navigation should be circular from end to start or start to end going backwards

**Steps to reproduce:**
A sample application which demonstrates the issue is in the repo: https://github.com/mahiii85/ionic-test.git

branch: review/ion-set-one

**Comment by tomByrer** [comment]
Might want to mention this is for Angular.

A quick test shows that there is no arrow navigation etc.

@liamdebeasi Is Adobe's Spectrum the navigation behavior what you're looking for?

https://react-spectrum.adobe.com/react-spectrum/RadioGroup.html
