### ISSUE TITLE
bug: datetime-local is missing from TextFieldTypes causes compiler to fail when "strictTemplates" is enabled

### ISSUE THREAD

**Issue by almothafar** [ionic-team/ionic-framework#21757]
# Bug Report
I'm trying to make solid strict templates here and make angular compiler check types passed inside templates to reduce any possible logical issues, the problem is I use some attribute values for attribute `type` that supported in modern browsers but it failed to compile when I use it in `ion-input`.

The code effects web version, attribute `type="datetime-local"` is not supported in Safari but still it is a valid value.

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Steps to reproduce:**

I enabled `strictTemplates` for `angularComplierOptions` in tsconfig:

```json
{
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": [
      "es2018",
      "dom"
    ],
    "baseUrl": "."
  },
  "angularCompilerOptions": {
    "strictTemplates": true,
    "strictInjectionParameters": true
  }
}
```

And inside any page add the following:
```html
<ion-input  type="datetime-local"></ion-input>
```

And start `ionic serve` you sill see an error talking about `datetime-local` is not assigned to `TextFieldTypes`:

https://github.com/ionic-team/ionic-framework/blob/4fd7c0cc5a6c97100fa380e4ff1be0bb84c7006b/core/src/interface.d.ts#L50

```console
[ng]     Error occurs in the template of component Page.
[ng] src/app/pages/+main/....../page.html:70:51 - error TS2322: Type '"datetime-local"' is not assignable to type 'TextFieldTypes'.
[ng] 70                          type="datetime-local"></ion-input>
```

**Other information:**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

**Ionic info:**

```console

Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\AlMothafar\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.10
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : not installed

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v13.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/21758, and a fix will be available in an upcoming release of Ionic Framework.
