### ISSUE TITLE
IonInput: IonOnChange event firing twice 

### ISSUE THREAD

**Issue by laclance** [ionic-team/ionic-framework#21759]
# Bug Report

**Ionic version:**
[x] **5.0.7**

**Current behavior:**
IonOnChange event for IonInput fires twice when backspacing 1 character.

**Expected behavior:**
When value is 1 character and backspace is pressed, input value should be empty.

**Steps to reproduce:**
if I enter any characters, lets say 5 and 6, into the input the value is now 56 and then I press backspace and the input value is now 5 but then I press backspace again and onChange event fires and input is empty, then onChange event fires a 2nd time with value of 5 (or what the previous character was) and input goes back to 5 (or the previous character) again. If i keep hitting backspace repeatedly the same thing happens until eventually the input clears.

**Related code:**
```
              <IonInput
                name={'amount'}
                value={amount?.value}
                onIonChange={(e) => {
                  e.preventDefault();
                  updateAmount(e.detail.value)}
                }
                color={!amount?.value || amount?.value === 0 ? 'danger' : 'primary'}
                autofocus
                enterkeyhint={'go'}
                inputMode={'decimal'}
              ></IonInput>

                function updateAmount(value?: number | string, error = "") {
                    dispatch({
                      type: "UPDATE_AMOUNT",
                      payload: { value, error },
                    });
                  }

		case 'UPDATE_AMOUNT':
			return {
				...state,
				amount: {
					value: action.payload.value || state.amount.value,
					error: action.payload.error
				}
			};
```

**Ionic info:**
```
'ionic' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
