### ISSUE TITLE
bug: Ionic Menu gets blank or slides to right on iOS Devices (not in browser)

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21750]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
IonMenu gets blank or slides to the right on IonItem click

**Expected behavior:**
It should not get blank or slide to the right.

**Steps to reproduce:**
1. Create IonMenu with IonItem
2. Click IonItem

**Related code:**
[https://codepen.io/BerkeAras/pen/WNrKgQb?editors=1010](https://codepen.io/BerkeAras/pen/WNrKgQb?editors=1010)

**Other information:**
Video: [https://youtu.be/zFyByXJgYo0](https://youtu.be/zFyByXJgYo0)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you double check your code? I am not able to reproduce the issue.

**Comment by BerkeAras** [comment]
@liamdebeasi Did you try it on an iOS Device? It does not happen in the browser.

**Comment by liamdebeasi** [comment]
Yes I did. Your video shows a modal, but your code does not include a modal.

**Comment by BerkeAras** [comment]
@liamdebeasi Oh, I'm sorry, it was a wrong code! The issue has been fixed. I don't know exactly what happened, but it has been fixed. Thanks for your help, and sorry again!
