### ISSUE TITLE
feat: Add type to ion-select interfaces

### ISSUE THREAD

**Issue by distante** [ionic-team/ionic-framework#21755]
# Feature Request
The `IonSelect` and interface should allow us to define which value are we expecting.

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
When working with `CustomEvent`'s that carry `IonSelect` as detail we have to always cast the value because the current type is `any`

```
  function newSoundType(event: CustomEvent<IonSelect>): void {
    const myValue = event.detail.value as MyType;  // Here value is any!
    this.updateTrainingConfigWith(myValue);
  }
```

**Describe Preferred Solution**
The `IonSelect` interface should accept an optional `T` generic type, if none is given, then keep using `any`

**Describe Alternatives**
Instead of using `CustomEvent<IonSelect>` one can also use `CustomEvent<{value: MyType}>` but then you can not be sure what is the source of that event.

**Related Code**
[Implementation using Interface with an value as an optional defined type](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=20&pc=40#code/C4TwDgpgBAaghgGwK4QDwBUB8UC8V1QQAewEAdgCYDOUSlEAZgJZkQVQD8UA3lBXMDgcAXFDhkQUAL5RRvfoNEEpAbgBQalqQBODOAGNoASQD2ZAMoQEEfcAy5a9ZqwrZuaqJ6+eA9ACo-D29gv3wAC2hSEihgEz4mKjAEOEkzGIiofXFDBCgAIyRgWLIAOiDgzz8fcuCAIiyyHPRiYFrRKmBtFgBzdQrfAJqK0OAMgDdEFCgTBnToKisbYDL+yurV2onkCFqRKABtdABdQhJyagO6CkYWNhOucUkAHygyJARcpT6vKQ1rYCgAFsQAAlCDdd5wbSWay2USmCyLWzqNT-IEgdDgNgwpbwsw42yoDpdMjdTAo4FgiHJaFI5ZbFAqKA+HzTMDAJhmRBiCQaYGYyAUAn0yYQJkstkcrm5Yk9IA)

[Implementation using Type instead of interface with a mapped NON Optional value](https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAaghgGwK4QDwBUB8UC8V1QQAewEAdgCYDOUSlEAZgJZkQVQD8UA3lAG6IUHAFxQ4ZEFAC+UUbwHIIoglIDcAKHWhIUAJIB7MgGUICCAGNgGXLXrNWFbN3VRXb1wHoAVF5fv-XvgAFtCkJFDA+lAUTFRgCHCShhEhUObi5qZQAEZIwJFkAHR+-q5eHiX+AETpZJkI6MTAVaJUwABOLADmGu4yAGSwgmhYmmbAUAC2IABKEF1ICe0mZpaiBsamFsAa6uNTIOjgbCvb64anlqhtnWRdmLvTcwtLl8CFCiiqUB4eUPpgYBMQyIMQSTTTI6QChvD7Db6-KBkZIAoEghBQG7dIA)

--------
I wanted to create a PR but I was not sure where to edit this 😢

**Comment by liamdebeasi** [comment]
Yesterday I merged a PR that adds this functionality 😊 . The feature should be available in an upcoming release of Ionic Framework: https://github.com/ionic-team/ionic-framework/commit/7c2d0c981ab91930478c4b76220ce4ec4ed4e471

**Comment by distante** [comment]
@liamdebeasi can I ask, why is the change in the txt file needed? I want to learn how to do PRs for this myself.

**Comment by liamdebeasi** [comment]
The `core/api.txt` file is basically a list of all of Ionic Framework's public APIs. We use this when generating documentation and for keeping track of new features in the framework. Taking `ion-input` as an example, the "Properties", "Events", "Methods", and "CSS Custom Properties" tables in the documentation (https://ionicframework.com/docs/api/input) is generated from this `api.txt` file.

We have a [contributing guide](https://github.com/ionic-team/ionic-framework/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request) that shows you how to make a PR, build the framework, lint, etc.

**Comment by distante** [comment]
Thanks @liamdebeasi
