### ISSUE TITLE
bug: ion-popover after dismissal takes the focus to the top of the page (a11y)

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#21768]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
ion-popover after dismissal takes the focus to the top of the page. This creates issues during keyboard navigation. User have to bring back the focus to the place where left off.

**Expected behavior:**
After closing the popover, leave the focus wherever you were before hand.

**Steps to reproduce:**
A sample of the issue is reproduced in the repo:
https://github.com/mahiii85/ionic-test.git

Branch: review/ion-popover

The popovers are on the "!"

tab to A, B, or C
press enter to open the popover
press esc to close the popover

Each time you do this you end up starting over at the top of the page in your tabbing

**Comment by saivishnutammineni** [comment]
The issue exists with all types of overlays... alerts, popovers, full page loaders, etc which extend the overlay.

**Comment by brandyscarney** [comment]
Created a simplified Codepen reproducing this behavior: https://codepen.io/brandyscarney/pen/bGpoNjR

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22167, and a fix will be available in an upcoming release of Ionic Framework.
