### ISSUE TITLE
bug: picker column prevSelect is always the same as selectedIndex

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#21764]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

ionPickerColChange picker event handler receives change details and its property prevSelected value is always the same as selectedIndex prop value;

**Expected behavior:**

I assume that prevSelected should reflect the previously selected index and selectedIndex should reflect the currently selected index and those should be different if there has been a changed made.

**Steps to reproduce:**
1) open the link to stackblitz (see below)
2) click/tap OPEN PICKER button
3) change the value in the first column
Note that in the console the prevSelected shown is the same as selectedIndex

**Related code:**
See https://stackblitz.com/edit/ionic-angular-v5-dbgcak?file=src%2Fapp%2Fapp.component.ts

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.9.2 (/Users/alexryltsov/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.1
   @capacitor/core : 2.1.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (/Users/alexryltsov/.nvm/versions/node/v12.16.3/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by thetaPC** [comment]
Thanks for the issue! This has been resolved via PR ionic-team/ionic-framework#27458 and will be available in an upcoming release of Ionic.
