### ISSUE TITLE
feat: Swipe to dismiss Toasts

### ISSUE THREAD

**Issue by jschillingApollo** [ionic-team/ionic-framework#21769]
# Feature Request
Toast can optionally be dismissed via swiping the toast.

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Describe the Feature Request**

Toasts should be dismissible via swiping. Many modern mobile apps that show messages similar to Toasts in Ionic are easily dismissible via swiping left or right on the toast.

**Describe Preferred Solution**

A swipeToClose boolean option that could be added to the opts parameter in the Toast Controller's .create() function. Set to false by default.

**Comment by roman-rr** [comment]
Hello @jschillingApollo 
Check in this [toolset](https://github.com/roman-rr/cupertino-pane) if somethings you are looking for.

**Comment by jschillingApollo** [comment]
> Hello @jschillingApollo
> Check in this [toolset](https://github.com/roman-rr/cupertino-pane) if somethings you are looking for.

Thanks @roman-rr for the suggestion! That library looks awesome. Lots of great options.

**Comment by TakumaKira** [comment]
Hi!

I'd like to try adding this feature.

**Comment by Yonier** [comment]
any update?

**Comment by jschillingApollo** [comment]
> any update?

Looks like it has been completed in this [PR](https://github.com/ionic-team/ionic-framework/pull/23124#issuecomment-811258035) and is awaiting review by the Ionic team to be added to a future minor release.

**Comment by katche70** [comment]
Hi, would be a nice feature. But it's still not supported?

**Comment by bstrasburg** [comment]
Waiting for this too....

**Comment by cyrilfr** [comment]
any news about this feature?

**Comment by katche70** [comment]
Hey whats going on here with jschillingApollo open PR ? Nothing form Team here to add this in official ionic release. Would by nice to have this feature, because it would be feel more native for ios user. Push Messages from ios simply can swipe up

**Comment by jschillingApollo** [comment]
Looks like there was some updates on the [PR](https://github.com/ionic-team/ionic-framework/pull/23124) for this Issue yesterday. Potentially targeted for Ionic v7 release but it didn't sound like they are dead set on that yet. They mentioned they are still very interested in including it and know that it is important to us.

**Comment by andrerds** [comment]
How wonderful! I'm looking forward to this new feature. Guys, it is possible to test this feature in advance, you would want to make a fork. Testing purposes.

**Comment by Sigmale1000** [comment]
How is the status of this issue? 
More and more applications use this and I think we need to modernise the toast anyways with a few more options. For example also seeing a timer bar which goes eg. from left to right (based on the duration) and then dismisses, or the swipe to dismiss feature.  🙈

**Comment by liamdebeasi** [comment]
Hi everyone,

This feature was implemented in https://github.com/ionic-team/ionic-framework/pull/28442 and will be available in an upcoming minor release of Ionic.
