### ISSUE TITLE
bug: IonModal and page transitions on iOS

### ISSUE THREAD

**Issue by pritamsoni-hsr** [ionic-team/ionic-framework#21773]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.2.3 React**

**Current behavior:**

when IonModal is open the original page on ios devices should follow ios 13 like design which is working fine on ionic angular.
the page transitions on react aren't super smooth like the are with ionic angular.

**Expected behavior:**

page transitions and modal should follow the new apple apple design patterns on Ionic React like they works with ionic angular.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by roopeshreddy** [comment]
We see the same issue with iOS 14 in latest version of Ionic Angular.

**Comment by liamdebeasi** [comment]
@roopeshreddy That is a different issue. Please see https://github.com/ionic-team/ionic-framework/issues/21613#issuecomment-648149256 for more information.

**Comment by pritamsoni-hsr** [comment]
@liamdebeasi [here](https://github.com/pritamsoni-hsr/ionic-testing) is the code 
and [here](https://youtu.be/yTa2EjWyxsk) is the result I'm getting, and here is the expected behaviour for these two [modal](https://s3.amazonaws.com/ionicframework.com/videos/modal-light.mov)  [page-transition](https://s3.amazonaws.com/ionicframework.com/videos/large-title-light.mov) last 4 seconds

**Comment by liamdebeasi** [comment]
Thanks! The problem with the modal is that you are not selecting the correct element. You should be passing a reference to `IonRouterOutlet` to `presentingElement`. The docs are confusing regarding this usage, so I will make sure it gets updated.

What's the problem with the page transitions? I am not seeing any issues with performance.

**Comment by pritamsoni-hsr** [comment]
Thanks it'd be really helpful.
For the page transition, you can see a smooth hold and swipe back transition in second video, if you do it slow you can feel it, but in the implementation I try to swipe back and it transition back to the initial page immediately.
Performance is the same in both cases, the first one is being preferred as per apple HCI.

**Comment by liamdebeasi** [comment]
Thanks. Swipe to go back not working properly is an existing issue (https://github.com/ionic-team/ionic-framework/issues/20904).

**Comment by pritamsoni-hsr** [comment]
Thanks. I got the modal working, maybe I'll update the docs soon.

**Comment by liamdebeasi** [comment]
I'm working on a documentation update right now, so I will close this issue out once it merges.

**Comment by pritamsoni-hsr** [comment]
Thanks

**Comment by roman-rr** [comment]
@liamdebeasi Does Ionic Framework inherit [safari bug](https://bugs.webkit.org/show_bug.cgi?id=133180) with transition, where touchmove return large number for clientX, clientY instead of double ?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/21780, and a fix will be available in an upcoming release of Ionic Framework.
