### ISSUE TITLE
feat: Label in ion-alert

### ISSUE THREAD

**Issue by somq** [ionic-team/ionic-framework#21776]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

Add the ability to use the [label property](https://ionicframework.com/docs/api/alert#usage) for inputs of type _text_ to add a label above inputs in alerts [as shown](https://prnt.sc/tjsmg9) in the [ion-input docs example](https://github.com/ionic-team/ionic-docs/blob/master/src/demos/api/input/index.html#L29).

**Describe Preferred Solution**

Use the label property already in place for checkboxes and radio inputs, and eventually add a position property (stacked, fixed, floating).

I guess this could be done directly [in the template](https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/alert/alert.tsx#L398) used for inputs.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I think this can be solved via https://github.com/ionic-team/ionic-framework/issues/18067.
