### ISSUE TITLE
bug: v5 Radio buttons stay to right

### ISSUE THREAD

**Issue by tomByrer** [ionic-team/ionic-framework#21789]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
The Radio buttons float to the Right but the text is Left-aligned for the examples, causing selection confusion.

**Expected behavior:**
Radio buttons to be & text to be both aligned to Left (or both Right for RtL languages).  Having the text & button next to each other is best practice UX.

**Steps to reproduce:**
Use React demo: 
https://ionicframework.com/docs/api/radio-group

** _Workaround_:**
Switching the button & label in the JSX works, but there is no gap between button & label:
```jsx
        <IonItem>
					<IonRadio value="duesenberg" />
          <IonLabel>Duesenberg</IonLabel>
        </IonItem>
```

**Ionic info:**
   Ionic CLI       : 6.10.1 (...\AppData\Local\Yarn\Data\global\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.2.3

Capacitor:
   Capacitor CLI   : 2.3.0
   @capacitor/core : 2.3.0

Utility:
   cordova-res : 0.15.1
   native-run  : not installed

System:
   NodeJS : v14.5.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10

Thanks for your time!  :)

**Comment by tomByrer** [comment]
@liamdebeasi Have a CodeSandbox starter for Ionic-React around so I can address this please?
All of the starters Ionic links to are for Angular.

**Comment by liamdebeasi** [comment]
I will work on getting an official template added, but here is a blank starter app I made you can fork: https://codesandbox.io/s/ionic-react-tabs-starter-hzoph

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
