### ISSUE TITLE
bug: HTML misalignment due to 3d perspective when using IonSlides on a WebKit browser

### ISSUE THREAD

**Issue by uncvrd** [ionic-team/ionic-framework#21795]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

I've discovered an issue when using the IonSlides component within a WebKit browser such as Safari (on mobile or desktop). Even though the elements are displayed properly, their actual "clickable" areas have shifted due to the `perspective` css class added on Ion Slides elements. Here's a quick video showing the problem:

Link: https://streamable.com/7dudmw

Timestamps: 

**0:00 to 0:08** I use the element inspector to show that the actual div element that you can select is not covering the full button. I'm not quite sure the technical term here.

**0:09 to 0:14** I click on the IonSlides DOM element and disable the perspective attribute.

**0:15 to END** I use the element inspector to show that the element now preserves its full width and I can click anywhere on the button again. 

Here's a repo to reproduce (remember to run in Safari): https://github.com/uncvrd/3d-perspective-ion-slides.git

I have no issues here when running it on Chrome.

Screenshot of the issue:

![image](https://user-images.githubusercontent.com/25097099/88276940-b90bb600-cc94-11ea-83a8-93d285d4d85b.png)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.7.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.2.3

Capacitor:

   Capacitor CLI   : 2.3.0
   @capacitor/core : 2.3.0

Utility:

   cordova-res (update available: 0.15.1) : 0.14.0
   native-run                             : 1.0.0

System:

   NodeJS : v12.16.2 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. `ion-slides` uses a library called Swiper under the hood, so I recommend you file an issue with them on their repo: https://github.com/nolimits4web/swiper/. Thanks!

**Comment by uncvrd** [comment]
@liamdebeasi Ah ok, I see that `slides-vendor.scss` isn't a file from the Ionic team. But I guess if they need to change this, wouldn't it be good to keep this issue open so that you guys can take note of the change and update the slides-vendor.scss with a fix?

**Comment by liamdebeasi** [comment]
We only keep these issues open if the bug is in Ionic Framework, but if Swiper updates their css to resolve this issue we will be sure to update the `slides-vendor.scss` file. Thanks!
