### ISSUE TITLE
bug: ion-virtual-scroll with custom components doesn't call onInit() for all list elements in custom component

### ISSUE THREAD

**Issue by comniemeer** [ionic-team/ionic-framework#21798]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When creating a `ion-virtual-scroll` list with a custom component inside, the `onInit()` and `ngAfterViewInit()` functions only get called for the items rendered initially. Other items, which will be rendered later when scrolling through the list, don't get their `onInit()` function called.

**Expected behavior:**

I expect `ion-virtual-scroll` to call the `onInit()` and other functions for every item when they get rendered.

**Steps to reproduce:**

Please see the sample application below on my GitHub and StackBlitz. I included a `console.log()` for each item in `onInit()`, so you are able to see that only the initially rendered items are being print out to the console.

**Related code:**

Sample application on my GitHub: https://github.com/comniemeer/ionic-virtualscroll-custom-component
Sample application StackBlitz: https://stackblitz.com/github/comniemeer/ionic-virtualscroll-custom-component
StackBlitz preview: https://jvmipjxzz.github.stackblitz.io/

**Other information:**

**Ionic info:**

From my local computer:
```
Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\<USERNAME>\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.0

Utility:

   cordova-res (update available: 0.15.1) : 0.8.1
   native-run (update available: 1.0.0)   : 0.2.9

System:

   NodeJS : v12.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.7
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. With upcoming major versions of Ionic Framework, we are going to be transitioning to using Angular's CDK Scroller. As a result, we have a freeze on new features and bug fixes on ion-virtual-scroll. See https://material.angular.io/cdk/scrolling/overview for how to get started with CDK Scroller.
