### ISSUE TITLE
bug: ion-datetime ignores AM/PM when format `A` is at front

### ISSUE THREAD

**Issue by darron1217** [ionic-team/ionic-framework#21797]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

ion-datetime with `display-format="A h:mm"` does not showing AM/PM option on spinner

**Expected behavior:**

Show AM/PM option on spinner

**Steps to reproduce:**

```
        <ion-item>
          <ion-label>A h:mm</ion-label>
          <ion-datetime display-format="A h:mm" value="01:47"></ion-datetime>
        </ion-item>
```

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-qaldbz

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\Darron\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v12.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I can confirm this is a bug. We are tracking datetime issues in https://github.com/ionic-team/ionic-framework/issues/16630, so I will add your issue there. Thanks!

**Comment by brandyscarney** [comment]
I did some debugging on this issue and found that this is the reason it isn't working properly: https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/datetime/datetime-util.ts#L387-L393

I just need to understand why this was added before I can remove it.
