### ISSUE TITLE
Voice Over and Talk Back on phone does not work with Ionic Alert

### ISSUE THREAD

**Issue by brandiwerner** [ionic-team/ionic-framework#21804]
**Ionic version:**

[ ] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

This is a very similar issue to issue [17126](https://github.com/ionic-team/ionic-framework/issues/17126) except it is concerning the ion alert and the screen reader reading content behind the alert.

**Current behavior:**
With Voice Over or Talk Back on, open an alert via the ionSelect element. Swiping (via your finger) move from element to element on screen and the screen reader will be able to read the elements in the parent page behind the alert.  

**Expected behavior:**
After opening the Selector the content behind the Selector should be hidden to the screen reader.

**Steps to reproduce:**
- Create an Ionic app
- Create an IonSelect 
- Try navigating with the select open on phone devices and notice the elements behind the alert are readable

**Related code:**

The illustration on [17126](https://github.com/ionic-team/ionic-framework/issues/17126) shows this issue but with a keyboard instead of swiping with a finger.

**Other information:**
This issue can be replicated in any blank project, no special configuration needed.

**Ionic info:** 
I am using Ionic React.

**Comment by brandiwerner** [comment]
FYI: I am testing the app as a PWA.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
