### ISSUE TITLE
feat: Set focus radius for IonButton, IonMenuButton, IonBackButton, ... on iOS

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21815]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
Ionic should add a focus radius for IonButton, IonMenuButton, IonBackButton and a few more elements on iOS. Native iOS Apps have this feature since many versions for a better accessibility. Elements should be focusable, without touching the button, just by touching something in the radius. Here are example videos:

Native: [https://youtu.be/sEuRl31gZO0](https://youtu.be/sEuRl31gZO0)
Ionic: [https://youtu.be/MdJwPp0SGcY](https://youtu.be/MdJwPp0SGcY)

![FocusRadius](https://user-images.githubusercontent.com/36629890/88455205-bb783680-ce73-11ea-98ce-c5eeaab5502b.png)
The red outline is the radius, where the element gets focused without touching it, just by touching something in the radius.

*How to try it out:*
Open a native iOS App. Touch a button and swipe your finger down. As you can see, it unfocuses. Swipe your finger back to the button, and it should focus.

**Describe Preferred Solution**
Some elements on iOS should get this effect automaticly, for a better accessibility.

**Describe Alternatives**
There are no alternatives.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is not something we plan on adding to the framework right now. There are 2 feature requests here:

1. Increase the hitbox on Ionic components.

Users can do this themselves by increasing the padding around an element or wrapping it in a larger container if they wish. This likely has other side effects, so instead we recommend that the dimensions of your button are large enough to be tapped.

2. When dragging a pointer over/out of a button, the button focuses/unfocuses.

We have gotten this request before, but this would require a custom gesture listener to be placed on each button. It would likely incur a large performance hit if we applied this to every single button/focusable element.
