### ISSUE TITLE
bug: ionTabs - Unknown event handler property `onIonTabsDidChange`. It will be ignored

### ISSUE THREAD

**Issue by visciang** [ionic-team/ionic-framework#21827]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.3.1**

**Current behavior:**

After 5.3.0 I see this warning about `onIonTabsDidChange`.
Nothing broken just a warning!
 
```
index.js:1 Warning: Unknown event handler property `onIonTabsDidChange`. It will be ignored.
    in div (created by Context.Consumer)
    in PageManager (created by IonTabs)
    in IonTabs (at Tabs.tsx:88)
    in Tabs (at App.tsx:30)
    in NavManager (created by IonRouterInner)
    in IonRouterInner (created by Context.Consumer)
    in IonRouter (created by IonReactRouter)
    in Router (created by IonReactRouter)
    in IonReactRouter (at App.tsx:29)
    in ion-app (created by IonApp)
    in IonApp (created by ForwardRef(IonApp))
    in ForwardRef(IonApp) (at App.tsx:28)
    in App (at src/index.tsx:6)
```

**Expected behavior:**

**Steps to reproduce:**

`git clone https://github.com/visciang/testTabs.git`
`ionic serve`

Have a look at console logs.

Project created with `ionic start testApp tabs --type=react`

with this addition only https://github.com/visciang/testTabs/commit/d338d03bfc6f821d2d0b8a79f5042862993af1d6

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.10.1 (/home/xxx/.asdf/installs/nodejs/14.3.0/.npm/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.3.1

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.3.0 (/home/xxx/.asdf/installs/nodejs/14.3.0/bin/node)
   npm    : 6.14.5
   OS     : Linux 5.4
```

**Comment by johannb75** [comment]
Facing the same issue. Does someone have the solution?

**Comment by rgoldiez** [comment]
Faced the same issue but moved the handler down to the `IonTabBar` component and the warning goes away.  I will note that it does indeed fire the event even though the warning comes up.

**Comment by johannb75** [comment]
Could you add an example please ?

**Comment by agenterp** [comment]
same problem here! any ideas

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22233, and a fix will be available in an upcoming release of Ionic Framework.
