### ISSUE TITLE
bug: @ionScroll does not work on ion-content

### ISSUE THREAD

**Issue by bartboersma** [ionic-team/ionic-framework#21821]
Hi,

Working on a Vue app where I noticed ```@ionScroll``` is not working, even though ```:scrollEvents="true"``` is enabled.

```
<template>
   <ion-page>
      <ion-content
         :scrollEvents="true"
         @ionScrollStart="logScrollStart()"
         @ionScroll="logScrolling($event)"
         @ionScrollEnd="logScrollEnd()"
      >
      // content
      </ion-content>
   </ion-page>
</template>

<script>
export default {
   methods: {
      logScrollStart() {
         console.log('in logScrollStart');
      },
      logScrolling(event) {
         console.log('in logScrolling: ' + event);
      },
      logScrollEnd() {
         console.log('in logScrollEnd');
      }
   }
}
</script>
```

```in logScrollStart``` and ```in logScrollEnd``` are logged. However, ```in logScrolling``` is never logged. I am not sure if the issue is with ```@ionScroll``` or with ```:scrollEvents="true"```.

**Comment by liamdebeasi** [comment]
Thanks for the issue. We are working on an updated version of Ionic Vue that should solve many of these issues. We hope to have a build out late summer/early fall. As a result, we are closing any new issues related to older Ionic Vue builds.

We will put out an announcement when we have more to share. Thanks!

**Comment by bartboersma** [comment]
Awesome! Thanks for replying.
