### ISSUE TITLE
bug: Simple menu + tabs implementation broken on iOS 14 beta 3

### ISSUE THREAD

**Issue by mattsteve** [ionic-team/ionic-framework#21829]
#21775 Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When opening an "ion-menu" by tapping an "ion-menu-button" inside an "ion-toolbar". The menu opens correctly. However, if you tap away in the empty space to close the menu, the menu closes but opens again immediately with empty content. At this point, you must restart the app because no user input lets you escape from this "empty menu" view.

This is a view of the screen when the menu first opens. Looks OK:

![IMG_139863CE288D-1](https://user-images.githubusercontent.com/34715493/88589748-9a584700-d027-11ea-8f27-96560d4ce628.jpeg)

This is a view after you close the menu, but it re-opens itself automatically with no content. At this point, no matter where you tap, nothing happens. The user is soft locked.

![IMG_8409E193C51A-1](https://user-images.githubusercontent.com/34715493/88589618-68df7b80-d027-11ea-95d0-9170cb7ced30.jpeg)

**Expected behavior:**
"ion-menu" should close with no problems like previous versions of the framework.

**Steps to reproduce:**

`ionic start menu-test tabs --capacitor`

In "tab1.page.html", add a menu button to the "ion-toolbar".

```
<ion-buttons slot="primary">
    <ion-menu-button menu="navigation"></ion-menu-button>
</ion-buttons>
```

In "app.component.html", add an "ion-menu" that targets the router outlet.

```
<ion-menu menuId="navigation" type="reveal" side="end" contentId="main"><!-- I don't know if it matters what goes in here --></ion-menu>
<ion-router-outlet id="main"></ion-router-outlet>
```

Run the application on an iOS 14 beta 3 device.

**Related code:**

Sample application:
https://github.com/mattsteve/ionic-5-ios-14-menu-bug

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 (update available: 1.0.0)

System:

   NodeJS : v12.18.3 (/usr/local/bin/node)
   npm    : 6.14.6
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. There are a few known bugs in WebKit with iOS 14. They typically get resolved after a few betas.
