### ISSUE TITLE
bug: Navigation: chain of push/replace

### ISSUE THREAD

**Issue by Elardzhi** [ionic-team/ionic-framework#21832]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Steps to reproduce:**
`https://github.com/Elardzhi/Ionic-React-navigation.git`

**Description:**
In the demo repository, we have a chain of `history.replace` and `history.push`.
Page 1 -> Page 2 : history.replace, no animation, working as expected
Page 2 -> Page 3 : history.push, transition with animation, working as expected
Page 3 -> Page 4 : history.replace, **animation exists, not expected**
Page 4 -> Page 1 : history.replace, **animation exists, not expected**
Page 1 -> Page 2 : history.replace, URL is updated, but **no transition to Page 2**

**Comment by elylucas** [comment]
Hi @Elardzhi,

Thanks for the issue.

We have a fix coming in the next release that will fix the unwanted animations when going to page 4 and back to page 1 when using a replace.

However, I'm curious what your use case is for using replace to navigate to new pages? If it is to not have an animation, you can specify the routerDirection on our components like so, and doing so will not use the animation:

<IonItem routerLink="/page2" routerDirection="none">Page 2</IonItem>
or
<IonButton routerLink="/page2" routerDirection="none">Page 2</IonButton>

**Comment by elylucas** [comment]
Also, you can specify the routerDirection programatically by using our ionRouterContext to do the transition:

`const ionRouterContext = useContext(IonRouterContext);`
....
```
       <IonButton
          onClick={() => {
            ionRouterContext.push('/page2', "none");
          }}
        >to Page 2</IonButton>
```

**Comment by Elardzhi** [comment]
Perhaps this is our specific case.
I'm building an App based on our web site (React). And we have a search-bar/autosuggest logic that sends users to a new page when the user selects a suggestion or hit Enter key.
That is fine without animation, using React users don't have a feeling that they are redirected to a new page. 
In the Ionic app, I tried to use `history.replace` to avoid the animation and pushing search links into the `history` object.
I read about `routerDirection` but it can't be implemented on Enter click (onKeyDown event). But I missed `IonRouterContext` it works perfectly! Thank you.

**Comment by aaronksaunders** [comment]
@elylucas where is there documentation in ionRouterContext? running into similar issues

**Comment by kayza-media** [comment]
I have the same problem in a another context.
I want to use the nativ back button on Android. I see the tabs on the bottom is hightlighted but my view doesnt change. And I cant close the app with the back button. It give me the following error Error: An Ionic Router is requiring for IonRouterContext.

What can I do. thanks for any help

**Comment by D4RKONION** [comment]
> @elylucas where is there documentation in ionRouterContext? running into similar issues

This!

This should absolutely be documented somewhere. I searched far and wide on the web for a programmatic way to change routerDirection to no avail. ```useContext(IonRouterContext)``` solved my issue and would have been much appreciated for solving the issue.

Just to add to what's here, this is the issue I was having, very similar to others:

I'm on ```page1/:name```. I have a custom menu which changes the name slug using ```history.replace('page1/{newName}')```. This works fine.

I navigate from ```page1/:name``` to ```page1/:name/:attribute``` and when I go back via the ```IonBackButton```, Ion Router seems to remember that the last direction that it used was back. 

Now using ```history.replace('page1/{newName}')``` causes a back animation every time, no matter where else I navigate in app.
