### ISSUE TITLE
bug: Focus goes behind the dialogue for alert dialogue using talkback in ionic 5.27.0 

### ISSUE THREAD

**Issue by shahezad-bacancy** [ionic-team/ionic-framework#21837]
I Use ionic 5.27.0, angular 9.0. 

I noticed that Focus goes behind the dialogue for alert dialogue using talkback if the user swipes forward.

I refer Below ticket for the same issue :
https://github.com/ionic-team/ionic-framework/issues/21598

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
