### ISSUE TITLE
bug: Ion-Nav not removing pages from DOM on pop()

### ISSUE THREAD

**Issue by Gorshtak** [ionic-team/ionic-framework#21831]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When using ion-nav pop() method page persist in DOM

**Expected behavior:**

Page should be removed from DOM

**Steps to reproduce:**

First there should be ion-nav and ion-router-outlet on the same level for bug to be reproducible. Page that are loaded via router-outlet should also contain an instance of ion-nav and when using that instance for pushing and popping the pages are not getting destroyed or rather they stay in DOM with display: none.

Using the project provided below steps to reproduce are:
1. Click on header("Go to Second page") to open second ion-nav
2. Click on "PUSH"
3. Click on "POP"

Inspect html structure and you will see the child component is still in DOM even though we popped it.

**Related code:**
Here is the minimal structure needed for the bug to reproduce https://github.com/Gorshtak/bug-ion-nav

<img width="652" alt="Screen Shot 2020-07-28 at 5 57 49 PM" src="https://user-images.githubusercontent.com/15227075/88690405-ed9bc980-d0fb-11ea-91d9-b8db9e5f4a04.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue. I'm not quite sure why the presence of the second `ion-nav` is causing this issue, but it definitely seems like a bug.

**Comment by cathypark** [comment]
I got the same issue too. My `@ionic/angular` version is `5.3.5`

**Comment by vlitv-rgu** [comment]
still not fixed, @ionic/angular ver is 5.5.0

**Comment by svrijsewijk** [comment]
Same issue, anyone got a workaround?

**Comment by svrijsewijk** [comment]
Not sure how helpful this is but it seems that `disconnectedCallback()` is called on the second ion-nav the moment it's instantiated.

[nav.tsx disconnectedCallback](https://github.com/ionic-team/ionic-framework/blob/11a59133d98994aa732d06de0f7e7c4113c56746/core/src/components/nav/nav.tsx#L123)

this sets this.destroyed to true. Which disables some crucial functions in the Nav instance:

[nav.tsx cleanup](https://github.com/ionic-team/ionic-framework/blob/11a59133d98994aa732d06de0f7e7c4113c56746/core/src/components/nav/nav.tsx#L949) this syncs the DOM

**Comment by cathypark** [comment]
@svrijsewijk I got same issue. Are you using nested ion-nav?

**Comment by svrijsewijk** [comment]
@cathypark I am using `ion-nav` nested inside an `ion-tab`. the experience is similar to Instagram.

**Comment by danishin** [comment]
We have the same issue and because of it cannot deploy new mobile app.
Could we have any update on this? @liamdebeasi
Our customers are loving the experience of ionic. Thank you always

**Comment by Yohandah** [comment]
I have the same issue which cause in some cases to have my IonNav with the attribute destroyed = true while it is not destroyed, so I cannot go back with .pop() even if .canGoBack() returns true !

**Comment by EslamNemr** [comment]
same with ionic vue

**Comment by EslamNemr** [comment]
i was able to solve this in ionic vue
the nav component return html element to framework delegate not vnode (component instance) which cause filtering the array of component instance not work and removing component instance

so the solution first modify removeviewfromdom function in framework delegate
https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/src/framework-delegate.ts
const removeViewFromDom = (parent, child) => {

        if (parent.tagName == 'ION-NAV') {
            if (child.children[0]) {
                removeFn(child.children[0].__vnode.ref.i.parent.uid);
                return Promise.resolve();
            }
        } else {
            Component && removeFn(Component);
            return Promise.resolve();
        }

    };

and modify removeview function in ionic nav component in vue 
https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/src/components/IonNav.ts

        const removeView = (component) => views.value = views.value.filter(cmp => cmp.children[0].component.uid !== component);

now the array compare the uid between components instance and if exist it will remove it and destroy component instance and remove dom element.

**Comment by sean-perkins** [comment]
Hello everyone 👋 this has been resolved in [6.2.0](https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#620-2022-07-27). Please let me know if you run into any issues.
