### ISSUE TITLE
After generating ionic android apk i install the apk it shows a blank screen 

### ISSUE THREAD

**Issue by Int-Eligence** [ionic-team/ionic-framework#21857]
In chrome console it shows 

local-ntp.js:2088 GET chrome-search://local-ntp/search-suggestions.js net::ERR_FAILED
requestAndInsertGoogleResources @ local-ntp.js:2088
init @ local-ntp.js:900

local-ntp.html:1 Invalid 'X-Frame-Options' header encountered when loading 'https://ogs.google.com/u/0/widget/app?origin=chrome-search%3A%2F%2Flocal-ntp&pid=1&spid=243&hl=en': 'ALLOW-FROM chrome-search://local-ntp' is not a recognized directive. The header will be ignored.

**Comment by BerkeAras** [comment]
@Int-Eligence Please fill out the Issue Template.

**Comment by Int-Eligence** [comment]
Issue solved after rebuilding android platform. Thank you.
