### ISSUE TITLE
feat: iOS 14 Context Menus

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21859]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
Adding the new context menus from iOS 14 would be a great new feature

**Describe Alternatives**
At the moment, popovers are very similar to context menus. They should be redesigned and the new animation should be added. The swipe-feature (known from #21052) should be added too.

**Additional Context**
Apple announced there context menus here: [https://developer.apple.com/videos/play/wwdc2020/10205/](https://developer.apple.com/videos/play/wwdc2020/10205/)

**Comment by roman-rr** [comment]
Seems can be realized as popup enhancement

**Comment by BerkeAras** [comment]
My first idea was, to create a new component (similar to ion-popover) because popovers are still existing in iOS 14 too. But the problem is, I don't know how to create new components for ionic :(
Isn't there a documentation or something?

**Comment by roman-rr** [comment]
@BerkeAras Exactly popovers. Listen event touchup then open popover by clientX, clientY.

**Comment by liamdebeasi** [comment]
Thanks for the issue! After discussion with the team, we have decided not to implement the new context menus found on iOS 14 at this time.

We do have plans to enhance `ion-popover` with additional features such as custom positioning (see https://github.com/ionic-team/ionic-framework/issues/21599).
