### ISSUE TITLE
Thanks for the issue. I am going to close this as this is now possible Ionic Framework.

### ISSUE THREAD

**Issue by daveshirman** [ionic-team/ionic-framework#21878]
Liam, this doesn't work, you get the error:

```
client:154 ./src/app/app.module.ts 57:34-55
"export 'mdTransitionAnimation' was not found in '@ionic/angular'
```

When trying your code.  Please unlock the thread and correct this!

Thanks for the issue. I am going to close this as this is now possible Ionic Framework.

Ionic Angular example:

```typescript
import { mdTransitionAnimation } from '@ionic/angular';

IonicModule.forRoot({
  navAnimation: mdTransitionAnimation
});
```

_Originally posted by @liamdebeasi in https://github.com/ionic-team/ionic-framework/issues/16829#issuecomment-639063238_

**Comment by liamdebeasi** [comment]
What version of Ionic Framework are you using?

**Comment by daveshirman** [comment]
```
ionic info

Ionic:

   Ionic CLI                     : 5.4.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 24 other plugins)

Utility:

   cordova-res : 0.15.1 
   native-run  : 0.2.8 (update available: 1.0.0)

System:

   ios-sim : 8.0.2
   NodeJS  : v10.16.0 (/Users/daveshirman/.nvm/versions/node/v10.16.0/bin/node)
   npm     : 6.14.0
   OS      : macOS Mojave
   Xcode   : Xcode 11.3.1 Build version 11C504


  ────────────────────────────────────────────────

     Ionic CLI update available: 5.4.5 → 5.4.16
            Run npm i -g ionic to update

  ────────────────────────────────────────────────
```

**Comment by liamdebeasi** [comment]
The export was added in as part of Ionic Framework v5.1.0. You need to upgrade to that version or newer to be able to use this feature.

**Comment by liamdebeasi** [comment]
I updated https://github.com/ionic-team/ionic-framework/issues/16829#issuecomment-639063238 to clarify this for others who may see it.

**Comment by daveshirman** [comment]
> I updated [#16829 (comment)](https://github.com/ionic-team/ionic-framework/issues/16829#issuecomment-639063238) to clarify this for others who may see it.

Ok thanks Liam, I was told this project was on V5, I specifically asked.

What's the syntax then for 4.8 to use the MD transition regardless of platform?

**Comment by liamdebeasi** [comment]
4.x does not have this functionality, so you will need to copy and paste the MD transition code into your application: https://github.com/ionic-team/ionic-framework/blob/master/core/src/utils/transition/md.transition.ts

**Comment by daveshirman** [comment]
This makes no sense Liam, the MD code is already in the app framework, why should I have to copy and paste the code into the project?

Additionally, when I DO copy and paste that code, I get broken references for `createAnimation()` and so on.

If you're going to answer a thread, at least please make sure the information you're providing to the community works / provide steps.  The documentation on this is particularly poor, so we need guidance from the Ionic team please!
