### ISSUE TITLE
bug: ion-fab-button close icon not showing on mouse over

### ISSUE THREAD

**Issue by leobaccili** [ionic-team/ionic-framework#21894]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When mouse over at fab button, close icon hides
**Expected behavior:**

Keep showing
**Steps to reproduce:**

https://ionicframework.com/docs/api/fab
Hover the mouse at examples
**Related code:**

```
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.2.0 (C:\Users\leobaccili\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 13 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.3.0
   native-run (update available: 1.0.0)   : 0.2.2

System:

   Android SDK Tools : 26.1.1 (H:\Android\sdk)
   NodeJS            : v10.15.3 (H:\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks! This issue has already been fixed, but the docs are running an outdated version of the framework. I will make sure the docs get the latest version of Ionic Framework.

**Comment by brandyscarney** [comment]
Here is the PR to update the demos: https://github.com/ionic-team/ionic-docs/pull/1601

Should be fixed soon on the site. 🙂
