### ISSUE TITLE
bug: background image on ion-content flickers in iOS 14 devices.

### ISSUE THREAD

**Issue by kumibrr** [ionic-team/ionic-framework#21892]
# Bug Report

**Ionic version: 6.11.0
[x] **5.x**

**Current behavior:**
When an ion-content has a background image set, the image flickers when anything on the view is touched. (like tapping an input).
**Expected behavior:**
Image should stay static.

**Steps to reproduce:**
I only tested on Apple devices, the app must be compiled and running on an iOS device. Flickering only happens on iOS 14. As i tested on two iPhone 11 and an iPad, one iPhone with iOS 13 and the other devices running iOS 14 developer beta 4.

**Related code:**
This is the related css code I apply to the content:

```
ion-content {
  --background: #fff url('../../../../../assets/img/background.svg') no-repeat center center/cover;
}
```
**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 18 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.18.2 (/usr/local/bin/node)
   npm        : 6.14.6
   OS         : macOS Big Sur
   Xcode      : Xcode 12.0 Build version 12A8169g
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is a problem with Safari/WebKit on iOS. The issue should not happen if the image is base64 encoded. I am going to close this as there is nothing actionable on our end as of now. Please see https://bugs.webkit.org/show_bug.cgi?id=195628 for more info.
