### ISSUE TITLE
feat: root config for each component to target platform

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21901]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I would like to change mode for each component through config.
ex
```
 IonicModule.forRoot({
IonToolBarMode: 'ios',
IonSearchBarMode: 'ios',
IonBackButtonMode: 'ios'
})
```
**Describe Preferred Solution**

option1. 
```
IonicModule.forRoot({
IonToolBarMode: 'ios',
IonSearchBarMode: 'ios',
IonBackButtonMode: 'ios'
})
```
option2.
```
IonicModule.forRoot({
iosModeComponent: ['IonToolBarMode', 'IonSearchBarMode'],
mdModeComponent: ['IonBackButtonMode']
})
```
**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as per-platform config is already possible in Ionic Framework. Please see: https://ionicframework.com/docs/angular/config#per-platform-config

**Comment by indraraj26** [comment]
Config option does not have ionToolbar option to set it mode: ios for all platforms

**Comment by liamdebeasi** [comment]
Can you please describe your use case for this feature? Typically we recommend setting the config globally in this instance.

**Comment by indraraj26** [comment]
In my application, I want to use mode="ios" for all toolbar, It is almost done, i hate to go on each page and component to add mode="ios" on ion-toolbar or basically any ion-component.

Why i am using mode="ios" with that my ion-title can be center even if i add more icons at start and end since this is not possible in MD specs.
