### ISSUE TITLE
bug: ion-menu-button with angular ssr doesn't work properly

### ISSUE THREAD

**Issue by pairmix** [ionic-team/ionic-framework#21918]
**Ionic version:**
[x] **5.3.0

**Current behavior:**
Ion-menu-button doesn't work properly when using angular ssr

**Expected behavior:**
ion-menu-button should work properly

**Steps to reproduce:**
````
ionic start menu-ssr sidemenu --type angular
cd menu-ssr
ng update @angular/core @angular/cli
npm install @angular/animations
ng add @nguniversal/express-engine
npm install @ionic/angular-server
npm run build:ssr 
````

If i do 'npm run start' and go to http://localhost:4200 (reduce window to show ion-menu-button), it works fine.
BUT if i do 'npm run serve:ssr' and go to http://localhost:4000 (reduce window to show ion-menu-button), that doesn't work

**Other information:**

**Ionic info:**

```
λ ionic info

Ionic:

   Ionic CLI                     : 6.10.0 (C:\Users\Adolphe\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.0
   @angular-devkit/build-angular : 0.1000.4
   @angular-devkit/schematics    : 10.0.4
   @angular/cli                  : 10.0.4
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   NodeJS : v12.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.10.3
   OS     : Windows 10
```

**Comment by mhartington** [comment]
Are you including the `@ionic/angular-server` module in here?

https://ionicframework.com/blog/ssr-with-angular-universal-and-ionic/

**Comment by pairmix** [comment]
> 
> 
> Are you including the `@ionic/angular-server` module in here?
> 
> https://ionicframework.com/blog/ssr-with-angular-universal-and-ionic/

Yes i did

**Comment by liamdebeasi** [comment]
Can you provide a repo we can use to reproduce the issue? I am not able to reproduce it using a menu starter app.

**Comment by pairmix** [comment]
> 
> 
> Can you provide a repo we can use to reproduce the issue? I am not able to reproduce it using a menu starter app.

Here it is @liamdebeasi : 

https://github.com/pairmix/menu-ssr.git
