### ISSUE TITLE
bug: [@ionic/angular][reactive forms] Mark `ion-item` and `ion-input` as touched when corresponding form control has been marked as touched

### ISSUE THREAD

**Issue by jadurani** [ionic-team/ionic-framework#21910]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Kindly see: https://ionic-angular-v5-bez9r7.stackblitz.io

1. Leave the required input field as empty (do not click on it)
2. Click the submit button
3. Nothing happens -- the input field does not show the "red" underline for invalid fields

**Expected behavior:**

The input field should show the "red" underline when the form control has been marked as touched programmatically, without the user having to click on the input field itself.

**Suggested fix:**

- Replace `ion-untouched` css class with `ion-touched` in the elements `ion-item` and `ion-input` when the form and/or its descendants have been marked as touched (has `ng-touched` class)

**Other info:**

- Before any user interaction:
![Screenshot from 2020-08-12 10-15-08](https://user-images.githubusercontent.com/11599005/89968182-c6a9cf80-dc85-11ea-9612-9647862e11cf.png)
  - NOTES:
    -  `ion-item` and `ion-input` have the css class `ion-untouched`
    -  `form` and `ion-input` have the css class `ng-untouched`

- After marking the form as touched (programmatically, with `this.sampleForm.markAllAsTouched()`:
![Screenshot from 2020-08-12 10-15-32](https://user-images.githubusercontent.com/11599005/89968180-c578a280-dc85-11ea-8993-2322a86bcb81.png)
  - NOTES:
    - `ion-item` and `ion-input` **still** have the css class `ion-untouched`
    - `form` and `ion-item` elements now have `ng-touched` instead of `ng-untouched`

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.9.0 
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.901.5
   @angular-devkit/schematics    : 9.1.5
   @angular/cli                  : 9.1.5
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.14.0
   npm    : 6.13.4
   OS     : Linux 5.4
```

**Comment by liamdebeasi** [comment]
Please update to Ionic Framework v5.2.0 or newer. This issue has already been fixed.
