### ISSUE TITLE
bug: SwiperJS API is not applicable on IonSlides.

### ISSUE THREAD

**Issue by pritamsoni-hsr** [ionic-team/ionic-framework#21913]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Swiper JS all API features are not working, only some of them are.

**Expected behavior:**

some custom methods are provided which is great, but a lot of API events are not working, to name a few, `slideNextTransitionStart`, `transitionStart`, `touchStart`, `slideChangeTransitionStart` none is working.

**Steps to reproduce:**

**Related code:**

```ts
  function demo() {
    console.log("abc");
  }
  const opts = {
    ...
    on: {
      beforeInit: function () {
        const swiper = this as any;
        console.log(swiper);
      },
      slideNextTransitionStart: demo,
      transitionStart: demo,
    },
  };
  ...
<IonSlides  {...opts}>
        ...
</IonSlides>

```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
