### ISSUE TITLE
feat: Shadow parts for ion-progress-bar

### ISSUE THREAD

**Issue by TDivDev** [ionic-team/ionic-framework#21914]
**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
Now there are no shadow parts for the ion-progress-bar. Shadow parts for styling the class "progress" and "progress-buffer-bar" within the shadow root would be great.

**Describe Preferred Solution**
Shadow parts for the ion-progress-bar. One shadow part for the div element with class "progress" and another shadow part for the div element "progress-buffer-bar".

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe how you would use these shadow parts? The progress bar component requires some updates on our end to the CSS before Shadow Parts become effective.

**Comment by TDivDev** [comment]
Hi,
we would use shadow parts like other parts in ionic components e.g. “ion-select”. Here we can use the part “placeholder” or “icon”.

For ion-progress-bar we would use a shadow part (e.g. “native”) like the following:

`
ion-progress-bar::part(native) {
  background-image: linear-gradient(to bottom, #DDD 0%, #CCC 100%);
}
`

So we can use gradient backgrounds for progress bars.

Best Regards

**Comment by liamdebeasi** [comment]
Thanks for the follow up. You can do that already using CSS Variables:

```css
ion-progress-bar {
  --progress-background: linear-gradient(to bottom, #DDD 0%, #CCC 100%);
}
```

You can customize other parts of the progress bar too: https://ionicframework.com/docs/api/progress-bar#css-custom-properties

Is there anything else you would use Shadow Parts for that is not covered by CSS Variables?

**Comment by TDivDev** [comment]
Hi Liam,
sorry, yes you´re absolutely right! I always testet the linear-gradient with the inner div elements (with class progress and progress-buffer-bar). 

By the way: really good decision to add the concept of CSS Shadows Parts. 
If there is anything else I would use Shadow Parts for that is not covered by CSS Variables, I would open a new issue, ok?

Best regards, Timm

**Comment by liamdebeasi** [comment]
Glad it is working now! I will close this since the original issue is resolved. If you run into another scenario where you feel Shadow Parts can help, please feel free to open a new issue.
