### ISSUE TITLE
bug: ion-title in ion-menu is visible while opening menu on iOS

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21927]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
`ion-title` in `ion-menu` is visible while opening menu (swiping) on iOS

**Expected behavior:**
`ion-title` should not be visible until it has been opened.

**Steps to reproduce:**
Just swipe to right slowly.

**Related code:**
Codepen: [https://codepen.io/BerkeAras/pen/yLOJOYE](https://codepen.io/BerkeAras/pen/yLOJOYE)

**Comment by liamdebeasi** [comment]
Thanks for the issue. I made a mistake when originally triaging this as this is not a bug in Ionic Framework. When using the collapsible large title you need to have `fullscreen="true"` set on the main page's `ion-content`. Adding this resolves the issue.
