### ISSUE TITLE
bug: ion-button hover do content jump and height re-calculation

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#21923]
# Bug Report

![ezgif-7-54d40ada7055](https://user-images.githubusercontent.com/10646478/90335456-60afa600-dfff-11ea-9bdf-ea5e48ba3dbc.gif)

**Ionic version:**
[x] **5.x** (Only iOS safari and wkWebView related)

**Current behavior:**
height re-calculated and content do jump when hover `ion-button` on page initialization. 
Reproduced only with ion-button

**Steps to reproduce:**
```bash
$ git clone https://github.com/roman-rr/ionic-page-height.git
$ cd ionic-page-height
$ npm i 
$ ionic serve
```
- Open app with safari or iOS WkWebView
- Click `Go Child page` button
- Quickly scroll to bottom
- Hover `ion-button` element

Height will recalculated and content do jump. 

**Related code:**
https://github.com/roman-rr/ionic-page-height

**Other information:**

**Comment by liamdebeasi** [comment]
I can reproduce the issue. Seems to be a WebKit bug, but I need to investigate this more.

**Comment by roman-rr** [comment]
Note that bug disappear with button absolutely positioned.

**Comment by BerkeAras** [comment]
@roman-rr Which iOS Version do you use? At the moment there are a few WebKit Bugs in the iOS 14 Betas.

**Comment by roman-rr** [comment]
@BerkeAras Issue reproductive with just Safari. For iOS WkWebView 13-14 also.
Most annoyance has in bug that you are push button and button run away up.
