### ISSUE TITLE
bug: keyboard covers over ion-alert (Android)

### ISSUE THREAD

**Issue by somq** [ionic-team/ionic-framework#21924]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
Keyboard floats over the alert inputs, preventing the user to type text in.

**Expected behavior:**
Alert should float above the keyboard

**Steps to reproduce:**

 (small sized screen helps)

- create an alert
- open the keyboard
- *alert does not move up*

**Addionnal**

This behavior might exist for other components.

**Comment by somq** [comment]
Workarounds:

- A [directive](https://gist.github.com/Manduro/bc121fd39f21558df2a952b39e907754) but we can't access the ion-alert component.
- [Capacitor prompt modal](https://capacitorjs.com/docs/apis/modals) but it does not support having multiple inputs.

**Comment by somq** [comment]
[Quickfix](https://gist.github.com/somq/7dcfca8dbaaa77a80130b7d4d0e4688f)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
