### ISSUE TITLE
bug: Ionic 4/5: NavController.pop() does not work after a route change with reused component

### ISSUE THREAD

**Issue by Schwankenson** [ionic-team/ionic-framework#21926]
# Bug Report

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**
After using `this.navController.navigateForward(newPath);` to switch route while reusing the current component (page), `NavController.pop()` does not work anymore.

**Expected behavior:**
`NavController.pop()` should go to the last path and last component state

**Steps to reproduce:**
**Related code:**
I broke this down to a stackblitz.com example:

[RouteReuseStrategy][1] (app.module.ts)  
[Page][2] (tabs.page.ts)

When the line `{ provide: RouteReuseStrategy, useClass: MyRouteReuseStrategy }` in `app.module.ts` is changed to `{ provide: RouteReuseStrategy, useClass: IonicRouteStrategy }`, the NavController.pop() works like expected, but the component is reloaded on every filter change.

  [1]: https://stackblitz.com/edit/ionic-5-angular-10-start-template-37gt6f?file=src/app/app.module.ts
  [2]: https://stackblitz.com/edit/ionic-5-angular-10-start-template-37gt6f?file=src%2Fapp%2Ftabs%2Ftabs.page.ts

**Comment by Schwankenson** [comment]
@mhartington Are you sure, that this should be the behaviour of the NavController for a framework, which is intended to be used for PWAs?

- I need to reuse a component on filter change. Reloading the complete page on filter change is not user friendly. Speed is one of the most important topics in an app. Users are used to not see any flickering when updating a filter in an app.
- We need to update the URL in a PWA. Thats a web default: It needs to be possible to share the current URL with other people, in social networks and so on, and it is important that the link shows exactly the page/filter which the user sees

Or is my idea on how to do this wrong, and this can be done in Ionic / Angular in another way?

**Comment by mhartington** [comment]
Let's move the conversation over to the forum, as this is now outside of the scope of an issue.

http://forum.ionicframework.com

**Comment by Schwankenson** [comment]
@mhartington Ok, I created a [topic in the ionic forum](https://forum.ionicframework.com/t/ionic-4-5-reuse-a-component-on-filter-change-while-updating-the-url/194729)
