### ISSUE TITLE
bug: Anmation display under image

### ISSUE THREAD

**Issue by weathon** [ionic-team/ionic-framework#21934]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

![image](https://user-images.githubusercontent.com/41298844/90575464-0e968e00-e181-11ea-94b1-ad431a233ee2.png)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
```html
  <ion-card style="background-image:url('./assets/beta.png');background-size:100% 100%;background-size: cover,cover;background-position: 50% 50%;">
      <ion-card-header style="background:rgba(44, 44, 44,0.5);width:50%">
        <ion-card-title style="font-size: large;color:white;opacity:1">Beta Group</ion-card-title> 
        <ion-card-subtitle style="color:lightgray">2 People Joined</ion-card-subtitle>
      </ion-card-header>
  </ion-card>
```

**Comment by indraraj26** [comment]
Hi, is it possible for you to create repo with minimal code to reproduce

**Comment by weathon** [comment]
@indraraj26 I am sorry, this is my bad. I forget to put things in the ion-content
