### ISSUE TITLE
bug: interaction with component is not available inside ion-reorder tag

### ISSUE THREAD

**Issue by archzaiko** [ionic-team/ionic-framework#21937]
# Bug Report

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**
It is impossible to change the state of a component (e.g. ```<ion-checkbox>```) when it is placed inside the ```<ion-reorder>``` tag of ```<ion-reorder-group>``` even if the group is disabled (```[disabled]="true"```)
![reorder-actual](https://user-images.githubusercontent.com/21239914/90747965-3ea57480-e2da-11ea-87ea-82a3c0630b6b.gif)

**Expected behavior:**
State of a component is changed after user interaction when the component is placed inside the ```<ion-reorder>``` tag of ```<ion-reorder-group>```
Should components be interactive if ```<ion-reorder-group>``` has the ```[disabled]="false"``` property?

**Steps to reproduce:**
* run an ionic application with following template
```HTML
<ion-reorder-group [disabled]="false">
  <ion-reorder>
    <ion-item>
      <ion-label>Checkbox</ion-label>
      <ion-checkbox></ion-checkbox>
    </ion-item>
  </ion-reorder>
</ion-reorder-group>
```
* try to check ```<ion-checkbox>```
* change the ```[disabled]``` property of ```<on-reorder-group>``` to ```true```
* try to check ```<ion-checkbox>```

**Related code:**
A sample application via GitHub: https://github.com/archzaiko/ionic-contributing.git

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.0 (...\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.6
   @angular-devkit/schematics    : 10.0.6
   @angular/cli                  : 10.0.6
   @ionic/angular-toolkit        : 2.3.0

Utility:

   cordova-res                          : not installed
   native-run (update available: 0.2.9) : 0.2.8

System:

   NodeJS : v10.20.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.11.3
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Whoops, looks like there is already an open issue for this. I am going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/21017. (I will still look at your PR though!)
