### ISSUE TITLE
bug: page navigation issue (screen flashes) on iOS 14 beta 5

### ISSUE THREAD

**Issue by perr124** [ionic-team/ionic-framework#21957]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
app glitches(screen flashes & doesn’t make the transition) when navigating to some specific pages in ios 14 beta 5. I have tested the same version of my app in TestFlight on an iOS14 beta 4 and iOS 13 and both don't have this issue.

**Expected behavior:**
Pages should open consistently

**Steps to reproduce:**
Open any of your ionic apps in iOS14 beta 5 and click around. Or, Go to the repo app and try opening "item 2" on an iPhone with iOS 14 beta 5. Screen will flash and not make transition to 'detail' but works fine in web.  https://ios-repro.web.app/list 

**Other information:**
Only on iOS 14 beta 5 now.

**Ionic info:**
Ionic:

   Ionic CLI                     : 5.4.12 (C:\Users\PerryKankam\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.1000.2
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 10.0.2
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (6 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v10.21.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.3
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is a WebKit bug that has already been fixed: https://bugs.webkit.org/show_bug.cgi?id=215622. Expect to see this fixed in an upcoming iOS 14 beta.
