### ISSUE TITLE
ion-range's ionChange event emitter emits fractional numbers unexpectedly

### ISSUE THREAD

**Issue by cmer4** [ionic-team/ionic-framework#21968]
**Ionic version:**
[ ] **4.x**
[x] **5.3.1**

**Current behavior:**
Given the following code:

```
    <ion-range [min]="option.min" [max]="option.max"
      [step]="option.step" (ionChange)="log($event); option.value = $event.target.value">
    </ion-range>
```

```
export class AppComponent {

  option: = {
          type: "range",
          label: "Distance",
          name: "distance",
          step: 0.05,
          min: 0,
          max: 1,
          value: 0.1
  }

  log(event) {
    console.log(event.target.value)
  }

}
```
We can observe fractional numbers (0.35000000000000003) assigned as input value.

**Expected behavior:**
The value should not be fractional number.

**Steps to reproduce:**
https://stackblitz.com/edit/ionic-angular-v5-ic1yf2?file=src/app/app.component.ts

Or just create ion-range with steps below 1 (e.g. 0.05 as a step)

I guess this relates to Javascript's specificity (quirk)?:
Numbers in JavaScript are "double-precision 64-bit format IEEE 754 values", according to the spec...

So if we would use standard HTML input type range:

```
<input type="range" [min]="option.min" [max]="option.max"
      [step]="option.step" onchange="console.log(event.target.value)"/>
```
Then there is no fractional value.

Not sure what is the best to address this but at the least we could remind of the 0.1 + 0.2 = 0.30000000000000004 issue in Javascript and that developer has to "toFixed" this situation?

**Comment by amandaejohnston** [comment]
This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27375 and the fix will be available in a future release of Ionic. Thank you!
