### ISSUE TITLE
bug: infinite scroll not working as Docs

### ISSUE THREAD

**Issue by m7ammad7assan** [ionic-team/ionic-framework#21965]
Ionic CLI                     : 5.4.16 (C:\Users\mhs4c\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.7
   @angular-devkit/schematics    : 10.0.7
   @angular/cli                  : 10.0.7
   @ionic/angular-toolkit        : 2.3.2

Utility:

   cordova-res : 0.3.0
   native-run  : 0.1.2

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

**Current behavior:**
 infinite scroll not working as Docs, loadMore() not called ever

**Expected behavior:**
loadMore should be called

**Related code:**

html file:

<ion-content >

    <p>to long data</p>

    <ion-infinite-scroll #infiniteScroll threshold="200px" (ionInfinite)="loadMoreData($event)">

        <ion-infinite-scroll-content
                loadingSpinner="spinners"
                loadingText="dfg نسيبة">

        </ion-infinite-scroll-content>
    </ion-infinite-scroll>
</ion-content>`

type script:

export class Tab3Page {

    @ViewChild(IonInfiniteScroll) infiniteScroll: IonInfiniteScroll;

    constructor() {
    }

    loadMoreData(event) {
        console.log('Done');
        setTimeout(() => {
            // console.log('Done');
            event.target.complete();

            // App logic to determine if all data is loaded
            // and disable the infinite scroll
            // if (data.length == 1000) {
            // event.target.disabled = true;
            // }

        }, 500);
    }
}

**Comment by m7ammad7assan** [comment]
you can see my code as html file and type script, to reproduce the issue when just scroll down the loadMore not triggered at all

**Comment by m7ammad7assan** [comment]
<p>to long data</p>

<ion-infinite-scroll #infiniteScroll threshold="200px" (ionInfinite)="loadMoreData($event)">

    <ion-infinite-scroll-content
            loadingSpinner="spinners"
            loadingText="dfg نسيبة">

    </ion-infinite-scroll-content>
</ion-infinite-scroll>




loadMoreData(event) {
    console.log('Done');
    setTimeout(() => {
        // console.log('Done');
        event.target.complete();

        // App logic to determine if all data is loaded
        // and disable the infinite scroll
        // if (data.length == 1000) {
        // event.target.disabled = true;
        // }

    }, 500);
}

**Comment by liamdebeasi** [comment]
Hi there, code snippets are not typically enough to reproduce the issue. Can you please reproduce this issue in a blank Ionic starter application and post the link to the repo here?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
