### ISSUE TITLE
Checked attribute on IonSegmentButton not available

### ISSUE THREAD

**Issue by rluttikhuizen** [ionic-team/ionic-framework#21961]
Hello,

We're using Ionic React 5.0.7. 

The documentation (https://ionicframework.com/docs/api/segment-button) mentions that there are 2 ways of setting the default (initial) value for segments:

* Using "value" on the IonSegment
* Using "checked" on the IonSegmentButton

The second option doesn't seem to work: 

Property 'checked' does not exist on type 'IntrinsicAttributes & IonSegmentButton & Pick<HTMLAttributes<HTMLIonSegmentButtonElement>

This might be a documentation issue. We're using the "value" attribute on IonSegment for now.

Thanks,

Ronald

**Comment by liamdebeasi** [comment]
Thanks for the issue. Apologies for the confusion, that documentation is outdated. With Ionic Framework v5 we removed the `checked` property from IonSegmentButton in favor of the `value` property on IonSegment: https://github.com/ionic-team/ionic-framework/blob/master/BREAKING.md#segment-button

I will submit a PR that resolves this.

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/21966. Thank you!
