### ISSUE TITLE
bug (searchbar): searchbar-search-icon width is not getting applied 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#21960]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I would like to have small icon, There is no custom properties available that can be applied to search-icon
link: https://codepen.io/indraraj26/pen/RwaKMgG

**Expected behavior:**

It should apply my width

**Steps to reproduce:**

**Related code:**

html 
```
    <ion-searchbar class="my-custom-searchbar"></ion-searchbar>
```

css
```
.my-custom-searchbar .searchbar-input-container .searchbar-input .searchbar-search-icon  {
  width: 10px !important;
}
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
You are targeting the wrong class. It should be:

`.my-custom-searchbar .searchbar-input-container .searchbar-search-icon`

not 

`.my-custom-searchbar .searchbar-input-container .searchbar-input .searchbar-search-icon`

**Comment by indraraj26** [comment]
I don't know why i am so bad in targeting element with nested css 
sorry
