### ISSUE TITLE
bug: IOS Button with prop type="button" looks odd in iOS

### ISSUE THREAD

**Issue by spencerpauly** [ionic-team/ionic-framework#21974]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Ionic button with type='button' has a weird styling on iOS. Button is still functional but just looks odd. I've determined that removing the explicit type='button' fixes the issue.

**Expected behavior:**

Shouldn't have that white-opaque background button look to it:

**Steps to reproduce:**

- Use Ionic React.
- Create an IonButton like the following:
```
<IonButton type='button'>
    Text
</IonButton>
```
- Build for iOS Capacitor by running `ionic cap copy ios`
- View in iOS emulator
Button will similar to:
![Screen Shot 2020-08-25 at 1 31 33 PM](https://user-images.githubusercontent.com/28174559/91213494-4cdb0280-e6d7-11ea-8b75-e3bcafc76d27.png)

**Related code:**
```
<IonButton type='button'>
    Text
</IonButton>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.2.3

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.4.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina```

**Comment by indraraj26** [comment]
somebody had similar issue forum: https://forum.ionicframework.com/t/button-css-does-not-work-on-ios-devices-bad-appears/194926

It worked when he removed type=submit

**Comment by BerkeAras** [comment]
@spencerpauly What if you add this to the style of the button?:

```css
-moz-appearance: none;
-webkit-appearance: none;
appearance: none;
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
