### ISSUE TITLE
bug: no animation on redirect route (react)

### ISSUE THREAD

**Issue by doender** [ionic-team/ionic-framework#21971]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
With the following routes:

```
<IonRouterOutlet>
        <Route path="/learn/dashboard" component={LearnDashboardPage} />
        <Route path="/learn/lesson/:lessonId" component={LessonPage} />
        <Route path="/learn" exact render={() => <Redirect to="/learn/dashboard" />} />
    </IonRouterOutlet>
```

when routing to `/learn` (which redirects to `/learn/dashboard`) no transition animation is shown. However, when routing directly to `/learn/dashboard` the transition is correctly displayed.

**Expected behavior:**
Transitions are shown on redirects

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
