### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by saurav-hd** [ionic-team/ionic-framework#21975]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
On some Android/IOS devices (regardless of the OS version), scrollToBottom does not work. The page opens at the top, instead of the bottom.

**Expected behavior:**
The page should open with the focus at the latest entry (bottom)

**Steps to reproduce:**
The following devices are having issues with scrollToBottom

1. Device: Pixel 1 OS - Android 10
2. Device - one plus 7 OS - Android  10
3. Device - Iphone pro OS - IOS  13

**Related code:**
`ionViewDidEnter() {
this.mutationObserver = new MutationObserver((mutations) => {
this.scrollToBottom();
})
const targetNode = this.chatList.nativeElement;
const config = { attributes: true, childList: true, subtree: true };
this.mutationObserver.observe(targetNode, config);
}
scrollToBottom(event?: any) {
setTimeout(()=>{this.content.scrollToBottom(0);},500);
}`

A sample application via GitHub

StackBlitz (https://stackblitz.com)
Ionic Angular StackBlitz: https://stackblitz.com/edit/ionic-v4-angular-tabs

Plunker (http://plnkr.co/edit/cpeRJs?p=preview)

-->

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
