### ISSUE TITLE
bug: Ionic Ripple, touchstart event getting attached multiple times and makes the ripple darker

### ISSUE THREAD

**Issue by jkprem31** [ionic-team/ionic-framework#21980]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

In an app, if there are multiple layouts, one for mobile and another for web, each have <ion-app> which gets re-rendered  as per the screen size.
On every ion-app re-render the touchstart event gets attached to the document multiple times, because of which the ripple keeps getting darker.

**Expected behavior:**

Ideally the previously attached events should be removed before the ion-app gets destroyed. And while re-rendering of the ion-app only required events should be attached

**Steps to reproduce:**

Using @ionic/core -- version -- 5.3.1 
In an SPA, create two pages with different layouts, both having ion-app. 
Move between these two pages, and check getEventListeners(document) in browser console, there would be duplicate handlers on the event touchstart.

I found that this event is getting applied two times 
one from tap-click module -- doc.addEventListener('touchstart', onTouchStart, true);
another from focus-visible module -- doc.addEventListener('touchstart', pointerDown);

On first load

![image](https://user-images.githubusercontent.com/25884624/91298453-b3d2e700-e7bd-11ea-87db-4eaa01e2a0e8.png)

After re-rendering the ion-app

![image](https://user-images.githubusercontent.com/25884624/91298600-f1377480-e7bd-11ea-8225-2200771ae4db.png)

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
