### ISSUE TITLE
bug: shadowRoot property is null in Jest tests with React Testing Library

### ISSUE THREAD

**Issue by RyanMcDonald** [ionic-team/ionic-framework#21987]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

`shadowRoot` property is `null` on all nodes rendered by React Testing Library.

**Expected behavior:**

I should be able to access `document.querySelector('ion-button').shadowRoot`, for example.

**Steps to reproduce:**

1. Use React Testing Library to render any Ionic React component.
2. Query for the element and access its `shadowRoot` property.

**Other information:**

I'm running Jest with `--env=jest-environment-jsdom-sixteen` which is using jsdom `16.2.2` so it should have Shadow DOM support.

I might just be missing a piece of information here, because I'm not super familiar with Web Components. I am able to query the `shadowRoot` for the components in the browser just fine.

Being able to access the Shadow DOM would help with testing, since it's not very useful to only have access to the top-level Web Components like `ion-button`.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.16
   Ionic Framework : @ionic/react 5.3.1

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support question related to testing. We use this tracker exclusively for Ionic Framework bugs and feature requests. 

I recommend asking your question on our forums: http://forum.ionicframework.com/. That being said, we do not typically recommend querying the internals of Ionic components for your tests as they tend to duplicate testing that is already done within the framework.
