### ISSUE TITLE
bug: Bounce animation in iOS jumps to Zero-position when focusing button

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#21989]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
The bounce animation in iOS jumps to the Zero-position when focusing something while swiping up and down. (See video)

**Expected behavior:**
The bounce animation should work properly.

**Steps to reproduce:**
Just touch the button and swipe down and unfocus the button. The bounce animation of iOS does not work here and it will jump to the 0-position.

**Related code:**
Git-Repo: [https://github.com/EatsApp/ionic-5-bounce-issue](https://github.com/EatsApp/ionic-5-bounce-issue)

**Other information:**
Video: [https://youtu.be/-ucBKa9DL-Y](https://youtu.be/-ucBKa9DL-Y)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is a bug in WebKit, not Ionic Framework. I have already reported this to the WebKit team here: https://bugs.webkit.org/show_bug.cgi?id=209968

**Comment by BerkeAras** [comment]
@liamdebeasi Oh, that's an WebKit Issue too, I'm so sorry for opening this issue :(

Thanks for reporting!!!

**Comment by BerkeAras** [comment]
iOS 14 Beta 7, and no fix :(
