### ISSUE TITLE
bug: Navigating from one page to another necessarily calls ionViewDidEnter on the original page after it has been unmounted

### ISSUE THREAD

**Issue by ashleydavis** [ionic-team/ionic-framework#22006]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**

Navigating from one page to another necessarily calls ionViewDidEnter on the original page when leaving it and after it has been unmounted. Calls to setState in this function result in this warning on page transitions `Can't perform a React state update on an unmounted component`.

**Expected behavior:**

ionViewDidEnter should not be called when leaving a page.

**Steps to reproduce:**

Minimal example application here: https://github.com/ashleydavis/ionic-set-state-issue

Clone or download that repo. Run `npm install` and then `ionic serve`. You can trigger the error by clicking *Click me to trigger the problem*.

**Related code:**

Minimal example application:

https://github.com/ashleydavis/ionic-set-state-issue

Created with:

```
ionic start ionic-set-state-issue blank --type=react --typescript
```

**Other information:**

![error](https://user-images.githubusercontent.com/625126/91650906-13d0d280-eac9-11ea-8f89-4c4157f494fb.png)

**Ionic info:**

```
> ionic info

Ionic:

   Ionic CLI       : 6.11.7 (C:\Users\ash\AppData\Roaming\nvm\v12.18.1\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.3.2

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.18.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10
```

My companies pays for Ionic, does that help get this looked at?

**Comment by liamdebeasi** [comment]
I was able to reproduce this issue. Ionic Framework is free to use, but if your company pays for Enterprise Support, they should get in touch with us through the Enterprise Support channels.

**Comment by elylucas** [comment]
Hi @ashleydavis,

I'm starting to look into this issue and wanted to ask a question.

You are giving your `PostScreen` component a new key based on the route params that get passed in. This will cause React to unmount and remount the component each time. Since you technically only have one page with a variable route param, is that what you intended? Removing the key from the `PostScreen` causes the error to go away.

Thanks

**Comment by ashleydavis** [comment]
Yes, I want the component to mount/unmount when viewing a different post.

It only has one page because I've given you a minimal example.

My actual application has many pages.

**Comment by elylucas** [comment]
Hi @ashleydavis,

Same situation here as in #22007. You could probably work around it using the same suggestions in the other bug.

Thanks

**Comment by ashleydavis** [comment]
I already know how to work around it.

I was hoping for a fix to the bug that's in Ionic.
