### ISSUE TITLE
bug: ion-button click doesn't work anymore

### ISSUE THREAD

**Issue by dvdknaap** [ionic-team/ionic-framework#22003]
Since today the click event for ion-button isn't working anymore 
The console isn't giving any error on my android device and in the browser

All my pages does have this problem suddenly where they were working.

I also tried to undo all my changes that i've made but it's still not reacting.

# Bug Report

**Ionic version:**
6.11.6

**Steps to reproduce:**
Create a simple page with html:
```html

    <ion-button button="true" (click)="test()">
       Test
    </ion-button>
```

Add the next function in the page.ts
```js

    test() {
        alert('ja');
    }
```

**Comment by indraraj26** [comment]
Hi, 
please provide small reproduction via github.
With above code i am not able to reproduce at my end.

**Comment by BerkeAras** [comment]
@dvdknaap Which Ionic Version do you use? 6.11.6 is probably the version of the CLI.

**Comment by dvdknaap** [comment]
> @dvdknaap Which Ionic Version do you use? 6.11.6 is probably the version of the CLI.

Indeed sorry It's the latest version v4

**Comment by dvdknaap** [comment]
> @dvdknaap Which Ionic Version do you use? 6.11.6 is probably the version of the CLI.

Ionic:

   Ionic CLI                     : 6.11.6 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.7
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, android 8.1.0, browser
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 10 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.0.0) : 0.2.2

System:

   Android SDK Tools : 26.1.1 (/home/danny/Android/Sdk)
   NodeJS            : v12.18.3 (/usr/bin/node)
   npm               : 6.14.8
   OS                : Linux 5.4

**Comment by BerkeAras** [comment]
@dvdknaap Okay, you are using ionic 5.3.2. Can you demonstrate the bug? You can share your code [here](https://stackblitz.com/edit/ionic-angular-v5) or by creating a new Repository.

**Comment by dvdknaap** [comment]
> Hi,
> please provide small reproduction via github.
> With above code i am not able to reproduce at my end.

Hi,

I hope i have some remove sensitive info because it's an real life app.

https://github.com/dvdknaap/bugbuttonclick

Hope you can find something when you use this repo and set it on your android device you will see that when you touch the button nothing happens and there is no error in the console

**Comment by indraraj26** [comment]
This is not how you setup tab routing, it is taking full height over on page
Just remove <app-bottom-menu><app-bottom-menu>
Please look at the starter kit: https://github.com/indraraj26/ionic5-starter-tabs-sidemenu

**Comment by dvdknaap** [comment]
@indraraj26  So whats wrong then just remove that part is not an option.

I saw that in src/app/component/bottom-menu/bottom-menu.component.html that i have removed to much so just add the closing tags yourself because they are there in the actual app.
