### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by manel00** [ionic-team/ionic-framework#22005]
# Bug Report

**Ionic version:**
[X] **4.x**

**Current behavior:**
Doing Ionic serve

**Expected behavior:**
It should run, but it crashes

**Steps to reproduce:**
"dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@capacitor/android": "^1.0.0",
    "@capacitor/cli": "^1.0.0",
    "@capacitor/core": "^1.0.0",
    "@ionic-native/camera": "^5.8.0",
    "@ionic-native/core": "^5.8.0",
    "@ionic-native/email-composer": "^5.9.0",
    "@ionic-native/local-notifications": "^5.28.0",
    "@ionic-native/photo-library": "^5.8.0",
    "@ionic-native/social-sharing": "^5.8.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.9.0",
    "@ionic/angular": "^4.1.0",
    "@ionic/lab": "^2.0.2",
    "angularfire2": "^5.2.1",
    "cordova-android": "^7.1.4",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-email-composer": "^0.9.2",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.1.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "5.4.7",
    "core-js": "^2.5.4",
    "es6-promise-plugin": "4.2.2",
    "firebase": "^7.19.1",
    "ngx-socket-io": "^3.2.0",
    "node-fetch": "^2.6.0",
    "rxjs": "~6.5.1",
    "translate": "^1.1.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
  }

**Other information:**
[error] Error: Cannot find module '@angular/compiler-cli/src/tooling'
Require stack:
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@ngtools/webpack/src/index.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/index.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/models/architect-command.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/commands/run-impl.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/utilities/json-schema.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/models/command-runner.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/lib/cli/index.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/lib/init.js
- /home/manel/Documentos/Ionic_projects/myxstories/xstories/node_modules/@angular/cli/bin/ng

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.6 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 7.3.10
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.5.3
   @capacitor/core : 1.5.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 10 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/home/manel/Android/Sdk)
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : Linux 4.13```

**Comment by dvdknaap** [comment]
If you do`npm i @angular/compiler-cli` it should be fixed

**Comment by manel00** [comment]
No, it doesn't fix it, once more it comes to the same situation:

found 17 vulnerabilities (9 low, 3 moderate, 5 high)  //**Ionic serve** It works but with errors on the UI

then I run **npm audit fix**  //Not working **Ionic serve**

then it comes this error i posted  //Still not working **Ionic serve**

and then **npm i @angular/compiler-cli** and it turns like the start (17 vulnerability)

**Comment by indraraj26** [comment]
kindly ignore the vulnerability that you will fix in upcoming version
`npm i @angular/compiler-cli --save-dev`
`ionic serve`

Note: do not run `npm audit fix`

**Comment by manel00** [comment]
It doesn't work the app properly, that's why

**Comment by indraraj26** [comment]
we don't know whats not working, It is not necessary to run `npm audit fix`
Please provide repo to reproduce the issue at our end
