### ISSUE TITLE
feat:   vue page component transition between stack navigation like "ion-vue-router"

### ISSUE THREAD

**Issue by lewdea** [ionic-team/ionic-framework#22004]
# Feature Request

**Ionic version:**

 **4.11**

**Describe the Feature Request**

We've seperated our app into serveral modules. Each module has a root ion-vue-router and serveral child components.  Now, within a single stack navigation, the page transition is working properly. However, when it comes to pages jump between two ion-vue-routers， there's no transitions at all which is not friendly to users.  

**Describe Preferred Solution**

Add page transitions between multiple stack navigation.

**Describe Alternatives**

I can't see another solution or alternative for now.

**Related Code**

**Additional Context**

loom video:     https://www.loom.com/share/c7e325cd95c9417286217c4f32bb06ac

**Comment by liamdebeasi** [comment]
Hey there, we are currently working on a new version of Ionic Vue that will have full support for stack-based navigation. We will be announcing more soon. Thanks!
