### ISSUE TITLE
Unable to build to production: AppComponent doesn't "seem" to be in a module

### ISSUE THREAD

**Issue by Zerokk** [ionic-team/ionic-framework#22002]
I have an Angular / Ionic project that is failing at the process where Angular builds the production bundle. If I just use "ionic build" (homologous to "angular build", actually it should do the very same at this point), everything works great.

But at the moment I choose to build for production, with "ionic build --prod", I start getting lots and lots of errors relating components that, apparently, do not belong... any module?

This started with some login components (login, register, forgotten_password...), which I bundled into a single module and added the dynamical components to entryComponents. That did the thing, but in the case of the AppComponent (which is my main component, in the main module), I cannot get this fixed.

You can see the error here: https://i.stack.imgur.com/3bryP.png

Lots of problems like these arise, as if the component couldn't load Ionic components. Just what would usually happen if you remove "BrowserModule" or "CommonModule" aren't imported into your module, and you try to use Angular directives such as *ngFor. If you're used to Angular, this will be common for you, but my main module correctly imports the BrowserModule that every Angular app needs at it main module:

```
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    AppRoutingModule,
    ComponentsModule,
    FormsModule,
  //  AssistanceCheckerModule,
    // ServiceWorkerModule.register('/ngsw-worker.js', { enabled: environment.production })
  ],
  providers: [
    ParseHandlerService,
    StatusBar,
    Geolocation,
    SplashScreen,
    AppStateService,
    SpinnerService,
    IconGetterService,
    ReactiveChannel,
    ImagePicker,
 //   DatePicker,
    ImageResizer
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }


```

I can still perfectly build normal bundles, but building the production one is not possible with this error. Any solution for this?

Extra info:
- Node  v.4.8.0
- Angular v.9.1.6
- Ionic 5

**Comment by indraraj26** [comment]
Hi,
I see ionicmodule.forRoot(), it should work though
can your provide small reproduction via github to reproduce issue

**Comment by Zerokk** [comment]
Honestly, do you even think about these things when you say "needs reproduction", or just don't want to spend time with issues like this that clearly show that this framework has some serious problems?

I don't wanna be a whinner, but I've been already working in this project for two years and I don't stop seeing serious problems like this. No, no reproduction of the problem is needed: the module is there, you could see it, and if you want, I can show you in a little video the things I already said:

- The app works well under `ionic serve`.
- It indeed builds well too in Capacitor if I create the bundle with `ionic build`.
- It only finds these weird Angular errors if I use the `--prod` flag.

Aside from this, I'm having 3 more inconsistency-related bugs that are not reproductible in the browser version, that actually appeared out of nowhere from one build to another. Something seems to be deeply broken here for these things to happen. I even dived deep into my phone's settings to see if there was something that could be messing up with the app, but the only problem I could find, is the typical "energy saving" option that all Xiaomi phones have. That thing totally destroys some views (they keep loading forever when trying to load external libraries, such as Google Places), but switching it off, doesn't fix other inconscistencies that you can find in the browser version.

So, really (and sorry for the tone, but one ends up being tired of this)... do anybody have any idea on what can be causing this weird build error, at very least? It's not the only problem I'm facing that I don't see in any other mobile development framework, but I'll be happy if, at least, the Ionic team is able to help me in this bug, which I consider the weirdest of them all.

**Comment by liamdebeasi** [comment]
Hi there,

We add the "needs reproduction" label when we are unable to reproduce the issue ourselves. Code snippets are not typically enough for us to reproduce the issue, so it is much more helpful to have the issue reproduced in a blank Ionic starter application. Doing this allows us to triage and resolve the issue much quicker. In addition, it allows us to help more people.

If there is an issue in Ionic Framework's code, I need to be able to reproduce the issue myself before I can fix it. Looking at the error screenshot you provided, there is likely a configuration issue in your application, so being able to see a GitHub repo with how you configured your application would be very helpful.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
