### ISSUE TITLE
bug: ion-radio checked removed?

### ISSUE THREAD

**Issue by JayzeeHuang** [ionic-team/ionic-framework#22012]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

The `checked` not woking now

**Expected behavior:**

Using `checked` set the default value.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Please see the Ionic Framework v5. breaking changes: https://github.com/ionic-team/ionic-framework/blob/master/BREAKING.md#radio
