### ISSUE TITLE
bug: text input does not work after clicking ion-label on safari

### ISSUE THREAD

**Issue by PaulSnijders** [ionic-team/ionic-framework#22017]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Safari browser: If I have an ion-input with an ion-label (like in the conference starter template) when I click on the ion-label the element somehow gets focus but when I start typing nothing happens. When I click directly on the ion-input it works fine. With Chrome it also works fine.

**Expected behavior:**
When I click on an ion-label inside a ion-item the corresponding ion-input should get focus and after typing on the keyboard the text should appear in the input. (textbox)

**Steps to reproduce:**
- Start new Angular Ionic conference template.
- Ionic serve
- Go to page 'Login' with Safari
- Click on the text 'Username'
- Start typing on the keyboard
- Nothing happens (expected: text in the username input)

**Related code:**
```
      <ion-item>
        <ion-label position="stacked" color="primary">Username</ion-label>
        <ion-input [(ngModel)]="login.username" name="username" type="text" #username="ngModel" spellcheck="false" autocapitalize="off"
          required>
        </ion-input>
      </ion-item>
```

**Other information:**
https://github.com/ionic-team/ionic-conference-app
In this working example: https://nghiacc.github.io/ionic-conference-app/ it works different from the newest build. It also fails for Chrome.
This also has been a problem in earlier versions of Ionic. But there always was some kind of fix.
It also doesn't work in a native ionic IOS build.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.11.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.3 (/usr/local/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 11.6 Build version 11E708

```

**Comment by liamdebeasi** [comment]
Please upgrade to Ionic Framework v5.3.2. This issue was fixed in that version.

**Comment by PaulSnijders** [comment]
It works after the upgrade. Thank you.
