### ISSUE TITLE
bug: ion-avatar - no ripple effect

### ISSUE THREAD

**Issue by akilude** [ionic-team/ionic-framework#22026]
#Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x** (v5.3.2)

**Current behavior:**
No ripple effect when an item contains an avatar with a nested element like a button or image.

**Expected behavior:**
Ripple and click effect should be present when when using an avatar

**Steps to reproduce:**

Let's consider the ionic conference app, specifically the schedule filter page which contains a list of tracks, users can select/deselect by clicking the item and the ripple effect is present

```
<ion-item *ngFor="let track of tracks" [attr.track]="track.name | lowercase">
     <ion-icon *ngIf="ios" slot="start" [name]="track.icon" color="medium"></ion-icon>
     <ion-label>{{track.name}}</ion-label>
     <ion-checkbox [(ngModel)]="track.isChecked"></ion-checkbox>
</ion-item>
```

Adding an avatar with a nested element stops the ripple effect from occurring and the user has to click on the checkbox only to toggle it.

```
<ion-item *ngFor="let track of tracks" [attr.track]="track.name | lowercase">
      <ion-avatar slot="start">
        <ion-button shape="round" class="round-avatar-btn">A</ion-button>
      </ion-avatar>
      <ion-icon *ngIf="ios" slot="start" [name]="track.icon" color="medium"></ion-icon>
      <ion-label>{{track.name}}</ion-label>
      <ion-checkbox [(ngModel)]="track.isChecked"></ion-checkbox>
</ion-item>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.7 (/Users/apple/.nvm/versions/node/v10.17.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 16 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/apple/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   NodeJS            : v10.17.0 (/Users/apple/.nvm/versions/node/v10.17.0/bin/node)
   npm               : 6.11.3
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708
```

**Comment by akilude** [comment]
Hi @liamdebeasi ,

Here is a stackBlitz, https://stackblitz.com/edit/ionic-v5-ripple?file=src/app/home/home.page.html as you can see in the demo, the first item has the ripple effect when clicking on anywhere on the item, the second one does not.

**Comment by brandyscarney** [comment]
Thanks for the issue! So this was done intentionally when you have an item with multiple clickable elements. In your first example, the item *only* has a checkbox, so the entire item is clickable to check/uncheck the checkbox. However, once you add a button in the item, it no longer adds a cover to check the checkbox because that would interfere with the button element's click events. If you add the following you can see that the avatar doesn't cause the cover to be removed, only multiple clickable elements (`a`, `ion-anchor`, `ion-button`, `ion-datetime`, etc) do:

```html
<!-- Button + Checkbox, no clickable cover -->
<ion-item>
  <ion-button slot="start">Button</ion-button>
  <ion-label>name</ion-label>
  <ion-checkbox></ion-checkbox>
</ion-item>

<!-- Avatar + Checkbox, has clickable cover -->
<ion-item>
  <ion-avatar slot="start">
    <img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48cGF0aCBmaWxsPSIjYzVkYmZmIiBkPSJNMCAwaDUxMnY1MTJIMHoiLz48cGF0aCBkPSJNMjU2IDMwNGM2MS42IDAgMTEyLTUwLjQgMTEyLTExMlMzMTcuNiA4MCAyNTYgODBzLTExMiA1MC40LTExMiAxMTIgNTAuNCAxMTIgMTEyIDExMnptMCA0MGMtNzQuMiAwLTIyNCAzNy44LTIyNCAxMTJ2NTZoNDQ4di01NmMwLTc0LjItMTQ5LjgtMTEyLTIyNC0xMTJ6IiBmaWxsPSIjODJhZWZmIi8+PC9zdmc+"/>
  </ion-avatar>
  <ion-label>name</ion-label>
  <ion-checkbox></ion-checkbox>
</ion-item>
```

You can read more about why we did this on this issue here: https://github.com/ionic-team/ionic-framework/issues/15850
