### ISSUE TITLE
bug: IonRoutlet within a Ionsplitpane Not rendering Page if a subpage is in history

### ISSUE THREAD

**Issue by clementvp** [ionic-team/ionic-framework#22020]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

So i have split my routing in two parts: 
-A public login page 
-Two privates pages: Home, and ForgotPassword in a IonSplitPane subComponent (see Private.tsx) 
I use Switch to have a my login page not in my IonSPlitPane. 
I use IonRouterOutlet inside my Private (see Private.tsx) component. 

I use a dummy Auth Context to simulate a Authentication process. I can Login and Logout via this Context (see AuthContext.tsx). 

In the login page (see Login.tsx) I call the AuthContext Login Method to set a loggedIn boolean to True and if this is True i redirect to /home. 

In the Private Component I have two Routes (see Private.tsx) encapsulated in a ionSplitPane and a side menu. 
If the loggedIn boolean is set to false I redirect to /login. 

In my menu I can Call the Logout Method of the AuthContext.

**Current behavior:** 

So first and simple behavior: 
-Click the login button 
-I'm redirected to the Home in the IonSplitPane and Menu. 
-Click logout in the menu 
-I'm redirect to login 
-Click the login button 
-I'm redirected to the Home page in the IonSplitPane and Menu. 

Second behavior (from the login page): 
-Click the login button. 
-I'm redirected to the Home in the IonsplitPane and menu. 
-Click the forgot password in the menu. 
-I'm redirected in the forgot password page in the IonsplitPane and Menu.
-Click the logout in the menu. 
-I'm redirected to the login page. 
-Click the login button.
-IonRouterOutlet does not render the home page.

**Expected behavior:**
When I navigate in my ForgotPassword Page, if i click the logout buton in the menu and i login again, I want to be redirected to The home page.

**Steps to reproduce:**
-Click the login button. 
-I'm redirected to the Home in the IonsplitPane and menu. 
-Click the forgot password in the menu. 
-I'm redirected in the forgot password page in the IonsplitPane and Menu.
-Click the logout in the menu. 
-I'm redirected to the login page. 
-Click the login button.
-IonRouterOutlet does not render the home page.

**Related code:**

You can find a minimal repo [here](https://github.com/clementvp/ion-router-outlet-bug) 
Check the second behavior parts in this issue (see above)

This is App.tsx
```
const App: React.FC = () => (
  <IonApp>
    <Authprovider>
      <IonReactRouter>
        <Switch>
          <Route path="/login" exact>
            <Login></Login>
          </Route>
          <Private />
          <Redirect from="/" to="/home" exact />
        </Switch>
      </IonReactRouter>
    </Authprovider>
  </IonApp>
);

export default App;
```

This is Login.tsx
```
const Login: React.FC = () => {
  const { loggedIn, login } = useContext(AuthContext);

  if (loggedIn) {
    return <Redirect to="/home"></Redirect>;
  }

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Login</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <IonButton
          onClick={() => {
            login();
          }}
        >
          LOGIN
        </IonButton>
      </IonContent>
    </IonPage>
  );
};

export default Login;
```

This is Private.tsx
```
const Private: React.FC = () => {
  const { loggedIn } = useContext(AuthContext);

  if (!loggedIn) {
    return <Redirect to="/login"></Redirect>;
  }

  return (
    <IonSplitPane contentId="main">
      <Menu></Menu>
      <IonRouterOutlet id="main">
        <Route path="/change-password" exact>
          <ChangePassword></ChangePassword>
        </Route>
        <Route
          path="/home"
          exact
          render={() => {
            console.log("normaly redirect to home");
            return <Home></Home>;
          }}
        />
      </IonRouterOutlet>
    </IonSplitPane>
  );
};

export default Private;
```

This is Menu.tsx
```
const Menu: React.FC = () => {
  const { logout } = useContext(AuthContext);

  return (
    <IonMenu contentId="main">
      <IonContent>
        <IonList id="inbox-list">
          <IonListHeader>Inbox</IonListHeader>
          <IonNote>hi@ionicframework.com</IonNote>
          <IonItem routerLink="/change-password" routerDirection="forward">
            <IonIcon slot="start" md={warningSharp} />
            <IonLabel>ForgotPassword</IonLabel>
          </IonItem>

          <IonItem
            onClick={() => {
              logout();
            }}
          >
            Logout
          </IonItem>
        </IonList>
      </IonContent>
    </IonMenu>
  );
};

export default Menu;
```

This is AuthContext.tsx
```
type ContextProps = {
  loggedIn: boolean;
  authLoading: boolean;
  login: any;
  logout: any;
};

export const AuthContext = React.createContext<Partial<ContextProps>>({});

export const Authprovider = ({ children }: any) => {
  const [loggedIn, setLoggedIn] = useState(false);

  const login = () => {
    setLoggedIn(true);
  };

  const logout = () => {
    setLoggedIn(false);
  };

  return (
    <AuthContext.Provider value={{ loggedIn, login, logout }}>
      {children}
    </AuthContext.Provider>
  );
};
```

Home.tsx and ForgotPassword.tsx are generic IonPages with a IonPage and IonContent at the root template.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.5 (/Users/clement/.nvm/versions/node/v14.4.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.3.2

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.4.0 (/Users/clement/.nvm/versions/node/v14.4.0/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by clementvp** [comment]
Completely related to #22022  (Example in #22022 is more clean and less complex to explain and understand)

**Comment by elylucas** [comment]
Hi @clementvp,

Could you try this dev build and let me know if it solves your issue?

`npm i @ionic/react@5.4.0-dev.202009041201.3d9e296 @ionic/react-router@5.4.0-dev.202009041201.3d9e296`

Thanks!

**Comment by clementvp** [comment]
I can confirm, with `@ionic/react@5.4.0-dev.202009041201.3d9e296 and  @ionic/react-router@5.4.0-dev.202009041201.3d9e296` it's working. Issue is gone 👍
