### ISSUE TITLE
bug: [@ionic/angular@5.3.2 bug] always focus at first ion-input inside ion-item w/ multiple inputs

### ISSUE THREAD

**Issue by pipoa** [ionic-team/ionic-framework#22037]
**Current behavior:**

I have switch 5.3.1 , 5.3.2 tested, It only happens in 5.3.2
If there are multiple ion-inputs inside ion-item, you have no idea to input data on ion-inputs except 1st one ex:
It always auto focus on 1st ion-input!

# Bug Report
Ionic 5
```
<ion-item>
    <ion-input></ion-input>  <!-- 1st, focus always goes here -->
    <ion-input></ion-input>  <!-- 2nd, click here jump to 1st -->
    <ion-input></ion-input>  <!-- 3rd, click here jump to 1st-->
    <ion-input></ion-input>  <!-- ... , click here jump to 1st-->
    <ion-input></ion-input>  <!-- ... , click here jump to 1st-->
</ion-item>
```

**Expected behavior:**

should correctly  focus each ion-input individually
**Steps to reproduce:**

create templat like above provided codes

**Comment by indraraj26** [comment]
Tested indeed it is always focus on first input even if you click on 2,3,4 and 5 ion input
playground: https://codepen.io/indraraj26/pen/dyMJLQQ

**Comment by moridianmess** [comment]
I can confirm that I am also having this issue.

**Comment by liamdebeasi** [comment]
This appears to be caused by https://github.com/ionic-team/ionic-framework/commit/e4964ff77b317c92b201cf7c265787b55bdde4d4#diff-3e56358e87207796613625bf863c6da0.
