### ISSUE TITLE
bug: ionChange not triggered when it uses ngForm

### ISSUE THREAD

**Issue by rockbass2560** [ionic-team/ionic-framework#22031]
# Bug Report

**Ionic version:**
**5.3.1**

**Current behavior:**
When you set a template variable on a form, ionChange is not triggered on ionInput.

**Expected behavior:**
The method is called when the event is triggered

**Steps to reproduce:**
Set a template variable in a form tag

**Related code:**

```
<form #formRegister="ngForm">
  <ion-input (ionChange="change($event)"></ion-input>
</form>

<!-- Change is not triggered. -->
```

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.11.1 (C:\Users\franc\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Comment by indraraj26** [comment]
It is not reproducible at my end with your code, Please provide reproduction via github repository

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
