### ISSUE TITLE
bug: Gesture animation and refresher animation laggy on Android after Chrome update on 25th August

### ISSUE THREAD

**Issue by diptanildas** [ionic-team/ionic-framework#22039]
Gesture animations and ion-refresher animation appears to be choppy and laggy after updating Chrome on 25th August.

Even the Gesture animation example from https://ionicframework.com/docs/utilities/animations  is laggy when implemented after the new update. 

Animation is smooth when run on browser with ionic serve. This animation lag can also be observed on the Ionic Conference App while dragging the side menu.

Ionic:

   Ionic CLI                     : 6.10.1 
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1001.0
   @angular-devkit/schematics    : 10.1.0
   @angular/cli                  : 10.1.0
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-webview 5.0.0, (and 14 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.15.0
   native-run                             : 1.0.0

System:

   NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.7
   OS     : Windows 10

**Comment by diptanildas** [comment]
Is this issue related to this?
https://bugs.chromium.org/p/chromium/issues/detail?id=1123304

**Comment by liamdebeasi** [comment]
Yes, this is related to the Chromium bug. We are working with the Chromium team on getting this resolved.
