### ISSUE TITLE
bug: google declines my APK (android sdk version to low)

### ISSUE THREAD

**Issue by dvdknaap** [ionic-team/ionic-framework#22042]
After developing my app i want to upload my apk to the google play console as a internal test but my apk get declined because the sk version is 28 and needs to be as minimal 29

I already tried to add the next line in config.xml but this didn't do anything:
`<preference name="android-minSdkVersion" value="29" />`

# Bug Report

**Ionic version:**
Ionic:

   Ionic CLI                     : 6.11.8 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.7
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, android 8.1.0, browser
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 10 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.0.0) : 0.2.2

System:

   Android SDK Tools : 26.1.1 (/home/danny/Android/Sdk)
   NodeJS            : v12.18.3 (/usr/bin/node)
   npm               : 6.14.8
   OS                : Linux 5.4

**Expected behavior:**
That google is just accepting the APK

**Comment by indraraj26** [comment]
Delete platforms folder
Delete plugins folder

`ionic cordova platform add android@latest`
`ionic cordova build android --prod`
which should be 9.0.0 and I see you are using 8.1.0

in config.xml
` <preference name="android-minSdkVersion" value="22" />`

**Comment by dvdknaap** [comment]
@indraraj26 Thanks for the fast reply this worked.

The APK is accepted i only get an error now about the signature
