### ISSUE TITLE
feat: swipe to close modal from content

### ISSUE THREAD

**Issue by nielsdewulf** [ionic-team/ionic-framework#22046]
# Feature Request

**Ionic version:**

[x] **5.3.2**

**Describe the Feature Request**

Expose swipe back gesture for customization at https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/modal/modal.tsx#L29 . I wish to change the canStart function to disable the gesture when scrolling still needs to happen in the ion-content. If its scrolled to the top, the gesture can happen.

**Describe Preferred Solution**

Allow to give a custom createSwipeToCloseGesture to the Modal.

**Describe Alternatives**

Allow to change the individual gesture functions in the already made swipeToCloseGesture

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. Can you please describe your use case for this feature?

**Comment by nielsdewulf** [comment]
Hi @liamdebeasi, I want to create a custom SwipeToCloseGesture. The issue persists when you have scrollable content inside the modal and you use the gesture. It doesn't work since the canStart function inside the gesture returns false when the target is ion-content. I wish to override the canStart function so that I can check if the scrollable content is scrolled to the top. If that's the case I want to allow the gesture so that the modal can be swiped away.

Hope this clarifies my situation a bit more.

**Comment by liamdebeasi** [comment]
From what it sounds like, you want to be able to swipe to close the modal from the content only if the content is scrolled to the top?

**Comment by nielsdewulf** [comment]
Yes, which incidentally requires me to customize the swipe to close gesture.

On Sep 8, 2020 17:29, Liam DeBeasi <notifications@github.com> wrote:

From what it sounds like, you want to be able to swipe to close the modal from the content only if the content is scrolled to the top?

**Comment by liamdebeasi** [comment]
Thanks - that use case makes sense. There is an open PR that adds this functionality: https://github.com/ionic-team/ionic-framework/pull/21227. There are still some issues with it, so I may work on it myself. I think I would rather add this than expose the entire gesture though.

**Comment by simion** [comment]
I was looking for something similar myself :) 
Swipeable modals in ios can be swiped down by pilling the content, if scroll has reached top.
Something similar on ionic would be awesome :)

**Comment by laocker96** [comment]
Sorry guys this is not working for me ... I'm using IonContent inside an IonModal with swipeToClose={true}
Is this currently working or still being fixed?
-----------------------------------------------------------
IONIC VERSION: @ionic/react: 5.5.4

**Comment by liamdebeasi** [comment]
This has not been resolved. When it is, this issue will be closed and you should receive an email notification.

**Comment by laocker96** [comment]
Thank you for your fast response.

Waiting for updates have a good day,
Simone

Il giorno gio 3 giu 2021 alle ore 14:36 Liam DeBeasi <
***@***.***> ha scritto:

**Comment by katche70** [comment]
This would indeed be a great feature

**Comment by liamdebeasi** [comment]
Hi everyone,

I am working on implementing this with the card style modal. Can everyone test this dev build and let me know if you run into any issues?

```
6.1.3-dev.11650647187.10053e0b
```

Note: This dev build applies to any Ionic Framework package (vue, angular, etc).

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25185, and a fix will be available in an upcoming release of Ionic Framework.

Please feel free to continue testing, and let me know if you run into any issues.
