### ISSUE TITLE
@ionic/vue bug: layout shifts with tabs are sometimes visible when loading quickly 

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-framework#22052]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Because of how fullscreen logic works in `ion-content`, sometimes layout shifts happen on page load. In Ionic React/Angular, the tab page is hidden when this happens, so users do not see it. This is not the case for Ionic Vue.

**Expected behavior:**

I would expect any layout shifts to not happen/not be visible.

**Steps to reproduce:**

1. Clone Ionic Vue tabs starter.
2. Switch tabs and occasionally you should notice some layouts shifts when each tab first loads.

**Comment by Livijn** [comment]
”Clone Ionic Vue tabs starter.” Where is that repo?

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/22254
