### ISSUE TITLE
bug: min & max when displayFormat="HH:mm" and max is set to another day

### ISSUE THREAD

**Issue by jammin197** [ionic-team/ionic-framework#22056]
# Bug Report

**Ionic version:**
[x] **5.2.3**

**Current behavior:**
This is the bug related to the ion-datetime. When the displayFormat is set to "HH:mm" and min is set to current day (today) & max is set to another day (e.g. tomorrow), then the picker is not visible. It shows white area on Android and some buggy lines on iOS. Works OK, when the day is not exceeded.

**Expected behavior:**
Possibility to set min date to now e.g. ('2020-09-15T21:58:35+02:00') and max date to +4h e.g. ('2020-09-16T01:58:35+02:00') and user can choose the time, which is suitable for him.

**Steps to reproduce:**

In javascript part set min='2020-09-15T21:58:35+02:00' & max='2020-09-16T01:58:35+02:00'
```
openTimePicker() {
    this.timePickerMin = '2020-09-15T21:58:35+02:00';
    this.timePickerMax = '2020-09-16T01:58:35+02:00';
    this.timePicker.open();
}
```
Angular component (nothing special):
```
export class TestComponent implements OnInit {
  @ViewChild('timePicker') timePicker: IonDatetime;
  customTimePickerOptions: any;
  timePickerMin;
  timePickerMax;

  constructor() {
   this.customTimePickerOptions = {
      buttons: [{
        text: 'Dismiss',
        handler: () => {
          this.onTimePickerDismiss();
          // return false; <-- do not dismiss
        }
      },
      {
        text: 'Confirm',
        handler: (data) => { this.onTimePickerConfirm(data); }
      }]
    };
  }
}
```
HTML:
```
<ion-datetime #timePicker displayFormat="HH:mm" [pickerOptions]="customTimePickerOptions" [min]="timePickerMin" [max]="timePickerMax"></ion-datetime>
```

**Other information:**

iOS
![image](https://user-images.githubusercontent.com/54538273/92600035-53f33a80-f2ab-11ea-8493-089ce0832fd7.png)
Android
![image](https://user-images.githubusercontent.com/54538273/92600210-87ce6000-f2ab-11ea-8f53-bd02fa57e37b.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\X\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.10
   @angular-devkit/schematics    : 9.1.10
   @angular/cli                  : 9.1.10
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v12.14.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by jammin197** [comment]
Hi, sample of bug is created here: https://github.com/jammin197/ion-datetime-Bug22056.git

**Comment by jammin197** [comment]
Hi, you can found a simple sample of bug here: https://github.com/jammin197/ion-datetime-Bug22056.git
Thank you in advance.

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. I have added your issue to our bug tracker here: https://github.com/ionic-team/ionic-framework/issues/16630

**Comment by jammin197** [comment]
Thank you.

**Comment by liamdebeasi** [comment]
The issue here seems to be that `ion-datetime` does not take into account day/month/year when the format is `HH:mm`. In the given example, the minimum time is `21:58:35` and the maximum time is  `01:58:35`. Since 21 > 1, `ion-datetime` does not have any valid options to show. I do not know if this is a bug or a behavioral quirk, but it is certainly something we should clear up in our docs.
