### ISSUE TITLE
bug: propagated tab lifecycle events fire twice

### ISSUE THREAD

**Issue by ehorodyski-ionic** [ionic-team/ionic-framework#22057]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

While working with a community member it was observed that [propagating Ionic lifecycle events](https://github.com/ionic-team/ionic-framework/issues/16834#issuecomment-631676434) from the `IonTabs` component to each individual tab page can fire Ionic lifecycle events twice.

**Expected behavior:**

It is expected that Ionic lifecycle events would be fired once. 

**Steps to reproduce:**

After cloning, installing dependencies, and serving the reproduction repository linked below:

1. Start on page "Delta" and refresh the page. 
2. Using the side menu, navigate to "Alpha".
    * Note that `AlphaPage.ionViewWillEnter` and `AlphaPage.ionViewDidEnter` are called twice.
3. Using the side menu, navigate to "Echo".
4. Using the side menu, navigate to "Bravo".
    * Note that `AlphaPage.ionViewWillLeave` and `AlphaPage.ionViewDidLeave` are called again.
    * Note that `AlphaPage` events should not fire after we have transitioned into "Echo" nor before transitioning from "Echo" to "Bravo".
5. Using the side menu, navigate to "Delta".
    * Note that `AlphaPage.ionViewDidEnter` is called twice.

**Related code:**

Reproduction: https://github.com/ehorodyski-ionic/fw-ng-tabs-lifecycle-events

**Other information:**

This issue has been observed for `@ionic/angular`.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.0 (/Users/eric/npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.2
   @capacitor/core : 2.0.2

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run                             : 1.0.0

System:

   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 6.14.7
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Discussed a revised workaround on Slack. The issue here is in the workaround they are using, not Ionic Framework.
