### ISSUE TITLE
bug: ion-datetime "engine.selectionChanged" is not a function

### ISSUE THREAD

**Issue by joshoconnor89** [ionic-team/ionic-framework#22059]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.2.0**

**Current behavior:**

When opening the ion-datetime picker on iOS devices, it fails to scroll, and I am constantly being hit with the "engine.selection.changed is not a function" error

**Expected behavior:**

You should be able to open the ion-datetime picker and scroll

**Steps to reproduce:**

Add ion-datetime, open date picker on iOS device.  You cannot scroll, and get a ton of errorss

**Related code:**
 

```
<ion-datetime displayFormat="MMMM" [value="2012-12-15T13:47:20.789"></ion-datetime>
```

**Other information:**

[
![Screen Shot 2020-09-09 at 3 02 29 PM](https://user-images.githubusercontent.com/9359439/92659922-32e01900-f2ae-11ea-8772-9afeff05c7a9.png)
](url)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.15
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : not installed
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.1.2

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res (update available: 0.15.1) : 0.8.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.16.2 (/usr/local/bin/node)
   npm        : 6.13.1
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a```

**Comment by joshoconnor89** [comment]
I am fairly confident this commit broke it 

https://github.com/ionic-team/ionic-framework/pull/21268/commits/44b88763339524a9d6df0df120e22d06abf10c82

it works in 5.1.0, but in 5.1.1, it is broken on iOS

**Comment by joshoconnor89** [comment]
@liamdebeasi can you please take a look at this?  im sure this is a widespread issue affecting a lot of users.

i am using capacitor, not sure if that affects anything. 

Thank you

**Comment by liamdebeasi** [comment]
Are you testing this on the latest version of Ionic Framework? I am testing with the following setup and the haptics are working fine:

```
Ionic:

   Ionic CLI                     : 6.11.8-testing.0 (/Users/liamdebeasi/.nvm/versions/node/v10.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.1
   @capacitor/core : 2.4.1

Utility:

   cordova-res (update available: 0.15.1) : 0.6.0
   native-run (update available: 1.1.0)   : 0.2.7

System:

   NodeJS : v10.15.0 (/Users/liamdebeasi/.nvm/versions/node/v10.15.0/bin/node)
   npm    : 6.9.2
   OS     : macOS Catalina

```

**Comment by joshoconnor89** [comment]
i was on 5.3.1, let me check 5.3.2

**Comment by joshoconnor89** [comment]
okay so i tried 5.3.2, issue is still occurring.  Are you testing on iOS?  this issue does not occur on the browser or android

**Comment by joshoconnor89** [comment]
@liamdebeasi based on your set up it looks like you're not running this on iOS, i dont see Xcode/ios deploy

**Comment by liamdebeasi** [comment]
I was running it on iOS, though I am not sure why `@capacitor/ios` did not show up in `ionic info`. Can you try reproducing this issue in a blank Ionic starter app and provide the link to the GitHub repo here?

**Comment by joshoconnor89** [comment]
sure thing

**Comment by joshoconnor89** [comment]
hm worked fine in the blank project.  we have a workaround doing this:
```
delete window['TapticEngine'];
delete Plugins.Haptics;
```

we think one of our plugins is interfering with this, no idea why this works but it does.

**Comment by liamdebeasi** [comment]
In the project where this is happening, can you send over your package.json?
