### ISSUE TITLE
bug: When you navigate to the previous page with changes in the url, the RouteComponentProps isn't updated

### ISSUE THREAD

**Issue by andyindahouse** [ionic-team/ionic-framework#22064]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.1.0**
[x] **5.3.0**

**Current behavior:**
When you navigate to the previous page from other page the RouteComponentProps of the previous page (location in this case) don't refresh theirs values. 

I'm reading about the lifecycle custom in ionic pages and I'm using useIonViewWillEnter or useIonViewDidEnter but I'm getting the same location without the new queryParams (but the search bar of the browser looks updated, so I think this is a bug). I think that in this case the component should have a normal render because of the url is changed (in this case the RouteComponentProps of the page)

**Expected behavior:**
If you navigate to the previous page and the url has changed, this previous page should refresh the component because of theirs RouteComponentProps params has changed.

**Steps to reproduce:**
I've created this code-sandbox to reproduce it:
https://codesandbox.io/s/ionic-react-router-forked-wjqoy

1) Navigate to Test page "/test"
2) Click on "Go to other page" ("/other-page")
3) In Other page, click on "Back to test page with query param"
4) Console should show the location updated with the queryParam "param=12345" but it doesn't do it :(

**Related code:**

I've created this code-sandbox to reproduce it:
https://codesandbox.io/s/ionic-react-router-forked-wjqoy

Thanks in advance

**Comment by elylucas** [comment]
Hi @andyindahouse,

This isn't documented well so my apologies, but you need to pass the location as dependency to the useIonView*** hooks for them to notice updates like so:

```
  useIonViewWillEnter(() => {
    console.log("useIonViewWillEnter", location);
  }, [location]);
  useIonViewDidEnter(() => {
    console.log("useIonViewDidEnter", location);
  }, [location]);
```

I'm going to close this for now, but if that doesn't help ping me and we can investigate further.

Thanks
