### ISSUE TITLE
feat: Please add --indicator-border-radius fpr ion-segment-button

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/ionic-framework#22063]
I try to follow my styleguide which requires a `border-radius` on the `indicator` from `ion-segment-button`
Is it possible to add this? :) 

This is what i try to do: https://imgur.com/a/VfNwGXy

https://ionicframework.com/docs/api/segment-button > please add `--indicator-border-radius`

best regards and thanks for reading!

**Comment by brandyscarney** [comment]
Thanks for the issue! The indicator background uses the `--border-radius` variable, like so:

```
ion-segment-button {
  --border-radius: 50%;
}
```

Here's a Codepen: https://codepen.io/brandyscarney/pen/XWdExgV?editors=1100

Does this accomplish what you need?

**Comment by SvenBudak** [comment]
Thanks for the fast reply, but this is not working for me. Because the `ion-segment-button` have no `overflow: hidden`.
If i add this manually, i lost the animation, because its cutted.

on your codepen is the ios mode activated. there its working. but not on material mode :)

i think the only clean way, is the variable `--indicator-border-radius`

**Comment by liamdebeasi** [comment]
Hey there,

I am going to close this issue since what you are trying to do can be accomplished via the `indictor-background` CSS Part as you noted in https://github.com/ionic-team/ionic-framework/issues/22063#issuecomment-690527370.

Thanks!
