### ISSUE TITLE
bug: ion-slides loop causes routerLinks to be disabled in Angular

### ISSUE THREAD

**Issue by danielzen** [ionic-team/ionic-framework#22070]
# Bug Report
When looping backward through ion-slides to the last slide, or forward to the first slide, routerLinks are disabled. If you move the slide slightly and let it resettle at the same location, routerLinks are re-enabled. I imagine this may have something to do with the underlying http://www.idangero.us/swiper/ implementation, but I am not sure.

In certain situations, the buttons with routerLinks to another route will incorrectly cause a switch to the previous slide. One has to play with the sample app a little to make it happen, but it isn't that difficult to see. (Click button, back, button, back, switch slides, button, back, button, back, switch slides & it will happen eventually) However, it is difficult to figure out the exact sequence that causes it. This latter issue happens even if loop is false, so perhaps this should be listed as a different bug?

**Needless to say, ion-slides causes some weird side effects on routerLinks.**

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

routerLinks do not work properly

**Expected behavior:**

routerLinks should work even when looping

**Steps to reproduce:**

**Related code:**

A sample application via StackBlitz:
https://stackblitz.com/edit/ionic-v5-ionslides-loop-bug?file=src/app/home/home.page.ts
The button with routerLink doesn't work if you loop backwards to the last slide, and when you loop forward to the first slide, but in most other cases it works fine.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8 (/Users/zen/.nvm/versions/node/v12.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.6
   @angular-devkit/schematics    : 10.0.6
   @angular/cli                  : 10.0.6
   @ionic/angular-toolkit        : 2.3.0

Utility:

   cordova-res (update available: 0.15.1) : 0.12.1
   native-run (update available: 1.1.0)   : 1.0.0

System:

   NodeJS : v12.18.2 (/Users/zen/.nvm/versions/node/v12.18.2/bin/node)
   npm    : 6.14.8
   OS     : macOS Mojave
```

**Comment by mybluedog24** [comment]
The div tag with click event not working too, when loop backwards to last slide or loop forward from last slide to first slide.

```html
<ion-slides [options]="slideOpts" [pager]="true">
  <ion-slide *ngFor="let banner of bannerNews">
    <div tappable (click)="openBannerLink(banner)">
      <img src="{{banner.image}}" alt="" />
    </div>
  </ion-slide>
</ion-slides>
```

```js
  slideOpts = {
    loop: true,
    autoplay: {
      delay: 3000,
    },
    slidesPerView: 1,
    spaceBetween: 10,
    breakpoints: {
      540: {
        slidesPerView: 1,
        spaceBetween: 10
      },
      960: {
        slidesPerView: 2,
        spaceBetween: 10
      },
      1140: {
        slidesPerView: 2,
        spaceBetween: 10
      }
    }
  };
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. So the underlying problem here, as mentioned in https://github.com/ionic-team/ionic-framework/issues/22070#issuecomment-703194977, is that when the slides loop Swiper duplicates the slide elements. This means that anything bound to the original instance of the slide is lost. This includes things such as click handlers and routerLink bindings.

I am going to consolidate this issue with https://github.com/ionic-team/ionic-framework/issues/22414 since that refers to the same underlying issue. Thanks!
