### ISSUE TITLE
bug: VirtualScroll allways renders all items

### ISSUE THREAD

**Issue by schacki** [ionic-team/ionic-framework#22084]
# Bug Report

**Ionic version:**

[x] **5.3.1 (angular 9.1.6)
[x] **5.3.1 (angular 10.0.0)

**Current behavior:**

I had implemented a list with virtualscroll (following this demo project https://github.com/ipsjolly/ionic-virtual-with-infinite-scroll-app). And while things are working fine for me, when I cloned this project, I never got it working in my actual project.

All 1000 items are rendered at once with of course a very poor performance.

**Expected behavior:**
I had expcected that only the items in the curent viewport (+- some additional on top and end) are rendered with very good perofmrance.

**Steps to reproduce:**
Pleas find my code below. Unfortunately, I cannot provide you much further information at the moment, because I can only reproduce the bug in my project, while I am not able to reproduce it here: https://github.com/ipsjolly/ionic-virtual-with-infinite-scroll-app. I am unclear what I need to look for or what furhter information you require. I am happy to provide anyhting you ask, but I cannot post my complete project)

**Related code:**

```
  <ion-list>
    <ion-list-header>
      Employee List
    </ion-list-header>

    <ion-virtual-scroll [items]="items">

      <ion-item *virtualItem="let item">
          <h2>{{item.serialNumber}}</h2>
      </ion-item>

    </ion-virtual-scroll>

  </ion-list>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8 (C:\Users\js\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. With upcoming major versions of Ionic Framework, we are going to be transitioning to using Angular's CDK Scroller. As a result, we have a freeze on new features and bug fixes on ion-virtual-scroll. See https://material.angular.io/cdk/scrolling/overview for how to get started with CDK Scroller.

**Comment by schacki** [comment]
Thanks for the response, you might want to add a hint to the current docs about that.

Are there already any docs/tutorials/... on how to migrate. My biggest problem at the moment is that "cdk-virtual-scroll-viewport" seems to need a fixed height to work (otherwise height is zero, and nothing is displayed).

**Comment by liamdebeasi** [comment]
We are still working on some docs here: https://github.com/ionic-team/ionic-docs/pull/1406. As you suggested, CDK Scroller only supports fixed heights and dynamic heights is "in progress" according to this issue: https://github.com/angular/components/issues/10113.

While we are going to be moving to CDK Scroller for Ionic Angular, we are still interested in learning about different use cases. So, if you have any other use cases where CDK Scroller does not meet your needs, we would love to hear them!

**Comment by schacki** [comment]
I am aware of the fixed/dynamic heights of the items (this is not my concern).

My problem in below example is that, if I remove the fixed height (style="height: 1500px") from the cdk-virtual-scroll-viewport element. The height is zero and I see nothing. On the other hand, setting a fixed height does not make sense either to me. This is certainly a css issue. But still this should somehow working out of the box. Any help appreciated.

`<ion-content id="machine-list-content">
  <ion-toolbar slot="fixed">
    <app-machine-sorting></app-machine-sorting>
  </ion-toolbar>
  <cdk-virtual-scroll-viewport [itemSize]="100 style="height: 1500px">
    <ion-list lines="none" *ngIf="(machines | machineFilter: filter | machineSorting: sortProperty:revers) as filtered">
      <div *cdkVirtualFor="let machine of filtered; trackBy: trackBy; templateCacheSize: 30">
        <app-machine [machine]="machine"></app-machine>
      </div>
    </ion-list>
  </cdk-virtual-scroll-viewport>
</ion-content>`
