### ISSUE TITLE
bug: platform.backButton doesn't work after kill the app - Android 10

### ISSUE THREAD

**Issue by devalexc** [ionic-team/ionic-framework#22085]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
```
  this.platform.backButton.subscribeWithPriority(XXXX, () => {
            console.log('Handler was called!');
        });
```
Subscribe and subscribeWithPriority with any priority doesn't fire after kill the app, UPDATE: only at Android 10.
This methods are use in AppComponent and also they were tested in the actual load page
I also tried   `document.addEventListener('ionBackButton' and   document.addEventListener('backbutton'`
And i used this methods in constructor,oninit and ionViewWillEnter with the same result.
**Expected behavior:**
Fire the subscribe event 

**Steps to reproduce:**
 You can create a new ion proyect and add 
```
  this.platform.backButton.subscribeWithPriority(10000, () => {
                console.log('test');
            });
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.10.1 (C:\Users\Aleja\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.1.1
   @angular/cli                  : 10.1.1
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 16 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\Aleja\AppData\Local\Android\Sdk)
   NodeJS            : v12.18.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.5
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
