### ISSUE TITLE
bug: The keyboard doesn’t work done with inputs

### ISSUE THREAD

**Issue by umbode** [ionic-team/ionic-framework#22082]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

https://forum.ionicframework.com/t/the-keyboard-doesnt-work-done-with-inputs/195956

**Expected behavior:**
ion-input right focus on keyboard and binding value on form 

**Steps to reproduce:**
Click on input 

**Related code:**

```
<form [formGroup]="form">
        <ion-grid>
          <ion-row class="ion-background-form-login">
            <ion-col [size]="6">
              <ion-item lines="none" no-padding>
                <!-- <ion-label position="stacked">Username</ion-label> -->
                <ion-input
                  formControlName="first_name"
                  type="text"
                  placeholder="..."
                ></ion-input>
              </ion-item>
            </ion-col>
          </ion-row>
        </ion-grid>
</form>
```
Ionic:

   Ionic CLI                     : 6.9.1 
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   NodeJS : v10.16.2
   npm    : 6.14.8

### GIF

![ezgif-5-de48b7383ef0](https://user-images.githubusercontent.com/71231346/93028389-f8f77580-f613-11ea-9fa4-b08345b41e02.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
