### ISSUE TITLE
bug: default background color for ion-loading is wrong ?

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#22104]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
Is the default background color for `ion-loading` wrong ?

In light mode : `ion-loading` background is white (like ion-cards for instance)
In dark mode : `ion-loading` background is pure black (not dark-gray like cards) : it looks weird

**Expected behavior:**
The background for the `ion-loading` alert should be the same as a `ion-alert` ? They're basically the same UI Component but variations like buttons on `ion-alert`. 

Currently `ion-loading` background is `--ion-color-step-50` and I would expect it to be `--ion-background-color` like `ion-alert`

I'm not sure if this is intentional or not

**Steps to reproduce:**
Setup a ionic-app with dark mode and display a `ion-alert`

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you using the latest dark mode theme? I am not able to reproduce this: https://codepen.io/liamdebeasi/pen/LYNJOJg.

**Comment by Yohandah** [comment]
@liamdebeasi  I figured it out.

I am using only one dark theme, forcing MD on Safari iOS user-agent and not using Cupertino styles because I'm deploying as a PWA only (and it looks weird to have native iOS components on a webapp. 

Looks like I merged themes without being careful and took Cupertino step colors instead of MD's ones.

Sorry for the useless issue and thanks for the help Liam!
