### ISSUE TITLE
bug: This webpage has reloaded because a problem occurred (Safari)

### ISSUE THREAD

**Issue by kyleabens** [ionic-team/ionic-framework#22111]
# Bug Report

**Ionic version:**
[x] **5.3.3**

**Current behavior:**
When you click an ion-item in Safari v14.0 the page reloads and says "this webpage was reloaded because a problem occurred"

**Expected behavior:**
You should be able to click an ion-item without an error in Safari.  

**Steps to reproduce:**
1. ionic serve an ionic/angular application
2. Open in Safari v14.0
3. Click an ion-item

**Other information:**
The ion-item doesn't even have to link anywhere for this to happen.  It's just the act of clicking it. This has always worked in the past so I'm not sure what has changed other than Safari v14.0 being released a couple days ago.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 11.7 Build version 11E801a
```

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21939#issuecomment-694259307
