### ISSUE TITLE
feat: Prioritize Vue 3 support

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/ionic-framework#22115]
Vue 3 has been released stable, yesterday.

Our company (and a lot of others) won't use Ionic but it's competitor (Quazar) until decent Vue.ts support come.

https://github.com/vuejs/vue-next/releases/tag/v3.0.0

**Comment by liamdebeasi** [comment]
We are currently publicly testing the new Ionic Vue beta, and you can get started using it today. See our blog post for more info: https://ionicframework.com/blog/announcing-the-new-ionic-vue-beta/
