### ISSUE TITLE
bug: safari 14 crash after click ion-item

### ISSUE THREAD

**Issue by Rhotan** [ionic-team/ionic-framework#22124]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
i have an ion-list with an ion-item and no functionality. If i click it on Safari 14, the browser refresh immediately.
no errors in browser console.

if i have a (click) directive, the breakpoint in the function not reached

No Problems in Safari < 14 or other browsers

**Expected behavior:**
no reactions if i click on a ion-item without a click event

**Steps to reproduce:**

- create a ion-list with ion-item
- start application with ionic serve
- click on item

**Related code:**

```
<ion-list>
    <ion-item>
        <ion-label>Testitem</ion-label>
    </ion-item>
</ion-list>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 6.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 19 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.15.0
   native-run                             : not installed

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.2 (/usr/local/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 12.0 Build version 12A7209
```

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21939#issuecomment-694259307
