### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/ionic-framework#22123]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

A feature required for `ion-slides` to slide upside and downside . it will be a good feature to include slides to go upside and downside. 
**Describe Preferred Solution**

An Attribute to sildeOptions something like

```
 const slideOpts = {
    initialSlide: 1,
    speed: 400,
   verticalSlide: true // something like this to swipe upside and downside
  };
```

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by indraraj26** [comment]
https://github.com/ionic-team/ionic-framework/issues/21933#issuecomment-675764916
Nevermind, for some reason you need to specify the directions in an options object. Changing it to the below fixed everything
```
<ion-slides [options]="slideOpts">
</ion-slides>

public slideOpts: any = { direction: 'vertical' }
```

**Comment by liamdebeasi** [comment]
As @indraraj26 suggested, you need to use `direction: 'vertical'` in your options to achieve this.
