### ISSUE TITLE
bug: Safari 14 Mac crashes when clicking on side menu item

### ISSUE THREAD

**Issue by fabiovena** [ionic-team/ionic-framework#22129]
When clicking in Safari 14 on Mac on a side menu item, the page crashes with the message "This web page was reloaded because of a problem occurred."

**Steps to reproduce:**

1. start a new Ionic app with the `sidemenu` template `ionic start myApp sidemenu`
2. run `ionic serve`
3. Open http://localhost:8100/ on Safari 14 on Mac
4. click on any side menu item

Works fine on other browsers and older Safari browsers. Could be a Safari issue, but would be nice to have a compatibility workaround on ionic as well.

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21939#issuecomment-694259307
