### ISSUE TITLE
feat: Align inline inputs on the right side.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#22128]
# Feature Request

**Ionic version:**
`@ionic/angular: '5.3.2'`

**Describe the Feature Request**
The value of an `ion-input` component should be aligned on the end / right side if inline (in row of item).

**Describe Preferred Solution**
By default attribute on list or item.

**Describe Alternatives**
No solution yet. I think I have to hack css.

Please see the docs for the demo:
https://ionicframework.com/docs/api/input

![image](https://user-images.githubusercontent.com/60390085/93782921-6e260480-fc2b-11ea-9a2c-20098334fcc6.png) | ![image](https://user-images.githubusercontent.com/60390085/93783373-e7bdf280-fc2b-11ea-870c-afc2f1b121f3.png)

Here you can see that the values are all on the left side. I expected the inline values on the right side.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. You can use `text-align: right` on the inputs to align the text to the right:

Example: https://codepen.io/liamdebeasi/pen/rNeQpZv

**Comment by infacto** [comment]
In my opinion the framework should do this or provide options for this. You solution is custom code.

**Comment by infacto** [comment]
Ok, I also can use the [CSS Utilities](https://ionicframework.com/docs/layout/css-utilities) Sorry.

```html
<ion-list>
  <ion-item>
    <ion-label>Default Label</ion-label>
    <ion-input class="ion-text-end"></ion-input>
  </ion-item>
</ion-list>
```
