### ISSUE TITLE
bug: ion-statusbar-padding value is wrong for some IOS devices

### ISSUE THREAD

**Issue by TheTonnio** [ionic-team/ionic-framework#22135]
# Bug Report

**Ionic version:**
[x] **5.3.1**

**Current behavior:**
`--ion-statusbar-padding` global CSS variable has a wrong value for the iPhone X and other devices.
It has a value of `20px` but it's not enough to cover the status bar area.

**Other information:**
![image](https://user-images.githubusercontent.com/27687623/93869572-4175f980-fccc-11ea-85ba-63d8b3ad3afd.png)

P.S. I know that `--ion-safe-area-top` can be used in this case, but it adds addition spacing after the status, which is missing for previous versions of the iPhone (e.g. SE, 6, 7, 8) and it causes visual inconsistency between these IOS devices.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.11.8
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.803.12
   @angular-devkit/schematics    : 8.3.12
   @angular/cli                  : 8.3.12
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 29 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.1.0) : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/antonbabenko/Library/Android/sdk)
   ios-deploy        : 1.11.2
   ios-sim           : 8.0.2
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.14.6
   OS                : macOS Catalina
   Xcode             : Xcode 12.0 Build version 12A7209
```

Reproduction link:
https://github.com/TheTonnio/ionic-ios-padding-bug-replication

**Comment by TheTonnio** [comment]
@liamdebeasi reproduction added

**Comment by liamdebeasi** [comment]
Thanks for the issue. So the `--ion-statusbar-padding` CSS variable is really just for devices that do not support safe area values. The value is set to `20px` and never updated since it is intended as a fallback.

Could you clarify why `ion-safe-area-top` does not work for your use case?

**Comment by TheTonnio** [comment]
@liamdebeasi the problem is that in my application I cannot reach the same search field's top margin for the iPhone X (devices with a safe area) and iPhone SE (devices w/o the safe area).

The problem caused by the `--ion-safe-area-top` which is not equal to the height of iPhone's top bar but has some additional space belove that. On the other hand, `--ion-safe-area-top` is equal to the status bar height, without any additional spacing. That creates some visual inconsistency between devices.

iPhone X with a `--ion-safe-area-top`:
![image](https://user-images.githubusercontent.com/27687623/95203566-38fce300-07e3-11eb-917d-bf899481efbb.png)

iPhone SE with a `--ion-safe-area-top`:
![image](https://user-images.githubusercontent.com/27687623/95202773-0e5e5a80-07e2-11eb-8b60-24d9940dbcf7.png)

P.S. I know that I can fix directly checking the device type, but I would rather prefer not to resort to this solution and manage that via style.

**Comment by liamdebeasi** [comment]
Thanks for the clarification. The value of `--ion-safe-area-top` is actually determined by the browser via the `env(safe-area-inset-top)` environment variable: https://github.com/ionic-team/ionic-framework/blob/master/core/src/css/core.scss#L149-L156. On non-notch devices, this is just the height of the status bar. On phones with a notch, this appears to be the value of the notch plus some padding.

This does not appear to be a bug in Ionic Framework, but one thing you could do is use the `max` function in CSS to account for some additional padding on the iPhone SE:

```css
ion-searchbar {
  padding-top: max(var(--ion-safe-area-top), 30px);
}
```

Say `--ion-safe-area-top` is `20px` on the iPhone SE, this ensures that there is an additional 10px of padding between the status bar and your searchbar.

Alternatively, if `--ion-safe-area-top` is `44px` on the iPhone X, then that value overrides the `30px` value you have.

`max()` is supported on iOS 11.3+: https://developer.mozilla.org/en-US/docs/Web/CSS/max. Can you give this a try and let me know if that resolves the issue?

**Comment by TheTonnio** [comment]
@liamdebeasi many thanks! It solved my problem 😄

**Comment by liamdebeasi** [comment]
Glad to hear the issue is resolved!
