### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by andrewrains** [ionic-team/ionic-framework#22130]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Clicking on certain components in Ionic 5 React while using Safari 14.0 cause the page to reload and then "an error repeatedly occurred with <url>"

**Expected behavior:**

Component work as they do in any other browser.

**Steps to reproduce:**

Go to Ionic Component docs while using Safari 14.0. Try to click a menu item in the Menu tab, or a Checkbox. 

**Related code:**

```
insert short code snippets here
```

**Other information:**

I have no idea if this is even something that Ionic can fix, if it's something specific to my particular set up, etc. But here's a few videos of it happening.

https://www.dropbox.com/s/eja44mqd7cv57tt/Screen%20Recording%202020-09-21%20at%201.24.06%20PM.mov?dl=0
https://www.dropbox.com/s/9j0167eq1eyl8za/Screen%20Recording%202020-09-21%20at%201.23.05%20PM.mov?dl=0

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21939#issuecomment-694259307
