### ISSUE TITLE
bug: Vue datetime picker: gestures should use a passive listener (ref #21038)

### ISSUE THREAD

**Issue by Sacrekin** [ionic-team/ionic-framework#22137]
# Bug Report

**Ionic version:**
[x] **5.x**
@ionic/vue@0.4.0 @ionic/vue-router@0.4.0

**Current behavior:**
Using datetime picker in Vue 0.4.0 displays similar behavior as documented in #21038

**Chrome console alert**
ion-datetime_3.entry.js?c15b:1457 [Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
5
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Related code: using Vue 3, composition API (reactive page data)

          <ion-item>
            <ion-label position="fixed">Date</ion-label>
            <ion-datetime display-format="DD-MMM-YY" v-model="date" />
            <ion-datetime display-format="HH:mm" v-model="date" />
          </ion-item>

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22140, and a fix will be available in an upcoming release of Ionic Framework.
