### ISSUE TITLE
bug: iOS 14 Easing for toast, modal, action sheet seem broken

### ISSUE THREAD

**Issue by Exocomp** [ionic-team/ionic-framework#22132]
I upgraded to iOS 14 and I'm noticing (if my eye are not deceiving me) abrupt ending for animations for toast, modal & action sheet which seems like might be an easing issue. There seems to be a noticeable difference from iOS 13. Before going any further has anyone else noticed animation issues (which seem like could be easing issues) when upgrading to iOS14 with the above-mentioned components?

Device: iPhone 7 Plus
Software Version: 14.0

```
Ionic:
   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0

Capacitor:
   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Utility:
   cordova-res : not installed
   native-run  : 1.1.0

System:
   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Catalina
```

**Comment by Exocomp** [comment]
Reading through the comments in #21613 & #21978 it appears this is related to those issues in WebKit.

How was acceptable to make it to prod with no workaround :(

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21978#issuecomment-693420179

**Comment by Exocomp** [comment]
@liamdebeasi I did read that comment and read through the other issues also and understand the problem. It's not your guys fault just whoever maintains Webkit that very disappointing.
