### ISSUE TITLE
feat: Access to Vue-devtool

### ISSUE THREAD

**Issue by Sacrekin** [ionic-team/ionic-framework#22138]
# Feature Request

**Ionic version:**

[x] **5**
@ionic/vue@0.4.0

**Access to Vue-devtool**
Vue dev tool tab is not activated in the Chrome debugging tool

**Expected Solution**
Availability to view components & Vuex states in Vue Dev Tool is a critical component of the Vue development process

**Comment by liamdebeasi** [comment]
Vue 3 support for dev tools is still in development. I recommend giving it a try with the beta version of dev tools: https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg.
