### ISSUE TITLE
feat: update component behaviors/styles for latest ios

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#22148]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
iOS 14 introduced new changes and it would be great if Ionic implemented those.

- [ ] spinner style has changed: `ion-spinner` doesn't match.
![85353330-cfb7c500-b4bc-11ea-9a41-776aaac8f0f6](https://user-images.githubusercontent.com/15921402/93994513-42705f00-fd90-11ea-9189-fdb951f7cdf5.gif)

- [ ] when long pressing on back button (top left corner), you can see the nav history
![image](https://user-images.githubusercontent.com/15921402/93994725-7ea3bf80-fd90-11ea-9284-7217c9a39bc3.png)

- [ ] there's a new popover and `ion-popover` doesn't match its style
![120036687_343660223537895_5145024124145916449_n](https://user-images.githubusercontent.com/15921402/93995355-3042f080-fd91-11ea-9e4b-2b7708d6c4de.jpg)

- [ ] new UIDatePicker and `ion-datetime` doesn't match its style
![image](https://user-images.githubusercontent.com/15921402/94027433-1fa77000-fdbb-11ea-9d85-83c9cd7dee76.png)

![image](https://user-images.githubusercontent.com/15921402/93995730-aba4a200-fd91-11ea-866e-e653111bcea3.png)

**Comment by BerkeAras** [comment]
Another component:
**Toasts:**
Toast are now rounder in iOS 14:
![image](https://user-images.githubusercontent.com/36629890/96368394-f2e53f00-1153-11eb-8b42-a68251546d51.png)

**Comment by liamdebeasi** [comment]
Hi everyone,

We are going to be breaking these tasks out into separate issues and closing this big issue out.

Toast: https://github.com/ionic-team/ionic-framework/issues/22781
Spinner: https://github.com/ionic-team/ionic-framework/issues/22782
Refresher: https://github.com/ionic-team/ionic-framework/issues/22783
DateTime: https://github.com/ionic-team/ionic-framework/issues/16630 (Most of the specs for this are being tracked internally, but we are planning big improvements to datetime that should resolve most of the outstanding issues and update the designs)

Regarding the nav history and context menu components, we do not have plans to implement those at this time.

Thanks!
