### ISSUE TITLE
bug: Gesture, GestureController, animations doesnot work in two components at a time, which ever loads first gets working

### ISSUE THREAD

**Issue by JunaidAlam36** [ionic-team/ionic-framework#22146]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I have four pages in my app all accessible with tab-bar, on two of the pages I have implemented ion-segment and gestures to swipe left and right between them, if both of the pages reloads separately they works fine but going from tab bar the other page doesnot listen to any gestures or animations
**Expected behavior:**

when I go to a page from tab bar its gestures should work fine and same for second page
**Steps to reproduce:**

create two pages, with tab bar and and add gestures in both of them with 
import { Gesture, GestureController } from "@ionic/angular";
and then try to switch between them to see if both of them works fine... you'll see whichever you land first after reloading would work only.
**Related code:**

```
**html page**
	<ion-segment #segment [(ngModel)]="segmentValue" (ionChange)="segmentChanged($event.detail.value)" color="purple">
		<ion-segment-button value=1>Pending</ion-segment-button>
		<ion-segment-button value=2>Active</ion-segment-button>
		<ion-segment-button value=3>Past</ion-segment-button>
	</ion-segment>


**gesture import**
import { Gesture, GestureController } from "@ionic/angular";
	constructor(
		private gestureCtrl: GestureController
	) {}

**gesture implementation**
async createswipeGesture() {
		
			this.gesture = await this.gestureCtrl.create(
				{
					el: document.getElementById("content"),
					threshold: 30,
					gestureName: "swipe",
					direction: "x",
					onEnd: (ev) => this.onSwipe(ev),
				},
				true
			);
			this.gesture.enable(true);
			console.log("this.gesture", this.gesture);
		
	}
	private onSwipe(detail) {
		if (detail.velocityX >= 0) {
			console.log("right");
			const temp = +this.segmentValue - 1;
			console.log("temp", temp);
			temp <= 0 ? (this.segmentValue = 3) : (this.segmentValue = temp);
		} else {
			console.log("left");
			const temp = +this.segmentValue + 1;
			console.log("temp", temp);
			temp >= 4 ? (this.segmentValue = 1) : (this.segmentValue = temp);
		}
	}
```

**Other information:**

**same implementation is being done in other component as well... but only either of them works at a time**
_I hope you can reproduce the bug with this information_

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 6.11.7 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.17.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
   Xcode  : Xcode 11.5 Build version 11E608c

```

**Comment by JunaidAlam36** [comment]
> Thanks for the issue! This issue has been labeled as `needs reproduction`. This label is added to issues that need a code reproduction.
> 
> Please provide a reproduction with the minimum amount of code required to reproduce the issue. Without a reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.
> 
> For a guide on how to create a good reproduction, see our [Contributing Guide](https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction).

I have added some more infromation please take a look

**Comment by liamdebeasi** [comment]
Can you please reproduce this in an Ionic starter app and provide a link to the GitHub repo? Code snippets are not typically enough to reproduce the issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
