### ISSUE TITLE
bug: ion-segment accidental selection when user only wants to scroll

### ISSUE THREAD

**Issue by cmaas** [ionic-team/ionic-framework#22161]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
If content is larger than the visible area and thus, can be scrolled vertically, `ion-segment` is too trigger sensitive. For example, if an `ion-segment` is in the middle of the visible area and the users accidentally taps on it because she wants to scroll the view vertically, the selection of `ion-segment` will change. This is especially bad, if `ion-segment` is used as some kind of input to select a value.

**Expected behavior:**
`ion-segment` seems to trigger `ontouchstart`. However, it should probably trigger only if `ontouchstart` does not lead to scrolling. Or to put another way: If the user intends to scroll, lock `ion-segment` so that it can't be triggered accidentally. Not sure what the usual mechanism is in Ionic to prevent accidental triggering of buttons, tabs or whatever when the user only wants to scroll the view.

**Steps to reproduce:**
* Open https://ionicframework.com/docs/demos/api/segment/index.html?ionic:mode=ios on an actual device (tested on iPhone with iOS 14 and Samsung with Android 10)
* Drag the view vertically but aim for a segment button when you touch the screen
* See how the segment button is selected, although you wanted to scroll

**Interestingly, if `ion-segment` itself is scrollable, it doesn't happen!**

**Comment by cmaas** [comment]
Hotfix for everyone having the same problem:

Set scrollable to true (this disables the dragging gesture and adds some CSS):

`<ion-segment scrollable>`

Reverse the applied CSS with inline styles:

`<ion-segment style={{'width': '100%', 'justify-content': 'center', 'overflow-x': 'visible'}} scrollable={true}>`

**Comment by liamdebeasi** [comment]
Can you provide some clarified steps to reproduce the issue? When I scroll the page, the segment does not accidentally select.

I think the best long term solution here is to allow users to disable the gesture when used in this way. We have an open issue at https://github.com/ionic-team/ionic-framework/issues/22048, and someone has added a PR that enables this feature.

**Comment by cmaas** [comment]
@liamdebeasi It only happens if you start scrolling by tapping on the segment button. It doesn't select by itself. You have to touch it. The thing is: If you have thousands of users, someone will accidentally touch the segment button if it's in the middle of the screen. Let me know if this didn't help. Then I make a video.

> I think the best long term solution here is to allow users to disable the gesture when used in this way.
Yes, that makes a lot of sense.

**Comment by liamdebeasi** [comment]
Thanks! I was able to reproduce the issue. Yeah, I agree that the behavior is not ideal when used in this manner. 

I am going to merge this issue with https://github.com/ionic-team/ionic-framework/issues/22048. I have reviewed the PR that adds the disable gesture feature, so we should be able to merge it pretty soon.

**Comment by cmaas** [comment]
@liamdebeasi Thanks for taking the time to look into this and for finding a good solution :)
