### ISSUE TITLE
bug: <ion-split-pane> strange behavior on Safari, web app breaks

### ISSUE THREAD

**Issue by earthican** [ionic-team/ionic-framework#22169]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When selecting items in an `<ion-split-pane>`, web app breaks in Safari (Safari 14, macOS Catalina).
Works fine in Chrome and Firefox.

**Expected behavior:**
Selecting items in `<ion-split-pane>` should work normally, as it does in Chrome and Firefox.

**Steps to reproduce:**

Start a new Ionic project using the `sidemenu` starter and run dev server:

```
$ ionic start sample sidemenu --type=ionic-angular
$ ionic serve
```

Then, open the web app and try to navigate using the side menu buttons.

**Related code:**

A sample application via GitHub:
https://github.com/earthican/ion-split-pane-safari-bug

**Other information:**

Bug demo screencast:
https://github.com/earthican/ion-split-pane-safari-bug/blob/master/bug-demo.mov

**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI                     : 6.11.8 (/path/to/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.11.0 (/path/to/node/v14.11.0/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21939#issuecomment-694259307.
