### ISSUE TITLE
bug: Cannot select certain time with ion-datetime

### ISSUE THREAD

**Issue by ahsanhabib91** [ionic-team/ionic-framework#22171]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

In case of time selection with format **h:mm A**, I cannot select **12:00 AM**. It automatically converts into **12:00 PM**. Also, I cannot select **12:XX PM**, where **XX>0** and **XX<60**. In such case, it automatically turns into **12:XX AM**
**Expected behavior:**

I should be able to select **12:00 AM** and **12:XX PM**
**Steps to reproduce:**

I have found such problem in my personal Ionic project. However, this can also be reproduced on the Ionic documentation page. Just go to the Ionic [datetime picker documentation page](https://ionicframework.com/docs/api/datetime). Select the label **Start Time** which has format **h:mm A**. Then try to select **12:00 AM** and **12:XX PM**.
**Related code:**

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : not installed

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 14 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.9.0
   native-run (update available: 1.1.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/bs263/Library/Android/sdk)
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina

```

**Comment by 1x2x3x4x** [comment]
This happens with the 5.3.3 version. I had to downgrade back to 5.3.2 to fix it also.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide some clarified steps to reproduce the issue? Here are the steps I am following:

1. Open the "Start Time" datetime on the link provided.
2. Change the minutes column to "00". Time now reads "2:00 AM".
3. Change the hours column to "12".

From here, the AM columns should automatically change from AM-->PM. This is expected behavior as this is what happens on native iOS and Android datetime pickers.

Is this the issue you are referring to, or are you referring to something else?

**Comment by ahsanhabib23** [comment]
@liamdebeasi Thanks for the reply. 

1. Open the "Start Time" datetime on the link provided.
2. Select **12:00 AM** Just like the 1st image provided. 
3. After that press **Done**
4. Now you suppose to **Start Time** as **12:00 AM**. However, you will see **12:00 PM** instead just like the 2nd image provided.
5. In the same process, If you select **12:30 PM** and press done, you will see **12:30 AM**

Please, feel free to ask any further query !!!

![image](https://user-images.githubusercontent.com/47731442/94294004-f9333180-ff80-11ea-98b1-d564a85e16f7.png)
![image](https://user-images.githubusercontent.com/47731442/94294084-1bc54a80-ff81-11ea-8926-9c92f927f4d6.png)

**Comment by ahsanhabib91** [comment]
@liamdebeasi Thanks for the reply.
1. Open the "Start Time" datetime on the link provided.
2. Select **12:00 AM** Just like the 1st image provided.
3. After that press Done
4. Now you suppose to Start Time as **12:00 AM**. However, you will see **12:00 PM** instead just like the 2nd image provided.
5. In the same process, If you select **12:30 PM** and press done, you will see **12:30 AM**.

Please, feel free to ask any further query !!!

![image](https://user-images.githubusercontent.com/9888992/94299112-05bb8800-ff89-11ea-8b33-1c0e95cda8a7.png)
![image](https://user-images.githubusercontent.com/9888992/94299163-166bfe00-ff89-11ea-8afa-7342bc68ccde.png)

**Comment by liamdebeasi** [comment]
Thanks I can reproduce this issue. This appears to be related to https://github.com/ionic-team/ionic-framework/commit/8b85fe0d9eea39adfdcf790bf00d8ef91d5edbe7 cc @brandyscarney
