### ISSUE TITLE
feat: Ionic Vue: Global registration of Ionic components

### ISSUE THREAD

**Issue by Sacrekin** [ionic-team/ionic-framework#22182]
# Feature Request

**Ionic version:**
[x] **5x**
@ionic/vue@0.4.0 @ionic/vue-router@0.4.0

**Describe the Feature Request**
As described in the Vue 3 doc, enable the global registration of Ionic components to avoid the repetition of lengthy imports & component registration in each page.

**Describe Preferred Solution**
Use the Vue 3 documented approach as described in the related code section below.

**Describe Alternatives**
Registration section in config.JSON

**Related Code**
Example for Vue 3 doc::

import { IonPage } from '@ionic/vue';

const app = createApp(App)
  .use(IonicVue)
  .use(router);

app.component('ion-page',IonPage);

**Comment by dlodeprojuicer** [comment]
Someone raised this on [Slack](https://ionic-worldwide.slack.com/archives/CJXBR0PNX/p1599724582012000), apparently its not happening... Imagine something like a button or icon is used almost everywhere and you have to import it every time.

**Comment by liamdebeasi** [comment]
Thanks for the issue. So I looked into this, and it appears this is already possible in Ionic Vue. However, we **do not recommend this approach**. Ionic Framework components are lazy loaded which allows us to speed up loading time and reduce your app's initial bundle size.

While it can be tedious to always have to import `IonButton` in every component you use it in, explicitly importing the component provides important information to the compiler as to how it can further optimize your application's bundle. Registering your components globally defeats this optimization.

That being said, if you have certain components that you know are going to be used everywhere in your app you can register them in `main.ts`:

```typescript
import { IonButton } from '@ionic/vue';

const app = createApp(App)
  .use(IonicVue)
  .use(router);
  
app.component('ion-input', IonInput);
```

From there, you can use `<ion-input>` in your component templates as you normally would without having to explicitly import it every time. Please use this sparingly!

I am going to close this issue. Thanks!

**Comment by liamdebeasi** [comment]
Hi everyone,

I have been investigating this more and I think I have found a way to globally register components in Vue while still lazy loading the component implementation.

Ionic Vue provides two things:  1) The Web Component implementation and 2) A small function that wraps each Web Component inside a Vue component.

By globally registering the Vue component wrapper, you should be able to use components such as `ion-button` or `ion-input` without having to manually import it into each component. Only when you actually use the component in your template will the component implementation be loaded. If this works as I expect, it would effectively get rid of the performance overhead concerns I initially had.

I am going to reopen this issue and will post a dev build when I have progressed on this task. Thanks!

**Comment by liamdebeasi** [comment]
Hi everyone,

We have added new documentation with information on how to globally register your Ionic Vue components. It also includes notes on the performance trade-offs that you should be aware of when using global registration: https://ionicframework.com/docs/vue/quickstart#optimizing-your-build

Thanks!
