### ISSUE TITLE
bug: IonIcon in React does not work with string icon or name property

### ISSUE THREAD

**Issue by kevinclarkadstech** [ionic-team/ionic-framework#22181]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I want to dynamically set the icon based on a record from the server. So have an object with a string property called myIcon that is "heart" or "thumbs-up". Then be able to say ''
```

 <IonIcon icon={myIcon} />

```
''. This does not work, nor does the name property. icon is a string property, but even if I just say 
```

 <IonIcon icon="heart" />

```
it still does not work. To see an icon I HAVE to import the icon...I don't want to have to import a bunch of icons and do a big switch statement in the JSX. Even if I use ion-icon with name set, it still doesn't render. In Stencil, this could be done with the name property on ion-icon. To me, this is a bug. It would be great to be able to use either the icon OR the name property.

**Expected behavior:**

I could pass a dynamic string like "heart" or "heart-outline" and see an icon.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by rgoldiez** [comment]
@kevinclarkadstech The icon string you pass in must be imported like this.  

```
import { heart } from 'ionicons/icons';

<IonIcon icon={heart} />
```

**Comment by kevinclarkadstech** [comment]
> @kevinclarkadstech The icon string you pass in must be imported like this.
> 
> ```
> import { heart } from 'ionicons/icons';
> 
> <IonIcon icon={heart} />
> ```

Lol I know...that was the whole point of this bug.  Is there anything you did not understand about how it was worded?

**Comment by rgoldiez** [comment]
@kevinclarkadstech I guess I don’t understand the issue.... this too is working just fine for me...

‘’’
import { heart, heartOutline } from 'ionicons/icons';

<IonIcon icon={someBoolean ? heart : heartOutline} />
‘’’

**Comment by rgoldiez** [comment]
@kevinclarkadstech also, your original post where you say `<IonIcon icon="heart" />` ... that’s not going to work and it’s not expected to.

**Comment by kevinclarkadstech** [comment]
> @kevinclarkadstech also, your original post where you say `<IonIcon icon="heart" />` ... that’s not going to work and it’s not expected to.

But this SHOULD work, after all, the property is string | undefined.  Importing the icon name should just be a helper-style thing.  If I am working in a vanilla JS app or StencilJS app, I can specify the name as a string.  If I have a value coming from the server that can be any of the hundreds of ionicons, I don't want to have to import every one of them and do a switch statement to display it.  The idea is to display one dynamically.

**Comment by rgoldiez** [comment]
@kevinclarkadstech why not import all then?

```
import * as Icons from 'ionicons/icons';
<IonIcon icon={Icons[myIconStringName]} />
```

**Comment by kevinclarkadstech** [comment]
> @kevinclarkadstech why not import all then?
> 
> ```
> import * as Icons from 'ionicons/icons';
> <IonIcon icon={Icons[myIconStringName]} />
> ```

Hmm interesting idea!  I wonder what this would do for performance/bundle size though by importing all of them.

**Comment by rgoldiez** [comment]
Well, if you want dynamic someone / something has to import all of them.  Sorry for originally not understanding your issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue. You can use the `addIcons` function provided in `ionicons` to do this:

**App.tsx**
```tsx
import { addIcons } from 'ionicons';
import { heart } from 'ionicons/icons';

...

addIcons({
  'heart': heart
});
```

from here, you can do:

```tsx
<IonIcon name="heart" />
```

The documentation on this isn't easily accessible, so I created an issue on the ionicons repo to address this: https://github.com/ionic-team/ionicons/issues/887

**Comment by kevinclarkadstech** [comment]
> Thanks for the issue. You can use the `addIcons` function provided in `ionicons` to do this:
> 
> 
> 
> **App.tsx**
> 
> ```tsx
> 
> import { addIcons } from 'ionicons';
> 
> import { heart } from 'ionicons/icons';
> 
> 
> 
> ...
> 
> 
> 
> addIcons({
> 
>   'heart': heart
> 
> });
> 
> ```
> 
> 
> 
> from here, you can do:
> 
> 
> 
> ```tsx
> 
> <IonIcon name="heart" />
> 
> ```
> 
> 
> 
> The documentation on this isn't easily accessible, so I created an issue on the ionicons repo to address this: https://github.com/ionic-team/ionicons/issues/887

Yikes! That's even worse, and doesn't solve the issue. I don't want to have to import anything because everything is dynamic. Why can't I just say name="heart" without addIcons? Seems bizarre.

**Comment by liamdebeasi** [comment]
Having all ionicons be global goes against how React is built and is really not something we recommend. Additionally, this is how React is intended to be used: For example, when you want to use `ComponentA` inside of `ComponentB`, you need to explicitly import `ComponentA` at the top of the file. The same goes for ionicons as it allow for the compiler to better optimize your bundle sizes. See https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs for more information.
