### ISSUE TITLE
(iOS 14) Swipe to go back without reaching threshold causes wrong animation

### ISSUE THREAD

**Issue by biesbjerg** [ionic-team/ionic-framework#22192]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

If you swipe to go back, without reaching threshold, the wrong animation is used (page disappears and animates in again).

![RPReplay_Final1601285857](https://user-images.githubusercontent.com/230182/94417688-ae800800-0180-11eb-8884-5f7b722ff5c9.gif)

**Expected behavior:**

If the swipe-to-go-back threshold is not reached when swiping, page should animate back in place from the place the swipe was stopped.

**Steps to reproduce:**

I used `ionic start list` using Angular and capacitor and ran it on an iOS 14 device.

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.9 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res (update available: 0.15.1) : 0.11.0
   native-run                             : 1.1.0

System:

   NodeJS : v12.15.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21978#issuecomment-693420179.

**Comment by biesbjerg** [comment]
Thanks, I missed that issue! Hoping for an update soon from Apple 😊
