### ISSUE TITLE
ERROR in No NgModule metadata found for ‘AppModule’ Angular 10

### ISSUE THREAD

**Issue by dharmdeep** [ionic-team/ionic-framework#22190]
I am getting [ng] ERROR while ionic serve in No NgModule metadata found for ‘AppModule’ this error. I searched a lot but not getting exact solution. I will be highly thankful if someone give me any idea or any help. I am sharing IONIC and other environment.

```
Ionic Framework               : @ionic/angular 5.3.3
@angular-devkit/build-angular : 0.1001.2
@angular-devkit/schematics    : 10.0.8
@angular/cli                  : 10.1.2
@ionic/angular-toolkit        : 2.3.3

Utility:
cordova-res : not installed
native-run  : not installed

System:
NodeJS : v12.18.4 (C:\Program Files\nodejs\node.exe)
npm    : 6.14.6
OS     : Windows 10
```
My app.module.ts file code

```
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    AppRoutingModule
  ],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```
Can anyone suggest where i am wrong as i globally installed latest version of IONIC, CORDOVA, NODE of all. I am trying from past 2 days but not succeed. I am attaching screenshot pls find.

![Capture](https://user-images.githubusercontent.com/7457022/94403956-d6c13400-018b-11eb-986b-4089f69389c4.PNG)

here is console screenshot. there is nothing error on console and network tab. its giving 404 error like Cannot GET /

![Capture - Copy](https://user-images.githubusercontent.com/7457022/94404261-57803000-018c-11eb-957c-262ab3631b70.PNG)

**Note: I also created this issue on https://forum.ionicframework.com/t/error-in-no-ngmodule-metadata-found-for-appmodule-angular-10/196921 as well as https://stackoverflow.com/questions/63997183/error-in-no-ngmodule-metadata-found-for-appmodule-angular-10 but no response. so I created this on here.**

Thanks in advance !!

**Comment by eun-choi** [comment]
In my case, modifying main.ts as below solved the problem.

```

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';

const appModule = AppModule;
const platformRef = platformBrowserDynamic();
platformRef.bootstrapModule(appModule);

```

**Comment by dharmdeep** [comment]
@eun-choi  Thanks for reply & help.

After implement this code i am getting this error any idea...

![image](https://user-images.githubusercontent.com/7457022/94662425-fd1ad700-0325-11eb-9c6e-9df0869ffbab.png)

**Comment by gp559** [comment]
you can try to remove the installed node modules downgrade the node version and then run npm install. then try to serve the app.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
