### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by PundoJnr** [ionic-team/ionic-framework#22214]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
  When I run ``` ionic serve ``` only the first page is loaded and the site breaks and reloads whenever a click event is initiated. No error in console. It however works well in Chrome.

**Expected behavior:**
 Navigate to respective route on click.

**Other information:**
* When I build for production for the ios platform, the app does not go past the splash screen

**Ionic info:**

``` 
Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.900.7
   @angular-devkit/schematics    : 9.0.7
   @angular/cli                  : 9.0.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.3
   @capacitor/core : 1.5.3

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 19 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.1.0

System:

   Android SDK Tools : 26.1.1 (/home/pj/Android/Sdk)
   NodeJS            : v10.19.0 (/usr/bin/node)
   npm               : 6.14.8
   OS                : Linux 5.4

```

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21939#issuecomment-694259307.
