### ISSUE TITLE
bug: slider is not working when inside of a modal after opening it the 2nd time

### ISSUE THREAD

**Issue by yagnesh-dahisaria** [ionic-team/ionic-framework#22213]
Ionic version:

[x] 6.2.2

Current behavior: Slider using on modal. Slider is working fine while opening first time in modal. but  slider not working while opening same modal 2nd time

Expected behavior: slider should work every time we open modal.

Steps to reproduce:

Related code:

        <ion-slides parallax id="picSlider" #picSlider pager="true"  [options]="sliderConfig">
          <ion-slide *ngFor="let slides of wallPostComments.imageArray">
            
            <img *ngIf="slides.ext == 'jpg' || slides.ext == 'JPG' || slides.ext == 'JPEG' || slides.ext == 'jpeg' || slides.ext == 'png' || slides.ext == 'PNG'" [src]="ImageUrl+slides.imagepath" padding>
            <video *ngIf="slides.ext=='mp4'" width="80%" controls="controls" preload="metadata" webkit-playsinline="webkit-playsinline" class="videoPlayer">
              <source [src]="ImageUrl+slides.imagepath" type="video/mp4" />
             </video>
          </ion-slide>

Other information:

Ionic info: Ionic 6.2.2

insert the output from ionic info he

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
