### ISSUE TITLE
bug: IonBackButton element is not visible on new Vue beta

### ISSUE THREAD

**Issue by NunoSav** [ionic-team/ionic-framework#22217]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When navigating back the `IonBackButton` element disappears

**Expected behavior:**
`IonBackButton` should be visible when there's routes left in the stack.

**Steps to reproduce** & **Related code:**
https://github.com/NunoSav/ionic-vue-beta-navigation-issue
The Readme has the steps for reproduction.

**Other information:**
I've scaffolded the project using ionic cli.
For Android i can still go back by using the phones back button, no workaround for iOS tho.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.8-testing.0
   Ionic Framework : @ionic/vue 0.6.0-dev.202009291532.25d3ea6

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.16.3
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```shell
npm install @ionic/vue@0.6.0-dev.202010061731.4c58b2f @ionic/vue-router@0.6.0-dev.202010061731.4c58b2f
```

**Comment by NunoSav** [comment]
I've only tried this on iOS and it didn't fix the issue.

**Comment by liamdebeasi** [comment]
Hmm can you try deleting `node_modules` and doing a fresh install? I am testing the dev build with the application you provided and I am seeing it resolved on my end.

**Comment by NunoSav** [comment]
Done. Nothing changed :\

**Comment by liamdebeasi** [comment]
That's strange. This is what I am seeing with the dev build installed:
![Oct-07-2020 10-07-55](https://user-images.githubusercontent.com/2721089/95342076-06a3c200-0885-11eb-8641-5df96c8d9608.gif)

Is this different from what you are seeing?

**Comment by NunoSav** [comment]
Yes, i still see the issue as originally described. I get to see the `ion-back-button` action once and then it disappears.
I've noticed however one error in the console `TypeError: e.$t is not a function` after pushing first route. This points to minified files of ionic and i haven't been able to trace it to anywhere i could share with you.

**Comment by NunoSav** [comment]
Never mind the error, it was related with i18n.

Since i've been running some tests on the repo used for reproduction of issue i've since reset all changes and am now using the code as seen in https://github.com/NunoSav/ionic-vue-beta-navigation-issue.

I then switched the `@ionic/vue` and `@ionic/vue-router` versions to the ones you mentioned. `yarn.lock` has the following:
```
"@ionic/core@0.6.0-dev.202010061922.2bad1bb":
  version "0.6.0-dev.202010061922.2bad1bb"
  resolved "https://registry.yarnpkg.com/@ionic/core/-/core-0.6.0-dev.202010061922.2bad1bb.tgz#4b62bfc76bf7688c157e00d9a9c49c589424c55c"
  integrity (...)
  dependencies:
    ionicons "^5.1.2"
    tslib "^1.10.0"

"@ionic/vue-router@^0.6.0-dev.202010061731.4c58b2f":
  version "0.6.0-dev.202010061922.2bad1bb"
  resolved "https://registry.yarnpkg.com/@ionic/vue-router/-/vue-router-0.6.0-dev.202010061922.2bad1bb.tgz#2749a2bd8d726a631c28fcda370aecc64badfe4f"
  integrity (...)

"@ionic/vue@^0.6.0-dev.202010061731.4c58b2f":
  version "0.6.0-dev.202010061922.2bad1bb"
  resolved "https://registry.yarnpkg.com/@ionic/vue/-/vue-0.6.0-dev.202010061922.2bad1bb.tgz#200151b4be2087a03571396e5052f7d0b21f0da8"
  integrity (...)
  dependencies:
    "@ionic/core" "0.6.0-dev.202010061922.2bad1bb"
    ionicons "^5.1.2"
```

Any idea of what can be done to further debug this on my side? Thanks.

**Comment by liamdebeasi** [comment]
Hmm can you try deleting `yarn.lock` then doing a fresh install? I've seen this happen with `package-lock.json` where it has an older dev build than what `package.json` has.

**Comment by NunoSav** [comment]
I've done that before when deleting `node_modules` but did it again just to be sure. Still doesn't work.

**Comment by liamdebeasi** [comment]
Oh actually it looks like it is grabbing a "newer" dev build, but that dev build does not have your fix in it. 

Try doing:

```
npm install @ionic/vue@0.6.0-dev.202010061731.4c58b2f @ionic/vue-router@0.6.0-dev.202010061731.4c58b2f --save-exact
```

**Comment by NunoSav** [comment]
Nice find!

I installed the correct version and it works.

Sorry for all the hassle 😛

**Comment by liamdebeasi** [comment]
Glad it works now! I will merge the PR shortly.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22260, and a fix will be available in an upcoming release of Ionic Framework.
