### ISSUE TITLE
bug: Reopening issue 9856 (virtualScroll): checkbox is not updating value on click

### ISSUE THREAD

**Issue by bbehling** [ionic-team/ionic-framework#22212]
Reopening issue https://github.com/ionic-team/ionic-framework/issues/9856

This is still occurring in latest version of Ionic

**Comment by liamdebeasi** [comment]
Thanks for the issue. With upcoming major versions of Ionic Framework, we are going to be transitioning to using Angular's CDK Scroller. As a result, we have a freeze on new features and bug fixes on ion-virtual-scroll. See https://material.angular.io/cdk/scrolling/overview for how to get started with CDK Scroller.

**Comment by bbehling** [comment]
Other than implementing a CDK scroller, any workaround ideas in the meantime?

There are quite a few issues I noticed with ion-checkbox in a virtual scroll list. Vanilla input checkboxes do not have any issues inside the virtual scroll.

**Comment by crees1** [comment]
@liamdebeasi Angular's CDK Scroller doesn't really seem to play nice with Ionic's pull to refresh. Currently scrolling in the CDK Scroller will randomly activate the refresher. Will there be work done to ensure the two are working nicely together?

**Comment by liamdebeasi** [comment]
Definitely. We have new docs coming, and we are tracking bugs that are still a problem with CDK Scroller: https://github.com/ionic-team/ionic-docs/pull/1406
