### ISSUE TITLE
bug: Wrong input value of ion-datetime

### ISSUE THREAD

**Issue by elvisgraho** [ionic-team/ionic-framework#22216]
# Bug Report

**Ionic version:**

[x] **5.3.4**

**Current behavior:**

ion-datetime suddenly decides to go one day back all the time. iOS 14

**Steps to reproduce:**

```html
    <ion-datetime
       value="2020-06-02T00:00:00"
       display-timezone="utc">
    </ion-datetime>
```

Ion-datetime configures it to June 1, 2020

**Comment by elvisgraho** [comment]
And also the onChange event has a strange output "2018-06-01T22:00:00-00:00"

**Comment by elvisgraho** [comment]
Setting the value to 3 hours more fixed it value="2020-06-02T03:00:00"
I wonder if it has something to do with a new output format "2018-06-01T22:00:00-00:00" which has this weird hour range.

**Comment by liamdebeasi** [comment]
Can you provide a repo I can use to reproduce this issue? I cannot reproduce it using the code snippet provided.

**Comment by elvisgraho** [comment]
I managed to achieve the same thing in [Web-Preview](https://ionicframework.com/docs/api/datetime).
Just adding the ```display-timezone="utc"``` sets 1 day back.

**Comment by elvisgraho** [comment]
I would still call it a bug because "displayTimezone" should not alter my input value.
