### ISSUE TITLE
feat: autofocus on AlertController input

### ISSUE THREAD

**Issue by korneeld** [ionic-team/ionic-framework#22215]
I am using Ionic 6.11.8 with angular.

There does not seem to be a way to automatically focus and open the keyboard after showing a popup with an input field using AlertController. Or am I missing something?

Best regards

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/16941.
