### ISSUE TITLE
feat: expose css variables for ion-segment overflow scrollbar

### ISSUE THREAD

**Issue by not-a-designer** [ionic-team/ionic-framework#22223]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
expose css variable for ion-segment with the `scrollable="true"` directive, or a shadowdom `::part(native)` to allow custom coloring of the overflow scrollbar. Currently it is only orange

**Describe Preferred Solution**
```
ion-segment::part(native) {
    scrollbar-color: //COLOR;
}
```

```
ion-segment {
    --overflow-scrollbar: //COLOR;
}
```

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. You can apply your scrollbar styles to the `ion-segment` element directly.

CodePen Example: https://codepen.io/liamdebeasi/pen/VwaJxXj
