### ISSUE TITLE
bug: Ion-Nav framework delegate is missing

### ISSUE THREAD

**Issue by aasif** [ionic-team/ionic-framework#22238]
# Bug Report: 
**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

There isn't rich documentation available on how to use `ion-nav`
Using `ion-nav` to implement nested routing inside an `ion-modal` gives ` framework delegate is missing` error

**Expected behavior:**

Nested routing should work

**Steps to reproduce:**

1. Add an ion-page with ion-nav in the template
2. Open this page in an ion-modal
3. Try to push pages/components on the ion-nav inside the parent page in step 1.

**Related code:**
1. I am trying to implement nested routing inside an ion-modal. I have a controller component that has the following template 

```HTML
<ion-nav #nav [root]="rootPage" [rootParams] ="rootParams" ></ion-nav>
```
 
2. I want to push other components/pages on this nav & set the first component/page as the `rootPage` along with its params as `rootParams`. I get the following error `framework delegate is missing`

**Comment by liamdebeasi** [comment]
Thanks for the issue, can you provide a repo I can use? Code snippets are not typically enough to reproduce the issue.

**Comment by aasif** [comment]
I was able to resolve this issue on my own. It turns out it was a slight mistake on my end. I missed out adding my controller modal to the `app.module.ts` imports which is why the template inside it started malfunctioning. By making this change I am now able to both push things on to the nav and also present `ion-nav` in a modal template.
