### ISSUE TITLE
bug: IOS PWA scroll bug

### ISSUE THREAD

**Issue by conde2** [ionic-team/ionic-framework#22240]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.3.4

**Current behavior:**

When scrolling in IOS PWA sometime the entire page scrolls and then freeze, if you try to scroll the ion content you are not able to. In my case it is possible to see the scrollbar as it is scrolling the entire page like a single block.
 
If you see this report, there are alot of people still reporting the same issue for the newest ionic, but reporting in the wrong place.
https://github.com/ionic-team/ionic-v3/issues/984#issuecomment-702663628

**Expected behavior:**
Not scroll the entire page and after that stop freezing

**Steps to reproduce:**
The Ion start examples can reproduce this just add it as PWA make sure ion content has enought content to be scrollable and try to scroll clicking in the tab bar moving to the top.

A sample application via GitHub
Just use the start tabs content and add enought content to be scrollable, using ion Slides is also a good idea

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.6 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.1.3
   @angular/cli                  : 10.1.3
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : not installed

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.12.0 (/usr/bin/node)
   npm    : 6.14.7
   OS     : Linux 5.8

```

**Comment by eun-choi** [comment]
I've reported the same problem.
#22205

**Comment by conde2** [comment]
@eun-choi Thanks will close this one and comment in your issue.
