### ISSUE TITLE
ionInfinitebug: vue3.0 添加滚动事件不执行，求demo写法 谢谢

### ISSUE THREAD

**Issue by xlanghejianfeng** [ionic-team/ionic-framework#22248]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by BerkeAras** [comment]
Edit issue: Fill out template correctly
