### ISSUE TITLE
bug: Cannot find module 'fork-ts-checker-webpack-plugin-v5'

### ISSUE THREAD

**Issue by MonsPavel** [ionic-team/ionic-framework#22246]
after npm install -g @ionic/cli@testing and ionic start myApp blank --type vue --tag vue-beta cd myApp and ionic serve
i see Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5', i try npm install --save-dev fork-ts-checker-webpack-plugin, but it doesn't help

**Comment by kanika-agarwal-hub** [comment]
> after npm install -g @ionic/cli@testing and ionic start myApp blank --type vue --tag vue-beta cd myApp and ionic serve
> i see Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5', i try npm install --save-dev fork-ts-checker-webpack-plugin, but it doesn't help

Hey,

I was getting the same error. I was using node:12.13.0 version earlier and then I changed the version to node:12.18.4 and the error was gone. Hope this helps.
