### ISSUE TITLE
bug: Vue fail to navigate with IonBackButton and default-href

### ISSUE THREAD

**Issue by scottix** [ionic-team/ionic-framework#22258]
**Bug Report**

When I use the IonBackButton and default-href it Fails to navigate back.

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
I open a tab with the tabs navigation. Go to the second tab and hit the backButton and nothing happens.

**Expected behavior:**
Should take me to the previous page.

**Steps to reproduce:**
1. Go to tabs with IonBackButton
1. Click on another Tab with IonBackButton
1. Hit the IonBackButton

**Related code:**

```
    <ion-header>
      <ion-toolbar>
        <ion-buttons>
          <ion-back-button default-href="/pretab"></ion-back-button>
        </ion-buttons>
        <ion-title>Tab 2</ion-title>
      </ion-toolbar>
    </ion-header>
```

Updated an example here.  
https://github.com/scottix/vue-pretab

**Other information:**
Might be similar to this
https://github.com/ionic-team/ionic-framework/issues/22166#issuecomment-702078531

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.8-testing.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 0.5.2

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.2.1) : 0.2.5

System:

   NodeJS : v12.18.4 (/usr/bin/node)
   npm    : 6.14.6
   OS     : Linux 5.4
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@0.6.0-dev.202010072007.d746561 @ionic/vue-router@0.6.0-dev.202010072007.d746561 --save-exact
```

**Comment by scottix** [comment]
> Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?
> 
> ```
> npm install @ionic/vue@0.6.0-dev.202010072007.d746561 @ionic/vue-router@0.6.0-dev.202010072007.d746561 --save-exact
> ```

Works

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22275, and a fix will be available in an upcoming release of Ionic Framework.
