### ISSUE TITLE
bug: ion refresher not hiding on IOS (reopen issue)

### ISSUE THREAD

**Issue by ItsMeSandu** [ionic-team/ionic-framework#22257]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

see @https://github.com/ionic-team/ionic-framework/issues/21291

I also noticed that this issue always occurs if you dragging an element (like a card or something). If you are dragging the "scrollview", the refreshIcon hides after the animation.  

**Expected behavior:**
see @https://github.com/ionic-team/ionic-framework/issues/21291

**Steps to reproduce:**

see @https://github.com/ionic-team/ionic-framework/issues/21291#issuecomment-629070437

**Additional info**
maybe there is something with the typeerror in the screenshot 
![Bildschirmfoto 2020-10-06 um 17 28 48](https://user-images.githubusercontent.com/15786274/95223560-07434680-07fa-11eb-8ab9-5f6104c5e897.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Please see https://github.com/ionic-team/ionic-framework/issues/21291#issuecomment-629244683. This is an issue in WebKit, not Ionic Framework.

**Comment by ItsMeSandu** [comment]
oh okay. It seems that I overlooked your comment. 
Sorry for that.

**Comment by liamdebeasi** [comment]
Oddly enough, the particular WebKit bug got marked as resolved the other day: https://bugs.webkit.org/show_bug.cgi?id=209968. Looks like it will be fixed in upcoming versions of iOS 🚀
