### ISSUE TITLE
bug: vue tabs template > on ios bottom tab bar can be swiped up with page

### ISSUE THREAD

**Issue by holygekko** [ionic-team/ionic-framework#22268]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When you create a vue tabs template project, the bottom tab bar can be swiped up the page on ios. It doesn't stick to bottom whatever happens.

**Expected behavior:**
I expected it to behave the same as for a react tabs template project. There the bottom bar sticks to the bottom of the screen on ios.

**Steps to reproduce:**
create a new project: ionic start --tag vue-beta
and select the tabs template
add capacitor
add ios platform
run the project in the simulator
pull from the bottom tab up

compare the behavior with a standard react template.

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.11.8-testing.0
   Ionic Framework : @ionic/vue 0.5.2

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Comment by holygekko** [comment]
Found out what the problem is! In Tabs.vue the `<ion-tabs>` component is wrapped in a `<ion-content>` component. This is causing it to scroll with the page.

**Comment by liamdebeasi** [comment]
Thanks! You are correct, that `ion-content` should not be there. I have updated the starters with this change, and you can safely remove `ion-content` from `Tabs.vue` in your own application.
