### ISSUE TITLE
Ionic scroll force feedback does not match Swift

### ISSUE THREAD

**Issue by christianmackin** [ionic-team/ionic-framework#22265]
Generator = UISelectionFeedbackGenerator() in Swift results in a given feedback intensity as can be felt while using the selection picker with the native iOS Timer settings. 

Using Ionic results in a very low feedback during scroll and then heavy feedback on selection. 

**Ionic version:**

[x] **4.x**
[ ] **5.x**

**I'm submitting a ...** 

[ ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify what the issue you are seeing is? Is this in regards to `ion-datetime` or `ion-picker`?

**Comment by BerkeAras** [comment]
@christianmackin Please fill out the Issue Template first.
