### ISSUE TITLE
bug: nested item is not always ready to listen to ionStyle event

### ISSUE THREAD

**Issue by hendrik244** [ionic-team/ionic-framework#22269]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
I placed a custom component into an ion-item. ion-item is part of an ion-reorder-group and an ion-list.
The ion-item contains a my custom component "app-resume-employment" and the ion-reorder element.
The ion-list is displayed on a page. When I'm entering the page the first time, the ion-item element looks good.
But when I navigate back and reentering the page the ion-item looses its right look.
There are no slots and wrapper anymore. 
(see screenshots)
<img width="377" alt="Bildschirmfoto 2020-10-07 um 17 05 24" src="https://user-images.githubusercontent.com/33331414/95349616-92d2db00-08bf-11eb-8a3d-f6c045bcb179.png">
<img width="390" alt="Bildschirmfoto 2020-10-07 um 17 06 07" src="https://user-images.githubusercontent.com/33331414/95349628-95cdcb80-08bf-11eb-8a5b-5ce01cd99fab.png">

**Expected behavior:**
I want to make sure the ion-item always looks the same. 

**Steps to reproduce:**
see the attached code to reproduce it.

**Related code:**

.html
```
<ion-content>
  <ion-list>
    <ion-reorder-group disabled="false">
      <ion-item
        lines="none"
        *ngFor="let employment of worker?.$cv?.$employments"
      >
        <app-resume-employment
          #employmentComponent
          [employmentItem]="employment"
          (onDelete)="deleteResume($event)"
          (onChange)="resumeDidChange()"
          class="w-100"
          item-content
        ></app-resume-employment>
        <ion-reorder item-content></ion-reorder>
      </ion-item>
    </ion-reorder-group>
  </ion-list>
  <ion-grid>
    <ion-row class="text-align-center">
      <ion-col>
        <ion-button
          color="primary"
          (click)="addNewResume()"
          id="newResumeButton"
        >
          <ion-icon slot="start" name="add-circle-outline"></ion-icon>
          Neue Anstellung
        </ion-button>
      </ion-col>
    </ion-row>
  </ion-grid>
</ion-content>
```

app-resume-component .html
```
<div class="this-component">
  <ion-grid *ngIf="employmentItem">
    <ion-row>
      <ion-col class="ion-padding-horizontal-small">
        <ion-item lines="none" class="w-100">
          <ion-label class="ion-text-wrap">
            TEXT
          </ion-label>
          <ion-icon
            name="close-outline"
            slot="end"
            (click)="deleteResume"
          ></ion-icon>
        </ion-item>
      </ion-col>
    </ion-row>
    <form [formGroup]="form">
      <ion-row>
        <ion-col class="ion-padding-horizontal-small">
          <ion-list>
            <ion-select
              formControlName="employment_category"
              placeholder="Auswählen"
              interface="popover"
            >
              <ion-select-option value="VALUE"
                ></ion-select-option
              >
              <ion-select-option value="VALUE"
                ></ion-select-option
              >
            </ion-select>
            <hr class="m-0" />
            <ion-item lines="none">
              <ion-label>von</ion-label>
              <ion-datetime
                formControlName=""
                (ionChange)=()"
                displayFormat="MMM YYYY"
                placeholder="Monat Jahr"
                doneText="Fertig"
                cancelText="Abbrechen"
                [max]="this.maxDate"
              ></ion-datetime>
            </ion-item>
            <hr class="m-0" />
            <ion-item lines="none">
              <ion-label>bis</ion-label>
              <ion-datetime
                formControlName=""
                (ionChange)="()"
                displayFormat="MMM YYYY"
                placeholder="Monat Jahr"
                doneText="Fertig"
                cancelText="Abbrechen"
                [max]="this.maxDate"
                [min]="employmentItem.period_start"
                [attr.disabled]="periodEndDisabled"
              ></ion-datetime>
            </ion-item>
            <ion-item lines="none">
              <ion-label>TEXT</ion-label>
              <ion-checkbox
                (ionChange)="employmentChanged()"
                color="primary"
                [checked]="isCurrent"
                (ionChange)="EVENT"
                checked="false"
              ></ion-checkbox>
            </ion-item>
            <hr class="m-0" />
            <ion-item lines="none">
              <ion-textarea
                formControlName=""
                (ionChange)="function()"
                color="secondary"
                inputmode="text"
                autocapitalize="sentence"
                placeholder="TEXT"
                rows="3"
                required
              >
              </ion-textarea>
            </ion-item>
          </ion-list>
        </ion-col>
      </ion-row>
    </form>
</ion-grid>
</div>
```

**Other information:**
see screenshots

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.9 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.4.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v14.7.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
   Xcode  : Xcode 12.0.1 Build version 12A7300
```

**Comment by hendrik244** [comment]
Hi,

I provided the scenario in this repository:
https://github.com/hendrik244/ion-item-looses-look

First enter the page by click on the ion-item "CLICK ME", then navigate back by clicking the button "back". Reenter the page by clicking on the ion-item "CLICK ME" again.

**Comment by liamdebeasi** [comment]
The issue appears to be that `ion-checkbox` is something being added to the DOM before `ion-label`. 

I will look into this more, but as a temporary workaround you can explicitly state the `slot`:

```html
<ion-item>
  <ion-label slot="start">akt. Anstellung</ion-label>
  <ion-checkbox slot="end"></ion-checkbox>
</ion-item>
```

**Comment by liamdebeasi** [comment]
The problem here is that `ion-textarea` fires an `ionStyle` event when it loads, but the parent `ion-item` is not ready to listen for `ionStyle` for whatever reason, so the event continues to bubble to top-most `ion-item` causing it to add classes which interferes with the styles as noted in this thread. (If the parent `ion-item` was ready to receive the event, it would have called `ev.stopPropagation()`, preventing the event from bubbling to the top-most `ion-item`).

While we do not recommend nesting `ion-item`, this is potentially an issue with other components that should be nested so I am going to mark this as a bug.

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with form components such as input and checkbox This issue is fixed when using that new syntax. We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new form syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
