### ISSUE TITLE
bug: ion-refresher very lag in Android

### ISSUE THREAD

**Issue by paulovargatt** [ionic-team/ionic-framework#22276]
Hello friends,
After implementing the ion-refresher feature in my app I noticed an abnormal slowness in his transition, there is a lot of lag when starting the transition by playing, as shown in the video ... I created a example a project "conference", which can be accessed on git.

In the browser everything looks normal, however when it is tested on the device even with build --prod lags happen

# Bug Report

**Ionic version:**
[x] **5.x**

**Steps to reproduce:**
Clone [https://github.com/paulovargatt/ion-refresher-lag](https://github.com/paulovargatt/ion-refresher-lag)
npm i
ionic cordova build android --prod

```
    <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
        <ion-refresher-content>
        </ion-refresher-content>
    </ion-refresher>
```

**Other information:**
Video (tested on an android 10)
[![](http://img.youtube.com/vi/kXJuw34C2Tg/0.jpg)](http://www.youtube.com/watch?v=kXJuw34C2Tg "")

**Ionic info:**

```
Ionic:
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.1.4
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.4.7, (and 14 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.0.0) : 0.2.8

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v12.13.1
   npm               : 6.14.8
   OS                : Windows 10


```

**Comment by indraraj26** [comment]
may be duplicate https://github.com/ionic-team/ionic-framework/issues/22008#issuecomment-704956999

**Comment by liamdebeasi** [comment]
This was a regression in Chrome 85. Please update to Chrome 86 to receive a fix for this issue: https://github.com/ionic-team/ionic-framework/issues/22008#issuecomment-686152162.

**Comment by paulovargatt** [comment]
Real problem with version 85.
I tried to update the webview, but the latest version is 85 in the playstore, even though my chrome is with version 86.

To solve it, I had to uninstall the webview app from the playstore, which made the system go back to version 83 of the webview, solving the problem.

Thank you
