### ISSUE TITLE
bug: Swiper params is null/undefined after slides are cleared

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#22289]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Application displays slides in swiper. Upon the action of changing the zip code to change clubs, the slides are cleared, and recreated. At that time, the following errors appear in the console.log:

<img width="1686" alt="Screen Shot 2020-10-09 at 4 58 11 PM" src="https://user-images.githubusercontent.com/1526846/95635124-34d5fd00-0a51-11eb-8752-bb956cd76dc0.png">

Working on narrowing down a reproduction case.

**Expected behavior:**
There would not be an error in the console.

**Steps to reproduce:**
In a sample APK that we have for another issue, open the app and connect the dev tools then use the login page to toggle between the two following zip codes:

- 18444
- 43085

You will see the error in the console log when you do this

**Comment by kensodemann** [comment]
Spoke with the user having this issue. They are currently patching Ionic as such:

```
     async optionsChanged() {
         if (this.swiperReady) {
             const swiper = await this.getSwiper();
-            Object.assign(swiper.params, this.options);
-            await this.update();
+            if (swiper && swiper.params) {
+              Object.assign(swiper.params, this.options);
+              await this.update();
+            }
         }
     }
```

Just in several places because they are applying this to the dist output...

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/23239.
