### ISSUE TITLE
bug: multi tab setup causes pages to render in wrong outlet

### ISSUE THREAD

**Issue by dlodeprojuicer** [ionic-team/ionic-framework#22286]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x** 

**Current behavior:**

Sometimes I get `Cannot read property 'classList' of undefined` when navigating between two pages.

**Expected behavior:**

**Steps to reproduce:**

This was mentioned [here](https://github.com/ionic-team/ionic-framework/issues/22166).... The error came up when I upgraded to `0.5.2`. Now I am on `5.4.0-rc.1`.

1. Clone and run the app
2. Open Chrome dev tools
3. On the app click Profile then click Home. The error will show up on the console.

**Related code:**

[Github repo](https://github.com/dlodeprojuicer/classListError)

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI       : 6.11.8-testing.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.0-rc.1

Capacitor:

   Capacitor CLI   : 2.4.1
   @capacitor/core : 2.4.1

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.18.0 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.4.0-dev.202010121817.181d322 @ionic/vue-router@5.4.0-dev.202010121817.181d322 --save-exact
```

**Comment by dlodeprojuicer** [comment]
@liamdebeasi the build resolves the issue.
