### ISSUE TITLE
bug: vue latest ion-tabs slot top not work 

### ISSUE THREAD

**Issue by xlanghejianfeng** [ionic-team/ionic-framework#22290]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by BerkeAras** [comment]
@xlanghejianfeng Could you please fill out the issue template? What does not work - and if possible, reproduce and show us some code. 😄
