### ISSUE TITLE
bug: Ionic Gestures with direction Y

### ISSUE THREAD

**Issue by TekinGomes37** [ionic-team/ionic-framework#22292]
# Bug Report

**Ionic version:**
[x] **5.x**

**Platform:**
[x] **Cordova Android**
[x] **Capacitor Android**

**Current behavior:**
When I create a Gestures by specifying that the direction must be the Y axis and not the X axis, I have a very important refresh loss.

**Expected behavior:**
Have the same result of refreshing the X axis with the Y axis.

**Steps to reproduce:**
If we copy exactly what the Ionic documentation (https://ionicframework.com/docs/utilities/gestures#basic-gestures), in a fresh project just by adding "direction: y" in the construction parameters.

**Related code:**
https://ionicframework.com/docs/utilities/gestures#basic-gestures)

```
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import { createGesture, GestureDetail } from '@ionic/core';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements AfterViewInit {
  @ViewChild('appStoreId', { static: false }) slide: ElementRef<HTMLDivElement>;
  @ViewChild('appStoreId2', { static: false }) p: ElementRef<HTMLParagraphElement>;

  constructor() {
  }

  ngAfterViewInit(): void {
    this.observerClientY();
  }

  observerClientY() {
    const gesture = createGesture({
      el: this.slide.nativeElement,
      gestureName: 'touchmouve2',
      threshold: 0,
      maxAngle: 1,
      direction: 'y',
      onMove: details => { this.mouseMove(details) }
    });

    gesture.enable();
  }

  private mouseMove(detail: GestureDetail) {
    const type = detail.type;
    const currentX = detail.currentX;
    const deltaX = detail.deltaX;
    const velocityX = detail.velocityX;
  
    this.p.nativeElement.innerHTML = `
      <div>Type: ${type}</div>
      <div>Current X: ${currentX}</div>
      <div>Delta X: ${deltaX}</div>
      <div>Velocity X: ${velocityX}</div>`
  }

}

```

**Other information:**
Need run with device.
My phone run with Android 10, I also tested with an Android 9, I have the same problems.

cordially.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.11 (C:\Users\leon-\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.5
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.2.1

System:

   Android SDK Tools : 26.1.1 (C:\Users\leon-\AppData\Local\Android\Sdk)
   NodeJS            : v12.18.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.5
   OS                : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify the issue you are running into? It sounds like on Android, Chrome's pull to refresh effect is kicking in as well?

**Comment by TekinGomes37** [comment]
Hello,

I have an application that must detect the location of the user's finger, preciously the Y axis. When I create a gesture with "GestureController", I specify that the direction that the gesture must be triggered is the Y. Then in the "onMove" function I take currentY from "GestureDetail", and I display its content in the view.
 
Then I launch the application in an Android terminal, once the application is launched, we notice that the view has trouble refreshing the currentY data, while the finger is sliding.

But I noticed 3 things:

* If you change in the "GestureController" configuration, the direction Y by X, the currentY value doesn't cause any problem anymore, because you start dragging your finger from left to right, then from top to bottom, doing this, the view manages to refresh the currentY value.

* If you reset the direction to Y, and you drag with 2 fingers, the currentY value is correctly refreshed in the view.

* And last but not least, for the currentY value in the view to refresh correctly using only 1 finger, just open the Google Chrome browser debug, and inspect the device in the Console menu. This allows the view to refresh the currentY value.

**Comment by liamdebeasi** [comment]
Apologies for the delay. Can you please reproduce this issue in an Ionic starter app and send the GitHub link? It is hard to say what is going on when I can't reproduce the issue myself.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
