### ISSUE TITLE
bug: fix for react security vulnerability breaks build

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-framework#22294]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

update react tabs starter to resolve security vulnerability

`npm audit fix`

shows this result

![2020-10-11 21_36_04-Window](https://user-images.githubusercontent.com/140737/95706050-a3aa8600-0c0a-11eb-8fa4-34285ec72902.png)

Stuck at emitting

Reported here but not fixed

https://github.com/ionic-team/ionic-cli/issues/4392

**Expected behavior:**

security update should work and not break the system

**Steps to reproduce:**

**Related code:**

Repo: https://github.com/peterennis/ae-gallery-react

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.8-testing.0 (C:\Users\peter\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.3.5

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.1
   native-run  : 1.2.1

System:

   NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify the issue you are running into? I ran `npm audit fix` to resolve any security issues, and your application you provided is still working.

**Comment by peterennis** [comment]
Run `npm audit fix` on the repo and it upgrades react scripts.

Build and run. Message says:

`Files successfully emitted, waiting for typecheck results...`

It then keeps writing to disc without stopping.

I do not want to `emit`.

**Comment by liamdebeasi** [comment]
Hi there,

I am still a bit confused as to what the issue is. Are you saying that react-scripts is continually writing to disk?

**Comment by peterennis** [comment]
Yes.

**Comment by liamdebeasi** [comment]
What OS are you testing this on?

The `Files successfully emitted, waiting for typecheck results...` message just means it is waiting for any type warnings. If nothing appears after then that means there were no type warnings.

**Comment by peterennis** [comment]
Windows 10.
I will try again and see if it does eventually complete.

**Comment by liamdebeasi** [comment]
Hi there,

I tried this again on Windows 10 and was still unable to reproduce the issue. Are you able to provide any additional steps to reproduce the issue?
