### ISSUE TITLE
feat: canLeave event for overlays

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#22297]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I want to add a CanLeave() Event on Overlays (mainly iOS card Style modal, but also for upcoming drawer) which should be somehow triggered while swiping. See attached Video of how native Web.de Mail-App handles this:

<img src="https://user-images.githubusercontent.com/20899975/95760383-40246500-0cab-11eb-9884-66d72f8e0861.gif" width="300">

If nothing was typed in, i can just swipe to close the modal. If i did, the swipe doesn't go to the end and shows a Action Sheet after i released.

**Describe Preferred Solution**

I think this should automatically work if a CanDismiss Callback is set to the Modal Element. This should be able to parse a boolean, or better a Promise<boolean> or even better both.

**Comment by BerkeAras** [comment]
@EinfachHans Good idea, but isn't it possible to something like that with ``ionModalWillDismiss``

**Comment by EinfachHans** [comment]
@BerkeAras it doesn't change the animation and i think i'm not able to "cancel" the dismissing here

**Comment by BerkeAras** [comment]
@EinfachHans event.preventDefault does not work?

**Comment by EinfachHans** [comment]
You don't have a event here and even if you have this won't be async and more a workaround then a solution @BerkeAras

**Comment by EinfachHans** [comment]
@liamdebeasi i can try my best for creating a PR if you give me a few hints:
- Should this automatically happen if a canDismiss is set?
- What's the preferred way to set this method for the modal? In the best case it needs to be handle from within the modal and outside where you created it.

**Comment by roman-rr** [comment]
@EinfachHans 
> You don't have a event here and even if you have this won't be async and more a workaround then a solution @BerkeAras 

Ok I see. Slower drag if dismiss not allowed. And `preventDismiss(true/false)`
Please make new feature request.

**Comment by liamdebeasi** [comment]
Merged https://github.com/ionic-team/ionic-framework/issues/22626 into this issue. I think this is an interesting feature and can see this being useful for modals in general, not just card-style modals.

**Comment by EinfachHans** [comment]
@liamdebeasi this PR is for normal Modals as well 😃

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24928, and a fix will be available in an upcoming release of Ionic Framework.
