### ISSUE TITLE
When you forward more than three pages in a row, and then fast click ion-back-button to return, the page will become blankbug: 

### ISSUE THREAD

**Issue by qq124719010** [ionic-team/ionic-framework#22293]
When you forward more than three pages in a row, and then quickly click **ion-back-button** to return, the page will become blank
 routerLink="/page2" -->  routerLink="/page3"   -->  routerLink="/page4" ，In page4, Fast click  **ion-back-button**  , then the page is blank

**Comment by qq124719010** [comment]
**fast click**，not quickly click

**Comment by BerkeAras** [comment]
I can not reproduce. Could you share a repository?
