### ISSUE TITLE
bug: Ion-input with [value] breaks Angular Validator.required

### ISSUE THREAD

**Issue by elinake** [ionic-team/ionic-framework#22314]
# Bug Report

**Ionic version:**

[x] **4.x**
[] **5.x**

**Current behavior:**

I need to use Angular DecimalPipe to round the number for presentation. That's why I need to get the value like this:
`[value]="parentGroup?.get(parameterName)?.value | number"`

But that breaks Angular's Validator.required. When I empty the field, validity stays the same as it was before emptying. If it had a valid value, it stays valid, if it had invalid value, it stays invalid. If I remove the decimal pipe, Validator.required still works incorrectly.

**Expected behavior:**

Getting input fields value from [value] must use Angular validators correctly.
Optionally, there should be some other way to use DecimalPipe with input, or some other way to round values for presentation.

**Related code:**
```
<ion-input
    type="number"
    formControlName="parameterName"
    [value]="form?.get(parameterName)?.value | number"
></ion-input>

this.form = this.formBuilder.group({
            parameterName: [parameterName, [Validators.required, Validators.min(min), Validators.max(max)]],
            })
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.15
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.802.2
   @angular-devkit/schematics    : 8.2.0
   @angular/cli                  : 8.2.0
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
