### ISSUE TITLE
My ion-cards on ios are flickering from rounded corners to square corners when I put them into ion-slides as the content of a ion-slide

### ISSUE THREAD

**Issue by TripTogs** [ionic-team/ionic-framework#22323]
My ion-cards on ios are flickering from rounded corners to square corners when I put them into ion-slides as the content of a ion-slide

_Originally posted by @michaelins in https://github.com/ionic-team/ionic-framework/issue_comments/518058032_

**Comment by liamdebeasi** [comment]
Hi there, please fill out the template completely and include a GitHub repo we can use to reproduce the issue. This helps us triage issues better. Thank you!
