### ISSUE TITLE
bug: Tabs navigation not pushed to navigation Stack

### ISSUE THREAD

**Issue by Flusinerd** [ionic-team/ionic-framework#22329]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When using tabs, and routing to another tab. The outlets ``stackEvents`` is not triggered, even if the url changes.

**Expected behavior:**
``stackEvents``should be triggered, when tabs change.

**Steps to reproduce:**
Build a simple application with two tabs. ``Tab1`` and ``Tab2``.   
Subscribe to ``IonRouterOutlet.stackEvents`` on the page containing the ``ion-tabs`` component and change from one tab to another via the tab buttons.

**Related code:**
-->

```

  constructor(
    private _outlet: IonRouterOutlet,
  ) { }

  ngOnInit() {
    this._outlet.stackEvents.subscribe((event) => console.log(event));
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.12 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.18.1 (/usr/local/bin/node)
   npm    : 6.14.7
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Hey there, can you please reproduce this in a tabs starter app and provide the link to the GitHub repo? This will help us triage the issue better.

**Comment by Flusinerd** [comment]
Sure, I'll do it tomorrow :)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
