### ISSUE TITLE
bug: Previous page is not drawn when navigating back in history

### ISSUE THREAD

**Issue by virusv** [ionic-team/ionic-framework#22324]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When you press the back button, the URL address changes, but the previous page is not displayed

**Expected behavior:**
Display the previous page

**Steps to reproduce:**
install ionic vue beta
`ionic start myApp blank --type vue --tag vue-beta`

**packages:**
```json
"@ionic/vue": "5.4.0-rc.3",
"@ionic/vue-router": "5.4.0-rc.3",
"core-js": "^3.6.5",
"vue": "^3.0.0-0",
"vue-router": "^4.0.0-beta.13"
```

Create 3 routes:
```js
const routes: Array<RouteRecordRaw> = [
    {
        path: '/',
        name: 'home',
        component: Home
    },
    {
        path: '/products/',
        name: 'products',
        component: Products
    },
    {
        path: '/products/:id/view',
        name: 'product',
        component: ProductSingle,
    }
];
```

Go from the first route to the second with query parameters:
```js
this.$router.push({
    name: 'products',
    query: {
        cat: 1,
        order: 'price',
    }
});
```

then go to 3rd page:
```js
this.$router.push({
    name: 'product',
    params: {
        id: 1,
    }
});
```

And try to go back:
`$router.back()` or using the `ion-back-button` component, the address bar changes, but the previous component is not rendered.

**Related code:**
https://github.com/virusv/bug-ionic-vue-backpage

**Other information:**
The bug exists in previous versions @ionic/vue && @ionic/vue-router (rc.1, rc.2 and -dev.*)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.8-testing.0 (C:\Users\Ivan Nalivayko\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.4.0-rc.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.8.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.7
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.5.0-dev.202010191854.1a2e532 @ionic/vue-router@5.5.0-dev.202010191854.1a2e532 --save-exact
```

**Comment by virusv** [comment]
> Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?
> 
> ```
> npm install @ionic/vue@5.5.0-dev.202010191854.1a2e532 @ionic/vue-router@5.5.0-dev.202010191854.1a2e532 --save-exact
> ```

Yes, this build solved the problem. Many thanks!

**Comment by liamdebeasi** [comment]
Thanks for checking! I am going to keep this issue open until https://github.com/ionic-team/ionic-framework/pull/22350 gets merged in.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22350, and a fix will be available in an upcoming release of Ionic Framework.
