### ISSUE TITLE
bug: Error starting a new React App with Blank Template

### ISSUE THREAD

**Issue by lanzoninicola** [ionic-team/ionic-framework#22326]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

During the installation I faced to this problem: 
npm ERR! Unexpected end of JSON input while parsing near '...:"4.4.4","aws-sdk":"^'.

I'm not able to start the application. 

**Expected behavior:**

Starting application

**Steps to reproduce:**

1- Open the terminal (I used VS Code terminal)
2- Moving to the folder you want to install application
3- Run the command "ionic start"
4- Select "React" framework
5- Select "blank" template
...and start

**Related code:**

```
insert short code snippets here
```

**Other information:**

_**Attachments:**_
- Terminal output during Ionic installation
[ionic_terminal_output.txt](https://github.com/ionic-team/ionic-framework/files/5385639/ionic_terminal_output.txt)

- NPM output
[ionic_react_app_setup_2020-10-15T14_15_22_961Z-debug.log](https://github.com/ionic-team/ionic-framework/files/5385642/ionic_react_app_setup_2020-10-15T14_15_22_961Z-debug.log)

**Extra Notes**

I think the problem is related to this:
3147 http fetch GET 304 https://registry.npmjs.org/@ionic%2fcore 109ms (from cache)
3148 silly fetchPackageMetaData error for @ionic/core@5.3.5 Unexpected end of JSON input while parsing near '...:"4.4.4","aws-sdk":"^'

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.12 (C:\Users\lanzo\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : not installed

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

Thanks for your attention

**Comment by liamdebeasi** [comment]
Can you update to the latest version of the Ionic CLI and try again?

```
npm install -g @ionic/cli@latest
```

**Comment by lanzoninicola** [comment]
Thanks @liamdebeasi for your feedback. 

I solved the issue by cleaning the cache of npm (`npm cache clear --force`).

You can close the issue.
