### ISSUE TITLE
bug: CSS Shadow Parts are not working on device

### ISSUE THREAD

**Issue by SlaySayto** [ionic-team/ionic-framework#22337]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.3**

**Current behavior:**

I have used some CSS styles to change the ion-select text with an icon, here is my code:
```css
.icon-english::part(text) {
  background-image : url("../../src/assets/icon/flag/usa.svg") !important;
  background-repeat : no-repeat !important;
  width: 2rem;
  height: 2rem;
}
``` 

```html
<ion-select [ngClass]=" {'icon-french': lang === 'fr', 'icon-english': lang === 'en'}"
                        [(ngModel)]="lang"
                        [cancelText]="'shared.button.annuler' | translate"
                        [selectedText]="' '"
                        (ionChange)="updateLang($event.detail.value)">
              <ion-select-option  class="en" value="en">{{"languages.english"| translate }}</ion-select-option>
              <ion-select-option  class="fr" value="fr">{{"languages.france"| translate }}</ion-select-option>
            </ion-select>
```

It works perfectly on the browser, but when I run it on the device, it's no longer working.  I've tried other styles like changing the color of the text inside the ion-select but it didn't work too. I supposed the CSS Shadow Parts is somehow ignored on the device.
My device has android 6
I did test the app on another phone which has android 9, It's working perfectly.
Another phone which has Android 8.1, not working

**Expected behavior:**

It should change the background image

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.8 (/home/sayto/.nvm/versions/node/v14.9.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 3.1.2, (and 26 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.1) : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/home/sayto/Android/Sdk/)
   NodeJS            : v14.9.0 (/home/sayto/.nvm/versions/node/v14.9.0/bin/node)
   npm               : 6.14.8
   OS                : Linux 5.4
```

**Comment by liamdebeasi** [comment]
Can you inspect your app on the affected devices and let me know what the result of `window.navigator.userAgent` in the developer tools console is? CSS Shadow Parts is relatively new in terms of browser support, so it could just be those devices have an outdated version of Chromium.

**Comment by SlaySayto** [comment]
Sorry for the delay in response, here is the output of the command: 
```
Mozilla/5.0 (Linux; Android 6.0; CAM-L21 Build/HUAWEICAM-L21; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36
```

**Comment by liamdebeasi** [comment]
Thanks for the follow up. CSS Shadow Parts was added in Chrome 73, and your webview is running Chrome 69 so it does not support them.

See https://developer.mozilla.org/en-US/docs/Web/CSS/::part for the complete browser support chart.

**Comment by niclaforge** [comment]
I can confirmed this is working with version 86 on Android:
`"Mozilla/5.0 (Linux; Android 9; SM-G955U Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 Mobile Safari/537.36"`

But it is not working for me on iOS, here's the output of `window.navigator.userAgent`
`"Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148" = $1`

Using the following css:
`ion-content::part(scroll) {}`

**Comment by niclaforge** [comment]
Ahh just noticed from your link.. supports starts on iOS 13.4. That makes is more complicate as we must support older and newer version. Thanks
