### ISSUE TITLE
bug: ion-range with bottom-drawer

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#22335]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
ion-range drag events disabled after present inside pane. 
**important note**: drag event's works well if pane presented immediately after DOM render

**Expected behavior:**
Drag events works for ion-range within Pane, even if Pane presented after some delay or with button. 

**Steps to reproduce:**
1. Open link https://output.jsbin.com/dojoxiz
2. Click to **Present Pane**
3. Try to drag range knobs
4. Open second example where pane presented immediately https://output.jsbin.com/dutuciv
5. Try to drag range knobs

**Related code:**

[Demo live](https://output.jsbin.com/dojoxiz)
[Demo immediately presented live](https://output.jsbin.com/dutuciv)

**Comment by roman-rr** [comment]
@liamdebeasi have you chance to look up ?

**Comment by liamdebeasi** [comment]
Are you able to reproduce this without the drawer component? If not, is it possible something in the drawer component gesture is interfering with the range gesture?

**Comment by roman-rr** [comment]
@liamdebeasi ok, I will check once again

**Comment by roman-rr** [comment]
@liamdebeasi 
Simple example without Drawer: https://output.jsbin.com/xufazic
Bug faces when appear element with ion-range inside to any other element with `.append()` method. 

```javascript
let rangeElement = document.querySelector('#range'); // Container with ion-range
let newContainer = document.querySelector('#new-container'); // New empty div container
newContainer.append(rangeElement); // We lose drag ability after append
```

**Comment by sohep** [comment]
Is there any solution yet ?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22407, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by roman-rr** [comment]
Big thanks for collaboration!
