### ISSUE TITLE
feat: Expand ion select and ion date time placeholder css props

### ISSUE THREAD

**Issue by bryce13950** [ionic-team/ionic-framework#22343]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

At the moment, there are quite a few more props that you can customize in relation to the ion-input such as placeholder font weight, placeholder font style, and placeholder opacity. At the moment these props are not available on the ion date time, and the ion select does not allow for the changing of the weight and style. It would be really great to have these editable directly through the css props as opposed to having to mess around with shadow Dom targeting. 

**Describe Preferred Solution**

The more robust placeholder styles to be propagated to more components.

**Describe Alternatives**

Targeting through shadow Dom, which is very hacky, and not very maintainable.

**Related Code**

```
ion-datetime,
ion-select,
ion-input {
  --placeholder-color: var(--ion-color-primary);
  --placeholder-font-weight: bold;
  --placeholder-opacity: 1;
```

At the moment the above code will only fully apply to the ion-input

**Additional Context**

I am more than willing to handle this if this sounds like something that could be merged in pretty quickly. I am in the middle of a project that could really use this as a feature, and said project will not be released for a couple months. In the meantime, I have the time to add this to the ionic project.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. We recently introduced CSS Shadow Parts on many of our components that allow you to further customize your app.

For example, in `ion-select` and `ion-datetime` you can customize the placeholder text:

```css
ion-select::part(placeholder),
ion-datetime::part(placeholder) {
  color: var(--ion-color-primary);
  font-weight: bold;
  opacity: 1;
}
```

Can you give this a try and let me know if it resolves your issue?

You can see all the shadow parts for `ion-select` and `ion-datetime` here:

Datetime: https://ionicframework.com/docs/api/datetime#css-shadow-parts
Select: https://ionicframework.com/docs/api/select#css-shadow-parts

**Comment by bryce13950** [comment]
Beautiful! I hadn't paid much attention to that section on the docs before. That seems to have covered my issue completely. Thanks a ton for the reply!
