### ISSUE TITLE
bug: ionic vue beforeEach redirect to tab hides tabs page

### ISSUE THREAD

**Issue by MarekGogol** [ionic-team/ionic-framework#22344]
**Ionic version:**
[ ] **4.x**
[x] **5.x**
"@ionic/vue": "5.4.0-rc.3",
"@ionic/vue-router": "5.4.0-rc.3",

**Current behavior:**
[bug # 1] - beforeEach in router/index.js triggers redirect from tab1 to tab3, but redirected route (tab3) wont be displayed.
[bug # 2] - ion-toggle infinity loop on ionChange event, if :checked property has been changed by ionChange method with 1 second timeout.
[bug # 3] in ionViewWillEnter and other router events vue instance is not represented in "this." (sorry, bug has been reported in #22338  )

**Expected behavior:**
[bug # 1] tab3 should be visible, but it is not.
[bug # 2] ionChange event in ion-toggle element should be fired only when toggle is actually pressed by user, not when :checked property is changed programmatically without user interaction.
[bug # 3] "this." should be binded as vue instance of given component. In 

**Steps to reproduce:**
[bug # 1] clone given repo. checkout branch "bug-1". Open localhost, and bug will be already visible. Then you can check router/index.ts for more info.
[bug # 2] clone given repo. checkout branch "bug-2". Press ion-toggle, and infinity loop will be already present after one toggle click. You can compare same behaviour with native checkbox.
[bug # 3] clone, checkout bug-3. See alert. Variable in alert is undefined.

A sample application via GitHub. All bugs are found in this repo, in separate branches. This is ifresh nstallation of vuejs tabs example, + demonstrated bugs in each branch.
https://github.com/MarekGogol/ionic-vue-bugs

Thank you very much. Sorry If something mentioned here is not bug.

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.11.8-testing.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.0-rc.3

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.2.2) : 0.3.0

System:

   NodeJS : v12.18.4 (/usr/local/bin/node)
   npm    : 6.14.6
   OS     : macOS Catalina
```

**Comment by isfk** [comment]
I find this bug too.

**Comment by liamdebeasi** [comment]
Thanks for the easy to reproduce test cases! A few notes on the issues you reported:

1. I will work on a fix for this bug.
2. This is how `ionChange` is designed, though I can see why it may be considered undesirable behavior. I have run into this infinite loop scenario in my own applications. `ionChange` is fired whenever the value of the toggle is changed, so when you set the value of the toggle in `onChangeBuggy` it will fire `ionChange` again. This appears to impact other components that use `ionChange`. I will open a separate issue for this.
3. As noted, this is already reported in https://github.com/ionic-team/ionic-framework/issues/22338. There is dev build in https://github.com/ionic-team/ionic-framework/issues/22338#issuecomment-712260216 if you would like to give it a try and see if it resolves the issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.5.0-dev.202010211624.cf85942 @ionic/vue-router@5.5.0-dev.202010211624.cf85942 --save-exact
```

**Comment by MarekGogol** [comment]
@liamdebeasi Fixed, thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22371, and a fix will be available in an upcoming release of Ionic Framework.
