### ISSUE TITLE
Does ionic support java version greater than '1.8'?

### ISSUE THREAD

**Issue by UltraBurstXD** [ionic-team/ionic-framework#22349]
I'm kinda new here and I've taken interest upon this marvellous framework, but I don't want use Java 8 for many reasons. Firstly it's EOL both in Community and Oracle distributions. Second, it lacks newer cool or updated APIs. So what I want to know is: Can I run it on Java 14?

**Comment by liamdebeasi** [comment]
Hey there,

Ionic Framework is a web-based UI Framework and does not manage your Java dependencies. It is possible that you are using something like Cordova to deploy your app which may use Java 8. This is more of a support question, so I recommend asking your question on our forums: http://forum.ionicframework.com/

Thanks!
