### ISSUE TITLE
Impossible to pick an "Hour" in <ion-datetime>

### ISSUE THREAD

**Issue by s3ppo** [ionic-team/ionic-framework#22346]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Impossible to pick "Hour" in Timepicker. It automatical scrolls up or down or do something other crazy things.
Other scrollables within the timerpicker work fine. 

**Expected behavior:**
that it dont scrolls up or down or whatever

**Steps to reproduce:**
```<ion-datetime required displayFormat="MMM DD, YYYY HH:mm"></ion-datetime>```

**Related code:**
```<ion-datetime required displayFormat="MMM DD, YYYY HH:mm"></ion-datetime>```

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What version of Ionic Framework are you testing this on? I am testing on v5.4.0 and cannot reproduce this issue.

**Comment by s3ppo** [comment]
hi and thanks for your answer :) 

this is my ionic info.. sorry i forgot to update the thread when i was on my macbook:
Ionic:

   Ionic CLI                     : 6.12.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.0
   @angular-devkit/build-angular : 0.1001.7
   @angular-devkit/schematics    : 10.1.7
   @angular/cli                  : 10.1.7
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 10 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.2.2

System:

   ios-sim : 8.0.2
   NodeJS  : v14.14.0 (/usr/local/bin/node)
   npm     : 6.14.8
   OS      : macOS Catalina
   Xcode   : Xcode 12.0.1 Build version 12A7300

**Comment by s3ppo** [comment]
it seems this happens only on platforms: android and browser
ios seems to work fine

**Comment by liamdebeasi** [comment]
Thanks! Can you provide some steps to reproduce the issue?

**Comment by s3ppo** [comment]
i think there are no specials on this...
i just used the <ion-datetime required displayFormat="MMM DD, YYYY HH:mm"></ion-datetime> in my html template file

it looks like this...
![Screen_Recording_20201019-164654_Hawara](https://user-images.githubusercontent.com/17125438/96467871-b258f480-122b-11eb-9a4f-9ee6b99dd5c0.gif)

**Comment by s3ppo** [comment]
here is a full example.. the others (month, day, year and minutes are working fine)
![Screen_Recording_20201019-165816_Hawara](https://user-images.githubusercontent.com/17125438/96468687-aa4d8480-122c-11eb-80ff-fc01d934057e.gif)

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Any chance you could reproduce this in a blank Ionic starter app and send me the GitHub link? I cannot seem to reproduce this behavior on my end.

**Comment by s3ppo** [comment]
hmm thats strange.. i created a new stackblitz and it also does not happen.. sorry for that i will try find out wheres the difference to the empty starter template :(
