### ISSUE TITLE
bug: ionic vue cannot route to shared url with param

### ISSUE THREAD

**Issue by milleniumfrog** [ionic-team/ionic-framework#22359]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Ion Router Outlet does not display shared urls, if they contain params.
If the shared urls do not contain params it works as expected.

**Expected behavior:**

Shared urls should always work, even when route params are used

**Steps to reproduce:**

### Reproduce Error
- create  shared urls with a param
e.g. /a/:message and /app/:message/test
- navigate to /app/:message/test without reloading the page

### Sample Application
- Clone this repository: https://github.com/milleniumfrog/ionic_router_bug
- yarn install
- yarn run serve
- visit localhost:8080
Then use the buttons to navigate to PageA (Page with route params) -> PageA1. (Should fail)
```
**Related code:**

<!-- If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:
https://github.com/milleniumfrog/ionic_router_bug

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.5.0-dev.202010201728.85ba838 @ionic/vue-router@5.5.0-dev.202010201728.85ba838 --save-exact
```

**Comment by milleniumfrog** [comment]
The dev package solves the issue 👍 .

**Comment by milleniumfrog** [comment]
I found a new related bug.

When using route parameters the routing only works the first time. If the same route is used with an other parameter routing stops working for this route

![Screen Recording 2020-10-21 at 12 05 23-Apple Devices 4K (HEVC 8-bit)](https://user-images.githubusercontent.com/25634732/96707172-d0dbfe80-1397-11eb-8634-810574ebe243.gif).

I updated the ionic bug sample app https://github.com/milleniumfrog/ionic_router_bug

**Comment by liamdebeasi** [comment]
@milleniumfrog Did you push your changes? I only see the package.json change.

**Comment by milleniumfrog** [comment]
@liamdebeasi yes i forgot to push the changes. I updated it now.

**Comment by liamdebeasi** [comment]
Thanks! Can you try this dev build? It should fix the issue:

```
npm install @ionic/vue@5.5.0-dev.202010212159.85ba838 @ionic/vue-router@5.5.0-dev.202010212159.85ba838 --save-exact
```

**Comment by milleniumfrog** [comment]
The update fixed the problems 👍.

**Comment by liamdebeasi** [comment]
Thanks for checking! I am going to keep this issue open until https://github.com/ionic-team/ionic-framework/pull/22360 gets merged in.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22360, and a fix will be available in an upcoming release of Ionic Framework.
