### ISSUE TITLE
bug: Wrong animation when swiping just a little bit for 'Swipe down to dismiss modal' and 'Swipe to go back'

### ISSUE THREAD

**Issue by AndrewBargan** [ionic-team/ionic-framework#22357]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
For "swipe right to go back" animation: when "Community Interaction" page swiped right just a bit and released weird animation happens
For "swipe down to dismiss modal" animation: when title of "Filter Sessions" modal swiped down just a bit a released weird animation happens

**Expected behavior:**
For "swipe right to go back" animation: when page released it should go back to its initial position
For "swipe down to dismiss modal" animation: when title of a modal released it should go back to its initial position

**Steps to reproduce:**
To reproduce use Ionic Angular 5.x Conference App

![ezgif-7-7b37db5dd757](https://user-images.githubusercontent.com/33483711/96578692-497e8480-12de-11eb-862e-0addaa47a518.gif)
-
![ezgif-7-15965c8d811d](https://user-images.githubusercontent.com/33483711/96578708-4e433880-12de-11eb-83db-4646bfac68c8.gif)

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21978#issuecomment-693420179.
