### ISSUE TITLE
bug: Ionic framework website doesn't replace old invalid e-mail from GitHub with newer

### ISSUE THREAD

**Issue by UltraBurstXD** [ionic-team/ionic-framework#22356]
Hi,
I'm trying to create account on official ionic framework website through GitHub credentials since yesterday. But for some reason the old primary e-mail account found on GitHub was invalid, and I wasn't receiving activation link so I decided to check my email settings and discovered it was invalid. After I changed it, I revoked ionic access from GitHub and cleared my browser history, but still SSO isn't recognizing the new primary e-mail... 
Pls, help!

**Comment by liamdebeasi** [comment]
Hey there,

This repo is for bugs in the Ionic Framework codebase only. Please email support [at] ionic.io and they will be able to help.

Thanks!
