### ISSUE TITLE
feat(keyboard): smooth keyboard input transitions

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#22368]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

One of the things that always made me jealous about frameworks like react native (or other frameworks which provide native UI) is the smooth native input transition.
I'm using ionic since release of ionic 2 and haven't been able to reach that point where you can't tell the difference between ionic and native UI input.

Things that bother me are for example:
- switching from one input to another is still a bit "laggy". You can feel some debounce.
- switching between input where autocomplete is on to an input where is not, results in black flicker effect.
  - just create two inputs: one type text and one type email and switch between them
- when you have a textarea inside ion-footer toolbar and focus, then the toolbar appears delayed above the keyboard. Also the toolbar styles break on focus but returns to normal on blur. Also there is a different behavior if you write something.
  - there was a [blog](https://ionicframework.com/blog/keyboard-improvements-for-ionic-apps/) post about keyboard improvements. But i was not able to reproduce this behavior.
  - i've added the keyboard listener and set the height as in the code example in this blog
  - i've tried different resize modes using capacitor (native, ionic, default, none). 
  - heres a [repo](https://github.com/DwieDima/ionic-keyboard-blog-repro) where i tried to copy the app provided in blog.
- on input focus, content should be pushed above keyboard (used different resize modes without success).

black flicker on input change   |  delayed buggy toolbar (from repo above)
:-------------------------:|:-------------------------:

<img width="300" alt="black_flicker" src="https://user-images.githubusercontent.com/26873275/96713341-bb1f0700-13a0-11eb-9c34-05699cc0e962.gif">  |  <img width="300" alt="buggy_toolbar" src="https://user-images.githubusercontent.com/26873275/96716067-d1c75d00-13a4-11eb-9a92-7378c5f10524.gif">

**Describe Preferred Solution**

![keyboard-attach](https://user-images.githubusercontent.com/26873275/96715772-5ebde680-13a4-11eb-88fd-57c85eacf82f.gif)

Gif above shows the work of @liamdebeasi from the blog post.
- It would be great if this behavior is given by default without having to animate the toolbar yourself. Maybe the same approach could be used like for ion-refresher, where compiled on ios native animations are used instead.
- push content animation when keyboard is present.
- When changing inputs it should run smoothly (no black flicker).

**Describe Alternatives**

These problems (footer toolbar, input change) have been recurring since ionic 2 and have been discussed frequently.
I love ionic, but these are characteristics that show to the enduser that it is not a native application.
In the long run unfortunately i have to switch to alternatives like react native or flutter, because these animations are a gamebreaker for me.

**Related Code**

Repo of second screen (laggy toolbar above keyboard):
https://github.com/DwieDima/ionic-keyboard-blog-repro

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is an area where web-based applications still struggle a bit. I will do my best to address all of your points.

> switching from one input to another is still a bit "laggy". You can feel some debounce.

This is a limitation with web view resizing. When using Capacitor/Cordova, opening the keyboard will typically resize the webview. In that case, the scroll assist needs to wait for the keyboard to open and the webview to resize before it has enough scrolling real estate. This results in the slight delay you are noticing. Some inputs higher up on the screen may have less of a delay because of their smaller scrolling requirement. The solution here is to disable webview resizing, but there is an issue with scroll assist not adding padding properly in those cases https://github.com/ionic-team/ionic-framework/issues/18532.

> switching between input where autocomplete is on to an input where is not, results in black flicker effect.

This is due to the webview resizing, not something Ionic Framework is doing. Disabling webview resizing should resolve this issue.

> when you have a textarea inside ion-footer toolbar and focus, then the toolbar appears delayed above the keyboard. Also the toolbar styles break on focus but returns to normal on blur. Also there is a different behavior if you write something.

This is also due to the webview resizing. It would be better to listen for keyboard events and translate the toolbar yourself using a CSS Transition. One thing to note is it is impossible to have the animation be perfectly in sync with the native keyboard transition, though you can usually get pretty close with the right easing curve/duration.

> on input focus, content should be pushed above keyboard (used different resize modes without success).

Can you clarify what you mean by this? The scroll assist should scroll content into view.

**Comment by DwieDima** [comment]
Thank you @liamdebeasi for quick response!

> Can you clarify what you mean by this? The scroll assist should scroll content into view.

Sorry for misunderstanding. I'm not talking about scroll assist.
I want to achieve the exact same behavior as you did for the ionic blog post (3rd gif).
If you focus the input inside ion-footer also the chat bubbles get pushed on top ob the toolbar.
In my example (2nd gif) my keyboard + toolbar overlap the chat bubbles. They should be above toolbar, like in your example.

Maybe you could share the code of this app, so others can see how you did the toolbar styling / disabling webview resizing / translate the toolbar transition 

> This is a limitation with web view resizing

That is a real pity that it is due to ios. Minding, this problem has been around for years.
Is there no possibility to use native inputs?

By the way:
NativeScript announced ionic support (also NSString), so maybe this could be a solution in future.
https://nativescript.org/ionic/

**Comment by liamdebeasi** [comment]
> Sorry for misunderstanding. I'm not talking about scroll assist.
I want to achieve the exact same behavior as you did for the ionic blog post (3rd gif).
If you focus the input inside ion-footer also the chat bubbles get pushed on top of the keyboards toolbar.
In my example (2nd gif) my keyboard + toolbar overlap the chat bubbles. They should be above toolbar, like in your example.

Thanks for clarifying. Unfortunately there is no performant way to do this in a "one size fits all" kind of manner. I think it would be better if developers had the information on how to implement this in their own app. As I mentioned before, there is no way to communicate between the web layer and the native layer to get the keyboard and the toolbar to sync up perfectly. Even if we did communicate between the layers, there would be the overhead of going between the two layers and the animation would still be out of sync as a result.

Sadly I cannot seem to find the code for that demo, though I think it warrants a blog post or some documentation that goes more in depth on how to do these kinds of things. Would something like that help?

**Comment by DwieDima** [comment]
> Sadly I cannot seem to find the code for that demo, though I think it warrants a blog post or some documentation that goes more in depth on how to do these kinds of things. Would something like that help?

yes that would help a lot.
Especialy how to solve 
- black flicker on input change
- the delay when footer gets on top of keyboard on focus
- push content smooth on top of keyboard (like chat bubbles)
- maybe how to jump to next input using steps arrow on keyboard

thank you 😊

**Comment by liamdebeasi** [comment]
Thanks! I will make a note of all of these. 

I am going to close this issue since this work will go into a blog not the framework code base. Keep an eye out for a keyboard-related blog soon.
