### ISSUE TITLE
bug: ios scrollbar appears in middle of the screen when using ion-menu

### ISSUE THREAD

**Issue by askilondz** [ionic-team/ionic-framework#22379]
# Bug Report

**Ionic version:**

[x] **4.x**
[x] **5.x**

**Capacitor**
[x] **2.4.x**

**Angular**
**9.1.x**

**Current behavior:**
This is a very specific use case. On iOS devices...if the ion-menu type is `push` and if a page has an `ion-content` but no `ion-header` and you navigate away from it and then back to it...the vertical scrollbar displays in the middle of the page. I've noticed this only on iOS across many iOS devices and different apps I've built where a page doesn't have an ion-header/ion-toolbar. If I change the side menu type to `reveal` or `overlay` then the issue is resolved. Something about the `push` effect causes the scrollbar to persist in the middle of the screen when coming to the page after the side menu has been opened. Strangely...if I include an ion-header/toolbar then this scrollbar issue goes away.

![kgl797to2oiu3puyl-80sljee44](https://user-images.githubusercontent.com/3945147/96919551-8b8bff80-1471-11eb-8d23-ee32f44ff007.jpg)

**Steps To Reproduce**
With `<ion-menu type="push">`, create a page that has no `ion-header` and has content to scroll...then go to another page from the menu then go back to the original page. The push effect of the menu sets the scroll bar in the middle of the screen on iOS.

**Comment by liamdebeasi** [comment]
Hey there,

Can you please reproduce this in an Ionic starter app? Code snippets are not typically enough for us to reproduce the issue.

**Comment by askilondz** [comment]
Here is app project that reproduces the bug:
https://github.com/ClearDesignGroup/IOS-Scrollbar-Bug

**Comment by liamdebeasi** [comment]
Thanks! This appears to be a WebKit bug. I have filed an issue here: https://bugs.webkit.org/show_bug.cgi?id=218124.

A temporary workaround for now is to set `transform: translate(0, 0)` on `ion-router-outlet` (or whatever your main content is going to be). This does not completely fix the issue, but it at least forces the scrollbar to snap back into place when the animation is done.

**Comment by sachi097** [comment]
I am facing same problem but scrollbar doesn't appear in middle of the screen instead appears at its position.
Since I can't upload an image of it, please find the exact same issue here : https://forum.ionicframework.com/t/scrollbar-appearing-on-menu-toggle/129729

How do I hide scrollbar when ion-menu is opened?
![issue](https://user-images.githubusercontent.com/36642643/105633469-c6417180-5e7e-11eb-8b6f-04c7d0d55278.png)
