### ISSUE TITLE
bug: debounce on <ion-textarea> also affects connected ngModel

### ISSUE THREAD

**Issue by frasen** [ionic-team/ionic-framework#22408]
# Bug Report

**Ionic version:**

[x] **4.8.1** (Stackblitz)
[x] **5.3.3** (My current environment)

**Current behavior:**
Adding a value to debounce affects ngModel

**Expected behavior:**
I expect the ngModel binding to not be affected by debounce

**Steps to reproduce:**
See stackblitz. Enter a value in the ion-textarea and the variable is updated 1500 ms later.

**Related code:**
https://stackblitz.com/edit/ionic-v4-angular-tabs-wj9v5r?file=src%2Fapp%2Ftab1%2Ftab1.page.html

**Other information:**
If you consider this to be expected behaviour I think this should be explicitly stated in the documentation for debounce.

**Ionic info:**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Yes, this is the intended behavior. Updating `ngModel` relies on the `ionChange` event, which will be throttled when `debounce` is a positive number. I am updating the docs here: https://github.com/ionic-team/ionic-framework/pull/22409.
