### ISSUE TITLE
bug: multi-step back navigation broken in IonReactRouter (regression)

### ISSUE THREAD

**Issue by larsblumberg** [ionic-team/ionic-framework#22400]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When doing 2 history steps back at once via `history.go(-2)` then `<IonReactRouter>` renders the wrong route.

**Expected behavior:**
`<IonReactRouter>` renders the correct route -- the route that is 2 steps back in history.

**Steps to reproduce:**

1. Start with one page and push 2 `IonPage`s to navigation stack via `navigation.push()`
2. Let the 3rd page navigate back ("history stack pop") to the first page via `navigation.go(-2)`
3. Observe that react's router does produce the proper URL (path) of the first page. But also observe that the the previous route (page) in the history stack is rendered, not the very first page which belongs to that path.

**Related code:**

https://github.com/larsblumberg/ionic-back-navigation-broken

**Other information:**

The bug doesn't manifest in `@ionic/react[-router]: 5.2.3` and has been introduced in `5.3.0`. All versions since `5.3.0` up to current version `5.4.1` show this bug.

**Ionic info:**

```
Ionic:
   Ionic CLI       : 6.11.1 (/Users/lars/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.4.1

Capacitor:
   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v14.4.0 (/usr/local/Cellar/node/14.4.0/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I can reproduce this behavior. I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/22563.

**Comment by larsblumberg** [comment]
You’re doing great work @liamdebeasi . Thanks!
