### ISSUE TITLE
bug: macOS Safari crushes on ion-toggle switch action

### ISSUE THREAD

**Issue by playerx** [ionic-team/ionic-framework#22415]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Web page crushes when try to switch ion-toggle in MacOS Safari. and need to refresh the page

**Expected behavior:**

ion-toggle should work normally without page crush

**Steps to reproduce:**

1. Visit: https://ionicframework.com/docs/api/toggle
2. Tap on any ion-toggle in the preview

**Other information:**

macOS - Cataline Version 10.15.7
Safari - Version 14.0 (15610.1.28.1.9, 15610)

<img width="1440" alt="Screen Shot 2020-11-01 at 3 18 24 PM" src="https://user-images.githubusercontent.com/1698274/97801338-7d9a6380-1c55-11eb-97a7-b27f7b958ada.png">

**Comment by liamdebeasi** [comment]
Please see https://github.com/ionic-team/ionic-framework/issues/21939#issuecomment-694259307.
