### ISSUE TITLE
bug: Router Push not changing the page(Non-Typescript)

### ISSUE THREAD

**Issue by HakobiDev** [ionic-team/ionic-framework#22420]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Changing routes not changing page using router.push("/login"); *not working
Changing using tabs href="/path" *working

**Expected behavior:**
SPA like behavior

**Steps to reproduce:**
1. ionic start myApp tabs --type vue

2 .Change all .ts files to .js. In a blank Ionic Vue app, this should only be router/index.ts and main.ts.

3. Remove @vue/typescript/recommended and @typescript-eslint/no-explicit-any: ‘off’, from .eslintrc.js.

5. Remove Array<RouteRecordRaw> from router/index.js.

6. Delete the shims-vue.d.ts file.

7. Remove lang="ts" from the script tags in any of your Vue components that have them. In a blank Ionic Vue app, this should only be App.vue and views/Home.vue.

8. npm uninstall --save typescript @types/jest @typescript-eslint/eslint-plugin @typescript-eslint/parser @vue/cli-plugin-typescript @vue/eslint-config-typescript

**Related code:**
Welcome.vue
` <ion-slide>
            <img src="../assets/obt/bueno.svg" />
            <h2>Ready to Explore?</h2>
            <ion-button fill="primary" @click="nextPage()">Get it on!</ion-button>
        </ion-slide>`

`    setup() {
        const router = useRouter();
        const nextPage = () => {
            router.push("/login");
        };
        const slideOpts = {
            initialSlide: 0,
            speed: 400
        };
        return {
            router,
            nextPage,
            slideOpts
        }
    }`

**Other information:**
Non-Typescript mode removing typescript same as the docs instruction

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide the contents of your `router/index.js` file?

**Comment by HakobiDev** [comment]
@liamdebeasi  thanks
here is my index.js

`
import { createRouter, createWebHistory } from '@ionic/vue-router';
import Login from '../views/Login.vue'
import Obt from '../views/Welcome.vue'
import Tabs from '../components/Tabs.vue'

const routes = [
  {
    path: '/',
    name: 'Welcome',
    component: Obt
  },
  {
    path: '/login',
    name: 'Login',
    component: Login
  },
  {
    // Test TODO: AUTH
    path: '/auth/',
    component: Tabs,
    children: [
      {
        path: '',
        redirect: '/auth/star'
      },
      {
        path: 'star',
        component: () => import('@/pages/Star.vue')
      },
      {
        path: 'add',
        component: () => import('@/pages/Add.vue')
      },
      {
        path: 'public',
        component: () => import('@/pages/Public.vue')
      },
      {
        path: 'wallet',
        component: () => import('@/pages/Wallet.vue')
      },
      {
        path: 'profile',
        component: () => import('@/pages/Profile.vue')
      }
    ]
  }
]

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes
})

export default router

`

Sample behavior video : https://streamable.com/bgucq0

**Comment by liamdebeasi** [comment]
Thanks. Can you please provide a reproduction of the issue in a GitHub repo? It's hard to tell what the issue is without being able to reproduce it myself.

**Comment by HakobiDev** [comment]
I created a small reproduction regarding to issue : [https://drive.google.com/file/d/1_SYTg0offl_HR8P1G7jX2QL4QAQcCNY9/view?usp=sharing](url)

Thanks in advance

**Comment by liamdebeasi** [comment]
You are not using `ion-page` in your page components, which is required for navigation transitions to work. Try wrapping your pages in `ion-page`:

```html
<template>
  <ion-page>
    <ion-content :fullscreen="true" class="ion-padding" scroll-y="false">
      ...
    </ion-content>
  </ion-page>
</template>

<script>
import {
  IonPage,
  IonContent
} from '@ionic/vue';

export default ({
  components: {
    IonPage,
    IonContent,
  }
});
</script>

**Comment by HakobiDev** [comment]
Thank you so much! Big help for us for that docs will be updated..
