### ISSUE TITLE
bug: Custom long press gesture doesn't work with ion-refresher

### ISSUE THREAD

**Issue by crees1** [ionic-team/ionic-framework#22439]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When using a custom long press directive (because Ionic decided to remove this feature) on an item in a list with an ion-refresher, the ion-refresher does not work because the gesture is taking over.

**Expected behavior:**
Long press and pull to refresh should work together as they used to do in Ionic 3.

**Steps to reproduce:**
Create a long press directive and attach it to a list of items in an ion-list with an ion-refresher. Notice the ion-refresher is not working when pulling to refresh in the list.

**Related code:**
`import {
    Directive,
    ElementRef,
    Input,
    AfterViewInit,
    NgZone,
    EventEmitter,
    Output
} from "@angular/core";
import { GestureController, GestureDetail, Gesture } from "@ionic/angular";

@Directive({
    selector: "[long-press]"
})
export class LongPressDirective implements AfterViewInit {

    @Output() press = new EventEmitter();
    @Input("delay") delay =  1000;
    action: any; //not stacking actions
    gesture: Gesture;

    private longPressActive = false;

    constructor(
                    private el: ElementRef, 
                    private gestureCtrl: GestureController, 
                    private zone: NgZone
                ) {}
    
    ngAfterViewInit() {
        this.loadLongPressOnElement();
    }    

    ngOnDestroy(){
        this.gesture.destroy();
    
    }

    loadLongPressOnElement() {
        this.gesture = this.gestureCtrl.create({
            el: this.el.nativeElement,
            threshold: 0,
            gestureName: 'long-press',          
            onStart: ev => {                                      
                this.longPressActive = true;
                this.longPressAction(ev);
            },
            onEnd: ev => {                
                this.longPressActive = false;
            }
        });
        this.gesture.enable(true);
    }
    
    private longPressAction(ev:GestureDetail) {
        if (this.action) {
            clearInterval(this.action);
        }
        this.action = setTimeout(() => {
            this.zone.run(() => {
                if (this.longPressActive === true) {
                    this.longPressActive = false;
                    this.press.emit(ev.event);
                }
            });
        }, this.delay);
    }
}`

`<ion-list class="ion-text-wrap">
      <ion-item button long-press *ngFor="let item of items" (click)="itemTapped($event, item, null)"  (press)="itemPressed($event, item)">
        ...
      </ion-item>
</ion-list>`

**Ionic info:**
```
   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.901.5
   @angular-devkit/schematics    : 9.1.5
   @angular/cli                  : 9.1.5
   @ionic/angular-toolkit        : 2.2.0
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
