### ISSUE TITLE
bug: angular proxies refactored on build

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#22441]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When creating a new Branch from master (for a PR) and without changing anything, running `npm run build`, there are a few changes made to `proxies.ts` and `proxies-list.txt` in **angular/src/directives**.

**Changes:**
`proxies.ts` gets refactored with another intend:
<img src="https://user-images.githubusercontent.com/20899975/98341052-8d77c600-200e-11eb-95d1-d4a129f67e15.png" width="800">

`proxies-list.txt`:
<img width="1005" alt="Bildschirmfoto 2020-11-06 um 09 01 55" src="https://user-images.githubusercontent.com/20899975/98341197-c7e16300-200e-11eb-9062-af2ad4e51363.png">

**Expected behavior:**

I don't want to commit these changes in a PR, that's why i'm currently have to check all PR changes related changes in these files manually (for example if a new Prop is added to a Component)

**Steps to reproduce:**

Like i said, it happens for me without any changes, just new branch from master and build. I'm unsure, but i don't think it is related to any changes on my side, because this behavior is kinda new and i did not change anything 🤔

**Comment by liamdebeasi** [comment]
The `proxies-list.txt` change is fine. We updated to Stencil 2 internally, so most of these changes you are seeing were intentionally done to accommodate that. For the `proxies.ts` file, I would recommend syncing your branch with `master` again.

**Comment by EinfachHans** [comment]
In my project i have added `https://github.com/ionic-team/ionic-framework.git` as Upstream remote. Before creating i do a git fetch and then create my pr-branch from your master directly. So i think it must be sync? Also the change in `proxies-list.txt` - shouldn't that be on master already from your own release builds?

**Comment by liamdebeasi** [comment]
It is: https://github.com/ionic-team/ionic-framework/blob/master/angular/src/directives/proxies-list.txt#L2. It sounds like something is out of sync with our `master` branch - not sure what it might be though.

**Comment by EinfachHans** [comment]
Yeah there it is: `import type * as d from './proxies';`, right?

But after a build it becomes to `import * as d from './proxies';` in my fork 🤔

**Comment by liamdebeasi** [comment]
I would try a fresh `npm install` and `npm run build` of `angular` and `core`.
