### ISSUE TITLE
feat: ionic vue lifecycle hook functions

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/ionic-framework#22440]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
i want to use lifecycle "ionViewWillEnter" width vue3 composition api in setup function, but there is no method, 

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

```
<script lang="ts">
import Goods from '@/api/goods';
import {useRouter, useRoute} from "vue-router";
// import {getInstance} from "@/utils/getInstance";
import {effect, reactive} from '@vue/reactivity'
import {defineComponent, onMounted, ref, watch} from "vue";
import {
  IonPage,
  IonList,
  IonItem,
  IonLabel,
  IonAvatar,
} from '@ionic/vue';

export default defineComponent({
  name: "GoodsList",
  components: {
    IonPage,
    IonList,
    IonItem,
    IonAvatar,
    IonLabel,
  },
  methods: {
    // only use like this
    ionViewWillEnter() {
      console.log('Home page will enter');
    }
  },
  setup() {
      onMounted(() => {
      })
      // i hope to use on here, eg:
     ionViewWillEnter(() => {})
  }
})
</script>
```
**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks! We already have a PR that does something similar, just need to merge it.

**Comment by liamdebeasi** [comment]
Thanks for the issue. We recently merged in a PR that will add better Composition API lifecycle hooks that should fit your use case: https://github.com/ionic-team/ionic-framework/pull/22241.

We will update the docs when this feature ships with examples of how to use it.
