### ISSUE TITLE
feature request: back-button outside of ion-nav

### ISSUE THREAD

**Issue by brendensoares** [ionic-team/ionic-framework#22454]
# Feature Request

**Ionic version:**
**5.x**

**Describe the Feature Request**
I want to use `ion-nav` with a common header bar (with back button and title).

I have a nearly working solution, but `ion-back-button` only works as a descendant of an `ion-nav`. It seems it was designed for each pushed nav item to have its own header and back button. This is not ideal because the transition animation is not fluid during the nav push, it increases code duplication by having headers in each nav item, and it makes it difficult to have a common/shared UI. 

**Describe Preferred Solution**
Don't require `ion-back-button` to be within an `ion-nav`. Perhaps add an optional property to target a specific `ion-nav`.

**Describe Alternatives**
The only other option right now is to duplicate the header in each nav item.

**Related Code**
https://github.com/ionic-team/ionic-framework/blob/753fd2f910e718438e3ac918e2f129501d8e9791/core/src/components/back-button/back-button.tsx

**Additional Context**
A side note, the docs for `ion-nav` and the related components seems lacking and possibly out of date.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify the problem you are trying to solve? `ion-back-button` is really only intended to be used with page transitions (I.e page routing or usage in `ion-nav`).
