### ISSUE TITLE
bug: I Followed Exactly what is written in Docs about Vue and Ionic But along the way I got this error and It can be a Bug about the Camera Plugin

### ISSUE THREAD

**Issue by BroJenuel** [ionic-team/ionic-framework#22455]
# Bug Report

## **Ionic version:**
6.12.1
![image](https://user-images.githubusercontent.com/31676163/98467848-989b4380-2212-11eb-942e-525370b5aafe.png)
"dependencies": {
    "@capacitor/core": "2.4.2",
    "@ionic/pwa-elements": "^3.0.1",
    "@ionic/vue": "^5.4.0",
    "@ionic/vue-router": "^5.4.0",
    "core-js": "^3.6.5",
    "vue": "^3.0.0-0",
    "vue-router": "^4.0.0-0"
  },
  "devDependencies": {
    "@capacitor/cli": "2.4.2",
    "@types/jest": "^24.0.19",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-e2e-cypress": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0-0",
    "@vue/eslint-config-typescript": "^5.0.2",
    "@vue/test-utils": "^2.0.0-0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "typescript": "~3.9.3",
    "vue-jest": "^5.0.0-0"
  },

## **Current behavior:**

There is an error when the function takePhoto from Camera plugin is triggered

## **Expected behavior:**

A model should show up showing the view of the camera being taken.

## **Steps to reproduce:**

I followed the tutorial and did exactly what was written in the ionic docs in here: https://ionicframework.com/docs/vue/your-first-app

## **Errors I GOT**
![image](https://user-images.githubusercontent.com/31676163/98468073-c765e980-2213-11eb-98b1-2a272b93044f.png)
![image](https://user-images.githubusercontent.com/31676163/98468065-c03edb80-2213-11eb-95f0-26668d5c759d.png)

**Comment by AlwaysLoveme** [comment]
you must follow this step:
![image](https://user-images.githubusercontent.com/29945352/98524430-2c701c80-22b2-11eb-9df2-b6b7dda5c82c.png)
