### ISSUE TITLE
bug: Ionic Angular - custom delegate not configurable for the modalOptions 

### ISSUE THREAD

**Issue by falconeta** [ionic-team/ionic-framework#22453]
**Ionic version:**
[] **4.x**
[x] **5.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
If i pass a custom delegate, the "create" function applies the default delegate

**Expected behavior:**
the ability to override the default framework delegate.

**Steps to reproduce:**

1. creates a new modal with the following options:
```
      component: page,
      componentProps: data,
      delegate: this.myDelegateService.create(this.componentFactoryResolver, this.injector)
```

2. the modal will be created with the default delegate. 

**Related code:**

```
modalController.create({
      component: page,
      componentProps: data,
      delegate: this.myDelegateService.create(this.componentFactoryResolver, this.injector)
    });

```

**Other information:**

I suppose that for fix the problem is necessary invert the object in the options assign of the create function into the modal-controller.ts, for example:
```
create(opts: ModalOptions): Promise<HTMLIonModalElement> {
    return super.create({
      ...opts,
      delegate: this.angularDelegate.create(this.resolver, this.injector)
    });
  }

```
could become
```
create(opts: ModalOptions): Promise<HTMLIonModalElement> {
    return super.create({
       delegate: this.angularDelegate.create(this.resolver, this.injector),
      ...opts
    });
  }

```

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.4.0
   Ionic Framework               : @ionic/angular 5.4.3
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.1.2
   @angular/cli                  : 10.1.2
   @ionic/angular-toolkit        : 2.3.3

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe the problem you are trying to solve? Why do you need to override the framework delegate?

**Comment by falconeta** [comment]
I need to override the framework delegate for use a custom NavParam service. The problem is that if i pass a custom delegate, the create function don't use the custom delegate but the default one.

**Comment by liamdebeasi** [comment]
Can you provide a StackBlitz/GitHub repo that shows the issue you are running into? You should be able to inject a service directly into your modal component or use Angular Router's dependency injection to get params.

**Comment by falconeta** [comment]
if I inject the NavParams service in the modal page it works, but I need a service that will be provided only in the modal page (like the NavParams service).

**Comment by liamdebeasi** [comment]
Have you tried using `@Input` instead of using `NavParams`? See https://ionicframework.com/docs/api/modal#passing-data. So you would present your modal like this:

```js
async presentModal() {
  const modal = await this.modalController.create({
    component: ModalPage,
    cssClass: 'my-custom-class',
    componentProps: {
      'firstName': 'Douglas',
      'lastName': 'Adams',
      'middleInitial': 'N'
    }
  });
  return await modal.present();
}
```

Then you would set it up in your modal component as `@Input`: 

```js
export class ModalPage {

  // Data passed in by componentProps
  @Input() firstName: string;
  @Input() lastName: string;
  @Input() middleInitial: string;

}
```

**Comment by falconeta** [comment]
I agree with you but, as say before, i need to provide a custom service like NavParams only for the modals page. I see that in the ModalOptions interface there is the optional "delegate?: FrameworkDelegate". So if it is present in the ModalOptions, 
why not use it?

```
export interface ModalOptions<T extends ComponentRef = ComponentRef> {
  component: T;
  componentProps?: ComponentProps<T>;
  presentingElement?: HTMLElement;
  showBackdrop?: boolean;
  backdropDismiss?: boolean;
  cssClass?: string | string[];
  delegate?: FrameworkDelegate;
  animated?: boolean;
  swipeToClose?: boolean;
  mode?: Mode;
  keyboardClose?: boolean;
  id?: string;
  enterAnimation?: AnimationBuilder;
  leaveAnimation?: AnimationBuilder;
}
```

**Comment by liamdebeasi** [comment]
The delegate is intended for internal framework usage. It basically bridges the gap between Angular (or React/Vue) and Ionic Framework when creating overlay components, so I am a bit hesitant to allow users to override this.

Can you please create a code example that shows the issue you are running into?

**Comment by falconeta** [comment]
I created the stackblitz project:
https://stackblitz.com/edit/ionic-5-angular-10-start-template-fxtpfc?file=src/app/modal-page/modal-page.component.ts

**Comment by liamdebeasi** [comment]
Thanks for the code reproduction. From the example you provided, it looks like you are trying to get the ID of the modal. Why does this have to be done through a custom service you inject? I think the easier approach would be to use the `getTop` method on `ModalController` to access the current modal instance:

```js
const modal = await this.modalCtrl.getTop();
const id = modal.id;
```

Can you try this instead of your custom service solution, and let me know if this resolves the issue?

**Comment by falconeta** [comment]
thanks for the quick response. the modal id is an example just to describe a simple scenario but for the real implementation this service is a little more complex and it has a specific logic for the modals. I understood that  override the framework delegate involves some risks... There is another way to provide a service only for modals without declare it into the component decorator?

**Comment by liamdebeasi** [comment]
Can you clarify what "provide a service only for modals" means? You should be able to inject any service in a modal component just as you would with any other Angular component.

Perhaps you could describe the real world problem that you are trying to solve?

**Comment by falconeta** [comment]
like the NavParams service, I need a service (es. FooService) that is provided only for modals and the instance of that service exist until the page is destroyed, so every page loaded like a modal have an instance of that service. For achieve this behavior 
I could declare the service into every components' page decorator with the providers params, es:
```
@Component({
  selector: 'modal-page',
  providers: [FooService]
})
export class ModalPage {

```

but is complex to apply this approach for every page that would be loaded with the modalController and also is impossible to pass any custom provider to the FooService (like a custom BarService or a value).

**Comment by liamdebeasi** [comment]
Thanks for the clarification. I don't think overriding the `delegate` property is going to help you here. Injecting your service directly into your component is what Angular recommends, so you are likely going to run into other issues if try to continue with your custom delegate approach.

I am not sure how you are approaching this in your app, but you can pretty simply add `providers: [FooService]` which would create a new instance of `FooService` per-modal as you described. You also mentioned that you can't provide a custom service inside of `FooService`, which sounds like you are doing something wrong in your app. When using a dependency injection, you should be able to inject any other services into it, assuming that they are provided in the correct scope.

This is more of a support question now, so I would encourage you to ask it on our forums instead: http://forum.ionicframework.com/.

Thanks!
