### ISSUE TITLE
bug: ionic vue tab change events not firing

### ISSUE THREAD

**Issue by Calvin1121** [ionic-team/ionic-framework#22466]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```
![image](https://user-images.githubusercontent.com/31435496/98663905-a7a20300-2384-11eb-9ac8-6dfe8b51033e.png)
I wanna get the selected tab when the tabs changed, so i used the event 'ionTabsDidChange' to listen the value of tab, but it doesn't work. And I hope get the value by 'getSelected' like the method what i coded on Angular. 
![image](https://user-images.githubusercontent.com/31435496/98664812-cead0480-2385-11eb-94a8-86d30fcccd60.png)
So anyone can help me to solve it. I'm just new in Ionic-vue. And the documentation of vue doesn't make it clear.

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. You are doing things correctly in Ionic Vue, there is just a bug where the event is not firing. I will work on a fix for this.

**Comment by Calvin1121** [comment]
Hello @liamdebeasi, There is still a questin that how can I use the method 'getSelected' in vue. Should I use the property 'ref' to get it? Thx a lot.

**Comment by liamdebeasi** [comment]
I don't think IonTabs has that method exposed. I can address in a separate PR. Once that is in, yes you would use a `ref` on `IonTabs` to access it.

Here is a dev build if you want to test the fix for the change events:

```
npm install @ionic/vue@5.5.0-dev.202011111859.6ee38a2 @ionic/vue-router@5.5.0-dev.202011111859.6ee38a2
```

**Comment by Calvin1121** [comment]
Thx a lot. The event is firing now. And I'm sure there is method exposed, and I just kenew it can be accessed by 'ViewChild' in Angular. BUt I have no idea about it in Vue.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22479, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by Snogo** [comment]
same with _ionChange_  from **ion-segment** or why does the method doesn't fire?

` <ion-segment v-model="counttype"  @ionChange="segmentChanged($event)">

...

segmentChanged(ev: CustomEvent) {
      console.log('Segment changed', ev);
      counttype = ev.detail.value;
    }`
