### ISSUE TITLE
bug: content resets scroll when infinite scroll fires and keyboard is open

### ISSUE THREAD

**Issue by dzNavitski** [ionic-team/ionic-framework#22465]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
 `ion-content` scrolls to top when input is focused and keyboard is visible after infinite scroll starts loading.

**Expected behavior:**
 `ion-content` does not scroll to top when input is focused and keyboard is visible after infinite scroll starts loading. 

**Steps to reproduce:**
Precondition: at the bottom of `ion-content` is placed empty `div` with ngIf condition which is toggled in loading method.

1. place focus on search input
2. check that keyboard is visible
3. scroll to bottom 
4. observe that ion-content scrolled to top

**Related code:**

https://github.com/dzNavitski/ionic-conference-app

Please check "Schedule" page.

**Other information:**

**Ionic info:**

```
ionic cordova run ios --prod --l
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This ended up being a bug in iOS that has since been resolved. I recommend updating your device to the latest version of iOS to receive a fix for this issue.
