### ISSUE TITLE
bug: Ionic list swipe gestures is laggy for Ipad with big lists (100 items)

### ISSUE THREAD

**Issue by lydemann** [ionic-team/ionic-framework#22460]
# Bug Report

We got two Issues with Ionic lists if they reach around 100 items:

Swipe gestures are very laggy on Ipad (Ipad 2017 with iOS14.1). The swipe gestures are often not responding when swiping to either of the sides

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

https://github.com/lydemann/list-swipe-demo

Go to list with 2017 iPad with iOS 14.1.

Reproduce laggy swipe actions:

1. Scroll down the list
2. Try to swipe a couple of the items fast
3. See often it is not responding to the swipe

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What version of Ionic Framework are you testing this on? I am testing this on Ionic Framework v5.4.3 and am unable to reproduce the issues you are describing.

**Comment by kensodemann** [comment]
I tried your sample on an iPad (6th generation, 2018) with iOS 14.2 and it ran just fine.

I took the sample and went up to 1000, and ran into the issue there, but at that point I suggest using some kind of virtual scroll mechanism.

**Comment by lydemann** [comment]
The swipe actions are still not very smooth/responsive on iPad.
Look at this video demonstrating some issues with my demo project on my iPad 2017 with iOS 14.1.
https://drive.google.com/file/d/1anUPpkeWVz6urthUJChxMR_xfNDz68dJ/view?usp=sharing

**Comment by kensodemann** [comment]
The behavior you are seeing I did not see on my iPad with only 100 items. However, if I bump it to 1000 then I do see that behavior with the sliding. This tells me it has something to do with the size of the DOM, so it makes sense to limit that.

So I changed the sample to use virtual scrolling, and that aliviates the problem:

```html
  <ion-virtual-scroll [items]="items">
    <ng-container *virtualItem="let item">
      <ion-item-sliding>
        <ion-item-options side="start">
```

Since `ion-virtual-scroll` will eventually be deprecated, you may want to use the CDK VS instead, though I do not know if the Ionic Framework is completely ready for that right now. I know it is being tested and documented, but I am not sure of the status. @liamdebeasi will have to chime in on that.

If it isn't ready yet, then `ion-virtual-scroll` for now and then swapping it out later for CDK VS is probably your best option.

**Comment by lydemann** [comment]
> The behavior you are seeing I did not see on my iPad with only 100 items. However, if I bump it to 1000 then I do see that behavior with the sliding. This tells me it has something to do with the size of the DOM, so it makes sense to limit that.
> 
> So I changed the sample to use virtual scrolling, and that aliviates the problem:
> 
> ```
>   <ion-virtual-scroll [items]="items">
>     <ng-container *virtualItem="let item">
>       <ion-item-sliding>
>         <ion-item-options side="start">
> ```
> 
> Since `ion-virtual-scroll` will eventually be deprecated, you may want to use the CDK VS instead, though I do not know if the Ionic Framework is completely ready for that right now. I know it is being tested and documented, but I am not sure of the status. @liamdebeasi will have to chime in on that.
> 
> If it isn't ready yet, then `ion-virtual-scroll` for now and then swapping it out later for CDK VS is probably your best option.

Maybe because you are using a newer iPad, mine is a 2017 with iOS 14.1.

How would you have swipe actions in Angular CDK's VS?

**Comment by liamdebeasi** [comment]
Angular CDK's Virtual Scroll should be a drop in replacement. There are no known issues that CDK Scroller introduces with Ionic apps, and it does fix several issues in `ion-virtual-scroll`.
Here is an example on how to add that to your app: https://material.angular.io/cdk/scrolling/overview

**Comment by lydemann** [comment]
@liamdebeasi thanks. Will see if we can make our list work with Angular CDK VS.
