### ISSUE TITLE
bug: hover state covers activated state on button

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#22468]
# Bug Report

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
The buttons on iOS should have a better UX. More life when buttons pressing.

**Describe Preferred Solution**
Just a better indication for user input. The user should not ask, "Did I press the button or not?"
Of course, a button action mostly results to screen change. (change value, page, etc.)
But I think, it's not the worst idea to breathe more life into the button. Optional or not.

**Describe Alternatives**
Option to enable ripple effect for iOS buttons too. But a fading highlight will also better than a static element. Something you can see, when your finger is not on screen anymore. A short animation time like ripple-effect. Immediately on / after pressing.

**Related Code**
https://ionicframework.com/docs/api/button

**Additional Context**

| md | ios |
| :-: | :-: |
| ![md-button](https://user-images.githubusercontent.com/60390085/98685836-29376800-2368-11eb-8cbf-249830163c1c.gif) | ![ios-button](https://user-images.githubusercontent.com/60390085/98685855-2f2d4900-2368-11eb-94b4-f084c6facab7.gif) |
|![wow-reaction](https://user-images.githubusercontent.com/60390085/98685896-38b6b100-2368-11eb-90a4-d0d9e8a9c1b8.gif)  | ![disappointed-reaction](https://user-images.githubusercontent.com/60390085/98685902-3a807480-2368-11eb-9ea0-affb05e1378c.gif) |

On iOS the only click indicator is from my gif recorder. 😄

**Comment by liamdebeasi** [comment]
Thanks for the issue. We do have an activated state, but it looks like the hover state is covering it up.
