### ISSUE TITLE
bug: HTML comment inside of ion-slides causing uncaught error

### ISSUE THREAD

**Issue by tones31** [ionic-team/ionic-framework#22475]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
An `<ion-slides>` element is **dynamically** added into an HTML file. This often causes an uncaught error `Uncaught (in promise) TypeError: Cannot read property 'childNodes' of null`. It seems that there is a stray HTML comment `<!---->` inside `ion-slide` regardless of whether it has any `ion-slide` elements. You can even see this HTML comment in the demo https://ionicframework.com/docs/api/slides

It seems that this element's state is "not connected" so perhaps if there is a way to wait until all `<ion-slides>` are 'ready' that would resolve the issue. This does not occur when hardcoding `<ion-slides>` into the HTML.

**Expected behavior:**
No errors. Comment should not exist or comment elements should be ignored.

**Steps to reproduce:**
Add an `<ion-slides>` element

**Related code:**
See attached images
![1](https://user-images.githubusercontent.com/8292995/98763166-74bd3680-23a7-11eb-99de-c55f233258d3.png)
![2](https://user-images.githubusercontent.com/8292995/98763168-7555cd00-23a7-11eb-95e6-119061fd2f90.png)
![3](https://user-images.githubusercontent.com/8292995/98763169-75ee6380-23a7-11eb-897c-d2bfd9bf120c.png)

PS - Are there any single-file dist JS files for the frontend? It's almost impossible to debug the obfuscated files like p-5aa5c370.js

**Comment by tones31** [comment]
There may be an easier way to solve this. But I cannot find any "hydrated" events or similar. So what I did was add a MutationObserver to wait until the "hydrated" class was appended and then emit an event on that. Then it was safe to append my slides.


       ```
 let obs = new MutationObserver((list, observer) => {
            for(const mutation of list){
                if (mutation.type === 'attributes') {
                    if(mutation.attributeName === 'class'){
                        if(this.slides.classList.contains('hydrated')){
                            let event = new Event("ready");
                            this.dispatchEvent(event);
                        }
                    }
                }
            }
        });
        obs.observe(this.slides, {attributes: true});
```

**Comment by liamdebeasi** [comment]
Can you reproduce the issue in an Ionic starter app and send a link to the GitHub repo? My initial thought is this is a bug in Swiper, but I am not 100% sure.

**Comment by tones31** [comment]
I will try and get that to you. So far to remedy this is:
I added a MutationObserver on the `<ion-slides>` to wait until the div with `swiper-wrapper` was appended. Then instead of appending my `<ion-slide>`s directly to `<ion-slides>` I appended it to the `swiper-wrapper`. This finally works reliably. Sometimes appending directly to `<ion-slides>` works and sometimes it doesn't. I can't figure out the lifecycle of this thing.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
