### ISSUE TITLE
bug:  iOS 14 device -  scrolling over ion-content/ion-tabs/ion-segment not working

### ISSUE THREAD

**Issue by marimendez88** [ionic-team/ionic-framework#22474]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.0.0**

**Current behavior:**

Only iOS 14 devices have issues with scrolling.
When a PWA with a larger content is shown on the app, is possible for scrollable areas to become "frozen" (i.e. the user is unable to scroll).
The scroll works as expected, but the app freezes after the scroll action :
i.e Having a tab with scrollable content and having another tab with buttons,
I am able to go to the scrollable tab, and do the scroll, after return to my first tab and try to click the buttons, the app freeze -> THE ENTIRE APP is frozen. 

**Expected behavior:**

The scroll should continue without any problems. 

**Steps to reproduce:**

1. Create an ion-tabs structure.
2. Make the ion-content a long scrollable area in one of the ion-tabs.
3. E.g, create over 1000 card content using *ngFor and ion-list.
5. After build, run on iOS 14 device.
5. The app freezes after repeated scrolling.

**Related code:**

I created this repo for your reproduction: 
https://github.com/marimendez88/ios-ionic-scroll-issue

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.0
   @angular-devkit/build-angular : 0.1001.1
   @angular-devkit/schematics    : 10.1.1
   @angular/cli                  : 10.1.1
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.1
   @capacitor/core : 2.4.2

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : 1.2.2

System:

   NodeJS : v14.7.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina

```

**Comment by marimendez88** [comment]
cc: @jedihacks -  @Fdom92 -  @pablo-of - @openforge

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide some clarified steps to reproduce? Here are the steps I am following:

1. Add the app as a PWA on an iOS device.
2. Open Tab 2 and begin to scroll.

I have not been able to get scrolling to break. Do I need to do something else?

**Comment by marimendez88** [comment]
Thanks to the response @liamdebeasi 

Some steps which I did: 
1. ng build
2. ionic cap copy ios
3. ionic cap run ios
4. Open the app on Xcode and install on my iOS device
5. Go to tab 2, scroll 
6. Go to tab 1, try to click any button there. -> the app freeze

**Comment by marimendez88** [comment]
in addition -> Normally that occurs frecuently when I use </ion-segment-button> /  <ion-tabs>

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I still am not able to reproduce the issue you are describing. Here are the steps I am following:

1. Run app in Capacitor on iOS 14 device. (I am using an iPhone 11 running iOS 14.2)
2. Tap the button for "Tab 2".
3. Scroll on Tab 2. I am able to scroll here.
4. Tap the button for "Tab 1".
5. Tap the "Simple Alert" button. The alert presents and dismisses correctly, but I can still scroll afterwards.

Do I need to do anything different?

**Comment by marimendez88** [comment]
Hey @liamdebeasi , I just updated the repo adding exactly what is happening with the ion-segment. 


So, steps: 

1. Run app in Capacitor on iOS 14 device.
2. Tap the button for "Tab 3".
3. Segment Atoms: try Scroll here
4. Change to the segment Modelules: scroll here. 
5. Change to the segment Organisms: try to click the buttons. should prompt an alert and an action sheet. 

The app freeze

**Comment by liamdebeasi** [comment]
Thanks for the clarification. I tried your app again using the steps provided, and was still unable to reproduce the issue. What device are you testing this on?
