### ISSUE TITLE
bug: SwipeGesture don't work for Android

### ISSUE THREAD

**Issue by LeandroSeoane** [ionic-team/ionic-framework#22471]
Hi everyone,

I need your help. I'm implemented an application with Ionic 5 (with angular) and I realize that I can't restrict the swipe gesture or the back button for Android.

I tried setting `[swipeGesture]="false"` and didn't work, I try many things and I can't make it work.

For iOS work fine adding:
`IonicModule.forRoot({
      swipeBackEnabled: false
    })`

But for Android unfortunately not.

Could you please help me?

Thanks in advance.

**Comment by liamdebeasi** [comment]
Hey there,

This GitHub issue tracker is for bugs and feature requests in Ionic Framework. If you are looking for general help debugging your Ionic app, I recommend first posting on our forums: https://forum.ionicframework.com/

If after debugging your app you think this is a bug in Ionic Framework, please open a new issue here with a GitHub repo that shows the issue happening, and we will be happy to take a closer look.

Thanks!
