### ISSUE TITLE
bug: scroll assist is not working on PWA with latest version of Ionic 5.4.3

### ISSUE THREAD

**Issue by joeszewski** [ionic-team/ionic-framework#22480]
# Bug Report

**Ionic version:**
5.4.3

**High level summary**
I opened a bug for the same problem when running 5.1.1, but it was fixed when I upgraded to 5.2.2 - see https://github.com/ionic-team/ionic-framework/issues/21345 

Since then, I've upgraded from 5.2.2 to 5.3.1 (still worked great), but now I've gone from 5.3.1 to 5.4.3 and the issue has popped up again.

**Current behavior:**
I have a form with a list of inputs (create account form). When tapping through the inputs, the keyboard overlays and hides the input. 

**Expected behavior:**
When tapping through a list of inputs and the keyboard displays, the focused input should also remain visible.

**Replication Steps**
1. Start a new app
2. Paste the below code snippet into an html template
3. Build the app and run on an iOS device (I noticed on iPhone 11 Pro running iOS 13.4.1)
4. Tap through list of inputs and notice that the auto-assist does not slide the next input into view after tapping through the first 2 to 3

**Related code:**
I'm running an Angular PWA on iOS safari.
Here's an example of what the structure of my template looks like:
```
<form>
 <ion-item>
  <ion-label position="stacked">Example</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item>
  <ion-label position="stacked">Example</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item>
  <ion-label position="stacked">Example</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item>
  <ion-label position="stacked">Example</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item>
  <ion-label position="stacked">Example</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item>
  <ion-label position="stacked">Example</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item>
  <ion-label position="stacked">Example</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item>
  <ion-label position="stacked">Example</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-item>
  <ion-label position="stacked">Example</ion-label>
  <ion-input type="text"></ion-input>
 </ion-item>

 <ion-button shape="round" expand="full">Create Account</ion-button>
</form>
```

**Other information:**
Notice that I'm not currently wrapping the ion-items in an ion-list, I'm not sure if that would have any impact.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.4.3
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.0.2
   @angular/cli                  : 10.0.2
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.1.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/usr/local/Cellar/node/9.6.1/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

**Comment by joeszewski** [comment]
@liamdebeasi I've added replication steps. Note that this only shows up on a real device with the keyboard, so you'll have to deploy it somewhere that you can get to from a phone.

**Comment by liamdebeasi** [comment]
Thanks. I tested this on an iPhone 11 (iOS 14.2) and an iPhone 11 Pro (iOS 13.6) and cannot reproduce the issue. Can you send a video of what you are seeing?

**Comment by joeszewski** [comment]
Here's a video. Note that there's a weird thing happening in the video playback where the keyboard doesn't display for some reason...it did not actually look like this when I recorded it, but you can still see that the scroll assist doesn't work.

[RPReplay_Final1605126032.MP4.zip](https://github.com/ionic-team/ionic-framework/files/5526563/RPReplay_Final1605126032.MP4.zip)

**Comment by liamdebeasi** [comment]
Thanks, that video was very helpful. https://github.com/ionic-team/ionic-framework/issues/18532 looks like it would solve this issue, so I will track progress on this issue there. Why it was working before, I don't really know. Scroll assist is one big hack to work around a long standing pain point with keyboards on the web, so it could have just been a convenient race condition that allowed it to work before.

I will post updates on https://github.com/ionic-team/ionic-framework/issues/18532. Thanks!
