### ISSUE TITLE
bug: core/dist/ionic/ionic.js was removed in 5.4.2

### ISSUE THREAD

**Issue by hankhester** [ionic-team/ionic-framework#22483]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

According to its readme the recommended way of using @ionic/core when `<script type="module"...` isn't an option is by loading `@ionic/core/dist/ionic/ionic.js`
This file was removed in the 5.4.2 release, as apparent from these two urls:
works: https://cdn.jsdelivr.net/npm/@ionic/core@5.4.1/dist/ionic/ionic.js
not found: https://cdn.jsdelivr.net/npm/@ionic/core@5.4.2/dist/ionic/ionic.js

**Expected behavior:**

Either this file should be added back or @ionic/core's readme should be updated with a new way of using the package when es modules aren't an option

**Comment by liamdebeasi** [comment]
Thanks! I just fixed this in the Ionic Framework v5.4.4 release.
