### ISSUE TITLE
Can't bind to 'ngForOf' since it isn't a known property of 'ion-col'.

### ISSUE THREAD

**Issue by rkpip3** [ionic-team/ionic-framework#22482]
**Describe the bug**

Can't bind to 'ngForOf' since it isn't a known property of 'ion-col'.

**To reproduce**
<ion-content>
  <ion-grid>
    <ion-row>
    <ion-col size="6"  *ngFor="let photo of homepage;">
        <ion-img [src]="item.file1"></ion-img>
    </ion-col>
    </ion-row>
  </ion-grid>

**Screenshots**

**Browser and OS (please complete the following information)**
 - OS: Mac
 - Browser: chrome
 - Version: 22

**Comment by indraraj26** [comment]
Make sure that your component is registered on appropriate module.ts and it has commonModule in imports[]
