### ISSUE TITLE
bug: ionic vue not going back to correct tab after replacing route

### ISSUE THREAD

**Issue by mattmilan-dev** [ionic-team/ionic-framework#22492]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

With a router containing a parent and child routes (tabs), start at a child route, navigating to a parent route, then back to a different child route, the child route loaded the second time around actually shows the first child component. The issue in the DOM shows as having a lower z-index and the 'ion-page-hidden' class on the second child route.

Example: 
- /parent-route
- /tabs
- - /child-1
- -  /child-2

Navigating from /tabs/child-1 to /parent-route back to /tabs/child-2 shows the child one component instead of the child two component (although the tabs component and URL do indeed show the child-2 route).

**Expected behavior:**
With the example above, the child-2 component should be shown when redirecting back down from the parent route.

**Steps to reproduce:**
Create a new ionic project for vue with 3 routes as explained in the example, using the tabs component. On load redirect to /tabs/child-1 and then use `useRouter().replace('/parent-route')` then `useRouter().replace('/tabs/child-2')`.

**Related code:**
router/index.ts
```
const routes = {
  {
    path: '/',
    redirect: '/tabs/child-1'
  },
  {
    path: '/tabs',
    component: Tabs,
    children: [
      {
        path: 'child-1',
        component: () => import('@/views/ChildOne.vue')    
      },
      {
        path: 'child-2',
        component: () => import('@/views/ChildTwo.vue')
      }
    ]
  }
}
```

Unfortunately, my actual repo closed source so I can't disclose the actual code, however the router look near identical to the above. With the effect happening using the `.replace('ROUTE')` method. In reality the parent route is an sign-in (auth) route, and the children represent auth locked content. If a user logs out it moves them to the parent route and then when they log in it redirects them back to the child (tabs) route.

**Other information:**
In my actual app. Initial DOM on child-1: (1 parent route, 1 tabs route, 4 children routes)
<img width="895" alt="Screenshot 2020-11-12 at 18 43 48" src="https://user-images.githubusercontent.com/49694881/98990764-cfc76880-2522-11eb-8eb9-65be1ff77e98.png">

After redirecting to the parent page, and back to the other child page
<img width="591" alt="Screenshot 2020-11-12 at 18 44 44" src="https://user-images.githubusercontent.com/49694881/98990888-fc7b8000-2522-11eb-97aa-b101d3f250e0.png">

How the DOM should actually look if the bug wasn't present:
<img width="748" alt="Screenshot 2020-11-12 at 20 11 33" src="https://user-images.githubusercontent.com/49694881/98991112-49f7ed00-2523-11eb-86ef-eae7a9e39d19.png">

What actually shows on screen (The initial child component with the correct tabs icon highlighted)
<img width="321" alt="Screenshot 2020-11-12 at 18 44 52" src="https://user-images.githubusercontent.com/49694881/98990917-069d7e80-2523-11eb-98f7-74e3beab6655.png">

What should actually show on screen (The redirected child component with the correct tabs icon highlighted)
<img width="324" alt="Screenshot 2020-11-12 at 18 45 04" src="https://user-images.githubusercontent.com/49694881/98991021-292f9780-2523-11eb-864c-7b463715fbfb.png">

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.1 (/Users/devleaf_matt/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.2
   native-run  : 1.2.2

System:

   NodeJS : v12.18.1 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide a full GitHub repo that I can use to reproduce the issue?

**Comment by mattmilan-dev** [comment]
Hi Liam,

Thanks for your rapid response. Getting a github repo up now as we speak. Writing the readme and should be up in 5 and tagged on this issue.

**Comment by mattmilan-dev** [comment]
Link here for github repo with instructions:
https://github.com/mattmilan-dev/Ionic-Vue-Routing-Bug

**Comment by liamdebeasi** [comment]
Thanks! I can reproduce the issue. I will work on a fix for this.

**Comment by mattmilan-dev** [comment]
Awesome, look forward to the fix being in place. Apologies for not submitting a fix request myself. I've only got started with vue about a month ago so don't feel confident enough to know exactly what's going wrong next. Thanks for your lightning fast responses though 👍

**Comment by AiNings** [comment]
I have the same problem

**Comment by yxg-xg** [comment]
I have the same problem.I felt so confused for this

**Comment by liamdebeasi** [comment]
Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.6.0-dev.202011251808.8f06c6a @ionic/vue-router@5.6.0-dev.202011251808.8f06c6a
```

Please note you will need an updated version of the `vue-router` pre-release: `npm install vue-router@next`

**Comment by mattmilan-dev** [comment]
Seems to be working as expected now on my actual app. Great job 👍

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22566, and a fix will be available in an upcoming release of Ionic Framework.
