### ISSUE TITLE
feat: toastDuration global config option

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/ionic-framework#22497]
A global config for toast duration would be helpfull here: https://ionicframework.com/docs/angular/config :)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe your use case for this feature?

**Comment by SvenBudak** [comment]
Currently i solved it in this way:

env:
```
    ionicComponentConfig: {
        toast: {
            duration: 4000
        }
    }
```

component.ts:
```
import {environment} from '../../../../environments/environment';

const toast = await this.toastController.create({
    message: this.translocoService.translate('error.validation.email_empty'),
    duration: environment.ionicComponentConfig.toast.duration <<<<<<
});
await toast.present();
```

And i think something like:
```
IonicModule.forRoot({
    toastDurration: 4000
}),
```

Is a bit nicer.

**Comment by amandaejohnston** [comment]
This has been added via https://github.com/ionic-team/ionic-framework/pull/26425 and will be available in the upcoming minor release of Ionic. Thank you!
