### ISSUE TITLE
bug: Scrollbar not showing using ion-virtual-scroll on Android 

### ISSUE THREAD

**Issue by moyinwong** [ionic-team/ionic-framework#22508]
# Bug Report

**Ionic version:**
[x] **5.4**

**Current behavior:**

When using ion-virtual-scroll, scrollbar is not showing up when scroll down or up on Android (Samsung Galaxy S10)

**Expected behavior:**

Scrollbar should be on the right hand side of the screen when scrolling

**Steps to reproduce:**

HTML:
```
<ion-content fullscreen>
  <ion-list *ngFor="let item of items;">
    <ion-item>
      <ion-label> {{ item }}</ion-label>
    </ion-item>
  </ion-list>
</ion-content>
```
Component.ts

``` 
items: Number[];
this.items = Array(100).fill(0);
```

**Other information:**

I have tried searching through stackoverflow, ionic forum, and github, followed suggestion such as:
https://github.com/ionic-team/ionic-framework/issues/10676
https://forum.ionicframework.com/t/scrollbar-not-visible-on-android/53616/2
but none of them work

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.11 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.3
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.1.7
   @angular/cli                  : 10.2.0
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 27 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.2.2) : 1.2.1

System:

   ios-deploy : 1.11.2
   ios-sim    : 8.0.2
   NodeJS     : v12.19.0 (/usr/local/bin/node)
   npm        : 6.14.8
   OS         : macOS Catalina
   Xcode      : Xcode 12.2 Build version 12B45b
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. With upcoming major versions of Ionic Framework, we are going to be transitioning to using Angular's CDK Scroller. As a result, we have a freeze on new features and bug fixes on ion-virtual-scroll. See https://material.angular.io/cdk/scrolling/overview for how to get started with CDK Scroller.
