### ISSUE TITLE
bug: Component disappears in the first time on iOS

### ISSUE THREAD

**Issue by SidiBecker** [ionic-team/ionic-framework#22509]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
On iOS, the first time I access the page, the ```ion-segment``` component is rendered but disappears shortly thereafter. The second time I access the page, the component remains visible. On android works normally.

**Expected behavior:**
The component must remain visible.

**Steps to reproduce:**
Create a secondary page with the structure below.

**Related code:**

```

<ion-header>
  <ion-toolbar>
...
  </ion-toolbar>

  <ion-segment value="{{someVar}}" (ionChange)="onChange($event)">

    <ion-segment-button [value]="item.id" *ngFor="let item of items">
      {{item.description}}
    </ion-segment-button>

  </ion-segment>

</ion-header>

<ion-content>
.....
</ion-content>
```

**Other information:**
I created a post on [Ionic Forum](https://forum.ionicframework.com/t/bug-component-disappears-in-the-first-on-ios/199748).

**Ionic info:**
```
Ionic Info:

   Ionic CLI                     : 5.2.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.803.28
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.3.28
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 30 other plugins)

Utility:

   cordova-res : 0.8.1 (update available: 0.15.2)
   native-run  : 0.2.8 (update available: 1.2.2)

System:

   ios-sim : 8.0.2
   NodeJS  : v10.16.3 (/usr/local/bin/node)
   npm     : 6.11.1
   OS      : macOS Catalina
   Xcode   : Xcode 11.4.1 Build version 11E503a
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the GitHub repo?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
