### ISSUE TITLE
feat: Vue unit tests -  remove hard requirement of a `navManager` injection when not using any navigation

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#22506]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
When doing unit testing with `@ionic/vue`, provide a way to not have to mount a component with the router if the component is not actually using any routing.

Currently, the following warning is raised in these situations:

```
  console.warn node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40
    [Vue warn]: injection "navManager" not found.
      at <Anonymous>
      at <Anonymous size="3" key=7 >
      at <Anonymous class="ion-align-items-stretch" key=1 >
      at <Anonymous>
      at <Anonymous fullscreen=true >
      at <IonPage>
      at <Tea ref="VTU_COMPONENT" >
      at <VTUROOT>
```

**Related Code**
The following tests raise the above warning:
https://github.com/kensodemann/tea-taster-vue/blob/main/tests/unit/views/Tea.spec.ts

However, the code itself is not (yet) doing any routing: 

```html
            <ion-card>
              <ion-img :src="tea.image"></ion-img>
              <ion-card-header>
                <ion-card-title>{{ tea.name }}</ion-card-title>
              </ion-card-header>
              <ion-card-content> {{ tea.description }} </ion-card-content>
            </ion-card>
```

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/22532
