### ISSUE TITLE
bug: canceling swipe back animation causes white screen

### ISSUE THREAD

**Issue by mozhn** [ionic-team/ionic-framework#22503]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
I am having the same situation as here. The only difference is ionic 4.
https://github.com/ionic-team/ionic-framework/issues/21056

**Expected behavior:**
Swipte back gesture should show the previous screen.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.3
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.13.5
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.5
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : 5.0.4, android 8.1.0, browser, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 35 other plugins)

Utility:

   cordova-res : 0.9.0 (update available: 0.15.2)
   native-run  : 0.3.0 (update available: 1.2.2)

System:

   Android SDK Tools : 26.1.1 (/Users/mazlumozhan/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.19.0 (/usr/local/Cellar/node@10/10.19.0/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 12.2 Build version 12B45b
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Does this problem occur on the latest version of Ionic Framework v5?

**Comment by mozhn** [comment]
> Thanks for the issue. Does this problem occur on the latest version of Ionic Framework v5?

Unfortunately, I do not know about this topic. I have only ionic 4 projects.

**Comment by liamdebeasi** [comment]
Thanks for the clarification. We are not developing Ionic Framework v4 anymore, so it is unlikely that we will resolve this issue there. It looks like the issue has been resolved in Ionic Framework v5, so I recommend upgrading to the latest version of v5 if you would like to receive this fix. Thanks!
