### ISSUE TITLE
feat: Remove necessity to define global dismissModal

### ISSUE THREAD

**Issue by tones31** [ionic-team/ionic-framework#22502]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
When creating a modal, which is already kind of weird (have to create on the fly, append to body, supply a component...) you also have to globally define a function called `dismissModal()`. I find this really silly especially when in the documentation it just calls `modal.dismiss()`. https://ionicframework.com/docs/api/modal#usage 

**Describe Preferred Solution**
No requirement to provide a global dismiss modal function. A callback option could be passed instead. `modal.dismissCallback = ...`

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. You can use the `ModalController` import in Ionic Angular or `modalController` import in Ionic Vue to programmatically dismiss the top-most modal.

Example in Angular:

```html
<ion-button (click)="modalCtrl.dismiss()">Dismiss Modal</ion-button>
```

```js
import { ModalController } from '@ionic/angular';
 
export class ModalPage {
  constructor(public modalCtrl: ModalController) {}
}
```

If you want to make the `modalCtrl` private you can create a `dismiss` method on your component that just called `modalCtrl.dismiss`, but the above solution may be simpler.
