### ISSUE TITLE
visual bug: ion-back-button ripple effect when no text

### ISSUE THREAD

**Issue by snakone** [ionic-team/ionic-framework#22501]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When you set **no text** to ion-back-button there's still --padding-end

**Expected behavior:**
ion-back-button --padding-end should be set to 0 when no text

**Steps to reproduce:**
```
<ion-back-button defaultHref="/tabs/home"
                              [text]="null">
</ion-back-button>

// set this to solve ripple visual bug when no text
ion-back-button {
  --padding-end: 0;
}
```
![sample](https://user-images.githubusercontent.com/18131303/99196863-394baf00-278f-11eb-9141-bec4a5e8fc6e.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in a blank Ionic starter app and provide a link to the GitHub repo? I cannot reproduce this behavior on my end.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
