### ISSUE TITLE
bug: problems with ion-input and ion-textarea when focusing

### ISSUE THREAD

**Issue by aparajita** [ionic-team/ionic-framework#22513]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

@liamdebeasi This might be one for you.

On Chrome or iOS, when clicking in either `ion-input` or `ion-textarea`, there is all kinds of undesired behavior:

- On Chrome (in `ios` mode), as you move down the page, there is a noticeable delay between the click and when the caret appears (~ 1-1.5 seconds).
- On both Chrome and iOS, the content of an ion-textarea with left padding shifts left and then right when focused.
- On iOS, the positioning of inputs in order to make them visible above the keyboard:
  - Does not always take into account the accessory bar.
  - Sometimes jumps around.
  - Does not fully reveal an input at the bottom of a modal. 

**Expected behavior:**

There should be no delay when clicking in those components, nor should they move. This is the behavior I see in other browsers and on Android.

**Steps to reproduce:**

1. Download the project listed below.
1. npm install.
1. npm run serve. Open in Chrome.
1. Click in each of the fields starting from the top. The first two should show no delay. Starting from the third, there is a delay which gets progressively longer as you go down.
1. Enter some text in field "Six".
1. Click in another field, then back in field "Six". You should see the text shift left immediately, and after a delay, shift back to its original position, after which the caret appears.
1. npm run ios. Run from Xcode.
1. The delays will not be so long, but you will see the moving behavior described above.
1. Click on "Modal". Do steps 4-6.

**Related code:**

Reduction/demo is here: https://github.com/aparajita/ionic-input-problem

This was created via `ionic start inputtest --type=vue blank`. Nothing changed other than taking out the large header, adding the markup, and adding some CSS.

The file `inputs.mov` shows the behavior that I get in iOS. The file `dom.mov` shows what's going on in the DOM during the bad behavior.

**Other information:**

When running on iOS, `window.navigator.appVersion` returns:

```
5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
```

Notes:

This bug is a result of some funny stuff going on when focusing an ion-input or ion-textarea via a click. If you look at dom.mov at 5 seconds, you'll see this happening during a click:

- The underlying `input` or `textarea` is cloned as a sibling.
- The original is given a translate3d transform with an X of -9999px (offscreen) and a Y that looks like it's compensating for the keyboard height.
- At some point later, the clone and transform are removed.

This does **not** happen when focusing via tab motion (and presumably the accessory bar). I won't speculate on why this is being done, but it's causing all kinds of problems. This doesn't happen on Safari or Firefox, or on Android using Chrome webview.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.1 (/Users/aparajita/.fnm/node-versions/v15.0.1/installation/pnpm-global/4/node_modules/.pnpm/@ionic/cli@6.12.1/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.4

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : not installed
   native-run  : 1.2.2

System:

   NodeJS : v15.0.1 (/Users/aparajita/.fnm/node-versions/v15.0.1/installation/bin/node)
   npm    : 7.0.3
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue.

> On Chrome (in ios mode), as you move down the page, there is a noticeable delay between the click and when the caret appears (~ 1-1.5 seconds).

> On iOS, the positioning of inputs in order to make them visible above the keyboard:
Does not always take into account the accessory bar.
Sometimes jumps around.
Does not fully reveal an input at the bottom of a modal.

These two should be resolved by https://github.com/ionic-team/ionic-framework/issues/18532.

> On both Chrome and iOS, the content of an ion-textarea with left padding shifts left and then right when focused.

This seems like a use case that https://github.com/ionic-team/ionic-framework/issues/18532 does not do well with either. I will merge this issue with the other one and track progress there. Thanks!
