### ISSUE TITLE
bug: ionic react IonTabButton overrides user onClick handler

### ISSUE THREAD

**Issue by AndreaBeggiato** [ionic-team/ionic-framework#22511]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
onIonClick on TabButton removed. 
We used to history.replace and not history.push when a tab is clicked, because our users when navigate between tabs prefer to back to the previous page and not to the previous tab. When they click back and forth through tabs, let's say 10 times, they need to press the back button (hardware or software) 10 times to return to the previous page.

**Expected behavior:**
Reintroduction of onIonClick on TabButton removed

**Steps to reproduce:**
Create any tab

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify the issue you are running into?

**Comment by AndreaBeggiato** [comment]
Hello @liamdebeasi 
here you can find a code example https://github.com/geekcups-team/ionic-5-tab-issue.
We have an outer tab bar with HomePage and TabPage. Inside TabPage we have two tabs (first and second). If you navigate between first tab and second tab a lot of time, you need to click the back button several time before returning to HomePage. In the previous release of Ionic we used to add a click handler to first tab and second tab buttons, and override the behaviour using history.replace inside the handler. With the new releases of Ionic we can't add such handler anymore.

**Comment by sstraus** [comment]
Same problem here.
@liamdebeasi have you some suggestions on how to handle click on v5?

**Comment by liamdebeasi** [comment]
Thanks for the clarification. We already have a feature request to add this functionality: https://github.com/ionic-team/ionic-framework/issues/17761. That being said, you should be able to override the default click event on `ion-tab-button`:

```jsx
const handleClick = (ev: Event) => {
  ev.stopImmediatePropagation();

  // Use router.replace or other custom logic here
}
...

<IonTabButton tab="first" href="/tabs/first" onClick={handleClick}>...</IonTabButton>
```

The key here is `ev.stopImmediatePropagation` as that will prevent other listeners of the same event from being called. I am going to close this issue, but any progress on this feature will be tracked in https://github.com/ionic-team/ionic-framework/issues/17761. Thanks!

**Comment by AndreaBeggiato** [comment]
@liamdebeasi I updated the repository https://github.com/geekcups-team/ionic-5-tab-issue and the main problem is that handleClick is never called because IonTabBar overrides the prop.

**Comment by liamdebeasi** [comment]
Oh weird, onClick was working last time I tested it. It looks like the IonTabButton component overrides any onClick handler you pass it in favor of its internal handler. What we should probably do is call the user's onClick handler and our internal logic, to give users a chance to preventDefault.

**Comment by AndreaBeggiato** [comment]
Any news about this?

**Comment by fr3fou** [comment]
Any news?

**Comment by fr3fou** [comment]
https://github.com/ionic-team/ionic-framework/blob/8e0e5da7407adecb7471b3a6b0ac059337761355/core/src/components/tab-button/tab-button.tsx#L135-L137

Isn't the fix just 4 lines?

```js
if (this.props.onClick) {
   this.props.onClick(ev)
}
this.selectTab(ev)
```

**Comment by paulantoine2** [comment]
I found a workaround with `onIonTabsWillChange` props

```
const handleTabWillChange = (e) => {
    if (e.detail.tab === 'tabName') {
       // onClick stuff
    }
};

<IonTabs onIonTabsWillChange={handleTabWillChange}>
    <IonTabButton tab="tabName">
        ...
    </IonTabButton>
</IonTabs>
```

**Comment by VonStroheim** [comment]
Not really _accessible_, but there is also the workaround of `onClick` on the IonIcon element instead of IonTabButton. This is handy when IonTabBar is not inside IonTabs, thus preventing the use of onIonTabsWillChange.

**Comment by kenchambers** [comment]
any updates on this?

**Comment by miodrage** [comment]
Any news?

**Comment by iamjoshua** [comment]
Very much still broken. Also, page transitions with IonTabButton are never fired for me in a clean Ionic project. I'm not sure if this is a related event handling issue.

**Comment by eugenelet** [comment]
@iamjoshua If that's the case, is there an alternative on combining page transitions and IonTabButton-related element?

**Comment by s-bridges** [comment]
Would love to see an update to this.

**Comment by C0ffeeL0ver** [comment]
One of the solutions is this:
```js
          <IonTabButton tab="Map" >
            <IonItem onClick={()=> console.log(2)}>
              <IonIcon icon={triangle} />
              <IonLabel>Map</IonLabel>
            </IonItem>
          </IonTabButton>
```

**Comment by sean-perkins** [comment]
Hello 👋  can someone that has experienced this issue, test with this dev-build and let me know if the problem persists?
```
6.1.5-dev.11651863883.16a7a3b0
```

Thanks!
