### ISSUE TITLE
bug: Navigation Hooks are never called (beforeEnterHook, beforeLeaveHook)

### ISSUE THREAD

**Issue by igorovic** [ionic-team/ionic-framework#22516]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
ion-route properties `beforeEnter` and `beforeLeave` are removed in function [matchesPath](https://github.com/ionic-team/ionic-framework/blob/33768e1d0ce5be2b9f6cb49faab6fbaa636e94a3/core/src/components/router/utils/matching.ts#L74)

**snippet**
```ts
return chain.map((route, i) => ({
      id: route.id,
      path: route.path,
      params: mergeParams(route.params, allparams![i])
    }));
```

**should be something like this**
```ts
return chain.map((route, i) => ({
      id: route.id,
      path: route.path,
      params: mergeParams(route.params, allparams[i]),
      beforeEnter: route.beforeEnter,
      beforeLeave: route.beforeLeave
    }));
```

Because then the navigation hooks are used in [router.tsx](https://github.com/ionic-team/ionic-framework/blob/77464ef21aaaa5afa7a02e5417f3ec295b240601/core/src/components/router/router.tsx#L283)

**snippet**
```ts
const beforeEnterHook = toChain && toChain[toChain.length - 1].beforeEnter;
const beforeLeaveHook = fromChain && fromChain[fromChain.length - 1].beforeLeave;
```

**_But since those properties where previously removed they are always undefined._**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a code reproduction of the issue and provide a link to the GitHub repo?

**Comment by igorovic** [comment]
Here is the reproduction code. 

[https://github.com/igorovic/ionic-bug-navhooks](https://github.com/igorovic/ionic-bug-navhooks)

You should check the file [app-root.tsx](https://github.com/igorovic/ionic-bug-navhooks/blob/0540b1cf210b1f010a0c32bdd052170b40deca9c/src/components/app-root/app-root.tsx#L3)

**Comment by liamdebeasi** [comment]
Thanks! Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/core@5.5.0-dev.202011181622.33768e1
```

**Comment by igorovic** [comment]
Yes it works :thumbsup:

Side note: _My VScode ts linter is not happy with my custom component since I installed this dev build._

**Comment by liamdebeasi** [comment]
> Side note: My VScode ts linter is not happy with my custom component since I installed this dev build.
 
Are you getting an error?

**Comment by igorovic** [comment]
Never mind, it's an issue in my custom component that broke the linter.

Regarding the navigation hook it's fixed in => `@ionic/core@5.5.0-dev.202011181622.33768e1`

**Comment by liamdebeasi** [comment]
Glad it's fixed! Thanks for double checking the linter issue.

**Comment by igorovic** [comment]
Thank you for the fix 👍 . I would have done it myself but I didn't read the contribution guide yet. 😄

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22521, and a fix will be available in an upcoming release of Ionic Framework.
