### ISSUE TITLE
bug: nested ion-tabs cause router errors

### ISSUE THREAD

**Issue by leibale** [ionic-team/ionic-framework#22536]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Clicking an `<ion-tab-button>` that is inside an `<ion-tabs>` that is nested inside another `<ion-tabs>` calls `router.navigate` twice.

**Expected behavior:**
Only the closest `<ion-tabs>` component should call `router.navigate`.

**Related code:**
https://stackblitz.com/edit/ionic-v5-nested-tabs
Just click on "Tab 3 (Nested)" and check the console

I think what causes the bug is that the `ionTabBarChanged` event target is the window
https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/tab-button/tab-button.tsx#L80

**Comment by liamdebeasi** [comment]
Thanks for the issue. The underlying problem looks related to https://github.com/ionic-team/ionic-framework/issues/18197 so I will track progress there.
