### ISSUE TITLE
bug: ion-datetime emits blur twice

### ISSUE THREAD

**Issue by ehorodyski-ionic** [ionic-team/ionic-framework#22535]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When tapping an `ion-datetime` component, `ionBlur` gets emitted instantly, while the overlay comes into focus. Upon closing the `ion-datetime` component through any option (cancel, selection, backdrop tap) `ionBlur` is not emitted -- however it will emit again once (a) the overlay is closed and (b) any other portion of the screen is tapped.

**Expected behavior:**
It is expected that `ionBlur` would be emitted once the overlay has been closed, not when the parent field has lost focus.

**Steps to reproduce:**
Using the reproduction provided in "Related Code", once serving the application:

1. Tap the date field. Observe that `onBlur triggered` is printed to the console.
2. Dismiss the overlay by either cancelling or selecting a date.
3. Tap anywhere outside of the input field or button. Notice `onBlur triggered` is printed to the console again. 

**Related code:**

Reproduction: https://github.com/ehorodyski-ionic/fw-ng-datetime-blur-repro

**Other information:**

This observation has been made with `@ionic/angular`. 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.2 (/Users/eric/npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.0
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : 0.15.2
   native-run  : 1.2.2

System:

   NodeJS : v14.15.1 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Merging with https://github.com/ionic-team/ionic-framework/issues/16630.
