### ISSUE TITLE
BUG: ion-icon can not work well in ionic/vue

### ISSUE THREAD

**Issue by AlwaysLoveme** [ionic-team/ionic-framework#22538]
**Ionic version:**

[] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
i try to use ionic icon width vue, but it not worked

**Expected behavior:**
can use well

**Steps to reproduce:**

**Related code:**
```
<template>
 <!--can not show icon-->
 <ion-icon name="chevron-forward-outline"></ion-icon>
</template>
<script>
****
import {IonIcon} from '@ionic/vue';
export default defineComponent({
   components: {IonIcon }
})
</script>
```
![image](https://user-images.githubusercontent.com/29945352/99771282-d0c05180-2b43-11eb-8cae-48025ac16057.png)

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI       : 6.12.1 (/Users/zhuxian/.nvm/versions/node/v12.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.4

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : not installed

System:

   NodeJS : v12.19.0 (/Users/zhuxian/.nvm/versions/node/v12.19.0/bin/node)
   npm    : 6.14.8
   OS     : macOS Big Sur

```

**Comment by MarekGogol** [comment]
Hey,

I think you need use icons like that:

template:
<ion-icon :icon="checkmarkOutline"></ion-icon>

js:
import { checkmarkOutline } from 'ionicons/icons';

export default {
    setup(){
        return {
            checkmarkOutline,
        }
    },
...

**Comment by liamdebeasi** [comment]
Our documentation covers examples of this. Please see: https://ionicframework.com/docs/vue/quickstart#adding-icons

**Comment by AlwaysLoveme** [comment]
> Hey,
> 
> I think you need use icons like that:
> 
> template:
> `<ion-icon :icon="checkmarkOutline"></ion-icon>`
> 
> js:
> 
> ```
> import { IonIcon } from '@ionic/vue';
> import { checkmarkOutline } from 'ionicons/icons';
> 
> export default {
>     components: { IonIcon },
>     setup(){
>         return {
>             checkmarkOutline,
>         }
>     },
> ...
> ```
> 
> I was struggling why icons does not work as well, but then I find out...

thanks
