### ISSUE TITLE
Ionic-button "color" property binding with ternary operator is not working as expected

### ISSUE THREAD

**Issue by rygarok** [ionic-team/ionic-framework#22531]
**Ionic version:**
[] **4.x**
[X] **5.x**

**I'm submitting a ...** 

[X] bug report
[ ] feature request

**Current behavior:**

I am trying to dynamicly set the "color" property of a ion-button using a ternary operator.

When I simply do [color]="['light']", without any ternary operators, it works as expected. (The button is light)

But when I do the same with a ternary operator [color]="[router.url === '/profil/informations' ? 'primary' : 'light']", the color is not being applied, even though that when I inspect the page, it is set to "light". It is still using the default primary color even though it is "light"

**Expected behavior:**

If the ternary operator returns 'light', the button should be light. If it returns 'primary', it should be primary

**Steps to reproduce:**

Put any ternary operation (see my example above) to reproduce the bug

**Related code:**
```
  <ion-col size="4" class="amm-no-padding-right amm-no-border-radius">
    <ion-button [color]="[router.url === '/profil/informations' ? 'primary' : 'light']" class="amm-no-border-radius amm-full-width amm-font-small amm-font-bold">Informations</ion-button>
  </ion-col>
  <ion-col size="4" class="ion-no-padding amm-no-border-radius">
    <ion-button [color]="[router.url === '/profil/mot-de-passe' ? 'light' : 'light']" class="amm-no-border-radius amm-full-width amm-font-small amm-font-bold">Mot de passe</ion-button>
  </ion-col>
  <ion-col size="4" class="amm-no-padding-left" >
    <ion-button [color]="[router.url === '/profil/horaire/soumission' ||  router.url === '/profil/horaire/rdv' ? 'primary' : 'light']"  class="amm-no-border-radius amm-full-width amm-font-small amm-font-bold">Horaires</ion-button>
  </ion-col>
```

In the example above, all of the buttons are blue (primary color), when its clearly impossible for them to all have the "primary" color. I even did the ternary operator directly in the component.ts and its working just fine.

**Ionic info:** 
```
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\Dominic\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.4.3
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.0
   OS     : Windows 10


```

**Comment by liamdebeasi** [comment]
Can you reproduce this in an Ionic starter app? The code snippet you provided was not enough for me to reproduce the issue.

**Comment by rygarok** [comment]
My mistake.

I was using square brackets inside of the property binding, returning in a non-empty array, which always resulted to true.... 

Sorry about that! Just found out my mistake
