### ISSUE TITLE
bug: ion-item click event not triggering if item contains checkbox

### ISSUE THREAD

**Issue by luboslav** [ionic-team/ionic-framework#22557]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
ion-item click event not triggering if item contains ion-checkbox

**Expected behavior:**
click event should be triggered

**Steps to reproduce:**
[Stackblitz](https://stackblitz.com/edit/ionic-5-angular-10-start-template-6yzyzk?file=src/app/app.component.html)

**Other information**
It is a breaking change, it has worked in recent versions.

**Ionic info:**
ionic version: 5.5.0

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. Last good version was 5.4.4. Possibly related to https://github.com/ionic-team/ionic-framework/commit/7214a8401b709e1353155304cf6e9f97b2b4d294 but I have not confirmed that yet. cc @brandyscarney

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22561, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by liamdebeasi** [comment]
Hey there,

We discovered an issue with the fix in https://github.com/ionic-team/ionic-framework/pull/22561, so I reverted it. I am going to re-open this issue until we can implement a proper fix.

As a workaround for now, you can add `[button]="true"` to your `ion-item`:

```html
<ion-item [button]="true">
  <ion-checkbox></ion-checkbox>
</ion-item>

**Comment by liamdebeasi** [comment]
@brandyscarney was able to come up with another solution, so this will still be fixed in an upcoming release of Ionic Framework. Thanks!
