### ISSUE TITLE
bug: Seconds are not validated in ionic date time component

### ISSUE THREAD

**Issue by markgonz** [ionic-team/ionic-framework#22553]
# Bug Report

**Ionic version:**
5.4.13

**Current behavior:**
When setting min and max properties on the date time component, seconds are ignores. In my case I am using the date time component strictly for time. The user needs to be able to select hours, minutes and seconds within a specified range.

**Expected behavior:**
date time component account for min and max in the seconds column.

**Steps to reproduce:**
See Stackblitz sample below. Steps to reproduce are included in the sample.

[Stackblitz sample](https://stackblitz.com/edit/ionic-angular-v5-zwowdf?file=src%2Fapp%2Fapp.component.html)

**Ionic info:**
Ionic:

   Ionic CLI                     : 5.4.13 (/Users/mgonzalez/.nvm/versions/node/v10.18.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.2.2) : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/mgonzalez/Library/Android/sdk)
   NodeJS            : v10.18.0 (/Users/mgonzalez/.nvm/versions/node/v10.18.0/bin/node)
   npm               : 6.13.4
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C504

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this behavior. I am going to merge this with our datetime issue tracker here: https://github.com/ionic-team/ionic-framework/issues/16630.
