### ISSUE TITLE
bug: use ion-virtual-scroll together with ion-reorder-group

### ISSUE THREAD

**Issue by NLueg** [ionic-team/ionic-framework#22551]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.5.0**

**Current behavior:**
`ion-virtual-scroll` can't be used together with `ion-reorder-group`. After doing this as shown in the sample code this is the behavior:

![ezgif-3-7698bdbe18d1](https://user-images.githubusercontent.com/48101693/99926910-9cb37f00-2d43-11eb-8cd4-f89d73beb384.gif)

**Expected behavior:**

It should be possible to reorder the items even with the `ion-virtual-scroll` element.

**Steps to reproduce:**

**Related code:**

```html
<div *ngIf="listToShow$ | async as listToShow">
  <ion-virtual-scroll [items]="listToShow" [trackBy]="trackByFunction">
    <ion-reorder-group
      (ionItemReorder)="reorderCurrentStrategy($event)"
      *virtualItem="let item"
    >
		<!-- DO SOMETHING WITH THE ITEM -->

    </ion-reorder-group>
  </ion-virtual-scroll>
</div>
```

**Other information:**

https://forum.ionicframework.com/t/reorder-group-virtual-scroll-problem/190869

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.11 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.0
   @angular-devkit/build-angular : 0.1100.2
   @angular-devkit/schematics    : 11.0.2
   @angular/cli                  : 11.0.2
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.1
   native-run  : 1.2.1

System:

   Android SDK Tools : 26.1.1 (/Users/NLueg/Library/Android/sdk/)
   ios-deploy        : 1.10.0
   ios-sim           : ios-sim/9.0.0 darwin-x64 node-v12.18.3
   NodeJS            : v12.18.3 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. With upcoming major versions of Ionic Framework, we are going to be transitioning to using Angular's CDK Scroller. As a result, we have a freeze on new features and bug fixes on ion-virtual-scroll. See https://material.angular.io/cdk/scrolling/overview for how to get started with CDK Scroller. We are working on proper transition docs as well!
