### ISSUE TITLE
bug: ion-router-outlet triggers ngOnDestroy outside the Angular zone

### ISSUE THREAD

**Issue by kawazoe** [ionic-team/ionic-framework#22571]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

In an ionic angular application using the ion-router-outlet, navigating away from a page in a way that would trigger the ngOnDestroy lifecycle method on the page component will cause the method to be called outside of the angular zone.

This causes issues when using ngOnDestroy to unsubscribe from observables which have finalize clauses that require change detection. For instance, dispatching an NgRx action in a finalize clause will cause an error in such scenario unless it is wrapped with `ngZone.run()`.

**Expected behavior:**

The standard angular behavior is to run all lifecycle methods inside the angular zone. Swapping the ion-router-outlet for a angular router-outlet fixes this issue.

**Steps to reproduce:**
 

**Related code:**

See this repository for a repro project: https://github.com/imadh/ionic-router-outside-angular-zone

Simply navigate between the "hello" and "bye" pages multiple times to trigger the ngOnDestroy call. A console log will indicate if the method is called in the right zone.

**Other information:**

**Ionic info:**

```
Ionic:
   Ionic CLI                     : 6.10.1 (/home/imad/.nvm/versions/node/v10.21.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.0
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3
Capacitor:
   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3
Utility:
   cordova-res                          : not installed
   native-run (update available: 1.2.2) : 1.0.0
System:
   NodeJS : v10.21.0 (/home/imad/.nvm/versions/node/v10.21.0/bin/node)
   npm    : 6.14.4
   OS     : Linux 4.19
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Did you push your changes that show this bug happening? I cloned your repository, but it just looks like a blank Ionic starter app.

**Comment by kawazoe** [comment]
Oups! Sorry for that. It should be ok now.

**Comment by kawazoe** [comment]
@liamdebeasi any news on this? It's been 4 months already and this is a pretty big issue.

**Comment by malinges** [comment]
Yup, I just got bit by this bug once again, even though I know about it...

**Comment by sean-perkins** [comment]
Hello everyone! I have an open PR to address this problem.

In the interim, you can test with this dev build:
```
6.0.13-dev.11647460756.170a3672
```

Thanks!

**Comment by kawazoe** [comment]
While I'm no longer working on this project, I just looked at your PR and it looks like it should address the issue. Fantastic!
