### ISSUE TITLE
bug: ion-textarea + ion-label stacked = jumping when focus - strang height

### ISSUE THREAD

**Issue by ivanov84** [ionic-team/ionic-framework#22584]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When I press on ion-textarea height is jumping

**Expected behavior:**
When I press on ion-textarea height stays same

**Steps to reproduce:**
Press on ion-textare

**Related code:**
```
<ion-item>
            <ion-label position="stacked" color="primary">kuku kuku ku ku kuku kuku</ion-label>
            <ion-textarea autoGrow="true" rows="3" [placeholder]="textPlaceholder"></ion-textarea>
</ion-item>
```

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\Dmitriy\AppData\Roaming\npm\
node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.2.0
   @angular/cli                  : 10.2.0
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 7
```

![example](https://user-images.githubusercontent.com/9296077/100386383-3de95080-3036-11eb-9a81-578f8e1cc10c.gif)

Example:
https://olympapp.com/content/example.mp4

Source:
[kuku.zip](https://github.com/ionic-team/ionic-framework/files/5604687/kuku.zip)

**Comment by ivanov84** [comment]
Hello! Anyone here?

**Comment by liamdebeasi** [comment]
> Hello! Anyone here?

The team was out the past few days due to a US holiday.

Looks like this is related to the `autoGrow` property. Someone has already opened an issue for this, so I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/21242.
