### ISSUE TITLE
feat: Add a --white-space Custom CSS for ion-button

### ISSUE THREAD

**Issue by hildo** [ionic-team/ionic-framework#22585]
I am upgrading an app from Ionic 3 to 5.  In the app, we have code which uses an ion-button, but the CSS styling of the button set the white-space CSS attribute to normal.  This allowed the text in the button to wrap.

Since upgrading to Ionic 5, I am unable to style the button this way because it is in the Shadow DOM.  Currently, in button.scss, the value is set to nowrap (line 60).

Would it be possible to add a new variable (--white-space) which would allow applications to set this value?  I would be happy to have a crack at implementing this if people are happy with this request.

**Comment by hildo** [comment]
I would also need a similar custom CSS entry for text-align.   So if there are additional custom properties that people think should be added, this could be an opportunity to introduce them.

**Comment by hildo** [comment]
I have a pull request with what I think are the changes.  I'm 100% sure, though, so a review would be good.  I was able to build locally.

PR is https://github.com/ionic-team/ionic-framework/pull/22587

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. You can use CSS Shadow Parts to target the inner button:

```css
ion-button::part(native) {
  white-space: normal;
}
```

See https://ionicframework.com/docs/api/button#css-shadow-parts for more information.

**Comment by hildo** [comment]
Thanks for the help.  I will give that a try.
