### ISSUE TITLE
bug: Ionic vue router ignores navigation cancelation on onBeforeRouteLeave

### ISSUE THREAD

**Issue by NunoSav** [ionic-team/ionic-framework#22591]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
In some cases, if navigation is canceled in `onBeforeRouteLeave()` next time it actually goes back it skips at least one route (i guess it will skip as many as it were cancelled)

**Expected behavior:**
When navigation is halted keep the history stack as is.

**Steps to reproduce:**
Do the following actions:

1. Click "Go to page2"
2. Click "Go to page3"
3. Click on the `IonBackButton` element
4. Click on "Click here" alert button
5. Click on the `IonBackButton` element

**Related code:**
https://github.com/NunoSav/ionic-vue3-navigation-guards

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.12.2 (/Users/nur/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.1

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run (update available: 1.2.2)   : 1.2.1

System:

   NodeJS : v12.16.3 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.6.0-dev.202012031522.dc9faa6 @ionic/vue-router@5.6.0-dev.202012031522.dc9faa6
```

**Comment by NunoSav** [comment]
Seems to be working fine now 👍

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22621, and a fix will be available in an upcoming release of Ionic Framework.
