### ISSUE TITLE
bug: hardware back button doesn't pop navigation stack on android

### ISSUE THREAD

**Issue by nkCreation** [ionic-team/ionic-framework#22595]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Sometimes, I don't really know when, the back button suddenly crash and the navigation stack isn't popped out anymore when press the hardware back button. Happen randomly. No error in console.

**Expected behavior:**
Back button working great.

**Steps to reproduce:**
I can reproduce in my app but I haven't a process as it seems to appear randomly and no error is fired.
I've tried to bypass to initial event with subscribeWithPriority and do a navCtrl.pop() myself but the problem still happen after few navigation push/pop and less than a minute on the app.

**Other information:**
I'm on a Tabs app.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1100.2
   @angular-devkit/schematics    : 11.0.2
   @angular/cli                  : 11.0.2
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/**/Library/Android/sdk)
   NodeJS            : v14.13.1 (/usr/local/Cellar/node/14.13.1_1/bin/node)
   npm               : 6.14.8
   OS                : macOS Big Sur
   Xcode             : Xcode 12.2 Build version 12B45b
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
