### ISSUE TITLE
feat: provide angular test harness for all ionic components

### ISSUE THREAD

**Issue by DmitryEfimenko** [ionic-team/ionic-framework#22601]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
Interacting with components provided by Ionic in Unit Tests is not straight forward. Now that Angular provides all the tools needed to build a [Component Test Harnesses](https://medium.com/@mhamel06/component-test-harnesses-angular-9s-second-best-feature-4261cabedc77), it should be built and provided for all Ionic components.

**Describe Preferred Solution**
Component Test Harnesses provided for all Ionic components.

**Describe Alternatives**
n/a

**Related Code**
Here's an example of a component harness provided by the Angular Material team for the input element: https://material.angular.io/components/input/api#material-input-testing-classes

**Additional Context**
Here's [a very old issue](https://github.com/ionic-team/ionic-framework/issues/9622) that shows an example of someone struggling to do just that. I believe the solution provided in the referenced issue is not applicable anymore.

**Comment by liamdebeasi** [comment]
Thanks for the report. The team is evaluating feature requests and we would be interested in understanding your use case for this feature. You mentioned that there are some difficulties with testing Ionic components. Can you clarify what these are?
