### ISSUE TITLE
bug: click ion-item[href] don't work

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-framework#22603]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x** ( > 5.5.0）

**Current behavior:**
click ion-item[href] don't work（seems e.preventDefault())

**Expected behavior:**
click ion-item[href] work（jump to link URL）

**Steps to reproduce:**

**Related code:**
```
<ion-item href="https://ionicframework.com/docs">
  <ion-label>Ionic Framework</ion-label>
</ion-item>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1100.2
   @angular-devkit/schematics    : 11.0.2
   @angular/cli                  : 11.0.2
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.3

Utility:

   cordova-res (update available: 0.15.2) : 0.11.0
   native-run                             : not installed

System:

   NodeJS : v14.15.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app? `ion-item` with `href` is working fine for me: https://codepen.io/liamdebeasi/pen/PoGqxXM

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
