### ISSUE TITLE
bug: ionic react history.replace not working with hardware back button

### ISSUE THREAD

**Issue by qiluo** [ionic-team/ionic-framework#22611]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.5.1**

**Current behavior:**

I've built a simple app which contains a login page and a tabs layout. When navigated from login page to tabs, I called `history.replace('/tabs')` to clear history. In browser simulation, it worked as expected `/login` not in history, never went back to it. But on device, the hardware back button can still have me go back login page, the `history.replace` didn't work
**Expected behavior:**

**Steps to reproduce:**

https://github.com/qiluo/ionic-react-history-replace

Please check my demo

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.1

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.17.0 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this behavior. This should be fixed by https://github.com/ionic-team/ionic-framework/pull/22559.
