### ISSUE TITLE
bug: Navigating back to a page with refresher & segments breaks scrolling

### ISSUE THREAD

**Issue by AlanAcDz** [ionic-team/ionic-framework#22616]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Navigating back to a page that has an ion-refresher and ion-segments, breaks content scrolling on the page.

**Expected behavior:**

Content should still be scrollable after navigating back to the page with ion-refresher and ion-segments.

**Steps to reproduce:**

- Inside an Ionic Angular app, create a page that contains both ion-refresher and ion-segments
- Navigate to another page and back
- Pull to refresh
- Scrolling on that page is now broken

**Related code:**

[Sample app repo](https://github.com/AlanAcDz/ionic-segment-refresher)

The sample app was created with Ionic CLI using blank template

**Other information:**

Issue #22590 seems to be related. Although it lacks code reproduction, the issue seems to be encountered when refresher is toggled with ngIf. I did not test that but looks like the issue happens when refresher is repainted, either using ngIf like on that issue, or by navigating to the page like the issue I'm describing.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.2 (\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1100.3
   @angular-devkit/schematics    : 11.0.3
   @angular/cli                  : 11.0.3
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this behavior. I will work on a fix.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@5.6.0-dev.202012031726.dc9faa6
```

**Comment by AlanAcDz** [comment]
I can confirm that the dev build does solve the issue, thanks 👍

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22623, and a fix will be available in an upcoming release of Ionic Framework.
