### ISSUE TITLE
bug: ion-slides - options.initialSlide isn't working anymore

### ISSUE THREAD

**Issue by csaar95** [ionic-team/ionic-framework#22625]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
After the latest `npm update` the `initialSlides` option in IonSlides isn't working anymore for us.

**Expected behavior:**
`initialSlide` is set to the last slide of my slides array, these slide should be initialy shown.

**Steps to reproduce:**
Use IonSlides and set the `initialSlide` option to any value except 0.

**Related code:**
```typescript
    <IonSlides
      ref={slidesRef} scrollbar={true} options={slidesOptions} key={slidesData.length}
      onIonSlideDidChange={async() =>
        setActiveDate(slidesData[await slidesRef.current.getActiveIndex()]?.date)
      }>
      {slidesData.map((slide, i) => {
        return <Slide slide={slide} key={i} />;
      })}
    </IonSlides>
```

**Other information:**
I got following workaround, after `initialSlide` changes I manually slide to the desired slide.
```typescript
  useEffect(() => {
    if (slidesOptions.initialSlide) {
      slidesRef.current.slideTo(slidesOptions.initialSlide, 0, false);
    };
  }, [slidesOptions.initialSlide]);
```

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.6.0 (C:\Users\Christian\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.5.1

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.0.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Hey there, can you reproduce this in an Ionic starter app?

**Comment by csaar95** [comment]
I actually couldn't reproduce it with a starter app, there it's working fine.
A colleague broke the slides by doing some preparations for a Windows electron build, we'll try to reproduce this behaviour in the starter app. Let you know if we finished.

**Comment by adityasingh0208** [comment]
Hi,

There is a bug in 5.5.1 version, I recently upgrade the package from 5.3.5 to 5.5.1 in my app which is in production and the ion-slides page went blank without throwing any errors in the console, reverting the package worked as normal. Not sure how to debug the issue without any helpful error logs.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
