### ISSUE TITLE
bug: IonReactRouter - Each route is rendering twice

### ISSUE THREAD

**Issue by Toto5931** [ionic-team/ionic-framework#22622]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] @ionic/react 5.5.1

**Current behavior:**
I am currently chassing the re-renders since it make my application very slow
I noticed that In a blank Ionic application, each route is rendered twice

**Expected behavior:**
Each page should render only once 

**Steps to reproduce:**
1. Create a new app using the ionic starter: ionic start myApp blank --type react
2. Add a console.log in the Home tab

**Related code:**
```
<IonApp>
      <IonReactRouter>
        <IonRouterOutlet>
          <Route path="/home" component={Home} exact={true} />
        </IonRouterOutlet>
      </IonReactRouter>
    </IonApp>
```

**Other information:**
This problem is similar to this one: https://github.com/ionic-team/ionic-framework/issues/21635 but the solutions do not work for me:
- Not passing the props this way: <Route path="/home" render={() => <Home/>} exact={true} /> does not change anything
- I can't memoize my <Home> component  since it will fetch data from an API at each render and could change from one render to an other

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.5.0 (C:\Users\zorro\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.5.1

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

Thanks

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am able to reproduce the behavior you are describing, but I am not sure that this is necessarily a bug in Ionic React. Your components are going to get rendered if they receive new props or if their parent component renders. In your original post you mention that an app you are working on is very slow. Can you provide an example of that app? Without an example I am not able to determine where the slow down might be coming from.
