### ISSUE TITLE
feat: Tabs without the same parent URL-part

### ISSUE THREAD

**Issue by PatrickG** [ionic-team/ionic-framework#22628]
# Feature Request
Provide a way for tabs that don't need the same parent URL-part.

**Ionic version:**
[x] **5.x** (react)

**Describe the Feature Request**
Currently page-transition animations are broken when using tabs that do not have the same parent URL-part.

Works:
```jsx
// App.jsx
<Route path="/tabs" component={Tabs} />

// Tabs.jsx
<Route path="/tabs/tab1" component={Tab1} />
<Route path="/tabs/tab2" component={Tab2} />
...
```

Broken page-transition animations:
```jsx
// App.jsx
<Route path="/:tab(tab1|tab2)" component={Tabs} />

// Tabs.jsx
<Route path="/tab1" component={Tab1} />
<Route path="/tab2" component={Tab2} />
// or
<Route path="/:tab(tab1)" component={Tab1} />
<Route path="/:tab(tab2)" component={Tab2} />
...
```

**Describe Preferred Solution**
Even better would be, if one tab could be at the root:
`/`, `/tab2`, ...

**Describe Alternatives**
None.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Could you provide a GitHub repo that shows this issue happening?
