### ISSUE TITLE
bug: native refresher does not reset styles from non-native refresher

### ISSUE THREAD

**Issue by R4yYx** [ionic-team/ionic-framework#22636]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When I'm using an Ion-List together with the refresher I am no longer able to scroll through the list filled with items.

Without refresher:
![image](https://user-images.githubusercontent.com/48794718/101453365-8276c500-392f-11eb-906e-76c8bd87bcbe.png)

With refresher:
![image](https://user-images.githubusercontent.com/48794718/101453372-87d40f80-392f-11eb-8823-d97ca89bc6f8.png)

**Expected behavior:**
You should be able to still scroll and use the refresher.

**Steps to reproduce:**
Can be reproduced using this [sample app](https://github.com/R4yYx/IonicPullRefreshRepro). Have Ion-Items in Ion-List and add the refresher. Try scrolling through the items with the refresher enabled, you will notice it won't scroll nor show that there even is anything to scroll on the right side. Take the refresher out and scrolling works again.

**Related code:**

https://github.com/R4yYx/IonicPullRefreshRepro

Refresher and item list:

```
<ion-content>

    <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
        <ion-refresher-content></ion-refresher-content>
    </ion-refresher>

    <ion-list>
        <ng-container *ngIf="(samples | async) as items">
            <ion-item *ngFor="let item of items">
                <ion-label class="unselectable">FOO:</ion-label>
                <ion-label class="unselectable">{{item.foo}}</ion-label>
            </ion-item>
        </ng-container>
    </ion-list>

</ion-content>
```

**Other information:**

The fix from https://github.com/ionic-team/ionic-framework/issues/22616 in @ionic/angular@5.6.0-dev.202012031726.dc9faa6 was tested too and did not fix this issue.

**Ionic Info:**

Ionic:

   Ionic CLI                     : 6.12.2 (C:\Users\Marvin.Havel\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1100.3
   @angular-devkit/schematics    : 11.0.3
   @angular/cli                  : 11.0.3
   @ionic/angular-toolkit        : 3.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 9 other plugins)

Utility:

   cordova-res : 0.15.2
   native-run  : 1.2.2

System:

   Android SDK Tools : 26.1.1 (C:\Users\Marvin.Havel\AppData\Local\Android\Sdk)
   NodeJS            : v14.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.8
   OS                : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22640, and a fix will be available in an upcoming release of Ionic Framework.
