### ISSUE TITLE
bug: material ion-refresher does not have a dark mode

### ISSUE THREAD

**Issue by ycintre** [ionic-team/ionic-framework#22637]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When using a dark mode by following the [doc](https://ionicframework.com/docs/theming/dark-mode), the `ion-refresher` for material design keeps a light theme rather than having a custom dark theme.
![image](https://user-images.githubusercontent.com/1143138/101488893-7bb47600-3960-11eb-81d9-fd6b5a7b75f5.png)

**Note: the issue does not appear on iOS design as the ion-refresher is completely different**

**Expected behavior:**
All basic components should have a dark theme variant

**Steps to reproduce:**
- Bootstrap an app
- Setup a dark mode following the [doc](https://ionicframework.com/docs/theming/dark-mode) 
- Add an [`ion-refresher`](https://ionicframework.com/docs/api/refresher) on a page
- Use material design 
- Pull down on the page

**Related code:**
Demo available here: https://stackblitz.com/edit/ionic-angular-v5-hpsehd
Just pull down on the page

**Other information:**
I'll submit a PR with a fix shortly

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.1100.3
   @angular-devkit/schematics    : 11.0.2
   @angular/cli                  : 11.0.3
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (/usr/local/bin/node)
   npm    : 6.14.9
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22639, and a fix will be available in an upcoming release of Ionic Framework.
