### ISSUE TITLE
bug: ion-page turning invisible when changing its css class to any value

### ISSUE THREAD

**Issue by larsblumberg** [ionic-team/ionic-framework#22631]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.5.1**

**Current behavior:**
When changing the css class of ion-page to any value, ionic adds `ion-page-invisible` which renders the page invisible.  

**Expected behavior:**
`ion-page-invisible` should not be added to list of style classes when changing a page's classes.

**Steps to reproduce:**

1. Set up a page inside `IonReactRouter`
2. Assign any class value to an `ion-page`'s style/classes attribute and display the page
3. Change the class attribute dynamically, i.e via button press 

**Related code:**

https://github.com/larsblumberg/ionic-invisible-page

```
const App: React.FC = () => (
  <IonApp>
    <IonReactRouter>
      <IonRouterOutlet>
        <Route path="/" component={Page} />
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
);

const Page: React.FC = () => {
  const [styleClass, setStyleClass] = useState('initial-class')
  return (
    <IonPage className={styleClass}>
      <IonContent>
        <IonButton onClick={() => setStyleClass('other-class')}>Add Class</IonButton>
      </IonContent>
    </IonPage>
  );
};
```

**Other information:**

Bug doesn't manifest if page is used outside (without) `IonReactRouter`.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.1 (/Users/lars/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.1

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v15.2.1 (/usr/local/Cellar/node/15.2.1/bin/node)
   npm    : 7.0.10
   OS     : macOS Catalina
```

**Comment by evgeniyefimov** [comment]
I have the same issue on angular project.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22666, and a fix will be available in an upcoming release of Ionic Framework.
