### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by HStokbro** [ionic-team/ionic-framework#22630]
# Feature Request

**Ionic version:**

[x] **5.5.1**

**Describe the Feature Request**

Allow for padding around checkbox checkmark.
This is how a big checkbox looks now: 
<img width="76" alt="Screenshot 2020-12-07 at 12 05 20" src="https://user-images.githubusercontent.com/1279879/101343637-97e2e500-3884-11eb-987c-ca27a32d39da.png">

This is the desired look:
<img width="68" alt="Screenshot 2020-12-07 at 12 05 30" src="https://user-images.githubusercontent.com/1279879/101343670-a3cea700-3884-11eb-8d17-1b4104e43528.png">

**Describe Preferred Solution**

We would like a variable for setting the padding on .checkbox-icon
It could be named --checkmark-padding
And used like so:
--checkmark-padding: 3px;

**Describe Alternatives**

Temporarily as a workaround. I have set the --border-width to 4px when checked to add extra spacing around checkmark. When using this approach the animation looks funny. The border grows until filled. I then set transition to none to remove animation. This is a workaround.

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. You can use the `container` CSS Shadow Part to add the style you want.

CodePen Example: https://codepen.io/liamdebeasi/pen/RwGRabO
Here is a list of the CSS Parts for `ion-checkbox`: https://ionicframework.com/docs/api/checkbox#css-shadow-parts
Here is an explainer on what CSS Shadow Parts are: https://ionicframework.com/docs/theming/css-shadow-parts

**Comment by HStokbro** [comment]
Awesome!! Thx
