### ISSUE TITLE
bug: ion-tab cannot be dynamically generated based on the array

### ISSUE THREAD

**Issue by yinglight** [ionic-team/ionic-framework#22646]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When tab uses an array, as shown below 
![image](https://user-images.githubusercontent.com/31800146/101565582-4c594400-3a08-11eb-8a97-42262e1c24ae.png)

![image](https://user-images.githubusercontent.com/31800146/101565546-3481c000-3a08-11eb-8b9a-8e2bf0c78ef3.png)
Then an error

![image](https://user-images.githubusercontent.com/31800146/101565480-161bc480-3a08-11eb-9001-450ea58df7d0.png)

When the version of "@ionic/vue" is greater than 5.4.1, an error is reported.
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

![image](https://user-images.githubusercontent.com/31800146/101565383-e7055300-3a07-11eb-9815-ea17061891fa.png)

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
