### ISSUE TITLE
bug: ion-textarea autoGrow=“true” works only the first time

### ISSUE THREAD

**Issue by majorbenks** [ionic-team/ionic-framework#22647]
# Bug Report

**Ionic version:**
5.4.2 and 5.5.1

**Angular version:**
10.2.2

**Current behavior:**
We use iontextarea inside a portal (https://material.angular.io/cdk/portal/overview) and also inside a ionmodal und it seems that we have the same issue as in https://github.com/ionic-team/ionic-framework/issues/18993 again: the size is only set the first time. The second time the size is ether not set at all (inside ionmodal) or is way to big (inside portal). 
Interestingly everything works fine with version 5.1.0.

**Expected behavior:**
iontextarea should grow every time it is displayed.

**Steps to reproduce:**
Open a modal with a iontextarea several times.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
