### ISSUE TITLE
bug: ionic vue navigating to the same page with a different parameter should still result in a transition

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-framework#22662]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Given a route of `/page/:id`, going from `/page/1` to `page/2` does not result in a nav transition. The new page content simply appears.

**Expected behavior:**

I would expect that there is a nav transition.

**Related code:**

We need to implement the following logic in Ionic Vue, similar to how Ionic React does it: https://github.com/ionic-team/ionic-framework/blob/91aaaab71a0df2feaec0b8edd94755fe5e733aee/packages/react-router/src/ReactRouter/StackManager.tsx#L166-L175

```
insert short code snippets here
```

**Other information:**

See: https://github.com/ionic-team/ionic-framework/issues/22658#issuecomment-743266142 and https://github.com/ionic-team/ionic-framework/issues/22658#issuecomment-743266142

**Comment by boboldehampsink** [comment]
+1

**Comment by beneverard** [comment]
On top of the details I added in #22931, I'm also finding that the component `$route` object always reflects the current route, and not the route that spawned the component. 

This is to say that components that remain mounted for ease of state management ([according to Ionics docs](https://ionicframework.com/docs/react/navigation#ionrouteroutlet)) are susceptible to their base data changing, and in my case, this causes errors as the component relies on route metadata that is incorrectly changed.

Note in this screenshot (details of this example in #22931) that the main `/home` component is populated with route information from the active `/message` component.

I hope this adds some more context to the bug, as before I assume this is related and will continue to add any nuances I discover.

![Screenshot 2021-02-19 at 10 42 53](https://user-images.githubusercontent.com/84081/108494271-3afda500-729f-11eb-8c53-362409052074.png)

**Comment by wsamoht** [comment]
Does anyone know of a workaround for this? I am having the issue mentioned in #22931 where I am navigating to the same route with different parameters but the content doesn't change (the URL does).

**Comment by GC-Mark** [comment]
> Does anyone know of a workaround for this? I am having the issue mentioned in #22931 where I am navigating to the same route with different parameters but the content doesn't change (the URL does).

Depending if you want a page transition or not (this example won't), we had to watch for changes of the route parameters along the lines of this...

```js
const route = useRoute();
let id = route.params.id

watchEffect(() => {
  if (route.params.id != id) {
    // trigger page refresh/trigger payload refresh
  }
});
```

(i don't have access to my actual code at the moment, but that was roughly the gist of it)

**Comment by wsamoht** [comment]
Awesome, thanks! Your code sparked a solution for me. I had already converted `router-link` to a `click` event on the button trying to figure out a solution. I just added updating my data properties with the new route parameters. Why I didn't think of that originally I don't know :) I have computed properties that are loading the data from Vuex with the data properties.

```javascript
<ion-button @click="navigateToLesson(trackId, previousLessonId)">Previous</ion-button>
<ion-button @click="navigateToLesson(trackId, nextLessonId)">Next</ion-button>
```

```javascript
async navigateToLesson(trackId: number, lessonId: number): Promise<void> {
    await this.$router.push({
        name: 'tabs.training.study.lesson',
        params: { trackId: trackId, lessonId: lessonId },
    })

    this.trackId = parseInt(this.$route.params.trackId.toString())
    this.lessonId = parseInt(this.$route.params.lessonId.toString())
}
```

**Comment by ryoji-sagara** [comment]
Request:
I've been using the `/page/:id` setting when transitioning from `/page/1` to `page/2`.
I'm looking for a way to not refresh the data on the same page.
I would like it to behave like an application that generates the page DOM of `/page/2` independently of the page DOM of `/page/1` and also has page transition animation.
Or is there a way to do that?

**Comment by GC-Mark** [comment]
@liamdebeasi I don't want to be one of _those_ people, but I was wondering if there is any progress on this issue. Seems like very common use case, and one that we come up against again and again.

Thanks

**Comment by liamdebeasi** [comment]
I do not have an update, but I have added to our v6 milestone.

**Comment by GC-Mark** [comment]
Thanks, i had a stab at making a fix this morning, but it got the point where I had to start cloning pages and I quickly got out of my depth.

Will keep an eye out for the fix 👍

**Comment by liamdebeasi** [comment]
Hi everyone,

I have a fix for this in https://github.com/ionic-team/ionic-framework/pull/23525 and will likely merge the PR tomorrow. I have included a dev build below for anyone who would like to test. 

Please note that this is a Framework v6 dev build and is subject to the breaking changes noted in https://github.com/ionic-team/ionic-framework/blob/next/BREAKING.md#version-6x. This fix depends on a change made in Ionic Vue v6 and cannot be easily backported to v5, so this is going to be a v6-only fix.

```
npm install @ionic/vue@6.0.0-dev.202106291310.379deca @ionic/vue-router@6.0.0-dev.202106291310.379deca
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23525, and a fix will be available in an upcoming release of the Ionic Framework v6 beta.
