### ISSUE TITLE
feat: ion-radio with icon placeholder

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#22669]
# Feature Request

**Ionic version:**

[x] **5x**

**Describe the Feature Request**

 I would like to have custom icon instead of radio with that i do not have to deal with state. Currently i am dealing with selected Index + ion-item ion-icon slot start

![image](https://user-images.githubusercontent.com/23274631/102006124-a0d02c80-3d44-11eb-9b17-1463c141bfc6.png)

**Describe Preferred Solution**

 `icon` placeholder on ion-radio element

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I think this use case may be out of scope for what `ion-radio` should handle. My main concern with this is changing the radio to display a custom icon removes any indication that the component is a radio, which may result in a poor user experience.

It might make sense to make this a custom component in your app where the component internally deals with a simple state (active button/item). That way you can deal with state once and then abstract away the rest of the details.

**Comment by indraraj26** [comment]
I agree with you. Lets stick with state.
