### ISSUE TITLE
bug: Ion-menu + Ion-content not rendering on v-if change

### ISSUE THREAD

**Issue by danisaurio** [ionic-team/ionic-framework#22672]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Using `v-if` to conditionally display `ion-menu`. When `true`, `ion-menu` is not shown on desktop views (works ok on mobile)

**Expected behavior:**

The `ion-menu` should display when `v-if` is set to true on desktop views

**Steps to reproduce:**

Anything rendered inside `ion-menu` and/or `ion-content`  will never be displayed on desktop view even though `v-if` becomes true

**Related code:**

_side-menu.vue_
```
<template>
    <ion-menu content-id="main-content" type="overlay" v-if="loggedUser">
      <ion-content>
          <p>"I'm not showing if loggedUser changes from false to true!!"</p>
      </ion-content>
    </ion-menu>
</template>

<script lang="ts">
import { IonContent, IonMenu } from '@ionic/vue';
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'SideMenu',
  components: {
    IonContent, 
    IonMenu, 
  },
  computed:{
    loggedUser(){
      return user.isLogged()
    }
  },
});
</script>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.2 (/Users/danielavidal/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.1

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.3 (/Users/danielavidal/.nvm/versions/node/v12.18.3/bin/node)
   npm    : 6.14.6
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
