### ISSUE TITLE
bug: modal doesn't work with vuejs

### ISSUE THREAD

**Issue by gnunicorn** [ionic-team/ionic-framework#22685]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
I want to show a modal using my vue (4) app. It is declared as the documentation show:
```vue
    <ion-modal :is-open="openTrigger">
      <h1>Content</h1>
    </ion-modal>
```

when the `openTrigger` switches to `true`, the modal animates in, but it keeps animation over and over again, blocking the browser from being usable. A look into the inspector reveals the modal is added over and over again...

![image](https://user-images.githubusercontent.com/40496/102349735-14bc4000-3fa4-11eb-868d-b5459549516b.png)

**Expected behavior:**
One modal is added to the view, only that shows up and the browser can be used.

**Other information:**
Using ionic-vue
```json
{
  "dependencies": {
    "@capacitor/core": "2.4.3",
    "@ionic/vue": "^5.5.2",
    "@ionic/vue-router": "^5.5.2",
    "core-js": "^3.6.5",
    "ionicons": "^5.2.3",
    "parse": "^2.18.0",
    "vue": "^3.0.4",
    "vue-router": "^4.0.1",
    "vuex": "^4.0.0-rc.2"
  },
}
```

Testing with `firefox`:

```
Name 	Firefox
Version 	84.0b4
Build ID 	20201122235112
Distribution ID 	Manjaro
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
OS 	Linux 5.9.11-2-MANJARO #1 SMP PREEMPT Tue Nov 24 15:40:17 UTC 2020
```

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/home/ben/.nvm/versions/node/v10.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.2

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.18.1 (/home/ben/.nvm/versions/node/v10.18.1/bin/node)
   npm    : 6.14.8
   OS     : Linux 5.9
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
