### ISSUE TITLE
bug: Ionic View Event Lifecycle firing 3 times | Vue 

### ISSUE THREAD

**Issue by HakobiDev** [ionic-team/ionic-framework#22688]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
In Ionic Framework Lifecycle Methods describe the alternative for some missing vue 3 lifecycle hooks apparently when the navigation to specific page that have Ion Lifecycle it firing 3 times instead of once. In browser it seems fine.

**Expected behavior:**
Firing Ion Lifecycle once in combination of capacitor js to prevent resource usage abuse.

**Steps to reproduce:**
To reproduce just create a very simple blank vue project(Standard) and add ionViewDidEnter or other lifecycle described here : [Docs](https://ionicframework.com/docs/vue/lifecycle#ionic-framework-lifecycle-methods) in about.vue and create an apk from it.

**Related code:**
```
  ionViewDidLeave() {
    try {
      StatusBar.setStyle({ style: StatusBarStyle.Light });
    } catch (err) {
      console.log("This does not have influence on the browser", err);
    }
  },
  ionViewDidEnter() {
    try {
      StatusBar.setStyle({ style: StatusBarStyle.Dark });
    } catch (err) {
      console.log("This does not have influence on the browser", err);
    }
  },
```

**Other information:**
Video Demonstration: [Demo](https://streamable.com/6imd96)

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.12.2 (C:\Users\Nic\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.5.2

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Utility:

   cordova-res : not installed
   native-run  : 1.2.2

System:

   NodeJS : v14.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10
```

EDIT: Video Link fixed

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter application and provide a link to the repo? Also, the video link you sent does not seem to be correct (doesn't load any video).

**Comment by HakobiDev** [comment]
Sure. In addition to confirm ionViewWillLeave and ionViewWillEnter are only causing this multiple fire of events.

**Comment by HakobiDev** [comment]
Closed due to self solve the issue there is nothing issue about Ionic and its own lifecycle event hooks it is problem with capacitor and I recently update the capacitor wrapper and works fine..
