### ISSUE TITLE
bug: IonInput of type password does not recognize autofill of credentials by iOS Password Manager

### ISSUE THREAD

**Issue by phal0r** [ionic-team/ionic-framework#22682]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x** (Ionic React 5.5.2)

**Current behavior:**
Given a simple form with 2 IonInput elements (user/password login). It can be set up to be recognized by iOS Password Manager to fill in credentials from iOS Keychain. 

Input elements are actually filled with data, BUT the IonInput of type password does not recognize the changed value of the underlying native html input element. This can be visually seen as the delete input element is not shown. Also when reading the value from IonInput it is just empty.

*Current workaround:* On form submit, I get the value from the underlying native html input, which is correctly set and works without a problem.

**Expected behavior:**
When values are set programmatically by iOS Password Manager, the value should be reflected in the IonInput element.

**Steps to reproduce:**
- Basic IonPage with a form and 2 IonInput (user/password login)
- Build the App for iOS and deploy an a device
- autofill credentials from iOS Password Manager 
- value of IonInput of password is empty, while value of html input of password contains the correct value

Important: This is not related to other issues, where problems with iOS Password Manager and nesting with IonItem are reported. This is not the case here.

**Related code:**

I am not sure, if a sample makes sense here, as it can only be reproduced on the device running in WKWebView.

My basic form:
```
<form onSubmit={handleSubmit} autoComplete="on" ref={formRef}>
          <IonInput
            autocomplete="username"
            type="text"
            value={userId !== '' ? userId : undefined}
            clearInput
            name="userId"
            required
          />
          <IonInput
            autocomplete="current-password"
            type="password"
            value={password !== '' ? password : undefined}
            clearInput
            name="password"
          />

          <IonButton
            color="secondary"
            size="large"
            type="submit"
            expand="full"
          >
              Submit
          </IonButton>
</form>
```

**Comment by BerkeAras** [comment]
@phal0r Could you check if the input in IonInput (ShadowDOM) has the autocomplete attribute

**Comment by phal0r** [comment]
@BerkeAras 
I use the above markup and I get the button for the password manager, when I focus user or password input, so it works. Also both native input fields are filled correctly, that means everything is set up properly. It is just, that the IonInput does not get the notification, that its underlying html input field changed the value - and it is only broken for the password field, it works for the user input field. 

I don't know, how IonInput internally detects changes of the underlying native input field, but it is broken for password fields when filled programmatically by iOS Password Manager. 

Accessing the native input fields works and they are properly filled with the correct values.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
