### ISSUE TITLE
Ionic Platform Backbutton firing multiple times.

### ISSUE THREAD

**Issue by nomanshahsyed** [ionic-team/ionic-framework#22686]
# Bug Report

**Ionic version:**

[x] **5.5.2**

**Current behavior:**

The back button fires multiple times.

**Expected behavior:**

It should only fire once.

**Steps to reproduce:**

In app.components.ts put the back button code in the constructor.

```
this.platform.backButton.subscribe((clicked) => {
    console.log("back clicked", clicked);
});
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.2 (C:\Users\noman.shah\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.2
[native-run] Installing platforms\android\app\build\outputs\apk\debug\app-debug.apk...
[native-run] Starting application activity com.linkdesign.linkeazy/com.linkdesign.linkeazy.MainActivity...
[native-run] Run Successful
PS C:\Users\noman.shah\Documents\LinkEazy\Nomi\LinkEazy> ionic info

Ionic:

   Ionic CLI                     : 6.12.2 (C:\Users\username\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, android 8.1.0, browser
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.3.0) : 0.2.7

System:

   NodeJS : v10.15.2 (C:\Program Files\nodejs\node.exe)
   npm    : 4.6.1
   OS     : Windows 10```

**Comment by nomanshahsyed** [comment]
@liamdebeasi I cant simulate this issue as it is only Android hardware back button issue.

**Comment by liamdebeasi** [comment]
Can you reproduce the issue in an Ionic starter application? I have an Android device I can test it on.

**Comment by nomanshahsyed** [comment]
Hi, ok i started a new Ionic project and added the platform button code and i only see it firing once. I wonder why is it firing multiple times in my app. I just checked that in my app, on the first page it fires twice. If i navigate to page two it fires thrice and so on. Do you have any idea as to why it is happening?

**Comment by liamdebeasi** [comment]
It's hard to say without seeing your application code. It sounds like you are re-subscribing to the hardware back button event every time you navigate, which would explain why the callback fires multiple times.

I am going to close this as this is more of a support question, but if you are still trying to figure out why this is happening I recommend opening an issue on our forums: http://forum.ionicframework.com/. Thanks!
