### ISSUE TITLE
feat: attach overlay to specific component 

### ISSUE THREAD

**Issue by BorjaFTW** [ionic-team/ionic-framework#22689]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
Allow to attatch loading overlay to specified component or DOM element

**Additional Context**
I want to put a loading just covering a container, but I don't want to lock all the screen.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe your use case in more detail? Also, if you could provide a code example of what you are trying to accomplish that would be helpful.

**Comment by BorjaFTW** [comment]
Hi @liamdebeasi ,
I want to create a loader but only it apply to specified component/element.

Example:

```
 async presentLoadingWithOptions(cmp?: any) {
    const loading = await this.loadingController.create({
      spinner: null,
      duration: 5000,
      message: 'Click the backdrop to dismiss early...',
      translucent: true,
      cssClass: 'custom-class custom-loading',
      backdropDismiss: true,
      component: cmp ? cmp : undefined
    });
    await loading.present();
}
```

With a similar code, the loading overlays only the specified component. Allowing the user to interact with other components  located at the same page.

Thanks.

**Comment by conde2** [comment]
I also need this feature. It will help me pass my services (instantiated within components) to the modal properly.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/24198 as they are the same request (just with different overlay components).
