### ISSUE TITLE
bug: Input won't get focused if you click icon inside button/input on Android

### ISSUE THREAD

**Issue by 1x2x3x4x** [ionic-team/ionic-framework#22691]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Same issue as here: https://github.com/ionic-team/ionic-framework/issues/21509

If I go back to  @ionic/angular@5.3.2 works as expected. Only fails under Android. Works perfectly on latest version of iOS.

**Expected behavior:**

If I tap on an icon that's inside an input, it should focus the input, just like the fixes from @5.3.2

input: properly focus the input when clicking the item padding in WebKit (#21930) (e4964ff), closes #21509
input: remain focused in the input after pressing the clear button (#21985) (6878fb9), closes #21549

**Steps to reproduce:**

**Related code:**

```
            <ion-input type="{{type}}" [(ngModel)]="user.password" (keyup)="checkPasswordMatch($event);" 
                <button *ngIf="showPass" ion-button clear type="button" slot="end" (click)="showPassword()">
                    <ion-icon name="eye-off-sharp"></ion-icon>
                </button>
            </ion-input>
     
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.803.27
   @angular-devkit/schematics    : 10.1.3
   @angular/cli                  : 8.3.27
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-webview 5.0.0, (and 16 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.1.0

System:

   Android SDK Tools : 26.1.1 (Android\Sdk)
   NodeJS            : v14.15.1 (nodejs\node.exe)
   npm               : 6.14.9
   OS                : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
