### ISSUE TITLE
ion-input getting disabled for no apparent reason

### ISSUE THREAD

**Issue by EricDriussi** [ionic-team/ionic-framework#22698]
**Ionic version:**

[x] **4.x**
[ ] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

Basically [this](https://github.com/ionic-team/ionic-framework/issues/13414#issuecomment-344359225). I have a login page with a couple of basic ion-inputs. Everything works the first time but after I logout it doesn't allow me to click on them. Does work if you tab into them but that is not helpful as an android app.
It behaves just the same in brave, firefox, chromium and android hardware.

**Expected behavior:**

Inputs working?

**Steps to reproduce:**

Not quite sure. The inputs per se follow the structure below and I just use @angular/router to jump in and out from the login view. Nothing special really.

```
        <ion-item>
            <ion-label position="floating">Contraseña:</ion-label>
            <ion-input type="password" [(ngModel)]="pwd"></ion-input>
        </ion-item>

```

**Ionic info:** 

```

Ionic:

   Ionic CLI                     : 6.12.3 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.5
   @capacitor/core : 2.4.5

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   Android SDK Tools : 26.1.1 (/home/USER/Android/Sdk/)
   NodeJS            : v15.4.0 (/usr/bin/node)
   npm               : 6.14.8
   OS                : Linux 5.9
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter application and provide a link to the GitHub repo?

**Comment by EricDriussi** [comment]
Thanks for the reply!
Unfortunately I can't. The code I'm working with is kind of a mess and its login process is connected to firebase.
I thought my set up might be causing it but I guess its just crappy code...

Sorry about that.

**Comment by liamdebeasi** [comment]
Without a reproduction I probably won't be able to fix the issue. Are you able to create a minimal reproduction in the app you are working on?

**Comment by EricDriussi** [comment]
Nevermind, I just realized (while trying to reproduce it with minimal code) the issue only appears to happen when I navigate to that page using th side menu. So clearly it's not an issue with ion-input. 
I'm closing as it seems like I misjudged the issue. Thanks again!
