### ISSUE TITLE
bug: ionic react back button does not show up when going back to child page in tab

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/ionic-framework#22692]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
The back button is not displayed after navigating back to a tab where the back button was previously visible. This happens with `@ionic/react-router` v5.3.0 and onwards up to the latest v5.5.2.

Please [watch this video](https://youtu.be/WYLIzkeAllA) to see exactly what's happening.

**Expected behavior:**
The back button should still be visible, like it used to work until v5.2.3 of `@ionic/react-router`.

**Steps to reproduce:**
Please use this [sample application](https://github.com/mirkonasato/ionic-react-router-back-button) and follow the same steps shown in the video.

**Related code:**

https://github.com/mirkonasato/ionic-react-router-back-button

**Other information:**
The [changelog](https://github.com/ionic-team/ionic-framework/blob/master/CHANGELOG.md#530-phosphorus-2020-07-23) mentions a "new react router" was introduced in v5.3.0.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/home/mirko/.nvm/versions/node/v14.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.1 (/home/mirko/.nvm/versions/node/v14.15.1/bin/node)
   npm    : 6.14.9
   OS     : Linux 5.8
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/react@5.7.0-dev.202103181349.8ac4d12 @ionic/react-router@5.7.0-dev.202103181349.8ac4d12
```

**Comment by mirkonasato** [comment]
Yes that works thanks

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23069, and a fix will be available in an upcoming release of Ionic Framework.
