### ISSUE TITLE
bug: es2015 dfChildren exception

### ISSUE THREAD

**Issue by mluis** [ionic-team/ionic-framework#22690]
# Bug Report

**Ionic version:**

[x ] **4.x**
[] **5.x**

**Current behavior:**

I have a toastController inside a Modal. It is just thrown as soon as toastController calls presentToast.
**Expected behavior:**

Not to have the exception thrown.
**Steps to reproduce:**

**Related code:**
Related issue [19442](https://github.com/ionic-team/ionic-framework/issues/19442) of the ionic framework.

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 9 other plugins)

Utility:

   cordova-res (update available: 0.15.2) : 0.9.0
   native-run (update available: 1.3.0)   : 0.2.9

System:

   Android SDK Tools : 26.1.1 (/Users//Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.0
   NodeJS            : v13.2.0 (/usr/local/bin/node)
   npm               : 2.15.12
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
