### ISSUE TITLE
bug: toastController.dismiss() throws an error if no toast is displayed

### ISSUE THREAD

**Issue by hankhester** [ionic-team/ionic-framework#22704]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Calling toastController.dismiss() when there is no toast displayed throws this error: `Uncaught (in promise) overlay does not exist`

**Expected behavior:**

Calling toastController.dismiss() when there is no toast displayed does nothing and doesn't throw an error.
In my case I want to automatically dismiss any previous toast before I show a new one, and calling dismiss before displaying any toast is the simplest way of doing that.

**Steps to reproduce:**

- `ionic start myApp blank --type react`
- Add the following code to App.tsx:
```ts
import { toastController } from '@ionic/core'
toastController.dismiss()
```
This will throw the following error:
`Uncaught (in promise) overlay does not exist`

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.16 (/Users/hankhester/.npm/_npx/864a9e3c2cd0cf50/node_modules/ionic)
   Ionic Framework : @ionic/react 5.5.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v15.3.0 (/usr/local/bin/node)
   npm    : 7.0.14
   OS     : macOS Big Sur
```

**Comment by DwieDima** [comment]
you can do following:

```
presentNewToastAndDismissActive() {

    const toast = await this.toastController.create({
      header: 'some header',
      message: 'some message',
      position: 'top',
      color: 'primary',
      duration: 2000,
    });

    const active = await this.toastController.getTop();

    if(active) {
      await active.dismiss();
    }

   return toast.present();

}
```

**Comment by hankhester** [comment]
Ah thanks! That totally works, I'll close this issue
