### ISSUE TITLE
bug: Alerts does not position relatively to keyboard on Android

### ISSUE THREAD

**Issue by somq** [ionic-team/ionic-framework#22707]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Alerts does not position relatively to keyboard on Android
Related to #19561 & #21924 but #19561 PR does not fix the issue (at least on Android, untested on iOS)

**Expected behavior:**
If an input is focused, the keyboard should open and the alert should move above the keyboard

**Steps to reproduce:**
Create an alert with an input and tap the input.

**Related code:**

An implementation of [this gist](https://gist.github.com/Manduro/bc121fd39f21558df2a952b39e907754) fixes the issue as a workaround

Relevant code

```ts
  private onShow(e) {
    let keyboardHeight: number = e.keyboardHeight || (e.detail && e.detail.keyboardHeight);
    this.setElementPosition(keyboardHeight);
  };

  private onHide() {
    this.setElementPosition(0);
  };

  private setElementPosition(pixels: number) {
    this.elementRef.nativeElement.style.paddingBottom = pixels + 'px';
    this.content.resize();
  }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI : 6.12.1

Utility:

   cordova-res : 0.15.2
   native-run  : 1.2.2

System:

   NodeJS : v12.14.0
   npm    : 6.14.8
   OS     : Linux 5.4
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
