### ISSUE TITLE
Keyboard flicker 

### ISSUE THREAD

**Issue by ashish3303** [ionic-team/ionic-framework#22708]
Hello, 

I am working on an issue regarding keyboard flicker, I used checkboxes under the ion-search bar. Please check the attached video about the issue. 

ionic version 3.20.0

Thanks 
[RPReplay-Final1608296803.MP4.zip](https://github.com/ionic-team/ionic-framework/files/5722600/RPReplay-Final1608296803.MP4.zip)

**Comment by BerkeAras** [comment]
@ashish3303 Could you reproduce this with a repository? And for the next time: Use the issue templates.
