### ISSUE TITLE
bug: "cannot bind to undefined" error in SSR

### ISSUE THREAD

**Issue by signuspl** [ionic-team/ionic-framework#22709]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When running the app with SSR you get error in the console window:
```
TypeError: Cannot read property 'bind' of undefined
    at hydrateFactory (...\dist\app\server\main.js:169296:36)
    at render (...\dist\app\server\main.js:196485:9)
    at ...\dist\app\server\main.js:196417:62
    at new ZoneAwarePromise (...\dist\app\server\main.js:441505:33)
    at hydrateDocument (...\dist\app\server\main.js:196409:33)
...
```
This error produce app in the SSR but without Ionic components hydrated into the code. This is visible when you disable JavaScript to test app.

**Expected behavior:**
Application in the SSR should generate without this error and should have Ionic components hydrated even if JavaScript is disabled.

**Steps to reproduce:**
Please run Ionic - Side-Menu or Tabs starter template app in SSR with latest ionic-angular (v. >= 5.4.2). Then start `npm run dev:ssr`. After that visit page at `http://localhost:4200` you will get this error.

**Related code:**
This error didn't show in `Ionic` versions `< 5.4.2`. The problem is in the `hydrateFactory` function on the server side code and this cause the problem with rendering of the Ionic components. You may find this function in `node_modules/@ionic/core/hydrate/index.js`
```
function hydrateFactory($stencilWindow, $stencilHydrateOpts, $stencilHydrateResults, $stencilAfterHydrate, $stencilHydrateResolve) {
...
var fetch = $stencilWindow.fetch.bind($stencilWindow);
...
}
```
This error means that `$stencilWindow.fetch` is `undefined`. 

**Other information:**
The simple solution is to comment this line and the app in SSR start working as expected - Ionic components are hydrated without any problems with JavaScript disabled.

**Ionic info:**
```
Ionic:

   Ionic CLI                     : 6.12.3
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : android 8.1.0, electron 2.0.0
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (c:\Users\signu\AppData\Local\Android\android-sdk)
   NodeJS            : v14.15.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.9
   OS                : Windows 10
```

**Comment by mhartington** [comment]
Can you provide a sample repo please? SSR has a lot of moving parts and a repo helps reduce errors in trying to replicate the issue.

**Comment by nirajhinge** [comment]
@mhartington Not the same poster but I have had the exact same issue for which I created a [repo here](https://github.com/nirajhinge/ionic-ssr) if that helps.

**Comment by signuspl** [comment]
> Can you provide a sample repo please? SSR has a lot of moving parts and a repo helps reduce errors in trying to replicate the issue.

@mhartington Very sorry for my late answer! This is the [sample repository](https://github.com/signuspl/ionic-5-ssr-issue) based on the Ionic Split-Pane starter template + Angular Server Side Rendering.

When you install it and call: `npm run dev:ssr` 
Then go to: `http://localhost:4200`

After page load you will see the error in terminal: `TypeError: Cannot read property 'bind' of undefined`
Also when you disable javascript in browser you will see that this error make the SSR page blank.

In the issue report you may see what line of code cause this error. I hope this will help you fix it!
Thank you!

**Comment by Cafnio** [comment]
Also had this problem (which was blocking rendering SSR with javascript disabled). 

Saw this post which allowed me to temporarly fix it. 

https://forum.ionicframework.com/t/ionicservermodule-cannot-read-property-bind-of-undefined/201545/2

**Comment by signuspl** [comment]
> Also had this problem (which was blocking rendering SSR with javascript disabled).
> 
> Saw this post which allowed me to temporarly fix it.
> 
> https://forum.ionicframework.com/t/ionicservermodule-cannot-read-property-bind-of-undefined/201545/2

Thanks @Cafnio that I could help you. This forum post is also mine :)

**Comment by Cafnio** [comment]
> 
> 
> > Also had this problem (which was blocking rendering SSR with javascript disabled).
> > Saw this post which allowed me to temporarly fix it.
> > https://forum.ionicframework.com/t/ionicservermodule-cannot-read-property-bind-of-undefined/201545/2
> 
> Thanks @Cafnio I am glad that I could help you. This forum post is also mine :)

Ohh! Didn't saw the user names! Thanks a lot! :)

**Comment by mhartington** [comment]
Thanks for the repo to look at. I can replicate the issue so I'll circle back with the team.

**Comment by gopi-hl** [comment]
> > > Also had this problem (which was blocking rendering SSR with javascript disabled).
> > > Saw this post which allowed me to temporarly fix it.
> > > https://forum.ionicframework.com/t/ionicservermodule-cannot-read-property-bind-of-undefined/201545/2
> > 
> > 
> > Thanks @Cafnio I am glad that I could help you. This forum post is also mine :)
> 
> Ohh! Didn't saw the user names! Thanks a lot! :)

Is the workaround here to modify inside of the node_modules? How will that work though? It's not like we check it in. So it will keep getting replaced with the real version from the package.

**Comment by signuspl** [comment]
> > > > Also had this problem (which was blocking rendering SSR with javascript disabled).
> > > > Saw this post which allowed me to temporarly fix it.
> > > > https://forum.ionicframework.com/t/ionicservermodule-cannot-read-property-bind-of-undefined/201545/2
> > > 
> > > 
> > > Thanks @Cafnio I am glad that I could help you. This forum post is also mine :)
> > 
> > 
> > Ohh! Didn't saw the user names! Thanks a lot! :)
> 
> Is the workaround here to modify inside of the node_modules? How will that work though? It's not like we check it in. So it will keep getting replaced with the real version from the package.

Unfortunately yes. I know it is temporary and will be replaced by any update of @ionic/core module but since you want to use Ionic version >= 5.4.2 with SSR feature this is the only solution I have found. That is the reason of this issue report and we just need to wait for the fix in future versions.

**Comment by mhartington** [comment]
We've isolated the issue and are just waiting to update a few deps. Will post when it is addressed.

**Comment by Cafnio** [comment]
> 
> 
> > > > Also had this problem (which was blocking rendering SSR with javascript disabled).
> > > > Saw this post which allowed me to temporarly fix it.
> > > > https://forum.ionicframework.com/t/ionicservermodule-cannot-read-property-bind-of-undefined/201545/2
> > > 
> > > 
> > > Thanks @Cafnio I am glad that I could help you. This forum post is also mine :)
> > 
> > 
> > Ohh! Didn't saw the user names! Thanks a lot! :)
> 
> Is the workaround here to modify inside of the node_modules? How will that work though? It's not like we check it in. So it will keep getting replaced with the real version from the package.

Downgrade the version of ionic to 5.4.1 if you need to send it to production server

**Comment by gopi-hl** [comment]
Awesome. That works!


    "@ionic/core": "5.4.1",
    "@ionic/angular": "5.4.1",
    "@ionic/angular-server": "5.4.1",

**Comment by agalper** [comment]
> We've isolated the issue and are just waiting to update a few deps. Will post when it is addressed.

Any update on the fix for this?

**Comment by mhartington** [comment]
This will be part of the next minor release, 5.6.

**Comment by signuspl** [comment]
> This will be part of the next minor release, 5.6.

@mhartington is it possible that [https://github.com/ionic-team/ionic-framework/issues/21394](this issue) will also be fixed? At this moment we use SSR only for SEO-bots because of this page flickering - loading page for regular user takes longer time with SSR than without it and with this flickering SSR for regular user makes no sense. Thank you in advance for your answer.

**Comment by signuspl** [comment]
@mhartington & @liamdebeasi Thank you very much for your efforts! Version 5.6 seems to solve this problem. I tested on my application and if no one objects to it, we can close this issue :)
