### ISSUE TITLE
bug: Selecting a radio button using spacebar scrolls to end of page. 

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#22716]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Selecting a radio button using spacebar scrolls to end of page. 

**Expected behavior:**
Would not scroll to end

**Related code:**

https://github.com/ionic-afl/ionic-v5-observations.git

1. Run in a iPhone emulation mode or some other small form factor so you cannot actually view the whole app at once.
2. refresh to ensure nothing is selected
3. tab to the radio area
4. press spacebar

Once the space bar is pressed, you will have selected the first radio button, but you will have also scrolled to the bottom of the page.

**Comment by liamdebeasi** [comment]
Here is a dev build if anyone would like to test:

```
npm install @ionic/angular@5.6.0-dev.202102081600.32cdca5
```

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/22892.
