### ISSUE TITLE
Ionic Datetime hour scroll error

### ISSUE THREAD

**Issue by winglovecola** [ionic-team/ionic-framework#22710]
**Ionic version:**
[] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
the hour jump back to the top when trying the scroll to a expected value

**Expected behavior:**
the hour shouldn't have jump back to the top

**Steps to reproduce:**
open ionic date picker and scroll the hour down 

<ion-datetime #dateTime  displayFormat="hh:mm" pickerFormat="h:mm"  hourValues="1, 2, 19, 20, 21" minuteValues="0,5,10,15,20,25,30,35,40,45,50,55"  doneText="Set"></ion-datetime>
</ion-item>

**Ionic info:** 

Ionic:

   Ionic CLI                     : 6.11.11 (C:\Users\Wing He\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1100.5
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 10.1.4
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.9
   OS     : Windows 10

**Comment by 1x2x3x4x** [comment]
Same thing as here? If so, try downgrading to 5.3.2 and see if that helps.

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this issue. I have added this issue to our datetime bug tracker here: https://github.com/ionic-team/ionic-framework/issues/16630.
