### ISSUE TITLE
[React]: IonIcon name 

### ISSUE THREAD

**Issue by ShaMan123** [ionic-team/ionic-framework#22726]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
The same as #18847

**Expected behavior:**
The same as #18847

**Steps to reproduce:**
The same as #18847

**Suggested Fix:**

```
import { IonIcon } from '@ionic/react';
import _ from 'lodash';
import React, { memo } from "react";

export const Icon = memo(({ name, icon, ...props }: Parameters<typeof IonIcon>[0]) =>
    <IonIcon
        {...props}
        icon={icon || name && require('ionicons/icons')[_.camelCase(name)]}
    />
);
```

**Other information:**

**Ionic info:**

```
N/A
```

**Comment by rgoldiez** [comment]
See this thread and comment in particular: https://github.com/ionic-team/ionic-framework/issues/22181#issuecomment-699533699
