### ISSUE TITLE
bug: No ESLint configuration found

### ISSUE THREAD

**Issue by simobit** [ionic-team/ionic-framework#22723]
# Bug Report

**Ionic version:**
**5.x**

**Current behavior:**
```ionic serve``` -> It prevents me to continue my app because the error appears on the page (build error)

i did a mac update (from High Sierra to Big Sur) and randomly this error started popping up

![Schermata 2020-12-28 alle 12 56 22](https://user-images.githubusercontent.com/75187932/103213020-b9c40a80-490c-11eb-902b-2953c01d7199.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
