### ISSUE TITLE
bug: enterkeyhint attribute doesn't work on iOS devices

### ISSUE THREAD

**Issue by NickSklA** [ionic-team/ionic-framework#22729]
# Bug Report
I am trying to use enterkeyhint attribute to specify the action label for the "Enter" key. Although it works fine for Android devices, it doesn't seem to work at all for iOS devices. 

I have tried all the accepted values ([enterkeyhint Standard](https://html.spec.whatwg.org/dev/interaction.html#input-modalities:-the-enterkeyhint-attribute)) but it always shows the "return" label.

 

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Action label for "Enter" key is always "return" regardless of the enterkeyhint attribute.

**Expected behavior:**
Action label for "Enter" key should be able to change through the enterkeyhint attribute.

**Steps to reproduce:**

- Start a new Ionic blank app with Angular & Capacitor
- Replace the home.page.html code with the following code snippet
- Build the app
- Add the iOS platform
- Open the app with an iOS emulator

**Related code:**

_home.page.html_
```
<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-title>
      Blank
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">Blank</ion-title>
    </ion-toolbar>
  </ion-header>

  <div id="container">
    <ion-item>
      <ion-label>Search</ion-label>
      <ion-input enterkeyhint="search"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Go</ion-label>
      <ion-input enterkeyhint="go"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Send</ion-label>
      <ion-input enterkeyhint="send"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Send</ion-label>
      <ion-input enterkeyhint="send"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Done</ion-label>
      <ion-input enterkeyhint="done"></ion-input>
    </ion-item>
  </div>
</ion-content>
```

**Other information:**

<img src="https://user-images.githubusercontent.com/25327910/103408718-67812480-4b6c-11eb-89bd-bcd3bc0b9dab.png" width="400">

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.5
   @capacitor/core : 2.4.5

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What version of iOS are you testing this on? `enterkeyhint` is only supported on iOS 13.4+.

**Comment by NickSklA** [comment]
It works as expected on iOS 13.4+. Thank you!
