### ISSUE TITLE
Cannot use IonReactMemoryRouter in testing

### ISSUE THREAD

**Issue by baldoalessandro** [ionic-team/ionic-framework#22735]
As mentioned here by @elylucas there is a problem with `IonRouterOutlet` in JSDOM
https://github.com/ionic-team/ionic-framework/blob/67b0853b28f117f35f558993be87186ca548130b/packages/react-router/src/__tests__/Router.spec.tsx#L10-L15

Does anybody has a workaroud for this. I'm trying to use `IonReactMemoryRouter` to test the logic in the component life-cycle hooks but the router outlet is just empty.

I would like to fix this but I'm not sure were to start.

**Comment by elylucas** [comment]
Hi @baldoalessandro,

Check out this article and see if it points you in the right direction: https://ionicframework.com/blog/testing-ionic-react-apps-with-jest-and-react-testing-library/.

I need to revisit it overall as its been a year and web component support might be good now in JSDom.

**Comment by baldoalessandro** [comment]
Thank you for the article, it is really helpful in showing how to test a component  using Ionic components.
I don't know if I got your point correctly, but as far I can see the mocks provided by `ion-react-test-utils` will only mock some UI components https://github.com/ionic-team/ionic-react-test-utils/blob/master/src/mocks/mockIonicReact.ts not the Router.

What I'm trying to achieve is something like this https://reactrouter.com/web/guides/testing

```jsx
<IonReactMemoryRouter history={history}>
  <IonRouterOutlet>
    <Route path="/" exact >
      {children}
    </Route>
  </IonRouterOutlet>
</IonReactMemoryRouter>
```
This renders to in JSDOM:

```html
<body>
  <div>
    <ion-router-outlet />
  </div>
</body>
```

While using the `MemoryRouter` from `react-router-dom` like so:

```jsx
<MemoryRouter>
  <IonRouterOutlet >
    <Route path="/" exact >
      {children}
    </Route>
  </IonRouterOutlet>
</MemoryRouter>
```
renders:

```html
<body>
  <div>
    <ion-router-outlet>
      <div class="ion-page">
        <p>
          Test component
        </p>
      </div>
    </ion-router-outlet>
  </div>
</body>
```
which is the expected output. The only problem is that this way the life-cycle hooks are not triggered at all.

Let me know if this makes sense to you and if I can help out troubleshoot this issue.
Thank you 👍

**Comment by Eliasvdb** [comment]
Any update on this? I am also experiencing issues unit testing an Ionic React App because the lifecycle hooks are not executed. I see this as a possible solution but I am experiencing the same behaviour as explained above where the outlet does not render the route using IonReactMemoryRouter.

**Comment by tijp** [comment]
As an ugly hack you could mock the lifecycle hooks yourself. I wanted to test some of my code in the `useIonViewDidEnter` hook, so I created a mock for it in my `setupTests.ts` file.

This executes the `useIonViewDidEnter` hook the first render for every test;
```
// Mocking useIonViewDidEnter to run every first render
let mockFirstRender: boolean;
beforeEach(() => (mockFirstRender = true));
jest.mock('@ionic/react', () => ({
  __esModule: true,
  ...jest.requireActual('@ionic/react'),
  useIonViewDidEnter: (callback: any) => {
    if (mockFirstRender) {
      callback();
      mockFirstRender = false;
    }
  },
}));
```

**Comment by liamdebeasi** [comment]
Hi everyone,

Does this issue reproduce with the latest version of Ionic React?
