### ISSUE TITLE
bug: Dynamically changing color to IonRange with dual knobs on Vue, sets value to NaN

### ISSUE THREAD

**Issue by luismartin** [ionic-team/ionic-framework#22731]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
An IonRange with dual knobs. It must go from red, if the upper-lower knobs value is lower than 25, to green, as their distance in between becomes longer.
The issue appears when the component is assigned a new color via the computed property. Then, both `event.detail.value.upper` and `event.detail.value.lower` are **NaN** despite the knobs remain on their position.

**Expected behavior:**
It should change the color as the specified thresholds are reached.

**Steps to reproduce:**
You just have to select and drag a knob away from the other until you reach the point when the event handler changes the component to a new color.

**Related code:**

```
<template>
   <ion-range
                    min="0" max="100"
                    dualKnobs="true" pin="true"
                    snaps="true" step="1"
                    ticks="false" value="0"
                    :color="percentLevel"
                    @ionChange="changeRange($event)">
                </ion-range>
</template>

<script>
import { IonItem, IonRange } from '@ionic/vue';
export default {
    components: {
        IonItem, IonRange
    },
    data() {
        return {
            percent: 0,
        }
    },
    methods: {
        changeRange(event) {
            this.percent = event.detail.value.upper - event.detail.value.lower; 
        }
    },
    computed: {
        percentLevel() {
            if (this.percent >= 75) {
                return 'success';
            }
            if (this.percent >= 50) {
                return 'primary';
            }
            if (this.percent >= 25) {
                return 'warning';
            }
            return 'danger';
        }
    }
}
</script>
```

**Other information:**

[https://forum.ionicframework.com/t/possible-bug-in-ion-range-with-vue/201960](https://forum.ionicframework.com/t/possible-bug-in-ion-range-with-vue/201960
)
**Ionic info:**

```
$ ionic info

Ionic:

   Ionic CLI       : 6.12.2 (C:\Users\tiger\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.5.0

Capacitor:

   Capacitor CLI   : 2.4.3
   @capacitor/core : 2.4.3

Utility:

   cordova-res : 0.15.2
   native-run  : 1.2.2

System:

   NodeJS : v12.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.6.0-dev.202101072104.07f95db @ionic/vue-router@5.6.0-dev.202101072104.07f95db
```

**Comment by luismartin** [comment]
Perfect! Now it works. Smooth as silk.
Thank you!

**Comment by liamdebeasi** [comment]
Great! I am going to keep this issue open until I can get https://github.com/ionic-team/ionic-framework/pull/22745 merged in.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22745, and a fix will be available in an upcoming release of Ionic Framework.
