### ISSUE TITLE
feat: add showClearIcon prop for ion-searchbar

### ISSUE THREAD

**Issue by jonathon-m** [ionic-team/ionic-framework#22738]
# Feature Request

**Ionic version:**
[x] 5.x 

**Describe the Feature Request**
`ion-searchbar` clear icon is currently only visible when focused, but when filtering a list of results it is useful to clear without clicking in the text field first.

**Describe Preferred Solution**
Add a property to the component `showClearIcon` with possible values that mirror `showCancelButton` (e.g. "always" | "focus" | "never") and defaulting to "focus" to keep current behavior.

**Comment by perifer** [comment]
I can’t find any examples in apps on iOS where the clear button is hidden on blur. Can this maybe be changed without introducing a new setting?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22759, and a fix will be available in an upcoming release of Ionic Framework.
