### ISSUE TITLE
bug: Cannot unselect radio button with space bar with allowEmptySelection true

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#22734]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Using an ion-radio-group with allowEmptySelection set to "true", a user is able to unselect via touch and via mouse click, but cannot unselect via spacebar. This causes issues for a11y.

https://ionicframework.com/docs/api/radio-group#properties

**Expected behavior:**
When allowEmptySelection is "true" the user should be able to both select and unselect with a spacebar.
When allowEmptySelection is "false" (or unspecified), the user should only be able to select via spacebar.

**Related code:**

https://github.com/ionic-afl/ionic-v5-observations

**Comment by liamdebeasi** [comment]
The problem here appears to be that the click handler is set on `ion-radio-group`, so when you click or tap a radio, the radio group click event handler fires. When you are focused on an `ion-radio` and press Space, the group's click handler does not fire.
