### ISSUE TITLE
bug: ion-fab position  vertical="center" is not correct on dir="rtl"

### ISSUE THREAD

**Issue by timsar2** [ionic-team/ionic-framework#22739]
# Bug Report

**Ionic version:**
[x] **5.2.3**

**Current behavior:**

ion-fab RTL not align in ios devices also for me in firefox but it is ok in android and chrome.
ion-fab RTL position end will put ion-fab to the right side instead of left side.
**Expected behavior:**

**Steps to reproduce:**

**Related code:**
`ion-fab.fab-horizontal-end{
        right: unset;
        left: calc(10px + var(--ion-safe-area-right, 0px));
    }`

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

Code reproduction: https://codepen.io/liamdebeasi/pen/porzjqm

**Comment by timsar2** [comment]
it's ok

**Comment by timsar2** [comment]
also if you set horizontal center it'll not align center because of  scroll bar width.
positioning left 50% calculate without scrollbar so ion-fab will not align center.
it is ok when I set direction: ltr for ion-fab or hole page.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26986, and a fix will be available in Ionic Framework v7.
