### ISSUE TITLE
bug: Floating label color is wrong when input is empty - it shoud have placeholder color (gray) instead of main input color (black)

### ISSUE THREAD

**Issue by MaximS** [ionic-team/ionic-framework#22753]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Floating label color is wrong when input is empty (black in default color scheme). It's the same as input color making a label indistinguishable from input value.

**Expected behavior:**
Floating label color when input is empty should be like placeholder color (gray in default color scheme).

**Steps to reproduce:**
[https://ionicframework.com/docs/api/input](https://ionicframework.com/docs/api/input) - see Floating Label in "phone view"

Any temporary workaround is welcome. For some reason it's impossible to address the label color using css depending on ion-item .has-value class.

**Comment by MaximS** [comment]
Adequate css should bprobably be:

```
.item.item-label-floating:not(.item-has-value):not(.item-has-focus) ion-label.sc-ion-label-md-h {
    color: var(--ion-color-medium);
}
```

But adding it to Angular component scss doesn't help because it gets overriden by inline css style in the generated html.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/19619. We are working on updating our inputs to match the latest MD spec.
