### ISSUE TITLE
bug: Time in ion-datetime is not visible if current value is before min value and time format is 12-hour

### ISSUE THREAD

**Issue by dzNavitski** [ionic-team/ionic-framework#22756]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Time in ion-datetime is not visible if current value is before min value and time format is 12-hour

**Expected behavior:**
Time in ion-datetime is visible if current value is before min value and time format is 12-hour

**Steps to reproduce:**
1. set `pickerFormat` to `'M/D/YY h:mm A'`
2. set value before min value
3. open datetime picker

**Related code:**

https://stackblitz.com/edit/ionic-datepicker-issue?file=pages/home/home.ts

```
public date = "2021-01-06T12:59:00+03:00";

<ion-datetime [displayFormat]="'M/D/YY h:mm A'"
                [pickerFormat]="'M/D/YY h:mm A'"
                [(ngModel)]="date"
                [min]="'2021-01-06T17:08:00+03:00'"
                [max]="'2026-01-06T17:08:59+03:00'"></ion-datetime>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The StackBlitz you posted used Ionic Framework v3, but we do not support that version anymore. Is this still an issue with Ionic Framework v5? Here is a v5 StackBlitz you can use: https://stackblitz.com/edit/ionic-5-angular-10-start-template-79kd5c

**Comment by dzNavitski** [comment]
Sorry for the incorrect example. Unfortunately the same result with Ionic v5. Please check StackBlitz:
https://stackblitz.com/edit/ionic-5-date-time-issue?file=src%2Fapp%2Ftab1%2Ftab1.page.ts

**Comment by liamdebeasi** [comment]
Thanks. Can you clarify what the expected behavior is? Are you expecting the hour/minute values to show up just with the minimum hour and minute selected?

**Comment by dzNavitski** [comment]
Yes, it looks like min hour/minute values should be selected when the value is before min. In 24-hour format it works this way. Also, I mention that hour/minute values are don't selected even if the valid value is provided. Without min prop the ion-datetime works as expected.
Please check https://stackblitz.com/edit/ionic-5-date-time-issue-valid-value?file=src%2Fapp%2Ftab1%2Ftab1.page.html

**Comment by liamdebeasi** [comment]
I agree that this is a bug in `ion-datetime`. I am going to log the issue in our datetime tracker here: https://github.com/ionic-team/ionic-framework/issues/16630

Thanks!
