### ISSUE TITLE
bug: Keychain autofill doesn't sets blurred fields properly

### ISSUE THREAD

**Issue by PozaTR** [ionic-team/ionic-framework#22757]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **@ionic/vue 5.4-0**

**Current behavior:**
Having a simple ion-page component with two separate ion-input fields, one used as username and the other as password, when the user fulfills on an iOS device from the account keychain, even when both credentials values seems to be fulfilled into DOM, only the focused field receives its value properly.
As it seems, is the same behavior of this closed issue a week ago without answer https://github.com/ionic-team/ionic-framework/issues/22682#issue-767393319

**Expected behavior:**
When the user selects a credential pair from the keychain, both values should be accessible on the page.

**Steps to reproduce:**
Common steps:
- Create a simple ion- page with two ion-input elements and a form element wrapping them up.
- First of them with autocomplete attribute set to "username" the other one to "current-password".
- Build de app, launch it to an iOS device.

Case 1:
- Focus on username input.
- Select Keychain icon on native keyboard.
- Choose a credential pair.
- Both inputs seems to be fulfilled (password shows as many dots as length the password has).
- Submit the form.
- Username has value, password is empty.

Case 2:
- Focus on password input.
- Select Keychain icon on native keyboard.
- Choose a credential pair.
- Both inputs seems to be fulfilled (password shows as many dots as length the password has).
- Submit the form.
- Username is empty, password has value.

**Related code:**

```
<template>
  <ion-page class="login">
    <form class="test-form login__form" @submit.prevent="onSubmit" novalidate>
      <div class="test-form__field">
        <ion-label class="test-form__label" for="name">
          Username
        </ion-label>
        <p class="test-form__error" v-if="validateForm?.userName?.$errors[0]?.$message">Required field</p>
        <ion-input class="test-form__input" type="text"  id="username" autocomplete=“username” placeholder="Username" v-model="validateForm.userName.$model"/>
      </div>
      <div class="test-form__field">
        <ion-label class="test-form__label" for="password">
          Password
        </ion-label>
        <p class="test-form__error" v-if="validateForm?.password?.$errors[0]?.$message">Required field</p>
        <ion-input class="test-form__input" type="password" id="password" autocomplete="current-password" placeholder="Password" v-model="validateForm.password.$model"/>
      </div>
      <ion-button class="test-form__button" type="submit" color="secondary">Send</ion-button>
    </form>
  </ion-page>
</template>

<script lang="ts">
import { useStore } from "vuex";
import { IonPage, IonLabel, IonInput, IonButton } from "@ionic/vue";
import { toRef, reactive } from "vue"
import { useRouter } from 'vue-router';
import { useVuelidate } from "@vuelidate/core";
import { required } from "@vuelidate/validators";

export default  {
  name: 'Login',
  components: {
    IonPage,
    IonLabel,
    IonInput,
    IonButton
  },
  setup() {
    const store = useStore();
    const form = reactive({
      userName: '',
      password: '',
    })
    const formRules = {
      userName: { required },
      password: { required }
    }

    const validateForm = useVuelidate(formRules, {
      userName: toRef(form, 'userName'),
      password: toRef(form, 'password')
    })

    const router = useRouter();

    const methods = {
      onSubmit: async () => {

        validateForm.value.$touch();
        const password = (document.getElementById('password') as HTMLInputElement).value;
        alert(password) // Empty on case 1
        const userName = (document.getElementById('username') as HTMLInputElement).value;
        alert(userName) // Empty on case 2
        form.userName = userName;
        form.password = password;
        alert("Form Submitted " + JSON.stringify(form, null, 2))

        if (!validateForm.value.$invalid) {
          try {
            await store.dispatch('auth', form)
            await router.push({ name: 'profile' })
          } catch(error) {
            alert(error)
          }

        }
      }
    }

    return {
      validateForm,
      ...methods
    }
  },
  ionViewDidEnter() {
    document.getElementById('password')?.addEventListener('change', event => {
      // It gets triggered on both cases, but the event.currentTarget.value is empty on case 1
      setTimeout(() => {
        // Trying to re-render view
        (this as any).$forceUpdate();
      }, 0)
    })
  }
}
</script>
```

**Other information:**
Related issue: https://github.com/ionic-team/ionic-framework/issues/22682

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo? I cannot reproduce this on my end.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
