### ISSUE TITLE
bug: Cannot set property 'innerText' of null at animateLargeTitle (only iOS)

### ISSUE THREAD

**Issue by Fernito69** [ionic-team/ionic-framework#22760]
#Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Getting an error when navigating from one page to another and both pages have a `ion-title` with `size="large"` on them. It only happens in iOS.
Screenshot: https://www.dropbox.com/s/so1f3uxh4p0mgda/ion-title-error.png?dl=0

**Expected behavior:**
The error shouldn't happen.

**Steps to reproduce:**
1) Use the sample app in this repo: https://github.com/Fernito69/ion-title-error/
2) Turn on the device mode on Chrome devtools and select an iOS device.
3) Click on the "go to next page" link and look at the console, you should get the error.

**Related code:**
https://github.com/Fernito69/ion-title-error/

**Other information:**
This issue was documented before, but it seems that it wasn't solved: https://github.com/ionic-team/ionic-framework/issues/20730
As mentioned, the error only happens in iOS. The error seems to go away when I add `slot="end"` to the "IonButtons" component in Page.tsx. 

**Ionic info:**
Ionic:

   Ionic CLI       : 6.11.0 (C:\Users\Feño\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.5.2

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22762, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by Fernito69** [comment]
Wow, that was quick! Thanks a lot! :)

**Comment by Fernito69** [comment]
@liamdebeasi just to have an idea, is there already a scheduled date for the next release? Thanks in advance!

**Comment by liamdebeasi** [comment]
No specific date, but I am trying to get an update out in the next 2 weeks.

**Comment by Fernito69** [comment]
@liamdebeasi thanks for the answer! Just one last question: is there a way to make use of the fix not having to wait for the release?

**Comment by liamdebeasi** [comment]
Yes! Here is a development build. It has the latest code in `master` (including this issue's fix). I wouldn't recommend going to production with it, but it should be fine for development:

```
npm install @ionic/react@5.6.0-dev.202101151418.14e8441 @ionic/react-router@5.6.0-dev.202101151418.14e8441
```

**Comment by Fernito69** [comment]
Excellent! Thanks a lot, I really appreciate your help!
