### ISSUE TITLE
feat: ionic vue composition lifecycle hooks

### ISSUE THREAD

**Issue by sniii** [ionic-team/ionic-framework#22769]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
Ionic lifecycle methods still not available as Vue Composition API functions, despite claims made in merged feature request #22440. 

**Describe Preferred Solution**
Ionic lifecycle methods are currently only accessible when using the Vue options API, but for those of us coding using the Composition API and thus relying on the setup() function, these methods are not available as composition equivalents.

**Related Code**
```javascript
<script lang="ts">
export default defineComponent({
  setup() {
      // a normal Vue lifecycle hook method
      onMounted(() => {
          // ...
      })

     // the Ionic specific lifecycle methods should always be available to access inside the setup function
     ionViewWillEnter(() => {
         // ...
     })
   }
})
</script>
```

**Additional Context**
See: https://v3.vuejs.org/guide/composition-api-lifecycle-hooks.html

**Comment by liamdebeasi** [comment]
The lifecycle hooks were indeed merged and released in v5.5.0. The final API is slightly different than what was proposed, but you should still be able to access data in the `setup` function:


```js
export default defineComponent({
  ionViewDidEnter() {
    console.log(this.myRef.value);
  },
  setup() {
   const myRef = ref();
   return { myRef }
  }
});
```

Can you try this again using the latest version of Ionic Vue and let me know if it is working for you?

**Comment by sniii** [comment]
I'm sure that will work, but it is not using the Composition API concepts of Vue.

I seems very weird for our component codebase to have Vue lifecycle methods inside the setup() function and Ionic lifecycle methods as properties on the component itself, do you follow what I mean?

I'm simply pleading for you guys to implement access to Ionic lifecycle methods inside the setup function, in the same way that the guy who posted the issue before me did.

**Comment by liamdebeasi** [comment]
I'm not opposed to adding it, but could you describe your use case for this feature? I am interested in identifying scenarios where the current lifecycle API makes it difficult or impossible to accomplish a particular task. You mentioned that the current API is odd to use. Could you elaborate on that?

**Comment by sniii** [comment]
Hi Liam

It's odd in the sense that it goes against the principles of coding in Vue 3 using the Composition API paradigm.
Essentially you no longer have any need to depend on the old Options API way of doing things, eg. have data, methods and lifecycles defined as properties on the component, instead it is all located inside the setup() function.

By having the Ionic lifecycle methods defined according to the old Options API, you force developers who code using Composition API to mix and match both worlds, which is not ideal by any stretch of the imagination.

Don't get me wrong, it's fine that the lifecycle methods are available as they are right now, as properties on the component, that will make it possible for developers who do not wish to code using Composition API, to create great Ionic Vue applications following the older and trusted Options API way of orchestrating things. I am only pleading for the Ionic team to _also_ make these lifecycle methods available inside the setup() function to cater to developers using the Composition API approach.

You asked for an example, well I'm sure I can come up with a ton of example why it's a bad idea to be coding using a mix of options and composition api, but at the end of the day it boils down to not having access to al the variables in the setup method, so you need to expose code in order to satisfy the ionic lifecycle methods has access to it. But that is bad, because I would never really want to expose such variables in the first place, now the view gets access to them aswell...

Small example:

```typescript`
export default defineComponent({
    setup() {
        const { products, productQuery } = useProducts()

        function filterByPrice() {
            productQuery.addFilter('price')
        }
        
        return {
            products,
            filterByPrice
        }
    },
    ionViewWillEnter() {
        this.productQuery.reset() // <-- I can't do this out there !
    }
})
```

Since productQuery interval setup variable is not available outside, I now have to expose it...

```typescript`
export default defineComponent({
    setup() {
        const { products, productQuery } = useProducts()

        function filterByPrice() {
            productQuery.addFilter('price')
        }
        
        return {
            products,
            productQuery, // <-- now also available to the view and other components :(
            filterByPrice,
        }
    },
    ionViewWillEnter() {
        this.productQuery.reset()
    }
})
```

The ideal composition world:

```typescript`
export default defineComponent({
    setup() {
        const { products, productQuery } = useProducts()

        function filterByPrice() {
            productQuery.addFilter('price')
        }

        onIonViewWillEnter(() => {
             productQuery.reset()
        })
        
        return {
            products,
            filterByPrice,
        }
    }
})
```

**Comment by liamdebeasi** [comment]
Thanks! The use cases you provided make sense -- I can see why having the `onIonView` hooks are useful here.

**Comment by JayBizzle** [comment]
Glad I stumbled upon this, as this tripped me up today. Fingers crossed this can get added soon 🙏

**Comment by liamdebeasi** [comment]
Hi everyone,

I had some time to work on this. Here is a dev build if anyone is interested in testing:

```
npm install @ionic/vue@5.6.0-dev.202102241737.3d8f949 @ionic/vue-router@5.6.0-dev.202102241737.3d8f949
```

**Usage**
```html
<template>
  <ion-page>
    ...
  </ion-page>
</template>

<script lang="ts">
import { IonPage, onIonViewDidEnter } from '@ionic/vue';
import { defineComponent } from 'vue';

export default defineComponent({
  ...,
  components: { IonPage },
  setup() {
    onIonViewDidEnter(() => {
      console.log('ionViewDidEnter!');
    });
  }
});
</script>
```

As with the regular lifecycle methods, `IonPage` is required. I have the code and tests written, I just need to work on updated documentation. Please let me know if you find any bugs. Thanks!

**Comment by JayBizzle** [comment]
Did a quick test with `onIonViewWillEnter`.

Seems to be working fine on initial testing.

The only thing I noticed was I get this problem in VScode...

<img width="988" alt="Screenshot 2021-02-24 at 20 46 26" src="https://user-images.githubusercontent.com/340752/109063862-94236980-76e1-11eb-9c00-af3f8bfb085f.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22970, and this feature will be available in an upcoming release of Ionic Framework. We will have new docs to go along with this feature as well. When this feature ships, the docs should be available at https://ionicframework.com/docs/vue/lifecycle.

**Comment by sniii** [comment]
Thanks, great stuff 👌🏻😉
