### ISSUE TITLE
bug: ionic react, modal inner component unmounted too early

### ISSUE THREAD

**Issue by nickwang0808** [ionic-team/ionic-framework#22761]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
when closing `<IonModal isOpen={showModal} />` via setting `showModal` to false, the modal would exit with a flicker, it does not flicker away when closing is with the ESC key on the keyboard

**Expected behavior:**
the modal should animate the same way as if it was close with the ESC key, aka smoothly

**Steps to reproduce:**
simply create a modal and toggle it with showModal state in React

**Related code:**

please see codesandbox example here 
https://codesandbox.io/s/zealous-poincare-1sih7?file=/src/pages/Home.tsx

all logical code is in src/components/home directory

**Other information:**
please see the gif below, first, 2 clicks are with the mouse, last 2 are with the ESC key, notice how with the ESC key it slides out but with a mouse click it flickers to white while sliding out
![ionmodal](https://user-images.githubusercontent.com/63834422/104464585-12262800-55ee-11eb-9cb3-c4a57c12ec81.gif)

**Ionic info:**
![image](https://user-images.githubusercontent.com/63834422/104464054-798fa800-55ed-11eb-810d-66adcae5cf8f.png)

at the end I would like to thank the ionic team for making something this exceptional, and I appreciate any help from you.

**Comment by liamdebeasi** [comment]
Thanks for the issue. It looks like the modal's inner component is being unmounted too early. It should be unmounted after the `onDidDismiss` not after `onWillDismiss`.

**Comment by nickwang0808** [comment]
> Thanks for the issue. It looks like the modal's inner component is being unmounted too early. It should be unmounted after the `onDidDismiss` not after `onWillDismiss`.

thank you for you quick reply.
so is there anything I can do on my end or is it something on the ionic side?

**Comment by liamdebeasi** [comment]
This is a bug on the Ionic side, but we are looking into a fix now.

**Comment by nickwang0808** [comment]
> This is a bug on the Ionic side, but we are looking into a fix now.

thank you very much!

**Comment by liamdebeasi** [comment]
Can you try the following dev build and let me know if it resolve the issue?

```
npm install @ionic/react@5.6.0-dev.202101131554.1c08e5b @ionic/react-router@5.6.0-dev.202101131554.1c08e5b
```

I would give this a try in one of your local applications. CodeSandbox seems to have trouble installing dev builds of Ionic.

**Comment by nickwang0808** [comment]
> Can you try the following dev build and let me know if it resolve the issue?
> 
> ```
> npm install @ionic/react@5.6.0-dev.202101131554.1c08e5b @ionic/react-router@5.6.0-dev.202101131554.1c08e5b
> ```
> 
> I would give this a try in one of your local applications. CodeSandbox seems to have trouble installing dev builds of Ionic.

Yes it seems like this dev build has the bug fixed!

**Comment by liamdebeasi** [comment]
Glad it is working now! This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22763, and a fix will be available in an upcoming release of Ionic Framework.
