### ISSUE TITLE
bug: Ionic Platform Incorrectly Identifying the Current Device

### ISSUE THREAD

**Issue by BrockWeekley** [ionic-team/ionic-framework#22776]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

This is only being experienced by one developer on our team, the platform is being correctly identified for other developers. For one of our developers, the Ionic platform is being identified as ["mobile", "mobileweb"] when the user is on desktop. They are running Windows 10 with a 3840 x 2160 pixel display. This is happening consistently for this developer and when typing Ionic.platforms in the console, it displays mobile and mobileweb as well.

**Expected behavior:**

When a user accesses the application from desktop, the Ionic platform should include "desktop" as one of the members of the array. This behavior is important when developing a hybrid app. 

**Steps to reproduce:**

We are not sure what is causing the issue specifically for the developer. The application being developed is [https://eventsapplication-b3d2b.firebaseapp.com/home](https://eventsapplication-b3d2b.firebaseapp.com/home). When the developer types `Ionic.platforms` in the console here, ["mobile", "mobileweb"] is displayed and mobile only code runs when they are on a desktop.

**Related code:**

Development site: [https://eventsapplication-b3d2b.firebaseapp.com/home](https://eventsapplication-b3d2b.firebaseapp.com/home)

Private Github: [https://github.com/ProfWergeles/EventApplication-Ionic](https://github.com/ProfWergeles/EventApplication-Ionic)

**Other information:**

We have not been able to find any issues relating to this one and are not able to determine why it is occurring 

**Ionic info:**

From the developer in question:

```
Ionic:

   Ionic CLI                     : 6.12.3 (...\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.2.2
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.9
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : not available

Utility:

   cordova-res                          : 0.15.2
   native-run (update available: 1.0.0) : 0.2.9

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10


```

**Comment by liamdebeasi** [comment]
Does the Windows 10 device have a touch screen?

**Comment by BrockWeekley** [comment]
Hi liamdebeasi, thanks for the quick reply. The Windows 10 device does not have a touch screen. This is the exact monitor being used: [https://www.amazon.com/Samsung-U28E590D-28-Inch-LED-Lit-Monitor/dp/B00YD3DBOC](https://www.amazon.com/Samsung-U28E590D-28-Inch-LED-Lit-Monitor/dp/B00YD3DBOC)

**Comment by liamdebeasi** [comment]
Thanks! Are you able to run this in your dev tools on the Windows 10 device and let me know if it returns `true` or `false`?

```js
window.matchMedia('(any-pointer:coarse)').matches
```

**Comment by BrockWeekley** [comment]
Running that command does return true

**Comment by liamdebeasi** [comment]
Ok thanks! That explains why Ionic Framework thinks it is "mobile". `any-pointer: coarse` typically returns `true` when there is a touch screen or stylus, both of which are considered "coarse" pointers (a mouse is considered a "fine" pointer).

Do you know the model of the device that runs Windows 10?

**Comment by BrockWeekley** [comment]
It is a personal computer with an AMD processor. The developer is using a mouse

**Comment by liamdebeasi** [comment]
Ok thanks! I am going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/19737.

It is not possible for us to correctly detect 100% of all devices, but we do plan on letting developers override our platform detection methods to use their own heuristics or even plug in a dedicated platform detection library altogether.

**Comment by BrockWeekley** [comment]
Okay, thank you! We will search for a different solution to detect devices.

**Comment by BrockWeekley** [comment]
Just as an update to this for anyone viewing in the future, Ionic's Platform continues to detect the device as mobile and mobileweb, but using Capacitor's Device from @capacitor/core results in the correct identification of the user's device. 
![image](https://user-images.githubusercontent.com/48456042/106348417-c4671c00-628b-11eb-94f7-2fce1b4f9f94.png)
