### ISSUE TITLE
bug: Android backbutton not handled on app start

### ISSUE THREAD

**Issue by FConstantMovework** [ionic-team/ionic-framework#22773]
# Bug Report

**Ionic version:**
5.30.0

**Current behavior:**
On app start, any click on back button causes the app to exit, whitout firing backbutton or ionBackButton events.
Annoying in the case of programmaticaly navigating to a page on app launch.

**Expected behavior:**
Nothing should happen if navigation history is empty, or app should navigate back if navigation history is not empty.

**Steps to reproduce:**
Start new app:
ionic start BugBackButton tabs --cordova

Paste given code in app.component.js (optionnal)

Run it: 
ionic cordova run android

Press back button: app exits instead of displaying alert() and navigating back

**Related code:**

```
import { Component } from '@angular/core';

import { Platform } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss']
})
export class AppComponent {
  constructor(
    private platform: Platform,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar,
    private router: Router
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();

      this.platform.backButton.subscribe(() => {
        alert()
      })

      this.router.navigate(['tabs/tab2'])
    });
  }
}
```

**Other information:**
As soon as user navigates by touching a navigation element or open menu unexpected behaviour stops occuring.
It need to be a "physical" touch that occurs, as even trigering a click event on navigation element initiate navigation but doesn't solve the problem.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.1 (/home/florent/.nvm/versions/node/v14.4.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run (update available: 1.3.0)   : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/home/florent/Android/Sdk)
   NodeJS            : v14.4.0 (/home/florent/.nvm/versions/node/v14.4.0/bin/node)
   npm               : 6.14.5
   OS                : Linux 4.15

```

**Comment by liamdebeasi** [comment]
There were a significant number of improvements to hardware back button handling in Ionic Framework v.5.1.0. Can you please try again using the latest version of the framework? Your issue says you are using Ionic Framework v5.0.5.

**Comment by FConstantMovework** [comment]
Sorry i copied the ionic info from the app on which I noticed the behaviours, but it happens on fresh installed app with @ionic/angular 5.5.2.
I'll update bug description with the right ionic info output.

**Comment by liamdebeasi** [comment]
The hardware back button event is being fired correctly when I follow your steps in the original post. Can you reproduce this issue in an Ionic starter app and provide a link to the GitHub repo?
