### ISSUE TITLE
bug: Tab crashes when using IonItem on IonDatetime (React)

### ISSUE THREAD

**Issue by KevsRepos** [ionic-team/ionic-framework#22786]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**

When wrapping an `<IonDatetime>` in an `<IonItem>` component, the tab crashes when clicking on it. 

**Expected behavior:**
Of course I expect this to not happen.

**Steps to reproduce:**

I just testet this in development mode and without typescript. On latest Firefox, Windows 10. The whole code is also wrapped in a `<form>` tag.

**Related code:**
```
const Register = () => {
  const [email, setEmail] = useState();
  const [username, setUsername] = useState();

  return(
    <>
    <form>
      <FormularInput label="Email-Adress"  value={email} setValue={setEmail} />
      <FormularInput label="Username"  value={username} setValue={setUsername} />
      <IonItem>
        <IonDatetime displayFormat="MM DD YYYY"></IonDatetime>
      </IonItem>
      <IonButton color="secondary" expand="block">Register</IonButton>
    </form>
    </>
  );
}
```
This is the Code. But when I remove the `<IonItem>` component, it works as it should:
```
return(
    <>
    <form>
      <FormularInput label="Email-Adress"  value={email} setValue={setEmail} />
      <FormularInput label="Username"  value={username} setValue={setUsername} />
       <IonDatetime displayFormat="MM DD YYYY"></IonDatetime>
      <IonButton color="secondary" expand="block">Register</IonButton>
    </form>
    </>
  );
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (C:\Users\Kev\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.5.2

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 10
```

**Comment by KevsRepos** [comment]
**UPDATE**
I just closed the tab and re-opened it again, then it worked finally... I dont know, maybe its a firefox issue. But maybe someone can can reproduce it.

**Comment by KevsRepos** [comment]
**UPDATE**
I now experience more crashes on different actions. I'm trying to list them down...

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
