### ISSUE TITLE
bug: header background when using large title is tinted

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-framework#22780]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When the large title collapses the toolbar is white.

**Expected behavior:**

The toolbar should be tinted to match the following:

<img src="https://user-images.githubusercontent.com/6577830/104778133-e10f3a00-574a-11eb-9319-c83bc7e80491.png" width="50%">

**Steps to reproduce:**

1. Open the Codepen here: https://codepen.io/brandyscarney/pen/RwGEpeY
2. Scroll down until the title collapses
3. You'll see the background of the toolbar is white

**Related code:**

I believe this should be as simple as changing the fallback on the following line away from white: https://github.com/ionic-team/ionic-framework/blob/master/core/src/themes/ionic.theme.default.ios.scss#L24

This will affect all toolbars though, even if they don't collapse, but it _shouldn't_ change the background of the large title toolbar since that should match the content. Confirm with @bensperry that this is the desired behavior (changing all toolbars default background from white to ~ #F6F6F6).

**Comment by liamdebeasi** [comment]
Confirm this with Ben, but we should also change `--ion-color-step-50` to `--ion-color-step-100`: https://github.com/ionic-team/ionic-framework/blob/master/core/src/themes/ionic.theme.default.ios.scss#L24

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/22852.
