### ISSUE TITLE
bug: ion-refresher is not working well when using with ion-header condense header

### ISSUE THREAD

**Issue by hoondeveloper** [ionic-team/ionic-framework#22789]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

![RPReplay_Final1611036077 2021-01-19 15_09_54](https://user-images.githubusercontent.com/32122626/104994762-6c007500-5a68-11eb-9fdc-2819551fc86b.gif)

https://user-images.githubusercontent.com/32122626/104994187-62c2d880-5a67-11eb-979b-4297330281ed.mov

when i scroll down to do refresh, refresher animation is not working well. refresher is stumbling..
weirdly, when i remove `ion-refresher-content`'s attributes (`pullingIcon`), this animation-bug doesn't happen.
i think this happens as `pullingIcon` attributes are executed in `ion-refresher-content`

**Related code:**
```js
<ion-header class="ion-no-border">
  <ion-toolbar>
    <ion-title>알림</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)" pullMin="60">
    <ion-refresher-content
        pullingIcon="chevron-down-outline"
        pullingText="당겨서 새로고침"
        refreshingSpinner="circles"
        refreshingText="Refreshing...">
    </ion-refresher-content>
  </ion-refresher>
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">알림</ion-title>
    </ion-toolbar>
  </ion-header>
  asd
</ion-content>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (/Users/*****/.nvm/versions/node/v14.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1100.5
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.5
   @capacitor/core : 2.4.5

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.1 (/Users/*****/.nvm/versions/node/v14.15.1/bin/node)
   npm    : 6.14.8
   OS     : macOS Big Sur```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
