### ISSUE TITLE
bug: Nested Routes shown empty @ionic/react

### ISSUE THREAD

**Issue by ImFranQ** [ionic-team/ionic-framework#22785]
Ionic version: 5.x

I appling a Nested Routes, but when runs the live reload, the page shown empty. only shown when i use `<Redirect />`. When i want access by url too.

> the console does not show errors

code: 

App.tsx:
```
const App: React.FC = () => (
  <IonApp>
    <IonReactRouter>
      <IonRouterOutlet>
        <Route path="/home" component={Home} exact={true} />
        <Route exact path="/" render={() => <Redirect to="/home" />} />
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
);
```

Home.tsx
```
const Home: React.FC<ContainerProps> = ({match}) => {
  return (
    <IonTabs>
      <IonRouterOutlet>
        <Route path={`${match.path}/search`} render={() => <h1>Search</h1>} />
        <Route path={match.path} render={() => <h1>Home</h1>} />
      </IonRouterOutlet>
      <IonTabBar slot="bottom">
        <IonTabButton tab="home">
          <IonLabel>Home</IonLabel>
        </IonTabButton>

        <IonTabButton tab="search">
          <IonLabel>Search</IonLabel>
        </IonTabButton>
      </IonTabBar>
    </IonTabs>
  );
};
```

When i clikc in `<IonTabButton  />` also shows empty using `href` property. This component does not have `routerLink` property.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
