### ISSUE TITLE
bug: toast has a new style

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-framework#22781]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Toast currently presents from the bottom on iOS and uses a grey rounded overlay:

<img src="https://user-images.githubusercontent.com/6577830/104778553-8a563000-574b-11eb-8aac-3071076b7bc3.png" width="50%">

**Expected behavior:**

The toast should match the following design, should we default the position to `top`?

<img src="https://user-images.githubusercontent.com/6577830/104779190-a5756f80-574c-11eb-8410-a967b587488b.png" width="50%">

**Steps to reproduce:**

Open a toast at the following link:
http://localhost:3333/src/components/toast/test/basic?ionic:mode=ios

**Related code:**

There is an open PR for this here which just needs to be reviewed: https://github.com/ionic-team/ionic-framework/pull/22676

**Comment by vagnersabadi** [comment]
Taking advantage of the issue, I believe that a toast should not overlap another toast already open, but appear below or above.

**Current behavior:**
![Captura de tela de 2021-02-19 11-58-36](https://user-images.githubusercontent.com/12532889/108520992-093e0b80-72aa-11eb-99c0-613502e9f016.png)

**Expected behavior:**
![Captura de tela de 2021-02-19 11-59-37](https://user-images.githubusercontent.com/12532889/108521037-14913700-72aa-11eb-82dc-701fff8f1b3d.png)

**Example:**
https://ngneat.github.io/hot-toast/

**Comment by BerkeAras** [comment]
@vagnersabadi AFAIK the native behavior is that toasts are overlapping. Correct me if I am wrong.

**Comment by vagnersabadi** [comment]
> AFAIK

Unfortunately I have no way to validate it, so if this behavior really does not make sense to change.

**Comment by liamdebeasi** [comment]
Hi everyone,

After discussion with the team, we have decided not to implement this feature. Please see https://github.com/ionic-team/ionic-framework/pull/22676#issuecomment-792880404 for a full explanation.

Thanks!

**Comment by farisfaisalthena** [comment]
But would be great if you can get the same animation for the current ionic toast because currently on ios it does not have animation

**Comment by liamdebeasi** [comment]
Toast on iOS does currently have an animation: https://ionicframework.com/docs/api/toast

Are you asking if we can add a different animation?

**Comment by farisfaisalthena** [comment]
Sorry I was not clear. What i meant it does not have the bounce effect animation on ios. Heres a screen record https://youtu.be/MPWZsbLh5Vo. If you compare from the docs its different

**Comment by BerkeAras** [comment]
> Sorry I was not clear. What i meant it does not have the bounce effect animation on ios. Heres a screen record https://youtu.be/MPWZsbLh5Vo. If you compare from the docs its different

I have the same issue 👍
