### ISSUE TITLE
bug: Shadow DOM part supporting not found in latest v4

### ISSUE THREAD

**Issue by dodongphure** [ionic-team/ionic-framework#22784]
# Bug Report

**Ionic version:**

[x] **4.x**
[ ] **5.x**

**Current behavior:**

Shadow DOM part does not included in @ionic/angular@4.11.13 via npm install.

![image](https://user-images.githubusercontent.com/9283980/104807698-60684080-5813-11eb-8c04-2c60f91e18e1.png)

**Expected behavior:**

As I check it already implemented here https://github.com/ionic-team/ionic-framework/blame/f81d18c6f9f1bce056afda1cac4cf6d6ace0a7ca/core/src/components/content/content.tsx#L336.

![image](https://user-images.githubusercontent.com/9283980/104807714-842b8680-5813-11eb-8ea0-7ce7a1599f96.png)
![image](https://user-images.githubusercontent.com/9283980/104807846-a1148980-5814-11eb-9ea6-a823bcff3d21.png)

**Comment by liamdebeasi** [comment]
CSS Shadow Part support for `ion-content` was not added until Ionic Framework v5.1.0: https://github.com/ionic-team/ionic-framework/blob/master/CHANGELOG.md#510-aluminum-2020-04-30.

**Comment by liamdebeasi** [comment]
Not really sure why GitHub says it was included in v4.11.x, but it's not in that version.
