### ISSUE TITLE
bug: V5 Ion-virtual-scroll rendering issue.

### ISSUE THREAD

**Issue by dodomui** [ionic-team/ionic-framework#22792]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I had written double ion-virtual-scroll by using component with dynamic ion-item height.
I did provided the actual item height for each virtual scroll item.

But the inner Ion-virtual-scroll doesn't render properly.

**Expected behavior:**

The inner loop can be render properly by just using ngFor, but my list might having long item, therefore ngfor is not applicable in my case.

**Related code:**

https://stackblitz.com/edit/ionic-angular-v5-virtual-scroll-issue-auqqvo

**Comment by liamdebeasi** [comment]
Thanks for the issue. With upcoming major versions of Ionic Framework, we are going to be transitioning to using Angular's CDK Scroller. As a result, we have a freeze on new features and bug fixes on ion-virtual-scroll. See https://material.angular.io/cdk/scrolling/overview for how to get started with CDK Scroller. We are working on proper transition docs as well!
