### ISSUE TITLE
bug: overlay interfaces should be exported

### ISSUE THREAD

**Issue by HyperLife1119** [ionic-team/ionic-framework#22790]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

I hope ionic can export more types and interfaces (such as the interface: `AlertOptions`) to facilitate the secondary packaging function of developers

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by HyperLife1119** [comment]
Sometimes, I need to write some convenient functions myself to encapsulate some functions provided by ionic. Since I use typescript, I need to get some of Ionic’s own parameter types/interfaces

**Comment by HyperLife1119** [comment]
I want to know when this problem will be fixed

**Comment by HyperLife1119** [comment]
> I want to know when this problem will be fixed

The workload doesn’t seem to be too much

**Comment by HyperLife1119** [comment]
Hello, is this issues forgotten? @liamdebeasi

**Comment by liamdebeasi** [comment]
This is part of our work for v5.7.0 but I forgot to add it to the milestone.

**Comment by HyperLife1119** [comment]
Thanks.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23619, and a fix will be available in an upcoming release of Ionic Framework.
