### ISSUE TITLE
bug: Rendering/flickering performance issue starting from version 5.4.2, when changes happens to many elements 

### ISSUE THREAD

**Issue by tgangso** [ionic-team/ionic-framework#22798]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.4.2*

**Current behavior:**
In version 5.4.2 and newer: General slower responsiveness in the app and pages with many components cause a few milliseconds of noticable 1 time flickering when toggling on/off or for example changing an array that has an ngFor with many elements. Or toggling on/off many components with a button. Directly compared with version 5.4.1 or older where this does not happend.

**Expected behavior:**
No flickering as with version 5.4.1 or older.

**Steps to reproduce:**
I can try to create a sample application where this issue is but had not had time yet. Let me know if this is required.

**Other information:**
Tested with angular version 8, 10 and 11, no difference.

Issue present both in dev mode and prod build.

Currently upgrading from ionic version 4 to 5 and noticed this immediately upon upgrading the project, downgrading to 5.4.1 instead of the newest version 5 solved the issue. 5.4.2 and newer the issue is present.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\tg\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.4.2
   @angular-devkit/build-angular : 0.1100.7
   @angular-devkit/schematics    : 11.0.7
   @angular/cli                  : 11.0.7
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Comment by tgangso** [comment]
If you are able to identify what change in 5.4.2 could possibly cause this, I would happily help test a custom build.

**Comment by tgangso** [comment]
I feel this would most likely affect all angular projects and something you should prioritise trying to reproduce. But I will try to get some time to get a repo up. @liamdebeasi

**Comment by liamdebeasi** [comment]
I tested in the Ionic starter applications and was unable to reproduce the issue, which is why I asked for a code reproduction from you.

**Comment by tgangso** [comment]
I see - might be something in my apps composition og application size, will try to get a repo up. But the only thing changing from when it is there or not is the ionic version. Thought maybe having a quick look at the diff between 5.4.1 and 5.4.2 could point out something since there was a limited amount of changes there.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
