### ISSUE TITLE
bug: ion-modal events (ionModalDidPresent & ionModalWillPresent) not exposed for angular

### ISSUE THREAD

**Issue by Viras-** [ionic-team/ionic-framework#22793]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Trying to bind to ionModalDidPresent & ionModalWillPresent is not possible due to missing exposed functions. Stencil compiler seems to only expose ionModalDidDismiss & ionModalWillDismiss - although with slightly different naming.

**Expected behavior:**
IonModal component should expose DidPresent and WillPresent as well.

**Steps to reproduce:**
Trying to bind to ionModalDidPresent & ionModalWillPresent is not possible due to missing exposed functions. Stencil compiler seems to only expose ionModalDidDismiss & ionModalWillDismiss - although with slightly different naming.

**Other information:**
Seems to be similar to this issue (which is for react): https://github.com/ionic-team/ionic-framework/issues/19923

**Ionic info:**
```
$ ionic info

Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\masked\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.2.2

System:

   NodeJS : v10.15.0 (C:\Users\masked\.codemix-store\nodejs\10.15.0\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
