### ISSUE TITLE
feat: class indicating that a ion-select is expanded / open

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#22801]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
I am working with an Ionic Framework user who would like to be able to style the ion-select differently when it is open vs when it it is closed. As an example, see these screenshots:

<img width="184" alt="Screenshot 2021-01-20 at 09 08 23" src="https://user-images.githubusercontent.com/1526846/105248545-3331d000-5b3c-11eb-85ee-e82bd5632ae5.png">
<img width="226" alt="Screenshot 2021-01-20 at 09 08 26" src="https://user-images.githubusercontent.com/1526846/105248546-33ca6680-5b3c-11eb-8445-70f976da5676.png">

We do not currently have a way to determine when this is the case.

**Describe Preferred Solution**
A class on ion-select that indicates when the select is open vs not.

**Describe Alternatives**
Prior to upgrading to @latest, they where using CSS such as the following:

```css
&[aria-expanded="true"] {
  background-color: blue;
  border-color: blue;
}
```

Ignoring the abuse of an aria attribute for non-a11y things, that is now no longer an option anyhow as the attribute has been moved from the ion-select to the underlying HTML element in the shadow DOM, so it is no longer visible via a selector like that.

Something _like_ that, however, would be helpful where for example an ion-select-expanded class is added to the ion-select when it is expanded and removed when it is not.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22846, and a fix will be available in an upcoming release of Ionic Framework.

You can target the `.select-expanded` class to style based upon expanded/collapsed state of the `ion-select`.
