### ISSUE TITLE
bug: item highlight does not account for --border-radius

### ISSUE THREAD

**Issue by timsar2** [ionic-team/ionic-framework#22816]
# Bug Report

**Ionic version:**

[x] **5.2.3**

**Current behavior:**

ion-item highlight has not correct position when making ion-item round. highlight-highlight line is not inside of ion-item and it has corner as you can see in this image:
[https://ibb.co/NnK8czr](https://ibb.co/NnK8czr)
   ```
ion-item{
    --border-width: 1px;
    --border-style: solid;
    --border-color: #CED8DC;
    --border-radius: 5px;
    }
```
**Expected behavior:**

`class="item-highlight"` in shadowpart of ion-item must have `right: 5px` and `left: 5px` but it doesnt have part name to change it's css.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue, I can reproduce this. As a temporary workaround, setting `border-radius: 5px` in addition to `--border-radius` on `ion-item` seems to fix the issue.

**Comment by 007razajutt** [comment]
Use this one to resolve the issue
  ion-item{
        border: 2px solid green;
        border-radius: 5px;
    }

**Comment by timsar2** [comment]
> Use this one to resolve the issue
> ion-item{
> border: 2px solid green;
> border-radius: 5px;
> }

Thank you. but this is diffrent. 
i need to use - - border

**Comment by sean-perkins** [comment]
Hello everyone, I've tried to reproduce this issue on the latest and it appears to be resolved. I am going to close out this issue, but please comment with a reproduction if you run into it and I will be happy to re-open it.

Thanks!
