### ISSUE TITLE
bug: removing target from DOM during gesture causes onEnd to not fire

### ISSUE THREAD

**Issue by Falingorn** [ionic-team/ionic-framework#22819]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When using `ion-card` and switching loading states while refreshing, scroll down after refresher completed triggers the refresh again.

**Expected behavior:**

Content is scrollable and refresh isn't triggered again.

**Steps to reproduce:**

* Open the example app
* Pull refresher down until refresh is triggered automatically (**!Important Tap on the card and pull down**)
* wait until refresher is closed
* swipe content from bottom to top
=> refresh is triggered again

example video: https://user-images.githubusercontent.com/7203239/105836301-4544c000-5fcd-11eb-9a91-b189a7c2aab4.mov

**Related code:**
Sample application: https://github.com/Falingorn/bug-ionic-refresher-example/tree/bug/refresher-snapback-refresh

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI : 6.12.3

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run (update available: 1.3.0)   : 1.0.0

System:

   NodeJS : v14.15.4
   npm    : 6.14.10
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Reposting from https://github.com/ionic-team/ionic-framework/pull/22820 in case other developers run into this:

> The reason why this bug is happening is that when an event's target is removed from the DOM, events will still be targeted at it but may not bubble anymore. So what's happening is `ion-card` is the target when you start the gesture, but the moment you remove `ion-card` from the DOM, the events no longer bubble.
> As a result, this causes the `touchend` event to never bubble up to the listeners on `ion-content` resulting in `onEnd` not being fired.
> As you noted in https://github.com/ionic-team/ionic-framework/pull/22820#issuecomment-868387447 there is another bug with the native refresher not hiding. This is caused by the same underlying problem of `onEnd` not firing because events no longer bubble.
> Given that this impacts both types of refreshers and potentially other gestures, I am not sure that the proposed solution is a good long term solution, but I will try to look into how we can address this problem in other ways.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23713, and a fix will be available in an upcoming release of Ionic Framework.
