### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by stefani0** [ionic-team/ionic-framework#22818]
ion-item and audio dont work on real  device.

**Code performed:**

`  <ion-item class="radio light">
      <audio id="myAudio" controls width="100%">
        <source src="http://xx.xx.xx.xxx1234" />
      </audio>
    </ion-item>`
    
    **Code tried:** 
  `    <ion-item class="radio light">
      <audio id="myAudio" controls width="100%">
        <source src="http://xx.xx.xx.xxx1234;stream.mp3" />
      </audio>
    </ion-item>`
    
    **Working code:** 
    
`   <div text-center>
     <audio id="myAudio" controls playsinline width="100%">
           <source src="http://xx.xx.xx.xxx1234" />
     </audio>
       </div>`

**Comment by BerkeAras** [comment]
@stefani0 I cannot reproduce this issue. Please provide a sample application. _And for the next time, please fill out the issue-template and the title._

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
