### ISSUE TITLE
Ui flickering on iOS

### ISSUE THREAD

**Issue by abhinav1999** [ionic-team/ionic-framework#22822]
**Ionic version:**

[x] **4.x**
[ ] **5.x**
ionic v5 
**I'm submitting a ...** 

[ ] bug report
[ ] feature request

**Current behavior:**

I noticed that when I add bg image to ion-content there is a strange flickering on the screen when user interacts or clicks anywhere this happens only for iOS devices or in safari. I am attaching a video in reference to the issue. Please guide or suggest a way to solve this problem.
**Expected behavior:**

On user input it should not flicker 
**Steps to reproduce:**

1. Start ionic project 
2. Add background image to ion-content
3. run it on safari or iOS device
**Related code:**

Css code
 ion-content {
    --background: url('../../assets/images/login-bg.png') no-repeat center center / cover;
    }

```
<ion-content>
<ion-content>
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is a problem with Safari/WebKit on iOS. The issue should not happen if the image is base64 encoded. I am going to close this as there is nothing actionable on our end as of now. Please see https://bugs.webkit.org/show_bug.cgi?id=195628 for more info. (Note that the issue has been resolved on WebKit's end, but the fix does not seem to have shipped yet)
