### ISSUE TITLE
bug: Ionic components not rendering when DOM updated via Phoenix LiveView

### ISSUE THREAD

**Issue by raymondboswel** [ionic-team/ionic-framework#22821]
# Bug Report

This is a very niche use case, but some advice would be much appreciated. 

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
We are currently using Ionic components on our server rendered pages using the Elixir/Phoenix framework. This works pretty well for the most part, but when we try and use LiveView, which sends updated state to the client via a socket and uses MorphDOM to replace a portion of the DOM with the fresh state from the server, the Ionic components render with visibility: hidden applied to them as per the attached screenshot. 
![image](https://user-images.githubusercontent.com/4745321/105851157-5a304c00-5feb-11eb-8558-d9c7dff10180.png)
We have tried to reload the ionic scripts to reexecute the code, and apply .hydrated to the component tree, but so far a solution has escaped us. Is there any hook we can call, to let Ionic know to rehydrate the DOM?

**Expected behavior:**
Ionic should render elements added to the DOM dynamically via MorphDOM

**Steps to reproduce:**
Create a LiveView template 

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by raymondboswel** [comment]
@liamdebeasi You can clone the repo here: https://github.com/raymondboswel/curious_messenger
I've updated the README, although it's hard to determine all the steps required for your specific environment, hopefully there's enough to get you started.
Once you have the app up and running
- register two accounts,
- Create chat room. Refresh your browser if the room doesn't appear.
- Once inside the room you should see a pretty ugly button that is an ion button with some additional styles applied. 
- Enter a message and press the button, and you'll see the button disappear.

**Comment by raymondboswel** [comment]
@liamdebeasi Please let me know if I should add a Dockerfile instead, as that would be quite a bit easier on your side.

**Comment by raymondboswel** [comment]
@liamdebeasi I spent some time and deployed the reproduction at: http://dazzling-fatal-rottweiler.gigalixirapp.com

You can log in using raymondboswel@gmail.com / letmein123

Once logged in, click on "Test Conversation" under the ongoing conversations section. You should see an ion-button render, and then shortly after disappear, although it's still in the DOM, just all the classes applied by ionic are missing.

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce the issue on the deployed web app. It looks like Ionic's internal component styles are being wiped when something is being loaded. When expanding the `shadow-root` there should be a `<style>` tag inside of each component that is no longer there.

Does your web app do any kind of template sanitizing?

**Comment by raymondboswel** [comment]
Not that I'm aware of. As far as I have it, when server side state is updated, a partial template is rendered on the server, passed through a web socket, and replaces the previously rendered html, without doing a page load. Our current workaround is to apply 'hydrated' to the template, eg

`<ion-card-content class="hydrated">`

It adds a bit of noise to the templates, but is quite a low effort workaround, so if this is a low priority use case you are welcome to close the ticket, I'm just glad we found a way to use the awesomeness that is Ionic given that our usage is a bit off the beaten track.

**Comment by liamdebeasi** [comment]
Looking at this https://github.com/patrick-steele-idem/morphdom/issues/127 it may just be the case that MorphDOM does not support Web Components w/ Shadow DOM very well. Are you able to exclude components from being replaced by MorphDOM?

**Comment by raymondboswel** [comment]
Interesting. IIRC, we did try add phx-ignore="true" to the Ionic elements. It worked in terms of keeping the ionic components hydrated, but the updates from the server were not applied to the elements in question. From the linked issue it appears that the ionic components would have to implement isSameNode() fn, though I'm not sure how that would work in practice.

**Comment by liamdebeasi** [comment]
Web components should already have that `isSameNode` method. I would recommend reaching out to the MorphDOM maintainer with a minimal example to see if they have a better idea of what may be going on. (maybe just an app with that single mocked conversation page)
