### ISSUE TITLE
bug: picker giving haptic feedback on android, capacitor v3

### ISSUE THREAD

**Issue by aditbharadwaj** [ionic-team/ionic-framework#22838]
### Capacitor Version

```
@capacitor/ios: not installed   
  @capacitor/cli: 3.0.0-beta.1    
  @capacitor/core: 3.0.0-beta.1   
  @capacitor/android: 3.0.0-beta.1
```

### Platform(s)

android 

### Current Behavior

when using the capacitor v3 the ion-datetime picker gives vibration feedback when its scrolled to change date, month or year.

### Expected Behavior

Their should be no vibration feedback on the scroll.

### Other Technical Details

their are no specific plugin or code that change this behavior installed or used.

`npm --version` output: v6.11.3

`node --version` output: v14.15.4

`pod --version` output (iOS issues only):

### Additional Context

the same thing when tested on latest capacitor v2 branch didn't reproduce and scroll was smooth with no vibration feedback.
( vid to show the scroll behavior causing the vibration)
https://user-images.githubusercontent.com/6751554/106288233-c8844100-626d-11eb-9278-c2ebfe96297f.mp4

**Comment by liamdebeasi** [comment]
Thanks for the issue. We should probably only add this haptic feedback when running on iOS.

**Comment by liamdebeasi** [comment]
I am going to merge this with our main datetime issue thread instead: https://github.com/ionic-team/ionic-framework/issues/16630
