### ISSUE TITLE
bug: ion-back-button crashes the application

### ISSUE THREAD

**Issue by mkuchak** [ionic-team/ionic-framework#22840]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
When you slide the page too fast (without actually moving it) on iOS, all application navigation crashes and stops working. The back button also stops working.

The only way to "resolve this" is to close the application and open it again.

**Expected behavior:**
Swiping slow or fast should trigger the swipe movement of the page without breaking the application's navigation.

**Steps to reproduce:**
I created a video to facilitate the understanding of reproducing the bug. In this video I run the bug twice, the first being at **15 seconds** and the second at **43 seconds**.

https://user-images.githubusercontent.com/3791148/106332382-76d7b880-6265-11eb-847e-10b3e9d9bbe8.mp4

The problem can be tested on the ion-back-button documentation link.

https://ionicframework.com/docs/demos/api/back-button/index.html?ionic:mode=ios
OR
https://ionicframework.com/docs/api/back-button

**Related code:**
The original code can be found here.
https://github.com/ionic-team/ionic-docs/blob/master/src/demos/api/back-button/index.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Back Button</title>
  <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
  <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css"/>
  <style>
    :root {
      --ion-safe-area-top: 20px;
      --ion-safe-area-bottom: 22px;
    }
  </style>
</head>
<body>
  <ion-app>
    <ion-nav root="nav-home"></ion-nav>
  </ion-app>

  <script>

    customElements.define('nav-home', class NavHome extends HTMLElement {
      connectedCallback() {
        this.innerHTML = `
          <ion-header translucent>
            <ion-toolbar>
              <ion-title>Back Button</ion-title>
            </ion-toolbar>
          </ion-header>
          <ion-content fullscreen>
            <ion-list>
            <ion-item onclick="navigateForward()">
              Navigate Forward
            </ion-item>
            </ion-list>
          </ion-content>
        `;
      }
    });

    const nav = document.querySelector('ion-nav');

    function navigateForward() {
      nav.push('nav-detail');
    }

    customElements.define('nav-detail', class NavDetail extends HTMLElement {
      connectedCallback() {
        this.innerHTML = `
          <ion-header translucent>
            <ion-toolbar>
              <ion-buttons slot="start">
                <ion-back-button defaultHref="/"></ion-back-button>
              </ion-buttons>
              <ion-title>Page Two</ion-title>
            </ion-toolbar>
          </ion-header>
          <ion-content fullscreen class="ion-padding">
            <p>Back-Button is displayed when there is history</p>
          </ion-content>
        `;
      }
    });
  </script>
</body>
</html>
```

**Other information:**
It can be a little difficult to reproduce in the browser, but directly on the phone, it's incredibly easy. I also reproduce it on my cell phone with CapacitorJS app. It is a serious bug because it blocks the entire navigation of the application and any user can easily reproduce it.

**Ionic info:**
The code has already been attached and it is the latest stable Ionic version.

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What browser are you testing this on? I am testing this on iOS Safari (14.4) and am unable to reproduce this issue.

**Comment by mkuchak** [comment]
> Thanks for the issue. What browser are you testing this on? I am testing this on iOS Safari (14.4) and am unable to reproduce this issue.

I have reproduce it with **Google Chrome Version 86.0.4240.198 (Official Build) (64-bit)**, but I have tested too with an **CapacitorJS v2 app** and occur the same problem on mobile.

**Comment by liamdebeasi** [comment]
Are you able to reproduce this on an iOS device? From the example you posted it looks like the issue only happens in iOS mode with the swipe gesture?

**Comment by mkuchak** [comment]
I forced iOS design on an Android device. I couldn't test it on an iOS device, but it should be reproducible there too.

**Comment by liamdebeasi** [comment]
Thanks. Can you provide some additional steps to reproduce? I have been testing this on multiple devices (both desktop and mobile) and am unable to reproduce the issue.
