### ISSUE TITLE
bug: input blurring should skip contenteditable

### ISSUE THREAD

**Issue by samwillis** [ionic-team/ionic-framework#22856]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
If you are focused in a `contenteditable` element (within an ion-app) and try to move the cursor by taping elsewhere in the element the keyboard may flicker (partially disappear and then come back), or completely disappear. From my testing it seem to be when you tap on a word rather than a space.

**Expected behavior:**
The keyboard should not flicker and you should be able to move the selection.

**Other information:**

It seems to be related to this previous issue: https://github.com/ionic-team/ionic-framework/issues/18368

That issue was resolved by adding the additional css but the patch did not add the `[contenteditable]` to SKIP_SELECTOR as per: https://github.com/ionic-team/ionic-framework/issues/18368#issuecomment-496513193

From my testing if you add `no-blur` to the `contenteditable` element the issue is resolved, however this is not necessarily possible if you are using a wysiwyg toolkit as it may control the `contenteditable` element and you are not provide a way to add attributes. A much better fix would be to add `[contenteditable]` to SKIP_SELECTOR.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.2

Capacitor:

   Capacitor CLI   : 2.4.5
   @capacitor/core : 2.4.5

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v15.5.0 (/usr/local/Cellar/node/15.5.0/bin/node)
   npm    : 7.3.0
   OS     : macOS Big Sur

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

**Angular**
```
npm install @ionic/angular@5.6.0-dev.202102021420.1a5accc
```

**React**
```
npm install @ionic/react@5.6.0-dev.202102021420.1a5accc @ionic/react-router@5.6.0-dev.202102021420.1a5accc
```

**Vue**
```
npm install @ionic/vue@5.6.0-dev.202102021420.1a5accc @ionic/vue-router@5.6.0-dev.202102021420.1a5accc
```

**Stencil/Vanilla JavaScript**
```
npm install @ionic/core@5.6.0-dev.202102021420.1a5accc
```

**Comment by samwillis** [comment]
Works perfectly! (and seriously impressed with how quickly you responded!!)

No more flickering and can now select word with double tap.

Thanks

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22857, and a fix will be available in an upcoming release of Ionic Framework.
