### ISSUE TITLE
bug: plaftform is desktop return false on desktop devices with touchscreen

### ISSUE THREAD

**Issue by Felipe-BP** [ionic-team/ionic-framework#22860]
# Bug Report
**Ionic version:**

[x] **4.x**
[x] **5.x**

**Current behavior:**
Ionic platform checking as desktop returns false on desktops with touchscreen available.

**Expected behavior:**
Result expect is true, but device is identified as mobile.

**Steps to reproduce:**

**Related code:**

```ts
return this.platform.is('desktop');
```

**Other information:**

Related issue [#18463](https://github.com/ionic-team/ionic-framework/issues/18463)
Ionic uses Window.matchMedia API (browser) by querying any-pointer:coarse to check out if device have touchscreen available, in this way considering as a mobile device, but today we have desktop devices with touchscreen.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this in favor of #19737.

It is not possible for us to correctly detect 100% of all devices, but we do plan on letting developers override our platform detection methods to use their own heuristics or even plug in a dedicated platform detection library altogether.
