### ISSUE TITLE
bug: Service worker registration not working in react

### ISSUE THREAD

**Issue by satheshsat** [ionic-team/ionic-framework#22861]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Try to register service worker file ( service-worker.js ) from root path. But there is no such a file in build.

**Expected behavior:**
Need to register service worker for PWA

**Steps to reproduce:**
ionic start pwa blank --type=react
change serviceWorker.unregister(); to serviceWorker.register(); in index.tsx
ionic build --prod
npx serve build
Service worker can't be registered in local. But it runs service worker validation.
console: GET http://localhost:5000/service-worker.js 404 (Not Found)

**Comment by liamdebeasi** [comment]
Thanks for the issue. There were some changes in how `react-scripts` v4 generated PWA-related files that caused this to no longer work. We have updated our starters to properly generate the service worker file now.
