### ISSUE TITLE
feat: format the pin text for ion-range

### ISSUE THREAD

**Issue by vicb** [ionic-team/ionic-framework#22864]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
Currently the pin always displays an integer value:

https://github.com/ionic-team/ionic-framework/blob/487349f02a41344db2478735d27bf79f2a1c99b3/core/src/components/range/range.tsx#L558

This is not very flexible and they are a lot of times when you would want something else:
- `35%`,
- `1.2`,
- `42px`,
- ...

**Describe Preferred Solution**

I think that adding a `pin` slot with the current label as the default value would be a great solution:

```
{pin && <div class="range-pin" role="presentation" part="pin"><slot name="pin">{Math.round(value)}</slot></div>}
```

The current usages would still work the same by using the default value:

```
    <ion-range pin min="20" max="80" step="2">
      <ion-icon size="small" slot="start" name="sunny"></ion-icon>
      <ion-icon slot="end" name="sunny"></ion-icon>
    </ion-range>
```

But you can customize the text by doing

```
    <ion-range pin min="20" max="80" step="2" @ionChange=${e => this.value = e.detail.value}>
      <ion-icon size="small" slot="start" name="sunny"></ion-icon>
      <ion-icon slot="end" name="sunny"></ion-icon>
      <ion-text slot="pin">${this.value}%</ion-text>
    </ion-range>
```

Edit:
I have quickly hacked this approach and it seems to work well.

There is one caveat: `@ionChange=${e => this.value = e.detail.value}` could be debounced (by adding debounce="<ms>") and then the value would not be updated as quickly as the pin is moved.

Adding a `ionRawChange` event might do the trick (this event would not be debounced).

**Describe Alternatives**

One alternative could be to pass a formatter callback as property: `(value: number) => string`.

I think that the slotted approach is nicer.

**Additional Context**

If this feature makes sense and is accepted, I would be happy to work on the implementation.

Thanks for the great framework !

**Comment by EinfachHans** [comment]
i already started a PR for this which started out to be a bit tricky as if the text is always centered over the pin it goes over the screen real quick so i think it need a reposition logic for the knobs if they are near to the side

**Comment by vicb** [comment]
Do you have some link to share ?

I think the issues are kind of orthogonal ? i.e. you would probably have the issue today it you need to select a value between 1000000 and 2000000

**Comment by EinfachHans** [comment]
no i didn't finished the PR. The pure format your own text part is quite easy, i can do this again. Yeah this issue will happen with that large numbers too i think, but i think it should be fixed within the change

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22972, and this feature will be available in Framework v6 beta 2. You will be able to provide a custom formatter function via the `pinFormatter` property.
