### ISSUE TITLE
bug: ionic vue, IonRadioGroup does not update selected option

### ISSUE THREAD

**Issue by NunoSav** [ionic-team/ionic-framework#22870]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
In a `ion-radio-group` list new selections won't be shown with a selection mark

**Expected behavior:**
Selected radio should get a icon identifying it as selected

**Steps to reproduce:**
**Related code:**

https://github.com/NunoSav/ionic-vue-bugs

Steps to reproduce:
1. Open app
2. Select either Green or Blue option

**Other information:**
This bug does not occur in @ionic/vue 5.5.2

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.2 (/Users/nur/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.3

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.2.1

System:

   NodeJS : v12.16.3 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via #22872, and a fix will be available in an upcoming release of Ionic Framework.
