### ISSUE TITLE
bug: (React) Wrapped ion-col component ignores className prop

### ISSUE THREAD

**Issue by zrev2220** [ionic-team/ionic-framework#22877]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I have an `IonGrid` where the inner `IonCol` elements are wrapped in [`Tippy` components](https://github.com/atomiks/tippyjs-react) to apply tooltips to interactions with each entire column. **These `IonCol` elements aren't properly getting their CSS class set by their `className` prop.** E.g. `className='some-class'`, but in the DOM the `<ion-col>` element does not have the `some-class` class.

This does _not_ happen if the `IonCol` is not wrapped in another element, i.e. the _direct parent_ of the `IonCol` is an `IonRow`.

**Expected behavior:**

The `<ion-col>` in the DOM should have its CSS class set according to the corresponding `IonCol` component's `className` prop value. This should happen **whether or not** the `IonCol`'s direct parent is an `IonRow`.

**Steps to reproduce:**

1. Create a new Ionic React project
2. Install `@tippyjs/react`
3. Create a simple table using `IonGrid`, `IonRow`, `IonCol`, where the `IonCol`s are wrapped in `Tippy` components
4. Set the `IonCol`s' `className` prop to some value and add styles for that class in an associated stylesheet

_See Related Code for a more concrete example_

**Related code:**

StackBlitz: https://stackblitz.com/edit/ion-col-ignore-class-name

Here's the general structure of the JSX structure causing the issue:

```tsx
<IonGrid>
  <IonRow>
    <Tippy content='Some tooltip'>
      <IonCol className='some-class'>
        Some column content
      </IonCol>
    </Tippy>
  </IonRow>
</IonGrid>
```

In this case, any styles for `some-class` will not be applied to the `IonCol` contents, because the class is not getting applied in the DOM.

Conversely, removing the `Tippy` element (thus making the `IonCol` the direct child of the `IonRow`) makes the class correctly get applied, and the `IonCol` is styled as expected.

**Other information:**

I have narrowed down that this behavior was introduced in **`@ionic/react@>=5.5.1`**. The expected behavior correctly appears in `@ionic/react@5.5.0`. As such, I'm currently locking the version to 5.5.0 to prevent the bug from manifesting.

This is reproducible in the StackBlitz&mdash;if you install 5.5.0, the behavior is as expected. Installing anything greater than that (`>=5.5.1`) produces the unexpected behavior.

**Ionic info:**

_Since it's reproducible in a StackBlitz, not sure `ionic info` is incredibly relevant? Posting output from the specific project I'm having the issue with below anyway._

```
Ionic:

   Ionic CLI       : 6.12.3
   Ionic Framework : @ionic/react 5.5.4

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : 0.15.2
   native-run  : 1.3.0

System:

   NodeJS : v14.4.0
   npm    : 7.5.2
   OS     : Windows 10
```

**Comment by zrev2220** [comment]
Pardon, somehow I bumped Enter and posted the issue prematurely. Will have the remaining required info in the issue in a moment.

**Comment by zrev2220** [comment]
Description updated

**Comment by zrev2220** [comment]
Any progress on this issue? Still exists in version 5.6.4.

**Comment by liamdebeasi** [comment]
Hi everyone,

This appears to be resolved in the latest version of Ionic 7. If you are still running into this problem after updating, please open a new issue. Thanks!
