### ISSUE TITLE
question: import cost is too high

### ISSUE THREAD

**Issue by saostad** [ionic-team/ionic-framework#22878]
"@ionic/react": "^5.5.3",

I am using import cost vscode extension. 
it shows the image below: 

![ionic import cost](https://user-images.githubusercontent.com/16025625/106956936-55634a80-6705-11eb-9c98-d786b2d738f7.png)

is that how it should be or there is a more effiecient way to import components?

**Comment by liamdebeasi** [comment]
Thanks for the issue. We have been investigating this, and the main issue is Webpack is incorrectly importing components when it really does not need to. With the next major release of Ionic Framework we will be using a "Custom elements" build of Ionic Framework which significantly reduces the amount of code that Webpack needs to import.

We will be talking more about this as we get closer to launch including an opportunity for the community to test this. Thanks!
