### ISSUE TITLE
bug: ion-datetime unclickable when used with floating ion-label on iOS, 'md' mode

### ISSUE THREAD

**Issue by aguerard** [ionic-team/ionic-framework#22882]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**
`"@ionic/angular": "^5.5.4"`
**Current behavior:**
```
      <ion-item>
        <ion-label position="floating">Cool label name</ion-label>
        <ion-datetime name="myIonDatetime" [(ngModel)]="myIonDatetimeModel">
        </ion-datetime>
      </ion-item>
```
Within a form, include this snippet above. When you click on the control on iOS (currently using ios 12.0 emulator) nothing happens if you're tapping the label. (FWIW I'm using 'md' mode on Android and iOS). 

**Expected behavior:**
Expect the datetime picker UI to slide-in. 

**Steps to reproduce:**
Create a form using the snippet above

**Related code:**

Just drop the snippet above into an 'md' themed ios angular app, and you should quickly repro it.

**Other information:**
Looking at the computed CSS for the ion-label next to an ion-datetime, it appears that the ion-label doesn't have `pointer-events: none` like it would if it were next to an ion-input. My current workaround is to define a CSS class that sets pointer-events to none and then use that class on any ion-labels I place next to an ion-datetime. Perhaps the fix is to just give ion-labels next to ion-datetime the same treatment as those next to ion-inputs. 

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (~/.nvm/versions/node/v14.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.4
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.5
   @capacitor/core : 2.4.5

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : 1.3.0

System:

   NodeJS : v14.15.1 (~/.nvm/versions/node/v14.15.1/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify the steps to reproduce? I am trying the code snippet you provided on an iOS 12 device and clicking the label is opening the datetime.
