### ISSUE TITLE
bug: IonIcon not showup in IonSelectOption

### ISSUE THREAD

**Issue by saostad** [ionic-team/ionic-framework#22885]
# Bug Report

**Ionic version:**
[x] **5.5.4**

**Current behavior:**
IonIcon not showup in IonSelectOption

**Expected behavior:**
to show Icon in SelectOption

**Related code:**
```
<IonSelect
    interface="popover"
    value={selectedPayPeriod}
    style={{ minWidth: 300 }}
    placeholder="Select One"
    onIonChange={(e) => selectPayPeriodSet(e.detail.value)}
  >
      <IonSelectOption key={el?.PP_ID} value={el?.PP_ID}>
          <IonIcon icon={lockOpenOutline} />
      </IonSelectOption>
</IonSelect>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.4 (C:\Users\SOstad\AppData\Roaming\nvm\v14.15.4\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.5.4

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/18067. `ion-select` does not allow custom templates/components inside of `ion-select-option`; however, we have a feature request for this in the issue I linked to.

**Comment by saostad** [comment]
is there any way to work around it? 
Here is a link to reproduce it
https://codesandbox.io/s/ionic-react-select-icon-bug-pjigf?file=/src/App.tsx

**Comment by liamdebeasi** [comment]
No workaround within `ion-select` at the moment. Typically we recommend using `ion-modal` for anything custom, but we also realize this may be cumbersome if you just want to add something simple like an icon.

**Comment by saostad** [comment]
ion-modal can't do what select interface="popover" does. 
I think these are two different use cases.

**Comment by liamdebeasi** [comment]
Right, what I am saying is if developers needed anything beyond what `ion-select` provides, we have previously recommended developers re-implement their form in an `ion-modal` or `ion-popover`. However, we realize this is cumbersome as you have to re-implement a lot of things that are given out of the box with `ion-select`. https://github.com/ionic-team/ionic-framework/issues/18067 seeks to address this.
