### ISSUE TITLE
bug: Clicking on a disabled fab in a fab-list closes the list

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#22881]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
If you click on a disabled fab that is in a fab-list, you would expect nothing to happen, but the list closes.

**Expected behavior:**
The list shouldn't close

**Steps to reproduce:**

* add a fab in a fab-list and set disabled to true
* click the button

**Related code:**
https://stackblitz.com/edit/ionic-v5-bug-fab-disabled?file=src/app/app.component.html

it's maybe a little related to this issue as well ? https://github.com/ionic-team/ionic-framework/issues/21678

**Comment by HMichel3** [comment]
I have the same problem at the moment. Is there anything new yet?

**Comment by liamdebeasi** [comment]
Thanks for the report. This appears to be fixed in the latest version of Ionic 6, so I am going to close this. Let me know if there are any questions.
