### ISSUE TITLE
feat: Add CSS variable --ripple-color to ion-menu-button component

### ISSUE THREAD

**Issue by Metroslim** [ionic-team/ionic-framework#22908]
# What I've tried to achieved:
I've tried to disable the ripple effect on browser platform for the ion-menu-button.
Adding  rippleEffect: false in the config (like below) didn't worked:
`IonicModule.forRoot({
    rippleEffect: false,
    mode: "md",
 }),`
So I've tried to set --ripple-color CSS variable with no effect and I've discovered that this property exist on ion-button but not on ion-menu-button.

# Feature Request
Add CSS variable --ripple-color on the ion-menu-button component.

**Ionic version:**
[x] **5.x**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a reproduction of the initial issue (ripple effect config not working)?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
