### ISSUE TITLE
bug: ionic react, IonRouterOutlet animated=false not working

### ISSUE THREAD

**Issue by Aupourbau** [ionic-team/ionic-framework#22903]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.5.0** (ionic-react)

**Current behavior:**
Animation between pages is not disabled when "animated" is set to false for IonRouterOutlet

**Expected behavior:**
Expecting no animation between pages when "animated" is set to false

**Steps to reproduce:**
ionic start myApp conference
Framework: React
npm i @ionic/react@latest @ionic/react-router@latest
add animated={false} to IonRouterOutlet in App.tsx
Alternate click on 'Skip' in tutorial page and 'show Tutorial' in tabs/schedule

**Ionic info:**
Ionic:

   Ionic CLI       : 6.12.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.4

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : not installed

System:

   NodeJS : v12.18.3 (/usr/local/bin/node)
   npm    : 7.5.2
   OS     : macOS Mojave

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/react@5.6.0-dev.202102101503.5fd1f35 @ionic/react-router@5.6.0-dev.202102101503.5fd1f35
```

**Comment by Aupourbau** [comment]
Working fine, thanks!

**Comment by Aupourbau** [comment]
> Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?
> 
> ```
> npm install @ionic/react@5.6.0-dev.202102101503.5fd1f35 @ionic/react-router@5.6.0-dev.202102101503.5fd1f35
> ```

Working fine, thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/22905, and a fix will be available in an upcoming release of Ionic Framework.
