### ISSUE TITLE
bug: Express style properties in the url don't get set in a tab component

### ISSUE THREAD

**Issue by claytongulick** [ionic-team/ionic-framework#22914]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When using vanilla js with ion-router and ion-tabs, the properties from the url are not getting set on the target component.

**Expected behavior:**

If I navigate to /somthing/:some_id/somewhere/:another_id, the tab component should forward some_id and another_id properties to the target component.

**Steps to reproduce:**

Set up routes, similar to:
```html
<ion-route url='/profiles/:profile_id' component='scene-profile'>
          <ion-route url='/projects' component="tab-profile-projects"></ion-route>
           ...
              
</ion-route>
```
Set up tabs, similar to:
```html
                <ion-tabs id="profile_tabs" style="background-color: var(--ion-color-light); ">
                    <ion-tab tab="tab-profile-projects" component='app-profile-projects'></ion-tab>
                    ...
                    </ion-tab-bar>
                </ion-tabs>
```

The component instantiated by app-profile-projects doesn't receive the profile_id property that's specified in the url.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
