### ISSUE TITLE
bug: geolocation service getCurrentPosition() does not response on Android

### ISSUE THREAD

**Issue by rbalet** [ionic-team/ionic-framework#22915]
# Bug Report

**Ionic version:**
[x] **5.31.1**

**Current behavior:**
using geolocation.getCurrentPosition() load infinitely on Android device when device location is disable

**Expected behavior:**
throw an error or empty location

**Steps to reproduce:**
1. Use the code provided and trigger the method with a button, for example
2. Deactivate smartphone location
3. Accept to share location if requested
4. any console.log won't never be triggered.

**Related code:**

```typescript
getPosition(): Promise<void> {
    return new Promise((resolve) => {
      this._geolocation
        .getCurrentPosition()
        .then((position) => {
          console.log('then')
          this.userPosition = {
            lng: position.coords.longitude,
            lat: position.coords.latitude,
          }
        })
        .catch(() => {
          console.log('catch')
          this.userPosition = null
        })
        .finally(() => {
          console.log('finally')
          this.onUserPositionChange.next(this.userPosition)
          resolve()
        })
    })
  }
```

**Other information:**
I did try to remove the finally option and to add the logic within the `catch` and the `then`.  
My installation
```
"dependencies": {
     ...
    "@ionic-native/geolocation": "^5.31.1",
},
"devDependencies": {
     ...
    "cordova-plugin-geolocation": "^4.1.0",
},
  "cordova": {
    "plugins": {
      "cordova-plugin-geolocation": {},
    }
 }

**Comment by EinfachHans** [comment]
This is not an Ionic Bug and has nothing to do with the Ionic Framework.

You should search for help in the Cordova Plugin Repository: https://github.com/apache/cordova-plugin-geolocation
