### ISSUE TITLE
feat: Preload Alerts and Dialogs

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/ionic-framework#22910]
I use the latest Ionic version (Generated with Ionic CLI) in Angular. I was not able to find a solution to preload Alert and Modal / Dialogs. This is very important to me (and surely for other developers too), because it broke the `Native Feeling`. If you click on a button that toggles a `Modal` or a `Alert` it happens on first toggle after Init, that they need 1 or 2 seconds to open.

And then it also needs about 1 seconds to load the icons as I discribed here: https://github.com/ionic-team/ionicons/issues/927

Any plans to make it possible to solve this?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework does not provide a built in utility for pre-loading, but our current recommendation is to place an instance of your component in the DOM to ensure that the necessary files are available on page load.

So for example, if you wanted to pre-load `<ion-modal>`, you would place an instance of `<ion-modal>` in `app.component.html`.
