### ISSUE TITLE
bug: ion button inside ion buttons disabled although never set disabled – react

### ISSUE THREAD

**Issue by mauriceackel** [ionic-team/ionic-framework#22913]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.0.7** ionic **react**

**Current behavior:**
If a button is rendered conditionally inside a toolbar using `IonButtons` and `IonButton`, a button that was never set disabled is suddenly disabled. It seems as if the `IonButtons` component keeps track of the index of a disabled button so if the buttons inside get changed, the disabled attribute is still set?!

**Expected behavior:**
Only the button that has a disabled property should be disabled.

**Steps to reproduce:**
Click on the arrow up/down button. The header buttons will change. Click on the cancel button.
Now, the arrow up/down button is disabled although it never was disabled and has no disabled attribute whatsoever.

**Related code:**
Sample application: https://react-6wf6u1.stackblitz.io

**Ionic info:**
See stackblitz

**Comment by mauriceackel** [comment]
I did some more testing. It seems as if you explicitly set `disabled={false}` it prevents the button from being wrongly disabled.
Nevertheless, I consider this behavior a bug as the button should not be disabled in the first place.

**Comment by mauriceackel** [comment]
@liamdebeasi I think I found the issue. It seems to be less of an issue with ionic and more of a thing with react. So it seems as if react will keep components alive on conditional rendering if they are of the same type. This is, unless you explicitly tell react that the elements are in fact different. You can do so by setting the key prop on the IonButtons. This makes react change its component tree on conditional rendering and correctly removes the disabled property.

I don't know how relevant this is then for the ionic project so feel free to close this issue.

**Comment by liamdebeasi** [comment]
Good catch! In this case I think it makes sense to close out this issue and just use the `key` property as you recommended. Thanks for the follow up!
