### ISSUE TITLE
feat: Elevation helper css classes.

### ISSUE THREAD

**Issue by y0nd0** [ionic-team/ionic-framework#22923]
# Feature Request

**Ionic version:**
- [x] **5.x**

**Describe the Feature Request**
I would be helpful if Ionic provides some css helper / class names to elevate (custom) elements. This adds a box-shadow like the card has.

**Describe Preferred Solution**
Ionic extends its [CSS Utilities](https://ionicframework.com/docs/layout/css-utilities) by the Elevation classes.

**Describe Alternatives**
Or if Ionic don't want to have that many elevation levels: Just provide one class name to have the Ionic like shadow (e.g. `ion-card`). 
But consider to add such levels (min 2 (3): None, Normal, High). For example for a hover / focus effect.
(You probably have better names for it. :) )

**Related Code**
Then we can just use e.g. 

```html
<!-- Some ideas / alternatives -->
<div class="ion-elevation">
<div class="ion-elevation-1">
<div class="ion-elevation-5">
<div class="ion-elevation-z5">
<div class="ion-elevation-none">
<div class="ion-elevation-small">
<div class="ion-elevation-regular">
<div class="ion-elevation-large">
<div class="ion-shadow">
<!-- ... -->
```

So finally we could have e.g. 4 types: `none` (to remove), `small`, `regular` (or without suffix), `large`. 

**Additional Context**

NOTE: It depends on mode (`ios` or `md`).

Examples of other frameworks:

- [Vuetify](https://vuetifyjs.com/en/styles/elevation/)
- [Angular Material](https://material.angular.io/guide/elevation)
- [Bootstrap](https://getbootstrap.com/docs/4.1/utilities/shadows/)
 
![image](https://user-images.githubusercontent.com/68586847/107883489-915d9300-6eef-11eb-88e9-db38c95bf435.png)

**Comment by liamdebeasi** [comment]
Thanks! I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/22844.
