### ISSUE TITLE
bug: Ionsegment not working as expected - fires inconsistent value

### ISSUE THREAD

**Issue by lemohammed** [ionic-team/ionic-framework#22926]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**

Using ion segment, the first button trigger is always undefined even though the 

**Expected behavior:**

The ionic segment button that was clicked should not become highlighted if the emitted event value from onIonChange event is not called. I am using the exact code snipet from the documentation 

**Steps to reproduce:**

create a useState value and setter, then call the setter when an onIonChange event is triggered if the event value is not undefined

**Related code:**

www.github.com/lemohammed/hackathon2021
```

 <IonSegment onIonChange={ (e) => { e.detail.value&&setFilter(e.detail.value); user&&getPosts(user)}}>
    <IonSegmentButton value="interests">
        <IonLabel>
            Select by <span className="major">Interest</span>
        </IonLabel>
    </IonSegmentButton>
    <IonSegmentButton value="major">
        <IonLabel>
            Select by <span className="major">Major</span>
        </IonLabel>
    </IonSegmentButton>
    <IonSegmentButton value="all">
        <IonLabel>
            Select <span className="major">All</span>
        </IonLabel>
    </IonSegmentButton>
</IonSegment>

```

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI : 6.12.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.13.1
   npm    : 6.14.8
   OS     : Windows 10```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is your repo public? I cannot access it.

**Comment by lemohammed** [comment]
Oops, please ignore that, it's a typo. I changed the code in my repo to ionbuttons instead of ionsegmentbuttons but the code snippet was exactly the same as I mention

**Comment by liamdebeasi** [comment]
Thanks. Could you please update your repo to include steps to reproduce as well as only the code required to reproduce the issue? I am unable to see the issue on my end.
