### ISSUE TITLE
feat: Integration of firebase for endless scrolling

### ISSUE THREAD

**Issue by FelixBrgn** [ionic-team/ionic-framework#22927]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
When subscribing to a collection with a lot of items loading times can become long. And you have to insert them manuly

**Describe Preferred Solution**
I know there's a way to do this manually but would be nice to have an integrated version that handles only getting a certain amount of items per time.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. We feel that Firebase integration is best done on a per-application basis, so we do not have plans to add Firebase integration at this time. For help implementing this solution in your app I recommend creating a post on our forums: http://forum.ionicframework.com/.
