### ISSUE TITLE
How to implement favorite/bookmarks in ionic5/Angular.

### ISSUE THREAD

**Issue by devsalimsulaiman** [ionic-team/ionic-framework#22920]
Hi. I am trying to implement a favorite/bookmarks page in ionic mobile app. It contains just texts. The pages are in an array of objects, so clicking on "add to favorite" button will push an object of {title: "page1", url: "/page1} into an array in a "my favorite" page where I can view them at the front end. I'm using Ionic5/Angular. After everything, when I refresh, it will not keep the pages in the favourite/bookmarks since I am not implementing a local storage functionality on them. So I need help on how to implement it and also be able to remove the added pages from the storage.

Thank you

**Comment by DwieDima** [comment]
You have to create CRUD operations for your favorites.
You can use here the storage plugin from capacitor.
Its a simple Key - Value Storage, where the value have to be saved as `string`.
There you can separate your `topics` by `key`. 
E.g. `{key: 'favorites', value: fav}` - for favorites.

You can save your array of objects to storage by using `JSON.stringify(yourArray)`
and retrieve by using `JSON.parse(yourArrayAsString)`.

I created a small example by using capacitor storage combined with rxjs for the CRUD operations inside a service.
Hope that helps.


```
import { from, Observable } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';
import { Plugins } from '@capacitor/core';

const { Storage } = Plugins;

export interface Bookmark {
  id: number;
  title: string;
  url: string;
}

export enum Key {
  FAVORITES = 'favorites'
}

export class StorageService {

addFavorite(favorite: Bookmark) {
    this.getFavorites().pipe( // get all favorites
      map(fav => {
        fav.push(favorite); // push new item to array
        return fav; // return updated favorites
      }),
      switchMap(fav => this.setFavorites(fav)) // replace updated favorites array with old
      );
  }

  getFavorites(): Observable<Bookmark[]> {
    const key = Key.FAVORITES;
    return from(Storage.get({key})).pipe(
      map(fav => fav ? JSON.parse(fav.value): []) // return json array of favorites
    );
  }

  getFavorite(id: number): Observable<Bookmark> {
    return this.getFavorites().pipe( // get all favorites
      map(fav => {
        const index = fav.findIndex(f => f.id === id); //find index of favorite
        return fav[index] // return single favorite by index
      })
    );
  }

  deleteFavorite(id: number) {
    return this.getFavorites().pipe(
      map(fav => {
        const index = fav.findIndex(f => f.id === id);
        return fav.splice(index, 1); //remove object inside array with given id
      }),
      switchMap(fav => this.setFavorites(fav)) // replace updated favorites array with old
    );
  }

  // like deleteFavorite()
  updateFavorite(favorite: Bookmark) {
    return this.getFavorites().pipe(
      map(fav => {
        const index = fav.findIndex(f => f.id === favorite.id);
        fav[index] = favorite;
        return fav;
      }),
      switchMap(fav => this.setFavorites(fav))
    );
  }

  // helper for parsing to storage
  private setFavorites(favorites: Array<Bookmark>) {
    const key = Key.FAVORITES;
    const value = JSON.stringify(favorites);
    return from(Storage.set({key, value}))
  } 

}

```

**Comment by devsalimsulaiman** [comment]
@DwieDima thank you very much!! Now I have a direction to follow because of this. I'm glad✌️
