### ISSUE TITLE
ionBlur and ionFocus acting reversed on ion-select element

### ISSUE THREAD

**Issue by aladearchives** [ionic-team/ionic-framework#22928]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

ionBlur triggers on ion-select when you focus, while ionFocus triggers on ion-select blur

**Expected behavior:**

ionFocus should be triggered when I enter an ion-select element, while ion-Blur should be triggered on remove from focus and not the other way around.
**Steps to reproduce:**

**Related code:**
TEMPLATE: 
    <ion-select (ionBlur)="runFunctionBlur()" (ionFocus)="runFunctionFocus()" placeholder="Select One">
      <ion-select-option value="f">Female</ion-select-option>
      <ion-select-option value="m">Male</ion-select-option>
    </ion-select>

CONTROLLER:
runFunctionBlur() {
console.log('I will only run on focus')
}

runFunctionFocus() {
console.log('I will only run on blur')
}

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
