### ISSUE TITLE
bug: thumbnail not being properly sized when slotted inside item

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#22935]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

The ionic docs says : 

> Thumbnails can be used by themselves or inside of any element. If placed inside of an ion-item, the thumbnail will resize to fit the parent component

But when a ion-thumbnail is inside a ion-item and slotted, it doesn't fit the ion-item, instead it forces its size to 56px which makes the ion-item height 56px.

![image](https://user-images.githubusercontent.com/15921402/108209864-18e31600-712b-11eb-810e-f2df93b5a367.png)

If we want to make the thumbnail smaller we can use the --size attribute, but it is overridden by the code above when slotted.

I add the size attribute : 
![image](https://user-images.githubusercontent.com/15921402/108209994-462fc400-712b-11eb-8c99-ad1340110887.png)

The ion-thumbnail size attribute is overridden by the slotted css : 

![image](https://user-images.githubusercontent.com/15921402/108210056-5d6eb180-712b-11eb-824c-615159b0df7c.png)

**Expected behavior:**

The size attribute shouldn't be overridden ?
Why force the height/width to 56px when slotted ?

**Steps to reproduce:**

Go to : https://ionicframework.com/docs/api/thumbnail 

* With your browser, inspect a thumbnail in the example in the top right corner
* Set a --size attribute to a value, for example 20px
* The thumbnail doesn't change its size

**Comment by dotNetkow** [comment]
To expand on this with a code example for reproduction, I also tried ion-item's min-height property to make the parent (ion item) larger. It didn't work though.

```css
ion-item {
  --min-height: 200px; // or any large size
}

ion-thumbnail {
  --size: 108px;  // this should take effect but doesn't
  --border-radius: 12px;
}
```

```html
<ion-item>
  <ion-thumbnail slot="start">
     <img src="path"/>
   </ion-thumbnail>
</ion-item>
```

**Comment by dotNetkow** [comment]
As a workaround, I directed set the height and width of the `ion-thumbnail`:

```
.thumbnail {
  height: 108px;
  width: 108px;
}
```

**Comment by idesignpixels** [comment]
Still an issue in Ionic 6.19.0
