### ISSUE TITLE
feat: Direct custom events.

### ISSUE THREAD

**Issue by y0nd0** [ionic-team/ionic-framework#22945]
What do you think about changing this:

```js
CustomEvent<SearchbarChangeEventDetail>
```

into this:

```js
SearchbarChangeEvent
```

by

```ts
interface SearchbarChangeEvent<T = { value: string | undefined }> extends CustomEvent<T> {}
// or (equal)
interface SearchbarChangeEvent<T = SearchbarChangeEventDetail> extends CustomEvent<T> {}
```

and all other CustomEvents.
For less and direct code.

It will change something like that: 

```ts
class MyComponent {
  public handleSearchInput(event: CustomEvent<SearchbarChangeEventDetail>): void {
    // ...
  }
}
```

into this:

```ts
class MyComponent {
  public handleSearchInput(event: SearchbarChangeEvent): void {
    // ...
  }
}
```

(Any better idea is welcome.)
Ionic 5

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a use case?

**Comment by liamdebeasi** [comment]
Actually I think this would be covered by https://github.com/ionic-team/ionic-framework/issues/22925.

**Comment by y0nd0** [comment]
The use case is already described above. Write less code, and have a direct event from the Ionic framework. No need for gernic type (CustomEvent<T>). 

In my experience, I have seen some developers (including myself) who used the event type `any` for the events. It's not clear how to use the Ionic event types.  ... With this change, it will get better.

In principle Ionic already has the interfaces of the `CustomEvent#detail`. Just wrap it, to have the full event type.
