### ISSUE TITLE
bug(router): redirect should trigger the `beforeEnter` of the target

### ISSUE THREAD

**Issue by vicb** [ionic-team/ionic-framework#22944]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.5.4**

**Current behavior:**

With this configuration:

```html
<ion-router use-hash="false">
  <ion-route url="/foo" component="x-foo"></ion-route>
  <ion-route url="/bar" component="x-bar"></ion-route>
  <ion-route url="/redir1" component="x-no"></ion-route>
  <ion-route-redirect from="/redir2" to="/bar"></ion-route-redirect>
</ion-router>

<script>
  route = document.querySelector('ion-route[url="/redir1"]');
  route.beforeEnter = () => {
    console.log("beforeEnter redirect");
    return {redirect: '/bar'};
  };
</script>
```

- `/redir1` is a `beforeEnter` redirect to `/bar`
- `/redir2` is a `<ion-route-redirect>` redirect to `/bar`

I would expect that the `beforeEnter` hook of `/bar` is triggered after a redirect from `/redir1` or `/redir2`.

It is not executed in any of the redirect.

**Expected behavior:**

The `beforeEnter` hook of `/bar` should be triggered after a redirect from `/redir1` or `/redir2`.

I think that it **must** be triggered for `/redir2` as there is no simple way to do it programatically.

Whether is should be for `/redir1` is probably disputable. You can always trigger it in the `beforeEnter` of the route `/redir1` itself. However I think that it should be done automatically to avoid surprises.

**Steps to reproduce:**

- Navigate to https://runkit.com/vicb/ionic-router-redirect
- Click on "endpoint" at the to open the app,
- Open the console
- Navigate to `/foo` or `/bar` (using the "go to ..." items) - you can see the `beforeEnter` logs in the console,
- Navigate to any of the redirect - as expected you are redirected to `/bar` but the `beforeEnter` is not executed 

**Other information:**

Semi-related issues:
- https://github.com/ionic-team/ionic-framework/issues/22936: the fix there does not fix the current issue,
- https://github.com/ionic-team/ionic-framework/issues/18687: I think that issue has been closed prematurely by @simonhaenisch and there are more things to discuss there.

**Comment by liamdebeasi** [comment]
Good catch! I am going to close this in favor of your first issue (https://github.com/ionic-team/ionic-framework/issues/22936) since the two are due to the same underlying bug.

**Comment by vicb** [comment]
@liamdebeasi maybe this should only be closed when the issue is actually fixed ?

I think I tried with your dev build and redirects were still not triggering the hooks.

**Comment by liamdebeasi** [comment]
The problem for both issues is that we are not checking for nav hooks on load. There is an extra case in my PR that I missed for the redirects, but the underlying issue is the same which is why I merged the two issues.

**Comment by liamdebeasi** [comment]
Reopening as per https://github.com/ionic-team/ionic-framework/pull/23123#issuecomment-812169509.

**Comment by liamdebeasi** [comment]
I am going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/23135. They are the same issue, but the new one has some additional information.

I believe we have talked about potential solutions on Slack, so we can track progress on #23135.
