### ISSUE TITLE
bug: ion-item background color does not match native iOS

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#22952]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

The `ion-item` on native iOS device does not match with apple item background color.

Ionic Default iOS List Item
![image](https://user-images.githubusercontent.com/61012396/108622934-004e6500-7477-11eb-88ed-1f88bf7404f7.png)

**Expected behavior:**

Apple Default List Item
![image](https://user-images.githubusercontent.com/61012396/108622807-2aebee00-7476-11eb-8d01-2cb3addc39cd.png)

**Steps to reproduce:**
Create a new ionic app and run on iOS devices

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.4
   @angular-devkit/build-angular : 0.1102.0
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.2.0
   @ionic/angular-toolkit        : 3.1.0

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.5 (/usr/local/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur
```

**Comment by BerkeAras** [comment]
@farisfaisalthena Could you show it on light mode too?

**Comment by farisfaisalthena** [comment]
![image](https://user-images.githubusercontent.com/61012396/108628807-cb9ed580-7497-11eb-94ef-897aa97fa4b9.png)

**Comment by BerkeAras** [comment]
@farisfaisalthena Thanks for your reply. The other thing is, that the native app background is #F2F2F7

**Comment by BerkeAras** [comment]
What we should do now is, changing the default background to #F2F2F7 and then changing the list-items to white (for light-mode).

**Comment by BerkeAras** [comment]
Here you can see the original colors from Apples Design Guideline
<img width="1514" alt="Bildschirmfoto 2021-02-21 um 16 57 16" src="https://user-images.githubusercontent.com/36629890/108630685-4c44de00-7466-11eb-9f83-88477170cbe8.png">

**Comment by liamdebeasi** [comment]
Thanks, we just fixed this. See https://ionicframework.com/docs/theming/dark-mode#ionic-dark-theme for the updated dark theme you can add to your app.

Specifically this:

```css
.ios body.dark ion-modal {
  --ion-background-color: var(--ion-color-step-100);
  --ion-toolbar-background: var(--ion-color-step-150);
  --ion-toolbar-border-color: var(--ion-color-step-250);
  --ion-item-background: var(--ion-color-step-150);
}
```

We only updated this for the modals because iOS is pretty inconsistent with the item background in non-modal contexts, so we decided it would be better to leave it as is for non-modals.
