### ISSUE TITLE
feat: AcionSheet/ActionAlert custom properties

### ISSUE THREAD

**Issue by SalahAdDin** [ionic-team/ionic-framework#22959]
# Feature Request

**Ionic version:**

[x] *5.x*

**Describe the Feature Request**

As we commented in a [pull request](https://github.com/ionic-team/ionic-framework/pull/18992#issuecomment-783986532), we find problems to test our mobile application using a [Cucumber](https://cucumber.io/)/[Appium](https://appium.io/) setup; in order to fight this problem we want to opt for using the [Cypress good practices](https://docs.cypress.io/guides/references/best-practices.html#How-It-Works) and a `data-cu` custom property to our component.

**Describe Preferred Solution**

So, at putting this kind of properties they should be rendered on the desired component in  order to be gotten by the automation test tool.

**Describe Alternatives**

Right now, we are approaching this  by adding either an available `id` property(for **IonAlert** and **IonAlert inputs**) or adding the custom property over the main parent(for **IonActionSheet**) in order to get a pivot from where we can get the required components easier, still, being trickier to do it.

**Related Code**

The aforementioned [pull request](https://github.com/ionic-team/ionic-framework/pull/18992#issuecomment-783986532) shows a good estimated code to use here.

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/18992, and this feature will be available in an upcoming release of the Ionic Framework v6 beta.
