### ISSUE TITLE
bug: ion-datetime wrong height/padding 

### ISSUE THREAD

**Issue by MaximS** [ionic-team/ionic-framework#22954]
# Bug Report

**Ionic version:**
[x] **5.5.2**

**Current behavior:**
If `ion-datetime` is used in a `ion-row` side-by-side with `ion-input` then it appers misaligned vertically. Entire `ion-item` has a height larger than a height of a corresponding `ion-item` with `ion-input`.

**Expected behavior:**
`ion-datetime` should have the same height as `ion-input`

**Steps to reproduce:**
```
          <ion-col size="6">
            <ion-item>
              <ion-label position="floating">Date and time</ion-label>
              <ion-datetime displayFormat="DD.MM.YYYY HH:mm" formControlName="start"></ion-datetime>
            </ion-item>
          </ion-col>
          <ion-col size="6">
            <ion-item>
              <ion-label position="floating">Caller Id</ion-label>
              <ion-input formControlName="callerId"></ion-input>
            </ion-item>
          </ion-col>
```
Experimentally found padding to solve the problem:
```
ion-datetime {
    --padding-bottom: 10px;
    --padding-top: 7px;
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. We released Ionic 6 in December of 2021, but it looks like we missed this issue when closing out resolved tickets. In Ionic 6, the datetime component is now rendered inline. You can set the padding directly by targeting `ion-datetime`. Please see https://ionicframework.com/docs/api/datetime for the full documentation.

I am going to close this as the reported issue has been resolved with this new architecture.
