### ISSUE TITLE
bug: App Crashes On Galaxy Tab A (Version 10 Android)

### ISSUE THREAD

**Issue by BartolomeoItaliano** [ionic-team/ionic-framework#22950]
**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
App Crashes, if two ion tabs clicked simultaneously.

**Expected behavior:**
One of two tabs will be opened

**Steps to reproduce:**
1. Create Ion Tabs With At least 2 tabs
2. Open App On Galaxy Tab A (Version 10 Android)
3. Click simultaneously (with two fingers) on both tabs.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
