### ISSUE TITLE
feat: Overlaying Status Bar

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#22966]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

There should be an option to set for status bar to overlay content on the status bar on iOS. Because if i dont add `ion-header` to that page, on iPhone X and above will overlay the content behind the status bar. For cordova there's a config that can be done on the config.xml to fix this issue, but not for capacitor. Screenshot below:

Cordova
![image](https://user-images.githubusercontent.com/61012396/108959630-9ff63800-76af-11eb-86aa-34dc8e4c82ed.png)

Capacitor
![image](https://user-images.githubusercontent.com/61012396/108959647-a84e7300-76af-11eb-98b8-aa0573ef7fae.png)

**Describe Preferred Solution**

It would be ideal to add something like `<ion-content [overlayStatusBar]="false">`

**Comment by BerkeAras** [comment]
@farisfaisalthena
Using the Capacitor API StatusBar you can change the behavior:
```js
StatusBar.setOverlaysWebView({
     overlay: false
});
```
For more information just see here: [capacitor/apis/staturbar](https://capacitorjs.com/docs/apis/status-bar)

**Comment by farisfaisalthena** [comment]
Its only for android actually

**Comment by BerkeAras** [comment]
@farisfaisalthena Set `--ion-safe-area-top` to `0`. This should work too.

**Comment by farisfaisalthena** [comment]
But that will still overlay right it wont have the characteristics like the cordova screenshot of mine above right

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you clarify the issue you are running into? You should be able to set the following CSS on `ion-content` to account for the statusbar:

```css
ion-content {
  --padding-top: var(--ion-safe-area-top);
}
```

**Comment by farisfaisalthena** [comment]
![image](https://user-images.githubusercontent.com/61012396/109019757-3fd5b500-76f4-11eb-9ce8-b096b9ddd177.png)

The issue is still the same. the issue is that when i have no `ion-header` on that page and when i scroll down it overlays my status bar. I believe it should not overlay the status bar like the cordova screenshot i provided to u. The cordova screenshot also does not have `ion-header` but it will still not overlay with status bar

**Comment by liamdebeasi** [comment]
What is the cordova config you are using?

**Comment by farisfaisalthena** [comment]
on config.xml `<preference name="StatusBarOverlaysWebView" value="false" />` but when i check for capacitor the `StatusBarOverlaysWebView` is only for android compared to cordova which works for both

**Comment by liamdebeasi** [comment]
Thanks for the clarification. I think this is out of scope for Ionic Framework, which is just the UI layer. We do not have control over how the WebView itself overlays the Status Bar. I recommend opening an issue on https://github.com/ionic-team/capacitor.

I am going to close this as there is nothing actionable to be done in Ionic Framework right now.
