### ISSUE TITLE
bug: Ripple effect on a <ion-button filled="outline"> doesn't show properly

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#22969]
**Ionic version:**
[x] **5.x**

**Current behavior:**
The ripple effect doesn't fill the whole available space, leaving a blank line

![outline-button](https://user-images.githubusercontent.com/15921402/109030804-6bd94200-76c4-11eb-92bd-263f31d8549d.png)

**Expected behavior:**
It should fill the white space

**Related code:**
https://stackblitz.com/edit/ionic-v5-ripple-button-outline-bug?file=src/app/app.component.html

**Comment by liamdebeasi** [comment]
Thanks for the issue. What browser are you testing this on? I cannot reproduce this on Chrome 88 or Safari 14

**Comment by Yohandah** [comment]
I can't reproduce it either this morning. I don't recall my Chrome updating tho ... and I had this bug for two days straight, and it was showing in the stackblitz as well ... weird. Sorry for the issue have a great day!
