### ISSUE TITLE
bug: useParams hook used in Grid layout returning wrong value

### ISSUE THREAD

**Issue by rluttikhuizen** [ionic-team/ionic-framework#22975]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
We have a grid layout using an IonGrid with 3 columns: a menu column on the left, the main content in the middle, and detail content in the right column. We use the useParams hook to determine the resource id's to retrieve the correct data from the backend and show the correct data in the main and detail columns. When clicking the browser back button, followed by a browser forward button (e.g. in Chrome), the useParams hook returns the wrong resource id: the value returned by the useParams hook does not match the id from the current URL in the browser address bar. This bug happens for the main (middle) column, while the detail (right) column correctly determines the resource id using the useParams hook. This causes the middle column to be out of sync with the detail column.

For example: After doing a browser back and browser forward, the current URL in the browser address bar is http://localhost:8100/main/topics/2/explanation (where "2" is the topic_id), while the useParams hook returns "1" as value for topic_id in the middle column. The middle column in our example shows topic 1, while the detail column shows details about topic 2 since useParams for that column has the correct topic id.

**Expected behavior:**
We expect the useParams hook to retrieve the resource id that matches the current value of the URL as shown in the browser address bar.

**Steps to reproduce:**
See https://codesandbox.io/s/nb1q3 for an example.

Steps to reproduce:

1. Click on "Go to dashboard to view topics".
2. Click on "Topics overview" from the menu (left column). Click on "Go to Topic 1" from the Topics Overview page (middle column). Click on "Show Topic Explanation" from the Single Topics page (middle column).
3. Click on "Topics overview" from the menu (left column). Click on "Go to Topic 2" from the Topics Overview page (middle column). Click on "Show Topic Explanation" from the Single Topics page (middle column).
4. Click on the browser back button. Click on the browser forward button.
5. Now the topic id from the useParams hook has the wrong value: 1 while it should be 2.

**Related code:**
See https://codesandbox.io/s/nb1q3

**Other information:**
See attached screen recording in separate comment showing the issue.

**Ionic info:**

Ionic:

   Ionic CLI       : 6.12.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.4

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.4.6

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.0.0

System:

   NodeJS : v14.15.3 (/usr/local/Cellar/node@14/14.15.3/bin/node)
   npm    : 6.14.9
   OS     : macOS Big Sur

**Comment by rluttikhuizen** [comment]
https://user-images.githubusercontent.com/5320983/109292765-2aaf7200-782b-11eb-975a-49c84449e0f3.mov

Video showing the issue

**Comment by rluttikhuizen** [comment]
Related to #22978

**Comment by liamdebeasi** [comment]
Thanks for the issue. Have you tried this without Ionic React? The `useParams` hook is something you import from `react-router` directly, so we do not have control over that.

**Comment by rluttikhuizen** [comment]
Hi @liamdebeasi ,

Thank you for the reply.
With plain React (without Ionic React), the useParams hook returns the correct value. 
I have created another sandbox here: https://codesandbox.io/s/react-useparams-in-grid-0e0w8 that shows this.

Thx, 

Ronald

**Comment by rluttikhuizen** [comment]
By the way, when creating the React example (without using Ionic React) as mentioned above, I noticed that instead of having a separate Router for the middle column and separate Routes for the 3rd column, the Router can also be made the parent of the entire Grid.

When I use that approach (see new sandbox project here: https://codesandbox.io/s/ionic-react-useparams-in-grid-possible-fix-g9x7s), it looks like the useParams hook returns the correct value. (Both in the plain React project as well as in the Ionic React project.)

Should we use the Router (IonRouterOutlet) in such a way then? So as parent element of the Grid as shown in the Grid.tsx file in https://codesandbox.io/s/ionic-react-useparams-in-grid-possible-fix-g9x7s?

**Comment by liamdebeasi** [comment]
Yeah, I would say stick with the single `IonRouterOutlet`. The moment you add nested `IonRouterOutlets`, things can get messy.

Does adding the single outlet resolve the issue for you?

**Comment by rluttikhuizen** [comment]
Ok, thanks! 

It looks like having a single `IonRouterOutlet` resolves the issue. It solves the issue in the sandbox app, we need to retest our main App to see if it resolves the issue there as well, but an initial smoketest looks good!

The main thing that we are still unsure of, is how to make use of `IonPage` in the grid:

* If the `Grid.tsx` has an `IonPage` wrapping the `IonRouterOutlet`, do we also need an `IonPage` as top-level container in the `tsx` that we display in the 2nd column of the Grid? (e.g. in `SingleTopic.tsx`). That way we have a nested `IonPage` of `SingleTopic.tsx` within the `IonPage` of the `Grid.tsx`.
* Same for the content we display in the 3rd (detail) column. It seems if we add an IonPage to those components, the grid won't work in the sense that one of the 2 columns in invisible.

**Comment by liamdebeasi** [comment]
For any components you want to have transitions for, you will need to use `IonPage`. It sounds like you just want the components in the 2nd and 3rd columns to appear, so you might be able to get away with not having `IonPage` in those.

**Comment by rluttikhuizen** [comment]
Thanks for the reply @liamdebeasi.

We will look into whether we need an `IonPage` in the components that we load into the 2nd and 3rd column of the Grid.

The issue with the `useParams` hook is resolved by wrapping the Grid in an `IonPage` and having a single `IonRouterOutlet` spanning the 2nd and 3rd column.
