### ISSUE TITLE
bug: placeholder types not compliant in ionic / react

### ISSUE THREAD

**Issue by HagenMorano** [ionic-team/ionic-framework#22976]
# Bug Report

**Ionic version:**
see below

**Typescript version:**
"typescript": "^4.1.3",

**Current behavior:**
When trying to apply properties of type `JSX.IonInput` to an `<IonInput />`, there is a type error (`Types of property 'placeholder' are incompatible.`)

**Expected behavior:**
There should be no error.

**Steps to reproduce:**
1. Create new variable of type `JSX.IonInput`
```const props: JSX.IonInput = { };```
2. Create new Element and apply props:
```<IonInput {...props} />```

**Related code:**
```
import { JSX } from '@ionic/core/dist/types/components';
import { IonInput } from '@ionic/react';
import React from 'react';

const ExploreContainer: React.FC = () => {
  const props: JSX.IonInput = {};
  return (
    <IonInput {...props} />
  );
};
```

**Other information:**
_Identified problem:_
`placeholder` in `interface HTMLAttributes` located in `node_modules/@types/react/index.d.ts` is not compliant with `placeholder` in  namespace `LocalJSX` `interface IonInput` located in `node_modules/@ionic/core/dist/types/components.d.ts`

(one is `undefined | string` other is `undefined | string | null`)

_Workaround:_
`const props: Omit<JSX.IonInput, 'placeholder'> = { };`

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.9.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.5.4

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.3 (/usr/local/bin/node)
   npm    : 6.14.9
   OS     : Linux 5.4
```

**Additional question:**
Is there a specific reason why `placeholder` is nullable?

**Comment by willmartindev** [comment]
Thank you for this issue! A fix for this will be available in Framework v6.
