### ISSUE TITLE
bug: cannot use IonItem with IonRouter on React-Tests

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#22986]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Cannot use IonItem with IonRouter on React Tests at "/packages/react/test/test-app/". Getting error: ```Property 'routerAnimation' is missing in type '{ children: Element[]; button: true; }' but required in type 'Pick<IonItem, "color" | "button" | "disabled" | "lines" | "mode" | "href" | "routerAnimation" | "rel" | "target" | "download" | "type" | "detail" | "detailIcon">'.  TS2741```

**Expected behavior:**
IonRouter should get the property routerAnimation.

**Steps to reproduce:**
See steps: https://github.com/ionic-team/ionic-framework/issues/22342#issuecomment-723108406

**Related code:**
https://github.com/ionic-team/ionic-framework/tree/master/packages/react/test/test-app

**Other information:**
Issue #22342 cannot be fixed without testing and fixing this issue.. 

**Ionic info:**
Cannot give ionic info because of working in the Source Code of Ionic Framework.

**Comment by liamdebeasi** [comment]
Sorry, the `react/test/test-app` is old. Can you give this a try with `react-router/test/test-app`?

**Comment by BerkeAras** [comment]
@liamdebeasi Unfortunately I just got an error and I still can't fix it :(
1. `Error: Cannot find module 'react-dev-utils/getPublicUrlOrPath'`
2. `npm ERR! enoent ENOENT: no such file or directory, stat '/Users/berkearas/Desktop/ionic-framework/packages/react/ionic-react-5.5.0.tgz'`

**Comment by liamdebeasi** [comment]
For 1) make sure you have run `npm install` first. 

For 2) follow these steps:

1. In the test-app directory, change `ionic-react-5.5.0` in both `package.json` and `build.sh` to `ionic-react-5.5.5`. This assume you have the latest `master`.
2. Run `./build.sh`. This assumes you have installed dependencies in the `react` directory first.

The steps here are not the most intuitive, so I can document these somewhere in the readme.

**Comment by BerkeAras** [comment]
@liamdebeasi It works now. It has to be like this:
1. `sh build.sh` in /packages/react-router/test-app/
2. `npm install` in /packages/react-router/test-app/
3. `npm start` in /packages/react-router/test-app/

Unfortunately on my MacBook `npm install` did not work, but `npm install --force`.
Thanks for helping, I can now focus on #22342
