### ISSUE TITLE
feat: capture groups and back references in ion-route-redirect

### ISSUE THREAD

**Issue by simonhaenisch** [ionic-team/ionic-framework#22996]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**

The use case for this is fairly advanced: we need a route guard for all routes if there's no authenticated user, except there's a few routes that we need to allow even for unauthenticated users. It's already possible to allow those anonymous routes by defining a route redirect to themselves before the route guard (using Stencil btw):

```tsx
const Router = ({ user }) => (
  <ion-router>
    {!user && [
      // this redirects every route to `/login` except `/reset-password`
      <ion-route-redirect from="/reset-password" to="/reset-password" />,
      <ion-route-redirect from="*" to="/login" />,
    ]}

    <ion-route url="/login" component="page-login" />
    <ion-route url="/reset-password" component="page-reset-password" />
  </ion-router>
)
```

But now we also want to put a token into the reset route as a route param:

```tsx
<ion-route url="/reset-password/:token" component="page-reset-password" />
```

The only way to make that "allowed route" work now is to inject the exact token value into the route redirect. I can catch the route with a wildcard, but i can't redirect it without losing the token.

```tsx
<ion-route-redirect from="/reset-password/*" to="/reset-password/:token" />
```

This will redirect `/reset-password/foo` to `/reset-password/:token` (i. e. `:token` literally in the URL).

**Describe Preferred Solution**

```tsx
<ion-route-redirect from="/reset-password/*" to="/reset-password/$1" />
```

**Additional Context**

A work-around is to use query params instead, but that's not really the preferred solution.

**Comment by liamdebeasi** [comment]
Thanks for the report. There has not been much support for this from the community since the issue was opened. Due to this, the team does not have plans to implement this in the immediate future. I am going to close this for now. However, we may re-consider this feature in the future if community support grows.
