### ISSUE TITLE
Modal UI input not binding to properties in controller

### ISSUE THREAD

**Issue by DeanWilliamMills** [ionic-team/ionic-framework#22995]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When opening a modal, bindings does not work.

![image](https://user-images.githubusercontent.com/12442560/109622019-4f199000-7b44-11eb-8ed1-840549ce381b.png)

![image](https://user-images.githubusercontent.com/12442560/109622052-58a2f800-7b44-11eb-8afb-4176883dbcc3.png)

![image](https://user-images.githubusercontent.com/12442560/109621902-36a97580-7b44-11eb-83f8-2dafd854be3e.png)

**Expected behavior:**
The input elements should bind with the properties on the controller

**Steps to reproduce:**
Open a modal which has an input. Enter values into the input, then the property on the controller does not have the value entered into to input field even though the input element has a `[(ngModel)]` set to the controller property

**Related code:**

Modal UI:
```
<ion-item>
          <ion-label position="stacked">Name</ion-label>
          <ion-input [(ngModel)]="name"></ion-input>
        </ion-item>
```

Modal Controller:
```
name: string = "Test";
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.4 (C:\Users\deanw\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.4
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.0

Utility:

   cordova-res (update available: 0.15.3) : 0.8.1
   native-run (update available: 1.3.0)   : 0.3.0

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by DwieDima** [comment]
you need to declare your variable `test` as input.

```
// Data passed in by componentProps
  @Input() name: string = 'test';
```

you can find these examples in the [docs for ion-modal](https://ionicframework.com/docs/api/modal)

**Comment by DeanWilliamMills** [comment]
Thanks for the reply.

I managed to solve the issue:
I must import the modal's `Module` into the parent's `Module` for the 2-way bindings to work.
