### ISSUE TITLE
bug: Side menu always refreshing and doesn't go to page

### ISSUE THREAD

**Issue by MInesGomes** [ionic-team/ionic-framework#23003]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**
Side menu always refreshing and doesn't go to page

**Expected behavior:**
Side menu going to page

**Steps to reproduce:**
Like my current app stop working because of ngcc problems,
I decided to create a new app with ionic start and choose side menu.

$Ionic start (side menu)
$ ionic serve.
If you click in any of the menu items sometimes the refresh is really fast and you don't notice. but always stays in the inbox, never goes to any other items like outbox, favorites, ...

and sometimes even appears a page **A problem repeatedly occurred with** and there is no error in the console.

`<!-- Title of the page that was showing right before the crash. --><title>Ionic App</title>`
<p class="error-message">A problem repeatedly occurred with <br> “‎localhost:8101/folder/Inbox”</p>

```
  <form class="suggestion-form" method="GET" action="reload-crashed-pages:">
                <!-- Button to reload affected webpages. -->
                <input type="submit" value="Reload Web Page">
   </form>
```

**Related code:**

[https://github.com/MInesGomes/testSideMenu](https://github.com/MInesGomes/testSideMenu)

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 6.12.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.5
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.0

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.0.0

System:

   NodeJS : v12.18.2 (/usr/local/Cellar/node@12/12.18.2/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What browser + version are you testing this on? I testing this on Chrome 88 and Safari 14.0.1 and cannot reproduce this issue.

**Comment by MInesGomes** [comment]
On Safari Version 14.0 (15610.1.28.1.9, 15610) doesn't navigate and refreshes.
On Google Chrome Version 88.0.4324.150 (Official Build) (x86_64) does navigate and has the normal procedure.

**Comment by liamdebeasi** [comment]
Thanks! So Safari 14.0 had a bug in the `delegatesFocus` API that caused this crash to happen. To fix this, you will need to update to the latest stable version of Safari. Please see https://github.com/ionic-team/ionic-framework/issues/21939#issuecomment-694259307 for more information.
