### ISSUE TITLE
bug: [angular] cursor doesn't move in <ion-input> in responsive form after setValue() for form control and setting selectionStart/End for input

### ISSUE THREAD

**Issue by lvalerij** [ionic-team/ionic-framework#23016]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
In responsive form there is <ion-input> and in input's handler I change value of the form control (as an example setting "!" at the end after key pressed). Then I move the cursor to the beginning via selectionStart/selectionEnd properties of input. But the cursor actually goes to the end despite selectionStart/End.

**Expected behavior:**
I expect that <ion-input> works as plain html input - if I have plain html input and change in input's handler form control value via setValue() and then move the cursor to the beginning via selectionStart/End, it works perfectly. 

**Steps to reproduce:**
1. In component's html file create <ion-input> with the handle on (ionInput).
2. In component's ts file create a handler for (ionInput). In the handler change form controls value by placing "!" at the end of event.target.value.
3. In component's ts file change input's selectionStart/End to 0.

**Related code:**

home.component.html
```
<form [formGroup]="form">
  <ion-item>
    <ion-label>Amount: </ion-label>
    <ion-input
      (ionInput)="amountHandler($event)"
      formControlName="amount"
    ></ion-input>
  </ion-item>
</form>
```

home.component.ts
```
export class HomeComponent {
  form = new FormGroup({
    amount: new FormControl(''),
  });
  constructor() {}

  amountHandler(event: any) {
    this.form.get('amount').setValue(event.target.value + '!');
    event.target.firstChild.selectionStart = 0;
    event.target.firstChild.selectionEnd = 0;
    // event.target.selectionStart = 0;
    //event.target.selectionEnd = 0;
  }
}
```

**Other information:**
1. It doesn't work for both cases when either changing initial wrapper ion-input's selectionStart/End or its child.
2. If setValue (or as alternative patchValue) wasn't used before moving the cursor, moving the cursor via selectionStart/End works perfectly.

**Comment by liamdebeasi** [comment]
Can you reproduce this in an Ionic starter app? I cannot see this happening on my end.

**Comment by lvalerij** [comment]
1. I created Ionic app -  ionic start myApp blank --type=angular
2. I changed 'home.module.ts' to: 
```import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HomePage } from './home.page';
import { HomePageRoutingModule } from './home-routing.module';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    IonicModule,
    HomePageRoutingModule,
  ],
  declarations: [HomePage],
})
export class HomePageModule {}
```
3. I changed 'home.page.ts' to: 
```
import { Component, ApplicationRef } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
})
export class HomePage {
  form = new FormGroup({
    ionInput: new FormControl(''),
    plainInput: new FormControl(''),
  });
  constructor(private appRef: ApplicationRef) {}

  ionInputHandler(event: any) {
    this.form.get('ionInput').setValue(event.target.value + '!');
    const input = <HTMLInputElement>(
      document.getElementById('ionInput').firstChild
    );
    this.appRef.tick();
    input.selectionStart = 0;
    input.selectionEnd = 0;
  }
  inputHandler(event: any) {
    this.form.get('plainInput').setValue(event.target.value + '!');
    event.target.selectionStart = 0;
    event.target.selectionEnd = 0;
  }
}
```
4. I changed 'home.page.html' to: 
```
<form [formGroup]="form">
  <ion-item>
    <ion-label>Ion-input: </ion-label>
    <ion-input
      (ionInput)="ionInputHandler($event)"
      formControlName="ionInput"
      id="ionInput"
    ></ion-input>
  </ion-item>
  <ion-item>
    <label>Plain input: </label>
    <input (input)="inputHandler($event)" formControlName="plainInput" />
  </ion-item>
</form>
```

**Comment by liamdebeasi** [comment]
Apologies for the delay, I am able to reproduce the behavior you are describing. So I think what is happening here is there is a rendering tick between when you set the form value via `setValue` and when the internal Web Component has its value changed, causing a re-render. During this time you set `selectionStart` and `selectionEnd`, but when the Web Component re-renders, this selection is cleared.

While I can understand that this behavior is not desirable, I don't think this is a bug in Ionic Framework as it has more to do with the component being updated async.

Luckily, there is an easy workaround. I found that your code works if you use a `requestAnimationFrame`, causing the selection to be changed after the component re-renders:

```js
requestAnimationFrame(() => {
  input.selectionStart = 0;
  input.selectionEnd = 0;
});
```

Hope this helps. Thanks!
