### ISSUE TITLE
bug: [react] broken routing with concurrent conditionally rendering routes

### ISSUE THREAD

**Issue by mauriceackel** [ionic-team/ionic-framework#23012]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x** (5.5.5)

**Current behavior:**
When having two (or more) routes inside a router outlet of an IonTab (possibly this is not limited to IonTab), that conditionally render a page as shown in the docs, when they change their rendered component, the pages end up in a broken state, leading pages being displayed wrongly. (See attached video)

https://user-images.githubusercontent.com/20804369/109847453-7c9f3000-7c4f-11eb-98ac-de8f6c700896.mov

**Expected behavior:**
Conditionally rendered routes should continue to work as before after they change what they render.

**Steps to reproduce:**
See the video and the explanations in the repo

**Related code:**
Please find the code to reproduce this in the following repo: https://github.com/mauriceackel/react-routing-issue-example/tree/concurrent-conditional-routes
**IMPORTANT: Make sure you use the 'concurrent-conditional-routes' branch**

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is the same underlying bug as https://github.com/ionic-team/ionic-framework/issues/22586#issuecomment-745361048. I am going to close this in favor of the linked issue since we have been tracking progress there.
