### ISSUE TITLE
ionScrollStart/End to emit full details to avoid using ionScroll

### ISSUE THREAD

**Issue by Tommertom** [ionic-team/ionic-framework#23025]
# Feature Request
ionScrollStart should emit ScrollDetail  instead of ScrollBaseDetail in order to have less code to capture the starting position of the scroll. This to help building scroll related UI features such as reported here https://forum.ionicframework.com/t/ionscroll-issue-in-ionic-4/206005. Basically on scrollStart (and End), having full access to the scroll position will assist in making fancy UI features with less code (including toggling the scrollEvents property to avoid a performance hit having to use ionScroll all the time).

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**
See earlier description

**Describe Preferred Solution**
Code: https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/content/content.tsx
Relates to method onScrollStart() that should emit this.detail (with isScrolling flag updated) instead of only a boolean wrapped in an object. This comes at no additional cost for the user and adds to the benefit of the developer. Same to onScrollEnd.

**Describe Alternatives**
Now, the developer needs to subscribe to the ionScroll and take one element and then resubscribe at scrollEnd. Next, toggle ionScroll to avoid performance hit. This is boilerplate.

**Related Code**
See forum link.

**Additional Context**
See forum link https://forum.ionicframework.com/t/ionscroll-issue-in-ionic-4/206005

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is that `ionScrollStart` and `ionScrollEnd` are not actually scroll events, where as `ionScroll` is a scroll event which is why `ionScroll` has the scroll information and the other events do not. That being said, you should be able to check the scroll position already.

Can you try the following and let me know if this works:

```js
// onScrollStart gets called when the ionScrollStart event happens
const onScrollStart = async () => {
  // ionContent is a reference to <ion-content>` in the DOM.
  const innerEl = await ionContent.getScrollElement();

  /** 
   * From here you can access innerEl.scrollTop or
   * any other properties.
   */
}
```

**Comment by Tommertom** [comment]
Hi @liamdebeasi 

Thx. This will work. 

The question though is whether you have considered enriching the API with the suggestion. From the code I can see the onStart could be changed to receive this.detail after the update of it (  updateScrollDetail(this.detail, this.scrollEl, ts, shouldStart); - line 167) So saving some code. Next. the onEnd could be emitting the detail as is for that moment, knowing the onScroll updates it.

Or is there a reason why you don't want 
`   if (shouldStart) {
      this.onScrollStart();

    }`

placed into that part of the code?

**Comment by liamdebeasi** [comment]
We could pass in the event for `ionScrollStart`, but we wouldn't be able to add it to `ionScrollEnd`, so I think it would be confusing to make this change for one event but not the other.

**Comment by Tommertom** [comment]
Good point. Let's close it for now, unless someone else has a strong point.
