### ISSUE TITLE
bug: picker column does not account for pressing when computing velocity

### ISSUE THREAD

**Issue by devinova** [ionic-team/ionic-framework#23034]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
The component picker-column does not select the correct element, as it is not waiting for the user to hold the touch or click for a while after a slide.

**Expected behavior:**

**Steps to reproduce:**
1 - Access the official website: https://ionicframework.com/docs/api/picker

2 - Move the column quickly but keep the mouse pressed and see that when you release the mouse button it will not select the element that is showing why it is still calculating the initial drag speed, but that speed should no longer exist.

https://user-images.githubusercontent.com/38766885/110809922-13797700-8264-11eb-8751-10370796c1d3.mov

**Other information:**
I also tested it directly on the official Ionic framework project and the problem still persists. I made a temporary correction, but I would like to know if there is already an official solution to this issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue. We are tracking all datetime/picker issues in https://github.com/ionic-team/ionic-framework/issues/16630, so I will add your issue there.

**Comment by devinova** [comment]
Thanks for the feedback. I would like to take one more question, I downloaded the official project and made a correction for this problem, how do I make a pull request with this correction?

**Comment by devinova** [comment]
Thanks for the feedback. I would like to take one more question, I downloaded the official project and made a correction for this problem, how do I make a pull request with this correction?

**Comment by liamdebeasi** [comment]
Check out our Contributing Guide: https://github.com/ionic-team/ionic-framework/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request

Let me know if you have any questions!

**Comment by liamdebeasi** [comment]
Hi everyone,

In the next major version of Ionic we will be introducing a new picker component where this issue is resolved: https://github.com/ionic-team/ionic-framework/pull/28689

I am going to close this since the work required to resolve this issue has been merged. Please let me know if there are any questions.
