### ISSUE TITLE
bug: iOs bug keyboard resize

### ISSUE THREAD

**Issue by iTEEECH** [ionic-team/ionic-framework#23038]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
I created a basic method with a switch for some pages where I switch to Keyboard Resize mode : none because I don't want iOs to redefine the height of my images when I open the keyboard. Problem when I switch on a page in Native mode and I open the keyboard and I go back to a page in "none" mode. I have the view that does not redefine. My bar stays in the middle of the screen and I have a white space where the keyboard was displayed. 

https://ibb.co/BgyV0hM

**Expected behavior:**
The height is redefined automatically.

***Steps to reproduce:***

Switch page None mode to Native or Ionic mode to native and native to none mode
```
this.router.events
      .pipe(filter(route => route instanceof NavigationEnd))
      .subscribe((route: NavigationEnd) => {
        switch (route.url) {
          case 'xxxx': {
            this.keyboard.setResizeMode(KeyboardResizeMode.None);
            break;
          }
          default: {
            this.keyboard.setResizeMode(KeyboardResizeMode.Native);
            break;
          }
        }
      });
```
**Ionic info:**
```
Ionic:

   Ionic Framework : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1200.0-next.3
   @angular-devkit/schematics    : 12.0.0-next.3
   @angular/cli                  : 12.0.0-next.3
   @ionic/angular-toolkit        : 3.1.0

Cordova: last version


System:

   NodeJS : v14.15.4 (/usr/local/bin/node)
   npm    : 6.14.9
   OS     : macOS Catalina
```

**Comment by BerkeAras** [comment]
@iTEEECH If you switch the resizeMode **while the keyboard is open**, your app thinks that the resized-height is the standard size (I have the same issue). Resize <ins>after closing the keyboard.</ins> The correct Capacitor Event is:
```js
Keyboard.addListener('keyboardDidHide', () => {
	console.log('keyboard did hide');
	// Resize now
});
```

**Comment by iTEEECH** [comment]
Hello @BerkeAras, Thank you for your answer. I found a solution. I put in Native and I edit directly in css with rem and not vh.
