### ISSUE TITLE
bug: IonSegment not working when setting initial value

### ISSUE THREAD

**Issue by rluttikhuizen** [ionic-team/ionic-framework#23048]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
We use an `IonSegment` with 2 `IonSegmentButtons` in our Ionic React project to toggle between 2 lists of values. When the user clicks on segment button 1, we display value list 1. If the user clicks on segment button 2, we display value list 2. This works as expected. See the example here: https://codesandbox.io/s/segment-no-default-value-ld61l

We would also like to have segment button 1 selected by default and display value list 1 whenever the page opens (i.e. when a user navigates to the page). We do this by setting the `value` property of the `IonSegment` to the `value` property of the first `IonSegmentButton`. This causes the initial state of the page to be as expected: `IonSegmentButton` 1 is selected and value list 1 is displayed. However, if the user clicks on (another) segment button, the wrong segment button is selected, and the wrong value list is displayed. We also see that the onIonChange in this case is fired 4x when clicking a segment button once. See the example here: https://codesandbox.io/s/segment-with-default-value-ucobg

**Expected behavior:**
Expected behavior is that setting an initial value on an `IonSegment` works, and that subsequent IonSegmentButton clicks fire the onIonChange event once and the correct value list is displayed.

**Steps to reproduce:**
See https://codesandbox.io/s/segment-with-default-value-ucobg for an example of an `IonSegment` where the initial value is set, the initial state is ok, but subsequent clicks on `IonSegmentButtons` have the wrong behavior.

See https://codesandbox.io/s/segment-no-default-value-ld61l for an example where the same `IonSegment` is working ok on `IonSegment` click when we don't set the initial value. (Although we would like to set the initial value ;)). 

**Related code:**

See: 

https://codesandbox.io/s/segment-with-default-value-ucobg
https://codesandbox.io/s/segment-no-default-value-ld61l

**Other information:**
n/a

**Ionic info:**

Ionic:

   Ionic CLI       : 6.12.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.0

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.0.0

System:

   NodeJS : v14.15.3 (/usr/local/Cellar/node@14/14.15.3/bin/node)
   npm    : 6.14.9
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue. I think the problem here is that when you update the values rendered in your list, `IonSegment` is also getting re-rendered. However, because you have hardcoded `value="segment1"`, when the segment re-renders the internal value is being re-set to `segment1`, causing the issues you have noted here.

Rather than keep that value hardcoded, can you try using `useState` on that as well? Something like this:

```js
...

const [selectedSegment, setSelectedSegment] = useState('segment1');

function toggleSegment(selectedSegment?: string) {
    console.log("Selected segment is: " + selectedSegment);

    if (selectedSegment === "segment1") {
      setSelectedSegment('segment1');
      setSegmentValues(segment1Values);
    }
    else if (selectedSegment === "segment2") {
      setSelectedSegment('segment2');
      setSegmentValues(segment2Values);
    }
    else {
      console.log("Invalid selected segment: " + selectedSegment);
    }
}
...

<IonSegment value={selectedSegment} ...> 
  ...
</IonSegment>
```

**Comment by rluttikhuizen** [comment]
Thanks for the fast reply @liamdebeasi !

That solves the issue :) 

I assumed that the value attribute was used for the initial value of the selected segment button. Now that we have it in a state as well and change it together with the value list, it works smoothly. I'll close the issue.

Thanks again,

Ronald
