### ISSUE TITLE
bug: ion-datetime opening value when "min" is set to a future date.

### ISSUE THREAD

**Issue by pg17** [ionic-team/ionic-framework#23046]
**Ionic version:**
[x] **5.5.5**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
When setting the "min" attribute of ion-datetime to a date in the future but before the current day of month (ie: if today is
2021-03-15 and you set the min date to 2022-02-01 (so in the future but to a day before march 15th), the preselected date when opening the component is set to the current day of month in the future (2022-03-15 in our example).

**Expected behavior:**
When setting a min value in the future, the date displayed on opening the component (when no value is selected) should (in my opinion) be that min date. In the example above that would be 2022-02-01.

**Steps to reproduce:**
```html
<!-- min value should be set to any year in the future but to a day and month prior to those of the current day -->
<ion-datetime min="2022-02-01"></ion-datetime>
```

**Other information:**
While I think the expected behavior I proposed would be reasonable I understand this is debatable. Being able to set the opening / pre-selected value (as discussed here https://github.com/ionic-team/ionic-framework/issues/20532) could be an even better solution.

**Ionic info:** 
```
Ionic:

   Ionic CLI                     : 6.13.1 (C:\Users\pg17\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.5
   @angular-devkit/build-angular : 0.1100.7
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 11.2.2
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.11
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I agree that this is a bug. We are tracking our datetime issues in https://github.com/ionic-team/ionic-framework/issues/16630, so I will close this issue out and add it to our datetime tracker I linked to above.
