### ISSUE TITLE
bug: "ion-spinner" displays a strange icon

### ISSUE THREAD

**Issue by Chreggii** [ionic-team/ionic-framework#23045]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.3.5**

**Current behavior:**

When I use `ion-spinner` on "desktop" platform the the spinner looks very strange.
![image](https://user-images.githubusercontent.com/34272764/111111652-0bb91b80-855f-11eb-8d8a-b7d518ea6b75.png)

**Expected behavior:**

It should show the default android spinner icon.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
