### ISSUE TITLE
bug: iOS NavController animates too much slide

### ISSUE THREAD

**Issue by wcooperscott** [ionic-team/ionic-framework#23042]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Navigating forward on iOS shows an animation that slides too far.

**Expected behavior:**
Navigation animation performs similar to native iOS navigation.

**Steps to reproduce:**
Navigate to new page using navController's `navigateForward` method.

This is the code that invokes the forward navigation.
```
openMessage(message) {
    if (!message.group) {
      this.navCtrl.navigateForward('chat/view-message/1');
    } else {
      this.navCtrl.navigateForward('chat/view-group/3');
    }
  }
```

Here is a gif of the issue:
![][image_ref_1]

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.0

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (1 plugins total)

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v12.18.3 (/usr/local/bin/node)
   npm    : 6.14.6
   OS     : macOS Catalina
   Xcode  : Xcode 12.4 Build version 12D4e
```

[image_ref_1]: https://i.imgur.com/yjN8Nuo.gif

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
