### ISSUE TITLE
bug: Toggle firing click event twice

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#23041]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
If you have a click event on an ion-toggle and that click event calls `evt.stopImmediatePropagation();` it will fire the click event twice for some reason.

**Expected behavior:**
Click event only fired once per click.

**Steps to reproduce:**
1. create an app with an ion-toggle
2. bind the click event on the toggle
3. give yourself some way to see how many events are fired
3. call `stopImmediatePropagation()` in the click event
4. event will fire twice per click

If I roll the `@ionic/angular` version back to 5.4.4 it behaves properly. Seems to have been introduced with 5.5.0, perhaps via this change: https://github.com/ionic-team/ionic-framework/pull/22477

**Related code:**

https://github.com/kensodemann/test-toggle

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/23146.
