### ISSUE TITLE
bug: IonRouterOutlet does not handle recursive routes/paths

### ISSUE THREAD

**Issue by cdes** [ionic-team/ionic-framework#23051]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.6.0**

**Current behavior:**

Consider a page component that shows a user profile and a list of friends.
When tapping on a friend, the app navigates to a new route to display that friend's profile along with a list of friends using the same page component.  In other words, recursive routing.

![CleanShot 2021-03-16 at 04 51 21](https://user-images.githubusercontent.com/1207863/111244206-7b88de00-8613-11eb-910d-0d24c3c80d94.gif)

**Expected behavior:**

Ionic navigation should keep showing the screen and building the url as you go deeper in the recursive path.

I've used this as a guide:
https://reactrouter.com/web/example/recursive-paths

**Steps to reproduce:**

**Related code:**

A sample application via code sandbox
https://codesandbox.io/s/ionic-recursive-route-x9r8x?file=/src/app.tsx

**Other information:**

**Ionic info:**

Versions
```
"@ionic/react": "5.6.0",
"@ionic/react-router": "5.6.0",
"react": "17.0.1",
"react-dom": "17.0.1",
"react-router-dom": "5.2.0",
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. In the react-router example you provided, the example author adds the following code which is necessary for this functionality to work:

```jsx
<Route path={`${url}/:id`}>
  <Person />
</Route>
```

This code was not found in your CodeSandbox, and adding it seems to make it work. Can you give that a shot?

**Comment by cdes** [comment]
@liamdebeasi Unfortunately no.  I've tried that before and nothing appears, which means that the route was not matched.

**Comment by liamdebeasi** [comment]
Hmm, I am not sure that usage is correct. Your example wraps the component template in a `Route` component, but the example on the `react-router` docs places the `Route` component inside of the template.

I would recommend placing the `Route` inside of the template as that was what worked for me.  So your code would look something like this:

```jsx
<IonPage>
  <IonHeader collapse="condense">
    <IonToolbar>
      <IonButtons slot="start">
        <IonBackButton />
      </IonButtons>
      <IonTitle>Friends App</IonTitle>
    </IonToolbar>
  </IonHeader>
  <IonContent>
    <div
      style={{
        display: "flex",
        alignItems: "center",
        padding: 16
      }}
    >
      <IonAvatar
        style={{
          width: 64,
          height: 64
        }}
        slot="start"
      >
        <img src={person?.avatar} />
      </IonAvatar>
      <IonText
        style={{
          marginLeft: 16,
          fontSize: 32
        }}
      >
        {person.name}
      </IonText>
    </div>
    <IonList>
      <IonListHeader
        style={{
          fontSize: 16,
          textTransform: "uppercase"
        }}
      >
        Friends
      </IonListHeader>
      {person.friends.map((id) => (
        <IonItem
          key={id}
          routerLink={`${url}/${id}`}
          routerDirection="forward"
        >
          <IonLabel>{find(id).name}</IonLabel>
        </IonItem>
      ))}
    </IonList>
  </IonContent>

  <Route path={`${url}/:id`}>
    <User />
  </Route>

</IonPage>
```

Note the `Route` immediately before the closing `IonPage` tag.

**Comment by cdes** [comment]
Interesting... navigation works but the transitions are not 

![CleanShot 2021-03-17 at 19 26 41](https://user-images.githubusercontent.com/1207863/111502366-da0aa500-8756-11eb-970a-27633e79ec51.gif)

**Comment by cdes** [comment]
I've managed to create another example for recursive route, but this has a different issue.  Back button only goes back ones and then disappears.

https://codesandbox.io/s/ionic-recursive-route-forked-9u5ot?file=/src/app.tsx


![CleanShot 2021-03-17 at 19 52 32](https://user-images.githubusercontent.com/1207863/111506141-610d4c80-875a-11eb-9e89-91e199abc960.gif)

**Comment by JayBizzle** [comment]
Just as a side note, i think this issue is related to https://github.com/ionic-team/ionic-framework/issues/22662

**Comment by liamdebeasi** [comment]
> I've managed to create another example for recursive route. The transition works, but this has a different issue.
> 
> The back button only goes back ones and then disappears.
> 
> https://codesandbox.io/s/ionic-recursive-route-forked-9u5ot?file=/src/app.tsx
> 
> ![CleanShot 2021-03-17 at 19 52 32](https://user-images.githubusercontent.com/1207863/111506141-610d4c80-875a-11eb-9e89-91e199abc960.gif)

Thanks! This was helpful. Looks like this is the same issue as https://github.com/ionic-team/ionic-framework/issues/22692, so I will close this in favor of the issue I linked to. I have an idea of how to fix this issue, so I will try to get a dev build for you to test today/tomorrow.

**Comment by liamdebeasi** [comment]
I posted a dev build on this thread: https://github.com/ionic-team/ionic-framework/issues/22692#issuecomment-801951461

**Comment by cdes** [comment]
@liamdebeasi IT WORKS!

https://codesandbox.io/s/ionic-recursive-route-570-dev2021031813498ac4d12-wzoyl

![CleanShot 2021-03-18 at 19 47 45](https://user-images.githubusercontent.com/1207863/111664493-e1978000-8822-11eb-86d2-66ec7bdc020f.gif)

**Comment by liamdebeasi** [comment]
Glad it's working now! I will try to get that PR merged in soon.
