### ISSUE TITLE
bug: ion-item a11y - screen reader reads detail icon name

### ISSUE THREAD

**Issue by eric-horodyski** [ionic-team/ionic-framework#23054]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Given an `ion-item` component that displays the default detail icon (by virtue of iOS platform), a screen reader will read the named value of the default icon aloud ("Chevron Forward").   

**Expected behavior:**

The detail icon of an `ion-item` should have `aria-hidden="true"` set in order to hide it from the accessibility tree.

**Steps to reproduce:**

1. Pull down the sample repository
2. Run `npm i && npx cap open ios`
3. Launch the application on an iOS device with VoiceOver enabled, and tap the detail icon.

**Related code:**

https://github.com/eric-horodyski/fw-ionitem-icon-a11y-issue

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (/Users/eric/npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.0

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run (update available: 1.3.0)   : 1.2.2

System:

   NodeJS : v14.15.1 (/usr/local/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/23055.
