### ISSUE TITLE
bug: <ion-toast> is not a known element (angular)

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#23068]
**Ionic version:**

[x] **5.x**

**Current behavior:**
I need to lazy load IonToast js in case I lose network to let the user know. So I did as @liamdebeasi recommends here https://github.com/ionic-team/ionic-framework/issues/17450#issuecomment-628223724 by just adding a `<ion-toast></ion-toast>` at the root of `<ion-app>`.

While this solution works for the lazy loading, my IDE (WebStorm) throw a warning :

![Sans titre](https://user-images.githubusercontent.com/15921402/111630843-0ffd6700-87f3-11eb-9230-7159bd272bd5.png)

And my Angular project compilation works in dev, but not in prod, it throws the following error and therefor I cannot compile : 

> error NG8001: 'ion-toast' is not a known element

I do import IonicModule.forRoot() in my **app.module.ts**.

I can make my app compile in prod by adding `schemas: [CUSTOM_ELEMENTS_SCHEMA]` in my **app.module.ts**, but since we can use `<ion-toast>` in a template, it would make sense if Ionic was exposing `<ion-toast>` tag to Angular ?

**Expected behavior:**

An Angular project using the tag <ion-toast> should compile in production configuration

**Steps to reproduce:**

* create an Angular Ionic project
* add a <ion-toast> tag at the root of `<ion-app>`
* compile the project with a production configuration

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.2
   Ionic Framework               : @ionic/angular 5.5.0
   @angular-devkit/build-angular : 0.1100.2
   @angular-devkit/schematics    : 11.0.3
   @angular/cli                  : 11.0.3
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 1.4.0
   @capacitor/core : 1.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.1
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
