### ISSUE TITLE
bug: Ion toolbar does not center align middle content with start and end slot content

### ISSUE THREAD

**Issue by MartinSkovsen** [ionic-team/ionic-framework#23072]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.5.2**

**Current behavior:**
The ion toolbar does not align start and end slot with the content of the middle slot content when the top padding are different from the bottom padding, but the total top and bottom padding are the same. So 32px padding to the top and 0 to the bottom won't yield the same result as 16px top and 16px bottom padding. 16px top and bottom padding will align the content with the start and end slot however 32px top and 0px bottom padding will make the title appear slightly above the start and end slot content.

**Expected behavior:**

The toolbar should center align middle slot content with the start and end slot content when the total top and bottom padding are fixed, but top and bottom padding aren't equal.

**Steps to reproduce:**
In Ionic docs:
1. Go to https://ionicframework.com/docs/api/modal
2. Click Show modal
3. Inspect modal title (or any other element, which would eventually bring you to ion-toolbar inside the modal header)
4. Modify --padding-top: 32px and --padding-bottom: 0

In Kirby cookbook:
1. Go to https://cookbook.kirby.design/home/showcase/modal
2. Click Show modal
3. Inspect ion-toolbar
4. Modify --padding-top: 32px and --padding-bottom: 0

**Related code:**
If necessary I can provide a sample project, however above reproduction description should suffice.

**Other information:**
[Link to issue in Kirby component library about wrong toolbar content alignment](https://github.com/kirbydesign/designsystem/issues/1405)
Screenshot from ionic docs: 
![billede](https://user-images.githubusercontent.com/30232520/111699048-e450a000-8837-11eb-8774-793cbd5e37b4.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23343, and a fix will be available in an upcoming release of Ionic Framework.
