### ISSUE TITLE
bug: Modal's "backdropDismiss: true" option doesn't work if it's shown as a half screen modal

### ISSUE THREAD

**Issue by AndrewBargan** [ionic-team/ionic-framework#23079]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Hey,

I'm showing half screen modal in the way like in the attached gif. For opening the modal I've specified "backdropDismiss: true" option but clicking backdrop doesn't close the modal. To reproduce the issue download the https://github.com/AndrewBargan/modal-dismiss-issue repository.
When reproduced make sure your browser window width is as narrow as possible.

Cheers,
Andrew.

![Mar-21-2021 10-49-55](https://user-images.githubusercontent.com/33483711/111900212-eaae6a00-8a39-11eb-9d11-5bd111769e67.gif)

**Expected behavior:**
Tapping/clicking backdrop closes the modal.

**Related code:**
https://github.com/AndrewBargan/modal-dismiss-issue repository

**Comment by EinfachHans** [comment]
i don't know if this changes the behavior, but have you tried to use the official `--height` property described [here](https://ionicframework.com/docs/api/modal#css-custom-properties)? Instead of your
```css
modal-wrapper {
  height: 50%;
}
```

**Comment by AndrewBargan** [comment]
My fault. Now it works! Thanks, @EinfachHans!
