### ISSUE TITLE
bug: bug in ionic-vue routing when using ion-back-button

### ISSUE THREAD

**Issue by bddexter** [ionic-team/ionic-framework#23087]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.6.0**

**Current behavior:**
I have an `ionic-vue` app that uses `vue-router` and the tabs template. When I navigate to a subroute, from the subroute changing to another tab, then go back to the tab which has the subroute still active and then pressing the back button in this subroute causes my route to change to the other tab (in the URL), but the animation still does go to the main tab of the sub route.

**Expected behavior:**
I would expect that - besides switching back to the parent view - my url would also return to the parent tab

**Steps to reproduce:**

- Make a `ionic-vue` app using the tabs template
- Add a sub route to one of the tabs (i.e. tab1) (make sure this view has the `ion-back-button` active in the `ion-toolbar`)
- Enter the sub route (of tab1)
- Switch to another tab (i.e. tab2) from this sub route
- Switch back to the tab that has the sub route active (i.e. tab1)
- Press the back button in this sub route
- The back button causes the view to return to the parent view of this tab (tab1 in this case, which I would expect) but the url switches back to the other tab (tab2)

**Related code:**

[working codesandbox](https://codesandbox.io/s/angry-villani-l9cbl?file=/src/views/Tab1.vue)

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.6.0

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

```

**Comment by bddexter** [comment]
Is this going to be looked into?

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this in both Ionic Vue and Ionic React. When clicking the `ion-back-button`, we grab the correct view (Tab1), but we do not properly update the URL. This does not impact Ionic Angular.

I will look into a fix for this.

**Comment by bddexter** [comment]
@liamdebeasi thanks for looking into this and confirming.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.7.0-dev.202104021913.b0533ff @ionic/vue-router@5.7.0-dev.202104021913.b0533ff
```

**Comment by bddexter** [comment]
@liamdebeasi Just did a dev build on my current project. all is working fine now.Fix did the job :)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23154, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by bddexter** [comment]
Tnx @liamdebeasi
