### ISSUE TITLE
bug: ion-input does not get focused when clicking on floating label

### ISSUE THREAD

**Issue by nagdevbharat** [ionic-team/ionic-framework#23097]
I have found the related issue https://github.com/ionic-team/ionic-framework/issues/21509#issuecomment-678478626
This says it was fixed in 5.3.2 and I am currently on 5.6.3 (latest version) and still getting this

# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When I click on a floating label the label starts floating but an input connected to it does not get focused

**Expected behavior:**
Clicking on the label should focus on input

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.1
   Ionic Framework               : @ionic/angular 5.6.3
   @angular-devkit/build-angular : 0.1101.3
   @angular-devkit/schematics    : 11.1.3
   @angular/cli                  : 11.1.3
   @ionic/angular-toolkit        : 3.0.0

Capacitor:

   Capacitor CLI   : 2.4.4
   @capacitor/core : 2.4.4

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.23.0
   npm    : 6.14.8
   OS     : macOS Big Sur
   Xcode  : Xcode 12.2 Build version 12B45b
```

**Comment by nagdevbharat** [comment]
Hi @liamdebeasi ,
Please find the stackblitz link(https://stackblitz.com/edit/ionic-v4-angular-tabs-gyiwnj?file=src/app/tab1/tab1.page.ts)
Click on the label when you see the mouse pointer as default. It will animate the label to float but won't open the modal.

**Comment by nagdevbharat** [comment]
Hi, @liamdebeasi ,

Can you please review this?

**Comment by nagdevbharat** [comment]
Hello @liamdebeasi ,
I think I am unable to explain the issue.
Please check the video link given.
https://www.loom.com/share/436c7b676f17443bac90fc58c1de0ced

What i want to do is open a modal on clikc of the input. Previously(ionic 3) it was working fine with `readonly=true`. But in the latest version it does not open modal on click of label.
However it does open the modal when clicking on input, regardless of the readonly property.

**Comment by liamdebeasi** [comment]
Since the click handler is on `ion-input` and not `ion-label`, I would not expect clicking `ion-label` to open the modal. You should add the click handler to `ion-item` if you want clicking either `ion-label` or `ion-input` to open the modal.

**Comment by nagdevbharat** [comment]
Hi @liamdebeasi ,
Thanks for the suggestion. This is much helpful.
I am confused about the version differences: 
- With Ionic 3 same code works even when the input is `readonly`.
- With Ionic 5 it does not allow me to open modal on label click.
- With Ionic 5 when clicked on the input it opens the modal. Even if `readonly` property is declared.

**Comment by liamdebeasi** [comment]
Ionic v3 --> Ionic v4/v5 was a pretty significant refactor so there are likely some small behavior differences.
