### ISSUE TITLE
ion-datepicker Use Icons with or instead of Text Labels

### ISSUE THREAD

**Issue by phillipa-llama** [ionic-team/ionic-framework#23106]
**Ionic version:**

[] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[ ] bug report
[x] feature request

**Current behavior:**

Currently I am able to send custom PickerOption buttons into the ion-datetime component. However, I'd like to be able to include an icon with these or use an icon instead of the text label altogether. Currently there doesn't seem to be a way to do this.

![image](https://user-images.githubusercontent.com/57439980/112635524-9abe1180-8e44-11eb-8dab-bbdefe14755d.png)

**Expected behavior:**

As an example, I would like the options to replace the Close / Done / Any buttons with a relevant icon. I would also like the ability to have both an icon and a label for the button.
![image](https://user-images.githubusercontent.com/57439980/112635295-516dc200-8e44-11eb-8162-1b31d22b565e.png)

**Steps to reproduce:**

N/A

**Related code:**

`this.customPickerOptions = {
      buttons: [
        {
          text: 'Switch Calendar',
          cssClass: 'switch-btn',
          handler: () => {
            this.switchCalendar();
          }
        },
        {
          text: 'Cancel',
          handler: () => {
          }
        },
        {
          text: 'Done',
          handler: (value) => {
          }
        }
      ]
    }`

`<ion-datetime #dateTimePicker [pickerOptions]="customPickerOptions" formControlName="validDate" displayFormat="DD MMM YYYY" [min]="getToday('YYYY-MM-DD')" [max]="getMaxValidDate()"></ion-datetime>`

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am adding your feature request to our datetime issue tracker here: https://github.com/ionic-team/ionic-framework/issues/16630
