### ISSUE TITLE
bug: ion-item-sliding performance issues

### ISSUE THREAD

**Issue by asa47** [ionic-team/ionic-framework#23116]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

We are noticing some perfomance issues with `ion-item-sliding`, it seems that the whole UI freeze for a few milliseconds when adding the element to the DOM. 

It works fine on the browser, but when it's built on an actual device (iPad) or simulator, we can see/feel the delay.
We also tested the same logic with `ion-item` or a `div` and there is no delay. 

Another additional note, it seems that the delay can be reduced by creating the `ion-item-sliding` with the disabled attribute i.e: `<ion-item-sliding disabled> ... </ion-item-sliding>`

**Expected behavior:**

It would be great if there was a way to reduce/remove the delay, or to understand what happens when the `ion-item-sliding` is pushed to the DOM.

**Steps to reproduce:**

Please test the following on an actual device on not the browser.
On user interaction, add an `ion-item-sliding` to an empty list. 
Currently if we quickly tap 5 times on the main button, the click event is triggered only 3 times (due to the delay). If we replace the `ion-item-sliding` with an `ion-item` the click event is triggered 5 times.

**Related code:**

```
<!-- Main Button -->
<ion-button @click="items.push({})">Main button</ion-button>

<!-- List from user interaction -->
<ion-item-sliding v-for="(item, index) in items" :key="index"> 
   <ion-item>
      ...
   </<ion-item>
   <ion-item-options>
      ...
   </<ion-item-options>
</ion-item-sliding>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.2

Capacitor:

   Capacitor CLI   : 2.4.5
   @capacitor/core : 2.4.5

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : not installed

System:

   NodeJS : v11.15.0 (/usr/local/bin/node)
   npm    : 6.7.0
   OS     : macOS Catalina
```

**Comment by lincolnthree** [comment]
I have also noticed a significant slowdown to rendering when using `ion-item-sliding`. I'm currently in the middle of a huge refactor to resolve this. I wasn't even looking for this issue but just saw it browsing for something else.

My initial thought is simply the complexity and number of DOM elements added when using ion-item-sliding is enough to overwhelm phones. It requires several rendering containers and has a few slots and a lot of other internals that have a multiplicative effect on the number of DOM elements when rending in lists. Virtual scroll helps significantly, but if new elements need to be rendered... it'll be jittery, laggy, and very slow to get a full render.

FWIW. This does not seem to be the case with the Ionic 3 version of ion-item-sliding. I'm still digging though.

**Comment by lincolnthree** [comment]
@asa47 Have you been able to reproduce the problem in a starter app? https://ionicframework.com/docs/cli/commands/start

**Comment by lincolnthree** [comment]
Related: https://github.com/ionic-team/ionic-framework/issues/23155

**Comment by lincolnthree** [comment]
Repro: https://ionic-angular-v5-ngcyvz.stackblitz.io

**Comment by liamdebeasi** [comment]
This issue and https://github.com/ionic-team/ionic-framework/issues/23155 refer to the same underlying problems so I am going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/23155
