### ISSUE TITLE
bug: There is a css bug on ios brwoser mode of chrome dev tools.

### ISSUE THREAD

**Issue by jhs512** [ionic-team/ionic-framework#23118]
There is a css bug on ios brwoser mode of chrome dev tools.

The title text new lined. is it normal?

![녹화_2021_03_30_17_49_36_842](https://user-images.githubusercontent.com/4741844/112961900-c44aa600-9180-11eb-828a-8f61ea7ffb78.gif)

**Comment by BerkeAras** [comment]
@jhs512 

1. Use the issue template.
2. Give us some code
3. It does not look live a css-issue, more like a jQuery issue. jQuery is going to be less relevant and should not be used with modern technologies like React, Angular or Vue.

**Comment by BerkeAras** [comment]
@liamdebeasi Should it be closed?
