### ISSUE TITLE
bug: css bug on ios device mode on chrome dev tools.(rewrited with issue template)

### ISSUE THREAD

**Issue by jhs512** [ionic-team/ionic-framework#23122]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
there is css bug on ios device mode on chrome dev tools.

**Expected behavior:**
no css bug on ios device mode on chrome dev tools.

**Steps to reproduce:**

I think it's a vue tabs template bug.
- ionic start
- Framework : Vue
- Project name : Exam1
- Starter template : tabs
- Create free Ionic account? : N
- cd Exam1
- npm i
- ionic serve
- http://localhost:8100/
- -F12 in chrome
- select iOS5/SE
- F5

that's it.
there are no code chagnes.

**Related code:**

https://github.com/jhs512/ionic_starter_template_bug

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

![녹화_2021_03_31_09_16_19_112](https://user-images.githubusercontent.com/4741844/113072381-e8020080-9201-11eb-9193-52f44960be88.gif)

**Comment by jhs512** [comment]
is there any problem?
sorry. i don't know about iOS very well.
i thought it wat bug.

**Comment by liamdebeasi** [comment]
I am trying to determine whether or not there is a bug. Can you please describe what the CSS bug you are seeing is?
