### ISSUE TITLE
bug: card-style modal does not resizes view (like it is on native)

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-framework#23138]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
Card-Style-Modals on **Ionic-Apps** are **pushing the content down.**

**Expected behavior:**
Card-Style-Modals on **Native-Apps** are **resizing the content view**

**Steps to reproduce:**
Just create a new app and slide down and up a modal.

**Related code:**

N/A

**Other information:**
See this video (the Content is centered here. You can see how the view resizes):

https://user-images.githubusercontent.com/36629890/113486228-fa09ca80-94b1-11eb-85b0-c9f3b324c9c9.mp4

**Ionic info:**

N/A

**Comment by liamdebeasi** [comment]
Thanks for the issue. I took a look and I am not sure this is something we are going to implement at this time. There are some significant performance implications with resizing the content on each gesture drag that I am not sure we can properly handle on older devices at the moment. Additionally, I don't think this behavior would be desired for most scenarios. For example, see the Calendar app on iOS: 

https://user-images.githubusercontent.com/2721089/113579108-d3eb4400-95f1-11eb-83be-dbda4afe6d44.MP4
