### ISSUE TITLE
bug(router): route-redirect does not honor the query string

### ISSUE THREAD

**Issue by vicb** [ionic-team/ionic-framework#23136]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.6**

**Current behavior:**

```
<ion-route-redirect from="/redirect" to="/foo?src=redirect"></ion-route-redirect>
```

would redirect to `/foo`

**Expected behavior:**

```
<ion-route-redirect from="/redirect" to="/foo?src=redirect"></ion-route-redirect>
```

should redirect to `/foo?src=redirect`

**Steps to reproduce:**
**Related code:**

https://runkit.com/vicb/ionic-router-redirect---query-string

using this runkit:
- click on "go to foo", the url changes to `/foo?src=button`,
- click on "redirect to foo", the url changes to `/foo` but we want `/foo?src=redirect`

**Other information:**

This feature is missing from the ionic source code.
It would be easy to implement and I am happy to contribute a fix.
I would make sense to merge #23123 first though.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23337, and a fix will be available in an upcoming release of Ionic Framework.
