### ISSUE TITLE
bug: overlays reusing inner component instance even after dismissing

### ISSUE THREAD

**Issue by uncvrd** [ionic-team/ionic-framework#23140]
# Bug Report

**Ionic version:**

[x] **5.6.3**

**Current behavior:**

In my `IonModal`, I define `useState` hooks to manage code while the modal is displayed on the page. This works great when the modal is displayed, however, when I close the modal and then reopen, the state variables that were modified during the last time the modal was opened, still show instead of the `useState` hooks resetting back to their initial state.

Video demo: https://streamable.com/cd965g

**Expected behavior:**

I expect to have the modal reset its state every time I reopen a modal.

**Steps to reproduce:**

CodeSandbox for reproduction:
https://codesandbox.io/s/cool-bash-z8f5j?file=/src/pages/Tab1.tsx

Steps to recreate using the link above:
1. On Tab One, click "Show Modal"
2. On the modal, observe the text displaying "init"
3. Click the button "Change Modal State"
4. On the modal, observe the text now displaying "changed state!"
5. Close the modal by clicking outside the modal or the close button in the top right
6. Reopen the modal by clicking "Show Modal"
7. Observe that the text on the page is NOT "init" but instead the "changed state!" text from the last time we used the modal

NOTE: if you switch between tabs and then back to Tab One and click "Show Modal" the state finally resets.

This behavior is different from an older version of Ionic React I had been using recently. Is this the new intended behavior or should the state indeed be resetting upon hiding the modal? Logically, since the modal is being removed from the DOM I'd expect the state to reset...right?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Did you publish your latest changes on the CodeSandbox? I do not see the "Show Modal" button on Tab1.

**Comment by uncvrd** [comment]
@liamdebeasi None of my changes saved...sorry about that. I rewrote the codesandbox. The same link should still work but here's the link again: https://codesandbox.io/s/cool-bash-z8f5j?file=/src/pages/Tab1.tsx

**Comment by liamdebeasi** [comment]
Thanks! Now I am getting the following error when I click the "Show Modal" button:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Tab1`.
```

**Comment by uncvrd** [comment]
@liamdebeasi goodness sorry, how about now? https://codesandbox.io/s/cool-bash-z8f5j?file=/src/pages/Tab1.tsx

Not sure why it's not saving my work. Just checked on a second computer and I was able to run it though.

**Comment by liamdebeasi** [comment]
Thanks! I can reproduce this. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/react@5.7.0-dev.202104052006.bc2e50a @ionic/react-router@5.7.0-dev.202104052006.bc2e50a
```

**Comment by uncvrd** [comment]
Hey Liam! Glad you were able to get it to work :) Yes the dev build looks like it resolves the problem

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23149, and a fix will be available in an upcoming release of Ionic Framework.
