### ISSUE TITLE
bug: react, callbacks refs not supported

### ISSUE THREAD

**Issue by coreyjv** [ionic-team/ionic-framework#23153]
# Bug Report

**Ionic version:**
[x] **5.6.3**

**Current behavior:**

Third party libraries such as [React Hook Form ](https://react-hook-form.com) use [React callback refs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) to collect the refs of multiple DOM elements. In the case of React Hook Form the refs are used to focus specific inputs when error states occur among other things.

As shown in the Codesandbox below when a callback ref is provided to `IonInput` it breaks the input. In the example shown handlers such as `onIonChange` no longer fire. 

https://codesandbox.io/s/ionic-callback-refs-react-hook-form-wucco?file=/src/App.js

**Expected behavior:**

Any Ionic React component should be able to accept a callback ref per the React documentation linked above.

**Steps to reproduce:**

1. Open the Codesandbox: https://codesandbox.io/s/ionic-callback-refs-react-hook-form-wucco?file=/src/App.js
2. Enter text in the input
3. Observe that the `onIonChange` does not fire
4. Remove the `ref` in the `IonInput`
5. Observe that the `onIonChange` event now fires

**Related code:**

https://codesandbox.io/s/ionic-callback-refs-react-hook-form-wucco?file=/src/App.js

**Other information:**

This has been mentioned before in two other issues: #23111 and #22890 

A colleague of mine has fixed the bug in a recently opened PR: #23152

**Comment by liamdebeasi** [comment]
Thanks for the issue. I double checked with the team, and it looks like we do not support callback refs in Ionic React so I will mark this as a bug.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23152, and a fix will be available in an upcoming release of Ionic Framework.
