### ISSUE TITLE
feat: App Switcher - Show Custom Image/Splashscreen

### ISSUE THREAD

**Issue by bjois** [ionic-team/ionic-framework#23165]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
When the app is in placed into the "app-switcher" mode, the ability to load the splashscreen OR a custom image to act as a privacy screen.

**Describe Preferred Solution**
a JavaScript hook to the app switcher trigger that allows developer to provide a callback to load a custom image or take some other action (load splashscreen). Another hook when app comes back from app switcher.

**Additional Context**
platform.pause and platform.resume seem like they don't trigger when app switcher is loaded.

**Comment by liamdebeasi** [comment]
Thanks for the issue. If you are using Capacitor, you can use the Privacy Screen plugin to accomplish this: https://github.com/capacitor-community/privacy-screen

**Comment by bjois** [comment]
Hi - we are not using capacitor, and would like to show the splashscreen on both platforms.

**Comment by liamdebeasi** [comment]
Are you using Cordova? There is a Cordova plugin for this as well: https://www.npmjs.com/package/cordova-privacyscreen-plugin
