### ISSUE TITLE
bug(ion-modal): dismiss event is not triggered in vue 

### ISSUE THREAD

**Issue by khaledosman** [ionic-team/ionic-framework#23164]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
The dismiss event is not triggered, according to the docs [here](https://ionicframework.com/docs/api/modal#events) the component has an `ionModalDidDismiss` event that I should be able to listen to, in the template/example however it uses the `onDidDismiss`, it doesn't seem to work with either

**Expected behavior:**
Should trigger the dismiss event and call my handler to display the alert

**Steps to reproduce:**
https://codesandbox.io/s/ionic-5-vue-3-rn1xi?file=/src/About.vue:155-183
Go to About page, then press esc to close the modal

```
<template>
  <ion-page>
    <h1>About Page</h1>
    <ion-modal
      :is-open="isDropdownModalOpen"
      css-class="my-custom-class"
      @onDidDismiss="handleDropdownModalDismissed"
      @ionModalDidDismiss="handleDropdownModalDismissed"
    >
      Modal content
    </ion-modal>
  </ion-page>
</template>

<script>
import { IonPage, IonModal } from "@ionic/vue";
import { ref } from "vue";
export default {
  components: {
    IonPage,
    IonModal,
  },
  setup() {
    const isDropdownModalOpen = ref(true);
    const handleDropdownModalDismissed = () => {
      alert("dismissed");
      isDropdownModalOpen.value = false;
    };
    return {
      isDropdownModalOpen,
      handleDropdownModalDismissed,
    };
  },
};
</script>

<style>
</style>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This was resolved in https://github.com/ionic-team/ionic-framework/commit/27318cf58563c4b38d0b7045fb61451f45954a8f, and a fix should be available in an upcoming release of Ionic Framework.
