### ISSUE TITLE
bug: query params passed without question mark when navigating between tabs

### ISSUE THREAD

**Issue by mvbn** [ionic-team/ionic-framework#23175]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.6**

**Current behavior:**
Ionic app with Vue and tabs.

Click Tab1: /tabs/tab1
Click Card inside Tab1: /tabs/tab1/card/param1/param2?category=A&genre=B
Click Tab2: /tabs/tab2
Click Tab1, and the address is now: /tabs/tab1/card/param1/param2category=A&genre=B

**Expected behavior:**
Click Tab1, and have again the address: /tabs/tab1/card/param1/param2?category=A&genre=B

**Ionic info:**
Ionic:

   Ionic CLI       : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.0

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.0 (/usr/local/bin/node)
   npm    : 7.6.3
   OS     : macOS Catalina

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
