### ISSUE TITLE
bug: @ionic-react Cannot read property 'removeChild' of null (StackManager.tsx)

### ISSUE THREAD

**Issue by ItayElgazar** [ionic-team/ionic-framework#23183]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

When using [Reactfire](https://github.com/FirebaseExtended/reactfire)'s component `<AuthCheck />` and navigating (specifically on firebase logout), navigation works but an error appears.

`StackManager.tsx:163 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at StackManager.transitionPage`

**Expected behavior:**

Navigation should work without error

**Steps to reproduce:**

1. Use `<AuthCheck>` to wrap your private components
2. Logout from your firebase session and navigate to somewhere else in the app (public route)
3. 
**Related code:**

```jsx
<>
  <Route path="/logout" exact={true}>
                <Logout />
              </Route>
 <AuthCheck fallback={<MainRoute />}>
                <PrivateRoute
                  exact
                  path="/customize"
                  component={CustomizeExperienceRoute} />
</AuthCheck>
</>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.4.3

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.1 (/usr/local/bin/node)
   npm    : 6.14.12
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Does this issue happen on the latest version of Ionic React? If it does, could you please reproduce this in an Ionic starter app and provide a link to the repo? Thanks!
