### ISSUE TITLE
bug: input type date shows wheels UI view instead of calendar UI

### ISSUE THREAD

**Issue by mastergogo** [ionic-team/ionic-framework#23188]
Ionic version:
5.6.0

Current behavior: On our ios app when we use the input type="date" we are getting the traditional wheel view. (please see screenshot)

Expected behavior: The expected behavior here is to get the compact calendar view (available from iOS 14) as it is ADA compliant and also provide more flexibility for screen reader user to add date.

Steps to reproduce: I could get the compact calendar view in a fresh ionic app if I simply use input type="date", however in our production app it is showing the wheel view. what could possibly be the reason for ionic to show one over the other? what is causing it show the wheel view?
<img width="172" alt="compact-calender-view" src="https://user-images.githubusercontent.com/8082610/114720187-6e1b5c80-9d55-11eb-8712-e101ded0b8bb.PNG">
<img width="183" alt="wheel view" src="https://user-images.githubusercontent.com/8082610/114720197-6fe52000-9d55-11eb-84b7-424e34624d32.PNG">

below are my dependencies, if it is related to capacitor or something.

`"dependencies": {
    "@adobe/cordova-acpcore": "^0.0.1",
    "@babel/runtime-corejs3": "^7.13.10",
    "@capacitor/android": "^2.4.7",
    "@capacitor/core": "^2.4.7",
    "@capacitor/ios": "^2.4.7",
    "@ionic-native/aes-256": "^5.31.1",
    "@ionic-native/call-number": "^5.31.1",
    "@ionic-native/core": "^5.31.1",
    "@ionic-native/file": "^5.31.1",
    "@ionic-native/file-transfer": "^5.31.1",
    "@ionic-native/in-app-browser": "^5.31.1",
    "@ionic-native/open-native-settings": "^5.31.1",
    "@ionic-native/preview-any-file": "^5.31.1",
    "@ionic/core": "^5.6.0",
    "@modus/ionic-vue": "^1.3.12",
    "@nuxtjs/auth": "^4.9.1",
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/sentry": "^5.0.2",
    "bootstrap": "^4.5.1",
    "call-number": "^1.0.1",
    "capacitor-biometric-auth": "git+https://github.com/aartithummar/capacitor-biometric-auth.git#master",
    "cordova-open-native-settings": "^1.5.3",
    "cordova-plugin-aes256-encryption": "^2.0.1",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-preview-any-file": "^0.2.3",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "core-js": "^3.9.1",
    "dotprop": "^1.2.1",
    "es6-promise-plugin": "^4.2.2",
    "jquery": "^3.6.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "nuxt": "^2.15.3",
    "popper.js": "^1.16.1",
    "portal-vue": "^2.1.7",
    "ssnc-widgets": "file:../ssnc-widgets",
    "vue-fragment": "^1.5.2",
    "vue-i18n": "^8.24.1",
    "vuex-persist": "^3.1.3"
  },
  "devDependencies": {
    "@capacitor/cli": "^2.4.7",
    "@nuxt/babel-preset-app": "^2.15.3",
    "@vue/cli-service": "^4.5.11",
    "babel-preset-vue-app": "^2.0.0",
    "case-sensitive-paths-webpack-plugin": "^2.4.0",
    "chalk": "^4.1.0",
    "cordova-res": "^0.15.3",
    "fs": "0.0.1-security",
    "gulp": "^4.0.2",
    "gulp-clean": "^0.4.0",
    "gulp-download-stream": "0.0.19",
    "gulp-json-editor": "^2.5.4",
    "gulp-replace": "^1.0.0",
    "gulp-request": "0.0.1",
    "gulp-streamify": "^1.0.2",
    "jetifier": "^1.6.6",
    "node-rest-client": "^3.1.0",
    "node-sass": "^5.0.0",
    "nodemon": "^2.0.7",
    "patch-package": "^6.4.7",
    "prettier": "^2.2.1",
    "properties-reader": "^2.2.0",
    "release-it": "^14.4.1",
    "sass-loader": "^10.1.0",
    "symlink-dir": "^4.1.0",
    "vinyl-source-stream": "^2.0.0",
    "vue-resource": "^1.5.2",
    "yargs": "^16.2.0"
`

please let me know if more info is needed or if there is a better place to ask this question?

**Comment by liamdebeasi** [comment]
Thanks for the issue! Ionic Framework does not manage the native calendar picker with `type="date"`, so I do not think this is a bug in Ionic Framework. I recommend asking your question on our forum: https://forum.ionicframework.com/
