### ISSUE TITLE
bug: Ion Datetime will show AM and PM no matter the max or min datetime set

### ISSUE THREAD

**Issue by tomheadifen** [ionic-team/ionic-framework#23198]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
Using the Ion Datetime component formatted to include am / pm with a min and max value set where both the min and max value are in the morning morning you will see both am and pm values.

**Expected behavior:**
When you have a min and max value set that is only in the morning or only in the afternoon you should only see the corresponding am / pm. Not both. The current behavior means that users can potentially pass in incorrect times.

**Steps to reproduce:**
Create a ion datetime component where both the min and max values are in the morning. You will see both AM and PM appearing.

**Screenshot**
![image](https://user-images.githubusercontent.com/5233524/114950485-3b817900-9ea7-11eb-8c43-15025a4e89ae.png)

**Related code:**
```
          <ion-datetime
            name="start-time"
            display-format="h:mm A"
            placeholder="Select time"
            min="2021-02-16T06:00:00.000Z"
            max="2021-02-16T07:00:00.000Z"
          ></ion-datetime>
```

**Other information:**

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.13.1 (/root/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.3

Capacitor:

   Capacitor CLI   : 2.4.5
   @capacitor/core : 2.4.5

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 1.2.2

System:

   NodeJS : v12.18.3 (/root/.nvm/versions/node/v12.18.3/bin/node)
   npm    : 6.14.6
   OS     : Linux 4.19
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to add this to our datetime tracker here: https://github.com/ionic-team/ionic-framework/issues/16630

We are working on a big update to `ion-datetime` which should resolve a majority of these issues and we hope to have more to share soon!
