### ISSUE TITLE
bug: in RTL direction ion-spinner/ion-loader moves up and down instead of circular

### ISSUE THREAD

**Issue by ZeeAziz** [ionic-team/ionic-framework#23202]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
in rtl mode the ion-spinner moves up and down instead of rotating in circular motion

**Expected behavior:**
ion-spinner should spin in circular motion in rtl

**Steps to reproduce:**
apply dir='rtl' on ion-app tag and see the result of ion-loading or ion-spinner

**Other information:**
The following style on svg is causing the bug
```
[dir="rtl"] svg, :host-context([dir="rtl"]) svg {
    left: unset;
    right: 0px;
}
```
![image](https://user-images.githubusercontent.com/78724714/115113340-3e619400-9fa3-11eb-97e8-9ba613e12e5e.png)

**Ionic info:**
Ionic:

 ```
  Ionic CLI                     : 6.13.1
_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.4
   @angular-devkit/build-angular : 0.1102.9
   @angular-devkit/schematics    : 11.2.9
   @angular/cli                  : 11.2.9
   @ionic/angular-toolkit        : 3.1.1

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v13.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.10.0
   OS     : Windows 7

```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
