### ISSUE TITLE
bug: vue, cannot call methods on overlay components using ref

### ISSUE THREAD

**Issue by khaledosman** [ionic-team/ionic-framework#23219]
# Bug Report

Originally posted as a forum question at https://forum.ionicframework.com/t/vue-unable-to-call-component-methods-via-vue-refs-i-e-to-manually-dismiss-a-modal/208120/6

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Calling exposed component methods via refs in vue doesn't work

**Expected behavior:**
Should be able to call component methods using vue refs

**Steps to reproduce:**
See a code example here https://codesandbox.io/s/ionic-5-vue-3-rn1xi?file=/src/About.vue

`modalRef.value.dismiss()` ← doesn’t work
`modalRef.value.$el.dismiss()` ← doesn’t work
`document.querySelector('ion-modal').dismiss()` ← works

**Comment by liamdebeasi** [comment]
Just as an update, this _should_ be much better with `ion-modal` and `ion-popover` in the Framework v6 beta. Doing `modalRef.value.$el.dismiss()` should work in beta 0.

I am going to keep this open since the issue likely still applies for components like `ion-toast` and other overlays.

**Comment by liamdebeasi** [comment]
Hey there,

In Ionic 7.0 we reworked how overlays are constructed. As a result, you will be able to call methods on the remaining overlay components (alert, action sheet, loading, picker, and toast) when this change ships. The work to fix this issue has been completed, so I am going to close this. There will be a public beta period to test Ionic 7 in the future. Let me know if there are any questions.
