### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by rjnunes** [ionic-team/ionic-framework#23216]
# Bug Report

Type: bug

Ionic Version: 1.x

Platform: android 4.4 webview

Ionic advertises its support for service workers: http://blog.ionic.io/tag/service-workers/

The staple app template as generated by https://ionicframework.com/getting-started/

Produces this section:
``
However, un-commenting it and running on Android causes this:
Error DOMException: Failed to register a ServiceWorker: The URL protocol of the current origin ('file://') is not supported.

I have missed a configuration step or Ionic - understood as hybrid app dev framework with Android and iOS being core - does not support service workers as advertised.

Please help

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is the repo for Ionic Framework v4+. The repo for Ionic Framework v1 is https://github.com/ionic-team/ionic-v1. Please note that this repo is not monitored for new issues, so your best bet is to post your question on our forum: https://forum.ionicframework.com/

Additionally, most of the resources you posted assume you are using Ionic Framework v5+, so they likely are not relevant to Ionic Framework v1.
