### ISSUE TITLE
feat: ion-action-sheet custom ionicons

### ISSUE THREAD

**Issue by realappie** [ionic-team/ionic-framework#23226]
# Feature Request

**Ionic version:**
**5.x**

**Describe the Feature Request**

`ion-action-sheet` API currently only allows to pass an existing [ionicon](https://ionicons.com/) name as `icon` property. We should be able to provide it custom icons path.

**Describe Preferred Solution**

We need to add a `iconSrc` to the `ActionSheetButton` and pass that to the `src` property of the `ion-icon` as described in the ionicon docs [here](https://ionicons.com/usage) section "Custom Icons"

So a small modification where we render the `ion-icon` here

https://github.com/ionic-team/ionic-framework/blob/ae47d77710140f01ac9793c7c8c09bfd84b9b6d3/core/src/components/action-sheet/action-sheet.tsx#L267-L273

The simplest solution I can come up with will require the following two things
-  Add a `iconSrc` to the `ActionSheetButton` interface 
- Add this line under the existing icon 
```tsx
{b.iconSrc && <ion-icon src={b.iconSrc} lazy={false} class="action-sheet-icon" />}
```

But all roads lead to rome, so if there is a better way to do this we should do that 😊

**Related Code**
https://github.com/ionic-team/ionic-framework/blob/7703da28f8181b02390b97a7d4d02df99b2ad34c/core/src/components/action-sheet/action-sheet-interface.ts#L19-L25

**Additional Context**
This feature was requested way back in 2016 as part of #6589. Also the current accepted way of doing this was posted on stackoverflow and its not so pretty. See question SO question here [43551463](https://stackoverflow.com/questions/43551463/add-my-custom-icons-to-ionic-2-actionsheets-buttons)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a code example of what you are doing right now? The `icon` property is a combination of both the `name` and `src` properties, so you should be able to pass in either the name of an icon or a path to an SVG:

```js
await actionSheetController.create({
  ...,
  buttons: [
    {
      text: 'My Button',
      icon: './path/to/icon.svg',
    }
  ]
});
```

**Comment by realappie** [comment]
@liamdebeasi I'm impressed! It works, I am closing this and perhaps a mention of this in the docs would be a nice improvement.
