### ISSUE TITLE
bug: IonTextarea autoCapitalize property not working and always defaults to 'none'

### ISSUE THREAD

**Issue by d00ML0rDz** [ionic-team/ionic-framework#23235]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
The autoCapitalize property on the IonTextarea component in the React library always seems to have it's value set to 'none', even when the value is 'on' or 'sentences'.

**Expected behavior:**
The autoCapitalize property correctly applies to the IonTextarea component.

**Steps to reproduce:**
Add an IonTextarea component using the React library inside an IonContent component where the autoCapitalize property is set to either "on" or "sentences":

`<IonTextarea autoCapitalize="on" />`

When the component renders, I get the following HTML where the autocapitalize property on the textarea element is 'none'.

```
<ion-textarea auto-capitalize="on" class="sc-ion-textarea-md-h sc-ion-textarea-md-s md hydrated">
    <div class="textarea-wrapper sc-ion-textarea-md">
        <textarea class="native-textarea sc-ion-textarea-md" autocapitalize="none" name="ion-textarea-1" placeholder="" spellcheck="false"></textarea>
    </div>
</ion-textarea>
```

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.11.0 (C:\Users\jammi\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.6.5

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v14.15.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.9
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is that you are writing `autoCapitalize` instead of `autocapitalize`. I know some other libraries prefer `autoCapitalize`, but we try to stay as close to the native HTML spec as possible. Doing the following should work:

```html
<IonTextarea autocapitalize="on" />
```
