### ISSUE TITLE
bug: IonNav is creating a new RootPage after modal dismiss

### ISSUE THREAD

**Issue by florian72810** [ionic-team/ionic-framework#23233]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I am using navigation inside a modal with IonNav. When I dismiss the modal, the IonNav is creating a new rootPage component.

**Expected behavior:**

When the modal is dismissed, IonNav should not create new component.

**Steps to reproduce:**

Using Ionic/Vue, create a IonNav inside a modal. You have to make a navigation action inside the modal (push) for the problem to appear.

If no navigation is made (modal dismiss without navigation), the case does not happen.

**Related code:**

Using the "Ionic/Vue Nav in modals" sample project from aaronksaunders, with some additional log statements [https://github.com/florian72810/ionic-vue-nav-in-modals](https://github.com/florian72810/ionic-vue-nav-in-modals)

```
BaseModal: created
ModalHome.vue?7215:80 ModalHome: created
ModalHomeDetail.vue?4bd5:53 ModalHomeDetail: created
ModalHome.vue?7215:68 ModalHome: modal is dismissing
ModalHome.vue?7215:80 ModalHome: created
ModalHome.vue?7215:70 ModalHome: modal dismissed
```

With the simple project, the problem is not blocking. But on my real project, the modal is dismissed while still rendering. This ends with an error "Cannot read property '__composer' of undefined" from "vue-i18n", and the router does not respond.

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.5.4

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v14.15.4 (/Users/foxer/.nvm/versions/node/v14.15.4/bin/node)
   npm    : 6.14.10
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide some steps to reproduce the issue? Opening the modal then clicking the "Close" button does not seem to reproduce the issue on my end.

**Comment by florian72810** [comment]
Yes, exactly, without doing any navigation inside the modal, it works as expected.

You have to open the modal, click the button "show modal detail" to navigate inside the modal, then go back and close the modal.

**Comment by liamdebeasi** [comment]
Thanks! Sorry I must have misread your original post. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@5.7.0-dev.202104261509.665b9c9 @ionic/vue-router@5.7.0-dev.202104261509.665b9c9
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/issues/23233, and a fix will be available in an upcoming release of Ionic Framework.
