### ISSUE TITLE
bug: Dark theme not working on bottom navigation bar of device

### ISSUE THREAD

**Issue by mayankkataria** [ionic-team/ionic-framework#23236]
When I'm changing my app theme to dark, the theme of bottom navigation bar (where overview, home and back buttons are present) remains light i.e. background is still white with black icons.

**Comment by BerkeAras** [comment]
@mayankkataria A few things:
1. Use the issue template the next time
2. Give us some code to reproduce the issue
3. Which Ionic version do you use? (run ionic info)

**Comment by mayankkataria** [comment]
@BerkeAras
1. What's issue template?
2. Here's my ```changeTheme()``` method code where I'm changing the theme of my app:
```
changeTheme() {
    this.darkTheme = !this.darkTheme;
    if (this.darkTheme) {
      // Change app theme
      document.body.setAttribute('theme-color', 'dark');
      // Change StatusBar theme
      StatusBar.setBackgroundColor({ color: 'black' });
      StatusBar.setStyle({style: StatusBarStyle.Dark});
      // How to change Bottom Navigation Bar theme?
    } else {
      // Change app theme
      document.body.setAttribute('theme-color', 'light');
      // Change StatusBar theme
      StatusBar.setBackgroundColor({ color: 'white' });
      StatusBar.setStyle({style: StatusBarStyle.Light});
      // How to change Bottom Navigation Bar theme ?
    }
  }
```
3. When I run ```ionic info``` I got this:
```
Ionic:

   Ionic CLI                     : 6.13.1 (C:\Users\mynkk\AppData\Roaming\nvm\v14.15.4\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1002.3
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0

Utility:

   cordova-res (update available: 0.15.2) : 0.11.0
   native-run (update available: 1.3.0)   : 0.3.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This is more of a support question, so I would encourage you to post your question on our [forum](https://forum.ionicframework.com/) instead. I recommend trying to reproduce this issue in an Ionic starter app and provide a link to the repo when posting your question.

**Comment by mayankkataria** [comment]
Well I found a workaround [here](https://stackoverflow.com/questions/67262794/change-bottom-navigation-bar-color-in-ionic-5/67281442#67281442)
