### ISSUE TITLE
bug: Virtual Scroll with Radio Group selection

### ISSUE THREAD

**Issue by SidiBecker** [ionic-team/ionic-framework#23249]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
With a large list of items, using ` ion-virtual-scroll` and `ion-radio-group`, when scrolling the screen, extra records are marked on screen, or, in some cases, it does not keep selected.

**Expected behavior:**
Keep selected only the record with the `ion-radio-group` value.

**Steps to reproduce:**
Put many items in a list and scroll the screen.

**Related code:**
StackBlitz: https://stackblitz.com/edit/virtual-scroll-with-radio-group-bug?file=src/app/tab1/tab1.page.html

```
<ion-content>
  <ion-radio-group [value]="selected">
    <ion-virtual-scroll [items]="items">
      <ion-item *virtualItem="let item">
        <ion-radio mode="md" [value]="item.id"></ion-radio>
        <ion-label>{{ item.name }}</ion-label>
      </ion-item>
    </ion-virtual-scroll>
  </ion-radio-group>
</ion-content>
```

```
export class Page implements OnInit {
  public items = [];
  public selected = 2;
  constructor() {}

  ngOnInit() {
    for (let index = 1; index < 91; index++) {
      this.items.push({ id: index, name: `Item ${index}` });
    }
  }
}
```

**Other information:**
```
**Ionic info:**
Ionic CLI                     : 6.14.0 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.6
   @angular-devkit/build-angular : 0.1102.11
   @angular-devkit/schematics    : 11.2.11
   @angular/cli                  : 11.2.11
   @ionic/angular-toolkit        : 3.1.1

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Comment by achakra21** [comment]
I found in `ion-virtual-scroll` doesn't know the position of the item in the screen when the list goes out the screen ,from your code i found a pattern  if you `**selects**` a radio button at item `index 2 ` the lets say your screen viewport can accomodate 15 items then the next select is coming at index 32. So the solution is when your scroll reach at the point 15 you can marks the tail the items array as dirty, so they can be re-rendered. using checkEnd() method (its a ion-virtual-scroll method) other wise don't use  `virtualscroll` the code below is working fine i didnt found any difference 
```
<ion-radio-group [value]="selected">
    <!-- <ion-virtual-scroll [items]="items"> -->
      <ion-item *ngFor="let item of items">
        <ion-radio mode="md" [value]="item.id"></ion-radio>
        <ion-label>{{ item.name }}</ion-label>
      </ion-item>
    <!-- </ion-virtual-scroll> -->
  </ion-radio-group>
```

**Comment by SidiBecker** [comment]
Thank`s for reply me @achakra21! 
I need to use `ion-virtual-scroll` because my implementation have a heavy html. Whitout that, the screen takes a long time to render. This code is just an example. 
How can I use the `checkEnd() method to resolve my case?`

**Comment by achakra21** [comment]
Ohh that's straight forward , once you found the last element in the `viewport`  lets say you have 60 elements loaded in the `ion-virtual-scroll` and 15 is the last element in the `viewport` when you scroll to next section which is` 16 to 30 ` you should call `checkEnd()`

**html** 

```
<ion-content>
  <ion-radio-group [value]="selected">
    <ion-virtual-scroll [items]="items"  #myvirtualscroll>
      <ion-item *virtualItem="let item">
        <ion-radio mode="md" [value]="item.id"></ion-radio>
        <ion-label>{{ item.name }}</ion-label>
      </ion-item>
    </ion-virtual-scroll>
  </ion-radio-group>
</ion-content>
```
**ts file**

@ViewChild('myvirtualscroll') myvirtualscroll: IonVirtualScroll;

when you scroll reach 16 item position call
     ```
this.myvirtualscroll.checkEnd();
    window.dispatchEvent(new Event('resize'));
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! With the release of Ionic 6, we made the decision to deprecate `ion-virtual-scroll` in favor of 3rd party solutions.

Moving forward, `ion-virtual-scroll` will only receive critical security fixes, and the component will be removed in Ionic 7. As a result, I am going to close this issue.

We have prepared migration guides for each of the 3 JavaScript frameworks we support, so developers can get started migrating right away.

[Migration for Angular](https://ionicframework.com/docs/angular/virtual-scroll)
[Migration for React](https://ionicframework.com/docs/react/virtual-scroll)
[Migration for Vue](https://ionicframework.com/docs/vue/virtual-scroll)

Some Ionic components that rely on scrolling inside of `ion-content` have some limitations when using 3rd party virtual scrollers, but we are actively working on a solution for this. Please follow https://github.com/ionic-team/ionic-framework/issues/23437 for updates. Thanks for your patience as we work to resolve this issue.

We believe this change will lead to a healthier Ionic ecosystem as it frees up resources for the Ionic team to dedicate to other areas of this project while still giving developers options for performant virtual scroll solutions.

Thank you!
