### ISSUE TITLE
bug: Ionic Vue Router throwing error when its running on server in SSR mode.

### ISSUE THREAD

**Issue by mohammadsiddiqui** [ionic-team/ionic-framework#23254]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Running ionic vue with SSR with ionic router, the @ionic/vue-router throws an error about history is not defined when it is running on server.

**Expected behavior:**

The error should not trigger.

**Steps to reproduce:**

clone the repo https://github.com/mohammadsiddiqui/vue-ionic-ssr and build it and run it in SSR mode and look at the server console.
**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

![image](https://user-images.githubusercontent.com/24387047/116839842-b054f280-abcb-11eb-89d2-f20f5858ed59.png)

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue and PR! Could your provide some more steps to reproduce? I am trying to run the app in SSR mode, but I do not get the `history is not defined` error.

**Comment by mohammadsiddiqui** [comment]
In the repo, I forgot to add back vue-router dependency as I was testing without ionic-router which I did now. you can run the same now.
Node: 12.16.3
NPM: 6.14.5

I have recorded a video demonstrating the issue, please find the link here. 

https://player.vimeo.com/video/544647326

![image](https://user-images.githubusercontent.com/24387047/116908124-74a54180-ac3a-11eb-980a-f36d2e8c4fbf.png)

**Comment by liamdebeasi** [comment]
Thanks, that makes sense. I left a comment on your PR.

**Comment by liamdebeasi** [comment]
Also here is a dev build of your changes if you would like to test them in your app:

```
npm install @ionic/vue@5.7.0-dev.202105031742.e2a0ece @ionic/vue-router@5.7.0-dev.202105031742.e2a0ece
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23255, and a fix will be available in an upcoming release of Ionic Framework.
