### ISSUE TITLE
bug: Ion-Modal component doesn't render when used with Vue 3 suspense

### ISSUE THREAD

**Issue by karmstr7** [ionic-team/ionic-framework#23274]
# Bug Report

**Packages:**
**@ionic-native/core: ^5.30.0**
**@ionic/core: ^5.5.1**
**@ionic/vue: ^5.5.2**
**vue: ^3.0.4**

**Current behavior:**
This is the top level code that renders each individual pages in the app:
```<Suspense>
                <template #default>
                    <transition name="fade" mode="out-in">
                        <component :is="Component" />
                    </transition>
                </template>
                <template #fallback>
                    <div>
                        <br />
                        <ion-spinner class="block-centered" />
                    </div>
                </template>
            </Suspense>
```

One of the pages uses and opens ion-modal, and in the modal I have this code:
```
<script>
import { IonContent, IonHeader, IonTitle, IonToolbar } from '@ionic/vue'
import { defineComponent } from 'vue'
import useCourse from '@/composables/global/use-course'

export default defineComponent({
    components: { IonContent, IonHeader, IonTitle, IonToolbar },
    props: {
        title: { type: String, default: 'Super Modal' },
    },
    async setup() {
        const { courses: courseList, fetchCourses } = useCourse()

        await fetchCourses()

        console.log({ courseList })
        return {
            content: 'Content',
        }
    },
})
</script>

<template>
    <ion-page>
        <ion-header>
            <ion-toolbar>
                <ion-title>{{ title }}</ion-title>
            </ion-toolbar>
        </ion-header>
        <ion-content class="ion-padding">
            {{ content }}
        </ion-content>
    </ion-page>
</template>
```

Implementing the example code found [here](https://ionicframework.com/docs/api/modal) results in a blank rendering of the modal component. Whether be using modalController or IonModal, the error still happens. When using a regular component in place of the modal, the component renders correctly.

**Expected behavior:**
The modal component should be able to work with suspense and render its content after a short delay.

**Comment by willmartindev** [comment]
Thanks for the issue, @karmstr7! Could you reproduce this in an Ionic starter app and provide a link to the repo?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
