### ISSUE TITLE
bug: Unable to style inner <img> tag of <ion-img>

### ISSUE THREAD

**Issue by eqcb** [ionic-team/ionic-framework#23276]
# Bug Report

**Ionic version:**

[x] **5.0.7**

**Current behavior:**

Trying to style the inner <img> tag of <ion-img> does not work as per documentation(accessing the --image shadow part)
I'm trying to limit the image max-height without success.

**Expected behavior:**

The inner <img> max-height should be what I set on the .scss file of that page.

**Steps to reproduce:**

Add a high height image in an <ion-card> as the [src] of an <ion-img> and add to the .scss file:

ion-img {
  --image: {
    object-fit: cover;
    max-height: 196px;
 }
}

**Related code:**

```
        <ion-list lines="none">

          <ion-item *ngFor="let p of promocoes" [routerLink]="['/','promocoes',p.Id]">

            <ion-card>

              <ion-card-header class="ion-no-padding">
                <ion-card-title> {{p.Titulo}} </ion-card-title>
                <ion-card-subtitle>{{p.NomeRestaurante}}</ion-card-subtitle>
              </ion-card-header>

              <ion-img [src]="p.UrlFoto"></ion-img>

              <ion-card-content class="ion-no-padding">
                <div class="info">
                  <div class="distance" *ngIf="p.Distancia != -1">
                    <span>{{p.Distancia | number : '1.2-2'}}{{ p.Distancia >= 1.0 ? "Km" : "m"}}</span>
                  </div>
                  <div class="description">
                    <p>{{p.Descricao}}</p>
                  </div>
                  <div class="price">
                    <span>{{p.Valor | currency}}</span>
                  </div>
                </div>
              </ion-card-content>

            </ion-card>

          </ion-item>

        </ion-list>

```

**Other information:**

Found same issue here but without any answers and closed automatically. #18021

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (C:\Users\geter\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.0
   @capacitor/core : 2.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.11
   OS     : Windows 10
```

**Comment by willmartindev** [comment]
Hi @eqcb! Selecting a shadow part in CSS/SCSS uses the `::part()` notation, described [here.](https://developer.mozilla.org/en-US/docs/Web/CSS/::part)

When I change your example code to the following, it works: 
```scss
ion-img {
  &::part(image) {
    max-height: 196px;
    object-fit: cover;
  }
}
```

Let me know if this works for you, and thank you for opening an issue. ☺️

**Comment by eqcb** [comment]
Hello @willmartindev. Thanks for replying.

I tried the css you posted but unfortunately it didn't work. Take a look at the browser inspector with computed styles:

![image](https://user-images.githubusercontent.com/8282658/117312926-d2fd3a80-ae5b-11eb-9982-719433920da0.png)

If I do it like this: 

ion-img {

   object-fit: cover;

  &::part(image) {
    max-height: 196px;
   }
}

the computed value for object-fit does change to `cover`. But that's all. Trying to add max-height to ion-img has no effect.

What I'm trying to do is to get the image cropped and centered while keeping the aspect ratio. object-fit: cover and max-height does the trick if I manually add them on the fly in the inspector.

**Comment by willmartindev** [comment]
@eqcb Could you reproduce this in an Ionic starter app and provide a link to the repo? I'm having difficulty reproducing the issue on my side.

**Comment by willmartindev** [comment]
Ah, actually @eqcb, I see you are using **v5.0.7**. Shadow part support was added in **v5.1.0**, so updating to a newer version of the framework should fix your issue.

**Comment by HyperLife1119** [comment]
Firefox does not seem to support ::part.

**Comment by eqcb** [comment]
Upgrading to 5.1.0 made it work! Thank you @willmartindev!
