### ISSUE TITLE
bug: Ionic back button bug only working after I slide the pointer on It

### ISSUE THREAD

**Issue by pepeillo12345** [ionic-team/ionic-framework#23291]
So basically, I have this simple code that should be working fine but for some reason I’m getting a rare bug.

Ionic version: 5.4.16

Current behavior: 
I have a page called “home” and a sidemenu which I use to navigate to the page “mysports”. When It first loads the page “mysports”, it displays the ion-back-button, but whenever I try to click it, it doesn’t work.
But, when I click the ion-back-button and slide it to the left, the HTML refreshes and the ion-back-button works perfectly fine.

On my html I have this code:

```<ion-header>
  <ion-toolbar>
    <ion-buttons>
      <ion-back-button text="Back"></ion-back-button>
      <ion-label>
        <ion-title class="ion-text-center">spoRts</ion-title>
      </ion-label>
    </ion-buttons>
  </ion-toolbar>
</ion-header>

<ion-content>

</ion-content>

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo?

**Comment by pepeillo12345** [comment]
Nevermind, already fixed it, looks like when using router.navigateByUrl() the sidemenu I had from previous page didn't close thats why I needed to slide to the left, to hide the "invisible" sidemenu
