### ISSUE TITLE
Ion-refresher is getting triggered when pulling up on Android

### ISSUE THREAD

**Issue by alexedwalvarado** [ionic-team/ionic-framework#23302]
<img width="454" alt="Screenshot 2021-05-14 at 14 56 44" src="https://user-images.githubusercontent.com/25674656/118273811-b187f880-b4c4-11eb-8eba-2cfadec8f075.png">
**Ionic version:**
[ ] **6.14.1**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
Ion-refresher is trigged when pulling up. See the uploaded picture. The arrow shows the gesture down by the user when triggering ion-refresher.

**Expected behavior:**
It should be triggered only when pulling down.

**Steps to reproduce:**
1) Run application on Android
2) Swipe up

**Related code:**
```
<ion-content class="ion-no-padding ion-margin-bottom" fullscreen="true">
  <ion-refresher slot="fixed" pullFactor="0.5" pullMin="300" pullMax="200" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
</ion-content>
```

**Ionic info:** 
```
Ionic:

   Ionic CLI                     : 6.14.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.6
   @angular-devkit/build-angular : 0.1100.7
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v14.16.1 (/usr/local/bin/node)
   npm    : 6.14.12
   OS     : macOS Big Sur
   Xcode  : Xcode 12.5 Build version 12E262
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This was fixed in Ionic Framework v5.6.7 😄 .

```
npm install @ionic/angular@5.6.7
```
