### ISSUE TITLE
ion-menu loading half screen

### ISSUE THREAD

**Issue by rajiv687** [ionic-team/ionic-framework#23305]
ion-menu loading half screen , working fine on browser inspect however issue is on simulator 
<img width="357" alt="Screenshot 2021-05-15 at 6 08 04 PM" src="https://user-images.githubusercontent.com/17966722/118361460-2af91700-b5a9-11eb-9375-e58948ba5743.png">

**Comment by achakra21** [comment]
This looks strange to me , can you add your code snippet , or a sample project on github  & please mention the ionic version and which simulator you are using

**Comment by rajiv687** [comment]
ionic --version
5.4.16.

**Comment by rajiv687** [comment]
<ion-split-pane when="sm"  contentId="main-content" class="split-pane-visible">
  <ion-menu contentId="main-content" swipeGesture="true"  (click)="closeMenu()">
    <ion-content >
      <nav class="nav-menu">
        <div class="logo d-md-none">
          <img src="assets/images/iLMS_logo.svg" alt=“ logo"/>
        </div>
        <ul class="nav-list no-bullet">

            <li  [routerLinkActive]="['active']">
              <a
               class="nav-item"
               [routerLink]="['/menu/markUp']"
               tabindex="100"
               id="lnkScheduleMark"
               >
                 Mark 
               </a>
             </li>

              <li [routerLinkActive]="['active']">
                  <a
                   class="nav-item"
                   routerLink="/menu/vacancies"
                   tabindex="100"
                   id="lnkSchedule"
                   >
                     Vacancy
                   </a>

                 </li>

          <li [routerLinkActive]="['active']">
           <a
            class="nav-item"
            routerLink="/menu/schedule"
            tabindex="100"
            id="lnkSchedule"
            >
              Schedule
            </a>
            <ul class="no-bullet sub-nav-items d-none d-sm-block">
              <li>
                <a
                  ng-class="{'active': $state.includes('main.schedule.overview') || matchesTopLevelNav('main.schedule.overview')}"
                  ng-click="menuClick('main.schedule.overview')"
                  tabindex="101"
                  id="lnkCurrentSchedule"
                >
               Test3
                </a>
              </li>
              <li>
                <a
                  ng-class="{'active': $state.includes('main.schedule.entitlements') || matchesTopLevelNav('main.schedule.entitlements')}"
                  ng-click="menuClick('main.schedule.entitlements')"
                  tabindex="102"
                  id="lnkVacations"
                  >
                  Test2
                </a>
              </li>

            </ul>
          </li>
          <li [routerLinkActive]="['active']">
            <a *ngIf="!isWeb"
              class="nav-item"
              [routerLink]="['/menu/assignments-bids']"
              tabindex="104"
              id="lnkABOverview"
              >
              Assignments &amp; Bids
            </a>
            <a *ngIf="isWeb"
              class="nav-item"
              ng-click="menuClick('main.assignments.permanentAssignment')"
              tabindex="104"
              id="lnkABPermAssignment"
              >
              Assignments
            </a>
            <ul *ngIf="isWeb" class="no-bullet sub-nav-items">
              <li>
                <a
    
                  tabindex="105"
                  id="lnkJobOwned"
                >
                  Job Owned
                </a>
              </li>
              <li>
                <a
              
                  tabindex="106"
                  id="lnkBulletins"
                >
                 Test2
                </a>
              </li>
              <li>
                <a
         
                  tabindex="109"
                  id="lnkOptionals"
                >
                 Test1
                </a>
              </li>
            </ul>
          </li>

        </ul>

      </nav>
      <button
        class="logOutButton"
        (click)="onLogout()"
        tabindex="124"
        style="margin: 1rem; width: calc(100% - 2rem);"
        id="btnLogout"
        >
        Log Out
      </button>
  

    </ion-content>

  </ion-menu>
  <ion-router-outlet id="main-content"></ion-router-outlet>
</ion-split-pane>
