### ISSUE TITLE
bug: action sheet header and subheader are not aligned/sized properly on ios

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#23317]
# Feature Request

**Ionic version:**
**5.x**

**Describe the Feature Request**

- The header text is too small.
- The icon maybe looks better when aligned at the left side?
- Add more space between icon and text.

**Current Behavior**
![image](https://user-images.githubusercontent.com/60390085/118531169-d50da600-b745-11eb-9263-91e5651bd64f.png)

**Preferred Solution**
![image](https://user-images.githubusercontent.com/60390085/118531111-c0c9a900-b745-11eb-878c-3e8fdaf07251.png)

Or all left align when icons are set? 
![image](https://user-images.githubusercontent.com/60390085/118531304-fb334600-b745-11eb-84ef-632d0184f33a.png)

(just some images from the web.)

Even if we stick to the iOS styles we should not hesitate to improve the style. We'll never perfect match the original native style. So why not improve things?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@5.7.0-dev.202105172137.6363d14
```

I fixed a few things that should make the action sheet look more like its native counterpart:

- Header is now a heavier font weight when a sub header is present
- Increased the font size of the subheader
- Reduced the spacing between the bottom of header and top of subheader
- Increased the spacing between the right edge of the icon and the left of the text in a button (I opted not to left align the icons since that is a bigger design change, but this increased spacing should help for now)

**Comment by infacto** [comment]
New result: 

![image](https://user-images.githubusercontent.com/60390085/118637312-f027f680-b7d5-11eb-9603-60a6824405d0.png)

Much better, thanks. 👍 

Just FYI in my case I added a custom class to hack some styles for that result:

![image](https://user-images.githubusercontent.com/60390085/118637898-9542cf00-b7d6-11eb-99f1-4cfbe6977849.png)

- Bigger text (header, subHeader).
- Border lines between buttons. (like on ion-item)

(font-size header 1.2em (bold) and sub header 0.8em (normal)) Better to read.
(don't add a border line at the bottom of the last button child. only a border at the top of each button, except the single cancel button.)

It's more like the original style: 

![image](https://user-images.githubusercontent.com/60390085/118638310-fff40a80-b7d6-11eb-9b9b-d95094fb6906.png)

With icons (all items with or without icons same layout):

![image](https://user-images.githubusercontent.com/60390085/118638427-1f8b3300-b7d7-11eb-9c24-b3dd6991ffb3.png)

(Not 100% sure if this is the original style. But looks not bad.)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23322, and a fix will be available in an upcoming release of Ionic Framework.
