### ISSUE TITLE
bug: Action sheet (md) subHeader overlapps the buttons.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#23316]
# Bug Report

**Ionic version:**
**5.x**

**Current behavior:**
The subHeader text overlapps the action buttons. 

**Expected behavior:**
!CurrentBehavior (No overlapping elements.)

**Steps to reproduce:**

**Related code:**

```
const actionSheet = await this.actionSheetCtrl.create({
  header: 'Demo',
  subHeader: 'This is a demo of an action sheet with a sub header.',
  buttons: [
    {
      text: 'Cancel',
      role: 'cancel',
    },
    {
      text: 'Bug',
      icon: 'bug',
    },
  ],
});

await actionSheet.present();
```

![image](https://user-images.githubusercontent.com/60390085/118530254-bbb82a00-b744-11eb-8677-6b6eb89ae7bf.png)

**Other information:**
Also see e.g. #17588 (which was closed due to inactivity)...
The ios mode is ok. It only appears in md mode.

![image](https://user-images.githubusercontent.com/60390085/118530654-2e290a00-b745-11eb-98f0-6cece043a24f.png)

**Ionic info:**

```
"@ionic/angular": "^5.3.2",
Windows 10
Chrome / Edge (Chromium 90)
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@5.7.0-dev.202105171939.d4827c1
```

**Comment by infacto** [comment]
@liamdebeasi Yes fixed. 👍

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23318, and a fix will be available in an upcoming release of Ionic Framework.
