### ISSUE TITLE
bug: Nested routes in tabs does not work (ionic react)

### ISSUE THREAD

**Issue by justinpathrose** [ionic-team/ionic-framework#23315]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.6.7**

**Expected behavior:**

Nested routes within Ion Tabs should work normally.

**Steps to reproduce:**

The routing of our app has a nested route which is rendered inside a tab. This does not work now.

I have created a codesandbox which roughly reflects the routing we use in our original app.  

In this project, we have 2 main routes "/home" and "/tabs".  The "/home" route renders the landing page from which we can navigate to the page rendering the tabs. The "/tabs" route renders MainTabs component which renders 3 tabs. In Tab1, we renders 3 more routes like this "/tabs/tab1/page1", "/tabs/tab1/page2" etc..

So if you navigate from Tab1 to Tab2, and try to go back to Tab1, it does not work. All the navigations within the Tab1 works fine.

**Related code:**

App.tsx
```
    <IonReactRouter>
      <IonRouterOutlet id="app">
        <Redirect exact path="/" to="/home" />
        <Route path="/home" render={() => <Home />} />
        <Route path="/tabs" render={() => <MainTabs />} />
      </IonRouterOutlet>
    </IonReactRouter>
```

MainTabs.tsx
```
    <IonTabs>
      <IonRouterOutlet id="main-tabs">
        <Route path="/tabs/tab1" render={() => <Tab1 />} />
        <Route path="/tabs/tab2" render={() => <Tab2 />} />
        <Route path="/tabs/tab3" render={() => <Tab3 />} />
      </IonRouterOutlet>
      <IonTabBar slot="bottom">
        <IonTabButton tab="tab1" href="/tabs/tab1">
          <IonIcon icon={triangle} />
          <IonLabel>Tab 1</IonLabel>
        </IonTabButton>
        <IonTabButton tab="tab2" href="/tabs/tab2">
          <IonIcon icon={ellipse} />
          <IonLabel>Tab 2</IonLabel>
        </IonTabButton>
        <IonTabButton tab="tab3" href="/tabs/tab3">
          <IonIcon icon={square} />
          <IonLabel>Tab 3</IonLabel>
        </IonTabButton>
      </IonTabBar>
    </IonTabs>
```

Tab1.tsx
```
    <IonRouterOutlet id="inner-pages">
      <Redirect exact path="/tabs/tab1" to="/tabs/tab1/page1" />
      <Route path="/tabs/tab1/page1" render={() => <Tab1Page1 />} />
      <Route path="/tabs/tab1/page2" render={() => <Tab1Page2 />} />
      <Route path="/tabs/tab1/page3" render={() => <Tab1Page3 />} />
    </IonRouterOutlet
```

The link to the sandbox - https://codesandbox.io/s/1zmpd?file=/package.json

Not sure if I am doing something wrong in the routing structure. I had checked the same using react router in a CRA project and it worked. Attaching the video here.

![routing](https://user-images.githubusercontent.com/7420258/118527108-93d5c000-b75e-11eb-9548-1e20f423b4ab.gif)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.15.0 (C:\Users\justi\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.6.7

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : 1.3.0

System:

   NodeJS : v12.19.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Since your routes have pieces of the URL in common, it is better to write these as sibling routes rather than nested routes.

So in your `MainTabs.tsx` file you would write:


```jsx
...

<IonRouterOutlet id="main-tabs">
  <Redirect exact path="/tabs/tab1" to="/tabs/tab1/page1" />
  <Route path="/tabs/tab2" render={() => <Tab2 />} />
  <Route path="/tabs/tab3" render={() => <Tab3 />} />
          
   <Route path="/tabs/tab1/page1" render={() => <Tab1Page1 />} />
   <Route path="/tabs/tab1/page2" render={() => <Tab1Page2 />} />
   <Route path="/tabs/tab1/page3" render={() => <Tab1Page3 />} />
</IonRouterOutlet>

...
```

Nested routes are great for when you need to render content in two different views (I.e. a tab bar in the main view and the tab content in another view). That does not seem to be the case here as you render additional pages inside of the `Tab1` page.

Can you give that change a try and let me know if it fixes the issue?

**Comment by justinpathrose** [comment]
> Thanks for the issue. Since your routes have pieces of the URL in common, it is better to write these as sibling routes rather than nested routes.
> 
> So in your `MainTabs.tsx` file you would write:
> 
> ```js
> ...
> 
> <IonRouterOutlet id="main-tabs">
>   <Redirect exact path="/tabs/tab1" to="/tabs/tab1/page1" />
>   <Route path="/tabs/tab2" render={() => <Tab2 />} />
>   <Route path="/tabs/tab3" render={() => <Tab3 />} />
>           
>    <Route path="/tabs/tab1/page1" render={() => <Tab1Page1 />} />
>    <Route path="/tabs/tab1/page2" render={() => <Tab1Page2 />} />
>    <Route path="/tabs/tab1/page3" render={() => <Tab1Page3 />} />
> </IonRouterOutlet>
> 
> ...
> ```
> 
> Nested routes are great for when you need to render content in two different views (I.e. a tab bar in the main view and the tab content in another view). That does not seem to be the case here as you render additional pages inside of the `Tab1` page.
> 
> Can you give that change a try and let me know if it fixes the issue?

Thank you.

I tried out the suggested changes and it is now working.

So this happens because it is being done inside of IonTabs is it?

**Comment by liamdebeasi** [comment]
Yes I believe that is part of it. If you wanted to nest another set of tabs inside of the tabs you already have (which we do not recommend since it seems like a confusing UX), you would be able to write your code as you did previously. In your original case, there is no need to do that since you are still sharing part of the URL inside of Tab1, so you can avoid the additional router outlet. I am going to close this since things seem to be working now. Thanks!
