### ISSUE TITLE
bug: a11y, talkback reads tab button twice when swiping to go to next/previous tab button

### ISSUE THREAD

**Issue by VittorioEuris** [ionic-team/ionic-framework#23332]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
When going over a tab-button with screen-reader it will be red but if I tick left with one finger it keeps on the same item, reading again the label and identifing it as tab. Inspecting the item it's caused by an anchor element inside the component.
This happens only on Android Talkback.

**Expected behavior:**
As on iOS the screen reader should ignore the anchor inside the component.

**Steps to reproduce:**
- Create a new app with tabs
- With screen reader enabled, on Android, tap on a tab button
- Swipe left with one finger

**Related code:**
https://github.com/VittorioEuris/ionic-a11y-issues.git

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.1
   Ionic Framework               : @ionic/angular 5.6.7
   @angular-devkit/build-angular : 0.1102.13
   @angular-devkit/schematics    : 11.2.13
   @angular/cli                  : 11.2.13
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI      : 3.0.0
   @capacitor/android : 3.0.0
   @capacitor/core    : 3.0.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.3.0

System:

   NodeJS : v14.17.0 (~/.nvm/versions/node/v14.17.0/bin/node)
   npm    : 6.14.13
   OS     : Linux 5.11
```

**Comment by VittorioEuris** [comment]
Same problem with the ion-segment-button:
Role tab with correct label and nested button with the same label that could not be hidden from the aria tree.
I've updated the repository with the ion-segment section on tab1 page.

**Comment by rafadbv** [comment]
Same problem here using ion-checkbox, ion-toggle and ion-segment

**Comment by Hari0507** [comment]
Same issue here. Any solution ?
