### ISSUE TITLE
bug: @ionic/react references unknown type React.forwardedRef

### ISSUE THREAD

**Issue by AntoineDannemark** [ionic-team/ionic-framework#23330]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.6.6, 5.6.7**

**Current behavior:**
enabling lib checking by the typescript compiler results in errors due to the usage of non-existing type React.forwardedRef in the following files:
- @ionic/react/dist/types/components/utils/index.d.ts on lines 6 & 7
- @ionic/react/dist/types/routing/PageManager.d.ts on line 7

**Expected behavior:**
No usage of non-existing types

**Steps to reproduce:**
Create a fresh ionic react app using @ionic/react version 5.6.6 or 5.6.7, and set _skipLibCheck_ to _false_ in the tsconfig. then run `tsc`;

**Related code:**

```
export declare const setRef: (ref: React.ForwardedRef<any> | React.Ref<any> | undefined, value: any) => void;
export declare const mergeRefs: (...refs: (React.ForwardedRef<any> | React.Ref<any> | undefined)[]) => React.RefCallback<any>;
```

```
interface PageManagerProps {
    className?: string;
    forwardedRef?: React.ForwardedRef<HTMLDivElement>;
    routeInfo?: RouteInfo;
}
```

**Other information:**
Our use case is actually different from the reproducible exemple above: 
Our app must be built for native as well as electron (@capacitor-community/electron). 
We are using the same _api_ repo (sqlite database code with typeorm), cloned in the react app _src_ folder (using cordova driver), as well as in in the electron _src_ folder (using better-sqlite3 driver). 
In this repo, we require _isPlatform_ from @ionic/react (but we use some guards to avoid using it when run in the electron folder) 
We noticed the error there, as the generated tsconfig for electron does not skip lib checking

As a sidenote, the version that we were using initially (5.5.2) does not mention these types and therefore did not break.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.15.0 (C:\Users\Antoine\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.6.6

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : 2.4.6

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try updating your `@types/react` dependency? The `ForwardedRef` type exists: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/737e5b0b2dc36feeed9b7ff6baf1c11a3e516396/types/react/index.d.ts#L561 your types dependency might just be outdated.

**Comment by AntoineDannemark** [comment]
yup it works now with @types/react 17.0.6 & @types/react-dom 17.0.5. Thx!!
