### ISSUE TITLE
bug: back button android closes app

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-framework#23348]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I am not 100% sure if this is a Capacitor or Ionic Angular Issue. 
If i navigate to a Page on Android and then press the Back button, the App Does close
`<ion-button [routerLink] ...`

**Expected behavior:**

The App should Navigate Back to the Page before. The App should only close then there is no parent Page left. 

**Steps to reproduce:**

Latest Capacitor / Ionic Angular Project.
Add a Page and a button to navigate to the page. 
Install on Android and click the button press then the Android Native Back button. 

**Other information:**
Capacitor Version 3 Stable.
The Latest Ionic Version (5.6.7)

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is likely that you did not install the `App` plugin when upgrading to Capacitor 3. (We received a similar issue last week). Please see the Capacitor 3 migration guide for more information: https://capacitorjs.com/docs/updating/3-0#migrating-your-app-to-use-the-new-official-plugin-packages

**Comment by danielehrhardt** [comment]
> Thanks for the issue. The problem here is likely that you did not install the `App` plugin when upgrading to Capacitor 3. (We received a similar issue last week). Please see the Capacitor 3 migration guide for more information: https://capacitorjs.com/docs/updating/3-0#migrating-your-app-to-use-the-new-official-plugin-packages

I created a new App from scratch.

**Comment by liamdebeasi** [comment]
What version of the Ionic CLI are you using? Older versions of the CLI will not install the App plugin for you automatically since this is a new requirement in Capacitor 3.

I am testing with Ionic CLI `6.16.1` with a blank Ionic Angular app, and the hardware back button is working as expected.

**Comment by danielehrhardt** [comment]
> What version of the Ionic CLI are you using? Older versions of the CLI will not install the App plugin for you automatically since this is a new requirement in Capacitor 3.
> 
> I am testing with Ionic CLI `6.16.1` with a blank Ionic Angular app, and the hardware back button is working as expected.

Let me double-check.

**Comment by danielehrhardt** [comment]
yes it does work 🙈😇👌
