### ISSUE TITLE
bug: IonTabButton getting darker each time you click on them

### ISSUE THREAD

**Issue by Loschcode** [ionic-team/ionic-framework#23349]
# Bug Report

**Ionic version:**
6.15.0
Used with React / TypeScript

**Current behavior:**
By clicking on a simple app IonTabButton the contrast gets bigger until you can't see anything. It also happens when I click on modals. Basically everywhere in the app.

**Expected behavior:**
When you click the color shouldn't change at all, it's like adding a "layer" for each click right now.

**Steps to reproduce:**
I've got the code of `App.tsx` to provide and a video. I suppose that's enough to understand the problem. If not let me know and I can send an invite to the repo with ionic (it's a very simple app)

**Related code:**

```
const App: React.FC = () => {

  const Routes = (
    <IonRouterOutlet>
      <CustomerRoute exact path="/events" unauthorizedTo="/signin">
        <EventsPage />
      </CustomerRoute>
      <CustomerRoute exact path="/analytics" unauthorizedTo="/signin">
        <AnalyticsPage />
      </CustomerRoute>
      <CustomerRoute path="/settings" unauthorizedTo="/signin">
        <SettingsPage />
      </CustomerRoute>
      <Route exact path="/">
        <Redirect to="/signin" />
      </Route>
      <GuestRoute exact path="/signin" unauthorizedTo="/events">
        <SigninPage />
      </GuestRoute>
      <GuestRoute exact path="/signup" unauthorizedTo="/events">
        <SignupPage />
      </GuestRoute>
    </IonRouterOutlet>
  )

  const Footer = (!isAuthenticated() ? null :
    <IonReactRouter>
      <IonTabs>
        {Routes}
        <IonTabBar slot="bottom">
          <IonTabButton tab="events" href="/events">
            <IonIcon icon={list} />
            <IonLabel>Events</IonLabel>
          </IonTabButton>
          <IonTabButton tab="analytics" href="/analytics">
            <IonIcon icon={analytics} />
            <IonLabel>Analytics</IonLabel>
          </IonTabButton>
          <IonTabButton tab="settings" href="/settings">
            <IonIcon icon={settings} />
            <IonLabel>Settings</IonLabel>
          </IonTabButton>
        </IonTabBar>
      </IonTabs>
    </IonReactRouter>
  )

  return (
    <IonApp>
      <IonReactRouter>
        {Routes}
      </IonReactRouter>
      {Footer}
    </IonApp>
  )
}

export default App
```

**Other information:**
I'm afraid it's linked to React somehow, but I'm not sure how.

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.15.0 (/Users/loschcode/.nvm/versions/node/v15.3.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.7

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v15.3.0 (/Users/loschcode/.nvm/versions/node/v15.3.0/bin/node)
   npm    : 7.5.4
   OS     : macOS Big Sur
```

https://user-images.githubusercontent.com/6666570/119249522-cb79a900-bb5e-11eb-9cad-0c3ef98cb2e6.mov

**Comment by bddexter** [comment]
For what it's worth: I couldn't reproduce this in `ionic-vue`.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo? Layering multiple ripple effects on top of each other is the intended behavior and is what native Android does, but certain colors may not look as good. I am interested in seeing how this example is getting themes applied.

**Comment by amitkharka** [comment]
I'm also facing the same issue. 

try this workaround :

* {
-webkit-tap-highlight-color: transparent;
}
