### ISSUE TITLE
bug: Prototype pollution vulnerability in bundled swiper library

### ISSUE THREAD

**Issue by jkronborg** [ionic-team/ionic-framework#23342]
# Bug Report

**Ionic version:**
[x] **4.x**
[x] **5.x**

**Current behavior:**
`@ionic/core` bundles `swiper` version 5.4.1 ([source](https://github.com/ionic-team/ionic-framework/blob/d473a5385108ef5f39d7c9a2b2924e89fec631de/core/src/components/slides/swiper/swiper.bundle.js#L833)), that has a critical prototype pollution vulnerability ([GitHub advisory](https://github.com/advisories/GHSA-p3hc-fv2j-rp68)).

**Expected behavior:**
`swiper` is updated to a version without the known vulnerability (>= 6.5.1).

**Comment by liamdebeasi** [comment]
Thanks! We were able to backport the prototype pollution fix to our installation of Swiper and it will ship in our next release.
