### ISSUE TITLE
feat: support for decimal/fractional/floating-point numbers on ion-range

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/ionic-framework#23362]
# Feature Request

**Ionic version:**
[x] **5.x**

**Describe the Feature Request**

Can you add support for decimal/fractional/floating-point numbers on `ion-range`? It looks like [`ion-range`](https://ionicframework.com/docs/api/range) currently only supports integers and I'm currently working on an Ionic project that requires a slider with decimal numbers. It also looks like other developers were/are trying to do the same:
- https://stackoverflow.com/questions/45152146/decimal-ion-range
- https://forum.ionicframework.com/t/can-i-use-step-0-01-with-an-ion-range-component/57970
- https://github.com/ionic-team/ionic-framework/issues/16962

**Describe Preferred Solution**

I would like, for example, to have an `ion-range` with `min="0"`, `max="3"` and `step="0.1"`. So it would step from 0, 0.1, 0.2, 0.3, etc...

**Describe Alternatives**
The following 3 alternatives support decimal steps.
Angular Material Slider: https://material.angular.io/components/slider/overview#selecting-a-value
ngx-slider: https://angular-slider.github.io/ngx-slider/demos#floating-point-slider
noUiSlider: https://refreshless.com/nouislider/

**Comment by amandaejohnston** [comment]
Thank you for the request! It looks like this was added at some point, but the issue was never closed out. Here's an example with the latest version of Ionic: https://stackblitz.com/edit/angular-pchpvp?file=src%2Fapp%2Fexample.component.html
