### ISSUE TITLE
bug: React IOS Scroll Problem 

### ISSUE THREAD

**Issue by yetkinaykan** [ionic-team/ionic-framework#23366]
Hello, iOS 13, 12 and earlier versions have scroll problems.

I attach screenshots and video for details:

The error I see in browser tests is scrolling on iOS devices even if the page is blank. If the page is blank on Android devices, scroll does not appear.

iOS
![ios](https://user-images.githubusercontent.com/56234617/119572181-09730900-bdbb-11eb-9a18-dd3577e69e83.png)

Android
![Android](https://user-images.githubusercontent.com/56234617/119572226-168ff800-bdbb-11eb-902d-41c5ad172d4e.png)

iOS Scroll Problem

https://user-images.githubusercontent.com/56234617/119573863-81423300-bdbd-11eb-8634-2312911eb3ba.mp4

There are errors in all newly created projects, you can only create a listing and test it.

**Comment by yetkinaykan** [comment]
I tried the tests again with the Ionic React Conference Application. The same problem exists in iOS 12 and 13 versions.

https://ionic-react-conference-app.firebaseapp.com/

https://user-images.githubusercontent.com/56234617/119738202-01819a80-be89-11eb-9d26-b4a2ba202b56.mp4

**Comment by BerkeAras** [comment]
@yetkinaykan Are you using something like cordova or capacitor, or do you use it as a PWA?

**Comment by yetkinaykan** [comment]
PWA, iOS Safari browser

**Comment by BerkeAras** [comment]
Could be a possible WebKit-Issue. @yetkinaykan

**Comment by BerkeAras** [comment]
@liamdebeasi You are the WebKit-Pro here 😁 do you know something?

**Comment by liamdebeasi** [comment]
Thanks! This looks like the same issue as https://github.com/ionic-team/ionic-framework/issues/23001 so I am going to close this in favor of that issue.

Basically when running as a PWA scrolling is latching to the underlying document, not the `ion-content`: https://bugs.webkit.org/show_bug.cgi?id=222654

**Comment by yetkinaykan** [comment]
Yes the problem is caused by Webkit. You can check the screenshots I sent. The problem arises when a different area is in focus. 

Thanks
