### ISSUE TITLE
bug: Collapsible Large Titles in RTL animation

### ISSUE THREAD

**Issue by hussainarthuna** [ionic-team/ionic-framework#23371]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**

When pulling down the page in iOS with Collapsible Large Titles, the title's animation on LTR works fine as expected with increased font size and moving a little bit on the right side. But with the RTL it the font size increases but it still moves towards the right.

**Expected behavior:**

When pulling down the page in iOS with Collapsible Large Titles, the title's animation on LTR should move on right during the animation and with RTL it should move on left after animation.

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

LTR version

https://user-images.githubusercontent.com/46491137/119693037-96b66c00-be54-11eb-8378-7bc37eb8d1b9.MP4

RTL version

https://user-images.githubusercontent.com/46491137/119693133-ac2b9600-be54-11eb-9cd6-4de003245216.MP4

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.7
   @angular-devkit/build-angular : 12.0.0
   @angular-devkit/schematics    : 12.0.1
   @angular/cli                  : 12.0.0
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 2.4.7
   @capacitor/android : 2.4.7
   @capacitor/core    : 2.4.7
   @capacitor/ios     : 2.4.7

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.3.0)   : 0.2.2

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23372, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by hussainarthuna** [comment]
> Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23372, and a fix will be available in an upcoming release of Ionic Framework.

Great, that was quick 💯
