### ISSUE TITLE
feat: too much !important in the ionic component style

### ISSUE THREAD

**Issue by bichikim** [ionic-team/ionic-framework#23382]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

!important is anti-pattern for css styling no doubt

**Describe Preferred Solution**
'
remove !important
![2021-05-31 at 3 13 PM](https://user-images.githubusercontent.com/13829322/120148372-106aa300-c223-11eb-914b-be4f5e0844b7.png)

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is there a particular problem you are running into? Sometimes the `!important` is necessary for components due to specificity of CSS selectors especially when it comes to applying themes.
