### ISSUE TITLE
bug: ion-skeleton-text animation not working when dark color scheme is enabled

### ISSUE THREAD

**Issue by SvenTiigi** [ionic-team/ionic-framework#23389]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
`<ion-skeleton-text>` not working when dark color scheme is enabled.
> Tested with Safari and Google Chrome.

https://user-images.githubusercontent.com/11733014/120227675-e678a700-c249-11eb-9c46-6fb9fd5bca12.mov

**Expected behavior:**
`<ion-skeleton-text>` animation should be visible when dark color scheme is enabled

**Related code:**

```html
<h1>
  <ion-skeleton-text animated style="width: 80%; height: 50px"></ion-skeleton-text>
</h1>
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.8
   @angular-devkit/build-angular : 12.0.2
   @angular-devkit/schematics    : 12.0.2
   @angular/cli                  : 12.0.2
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.0.0
   @capacitor/android : 3.0.0
   @capacitor/core    : 3.0.0
   @capacitor/ios     : 3.0.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v16.2.0 (/usr/local/Cellar/node/16.2.0/bin/node)
   npm    : 7.15.0
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo? I tested this using our example app on https://ionicframework.com/docs and I cannot reproduce this behavior.

**Comment by SvenTiigi** [comment]
Hi @liamdebeasi 

You are correct! 
When I setup a new ionic project the `<ion-skeleton-text>` is correctly animating when dark color scheme is enabled.

I have made a short diff an identified that in my `angular.json` under `projects.app.architect.build` the following configurations/properties were missing:

```json
"aot": false,
"vendorChunk": true,
"extractLicenses": false,
"buildOptimizer": false,
"sourceMap": true,
"optimization": false,
"namedChunks": true
```

The key property seems to be `"optimization": false` when this flag is not set (which default value is `true`) the `<ion-skeleton-text>` will not animate when dark color scheme is enabled.

**Comment by liamdebeasi** [comment]
Thanks for the additional info. Did you create your Angular project via the Angular CLI or did you use one of our starters? Trying to figure out what would cause the `angular.json` diff.

**Comment by SvenTiigi** [comment]
I used `ionic start` and choosed the template `blank`.
I have created the project last week ago sadly I can not tell which CLI version I was exactly using at this time 😅

**Comment by SvenTiigi** [comment]
Seems like the following commit added those configuration properties to the `angular.json` which were not added at the moment of time when I generated the ionic project:

https://github.com/ionic-team/starters/commit/5db1644893680a5a5e36ec1909853c3eb711955b#diff-3f90ecae5dfb0e908567cc2f2654b241e8b0414f58ff6a1569fccfa68533ff7f

**Comment by liamdebeasi** [comment]
Yep looks like your project was made before that commit was merged/released. If you copy those changes over to your local `angular.json` is the issue resolved?

**Comment by SvenTiigi** [comment]
Yes the issue is fixed thank you 👌

**Comment by SvenTiigi** [comment]
@liamdebeasi sorry for too quickly closing this issue.

The issue is resolved for `dev` mode but not for `production`.

When using `ionic serve` the `<ion-skeleton-text>` will animate properly in both light and dark color scheme.

But when running `ionic serve --prod` or building in `prod` mode in general for example when running `ionic capacitor sync --prod` the `<ion-skeleton-text>` is not properly animating when dark color scheme is enabled.

When disabling the `optimization` configuration for production `projects.app.architect.build.configurations.production` in the `angular.json` the `<ion-skeleton-text>` is animating correctly.

But disabling the `optimization` configuration for production feels quite wrong 😅

![Bildschirmfoto 2021-06-01 um 19 29 28](https://user-images.githubusercontent.com/11733014/120366209-b09df600-c30f-11eb-92ed-210a571eb6e2.png)

**Comment by liamdebeasi** [comment]
No worries. Can you reproduce this in an Ionic starter app? I am testing your code snippet above in an Angular 12 Ionic app using `ionic serve --prod` and the skeleton text is animating correctly for me in dark mode.

**Comment by SvenTiigi** [comment]
Issue is now fixed 😅
There was one more configuration in my `angular.json` which caused this strange bug.

My `angular.json` had an `allowedCommonJsDependencies` configuration and after removing this configuration the `<ion-skeleton-text>` was animating correctly again in production mode.

But sadly I can't tell why this configuration field is causing this bug for Angular Production Mode when displaying an `<ion-skeleton-text>` with dark color scheme enabled.

**Comment by liamdebeasi** [comment]
Glad it is fixed! There is probably some configuration that may have caused some important CSS to not be included in your app bundle.

**Comment by SvenTiigi** [comment]
Yeah that might be the reason. 
Thank you for your help 🙌
