### ISSUE TITLE
bug: swipe to close modal should not be swipeable on the footer

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23398]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

If i create a Modal, that uses swipeToClose iOS Mode and has a Footer, i'm able to swipe down on that Footer to close the Modal.

**Expected behavior:**

It should only be possible when swiping the Header?

**Steps to reproduce:**

Open Stachblitz, use iOS version of the Browser

**Related code:**

Stackblitz: https://ionic-angular-v5-jraezm.stackblitz.io

**Comment by liamdebeasi** [comment]
Thanks for the issue. I agree that for now the modal should just swipe from the header. The necessary change should be in here: https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/modal/gestures/swipe-to-close.ts#L27-L34

Changing `target.closest('ion-content');` to `target.closest('ion-content, ion-footer');` and updating the variable name + comments should be the only changes necessary. I think this change is low in terms of difficult so I am going to add the `help wanted` label in case anyone in the community is interested in putting up a PR.

**Comment by EinfachHans** [comment]
i will create a PR tomorrow 😊

**Comment by liamdebeasi** [comment]
Thank you!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23401, and a fix will be available in an upcoming release of Ionic Framework.
