### ISSUE TITLE
bug: Dark theme detecting on Android app - Ionic 5, Angular, Capacitor is not working

### ISSUE THREAD

**Issue by victoriaunizhona** [ionic-team/ionic-framework#23390]
# Bug Report

**Ionic version:**
[x] **5.29.0**

**Current behavior:**
If I open it like a website in a browser - it is detecting dark theme enabled on device both on pc and mobile.

But if I build the app with capacitor and then open it on Android device as an app - it cannot detect dark theme enabled. It always shows that app is in light mode. prefers-color-scheme is always showing light.

I tested on device with Android 10+.

I used this guide: https://ionicframework.com/docs/theming/dark-mode#using-media-queries

**Expected behavior:**
Dark theme is detected correctly on android app and app switches to dark one automatically.

**Steps to reproduce:**
1. Create ionic app with dark theming available
2. Build the app with Capacitor
3. Open app on Android with dark theme enabled(it is in light mode instead of dark one)

**Ionic info:**

   Ionic CLI                     : 5.4.16 (C:\Users\User\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.6.4
   @angular-devkit/build-angular : 0.1102.8
   @angular-devkit/schematics    : 11.2.8
   @angular/cli                  : 11.2.8
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is a known behavior on Android and not a bug in Ionic Framework. Please see https://github.com/ionic-team/capacitor/discussions/1978 for a workaround.
