### ISSUE TITLE
Ionic 5 glitches on Android 8.1

### ISSUE THREAD

**Issue by ivanov84** [ionic-team/ionic-framework#23392]
**Ionic version:**
[ ] **4.x**
[x] **5.x**

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
App runs with render glitches or artifacts or bugs, I don't know how it to name. Please see an attached video.

**Expected behavior:**
App runs without artifacts and response on clicks.

**Steps to reproduce:**
Build an ionic 5 app on an android 8.1 and run it.

**Other information:**
![video_2021-05-29_16-34-31 (2)](https://user-images.githubusercontent.com/9296077/120319711-fb0c7c00-c2e9-11eb-8077-be5dccab9f93.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue. There is not a lot to go off here, so I am unsure of how I can help. I recommend checking that you are using the latest Android WebView as there have been some issues with webview rendering in older versions. 

Unfortunately, we do not provide application support so I recommend creating a post on the forums (https://forum.ionicframework.com/) to see if you can do some more debugging. If you are able to pinpoint something in the Framework that may be causing this issue please feel free to reply with more information surrounding that and I can re-open this.
