### ISSUE TITLE
bug: vue testing logs error when run with certain test runners

### ISSUE THREAD

**Issue by mattsteve** [ionic-team/ionic-framework#23397]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
The IonicVue plugin has an aversion to being used multiple times, shows an error "ionic config was already initialized".

```
    console.error node_modules/@ionic/core/dist/cjs/index.cjs.js:24
      ionic config was already initialized
    console.error node_modules/@ionic/core/dist/cjs/index.cjs.js:24
      ionic config was already initialized
    console.error node_modules/@ionic/core/dist/cjs/index.cjs.js:24
      ionic config was already initialized
    console.error node_modules/@ionic/core/dist/cjs/index.cjs.js:24
      ionic config was already initialized
    console.error node_modules/@ionic/core/dist/cjs/index.cjs.js:24
      ionic config was already initialized
    console.error node_modules/@ionic/core/dist/cjs/index.cjs.js:24
      ionic config was already initialized
```

This is a problem with @vue/test-utils, as it is designed to install plugins every time a wrapper is mounted for testing. In a unit test environment, this is usually once per test.

https://next.vue-test-utils.vuejs.org/api/#global

**Expected behavior:**
Change whatever is needed so IonicVue can be installed on multiple Vue applications on the page without throwing errors.

**Steps to reproduce:**
1. Create an @ionic/vue application
2. Follow the installation guide for @vue/test-utils (next) https://next.vue-test-utils.vuejs.org/installation/
3. Create a basic test that installs the IonicVue plugin via the global component mount options https://next.vue-test-utils.vuejs.org/api/#global
4. Run the test

**Related code:**

Vue test utils plugins can be installed for all tests:
```
import { IonicVue } from '@ionic/vue';
import { config } from '@vue/test-utils';
config.global.plugins = [IonicVue];
```

Or at mount time for a component:
```
import { IonicVue } from '@ionic/vue';
import { mount } from '@vue/test-utils';
const ionApp = document.createElement('ion-app');
document.body.appendChild(ionApp);
const wrapper = mount(MyComponent, {
    attachTo: ionApp,
    global: {
        plugins: [IonicVue]
    }
});
```

In either case, the plugin always runs at mount time for the component.

**Comment by mattsteve** [comment]
Hmmm I don't like those examples because the wrapper always starts at the app, instead of the component I'm actually trying to test. Also, they all use a router outlet which is a lot of unnecessary setup if I'm not testing router functionality.

**Comment by liamdebeasi** [comment]
Can you give me a complete example of what you are trying to do? If you are trying to test components neither `IonApp` nor `IonRouterOutlet` are required (unless you are trying to test routing of course)

**Comment by mattsteve** [comment]
There are cases where I'm trying to inject a page component into an app, and tests rely on ion-app being there for styles to work properly. So essentially, I want to inject a component into an existing app. Is there a way to tell when it's hydrated already? This example shows the error.

```
import { mount, VueWrapper } from '@vue/test-utils';
import { defineComponent } from 'vue';
import { IonicVue, IonInput } from '@ionic/vue';

const ExampleComponent = defineComponent({
    components: {
        IonInput
    },
    template: `<div><ion-input id="foo" /></div>`
});

const createWrapper = async (): Promise<VueWrapper<InstanceType<typeof ExampleComponent>>> => {
    const ionApp = document.querySelector('ion-app');
    const wrapper = mount(ExampleComponent, {
        attachTo: ionApp || undefined,
        global: {
            plugins: [IonicVue]
        }
    });
    await wrapper.vm.$nextTick();
    return wrapper;
};

describe('ExampleComponent.vue', () => {

    beforeEach(() => {
        const ionApp = document.createElement('ion-app');
        document.body.appendChild(ionApp);
    });

    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('test 1', async () => {
        await createWrapper();
        await new Promise((resolve) => {
            setTimeout(() => {
                resolve();
            }, 200);
        });
    });

    it('test 2', async () => {
        await createWrapper();
        await new Promise((resolve) => {
            setTimeout(() => {
                resolve();
            }, 200);
        });
    });

});
```

**Comment by liamdebeasi** [comment]
Thanks! At the moment Framework does not expose a "hydrated" event, but the good news is that in Framework v6 we will be moving away from component hydration so styles should work properly. (This use case is one of the reasons why we are moving away from it)

In your example, where is the error? Both of the tests are passing when I run them.

**Comment by mattsteve** [comment]
Yeah the tests aren't testing anything, that's why they pass. I was just showing the error that happens in the console

```
console.error node_modules/@ionic/core/dist/cjs/index.cjs.js:24
   ionic config was already initialized
```

![image](https://user-images.githubusercontent.com/34715493/120526363-1e493100-c3a7-11eb-8f69-33a4a577aef8.png)

If you don't see that console error, pass in `--verbose=false`. Jest likes to eat console logs without that.

```
npm run test:unit -t example.spec -- --verbose=false
```

What do you suggest in terms of mounting example component directly? `mount(ExampleComponent)`. This is necessary to pass required props on instantiation.

**Comment by mattsteve** [comment]
No, I mean mounting directly but putting it inside of a a hydrated ion-app by using attachTo.

**Comment by liamdebeasi** [comment]
Thanks for the clarification. If you could still provide the repo that would be really helpful.

**Comment by mattsteve** [comment]
https://github.com/mattsteve/ionic-vue-test-config

**Comment by liamdebeasi** [comment]
Thanks for the repo. The issue seems to be related to the use of Electron for running spec tests which is causing this statement to be `true`: https://github.com/ionic-team/ionic-framework/blob/master/core/src/utils/config.ts#L203

That being said, the console error can be quite jarring even though the tests are working correctly, so I am going to remove it.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23421, and a fix will be available in an upcoming release of Ionic Framework.
