### ISSUE TITLE
bug: Text in ion-label in ion-segment doesn't show in Firefox, but it does in Chrome.

### ISSUE THREAD

**Issue by fstorres49** [ionic-team/ionic-framework#23406]
# Bug Report

**Ionic version:**
[ ] **4.x**
[x] **5.x**

**Current behavior:**
Text in ion-label in ion-segment doesn't show in Firefox, but it does in Chrome.

**Expected behavior:**
Text in ion-label in ion-segment should show in both Firefox and Chrome.

**Steps to reproduce:**

- Create a new app with scrollable ion segments.
- Run ionic serve and run local on Firefox and Chrome.

**Related code:**
<img width="698" alt="Firefox" src="https://user-images.githubusercontent.com/60103532/120558916-ca017980-c3c5-11eb-95b3-95d72eb12a55.png">
<img width="669" alt="Chrome" src="https://user-images.githubusercontent.com/60103532/120558921-cbcb3d00-c3c5-11eb-8e34-ebd166f7a771.png">

```
<template>
  <ion-page>
      <ion-grid fixed>
        <ion-row>
          <ion-col size="12">
            <ion-segment scrollable>
              <ion-segment-button 
              v-for="category in categories"
              :key="category.id"
              :value="category.value">
                <ion-label> {{ category.value }} </ion-label>
                </ion-segment-button>
            </ion-segment>
          </ion-col>
        </ion-row>
      </ion-grid>
  </ion-page>
</template>

<script>
import { mapState, mapActions } from "vuex";
import {
  IonCol,
  IonGrid,
  IonLabel,  
  IonPage,
  IonRow,
  IonSegment,
  IonSegmentButton,
} from "@ionic/vue";
export default {
  name: "ProductList",
  components: {
    IonCol,
    IonGrid,
    IonLabel,  
    IonPage,
    IonRow,
    IonSegment,
    IonSegmentButton,
  },
  computed: {
    ...mapState("products", ["products", "categories"]),
  },
};
</script>

Categories in products.js:

export const state = {
categories: [
    {
      id: "001",
      value: "Entrada",
    },
    {
      id: "002",
      value:"Ensaladas",
    },
    {
      id: "003",
      value: "Sopas",
    },
  ],
};
```

**Other information:**
Firefox version: 89.0 (64-bit)
Chrome version:  90.0.4430.212

Console warning on firefox: 
Unknown pseudo-class or pseudo-element ‘host-context’.  Ruleset ignored due to bad selector.

**Ionic info:**
```
Ionic:

   Ionic CLI       : 6.16.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.1

Capacitor:

   Capacitor CLI      : 2.4.6
   @capacitor/android : not installed
   @capacitor/core    : 2.4.6
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run (update available: 1.3.0)   : 1.2.2

System:

   NodeJS : v15.0.1 (/usr/local/bin/node)
   npm    : 7.0.10
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in a blank Ionic starter app and provide a link to the repo? I am testing your code snippet on Firefox and am unable to reproduce the issue described here.

**Comment by fstorres49** [comment]
I solved it. It wasn't a bug. I'm closing this issue.
