### ISSUE TITLE
bug: vue-service-cli not taking browserslist into account

### ISSUE THREAD

**Issue by kas84** [ionic-team/ionic-framework#23409]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

I set "IE 11" a browserslist field inside the package.json or in .browserslistrc. dist folder generates bundles with arrow functions =>
**Expected behavior:**

It should generate bundles without arrow functions =>

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this issue as Ionic Framework does not manage the Vue build process. I recommend opening an issue on the Vue CLI repo: https://github.com/vuejs/vue-cli.

You might also want to try v5 of the Vue CLI. It looks like they added a feature to transpile dependencies inside of node_modules as well: https://github.com/vuejs/vue-cli/releases/tag/v5.0.0-alpha.8
