### ISSUE TITLE
bug: <ion-back-button> doesn't go back to last state of tabs page (Ionic Angular)

### ISSUE THREAD

**Issue by armspativong** [ionic-team/ionic-framework#23419]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
```<ion-back-button>``` triggers redirection as set in routing and brings back the first tab of tabs page.
(This happened before as issued in [#17421](https://github.com/ionic-team/ionic-framework/issues/17421) and was fixed by ```npm i @ionic/angular@dev```)

**Expected behavior:**
```<ion-back-button>``` should brought back the last state of selected tab in tab page.

**Steps to reproduce:**
Updated Ionic Angular with ```npm i @ionic/angular@dev``` (to latest **5.7.0-dev.202105252124.46831de**)
(From where I checked, version **5.7.0-dev.202105172137.6363d14** is still working. So now I downgraded)

**Related code:**

```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```

**Other information:**

**Ionic info:**

```
Ionic:
   Ionic CLI : 6.16.1

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v14.17.0
   npm    : 6.14.13
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Please try this again on the latest stable version of Ionic Framework, not the dev version. Dev versions contain in-progress work and are not considered production-ready:

```
npm install @ionic/angular@latest
```

If the issue persists, please reproduce the issue in an Ionic starter app and provide a link to the GitHub repo.
