### ISSUE TITLE
bug: Infinite scroll threshold still not working

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/ionic-framework#23417]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
As pointed out in a previous thread, the infinite scroll threshold doesn't work properly and causes a buggy jault effect when scrolling quickly. The initial scroll works and it is triggered at the specified threshold, however for any of the scroll threshold trigger events after the first one, it is only triggered upon reaching the bottom of the view - https://github.com/ionic-team/ionic-framework/issues/20947#issuecomment-612573636

**Expected behavior:**
The threshold should continue to keep the scroll tigger emitting at the same point when more items are added to the list.

**Steps to reproduce:**
Create any list  of items, and on scroll event trigger, add another set of items to the array - the next triggered event only happens when the bottom of the list is reached.

**Other information:**

**Ionic info:**
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.7
   @angular-devkit/build-angular : 0.901.15
   @angular-devkit/schematics    : 9.1.15
   @angular/cli                  : 9.1.15
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v14.16.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Big Sur

**Comment by indraraj26** [comment]
This is an old bug since ionic 3

After 2-3 infinite scroll you will notice this bug.

1. sometime you will have to scroll-up-scroll-down to trigger infinite scroll.
2.  sometime threshold does not work you have go to bottom to trigger infinite scroll.

**Comment by oliverandersencox** [comment]
@indraraj26 how is there not been any fix for this if its been like this since then!?

**Comment by indraraj26** [comment]
This is how open source work if you are interested feel free to open PR to fix the above issue or share the reproduction they might fix in upcoming version or get an enterprise support.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
