### ISSUE TITLE
bug: Nested routes in tabs not working

### ISSUE THREAD

**Issue by yetkinaykan** [ionic-team/ionic-framework#23418]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

https://ionicframework.com/docs/react/navigation#nested-routes

The example in the link works fine. But it doesn't work when used in tabs. 
Note: Tab Button does not work when clicked. It works if you go directly to the link. (/settings)

**Expected behavior:**

Example: Creating different routes within the Settings tab. (Settings > Notifications) 

**Steps to reproduce:**

**Related code:**

```
<IonReactRouter>
  <IonTabs>
    <IonRouterOutlet>     
      <Route path="/settings" render={props => <SettingsPage {...props} />} />
    </IonRouterOutlet>

    <IonTabBar slot="bottom">
      <IonTabButton tab="tab1" href="/settings">
        <IonIcon icon={triangle} />
        <IonLabel>Settings</IonLabel>
      </IonTabButton>
    </IonTabBar>
  </IonTabs>
</IonReactRouter>

const SettingsPage: React.FC<RouteComponentProps> = ({match}) => {
  return (
    <IonRouterOutlet>
      <Route path={`${match.url}/notifications`} component={NotificationsPage} />
    </IonRouterOutlet>
  );
};
```

**Other information:**

**Ionic info:**

```
Ionic:
   Ionic CLI : 6.15.0

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v14.15.2
   npm    : 6.14.9
   OS     : Windows 10
```

**Comment by yetkinaykan** [comment]
@liamdebeasi https://github.com/yetkinaykan/ionic-23418

**Comment by liamdebeasi** [comment]
Thanks. You are missing an `IonPage` in your `DashboardPage.tsx` file. All views that can be navigated to (including pages that are just contain nested router outlets) need `IonPage`. The docs there should include `IonPage`, so I will make sure to update them.

**Comment by yetkinaykan** [comment]
@liamdebeasi Thanks for the feedback.

same example works in older version.

https://stackblitz.com/edit/ionic-react-routing-aecehd

**Comment by yetkinaykan** [comment]
https://github.com/ionic-team/ionic-framework/issues/23408

this problem is also solved. Nested routes are automatically removed from the dom.

**Comment by liamdebeasi** [comment]
Glad both issues are resolved!
