### ISSUE TITLE
bug: The state/prop "multipleInputs" changed during "componentDidLoad()"

### ISSUE THREAD

**Issue by Lxstr** [ionic-team/ionic-framework#23427]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
ion-item with two ion-inputs gives the following error due to whre the state multipleInputs is changed in ionic source code.

```
The state/prop "multipleInputs" changed during "componentDidLoad()", this triggers extra re-renders, try to setup on "componentWillLoad()" 
Element <ion-item class=​"item-multiple-inputs item-interactive item-input item md in-list ion-focusable hydrated item-label item-label-color ion-color-robo">​…​</ion-item>​ 
New value true 
Old value false
```

**Expected behavior:**
Mulitpleinputs is updated at componentWillLoad and no warning.

**Steps to reproduce:**
ion-item with two ion-inputs

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23429, and a fix will be available in an upcoming release of Ionic Framework.
