### ISSUE TITLE
bug: ion-img sets incorrect src property

### ISSUE THREAD

**Issue by FredrikZeiner** [ionic-team/ionic-framework#23428]
# Bug Report

**Ionic version:**
5.27.0

**Current behavior:**
src property is sometimes not set correctly. it seems like ion-img parses the string and leaves out the file. F.ex "assets/img/img1.png" becomes "assets/img/". This happens arbitrarily and is incredibly hard to reproduce. It seems to happen in modals more than anything else.

**Expected behavior:**
Would expect ion-img to not alter the src prop

**Steps to reproduce:**
Put an ion-img inside a modal. Use relative paths. Open and close the modal several times, reload the page etc. Eventually the bug will appear.

**Related code:**
```
<ion-img [src]="img.src" "></ion-img>
```

The below image illustrates the issue. The path to the image is inside a span right next to the ion-img to show that there are no issues with the path itself.
![Screenshot 2021-06-08 at 08 42 29](https://user-images.githubusercontent.com/42534694/121138364-e5daa480-c837-11eb-8171-06004fc6e9c9.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
