### ISSUE TITLE
feat: (ion-virtual-scroll) Scroll to / scroll top.

### ISSUE THREAD

**Issue by y0nd0** [ionic-team/ionic-framework#23424]
# Feature Request

**Ionic version:**
**5.x**

**Describe the Feature Request**
I wish I could scroll the `ion-virtual-scroll` programmatically to scroll to top before I generate complete new item list. 

[Docs](https://ionicframework.com/docs/api/virtual-scroll) (In [Angular Material](https://material.angular.io/cdk/scrolling/api) there is a method `scrollTo` (click link). Maybe this helps.)

**Describe Preferred Solution**
Add the possibility to set the scroll position like `scrollTop`. In my case I want to scroll to top before I change the item list. Otherwise the items are weirdly rendered (glitch / overlapped).

I alrady tried to set the scroll position like for a `HTMLElement` but this does not work.
Btw. I use Angular.

**Comment by liamdebeasi** [comment]
Thanks for the issue. With upcoming major versions of Ionic Framework, we are going to be transitioning to using Angular's CDK Scroller. As a result, we have a freeze on new features and bug fixes on ion-virtual-scroll. See https://material.angular.io/cdk/scrolling/overview for how to get started with CDK Scroller. We are working on proper transition docs as well!

**Comment by y0nd0** [comment]
Ok thanks for that info. 

Just fyi:
I've tried it now. It does not work in my case. Since the Ionic Virtual Scroll works really great. It only causes problems when switching the items while scroll position is not on top. 
But the CDK Angular VIrtual Scroll completely bugs. It jumps over items etc. 

My items height are slighly different. But I don't think that this is the probleme with CDK. I wanted to try the experimental `autoSize` for that CDK component. [See here](https://github.com/angular/components/issues/10113). But I can't bring it to life since Angular import issues. *sigh* So finally I have to find another solution. :(

Is there a Ionic dev version published to test the new implementation with this cdk scrolling? It's possible that the Ionic team fixed that issue with jumping items (scroll pos and flickering).
