### ISSUE TITLE
bug: Ionic Platform pause and resume with Capacitor 3, Angular 12

### ISSUE THREAD

**Issue by oneclickwebstudio** [ionic-team/ionic-framework#23425]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

After upgrading to Capacitor 3 and Angular 12, Platform `pause` and `resume` stopped working;

**Expected behavior:**

Should trigger when app minimized and reopened.

**Steps to reproduce:**

Added subscribtion in app.component.ts.

**Related code:**

I have tried these versions, nothing helps

```
    this.platform.resume.subscribe(() => this.zone.run(() => {
      alert('RESUME');
    }));
```
```
    this.platform.resume.subscribe(() => {
      alert('RESUME');
    });
```
```
    this.platform.resume.subscribe(async () => {
      alert('RESUME');
    });
```

My `AppDelegate.swift`

```
func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (...../.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.8
   @angular-devkit/build-angular : 12.0.3
   @angular-devkit/schematics    : 12.0.3
   @angular/cli                  : 12.0.3
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI   : 3.0.0
   @capacitor/core : 3.0.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.1

System:

   NodeJS : v15.14.0 (...../.nvm/versions/node/v15.14.0/bin/node)
   npm    : 7.15.1
   OS     : macOS Big Sur
```

**Comment by oneclickwebstudio** [comment]
StackBlitz: https://ionic-mnbypx.stackblitz.io

**Comment by liamdebeasi** [comment]
Can you reproduce this in an Ionic starter app and provide a link to the repo? The StackBlitz you provided looks to be using Ionic v3 and does not have Capacitor configured.

**Comment by liamdebeasi** [comment]
Also double check that you have all the required plugins installed, in particular the `App` plugin: https://capacitorjs.com/docs/updating/3-0#migrating-your-app-to-use-the-new-official-plugin-packages

**Comment by EinfachHans** [comment]
i experienced the same today and switched to the Capacitor App's listener `appStateChange` which works for me.

**Comment by oneclickwebstudio** [comment]
> i experienced the same today and switched to the Capacitor App's listener `appStateChange` which works for me.

I did the same with `appStateChange`. 

I also use `App.addListener` to control hardware back button on `android`. and when i have to remove back button listener, its recommended to use `App.removeAllListeners()`. Unfortunately, this command also removes `appStateChange` listener.

**Comment by EinfachHans** [comment]
@oneclickwebstudio can you create a Repo like Liam asked for?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
