### ISSUE TITLE
bug: <ion-menu> error changing disabled state

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic-framework#23433]
# Bug Report

**Ionic version:**
[x] **5.6.9**

**Current behavior:**
When attempting to disable the `<ion-menu>` for certain pages it results in the debugger being displayed with an error.

The use case is an application that uses a menu sidebar but does not display the sidebar for certain pages (e.g. Sign In).

The top level app renders as follows:
```
<ion-app>
    <AppRoutes />
    <ion-split-pane contentId="app-nav">
        <ion-menu disabled={this.isMenuDisabled} contentId="app-nav">
            <ion-content>
                <AppSidebar />
            </ion-content>
        </ion-menu>
        <ion-nav animated id="app-nav" />
    </ion-split-pane>
</ion-app>
```

If a navigation change results in a change to whether the menu should be disabled then the top level component is rendered again so that the menu disabled property gets updated.

When the `disabled` value changes the follow error occurs:
```
// console
ASSERT: can not be animating

// menu.tsx
  private updateState() {
    const isActive = this._isActive();
    if (this.gesture) {
      this.gesture.enable(isActive && this.swipeGesture);
    }

    // Close menu immediately
    if (!isActive && this._isOpen) {
      // close if this menu is open, and should not be enabled
      this.forceClosing();
    }

    if (!this.disabled) {
      menuController._setActiveMenu(this);
    }
    assert(!this.isAnimating, 'can not be animating');
  }

// helpers.ts
const assert = (actual, reason) => {
  if (!actual) {
    const message = 'ASSERT: ' + reason;
    console.error(message);
    debugger; // tslint:disable-line
    throw new Error(message);
  }
};
```

Looking at the code it looks like any change to the menu state result in an assert that the menu is not animating.  This results in not only a console error entry, but also brings up the debugger and aborts all higher level code (e.g. ionMenuChange event).  The component is then in an inconsistent state with an internal property value different from what is rendered.

**Expected behavior:**

- It should be possible to change `<ion-menu>` properties.
- Showing the debugger seems too strong vs. logging an error. Users would not know what to do.

**Ionic info:**

```
Ionic:

   Ionic CLI : 6.12.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.15.0
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This looks to be related to https://github.com/ionic-team/ionic-framework/issues/20092, so I will track progress in that thread.

Possibly related: https://github.com/ionic-team/ionic-framework/issues/19000
