### ISSUE TITLE
bug: iOS/Safari debugging no longer works

### ISSUE THREAD

**Issue by Exocomp** [ionic-team/ionic-framework#23445]
The instructions at the following:

https://ionicframework.com/docs/troubleshooting/debugging#ios-and-safari

The Safari Web Inspector, console, etc. no longer work for debugging purposes.

App created with iconic cli:
ionic --version
6.16.2

iOS: 14.6
Angular: 12.0.1
Ionic: 5.6.8
Capacitor: 3.0.0

**Comment by EinfachHans** [comment]
I think this is a Bug in current Safari Version, not Ionic Framework. Have you tried **Safari Technology Preview**?
