### ISSUE TITLE
bug:  Button flickering when hided

### ISSUE THREAD

**Issue by ZeroSkill830** [ionic-team/ionic-framework#23457]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When the keyboard is open the button flicker before disappear.

**Expected behavior:**
When the keyboard is open the button have to disappear without flickering.

**Steps to reproduce:**
Open the keyboard

**Related code:**

```
TS
Keyboard.onKeyboardShow().subscribe( (value)=>{
document.body.classList.add(‘hide-on-keyboard’);
}

Keyboard.onKeyboardHide().subscribe( (value)=>{
document.body.classList.remove(‘hide-on-keyboard’);
}

CSS
.hide-on-keyboard{
display: none;
}

HTML
<ion-footer class="hide-ok-keyboard">
   <ion-toolbar>
      <ion-button>Click me</ion-button>
   </ion-toolbar>
</ion-footer>
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by BerkeAras** [comment]
@ZeroSkill830 Thanks for your issue. Unfortunately I cannot reproduce this. On which device does this issue happen?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
