### ISSUE TITLE
bug: Opening Menu freezes app TypeError: undefined is not an object (evaluating 'this.menuInnerEl.offsetWidth')

### ISSUE THREAD

**Issue by pzontrop** [ionic-team/ionic-framework#23464]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**
When opening the menu more than once the app crashes on IOS.

**Expected behavior:**
That the app doesn't crash

**Steps to reproduce:**
Create a Lazy loaded page that contains 3 components (that are inside the module) which all contain an ion-menu (one side="start" and the others side="end". The first menu uses the MenuController to open one of the others by calling
```
  async openMenu(menuId: string) {
    await this.menu.enable(true, menuId);
    await this.menu.open(menuId);
  }
```
Sometimes the menu works. But triggering a redeploy in xcode and trying again will almost always make it fail. I have googled this issue and found similar bugs but they seemed to be related to the swipe gesture. Turning the swipe gesture off however does not fix the issue for me.

**Other information:**
I have located the error in xcode in 19.js on line 238 inside the function async loadAnimation():
```
// Menu swipe animation takes the menu's inner width as parameter,
// If `offsetWidth` changes, we need to create a new animation.
const width = this.menuInnerEl.offsetWidth;
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.3 (/Users/pascal/.nvm/versions/node/v16.1.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.8
   @angular-devkit/build-angular : 0.1102.10
   @angular-devkit/schematics    : 11.2.14
   @angular/cli                  : 11.2.14
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI      : 3.0.0
   @capacitor/android : 3.0.0
   @capacitor/core    : 3.0.0
   @capacitor/ios     : 3.0.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.4.0) : 1.3.0

System:

   NodeJS : v16.1.0 (/Users/pascal/.nvm/versions/node/v16.1.0/bin/node)
   npm    : 7.11.2
   OS     : macOS Big Sur

```

**Comment by pzontrop** [comment]
For now I am not able to reproduce it in a small project. I will continue to work on it so please do not close this issue.

**Comment by pzontrop** [comment]
Ok I have spent almost a full day in trying to reproduce it but I am not unable to do it outside of my main project. In my main project I have been able to find a workaround and for now I will just go with that.

For anyone finding this issue: my workaround is declaring the menus components in the app-module.ts and putting them in the app-component.html in stead of in the lazyloaded page/module.

**Comment by cathypark** [comment]
@pzontrop Hi, I have the same problem. when declaring ion-menu in the lazyloaded page.

My guess is that the cause is the same with https://github.com/ionic-team/ionic-framework/issues/20356#issuecomment-605303030

In ion-slides, it was solved by adding `didInit` variable and deleting async.
I think ion-menu is the same cause.

https://github.com/ionic-team/ionic-framework/commit/3123a318b6755dbf8fde8476f81c37e6ffa9b70e#diff-67e9ec0742b85cf8c11d755bb5138c2c2591935ab9c6efab782a720823507410
