### ISSUE TITLE
bug: Ionic serve is not running

### ISSUE THREAD

**Issue by ajay0CarBazar** [ionic-team/ionic-framework#23466]
C:\Users\ajay\OneDrive\Desktop\Ionic R&D\new-app>ionic serve
> ng.cmd run app:serve --host=localhost --port=8100
[ng] 'D\new-app\node_modules\.bin\' is not recognized as an internal or external command,
[ng] operable program or batch file.
[ng] internal/modules/cjs/loader.js:905
[ng]   throw err;
[ng]   ^
[ng] Error: Cannot find module 'C:\Users\ajay\OneDrive\Desktop\@angular\cli\bin\ng'
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[ng]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
[ng]     at internal/main/run_main_module.js:17:47 {
[ng]   code: 'MODULE_NOT_FOUND',
[ng]   requireStack: []
[ng] }

[ERROR] ng has unexpectedly closed (exit code 1).

        The Ionic CLI will exit. Please check any output above for error details.

C:\Users\ajay\OneDrive\Desktop\Ionic R&D\new-app>
![Screenshot 2021-06-19 230137](https://user-images.githubusercontent.com/71268814/122650775-5d6ed480-d152-11eb-9d0f-e3ed9541c7b1.png)

**Comment by BerkeAras** [comment]
@ajay0CarBazar Could you try installing the angular-cli global? `npm install -g @angular/cli`

**Comment by BerkeAras** [comment]
@ajay0CarBazar Something else: Could you rename the Folder `Ionic R&D` to for example `Ionic R-D`?
Maybe the and-symbol could cause the error

**Comment by ajay0CarBazar** [comment]
@BerkeAras  Thank you folder name was issue.

**Comment by BerkeAras** [comment]
Great that it works now 😄
