### ISSUE TITLE
bug: Ionic/vue 3.1 compat mode doesn’t respond to @click events 

### ISSUE THREAD

**Issue by inspire22** [ionic-team/ionic-framework#23470]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

@click events are not fired when vue.config.js includes 
` config.resolve.alias.set("vue", "@vue/compat");`

**Expected behavior:**

@click events should fire

**Steps to reproduce:**

**Related code:**
A vanilla ionic start, upgrade to vue 3.1, add compat mode, and click events don't fire
ionic start myApp blank --type=vue

A sample application via GitHub
https://github.com/inspire22/ionic-click-bug

I'd suspected that adding ion-* to isCustomElement might solve it, but it does not.  It does work to put a div/span around the ionic element and move the click element handler to that.

**Other information:**

I created a thread in the forums first but didn't hear anything so am adding a ticket. I'm sorry that my knowledge of vue/ionic isn't enough to debug this further.  https://forum.ionicframework.com/t/ionic-vue-3-1-compat-mode-doesnt-respond-to-click-events/211353

**Ionic info:**

```
Running on WSL 2 from windows 10 if it matters.

Ionic:

   Ionic CLI       : 6.12.2 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.6.9

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : not installed

System:

   NodeJS : v14.17.1 (/home/kevin/.nvm/versions/node/v14.17.1/bin/node)
   npm    : 7.17.0
   OS     : Linux 4.4
  ─────────────────────────────────────────────────

     Ionic CLI update available: 6.12.2 → 6.16.3
          Run npm i -g @ionic/cli to update
  ─────────────────────────────────────────────────

```

Thanks for a great project, I appreciate all the volunteers and staff that work on it.

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here looks to be that Vue is not passing in your click handler to the component when using compat mode. I need to do some more digging to figure out what the correct behavior in the Vue compat build is.

**Comment by liamdebeasi** [comment]
I was able to reproduce this issue outside of Ionic Framework, and I think this may be a bug in the compat build of Vue 3. I filed an issue with the Vue Team to verify, so I will see what they say: https://github.com/vuejs/vue-next/issues/3998

**Comment by inspire22** [comment]
Thanks!  Phew they shut that down fast lol, I'll chime in with my 2c in case it helps.

**Comment by liamdebeasi** [comment]
Thanks! Yeah I am a bit confused as to what the intended behavior is supposed to be here, as the Migration Build guide does not really specify. The other thing that is confusing is the original syntax I had seems to be correct according to the docs, but the team member said it was not.

If I don't hear back soon I will just post on the forums since that sounds like what they want me to do.

**Comment by liamdebeasi** [comment]
Recapping from https://github.com/vuejs/vue-next/issues/3998, sounds like your app needs to set the compat mode on each Ionic component to `MODE: 3` to have it run in Vue 3 mode. Can you try that in your app and let me know if it resolves the issue?

**Comment by inspire22** [comment]
It's working great, thanks so much for your help :)  I went ahead and updated my test app on github with the fix if anyone else runs into this.  https://github.com/inspire22/ionic-click-bug
