### ISSUE TITLE
website bug ionic.io

### ISSUE THREAD

**Issue by ncamaa** [ionic-team/ionic-framework#23471]
you have a typo in the mega menu
![image](https://user-images.githubusercontent.com/25122974/122730503-f3a21800-d282-11eb-926e-d586a05bf521.png)

**Comment by BerkeAras** [comment]
@liamdebeasi Is there a repository for the **ionic.io** website? I could not find anything...

**Comment by liamdebeasi** [comment]
The website repo is private. I will inform the correct team so that they can make this fix. Thanks for the report!

**Comment by BerkeAras** [comment]
@liamdebeasi Great, thanks. Just a question: Why is the repo private? 😄
