### ISSUE TITLE
bug: ion header flicker (previous tab shows up on the current tab)

### ISSUE THREAD

**Issue by Exocomp** [ionic-team/ionic-framework#23490]
# Bug Report

**Ionic version:**
Ionic: v5.6.10
Angular: v12.0.5

**Current behavior:**
- Change navigate from tab1 to tab2
- Tab1 header shows up on tab2 for a split second causing a flicker, it is noticeable and bad user experience.

**Expected behavior:**
As soon as the user is on tab2 the tab1 header should not be visible

<img width="408" alt="Screen Shot 2021-06-22 at 6 15 55 PM" src="https://user-images.githubusercontent.com/25571083/123011429-f89bc000-d385-11eb-87ec-2a9473bad4e6.png">

<img width="415" alt="Screen Shot 2021-06-22 at 6 17 20 PM" src="https://user-images.githubusercontent.com/25571083/123011543-36004d80-d386-11eb-85dd-5fac98956d5d.png">

**NOTE**: See screen shots above, note how the tab1 header is showing on tab2 which should not happen.

**NOTE** This started happening as I added a few components to both tab1 and tab2, if tab1 and tab2 have no components the issue does not occur.

Here is how Tab 2 should look like:

<img width="415" alt="Screen Shot 2021-06-22 at 6 21 48 PM" src="https://user-images.githubusercontent.com/25571083/123011833-ca6ab000-d386-11eb-9ff6-d0971b11ee2a.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue! Could you please reproduce this in an Ionic starter app and provide a link to the repo?

**Comment by Exocomp** [comment]
I'll try to but since the starter app is barebones it doesn't happen. I would have to create a few components and add it to each tab, if I can get some time I will try it. I tried several work arounds yesterday, mainly to not show anything on the DOM initially waiting about 250 millis and that solved the issue. However, that results in bad user experience also since for a moment the user gets a flash of white screen.  Anyway today I'm working simple custom header to avoid the issue but would rather the ion header issue be resolved.

Also the issue happens initially on the first navigate from tab1 to tab2, I suspect (just from observation) the issue is that as one adds more components the page takes a little bit more time to load/initialize which produces the issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
