### ISSUE TITLE
feat: Allow disabling Haptic feedback for Ion-Picker or Ion-Datetime

### ISSUE THREAD

**Issue by michalsisak** [ionic-team/ionic-framework#23491]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**
Allow option to disable Haptic feedback in Ion-Picker. ( I specifically need it for Ion-Datetime)

**Describe Preferred Solution**
An input to Ion-Datetime disabling haptic response. e.g. `hapticResponse="false"`. Can be enabled by default.

**Comment by liamdebeasi** [comment]
Thanks for the issue! Could you please clarify why you want to disable the haptic feedback on `ion-datetime`?

**Comment by michalsisak** [comment]
While we realize it is a default iOS experience. We feel like it is interfering with a pleasant UX we wish to deliver to our users. When we are setting a time for example from 08:00 to 08:40 (so basically 40 or so little vibrations) it feels buggy in a way and we think its not improving user experience. It may feel like the phone is vibrating way too much.

We also feel that Haptic on Android is much less smooth and refined. Not sure if that is a problem of a phone or Android but ideally we could at least turn it off for given platform as suggested [here](https://github.com/ionic-team/ionic-framework/issues/22838).

**Comment by liamdebeasi** [comment]
Thanks! That makes sense. We are tracking all datetime issues in https://github.com/ionic-team/ionic-framework/issues/16630, so I will add your issue there. We got another request similar to this in #22838 so I think this is definitely something we can provide configuration for.
