### ISSUE TITLE
bug: Switch required with fallback routes in React

### ISSUE THREAD

**Issue by sherbst** [ionic-team/ionic-framework#23507]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**
[ ] **6.x**

**Current behavior:**

According to the [docs](https://ionicframework.com/docs/react/navigation#switches-in-ionrouteroutlet) a react-router `Switch` component placed inside of `IonRouterOutlet` should have no effect. This doesn't appear to be true for two reasons.

1. A `Switch` placed inside a `IonRouterOutlet` results in animations not being displayed between transitions.
2. And, the lack of a `Switch` results in the fallback route (if it exists) always being rendered.

This second point is crucial because it means you can't use a fallback route AND page transition animations. Perhaps these two points are expected behavior and the docs should be updated, but it seems it is a bug.

**Expected behavior:**

Neither of those issues should happen (or the docs should be updated if this is intended behavior).

**Steps to reproduce:**

1. [Clone test project](https://github.com/sherbst/ionic-router-test/tree/master/src)
2. Start dev server: `npm start`

For my first point above go to [http://localhost:3001/1](http://localhost:3001/1] and click the link. The app will navigate successfully, but there will be no animation as is expected.

For my second point remove the `Switch` from `App.tsx` and reload the page. The app should now display the fallback route, instead of the first matching route.

**Ionic info:**

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /home/sawyer/.npm-packages/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/sawyer/.npm-packages/lib/node_modules/@ionic/cli/lib/index.js
       - /home/sawyer/.npm-packages/lib/node_modules/@ionic/cli/index.js
       - /home/sawyer/.npm-packages/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /home/sawyer/.npm-packages/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/sawyer/.npm-packages/lib/node_modules/@ionic/cli/lib/index.js
       - /home/sawyer/.npm-packages/lib/node_modules/@ionic/cli/index.js
       - /home/sawyer/.npm-packages/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.16.1 (/home/sawyer/.npm-packages/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.10

Capacitor:

   Capacitor CLI      : 3.0.2
   @capacitor/android : not installed
   @capacitor/core    : 3.0.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v12.18.2 (/usr/bin/node)
   npm    : 6.14.8
   OS     : Linux 5.8

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Did you push your changes to the repo? All I see is a blank starter app without the Switch. Also when you push your code, I would double check the [Ionic React Fallback Route Docs](https://ionicframework.com/docs/react/navigation#fallback-route) since we handle fallback routes a bit differently than React Router does.

Also regarding the Switch, I guess a better way of describing it in the docs is since `IonRouterOutlet` takes over the job in determining which routes get rendered, using a `Switch` will interfere with `IonRouterOutlet` (as you noted above). In other words it may be better to say that using Switch will not have the intended behavior, rather than it not doing anything.
