### ISSUE TITLE
bug: Redirect behaviour inconsistent with Ionic/React

### ISSUE THREAD

**Issue by damiensawyer** [ionic-team/ionic-framework#23503]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x ] **5.x**
[ ] **6.x**

**Current behavior:**

Navigating to a Redirect route shows inconsistent behaviour. 

**Expected behavior:**
Clicking on links to a route which has been registered to redirect to another route should consistently work. 

**Steps to reproduce:**

See replication [here](https://stackblitz.com/edit/react-1g5v5u) (note that, on my system, I had to expand the width of the embedded browser panel to show the links). 

I can replicate the issue with the following steps. 
- Load page (I had to press ctrl-shift-r in Chrome... not just the refresh button in StackBlitz)
- click 'home'  --> You are taken to Home.
- click 'login' --> You are taken to Login
- click 'counter' --> You are taken to Home (which is what I would expect. Counter redirects to Home)
- click 'home'  --> You are taken to Home.
- click 'login' --> You are taken to Login
- click 'counter' --> Error! The url says /page/Counter, however the Login component is still displayed. 

**Related code:**
see https://stackblitz.com/edit/react-1g5v5u

**Other information:**

**Ionic info:**

```
$ ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\Damien\AppData\Roaming\nvm\v16.2.0\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Damien\AppData\Roaming\nvm\v16.2.0\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Damien\AppData\Roaming\nvm\v16.2.0\node_modules\@ionic\cli\index.js
       - C:\Users\Damien\AppData\Roaming\nvm\v16.2.0\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.16.1 (C:\Users\Damien\AppData\Roaming\nvm\v16.2.0\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.6.9

Capacitor:

   Capacitor CLI      : 3.0.1
   @capacitor/android : 3.0.1
   @capacitor/core    : 3.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v16.2.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.13.0
   OS     : Windows 10
```

**Comment by amandaesmith3** [comment]
Thanks for the issue. This is a quirk of React Router (which `IonReactRouter` uses under the hood). The `from` prop of `Redirect` can only be used when inside a `Switch` component (see the docs [here](https://v5.reactrouter.com/web/api/Redirect/from-string)). In other cases, the `Redirect` should be used in the render of a `Route`.

Could you try this instead and let me know if it works for you?
```
<IonRouterOutlet id="main">
  <Route path="/page/Home" component={HomePage} />
  <Route path="/page/Login" component={LoginPage} />
  <Route path="/page/Counter" render={() => <Redirect to="/page/Home" />} />
</IonRouterOutlet>
```

**Comment by damiensawyer** [comment]
Hi @amandaesmith3 - thanks very much. That appears to work as expected.
