### ISSUE TITLE
bug: Item Highlight should appear above Helper Text

### ISSUE THREAD

**Issue by RobertWeaver** [ionic-team/ionic-framework#23510]
# Bug Report

**Ionic version:**
[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**
When a Material Input has focus the item highlight is appearing below the helper and error text.

![image](https://user-images.githubusercontent.com/6476560/123394319-99ca8680-d5d1-11eb-840d-d150494b5b82.png)

**Expected behavior:**
When a Material Input has focus a highlight should appear below the input but above the helper and error text.

Here is how the focused input appears using Angular Material.

![image](https://user-images.githubusercontent.com/6476560/123394523-d0a09c80-d5d1-11eb-86b8-a825a1b66110.png)

[https://material.angular.io/components/input/examples#input-error-state-matcher](https://material.angular.io/components/input/examples#input-error-state-matcher)

![image](https://user-images.githubusercontent.com/6476560/123395432-c7fc9600-d5d2-11eb-8ff4-42de4638b9c8.png)

[https://material.angular.io/components/input/examples#input-hint](https://material.angular.io/components/input/examples#input-hint)

**Steps to reproduce:**
Click or set focus to an Input in Material mode with helper or error text defined.

**Related code:**

CodeSandBox Demo using Ionic Custom Elements
[https://codesandbox.io/s/pensive-flower-mtpep?file=/src/index.js](https://codesandbox.io/s/pensive-flower-mtpep?file=/src/index.js)

**Ionic info:**
Ionic 6.0.0-dev.202106232232.ceabba1

**Comment by willmartindev** [comment]
@RobertWeaver Thank you for the issue, the reproduction, and participating in the Framework v6 beta!

It looks like this issue is happening because the `ion-item` isn't given `fill="solid"` or `fill="outline"`. I will take a look into how we want to proceed with this issue.

**Comment by willmartindev** [comment]
This has been resolved and the fix will be available in the next beta release of Framework v6. Thanks!
