### ISSUE TITLE
bug: Arrow Keys do not seem to work with Popover

### ISSUE THREAD

**Issue by RobertWeaver** [ionic-team/ionic-framework#23512]
# Bug Report

**Ionic version:**
[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**
When using the keyboard to interact with the Popover the arrow keys do not move up and down the list items. Once the trigger button has focus I can open the menu with the space or enter key and then tab between the items. But up and down arrow does not work.

**Expected behavior:**
The documentation confirms the arrow keys should work for keyboard navigation between items.

![image](https://user-images.githubusercontent.com/6476560/123426015-70bbed00-d5f5-11eb-946a-ee151731d028.png)

[https://beta.ionicframework.com/docs/api/popover#keyboard-navigation](https://beta.ionicframework.com/docs/api/popover#keyboard-navigation)

Angular Material opens a select style dropdown with the first item already focused saving a key stroke. It would be good to have such a feature for desktop users.

![image](https://user-images.githubusercontent.com/6476560/123426168-a3fe7c00-d5f5-11eb-9a1b-4bedd371b0ad.png)

[https://material.angular.io/components/select/overview#select-form](url)

Also the regular Angular Material Menu dropdown can navigate down to nested menus using only arrow keys.
![image](https://user-images.githubusercontent.com/6476560/123426354-e627bd80-d5f5-11eb-9bbe-6cef07226021.png)

[https://material.angular.io/components/menu/examples#menu-icons](https://material.angular.io/components/menu/examples#menu-icons)

**Steps to reproduce:**
Click or set focus to a button that can open a Popover then use the tab key to focus to first item then try to use arrow keys to move up and down between items.

**Related code:**
CodeSandBox Demo using Ionic Custom Elements
[https://codesandbox.io/s/thirsty-brook-b9lhr?file=/src/index.js](https://codesandbox.io/s/thirsty-brook-b9lhr?file=/src/index.js)

**Ionic info:**
Ionic 6.0.0-dev.202106232232.ceabba1

**Comment by willmartindev** [comment]
Thanks for the issue! This has been resolved and a fix will be available in the next beta release of Framework v6.
