### ISSUE TITLE
bug: useIonModal dismiss() does not unmount component

### ISSUE THREAD

**Issue by babycourageous** [ionic-team/ionic-framework#23517]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ x] **5.x**
[ ] **6.x**

**Current behavior:**

The new `useIonModal` hook does not unmount the component that is being used as the modal when `dismiss()` is called.

**Expected behavior:**

The `present` function mounts the component and the `dismiss` function unmounts and removes the component from the React tree.

**Steps to reproduce:**

Follow the docs for `useIonModal`

**Related code:**
Below is a video of the react component tree as i `present` and `dismiss` the modal using the return tuple from `useIonModal()`

https://user-images.githubusercontent.com/14936212/123503005-2864f500-d61e-11eb-803a-7b20d4f0047b.mov

**Ionic info:**

```
Ionic:

   Ionic CLI       : 5.4.16 (/Users/rene/.npm/_npx/23301/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 5.6.10

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.3 (/Users/rene/.nvm/versions/node/v12.16.3/bin/node)
   npm    : 6.14.4
   OS     : macOS Mojave```

Thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. Could you reproduce this issue in an Ionic starter app and provide a link to the repo? I see you also reported https://github.com/ionic-team/ionic-framework/issues/23516, so feel free to just re-use the reproduction from there.

**Comment by babycourageous** [comment]
Hi Liam

Absolutely, here ya go!
https://github.com/babycourageous/ionic-react-modal-hook-issue

**Comment by liamdebeasi** [comment]
I can reproduce this behavior. Likely related to https://github.com/ionic-team/ionic-framework/issues/23516 given that the overlay is not rendered within the app context.

**Comment by babycourageous** [comment]
Thanks for the update @liamdebeasi !

Yeah, i figured the two had some crossover.

**Comment by babycourageous** [comment]
Hi @liamdebeasi - sorry to ping this issue- but wanted to see if it makes sense to close this issue as something that won't be addressed for v5. 
I saw that [#24008](https://github.com/ionic-team/ionic-framework/pull/24008) was merged into the "next" branch and #23516 is closed. I can confirm v6 modal mounts and unmounts as expected; so i was curious if it would only be addressed for v6. If so, I totally understand if this is a not-fix for v5 and you can close this issue accordingly. 

Thanks again!

**Comment by liamdebeasi** [comment]
Thanks for the ping! I can confirm that this issue will only be fixed in Ionic 6. Ionic 5 is only receiving critical security fixes now.

I am going to close this as this issue is resolved in Ionic 6.

**Comment by babycourageous** [comment]
Thanks so much @liamdebeasi !
