### ISSUE TITLE
bug: v6, datetime should have better APIs for controlling size

### ISSUE THREAD

**Issue by RobertWeaver** [ionic-team/ionic-framework#23518]
# Bug Report

**Ionic version:**
[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**
DateTime component inside a modal seems to have a fixed width of 350px.
![image](https://user-images.githubusercontent.com/6476560/123504330-25ecb480-d68b-11eb-91f3-d02d6c191fa7.png)

Desktop Tablet
![image](https://user-images.githubusercontent.com/6476560/123504433-e4103e00-d68b-11eb-9a75-7378ff352691.png)

Phone
![image](https://user-images.githubusercontent.com/6476560/123504471-1b7eea80-d68c-11eb-97f0-41e4506d7a05.png)

**Expected behavior:**
Would like ability to control the width of the DateTime component.

Vuetify's DateTime component has this feature...
![image](https://user-images.githubusercontent.com/6476560/123504539-88928000-d68c-11eb-9b2a-6b47ebb54e1b.png)

[https://vuetifyjs.com/en/components/date-pickers/#width](https://vuetifyjs.com/en/components/date-pickers/#width)

Then maybe we can have a display like this inside the modal...

Desktop Tablet
![image](https://user-images.githubusercontent.com/6476560/123504629-356cfd00-d68d-11eb-90fe-ad7e8934f135.png)

Phone
![image](https://user-images.githubusercontent.com/6476560/123504668-52a1cb80-d68d-11eb-9b53-044fa9bab4e2.png)

**Steps to reproduce:**
Launch a modal containing a DateTime component.

**Related code:**

CodeSandBox Demo using Ionic Custom Elements
[https://codesandbox.io/s/pedantic-firefly-hylbr?file=/src/index.js](https://codesandbox.io/s/pedantic-firefly-hylbr?file=/src/index.js)

Ionic info:
Ionic 6.0.0-dev.202106232232.ceabba1

**Comment by liamdebeasi** [comment]
Thanks for the issue. I agree, we need better APIs to control the `ion-datetime` sizing inside of modals/popovers.

**Comment by Klunk75** [comment]
Hi,
I confirm the behaviour, I had to remove the width property to fit properly the component in the window.
Also, I had to remove the background property in order to have the color scheme to match the theme.

Paolo

![image](https://user-images.githubusercontent.com/15050263/124114530-fb28a480-da6c-11eb-98de-45a7be6eb163.png)

**Comment by liamdebeasi** [comment]
Hmm, the background of the datetime is white in light mode so it should match the theme automatically. Are you customizing your theme at all?

**Comment by Klunk75** [comment]
> Hmm, the background of the datetime is white in light mode so it should match the theme automatically. Are you customizing your theme at all?

Yes, I'm using a custom dark theme (I've just modified the dark theme variable values in the "variables.scss" file).
Here is how it shows:

![image](https://user-images.githubusercontent.com/15050263/124131573-3c767f80-da80-11eb-8944-685b0ac926c7.png)

If I remove the background variable it shows correctly:

![image](https://user-images.githubusercontent.com/15050263/124131804-7051a500-da80-11eb-90eb-0ae79c306774.png)

Same thing for the month picker:

![image](https://user-images.githubusercontent.com/15050263/124131952-98410880-da80-11eb-823d-83cd9ae31485.png)

Removing background:

![image](https://user-images.githubusercontent.com/15050263/124132115-c32b5c80-da80-11eb-86e7-59ab6d14d0e5.png)

**Comment by liamdebeasi** [comment]
Datetime internally uses the `--ion-color-light` and `--ion-color-step-100` CSS Variables, so I would make sure that those are set in your application otherwise it will fall back to the light mode values (`#ffffff`).

**Comment by Klunk75** [comment]
> Datetime internally uses the `--ion-color-light` and `--ion-color-step-100` CSS Variables, so I would make sure that those are set in your application otherwise it will fall back to the light mode values (`#ffffff`).

Thanks for the info Liam,
those variables were still set to colors for light mode, now I have updated to dark mode colors and the problem disappeared.
Thanks again for the address!

Paolo

**Comment by liamdebeasi** [comment]
Glad it is working now!

**Comment by liamdebeasi** [comment]
(And thanks for testing the v6 beta!)

**Comment by EinfachHans** [comment]
Additional: I'm unsure if this width expanding only is important for overlays.
I just tested the DateTime Component inside of a Accordion Component (to create the same look and feel like native ios has for example in reminders). Here is what is looks like:

<img width="419" alt="Bildschirmfoto 2021-07-01 um 16 34 12" src="https://user-images.githubusercontent.com/20899975/124142077-32f21500-da8a-11eb-92c1-91c441912ae0.png">

I think it should have a width of 100% here defaultly

**Comment by liamdebeasi** [comment]
The original reason why we set a fixed width was we assumed most people would try to put the datetime into a page when developing on their computer. If the datetime took up 100% of the width, the datetime would be huge and we think it would leave developers wondering if something was broken.

For now, we recommend setting the width manually on the `ion-datetime` but the team is going to discuss if another API is necessary for this.

**Comment by willmartindev** [comment]
Thank you for this issue! A `size` property has been added to `ion-datetime` and will be available in the next release of the beta.
