### ISSUE TITLE
bug: popover size is not working properly with an event (no trigger)

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-framework#23528]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**

Passing `size: 'cover'` when opening a popover using a `popoverController` is not working with an event without a `trigger`, the `trigger` is `null`

**Expected behavior:**

The popover should be using the element from the passed in event here:
https://github.com/ionic-team/ionic-framework/blob/next/core/src/components/popover/animations/ios.enter.ts#L22
https://github.com/ionic-team/ionic-framework/blob/next/core/src/components/popover/animations/md.enter.ts#L21

**Steps to reproduce:**

Can be reproduced on the `next` branch by passing `size: cover` with an event

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/23532.
