### ISSUE TITLE
bug: segment should be usable with arrow keys

### ISSUE THREAD

**Issue by RobertWeaver** [ionic-team/ionic-framework#23520]
# Feature Request

**Ionic version:**
[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Describe the Feature Request**
Would like the ability to arrow key left and right between Segment buttons. 
Bonus feature request would be able to use Enter Key to activate the focused Segment Button.

**Describe Preferred Solution**
Closest I can find for this behavior is with the Angular Material Tabs.

![image](https://user-images.githubusercontent.com/6476560/123505281-c2658580-d690-11eb-8ef0-459e69849aa0.png)

[https://material.angular.io/components/tabs/overview#tab-group-basic](https://material.angular.io/components/tabs/overview#tab-group-basic)

**Comment by willmartindev** [comment]
Thanks for this issue! Keyboard navigation in `ion-segment` has been improved in a change that is going live in Framework v6.
