### ISSUE TITLE
feat: toast with icon

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#23524]
# Feature Request

**Ionic version:**
[ ] **4.x**
[x] **5.x**
[ ] **6.x**

**Describe the Feature Request**
A toast with an icon would be nice. The buttons can already have an icon. But the message itself should have an optional icon at slot start.

https://ionicframework.com/docs/api/toast

![image](https://user-images.githubusercontent.com/60390085/123633958-210a3b00-d81a-11eb-9470-5e39461a6448.png)
<sup>Just a photo montage.</sup>

**Related Code**

```ts
const toast = await this.toastController.create({
  header: 'Toast header',
  message: 'Click to Close',
  icon: 'bug', // <- new property
});
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23596, and this feature will be in the next Framework v6 beta.
