### ISSUE TITLE
bug: ion-select arrow has wrong padding in rtl + ios mode on safari

### ISSUE THREAD

**Issue by eviv3k** [ionic-team/ionic-framework#23540]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**
[ ] **6.x**

**Current behavior:**
`:host-context` is not supported in Safari.
On Safari iOS: Wrong padding/space (arrow) when using ion-select in RTL layouts:
![Safari](https://user-images.githubusercontent.com/4935981/123923663-d4079f80-d9a6-11eb-9d71-0dbab1a728af.png)

**Expected behavior:**
On Chrome: Correct the padding/spacing in RTL layouts, to work as excepted:
<img width="400" alt="Chrome" src="https://user-images.githubusercontent.com/4935981/123924020-2c3ea180-d9a7-11eb-9725-df634cebccae.PNG">

**Steps to reproduce:**
Using in RTL Ionic 5 apps

**Related code:**

```
<ion-item>
     <ion-label>Item 1</ion-label>
     <ion-select>
           <ion-select-option [value]="item" *ngFor="let item of items">{{ item.Name }}</ion-select-option>
      </ion-select>
</ion-item>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.7
   @angular-devkit/build-angular : 0.901.15
   @angular-devkit/schematics    : 9.1.15
   @angular/cli                  : 9.1.15
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 29 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.4.0) : 1.3.0

System:

   ios-sim : 8.0.2
   NodeJS  : v14.16.1 (/usr/local/bin/node)
   npm     : 6.14.12
   OS      : macOS Big Sur
   Xcode   : Xcode 12.4 Build version 12D4e
```

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with ion-select. This issue is fixed when using that new syntax. We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new select syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
