### ISSUE TITLE
bug: ion-list items cannot be scrolled through

### ISSUE THREAD

**Issue by NunoSav** [ionic-team/ionic-framework#23547]
# Bug Report

**Ionic version:**
[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**
`ion-list` content can't be scrolled.

**Expected behavior:**
Scrolling through `ion-list` items.

**Steps to reproduce:**
1. `ionic start sample list --type=vue`
2. perform the steps detailed [here](https://github.com/ionic-team/ionic-framework/blob/next/BETA.md#ionic-vue)
3. run `ionic serve` (best to use mobile dimensions)

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.16.3
   Ionic Framework : @ionic/vue 6.0.0-dev.202106291310.379deca

Capacitor:

   Capacitor CLI      : 3.0.2
   @capacitor/android : not installed
   @capacitor/core    : 3.0.2
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : 1.4.0

System:

   NodeJS : v14.16.0 (/usr/local/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you send over a repo of how you are using the `ion-list`? I tried scrolling with the v6 beta in the list starter app and it scrolled as expected.

**Comment by NunoSav** [comment]
Here's the repo https://github.com/NunoSav/ionic6-ion-list

**Comment by liamdebeasi** [comment]
Thanks! This is the same problem as https://github.com/ionic-team/ionic-framework/issues/23539. There was a breaking change in Vue 3.1.0 where all component properties were set to `undefined` if they weren't being used. Previously, the properties were just not included in the Vue component `props` object. As a result of this change, the `scrollY` property on `ion-content` is being set to `undefined` which prevents scrolling from happening.

Going to merge this with https://github.com/ionic-team/ionic-framework/issues/23539, and you can workaround this for now by downgrading to `vue@3.0.11`.
