### ISSUE TITLE
feat: Change Datetime Start of the Week

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23556]
# Feature Request

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[X] **6.x**

**Describe the Feature Request**

For me living in Germany it would be great to be able to change the Start of the Week day as it is Monday for us.

**Describe Solutions**

- `startOfTheWeek` Property
- automatically by locale if this is possible?

**Comment by EinfachHans** [comment]
What would be the preferred implementation here? @liamdebeasi 

I guess a Property as it looks like there is no pure js implementation without creating a map for every locale

**Comment by KristjanLaane** [comment]
Yup, our users keep picking the wrong day because they visually pick the first date in the row assuming it is Monday, when in fact it is Sunday in this date picker.

**Comment by EinfachHans** [comment]
I can create a PR, i just don't know what the Ionic Team's preferred Solution is.

Creating a Prop would be the easiest one, but it removes the configuration by locale advantage. But it doesn't look like there is an pure js solutions, so i think the options are:
- `startOfWeek` Prop
- Include a Map with all locales and the startOfWeek Day into Ionic (i personally on't like this one)
- Include a external library into Ionic (i think they won't like that one)

**Comment by liamdebeasi** [comment]
I would prefer a `startOfWeek` property that accepts an integer value corresponding to the first day of the week. This property should default to `0` so the start of the week is Sunday by default.

For example, `startOfWeek="2"` would make Tuesday the first day of the week.

The definition should look something like this:

```ts
@Prop() startOfWeek: number = 0;
```

It might be worth doing some investigating first to see if we can determine the start of the week automatically. We use this API internally: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat.

**Comment by EinfachHans** [comment]
I found this open Issue so looks like it's not able to determinate automatically currently: https://github.com/tc39/ecma402/issues/6

I will create a PR with a new Property 😊

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23692, and this feature will be available in an upcoming release of the Ionic Framework v6 beta.
