### ISSUE TITLE
bug: Accordion multiple throws error if value is not an array

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23550]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[X] **6.x**

**Current behavior:**

When i have an Accordion, that has `multiple: true` and a value as a string (not an array), it throws an error whenever i try to collapse / expand something:

```
TypeError: groupValue.find is not a function. (In 'groupValue.find(v => v === accordionValue)',
``` 

**Expected behavior:**

I think this case needs an additional Check here:
https://github.com/ionic-team/ionic-framework/blob/bdb95b7b6dd798cbc6d1786ae54fa95ac1dfd096/core/src/components/accordion-group/accordion-group.tsx#L71-L75

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.0
   @angular-devkit/build-angular : 12.0.5
   @angular-devkit/schematics    : 12.0.5
   @angular/cli                  : 12.0.5
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.0.2
   @capacitor/android : not installed
   @capacitor/core    : 3.0.2
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : 1.4.0

System:

   NodeJS : v14.15.4 (/usr/local/bin/node)
   npm    : 7.17.0
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Accordion group does not currently accept a comma separated string like components such as `ion-datetime` do, but it probably should otherwise this is going to be hard to use in vanilla JS environments.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23581, and a fix will be available in an upcoming release of Ionic Framework.
