### ISSUE TITLE
feat: Add option to remove "Time" Label from DateTime

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23555]
# Feature Request

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[X] **6.x**

**Describe the Feature Request**

The DateTime Picker has a "Time" Label next to the Time selector. As i mostly want to use the Datetime Component inline like native ios, it would be great to be able to remove this text, as it isn't there on native ios either (compare reminder app).

**Describe Solutions**

- `timeLabel` Property which can be a string
- `showTimeLabel` boolean Property

I can create a PR for this if you say me which is the preferred way of handling this

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23577, and a fix will be available in an upcoming release of Ionic Framework.
