### ISSUE TITLE
bug: Toggle IonAccordion from Controller

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23551]
# Feature Request

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[X] **6.x**

**Describe the Feature Request**

I would like to toggle a specific Accordion from my Controller.

**Describe Preferred Solution**

In Angular:
```ts
@ViewChild('accordion')
accordion: IonAccordion;

someMethode() {
    this.accordion.toggle();
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide a use case for this feature? `ion-accordion-group` is designed in the same way as `ion-radio-group` and `ion-segment` in that you need to set the `value` property in order to activate a particular accordion.

**Comment by EinfachHans** [comment]
My specific Use case i had in mind is we have a page with a accordion and one of the items contains a checkbox which could be required. If the Users clicks on a "next" button and hasn't checked the checkbox i show them a Message and open the specific Accordion.

**Comment by liamdebeasi** [comment]
I think it would be better to stay with setting the `value` as that does not require getting a reference to an accordion element. The problem with manually toggling the accordion is you would then also be responsible for collapsing other open accordion elements which seems like a lot of additional programming for the user.

When clicking the `next` button, can you try setting the `value` of the `ion-accordion-group` using ngModel and see if that produces the desired effect? Something like this:

```html
<ion-accordion-group [(ngModel)]="accordionValue">
  ...
</ion-accordion-group>

<ion-button (click)="validate()">Next</ion-button>
```

```js
validate() {
  if (!isCheckboxChecked) {
    this.accordionValue = 'my-accordion-value';
  }
}
```

The other thing is I am not sure an accordion is going to be the best UX for form validation. It might be better to show/hide a div based upon Angular's Form Validation.

**Comment by EinfachHans** [comment]
I don't think that there would be extra programming for the user, as if we would use the same function like on the Accordion Click, the other Accordions would collapse (if not multiple) automatically?

But anyways, i tried by reassigning the Value Field, which **does work** 😊 
What doesn't work for me is using `[(ngModel)]`, should that be supported?

**Comment by liamdebeasi** [comment]
> I don't think that there would be extra programming for the user, as if we would use the same function like on the Accordion Click, the other Accordions would collapse (if not multiple) automatically?

In order to do this, `ion-accordion` would have to set the value of `ion-accordion-group` automatically which is a practice we moved away from with v5 because it caused a lot of synchronization issues (for example, we did this with radio: https://github.com/ionic-team/ionic-framework/blob/master/BREAKING.md#radio)

Glad setting the `value` property works. Also sorry I misspoke, accordion group does not have `ngModel` support since it's not a form element.

**Comment by EinfachHans** [comment]
Okay understood 😊
