### ISSUE TITLE
bug: Datetime: Make Time-selector match more native

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23568]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[X] **6.x**

**Current behavior:**

**Note**: If they stick with reverting the Timepicker for iOS15 i think this Issue can be closed, but currently:

- If i (in native iOS) drag the timepicker up, the hour or minute value increases, and decreases on dragging down. In the Ionic one this seems to be switched
- In native iOS the Values are a Loop, so you can scroll infinite, after 23 comes 0 again. The Ionic one stops at first and last Value

**Expected behavior:**

To match the native Look & Feel (if it's not getting changed)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.0
   @angular-devkit/build-angular : 12.0.5
   @angular-devkit/schematics    : 12.0.5
   @angular/cli                  : 12.0.5
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.0.2
   @capacitor/android : not installed
   @capacitor/core    : 3.0.2
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : 1.4.0

System:

   NodeJS : v14.15.4 (/usr/local/bin/node)
   npm    : 7.17.0
   OS     : macOS Big Sur

```

**Comment by liamdebeasi** [comment]
Thanks! I am going to merge this with out iOS 15 support issue: https://github.com/ionic-team/ionic-framework/issues/23423
