### ISSUE TITLE
bug: inline modal/popover framework integrations should automatically dismiss before unmount

### ISSUE THREAD

**Issue by tho-masn** [ionic-team/ionic-framework#23567]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**
The closing behavior of the ion-modal vue component changed. I have a base modal which is integrated similar to this:
```
<BaseModal
    v-if="showModal"
    @click:close="showModal = false"
/>
```
The BaseModal component wraps the actual ion-modal component, setting `is-open` always to true. So the outer v-if decides if the modal gets rendered or not.

In v5 setting `showModal` to false triggered the close animation. In v6.beta-0 the modal disappears immediately.

Behavior in v5:

https://user-images.githubusercontent.com/23264228/124237450-d50c0e80-db17-11eb-8958-6746d01eb2df.mov

Behavior in v6:

https://user-images.githubusercontent.com/23264228/124237459-d76e6880-db17-11eb-85fb-ac7f42f9f818.mov

**Expected behavior:**
The close animation should be triggered if the Modal gets deactivated via v-if

**Steps to reproduce:**
Sample code for v5: https://github.com/tho-masn/ionic-issues/tree/v5-ion-modal-close
Sample code for v6: https://github.com/tho-masn/ionic-issues/tree/v6-ion-modal-close

**Comment by liamdebeasi** [comment]
Thanks for the issue. With v6 we are trying to move as much of the inline modal logic inside of `ion-modal` itself and away from the framework-specific wrappers.

The framework-specific wrappers automatically call dismiss in `onVnodeBeforeUnmount` which is something that got removed in v6, but I think we should still keep this functionality.

For context, here is what the modal wrappers look like in v5: https://github.com/ionic-team/ionic-framework/blob/master/packages/vue/src/vue-component-lib/overlays.ts

And here is what modal looks like in v6: https://github.com/ionic-team/ionic-framework/blob/next/packages/vue/src/components/IonModal.ts. I think we could add `onVnodeBeforeUnmount` here to preserve this dismiss behavior.

**Comment by tho-masn** [comment]
@liamdebeasi: I'm wondering if there is any workaround to this? I've tried dismissing the modal manually in the `beforeUnmount` hook of my `BaseModal` component, but that doesn't seem to work correctly.
Would be happy for any guidance, as this is blocking us from upgrading to v6.

**Comment by liamdebeasi** [comment]
You might be able to integrate with [Vue Enter and Leave Transitions](https://v3.vuejs.org/guide/transitions-enterleave.html#javascript-hooks). This is likely what we will implement internally.

**Comment by thetaPC** [comment]
Thank you for submitting the issue! The team has investigated this further. If an overlay is unmounted via a conditional rendering then the dismiss animation will not occur.

If you want to have the dismiss animation, then it is recommended to call the `dismiss` function before unmounting.

```vue
dismiss() {
   this.$refs.modal.$el.dismiss();
   this.showModal = false;
},
```
