### ISSUE TITLE
bug: Going to a nested route inside another nested route doesn't show an animation on first visit

### ISSUE THREAD

**Issue by fr3fou** [ionic-team/ionic-framework#23575]
# Bug Report

**Ionic version:**

- [x] **5.x**

**Current behavior:**
If you have a nested route (`/dashboard/users/:id`, in the example below, note how it also has its own `IonRouterOutlet`) inside another nested route (`/dashboard`, also has its own `IonRouterOutlet`) and you are located on `/dashboard`, then navigate to a subpage `/dashboard/users/:id`(in the example below, click on `User 1`), there will **not** be an animation **only** on the first time that page is rendered (I would assume it has to do with the `IonRouterOutlet` needing to match a URL first before transitioning?), any subsequent navigations to it will have an animation. (sidenote: I also think that back animations are slightly different than usual?)

Some context what I want to achieve:

> Take Instagram for example - if you are on your Home page, then click on a Post to see the post's comments (that's 1 nested route) and then you can click on the User of a given comment (that will take you to their profile), from which you can keep doing the same thing recursively (Post -> PostComments -> UserProfile -> Post -> ... and so on); The reason why it has to be nested is because each Tab has to keep its own Stack. If I instead have a single `/post-comments/:id` and a single `/user-profile/:id` at the root of my router, each Tab that _can_ go to those pages won't keep their stack (i.e. Go to a Post from your Home page, then to a UserProfile, then on another tab, say from Search, you do the same thing and what you'd expect is that _both_ tabs keep their stack.

**Expected behavior:**
I expect there to be an animation on the nested route as well

**Steps to reproduce:**

1. Load the example below
2. Click on `User 1`

**Related code:**

https://stackblitz.com/edit/nested-route-bug?file=src/pages/UserDetailPage.tsx

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.16.3 (/Users/simo/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.11

Capacitor:

   Capacitor CLI      : 3.0.2
   @capacitor/android : 3.0.2
   @capacitor/core    : 3.0.0
   @capacitor/ios     : 3.0.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v16.3.0 (/opt/homebrew/Cellar/node/16.3.0/bin/node)
   npm    : 7.15.1
   OS     : macOS Big Sur
```

**Comment by joelmeaders** [comment]
Unfortunately you're going to have a lot more issues than this using nested ion-router-outlets, especially if you're utilizing lazy loading in those nested outlets. There are unsolved bugs going back years relating to nested ion-router-outlets.

**Comment by fr3fou** [comment]
> Unfortunately you're going to have a lot more issues than this using nested ion-router-outlets, especially if you're utilizing lazy loading in those nested outlets. There are unsolved bugs going back years relating to nested ion-router-outlets.

Do you have any recommendations for achieving what I described in the context part of the issue? This thread goes a bit more into detail https://www.reddit.com/r/ionic/comments/od51jo/can_anyone_help_me_fix_this_if_im_going_to_a/

I've been thinking of abandoning `<IonReactRouter>`, using `<BrowserRouter>` and implementing some simple transitions manually. What other benefits are there to using `<IonReactRouter>`?

**Comment by joelmeaders** [comment]
> I've been thinking of abandoning `<IonReactRouter>`, using `<BrowserRouter>` and implementing some simple transitions manually. What other benefits are there to using `<IonReactRouter>`?

Ah I didn’t see you were using React, I apologize! I’m not sure if the react version of the router outlet has the same issues as the angular version.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Could you give me some more context about why you need to use 3 levels of nested router outlets in your application?

In general, you should only really use nested routes when you need to render content in multiple outlets at once (for example, a tab bar and tab content). In your example application, that does not seem to be the usage here so I think it might make more sense to use shared URLs here instead.

**Comment by fr3fou** [comment]
> Thanks for the issue. Could you give me some more context about why you need to use 3 levels of nested router outlets in your application?
> 
> In general, you should only really use nested routes when you need to render content in multiple outlets at once (for example, a tab bar and tab content). In your example application, that does not seem to be the usage here so I think it might make more sense to use shared URLs here instead.

From my original issue:

> Take Instagram for example - if you are on your Home page, then click on a Post to see the post's comments (that's 1 nested route) and then you can click on the User of a given comment (that will take you to their profile), from which you can keep doing the same thing recursively (Post -> PostComments -> UserProfile -> Post -> ... and so on); The reason why it has to be nested is because each Tab has to keep its own Stack. If I instead have a single `/post-comments/:id` and a single `/user-profile/:id` at the root of my router, each Tab that _can_ go to those pages won't keep their stack (i.e. Go to a Post from your Home page, then to a UserProfile, then on another tab, say from Search, you do the same thing and what you'd expect is that _both_ tabs keep their stack.

An example of a recursive route - `/tabs/tab1/post/x/user/y/post/z/user1` and so on; having only a single `/post-detaills` and a single `/user` won't suffice as you can keep going on and on forever.

I managed to fix the animations issue using this - https://github.com/ionic-team/ionic-framework/issues/20597#issuecomment-648468733 

I added `ionPage` to my nested RouterOutlets and it fixed it, however I have to ask, why is this not documented anywhere?
Nowhere in the docs does it say that such prop exists and that it's mean to be used with nested RouterOutlets;
![image](https://user-images.githubusercontent.com/1344906/124606271-66131a80-de75-11eb-8d3d-78e29742e889.png)

Speaking of the docs, why do the docs say that React apps shouldn't be using RouterOutlet? The official starter templates use it, but the docs say otherwise.
![image](https://user-images.githubusercontent.com/1344906/124606399-85aa4300-de75-11eb-8fce-8bec3bf2fdc8.png)

**Comment by liamdebeasi** [comment]
Let me check in with the team on this. I don't know if the `ionPage` property is production-ready or if it's still experimental. Also those docs should include React -- I can put up a PR to address it.

**Comment by liamdebeasi** [comment]
Also are you able to access that `ionPage` property in the latest stable version of Ionic React? Or did you install the dev build? If it only works in the dev build, then the feature has not shipped yet which would explain why it does not show up in the docs.

**Comment by fr3fou** [comment]
> Also are you able to access that `ionPage` property in the latest stable version of Ionic React? Or did you install the dev build? If it only works in the dev build, then the feature has not shipped yet which would explain why it does not show up in the docs.

I'm using these version
![image](https://user-images.githubusercontent.com/1344906/124608021-0d448180-de77-11eb-8443-ce5969d7c39f.png)

**Comment by liamdebeasi** [comment]
Are you able to make an example of the incorrect behavior when not using nested outlets? It would be helpful to see what you previously tried before doing the nested outlet solution. There should be a way to accomplish what you are trying to do without using 3 nested outlets.

**Comment by fr3fou** [comment]
> Are you able to make an example of the incorrect behavior when not using nested outlets? It would be helpful to see what you previously tried before doing the nested outlet solution. There should be a way to accomplish what you are trying to do without using 3 nested outlets.

I've honestly tried so many things at this point and I've forgotten what worked and what didn't, from what I remember I had a single `/post-details` and a single `/user` at the root of my app, no nested RouterOutlets and then I simply redirected from, say, `/tabs/home` _or_ `/tabs/explore/` to `/post-details/5` which didn't add it to the appropriate stack of the given tab. So if I was at `/tabs/home`, clicked on a post that redirects to`/post-details/5`, then changed to another tab, then back to the the home tab, the PostDetails screen would be gone. Issues with this approach were:

- Only one PostDetails screen could be kept at once (even though each tab can open _its own_ PostDetails screen)
- Nesting recursively is impossible while keeping a stack - PostDetails -> UserProfile -> PostDetails -> UserProfile and so on

**Comment by liamdebeasi** [comment]
Do you have a video of the behavior you are expecting to see? Your original post mentioned Instagram, but I do not that so I am a bit unfamiliar with how navigation is supposed to happen there.
