### ISSUE TITLE
Page messes up or keeps flashing on some Android devices

### ISSUE THREAD

**Issue by molobala** [ionic-team/ionic-framework#23579]
**Ionic version:**

[] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
My application(capacitor) keeps flashing on some Android devices: Tecno Camon 11 running on Android 8.1, Alcal 1, ...  
It messes up the whole page, user can't do anything

**Expected behavior:**
Should display the page correctly  

**Other information:**

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.16.3 (/Users/doumbia0804/.nvm/versions/node/v16.3.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.1000.5
   @angular-devkit/schematics    : 10.0.5
   @angular/cli                  : 10.0.5
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI      : 2.4.6
   @capacitor/android : 2.4.6
   @capacitor/core    : 2.4.6
   @capacitor/ios     : 2.4.6

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.3.0 (/Users/doumbia0804/.nvm/versions/node/v16.3.0/bin/node)
   npm    : 7.15.1
   OS     : macOS Big Sur
   Xcode  : Xcode 12.1 Build version 12A7403
```

**Comment by liamdebeasi** [comment]
You might want to take a look at this forum post: https://forum.ionicframework.com/t/android-8-1-icons-not-displaying/211106/41

Some users have discovered a Chromium related bug with Android 8.1 on certain devices. Here is the specific Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1222095
