### ISSUE TITLE
bug: can't serve project ionic vue

### ISSUE THREAD

**Issue by xenom97** [ionic-team/ionic-framework#23570]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x ] 6.16.3

**Current behavior:**

![image](https://user-images.githubusercontent.com/37261132/124244458-28e31b80-db49-11eb-8e31-5bf1ece4bfae.png)

**Expected behavior:**

no error when running `ionic serve`

**Steps to reproduce:**

start the project as usual,
ionic start > ionic vue > project name
then i run the command `ionic serve`

**Comment by willmartindev** [comment]
Hi, thanks for the issue. Could you provide a link to a repo that reproduces this issue?

**Comment by xenom97** [comment]
> Hi, thanks for the issue. Could you provide a link to a repo that reproduces this issue?

Hi @willmartindev  I just created a new ionic vue project, and now this bug is gone (maybe fixed). I will close this issue. Thank you very much
