### ISSUE TITLE
Ion - Toast moving the the entire page up, if given a custom CSS with top: 7%

### ISSUE THREAD

**Issue by himanshusukhpal** [ionic-team/ionic-framework#23574]
[x] ionic 6 

giving a custom class to the ion-toast
.topAlertClass {
  top: 7% !important;
  text-align: center;
}
the class moves the entire page and the header gets disappeared
The same thing is working fine ionic 5

Ionic 6

![image](https://user-images.githubusercontent.com/10000755/124270261-9c8d2480-db59-11eb-9e84-eccfdd3ff8c5.png)

Ionic 5

![image](https://user-images.githubusercontent.com/10000755/124270123-66e83b80-db59-11eb-823e-05f82583667b.png)

**Comment by willmartindev** [comment]
Thanks for the issue! Could you reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by himanshusukhpal** [comment]
Yeah, I couldn't replicate the issue, the problem must be somewhere in my code, thanks for the help.

> Thanks for the issue! Could you reproduce this issue in an Ionic starter app and provide a link to the repo?
