### ISSUE TITLE
bug: date picker vibration issue with scroll 

### ISSUE THREAD

**Issue by amitkrgautm** [ionic-team/ionic-framework#23584]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Capacitor version:**
"@capacitor/cli": "3.0.1"

**Current behavior:**
ion-datetime gives vibration in android when user trying to change day, month and year in capacitor 3.

**Expected behavior:**
ion-datetime should works without vibration in android when user trying to change day, month and year in capacitor 3. OR add any property to off vibration.

**Steps to reproduce:**
Use ion-datetime using capacitor 3 and then try to change date in android.

**Related code:**
```
<ion-label>
        <ion-datetime placeholder="23-07-2020" [(ngModel)]="dateOfBirth" display-format="DD-MM-YYYY"></ion-datetime>
</ion-label>

In Typescript:-
     dateOfBirth: string = new Date().toISOString();
```

**Output screen:**
![image](https://user-images.githubusercontent.com/36753607/124645136-b196ea00-deb0-11eb-8c6f-782db41ca136.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.3
   Ionic Framework               : @ionic/angular 5.5.2
   @angular/cli                  : 12.0.1

Capacitor:

   Capacitor CLI   : 3.0.1
   @capacitor/core : 3.0.1

System:

   NodeJS : v14.15.4
   OS     : Andriod
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to merge this with our main datetime thread: https://github.com/ionic-team/ionic-framework/issues/16630

**Comment by lajith111** [comment]
@liamdebeasi  is there in option to temporary we can fix? please let us know?
