### ISSUE TITLE
feat: ios popover animation

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23587]
# Feature Request

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[X] **6.x**

**Describe the Feature Request**

Add the iOS default popover animation as shown in this video (https://www.youtube.com/watch?v=-hk4dLJ6OVk). Currently the Ionic Popover component does not have any animation for iOS

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to add this to our iOS 15 issue: https://github.com/ionic-team/ionic-framework/issues/23423

**Comment by BerkeAras** [comment]
@liamdebeasi Thats literally that I mentioned in #21859

**Comment by liamdebeasi** [comment]
Your comment in https://github.com/ionic-team/ionic-framework/issues/23423#issuecomment-856626104 was referring to the new context menu component. This feature is asking for just the new context menu animation and no new component:

> Consider adding context menu-like animation to popover

Just because something is added to the tracker does not mean it will be implemented. This is stated in the linked iOS 15 issue: 

> Note: This issue is being used to track all notable changes in iOS 15 that might impact Ionic Framework apps. It is not a list of confirmed changes coming to the Framework. We will be evaluating iOS 15 changes in the coming weeks to see which ones require Framework updates.

Since we added this we have considered adding the component versus adding just the animation. Our current thinking is that if we were to implement any of this, it would make sense as a separate component. However, since this component is very iOS specific we do not have any plans to implement at the moment.

**Comment by BerkeAras** [comment]
> Your comment in [#23423 (comment)](https://github.com/ionic-team/ionic-framework/issues/23423#issuecomment-856626104) was referring to the new context menu component. This feature is asking for just the new context menu animation and no new component:
> 
> > Consider adding context menu-like animation to popover
> 
> Just because something is added to the tracker does not mean it will be implemented. This is stated in the linked iOS 15 issue:
> 
> > Note: This issue is being used to track all notable changes in iOS 15 that might impact Ionic Framework apps. It is not a list of confirmed changes coming to the Framework. We will be evaluating iOS 15 changes in the coming weeks to see which ones require Framework updates.
> 
> Since we added this we have considered adding the component versus adding just the animation. Our current thinking is that if we were to implement any of this, it would make sense as a separate component. However, since this component is very iOS specific we do not have any plans to implement at the moment.

Thanks for your reply. What about a property to the current ion-popover? For example **isContextMenu(boolean)**

**Comment by liamdebeasi** [comment]
Apple considers popovers and context menus to be separate components, so we do not think it is a good idea to combine the two.

Popover: https://developer.apple.com/design/human-interface-guidelines/ios/views/popovers/
Context Menu: https://developer.apple.com/design/human-interface-guidelines/ios/controls/context-menus/

**Comment by BerkeAras** [comment]
If you have no plans to implement (creating a new component) this at the moment, wouldn't the easiest solution to just combine them?

**Comment by liamdebeasi** [comment]
Like I said, these are two fundamentally different components so we do not think it is a good idea to combine them.
