### ISSUE TITLE
bug: The parent pointer-events none  has no effect on the ion-button

### ISSUE THREAD

**Issue by 442623641** [ionic-team/ionic-framework#23588]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**
[ ] **6.x**

**Current behavior:**

The parent pointer-events none  has no effect on the ion-button
**Expected behavior:**

The state of the ion-button on the page is not clickable while the page is still animating
**Steps to reproduce:**

Quickly click the ion-button on the current page when the page animating to the next page, the state of the ion-button  is clickable
**Related code:**

```
<app-home style='pointer-events:none'>
<ion-content>
<ion-button>clickable?<ion-button>
</ion-content>
</app-home>
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.11
   @angular-devkit/build-angular : 12.1.1
   @angular-devkit/schematics    : 12.1.1
   @angular/cli                  : 12.1.1
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 2.4.7
   @capacitor/android : 2.4.7
   @capacitor/core    : 2.4.7
   @capacitor/ios     : 2.4.7

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.4.0) : 0.2.8

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 7.14.0
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@5.7.0-dev.202107081314.216a5a7
```

**Comment by 442623641** [comment]
> Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?
> 
> ```
> npm install @ionic/angular@5.7.0-dev.202107081314.216a5a7
> ```



> angular@5.7.0-dev.202107081314.216a5a7
fixed

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23589, and a fix will be available in an upcoming release of Ionic Framework.
