### ISSUE TITLE
bug:maxlength not working in ion-textarea in ionic 4  android 

### ISSUE THREAD

**Issue by achakra21** [ionic-team/ionic-framework#23593]
# Bug Report

**Ionic version:**

[x] **4.x**
[ ] **5.x**
[ ] **6.x**

**Current behavior:**
```
 <ion-textarea [(ngModel)]="text"
          id="text-area" type="tel" maxlength="350" > 
```
allowing more than 350 characters in android it's working as expected in ios
**Expected behavior:**
it should stop after input more than 350 chracters

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you testing this in a standalone Capacitor/Cordova app or in the Chrome browser on Android?

**Comment by achakra21** [comment]
@liamdebeasi i am using capacitor testing with Android with APK

**Comment by liamdebeasi** [comment]
Thanks. What version of the Chromium webview are you using? You can find this by logging `window.navigator.userAgent` in the DevTools Console.

Also does this issue reproduce on the latest release of Ionic Framework?

I am testing this on Chrome 91 with Framework v5 and I cannot reproduce the issue: https://codepen.io/liamdebeasi/pen/BaRzWMw

**Comment by achakra21** [comment]
I tested on **android 28 api level i.e Android 9** with latest ionic version **6.16.1** here is my chromium version when i log using `window.navigator.userAgent` 
```
 <ion-textarea  
          id="text-area" type="text" maxlength="10" > 
        </ion-textarea>
```

it's not working but its works with codepen browser also works with ios

**Comment by liamdebeasi** [comment]
`ion-textarea` uses the native `textarea` under the hood, so I would see if the bug reproduces with just a regular `textarea`:

```
<textarea maxlength="10"></textarea>
```

Your webview is running the equivalent of Chrome 69 which came out several years ago, so it is very outdated. I would try updating the webview if possible too.

**Comment by achakra21** [comment]
I am facing same issue on android 11 too i.e API level 30

**Comment by liamdebeasi** [comment]
Can you try what I recommended in https://github.com/ionic-team/ionic-framework/issues/23593#issuecomment-877186076?

**Comment by achakra21** [comment]
Yes it's not working I tried with android 9 old and also new android 11

**Comment by liamdebeasi** [comment]
What is the version of Chromium running on the device with Android 11?
