### ISSUE TITLE
feat: Ability to get current state of accordion

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23591]
# Feature Request

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[X] **6.x**

**Describe the Feature Request**

It would be great if we are able to get the current state of Accordion whether its expanded or not. For example if i use the accordion for the search filters as shown in the image, when i click on "Search Player" i should be able to close the accordion automatically. To do this I would get the current state of accordion in .ts file

<img width="753" alt="Screenshot 2021-07-08 at 9 55 43 PM" src="https://user-images.githubusercontent.com/61012396/124934469-504d5300-e037-11eb-8ffe-a6a6e9e93043.png">

**Related Code**

```ts
  searchPlayer() { this.accordion.toggle } for example
```

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. You can get the state of the accordion by checking the `value` property on `ion-accordion-group` which will tell you the accordion (or accordions if `multiple="true"`) that are expanded.

From there, if you wanted to open a different accordion or close the open accordion you would update the `value` property on `ion-accordion-group`. 

Can you give that a try in your app and let me know if it works?

**Comment by farisfaisalthena** [comment]
Seems the value returns as undefined
```ts
@ViewChild(IonAccordionGroup, { static: true }) content: IonAccordionGroup;

  click() {
    console.log(this.content.value)
  }
```

**Comment by liamdebeasi** [comment]
Can you send over a GitHub repo that shows the issue?

**Comment by farisfaisalthena** [comment]
https://github.com/farisfaisalthena/ionic-starter

**Comment by liamdebeasi** [comment]
The code is working as expected for me. When I click "Search Player" , the `searchPlayer` function logs `search` since that is the value of `ion-accordion-group`. Doing the following closes the accordion:

```js
this.accordion.value = undefined;
```

Does this work on your end?

**Comment by farisfaisalthena** [comment]
Yeah now it works dint know i could do `this.accordion.value = undefined;` thanks!

**Comment by liamdebeasi** [comment]
I am going to work on some docs for this since I don't think it's very clear in the documentation how to programmatically get/set the state currently. I'll keep this issue open but will close it out when those docs are merged.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I updated the accordion docs and added code examples for how to get/set the accordion state programmatically in https://github.com/ionic-team/ionic-framework/pull/23595. These docs should be available when Beta 2 ships.
