### ISSUE TITLE
feat: ion-refresher component threshold of createGesture() configurable via prop 

### ISSUE THREAD

**Issue by derbenoo** [ionic-team/ionic-framework#23594]
# Feature Request

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[ X ] **6.x**

**Describe the Feature Request**

The threshold of the "refresher" gesture is statically set to "20". It would be awesome to make this configurable via an input to the component. I tried building a custom content component for the ion-refresher and had an iOS overscroll/ rubberband jittering bug because the animation starts after 20px instead of immediately (therefore, the iOS overscroll starts, then gets aborted when the animation starts).

Thanks in advance :pray: 

https://github.com/ionic-team/ionic-framework/blob/39315bc857b850347dca386776665e21c9742cad/core/src/components/refresher/refresher.tsx#L428

**Describe Preferred Solution**

Add an input to the component to make the threshold configurable by the consumer.

**Describe Alternatives**

Tried styling the existing ion-refresher-content component but need to provide a custom SVG and the behavior differs from the desired behavior.

**Related Code**

**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo that shows what you are trying to do/any issues surrounding the current configuration?
