### ISSUE TITLE
bug: Ion refresher icon showing when scrolling down page

### ISSUE THREAD

**Issue by fbcsa** [ionic-team/ionic-framework#23597]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**
[ ] **6.x**

**Current behavior:**

Have a page with an ion-refresher and multiple ion-items. When the ion-refresher is pulling down, it loads data from an api into an array (we don´t empty the array). That works fine.

When we have too much items, we have to scroll down the screen, so we pull up to scroll down. In that moment the ion-refresh icon appears (only appears, the (ionRefresh) function is not called), the  and stays there until we launch the refresher again by pulling down (the (ionRefresh) function executes as expected).

Been tweaking the refresher with pullMax and pullMin but doesn´t change anything on the behaviour.

**Expected behavior:**

The icon should not appear when scrolling down on the screen.

**Steps to reproduce:**

[Video](https://drive.google.com/file/d/1Pvi2BddTIhRZFPnfSdcD6y8_KSbOj5GJ/view?usp=sharing)

**Related code:**

```
<ion-content class="tieneqr">
  <ion-refresher (ionRefresh)="doRefresh($event)" slot="fixed">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
  <ion-item detail="false" *ngFor="let objInstalacion of instalaciones" class="instalacion ion-margin" lines="none">
    <div class="info">
      <div class="tituloInstalacion">
        <div class="iconoYnombre">
          <ion-icon name="home" class="iconoInstalacion"></ion-icon>
          <ion-label color="primary" class="nombreInstalacion">{{objInstalacion.datos.Nombre}}</ion-label>
        </div>
        <ion-label color="primary" class="zonas">{{obtenerTextoZonas(objInstalacion.nzonas)}}</ion-label>
      </div>    
    </div>
  </ion-item>
</ion-content>
```
Code of the refresh function:
```
  doRefresh(event) {
    this.loadInstalations();
    event.target.complete();
  }

  loadInstalations() {

    this.gws.obtenerInstalaciones()
    .pipe(finalize(()=>{
      this.loadingCrtl.dismiss();
    }))
    .subscribe(obtainedInfo => {
      this.instalaciones = obtainedInfo;
    });
  }

```
**Other information:**

Tried in chrome latests version and Android.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.13.1 (C:\programas\nvm\v12.16.1\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.4
   @angular-devkit/build-angular : 0.1102.8
   @angular-devkit/schematics    : 11.2.8
   @angular/cli                  : 11.2.8
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 3.0.1
   @capacitor/core : 3.0.1

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This bug was fixed in Ionic Framework v5.6.7. Please update to the latest version of Ionic Framework to receive this fix:

```
npm install @ionic/angular@latest
```
