### ISSUE TITLE
bug: CSS Shadow part not work on device

### ISSUE THREAD

**Issue by mastercodingbear** [ionic-team/ionic-framework#23609]
# Bug Report

**Ionic version:**
[ ] **4.x**
[ ] **5.x**
[X ] **6.x**

```
Ionic:

   Ionic CLI : 6.16.3

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.16.1
   npm    : 6.14.12
   OS     : Windows 10
```
Is it Ionic v6? 
in package.json version is ``"@ionic/angular": "^5.5.2"``

**Current behavior:**
CSS shadow part works well on the browser but it doesn't work on the device.
Here is the code in ``global.scss``.
```
ion-content::part(background) {
    border-top-left-radius: 50px;
    border-top-right-radius: 50px;
}
ion-content::part(scroll) {
  margin: 40px 20px 0px !important;
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. What device are you testing this on? Shadow Parts are only supported on Chrome 73+ and iOS 13.4+: https://caniuse.com/mdn-css_selectors_part

**Comment by mastercodingbear** [comment]
I'm testing on Android(Pixel 2 API 28) as a tutorial but It doesn't work.
It also seems like doesn't work the first time.
Does this happen because of `capacitor live reload`?(not work at the first time)
![Screenshot 2021-07-12 235543](https://user-images.githubusercontent.com/84164835/125348254-09c86300-e36d-11eb-9ff9-c1217991c1f7.jpg)
**Browser**
![Screenshot 2021-07-12 235607](https://user-images.githubusercontent.com/84164835/125348261-0b922680-e36d-11eb-84ff-b67985a5882d.jpg)
**Android emulator**

**Comment by liamdebeasi** [comment]
What webview version are you using on the Pixel 2? You can find this by logging `window.navigator.userAgent` in the dev tools console.

**Comment by mastercodingbear** [comment]
"Mozilla/5.0 (Linux; Android 8.0; Pixel 2 Build/OPD3.170816.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Mobile Safari/537.36"

**Comment by liamdebeasi** [comment]
Thanks! You are using Chrome 91 which should support shadow parts. Can you reproduce this issue in an Ionic starter app and provide a link to the repo? My initial thought is maybe some styles are not being loaded properly.

**Comment by mastercodingbear** [comment]
Thank you your support.
https://github.com/mastercodingbear/IonicTest

**Comment by mastercodingbear** [comment]
It works on Pixel 3(API 30). Maybe version issue.
