### ISSUE TITLE
bug: ion-datetime not listing all possible years (v6)

### ISSUE THREAD

**Issue by martinmitteregger** [ionic-team/ionic-framework#23615]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x ] **6.x**

**Current behavior:**

Datepicker shows only 40 years when listing all possible years. Initially 2041 to 2001 are listed even though max is set to today and min to today minus 100 years (or 1900 which changes nothing).

**Expected behavior:**

List all years between min and max. Years after max should not be displayed in my opinion.

**Related code:**
```
<ion-datetime
    presentation="date"
    [min]="1900"
    [max]="2022"></ion-datetime>
```

![image](https://user-images.githubusercontent.com/15977182/125459065-b4dd45c9-7746-4b8f-96e8-e6eb146e2fc4.png)
![image](https://user-images.githubusercontent.com/15977182/125459138-67b19fd5-a335-4a96-8f2c-923d7b0d8f97.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\xxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.1
   @angular-devkit/build-angular : 12.0.5
   @angular-devkit/schematics    : 12.1.0
   @angular/cli                  : 12.0.5
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI   : 3.0.2
   @capacitor/core : 3.0.2

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : 1.4.0

System:

   NodeJS : v16.3.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.17.0
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. There are a couple things go on here:

1. When using max/min dates, the out of bound years are shown as disabled buttons in MD mode.

The spec does not really define what to do here, but the Flutter implementation is to show out of bound dates: https://material.io/components/date-pickers/flutter#date-pickers

However, looking at this again I don't really see the value in showing the out of bound years, especially where datetime in `ios` mode hides them. I can change this so the behavior is consistent.

2. By default, the datetime picker will only show a total of 40 years for performance reasons. The 40 value here is a bit arbitrary, and I am open to increasing that. That being said, if you explicitly set the max/min values, the years rendered should match those bounds. Datetime does not currently do this, so this is a bug we should fix.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23616, and a fix will be available in v6 beta 2.
