### ISSUE TITLE
bug: Android - WebContentsDelegate::CheckMediaAccessPermission: Not supported

### ISSUE THREAD

**Issue by abdulajet** [ionic-team/ionic-framework#23617]
# Bug Report

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.x**

**Current behavior:**

I am trying to use WebRTC via https://www.npmjs.com/package/@opentok/client in an ionic project but I cannot seem to get it working on Android, whereas iOS works perfectly fine. When I check the android logcat i have the error `WebContentsDelegate::CheckMediaAccessPermission: Not supported`. Which is odd because I have used other WebRTC libraries with ionic and android before. 

**Expected behavior:**

The Camera and microphone to work and start a video call. 

**Steps to reproduce:**

https://github.com/abdulajet/ionic-test
Ionic serve 
proxy your local port via localtunnel/ngrok to get a https url
ionic capacitor run android -l --external --livereload-url=HTTPS_URL_HERE
Try use https://www.npmjs.com/package/@opentok/client to make a video call 

**Related code:**

Here is a GitHub repo https://github.com/abdulajet/ionic-test/blob/main/src/pages/Home.tsx
If you would like to test it with creds you can email me for some. 

Here is the android manifest file
```
<!-- Video -->
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.VIDEO_CAPTURE" />
<uses-feature android:name="android.hardware.camera" android:required="true"/>
<!-- Audio -->
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
<uses-permission android:name="android.permission.AUDIO_CAPTURE" />
<uses-feature android:name="android.hardware.microphone" android:required="true"/>
```

**Other information:**

Some people have had some luck changing permissions on the web view but I don't think I can do this with ionic? https://stackoverflow.com/a/38918764

Is it also possible that the ionic app isn't being served over HTTPS which is usually the cause for these kinds of issues on iOS?

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.16.3 (/Users/aajetunmobi/.nvm/versions/node/v12.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.9

Capacitor:

   Capacitor CLI      : 3.0.1
   @capacitor/android : 3.0.1
   @capacitor/core    : 3.0.1
   @capacitor/ios     : 3.0.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v12.18.2 (/Users/aajetunmobi/.nvm/versions/node/v12.18.2/bin/node)
   npm    : 7.9.0
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework does not manage the WebRTC plugin and has no control over the WebRTC implementation on Android/iOS. Since this is more of a support question I encourage you to ask this on the Ionic Forums: http://forum.ionicframework.com/
