### ISSUE TITLE
How to change fab close button icon as text in latest ionic version

### ISSUE THREAD

**Issue by ipehimanshu** [ionic-team/ionic-framework#23626]
Hello 

How to change fab close button icon as text in latest ionic version?

As we see it always replaced any text given for label when fab button open.

Thanks

**Comment by herobarua** [comment]
Here inside action Button we added some text, but when it exapand it chnage icon and hide text as well, is there anyway to keep text remain and chnage only icon?

![image](https://user-images.githubusercontent.com/1532317/125629486-62b70ccf-d855-42ab-9378-babbe1b85db9.png)
