### ISSUE TITLE
feat: collapsible large titles for ion-header

### ISSUE THREAD

**Issue by zhuyifang** [ionic-team/ionic-framework#23642]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

When scrolling the page, the effect of color transition is achieved by changing the opacity of .toolbar-background

### Describe the Use Case

But if you can change the background color transparency of .toolbar-background, the whole transition effect will be more graceful

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe the problem you are running into? Changing the opacity on the background color should be no different than changing the opacity of the element in terms of what you see in your app.

**Comment by zhuyifang** [comment]
Yes, I agree with you, it seems that changing the transparency of .toolbar-background cannot solve this problem.
I checked it again just now and found that the background color was also set in .header-collapse-condense-inactive.

Therefore, in my experiment, with the .toolbar-background transparency and background color disabled, changing the transparency of the .header-collapse-condense-inactive background color can achieve the desired effect.

The effect we want is: For example, in the 2 picture, it should show: a semi-transparent toolbar, you can see the content covered by the toolbar (such as an avatar)
<img width="339" alt="WX20210727-092038@2x" src="https://user-images.githubusercontent.com/16346219/127079807-4ca978ba-8ca7-43da-9e3e-ff07b711164a.png">
<img width="332" alt="WX20210727-091635@2x" src="https://user-images.githubusercontent.com/16346219/127079820-ad6dbd19-2271-4faf-b2ba-f0c60cb3d1c1.png">
<img width="335" alt="WX20210727-092011@2x" src="https://user-images.githubusercontent.com/16346219/127079817-f31f6230-97a3-4d29-ae78-6f69a8a2fb21.png">

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you please clarify what your feature request is?

**Comment by zhuyifang** [comment]
Thank you very much for your reply!
I have found the problem, I can achieve the effect I want through CSS and other things. It seems that this is not a good suggestion
