### ISSUE TITLE
bug: Uncaught RangeError: Maximum call stack size exceeded. When adding an overlay on top of a modal

### ISSUE THREAD

**Issue by AVatch** [ionic-team/ionic-framework#23655]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

In a modal overlay I am calling an emoji picker (https://github.com/joeattardi/emoji-button) which when it renders causes the following error. This was not being thrown on the 5.x version of ionic. 

<img width="621" alt="Screen Shot 2021-07-18 at 6 27 15 PM" src="https://user-images.githubusercontent.com/1807958/126084002-32be9fb0-a790-4753-8ee0-318c5ea8dbcd.png">

### Expected Behavior

I should be able to stack overlays without issue. 

### Steps to Reproduce

Add a button which triggers calls https://github.com/joeattardi/emoji-button in a Modal.  

### Code Reproduction URL

https://github.com/AVatch/broken-focus

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.1
   @angular-devkit/build-angular : 12.1.2
   @angular-devkit/schematics    : 12.1.2
   @angular/cli                  : 12.1.2
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.1
   @capacitor/android : not installed
   @capacitor/core    : 3.1.1
   @capacitor/ios     : 3.1.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v16.0.0 (/usr/local/bin/node)
   npm    : 7.16.0
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by AVatch** [comment]
Sure @liamdebeasi 

You can see the exception be thrown in the below repo...
https://github.com/AVatch/broken-focus

If you downgrade to ionic 5.x it works with no exception. I also added the emoji button to the home page and it works fine, this is only thrown when this is called from an overlay.

**Comment by liamdebeasi** [comment]
Apologies for the delay! Which browser are you testing this in? I tried opening the emoji picker from the modal in Chrome 92, and did not receive a `RangeError`.
