### ISSUE TITLE
bug: Incorrect alignment of ion-select selection using floating labels

### ISSUE THREAD

**Issue by martinmitteregger** [ionic-team/ionic-framework#23657]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using an ion-select with `fill=outline`  and a floating label the initial label is positioned right but after selecting a value the alignment of the selected value is false.
![image](https://user-images.githubusercontent.com/15977182/126315973-bacffc07-8bfd-41e1-bebe-5f35df0bd1f1.png)

### Expected Behavior

Selected value is aligned like other input values (see e.g. birthdate).

### Steps to Reproduce

```
<ion-item fill="outline" class="ion-margin-top">
    <ion-label position="floating">Gender *</ion-label>
    <ion-select formControlName="gender">
        <ion-select-option [value]="gender.FEMALE">Female</ion-select-option>
        <ion-select-option [value]="gender.MALE">Male</ion-select-option>
        <ion-select-option [value]="gender.NON_BINARY">Non Binary</ion-select-option>
    </ion-select>
</ion-item>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\xxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.1
   @angular-devkit/build-angular : 12.0.5
   @angular-devkit/schematics    : 12.1.0
   @angular/cli                  : 12.0.5
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI   : 3.0.2
   @capacitor/core : 3.0.2

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : 1.4.0

System:

   NodeJS : v16.3.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.17.0
   OS     : Windows 10

### Additional Information

According to the [material design guidelines](https://material.io/components/menus#exposed-dropdown-menu) it should look like in the image below.
![image](https://user-images.githubusercontent.com/15977182/126316064-b79fd890-b629-4091-b585-9c02500a4dd2.png)

**Comment by liamdebeasi** [comment]
Thanks! This will be fixed in https://github.com/ionic-team/ionic-framework/pull/23474.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This was resolved via https://github.com/ionic-team/ionic-framework/pull/23474, and this update will be available in Ionic Framework v6 beta 2.
