### ISSUE TITLE
feat: Override option to force 12-hour/24-hour format in ion-datetime

### ISSUE THREAD

**Issue by bchehraz** [ionic-team/ionic-framework#23661]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The feature would allow for `ion-datetime` (v6) to take in a property to force its time display format, to either 12-hour or 24-hour time, regardless of the user's locale/region. 

### Describe the Use Case

Currently developing an app for businesses to track employee time and there's a client-level preference to show all times within the app in 12-hour or 24-hour format. Some clients need their times specifically in 24-hour time, such as hospitals.

### Describe Preferred Solution

- Add a "timeFormat" property which by default is null or undefined (listens to locale/region)
- Has optional "12h" and "24h" as input to override locale and force one format or the other.

### Describe Alternatives

An alternative could be bringing back `displayFormat` as was implemented in Ionic <= 5 for `ion-datetime` which took in  values, such as `"H:mm"`, `"h:mm A"`, etc. Perhaps renaming to `timeFormat` to be more specific.

### Related Code

```
<ion-datetime
    ...
    timeFormat="24h"
>
</ion-datetime>
```

or the alternative

```
<ion-datetime
    ...
    timeFormat="H:mm"
>
</ion-datetime>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23686, and a fix will be available in an upcoming release of Ionic Framework.
