### ISSUE TITLE
feat: translate backButtonText in Ionic v6

### ISSUE THREAD

**Issue by NLueg** [ionic-team/ionic-framework#23672]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Currently, I translate the Back button text in my angular-based ionic app with `config.set(...)` like this:

```
      if (this.deviceService.isIos) {
        this.translate
          .get("global.backButtonText")
          .pipe(first())
          .subscribe((text) => {
            this.config.set("backButtonText", text);
          });
      }
```

This is not possible with Ionic v6  but this is very important in my opinion.

### Expected Behavior

It should be possible to set the back button text based on the current language

### Steps to Reproduce

The `config.set` method does not exist anymore and inside the docs (https://ionicframework.com/docs/angular/config) is no description on how to implement such a behavior in Ionic v6.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\lueg\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0-dev.202106282030.9f3b1d9
   @angular-devkit/build-angular : 12.1.3
   @angular-devkit/schematics    : 12.1.3
   @angular/cli                  : 12.1.3
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.2
   @capacitor/ios     : 3.1.2

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v14.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.11
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. We typically leave translation implementation up to the developer as translation use cases vary from app to app. That being said, you can absolutely set custom back button text. The `config.set` method was removed in v6, but everything you did with `config.set` you can do in one of two ways:

1. Set the `backButtonText` value in your app config. How to do this is detailed in https://ionicframework.com/docs/angular/config. Note that the app config is set at runtime, so it is not reactive.

2. Set the `text` property on each `ion-back-button` instance: https://ionicframework.com/docs/api/back-button#properties. This property is reactive, so you could change this property if a user changes the language more than once.

I am going to close this as the functionality requested is already implemented in Ionic Framework.
