### ISSUE TITLE
bug: IonBackButton can't show custom icon

### ISSUE THREAD

**Issue by shikelong** [ionic-team/ionic-framework#23673]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

![image](https://user-images.githubusercontent.com/4499997/126596537-ea9ebe88-6dc3-4912-bf95-727f77cae74d.png)

IonicBackButton icon props not work. 

![image](https://user-images.githubusercontent.com/4499997/126596943-933ce91d-7d13-4e21-867d-086ee7cad0d9.png)

also not work if icon is ionic icon.
```javascript
<IonBackButton
              defaultHref="/"
              icon="chevron-back-outline"
              color="danger"
            />
```

v5&v6 both has this issue.

### Expected Behavior

Should show custom icon.

### Steps to Reproduce

create a new react/typescript based ionic v5/v6 project. then paste sample code.

**Comment by liamdebeasi** [comment]
Thanks for the issue. With Ionic React, icons are not globally registered on application startup so you need to import the icon you want to use:

```js
import { chevronBackOutline } from 'ionicons/icons';

...

<IonBackButton icon={chevronBackOutline} />
```

For the custom URL, make sure that your path is correct. If you are placing the SVG in the `assets` directory, the path should look like `./assets/back.svg`.

Can you try those and let me know if it resolves the issue? If it does not, please reproduce the issue in an Ionic starter app and provide a link to the repo.

**Comment by shikelong** [comment]
@liamdebeasi Thank you! 
The issue was solved after I import icon from 'ionicons/icons'.
