### ISSUE TITLE
bug: double tapping ion back button still causes app to go back two pages

### ISSUE THREAD

**Issue by andrewsetterfield** [ionic-team/ionic-framework#23678]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When navigating to a new page containing a back button using <ion-back-button>, if I immediately double click the back button it navigates me back to the previous screen, then navigates me back that that pages previous screen. Note that in my application this first screen does not have a back button for me to have mis-clicked.

### Expected Behavior

only navigate back one page

### Steps to Reproduce

multiple click of back button.

### Ionic Info

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.6.12
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   capacitor (Capacitor CLI) : 2.4.2
   @capacitor/core           : 2.4.7

Cordova:

   cordova (Cordova CLI) : 9.0.3 (cordova-lib@9.0.2)
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v14.17.0 (/Users/andrew/.nvm/versions/node/v14.17.0/bin/node)
   npm        : 6.14.13
   OS         : macOS Big Sur
   Xcode      : Xcode 12.5 Build version 12E262

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
