### ISSUE TITLE
bug: opening item-sliding while another is open requires multiple swipes

### ISSUE THREAD

**Issue by Sitronik** [ionic-team/ionic-framework#23682]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When I swipe on the first element to open the buttons, the buttons open immediately, if I swipe on another element, the buttons will not open, they will open only if I swipe a second time

### Expected Behavior

After swiping on the element, the buttons should be displayed immediately, and if you swipe on the next element, the buttons should be displayed immediately and not the second time.

Previously, everything worked correctly for in version 3 of ionic:
https://ionicframework.com/docs/v3/api/components/item/ItemSliding/

### Steps to Reproduce

Open it:
https://codepen.io/sitronik/pen/PomOrYx

Then:
Make swipe by elements

**Comment by liamdebeasi** [comment]
Thanks for the issue. I will take a look at the PR soon. It looks like we have an existing issue open, so I am going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/21579.
