### ISSUE TITLE
bug: @ionic/angular - platform.is() is missing 'capacitor' in method documentation

### ISSUE THREAD

**Issue by meck93** [ionic-team/ionic-framework#23687]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

```
  /**
   * ```
   *
   * | Platform Name   | Description                        |
   * |-----------------|------------------------------------|
   * | android         | on a device running Android.       |
   * | cordova         | on a device running Cordova.       |
   * | ios             | on a device running iOS.           |
   * ....
   *
   */
  is(platformName: Platforms): boolean {
    return isPlatform(this.win, platformName);
  }
```

The string 'capacitor' existing as a platform and in the type definition of `Platforms` but it is missing in the method documentation. 

### Expected Behavior

```
   * ```
   *
   * | Platform Name   | Description                        |
   * |-----------------|------------------------------------|
   * | android         | on a device running Android.       |
   * | capacitor       | on a device running Capacitor.     |
   * | cordova         | on a device running Cordova.       |
   * | ios             | on a device running iOS.           |
   * ...
   *
   */
  is(platformName: Platforms): boolean {
    return isPlatform(this.win, platformName);
  }
```

The string 'capacitor' is added to the method documentation. 

### Steps to Reproduce

Check the method documentation of `@ionic/angular` v5.6.12.

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/23688. Thank you!
