### ISSUE TITLE
bug: menu hamburger crash app

### ISSUE THREAD

**Issue by kiozix** [ionic-team/ionic-framework#23684]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

i start my app on ios i click on the menu but the app stop working check this videos for more for unbug the app i need to slide from the right and click home and app working again

https://youtu.be/-uDfFuyBq9A  (on 0.04 check the button it flashes when I click on it)

### Expected Behavior

the menu open without crash 

### Steps to Reproduce

I cannot provide you with this information

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\PC01\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.3
   @angular-devkit/build-angular : 0.1102.5
   @angular-devkit/schematics    : 11.2.5
   @angular/cli                  : 11.2.5
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI      : 2.4.7
   @capacitor/android : 2.4.7
   @capacitor/core    : 2.4.7
   @capacitor/ios     : 2.4.7

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by xsh2047** [comment]
Yo Kiozik, Think it's related to this?

https://github.com/ionic-team/ionic-framework/issues/17948

**Comment by kiozix** [comment]
hello nop if i wait 1 min after app open same probleme
