### ISSUE TITLE
bug: datetime should change height based on presentation type

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23690]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

#### I'm using 6.0.0-beta.2

`datetime.ios.scss` sets a `min-height: 300px` which causes the date time to have a wrong height when using `presentation="time"`

![Bildschirmfoto 2021-07-26 um 14 38 29](https://user-images.githubusercontent.com/20899975/126989962-91ffb512-6ddb-4ae2-8f96-56126c52c12a.png)

### Expected Behavior

The Date-time should have the correct height

### Steps to Reproduce

- Create a new App with Beta 2
- Show a Datetime like:

```
<ion-datetime presentation="time" size="cover"></ion-datetime>
```

**Comment by willmartindev** [comment]
Just merged in a fix for this that will be available in the next beta release of Framework v6. Thanks for the awesome work @EinfachHans :)
