### ISSUE TITLE
bug: ion-modal stacking with presenting-element option not working

### ISSUE THREAD

**Issue by tho-masn** [ionic-team/ionic-framework#23698]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Using the `presenting-element` option of the `ion-modal` component doesn't visually stack the modal like in v5. It seems like the option gets ignored completely.

### Expected Behavior

Here you can see the behaviour of v5 vs v6:

https://user-images.githubusercontent.com/23264228/127309509-ffa1569e-4251-48d0-97ba-70678755c5cc.mov

https://user-images.githubusercontent.com/23264228/127309518-0f04c2d2-454c-4aaa-bfba-87e6e02c4df8.mov

### Steps to Reproduce

- Add the ion-modal component with the presenting-element option
- Use the ion-router-outlet component as presenting-element
- Check the modal animation

### Code Reproduction URL

https://github.com/tho-masn/ionic-issues/tree/v6-ion-modal-stacking

**Comment by NunoSav** [comment]
I've experienced the same behaviour.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@6.0.0-dev.202108111541.83d9799 @ionic/vue-router@6.0.0-dev.202108111541.83d9799
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23761, and a fix will be available in an upcoming release of Ionic Framework.

Please feel free to continue testing, and let me know if you run into any issues!

**Comment by tho-masn** [comment]
Sorry, a bit late, but now it works. Thanks!
