### ISSUE TITLE
bug: the hardware back button closes the application

### ISSUE THREAD

**Issue by ima-antonio** [ionic-team/ionic-framework#23706]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

My ionic application closes whenever I click the device's back button.

### Expected Behavior

    
I want to activate this function. 
this.platform.backButton.subscribe(() =>{
      console.log("Ok");
});

But it seems to be ignored. because the console does not return what is expected.

### Steps to Reproduce

I've been on this project for some time. But when I upgraded my capacitor, this problem came with it.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.14.1 (C:\Users\IVO MARTINS\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.6
   @angular-devkit/build-angular : 0.1102.12
   @angular-devkit/schematics    : 11.2.12
   @angular/cli                  : 11.2.12
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v14.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
