### ISSUE TITLE
bug: ngIf does not get refreshed when the variable changes in app.component.html

### ISSUE THREAD

**Issue by danchaseCTS** [ionic-team/ionic-framework#23708]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I attempted to hide the side-menu when the user was not logged in, by subscribing to the user service from app.component.ts. I have a variable called currentUser, which gets assigned:

```
  ngOnInit() {
    this.userService.currentUser.subscribe(user => {
      if (user != null) {
      this.currentUser = user;
      } else this.currentUser = null;
  });
  } 
```

I attempted to wrap the ion-menu component in a ng-container, and display the value of currentUser right above it:

```
<ion-app>
  <ion-split-pane contentId="main-content">
    User = {{ currentUser | json }}
    <ng-container *ngIf="currentUser">

    <ion-menu contentId="main-content" type="overlay">

```

The menu is invisible, as expected, but when I login, the sidebar doesn't update it's ngIf even though currentUser gets updated and is properly displayed right above it. I've also tried currentUser != null and got the same result. it's almost like the ngIf is just not being re-evaluated, even though interpolation is working. If I refresh the page, the sidebar then shows itself.

Also, I put a breakpoint and confirmed the subscription event is being hit, and currentUser is being assigned, as I can also see from the rendering of the user above where the sidebar should have appeared.

Interestingly enough, I have an ngIf that works perfectly further down the page that is inside of <ion-note>:

```
  <ion-note>
         <ng-container *ngIf="currentUser != null">
              {{ (currentUser != null ? currentUser.username : '')  }} {{ (currentUser != null ? '(' + currentUser.role + ')' : '') }}
                <a [routerLink]="" href="#" (click)="onLogoutClick()">Logout</a>
          </ng-container>
  </ion-note>

```

Does something in ion-split-pane that prevents the ngIf, that would allow it in ion-note or anywhere else seemingly in the program?  is this a bug in ionic, or angular even?

### Expected Behavior

The ngIf re-evaluates in the sidebar, without refreshing the page.

### Steps to Reproduce

You should be able to reproduce this by using any ngIf in app.component.ts.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
