### ISSUE TITLE
bug: Upgrading from @Ionic/React 5.3.2 to 5.6.12 breaks my IonMenu

### ISSUE THREAD

**Issue by crates** [ionic-team/ionic-framework#23702]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I have no problems with my menus on the previous version of Ionic React (5.3.2).

I recently upgraded to 5.6.12 to make use of the `useIonModal` hook, which was cool.
The only 3 package upgrades entailed were:
* `@ionic/react` from v5.3.2 to v5.6.12
* `@ionic/react-router` from v5.3.2 to v5.6.12
* `history` from v4.10.1 to v5.0.0

Simply upgrading the version has caused my main site navigation menu to break.
I can open the menu just fine, but now, the buttons are no longer clickable. 
In fact, hovering over the buttons won't trigger the hover state either, on the new version of Ionic React.

When I right-click and "inspect element" on the button, I'm not getting focus on the `ion-button`.
Instead, the element focused is an item in the shadow root of `ion-menu` with the class `menu-inner`.
As the mouse events are targeting that div instead of the buttons inside, the buttons aren't clickable.

Here's the code that I'm using to invoke my main navigation menu, which mirrors the official docs:

```
export interface MainNavMenuProps extends UiProps {
  options: string[];
}
const MainNavMenu = (p: MainNavMenuProps) => {
  const mainNavOptions = H.filterViewsByMenuIds(p.options, [V.MN_MAIN_NAV_TRAY]);
  const mainNavLinks = [];

  for (const k of Object.keys(mainNavOptions)) {
    const view: V.VIEW = mainNavOptions[k];

    mainNavLinks.push(<IonItem
      button={true}
      key={R.getLinkTestId(view.name)}
      data-testid={R.getLinkTestId(view.name) + '-menu-item'}
    ><IonButton
      className="main-nav-button button-no-style"
      href={view.route}
      expand="block"
      key={R.getLinkTestId(view.name) + '-anchor'}
      data-testid={R.getLinkTestId(view.name)}
    >{view.menuTitle}</IonButton></IonItem>);
  }

  return <IonList>{mainNavLinks}</IonList>;
};

export const MainNavOptions: React.FC<MainNavMenuProps> = (p: MainNavMenuProps) => {
  return <IonMenu
    side="start"
    menuId="main-nav"
    contentId="main-nav"
  >
    <IonHeader>
      <IonToolbar
        color="primary"
        data-testid="main-nav-toolbar">
        <IonTitle data-testid="main-nav-title"
          >VieDay Menu</IonTitle>
      </IonToolbar>
    </IonHeader>

    <IonContent id="main-nav">
      <MainNavMenu {...p} />
    </IonContent>
  </IonMenu>
};
```

### Expected Behavior

Our menu buttons work fine in the older version of Ionic. You can click on them normally, hover over them and get a hover state, or right-click and "Inspect Element" to find the `ion-button` reference in the Chrome Inspector. This is the same behavior that I would expect in the newer version.

### Steps to Reproduce

Presumably, you will find this behavior happening by testing the basic menu functionality in the latest version of Ionic React. We're not doing anything terribly non-standard with our approach, so I would expect anyone to be facing the same problem we're facing. Our Node version is currently 12.16.1, but I also tested this with Node v14.x on another computer, and found the same problem occurring.

### Ionic Info

Ionic:
   Ionic CLI       : 5.4.16 (/Users/crates/.npm/_npx/44395/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 5.6.12 (/Users/crates/Code/crates-media/node_modules/@ionic/react)

Capacitor:
   Capacitor CLI   : 2.4.0
   @capacitor/core : 2.4.0 (/Users/crates/Code/crates-media/node_modules/@capacitor/core)

Utility:
   cordova-res : not installed
   native-run  : not installed

System:
   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 7.10.0
   OS     : macOS Mojave (10.14.6 but also tested/repro'd on Big Sur)

**Comment by crates** [comment]
I _really_ need this fixed ASAP as I'm teaching a free programming class 3 nights a week where we use Ionic 5, and this bug has us totally blocked. I'm trying to evangelize your framework on live streams to YouTube and Facebook as we build this app, but as long as this is happening, we're pretty jammed up and can't proceed easily.

I put together a video to demonstrate precisely what broke between version 5.3.2 and the latest ones:
[youtu.be/mGr1tqrRA3U](https://youtu.be/mGr1tqrRA3U)

I hope that helps to diagnose and resolve this problem in an expeditious fashion!

**Comment by crates** [comment]
Hello again, friends. I couldn't wait for anyone to fix this, so I've tracked it down myself.

The issue in question is caused by an inherited CSS property coming from `.menu-content-open` in your core scss.

The parent has a property (which must've been added AFTER version 5.3.2 where this wasn't a problem:
`pointer-events: none;` 

Uh-oh, spaghetti-os.

I was able to work around this issue for the time being by adding a CSS rule to my SCSS for my menu treatment:
`pointer-events: auto !important;`

However, this is an ugly hack and I would prefer not to use it. I'll see if I can track down the actual source of the bug.

**Comment by crates** [comment]
According to this post (which helped me diagnose the issue) this has been problematic for at least 2 years now:
https://forum.ionicframework.com/t/ion-items-not-clickable-as-button-in-content-of-ion-menu/179115/5

That's a little embarrassing for your framework, honestly, and makes me question whether I should keep promoting it.
We're talking about a major, game-breaking, show-stopping bug that is clearly affecting quite a few people now.

Moreover, it's just ONE LINE of CSS that needs to get fixed to make the problem go away, universally, and forever.

Whatever the change was that broke this, it happened some time after you released version 5.3.2 on August 27, 2020.

You should be able to fix it by adding a default property to any interactable items within menus:
```
.menu-content-open {
  .hydrated {
    &.ion-activatable, &.ion-focusable {
      pointer-events: auto;
    }
  }
}
```

Let me know if you need a PR for this. It's a very simple change to instrument and should take 2 seconds.

And for the love of god, please run more extensive tests around your version updates so I don't lose my mind.

**Comment by willmartindev** [comment]
Hi Crates, first I want to acknowledge your frustration--you’re helping evangelize software that seemed to introduce a bug, and that sucks. Second, one huge help would be to add a reproduction case for us; I am unable to reproduce this in a starter Ionic React app, could you link one?

Finally, thank you for the patience while we figure out the problem here. We understand you may feel stuck and we don’t want that.

**Comment by crates** [comment]
@willmartindev - I wish I could reproduce it directly, except that I don't know what the fundamental difference is between my code and anyone else's that is causing this problem. I already tried reproducing it with your app starter tool and couldn't produce the same result; however, I can consistently reproduce it in my own app simply by downgrading the version number.

It's definitely a bug and not just my implementation, though - searching online I found dozens of variants of the same question/problem, and in the Ionic Forum post I linked above, there's half a dozen people in that post alone corroborating the bug in different versions of Ionic. I also believe this is happening not just for React, but Angular and Vue... but I don't know the specifics of what in your extraordinarily-complex framework is the culprit.

All i can say is, I have a working fix for you that definitely resolves the bug and doesn't seem to have any negative ramifications, which I have also posted in the comments above. I'd love to do more for you on this but I just don't know how. I copied my menu example basically verbatim from your documentation, with the sole exception that I'm mapping over an array instead of coding every list item manually.

**Comment by willmartindev** [comment]
Hey again @crates - would you mind posting a link to the GitHub repo your app is in?

**Comment by crates** [comment]
@willmartindev - It's a private repo, but I'm happy to add you to it. I'll do that now so you can experiment with it.

Here's that repository: https://github.com/crates/crates-media/

The branch I'd recommend using for test purposes is: VIE-9_Checklist

I tremendously appreciate your inquiry into this issue. Thanks very much for having a look.

**Comment by crates** [comment]
@willmartindev ~
It's also worth noting that my branch (mentioned above) already has the fix I mentioned earlier in place. 

If you want to reproduce the issue, you'll need to remove line 32 from the following file:
https://github.com/crates/crates-media/blob/VIE-9_Checklist/libs/ui/src/lib/ui.scss

(That's the line that says `pointer-events: auto !important;`.)

Once you remove that fix, the bug will manifest. When you downgrade Ionic to v5.3.2 the bug goes away again.

**Comment by nuno** [comment]
@crates 
if you set  button on IonItem ->> ```<IonItem button``` ...
you don't need to add an ```<IonButton>``` inside.
Also  you have  menuId and contentId,  I think you only need only contentId and not both .

**Comment by nuno** [comment]
@crates @willmartindev
found the issue, remove the  id="main"  from <IonContent>

````
  <IonContent>
      <MainNavMenu {...p} />
    </IonContent>````

**Comment by crates** [comment]
@nuno - I can't tell you how much it means that you looked into this for me, especially since I couldn't get a proper reproduction for you.

Just curious though: why did the upgrade between versions change this behavior and cause a glitch where one wasn't present previously? 

And also: how would I have known this from the docs to avoid this kind of mistake?

I'm eagerly awaiting Ionic X. My team at PwC had some of your lead engineers demo some of what's coming, over a year ago, and it was very enticing. I'm working on a low-code solution of my own until more desirable alternatives are available. If there's any way to get on a mailing list as details develop, I'd be very much interested.

Thanks again for looking into this, fellas.

**Comment by nuno** [comment]
@crates Glad I can help.
My investigation lead me here:
version 5.6.5 -> https://github.com/ionic-team/ionic-framework/releases/tag/v5.6.5. 
-> content: only render a main element when content is being used in primary view (#23160) (2d07d82)

Related links:
https://github.com/ionic-team/ionic-framework/pull/23160
https://github.com/ionic-team/ionic-framework/commit/2d07d8216af908b181c5e7e438e79a049bb6d8c2

On my test, soon as I put the  id="main" in  **ion-menu ->  IonContent**
I had the same behavior, if you look at the docs they not put any id on IonContent.

**V5.x**- https://ionicframework.com/docs/api/menu
**V6beta.x**  https://beta.ionicframework.com/docs/api/menu


Hope is now more clear to you. :)

**Comment by crates** [comment]
That's some stellar sleuthing!

But, is it really the desired behavior?

The "id" attribute is almost universally-used in HTML, CSS and JS to uniquely identify an element. It seems counter-intuitive to have any Ionic treatment break as a result of applying such a common attribute. It's almost like saying we can't use the "class" attribute or a "data-something" attribute. 

In any case where using Ionic would countermand the universal standards for HTML5, I'd suggest warning people in the documentation, at a minimum, so others don't get caught by the same snare.

Thanks again for everything.

**Comment by nuno** [comment]
More investigation:

you can not use the same as contentId="main" ....   and `<IonContent id="main">`
But if we use a diff id like id="main2"   `<IonContent id="main2"> `that will work!

Also the issue  only happens ` <IonContent id="main">` that is inside of `<IonMenu ..>`

I created an ` ionic start menuIssue sidemenu` and tested by adding the id on IonContent, the same as contentId="main" and I reproduced the issue. 
but as I said above if I named a diff id than contentId it works.

**Comment by willmartindev** [comment]
Thanks @nuno and @crates for the investigation! I agree that managing the multiple ID's might get a little error prone. 

I believe the issue occurred because `contentId` is meant to be reference the _main_ `ion-content` rather than the `ion-content` within the menu: https://ionicframework.com/docs/api/menu#contentid

Interactions are meant to be disabled on the _main_ content when a menu is open, so I can see why misattributing the property causes this issue.

As for updating the docs, do you have a suggestion for a place where mentioning this might be useful? I will discuss adding a `console.warn` with the team, as I think that would indeed be helpful.

**Comment by nuno** [comment]
I don't think this is a bug, also there is not place is the documentation that said to put the same id  as ionmenu in  IonContent.
Here I explain everthing https://github.com/ionic-team/ionic-framework/issues/23702#issuecomment-897225470

Ionic have his own properties, methods and are documented in every component at the bottom.

"Are you able to put together a reproduction repo that reflects your findings"
Just run:
`ionic start menuIssue sidemenu`

**Comment by willmartindev** [comment]
Going to close out this issue, as we determined the cause was not a bug but rather a lack of clarity in the usage of the `contentId` prop. 

I created #23810 as an action item to create a console warning to help mitigate this issue for future users. Unless a community member wants to work on it first, it will be tackled in a future sprint. Thank you both!
