### ISSUE TITLE
bug: trying to change styles disabled button

### ISSUE THREAD

**Issue by alicalo** [ionic-team/ionic-framework#23710]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

We are using ionic-react 5.5.0. Specifically, we are encountering a problem when we use buttons or components that have the disabled state, and we see that an opacity is applied by default, but we can't get a style that we specifically created to be applied.

This is the button component: 
`<IonButton className={styles.button_style} color={color} disabled={disabled} > {text} </IonButton>`

These are the colour variables applied from the theme/variables.css file: 
  ```
--ion-color-primary: #111111;
  --ion-color-primary-rgb: 17, 17, 17;
  --ion-color-primary-contrast: #ffffff;
  --ion-color-primary-contrast-rgb: 255, 255, 255;
  --ion-color-primary-shade: #0f0f0f;
  --ion-color-primary-tint: #292929;
```
  
Preview active button:
![image](https://user-images.githubusercontent.com/49151387/127834853-94a8aafe-54d7-4c1f-85b0-6c631c17f61f.png)

What the default ionic button looks like when disabled:
![image](https://user-images.githubusercontent.com/49151387/127835050-0db7f8f8-6bb8-49da-99ae-0ed406e10548.png)
 

### Expected Behavior

What we expect to happen when we apply our styles in the scss, is the following: 

```
ion-button {
    &[disabled] {
        --background: #F5F5F5!important;
        --color: #C0C0C0!important;
        --opacity: 1!important;
    }
}
```
What the disabled button should look like with our custom styles:
![image](https://user-images.githubusercontent.com/49151387/127836015-c6d5d0d4-673e-4822-a01e-a97eeca8222d.png)

### Steps to Reproduce

The steps to create it were: create an ionic button with its module.scss class that is called from the component to apply the styles. But these have no effect because they always take the default styles from the main class of theme/variables.css and apply the opacity.
![image](https://user-images.githubusercontent.com/49151387/127836643-72b9ea69-6b56-4c64-8466-ea5ecd4f8d97.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
