### ISSUE TITLE
bug: ion-datepicker triggering Reachability on iOS in iPhone X and onward devices

### ISSUE THREAD

**Issue by Muhammad-AhmadRafique** [ionic-team/ionic-framework#23720]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Reachability will be activated and the application will slide down when you scroll down within the datetime picker.

### Expected Behavior

The component should allow the user to enter the date and time easily without activating Reachability.

### Steps to Reproduce

Trigger an <ion-datetime> element on an iPhone X or other device with Reachability enabled.
Scroll down several items.

### Ionic Info

Ionic:

   Ionic CLI       : 6.16.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.4.4

Capacitor:

   Capacitor CLI      : 2.4.4
   @capacitor/android : 2.4.2
   @capacitor/core    : 2.4.4
   @capacitor/ios     : 2.4.7

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Big Sur

### Additional Information

This issue was posted in 2018, and it is still in iPhone X and onward devices,
The previous issue ticket number was :   #17526

So, it means, it is still not fixed, 
waiting for your feedback.

Thanks,

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is fixed in the Ionic Framework v6 beta. If you are interested in testing the beta, please see https://github.com/ionic-team/ionic-framework/blob/next/BETA.md.
