### ISSUE TITLE
bug: datetime current day on ios should not use text color var

### ISSUE THREAD

**Issue by milanharia** [ionic-team/ionic-framework#23723]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using the IonDatetime component, when the current day is selected, the text color takes the same color as defined by **--ion-text-color**  _in variables.css_. This causes contrast issues as seen in the attached screenshot. This only happens in iOS, the md variation of the component works fine.

I currently have --ion-text-color defined in :root as #6A6A6A which makes the selected current day inherit that color instead of displaying as white.

![localhost_8100_home(iPhone X)](https://user-images.githubusercontent.com/76167627/128189189-ebfc49f6-ea55-423b-abbf-2f5519deac71.png)

### Expected Behavior

I expect the color of the selected current day to display as white as it does in the md variation of the component (see below),

![localhost_8100_home(Pixel 2 XL)](https://user-images.githubusercontent.com/76167627/128189501-8906f8f1-4048-4bdf-8278-c7202bf90f15.png)

### Steps to Reproduce

I am using the current code to render the home component:

  ```
  <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Home</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen className='ion-padding'>
        <IonDatetime display-timezone='utc' presentation='date'>
          <div slot='title'>TITLE</div>
        </IonDatetime>
      </IonContent>
    </IonPage>
```

In variables.css:

`:root {
  --ion-text-color: #6a6a6a;
}`

### Ionic Info

Ionic:

   Ionic CLI       : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.0-beta.2

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : not installed
   @capacitor/core    : 3.1.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v14.15.1 (/usr/local/bin/node)
   npm    : 6.14.8
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/react@6.0.0-dev.202108041524.092d6d6 @ionic/react-router@6.0.0-dev.202108041524.092d6d6
```

**Comment by milanharia** [comment]
It works fine in the dev build. Thank you for the quick response!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23729, and a fix will be available in an upcoming release of Ionic Framework.
