### ISSUE TITLE
bug: form validation not highlighting errors on mode md

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/ionic-framework#23733]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

On ionic Angular, the form fields will highlight red for when `.markAllAsTouched()` for `item mode="md"`.
After upgrading to v6, the behavior is not experienced anymore. the highlight only shows when fields are focused__

### Expected Behavior

The form should show (highlight) errors on the fields when submitted or `.markAllAsTouched()`

### Steps to Reproduce

upgrade ionic angular `npm install @ionic/angular@next` from v5 to v6

```
<form (ngSubmit)="onSubmit()" [formGroup]="loginForm">
          <ion-list mode="md">
            <ion-item>
              <ion-label position="stacked" >Email Address</ion-label>
              <ion-input  type="email" formControlName="email"></ion-input>
            </ion-item>
            ...
          </ion-list>
</form>
```

```
this.loginForm = this.formBuilder.group({
      email: [
        '',
        Validators.compose([
          Validators.maxLength(100),
          Validators.required,
          Validators.email
        ])
      ]
...
```

```
onSubmit() {
    this.loginForm.markAllAsTouched();
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/Users/jonathan/.nvm/versions/node/v16.4.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.2
   @angular-devkit/build-angular : 12.1.2
   @angular-devkit/schematics    : 12.1.2
   @angular/cli                  : 12.1.2
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.2
   @capacitor/ios     : 3.1.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v16.4.2 (/Users/jonathan/.nvm/versions/node/v16.4.2/bin/node)
   npm    : 7.18.1
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue. Could you reproduce this in an Ionic starter app and provide a link to the repo?

**Comment by jongbonga** [comment]
@liamdebeasi Please see reproduction [here](https://github.com/jongbonga/23733) 

on click of the login button

`v5` on main branch behaves like expected 
`v6` on v6 branch doesn't validate the fields

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23853, and a fix will be available in an upcoming release of the Ionic Framework v6 beta.
