### ISSUE TITLE
bug: type '{ icon: string; }' is not assignable to parameter of type 'ToastOptions'.

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/ionic-framework#23736]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

ToastOptions does not include icon as per #23596 

```
export interface ToastOptions {
  header?: string;
  message?: string | IonicSafeString;
  cssClass?: string | string[];
  duration?: number;
  buttons?: (ToastButton | string)[];
  position?: 'top' | 'bottom' | 'middle';
  translucent?: boolean;
  animated?: boolean;
  color?: Color;
  mode?: Mode;
  keyboardClose?: boolean;
  id?: string;
  enterAnimation?: AnimationBuilder;
  leaveAnimation?: AnimationBuilder;
}
```

### Expected Behavior

`ToastOptions` should be able to get `icon`

### Steps to Reproduce

install latest  `@ionic/angular 6.0.0-beta.3`

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.16.3 (/Users/jonathan/.nvm/versions/node/v16.4.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.0
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23737, and a fix will be available in an upcoming release of Ionic Framework.
