### ISSUE TITLE
bug: ion-slides pager inside modal disappears when modal dismissed

### ISSUE THREAD

**Issue by vanessag** [ionic-team/ionic-framework#23747]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When an ion-slides element with pager="true" is placed inside of a modal the pager element disappears when the modal is dismissed and then reopened. In addition to the pager disappearing the slide animation appears to break and seems more like a scroll than a slide. NOTE: ion-slides works as expected the first time the modal is opened.

### Expected Behavior

The ion-slides pager should not disappear when the modal is dismissed and the slide animation should work as expected.

### Steps to Reproduce

1. Create brand new ionic angular project
2. Create modal page with `ionic g page modal`
3. Open modal from home page:
```
  async open() {
    const modal = await this.modalController.create({
      component: ModalPage
    });
    return await modal.present();
  }
```
4. Place ion-slides inside modal page:
```
<ion-header>
  <ion-toolbar>
    <ion-title>modal</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <ion-slides pager="true">
    <ion-slide>
      <p>slide 1</p>
    </ion-slide>
    <ion-slide>
      <p>slide 2</p>
    </ion-slide>
  </ion-slides>

  <ion-button (click)="close()">Close</ion-button>
</ion-content>
```
5. Implement close in modal:
```
  async close() {
    await this.modalController.dismiss();
  }
```
6. Open the modal and then dismiss and reopen

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.13
   @angular-devkit/build-angular : 12.0.5
   @angular-devkit/schematics    : 12.0.3
   @angular/cli                  : 12.0.5
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.2
   @capacitor/ios     : 3.1.2

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.17.4 (/usr/local/Cellar/node@14/14.17.4/bin/node)
   npm    : 6.14.14
   OS     : macOS Big Sur

**Comment by vanessag** [comment]
I found a workaround by calling slider.update() in ngOnInit.

```
export class ModalPage implements OnInit {
  @ViewChild(IonSlides, { static : true }) slides: IonSlides;

  constructor(
    private modalController: ModalController
  ) { }

  ngOnInit() {
    this.slides.update();
  }

  async close() {
    await this.modalController.dismiss();
  }

}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. With the upcoming release of Ionic Framework v6 we will be deprecating `IonSlides` and `IonSlide` component. As a result, we have a freeze on new feature development and bug fixes for these components (with the exception of critical security fixes).

We recommend using Swiper.js directly, which is the technology that powers `IonSlides`. The good news is that since the underlying technology is the same, the migration should be easy. Please see our migration guide for more information: https://beta.ionicframework.com/docs/api/slides#migration
