### ISSUE TITLE
bug: Ripple Color on ion-back-button not working

### ISSUE THREAD

**Issue by chirag-khandhar** [ionic-team/ionic-framework#23748]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Using `--ripple-color` on `ion-back-button` does not affect the ripple color on the back button. 

### Expected Behavior

Using this Custom CSS property should change the ripple color. 

### Steps to Reproduce
1. Create brand new ionic angular project
2. Replace the following files with the code below

**home.page.html**
```
<!-- Default back button -->
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button defaultHref="/" text=""></ion-back-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```
**home.page.scss**
```
ion-back-button {
  --ripple-color: red;
}
```
3. Run `ionic serve`
4. Click on the back button (Android View/Default browser view)

The expected ripple should have been red but it is not changed. 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/86026523/128758394-4d427c5f-87ca-434d-b62e-e13f9f6da071.png">

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.13
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.0
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.17.1 (/usr/local/bin/node)
   npm    : 7.18.1
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@5.7.0-dev.202108091903.f83768c
```

**Comment by chirag-khandhar** [comment]
Yes installing the above mentioned package did solve the issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23749, and a fix will be available in an upcoming release of Ionic Framework.
