### ISSUE TITLE
bug: React overlay hooks (useIon*) are not fully memorised 

### ISSUE THREAD

**Issue by FWeinb** [ionic-team/ionic-framework#23741]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Using the [new overlay hooks](https://ionicframework.com/blog/introducing-the-new-overlay-hooks-for-ionic-react/) feels great and is a nice improvement in my opinion. When using them I noticed that for `useIon{Toast|Alert|Popover|...}` the results aren't memorised and change each render. This will cause a great deal of overhead when the `present`/`dismiss` methods will be dependencies of other `useEffects`. 

You can see a demo of this behaviour [here](https://codesandbox.io/s/ionic-hooks-memorisation-5o4yc?file=/src/App.tsx)

### Expected Behavior

All the `useIon*` hooks should memorised the returned `present`/`dismiss` to match developers expectation. 

### Steps to Reproduce

1. Use any of the new overlay hooks e.g. `useIonToast`
2. Make it a dependency of `React.useEffect(..., [presentToast])`
3. See that this effect is reevaluated each time the component is rendered. 

### Code Reproduction URL

https://codesandbox.io/s/ionic-hooks-memorisation-5o4yc?file=/src/App.tsx

### Additional Information

I tracked this issue down to `useController`. Adding some `React.useCallback` here
https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/packages/react/src/hooks/useController.ts#L38
and here
https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/packages/react/src/hooks/useController.ts#L74
and a `React.useMemo`
https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/packages/react/src/hooks/useController.ts#L79-L82
will ensure that the `controller` is memorised. Looking at the other `useIon*` hooks should be straight forward. Fixing `useIonToast` would need a `React.useCallback` here
https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/packages/react/src/hooks/useIonToast.ts#L18

If you think this is something that should be implemented I can create a PR for these changes.

**Comment by willmartindev** [comment]
Hey @FWeinb, thanks for the issue and the useful code reproduction!

I agree that this is unwanted behavior and I think your proposed solution is in the right direction. If you could create a PR for this, that would be very helpful. 😄

**Comment by FWeinb** [comment]
Closing this because I submitted a PR fixing this.

**Comment by liamdebeasi** [comment]
Thanks for the PR! I am going to keep this issue open until the PR gets merged.

**Comment by willmartian** [comment]
Thanks for the contribution on this issue @FWeinb! The fix for this issue has been merged and will be available in the next release of Ionic Framework.
