### ISSUE TITLE
bug: White gap / padding above keyboard when input is focused only on iOS

### ISSUE THREAD

**Issue by impzero** [ionic-team/ionic-framework#23742]
### Prequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

The ion-content is resized when the keyboard shows up on iOS, leading to a white box right above the keyboard when a `Chakra UI` input is focused. However, focusing on an ion-input is fine and the resizing is correct.

It appears that the --keyboard-offset prop is set to 290px when emulating an iOS device, otherwise it is 0px on Android.

### **Initially when no inputs are focused**
<img src="https://i.imgur.com/VHxpAvS.png" alt="ss" width="300"/>

### **When I focus on any of the inputs**
<img src="https://i.imgur.com/BJkq026.png" alt="ss" width="300"/>

_right now NO keyboard is showing because I am using the chrome tools to emulate iOS browser behaviour, but keep in mind that running it on iOS device opens the keyboard and displays this white gap above the keyboard_

Digging the DOM elements I found  that the `ion-content` component has a prop `--keyboard-offset` .

When any of the two inputs is focused the `--keyboard-offset` prop is set to 290px (only on iOS)

### Expected Behavior

The `ion-content` component should keep its size and handle properly the scrolling when iOS keyboard is opened.

### Steps to Reproduce

Here is a live demo version:
https://w1fxx.csb.app/

Source code:
https://codesandbox.io/s/white-gap-padding-above-keyboard-when-input-is-focused-only-on-ios-w1fxx

1. Open DevTools, toggle device view and **iPhone X**, alternatively you could open the link above from an iOS device
    <img src="https://i.imgur.com/uiF1ERX.png" width="600"/>

2. **VERY IMPORTANT** - hard refresh the page after toggling device view - it is `CTRL` + `SHIFT` + `R` - for chrome
3. Now click on any of the inputs - you should see the **white box**

### Code Reproduction URL

https://codesandbox.io/s/white-gap-padding-above-keyboard-when-input-is-focused-only-on-ios-w1fxx

### Ionic Info

```bash
Ionic:

   Ionic CLI       : 6.16.3 (/home/lyubo/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.12

Capacitor:

   Capacitor CLI      : 3.0.2
   @capacitor/android : 3.0.2
   @capacitor/core    : 3.0.0
   @capacitor/ios     : 3.0.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v15.14.0 (/usr/bin/node)
   npm    : 7.17.0
   OS     : Linux 5.11
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is to be expected. We have a scroll assist utility that adds padding to the bottom of `ion-content` to ensure that we can scroll any inputs above the keyboard so they are not covered.

The white you are seeing is `ion-content` with padding. You can get that padded area to be green by applying the background color to the `--background` css variable on `ion-content` instead of the inner div like you currently have.

We have limited control over the keyboard when running in a web browser, so scroll assist needs to estimate dimensions. As a result, sometimes it overestimates the keyboard dimension. I think this is an area we can improve, so I am going to merge this issue with https://github.com/ionic-team/ionic-framework/issues/23664.

**Comment by fr3fou** [comment]
The weird gap also seems to push all of the inputs behind the keyboard while testing on a real iOS device so it's not necessarily a browser-only issue

**Comment by liamdebeasi** [comment]
As I mentioned, this is to be expected as it is the scroll assist utility. It is there to ensure that inputs do not get pushed under the keyboard.

You can disable it by setting `scrollAssist: false` in the Ionic config, but then you will need to make sure that inputs are never covered by keyboards. Alternatively, you can disable just the scroll padding by setting `scrollPadding: false`.
