### ISSUE TITLE
bug: angular, navigating multiple times causes pages to not get setup properly

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#23740]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

I have an application with few tabs. 
I would like to route from one tab to other within controller function, and then to child route, like this:
```js
async navigate() {
  await this.nav.navigateForward(['tabs', 'tab2']);
  this.nav.navigateForward(['tabs', 'tab2', 'child-route']);
}
```
However, if i use condense header, after navigation to child page, both  ion-title's will be visible.
Note that it is happen only after app started. If you will firstly come to child route, and scroll page, then issue will not be reproduced again. 

Also, adding timeout solve this issue:
```js
async navigate() {
  await this.nav.navigateForward(['tabs', 'tab2']);
  await new Promise(resolve => setTimeout(resolve, 100));
  this.nav.navigateForward(['tabs', 'tab2', 'child-route']);
}
```

If here is some trick to solve this issue without increasing timeout, please let me know. 

### Expected Behavior

ion-title must be visible on the header only if page is scrolled. 

### Steps to Reproduce

1. `ionic cordova build ios`
2.  Run on device/emulator
3. Click to the button 

### Code Reproduction URL

https://github.com/roman-rr/ionic-routing-header

### Additional Information

![ezgif-3-28e5ad1d6286](https://user-images.githubusercontent.com/10646478/128623029-4becf9c8-e852-4db9-93ef-e4becf357dc3.gif)

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is that `navigateForward` resolves when the Angular Router is done routing. It does not wait for any internal Ionic lifecycles to finish. As a result, the child page is not setup properly (I.e. it does not get the `.ion-page` class) and so the collapsible header is not setup properly either.

**Comment by sean-perkins** [comment]
Hello 👋 we recently updated our documentation to explain best practices with routing with regards to tabs: https://ionicframework.com/docs/angular/navigation#switching-between-tabs

The specific use case reported here is a pattern that we do not recommend (navigating between tabs programmatically).

In your example recording, "Child Route" should be a child of the "Tab 1". Tab 1 should remain active when clicking the button to navigate.

I am going to close this issue as this is not an intended pattern for native navigation. Please let me know if you have any questions!
