### ISSUE TITLE
App is crashing on click of any video, when the screen reader mode is on in IOS

### ISSUE THREAD

**Issue by AnkurOO9** [ionic-team/ionic-framework#23758]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

App is crashing when voice over mode is on in IOS.

### Expected Behavior

App should not be crash when voice over mode is on in IOS.

### Steps to Reproduce

1) Turn on voice over.
2) Play any video. Double tap on enter full screen. Sometimes It is also occurring when we are trying to play video. It's random issue not occurring every time.

### Ionic Info

Ionic:

Ionic CLI : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 5.6.9
@angular-devkit/build-angular : 0.1000.8
@angular-devkit/schematics : 10.0.8
@angular/cli : 10.0.8
@ionic/angular-toolkit : 2.3.3

Cordova:

Cordova CLI : 10.0.0
Cordova Platforms : ios 6.2.0
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 2.5.1, (and 16 other plugins)

System:

ios-sim : 8.0.2
NodeJS : v14.17.0 (/usr/local/bin/node)
npm : 6.14.13
OS : macOS Big Sur
Xcode : Xcode 12.5 Build version 12E262```

### Additional Information

We are using npm-plyr (https://www.npmjs.com/package/plyr) for videos.

Because of this issue(https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/378) we are using 2.5.1 version instead of 5.0.0.

**Comment by Jalpesh009** [comment]
Please refer below link for code.  https://github.com/hitendraalbiorix/demo

**Comment by willmartindev** [comment]
Hi @jaapjanfrans, based on the code reproduction you sent in, I don't believe this issue is related to Ionic Framework, as we do not hook into videos or any specific screen reader mode.

It is possible that this could be an issue with the video library you are using, or an issue with the older version of `cordova-plugin-ionic-webview` you are using. I'm not sure exactly; I would recommend posting in the Ionic forums for additional support on this issue. 

Thank you!
