### ISSUE TITLE
feat: configurable fab space

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#23756]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The floating action button (FAB) space should be configured. It's about the fixed position to the screen edge. Currently it has a fixed size. Adding CSS variable or similar will fix it.

### Describe the Use Case

Give more control about the FAB button position / edge space / gap. Including dynamically space. (Change space during runtime.)

### Describe Preferred Solution

Can be CSS variables. What do you think?

### Related Code

```html
<ion-fab horizontal="end" vertical="bottom" slot="fixed">
```

### Additional Information

![image](https://user-images.githubusercontent.com/60390085/128864421-4c14d040-c027-4a6c-895f-bcfe69253b2f.png)

![image](https://user-images.githubusercontent.com/60390085/128873392-64ca9f8f-a495-4a48-a2a6-12bc939e5f4f.png)

Ionic 5

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify the problem you are trying to solve? You can add `margin` to the `ion-fab` to add gaps between the bottom and right edges of the screen.

**Comment by infacto** [comment]
I was just thinking about a variable to specify the value which the framework is using. But yes, I know I can use custom css. With `margin` or `bottom` / `right`. And use [ion-safe-area](https://ionicframework.com/docs/theming/advanced#application-variables) etc. See my updated initial post (graphic added). Indeed, in this case it's pretty easy. The most stuff can be "hacked" with css. In my opinion the frontend should present such stuff. Anyway... Ok, I close this issue. Thanks for your time.
