### ISSUE TITLE
bug: After I got the same bug like post #22654, I updated it and got warning with ion lifecycle not found

### ISSUE THREAD

**Issue by whitersun** [ionic-team/ionic-framework#23751]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

After installing the router in post #22654, I got onIonView lifecycle not found and after using router.replace to home -> the web address is correct but the view page in wrong. How can I solve this problem?

### Expected Behavior

expect like the result in post #22654 said. After leaving the current to a specific page will show up the correct page with web address.

### Steps to Reproduce

after installing 
npm install @ionic/vue@5.6.0-dev.202012091649.c699e16 @ionic/vue-router@5.6.0-dev.202012091649.c699e16

I got the warning about ionic vue lifecycle not found.

### Ionic Info

Ionic:

   Ionic CLI       : 6.16.3 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.6.0-dev.202012091649.c699e16

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.17.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.14
   OS     : Windows 10

**Comment by whitersun** [comment]
I already fixed it. Thanks, ionic team. After update
    "@ionic/vue": "^5.4.0",
    "@ionic/vue-router": "^5.4.0",
to 
    "@ionic/vue": "^5.6.13",
    "@ionic/vue-router": "^5.6.13",
issue from post #22654 and ionic vue lifecycle missing is solved.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
