### ISSUE TITLE
bug: slider breaks after return

### ISSUE THREAD

**Issue by white91wolf** [ionic-team/ionic-framework#23754]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [x] v4.x
- [ ] v5.x
- [ ] v6.x

### Current Behavior

I can reproduce a strange behavior in my app using the swiper -"swiper": "^6.7.5"-  (ion-sliders) component.
Initially the swiper slides work fine. After i click on a slide to change the content and then go back the slides brake and i can't slide properly - for example the very left one is not reachable anymore.

i also tried it with some other options like loop and centeredSlides to kinda unterstand the behavior but i don't got any more information. I made a few clips from the app where i also colored the first slide cyan.
![normal-min](https://user-images.githubusercontent.com/52070923/128845611-0adb3c17-d802-4e25-b280-3e13c10b41aa.gif)

### loop: true
![loop-min](https://user-images.githubusercontent.com/52070923/128845628-3f1b0f69-533f-4979-aa9f-ca287e7a7d60.gif)

### centeredSlides: true
![centeredSlides-min](https://user-images.githubusercontent.com/52070923/128845647-58386349-2b0e-48df-bb41-dd9cdf725efa.gif)

### Expected Behavior

The slides should behave like before switching the page. Normal sliding.

### Steps to Reproduce

I create the overview with the slides like that:

```
<ion-slides  [options]="{ slidesPerView: 'auto', zoom: false, centeredSlides: false }" >
  <ion-slide *ngFor="let c of workflow.c" class="slideWorkflow">
	<ion-card button="true" (click)="clickWorkflowEntry(c)">
	  <ion-card-content>
		<div class="cardWrapper">
		  <span [ngClass]="{'flowText' : c.title.length > 20}" [innerHTML]="c.title|keepHtml"></span>
		</div>
		<ng-container *ngIf="c?.iconFa != null">
		  <br />
		  <fa-icon
			[icon]="c?.iconFa"
			style="font-size: xxx-large"
		  ></fa-icon>
		</ng-container>
		<div *ngIf="c?.trigger != null" style="text-align: -webkit-center;">
		  <div [style]="c?.qrStyle">
			<ngx-qrcode
			  elementType="img"
			  [cssClass]="'ngxQrcode' + c.id"
			  [value]="c?.trigger"
			></ngx-qrcode>
		  </div>
		</div>
	  </ion-card-content>
	</ion-card>
	<ion-badge *ngIf="c.badge != null">{{c.badge}}</ion-badge>
  </ion-slide>
</ion-slides>
```

where the '_clickWorkflowEntry_' is called and this looks like:

```
  clickWorkflowEntry(w) {
    this.groupChatByWorkflowShowChat = true;
    this.zone.run(async () => {
      this.page = 0;
      this.chats = [];
      this.chatWorkflow = w;
      this.getMsg(true);
    });
  }
```

so i don't really switch to another page - i change the content. and then go back.
Behind the back button there is only a simple logic which is resetting the values made in the click:

```
this.chatWorkflow = null;
this.groupChatByWorkflowShowChat = false;
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 29 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v14.17.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. With the upcoming release of Ionic Framework v6 we will be deprecating `IonSlides` and `IonSlide` component. As a result, we have a freeze on new feature development and bug fixes for these components (with the exception of critical security fixes).

We recommend using Swiper.js directly, which is the technology that powers `IonSlides`. The good news is that since the underlying technology is the same, the migration should be easy. Please see our migration guide for more information: https://beta.ionicframework.com/docs/api/slides#migration
