### ISSUE TITLE
feat: Better keyboard input support on web for ion-datetime

### ISSUE THREAD

**Issue by bchehraz** [ionic-team/ionic-framework#23768]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

On web/desktop, it's not obvious that you must use the mouse-wheel or up-down arrow keys in order to select a time in the time input fields of `ion-datetime` (v6). It would be nice if a user could type numbers into the time fields as input.

### Describe the Use Case

The app I'm building is for a wide range of users in terms of age & demographic and so I could use as much support as I can get in terms of usability. I want to use the same `ion-datetime` component on both web and mobile, but I just want the web version of the component have better support to allow for typing numbers into the time input fields because it's just not obvious that the user must scroll or use up-down keys. 

### Describe Preferred Solution

Allow for an override when on web to allow keyboard input (0-9, ":") to fill in the time fields. Perhaps this should be an override option to override the normal behavior, so I can decide that if the user is on web, to override the behavior and make it input from keyboard.

### Additional Information

I haven't tried the component since beta v1 or 2 but looking at the beta docs, I haven't any reason to believe this is a feature yet, but if it is and I'm just missing it, please let me know. Or if this feature doesn't seem reasonable or if I'm missing the point with the component, let me know how I can accomodate my users. Thanks

**Comment by willmartindev** [comment]
Thank you for the feature request, @bchehraz. I think this would be a good addition; let me discuss it with the team.

**Comment by bchehraz** [comment]
Thank you. Keeping my fingers crossed 🤞

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23996, and a fix will be available in an upcoming release of Ionic Framework.
