### ISSUE TITLE
bug: ion-nav animation always reset by router

### ISSUE THREAD

**Issue by MarkChrisLevy** [ionic-team/ionic-framework#23777]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When ion-nav has animation prop set to custom transition, the transition is never used when page change is triggered by ion-router.

### Expected Behavior

When ion-nav has animation prop, the custom transition should be used instead of default (mode specific) transition.

### Steps to Reproduce

1. Define router with some routes
2. For ion-nav set custom transition (e.g. when in md mode set animation=iosTransitionAnimation from "@ionic/core" package)
3. Trigger page change with ion-route-link or other component that uses ion-router for page changes

### Ionic Info

5.6.13

**Comment by MarkChrisLevy** [comment]
PR is comming...

**Comment by liamdebeasi** [comment]
Thanks! Looks like `animationBuilder` needs to be set after `...opts` here: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/nav/nav.tsx#L875

This is the same thing as what we did for `ion-router-outlet`: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/router-outlet/route-outlet.tsx#L230-L231

**Comment by MarkChrisLevy** [comment]
@liamdebeasi exactly, I will make a PR in a moment

**Comment by MarkChrisLevy** [comment]
@liamdebeasi Done :-)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23779, and a fix will be available in an upcoming release of Ionic Framework.
