### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by aalcantara63** [ionic-team/ionic-framework#23790]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

We are getting a different result when we deploy our application in IOS devices vs Android devices. The IOS version covers the entire top bar of the phone where the phone settings are located, and the bottom portion shows at the very bottom with hardly any space. It looks zoomed in. On the Android devices the view looks just right. I attached two pictures showing how it looks. We did it using Ionic components first and then we changed it to Vue.Js components and we still get the same result. We are using ionic/core 5.3.1, ionic/vue 0.0.9 code. 
![Android Samsung Screenshot iMenuApps](https://user-images.githubusercontent.com/43117317/129928075-3e4a10cb-8b88-4124-8407-c823438ee285.jpg)
![iPhone Screenshot iMenuApps](https://user-images.githubusercontent.com/43117317/129928084-11ba49e9-65bc-4b25-af10-b488d2711726.PNG)

### Expected Behavior

We should be able to every window of the application properly in IOS devices as we see it in Android devices.

### Steps to Reproduce

We have are not sure how to reproduce the problem since we are using the same code and it should show all screens within the area expected in all devices.

### Ionic Info

Ionic CLI : 5.4.16 (C:\Users\Miguel\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/vue 0.0.9

Capacitor:

Capacitor CLI : 2.4.2
@capacitor/core : 2.4.5

Utility:

cordova-res : not installed
native-run : not installed

System:

NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
npm : 6.14.6
OS : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. `@ionic/vue@0.0.9` is not supported anymore. We recommend using the latest version of Ionic Vue (5.6.14 at the time of writing) with Vue 3.

Are you using Vue 2 in your application?

**Comment by aalcantara63** [comment]
Yes, we are sing Vue 2.6.11

**Comment by liamdebeasi** [comment]
Thanks for the reply. The latest stable version of Ionic Vue only supports Vue 3.0+, and we are not maintaining the pre-release versions of Ionic Vue that supported Vue 2.

I am going to close this issue, but I recommend updating to Vue 3 if possible. You can also use the [Vue 3 Migration Build](https://v3.vuejs.org/guide/migration/migration-build.html) to make it easier to upgrade from Vue 2 to Vue 3.
