### ISSUE TITLE
bug: Jest raises " React does not recognize the `cssClass` prop on a DOM element"  in IonModal for cssClass property 

### ISSUE THREAD

**Issue by thetinshusasi** [ionic-team/ionic-framework#23794]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

1.  Create component with IonModal
`
const Component = ()=>{
 return. <IonModal cssClass="some-class" />
}
`
2.  Create a unit test
`
describe('Component', () => {
let spy;
  beforeEach(() => {
    spy = jest.spyOn(global.console, 'error');
  });

  afterEach(() => {
    expect(spy).not.toHaveBeenCalled();
  });

 
  it('should mount', () => {
    const { baseElement } = render(<Component  />);
    expect(baseElement).toBeDefined();
  });
});
` 
3. npm run test

**Result**

console.error
      Warning: React does not recognize the `cssClass` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `cssclass` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          at div

### Expected Behavior

1. Test case should pass and jest console should not show error

### Steps to Reproduce

1.  Create component with IonModal
`
const Component = ()=>{
 return <IonModal cssClass="some-class" />
}
`
2.  Create a unit test
`
describe('Component', () => {
let spy;
  beforeEach(() => {
    spy = jest.spyOn(global.console, 'error');
  });

  afterEach(() => {
    expect(spy).not.toHaveBeenCalled();
  });

 
  it('should mount', () => {
    const { baseElement } = render(<Component  />);
    expect(baseElement).toBeDefined();
  });
});
` 
3. npm run test

### Ionic Info

Ionic:

   Ionic CLI       : 6.16.3 (<Path>/.nvm/versions/node/v14.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.6

Capacitor:

   Capacitor CLI      : 2.4.7
   @capacitor/android : 2.4.7
   @capacitor/core    : 2.4.7
   @capacitor/ios     : 2.4.7

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.16.0 (<Path>/.nvm/versions/node/v14.16.0/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur

  ─────────────────────────────────────────────────

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo? I cannot reproduce this on my end.
