### ISSUE TITLE
bug: reorder event gives incorrect 'to' value when an item is dragged far enough

### ISSUE THREAD

**Issue by tobysmith568** [ionic-team/ionic-framework#23796]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

The `to` field on the `ItemReorderEventDetail` event is off-by-one (too high) when an item is dragged past the end the list.

### Expected Behavior

The `to` field should never be more that the number of items - 1.

### Steps to Reproduce

I have created a repro but this can also be reproduced in the ionic unit tests found at [src/components/reorder-group/test/basic](https://github.com/ionic-team/ionic-framework/tree/main/core/src/components/reorder-group/test/basic).

- Run the app
  - If using the ionic unit tests: toggle on the reorder behaviour
- Open the browser console
- Drag an item to the end of the list, ensuring that is is dragged only just far enough to be in the last position
  - The console shows that it was dragged to index 11
- Drag an item to the end of the list, ensuring that it is dragged as far as it possibly can be
  - The console shows that it was dragged to index 12

![yi9j7qwFvH](https://user-images.githubusercontent.com/22356255/130356204-e3c7b122-15bb-4f56-be29-a9ad70752389.gif)

### Code Reproduction URL

https://github.com/tobysmith568/ionic-reorder-repro

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\tobys\AppData\Roaming\nvm\v14.15.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.14
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Utility:

   cordova-res : 0.15.3
   native-run  : not installed globally

System:

   NodeJS : v14.15.0 (C:\Tools\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10

### Additional Information

~~Will be providing a PR with a possible solution soon.~~
PR: #23797

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23797, and a fix will be available in an upcoming release of Ionic Framework. Thanks for putting up the PR!
