### ISSUE TITLE
bug: Can Popover always appear fixed above?

### ISSUE THREAD

**Issue by vivianus-chan** [ionic-team/ionic-framework#23792]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

```
const [present, dismiss] = useIonPopover(PopoverList, {onHide: () => dismiss()})


const PopoverList: React.FC<{
    onHide: () => void
}> = ({onHide}) => (
    <IonList>
        <IonItem onClick={onHide} lines="none">
            加签
        </IonItem>
    </IonList>
)


          <IonHeader translucent>
                <IonToolbar>
                    <IonTitle>Default Title</IonTitle>
                </IonToolbar>
            </IonHeader>

           <IonContent fullscreen>
                dd
            </IonContent>
            <IonFooter className="ion-no-border">
                <IonGrid>
                    <IonRow>
                        <IonCol size="5">
                            <IonButton fill="outline" expand="block" onClick={() => {}}>
                                数据暂存
                            </IonButton>
                        </IonCol>
                        <IonCol size="5">
                            <IonButton expand="block" onClick={() => {}}>
                                提交
                            </IonButton>
                        </IonCol>
                        <IonCol size="2">
                            <IonButton
                                fill="default"
                                expand="block"
                                onClick={(e) => {
                                    console.log(e, e.nativeEvent)
                                    present({
                                        event: e.nativeEvent
                                    })
                                }}
                            >
                                更多
                            </IonButton>
                        </IonCol>
                    </IonRow>
                </IonGrid>
            </IonFooter>
```

It's normal most of the time：
![C5A91F98-2FE2-4be8-BA71-1E31D7119D62](https://user-images.githubusercontent.com/16096294/129996015-deb5a96e-07b5-4c8b-9987-3a3a008c4314.png)

It happens occasionally：
![BD814D57-F3C1-447c-BD78-F63C409F4B3F](https://user-images.githubusercontent.com/16096294/129996250-d579b00e-fc7b-4f34-baa7-b0638e76ef15.png)

**QS: Can Popover always appear fixed above?**

### Expected Behavior

![C5A91F98-2FE2-4be8-BA71-1E31D7119D62](https://user-images.githubusercontent.com/16096294/129996015-deb5a96e-07b5-4c8b-9987-3a3a008c4314.png)

### Steps to Reproduce

Click  ‘更多’ buttons many times，Sometimes Popover appears outside the visual area，Can Popover always appear fixed above?

**Comment by liamdebeasi** [comment]
Thanks for the issue! In Framework v5, Ionic does its best to position the popover based on a few heuristics, but sometimes it gets it wrong. In Ionic Framework v6 we are introducing new positioning APIs that make the positioning of the popover more predictable. For example, you will be able to tell the popover to always appear on top of the trigger button.

I am going to close this for now as this functionality is already implemented. If you are interested in the giving the v6 beta a try please see https://github.com/ionic-team/ionic-framework/blob/next/BETA.md.
