### ISSUE TITLE
bug: margin-inline-start of end slot is too big.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#23805]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

![image](https://user-images.githubusercontent.com/60390085/130613063-2e8f1379-21c9-4a38-bc56-ff2a7ffa7b1a.png)

32px is too big. 

### Expected Behavior

![image](https://user-images.githubusercontent.com/60390085/130613159-63283391-316c-45d8-830f-47aafcc980da.png)

(Changed in Chrome dev tools.)
Should be e.g. `16px`.

### Steps to Reproduce

```html
<ion-item>
  <ion-label>Demo</ion-label>
  <p slot="end">See inspector</p>
</ion-item>
```

![image](https://user-images.githubusercontent.com/60390085/130612645-18630a90-99ad-44dd-97b0-b7d8c21e2d81.png)

Why? It's a weird break and overflow behavior. Especially on larger text content. What do you think? Why this huge space? Just created it as bug because of unexpected behavior.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Could you please describe how this behavior impacts your application?
