### ISSUE TITLE
feat: extend ion-toast css shadow parts

### ISSUE THREAD

**Issue by vladimirSnapAddy** [ionic-team/ionic-framework#23801]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Extend ion-toast CSS shadow parts(https://ionicframework.com/docs/api/toast#css-shadow-parts) with `content` so that html element with class "toast-content" can be stylized. 

### Describe the Use Case

.toast-content element would be stylizeable, which is not not an option. In our case, it helps with making `message` part overflowing text displayed as ellipsis, but I could easily believe other users will find more uses to it.

### Related Code

 ```
 async showToastError(opts: ToastOptions): Promise<HTMLIonToastElement> {
    opts.duration = 3000;

    opts.color = 'danger';

    this.addErrorDetailsButton(opts);

    const toast = await this.toastController.create(opts);

    await toast.present();

    return toast;
  }
```

```
private async addErrorDetailsButton(opts: ToastOptions): Promise<void> {
    opts.cssClass = 'snap-error-toast';

    const errorDetailsButton: ToastButton = {
      side: 'end',
      text: 'More details',
      handler: () => this.presentModal(opts.message)
    };
    opts.buttons = [errorDetailsButton];
  }
```

in scss file we have this part:

```
.snap-error-toast::part(message) {
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}
```

in order for ellipsis to work as we need it to, `min-width: 0` should be added to html element that currently contains 'toast-content' class.

### Additional Information

Screenshots with results of the code above:

What is currently the case:
![image](https://user-images.githubusercontent.com/85163599/130463371-33c5180a-7f2d-4d98-adc0-2f0b0ea1e231.png)

What we want to achieve:
![image](https://user-images.githubusercontent.com/85163599/130463575-5891fb0f-d07b-4123-9a38-09688df9c91d.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide a code example of when the existing shadow parts are not sufficient? I understand there are some difficulties around overflowing text, but if you could provide a code example that would be really helpful.

**Comment by vladimirSnapAddy** [comment]
Thank you for a prompt response. Initial feature req was edited and hopefully has enough details. Please write if you need more information.

**Comment by infacto** [comment]
You want text overflows with ellipsis? Why not break multiline?

**Comment by liamdebeasi** [comment]
If you could provide an example of what you are trying to do in an Ionic starter app that would be very helpful.

**Comment by vladimirSnapAddy** [comment]
Sure! I will do it as soon as possible.

**Comment by liamdebeasi** [comment]
Thanks! I can reproduce this behavior. Is there a reason why you do not want the text to wrap to the next line? I think truncating the text is going to make it harder for users to read the toast notification.
