### ISSUE TITLE
bug: ion-searchbar bug on v6-beta for chinese languages

### ISSUE THREAD

**Issue by yimity** [ionic-team/ionic-framework#23815]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

like this, it shows in v6-beta React version again. 
https://github.com/ionic-team/ionic-framework/issues/18768

### Expected Behavior

The ion-input ion-searchbar should work normally with the different language inputs.

### Steps to Reproduce

see this bug https://github.com/ionic-team/ionic-framework/issues/18768

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please reproduce this issue in an Ionic starter app and provide a link to the repo? The issue you linked to is over 2 years old and the context is likely outdated. Having a fresh reproduction helps us fix any potential issues quicker.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
