### ISSUE TITLE
bug: vue, lifecycle hooks not fired with vue 3.2 setup

### ISSUE THREAD

**Issue by riderx** [ionic-team/ionic-framework#23824]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

This code in component is never trigger :
```
  onIonViewDidEnter(() => {
      console.log('About page did enter');
    });

  onIonViewDidLeave(() => {
    console.log('About page did leave');
  });

  onIonViewWillEnter(() => {
    console.log('About page will enter');
  });

  onIonViewWillLeave(() => {
    console.log('About page will leave');
  });
```

### Expected Behavior

this should be triggered during routing

### Steps to Reproduce

you can clone : https://github.com/riderx/ionicv6-beta-vue-vite
`yarn`
and 
`yarn dev`

### Code Reproduction URL

https://github.com/riderx/ionicv6-beta-vue-vite

### Ionic Info

Ionic:

   Ionic CLI : 6.17.0

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : 1.4.0

System:

   NodeJS : v16.7.0
   npm    : 7.20.3
   OS     : macOS Monterey

**Comment by snowwolfjay** [comment]
any progress? because the router cache, it looks like disaster, because when you just need open one page, it open five visited for you... go(-1)/replace / back not clear the cache.

**Comment by raymer** [comment]
Any update on this? My app basically won't work unless I convert everything to the composition API instead of `<script setup>`

**Comment by Vshow101** [comment]
@liamdebeasi Is there any progress?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24253, and a fix will be available in an upcoming release of Ionic Framework.

Big thanks to @snowwolfjay for creating the fix!
