### ISSUE TITLE
bug: expose role attribute on ion-alert + ion-toast 

### ISSUE THREAD

**Issue by eric-horodyski** [ionic-team/ionic-framework#23825]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

While working with a community member, it was observed that there is no way to modify the `role` attribute for the `IonToast` and `IonAlert` components.

### Expected Behavior

As a developer, I would like to have the ability to set the `role` attribute as my application would like to set this attribute to `alert` for both components. 

`IonAlert` sets `role="dialog"` but in this application's accessibility context it needs to be set to "alert".

### Steps to Reproduce

Using the `AlertController` and `ToastController` there is no ability to manually set the `role` attribute.

### Code Reproduction URL

https://github.com/eric-horodyski/fw-ng-alert-toast-a11y

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.17.0 (/Users/eric/.volta/tools/image/packages/@ionic/cli/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.14
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.2
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.0
   @capacitor/android : not installed
   @capacitor/core    : 3.2.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.17.0 (/Users/eric/.volta/tools/image/node/14.17.0/bin/node)
   npm    : 7.14.0
   OS     : macOS Big Sur
```

**Comment by willmartindev** [comment]
Available in the next release of Framework, `ion-toast` and `ion-alert` will accept an `htmlAttributes` prop, which allows developers to pass arbitrary attributes to the host element, including `role`. Thanks!
