### ISSUE TITLE
feat: Add Sidenav

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23834]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add a new component which is sidenav like the link provided [here](https://material.angular.io/components/sidenav/overview) in Angular Material

### Describe the Use Case

This would be suitable for desktop websites instead of tab bar

**Comment by EinfachHans** [comment]
What about the [Ionic Menu](https://ionicframework.com/docs/api/menu)?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Have you tried using `<ion-split-pane>` with `<ion-menu>`? This should provide a similar result. Here is a code example: https://github.com/ionic-team/starters/blob/main/angular/official/sidemenu/src/app/app.component.html

You can play with a sample by creating a new "menu" starter app here: https://ionicframework.com/start

**Comment by farisfaisalthena** [comment]
Hi, yes i just double check on the docs and found the mentioned component. This leads me to another question to create the sidebar for iPad OS we would use this component also right?

**Comment by liamdebeasi** [comment]
Yes, you can use these components for iPadOS as well.

**Comment by farisfaisalthena** [comment]
Alright thanks i will be closing this issue.
