### ISSUE TITLE
feat: picker column - add prefix text align css property

### ISSUE THREAD

**Issue by Giulio-91** [ionic-team/ionic-framework#23836]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

In order to align the prefix text, a new attribute that modified the text-align css class is needed

### Describe the Use Case

Change the text align css property of the prefix column

### Describe Preferred Solution

add a column attribute (prefixTextAlign for example) that modifies the text align property

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide a code example of what you are trying to accomplish? If you can highlight the current problem in an Ionic starter app that would be really helpful.

**Comment by Giulio-91** [comment]
I actually I created a pull request for this:

https://github.com/ionic-team/ionic-framework/pull/23837

I just add a css property in order to be able to custom align the text inside the prefix column of a picker

**Comment by liamdebeasi** [comment]
Thanks for the reply. I saw the PR you created, but I am interested in understanding the problem you are trying to solve. Can you please provide a code example of what you are trying to do?
