### ISSUE TITLE
bug: IonModal not working on Typescript

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23846]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When importing the code below Visual Studio will not compile and will give me an error `Failed to compile.`
```ts
import { IonModal } from '@ionic/angular/directives/overlays/ion-modal';

@ViewChild(IonModal, { static: true }) modal: IonModal
```

### Expected Behavior

In order to use any functionality from Ion Modal using typescript, compiling the project should not fail

### Steps to Reproduce

Copy paste the code below

```ts
import { IonModal } from '@ionic/angular/directives/overlays/ion-modal';

@ViewChild(IonModal, { static: true }) modal: IonModal
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Your import here looks incorrect. It should be:

```
import { IonModal } from '@ionic/angular';
```

Can you try that and let me know if it resolves the issue?

If it still does not fix the issue, please reproduce this in an Ionic starter app and provide a link to the repo.

**Comment by farisfaisalthena** [comment]
`Module '"@ionic/angular"' has no exported member 'IonModal'.` this is the error on the `import { IonModal } from '@ionic/angular';`

**Comment by liamdebeasi** [comment]
Thanks! Can you try this dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.0.0-dev.202108301401.736a0c2
```

**Comment by farisfaisalthena** [comment]
Yup working now

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23847, and a fix will be available in an upcoming release of Ionic Framework.
