### ISSUE TITLE
bug: ion-loading vue-cli-plugin on iOS device and simulator

### ISSUE THREAD

**Issue by reslear** [ionic-team/ionic-framework#23840]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

vue3 component IonLoading not set shadow dom on ios or simulator in production mode, maybe this problem with webpack and svg spiners 

```vue
<tempalate>
  <ion-page>
        <ion-loading
          :is-open="isLoading"
          :duration="5000"
          @didDismiss="setLoading(false)"
        >
        </ion-loading>
  </ion-page>
</tempalate>
```

### Expected Behavior

showing loader with animation

### Steps to Reproduce

1. add component with vue 3 and 
2. build with vue-cli-plugin
3. run in simulator

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic start app and provide a link to the repo?
