### ISSUE TITLE
bug: outline on ion-select

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23848]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

After the recent beta change on the ion-item, when using `ion-select` inside the `ion-item`, the `ion-select` will have a green outline below as shown in the screenshot below. Please note that this only appears for `md` and not on ios

<img width="1098" alt="Screenshot 2021-08-30 at 10 50 27 PM" src="https://user-images.githubusercontent.com/61012396/131359669-38484173-6b8e-4257-a15d-a4cb50f2c708.png">

### Expected Behavior

For `ion-item` with `ion-select` inside it should not have the green outline

### Steps to Reproduce

The code as shown below

```ts
 <ion-item lines="inset">
            <ion-label>Theme</ion-label>
            <ion-select [ngModel]="theme$ | async" (ngModelChange)="changeTheme($event)">
              <ion-select-option value="">Auto</ion-select-option>
              <ion-select-option value="light">Light</ion-select-option>
              <ion-select-option value="dark">Dark</ion-select-option>
            </ion-select>
          </ion-item>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce the issue in an Ionic starter app and provide a link to the repo?

**Comment by farisfaisalthena** [comment]
https://github.com/farisfaisalthena/starter-repo

**Comment by liamdebeasi** [comment]
Thanks! This was fixed in Framework v6 beta 5:

```
npm install @ionic/angular@next
```
