### ISSUE TITLE
bug: ion-item fill property

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23849]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I am not sure if this is intended or its a bug. On iOS using `fill="outline"` does not show any outline when its focused as shown in the screenshot below. This issue is only on iOS and for MD its working fine

![IMG_1288](https://user-images.githubusercontent.com/61012396/131450377-5365e57f-2d56-4d7d-8761-111c225998f3.PNG)

### Expected Behavior

When using the fill property its should have the outline just like on MD as shown below

<img width="599" alt="Screenshot 2021-08-30 at 11 10 46 PM" src="https://user-images.githubusercontent.com/61012396/131451067-9c1dac81-d411-4486-a401-d63b2ee32e4a.png">

### Steps to Reproduce

```html
 <ion-item fill="outline" class="ion-margin-bottom ion-margin-top">
    <ion-label position="stacked">Username</ion-label>
    <ion-input formControlName="username" placeholder="Account Username"></ion-input>
 </ion-item>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. The `fill` mode is for MD items only. We are following the MD implementation here: https://material.io/components/text-fields
