### ISSUE TITLE
bug: Ionic React page with multiple modals may mount other modals when one is dismissed

### ISSUE THREAD

**Issue by babycourageous** [ionic-team/ionic-framework#23841]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I ran into an interesting situation in an app. 

If a page has multiple modals on it when one is dismissed, they all get mounted. Since the shell gets mounted, any component that is in the modal would run its code and potentially cause errors, bugs, etc.

Strangely it seems it does this for all modals "below" the called modal in the jsx. See the repro instructions to understand.

Not sure if this is intended or perhaps a bug. 
thanks!

### Expected Behavior

I expect only the modal that is open to be dismissed and no others should mount or run their code.

### Steps to Reproduce

In the sample app - open Tab 2. There are 4 buttons that each open their own modal. You can see that if you open Modal 2, when you dismiss it Modal 3 and 4 get mounted and Modal 2 shell remains (you can see this in the Components inspector of React dev tools)

![image](https://user-images.githubusercontent.com/14936212/131230321-90bdeccf-2d77-425f-9553-deafd9d0d5fa.png)

...as well as in the console logs - first "modal 2" is the opening. the next three logs are when modal 2 is dismissed.
![image](https://user-images.githubusercontent.com/14936212/131230413-ee75dcb2-5a28-4f39-9787-d31e12c01702.png)

### Code Reproduction URL

https://github.com/babycourageous/ionic-react-modal-render-issue

### Ionic Info

ionic info[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'
       
       Require stack:
       -
       /Users/rene/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli/lib/project/index.js
       -
       /Users/rene/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli/lib/index.js
       -
       /Users/rene/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli/index.js
       -
       /Users/rene/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package'
       
       Require stack:
       -
       /Users/rene/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli/lib/project/index.js
       -
       /Users/rene/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli/lib/index.js
       -
       /Users/rene/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli/index.js
       -
       /Users/rene/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.16.3 (/Users/rene/.nvm/versions/node/v12.16.3/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.14

Capacitor:

   Capacitor CLI      : 3.2.0
   @capacitor/android : not installed
   @capacitor/core    : 3.2.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v12.16.3 (/Users/rene/.nvm/versions/node/v12.16.3/bin/node)
   npm    : 6.14.4
   OS     : macOS Mojave

### Additional Information

Strangely in my actual app this behavior also happens when you navigate from a page with modals to another page with modals. When you open and then close a modal on the new page, the leaving page's modals also get "mounted" on close but i cannot yet repro this in the test repository.

**Comment by liamdebeasi** [comment]
Hey there,

This issue was resolved in Ionic 6, but we forgot to close this out. We recommend updating to the latest version of Ionic 6 to receive a fix for this.

Thanks!
