### ISSUE TITLE
bug: v6 datetime, ionBlur and ionFocus not working

### ISSUE THREAD

**Issue by MaNic1980** [ionic-team/ionic-framework#23842]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I run in an issue with "focus in" and "focus out" of the new "ion-datetime" component.
I have an "div" around the "ion-datetime" and check if the focus is in or outside.
If i click on the days or time, my focus is in like expected, but on the month arrows or the year button, the focus got lost.

https://user-images.githubusercontent.com/66515430/131230483-73d88e3c-aa3a-4a8e-9193-2f134abce962.mp4

 

### Expected Behavior

I expected in the whole "ion-datetime" component, my focus is in.

### Steps to Reproduce

Click inside the day area and then on the month arrows and year button to check the focus.

```
<ion-label>{{label}}</ion-label>
<div tabindex="1" (focusin)="focusin()" (focusout)="focusout()">
    <ion-datetime></ion-datetime>
</div>
```

```
label: string;
focusin() {
    this.label="focusin";
  }

focusout() {
    this.label="focusout";
}
```

### Code Reproduction URL

https://stackblitz.com/edit/ionic-angular-v5-5kjnbu?file=src%2Fapp%2Fapp.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.4
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.3
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v16.8.0 (/usr/local/Cellar/node/16.8.0/bin/node)
   npm    : 7.21.0
   OS     : macOS Big Sur

### Additional Information

https://stackblitz.com/edit/ionic-angular-v5-5kjnbu?file=src%2Fapp%2Fapp.component.html

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please try this again using the `ionBlur` and `ionFocus` events? These events are intended to be used to determine whenever the datetime is focused: https://beta.ionicframework.com/docs/api/datetime#events

**Comment by MaNic1980** [comment]
Hi @liamdebeasi i added the Ionic starter app to the "Additional Information" i hope it is helpfull. 
Just click between the days, month and year.

**Comment by amandaesmith3** [comment]
Thanks for the report, this has been resolved via https://github.com/ionic-team/ionic-framework/pull/23980. The fix will be available in a future release of Ionic.

There are a couple of Webkit bugs which will cause the `ion-datetime` to still lose focus when clicking certain buttons. I've added an explanation and links to the PR under "Other information."
