### ISSUE TITLE
bug: desktop select always focuses first item, does not account for selected item

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23857]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using something like `(ngModel)` on a popover interface in `ion-select`, there will have two highlighted value one is the correct one and one will always be the first one. Screenshot as shown below

<img width="718" alt="Screenshot 2021-09-01 at 3 07 54 PM" src="https://user-images.githubusercontent.com/61012396/131627783-1ecec9cd-e291-4453-93c3-58b1747207bd.png">

### Expected Behavior

When a value is already choosen from `ion-select` the first value from the `ion-select` should not be highlighted as well.

### Steps to Reproduce

```html
<h2>Hover Issue</h2>
  <ion-item lines="inset">
    <ion-label>Time (Select One)</ion-label>
    <ion-select interface="popover" [ngModel]="15">
      <ion-select-option [value]="5">5</ion-select-option>
      <ion-select-option [value]="10">10</ion-select-option>
      <ion-select-option [value]="15">15</ion-select-option>
    </ion-select>
  </ion-item>
```

### Code Reproduction URL

https://github.com/farisfaisalthena/starter-repo

**Comment by amandaesmith3** [comment]
Thanks for the report, I've resolved this via https://github.com/ionic-team/ionic-framework/pull/23991 and the fix will be available in a future release of Ionic.
