### ISSUE TITLE
bug: select does not automatically dismiss when selecting an option when value is a number

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#23856]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using `ion-select` with number values and using the popover interface, I will not be able to select anything. Using the default interface or `action-sheet` will only work. Besides that, if the `value` property is a string then it will not have this issue.

### Expected Behavior

Regardless of the interface, when a `value` property is a number, I should be able to select them

### Steps to Reproduce

```html
    <ion-item lines="inset">
      <ion-label>Time (Select One)</ion-label>
      <ion-select interface="popover">
        <ion-select-option [value]="5">5</ion-select-option>
        <ion-select-option [value]="10">10</ion-select-option>
        <ion-select-option [value]="15">15</ion-select-option>
      </ion-select>
    </ion-item>
```

### Code Reproduction URL

https://github.com/farisfaisalthena/starter-repo

**Comment by amandaesmith3** [comment]
Thanks for the report, I've resolved this via https://github.com/ionic-team/ionic-framework/pull/23998 and the fix will be available in a future release of Ionic.
