### ISSUE TITLE
bug: IonSearchbar double clearn buttons

### ISSUE THREAD

**Issue by jonathan-chin** [ionic-team/ionic-framework#23852]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

when using IonSearchbar in react, two clear buttons show up when viewing on Crhome.

![Screenshot from 2021-08-31 10-56-02](https://user-images.githubusercontent.com/7519412/131526237-cd7ce962-fd3d-4697-bcfc-3ec7d71c997a.png)

both buttons are functional. it seems to have been reported before in #20083 but was closed due to being stale.

### Expected Behavior

only one close button should be shown

### Steps to Reproduce

```
import {
    IonSearchbar
} from '@ionic/react';

export default function TagPicker(){
    return (
        <>
          <IonSearchbar
            onIonChange={(event) => {console.log(event.detail.value);}}
            debounce={1000}
          />
          tag picker
        </>
    );
}
```

### Ionic Info

```
Ionic:

   Ionic CLI : 6.17.0

Utility:

   cordova-res : 0.15.3
   native-run  : not installed globally

System:

   NodeJS : v14.15.4
   npm    : 6.14.10
   OS     : Linux 5.11
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Which version of Chrome are you testing this in?

**Comment by jonathan-chin** [comment]
```
Google Chrome | 92.0.4515.131 (Official Build) (64-bit)
-- | --
Revision | 6b8d6c56ce21e38a72f7c4becb5abc1fa5134f29-refs/branch-heads/4515@{#1933}
OS | Linux
JavaScript | V8 9.2.230.22
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
```

**Comment by liamdebeasi** [comment]
Thanks! Could you reproduce this in an Ionic starter app and provide a link to the repo? I do not see that smaller "X" button on my end, just the one provided by Ionic.

**Comment by jonathan-chin** [comment]
hmm. I tried reproducing from a fresh project and I can't replicate the issue. the project I'm experiencing this in is a [react-redux-firebase](http://react-redux-firebase.com/) project. obviously, I'll go over there and ask but I'm wondering if you have any idea what might be happening? since #20083 also experienced the same issue, there might be something going on?

**Comment by liamdebeasi** [comment]
What version of Ionic are you using in the project where this bug happens? You can run `ionic info` in the project directory to find this.

**Comment by jonathan-chin** [comment]
my package.json says @ionic/react ^5.6.9
the default blank starter uses ^5.5.0, though even after changing it to ^5.6.9 (and clearing node_modules and yarning again), I still couldn't experience it.

hmm. running ionic info in the starter project lists Ionic CLI and Ionic Framework versions. running ionic info in my live project only lists Ionic CLI? is that meaningful?

**Comment by liamdebeasi** [comment]
The live project may not have an `ionic.config.json` so the Ionic version will not show up. If you run `npm ls @ionic/react` in your live project terminal, what does it return?

**Comment by jonathan-chin** [comment]
thanks. correct, it doesn't have ionic.config.json
live is running @5.6.9

**Comment by jonathan-chin** [comment]
I upgraded to 5.6.14 but am still experiencing the same issue

**Comment by liamdebeasi** [comment]
Are you able to send over the repo where you are running into this problem?

**Comment by jonathan-chin** [comment]
it's proprietary code. let me see if I can run a blank react-redux-firebase project and reproduce the issue with that.

**Comment by jonathan-chin** [comment]
bad news: it looks like a lot of work to put together such a repo
good news: some sleuthing has shown the following CSS code hides the non-Ionic close button:

```
input[type="search"]::-webkit-search-decoration,
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-results-button,
input[type="search"]::-webkit-search-results-decoration {
  -webkit-appearance:none;
}
```

any idea why I would need this? I did a quick grep for `::-webkit-search-cancel-button` everywhere and I don't think I have any other style sheets that override this. I see that Ionic has normalize.css that does this for me.

I guess normalize.css wasn't being imported? I don't think there are any good guides on how to properly import styles and themes in @ionic/react (I could be wrong).

**Comment by liamdebeasi** [comment]
Yeah, the `normalize.css` file from `@ionic/react` is what is going to hide the non-Ionic clear button. Here are the CSS files we recommend you import in an Ionic app: https://github.com/ionic-team/starters/blob/main/react/base/src/App.tsx#L1-L15 (All Ionic starter apps come with these imports)

If you import the `normalize.css` file does that fix the issue?

**Comment by jonathan-chin** [comment]
thanks. yes I think that fixes it. I think what happened was I started with a blank starter and just trashed the App.tsx, partially because we're not using typescript
