### ISSUE TITLE
bug: ion-datetime 

### ISSUE THREAD

**Issue by cbuchert-blackthorn** [ionic-team/ionic-framework#23864]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [x] v5.x
- [ ] v6.x

### Current Behavior

Clicking on an `ion-datetime` when its `picker-format` and `display-format` are set to `h:mm A` and its `min` is set to an ISO 8601 timestamp (eg. `new Date().toISOString()`) doesn't render any selectable times.

![Screen Shot 2021-09-01 at 5 09 00 PM](https://user-images.githubusercontent.com/79945002/131757360-9c64158d-6025-430d-b683-8f4b9cd2bd05.png)

### Expected Behavior

The docs (https://ionicframework.com/docs/api/datetime#min-and-max-datetimes) indicate that an ISO 8601 timestamp can be used to set `ion-datetime`'s minimum and maximum values and lists 8 acceptable formats (https://ionicframework.com/docs/api/datetime#iso-8601-datetime-format-yyyy-mm-ddthh-mmz). Per the docs, supplying a 8601 (eg: `2021-09-01T21:32:21.916Z`) to `min` should limit the selectable times accordingly.

### Steps to Reproduce

1. In an Angular HTML template, add the following `ion-datetime` implementation:

```
    <ion-datetime
      placeholder='Not working'
      display-format='h:mm A'
      picker-format='h:mm A'
      min='2021-09-01T21:32:21.916Z'
    ></ion-datetime>
```
2. Serve the project and click on the `ion-datetime` implementation.
3. Notice that it does not render correctly.
4. Weep.

### Code Reproduction URL

https://github.com/cbuchert-blackthorn/ion-datetime-min

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.13.1 (/Users/chris/.nvm/versions/node/v14.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.7.0
   @angular-devkit/build-angular : 12.1.1
   @angular-devkit/schematics    : 12.1.1
   @angular/cli                  : 12.1.3
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI   : 3.1.2
   @capacitor/core : 3.1.2

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 1.4.0

System:

   ios-sim : 8.0.2
   NodeJS  : v14.16.0 (/Users/chris/.nvm/versions/node/v14.16.0/bin/node)
   npm     : 7.20.3
   OS      : macOS Big Sur
   Xcode   : Xcode 12.5 Build version 12E5244e
```

### Additional Information

Thanks for taking a look at this! I have only been able to reproduce the issue with the specified `display-format` and `picker-format`. It seems to work just fine when no format is specified. It also works fine with `yyyy`, `yyyy-MM`, and `yyyy-MM-dd` date strings.

**Comment by willmartindev** [comment]
Hi @cbuchert-blackthorn, `ion-datetime` has been reworked in Framework v6 _(coming soon, beta available for testing now)_ and this has been resolved there. Gonna close this one out. Thanks!
