### ISSUE TITLE
bug: watchers not firing with custom elements build

### ISSUE THREAD

**Issue by miljan-aleksic** [ionic-team/ionic-framework#23876]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The Split Pane Menu is not initially visible even if the screen size is bigger than the minimum mode set.

### Expected Behavior

It should be rendered visible and only be hidden if the screen is smaller than the minimum.

### Steps to Reproduce

This behaviour work as expected in Ionic v5, so its quite easy to reproduce using the exact same configuration. I went ahead and created two codesands:

Ionic 5 with Vue 3 (works as expected)
  -  https://g6dzc.csb.app (source: https://codesandbox.io/s/ionic-5-vue-3-g6dzc)

Ionic 6 with Vue 3 (does not work as expected)
 - https://i2m4n.csb.app/ (source: https://codesandbox.io/s/ionic-6-vue-3-i2m4n)

**Comment by liamdebeasi** [comment]
Thanks for the issue. I can reproduce this. The problem here is that the `visible` watcher in `ion-split-pane` is not firing with the custom elements builds: https://github.com/ionic-team/ionic-framework/blob/next/core/src/components/split-pane/split-pane.tsx#L57-L61

This appears to be fixed in Stencil 2.7.0: https://github.com/ionic-team/stencil/commit/8c375bd4bc1b55e269db69af542fa404714c9b26

**Comment by sean-perkins** [comment]
@miljan-aleksic we believe this issue has been resolved in the latest RC candidate (after reviewing the sandbox examples). 

If the issue still persists after updating, please let us know and open a new issue referencing this one. Thank you!
