### ISSUE TITLE
bug: Bottom Sheet expands beyond safe area

### ISSUE THREAD

**Issue by willmartindev** [ionic-team/ionic-framework#23874]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

An `ion-modal` with `this.breakpoints=[..., 1]` will extend beyond the top safe area:

https://user-images.githubusercontent.com/17113462/132072632-32ff537e-8cbd-43c8-b207-3ac17b5ffc3b.mov

### Expected Behavior

The modal and modal handle should respect the safe area so it isn't covered by the hardware notch in `ios` mode. 

### Steps to Reproduce

1. Init an Ionic starter app
2. Add `<ion-modal breakpoints=[0, 1]></ion-modal>`
3. Run on an iOS device or simulator
4. Open modal and observe

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23884, and a fix will be available in an upcoming release of Ionic Framework.
