### ISSUE TITLE
bug: ios input does not have start padding when used outside ion-item

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/ionic-framework#23881]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

`ion-input` not showing `padding-left` or `--padding-start` on IOS. 

![Screenshot 2021-09-06 at 6 34 46 PM](https://user-images.githubusercontent.com/7135885/132225473-97bb02d3-4024-43f9-9f83-8a3492c97581.png)

### Expected Behavior

It should show padding left on inputs and textareas for IOS same as Android.  

### Steps to Reproduce

`<ion-input placeholder="Enter text here"></ion-input>`

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.17.0 (/Users/fahadaslam/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.10
   @angular-devkit/build-angular : 12.0.5
   @angular-devkit/schematics    : 12.0.5
   @angular/cli                  : 12.0.5
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.2
   @capacitor/android : 3.2.2
   @capacitor/core    : 3.2.2
   @capacitor/ios     : 3.2.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.1

System:

   NodeJS : v14.17.6 (/Users/fahadaslam/.nvm/versions/node/v14.17.6/bin/node)
   npm    : 6.14.15
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. With MD mode we set `--padding-start` to be half of the item padding (https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/input/input.md.vars.scss#L20) and then remove it when using the input in an `ion-item` (https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/input/input.scss#L52-L54). 

The same logic applies for the input in iOS mode, but the difference is we always set `--padding-start` to `0`, so the input never has padding even when used outside of an `ion-item`.

**Comment by Saqib92** [comment]
Temporary Fix i used to add paddings on `ion-input` and `ion-textarea` for iOS only:
add Following CSS to global.scss:

```
.sc-ion-input-ios-h, .sc-ion-textarea-ios-h {
    --padding-start: 10px;
}
```
