### ISSUE TITLE
bug(react): content of inline IonModal has zero height

### ISSUE THREAD

**Issue by willmartian** [ionic-team/ionic-framework#23883]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When presenting an inline `ion-modal` in React, the modal's `ion-content` has zero height.

Adding `height: 100%` to `#ion-react-wrapper` fixes the issue for me: https://github.com/ionic-team/ionic-framework/blob/next/packages/react/src/components/createInlineOverlayComponent.tsx#L120

### Expected Behavior

The `ion-content` should be visible.

### Steps to Reproduce

In an Ionic React starter app, create and display an inline modal.

**Comment by amandaesmith3** [comment]
Resolved via: https://github.com/ionic-team/ionic-framework/pull/23968
