### ISSUE TITLE
bug: IonDatetime's time separator is not alligned

### ISSUE THREAD

**Issue by sujith97** [ionic-team/ionic-framework#23882]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

```
<IonDatetime
  presentation="time"
/>
```
Renders the time with a colon between hours and minutes.

### Expected Behavior

The colon that is rendered is not aligned correctly with the hour and minute values.
Adding some padding bottom will fix it.

### Steps to Reproduce

```
<IonDatetime
  presentation="time"
/>
```

### Ionic Info

```
❯ ionic info

Ionic:

   Ionic CLI       : 6.17.0 (/Users/sbheemir/.nvm/versions/node/v16.5.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.0-beta.5

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.2
   @capacitor/ios     : 3.1.2

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.4.1) : 1.4.0

System:

   NodeJS : v16.5.0 (/Users/sbheemir/.nvm/versions/node/v16.5.0/bin/node)
   npm    : 7.19.1
   OS     : macOS Big Sur
```

### Additional Information

<img width="345" alt="Screen Shot 2021-09-06 at 11 04 21 AM" src="https://user-images.githubusercontent.com/5000631/132251195-9ac00b52-d79b-42ab-8b03-a1363ae66ac1.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue. What browser are you testing this in?

**Comment by sujith97** [comment]
> Thanks for the issue. What browser are you testing this in?

This happens on:
1. Google Chrome Version 93.0.4577.63 (Official Build) (x86_64)
2. Android app (Once deployed using `ionic capacitor run android -l --external`)

**Comment by liamdebeasi** [comment]
Thanks! I am testing this on Chrome 93 and I do not see this issue happening:

![image](https://user-images.githubusercontent.com/2721089/132517540-0c771c05-15cf-47ce-94c8-059fb7afe480.png)

Can you reproduce this in an Ionic starter app and provide a link to the repo?
