### ISSUE TITLE
bug: modal getting ion-page class by default prevents modal content from scrolling

### ISSUE THREAD

**Issue by Jesse-Drivetime** [ionic-team/ionic-framework#23894]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When creating a modal using the ionic framework, the 'ion-page' css class is getting added automatically. This class has 'overflow: hidden' by default and I am unable to override that on my component level without using an '!important' flag. This is preventing me from seeing some of the content in my modal when I expand a list nested inside the modal.

### Expected Behavior

I would expect there to be a way to make my modal content scrollable.

### Steps to Reproduce

Create a modal utilizing the ionic framework and put enough content inside to make it overflow. Then try and change the overflow to scroll and it should appear as if nothing is happening.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.11
   @angular-devkit/build-angular : 0.901.15
   @angular-devkit/schematics    : 9.1.5
   @angular/cli                  : 9.1.5
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI      : 3.1.1
   @capacitor/android : 3.1.1
   @capacitor/core    : 3.1.1
   @capacitor/ios     : 3.1.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Big Sur

### Additional Information

I found this link which Liam has addressed for context: https://gitmemory.com/issue/ionic-team/ionic-framework/23304/860660740

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
