### ISSUE TITLE
bug: @ionic-react Cannot read property 'removeChild' of null (StackManager.transitionPage - StackManager.tsx)

### ISSUE THREAD

**Issue by byurhanbeyzat** [ionic-team/ionic-framework#23898]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

On start the app everything works but the error appears

`StackManager.tsx:175 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null at StackManager.transitionPage`

### Expected Behavior

App should work without errors

### Steps to Reproduce

I don't know exactly what cause the error but I think it's maybe because of this page
where I render page content based on a state, but the first component should always render.
At the same time I don't render or redirect directly to this page after app start.

```
const BackupPage: React.FC = () => {
  const { identity } = useAuth();
  const [step, setStep] = useState(0);

  return (
    <IonPage>
      <IonContent fullscreen scrollY={false}>
        {identity.hasBackup && (<p>..........</p>)}
        {!identity.hasBackup && (
		  <AgreementPage setStep={setStep} isVisible={step === 0} />
		)}
        {!identity.hasBackup && step === 1 && (
          <ShowPhrasePage setStep={setStep} isVisible={step === 1} />
        )}
        {!identity.hasBackup && step === 2 && (
		  <ValidatePhrasePage isVisible={step === 2} />
		)}
      </IonContent>
    </IonPage>
  );
};

export default BackupPage;
```

### Code Reproduction URL

https://github.com/byurhanbeyzat/ionic-react-tabs-test

### Ionic Info
```
Ionic:

   Ionic CLI       : 6.17.0 (/Users/byurhanbeyzat/.nvm/versions/node/v16.3.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.7.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.2.2
   @capacitor/core    : 3.2.2
   @capacitor/ios     : 3.2.2

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.4.1) : 1.4.0

System:

   NodeJS : v16.3.0 (/Users/byurhanbeyzat/.nvm/versions/node/v16.3.0/bin/node)
   npm    : 7.21.1
   OS     : macOS Big Sur
```

**Comment by byurhanbeyzat** [comment]
@liamdebeasi Here is the app itself that I'm working on https://github.com/byurhanbeyzat/ionic-react-tabs-test
I don't know what causes the error to be able to reproduce it again and there is a lot of code
App should run on a real device with USB debugging

**Comment by liamdebeasi** [comment]
Can you include only the code required to reproduce the issue? Having a full app like this makes it challenging for me to debug. I recommend removing your code component by component to see what causes the issue to reproduce.
