### ISSUE TITLE
bug: angular outer tabs receive tab button click events for nested tabs

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23897]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I have the following page setup:

```
- Base Page (Ion Tabs)
  - Page 1 (Ion Tabs)
    - Page 1.1
    - Page 1.2
    - Page 1.3
  - Page 2
  - Page 3
```

The i use nested tabs. This works in general, but i get an error when i change on of the inner tabs:
```
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '...'
```

I debugged a bit and found that the `select()` function of the **IonTabs** is called two times, one for each Tabs, i can see that on the outlet.

### Expected Behavior

The IonTabs should only executed the `select` method for Tabs belongs to this.

### Steps to Reproduce

See page structure above

**Comment by EinfachHans** [comment]
Here is a Repo: https://github.com/EinfachHans/ionic-nested-tabs-bug

Switching the outer tabs (bottom) not cause the error to be shown in console

Switching the inner tabs (top under outer tab 1) cause the error in the console to be shown

**Comment by liamdebeasi** [comment]
I get the following error when trying to run your app:

```
[ng] ./src/app/tab1/tab1-routing.module.ts:12:36-70 - Error: Module not found: Error: Can't resolve './subtab1/subtab1.module' in '/Users/liamdebeasi/Ionic/ionic-nested-tabs-bug/src/app/tab1'
[ng] ./src/app/tab1/tab1-routing.module.ts:16:36-70 - Error: Module not found: Error: Can't resolve './subtab2/subtab2.module' in '/Users/liamdebeasi/Ionic/ionic-nested-tabs-bug/src/app/tab1'
[ng] ./src/app/tab1/tab1-routing.module.ts:20:36-70 - Error: Module not found: Error: Can't resolve './subtab3/subtab3.module' in '/Users/liamdebeasi/Ionic/ionic-nested-tabs-bug/src/app/tab1'
[ng] Error: src/app/tab1/tab1-routing.module.ts:12:36 - error TS2307: Cannot find module './subtab1/subtab1.module' or its corresponding type declarations.
[ng] 12         loadChildren: () => import('./subtab1/subtab1.module').then(m => m.Subtab1PageModule)
[ng]                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: src/app/tab1/tab1-routing.module.ts:16:36 - error TS2307: Cannot find module './subtab2/subtab2.module' or its corresponding type declarations.
[ng] 16         loadChildren: () => import('./subtab2/subtab2.module').then(m => m.Subtab2PageModule)
[ng]                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] Error: src/app/tab1/tab1-routing.module.ts:20:36 - error TS2307: Cannot find module './subtab3/subtab3.module' or its corresponding type declarations.
[ng] 20         loadChildren: () => import('./subtab3/subtab3.module').then(m => m.Subtab3PageModule)
[ng]   
```

**Comment by EinfachHans** [comment]
Damn sorry i forget to add these pages, updated pushed

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@5.8.0-dev.202109082139.16dc6d4
```

**Comment by EinfachHans** [comment]
Yes, the Error disappears! 🎉

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23902, and a fix will be available in an upcoming release of Ionic Framework.
