### ISSUE TITLE
bug(tab-bar): safe area padding not added when slot="top"

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23893]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

We use a `<ion-tab-bar>` that is placed with `slot="top"`. This seems to not respect the safe area for the top

### Expected Behavior

To have a `padding-top: var(--ion-safe-area-top, 0);` in a top placed tab bar

### Steps to Reproduce

- Tabs Starter
- Place it on top

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23895, and a fix will be available in an upcoming release of Ionic Framework.
