### ISSUE TITLE
bug: v6, item padding adds additional spacing to bottom

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-framework#23892]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

```
ion-item {
  --padding-top: 20px;
  --background: red;
}
```

`--padding-top` of this css is not work like v4 - 5. If `--padding-**` is deprecated and recommend `--padding-inner-**`, we should write break changes.

<img width="628" alt="スクリーンショット 2021-09-08 午後11 34 14" src="https://user-images.githubusercontent.com/9690024/132530953-4b077182-d0ea-45d8-85a4-864a6bebc039.png">

Thanks.

### Expected Behavior

<img width="441" alt="スクリーンショット 2021-09-08 午後11 34 32" src="https://user-images.githubusercontent.com/9690024/132529656-e32f0de4-55fd-4a13-9e0b-8ae9385abe6b.png">

### Steps to Reproduce

File is here:
https://github.com/rdlabo/ionic-v6-suggest/pull/1/files

And hosted with netlify:

https://deploy-preview-1--sharp-varahamihira-473c70.netlify.app/

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-beta.5
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Utility:

   cordova-res (update available: 0.15.3) : 0.11.0
   native-run (update available: 1.4.1)   : 1.3.0

System:

   NodeJS : v14.16.0 (/usr/local/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur

**Comment by sean-perkins** [comment]
@rdlabo thanks for reporting this issue.

This has been fixed and will be available in the next release of Ionic 6 (6.0.1 and later).
