### ISSUE TITLE
Can't get IonRadio via testing-library's getByRole / getAllByRole.

### ISSUE THREAD

**Issue by shikelong** [ionic-team/ionic-framework#23905]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

I can't get IonRadio by testing-library's getAllByRole/getByRole method.

### Expected Behavior

I can get IonRadio by role.

### Steps to Reproduce

1. use ionic-cli create a new tab project. 
2. write a component: 
    ```typescript
    
     import { IonItem, IonLabel, IonRadio, IonRadioGroup } from "@ionic/react";
import React from "react";

const Test = (): JSX.Element => {
  return (
    <div>
      <IonRadioGroup value={2}>
        <IonItem>
          <IonLabel>Radio 1</IonLabel>
          <IonRadio slot="start" value={1} />
        </IonItem>
        <IonItem>
          <IonLabel>Radio 2</IonLabel>

          <IonRadio slot="start" value={2} />
        </IonItem>
      </IonRadioGroup>
    </div>
  );
};

export default Test;

    ```
3. write the jest test file:

```typescript
import { screen, render } from "@testing-library/react";
import Test from "./Test";

test("test find radio", () => {
  render(<Test />);

  const radios = screen.getAllByRole("radio");
  expect(radios.length).toBe(2);
});

```

![image](https://user-images.githubusercontent.com/4499997/132619091-6baf8570-d1bc-4084-ad6c-434d9a4de27b.png)

### Ionic Info

Ionic:

   Ionic CLI       : 6.16.3 (/home/rioshi/.nvm/versions/node/v14.15.4/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.11

Capacitor:

   Capacitor CLI      : 3.1.1
   @capacitor/android : not installed
   @capacitor/core    : 3.1.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v14.15.4 (/home/rioshi/.nvm/versions/node/v14.15.4/bin/node)
   npm    : 6.14.10
   OS     : Linux 5.4

**Comment by willmartindev** [comment]
Hi @shikelong, thanks for the issue! Do you still see the issue if you use the following? https://github.com/ionic-team/ionic-react-test-utils

If so, providing a minimal reproduction repo from an Ionic starter app would be helpful to help me debug this.

**Comment by shikelong** [comment]
Of course. This repo includes my test code. Please use it. Regards.

https://github.com/shikelong/IonicUTPlayground 

@willmartian

**Comment by willmartian** [comment]
Hey @shikelong, thank you for your patience with this issue. It looks like this is a bug with how Testing Library interacts with web components (our React components wrap web components) and I am going to do some research on how to best resolve the issue for you.

**Comment by shikelong** [comment]
thanks. Waiting for your good news  👍

**Comment by sean-perkins** [comment]
Hello, thank you for your patience with this issue.

A few things have changed since the last reply. Ionic Framework now has a modern syntax for form controls in v7. With the modern syntax we are able to render an `<input type="radio">` and no longer assign `role="radio"` on the host of the web component.

If you continue to use the legacy syntax (either through manually opting in with `legacy={true}` or using the legacy label syntax), you can query the radios by role, by doing the following:

1. Use the JSDOM test environment

In your `package.json`, update your `test` command to:

```json
"test": "react-scripts test --env=jsdom --transformIgnorePatterns 'node_modules/(?!(@ionic/react|@ionic/react-router|@ionic/core|@stencil/core|ionicons)/)'",
```

2. Initialize Ionic React 

In `src/setupTests.ts` import Ionic React and initialize it:

```ts
import { setupIonicReact } from '@ionic/react';

setupIonicReact();
```

3. Have a test that queries the radio by roles.

For example, with this component:

```tsx
import { IonRadio, IonRadioGroup } from "@ionic/react";
import "./ExploreContainer.css";

interface ContainerProps {}

const ExploreContainer: React.FC<ContainerProps> = () => {
  return (
    <IonRadioGroup value="radio1">
      <IonRadio legacy={true} value="radio1">
        Radio 1
      </IonRadio>
      <IonRadio legacy={true} value="radio2">
        Radio 2
      </IonRadio>
      <IonRadio legacy={true} value="radio3">
        Radio 3
      </IonRadio>
    </IonRadioGroup>
  );
};

export default ExploreContainer;
````

An expected test would be:

```tsx
import { screen, render, waitFor } from "@testing-library/react";
import ExploreContainer from "./ExploreContainer";

test("should have 3 radios", async () => {
  render(<ExploreContainer />);

  await waitFor(() => {
    const radios = screen.getAllByRole("radio");

    expect(radios).toHaveLength(3);
  });
});
```

Let me know if you run into any problems or have any additional questions. I'll add the `needs: reply` label, so that this issue will automatically close if there is no additional feedback or questions. Thank you!
