### ISSUE TITLE
bug: ionTabs with ionTabs (not nested) will lose the selected state

### ISSUE THREAD

**Issue by yimity** [ionic-team/ionic-framework#23906]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

after some operations the ion tabs lose the ‘tab-selected’ state in ui。
also the routeinfo ({routeInfo: props.routeInfo || context.routeInfo || {pathname: window.location.pathname}) from the IonTabBarContainer was also incorrent.
![image](https://user-images.githubusercontent.com/4271704/132621670-9dcc7558-fb7f-479f-8632-d038c88a3dd0.png)

### Expected Behavior

show the correct state in ui and state

### Steps to Reproduce

visit it in browser.
1. click 'Go List Page'.
2. click each ListTab 3 -> ListTab 2 -> ListTab 1
3. click the back button of the browser
4. it shows.

### Code Reproduction URL

https://github.com/yimity/ionic-tab-demo

### Ionic Info

Ionic:
   Ionic CLI       : 6.17.1
   Ionic Framework : @ionic/react 5.7.0

Capacitor:
   Capacitor CLI      : 3.2.2
   @capacitor/android : not installed
   @capacitor/core    : 3.2.2
   @capacitor/ios     : not installed

Utility:
   cordova-res : not installed globally
   native-run  : 1.4.1

System:
   NodeJS : v14.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10

### Additional Information

demo : https://codesandbox.io/s/twilight-cache-z7dtc?file=/src/App.tsx

**Comment by liamdebeasi** [comment]
Thanks for the issue. Your routing configuration is incorrect which is resulting in React Router not being able to direct to the correct tabs instance. While we do not recommend having two sets of tabs (it tends to make for a confusing user experience), they both need to live under route prefixes if you need them in your app. Additionally, your list route was not being rendered inside of an `IonRouterOutlet`

Your new app component should look something like this:

```jsx
  <IonApp>
    <IonReactRouter>
      <IonRouterOutlet>
        
        <Route path="/list">
          <List />
        </Route>
        
        <Route path="/tabs">
          <IonTabs>
            <IonRouterOutlet>
              <Route exact path="/tabs/tab1">
                <Tab1 />
              </Route>
              <Route exact path="/tabs/tab2">
                <Tab2 />
              </Route>
              <Route path="/tabs/tab3">
                <Tab3 />
              </Route>
              <Route exact path="/tabs">
                <Redirect to="/tabs/tab1" />
              </Route>
            </IonRouterOutlet>
            <IonTabBar slot="bottom">
              <IonTabButton tab="tab1" href="/tabs/tab1">
                <IonIcon icon={triangle} />
                <IonLabel>Tab 1</IonLabel>
              </IonTabButton>
              <IonTabButton tab="tab2" href="/tabs/tab2">
                <IonIcon icon={ellipse} />
                <IonLabel>Tab 2</IonLabel>
              </IonTabButton>
              <IonTabButton tab="tab3" href="/tabs/tab3">
                <IonIcon icon={square} />
                <IonLabel>Tab 3</IonLabel>
              </IonTabButton>
            </IonTabBar>
          </IonTabs>
        </Route>
        
        <Redirect path="/" to="/tabs" exact />
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
```

 Making these changes resolved the issue on my end. Thanks!
