### ISSUE TITLE
feat: sheet modal programmatically move to a breakpoint

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#23917]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I have some feature requests for the new v6 Sheet Modal that all kinda belongs to each other:

## Auto calculated height
It would be great to make the modal have the height of the content, not more, not less. The library we are currently using (https://github.com/roman-rr/cupertino-pane) has such an option.

## Disable Drag Gesture
It would be great do be able to dynamically enable/disable the Drag Gesture

## Manual move to Breakpoint
It would be great to be able to have a method on the modal like `moveToBreakpoint()`, where i can dynamically move to a breakpoint.

### Describe the Use Case

These three requests should work all together, image the following use case:

I want to show a Sheet Modal that has only a checkbox and a button below.
This should have the height of the content (Request No 1).
Dragging on this Sheet should be disabled (Request No 2).
If the users selects (or unselects) the checkbox some more content will be shown. After that i want to dynamically move the Breakpoint (Request No 3).
Also this `moveToBreakpoint()` method should of course accept numbers for the breakpoint, but also accepts something like `'auto'` to adjust the height on the current content (which changes with the checkbox)

 I hope i described it understandable 😃

**Comment by liamdebeasi** [comment]
Can you provide a code example of how this currently works using the Cupertino pane?

**Comment by EinfachHans** [comment]
See [here](https://github.com/roman-rr/cupertino-pane#common-configuration): There is the option **fitHeight**

**Comment by liamdebeasi** [comment]
Sorry, my last comment was confusing. What I was asking for is a code example of how this is working with regards to your use case. I am interested in seeing how you are applying the feature from Cupertino Pane to address the use case that you have.

**Comment by EinfachHans** [comment]
I create the pane with 

```
this.drawer = new CupertinoPane('#drawerPane', {
  showDraggable: false,
  fitHeight: true
});
```

It offers a function [`calcFitHeight()`](https://github.com/roman-rr/cupertino-pane#calcfitheight) which i can use after the content changes (the checkbox in my example).
Also i can disable the dragging: [`disableDrag()`](https://github.com/roman-rr/cupertino-pane#disabledrag) and switch between breakpoints is possible via [`moveToBreak()`](https://github.com/roman-rr/cupertino-pane#movetobreaktop--middle--bottom)

**Comment by liamdebeasi** [comment]
I can see the value in programmatically moving the sheet to a certain breakpoint, but what is the use case here for disabling dragging on the sheet modal? The sheet is designed to be dragged/swiped, and disabling that breaks the primary usage of the sheet.

Also what is the use case for `calcFitHeight`? By default the sheet modal will take up the full height of the screen. It sounds like this behavior already exists in Ionic.

**Comment by EinfachHans** [comment]
As described i want to have the Sheet have a height to fit the content. After the content changes `calcFitHeight()` would recalculate this.

Disabling the Drag would be for this use case as well as the sheet should only have one breakpoint (the auto height one) so dragging it down or up shouldn't be possible

**Comment by liamdebeasi** [comment]
Can you provide an example of the sheet height changing? I have not seen this used in native apps.

> Disabling the Drag would be for this use case as well as the sheet should only have one breakpoint (the auto height one) so dragging it down or up shouldn't be possible

Maybe I am misunderstanding the use case, but this sounds like a regular modal with a custom height/styles?

**Comment by DavidStrausz** [comment]
I agree, disabling dragging (and also dismissing by dragging it down) the sheet modal would be a welcome addition. 
In our projectes we often have use-cases where we display the user some (short) info along with a checkbox or only an action button - in this case I would like to use a sheet modal with one breakpoint which can't be dragged or dismissed execpt if the user presses the button (or checks the checkbox and then presses the button) - think agreeing to T&Cs or GDPR etc.

**Comment by EinfachHans** [comment]
I don't know if i have seen this in a native app, but i bet it's possible somehow 😃🤔

Yeah i use case is like @DavidStrausz described. Of course a normal Modal would work here too, but it should be a Sheet Modal (including handle etc)

**Comment by liamdebeasi** [comment]
We have plans to implement a `canDismiss` feature for `ion-modal` which should cover the use cases described here (I.e. not allowing dismiss until a user checkbox a box on the modal). This is being tracked on https://github.com/ionic-team/ionic-framework/issues/22297.

In terms of resizing the modal to fit the height, I am not sure that API is a good fit for Ionic since we already expose a `--height` CSS Variable that you can use to adjust the height of the modal dynamically.

Being able to programmatically move to a certain breakpoint seems useful, so I can mark that as a feature request. Any updates regarding that feature will be posted on this thread. Thanks!

**Comment by not-a-designer** [comment]
I am trying to implement a sheet modal as a footer toolbar with a `fab-button` that works as a toggle between min/init breakpoint and .5. It feels a little more intuitive sometimes to see the top edge of a sheet to know its there

so on `ngOnInit()` i present the modal already (backdrop breakpoint greater than initial) and then i want to click on the `fab-button` to expand the modal to halfway. a `moveToBreakpoint()` would be really useful in this use case

**Comment by jeremyw189** [comment]
Any news on programmatically moving to breakpoints? Hopefully that would include the ability to get the current breakpoint as well.

**Comment by philkonick** [comment]
Bumping for news on programmatically moving to breakpoints? 

I have a few more related features I'd like to see too:
- Enabling dragging only on the handle to allow for scrollable content in the modal.
- Allowing px defined breakpoints (auto-height based on contents would also work for our use case)

The library we are currently using ([https://github.com/arielfaur/ionic-pullup](https://github.com/arielfaur/ionic-pullup)) has these features but it requires a lot of work-arounds and code duplication, we would love to be able to migrate to a simple, bundled component.

**Comment by EinfachHans** [comment]
I created a PR which activates the possibility to do this: #24648

**Comment by jeremyw189** [comment]
> Bumping for news on programmatically moving to breakpoints?
> 
> I have a few more related features I'd like to see too:
> 
> * Enabling dragging only on the handle to allow for scrollable content in the modal.
> * Allowing px defined breakpoints (auto-height based on contents would also work for our use case)
> 
> The library we are currently using (https://github.com/arielfaur/ionic-pullup) has these features but it requires a lot of work-arounds and code duplication, we would love to be able to migrate to a simple, bundled component.

I would love to see those features as well. Until then, I'm using this method to get breakpoints at 120px, 290px, and 100%. It's not great but it get's the job done for now.

`breakpoints = [
  120 / this.platform.height(),
  290 / this.platform.height(),
  1
];

initialBreakpoint = 290 / this.platform.height()`

**Comment by MartinR2295** [comment]
Beside the feature to move to a breakpoint programmatically, it would be also great, if there is some method, to listen to breakpoint changes.

Example: I want to show an element e, if I reach the breakpoint b. 
onBreakpoint(breakpoint) {
    if (breakpoint.value === 0.5) {
        showElementE();
    }
}

**Comment by EinfachHans** [comment]
@MartinR2295 my [PR](https://github.com/ionic-team/ionic-framework/pull/24648) adds also two methods: `ionModalBreakpointWillChange/breakpointWillChange` and `ionModalBreakpointDidChange/breakpointDidChange`

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24648, and a fix will be available in an upcoming release of Ionic Framework.
