### ISSUE TITLE
bug: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by GooryDev** [ionic-team/ionic-framework#23918]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Hi.

I'm trying to make deploy to a firebase hosting, after i run "ionic build -c production" i try to make the deploy but when is trying to upload the files happens an error.

> Error: Task ebfedf96e9738569d313163848e141f68bcded7bd5e4871490b648854b08f08d failed: retries exhausted after 6 attempts, with error: The "path" argument must be of type string. Received undefined

Then i search in the deploy task cache and after search the index i found this

> svg/stats-chart-outline.svg,499162500000,ebfedf96e9738569d313163848e141f68bcded7bd5e4871490b648854b08f08d

I tried whit a lot of diferent types of build but always mark the same error in a random "svg/file".

> 

### Expected Behavior

A normal deploy to my website

### Steps to Reproduce

- run any of the next commands
`ionic build --prod` `ionic build -c production`

- run `firebase deploy --only hosting`

### Ionic Info

Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\gesad\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.12
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Utility:

   cordova-res : not installed
   native-run  : 1.4.0

System:

   NodeJS : v14.17.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.7
   OS     : Windows 10

**Comment by willmartindev** [comment]
Hi @GooryDev, thanks for the issue! A minimal reproduction repo would be helpful for me to see what is going on here.
