### ISSUE TITLE
bug: Ionic 5 SSR: ERROR TypeError: Cannot redefine property: constructorbug: 

### ISSUE THREAD

**Issue by khaled-elrifaay** [ionic-team/ionic-framework#23916]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [x] v5.x
- [ ] v6.x

### Current Behavior

Adding Ionic SSR to the project is, the SSR server when running shows "self is not defined", the same for document and window.

Adding this piece of code in the server.ts file, as shown in some threads:

const domino = require('domino');

const templateA = readFileSync(join(distFolder, indexTemplate)).toString();
const win = domino.createWindow(templateA);
(win as any).Object = Object;
(win as any).Math = Math;
global['self'] = win; //TODO: Is giving ERROR TypeError: Cannot redefine property: constructor at Function.defineProperty
global['window'] = win;
global['win'] = win;
global['branch'] = null;

### Expected Behavior

any library can solve this issue .

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.7.0
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.2
   @capacitor/android : not installed
   @capacitor/core    : 3.2.2
   @capacitor/ios     : 3.2.2

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.1

System:

   NodeJS : v12.22.6 (/usr/bin/node)
   npm    : 6.14.15
   OS     : Linux 5.4

**Comment by willmartindev** [comment]
Hi @khaled-elrifaay, thanks for the issue! A minimal reproduction repo would be helpful for me to see what is going on here.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
