### ISSUE TITLE
feat: Refactor the ion-fab component

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-framework#23924]
### Prequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The ion-fab is a really handy component, and it looks great in Ionic toolset, but right now, when you really use it, in a real app (not a mockup) it has many issues and it can be a real struggle to work with. I encountered a lot of issues implementing a ion-fab in my app and if I had the choice again, I would not use the ion-fab component but a third-party one, since I already implemented it at start, I now have several hacks to fix the different issues (some opened over a year ago ...).

It may use a global refactor to make it really usable.

- [ ] https://github.com/ionic-team/ionic-framework/issues/22564
- [ ] https://github.com/ionic-team/ionic-framework/issues/21772
- [ ] https://github.com/ionic-team/ionic-framework/issues/21992
- [ ] https://github.com/ionic-team/ionic-framework/issues/22881
- [ ] https://github.com/ionic-team/ionic-framework/issues/21346
- [ ] https://github.com/ionic-team/ionic-framework/issues/21678
- [ ] https://github.com/ionic-team/ionic-framework/issues/21526

### Describe the Use Case

* As stated in https://github.com/ionic-team/ionic-framework/issues/21678, it would be great to have a global refactor, that allows to control fab state manually
* Implement new material design guidelines
* Correct the issues

**Comment by liamdebeasi** [comment]
Thank you for the feedback on this! We will definitely keep this in mind when planning our roadmaps. However, I am going to close this out in favor of the existing fab issues as having one main thread makes it hard for us to track progress on the individual issues.

We will provide updates for each issue on their respective GitHub threads as we have them. Thanks!
