### ISSUE TITLE
feat: Allow data-testid on <IonSelectOption> to run unit test in the interface

### ISSUE THREAD

**Issue by JochemG** [ionic-team/ionic-framework#23921]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Make unit testing the <IonSelectOption> easier.

### Describe the Use Case

Unit testing is an important element of software development. Our team uses test-library/react with Jest to run unit tests on Ionic/React. We prefer to use the "data-testid" property for our unit tests as this has build in support for the test-library/react and allows us to remove all the testid's in the production build so that there is no test code remaining.

Our team is having issues firing a click event on the IonSelectOption's from our unit tests without adding test specific cssClass or dig through the DOM.

### Describe Preferred Solution

Would it be possible for Ionic to support the "data-*" properties to be propagated to the IonSelect interface as shown below?

(Note the <IonSelectOption **data-testid={...}**> which we think would be the preferred solution)
```
// App.tsx 
export function App() {
  return <IonSelect data-testid={"languageSelector"} slot='end' interface="popover"
            value={"fr"} placeholder={"FR"} onIonChange={e => setLanguage(e.detail.value)}>
            <IonSelectOption value="fr" data-testid={"languageSelectorFr"}>FR</IonSelectOption>
            <IonSelectOption value="nl" data-testid={"languageSelectorNl"}>NL</IonSelectOption>
  </IonSelect>
}

// App.test.tsx
test('change language', () => {
    const rendered = render(<App/>);
    // Open the ion-select-popover
    fireEvent(
      getByTestId(rendered.container, 'languageSelector'),
      new MouseEvent('click', {
        bubbles: true,
        cancelable: true,
      }),
    );
    // Select the FR language from the ion-select-popover
    fireEvent(
      getByTestId(rendered.container, 'languageSelectorFr'),
      new MouseEvent('click', {
        bubbles: true,
        cancelable: true,
      }),
    );
    
    expect(window.document.body.innerHTML).toMatchSnapshot();
}
```

**Comment by liamdebeasi** [comment]
Hey there,

I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/22917. This issue notes `aria-label` instead of `data-testid`, but both relate to the same underlying bug.
