### ISSUE TITLE
bug: ion-datetime freeze inside modal with custom width and height

### ISSUE THREAD

**Issue by xbrancher** [ionic-team/ionic-framework#23925]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Datetime wheels are not shown after datetime input is clicked in a modal with custom width and height.

![IMG_0036](https://user-images.githubusercontent.com/41447192/133261631-0d844899-9eba-4449-a831-4dddeb837d1a.jpg)

### Expected Behavior

Datetime wheels should be shown immediately after datetime input is clicked.

### Steps to Reproduce

- create modal
- add `ion-datetime` input into modal
- create custom class for modal:
  ```
  .modal-xxl .modal-wrapper {
    --width: 94vw;
    --min-width: 94vw;
    --max-width: 94vw;
    --height: 94vh;
    --min-height: 94vh;
    --max-height: 94vh;
  }
  ```
- open modal with `modal-xxl` cssClass
  ```
  this.modalCtrl.create({
    component: ExampleModalComponent,
    cssClass: 'modal-xxl'
  }).then(modal => modal.present()); 
  ```

### Code Reproduction URL

https://github.com/xbrancher/ionic-modals-issue

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (~/.nvm/versions/node/v14.15.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.7.0
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.2
   @capacitor/android : not installed
   @capacitor/core    : 3.2.2
   @capacitor/ios     : 3.2.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.1

System:

   NodeJS : v14.15.3 (~/.nvm/versions/node/v14.15.3/bin/node)
   npm    : 6.14.9
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue. `ion-datetime` has been redesigned for Ionic v6 and this should be resolved there, so I am going to close this issue.

Please see https://github.com/ionic-team/ionic-framework/blob/next/BETA.md if you are interested in getting started with the Ionic v6 beta.
