### ISSUE TITLE
bug: <IonSelect /> not showing select options on iOS

### ISSUE THREAD

**Issue by iAMkVIN-S** [ionic-team/ionic-framework#23922]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v6.x

### Current Behavior

When using the **<IonSelect />** component, the **<IonSelectOption /> s** do not show up on iOS.

It seems to work perfectly on Chrome using _ionic serve_ but when I build onto my iPhone XR via Xcode, I see the touch input (the select field background highlights), but no UI from which to select options.

At first I thought it was something specific to my code, but it also happens when running the [Single Selection Example](https://ionicframework.com/docs/api/select#usage) in the documentation.

I also tried the selection interface with Alert, Action sheet and Popover options. Same result.

Code:
![image](https://user-images.githubusercontent.com/40800721/133183787-d5b5bf56-60b2-4ff6-b3e4-733efdacb52c.png)

iOS Behavior: ("Gender" is clicked, but no option UI)
![image](https://user-images.githubusercontent.com/40800721/133184243-91ae3ce0-e336-4cdb-b4ea-ec5c5b677ad5.png)

### Expected Behavior

The selectable options should appear on iOS just as they do on Chrome.

Expected Behavior:
![image](https://user-images.githubusercontent.com/40800721/133183881-048bb495-76c1-4e9d-8251-bc22ecfe24cc.png)

### Steps to Reproduce

- Use the [Single Selection Example](https://ionicframework.com/docs/api/select#usage) from the documentation in a blank Ionic Project
- _Ionic Serve_ to **notice the selectable options appear properly in the web browser**
- _ionic build_
- _npx cap copy ios_
- _npx cap open ios_
- Build the Xcode project onto your connected iOS device
- **notice that there are no UI's to select your options from**

### Ionic Info

Ionic:

   Ionic CLI       : 6.12.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.0-dev.202109081634.78849be

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.1

System:

   NodeJS : v14.4.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Big Sur

### Additional Information

Tested on iPhone XR running iOS 14.7.1
Tested on iPhone 12 via Xcode's emulator

**Comment by liamdebeasi** [comment]
Thanks for the issue. It looks like you are using a development build of Ionic. Can you please try this again using the latest beta version of Ionic v6?

**Comment by iAMkVIN-S** [comment]
Hello Liam,

Thank you for the prompt reply!

It seems like using the @latest v6 beta solved the issue:

Ionic:

   Ionic CLI       : 6.12.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.0-beta.5

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.1

System:

   NodeJS : v14.4.0 (/usr/local/bin/node)
   npm    : 6.14.5
   OS     : macOS Big Sur

![image](https://user-images.githubusercontent.com/40800721/133265201-6d033cf2-f18a-4a6a-8a24-9dd71b36829e.png)

That being said, I don't believe I had originally manually selected to be on the development build of ionic, was it just the @latest when I happened to create this project? 

Cheers

**Comment by liamdebeasi** [comment]
Glad it is fixed! You may have accidentally typed `dev` somewhere when installing which installed a development build of Ionic v6. We do not put dev builds on the `latest` tag on npm.
