### ISSUE TITLE
bug: ionic 6 white screen on android 11 

### ISSUE THREAD

**Issue by alitalaee** [ionic-team/ionic-framework#23933]
### Prequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Hello 

ionic 6 application show white screen on android 11 when try to run my app. 

i did upgrade

- cordova to version 10.1.0 
- android studio to latest version 
- gradle to version 7.1.1 
- installed android sdk build tools (below image)
- remove whitelist plugin from project 
- update config.xml with 

`
<preference name="android-targetSdkVersion" value="30" />
    <preference name="android-compileSdkVersion " value="30" />
    <preference name="android-minSdkVersion" value="22" />

  <preference name="hostname" value="localhost" />
    <preference name="AndroidInsecureFileModeEnabled" value="true" />
`
please check [this link](https://forum.ionicframework.com/t/ionic-application-not-installed-on-android-11/214997/5) on ionic froum for more information 

### Steps to Reproduce

install cordova 10

### Ionic Info

ionic version 6

**Comment by liamdebeasi** [comment]
Thanks for the issue. What version of the Chromium WebView are you using? You can find this out by running `window.navigator.userAgent` in the dev tools console when inspecting your app.
