### ISSUE TITLE
bug: toast overlaps fab at bottom

### ISSUE THREAD

**Issue by shyamal890** [ionic-team/ionic-framework#23938]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Currently if both the toast and Fab button at present at the bottom of the screen the Fab button gets covered by the toast. So lets, say a user saved something and wants to add a new item he has to wait for toast to go away.

### Expected Behavior

Incase toast and fab button both are present at the bottom. Fab button should move up so that user can immediately click on button and move forward.

### Steps to Reproduce

Simply have fab icon in the bottom and trigger a bottom position toast

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\Shyamal\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.11
   @angular-devkit/build-angular : 0.1102.14
   @angular-devkit/schematics    : 11.2.14
   @angular/cli                  : 11.2.14
   @ionic/angular-toolkit        : 3.1.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.4.7, (and 20 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run (update available: 1.4.1)   : 0.2.7

System:

   NodeJS : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.13.0
   OS     : Windows 10

### Additional Information

This issue was already created earlier by me with no resolution, yet it was closed down by the bot - https://github.com/ionic-team/ionic-framework/issues/12139

**Comment by liamdebeasi** [comment]
Hi there,

In [Ionic 7.5.0](https://github.com/ionic-team/ionic-framework/releases/tag/v7.5.0) we added a feature to toast that lets you anchor the toast relative to a specific element. This lets you ensure that the toast never overlaps the fab.

Documentation for this feature is available at https://ionicframework.com/docs/api/toast#relative-positioning.
