### ISSUE TITLE
bug: position: fixed container isn't aligned properly on all browsers

### ISSUE THREAD

**Issue by trytuna** [ionic-team/ionic-framework#23959]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I've discovered a weird inconsistency of browser behaviour. Take a look at this sample Application:

https://stackblitz.com/edit/ionic-txglcj
Ionic v5 demo project: https://github.com/trytuna/ionic-ui-inconsistency

The main actor here is the red `div.footer` which should be positioned 6px above the `ion-tabbar`. However it seems that Firefox/Safari and Chrome have different opinions. Firefox/Safari are doing the "right" rendering in my eyes.

![Firefox - the intended result](https://user-images.githubusercontent.com/128096/134148390-f3cacd6f-737d-4501-9f26-7db0b86adab1.png)

![Chrome](https://user-images.githubusercontent.com/128096/134148552-e0fd5a2f-5d1a-4ea2-9979-c7ee3e41e205.png)

I've tried to replicate this issue in a plain html/css application (https://stackblitz.com/edit/js-yy2kqk) but I couldn't get the same result. This leads me to issue the bug on the ionic framework.

### Expected Behavior

Should behave the same on Chrome and Firefox/Safari

### Steps to Reproduce

See `Current Behavior`

### Ionic Info

I've tested it on Ionic 3 (see stackblitz links above) and Ionic 5.6.14.

% ionic info

Ionic:

   Ionic CLI                     : 6.17.1 (/Users/timo/.nvm/versions/node/v12.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.14
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.2
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 2.4.5
   @capacitor/android : 2.4.5
   @capacitor/core    : 2.4.5
   @capacitor/ios     : 2.4.5

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v12.18.2 (/Users/timo/.nvm/versions/node/v12.18.2/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur
   Xcode  : Xcode 12.5.1 Build version 12E507

**Comment by trytuna** [comment]
Thanks for the fast reply. It's no problem to provide an example project.

There you go: https://github.com/trytuna/ionic-ui-inconsistency

**Comment by liamdebeasi** [comment]
Thanks! This looks to be related to our usage of `contain` on several elements. We already have an issue open related to this, so I am going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/20087.
