### ISSUE TITLE
bug: Ionicons not showing up on iOS device with ionicons 5 and ionic 5 bug: 

### ISSUE THREAD

**Issue by shilpidaswani** [ionic-team/ionic-framework#23950]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

when build with ios, icons and some assets images are not loading,
gives error of not found. I am using Ionic-core 5.36 and angular 12

### Expected Behavior

when built with android/ios/browser, icons and images should load

### Steps to Reproduce

<ion-icon ios="heart-circle" md="heart-sharp"></ion-icon>
<ion-icon name="sync"></ion-icon>
<ion-icon src="./assets/icons/calender-ouline.svg"></ion-icon>  // Loading from assets is not loading icon.

### Ionic Info

package.json

{
  "name": "Demo",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.2.6",
    "@angular/cdk": "^12.2.6",
    "@angular/common": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/flex-layout": "^12.0.0-beta.35",
    "@angular/forms": "~12.1.1",
    "@angular/material": "^12.2.6",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "@angular2-material/slide-toggle": "^2.0.0-alpha.8-3",
    "@ionic-native/app-launcher": "^5.36.0",
    "@ionic-native/background-fetch": "^5.36.0",
    "@ionic-native/background-mode": "^5.36.0",
    "@ionic-native/core": "^5.36.0",
    "@ionic-native/device": "^5.36.0",
    "@ionic-native/email-composer": "^5.36.0",
    "@ionic-native/file": "^5.36.0",
    "@ionic-native/file-opener": "^5.36.0",
    "@ionic-native/file-picker": "^5.36.0",
    "@ionic-native/file-transfer": "^5.36.0",
    "@ionic-native/http": "^5.36.0",
    "@ionic-native/in-app-browser": "^5.36.0",
    "@ionic-native/keyboard": "^5.36.0",
    "@ionic-native/local-notifications": "^5.36.0",
    "@ionic-native/native-keyboard": "^5.36.0",
    "@ionic-native/native-storage": "^5.36.0",
    "@ionic-native/network": "^5.36.0",
    "@ionic-native/pin-check": "^5.36.0",
    "@ionic-native/safari-view-controller": "^5.36.0",
    "@ionic-native/screen-orientation": "^5.36.0",
    "@ionic-native/speech-recognition": "^5.36.0",
    "@ionic-native/splash-screen": "^5.36.0",
    "@ionic-native/sqlite": "^5.36.0",
    "@ionic-native/status-bar": "^5.36.0",
    "@ionic-native/touch-id": "^5.36.0",
    "@ionic/angular": "^5.5.2",
    "@ionic/storage": "^3.0.6",
    "@material-extended/mde": "^3.0.3",
    "@material/snackbar": "^12.0.0",
    "@ng-select/ng-select": "^7.2.0",
    "@ngx-pwa/local-storage": "^12.1.0",
    "angular-highcharts": "^12.0.0",
    "angular-material-expansion-panel": "^0.7.2",
    "angular-ng-autocomplete": "^2.0.5",
    "angular-progress-bar": "^1.0.11",
    "angular-tree-component": "^8.5.6",
    "axios": "^0.21.4",
    "chart.js": "^2.9.3",
    "cordova-plugin-app-launcher": "^0.4.0",
    "cordova-plugin-background-fetch": "^7.0.3",
    "cordova-plugin-background-mode": "^0.7.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-email-composer": "^0.9.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^3.0.5",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-filepicker": "^1.1.6",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",
    "cordova-plugin-native-keyboard": "^2.0.6",
    "cordova-plugin-network-information": "^3.0.0",
    "cordova-plugin-pincheck": "0.0.6",
    "cordova-plugin-safariviewcontroller": "^2.0.0",
    "cordova-plugin-speechrecognition": "^1.2.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-sqlite-2": "^1.0.7",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-touch-id": "^3.4.0",
    "highcharts": "^9.2.2",
    "is-base64": "^1.1.0",
    "lodash": "^4.17.21",
    "mat-sidenav-menu": "^0.10.1",
    "moment": "^2.29.1",
    "nanoid": "^3.1.25",
    "ng-block-ui": "^3.0.2",
    "ng2-charts": "^2.3.0",
    "ngx-localstorage": "^3.4.0",
    "ngx-moment": "^5.0.0",
    "ngx-pipes": "^2.7.5",
    "ngx-scroll-event": "^2.0.2",
    "ngx-sortablejs": "^11.1.0",
    "pouchdb": "^7.2.2",
    "pouchdb-adapter-cordova-sqlite": "^2.0.8",
    "pouchdb-find": "^7.2.2",
    "pouchdb-upsert": "^2.2.0",
    "rxjs": "~6.6.0",
    "sortablejs": "^1.14.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular-eslint/builder": "~12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "12.1.4",
    "@angular/compiler": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@angular/language-service": "~12.0.1",
    "@ionic/angular-toolkit": "^4.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@types/pouchdb": "^6.4.0",
    "@typescript-eslint/eslint-plugin": "^4.16.1",
    "@typescript-eslint/parser": "^4.16.1",
    "cordova-android": "^8.1.0",
    "cordova-ios": "~4.3.1",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-whitelist": "^1.3.3",
    "eslint": "^7.6.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "query-string": "^7.0.1",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-file-opener2": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-file": {},
      "cordova-plugin-safariviewcontroller": {},
      "cordova-plugin-app-launcher": {},
      "cordova-plugin-email-composer": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-device": {},
      "cordova-plugin-native-keyboard": {
        "LICENSE": "TRIAL",
        "LIC_ANDROID": "TRIAL"
      },
      "cordova-plugin-network-information": {},
      "cordova-plugin-sqlite-2": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-filepicker": {},
      "cordova-plugin-pincheck": {},
      "cordova-plugin-touch-id": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-androidx": {},
      "cordova-plugin-androidx-adapter": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
}

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
