### ISSUE TITLE
bug: angular, tab select method has wrong types

### ISSUE THREAD

**Issue by conde2** [ionic-team/ionic-framework#23952]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

After updating to new ionic the 5.8 I can't select my IonTabs using string object anymore.

https://github.com/ionic-team/ionic-framework/commit/1ed9f07060736d0c951910427fb12b250d7dd9af#commitcomment-56780145

### Expected Behavior

Be able to use the select method from IonTabs with string.

### Steps to Reproduce

```
<ion-tabs #appTabs>

```

```
  @ViewChild('appTabs') tabsRef: IonTabs;

  changeTab(tabName: string) {
      this.tabsRef.select(tabName);
  }
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.12.4 (C:\Users\joao_\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.14
   @angular-devkit/build-angular : 0.1100.7
   @angular-devkit/schematics    : 11.2.14
   @angular/cli                  : 11.2.14
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 3.2.0
   @capacitor/core : 3.2.0

Utility:

   cordova-res : not installed
   native-run  : 1.4.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@5.9.0-dev.202109201500.ae1325c
```

**Comment by thomasletallec** [comment]
Hi @liamdebeasi 

We had the same issue in our application. I can confirm the dev build fixes the issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/23953, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by liamdebeasi** [comment]
Ionic 5.8.1 was just released and has this fix. Thanks!

**Comment by thomasletallec** [comment]
Thanks!
