### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by RouR** [ionic-team/ionic-framework#23962]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I`m using WebWorker as it described in docs https://stenciljs.com/docs/web-workers
I see that it work in main thread (Chrome->Debugger->Threads)
UI artefacts also visible for user.

### Expected Behavior

It must work in separate thread

### Steps to Reproduce

https://stenciljs.com/docs/web-workers

* Create src/stuff.worker.ts
* In any angular component use it with ```import { sum, expensiveTask } from '../../stuff.worker';```

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\Alex\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0-dev.202106282030.9f3b1d9
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.1
   @capacitor/android : 3.1.1
   @capacitor/core    : 3.1.1
   @capacitor/ios     : 3.1.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 7.20.0
   OS     : Windows 10```

### Additional Information

It is unclear how to use WebWorkers with Ionic.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is more of a support question. Ionic only concerns itself with its UI components and does not interact with Web Workers. As a result, Web Workers should work in Ionic as they would in any web-based application.

For additional help getting Web Workers setup in your app, I recommend posting on the [Ionic Forum](https://forum.ionicframework.com/)
