### ISSUE TITLE
bug: segment not respecting rtl when dir set on host element

### ISSUE THREAD

**Issue by Mohamed-Karkotly** [ionic-team/ionic-framework#23978]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

When layout is RTL the swipeGesture goes far left to the end when swiped right, and goes far right to the end when swiped left.

### Expected Behavior

Behave the correct way as in LTR.

### Steps to Reproduce

Create an `ion-segment` with attribute `dir="rtl"`, then add few `ion-segment-buttons` inside of it and try swiping.

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.17.1 (node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.8.0
   @angular-devkit/build-angular : 12.2.6
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.2.6
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.3
   @capacitor/android : not installed
   @capacitor/core    : 3.2.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.1

System:

   NodeJS : v14.17.1 (c:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I can reproduce this behavior. This line looks to be the culprit: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/segment/segment.tsx#L310.

We determine RTL by looking at the `document` direction, but we do not look at the `dir` set on the host element.
