### ISSUE TITLE
bug: alert does not match MD spec for tablet dimensions

### ISSUE THREAD

**Issue by amandaejohnston** [ionic-team/ionic-framework#23977]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

All `ion-alert`s in `md` mode have a max width of 280px, and the alert content has a max height of 240px.

### Expected Behavior

Dialogs should scale to 560px by 560px, with a minimum 48px from the top/bottom edges of the dialog and screen.

Source: https://m2.material.io/components/dialogs#behavior Scroll to "Scaling and adaptation."

Possibly worth noting that dialogs covering the whole screen ("Full-screen dialogs" in the MD spec) are handled by the `ion-modal` component.

### Steps to Reproduce

Create any `ion-alert` with sufficient content to max out the current height. Can be seen in a few tests already, like "Radio" in `/alert/test/basic`.

**Comment by liamdebeasi** [comment]
Looks like this primarily impacts apps running on tablets. Here is a screenshot of an alert-style dialog on Android 11:
![Screenshot_1632495359](https://user-images.githubusercontent.com/2721089/134696177-effd313c-d808-4ce9-8dac-7e850fc465f3.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28501, and a fix will be available in an upcoming release of Ionic Framework.
