### ISSUE TITLE
Android resource linking failed (AAPT: error: resource android:attr/lStar not found)

### ISSUE THREAD

**Issue by ipehimanshu** [ionic-team/ionic-framework#23999]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x

### Current Behavior

Hello

Here is our ionic info

Ionic:

Ionic CLI : 6.16.3 (C:\Users\admin\AppData\Roaming\npm\node_modules@ionic\cli)
Ionic Framework : @ionic/angular 5.4.0
@angular-devkit/build-angular : 0.803.25
@angular-devkit/schematics : 9.0.6
@angular/cli : 8.3.26
@ionic/angular-toolkit : 2.2.0

Cordova:

Cordova CLI : 10.0.0
Cordova Platforms : android 9.0.0
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 17 other plugins)

Utility:

cordova-res : 0.15.3
native-run : 1.4.0

System:

NodeJS : v14.17.1 (C:\Program Files\nodejs\node.exe)
npm : 6.14.13
OS : Windows 10

here is plugin list which we are using

com.antOnFire.camera-access 0.1 "Check access to camera on a device"
com.markveys.picture-access 0.0.1 "Check access to pictures on a device"
com.phonegap.plugins.nativesettingsopener 1.2.0 "Native settings"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-calendar 5.1.5 "Calendar"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-keychain-touch-id 3.3.0 "TouchID and Keychain"
cordova-plugin-network-information 3.0.1-dev "Network Information"
cordova-plugin-printer 0.8.0 "Printer"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-universal-clipboard 0.1.0 "Clipboard"
cordova.plugins.diagnostic 6.0.2 "Diagnostic"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"

All is working fine still last day but after that it fire error when we are trying to create release build like

cordova-plugin-androidx-adapter: Processed 74 source files in 1227ms
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: C:\Users\admin\AppData\Local\Android\sdk
Subproject Path: CordovaLib
Subproject Path: app

    Task :app:processReleaseResources FAILED

FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':app:processReleaseResources'.

    A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
    Android resource linking failed
    C:\Users\admin.gradle\caches\transforms-2\files-2.1\082fd8435f96aa3f026dd001121230f9\core-1.7.0-beta02\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    Get more help at https://help.gradle.org

BUILD FAILED in 3s
15 actionable tasks: 1 executed, 14 up-to-date
Command failed with exit code 1: D:[user]\platforms\android\gradlew cdvBuildRelease -b D:[user]\platforms\android\build.gradle
[ERROR] An error occurred while running subprocess cordova.

    cordova.cmd build android --release -- --keystore=instantautosite.keystore --ali... exited with exit code 1.

    Re-running this command with the --verbose flag may provide more information.

### Expected Behavior

It need to success android build

### Steps to Reproduce

So far till last day all is fine, We have not updated any plugin or SDK, so any one please help ?

Thanks

**Comment by Tariqali99** [comment]
Facing the same issue in Ionic 5 :(
