### ISSUE TITLE
bug: getUserMedia black screen on iOS 15 in case new install

### ISSUE THREAD

**Issue by kisbalazs90** [ionic-team/ionic-framework#23997]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Hi,
I'm developing a streaming application to stream via webRTC. On iOS 14.7 and iOS 14.8, all the things work well with the camera. I changed to iOS 15, the video is not presented. (new install on new device)
I updated a device from 14.8 to 15, the app already was installed on the 14.8 os version, but it worked after the update to ios 15 was installed as well.
I've reinstalled it, and the problem os occurred on this phone as well. 
The codebase was untouched.

```
  navigator.mediaDevices.getUserMedia({ audio: true, video: true }).then(
      stream => {
        this.myEl.srcObject = stream;
      },
```

And the video is not playing. 

### Expected Behavior

Start the camera in the app, to stream on iOS 15 as well.

### Steps to Reproduce

I'd created a simple component only to test the camera. 

**video-call.component.ts**
```
import { Component, ElementRef, OnInit } from '@angular/core';

@Component({
  selector: 'app-video-call',
  templateUrl: './video-call.component.html'
})
export class VideoCallComponent implements OnInit {
  myEl: HTMLMediaElement;

  constructor(public elRef: ElementRef) {}

  ngOnInit() {
    this.myEl = this.elRef.nativeElement.querySelector('#my-video');
    navigator.mediaDevices.getUserMedia({ audio: true, video: true }).then(
      stream => {
        this.myEl.srcObject = stream;
      },
      err => console.log(err)
    );
  }
}
```

**video-call.component.html**
```
<div class="wrapper">
    <video id="my-video" playsinline autoplay muted></video>
</div>

```

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 5.8.1
   @angular-devkit/build-angular : 12.2.7
   @angular-devkit/schematics    : 12.2.7
   @angular/cli                  : 12.2.7
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.5.0
   @capacitor/core : 2.5.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.20.1 (/usr/local/bin/node)
   npm    : 6.14.10
   OS     : macOS Big Sur
   Xcode  : Xcode 13.0 Build version 13A233

### Additional Information

I tried to reinstall the node_modules, update the packages, create a new build.
I changed video: true to min, max, and ideal sizes.
I tried to use the device id instead of the user and environment face modes.
I tried with autoplay and manual play with controls.
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

I found a bug report on Xcode https://developer.apple.com/forums/thread/689293
But in my case, I cant see the same log.

The stream is working, just the video is black because my camera is not turning on, but the privileges are always granted. 

info.plist>
NSCameraUsageDescription, NSMicrophoneUsageDescription are there. 

Capacitor update is not possible, because the other 3rd party plugins are not compatible with it.

I found the following as well, but I don't know-how is relevant.
https://developer.apple.com/forums/thread/689293

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this impacting any Ionic applications or does this only have to do with `getUserMedia`?

**Comment by kisbalazs90** [comment]
> Thanks for the issue. Is this impacting any Ionic applications/components or does this only have to do with `getUserMedia`?

It only has to do with getUserMedia.

**Comment by liamdebeasi** [comment]
Thanks! This issue tracker is only for issues impacting Ionic Framework apps, so I am going to close this as this is outside the scope of what Ionic manages.

I definitely recommend filing an issue on the WebKit bug tracker at https://bugs.webkit.org/. Having a minimal reproduction helps the WebKit team fix these issues faster.

Additionally, I recommend joining the [WebKit Slack](https://webkit.org/getting-started/) as WebKit team members are on there and can advise you on how to go about reporting the issue/developing a workaround in your application. Thank you!

**Comment by kisbalazs90** [comment]
**Thanks Liam**!
I was there...

The problem is possibly in the url what the app is using, `capacitor://localhost...` so I should to change this, to http or https.
I can’t change the iosScheme from capacitor to file or any other because is restr
icted to change.

[Here is the manual about capacitor config](https://capacitorjs.com/docs/config)

```
  /**
     * Configure the local scheme on iOS.
     *
     * [Can't be set to schemes that the WKWebView already handles, such as http or https](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/2875766-seturlschemehandler)
     * This can be useful when migrating from
     * [`cordova-plugin-ionic-webview`](https://github.com/ionic-team/cordova-plugin-ionic-webview),
     * where the default scheme on iOS is `ionic`.
     *
     * @since 1.2.0
     * @default capacitor
     */
```

**Application log:**
```
Loading app at capacitor://localhost...
Can't be set to schemes that the WKWebView already handles, such as http or https... https://capacitorjs.com/docs/config
xcode system log from the phone>
    App	UserMediaPermissionRequestManagerProxy::grantRequest(B75AA62ED06DE7FB) 158, video: Front Camera, audio: iPhone Microphone
    App	UserMediaPermissionRequestManagerProxy::processUserMediaPermissionValidRequest(B75AA62ED06DE7FB) 158, action: Grant
    App	UserMediaPermissionRequestManagerProxy::finishGrantingRequest(B75AA62ED06DE7FB) 158
    App	Could not create a 'com.apple.tccd' sandbox extension
    App	Unable to create com.apple.tccd sandbox extension
    App	0x15200d618 - [pageProxyID=5, webPageID=6, PID=6669] WebPageP    default	20:49:08.822745+0200	App	UserMediaPermissionRequestManagerProxy::processUserMediaPermissionValidRequest(B75AA62ED06DE7FB) 158, action: Grant
    App	UserMediaPermissionRequestManagerProxy::grantRequest(B75AA62ED06DE7FB) 158, video: Front Camera, audio: iPhone Microphone
    App	UserMediaPermissionRequestManagerProxy::finishGrantingRequest(B75AA62ED06DE7FB) 158
    App	Could not create a 'com.apple.tccd' sandbox extension
    App	Unable to create com.apple.tccd sandbox extension
    App	0x15200d618 - [pageProxyID=5, webPageID=6, PID=6669] WebPageP
```

**How could I change it from capacitor?**

Thanks in advance! :)

**Comment by liamdebeasi** [comment]
On iOS you cannot customize the scheme to use `http`, `https`, `file`, etc. This is a WKWebView restriction and not something Capacitor has control over.
