### ISSUE TITLE
bug: @ionic/vue v6 can't run build with vite

### ISSUE THREAD

**Issue by Ripwords** [ionic-team/ionic-framework#24005]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

```
node_modules/ionicons/dist/types/components.d.ts:66:15 - error TS2320: Interface 'HTMLIonIconElement' cannot simultaneously extend types 'IonIcon' and 'HTMLStencilElement'.
  Named property 'ariaLabel' of types 'IonIcon' and 'HTMLStencilElement' are not identical.
66     interface HTMLIonIconElement extends Components.IonIcon, HTMLStencilElement {       
                 ~~~~~~~~~~~~~~~~~~
```

![image](https://user-images.githubusercontent.com/58784686/135693873-686bf8c5-5270-4792-8cde-a96780abe688.png)

npm run build (using vite) results in the above error

### Expected Behavior

npm run build with no errors

### Steps to Reproduce

running "npm run build" results in multiple of the above error messages, i found an issue regarding this over a year ago, but it was closed with no explanation on how the bug occurred. 

I am using @ionic/vue V6 with vite

Please let me know if any further details are required 

### Code Reproduction URL

https://github.com/Ripwords/astro-calc

### Ionic Info

![image](https://user-images.githubusercontent.com/58784686/135694093-a93cee97-725d-4763-b95d-5b856da9d431.png)

### Additional Information

Similar issue in [#20208](https://github.com/ionic-team/ionic-framework/issues/20208)

## Update
I was able to track down the issue in ionicons [here](https://github.com/ionic-team/ionicons/issues/1000). It seems to be a typescript version error, however the ionicons repo doesn't seem to be as active and I would rate this issue quite high since typescript is getting more and more popular

**Comment by Ripwords** [comment]
Thanks, I tested it and it's working as expected now. Maybe this could be mentioned for those who are adding ionic as a library instead of using the starter apps. Although that might be the minority of the users.

**Comment by liamdebeasi** [comment]
Glad it works. Yes, I agree this should be mentioned in the docs. I am going to close this issue for now, but we plan on having more docs on getting Ionic setup with Vite when Ionic 6 ships (this is being tracked internally).
