### ISSUE TITLE
bug: Ionic 5.x produces a blank page on Android 5/6/7/8

### ISSUE THREAD

**Issue by obnijnil** [ionic-team/ionic-framework#24013]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

The Ionic project created with Vue produces an empty page instead of the expected page structure (3 Tabs) after the splash screen on Android devices.

The blank page occurs on Android 5/6/7/8, but it's fine on Android 9 and desktop Chrome (Version 94).

### Expected Behavior

As the doc https://ionicframework.com/docs/reference/browser-support#mobile-browsers says, Ionic should fully support the mobile platform (Ionic V5 on Android 5.0+).

The page should looks like:

![localhost_1234_tabs_tab1(Nexus 4)](https://user-images.githubusercontent.com/17563264/135978905-f4108311-f709-4fcc-8b8d-2160b551a4d3.png)

### Steps to Reproduce

Start a new project and build it into an Android app:

```
ionic start myApp tabs --type vue
ionic build
ionic cap add android
```

Run the app in an Android 7 (API 24) virtual device from Android Studio, then the app shows up with a blank page after the splash screen.

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.16.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.8.1

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : 3.2.4
   @capacitor/core    : 3.2.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.1

System:

   NodeJS : v15.13.0 (/usr/local/Cellar/node/15.13.0/bin/node)
   npm    : 7.11.1
   OS     : macOS Big Sur
```

### Additional Information

Same behavior found in these issues:

1. https://github.com/ionic-team/ionic-framework/issues/19002
2. https://github.com/ionic-team/ionic-framework/issues/18923
3. https://github.com/ionic-team/ionic-framework/issues/17913
4. https://github.com/ionic-team/ionic-framework/issues/8939

**Comment by obnijnil** [comment]
@liamdebeasi thx following up.

Using the default WebView shipped with the Android system. Seams like they are all < 60 :(

1. Android 8: Chrome/58
    ```
    Mozilla/5.0 (Linux; Android 8.0.0; Android SDK built for x86 Build/OSR1.170901.027) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.125 Mobile Safari/537.36
    ```
1. Android 7: Chrome/51
    ```
    Mozilla/5.0 (Linux; Android 7.0; Android SDK built for x86 Build/NYC) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.90 Mobile Safari/537.36
    ```

So is there a way the latest WebView can be bundled with the Android .apk, instead of asking the user to update the WebView version manually?

**Comment by liamdebeasi** [comment]
The WebView should automatically update, but certain devices have that feature disabled by the phone vendor. What device are you using?

**Comment by obnijnil** [comment]
We don't expect users using the app with specific devices, but we want to support Android 7 which covers approximately 73.7% of devices.

![image](https://user-images.githubusercontent.com/17563264/136057505-3d4fcd61-d717-4e74-ac0f-ac16af35a631.png)

**Comment by liamdebeasi** [comment]
Of that 73.7%, most of those devices have webviews that autoupdate. A small percentage of devices do not allow the webview to update. This is a device manufacturer restriction and not something Ionic is able to control. (Some devices also ship their own built in webviews which update less frequently than the regular Chromium webviews).

I am going to close this issue as this is not something we can control, but I recommend looking at the "Browser Compatibility" page on the Vue CLI documentation: https://next.cli.vuejs.org/guide/browser-compatibility.html

The "browserslist" file can help determine which JavaScript features need to be transpiled down for older browsers as well as which CSS vendor prefixes are needed. Additionally, the Vue CLI uses the `@vue/babel-preset-app` plugin which you can add to your project to have the CLI determine which polyfills are needed for your project. Using both of those can help get your app to run better on older webviews.

Thanks!
