### ISSUE TITLE
bug: Mobile Safari Keyboard causes scroll issues

### ISSUE THREAD

**Issue by TylerAHolden** [ionic-team/ionic-framework#24047]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When the keyboard is opened in mobile safari, sometimes it seems to be possible to scroll outside of the ion app causing the content to become hidden. It's like some container element is scrollable when it shouldn't be.

### Expected Behavior

When the keyboard is open, the ion app content is scrollable but the entire "webview" should not be scrollable which causes content to be hidden.

### Steps to Reproduce

1) click on input in scrollable ion-content
2) after keyboard shows, scroll all the way down - sometimes it scrolls the wrong element.

### Video:
You can see that if you wait for the scrollbar to fade out and the scrolled element is no longer focused, you can try scrolling again and sometimes it scrolls the wrong "container".

*This is just the list ionic starter app with an input added at the bottom of the list*

https://user-images.githubusercontent.com/38476278/136576264-01b5cc6e-45f1-4539-b4fd-516bb438c1a3.MP4
the 

### Code Reproduction URL

https://github.com/TylerAHolden/ionic-safari-mobile-webview-bug

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.8.3

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : not installed
   @capacitor/core    : 3.2.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.1

System:

   NodeJS : v16.10.0 (/usr/local/Cellar/node/16.10.0/bin/node)
   npm    : 7.24.1
   OS     : macOS Big Sur
```

### Additional Information

I've noticed this issue on iOS 14 as well as iOS 15.

**Comment by liamdebeasi** [comment]
Thanks for the issue. The behavior you are seeing is to be expected when using a regular `<input>` element. When focusing inputs, Safari will scroll the entire view to ensure that the input appears above the keyboard. This means that your `ion-header` and part of the `ion-content` gets scrolled out of view.

When using `ion-input` inside of `ion-content`, we have a utility that will prevent this behavior from happening, but we intentionally do not extend this utility to non `ion-input` elements. Can you try this again with `ion-input` and let me know if it resolves the issue?
