### ISSUE TITLE
bug: angular framework bindings, events emitted twice

### ISSUE THREAD

**Issue by kinggolf** [ionic-team/ionic-framework#24057]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Starting with 6.0.0-beta-7 and including 6.0.0-rc.0, ion-datetime double emits to ionChange after selecting a new date and then tapping Done button.

### Expected Behavior

Using 6.0.0-beta-6 ionChange emitted a single event in ion-datetime after selecting a new value and tapping Done button.

### Steps to Reproduce

`
          <ion-datetime displayFormat="MMMM DD, YYYY" max="2030-12-31" (ionCancel)="openCalendar = false" 
(ionChange)="dateSelected($event)"
                        mode="ios" presentation="date" showDefaultButtons="true" size="fixed" showDefaultTitle="true" #ionDatetime class="date-time">
            <div slot="title">Select Date</div>
          </ion-datetime>
`

Select new date and then tap Done button.

### Ionic Info

Ionic:

   Ionic CLI : 6.17.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.1

System:

   NodeJS : v14.15.1
   npm    : 7.20.5
   OS     : macOS Big Sur

**Comment by kinggolf** [comment]
Hello @liamdebeasi - here you go.

https://github.com/kinggolf/dt-test

Thanks for your support.

**Comment by liamdebeasi** [comment]
Thanks! We updated our Angular wrappers in beta 7 to use https://github.com/ionic-team/stencil-ds-output-targets, but it looks like there is an issue that causes events to be emitted twice.

**Comment by sean-perkins** [comment]
Hello everyone 👋   this issue has been addressed and is available in Ionic [`6.0.0-rc.3`](https://github.com/ionic-team/ionic-framework/blob/next/CHANGELOG.md#600-rc3-2021-11-17) and later.
