### ISSUE TITLE
bug: ion-datetime month/year picker (md) incorrectly applies primary color to every month you switch to with arrow-left/right

### ISSUE THREAD

**Issue by bchehraz** [ionic-team/ionic-framework#24067]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).

### Ionic Framework Version

- [X] v6.x

### Current Behavior

See screen recording. Not sure if intended, but the issue is that when I use the arrow keys to change the month and then end up clicking on the month picker in the top left corner, each month I already scrolled through will have applied the primary color. If the primary color happens to be the same color as the rest of the items (by default it was), then the issue is not noticeable. However by not using the arrow keys and going directly for the month picker in the top left, I don't have this issue.

This issue will happen on Web and Android through chrome dev tools (with the `md` month picker). And this may be a separate issue, but what I also noticed was that regardless of `mode="ios"` or `mode="md"`, the month picker seems to be stuck on `md` for Android and Web, and therefore the issue is not visible on iOS.

https://user-images.githubusercontent.com/7946204/137170829-acc8db5c-582c-404e-a998-803aa9095444.mov

### Expected Behavior

The expected behavior is seen at the start of the screen recording. Regardless of whether I use the arrow keys to change months, the primary color should only be applied to the currently selected month and not each one I have switched to.

### Steps to Reproduce

1. Simply generated a new ionic project, deleted some unnecessary code in the starter project, ran `ionic serve`
2. Added the following code into `home.html`. I happened to be testing out the ion-datetime inside a modal, but this issue will happen regardless of being in a modal.
```
  <ion-button id="open-modal">Open Datetime Modal</ion-button>
  <ion-modal trigger="open-modal" style="--height: 386px; --width: 351px;">
    <ng-template>
      <ion-content>
        <ion-datetime mode="ios" size="cover"></ion-datetime>
      </ion-content>
    </ng-template>
  </ion-modal>
```
3. changed the default primary color on light mode to some purple color
4. opened modal and began interaction with ion-datetime to produce the result

### Code Reproduction URL

https://github.com/bchehraz/ionic-v6-bugs

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.17.1 (/Users/user/.nvm/versions/node/v14.15.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.0
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : 3.2.4
   @capacitor/core    : 3.2.4
   @capacitor/ios     : 3.2.4

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run                             : 1.5.0

System:

   NodeJS : v14.15.3 (/Users/user/.nvm/versions/node/v14.15.3/bin/node)
   npm    : 6.14.9
   OS     : macOS Big Sur
```

**Comment by amandaesmith3** [comment]
Thanks for the issue, I've resolved this via https://github.com/ionic-team/ionic-framework/pull/24268. The fix will be available in a future release of Ionic 👍
