### ISSUE TITLE
feat: ion-select event for when overlay is closed for any reason

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#24088]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Currently the `ionBlur` of the `ionSelect` is emitted if the inner used button fires the `blur` which doesn't make any sense to me 🤔

### Expected Behavior

I would expect the **blur** event to be fired after the overlay is dismissed.

In my case i want to check if the users selects an element after he is finished (selects or closed the overlay).

### Steps to Reproduce

Not needed i guess? 😃

**Comment by amandaesmith3** [comment]
I've merged in the PR and am closing this issue. The new event will be available in an upcoming release of Ionic. Thank you for your work!
