### ISSUE TITLE
bug: ionInput type emits KeyboardEvent, but should be InputEvent

### ISSUE THREAD

**Issue by wmadden** [ionic-team/ionic-framework#24083]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

The type of `ion-input`'s `onIonInput()` event handler is incorrect:

[The existing code](https://github.com/ionic-team/ionic-framework/blob/24659a527abe0c70df7e8ae6da3dcb4017bf500c/core/src/components.d.ts#L4316): 
```ts
        /**
          * Emitted when a keyboard input occurred.
         */
        "onIonInput"?: (event: CustomEvent<KeyboardEvent>) => void;
```

The type of the event is `InputEvent`, not `KeyboardEvent`, so it should be:

```ts
        /**
          * Emitted when a keyboard input occurred.
         */
        "onIonInput"?: (event: CustomEvent<InputEvent>) => void;
```

<img width="924" alt="Screenshot 2021-10-16 at 12 31 15" src="https://user-images.githubusercontent.com/12165/137584062-19e0eb24-c6f6-4753-8ee5-a151915ac7b2.png">

### Expected Behavior

`onIonInput()` should accept a callback of type `(event: CustomEvent<InputEvent>) => void`

### Steps to Reproduce

1. Create an `ion-input`
2. Assign it an `onIonInput` event handler
3. Inspect the event generated on keypress

It will be a `CustomEvent<InputEvent>`, not a `CustomEvent<KeyboardEvent>`

### Ionic Info

Ionic:

   Ionic CLI       : 6.17.1
   Ionic Framework : @ionic/react 5.8.1

Capacitor:

   Capacitor CLI      : 2.4.5
   @capacitor/android : 2.4.7
   @capacitor/core    : 2.4.5
   @capacitor/ios     : 2.4.7

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.4.1) : 1.4.0

System:

   NodeJS : v14.16.1 (/usr/local/bin/node)
   npm    : 6.14.12
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via #24111, and a fix will be available in an upcoming release of Ionic Framework.
