### ISSUE TITLE
bug: events in child components within overlay components in react do not work

### ISSUE THREAD

**Issue by nickmeulen** [ionic-team/ionic-framework#24094]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Click events in child components of overlays such as Modals in react do not propogate

### Expected Behavior

Click events should call their handlers

### Steps to Reproduce

Add an IonButton to a modal component which is added to the dom via `ReactDOM.render`

```
const modalContainer = document.createElement('div');
document.body.appendChild(modalContainer);
ReactDOM.render(React.createElement(IonModal, {
      isOpen: true,
      presentingElement: undefined,
      className: modalOptions.cssClass,
      swipeToClose: false,
      backdropDismiss: false,
      children: [
          React.createElement(IonButton, {
                  expand: 'block',
                  buttonType: 'button',
                  onClick: () => {
                    console.log('BUTTON CLICK'); // This does nothing
                  },
         }, 'Click Me')
      ]
}), modalContainer);

### Code Reproduction URL

_No response_

### Ionic Info

Ionic:

   Ionic CLI : 6.12.2

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.2
   npm    : 6.14.14
   OS     : macOS Big Sur

### Additional Information

_No response_

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this in an Ionic starter app and provide a link to the repo?
