### ISSUE TITLE
bug: issues with getting app to run as expected

### ISSUE THREAD

**Issue by nhatter** [ionic-team/ionic-framework#24101]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Memory leak caused by images in Ionic framework - causes heavy memory usage over time and then causes app to become unstable and eventually forces WKWebView to refresh (WKWebView flashes white) which resets the app.

This is obviously not ideal as it means the app is not stable and is likely to break in a production environment.

Also, leaving the app after a long period of activity, and coming back to it, can also trigger a forced WKWebView refresh.

See video gif:
![Memleak causing WkWebView to force refresh which causes app to crash](https://github.com/4bsolut/cards/raw/main/GIF-2021-10-20-14-07-27.gif?raw=true)

The video was recorded while 'accepting and rejecting' a bunch of 'image cards'

Here's the memory usage chart before we get the 'forced refresh' - as you can see, astronomical memory usage!
<img width="800" alt="Mem usage Ionic" src="https://user-images.githubusercontent.com/2399351/138187793-b8aba98f-ae14-4285-aa02-39a2a7f3b8c9.png">

And here's the memory chart with the bug reproduction demo in action - you can see there's a huge spike in memory before the app crashes and force refreshes / resets:

![Memleak video](https://user-images.githubusercontent.com/2399351/138188417-c82eaf86-8a42-483a-b4dd-e973804d3309.gif)

### Expected Behavior

When loading new images that have been loaded via DOM (and removed from DOM), memory assigned to previously loaded images should be appropriately garbage collected so that the app remains stable and does not trigger a WKWebView forced refresh / app crash.

### Steps to Reproduce

1. Load images in an Ionic page eg. such as through cards containing images (as in the code reproduction URL).
2. Hide or remove images as appropriate.
3. Load some more images (without navigating away from the current page).
4. Eventually WKWebView will run out of memory because garbage collection / memory cleanup doesn't seem to happen for the images.
5. App will eventually become unstable and will either become non-responsive for user input or WkWebView will refresh.

Note -- we checked the DOM -- when new images are loaded, the old ones are certainly being removed from the DOM tree.

We have tried to set our cards array to empty or length = 0.

Our suspicion is that something is going on in Ionic core which is out of our hands :(

We have also tried small image card batch sizes of 5 (rather than 20, as per the demo). We still get the forced refresh by WKWebView -- it just takes longer with a smaller batch size.

(Note: we also removed the card flicking animation when you press x or heart, just to help simplify the issue)

### Code Reproduction URL

https://github.com/4bsolut/cards

### Ionic Info

Ionic:

Ionic CLI : 6.17.1 Ionic Framework : @ionic/angular 5.8.4 @angular-devkit/build-angular : 12.1.4 @angular-devkit/schematics : 12.2.10 @angular/cli : 12.1.4 @ionic/angular-toolkit : 4.0.0

Capacitor:

Capacitor CLI : 3.2.5 @capacitor/android : not installed @capacitor/core : 3.2.5 @capacitor/ios : 3.2.5

Utility:

cordova-res : not installed globally native-run : 1.5.0

System:

NodeJS : v12.20.2 (/Users/jrequena/.nvm/versions/node/v12.20.2/bin/node) npm : 7.24.0 OS : macOS Big Sur

### Additional Information

**Seems to be fine in iPhone emulator, but get the 'white flash' refresh / crash on actual device.**

Tested using actual devices: iPhone 12 Pro (iOS 15.0.2) and iPhone XR (iOS 13.4.1) - both **not** jailbroken and legit.

Unless we can fix this, we will be forced to migrate to perhaps React Native :( Would be a huge shame as both my CTO and I did a lot of dev with Ionic and we would prefer not to throw away 7+ months of coding!

**Suggestions on how to fix:**

- Try to reproduce the bug as described.
- Investigate Ionic core to check for mem leaks, listeners, observables, etc -- anything that might be causing a persistence reference which is preventing garbage collection by Javascript / WkWebView
- Perhaps automatically unload images by setting img.src = "" in Ionic Core - or have an option to enable/disable this and give ample warnings in Ionic documentation about this

**Related issues:**

- (https://github.com/ionic-team/ionic-framework/issues/11570)
- (https://forum.ionicframework.com/t/memory-leaks/10036/19)
- (https://github.com/ionic-team/ionic-framework/issues/1096#ref-issue-40172100)

**Possible temporary workaround:**

Before loading new images, perhaps could try setting img.src = "" on any images currently loaded and see if that triggers garbage collection.

I note that @jrianto and @g4spow set src = "" for videos previously loaded to unload them and this seemed to work for them with regards to [memory leaks in another Ionic issue](https://github.com/ionic-team/ionic-framework/issues/1096#issuecomment-214266877), so perhaps this will work for images too. However, it seems odd that we would have to do this...

**Comment by nhatter** [comment]
Thanks Liam! The refresh is triggered by a large amount of memory usage...
we’ve reproduced it on two different iPhones with different iOS versions.

Note that the app we’ve shown is a drastically simplified version of our
actual app but yes still get the same problem.

In our actual app we have a much smaller image / profile card batch size of
5. Eventually after viewing anywhere from 20-40 profiles we get the huge
memory usage and then the refresh bug.

**Comment by nhatter** [comment]
Hi Liam,

So I did a search in our github repo for our actual project, and we can't find anything in our code. Our actual code doesn't use any of those CSS properties :(  So our suspicion is that an Ionic component / module may be adding the offending styles.

I did however git clone Ionic's repo and I searched for those three CSS properties which caused the memleak in the test Ionic project we shared.

```
Nicks-MacBook-Pro:components nick$ pwd
/Users/nick/Documents/GitHub/ionic-framework/core/src/components

Nicks-MacBook-Pro:components nick$ grep -nr "transition:.*all" *
checkbox/test/standalone/index.html:103:      --transition: all 5s ease-out;
fab-button/fab-button.scss:129:  transition: all ease-in-out 300ms;
fab-button/fab-button.scss:221:  transition: all ease-in-out 300ms;
header/header.ios.scss:72:  transition: all 0.2s ease-in-out;
modal/modal.ios.scss:66:    transition: all 0.5s ease-in-out;
searchbar/searchbar.ios.vars.scss:52:$searchbar-ios-input-transition:                  all 300ms ease !default;
searchbar/searchbar.ios.vars.scss:55:$searchbar-ios-cancel-transition:                 all 300ms ease !default;
segment-button/segment-button.ios.vars.scss:61:$segment-button-ios-transition:                       100ms all linear !default

Nicks-MacBook-Pro:components nick$ grep -nr "transition:.*opacity" *
back-button/back-button.scss:73:  --transition: background-color, opacity 100ms linear;
button/button.ios.scss:14:  --transition: background-color, opacity 100ms linear;
fab-button/fab-button.scss:44:  --transition: background-color, opacity 100ms linear;
input/input.scss:183:  transition: opacity 0.15s cubic-bezier(0.4, 0, 0.2, 1);
item/item.ios.scss:9:  --transition: background-color 200ms linear, opacity 200ms linear;
item/item.md.scss:19:  --transition: opacity 15ms linear, background-color 15ms linear;
segment-button/segment-button.md.vars.scss:64:$segment-button-md-transition:                        color .15s linear 0s, opacity .15s linear 0s !default;
segment-button/segment-button.ios.scss:57:  transition: 160ms opacity ease-in-out;
slides/slides-vendor.scss:214:  -webkit-transition: 300ms opacity;
slides/slides-vendor.scss:215:  -o-transition: 300ms opacity;
slides/slides-vendor.scss:216:  transition: 300ms opacity;
textarea/textarea.scss:149:  transition: opacity 0.15s cubic-bezier(0.4, 0, 0.2, 1);
toast/toast.ios.scss:69:  transition: background-color, opacity 100ms linear;
toolbar/test/collapse/index.html:16:      transition: opacity ease-in-out 200ms;

Nicks-MacBook-Pro:components nick$ grep -nr "will-change:.*transform" *
item-sliding/item-sliding.scss:29:  will-change: transform;
picker-column/picker-column.scss:45:  will-change: transform;
reorder-group/reorder-group.scss:8:  will-change: transform;
ripple-effect/ripple-effect.scss:40:  will-change: transform, opacity;
segment-button/segment-button.scss:277:  will-change: transform, opacity;
toggle/toggle.scss:79:  will-change: transform;
toggle/toggle.md.scss:49:  will-change: background-color, transform;
toggle/toggle.ios.scss:50:  will-change: transform;
virtual-scroll/virtual-scroll.scss:27:  will-change: transform;

```

Note, here's a snippet of our view from our actual codebase:

 ```
<ion-slides  pager="false"  [options]="slideOpts" [id]="'slideUsersMain'" #slideWithNavUsers *ngIf="!is_end" style="padding-top: 65px;
    height: 91%;"> 
      <ion-slide    *ngFor="let user of common.allCards; let i = index" class="user-card" [attr.user-id]="user.uid" >
         <ng-container *ngIf="!_.has(user,'special')" >  
          <ion-card     [id]="'user-card-'+user.uid"  > 
              <div class="scrolling-wrapper" id="scrolling-wrapper" [ngStyle]="{'height': height}"> 
                <ion-card-header >
                          <ion-slides (ionSlideDidChange)="check_images_slide('user-'+user.uid,i)" pager="false" [options]="slideOpts2"  #slides [id]="'user-'+user.uid" >
                            <img *ngIf="!user.images"  src="./assets/loading.gif" class="img-rating">              
                            <ion-slide  *ngFor="let image of user.images; let i = index">
                              <div 
                              style="display: inline-block;width: 100%;"
                              >
                              <img *ngIf="image"    [id]="'img-'+image.uid" [defaultImage]="'./assets/loading.gif'" class="img-rating" [lazyLoad]="image.path"     [attr.image-id]="image.uid">  
                              </div>              
                                <div style="margin: 0px;
                                position: absolute;
                                top: 5px;
                                left: 40%;
                                ">
```

I'll add you as a collaborator temporarily to our project for the sole purpose of confirming whether or not this is an Ionic 5.8.4 bug. Note we added a test component called "swiper" which does use the offending styles (as you've seen in the sample reproduction repo I originally linked to). But the rest of our codebase does not use these styles, at least, not explicitly, -- unless Ionic core is adding them somehow behind the scenes.

I've asked our CTO to experiment with trying plain divs rather than ion-slides, ion-cards or any Ionic components... I've also asked him to remove non-essential modules and I believe he has already tried that.

Tearing our hair out! We've both spent probably a good few weeks on this issue. My CTO is convinced this is an Ionic core problem... but naturally, only further investigation will confirm if Ionic core has a bug.

**Comment by liamdebeasi** [comment]
I guess I am a bit confused. The code I mentioned was found in the reproduction provided: https://github.com/4bsolut/cards. Does the issue reproduce in a different way without that code?

**Comment by nhatter** [comment]
Added you to the project @liamdebeasi - switch to the new-swiper branch.

Steps to reproduce in our project:
- Build the project and run it on an iPhone
- Create a basic dating profile
- Go through about 40 profiles and monitor the mem usage (just accept or reject)

Feel free to have a look around, we trust you won't publish our source code in its entirety :) (for your eyes only)

**Comment by nhatter** [comment]
I will create an account and give you credentials, no problem.

We have tried to isolate by way of minimal example we shared :(

We are this close to switching to NativeScript :(  this is our last attempt to salvage Ionic...

**Comment by nhatter** [comment]
BTW CTO says that your fixes did work for the minimal example, at least. He says he loaded 100 profile cards, no problem.

Problem is, we're not using the offending styles in our actual source code as you'll see in the repo I gave you access to...
