### ISSUE TITLE
bug: iOS ion-range & ion-reorder not working properly

### ISSUE THREAD

**Issue by OrazioLocchi** [ionic-team/ionic-framework#24106]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

on iOS only:
- ion-range knob is not responding
- ion-reorder item are undisplayed after drag and drop move

see https://youtu.be/qU5hJ6HF7QI 

=> everything is doing fine on web AND Android. 
Code is a copy/paste of docs 

### Expected Behavior

- ion-range: being able to move and see the knob in the right position.
- ion-reorder: being able to see all items after drag/drop effect.

### Steps to Reproduce

1/ init ionic project
2/ add component 
3/ insert ion-range and/or ion-reorder into the component
4/ run on iOS device (or simulator, same observation)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.4
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.10
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : 3.2.5
   @capacitor/core    : 3.2.5
   @capacitor/ios     : 3.2.5

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.17.3 (/usr/local/bin/node)
   npm    : 7.20.0
   OS     : macOS Big Sur

### Additional Information

I've tried:
- update to ionic fwk 6
- update iOS (from 14 to 15)
- run on different devices (iPhone X, and many simulators)
- change code parameters 
- change code with no variables 

I had no problem on Capacitor v2 with old apps. 
I guess the problem might be related to cap v3.

Thanks for your help

**Comment by ghenry22** [comment]
I use ion-range and ion-reorder pretty extensively in my app and have no issues with either, they both function as intended on iOS and Android.  I am currently running the latest ionic v5 release but have been using these components consistently all the way back to ionic v3 with no issues on iOS.

ion-reorder does NOT work with virtual-scroll, it will have symptoms similar to what you see where items will disappear, works fine with ngFor and infinite-scroll though.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
