### ISSUE TITLE
bug: v6 datetime does not show if rapidly presented multiple times

### ISSUE THREAD

**Issue by nvthuong1996** [ionic-team/ionic-framework#24112]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Please see video. calendar don't show

https://user-images.githubusercontent.com/24992586/138548305-358ab761-25e3-4dc9-807e-2f4977ec0768.mov

### Expected Behavior

calendar show exacly

### Steps to Reproduce

error only happen when i use dimensions Iphone in chrome develop tool.

it seems to be related to css class: datetime-ready

https://github.com/ionic-team/ionic-framework/blob/7fed7bcb6132e7d8a47822ea3fd1e4ec67133bc6/core/src/components/datetime/datetime.tsx#L844

**Comment by sean-perkins** [comment]
@nvthuong1996 are you able to replicate this bug without modifying the box container size of the `ion-datetime`? Currently in your example project, you are adding `100px` of padding to the bottom of the element.

`ion-datetime` is not intended to span larger than the screen height. There is logic with intersection observers to properly scroll contents into the view. By modifying the container to overflow, the IO does not reliably fire and the `datetime-ready` class will not be consistently applied.

Let me know 👍

**Comment by nvthuong1996** [comment]
https://www.youtube.com/watch?v=o27nTK_JvXM

please check. i retry it many times

**Comment by amandaesmith3** [comment]
Thanks for the issue, I've resolved this via https://github.com/ionic-team/ionic-framework/pull/24385 and the fix will be available in a future release of Ionic 👍
