### ISSUE TITLE
bug: react: useIonAlert fails in production (but works in dev)

### ISSUE THREAD

**Issue by burggraf** [ionic-team/ionic-framework#24116]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Using `useIonAlert()` in an Ionic React 6.x project works in dev mode (`ionic serve`) but silently fails in production (`ionic build --production`).

Basically, any use of alert dialogs fails in production, but works fine in the local dev server.  Super annoying.

### Expected Behavior

Clicking the **TEST** button should bring up the test `alert` dialog just as it does in `ionic serve` mode.

### Steps to Reproduce

Here's a full test repo for you:

[https://github.com/burggraf/ionic-react-alert-bug](https://github.com/burggraf/ionic-react-alert-bug)

Let me know if you need anything else to reproduce this.  I have verified this is specific to 6.x.  Compiling with `ionic build --prod` seems to work fine in the 5.x environment.

### Code Reproduction URL

https://github.com/burggraf/ionic-react-alert-bug

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.17.1 (/Users/markb/.nvm/versions/node/v14.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.0-rc.0

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : not installed
   @capacitor/core    : 3.2.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.16.0 (/Users/markb/.nvm/versions/node/v14.16.0/bin/node)
   npm    : 7.17.0
   OS     : macOS Big Sur


```

**Comment by willmartian** [comment]
This issue has been resolved in #24191, and the fix will be available in Ionic v6.0.0-rc.3. Thanks everyone!
