### ISSUE TITLE
OnIonInput wrong attr

### ISSUE THREAD

**Issue by FernetB** [ionic-team/ionic-framework#24115]
**Ionic version:**

[] **4.x**
[ x ] **5.x**

**I'm submitting a ...** 

[ x ] bug report
[ ] feature request

**Current behavior:**

The `onIonInput` event has `cancelable` on `true` while actually is not cancelable
**Expected behavior:**

Attr `cancelable` on false 
**Steps to reproduce:**

`Console.log` the event `onIonInput` and `onInput` and see the difference, also you can try to `preventDefault` the event and nothing happen

**Ionic info:** 

```

Ionic:

   Ionic CLI       : 6.17.1
   Ionic Framework : @ionic/react 5.8.4

Capacitor:

   Capacitor CLI      : 3.0.2
   @capacitor/android : 3.2.4
   @capacitor/core    : 3.0.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.6
   npm    : 6.14.15
   OS     : Linux 5.11
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
