### ISSUE TITLE
bug: Popover backdrop not included in production builds

### ISSUE THREAD

**Issue by jvartanian** [ionic-team/ionic-framework#24129]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

In our Ionic React application, we are using the `IonPopover` component with the backdrop enabled. 

When developing locally using `npm run start`, the popover opens and the backdrop is shown. Clicking outside of the popover closes it as expected. 

However, when we deploy to our dev environment, the backdrop is not being shown, and the popover cannot be closed by clicking outside of it. 

After some investigation, it appears that the `IonBackdrop` component is being marked as dead code during tree shaking, and not being included in the bundles created by `npm run build`. 

Explicitly referencing the `IonBackdrop` somewhere in our code fixes the problem (i.e. `console.log(IonBackdrop)`).

### Expected Behavior

After building and deploying the application, the backdrop should show and the user should be able to close the Popover by clicking outside of it.

### Steps to Reproduce

1. Create a blank React Ionic v6 project
2. Add an `IonButton` and an `IonPopover`, with the button triggering the popover.
3. Build the application: `npm run build`
4. Run the application using a package such as [serve](https://www.npmjs.com/package/serve)
5. Click on the button
6. The popover shows without a backdrop

### Code Reproduction URL

https://github.com/jvartanian/backdrop-tree-shaking

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.0 (~/.nvm/versions/node/v16.6.2/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.0-rc.1

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : not installed
   @capacitor/core    : 3.2.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.6.2 (/Users/justinvartanian/.nvm/versions/node/v16.6.2/bin/node)
   npm    : 7.20.3
   OS     : macOS Big Sur

**Comment by willmartian** [comment]
This issue has been resolved in #24191, and the fix will be available in Ionic v6.0.0-rc.3. Thanks for the bug report!
