### ISSUE TITLE
feat: Create Angular version of ionic-react-test-utils

### ISSUE THREAD

**Issue by magz99** [ionic-team/ionic-framework#24133]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Export an Angular version of the `ionic-react-test-utils` to make use of the `ionFireEvents` methods in unit tests.

### Describe the Use Case

We're using Angular Testing Library (https://testing-library.com/docs/angular-testing-library/api) for our unit tests in our Ionic app.

It would be great to have an angular version of the `ionic-react-test-utils` to use the ion events.

Right now our workaround is to copy the contents of  `ionFireEvent.ts` from https://github.com/ionic-team/ionic-react-test-utils/blob/master/src/ionFireEvent.ts  into our project.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Could you please describe the issue you are running into? Events should fire correctly when testing in Angular.
