### ISSUE TITLE
How to Contribute for Angular package is missing

### ISSUE THREAD

**Issue by vicmarcal** [ionic-team/ionic-framework#24137]
**Current behavior:**
In the Contributing.MD page just "Core" contribution is explained, while other packages as "angular" are missing.

https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#setup

**Expected behavior:**
Core package contribution is well-explained, but Angular is missing.

**Steps to reproduce:**
Visit https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md

Core is explained, but Angular package is not

**Comment by liamdebeasi** [comment]
Thank you! I updated the contributing guide for Angular, React, and Vue: https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#angular-react-and-vue
