### ISSUE TITLE
bug: can't change font-family or size in calendar-day

### ISSUE THREAD

**Issue by nickmeulen** [ionic-team/ionic-framework#24158]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Font-family is not targetable for calendar day's

### Expected Behavior

Be able to target font-family 

### Steps to Reproduce

Font-family is not inherited in `:host .calendar-day`

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you help me understand what you are trying to do by increasing the font size?

**Comment by nickmeulen** [comment]
Font-size needs to be able to be changed for cases where a user requires a larger font due to ADA requirements.

**Comment by liamdebeasi** [comment]
Thanks! I think the long term solution for this is https://github.com/ionic-team/ionic-framework/issues/18592 which adds dynamic font sizes for iOS, but being able to override on a per-component basis is still important, so I will mark this as a bug.

**Comment by surabhiBh** [comment]
@liamdebeasi  Has this been resolved as I am unable to find any solution to modify the font size or the selected text colour ?

**Comment by liamdebeasi** [comment]
The issue here is still open which means it has not been resolved. A team member will close the issue and leave a comment when it is resolved.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/24638. Font size adjustment goes beyond `ion-datetime`, and we would like to find a way to resolve this issue for all Ionic components. Please follow that thread for updates on this issue.
