### ISSUE TITLE
bug: ion-content scroll element undefined in Vue onMounted hook

### ISSUE THREAD

**Issue by a-Leong** [ionic-team/ionic-framework#24168]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When called in mounted lifecycle hook, IonContent scroll methods raise errors related to scroll element evaluating to `undefined`. `getScrollElement` resolves to `undefined` as well. E.g.:
```console
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'scrollHeight')
    at HTMLElement.scrollToBottom (ion-content.js?0289:149)
    at scrollToBottom (Home.vue?4912:21)
    at eval (Home.vue?4912:26)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:6701)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:6710)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js?5c40:1964)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?5c40:6902)
    at render (runtime-core.esm-bundler.js?5c40:4840)
    at mount (runtime-core.esm-bundler.js?5c40:3173)
    at Object.app.mount (runtime-dom.esm-bundler.js?830f:1574)
```

The IonContent element itself is not undefined the time of this invocation, only its scroll element appears to be.

### Expected Behavior

Scroll methods run successfully and `getScrollElement` resolves to the scroll element for an IonContent component in onMounted. This is the working behavior in v5.x. 

### Steps to Reproduce

Make a call to any scroll method on an IonContent component in the onMounted lifecycle hook of a Vue component. An error is raised when the component mounts. Invocations of scroll methods from user-triggered events work as expected. Adding a sufficiently large timeout before invoking scroll methods within onMounted causes methods to work as expected as well.

Edit:
The above are steps in the general sense. In the attached reproduction repo, simply run the app and observe console error when Home.vue mounts. Clicking "Scroll To Bottom" button exhibits expected behavior.

### Code Reproduction URL

https://github.com/a-Leong/ion-content-bug

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.0 (/Users/{...}/.nvm/versions/node/v12.20.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.0-rc.2

Capacitor:

   Capacitor CLI      : 3.3.0
   @capacitor/android : not installed
   @capacitor/core    : 3.3.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v12.20.0 (/Users/{...}/.nvm/versions/node/v12.20.0/bin/node)
   npm    : 7.18.1
   OS     : macOS Big Sur

**Comment by amandaesmith3** [comment]
Thanks for the report. I've resolved this via https://github.com/ionic-team/ionic-framework/pull/24255 and the fix will be available in a future release of Ionic.
