### ISSUE TITLE
bug: Unable to do development builds of Ionic Cordova app with Angular version 12 and above

### ISSUE THREAD

**Issue by RowTracker** [ionic-team/ionic-framework#24178]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

Since upgrading to Angular V12 I have found that i can no longer do development builds of Ionic Cordova apps.

This is because in version 12 of Angular the default build has been changed from Development to Production. The Ionic build scripts assume the default build is Development which is no longer true.

### Expected Behavior

Ionic Cordova Build should allow a Development configuration option for example:

ionic cordova build android --configuration=dev

or 

ionic cordova build android --c=dev

### Steps to Reproduce

any build of ionic cordova produces production builds

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.1
   @angular-devkit/build-angular : 12.2.12
   @angular-devkit/schematics    : 12.2.12
   @angular/cli                  : 12.2.12
   @ionic/angular-toolkit        : 5.0.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 9.1.0, browser 6.0.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 21 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (/Users/rowtracker/Library/Android/sdk)
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v16.13.0 (/usr/local/bin/node)
   npm               : 7.5.6
   OS                : macOS Big Sur
   Xcode             : Xcode 13.1 Build version 13A1030d

a

### Additional Information

The issue can be resolved by adding the following configuration option to the "ionic-cordova-build" section angular.json file:

            "dev": {
              "browserTarget": "app:build"
            }

This creates a dev build configuration that does not include the production option.

I believe that Ionic should update the "addIonicBuilder" method of @ionic/angular/schematics/add/index.js to add the above build configuration option. At present it only adds a production option on the out of date assumption that default builds are development builds.

**Comment by mhartington** [comment]
Hey there! Can you please share a sample project? I am unable to replicate this locally.

**Comment by RowTracker** [comment]
Hi, I've now found I can't reproduce the problem now. Default builds are dev builds and the --prod option creates production builds.

I did spend a lot of time since logging this issue rebuilding my app into a new blank V6 Ionic project so I guess whatever was causing the problem has gone away.
