### ISSUE TITLE
bug: action-sheet does not respect --ion-safe-area-bottom in mode: 'md' 

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#24175]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When displaying action sheet on devices where --ion-safe-area-bottom has a value, and the mode is 'md', the action sheet overlaps the safe area and does not apply appropriate padding to the bottom button:

![image](https://user-images.githubusercontent.com/362329/140569848-ac53be8a-b767-4a7d-bc3e-9644131168b8.png)

### Expected Behavior

The action-sheet should respect the safe area:

![image](https://user-images.githubusercontent.com/362329/140569966-831d0bf3-1c4e-4bc4-b385-4cd3ca67a417.png)

### Steps to Reproduce

Just display any action-sheet in MD mode and change the value of `--ion-safe-area-bottom`. This can be reproduced even in the ionic docs themselves. See code repro URL.

### Code Reproduction URL

https://ionicframework.com/docs/demos/api/action-sheet/index.html?ionic:mode=md

### Ionic Info

Version 5x and whatever version the ionic docs are running.

Ionic:

   Ionic CLI                     : 6.17.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.5
   @angular-devkit/build-angular : 13.0.1
   @angular-devkit/schematics    : 13.0.1
   @angular/cli                  : 13.0.1
   @ionic/angular-toolkit        : 5.0.3

### Additional Information

The last child of the action-sheet should have padding applied to its bottom:

```
.action-sheet-group.sc-ion-action-sheet-md:last-child {
    padding-bottom: 0;
    padding-bottom: var(--ion-safe-area-bottom);
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24176, and a fix will be available in an upcoming release of Ionic Framework.
