### ISSUE TITLE
bug: v6 ion-textearea with item fill outline + autogrow makes contents grow outside of container

### ISSUE THREAD

**Issue by jesperbjerke** [ionic-team/ionic-framework#24187]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using the new `fill="outline"` on an item that contains an ion-textearea with `auto-grow="true"` makes the contents of the ion-textarea grow outside of the container. Removing the `fill="outline"` makes it work properly again.

### Expected Behavior

Contents should be contained within the textearea, like when not using `fill="outline"` 

### Steps to Reproduce

```html
<ion-item mode="md" fill="outline">
    <ion-label position="floating">This is my label</ion-label>
    <ion-textarea auto-grow="true"></ion-textarea>
</ion-item>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.2
   @angular-devkit/build-angular : 12.2.13
   @angular-devkit/schematics    : 12.2.13
   @angular/cli                  : 12.2.13
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : 3.3.1
   @capacitor/core    : 3.3.1
   @capacitor/ios     : 3.3.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by sean-perkins** [comment]
@jesperbjerke thanks for reporting this issue!

On an initial look, it's the combination of three separate factors that are causing this issue:
1. Using an `ion-item` with `fill="outline"`
2. Using an `ion-textarea` with `auto-grow="true"`
3. Using an `ion-label` with `position="floating"`

The ion-label is the main factor, as adjusting the position value to any value other than `floating` or removing the label, results in a proper display.

I'll discuss with the team on best steps forward 👍 

Video for reference of the issue:
<video src="https://user-images.githubusercontent.com/13732623/140972678-6fcc9184-40f9-48ae-a6f7-9f46c122fbea.mp4" alt="Textarea auto grow display issue"></video>

**Comment by sean-perkins** [comment]
Narrowed down the issue to this specific line: https://github.com/ionic-team/ionic-framework/blob/next/core/src/components/item/item.md.scss#L466

Currently we are translating the slotted contents, by 25% of the content's height. This worked fine for fixed height inputs, but doesn't transfer to auto grow with ion-textarea. Ideally we only need to translate the slotted contents by the difference of the label's height.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24202, and a fix will be available in an upcoming release of Ionic Framework.
