### ISSUE TITLE
bug: ion-searchbar cursor slides out of component bounds

### ISSUE THREAD

**Issue by eric-horodyski** [ionic-team/ionic-framework#24184]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

On iOS, when an `<ion-searchbar>` is used, the cursor within can slide out of the component's bounds when the user scrolls content above or below the search bar. 

The "cursor sliding" does not impact the component from retaining focus. This issue has only been observed on iOS and appears to work as intended on web/Android.

### Expected Behavior

The cursor should not leave the bounds of the `<ion-searchbar>` component.

### Steps to Reproduce

1. Run the reproduction app
2. Focus the `<ion-searchbar>` 
3. Slide the view up or down
4. Observe the cursor leaves the boundary of the `<ion-searchbar>` before disappearing.  

### Code Reproduction URL

https://github.com/eric-horodyski/fw-ng-searchbar-cursor

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.17.1 (/Users/eric/.volta/tools/image/packages/@ionic/cli/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.5
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : not installed
   @capacitor/core    : 3.3.1
   @capacitor/ios     : 3.3.1

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.17.0 (/Users/eric/.volta/tools/image/node/14.17.0/bin/node)
   npm    : 7.14.0
   OS     : macOS Big Sur
```

### Additional Information

The video attached demonstrates the issue. 

https://user-images.githubusercontent.com/62819287/140804853-71f9427f-7140-4b0a-949d-80404b30b8e5.MP4

**Comment by liamdebeasi** [comment]
Thanks, Eric! This is a longstanding issue with WebKit that has gotten (somewhat) better over time. My understanding is the caret is part of the native UI that sits on top of the rendered web content. As a result, there have been some issues with caret positioning when you scroll on non-body content.

Newer versions of iOS hide the caret when you scroll and then re-show it when scrolling stops. That is the behavior noted in the video. That being said, I think this is something better addressed on the WebKit side as it is not a bug in Ionic. Does this address your concern?
