### ISSUE TITLE
bug: Ion-input is pushed behind header after focus on iOS 

### ISSUE THREAD

**Issue by swernimo** [ionic-team/ionic-framework#24195]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I believe what I'm experiencing is similar to this issue [https://github.com/ionic-team/ionic-framework/issues/17457](https://github.com/ionic-team/ionic-framework/issues/17457) which says it was fixed in ionic v4, but I'm still experiencing the bug. 

Currently, when a control receives focus it scrolls up to the top of the parent container (div in my case), but top of the container is scrolled behind the header. 

https://user-images.githubusercontent.com/11137058/141018457-98fffce5-ec2c-408a-9e37-824fe8991383.mov

 

### Expected Behavior

The expected behavior is that the page wouldn't scroll so heigh that the input is off the page.

### Steps to Reproduce

I've only seen this on iOS devices, I haven't been able to reproduce it on Android or on the simulator. 

- Have a div with children controls that extend past the page
- Scroll down the page to find an input
- Tap on the input to give it focus
- Page scrolls up to make the input be top of page
- Parent Div containing input is hidden behind header

Here's my page (partial) layout
```
<ion-header>
    <ion-toolbar class="toolbar" mode="md">
        <ion-button class="link" (click)="cancel()" slot="start">Cancel</ion-button>
        <ion-title>{{ leadId ? 'Edit Lead' : 'Create Lead' }}</ion-title>
        <ion-button class="link" slot="end" [disabled]="!isFormValid() || isSaving" (click)="save()">Save</ion-button>
    </ion-toolbar>
</ion-header>
<ion-content class="modalContent">
  <div class="page">
    <div class="section">
      <div class="header">
        <span class="title label strong">
          Key Info
        </span>
        <div *ngIf="keyInfo.expanded" (click)="toggleKeyInfo()">
          <ion-icon class="icon-gen3-angle-up-small"></ion-icon>
        </div>
        <div *ngIf="!keyInfo.expanded" (click)="toggleKeyInfo()">
          <ion-icon class="icon-gen3-angle-down-small"></ion-icon>
        </div>
      </div>
      <div *ngIf="keyInfo.expanded" class="items">
        <div *ngIf="isVisible('Name')">
          <ion-input inputTitle="Lead Name" [isRequired]="true" [inputValue]="leadName" (outputValue)="setForm({ field: 'Name', value: $event })"></ion-input>
        </div>
        <div *ngIf="isVisible('PotentialClient')">
          <potential-client [selectedCompany]="selectedCompany" [title]="'Potential Client'" (outputValue)="setForm({ field: 'PotentialClient', value: $event })"></potential-client>
        </div>
        <div *ngIf="isVisible('Stage')">
          <cos-selectlist [title]="'Stage'" [items]="stages"></cos-selectlist>
        </div>
        <div *ngIf="isVisible('LeadSource')">
          <cos-selectlist [title]="'Lead Source'" [items]="sources"></cos-selectlist>
        </div>
        <div *ngIf="isVisible('City')">
          <ion-input inputTitle="City" [inputValue]="city" (outputValue)="setForm({ field: 'City', value: $event })"></ion-input>
        </div>
        <div *ngIf="isVisible('Country')">
          <country-list [title]="'Country'" (onCountrySelect)="onCountrySelect($event)" [selectedCountry]="selectedCountry"></country-list>
        </div>
        <div *ngIf="isVisible('State')">
          <statelist [title]="'State'" (onStateSelected)="onStateSelected($event)" [selectedCountry]="selectedCountry" [selectedState]="selectedState"></statelist>
        </div>
        <div *ngIf="isVisible('Score')">
          <cos-selectlist [title]="'Score'" [items]="scores"></cos-selectlist>
        </div>
        <div *ngIf="isVisible('RiskProfile')">
          <cos-selectlist [title]="'Risk Profile'" [items]="riskProfiles"></cos-selectlist>
        </div>
        <div *ngIf="isVisible('Deliverable')">
          <ion-input inputTitle="Deliverables" [inputValue]="deliverable" (outputValue)="setForm({ field: 'Deliverable', value: $event })"></ion-input>
        </div>
        <div *ngIf="isVisible('EstimatedCost')">
          <cos-currency-input inputTitle="Estimated Cost" [inputValue]="estimatedCost" (outputValue)="setForm({ field: 'EstimatedCost', value: $event })"></cos-currency-input>
        </div>
        <div *ngIf="isVisible('EstimatedSize')">
          <ion-input inputTitle="Estimated Size" [inputValue]="estimatedSize" inputMode="decimal" (outputValue)="setForm({  field: 'EstimatedSize', value: $event })"></ion-input>
        </div>
        <div *ngIf="isVisible('UnitSize')">
          <ion-input inputTitle="Estimated Unit Size" [inputValue]="unitSize" (outputValue)="setForm({ field: 'UnitSize', value: $event })"></ion-input>
        </div>
        <div *ngIf="isVisible('TickDate')">
          <ion-input inputTitle="Tickler Date" [inputValue]="tickDate" inputType="date" (outputValue)="setForm({ field: 'TickDate', value: $event })"></ion-input>
        </div>
        <div *ngIf="isVisible('Date')">
          <ion-input inputTitle="Origination Date" [inputValue]="date" inputType="date" (outputValue)="setForm({ field: 'Date', value: $event })"></ion-input>
        </div>
        <div *ngIf="isVisible('BidDate')">
          <ion-input inputTitle="Bid Date" [inputValue]="bidDate" inputType="date" (outputValue)="setForm({ field: 'BidDate', value: $event })"></ion-input>
        </div>
      </div>
      <div class="footer" *ngIf="keyInfo.expanded">
        <ion-button class="link" (click)="toggleKeyInfoShowMore()">{{keyInfo.footerLabel}}</ion-button>
      </div>
    </div>
<!--additional sections with their children-->
</ion-content>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.1000.0
   @angular-devkit/schematics    : 10.0.5
   @angular/cli                  : 10.0.5
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI      : 2.4.7
   @capacitor/android : 2.4.7
   @capacitor/core    : 2.4.7
   @capacitor/ios     : 2.4.7

### Additional Information

I think it might be related to the "section" div scrolling beyond its parent. you can see the height of the "page" div (first div after ion-content) is what I'd expect.
![page](https://user-images.githubusercontent.com/11137058/141019668-a89aae1a-c730-46b7-9b63-e408712abb25.png)
but when I scroll the "section" div it's top is at the very top of the page.
![section](https://user-images.githubusercontent.com/11137058/141019820-f5221257-ffce-4181-991c-c5c55b2a3cfa.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please try this again using the latest version of Ionic 5? It looks like you are using Ionic 5.1 which was released before several scroll assist improvements.

**Comment by swernimo** [comment]
I updated `"@ionic/angular": "5.8.5",` are there any other packages I should update?

**Comment by liamdebeasi** [comment]
`@ionic/angular` should be the only package you need to update. Is this issue appearing when running in Capacitor or when running in mobile Safari?

**Comment by swernimo** [comment]
It's still happening after upgrading to 5.8.5. The behavior is a little different than previous. sometimes the page does not scroll up at all and sometimes it scrolls off the page (original bug behavior).  I'm only seeing the bug on smaller view ports. My iPhone Xr & iPhone 11 Pro and Samsung Galaxy S9+ do not have the bug. The new clip below is taken on an iPhone 6s running iOS 13.2.2. iPhone Xr is on 15.1, 11 Pro is running 14.6 and the Android is on 10.

https://user-images.githubusercontent.com/11137058/141176403-a7b708fc-ec8a-4067-8d7a-620e62ec1574.mov

**Comment by bchehraz** [comment]
Hello, I'm not sure if this is related, but I'm having an issue currently where focusing on a form element inside a modal on iOS doesn't scroll to the focused input field, even if the field will become hidden behind the keyboard... Are you guys also having this issue??

**Comment by sean-perkins** [comment]
> Hello, I'm not sure if this is related, but I'm having an issue currently where focusing on a form element inside a modal on iOS doesn't scroll to the focused input field, even if the field will become hidden behind the keyboard... Are you guys also having this issue??

@bchehraz can you see if you can replicate your issue with the repo I posted above: https://github.com/sean-perkins/24195-ion-input-keyboard?

**Comment by bchehraz** [comment]
Nope, no issue with the repo but it helped me solve my problem. I just needed an ion-content wrapping the modal content..... :sweat_smile: Oops. Thanks!
