### ISSUE TITLE
feat: datetime disable specific dates

### ISSUE THREAD

**Issue by himanshusukhpal** [ionic-team/ionic-framework#24209]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Ion-Datetime calendar I believe lacks a function to disable holidays/specific dates with a label

### Describe the Use Case

It would be great to have a way to mark specific dates as disabled not for every month

### Describe Preferred Solution

Ion2-calendar can be looked into and a similar daysConfig option can be added which takes an array of objects that have the details to edit a specific date, such as
daysConfig = [
{
  date: new Date(2021-10-05),
  disabled: true,
  cssClass: 'subtitle',
  subTitle: 'Govardhan Pooja'
}
]

![image](https://user-images.githubusercontent.com/10000755/141268498-7a99367f-17ea-4118-8733-c53105aa4801.png)

**Comment by sean-perkins** [comment]
Hello @himanshusukhpal, I am excited to announce that this feature will be available in the upcoming 6.1.0 release :tada:.
