### ISSUE TITLE
feat: support Angular 13

### ISSUE THREAD

**Issue by HyperLife1119** [ionic-team/ionic-framework#24235]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Support Angular 13.

### Describe the Use Case

Use ionic on Angular 13.

**Comment by Jahrenski** [comment]
ionic 5.8 works on my Angular 13 app
What is the problem you are having?

**Comment by HyperLife1119** [comment]
Oh sorry, I thought ionic has not yet supported Angular 13. If official support is confirmed, then this issue can be closed.

**Comment by liamdebeasi** [comment]
Thanks! Angular 13 support will be coming in Ionic 6 🎉 . Going to close this as the work to add support is complete. The next RC should provide full support for it.
