### ISSUE TITLE
bug: invalid package contents when installing @ionic/angular@5.9.0

### ISSUE THREAD

**Issue by oluwafemi-filed** [ionic-team/ionic-framework#24234]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

running npm install @ionic/angular 

install the required dependency in the dist folder

### Expected Behavior

it supposed to export the files/folder into the @ionic/angular folder inside the node_module directly not inside dist

### Steps to Reproduce

create new ionic project or run (npm install @ionic/angular ) on existing codes

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.0
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.13
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : 3.3.1
   @capacitor/core    : 3.3.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.18.1 (/usr/local/bin/node)
   npm    : 6.14.15
   OS     : macOS Big Sur

**Comment by Jahrenski** [comment]
Same here. Makes all '@ionic/angular'  imports unavailable.

**Comment by rossholdway** [comment]
Can also confirm this. Issues seems to be with the new v5.9.0 release - @liamdebeasi

**Comment by liamdebeasi** [comment]
Thanks! Looking into this and will cut a new release soon.

**Comment by oluwafemi-filed** [comment]
it also affect the 3wweks old ionic project that is using "@ionic/angular": "^5.5.2". The angular directory rewrite the files when i try to add ios support to the project

**Comment by liamdebeasi** [comment]
We have a fix in place and are preparing an Ionic 5.9.1 release.

**Comment by HyperLife1119** [comment]
I just want to raise this question. You are one step faster than me.

**Comment by liamdebeasi** [comment]
Ionic 5.9.1 has been released with this fix. Thanks for your patience!

```
npm install @ionic/angular@5.9.1
```
