### ISSUE TITLE
bug: opening modal quickly results in white screen

### ISSUE THREAD

**Issue by riderx** [ionic-team/ionic-framework#24230]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

if you click multiple time on action sheet button at one point it become full white and you cannot do anything anymore

### Expected Behavior

it shouldn't fail

### Steps to Reproduce

you can go to this codesanbox here :
https://codesandbox.io/s/vue-3-ionic-vuex-forked-rdckf?file=/src/App.vue

and click on the cross on top right corner multiple time.

### Code Reproduction URL

https://codesandbox.io/s/vue-3-ionic-vuex-forked-rdckf?file=/src/App.vue

### Additional Information

Here a video to see the problem

https://user-images.githubusercontent.com/4084527/142094136-10f725d2-a5eb-4d83-abd2-a98cf4a9a4fc.mp4

**Comment by amandaesmith3** [comment]
Thanks for the issue, I've resolved this via https://github.com/ionic-team/ionic-framework/pull/24380 and the fix will be available in a future release of Ionic 👍

**Comment by liamdebeasi** [comment]
Reopening this. The initial fix caused some expected issues (see https://github.com/ionic-team/ionic-framework/issues/24460). We will look into a better long term fix and reply here when we have more information.

For context, we prioritized fixing #24460 as we considered that to be higher priority. That fix will be in Ionic 6.0.3. As a result, I recommend staying on 6.0.2 until this thread's issue gets resolved. Thanks for your patience!

**Comment by liamdebeasi** [comment]
Hi there,

This appears to be resolved on the latest version of Ionic 6, so I am going to close this. If you are still running into an issue, please let me know. Thanks!
