### ISSUE TITLE
  46:2  error  Parsing error: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?

### ISSUE THREAD

**Issue by snolangps** [ionic-team/ionic-framework#24248]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When I run `ionic capacitor sync && ionic capacitor open ios`, it's very finicky. Sometimes it will build, and sometimes (more than not) I get an error of ```45:2  error  Parsing error: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?```, which doesn't make ANY sense, because when I go to the line (45:2) it's pointing to my data object. 

### Expected Behavior

I expect ionic to build as it should and open in xcode without errors, since the error is totally irrelevant to the situation and doesn't make any sense why it is failing, and sometimes it builds... 

### Steps to Reproduce

I can't say that this is happening to everyone, but I also can't be the only one having this issue.

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.8.5

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : not installed
   @capacitor/core    : 3.3.1
   @capacitor/ios     : 3.3.1

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.15.5 (/usr/local/bin/node)
   npm    : 6.14.11
   OS     : macOS Big Sur

### Additional Information

here is my data object ```	data () {
		return {
			location: false,
			position: <PositionObject>{},
			positions: new Array<any>(),
			watchId: 0
		}
	},```
	
and the interface being used ```interface PositionObject {
	longitude: number
	latitude: number
}```

**Comment by snolangps** [comment]
For reference, this also fails when running `vue-cli-service build` as well, just noticed that...

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
