### ISSUE TITLE
bug: Two ion-menu in different tabs unable to working properly

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#24240]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

I would like to use ion-menu in each tabs for different purposes. 
However it is working with bugs. When you interact with one menu, then try to open other, application give some bugs. 

### Expected Behavior

Both menus works properly in different tabs

### Steps to Reproduce

```bash
git clone https://github.com/roman-rr/ionic-menu-bug
cd ionic-menu-bug
npm i
ionic serve
```
1. Click menu button to open ion-menu 1
2. Close menu 1
3. Go to second tab page
4. Click menu button to open ion-menu 2
5. Close menu 3
6. Come back to first tab page and try to open ion-menu 1

### Code Reproduction URL

https://github.com/roman-rr/ionic-menu-bug

### Ionic Info

```
Ionic:
   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.5
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Utility:
   cordova-res (update available: 0.15.3) : 0.14.0
   native-run (update available: 1.5.0)   : 1.4.0

System:
   NodeJS : v14.17.6 (/usr/local/bin/node)
   npm    : 6.14.15
   OS     : macOS Monterey
```

### Additional Information

![ezgif-2-6025b995a858](https://user-images.githubusercontent.com/10646478/142255440-5e4b0e86-efe5-4b24-9d84-e4dee6a26629.gif)

**Comment by liamdebeasi** [comment]
Thanks! This looks to be related to https://github.com/ionic-team/ionic-framework/issues/18974, so I am going to merge the two.

**Comment by roman-rr** [comment]
Thank you very much, it was not easy to find this issue so i created this one.

**Comment by liamdebeasi** [comment]
No worries, thanks for the report!
