### ISSUE TITLE
bug: Modal not displaying in fullscreen (Stencil)

### ISSUE THREAD

**Issue by PabloBitGenoma** [ionic-team/ionic-framework#24249]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When the modal is shown it doesn't go full screen even though you specify the width and height as usual.

### Expected Behavior

With the code below the modal should render at fullscreen, **as it does in v5.**

### Code NOT working on  @ionic/core: 6.0.0-rc.3 and @stencil/core: 2.10.0

**Creating modal:**
```
const modal = await modalController.create({
    component: 'modal-app-client-edit'
    cssClass: 'modal-app-client-edit'
    componentProps: {
        cliente
    }
});
await modal.present();
```

**In modal-app-client-edit.tsx**
```
@Component({
    tag: 'modal-app-client-edit',
    styleUrl: 'modal-app-client-edit.css',
});
```

**And in modal-app-client-edit.css**
```
.modal-app-client-edit .modal-wrapper {
    width: 100%;
    height: 100%;
};
```

### Code Reproduction URL

https://github.com/PabloBitGenoma/ionic-modal-bug

**Comment by liamdebeasi** [comment]
In Ionic 6 `ion-modal` was converted to use the Shadow DOM, so you are no longer able to directly query `.modal-wrapper`: https://github.com/ionic-team/ionic-framework/blob/next/BREAKING.md#modal.

However, even in Ionic 5 you should not be querying for `.modal-wrapper` to set the dimensions. Instead, you should be using the `--width` and `--height` CSS Variables:

```
.modal-app-client-edit {
  --width: 100%;
  --height: 100%;
}
```

Can you try the above change and let me know if it resolves the issue?

**Comment by PabloBitGenoma** [comment]
> In Ionic 6 `ion-modal` was converted to use the Shadow DOM, so you are no longer able to directly query `.modal-wrapper`: https://github.com/ionic-team/ionic-framework/blob/next/BREAKING.md#modal.
> 
> However, even in Ionic 5 you should not be querying for `.modal-wrapper` to set the dimensions. Instead, you should be using the `--width` and `--height` CSS Variables:
> 
> ```css
> .modal-app-client-edit {
>   --width: 100%;
>   --height: 100%;
> }
> ```
> 
> Can you try the above change and let me know if it resolves the issue?

### **Done and working.**
I've tried with the custom properties before and messed around with classes, but didn't see about Shadow DOM.
Thank you for your rapid and nice response.
