### ISSUE TITLE
bug: Datetime UI does not update the value after it has changed programmatically.

### ISSUE THREAD

**Issue by NormanV41** [ionic-team/ionic-framework#24241]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Datetime UI does not show that the value has changed after it changed programmatically. This issue is unique for version 6.

### Expected Behavior

The Datetime UI should be updated when its value changes programmatically.

### Steps to Reproduce

- Start a new app with a blank template.
- add a Datetime component with its value bound to a component property.
- asynchronously update the value of the component property.
- observe that the UI does not show that the value has changed.

### Code Reproduction URL

https://github.com/NormanV41/ionic-issues-demo/tree/datetime-issue-v6

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /usr/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/lib/node_modules/@ionic/cli/index.js
       - /usr/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /usr/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/lib/node_modules/@ionic/cli/index.js
       - /usr/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.18.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : not installed
   @capacitor/core    : 3.2.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.16.1 (/usr/bin/node)
   npm    : 6.14.12
   OS     : Linux 5.14

**Comment by sean-perkins** [comment]
@NormanV41 thanks for reporting this issue 👍 

I've confirmed on your reproduction branch that this is an active issue. The internal value of the `ion-datetime` does update to the new value. You can bind to `(ionChange)` to see the value is emitted on change. 

However, it appears the visual state does not re-render correctly; specifically around the active day (`activeParts`).

**Comment by sean-perkins** [comment]
This issue has been resolved and will be available in the next release 🎉
