### ISSUE TITLE
Trying to use exitApp on ios devices does not take effect

### ISSUE THREAD

**Issue by chengpengvb** [ionic-team/ionic-framework#24259]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

As the personal privacy law requires the app to be used after the user agrees to the privacy agreement, if you do not agree, you will exit the app. According to the tutorial on the official website (https://ionicframework.com/docs/developing/hardware-back-button#exiting-the -app) I found it invalid using the exitApp method. I don’t know what’s going on on Android. At present, I only adapt to ios devices. After checking the related issues, I still haven’t solved it.

### Describe the Use Case

![image](https://user-images.githubusercontent.com/28288567/142966535-dc0c1373-600c-463d-b083-c13d3b1ca1e6.png)
![image](https://user-images.githubusercontent.com/28288567/142966558-b73a3c1a-1168-4a21-bd86-c27dfc48e65f.png)
![image](https://user-images.githubusercontent.com/28288567/142966571-a3677009-074a-4f24-941a-640cf7feb5f3.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you reproduce this issue in an Ionic starter app and provide a link to the repo? Also, if you are using Capacitor 3 you will need to have the `@capacitore/app` plugin installed.

**Comment by chengpengvb** [comment]
Thank you for your answer. I think what you said is right. Yesterday, due to time constraints, I directly changed the source code in WebViewDelegationHandler.swift, 
![image](https://user-images.githubusercontent.com/28288567/143156466-a56d86d5-decd-491c-836f-e0590c2cbbd1.png)

which is located in node_modules/@capacitor/ios/Capacitor/Capacitor/WebViewDelegationHandler.swift. I Will try the method you said, thanks

**Comment by indraraj26** [comment]
ExitApp isn't allowed in iOS

**Comment by liamdebeasi** [comment]
Ah thanks! I misread this as `exitApp` on Android. @indraraj26 is correct. The `exitApp` method is not allowed on iOS. You may be able to hack it to get it to work, but your app will likely get rejected during the App Store review process.
