### ISSUE TITLE
bug: display issue when changing certain CSS Custom Properties

### ISSUE THREAD

**Issue by MattDHill** [ionic-team/ionic-framework#24261]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

## Issue 1
```
--border-radius: 6px; 
--border-width: 1px;
--border-style: solid;
```
results in the corners being cut off, apparently because the border-radius attr is not cascading to item-native

## Issue 2
```
--highlight-height: 0;
```

results in a full border highlight, whereas it should eliminate the highlight per the docs.

## Issue 3
```
--highlight-color-valid: transparent;
```

results in the erasure of the bottom-border of the item.

## Issue 4
The input cursor is the same as the highlight color of the item.

### Expected Behavior

My goal here is to have a full border around an ion-item input that does not display a highlight color. The various approaches above worked fine in Ionic 5.

Input cursor should always be black, or a way to make it black is needed.

### Steps to Reproduce

Try out the CSS configurations above.

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.3
   @angular-devkit/build-angular : 13.0.3
   @angular-devkit/schematics    : 13.0.3
   @angular/cli                  : 13.0.3
   @ionic/angular-toolkit        : 5.0.3

Utility:

   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.5.0)   : 1.0.0

System:

   NodeJS : v16.10.0 (/usr/local/Cellar/node/16.10.0/bin/node)
   npm    : 8.0.0
   OS     : macOS Catalina

```

**Comment by sean-perkins** [comment]
Hey @MattDHill thanks for reporting this! Could you help me out by isolating these conditions in an example app and share the link back here?

Example repos help us greatly to validate the issue quickly and allow us to verify our solutions against them.

Thanks a bunch!

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
