### ISSUE TITLE
bug: Ionic React navigate with push from useIonRouter ignores direction when used as "replace"

### ISSUE THREAD

**Issue by babycourageous** [ionic-team/ionic-framework#24260]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

using Ionic React and `useIonRouter` the direction is not respected if the route action is "replace". It always goes "forward"
If the action is "push" (the default) all directions respected.

### Expected Behavior

Direction of the router should behave based on function call - no matter the route action.

### Steps to Reproduce

In the repo, fire up the app and you should go to the EXAMPLE menu item. Here there are three links to detail pages. 
Detail 1 has a button to redirect using "replace" with direction "none" - this will redirect but animate using "forward"
Detail 2 has a button to redirect using default behavior ("push") with direction "none" - this will redirect and have no page transition animation.

### Code Reproduction URL

https://github.com/babycourageous/ionic-use-ion-router-direction-bug

### Ionic Info

Ionic:

   Ionic CLI       : 6.17.1 (/Users/renedellefont/.fnm/node-versions/v14.17.6/installation/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.8.4

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : not installed
   @capacitor/core    : 3.2.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.6 (/Users/renedellefont/.fnm/node-versions/v14.17.6/installation/bin/node)
   npm    : 6.14.15
   OS     : macOS Big Sur

### Additional Information

Just let me know if there's any more info you need!

**Comment by gregorgretz** [comment]
i stumbled across the same problem and can confirm the described behavior

**Comment by fr3fou** [comment]
any updates?

**Comment by gregorgretz** [comment]
in my use case I just wanted to use 'none' as routerDirection to remove the page animation. My workaround was to pass the animationBuilder property and use an empty animation like that:

`router.push(n.href, 'none', 'replace', {}, createAnimation());`

maybe this will help someone

**Comment by ankrut** [comment]
Same issue with `v6.x`. I also noticed that it works only if there is no history yet. For example, if the first `push` is a `back` with `replace` then it will work properly with a `back` animation. But then all following `push` calls (with `replace`) will result in a `back` transition, regardless if the routerDirection is `back` or `forward`. Analog behavior if the first `push` is a `forward`.

So, a `push` with a `replace` seems to ignore the routerDirection unless it is the first call with no history yet. 

I found the following workaround

``` ts
const router = useIonRouter()

// navigation back
router.routeInfo.routeDirection = 'back'
router.push('some/path', 'back', 'replace')

// navigation forward
router.routeInfo.routeDirection = 'forward'
router.push('some/path', 'forward', 'replace')
```

**Comment by aeharding** [comment]
> in my use case I just wanted to use 'none' as routerDirection to remove the page animation. My workaround was to pass the animationBuilder property and use an empty animation like that:
> 
> `router.push(n.href, 'none', 'replace', {}, createAnimation());`
> 
> maybe this will help someone

This works, the only drawback is that the swipe back animation is broken.

**Comment by TylerAHolden** [comment]
I do not know why it works but I had to do a mix of both of these solutions....

```
ionRouter.routeInfo.routeDirection = 'none';
ionRouter.push(url, 'none', 'replace', {}, () => createAnimation());
```

**Comment by aeharding** [comment]
@TylerAHolden Unfortunately that doesn't solve it for me, the swipe back animation still doesn't work (due to forcing it off from `createAnimation()` call)

**Comment by TylerAHolden** [comment]
> @TylerAHolden Unfortunately that doesn't solve it for me, the swipe back animation still doesn't work (due to forcing it off from `createAnimation()` call)

Ah yes the swipe back still doesn't work.
