### ISSUE TITLE
feat: Ion-Nav should respect its own component "mode" and defaulting to the global mode.

### ISSUE THREAD

**Issue by bmidget** [ionic-team/ionic-framework#24264]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Ion-Nav currently uses stock page transitions based on the app-level `mode` ("ios" or "md").

But this component should allow its own "mode" which allows for simple choice of using pre-defined MD or iOS page transitions for that component only.

For example:

```vue
// This one uses the document mode
<ion-nav :root="SomeRootComponent"></ion-nav>

// This one uses the stock animations for the ion-nav component
<ion-nav :root="SomeRootComponent" mode="ios"></ion-nav>
```

### Describe the Use Case

Despite the app running in MD mode, the modal may make more sense to navigate within itself using the stock iOS push left/right animations.

### Describe Preferred Solution

Allow "mode" option on the `ion-nav` component.

**Comment by liamdebeasi** [comment]
Thanks! Looks like `ion-nav` does not have the same mode virtual prop that most other Ionic components have: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/nav/nav.tsx#L13

As a comparison, `ion-modal` has this: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/modal/modal.tsx#L18

We should probably add a virtual prop so all Ionic components can have their mode overridden.

**Comment by sean-perkins** [comment]
Hello @bmidget thanks for this feature request. After some initial investigation into this behavior, I found that by making `ion-nav` correctly inherit the `mode`, it will change the display of all page components within Nav, to that respective mode. 

Based on your use case, I believe the correct implementation would instead be setting the expected animation:
```html
<ion-nav :animation="iosTransitionAnimation"></ion-nav>
```

`iosTransitionAnimation` is available as a global constant from `@ionic/vue`. 

This will allow your nav page components to respect the application's mode, while using iOS page transitions.

An example can be found here: https://stackblitz.com/edit/angular-jkitzd?file=src%2FApp.vue,src%2Fcomponents%2FExample.vue

Can you let me know if this resolves your request?

**Comment by callumacrae** [comment]
> After some initial investigation into this behavior, I found that by making `ion-nav` correctly inherit the `mode`, it will change the display of all page components within Nav, to that respective mode.

That's the same as all the other components that you can override the mode for - e.g. if you set `mode="ios"` on an ion-modal component, you have to set `mode="md"` or `:mode="platform"` or whatever you want on any children of the modal. I don't see why you'd want it to be any different for the nav component?

(The animation workaround is super useful, though)

**Comment by bmidget** [comment]
As far as my use case, the animation work around is enough.

As for the consistency of the component modes, I don't really haver an opinion except I think it should work like other components when `mode` is set (whether that trickles down inside themselves or not).

**Comment by sean-perkins** [comment]
@callumacrae with the original request it sounds like the scenario is:

An app that is in `md` mode, that wants to use `ion-nav` with iOS page transitions. If the mode inherited to all the children of the `ion-nav`, it would mean that that experience would default to iOS for all the page components, when the base app is MD.

I believe `animation` is likely the best implementation pattern for that use case, regardless of the mode inheriting. 

Since the existing behavior does not inherit and hasn't since v4 or earlier, I would consider that change in behavior a breaking change to apps using Ionic. 

I think the best course of action here is to resolve this issue since the core request is handled and split out a new request to fix the mode behavior in v7.

**Comment by sean-perkins** [comment]
New issue is: https://github.com/ionic-team/ionic-framework/issues/25644

Resolving this one, feel free to comment if you have any questions/concerns; thanks everyone!
