### ISSUE TITLE
bug: [v6] popover documentation example issue

### ISSUE THREAD

**Issue by hakimio** [ionic-team/ionic-framework#24266]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

If you check [Triggers](https://beta.ionicframework.com/docs/api/popover#triggers) example, you'll see the following example code:
```html
<ion-button id="trigger-button">Right click me!</ion-button>
<ion-popover
  trigger="trigger-button"
  trigger-action="context-menu"
>
  <ion-content>
    <ion-list>
      ...
    </ion-list>
  </ion-content>
</ion-popover>
```
The example doesn't work as intended.

### Expected Behavior

The example should have `<ng-template>` inside `<ion-popover>` like [the basic Angular example](https://beta.ionicframework.com/docs/api/popover#angular) has.
```html
<ion-button id="trigger-button">Right click me!</ion-button>
<ion-popover
  trigger="trigger-button"
  trigger-action="context-menu"
>
  <ng-template>
    <ion-content>
      <ion-list>
        ...
      </ion-list>
    </ion-content>
  </ng-template>
</ion-popover>
```

### Steps to Reproduce

Inspect popover [Triggers](https://beta.ionicframework.com/docs/api/popover#triggers) example carefully.

**Comment by liamdebeasi** [comment]
Thanks! I added better examples in https://github.com/ionic-team/ionic-framework/pull/24267.
