### ISSUE TITLE
bug: Popover flickers when dismissed v6 (Stencil)

### ISSUE THREAD

**Issue by PabloBitGenoma** [ionic-team/ionic-framework#24274]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Issue opened as [requested here](https://forum.ionicframework.com/t/popover-flickers-when-dismissed/217682)

**I'm working with Ionic v6 rc3 and Stencil 2.10.**
The problem is that when the popover closes, it flickers. It does when I click in the inside options or backdrop.
Here's the visual demo:
![demo2](https://user-images.githubusercontent.com/94697541/143431782-e0c247b7-766b-45fc-a419-ae1334c79b6d.gif)

### Expected Behavior

As I tested on Ionic Ionic 5.9.1 and Stencil 2.10 the popover dismisses with the correct smooth animation.
Tested with the same exact code. (Neither CSS or js interferes with the popover)

### Steps to Reproduce

Same code used for both Ionic versions. In v6 flickers, in v5 not.

**Calling popover**
```
<ion-button onClick={ev => this.presentPopover(ev)}>
     <ion-icon name="ellipsis-horizontal" />
</ion-button> 
```

**Creating popover**
```
async presentPopover(ev: any) {
        const popover = await popoverController.create({
            component: 'popover-modal-configure-mold',
            cssClass: 'popover-modal-configure-mold',
            event: ev,
            translucent: true,
        });
        await popover.present();

        popover.onDidDismiss().then((data) => {
            if (data.data !== undefined) {
                if (data.data === 'copy') {
                    this.copyFromBuiltMold(); // just a console.log(), no logic
                } else {
                    this.saveMold(); // just a console.log(), no logic
                }
            }
        });
    }
```

**And rendering popover**
```
@Element() popover: HTMLElement;

    render() {
        return [
            <ion-list>
                <ion-item onClick={() => this.popover.closest('ion-popover').dismiss('copy')}>
                        Copiar de otro molde
                    <ion-icon name="copy" slot="end" />
                </ion-item>
                <ion-item lines="none" onClick={() => this.popover.closest('ion-popover').dismiss('save')}>
                        Guardar
                    <ion-icon name="save" slot="end" />
                </ion-item>
            </ion-list>,
        ];
    }
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. After updating to the latest version of Ionic 6, I am no longer able to reproduce this behavior. As a result, I am going to close this issue.

If you are still running into this issue, please open a new issue and provide a GitHub repo that I can use to verify the behavior. Thank you!
