### ISSUE TITLE
feat: add presence indicator to avatar component

### ISSUE THREAD

**Issue by luettgau** [ionic-team/ionic-framework#24275]
**Ionic version:**

[x] **4.x**
[x] **5.x**

**I'm submitting a ...** 

[ ] bug report
[ x] feature request

**Current behavior:**

It is complicated to add an presence indicator to an avatar component

![grafik](https://user-images.githubusercontent.com/20316146/143445949-160bd017-6ac3-4f31-9eb6-aa4f940e00dc.png)

**Expected behavior:**

A) Provide a property to give a presence color

![grafik](https://user-images.githubusercontent.com/20316146/143445849-d69e8f0e-1d3f-4c7e-9422-517041124e50.png)

```
<IonAvatar slot="start" presence="online">
        <img src="https://gravatar.com/avata /dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y" />
      </IonAvatar>
```
B) Provide a property to give a presence color and an icon

![grafik](https://user-images.githubusercontent.com/20316146/143445892-b70837db-ba61-4e4f-8890-1307d1079188.png)

```
<IonAvatar slot="start" presence="online" icon={checkmark} >
        <img src="https://gravatar.com/avata /dba6bae8c566f9d4041fb9cd9ada7741?d=identicon&f=y" />
      </IonAvatar>
```

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by sean-perkins** [comment]
@luettgau you should be able to accomplish similar UI with the usage of the default slot in `ion-avatar` and a little CSS for positioning. 

```
<ion-avatar>
    <img src="" />
    <span class="indicator"></span>
</ion-avatar>
```

```
ion-avatar {
  position: relative;
}

.indicator {
  width: 14px;
  height: 14px;
  display: block;
  border-radius: 999rem;
  background-color: green;
  position: absolute;
  bottom: 0;
  right: 0;
}
```

**Comment by sean-perkins** [comment]
With the example snippet above, I am going to close out this feature request for now.

At this time, it is more advantageous to keep the `ion-avatar` implementation very generic, to handle a variety of implementation patterns (not only focused on an active indicator). 

If the community requires more baked out variants of an avatar display in the future, we can evaluate what that could look like.

Thank you for submitting the feature request 🙂
