### ISSUE TITLE
feat: ion-select autoscroll to last selection

### ISSUE THREAD

**Issue by brentspector** [ionic-team/ionic-framework#24271]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

If an option is selected, ion-select will automatically scroll to the position in the ion-select-options list when opening the selection window.

### Describe the Use Case

When presented with a ion-select that has multiple pages worth of scroll, it is difficult and tedious to get back to the last place selected in the list.

### Describe Preferred Solution

This feature should be enabled by default. It could be a boolean property on ion-select components if developers do not want that feature.

### Describe Alternatives

I plan to make a component that outright skips using ion-select (see https://github.com/brentspector/reborn-pokepedia/issues/14) and instead provides a searchbar over a list of ion-items. However, the all-in-one functionality of an ion-select (plus the integration with Capacitor) makes ion-select much more attractive.

### Additional Information

I cannot show related code, but here is an issue with the steps to reproduce the issue on my app, 

App URL: https://brentspector.github.io/reborn-pokepedia/locations/
Issue URL: https://github.com/brentspector/reborn-pokepedia/issues/13

**Comment by sean-perkins** [comment]
Duplicate request of #19296. Closing in favor of that request to prevent duplicate tickets.

You can upvote (👍 ) that thread to let us know this feature is important to you.
