### ISSUE TITLE
Why new Ionic angular project created with old angular 12 version ?

### ISSUE THREAD

**Issue by Shivamshah1401** [ionic-team/ionic-framework#24276]
I have install both angular 13 and ionic 6 version globally still when I create new ionic angular projects why it is taking angular 12 version instead of latest angular 13 version ? 
I am attaching Package.json file here with

![package](https://user-images.githubusercontent.com/21077377/143470713-db0bfc8e-9f74-493c-9ac0-b376a9ea8a90.jpg)

**Comment by sean-perkins** [comment]
Globally installed packages do not take priority over the project-specified dependencies. You would need to remove the dependency from your project (which is not recommended), then the dependency would resolve from your globally installed dependencies. 

You can locally update the new Ionic project you've created with your preferred dependencies in the interim.

Ionic 6 will not be the default version, until it is officially released.

**Comment by AndriiNeverov** [comment]
Still seeing this even after Ionic 6 is officially released.
