### ISSUE TITLE
bug: Getting [ERROR:network_service_instance_impl.cc(179)] failed to grant sandbox access to network context data for ...

### ISSUE THREAD

**Issue by akshaykatale99** [ionic-team/ionic-framework#24272]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [ ] v5.x
- [ ] v6.x

### Current Behavior

Getting **[ERROR:network_service_instance_impl.cc(179)] failed to grant sandbox access to network context data for /data/data/com.app.name/app_webview/Default with result 7: no such file or directory (2)** when starting app on android 5, 6, 7 versions only. on android version 8+ devices app is working file. 

![Screenshot 2021-11-25 at 12 56 12 PM](https://user-images.githubusercontent.com/12472207/143397877-3632f130-3772-4404-aa2a-76f0ab654ab2.png)
.
and stuck the app at the startup after this error.

### Expected Behavior

the app should not be stuck at startup.

### Steps to Reproduce

it was working before last week and suddenly stops working on android 5, 6, 7 devices.

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 3.1.2, (and 40 other plugins)

Utility:

   cordova-res (update available: 0.15.2) : 0.10.0
   native-run (update available: 1.3.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v12.22.3 
   npm               : 6.14.7
   OS                : Windows 10

**Comment by sean-perkins** [comment]
Hello @akshaykatale99, after following up with the team the best place to receive help in this issue would be on the [Ionic Forums](https://forum.ionicframework.com/). 

Ionic (the framework) doesn't handle any of the app build process for you. You can use either Cordova (older solution) or Capacitor (managed and recommended by the Ionic team).
