### ISSUE TITLE
bug: Calendar does not respect hourCycle on current day when min is set

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/ionic-framework#24287]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I have this setup 

```
<ion-datetime
        #calendar
        size="cover"
        hourCycle="h23"
        [min]="now"
        [(ngModel)]="datetime"
      >
```
where now is `new Date().toISOString() //'2021-11-30T11:58:35.171Z'`

https://user-images.githubusercontent.com/12111716/144045927-9181c488-1480-4e41-8a71-a461d2253678.mov

Datetime doesn't respect `hourCycle` on the current date

### Expected Behavior

Hour

### Steps to Reproduce

`hourCycle` should stay consistent when min is set

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/jonathan/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.3
   @angular-devkit/build-angular : 12.2.11
   @angular-devkit/schematics    : 12.2.11
   @angular/cli                  : 12.2.11
   @ionic/angular-toolkit        : 5.0.3

### Additional Information

The issue does not appear when only the `YYYY-MM-DD` is passed to min.
As soon as the time is also there, it appears

**Comment by sean-perkins** [comment]
@jongbonga I believe this issue may have been resolved with recent datetime enhancements. Can you confirm the same on your end? Thanks!

<video src="https://user-images.githubusercontent.com/13732623/153279337-2f15e806-c222-4c44-a76b-e45bf957f7c2.mp4"></video>

**Comment by jongbonga** [comment]
yes, it has been resolved.
Thank you!
