### ISSUE TITLE
bug: Fixed slot in ion-modal sometimes behind content in iOS

### ISSUE THREAD

**Issue by tho-masn** [ionic-team/ionic-framework#24286]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

There is some strange behaviour when using fixed slots in ion-modals in Ionic Vue. Usually the fixed slot should appear above the content of the modal. This works fine in Chrome (Desktop). But as soon as I run the code in the iOS app, the fixed slot is behind the content. I've tried to reproduce the behaviour in a minimal repo: https://github.com/tho-masn/ionic-issues/tree/v5_modal_fixed_slot_overlap
Same is happening in Ionic Vue 6.0.0-rc.3: https://github.com/tho-masn/ionic-issues/tree/v6_modal_fixed_slot_overlap

I've also tried to debug it with the Safari Devtools. Looks like as soon as I update any CSS property of the ion-modal component some rerendering happens and the fixed slot appears above the content.

Chrome (correct):
<img width="374" alt="Bildschirmfoto 2021-11-29 um 17 54 15" src="https://user-images.githubusercontent.com/23264228/143910598-7868cb67-f0e4-438f-be67-9b0e1d0c5c21.png">

iOS (wrong):
![IMG_4212](https://user-images.githubusercontent.com/23264228/143910872-07b1404e-681b-468b-9a2e-9af544c31432.PNG)

### Expected Behavior

Fixed slots should always appear in the front.

### Steps to Reproduce

Check out the Repo URLs and run it on your iOS device.

### Code Reproduction URL

Ionic Vue v5.9.1: https://github.com/tho-masn/ionic-issues/tree/v5_modal_fixed_slot_overlap
Ionic Vue v6.0.0-rc.3: https://github.com/tho-masn/ionic-issues/tree/v6_modal_fixed_slot_overlap

**Comment by amandaesmith3** [comment]
I've resolved this via https://github.com/ionic-team/ionic-framework/pull/24300 and the fix will be available in a future release of Ionic.

In the meantime, adding `transform: translateZ(0)` to the element(s) in the `fixed` slot will do the trick 👍

**Comment by tho-masn** [comment]
Awesome, thanks for the quick fix!

**Comment by maximilianschmid** [comment]
Great, thx for the fast response!
