### ISSUE TITLE
feat: expose every single thing as shadow part (allow us to style components)

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [ionic-team/ionic-framework#24283]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Please, do not try to guess how ppl uses your component or how will they style them. If you rely on Shadow Parts, please expose  every single code that has any styles applied and can have any style applied. My main struggle is styling and customizing your component. Please don't force us to write js to apply css styles.

### Describe the Use Case

Style ANY  component in ANY possible way.

**Comment by sean-perkins** [comment]
@Melmoth-the-Wanderer it would be helpful to list possible use cases where you have struggled styling or customizing an Ionic component to meet your needs.

Shadow parts relies on giving an explicit name to the portion you are exposing out to the implementation. Anytime we are dealing with exposing things to developers, we have to take in consideration the consistency and developer experience of that API. Exposing every possible tag, while extremely open for custom implementations; can be confusing to developers on what parts to use and even cause unintended side-effects as a result of customizing nodes in ways they were never intended. 

If you could list which exposed parts are missing from our existing implementations, we would be happy to consider them in future releases 👍
