### ISSUE TITLE
bug: When we load list of Ion-card element in UI during scroll it's showing blank white screen and it's taking time to load the data in IOS. But it looks working fine in Android

### ISSUE THREAD

**Issue by tamil01** [ionic-team/ionic-framework#24284]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [ ] v5.x
- [ ] v6.x

### Current Behavior

When we load list of Ion-card in page it's taking more time to render and load and showing white screen. Sometimes we see the app is freezed. We noted this issue only occur in IOS build not Android build. The list count would be more then 500 items. We create the ion-card element using angular *ngFor. We implemented with Infinity scroll to check if that fixes the render issue. But upto render 100 items it's fine but if we added more then 100 items the application start slow and showing white screen in IOS.

### Expected Behavior

It should load the list of items without white screen or freeze the app.

### Steps to Reproduce

- Create a page with loading Ion-card with more then 200+ cards on a page via API response Data
- Run the app in IOS
- Scroll the list page to see the list of cards

### Additional Information

This issue only persists in IOS and It's looks working fine in Android

**Comment by tamil01** [comment]
I have added a sample app here to reproduce the issue - https://github.com/tamil01/ionic_starter
I have run the app using in IOS using capacitor
If you keep scroll down to the page you can see white screen appearing and also if you try to scroll to top you can see white screen after 300+ ionic card elements render in the app
Let me know if you need more details to reproduce.
Thanks

**Comment by sean-perkins** [comment]
@tamil01 thanks for the repository!

When dealing with large lists of data in Angular, it's strongly recommended to make use of a `trackBy` function to improve the render performant with `*ngFor`. `trackBy` allows Angular to better recycle the individual templates that are created for each index.

In your mark-up add the following to your template:
```html
<ion-card *ngFor="let data of loadedData; trackBy: dataTrackBy">
```

In your component's class, add the following:
```ts
dataTrackBy(index, data) {
   return data.id;
}
```

`id` appears to be an unique value that is returned from the example API.

I would strongly encourage looking into a virtual scroll library for Angular, if you finding yourself needing to render 300+ cards in a page. I would also encourage using `ion-img` or adding `loading="lazy"` to your image tags.

Can you try these suggestions and let me know if they resolve your issue?
