### ISSUE TITLE
bug: ion-datetime time overlay selector only updates touched hours or minutes when "hourValues" or "minuteValues" is set

### ISSUE THREAD

**Issue by Klunk75** [ionic-team/ionic-framework#24281]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

ion-datetime time overlay selector only updates touched hours or minutes when "hourValues" or "minuteValues" is set.
(example: if minuteValues is set as: minuteValues="0,15,30,45" and I only touch hours wheel - I don't touch the minutes wheel, that displays "00" - when I tap outside the overlay selector the time box only updates the hour I touched, minutes remains unchanged, to the default current minutes)

### Expected Behavior

I expect minutes in the time box are update as well (in the example above to "00", when I don't touch the minutes wheel)

### Steps to Reproduce

Can be reproduced on the samples in the official documentation: https://beta.ionicframework.com/docs/api/datetime

### Code Reproduction URL

https://github.com/ionic-team/ionic-docs/blob/main/static/demos/api/datetime/index.html

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.0 (/Users/comandante/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.3
   @angular-devkit/build-angular : 13.0.3
   @angular-devkit/schematics    : 13.0.3
   @angular/cli                  : 13.0.3
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : not installed
   @capacitor/core    : 3.3.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.13.0 (/Users/comandante/.nvm/versions/node/v16.13.0/bin/node)
   npm    : 8.1.0
   OS     : macOS Big Sur

**Comment by sean-perkins** [comment]
@Klunk75 updating user input controls when they are not directly interacted with, can be an accessibility concern. 

Can you share a few examples of interfaces of libraries that may behave similar to how you describe?

I would recommend if using the `minuteValues` increments and not wanting the current behavior; strip the time value from the date value that is being assigned to `ion-datetime`. This would default it to `00` and only update based on time selection.
