### ISSUE TITLE
feat: adding Ionic Stylus version

### ISSUE THREAD

**Issue by InfoLibre** [ionic-team/ionic-framework#24290]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Adding a Stylus version of Ionic.

### Describe the Use Case

Projects that already use solutions with Stylus. No need to lear a new CSS postprocessor.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify what you are looking to achieve? Ionic does not touch your application's CSS, so you should be able to use Sass, Stylus, Less, etc in your application already.

**Comment by InfoLibre** [comment]
Are Ionic CSS made with SCSS? Iif I want to modify them, I must learn SCSS.

**Comment by liamdebeasi** [comment]
Are you referring to the code base of Ionic or building applications with Ionic?

**Comment by InfoLibre** [comment]
Both. I don't know Ionic, I will perhaps use something else than Bootstrap. Ionic, Element+,  Fomantic-UI?

**Comment by liamdebeasi** [comment]
I guess I am a bit confused as to what you are trying to do. Are you trying to use Ionic to build an application with Rapido?

**Comment by InfoLibre** [comment]
Rapido is made with Vue 2, Go and Bootstrap. I don't know if the next version of Rapido with Vue 3 will still use Bootstrap or something else.

**Comment by liamdebeasi** [comment]
It sounds like you are looking to build with Ionic. In that case, your application should be compatible with Stylus already as long as Rapido supports Stylus. As I mentioned in https://github.com/ionic-team/ionic-framework/issues/24290#issuecomment-983753723, Ionic does not touch your CSS.

Does this address your concern?

**Comment by InfoLibre** [comment]
Yes, we are using Stylus in Rapido. I don't want to use different CSS preprocessors in the next version, only Stylus (and CSS). If I can replace Bootstrap by Ionic, without using SCSS/Sass, why not.

**Comment by liamdebeasi** [comment]
In that case, you should be able to use Stylus with Ionic. Since Ionic does not manage your styles, there should be no additional setup required to get Stylus to work with Ionic components.

I am going to close this since there is nothing actionable from Ionic's end. If you have additional questions about building with Ionic, feel free to post on the [Ionic Forum](forum.ionicframework.com). Thanks!

**Comment by InfoLibre** [comment]
Thank you for your informations.
