### ISSUE TITLE
feat: ion back button with custom icon  

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#24304]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Request you to add one more props in ion-back-button to use custom svg/icon just like ion-icon with src

### Describe the Use Case

We can add custom back button other than ionicons via props.

### Describe Preferred Solution

For now we can add
iconUrl

Long Term: 
** Would be breaking changes **
so that ion-back-button can have similar props name as ion-icon
```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button text="" name="add" src=""></ion-back-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```
new Props:
```
name | src
```

**Comment by sean-perkins** [comment]
Thanks for the feature request!

In addition to exposing more of the icon props to the top-level `ion-back-button`, it could also make sense to support a `slot` to have complete flexibility in the implementation.

**Comment by sean-perkins** [comment]
@indraraj26 looks I've learned something new today.

`ion-icon` supports a property called `icon` which handles both the `name` and `src` approach: https://github.com/ionic-team/ionicons/blob/main/src/components/icon/icon.tsx#L62.

The back button is making use of this implementation pattern, so you can already use:

```html
<ion-back-button icon="https://example.com/my-img.svg"></ion-back-button>
<ion-back-button icon="add-outline"></ion-back-button>
```

This means the feature is already fully supported. Please reply if that's not the case or if I've misunderstood your request.

**Comment by indraraj26** [comment]
Thank you @sean-perkins, Its works
