### ISSUE TITLE
bug: clearOnEdit has no effect in ion-input

### ISSUE THREAD

**Issue by tvanesse** [ionic-team/ionic-framework#24306]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Pretty much the same problem as in #17055: setting `clearOnInput` on an `ion-input` has no effect. That is, the value of the input is **not** cleared when it receives focus.

### Expected Behavior

As the name suggests, it **should** clear the input when it's focused.

### Steps to Reproduce

Start a blank project

```
$ ionic start
```

Then in `home.page.html`, insert

```
<ion-input type="number" [clearOnEdit]="true"></ion-input>
```

```
$ ionic serve
```

See for yourself: try to set any value in the `ion-input`, then click outside of it and back inside again. The value doesn't get cleared.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/home/thomas/.nvm/versions/node/v14.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.3.2
   @capacitor/android : not installed
   @capacitor/core    : 3.3.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.15.1 (/home/thomas/.nvm/versions/node/v14.15.1/bin/node)
   npm    : 6.14.8
   OS     : Linux 5.4

**Comment by tvanesse** [comment]
The way I currently work around the problem is by listening to `ionFocus` and clearing the input's value in the handler. But being able to use `clearOnInput` would be much better.

**Comment by liamdebeasi** [comment]
Thanks for the issue. When `clearOnEdit` is `true`, the value of the input will be cleared after focus upon edit: https://ionicframework.com/docs/api/input

In other words, the value is not intended to be cleared the moment you focus the input. Does this address your concern?

**Comment by tvanesse** [comment]
Thanks for the clarification @liamdebeasi. My bad, I should have been more _focused_ (got it?) when I read the doc.

I guess listening to `ionFocus` to implement what I want to achieve _is_ the way to go then :-)
