### ISSUE TITLE
bug: Angular ion-item combined with stacked ion-label loses item-label-stacked class once ion-chip is added

### ISSUE THREAD

**Issue by astukanov** [ionic-team/ionic-framework#24312]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

**ion-item** combined with **stacked ion-label** loses **item-label-stacked** class once **ion-chip** is added inside **ion-item**. 

### Expected Behavior

ion-item stays in stacked mode after ion-chip is added 

### Steps to Reproduce

- Create ion-item with input and add chip elements which will be populated once input changes.
- Once an ion-chip is added inside the ion-item element the ion-item loses the item-label-stacked class.

### Code Reproduction URL

https://github.com/astukanov/ion-label-stacked-with-chip-bug

**Comment by sean-perkins** [comment]
@astukanov thanks for the bug report and reproduction app!

The issue here is the use of multiple `ion-label` that re-render in an `ion-item`. When `ion-label` first renders, it emits an event to update the `ion-item` with the correct CSS classes based on the label's position. 

With the usage of `*ngFor` you are cause a new `ion-label` to render, which notifies `ion-item` that an `ion-label` without a `position="stacked"` has rendered and this removes the class.

```html
<ion-item>
  <ion-label position="stacked">Label</ion-label>
  <ion-chip *ngFor="let value of control.value">
    <ion-label>{{value}}</ion-label>
  </ion-chip>
</ion-item>
```

To fix your problem, update the `ion-label` to any other tag (`span` or `p`).
```html
<ion-chip *ngFor="let value of control.value">
  <span>{{value}}</span>
</ion-chip>
```

Can you let me know if this solves the problem on your end?

**Comment by astukanov** [comment]
Hi @sean-perkins

Thanks a lot for your reply and support. Yes, using span inside chips instead of ion-label works like a charm. 
Would it maybe make sense to change the examples in https://ionicframework.com/docs/api/chip to avoid such incidents, or does ion-label inside a chip provide its own advantages?

**Comment by sean-perkins** [comment]
@astukanov Really good question regarding the documentation. I'll consult with the team and discuss best options for this issue. 

There's related issues around `ion-item` and `ion-label` that highlights other flaws that exist in the current implementation pattern (#22541). 

The relationship of how the inner `ion-label` can alter the outer `ion-item`, results in a small decrease in performance with re-rendering and also causes related side effects such as this bug; where the last rendered `ion-label` overrides the ion-item completely. 

I've started to explore this issue privately and there's a few paths that have presented themselves (although I am open to suggestions):
1. Only allow the first child that matches `ion-label` to modify the `ion-item`. This would allow multiple `ion-label`, but could cause odd behaviors that aren't immediately clear to the implementer.
```html
<ion-item>
   <ion-label position="stacked">Email</ion-label>
   <ion-input></ion-input>
   <ion-label>Because this is last it will not affect ion-item.</ion-label>
</ion-item>
```

2. Introduce a new property for `ion-label`, such as `main` that would allow the implementer to hard-set the label that is the main label for the item's container. 
```html
<ion-item>
   <ion-label position="stacked" main="true">Email</ion-label>
   <ion-input></ion-input>
   <ion-label>Your email must contain a .com</ion-label>
</ion-item>
```


3. Have explicit variants of `ion-item` that removes the need for implementers to maintain the `ion-label` themselves, such as:
```html
<ion-stacked-item label="Plain text">
   <ion-input></ion-input>
</ion-stacked-item>

<ion-stacked-item color="secondary">
   <div slot="label">
        Slot usage of label
   </div>
   <ion-input></ion-input>
</ion-stacked-item>
```

4. Extend `ion-item`'s API to allow specifying the main label ID that is used for the implementation. Ionic could generate the label ID automatically (a consistent generated value) or you could use your own (preferred). 

```html
<ion-item labelId="emailLbl">
   <ion-label id="emailLbl" position="stacked">Email</ion-label>
   <ion-input></ion-input>
</ion-item>
```

Option 3 is currently the only path that resolves the inner contents, automatically re-rendering the `ion-item` on first paint, but is also the largest change for Ionic developers who have been using `ion-item` for many years.

**Comment by astukanov** [comment]
Hi @sean-perkins 
Very Interesting proposals. Thanks!

To be honest I'm very new to Ionic and havent had the possibility et to deep-dive into the frameworks wearabouts.

From my experience option 3 would add further complexity to the framework, would be great to avoid this if possible.

The id solution (4), is so far my favorite. It allows to keep the current implemetation as is and provides additional functionality while also being robust. An ```ion-label``` could be passed per reference to ```ion-item```. If a reference is set it would ignore events from other ```ion-labels```'s and prevent interferance with current settings.

For example this could be the solution:

```typescript
  <ion-item [labelRef]="label">
     <ion-label #label position="stacked">Email</ion-label>
     <ion-input></ion-input>
  </ion-item>
```

Furthermore an ```ion-label-base``` component could be extracted from ```ion-label``` and two subclasses can be created from it: ```ion-label``` with current behavior, and an ```ion-label-secondary``` | ```ion-tag``` | ```ion-stamp```... which also extends it and has just a subset of the```ion-label``` functionality e.g. does not propagate events to the ```ion-item``` component.

**Comment by liamdebeasi** [comment]
Hi there,

We are proposing some changes to form components that seek to resolve this issue. We would love your feedback on these proposed changes! You can read more about the changes and leave comments here: https://github.com/ionic-team/ionic-framework/discussions/25661

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with ion-input. This issue is fixed when using that new syntax. We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new input syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
