### ISSUE TITLE
feat: range, add reference point to start range slider at

### ISSUE THREAD

**Issue by sachingarg05** [ionic-team/ionic-framework#24348]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

ion-range shows an active bar which starts from extreme left (0 value) to current knob location. 

Very often ion-range needs to have its floor value (or base value) in the center or somewhere else. In these cases, it is required for the active bar to show between the floor value and current knob value, instead of always starting from 0 (extreme left).

### Describe the Use Case

A slider to reduce or increase brightness of an image.

### Describe Preferred Solution

Adding a 'floor' value attribute for ion-range, and then updating the left/right calculation of active bar to start from 'floor' value to current knob value (instead of always starting from 0 to current knob value)

### Related Code

/main/core/src/components/range/range.tsx, line 424
```
    const barStart = `${ratioLower * 100}%`;
    const barEnd = `${100 - ratioUpper * 100}%`;

```

These calculations will need to be updated to start from a floor value (or base value) to current knob value, instead of always starting from 0 (ratioLower is always zero for single knob ion-range).

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a code sample of the issue you are running into to help me better understand your use case?

**Comment by sachingarg05** [comment]
Consider this ion-range with min and max of -100 and 100
```
<ion-range color="dark" [min]="-100" [max]="100" [value]="0" [snaps]="10" [step]="10" mode="md" pin="true">
```
![image](https://user-images.githubusercontent.com/4737179/145359734-0ba12974-8f42-4782-b4eb-f776b8a81362.png)

Side note: Maybe the 'tick' mark at 'floor value' location can also be slightly 'heavier' than other tick marks.

**Comment by liamdebeasi** [comment]
Thanks! That makes sense. Do you happen to have examples of other applications/libraries that offer this behavior?

**Comment by sachingarg05** [comment]
ngx-slider has this option, by setting property 'showSelectionBarFromValue'

On their demo page, check the demo for "Slider with visible selection bar from specified value":

https://angular-slider.github.io/ngx-slider/demos#selection-bar-from-value-slider

**Comment by liamdebeasi** [comment]
Thank you! I discussed with the team and we think this would be a good feature to add to Ionic.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25598 and the feature will be available in an upcoming release of Ionic.

**Comment by sachingarg05** [comment]
Thanks 👍
