### ISSUE TITLE
bug: Ionic React 6.0.0 doesn't work in Vite

### ISSUE THREAD

**Issue by elylucas** [ionic-team/ionic-framework#24357]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Hello,

Booting up a project with Vite and manually adding the ionic dependencies isn't working in @ionic/react 6.0.0. It did work in 6.0.0-rc.2, but looks like a regression in rc.3.

It appears that some classes applied to elements are off. Here is a few screenshots showing the diffs between 6.0.0 and rc2:

With @ionic/react@6.0.0
![image](https://user-images.githubusercontent.com/168135/145445798-374c2ed1-c694-4865-9a0f-b2bd26a2a766.png)

With @ionic/react@6.0.0-rc.2
![image](https://user-images.githubusercontent.com/168135/145446159-4ad060bd-e67b-43c4-ab40-1553997c90aa.png)

Applying the correct classes manually to the 6.0.0 `html` and `ion-app` elements gets some of the elements to appear but it seems the problem run deeper:

![image](https://user-images.githubusercontent.com/168135/145447538-64f45ca8-1968-4f42-ae69-aa3ad25d48d6.png)

There is also a warning in the console when vite starts up, but not sure if its related or not:

```bash
10:35:58 AM [vite] warning:
/Users/elylucas/projects/ionictestapps/react/ionic-react-tabs/node_modules/.vite/chunk-MLJBYYQS.js
1846|      return module[exportName];
1847|    }
1848|    return import(
   |                  ^
1849|      /* webpackInclude: /\.entry\.js$/ */
1850|      /* webpackExclude: /\.system\.entry\.js$/ */
The above dynamic import cannot be analyzed by vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.
```

### Expected Behavior

Site should pull up and work normally

### Steps to Reproduce

Here is a demo repo: https://github.com/elylucas/ionic-react-tabs-vite-starter

run `npm install` and `npm run dev` and you will see the site pulls up but no components are visible:

![image](https://user-images.githubusercontent.com/168135/145447088-90977370-f90b-4944-924d-ea51bd06d153.png)

### Code Reproduction URL

 https://github.com/elylucas/ionic-react-tabs-vite-starter

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/Users/elylucas/.nvm/versions/node/v17.2.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.0

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v17.2.0 (/Users/elylucas/.nvm/versions/node/v17.2.0/bin/node)
   npm    : 8.1.4
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Hey Ely!

It looks like your app does not call `setupIonicReact`. This is required for Ionic's classes to get set properly. We switched off the lazy loaded Ionic Core bundle for Ionic 6, so we could no longer rely on that to automatically initialize Ionic for us.

You will need to import `setupIonicReact` from `@ionic/react` and call it in App.tsx. Can you try that and let me know if it resolves the issue?

Here is the full Ionic 6 migration guide: https://ionicframework.com/docs/next/intro/upgrading-to-ionic-6#react

**Comment by elylucas** [comment]
Ahh that was it, seems to work calling setupIonicReact. The warning in the console still appears but thats probably a different issue. Thanks Liam!

**Comment by liamdebeasi** [comment]
Glad it's fixed! The warning is probably this: https://github.com/ionic-team/ionic-framework/issues/23823
