### ISSUE TITLE
feat: Disable swipeGesture on IonRouterOutlet

### ISSUE THREAD

**Issue by Livijn** [ionic-team/ionic-framework#24354]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like to disable `swipeGesture` on `IonRouterOutlet` only for certain pages. I have tried using `<ion-router-outlet :swipe-gesture="false" />` but that's not possible looking at:

https://github.com/ionic-team/ionic-framework/blob/672ab80807f9f6dc600aaf8a57a09d041b418123/packages/vue/src/components/IonRouterOutlet.ts#L89-L90

### Describe the Use Case

I have a `IonMenu` on the left side of a sub router page. When swiping is enabled, I can't open that menu.

**Comment by amandaesmith3** [comment]
Thanks for the issue. Could you create a code reproduction and link to the repo so we can better understand your use case?

**Comment by Livijn** [comment]
Here is a GIF showing what happens atm: https://gyazo.com/ec3d7c2b96f1c0b1e3a066cb8bcf3d9f

Maybe a better user experience would be to disable the swipeGesture on the menu, but only on "open". I would still want the users to be able to swipe to close.

**Comment by amandaesmith3** [comment]
Would it be possible for you to post a code repo that reproduces the behavior? I want to make sure I fully understand the use case before diving in. Here's our guide on creating a code reproduction: https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction
