### ISSUE TITLE
bug: Blank page in Ionic app with visible tab-bar

### ISSUE THREAD

**Issue by Algoritm211** [ionic-team/ionic-framework#24363]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

While I'm entering to the main page of my Ionic application as PWA or mobile I see blank page with tab-bar.

That is, I have an application that suddenly stopped displaying the main content on the page. My splash screen, as well as the tab bar, load and work fine for me, but there is no content on the page, just a blank page.

I think it's problem with Ionic routing, but all right, no errors in console, which may be corresponding with it. 

<img width="1920" alt="Снимок экрана 2021-12-10 в 11 46 33 (2)" src="https://user-images.githubusercontent.com/60394886/145553418-6d9b1fa9-0c8a-47ef-bc35-96704ba86fbb.png">

<img width="1920" alt="Снимок экрана 2021-12-10 в 11 51 32 (2)" src="https://user-images.githubusercontent.com/60394886/145554186-73c6e894-859a-4a33-8c3f-797870e9b25a.png">

I really hope for your help)

### Expected Behavior

All rendering good and I can see tab-bar and main content of my application on the PWA and Web-View

### Steps to Reproduce

Blank page in Ionic app with working tab-bar and splash screen

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.9.2

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/opt/homebrew/Cellar/node@16/16.13.1/libexec/node)
   npm    : 8.1.2
   OS     : macOS Big Sur

**Comment by maylorsan** [comment]
The same. :(

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
