### ISSUE TITLE
bug: Ionic migration from 5 to 6 - No display

### ISSUE THREAD

**Issue by fortesp** [ionic-team/ionic-framework#24367]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Hello,
I’ve been trying to migrate from version 5.9 to 6.
After fixing all the differences and a successful compile, when i execute the project nothing gets displayed anymore, unless i remove or comment the `import '@ionic/react/css/normalize.css';` from the `App.tsx` or in some other cases only the `import '@ionic/react/css/core.css';`

I am not sure whether this is an actual bug. But by following the [guide](https://ionicframework.com/docs/next/intro/upgrading-to-ionic-6) and not finding anything related to what we should import, i can only assume its undesirable behaviour and the imports are still valid.

It would be great if there was already available template projects of the version 6 so we can see the actual differences.

Thank you.

### Expected Behavior

No blank screen and a normal template project look and behaviour.

### Steps to Reproduce

**Create a new project**

`ionic start myApp tabs --type react`

**Upgrade to version 6**

```
npm install @ionic/react@6 @ionic/react-router@6 @ionic/core@6
npm install react@latest react-dom@latest
npm install @types/react@latest
npm install @types/react-dom@latest 
npm install ionicons@latest
```

### Ionic Info

`[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.0

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Big Su`

**Comment by fortesp** [comment]
`
setupIonicReact({
    mode: 'ios',
});
`

I just discovered that this must be in the code as well. Missing in the template though.

**Comment by liamdebeasi** [comment]
Hey there,

We will have new starters coming in a few days. Thanks for the report, and glad the issue is resolved.
