### ISSUE TITLE
bug: picker not rendering columns

### ISSUE THREAD

**Issue by natqe** [ionic-team/ionic-framework#24366]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

using 'useIonPicker' as the example in the docs will not display the columns as expected

### Expected Behavior

using 'useIonPicker' as the example in the docs should display the columns as expected

### Steps to Reproduce

just do exactly what is written in ionic docs for react

### Code Reproduction URL

- [https://github.com/sean-perkins/issue-ionic-react-picker-24366](https://github.com/sean-perkins/issue-ionic-react-picker-24366)

**Comment by amandaesmith3** [comment]
Thanks for the issue, confirming I can replicate. The `ion-picker-column` components don't render any content. I'm seeing this in both React and Vue, but not in core alone.

It looks like the regression was between rc-3 and rc-4. A short-term workaround would be to downgrade to rc-3: `npm install @ionic/react@6.0.0-rc.3 @ionic/react-router@6.0.0-rc.3`

**Comment by sean-perkins** [comment]
Adding some additional notes as well. The inner `ion-picker-column` element isn't being hydrated/initialized. 

Created a repository to verify against (react): https://github.com/sean-perkins/issue-ionic-react-picker-24366

With the issue being only in Vue/React, it's likely a result of: https://github.com/ionic-team/ionic-framework/commit/13d4418588b98d301b05ebd94e0eac670163a553

**Comment by sean-perkins** [comment]
@natqe thanks for reporting this issue!

This issue has been resolved and will be available in the next release of Ionic 6 (`^6.0.1`).
