### ISSUE TITLE
bug: Cannot focus any element inside of IonModal while IonMenu is open.

### ISSUE THREAD

**Issue by Cyral** [ionic-team/ionic-framework#24361]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Elements inside an IonModal should be focusable (and editable) at all times. When an IonMenu is open in the background, the focus gets trapped inside of the menu and input elements inside the modal cannot be used.

https://user-images.githubusercontent.com/4945029/145516016-91451409-04c7-4d3a-8bc1-8dff4b11f79e.mov

### Expected Behavior

Elements inside an IonModal cannot be focused (meaning inputs cannot be typed in) if an IonMenu is open (behind the modal).

### Steps to Reproduce

Create an IonMenu with a button that launches an IonModal. Both the menu and the modal should have an input element. If the menu has no inputs, the bug doesn't seem to occur.

### Code Reproduction URL

https://github.com/Cyral/ionic-24361

### Ionic Info

Ionic 5.9.2 w/ React 

_No response_

### Additional Information

The input element inside the IonModal receives a focus event, but it is quickly blurred and the last descendant of the IonMenu is then focused. The stack trace from adding a focus event handler tot he last menu descendant is:

```
t.focusLastDescendant	@	ion-menu_3.entry.js:1
t.trapKeyboardFocus	@	ion-menu_3.entry.js:1
handleFocus	@	ion-menu_3.entry.js:1
```

I believe this commit introduced in 5.8.5 is the issue: https://github.com/ionic-team/ionic-framework/commit/bdb268aa12c5bf411c96529672486d35e018cefa Reverting to 5.8.4 fixes the issue

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide some more context as to why the menu needs to stay open when the modal is also visible in this scenario? I would like to understand the use case before we make any potential changes.

In general, focus should remain trapped inside of a menu when it is open to keep the experience accessible, which is why the focus is not being moved to the modal.

**Comment by Cyral** [comment]
> Thanks for the issue. Can you provide some more context as to why the menu needs to stay open when the modal is also visible in this scenario? I would like to understand the use case before we make any potential changes.
> 
> In general, focus should remain trapped inside of a menu when it is open to keep the experience accessible, which is why the focus is not being moved to the modal.

In my app, the menu has various controls (including inputs) to filter items in a list. These filters can also be saved by the user, and later edited. If the user edits a filter, the menu should not close otherwise they will lose their place after closing the modal.

In any case, the focus should be trapped in the menu or modal that is on top of all other content.

**Comment by hoangnv2nf** [comment]
I have same issue in Ionic v6.
![image](https://user-images.githubusercontent.com/86584361/146906293-1cc27fb2-2c7f-4385-9e43-46490c1d265c.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can everyone try the following dev build and let me know if it resolves the issue?

**Angular**
```
npm install @ionic/angular@6.0.4-dev.1642713982.5768e9d
```

**React**
```
npm install @ionic/react@6.0.4-dev.1642713982.5768e9d @ionic/react-router@6.0.4-dev.1642713982.5768e9d
```

**Vue**
```
npm install @ionic/vue@6.0.4-dev.1642713982.5768e9d @ionic/vue-router@6.0.4-dev.1642713982.5768e9d
```

**Stencil/Vanilla JavaScript**
```
npm install @ionic/core@6.0.4-dev.1642713982.5768e9d
```

**Comment by Cyral** [comment]
@liamdebeasi Thank you, it resolves it for me.

**Comment by liamdebeasi** [comment]
Great! I am going to keep this issue open until #24611 is merged. Thanks for testing!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24611, and a fix will be available in an upcoming release of Ionic Framework.
