### ISSUE TITLE
bug: @awesome-cordova-plugins/qr-scanner not found

### ISSUE THREAD

**Issue by Singh-danskapps** [ionic-team/ionic-framework#24376]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [x] v6.x

### Current Behavior

unable to install @awesome-cordova-plugins/qr-scanner      
npm install @awesome-cordova-plugins/qr-scanner      
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@awesome-cordova-plugins%2fqr-scanner - Not found
npm ERR! 404 
npm ERR! 404  '@awesome-cordova-plugins/qr-scanner@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

### Expected Behavior

should install qr-scanner    
on command
npm install @awesome-cordova-plugins/qr-scanner   

### Steps to Reproduce

npm install @awesome-cordova-plugins/qr-scanner   

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 23 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

### Additional Information

cannot find neither in repo
 https://www.npmjs.com/search?q=%40awesome-cordova-plugins%2Fqr-scanner

**Comment by sean-perkins** [comment]
Hello @Singh-danskapps this is not an issue with Ionic.

If you'd like to report the issue you can do so here: https://github.com/danielsogl/awesome-cordova-plugins.

The reason for this package no longer existing on the registry is explained here: https://github.com/danielsogl/awesome-cordova-plugins/issues/3778#issuecomment-929220465.

If you are looking for a successor to the legacy cordova plugin, I would highly recommend the Capacitor barcode scanner plugin: https://github.com/capacitor-community/barcode-scanner

**Comment by 1907382219** [comment]
The QR-Scanner plugin is very important in my project😥.
I can't upgrade to ionic6 for the time being

**Comment by Singh-danskapps** [comment]
As sean says its not a ionic issue. :)

Just a suggestion : You can also install from ionic native plugins  

 ionic cordova plugin add cordova-plugin-qrscanner
 npm install @ionic-native/qr-scanner

Then import as 

import { QRScanner, QRScannerStatus } from '@ionic-native/qr-scanner/ngx';
