### ISSUE TITLE
bug: ion-datetime in RTL shows the time picker in reverse order

### ISSUE THREAD

**Issue by MuhAssar** [ionic-team/ionic-framework#24378]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

in RTL application (dir=rtl)
ion-datetime component shows the time picker in reverse order, the hours on the right and the minutes on the left.

### Expected Behavior

ion-datetime component should show the time picker in the same order regardless of the direction ( rtl or ltr), the hours on the left and the minutes on the right,  as this is a universal agreement on how to read time.

### Steps to Reproduce

set 
**< html dir="rtl" >**

and use  
**< ion-datetime presentation='time' >< /ion-datetime >**

observe the order of the hours and minutes picker

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/mohamed/.nvm/versions/node/v14.17.5/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0
   @angular-devkit/build-angular : 13.1.1
   @angular-devkit/schematics    : 13.1.1
   @angular/cli                  : 13.1.1
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android broken
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 18 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : not installed globally

System:

   ios-sim : 8.0.2
   NodeJS  : v14.17.5 (/Users/mohamed/.nvm/versions/node/v14.17.5/bin/node)
   npm     : 6.14.14
   OS      : macOS Big Sur
   Xcode   : Xcode 12.5.1 Build version 12E507

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24546, and a fix will be available in an upcoming release of Ionic Framework.
