### ISSUE TITLE
bug: Controllers are typed as any after upgrading to Ionic 6

### ISSUE THREAD

**Issue by raymer** [ionic-team/ionic-framework#24387]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

After upgrading to Ionic 6. I noticed typescript errors when looking at my existing use of `modalController` in my Vue components related to trying to use `modalController.onDidDismiss<T>`. 

I then noticed that it's typed as `any` in `controllers.d.ts`.

![image](https://user-images.githubusercontent.com/490221/145919657-8bbd351b-d4b2-4d53-ba36-4d021a6409b9.png)

### Expected Behavior

The controllers are strongly typed

### Steps to Reproduce

- Open Ionic 6 application
- import modalController from @ionic/vue
- notice it's typed as `any`

### Ionic Info

Ionic:

   Ionic CLI       : 5.4.16 (C:\Users\rayme\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/vue 6.0.0

Capacitor:

   Capacitor CLI   : 3.2.4
   @capacitor/core : 3.2.4

Utility:

   cordova-res : not installed
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.0
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Thanks for reporting this issue!

It looks like when introducing custom elements, the `createController` method was introduced, which doesn't carry forward the types of the individual controller arguments to the return type.
