### ISSUE TITLE
bug: v6, overlay controllers not defining backdrop

### ISSUE THREAD

**Issue by raymondboswel** [ionic-team/ionic-framework#24393]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

My project is currently running on 6.0.0-rc3 and the action sheet controller works as expected. When upgrading to 6.0.0, I get the following error: 

![Uploading image.png…]()

### Expected Behavior

The actionsheet should keep working. 

### Steps to Reproduce

Clone the reproduction project
> npm i
> npm run dev:start

Click the FAB to see the action sheet. 

Update to 6.0.0, and run the project again.

### Code Reproduction URL

https://github.com/raymondboswel/ionic-modal-reproduction

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please isolate your test case a bit more? I am getting some errors for 3rd party dependencies when trying to install. In particular, I am receiving this error:

```
pm ERR! code ETARGET
npm ERR! notarget No matching version found for tailwindcss@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

In order for us to effectively triage this issue, the sample app should only include the code necessary to reproduce the issue.

**Comment by raymondboswel** [comment]
Hi @liamdebeasi, apologies for the deps not installing, I have pinned the offending dependency. You can pull the latest branch now to see the exception being thrown :+1:

**Comment by liamdebeasi** [comment]
Thanks. Now I am getting the following error:

```js
Failed to resolve import "../.routify/routes" from "src/App.svelte". Does the file exist?
```

Did you include your routing config?

**Comment by raymondboswel** [comment]
Hmm. I just cloned the repo in a fresh directory on my side, and it works. I *think* you might be running into this issue: https://github.com/vitejs/vite/issues/2585 || https://github.com/vitejs/vite/issues/2647 ("issue was because of a space in parent folder name.").

**Comment by liamdebeasi** [comment]
I don't seem to have the `.routify` directory at the root. Do I need to do anything special to get this? I also do not see the `.routify` directory in the repo: https://github.com/raymondboswel/ionic-modal-reproduction

**Comment by raymondboswel** [comment]
The .routify directory is in the .gitignore of the starter project I used. But if I delete it locally and run `npm run dev:start` it gets recreated. You can also try npm run build:app, or npm run build:routify to create it. In the mean time I'll push the directory then we can see if that works.

**Comment by liamdebeasi** [comment]
`npm run dev:start` did the trick! Not sure why it did not work the first time. Thanks!

**Comment by raymondboswel** [comment]
Excellent! I'm glad it's working. Let me know if you need anything else.

**Comment by liamdebeasi** [comment]
One more question -- what is the error you are getting? The screenshot you attached is not showing up:

![image](https://user-images.githubusercontent.com/2721089/146038820-47b8be77-59a0-4536-a033-e19cccdd9bec.png)

**Comment by raymondboswel** [comment]
![image](https://user-images.githubusercontent.com/4745321/146039122-11eb4a8b-b63d-42b6-9272-e6fd24d0426f.png)

**Comment by liamdebeasi** [comment]
If you import `actionSheetController` from `@ionic/core/components` instead of `@ionic/core`, does that fix the issue?

`@ionic/core` uses lazy loading while `@ionic/core/components` does not. It seems that mixing the two is causing some unexpected behaviors.

**Comment by raymondboswel** [comment]
That took care of the exception, but there's an issue with the backdrop in 6.0.0. I've attached video of the behaviour (You can't see me clicking, but clicking on the background does not dismiss the AS)
 
file:///home/raymond/Videos/action-sheet-6.0.0.mp4

**Comment by raymondboswel** [comment]
For reference 6.0.0-rc.3:

![action-sheet-6 0 0-rc3](https://user-images.githubusercontent.com/4745321/146221261-a76ea47b-c879-444b-9699-a0658428cfec.GIF)

**Comment by liamdebeasi** [comment]
Ah looks like the backdrop is not getting defined. We should fix that internally.

As a workaround, importing and defining `IonBackdrop` should fix the issue until we can get a patch in.

**Comment by liamdebeasi** [comment]
This looks to be a continuation of https://github.com/ionic-team/ionic-framework/pull/24372.

**Comment by raymondboswel** [comment]
Ok great. I'll be happy to try a fix out when it's released :+1:

**Comment by sean-perkins** [comment]
@raymondboswel can you try this dev build of v6 with the additional custom elements defined for overlays and let me know if that resolves the issues you've reported?

```bash
npm install @ionic/core@6.0.0-dev.1639604950.5995f29
```

**Comment by raymondboswel** [comment]
Yes, that looks great @sean-perkins :+1: . The only remaining issue I can see at this stage, is that a modal created with
```<ion-modal bind:this={modal} is-open={showModal}>
  <CreateProject />
</ion-modal>
```
doesn't seem to quite get the screen dimensions right, but I've already reported that in https://github.com/ionic-team/ionic-framework/issues/24379.

![image](https://user-images.githubusercontent.com/4745321/146310528-72a35d64-18f8-4c3b-b20c-093b492851f8.png)

Created with modalController:
![image](https://user-images.githubusercontent.com/4745321/146310602-64382c79-d018-40aa-b221-f17365c438b5.png)

Thank you very much guys! I think we can close this one out :+1:
