### ISSUE TITLE
bug: angular, routerLink prevents opening link in new tab

### ISSUE THREAD

**Issue by Juarrow** [ionic-team/ionic-framework#24413]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [x] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

When importing the IonicModule and using ``[routerLink]``,
the following line prevents Ctrl+Click behavior on Desktop browsers.

https://github.com/ionic-team/ionic-framework/blob/732f8e10ce604f1a3e98518ae9c3a4afd7803e9a/angular/src/directives/navigation/router-link-delegate.ts#L56

### Expected Behavior

Ctrl+Click should trigger the default browser behavior (e.g. open the link in a new tab/page/etc).

### Steps to Reproduce

1. Create an anchor element with a ``[routerLink]="[<your link>]"``
2. Ctrl+Click on it

### Code Reproduction URL

[Link to repository](https://github.com/Juarrow/ionic-angular-ctr-click-bug)

On the home page CTRL+Click the link

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\Julian\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.1
   @angular-devkit/schematics    : 13.0.3
   @angular/cli                  : 13.0.3
   @ionic/angular-toolkit        : 5.0.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 10
```

### Additional Information

I'm currently monkey-patching it 🙈 .

Maybe this can be fixed by something like (pseudo-code)
````
if(platform is desktop && (key == CTRL || key == Meta) && button == 0)) {
 return true;
}
````

**Comment by Juarrow** [comment]
@liamdebeasi added the [reproduction repo link](https://github.com/Juarrow/ionic-angular-ctr-click-bug) to the issue.

**Comment by liamdebeasi** [comment]
Thanks! I can reproduce this behavior.

For additional context, this Ctrl+Click behavior works with the standard routerLink in an Angular app without Ionic, so I think we should support this.

**Comment by Juarrow** [comment]
If you like, i can create a PR with a fix.

**Comment by liamdebeasi** [comment]
Yes, that would be great! Just as a heads up, much of the team is taking time off for the upcoming holidays in the United States, so we may not get to your PR right away.

**Comment by maelp** [comment]
I have the same issue with Ionic and VueJS, cmd+click on a link does not allow opening in a new tab

**Comment by sean-perkins** [comment]
@maelp can you share more information about the problem you are facing in Vue? This issue is tracking router links not working as expected with native HTML elements (`a` tag, etc.). 

Quickly checking with Vue, CMD/CTRL + click works under these conditions:
```vue
<router-link to="/routing/child">
  <button>button</button>
</router-link>
<router-link to="/routing/child" custom v-slot="{ navigate, href }">
  <a :href="href" @click="navigate">link text</a>
</router-link>
```

**Comment by maelp** [comment]
Well for me, when I add a regular `<ion-button>` (without any `router-link` around) and do a cmd+click, it just does the same as a click (opens in the same tab)

**Comment by sean-perkins** [comment]
Correct, that is currently the expected/default behavior. If you wouldn't mind opening a new issue to track that request change, that would be appreciated. I don't have a strong stance at the moment if `ion-button` should operate differently, but that should be evaluated by the team & community to make sure it doesn't negatively impact existing applications. 

The scope of this issue is around fixing the behavior of an `a` tag not working with CMD/CTRL + click with Ionic, when it works as expected without Ionic in the framework itself (Angular).
