### ISSUE TITLE
bug: ion-datetime not changing class 'calendar-day-active' when clicking a date

### ISSUE THREAD

**Issue by DominikRoth** [ionic-team/ionic-framework#24414]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior
It happens when I use the ion-datetime in a modal and when showDefaultButtons=true.

#### In browser and on android phone: 

When I select a date, the class 'calendar-day-active' doesn't change to the selected date.
The only thing that happens when I select a date is that the :focus styling applies. (I selected 17. in this example)
<img width="317" alt="Bildschirmfoto 2021-12-15 um 15 22 03" src="https://user-images.githubusercontent.com/86354362/146203666-793f28e0-bcae-44bf-b0cc-287fbe63511e.png">
**EDIT: The behavior for browser and android seems to be normal, it just feels odd to me. Because when I click a date, I expect it to change the active styling and when i press 'Done' i want the value to be written to my variable.**

#### On iOS:
The selected date doesn't change styling at all. Not even the focused styling gets applied.
After i clicked 15. the value is set to my variable, but it is not visible.
<img width="273" alt="Bildschirmfoto 2021-12-15 um 15 20 38" src="https://user-images.githubusercontent.com/86354362/146203584-52d91619-8add-4710-bd66-3f097aca7f10.png">

### Expected Behavior

When I click on a date, I expect it to have the active styling.

### Steps to Reproduce
1. Put the code snippet into an Ionic v6 app and build for iOS
2. Run the app on simulator or on physical iOS device
3. Open ion-datetime in modal-mode
4. click on another date than the currently selected one
5. Check if active styling is applied to the selected date

### Code Snippet

```
<ion-button id="open-modal">Open Datetime Modal</ion-button>
<ion-modal trigger="open-modal">
  <ng-template>
    <ion-content>
      <ion-datetime showDefaultButtons="true"></ion-datetime>
    </ion-content>
  </ng-template>
</ion-modal>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.2
   @capacitor/android : 3.2.4
   @capacitor/core    : 3.2.4
   @capacitor/ios     : 3.2.4

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.5.0) : 1.4.0

System:

   NodeJS : v14.15.3 (/usr/local/bin/node)
   npm    : 6.14.9
   OS     : macOS Catalina

**Comment by wangzhengjiang** [comment]
I am facing same problem on iphone, ios version 15.2

**Comment by brinehart** [comment]
I can reproduce this issue as well on Edge and Chrome on an intel 2020 Macbook.

It only happens for me when `[showDefaultButtons]="true"` is displayed

**Comment by DominikRoth** [comment]
@Ionitron I added a code snippet for reproduction

**Comment by jongbonga** [comment]
experienced the same thing with other weird behaviors, reported #24451

**Comment by sean-perkins** [comment]
Hello everyone! Thanks for reporting this issue, adding additional details and helping isolate the driving factors contributing to the bug. 

I have an open PR to address this issue (and other mentioned issue): #24454

Unfortunately I am the one that introduced this bug when fixing another issue (programmatically setting the value wasn't updating the date picker display) 🪦. 

I want to write a few more tests later today to validate the previous (expected) behaviors as well as the patched fixes. If all that goes well, I'll post a dev build for everyone to test with. With the holiday cycle, we won't be publishing `6.0.2`/`6.1.0` until after the New Year.

**Comment by sean-perkins** [comment]
If anyone that is available would like to also additionally confirm this resolution, I'd appreciate it 👍 

```bash
npm install @ionic/core@6.0.1-dev.1640104484.e62df80
```

**Comment by brinehart** [comment]
@sean-perkins I have tested this locally with `ion-datetime` inside of an `ion-modal` and it does not appear to have been fixed. I am still seeing the behavior described above in the bug.

**Comment by sean-perkins** [comment]
> @sean-perkins I have tested this locally with `ion-datetime` inside of an `ion-modal` and it does not appear to have been fixed. I am still seeing the behavior described above in the bug.

@brinehart  thanks for testing this! Did you happen to install the dependency for both `@ionic/core` and `@ionic/angular` (if your project is using Angular)? With dev builds, the framework targets will often just install the latest published release of `@ionic/core`, which would be `6.0.1` and not the fixes I've included. 

Here's a test repository to confirm:
- https://github.com/sean-perkins/gh-24414-datetime-active-day/tree/main (issue is present)
- https://github.com/sean-perkins/gh-24414-datetime-active-day/tree/fix (issue is resolved)

|Before|After|
|---|---|
|<video src="https://user-images.githubusercontent.com/13732623/147128163-7aa0edb7-1b03-436b-a8de-e4fa7a5cea34.mp4"></video>| <video src="https://user-images.githubusercontent.com/13732623/147127978-7bc0bff6-c74f-4e4e-b151-0c2b3255d2a0.mp4"></video>|

**Comment by ectan** [comment]
FYI. I have tested OK (both android and ios) using:
"@ionic/core": "^6.0.1-dev.1640104484.e62df80",
"@ionic/vue": "^6.0.1-dev.1640104484.e62df80",
"@ionic/vue-router": "^6.0.1-dev.1640104484.e62df80",

**Comment by Paul-1986** [comment]
@sean-perkins Tried it, but didn't work. npm list:
├── @ionic/angular@6.0.1-dev.1640104484.e62df80
├── @ionic/core@6.0.1-dev.1640104484.e62df80
