### ISSUE TITLE
bug:  network error after build (ionic 6 using vue 3) ANDROID

### ISSUE THREAD

**Issue by ryansyrl** [ionic-team/ionic-framework#24428]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

hello,

is there anyone have the same problem with ionic 6 that using vue 3 (composition API), that the axios seems could not make a request to the server? the error message is "NETWORK ERROR"  i try to googled it, but i dont find any solution for this or any explanation

![image](https://user-images.githubusercontent.com/67872022/146434068-03476b14-10de-4e6c-8140-f7edd45eede8.png)

### Expected Behavior

i did try with and no live reload (the api request i made to my own computer) the axios request doing just fine, no problem at all.

### Steps to Reproduce

things i've tried for this issue are, i build the project to APK version.

### Ionic Info

vue: 3.2.1,
ionic: 6.18.1
capacitor/android: 3.3.2
ionic/vue: 5.4.0
axios: 0.24.0

**Comment by liamdebeasi** [comment]
Hey there! The error seems to coming from a native layer in your app which is not something that Ionic Framework manages. As mention in https://github.com/ionic-team/ionic-framework/issues/24428#issuecomment-996158823, I recommend posting your question on the [Ionic Forums](https://forum.ionicframework.com/). Thanks!
