### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by FranciskoNeves** [ionic-team/ionic-framework#24437]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The event `RangeCustomEvent` returned by `ionChange` in `ion-range` returns a RangeValue with lower and upper properties correctly, but I can't access the values directly as shown below:

<img width="390" alt="Screenshot_1" src="https://user-images.githubusercontent.com/22598113/146547727-07c2891a-33be-40b0-b56b-b594019636df.png">

### Expected Behavior

Access `RangeValue` object properties lower and upper directly, like for example event.detail.value.lower

### Steps to Reproduce

Set an ion-range component, set an ionChange callback function, and try to access lower and upper properties directly( For example: event.detail.value.lower or event.detail.value.upper)

### Ionic Info

**Ionic:**

   Ionic CLI                     : 6.18.1 (C:\Users\Francisco.neves\AppData\Roaming\nvm\v16.13.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.0
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.12
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

**Cordova:**

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

**Utility:**

   cordova-res : 0.15.4
   native-run  : 1.5.0

**System:**

   Android SDK Tools : 26.1.1 (C:\Users\Francisco.neves\AppData\Local\Android\Sdk)
   NodeJS            : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 8.1.0
   OS                : Windows 10

**Comment by sean-perkins** [comment]
@FranciskoNeves it looks this is the result of having two different return type values for `RangeValue`.

You can narrow the type to allow TypeScript to detect the correct type for autocompletion. 
```ts
if (typeof time !== 'number') {
  const { lower, upper } = time;
}
```

I don't believe in TypeScript you can have property detection when using a compound type that includes a primitive. Can you let me know if the above would suffice for you needs? 

Also if you have additional context of an example where there is a custom type with a primitive type, I'd appreciate that too!
