### ISSUE TITLE
bug: popover with datetime is too narrow in ios mode and goes off bottom of screen

### ISSUE THREAD

**Issue by Daniel-Aragao** [ionic-team/ionic-framework#24430]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When opening the datepicker in a popover as [exemplified](https://ionicframework.com/docs/api/datetime#usage) its width is not containing all of its contents when looking at an IOS device.

Also, the height is causing it to pass the page limit when also disabling the scroll.

![image](https://user-images.githubusercontent.com/12102965/146451434-feba29d0-8923-4f37-a891-b24d9bbee58b.png)

### Expected Behavior

The expected here is that the calendar would move up enough to fit the page and left to fit its own content

my personal workaround was:
`ion-popover {
  --width: 288px;
  --offset-y: -42px
}`

![image](https://user-images.githubusercontent.com/12102965/146451889-21322082-f522-4093-8021-c521976c4521.png)

### Steps to Reproduce

1. Download and install the project
2. Open the app 
2. Right-click on the page and open the browser inspection
3. Select Device mode
4. Select any IOS device
5. Refresh the page 
6. Open the calendar and see it broken

### Code Reproduction URL

https://github.com/Daniel-Aragao/datepicker-size-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\**{my-user}**\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI   : 3.3.3
   @capacitor/core : 3.3.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 10

**Comment by wallstudios** [comment]
Any update on this? I have the same issue. Width and position on iOS

**Comment by josef-kriz** [comment]
This is preventing us from migrating to Ionic 6 in our company.

Unfortunately we haven't found an easy and general workaround for it.

**Comment by adinaamza** [comment]
Hello! Any update on this yet? We'd love to be able to use the new calendar and finally upgrade to Ionic 6.

**Comment by anura-apps** [comment]
Hello,

You can force the popover width :

`<ion-popover trigger="date" show-backdrop="true" class="popover-datetime">
<ng-template>
	<ion-datetime [(ngModel)]="date"></ion-datetime>
</ng-template>
</ion-popover>`

`.popover-datetime::part(content) {
		width: 80vw !important;
}`

**Comment by cwetyyy** [comment]
Hi, Is there any update on this? Do you plan on resolving this any time soon?

**Comment by liamdebeasi** [comment]
Hi everyone,

With Ionic 6.2 we released `ion-datetime-button` which makes it easy to present a datetime in a modal or popover that is correctly sized. As a result, I am going to close this as the requested behavior is now available.

Ionic 6.2 announcement blog: https://ionicframework.com/blog/announcing-ionic-v6-2/
Datetime Button docs: https://ionicframework.com/docs/api/datetime-button

For any other requests, please open a new issue. Thanks!
