### ISSUE TITLE
bug: Cordova Live reload not working after updating to ionic 6

### ISSUE THREAD

**Issue by sufian1985** [ionic-team/ionic-framework#24438]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

> ng run app:ionic-cordova-serve --host=localhost --port=8100 --platform=ios --consolelogs --consolelogs-port=53703
[ng] An unhandled exception occurred: Must use import to load ES Module: /Users/muhammadsufian/Desktop/FSM/node_modules/@angular/compiler-cli/bundles/index.js
[ng] require() of ES modules is not supported.
[ng] require() of /Users/muhammadsufian/Desktop/FSM/node_modules/@angular/compiler-cli/bundles/index.js from /Users/muhammadsufian/Desktop/FSM/node_modules/@ionic/angular-toolkit/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
[ng] Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/muhammadsufian/Desktop/FSM/node_modules/@angular/compiler-cli/package.json.
[ng] 
[ng] See "/private/var/folders/1s/ff3gfb1x57q2xg5k023ft9yh0000gn/T/ng-FgiRHs/angular-errors.log" for further details.

[ERROR] ng has unexpectedly closed (exit code 127).
        
        The Ionic CLI will exit. Please check any output above for error
        details.

### Expected Behavior

It should open the target emulator and we should be able to test properly

### Steps to Reproduce

ionic cordova run ios -l --consolelogs --emulator

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 21 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v14.18.1 (/usr/local/bin/node)
   npm        : 6.14.15
   OS         : macOS Monterey
   Xcode      : Xcode 13.2 Build version 13C90

**Comment by sean-perkins** [comment]
Hello @sufian1985 thanks for reporting this issue. 

We are currently tracking this bug here: https://github.com/ionic-team/ionic-cli/issues/4795

Please upvote that issue to follow its resolution. Thanks!
