### ISSUE TITLE
bug: vue, scroll position resets with swipe down

### ISSUE THREAD

**Issue by franzwilding** [ionic-team/ionic-framework#24435]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When starting a new ionc vue list app, there is a problem with collapsed ios titles on first scroll. After the first scroll everything is working as expected. Without the collapsed ion-header, everything works fine. Also wenn navigating to a child page and come back, scrolling works fine, the bug only occurs after app start (or after navigating via tabs)

https://user-images.githubusercontent.com/309309/146513535-24c8885c-2e80-4126-9eb4-cf940b2069b6.mp4

### Expected Behavior

The app should be scrollable also on the first scroll event. 

### Steps to Reproduce

- Start a new ionc app with cli
- Add ios platform
- Run in simulator

**Comment by franzwilding** [comment]
The bug also occurs in the official starter app template (https://github.com/ionic-team/starters/tree/main/vue/official/list) so a step-by-step reproduction would be: 

```bash
ionic start myApp list --type=vue
cd myApp
ionic cap add ios
ionic cap run ios
```

**Comment by liamdebeasi** [comment]
I can reproduce this behavior. It looks to be unique to Vue as I can only reproduce it in an Ionic Vue starter app. Also, I can only reproduce this in Ionic 6.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@6.0.8-dev.1644947788.52fe65d @ionic/vue-router@6.0.8-dev.1644947788.52fe65d
```

**Comment by franzwilding** [comment]
Yes this looks good! Thank you.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24791, and a fix will be available in an upcoming release of Ionic Framework.
