### ISSUE TITLE
bug: ```ion-datetime``` cannot select date after open month/year dropdown (desktop browser ios mode)

### ISSUE THREAD

**Issue by Wasenshi123** [ionic-team/ionic-framework#24444]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When I play demo on the document page on my PC (I use Edge browser), I cannot select date after I open month/year dropdown.
Note: It only happens on ios demo, not on android one. (and after you use arrow to change month, then it can be selected again)

### Expected Behavior

I should be able to select date after I open month/year dropdown.

### Steps to Reproduce

1. go to ion-datetime document page using desktop browser [Edge] https://ionicframework.com/docs/api/datetime
2. Play the demo on the right by clicking to open month/year dropdown button
3. with or without changing the value, close and back to the calendar
4. you cannot select date anymore (until you use arrow to change month, then it can be selected again)

### Code Reproduction URL

https://github.com/ionic-team/ionic-docs/blob/main/static/demos/api/datetime/index.html

### Additional Information

Though I haven't tried v6 myself, but I found this bug just by playing demo on the document page, so I assume that it should be noted and reported here.

Platform: Desktop / Edge browser Version 96.0.1054.62 (Official build) (64-bit)
Component Mode: ios

**Comment by liamdebeasi** [comment]
Thanks for the issue. The team is unable to reproduce this behavior anymore, so we believe this issue has been resolved.

If you are still running into the issue, please follow up on this thread. Thanks!
