### ISSUE TITLE
bug: ion-select cannot access "action-sheet" before initialization

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/ionic-framework#24448]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Breaks when upgrading to 6.0.1
![image](https://user-images.githubusercontent.com/4184680/146735054-cf01d055-3bdc-4b8a-827e-24d5b5a9948f.png)

### Expected Behavior

Should work as it did in v5.9.1

### Steps to Reproduce

Upgrade to v6.0.1

### Code Reproduction URL

https://github.com/FireEnjin/Components/tree/ionic-v6.0.1

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.13.1
   npm    : 8.1.2
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Hello @popcorn245 can you isolate the issue with a new Stencil app/library and Ionic v6?

I created a new project with Stencil v2.12.0 & Ionic v6, but was unable to replicate the issue present in your project. The only side-effect that I can see from your project, is that the custom elements are not being defined; but that is likely a result of the exception preventing future execution.

**Comment by popcorn245** [comment]
> Hello @popcorn245 can you isolate the issue with a new Stencil app/library and Ionic v6?
> 
> I created a new project with Stencil v2.12.0 & Ionic v6, but was unable to replicate the issue present in your project. The only side-effect that I can see from your project, is that the custom elements are not being defined; but that is likely a result of the exception preventing future execution.

Okay, I will see if I can debug further and follow up, thanks.

**Comment by OPerel** [comment]
Hello,
I'm having the same issue.
Just updated ionic from `5.5.2` to `6.0.1` and stencil from `2.3.0` to `2.12.0`.
This is what I'm seeing in my console:
![image](https://user-images.githubusercontent.com/42510547/146907615-f1be7484-2fc1-43c3-bc78-15670c5ff805.png)

Unable to find the reason so far...
Thanks

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
