### ISSUE TITLE
bug: property style doesn't work on root IonPage

### ISSUE THREAD

**Issue by natqe** [ionic-team/ionic-framework#24442]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Property `style` doesn't passing through an `IonPage` component

### Expected Behavior

Property `style` should be passing to the actual `IonPage` element get rendered on the DOM

### Steps to Reproduce

minimal ionic-react code
```jsx
import { IonApp, IonContent, IonHeader, IonPage, IonTitle, IonToolbar, setupIonicReact } from '@ionic/react'
import '@ionic/react/css/core.css'
import { createRoot } from 'react-dom'

setupIonicReact()

createRoot(document.getElementById('root')).render(<IonApp>
  <IonPage style={{ backgroundColor: 'black !important' }}>
    <IonHeader>
      <IonToolbar>
        <IonTitle>My Title</IonTitle>
      </IonToolbar>
    </IonHeader>
    <IonContent>
      Hello World
    </IonContent>
  </IonPage>
</IonApp>)
```

### Code Reproduction URL

https://github.com/natqe/ionic-page-style-not-working/

**Comment by sean-perkins** [comment]
@natqe from a fresh starter app, I can see the style is being passed to the generated `.ion-page` element:

![Screen Shot 2021-12-18 at 9 40 13 PM](https://user-images.githubusercontent.com/13732623/146661682-344fff9e-bc12-4e91-87f8-3a1f0b224ec5.png)

With the following code:
```ts
<IonPage style={{
  backgroundColor: 'black'
}}>
```

Are you actually trying to change the background color of the page or was that an example of a style?

If you are needing to modify the background color, you should use the respective CSS variables for `ion-header` and `ion-content`.

**Comment by natqe** [comment]
@sean-perkins idk what Versions r u run but i created a repo for showing that.
https://github.com/natqe/ionic-page-style-not-working/

Steps to run:
- clone the repo.
- install via `npm i -f`
- run `npm start`

**Comment by sean-perkins** [comment]
@natqe thanks for the reproduction!

This appears to be an issue with the root `IonPage` instance. If you have a nested `IonPage`, the inner instance appropriately applies inline styles.  

This looks to be a flaw with the `IonPage` react implementation. 

To work around this issue, you can specify `className` and it will apply correctly:

```html
<IonApp>
  <IonPage className="my-custom-class">
    ..
  </IonPage>
</IonApp>
```

```css
.my-custom-class {
  background-color: black;
}
```

I'll track this issue as a bug with react & we will prioritize in upcoming sprints or downtime. Thanks!

**Comment by sean-perkins** [comment]
Hello @natqe,

After revisiting this issue, I believe the root problem is the use of `!important`. If you remove that portion, the inline styles are applied correctly to the React component.

To change the background color of the page however, it would be better to use the following approach:
```tsx
<IonPage style={{
 '--ion-background-color': 'black'
}}>
 {/* Existing content */}
</IonPage>
```

I am going to close this issue. Please let me know if you have questions or run into any issues with my recommended approach.
