### ISSUE TITLE
bug: Ionic 6 - Ion-Datetime UI should not be solid blue for todays date when no value set

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic-framework#24456]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

On Ionic 6 and to be honest its a bit harsh to call it a bug. But in short when in popover mode when the user clicks on the text or input date field to open up the new ion-datetime UI. If no value is selected, the date defaults to today's date. This is fine however the circle is blue solid which visually means the user has selected the date already which is incorrect. This could cause confusion. 

<img width="241" alt="Screen Shot 2021-12-21 at 5 33 13 pm" src="https://user-images.githubusercontent.com/10624315/146883652-d032716d-9fd3-4a43-baee-f940ab16c055.png">

### Expected Behavior

If no value set, the default today's date should be a blue outline circle not a solid circle.  See below correct expected behaviour.

<img width="193" alt="Screen Shot 2021-12-21 at 5 33 00 pm" src="https://user-images.githubusercontent.com/10624315/146883334-12f96494-dc4f-4df0-9191-ac93e1f7948f.png">

### Steps to Reproduce

Test new ionic datetime using a ngModel value set to "" or null. I tested in popover mode in Angular 13:

```
<ion-item class="ion-text-wrap" button="true" id="ionic-date-start">
                        <ion-icon name="calendar" slot="start"></ion-icon>
                         <ion-label style="color:#424242">Start Date</ion-label>
                         <ion-text>{{record.start_date|date:'mediumDate'}}</ion-text>

                        <ion-popover trigger="ionic-date-start" show-backdrop="false">
                          <ng-template>
                            <ion-datetime
                              #popoverDatetime
                              presentation="date"
                              [showClearButton]="true"
                             [(ngModel)]="record.start_date"
                            ></ion-datetime>
                          </ng-template>
                        </ion-popover>
                      </ion-item>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.15.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.2
   @angular-devkit/schematics    : 13.0.2
   @angular/cli                  : 13.0.2
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.1.1
   OS     : macOS Big Sur
   Xcode  : Xcode 13.2.1 Build version 13C100

  ─────────────────────────────────────────────────

**Comment by sean-perkins** [comment]
Hello @bkarv thank for reporting this issue.

Currently the datetime component will set the default value to today's date, which acts similar to the browser's implementation of [`datetime-locale`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local).

I don't currently believe this is a bug. I believe this could be better classified as a feature to prevent setting the default date value to today. This would achieve the visual display you are expecting.

Does that feel fair?

**Comment by bkarv** [comment]
thanks for replying as mentioned previously bit harsh to call this a bug. I happy if this can be classified as a feature request cheers.

**Comment by amandaesmith3** [comment]
I took another look at this, and confirmed that if no value is specified on the `ion-datetime`, it defaults to `undefined`, but the visual display still shows a blue circle on today's date. Also, manually setting the `value` to something falsy after the fact doesn't update the display -- for example, you could set it to tomorrow, and then `null`, and the display still highlights tomorrow with the solid blue circle.

I agree that this feels odd 🤔 There are a couple ways we could go about fixing this...

If no initial value is set, the datetime should either automatically initialize with a value of today, or not highlight any day and just show the outline around today.

And then if the value is manually set to something falsy, either there should be an error with no further action, the solid blue circle should go away (leaving just the outline), or the value should automatically switch to today. How we handle this will likely depend on how the first problem is handled.

Either way, I agree that the implementation should be improved here. I'll go ahead and file it as a bug so we can take a deeper look.

**Comment by bkarv** [comment]
@amandasmith3 thanks for the comments and detailed response. What you have propose make sense, I look forward to the investigation and final solution.

**Comment by tetsuwanadam** [comment]
Agreed that the current UI of highlighting the current day with a solid blue circle even when there's no value is confusing. On init if there's no value the current day should have an outline around it, as @amandaesmith3 suggests.

**Comment by amandaesmith3** [comment]
Hi all, could you try the below dev build and let me know if it resolves things on your end?
```
6.1.2-dev.11650392645.12c652f6
```
Example:
```
npm install @ionic/angular@6.1.2-dev.11650392645.12c652f6
```

**Comment by amandaejohnston** [comment]
This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25151, and the fix will be available in a future release of Ionic 👍
