### ISSUE TITLE
bug: Glitching when the Searchbar inside Sheet Modal 

### ISSUE THREAD

**Issue by chrisk8er** [ionic-team/ionic-framework#24457]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Glitch and lose autofocus in the search bar when opening the sheet modal.

### Expected Behavior

smooth opening the modal and then the search bar will autofocus.

### Steps to Reproduce

- Create a Simple Page with an open sheet modal button
- Create Sheet Modal on that page
- Put Searchbar inside Sheet modal
- Click the button to open the Sheet modal
- Watch the glitch when ionic is trying to autofocus the search bar
- Search bar then losing the autofocus

### Ionic Info

Ionic React 6

**Comment by liamdebeasi** [comment]
In addition to the reproduction, also try setting `keyboardClose` to `false` on the sheet modal. By default, the keyboard is automatically dismissed when the overlay is presented. See https://ionicframework.com/docs/api/modal#keyboardclose for more information.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
