### ISSUE TITLE
bug: Using Ionicons with Vite

### ISSUE THREAD

**Issue by raymondboswel** [ionic-team/ionic-framework#24455]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I'm trying to use Ionicons with Vite. When using an an ion-icon element by passing in the name attribute, the following error is returned:

![image](https://user-images.githubusercontent.com/4745321/146876176-d315a875-c744-4be0-b998-8c9da0787048.png)

The icons can be downloaded and referenced using the src attribute, but this doesn't work in all cases, for example when using an action sheet, the icon has to be referenced by name. I found a workaround that works in dev mode, but unfortunately doesn't work when building the app, as referenced here: https://github.com/ionic-team/ionic-docs/issues/2130

### Expected Behavior

Ionicons should work as expected.

### Steps to Reproduce

Clone the reproduction repo.
Click on the FAB in the bottom right corner to open the action sheet. 
Note tha missing icons and error in console.

### Code Reproduction URL

https://github.com/raymondboswel/ionic-modal-reproduction

**Comment by raymondboswel** [comment]
Thank you for the suggestion @liamdebeasi, I'll give it a shot. This covers the ion-icon case, but how should the icon for an action sheet button be specified?

**Comment by liamdebeasi** [comment]
The `icon` property in the action sheet is passed into the `icon` property in `ion-icon`, so you should be able to pass it in the same way.

**Comment by raymondboswel** [comment]
Thank you very much @liamdebeasi, I very much appreciate all the help!
