### ISSUE TITLE
bug: datetime has inconsistent behaviour when using custom buttons

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/ionic-framework#24451]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using custom buttons in the `slot="buttons"`, selecting a date leaves an active class on the current/today's date, and the time display doesn't update when selecting/scrolling new time

### Expected Behavior

The behavior should stay consistent all around

### Steps to Reproduce

https://user-images.githubusercontent.com/12111716/146771161-9d43b4cc-b9ef-45af-a8b4-689ee373b3d2.mov

Custom Buttons section on https://github.com/ionic-team/ionic-docs/blob/main/static/demos/api/datetime/index.html

### Code Reproduction URL

https://github.com/ionic-team/ionic-docs/blob/main/static/demos/api/datetime/index.html

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/jonathan/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3
```

**Comment by jongbonga** [comment]
**UPDATE**
The same behavior happens when using `showDefaultButtons`

**Comment by sean-perkins** [comment]
This issue has been resolved and is available in the latest patch release.
