### ISSUE TITLE
bug: datetime component design issue under android (md)

### ISSUE THREAD

**Issue by amiraiouaz** [ionic-team/ionic-framework#24464]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Under android (md), there is a little design issue for the datetime component in the first line:

![image](https://user-images.githubusercontent.com/22788646/146999865-268bd80d-9fb0-4158-a4c5-b0430510c825.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/22788646/146999940-cec6760b-4180-4a12-b201-d4544777709c.png)

### Steps to Reproduce

- Open the datepicker in android mode (md)
- Select a day in the first line

**Comment by indraraj26** [comment]
duplicate https://github.com/ionic-team/ionic-framework/issues/24408

**Comment by sean-perkins** [comment]
Hello & thanks for reporting this issue!

Since there is another issue already tracking this, I will close this issue out.
