### ISSUE TITLE
Modal controller does not trigger ngOnDestroy when dismissing

### ISSUE THREAD

**Issue by agencia-estado** [ionic-team/ionic-framework#24460]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Modal controller does not trigger ngOnDestroy when dismissing

### Expected Behavior

Trigger ngOnDestroy when dismissing

### Steps to Reproduce

Present a modal component with modalController.
In the component, implement the OnDestroy interface and write to the console to see the bug
In the component, call this.modalController.dismiss()

Nothing is written to the console

### Code Reproduction URL

- https://github.com/sean-perkins/gh-24460-modal-ngondestroy

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\leandro\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.4.1

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.4
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Thanks for reporting this issue! This is going to require a little extra discovery on our end, but I have been able to replicate that in v5, `ngOnDestroy` fires when the modal is dismissed; whereas in v6, `ngOnDestroy` is not firing.

**Comment by akram-pi** [comment]
I am also facing the same issue in V6!
It is causing a memory leak in the app ⛔️
I was able to fix the issue with `ionViewDidLeave`.
But keep in mind that `ionViewDidLeave` should only be used in a `modal` to unsubscribe .
For `components`, it will be called when navigating between pages!

**Comment by HyperLife1119** [comment]
I think this is a serious problem.

**Comment by AVatch** [comment]
+1 on this.

**Comment by sean-perkins** [comment]
Please use the 👍  on the original post to upvote an issue instead of commenting +1. We appreciate keeping comments focused around the reproduction or the resolution to reported issues.

I've created a reproduction app to help isolate this issue: https://github.com/sean-perkins/gh-24460-modal-ngondestroy and attached it to the original issue.

Will share more as we discover the cause.

**Comment by sean-perkins** [comment]
Following up, I have narrowed that the behavior regressed in this PR #24380.

I'll need to discover more into the original bug that PR aimed to achieve while still unmounting overlay components.

**Comment by KirstenStake** [comment]
@sean-perkins can you please provide an update on this issue? Can see a fix has been merged. when will this be released as a new version to update to with the fix?

**Comment by JesperBalslev** [comment]
I just stumpled upon this today - to my big surprise - and are also looking forward to an update with the merged fix. 
Only reason i noticed this error, was because i was checking out the new sheet modals (cool feature).

**Comment by sean-perkins** [comment]
Hello @KirstenStake , @JesperBalslev & everyone!

This change will be officially available in 6.0.3 and will be released tentatively Wednesday (01/19/2022). We are internally aiming for weekly official releases and eventually nightly builds of the latest fixes on the `main` branch.

Due to the sensitivity and high impact of this bug on Angular projects, I've created a dev build for those that would like to use it in the interim.

```bash
npm install @ionic/angular@6.0.3-dev.1642089307.c8a392a
```

**Comment by JesperBalslev** [comment]
Thanks alot @sean-perkins - good work with the quick fix.

**Comment by andreas-aeschlimann** [comment]
I discovered huge memory leaks in my app because I subscribe to observables in modal components. I noticed now that the subscriptions never get destroyed because the component stays alive even after calling `modalController.dismiss()`.

I am on Ionic 6.0.1. Has this already been fixed in a release?

**Comment by sean-perkins** [comment]
@andreas-aeschlimann yes, this has been resolved in v6.0.3.

https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#603-2022-01-19

Upgrading should resolve the issue on your end.
