### ISSUE TITLE
bug: @ionic/vue-router 6.0.1 hardcodes @ionic/vue 6.0.0 as dependency

### ISSUE THREAD

**Issue by boboldehampsink** [ionic-team/ionic-framework#24467]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

https://github.com/ionic-team/ionic-framework/blob/main/packages/vue-router/package.json#L47

### Expected Behavior

^6.0.0

### Steps to Reproduce

See https://github.com/ionic-team/ionic-framework/blob/main/packages/vue-router/package.json#L47

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework/blob/main/packages/vue-router/package.json#L47

**Comment by sean-perkins** [comment]
Thanks for reporting this issue! It will be resolved in 6.0.2 after the New Year 🙂
