### ISSUE TITLE
bug: Class "ion-page-hidden" is not updated

### ISSUE THREAD

**Issue by juanjcardona13** [ionic-team/ionic-framework#24469]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When I create nested routes it does not show the correct page according to the url

### Expected Behavior

When navigating the routes, show the vue component in an appropriate way according to the url that corresponds to it specified in the index.js of the vue-router configuration

### Steps to Reproduce

Download the project

At the root of the project run "npm install"

Run the project with "ionic serve"

Option 1

4.1 From the initial page "/ tabs / tab1", press the button "Go page view"
4.2. In the header press back arrow
4.3 Go to "Tab 3"
4.4 Press the tab where it says "Go page create" (Error: It shows the two pages "View" and "Create" at the same time)

Option 2
5.1 From the initial page "/ tabs / tab1", press the button "Go page view"
5.2. In the header press back arrow
5.3 Press the tab where it says "Go page create"
5.4. In the header press back arrow
5.3 Go to "Tab 3"
5.1 Press the "Go page view" button (Error: It shows the "Create" page instead of the "View")

### Code Reproduction URL

https://github.com/juanjcardona13/NestedRoutesIonicVue

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/Users/jose.guzman/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.6 (/Users/jose.guzman/.nvm/versions/node/v14.17.6/bin/node)
   npm    : 6.14.15
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue! I can reproduce this behavior, but it does not seem to be related to an issue inside of Ionic. The issue is the click handler here: https://github.com/juanjcardona13/NestedRoutesIonicVue/blob/main/src/views/GenericLayoutPage.vue#L6

When you click the `ion-back-button`, the component will automatically try to pop the page off the stack. But since you have a click handler that pushes `/tabs/tab1`, you are trying to push the same view that is getting popped off the stack.

Removing this @click handler fixes the issue from both options on my end. Can you try removing that and let me know if it fixes the issue for you?

**Comment by juanjcardona13** [comment]
Hello!
Thank you very much for your time and for reviewing this report, I just reviewed and applied your suggestion and it worked very well

I do not know if it was something very simple and I need to review it and pay more attention, but regardless, I thank you again for your help

It is very valuable to me
