### ISSUE TITLE
bug: Adding isPlatform to Vue page causes tests to fail

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-framework#24461]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Add `isPlatform` to a `.vue` file as shown here: https://github.com/kensodemann/test-is-platform/commit/ec505eb93dc81844cc215e495e8f371bea14e1c0

At that point, the test will start failing with the following errors:

```
 FAIL  tests/unit/example.spec.ts
  HomePage.vue
    ✕ renders home vue (36 ms)

  ● HomePage.vue › renders home vue

    TypeError: (0 , vue_1.isPlatform) is not a function

      51 |   },
      52 |   setup() {
    > 53 |     const isMobile = isPlatform("hybrid");
         |                      ^
      54 |     return { isMobile };
      55 |   },
      56 | });
```

### Expected Behavior

Test would not fail saying that `isPlatform` does not exist.

### Steps to Reproduce

I took a base blank starter for `@ionic/vue` and made only the following change: https://github.com/kensodemann/test-is-platform/commit/ec505eb93dc81844cc215e495e8f371bea14e1c0

I also tried mocking the method as such:

```
jest.mock('@ionic/vue', () => {
  const actual = jest.requireActual('@ionic/vue');
  return { ...actual, isPlatform: jest.fn() };
});
```

Which I would have thought would work since `jest.mock` calls should be hoisted, and even if `isPlatform` didn't exist for whatever reason 🤷‍♂️, it should at that point. Still no luck.

### Code Reproduction URL

https://github.com/kensodemann/test-is-platform

### Ionic Info

▶ ionic info

Ionic:

   Ionic CLI       : 6.18.1 (/Users/ken/.volta/tools/image/packages/@ionic/cli/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.3

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v16.13.0 (/Users/ken/.volta/tools/image/node/16.13.0/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Filed issue with VTU maintainer. We believe this to be an external bug: https://github.com/vuejs/test-utils/issues/1294

**Comment by liamdebeasi** [comment]
After discussing with the VTU maintainer, we believe this to be a Vue Jest bug: https://github.com/vuejs/vue-jest/issues/456

Vue Jest outputs the result in my sample app:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var vue_1 = require("@ionic/vue");

exports.default = {
  setup: function () {
    (0, vue_1.testFunction)();
  }
};
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.render = void 0;
var vue_1 = require("vue");
function render(_ctx, _cache) {
    return ((0, vue_1.openBlock)(), (0, vue_1.createElementBlock)("div", null, "Hello World"));
}
exports.render = render;
exports.default = {...exports.default, render};
```

Notice that both `vue` and `@ionic/vue` are assigned to the `vue_1` variable.

**Comment by liamdebeasi** [comment]
Hi everyone,

We have since moved our Ionic Vue starters to use Vite and Vitest which does not have this issue. Alternatively, you can use the `<script setup>` syntax to avoid the Vue Jest bug if you would prefer to stick with Vue CLI. I am going to close this, but let me know if you have questions.
