### ISSUE TITLE
bug: ion-datetime scrolls infinitely with dir=rtl

### ISSUE THREAD

**Issue by dima-gusyatiner** [ionic-team/ionic-framework#24472]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The calendar spins months backwards infinitely.
![Peek 2021-12-22 19-18](https://user-images.githubusercontent.com/6461669/147131043-41b0e9d1-74ef-4b38-bcc6-3c48c97d8c01.gif)

### Expected Behavior

The calendar should stay still.

### Steps to Reproduce

Add `dir="rtl"` to `index.html`

### Code Reproduction URL

https://github.com/dima-gusyatiner/datetime-migration-samples/commit/99e44f3b507806445bc0174525f7322cbbeb76af

### Ionic Info

Ionic:
   Ionic CLI                     : 6.16.3 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

System:
   NodeJS : v16.13.1 (/usr/bin/node)
   npm    : 8.3.0
   OS     : Linux 5.13

### Additional Information

Issue still persists on latest `angular` & `ionic` versions.

**Comment by sean-perkins** [comment]
Thanks for reporting this! See the same from our basic examples. Intersection observers and CSS scroll snap are a little finicky.

**Comment by sean-perkins** [comment]
This has been fixed in #24475 and will be available in the next release of Ionic after the New Year. Please let me know if you would like a dev build to test with in the interim. Thanks!
