### ISSUE TITLE
bug: `ion-datetime` timepicker does not respect hour cycle format with min provided

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/ionic-framework#24474]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When setting the minimum DateTime to now (`new Date()`), there is no way to select previous minutes even on a different hour.
And the hour wheel doesn't respect the default h23 even when specified.

### Expected Behavior

1. The min value should restrict only up to what is specified. if minimum was set to 19:30, I should be able to select 20:everthing else
2. The hour should stick to the default hour system or the specified one

### Steps to Reproduce

https://user-images.githubusercontent.com/12111716/147143799-39426950-d69e-438c-8b34-f793f4e727c7.mp4

```
  now = moment().add(1, 'h').format();
  minInsterval: number[];
  dateTime:any

ngOnInit() {
    const min = 0,
      max = 55,
      interval = 5;

    const length = (max - min) / interval + 1;
    this.minInsterval = Array.from({ length }, (_, i) => min + i * interval);
  }
```

```
<ion-datetime
        #calendar
        size="cover"
        hourCycle="h23"
        [min]="now"
        [minuteValues]="minInsterval"
        [(ngModel)]="dateTime"
      >
      </ion-datetime>
```

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/jonathan/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3
```

**Comment by sean-perkins** [comment]
Hello @jongbonga there appears to be an issue with the uploaded mp4. Can you please re-upload that video asset? Thanks!

**Comment by jongbonga** [comment]
hey @sean-perkins, updated! sorry about earlier, fighting with compression

**Comment by jongbonga** [comment]
@sean-perkins thanks for the title change, but notice the minutes' behavior, they don't update properly. the wheel is locked to the min value even when updating the hour

**Comment by sean-perkins** [comment]
@jongbonga I see that as well 👍 

Is this behavior closer to your expectation?

Min: 19:30
Initial value: 20:30
Hour cycle: h23

<video src="https://user-images.githubusercontent.com/13732623/147146337-f0d23717-ec29-41ad-9cf8-278236c85a0d.mp4"></video>

I believe the value going to 19:59 once stepping back isn't ideal 🤔  but also it cannot send you to 19:00 because of the min range.

**Comment by jongbonga** [comment]
Yes, 100%! 
if it goes back to 19:59, it won't be "wrong" as long as the other options can be set properly. and Yes, shouldn't go back to 19:00 because the min is the expected behavior

**Comment by jongbonga** [comment]
Will the fix also resolve the issue where 19:00 would show 7:00 first time then 19:00 when re-opened?

**Comment by sean-perkins** [comment]
Yes I believe so 👍  at least in the hour cycle examples, it is showing the 24 hour format consistently on initial render of the time, as well as for the time picker selection. 

Is that another bug logged somewhere else that I can associate to the PR?

**Comment by jongbonga** [comment]
I don't know if the issue is caused by the DateTime format being ISO but for some reason, I get it every time as you can see in the video.
I haven't logged it yet but I can. I will try to reproduce as soon as possible on a blank and will open a new one if the issue persists
