### ISSUE TITLE
bug: Ionic 6 + angular 13 live reaload on device not working

### ISSUE THREAD

**Issue by vadimwe** [ionic-team/ionic-framework#24485]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

ionic cordova run ios -l throws CLI errors:

`[ng] An unhandled exception occurred: Must use import to load ES Module: /Users/vs/Desktop/Projects/myDealer_client_app/node_modules/@angular/compiler-cli/bundles/index.js
[ng] require() of ES modules is not supported.
[ng] require() of /Users/vs/Desktop/Projects/myDealer_client_app/node_modules/@angular/compiler-cli/bundles/index.js from /Users/vs/Desktop/Projects/myDealer_client_app/node_modules/@ionic/angular-toolkit/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
[ng] Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/vs/Desktop/Projects/myDealer_client_app/node_modules/@angular/compiler-cli/package.json.
`

ionic cordova run iOS works as expected.

### Expected Behavior

ionic cordova run ios -l should start app on device with live reload.

### Steps to Reproduce

ionic cordova run ios -l with iPhone connected.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 10.1.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 17 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.5.0)   : 1.4.1

System:

   Android SDK Tools : 26.1.1 (/Users/vs/Library/Android/sdk)
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v14.18.1 (/usr/local/bin/node)
   npm               : 6.14.15
   OS                : macOS Big Sur
   Xcode             : Xcode 13.2.1 Build version 13C100

**Comment by indraraj26** [comment]
It is already being reported in ionic cli repo

Please track here https://github.com/ionic-team/ionic-cli/issues/4795

You can close this issue as it is nothing to do with this repo as of now.

**Comment by sean-perkins** [comment]
Closing this issue so that we can track it appropriately in the CLI repository. Thanks!
