### ISSUE TITLE
bug: ion-item don't changes ion-untouched to ion-touched on form markAllAsTouched();

### ISSUE THREAD

**Issue by oneclickwebstudio** [ionic-team/ionic-framework#24483]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

```
ion-item class="ion-untouched ion-pristine ion-invalid item-interactive item-input item ios item-fill-none in-list hydrated item-label item-label-floating"
```

### Expected Behavior

After form submitting i use  `markAllAsTouched()`
in previous versions it worked well
```
ion-item class="ion-touched ion-pristine ion-invalid item-interactive item-input item ios item-fill-none in-list hydrated item-label item-label-floating"
```

### Steps to Reproduce

just place ion-item with ion-input inside form element

### Code Reproduction URL

- https://github.com/sean-perkins/gh-24483-form-touched

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (....../.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.3

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v16.13.0 (....../.nvm/versions/node/v16.13.0/bin/node)
   npm    : 8.1.4
   OS     : macOS Monterey

```

**Comment by luke37b** [comment]
I'm experiencing the same issue after updating to Ionic 6 today.

**Comment by sean-perkins** [comment]
Thanks for reporting this issue 👍  I've created a reproduction app to help test the end solution.

**Comment by oneclickwebstudio** [comment]
Looking forward to receive bugfix.

**Comment by oneclickwebstudio** [comment]
problem still existing in 

```
"@ionic/core": "^6.0.2",
"@ionic/angular": "^6.0.2",
```

**Comment by oneclickwebstudio** [comment]
problem has been fixed in: 
```
"@ionic/core": "^6.0.3",
"@ionic/angular": "^6.0.3",
```
