### ISSUE TITLE
feat: declarative action sheet, alert, loading, toast, picker overlays

### ISSUE THREAD

**Issue by Sukaato** [ionic-team/ionic-framework#24484]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add trigger options on `ion-action-sheet` like `ion-popover`

### Describe the Use Case

It make action sheet more customizable

### Describe Preferred Solution

```tsx
{/* Use a trigger */}
<ion-button id="trigger-button">Click to open action sheet</ion-button>
<ion-action-sheet trigger="trigger-button">
    <ion-content>Action sheet Content</ion-content>
</ion-action-sheet>
```

**Comment by liamdebeasi** [comment]
Thanks! We plan on making the remaining overlays declarative, so I think this is a feature we should add.

**Comment by waterplea** [comment]
Any news on this issue?

**Comment by liamdebeasi** [comment]
Hi everyone,

We have completed work on this, and the changes are currently targeted for the Ionic 7.0 release. We will have a public beta testing period in the future where developers can try the new inline overlays and provide feedback. I am going to close this, but let me know if there are any questions.
