### ISSUE TITLE
bug: PopoverOptions interface lacks arrow attribute

### ISSUE THREAD

**Issue by HyperLife1119** [ionic-team/ionic-framework#24487]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

`PopoverOptions` interface lacks `arrow` attribute.
Cannot enable `arrow` when using popover controller to create popover.

### Expected Behavior

The `PopoverOptions` interface should provide `arrow` attribute.

### Steps to Reproduce

https://github.com/ionic-team/ionic-framework/blob/ee488ff27a05cc3325deb48d39162695a3ff815e/core/src/components/popover/popover-interface.ts#L9

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework/blob/ee488ff27a05cc3325deb48d39162695a3ff815e/core/src/components/popover/popover-interface.ts#L9

### Ionic Info

Ionic:

   Ionic CLI                     : 6.11.10 (C:\Users\18384\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

**Comment by sean-perkins** [comment]
You can work around this issue by type casting the component props:

```ts
.create({
  componentProps: {
    arrow: true
  } as any
});
```

but I agree that it should be added to the popover interface 👍

**Comment by HyperLife1119** [comment]
Thanks for the reply, hope it can be fixed as soon as possible. 😋

**Comment by queejie** [comment]
Even if the type error is suppressed with @ts-ignore, the **arrow:true** does not actually show the arrow.

**Comment by shivamsharmanps** [comment]
> Even if the type error is suppressed with @ts-ignore, the **arrow:true** does not actually show the arrow, with **mode:'ios'**, as it used to in previous versions.

I am also getting this issue I was using "@ionic/angular": "^5.5.2", and used popover with arrow for every platform ios/android/desktop but after migration, It just disappeared with popover controller even I have added mode/arrow-
const instance = await this.tooltipCtrl.create({
      cssClass: 'popover-1',
      mode: 'ios',
      component: Component,
      componentProps: {param: paramText},
      event: ev,
      reference: "event",
      side: 'top',
      align: 'end'
    });

**Comment by shivamsharmanps** [comment]
> > Even if the type error is suppressed with @ts-ignore, the **arrow:true** does not actually show the arrow, with **mode:'ios'**, as it used to in previous versions.
> 
> I am also getting this issue I was using "@ionic/angular": "^5.5.2", and used popover with arrow for every platform ios/android/desktop but after migration, It just disappeared with popover controller even I have added mode/arrow- const instance = await this.tooltipCtrl.create({ cssClass: 'popover-1', mode: 'ios', component: Component, componentProps: {param: paramText}, event: ev, arrow: true, reference: "event", side: 'top', align: 'end' });

It is still not working , arrow is not appearing for browser even I set mode: 'ios'

**Comment by HyperLife1119** [comment]
https://github.com/ionic-team/ionic-framework/issues/24389

**Comment by HyperLife1119** [comment]
#24389
