### ISSUE TITLE
bug: Ionic React Breadcrumbs `href` prop causes full page refresh

### ISSUE THREAD

**Issue by babycourageous** [ionic-team/ionic-framework#24493]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

There currently isn't a `routerLink` prop on the `IonBreadcrumb` for Ionic React. It seems the only way to navigate with them is through the `href` prop which causes a full page refresh and you lose out on animations, etc. 

Filing this under bug since it seems other "routing" type components do have a `routerLink` prop for Ionic React components to take advantage of. But happy to move to Feature Request if that's more appropriate a spot.

Thanks!

### Expected Behavior

I think since breadcrumbs are used to route within your app having a `routerLink` prop for React apps like other routing components so that there isn't a full page refresh when using the breadcrumb.

### Steps to Reproduce

You can spin up the repo sample and navigate either to the "list" or "detail" page. If you then use the breadcrumb to navigate back in the tree you will see the full page refresh. 

### Code Reproduction URL

https://github.com/babycourageous/ionic-breadcrumbs-routing-refresh

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/Users/renedellefont/.fnm/node-versions/v14.17.6/installation/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.6 (/Users/renedellefont/.fnm/node-versions/v14.17.6/installation/bin/node)
   npm    : 6.14.15
   OS     : macOS Big Sur

**Comment by sean-perkins** [comment]
Thanks for reporting this @babycourageous! 

I agree, `ion-breadcrumb` is a routing component and should have the same behavior as other components with `routerLink`.

**Comment by babycourageous** [comment]
Thanks so much for the update @sean-perkins . Oh wow AND PR. Awesome!!
