### ISSUE TITLE
bug: Uncaught RangeError: Maximum call stack size exceeded. Stacked overlays with focusable elements

### ISSUE THREAD

**Issue by CFT-Chris** [ionic-team/ionic-framework#24491]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

An Ionic component with an overlay and a focusable element opens another Ionic component with an overlay and a focusable element.  Infinite loop occurs (trapkeyboardFocus leads to focus on a descendant, causing focus event handler to spawn the same behaviour):

```
Uncaught RangeError: Maximum call stack size exceeded.
    at focusElement (helpers-eed79a2b.js:158)
    at focusFirstDescendant (overlays-5f2f4ffc.js:4090)
    at trapShadowFocus (overlays-5f2f4ffc.js:4230)
    at trapKeyboardFocus (overlays-5f2f4ffc.js:4247)
    at HTMLDocument.<anonymous> (overlays-5f2f4ffc.js:4256)
    at ZoneDelegate.invokeTask (zone.js:434)
    at Zone.runTask (zone.js:205)
    at ZoneTask.invokeTask [as invoke] (zone.js:516)
    at invokeTask (zone.js:1656)
    at HTMLDocument.globalZoneAwareCaptureCallback (zone.js:1725)
```

### Expected Behavior

No infinite loop that causes call stack size to be exceeded.

### Steps to Reproduce

1. `ionic start` Angular project
2. choose menu template
3. make menu have an overlay by removing the split pane in the template's app component's HTML
4. create a modal with a button inside of it
5. make an ion-item as a button in the menu present the modal

### Code Reproduction URL

https://github.com/CFT-Chris/trapKeyboardFocusBug

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/home/chris/.nvm/versions/node/v16.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/home/chris/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.1.2
   OS     : Linux 5.13
```

### Additional Information

This was already logged here but was closed due to inactivity: https://github.com/ionic-team/ionic-framework/issues/23655

**Comment by thameurr** [comment]
same problem here any update ?

**Comment by henkkelder** [comment]
I also have this error when using popovers. But only on when running in 'IOS' mode. Not in MD mode.

**Comment by CFT-Chris** [comment]
An option to turn this behaviour off (focusFirstDescendant) would be preferable in addition to fixing the infinite loop case, since many applications have modal or popover forms and placeholders/hints for unfocused inputs.  

If the first form element always gains focus, then any placeholder or hint is never seen.  In some cases, validation also triggers prematurely showing an error for that input element.  Focusing on the modal/popover itself would be optimal (e.g. with its tabIndex="-1") so that accessibility can still focus on the first input with a Tab keypress.

**Comment by filiphecarvalho** [comment]
In my case, for now, replacing a direct record of a <IonModal> component by a useIonModal #hook worked perfectly. I believe that in this situation, the focus to the child component is not realized because the useIonModal add to the DOM dynamically an <ion-modal>.

But the bug still persists! :(

Ref: https://ionicframework.com/docs/api/modal#useionmodal-hook

**Comment by sean-perkins** [comment]
Hello @CFT-Chris thanks for reporting this issue & attaching an example. I'm seeing the same behavior on my end.

Will share more once the team has a moment to prioritize in the upcoming sprints.

**Comment by guidopontet** [comment]
Same problem, any update?

**Comment by aquachris** [comment]
same problem here

**Comment by onesse** [comment]
Same problem here but with a react Project :
There is another repo for error reproduction and instructions
https://github.com/onesse/ionic_toast_error

**Comment by hermitdemschoenenleben** [comment]
same problem here

**Comment by 442623641** [comment]
same problem here

**Comment by 442623641** [comment]
I escaped the broken by inserting a  input `<input style="display: none;" />`

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can everyone try the following dev build and let me know if it resolves the issue?

Dev Build: 6.0.4-dev.1642703076.3d49fbe
Install example (using Angular as an example): `npm install @ionic/angular@6.0.4-dev.1642703076.3d49fbe`

**Comment by CFT-Chris** [comment]
> Thanks for the issue. Can everyone try the following dev build and let me know if it resolves the issue?
> 
> Dev Build: 6.0.4-dev.1642703076.3d49fbe Install example (using Angular as an example): `npm install @ionic/angular@6.0.4-dev.1642703076.3d49fbe`

Hi Liam, thanks for looking at this.

The `Uncaught RangeError: Maximum call stack size exceeded.` still happens. It no longer errors immediately when the second overlay appears, but instead it errors when I focus on an input element in the second overlay (whether using the mouse or Tab key).  

Consequently, the focus is not kept in the input element, and the user is ultimately unable to fill out any form data in the second overlay.

**Comment by liamdebeasi** [comment]
Thanks for testing. Can you try this dev build? It should fix the issue with the inputs as well:

`6.0.4-dev.1642713982.5768e9d`

**Comment by CFT-Chris** [comment]
Yes, it appears to be working now.  Thanks!

Now working without error:
- opening a popover or modal from a menu (with menu staying open after second overlay presented)
- focusing on an input element with tab or click in the second overlay
- first input element doesn't automatically get focus, which is good for keeping the initial placeholder/hint displayed

Presumably whatever the new behaviour was supposed to be introduced with the new "trapKeyboardFocus"/"focusFirstDescendant" is still there, but I don't know what to test to confirm that.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24611, and a fix will be available in an upcoming release of Ionic Framework.
