### ISSUE TITLE
bug: ion-accordion in a ion-menu scrolls up every time the menu opens. 

### ISSUE THREAD

**Issue by erikramalho** [ionic-team/ionic-framework#24506]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

If we put a ion-accordion inside a ion-menu with a ion-split-pane app, the menu scrolls up every time you close and reopen the ion-menu. The ion-menu scroll up right after the event ionDidOpen finishes.

### Expected Behavior

The ion-menu must keep the scroll postion. This behavior is seen if you put a ion-list + ion-item in a ion-menu.

### Steps to Reproduce

Just create a side menu app  (ionic start and side menu) and then place a multiple ion-accordion / ion-accordion-group. You can use the demo code provided on the ionic page

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/node/v12.22.5/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 12.2.14
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 12.2.14
   @ionic/angular-toolkit        : 5.0.1

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v12.22.5 (/.nvm/versions/node/v12.22.5/bin/node)
   npm        : 6.14.14
   OS         : macOS Monterey
   Xcode      : Xcode 13.2.1 Build version 13C100

**Comment by amandaesmith3** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
