### ISSUE TITLE
bug: Angular Inline Sheet Modal are not updated

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#24502]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

CommonModule Angular directives for example ngFor or ngIf inside Inline Sheet Modal are not updated. I think because of ng-template. For example, you can't do a search and update the list.

### Expected Behavior

Items should be updated.

### Steps to Reproduce

Create an Inline Sheet Modal with a list with items and a ngFor, update the array.

### Code Reproduction URL

https://github.com/Marius-Romanus/ionic-bug-modals-24502
https://stackblitz.com/edit/ionic-angular-v5-g9hhgc?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

Ionic:

   Ionic CLI : 6.18.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v17.3.0
   npm    : 8.3.0
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Thanks @Marius-Romanus for reporting this issue.

There does appear to be an issue with dynamically changing the values bound within the `ng-template` for inline modal usage. This applies to pipes, structural directives, etc.

I'll need to dig a little deeper into our inline usage to see if there's anywhere we are caching the template reference that is conflicting with how Angular triggers change detection on those projected templates.
