### ISSUE TITLE
TS error: cssClass property doesn't exist on IonModal

### ISSUE THREAD

**Issue by Janaka-Steph** [ionic-team/ionic-framework#24504]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Type '{ children: Element[]; cssClass: string; isOpen: boolean; onDidDismiss: (ev: any) => void; }' is not assignable to type 'IntrinsicAttributes & IonModal & Pick<HTMLAttributes<HTMLIonModalElement>, "slot" | "title" | "defaultChecked" | ... 249 more ... | "onTransitionEndCapture"> & IonicReactProps & RefAttributes<...>'.

Property 'cssClass' does not exist on type 'IntrinsicAttributes & IonModal & Pick<HTMLAttributes<HTMLIonModalElement>, "slot" | "title" | "defaultChecked" | ... 249 more ... | "onTransitionEndCapture"> & IonicReactProps & RefAttributes<...>'.  TS2322

### Expected Behavior

cssClass property should be included in IonModal type.

### Steps to Reproduce

Install Ionic-React 6, Typescript 4.5.4 and use IonModal with a cssClass property.

### Ionic Info

▶ ionic info

Ionic:
   Ionic CLI       : 6.18.1
   Ionic Framework : @ionic/react 6.0.1

Capacitor:
   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.3

Utility:
   cordova-res : 0.15.4
   native-run  : 1.5.0

System:
   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.1.4
   OS     : macOS Monterey

### Additional Information

Typescript 4.5.4

**Comment by sean-perkins** [comment]
Hello @Janaka-Steph, thanks for reporting this issue.

Is there a reason for the inline usage of `IonModal`, that you are not taking advantage of `className` instead?

```tsx
<IonModal className='my-custom-class'>

</IonModal>
```

**Comment by Janaka-Steph** [comment]
@sean-perkins The reason is that I thought `cssClass` is the proper way to apply styles unless it changed in v6. Also the property is still in the v6 documentation https://ionicframework.com/docs/api/modal#interfaces

**Comment by sean-perkins** [comment]
@Janaka-Steph in that same section we do try to call out that those options are for the controller pattern:
> These options should be supplied when calling modalController.create().

The inline pattern acts like a regular HTMLElement, allowing you to use the syntax pattern of your respective framework (i.e. `className` for React). The reason that his pattern is different than the controller usage, is that developers don't have direct access to the element reference when using the more declarative pattern. 

Closing this issue out as `className` will resolve your use case. Thanks!
