### ISSUE TITLE
bug: alert header formatting can result in overlapping text

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionic-framework#24513]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

There are issues with the formatting of the header within an Ionic alert dialog.

If you display an alert with a long title as follows:

```ts
alertController.create({
    header: 'This is a long header value', 
    message: 'Sample message'
});
```

The resulting alert dialog shows:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/2199401/148230831-371f7a94-e72b-41b8-84f0-5c2c51292450.png">

If you specify a subHeader value as follows:

```ts
alertController.create({
    header: 'Sample title', 
    subHeader: 'Sample subtitle',
    message: 'Sample message'
});
```

The resulting alert dialog shows:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/2199401/148231889-51af398f-ad0a-4321-bbeb-a939910f1033.png">

### Expected Behavior

If the header value does not fit then it should wrap to the next line.

The subHeader should not overlap the header.

### Steps to Reproduce

```ts
const alert = await alertController.create({
    header: 'This is a long header value', 
    subHeader: 'Sample subtitle',
    message: 'Sample message'
});
alert.present();
```

**Comment by sean-perkins** [comment]
Hello @cjorasch could you provide a reproduction of the issue? I'm having a difficult time seeing the same result. Also are you seeing this on device vs. in the browser?

Here's what I am seeing (browser preview):

|Android|iOS|
|----|----|
|<img src="https://user-images.githubusercontent.com/13732623/148251011-8e12069a-c8f8-49ff-a02d-36e6af14767b.png" width="350px" /> | <img src="https://user-images.githubusercontent.com/13732623/148251013-c9b8d6a6-201d-4612-a516-30d348bb3c17.png" width="350px" />|

with the following:
```ts
const alert = await this.alertCtrl.create({
  header: 'This is a long header value',
  subHeader: 'This is a long subheader',
  message: 'This is a message'
});
alert.present();
```

Thanks!

**Comment by cjorasch** [comment]
I am seeing the problem on Chrome, and with Chrome emulating iPhone or
Galaxy.

I will try to put together a repro project
