### ISSUE TITLE
bug: ion-img and others do not load propsData appropriately in unit tests 

### ISSUE THREAD

**Issue by 1beb** [ionic-team/ionic-framework#24520]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I've created a repository for review here: https://github.com/1beb/bug-report-ioni-img-example

When you run the test, if you look at the html, you'll see that the propsData get pushed onto the root node, instead of the actual node that they should be: 

Here's the component: 

```
<template>
  <div id="container">
    <strong>{{ name }}</strong>
    <ion-img :src="img"></ion-img>
    <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
  </div>
</template>

<script lang="ts">
import { IonImg } from "@ionic/vue";

export default {
  name: 'ExploreContainer',
  components: {
    IonImg
  },
  props: {
    name: String,
    img: String,
  }
}
</script>

<style scoped>
/* snipped */
</style>
```

Here's the test: 

```
import { mount } from '@vue/test-utils'
import ExploreContainer from '@/components/ExploreContainer.vue'

describe('Tab1Page.vue', () => {
  it('renders ExploreContainer component, () => {
    const wrapper = mount(ExploreContainer, { propsData: { name: "hello", img: "https://picsum.photos/200/300" }})
    expect(wrapper.text()).toMatch('hello')
    console.log(wrapper.html())
    console.log(wrapper.props())
  })
})
```

Here's the output of the wrapper.html() 

```
    <div id="container"><strong>hello</strong>
      <ion-img class=""></ion-img> // NO src?
      <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
    </div>
```

### Expected Behavior

I would have expected the propsData to load approiately as `:src="img"`

### Steps to Reproduce

See provided repo: 

### Code Reproduction URL

https://github.com/1beb/bug-report-ioni-img-example

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /usr/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/lib/node_modules/@ionic/cli/index.js
       - /usr/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /usr/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/lib/node_modules/@ionic/cli/index.js
       - /usr/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.18.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/usr/bin/node)
   npm    : 8.1.2
   OS     : Linux 5.15
 ```

### Additional Information

Nothing more to add.

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I think the issue here is that you are missing an `await` from the `wrapper.setProps`. When I add the await, this works consistently for me. Can you give that a shot and let me know if it works?

**Comment by 1beb** [comment]
Thanks Liam, my only comment would be that this happens on all newer versions of vue packages, but it does not happen on older versions. I don't believe the async/await requirement is new. I had tried some variations with async/await and it work on the old+new.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. Can you clarify what you mean by "vue packages"? Are you referring to the `vue` package or `@ionic/vue`? 

Also there is a note in the `setProps` documentation that says to use `await`: https://next.vue-test-utils.vuejs.org/api/#setprops (might be new to this version of the Vue Test Utils)
