### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by ford-thomas-w** [ionic-team/ionic-framework#24527]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The popover triggerAction option "context-menu" does not seem to work.   

### Expected Behavior

Per docs: https://ionicframework.com/docs/api/popover#triggeraction

1. I would expect the popover to appear when the user right-clicks or long-presses  (mobile) over the div element.  However, it seems to appear on "click" instead. 
   ** I know the trigger placement is by element ID.  However, for the context-menu option, wouldn't it make more sense to use the event reference instead since that is more consistent with the actual context menu behavior?

2. I would expect the div element to not lose focus if the cursor is in the box when the user right-clicks or long-presses over it.   This is important for input elements if you want use the popover options to insert something at the cursor point.

### Steps to Reproduce

Use the inline popover in ionic 6 with trigger and triggerAction=context-menu as show in the gist provided.

### Code Reproduction URL

https://gist.github.com/ford-thomas-w/9496d8ef2cb95046c95c72d1242828a3

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try writing `trigger-action` instead of `triggerAction`? When using the popover with plain HTML, you need to set the attribute rather than the property.

**Comment by ford-thomas-w** [comment]
Sorry, I had copied that over from a StencilJs project which uses JSX in render method which is why it was camelCase.  Was hoping the simple html gist would be sufficient to demo the issue, but it seems not.  I'm afraid I don't have time to demo this a stencil starter project with ionic and I've found a workaround for the feature I'm working on.  Thanks anyhow.

**Comment by liamdebeasi** [comment]
No problem. I am going to close this issue out, but feel free to open a new issue with a code reproduction if you run into it again. Thanks!
