### ISSUE TITLE
feat: Accordion second action on header slot

### ISSUE THREAD

**Issue by Errabaany** [ionic-team/ionic-framework#24536]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The New Accordion Component slot header is toggling the content if you clicked in the whole element,
I want a feature that makes the click works on icon only

### Describe the Use Case

use a second action in header slot

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe your use case a bit more for this feature? A sample application that shows the issues you are running into right now would be helpful.

**Comment by Errabaany** [comment]
somehow I forgot to answer @liamdebeasi question,
Yes exactly just like @leejustin attached in the Video.

**Comment by liamdebeasi** [comment]
Thanks! You should be able to do this already in Ionic. Here is an example: https://codepen.io/liamdebeasi/pen/YzroNdV?editors=1010

Ionic listens for clicks on the element in the `header` slot. By using `stopPropagation` when clicking your second action, you can prevent the click event from bubbling up to the element in the `header` slot.

Does that work for your use case?

**Comment by Errabaany** [comment]
Yes that what I wanted
Thank You

**Comment by leejustin** [comment]
@liamdebeasi I think I can make this work. It's not working for me but it might because I'm using Ionic React? I'll be playing around a bit to figure it out. Thanks for the suggestion!

**Comment by leejustin** [comment]
Alright I'm just leaving a paper trail but I got this working for my use case. I'm using React 17 and the way React handles events as synthetic events made it really difficult to get this working. I read a lot of guides that suggested doing something like:
```javascript
  const onOptionClick = (e) => {
    e.stopPropagation();
  };
```
I tried `e.stopPropagation()`, `e.nativeEvent.stopImmediatePropagation()` and nothing worked.

In the end I set up an `EventListener` to check for native propagation of events and checks to see if the class name of the target was expected:
```javascript
  useEffect(() => {
    function handleStopPropagation(e: any) {
      if (e.target.className.includes("accordion-title")) {
        e.stopPropagation();
      }
    }

    const parentDivs = document.getElementsByClassName("accordion-header");
    for (let i = 0; i < parentDivs.length; i++) {
      parentDivs[i].addEventListener('click', handleStopPropagation);
    }

    return () => {
      for (let i = 0; i < parentDivs.length; i++) {
        parentDivs[i].removeEventListener("click", handleStopPropagation);
      }
    }
  })
```
and I set the `header` element with `className="accordion-header"` and `className="accordion-title"` on the element that I did not want expanding/collapsing the menu.

It's not the cleanest implementation but this is what worked for me.
