### ISSUE TITLE
bug: missing sass files

### ISSUE THREAD

**Issue by fmp777** [ionic-team/ionic-framework#24543]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Brand new project, started by Ionic website. When cloned and npm installed, project has src/theme/variables.css without the sass file.

### Expected Behavior

Include the sass for easy modification of the theme.

### Steps to Reproduce

1. Start a brand new project, tab starter template, vuejs.
2. and no sass.

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.10.0 (/opt/homebrew/Cellar/node/16.10.0_1/bin/node)
   npm    : 8.0.0
   OS     : macOS Monterey

### Additional Information

Old threads online suggest to run ionic setup sass - but that no longer seems to be a part of ionic 6.  There is an old issue here in GitHub with the same complaint, but that was supposedly solved back then.

**Comment by fmp777** [comment]
Why wouldn't you at least include a file with the default CSS variables then?  Really makes the learning curve of ionic greater when we have to hunt down whatever these variables are supposed to be. I don't see a good reasoning for this.

**Comment by amandaesmith3** [comment]
Documentation on available CSS variables can be found here: https://ionicframework.com/docs/theming/css-variables#ionic-variables Does that help or is there anything else we can answer?

**Comment by fmp777** [comment]
Those docs are sorely lacking when one simply wants to theme the UI.  Not to mention it still says the sass file is included.
![image](https://user-images.githubusercontent.com/2659615/150899628-1b8ada4e-61ad-4ae5-ad21-6b5e35f4ab5c.png)

I'm not sure why you guys chose to go that way, suppose that's one reason why popularity has been rapidly decreasing. Anyway, thank you for your attention and answers. I'll close this, think I'm going Framework7+Svelte anyway.
