### ISSUE TITLE
bug: datetime, showing calendar body after intersection observer callback causes issues on safari

### ISSUE THREAD

**Issue by elbugs** [ionic-team/ionic-framework#24542]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Animations are choppy, feels like need more frames. (Have seen it opening a date time and action sheet menu
![ezgif-6-1b0a9adcd5](https://user-images.githubusercontent.com/3017280/148698343-0d018144-bc14-4d00-b915-8fdbf6974b7d.gif)
)

### Expected Behavior

It should open smooth, without lag, without choppy frames. Like in material design, or google chrome: 
![ezgif-3-39c1c976ab](https://user-images.githubusercontent.com/3017280/148701609-b67564da-4ab4-47a0-a8f5-78d27b66f9f0.gif)

### Steps to Reproduce

Just install the blank starter project, add a ionic date-time for exampl. 
Open in Safari with **ios** theme and click to open the modal. Be aware of the choppy frames at the end of the animation and the lag at showing the days of the month. 

All of this issues do not happen in Chrome, _neither with md or ios theme_ or Android device.  
Also, does not happen with Safari **with** md theme.

### Code Reproduction URL

https://github.com/gpiccon/ionic_playground

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.1

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4 (/Users/jordipicon/node_modules/@capacitor/android)
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4 (/Users/jordipicon/node_modules/@capacitor/ios)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

### Additional Information

Note: Can't reproduce with Angular framework.

**Comment by liamdebeasi** [comment]
Thanks for the issue. There appear to be two reported problems:

1. The entering animation in iOS mode on Safari has poor performance.
2. There is a delay in showing the body of the calendar picker in iOS mode on Safari.

Did I understand the issue correctly? I can reproduce issue 2, but I cannot reproduce issue 1. What device are you testing on to get issue 1 to reproduce?

**Comment by gpiccon** [comment]
Hello. Yes, you are right. 
Issue 1 happens on iPad and iOS when I compile using capacitor, MacBook Pro M1 with Safari and narrow screen... Everywhere. How can I help?

**Comment by liamdebeasi** [comment]
Thanks! I think the jump you are seeing in Safari is related to the repaint that happens when we show the calendar body. This behavior was added to workaround another issue, but I think we can improve on this: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/datetime/datetime.tsx#L867-L876

My current thinking is that by removing this additional repaint the animation jump in Safari will disappear as well.

**Comment by gpiccon** [comment]
Thanks! I do not think that's the problem, well maybe it's part of it. Why?
Because with the ActionSheet animation happens the same behaviour :/

**Comment by liamdebeasi** [comment]
What version of Safari are you testing this on? It might be a matter of device performance or a Safari bug.

**Comment by gpiccon** [comment]
I'm on Safari 15.1 (17612.2.9.1.20) in Mac OS Monterey 12.0.1 (21A559). I don't think so because in the iPhone when compiled with capacitor happens the same... That's the big problem here, the iOS performance, I can't ship the app with that performance. (Still work to do for about 5 months, but we have to find the way to solve it) I post this in the forums and had no reply, it's strange to me that nobody has the same bad performance, so maybe it's something from my side... I don't know what as it happens with a blank template. I'm open to work and help you in whatever you need to improve ionic even more, despite this issues I'm fall in love with it. Congrats and keep up the good work!!

**Comment by liamdebeasi** [comment]
Are you able to help me better understand how to reproduce the performance issue? I cannot reproduce it on my end, and I am unable to see any animation jumping in the video in https://github.com/ionic-team/ionic-framework/issues/24542#issuecomment-1009132926.

**Comment by gpiccon** [comment]
It's like all the animations in general at the end of the animation breaks too hard, so that's why it does not look smooth. I can record a video, but the FPS are not helping to show the issue... :/

**Comment by gpiccon** [comment]
Okay, here is a comparative between native Objetive-c action sheet, and ionic6 with react. 
Look at the end of the animation, you will see a little jump.
![image](https://user-images.githubusercontent.com/3017280/148935641-70baf890-8e13-43d5-ac48-4a0163cd7bec.png)

Thats what is happening with iOS theme. If I compile the app forcing the MD design, everything runs smooth. 

https://vimeo.com/664717008/a6bf5a9b50

**Comment by gpiccon** [comment]
Hello. Are you able to see the performance issue now? Is there anything else I can help with? Thanks 🙂

**Comment by andrerds** [comment]
> I'm on Safari 15.1 (17612.2.9.1.20) in Mac OS Monterey 12.0.1 (21A559). I don't think so because in the iPhone when compiled with capacitor happens the same... That's the big problem here, the iOS performance, I can't ship the app with that performance. (Still work to do for about 5 months, but we have to find the way to solve it) I post this in the forums and had no reply, it's strange to me that nobody has the same bad performance, so maybe it's something from my side... I don't know what as it happens with a blank template. I'm open to work and help you in whatever you need to improve ionic even more, despite this issues I'm fall in love with it. Congrats and keep up the good work!!

Hey man, how are you?
I'm having the same problem, apart from that there are some strange behaviors using the time, sometimes it selects it right, sometimes it has the time zeroed out of the performance that was shown there.
I had to resort to other date pickers, until this date time was better.

I liked it a lot, but with these gaps and delays it was really bad.
Thanks man, you're not alone.

**Comment by liamdebeasi** [comment]
I finally found the issue with the animations. Applying an easing to the overall animation effect (like Ionic does) does not produce the same visual results as applying an easing to the first of two keyframes. While effect and keyframes animations are different, both should produce the same visual results in the case of an animation with 2 keyframes.

I reported this to Apple (https://bugs.webkit.org/show_bug.cgi?id=241020) and will look into a possible workaround in Ionic.

**Comment by liamdebeasi** [comment]
This issue is dedicated to an issue in datetime and is unrelated to the animation issues being reported on this thread. As a result, I created https://github.com/ionic-team/ionic-framework/issues/25369 which will track updates on the animation issue.

When the datetime issue is resolved, this thread will be closed out. Please follow the linked thread for updates on the animation issue.

**Comment by elbugs** [comment]
Hey Liam, one quick question, why this is not happening with Angular and how is it possible that no one has detect this before? Looks weird to me that we are in version 6 of ionic with this issue that seems stupid, but affects the overall look of the apps, making a sensation of not a native app. Thanks.

**Comment by elbugs** [comment]
I know it is a bug from WebKit but my question is, why this is. It happening with angular for example? Or in Inter words, all the apps made with ionic and react are facing this issue and from ionic aren't offering any solution? I consider that a workaround from your side or at least a guide on how to solve it would be helpful. In the end it's the image of ionic.

**Comment by capc0** [comment]
has there been any update on this? explicitly the delayed animation for the datetime picker.

**Comment by liamdebeasi** [comment]
Updates on the animation issue are being tracked in https://github.com/ionic-team/ionic-framework/issues/25369.

**Comment by hedinasr** [comment]
any news on this issue ?

**Comment by liamdebeasi** [comment]
Hi everyone,

Here is a dev build with a proposed fix: `7.8.1-dev.11710449785.14ebd5a0`. This patch should resolve the original issue where the calendar body does not show until the modal animation finishes on iOS.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29163, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue testing the dev build, and let me know if you have any questions.
