### ISSUE TITLE
bug: ModalController.getTop() method returns modals that are closed

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/ionic-framework#24545]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I have an Ionic app that displays Datetime-Pickers in Modals.

With the switch to Ionic 6 I changed my code from this solution:
```
<ion-datetime (ionChange)="dateTimeChange($event)"
             displayFormat="DD.MM.YYYY"
             [value]="startAt"
             [min]="minStartAt"
             [max]="maxStartAt">
</ion-datetime>
```

to this one (as explained in the documentation [here](https://ionicframework.com/docs/api/datetime#usage)):
```
<ion-button fill="clear" id="open-start-date-input">
  <ion-icon icon="calendar"></ion-icon>
  <ion-input>&nbsp;{{ startAt | date }}</ion-input>
</ion-button>
<ion-modal class="datetime" trigger="open-start-date-input" show-backdrop="false">
  <ng-template>
    <ion-datetime (ionChange)="dateTimeChange($event)"
                  presentation="date"
                  [min]="minStartAt"
                  [max]="maxStartAt"
                  [value]="startAt"
                  [showDefaultButtons]="true">
    </ion-datetime>
  </ng-template>
</ion-modal>
```

Now when I want to close my "main" modal by calling `(await this.modalController.getTop()).dismiss()` the already closed inner Datetime Modal get's returned by `this.modalController.getTop()` so the "main" modal won't close.

### Expected Behavior

`ModalController.getTop()` only returns modals that are currently displayed.
Modals, that are not shown aren't returned.

### Steps to Reproduce

Migrating Datetimes in Modals from the Ionic 4/5 approach to Ionic 6 and try to dismiss a Modal via the `ModalController.getTop()` approach

### Code Reproduction URL

- https://github.com/sean-perkins/gh-24545-modal-top

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 12.2.13
   @angular-devkit/schematics    : 12.2.13
   @angular/cli                  : 12.2.13
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by sean-perkins** [comment]
@carstenbaumhoegger thanks for reporting this issue!

This is also an issue with the regular `modalCtrl.dismiss` behavior, as it will call `#getTop()` when an id isn't supplied.

**Comment by sean-perkins** [comment]
Closing in favor of #19111.

**Comment by sean-perkins** [comment]
@papagei-ma were you able to access `getTop()` previous to this change (compare v6.0.1 vs v6.0.4) in the `ngOnInit` life cycle?

My initial thought is that anything dealing with DOM querying should happen in `ngAfterViewInit`.

**Comment by papagei-ma** [comment]
@sean-perkins thanks for the reply. Anyways, even in `ngAfterViewInit` I get the same result, I guess it has got something to do with change detector. 
And, Sorry about the unclear clarifications, Actually the last version I was able to get the modal with in `ngOnInit,` was 5.8.4 :(. So none of 6.0.x are working for me !

**Comment by papagei-ma** [comment]
@sean-perkins I hope its ok, that I created a new issue https://github.com/ionic-team/ionic-framework/issues/24545 for this matter.
