### ISSUE TITLE
bug: action sheet controller referencing ActionSheet before initialized

### ISSUE THREAD

**Issue by popcorn245** [ionic-team/ionic-framework#24549]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Updated from ionic 5 to 6 and throws an error that has been reported by several users.

### Expected Behavior

Should work on as it did before the update

### Steps to Reproduce

Start the app and try to use a select on any page.

### Code Reproduction URL

https://github.com/popcorn245/ionic6-select-bug

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.13.1
   npm    : 8.1.2
   OS     : Windows 10

### Additional Information

Related to this issue.

https://github.com/ionic-team/ionic-framework/issues/24448#event-5852991367

**Comment by popcorn245** [comment]
![image](https://user-images.githubusercontent.com/4184680/148887584-3288969a-40dd-496f-bc44-40585224aee7.png)

Also, kills prerender even if not using the component in your build.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This behavior broke between RC 2 and RC 3 with RC 2 being the last working version.

**Comment by corysmc** [comment]
So I was seeing this same issue when running stencil in dev serve - however when I pulled the `--dev` flag off - it's serving properly (but minified - so kind of a pain - but at least it works): `stencil build --watch --serve`

`@stencil/core@2.12.0`
`@ionic/core@6.0.4`

Other workaround is to downgrade to `@ionic/core@6.0.0-rc.2`

**Comment by GerardvdStelt** [comment]
I have the exact same problem using StencilJS. Using ```@ionic/core@6.0.3``` I can run locally but making a static build (```stencil build --prerender```) fails due to the before mentioned reason. Upgrading to @ionic/core@6.0.4 makes that I cannot even run locally; the build provides no errors but the browser starts complaining about ActionSheet and doesn't show my page anymore.

Downgrading to ```@ionic/core@6.0.0-rc.2``` like @corysmc mentions fixes these issues.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24681, and a fix will be available in an upcoming release of Ionic Framework.
