### ISSUE TITLE
bug: Navigation Breaks 

### ISSUE THREAD

**Issue by AksharX** [ionic-team/ionic-framework#24541]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Navigation breaks, the page becomes overlayed by another ion-page and make the app unusable until you refresh.

### Expected Behavior

Navigation shouldn't break by visiting the links. Seems like multiple IonRouterOutlet are being spawned and there are pages that are in the wrong place. 

### Steps to Reproduce

https://stackblitz.com/edit/ionic-react-routing-8hm4w3

Navigating by utilizing the links will eventually break the application

### Code Reproduction URL

https://stackblitz.com/edit/ionic-react-routing-8hm4w3

**Comment by brhoomjs** [comment]
Fixing that by setting these:

`<ion-content color="light" [fullscreen]="true">...`

**Comment by amandaesmith3** [comment]
Thanks for the issue. Could you try this with the latest version of Ionic, and add an `ionPage` prop to the nested router outlets as described [here](https://github.com/ionic-team/ionic-framework/issues/20219#issuecomment-648469645)?

I noticed that you're using a fork of the nested router outlets example from [the docs](https://ionicframework.com/docs/react/navigation#live-example). Assuming the fix from https://github.com/ionic-team/ionic-framework/issues/20219 works here, we should update the docs accordingly, including the inline code examples (which are currently missing the `ionPage` prop). I'll get things organized once we've confirmed the `ionPage` fix still works.
