### ISSUE TITLE
bug: can't access child process 

### ISSUE THREAD

**Issue by axk2** [ionic-team/ionic-framework#24552]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I've tried to access child process from node js, but i can't.

I've seen the docs but i can't find a way to access to it, i want to run commands and run native code

### Expected Behavior

I would like to access to the terminal with child process from node js.

I don't know if there is a wat to access to the main process

### Steps to Reproduce

Just can't import from the library

const { spawn } = require('child_process')
const ls = spawn('ls', ['-lh', '/usr'])

ls.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`)
})

**Comment by sean-perkins** [comment]
@axk2 can you please let me know how your issue relates to Ionic web components?

**Comment by axk2** [comment]
Because i am using ionic framework, my dependencies are:

@ionic/core
Ionicons
Next
React
React-dom

Nothing else.

I want to use a button to run a cmd script, and i need to access to the main process to use child process and run cmd commands.

**Comment by sean-perkins** [comment]
> Because i am using ionic framework, my dependencies are:
> 
> @ionic/core Ionicons Next React React-dom
> 
> Nothing else.
> 
> I want to use a button to run a cmd script, and i need to access to the main process to use child process and run cmd commands.

This does not appear to be an issue of Ionic Framework, but more of a support question on an implementation. 

You can post your question on any of the community links available in the [README](https://github.com/ionic-team/ionic-framework#--quickstart----------documentation--------contribute------blog----community---discord------forums------twitter) or StackOverflow. 

Thanks!
