### ISSUE TITLE
bug: `ion-toast` prevents focusing `ion-input` while visible

### ISSUE THREAD

**Issue by papagei-ma** [ionic-team/ionic-framework#24571]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When a toast is being displayed the input elements (type='text', because checkboxes, selects and buttons work properly) are not working. I checked that they are not disabled, but somehow the click event is not captured. The element keep working programmatically properly, as I set a timer and changed the value of the bound variable every second, and the value gets emitted to the element. But no user interactivity is available 

### Expected Behavior

One can type in the input element

### Steps to Reproduce

1. Have an ion-input or an html input type='text' on your page.
2. Create a toast for a reasonable amount of time maybe 5 seconds, through 
` const toast = await this.toastController.create({
      message: 'Your settings have been saved.',
      duration: 2000
    });
    toast.present();`
3. While the toast is showing, try to type anything in the input element.

### Code Reproduction URL

https://github.com/papagei-ma/ion-toast-v6

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.2
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

### Additional Information

Checked on Chrome and safari, bug appears on both.

**Comment by sean-perkins** [comment]
Thanks for reporting this! 

On an initial look, it looks like the keyboard focus trap we use for overlays is being applied to toasts (when it shouldn't).

**Comment by papagei-ma** [comment]
@sean-perkins thanks for the quick reply, do you mean you introduced it just recently, because I know for sure, It was working just fine, before v6
