### ISSUE TITLE
bug: HTMLIonInfiniteScrollElement is not defined: no undef by eslint

### ISSUE THREAD

**Issue by nightost** [ionic-team/ionic-framework#24576]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

related to issue [22925](https://github.com/ionic-team/ionic-framework/issues/22925)

when i wrote this:
```
interface InfiniteScrollEvent extends CustomEvent {
  target: HTMLIonInfiniteScrollElement;
}
```
eslint came out 
```
HTMLIonInfiniteScrollElement is not defined: no undef
```

### Expected Behavior

import type  HTMLIonInfiniteScrollElement from somewhere

### Steps to Reproduce

wrote
```
interface InfiniteScrollEvent extends CustomEvent {
  target: HTMLIonInfiniteScrollElement;
}
```

**Comment by amandaesmith3** [comment]
Thanks for the issue. Could you run `ionic info` in your project directory and paste the output here?

**Comment by nightost** [comment]
> 

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
ERROR in
E:\mrs-app\src\views\Home.vue
  94:23  error  'HTMLIonInfiniteScrollElement' is not defined  no-undef
  96:25  error  'HTMLIonInfiniteScrollElement' is not defined  no-undef

**Comment by nightost** [comment]
> Thanks for the issue. Could you run `ionic info` in your project directory and paste the output here?

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\proaim\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\proaim\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\proaim\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\proaim\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\proaim\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic7ue 6.0.2

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.15.1 (D:\Program Files\nodejs\node.exe)
   npm    : 6.14.9
   OS     : Windows 10

**Comment by amandaesmith3** [comment]
Thanks! Can you try using the existing `InfiniteScrollCustomEvent` type instead of creating a new `InfiniteScrollEvent` interface?
```
import { InfiniteScrollCustomEvent } from '@ionic/vue'
```

**Comment by nightost** [comment]
> Thanks! Can you try using the existing `InfiniteScrollCustomEvent` type instead of creating a new `InfiniteScrollEvent` interface?
> 
> ```
> import { InfiniteScrollCustomEvent } from '@ionic/vue'
> ```

tks, it works.
This issue can be closed.

**Comment by amandaesmith3** [comment]
Awesome, glad it worked. I'll go ahead and close this issue. Thanks for using Ionic!
