### ISSUE TITLE
bug: Gesture, GestureController in @ionic/angular not working.

### ISSUE THREAD

**Issue by manikandan-bambus** [ionic-team/ionic-framework#24589]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When we create and assign/enable Gesture to a Element in HTML file by accessing its nativeElement property, the created Gesture must work.

### Expected Behavior

There is no error of wrong implementation and there is no response for swipe Gesture created (Onmove).

### Steps to Reproduce

1. Create a ionic angular project.
2. Add a ionic-content element in home.page.html. Add a reference. 
3. Refer the element in home.page.ts file using @viewChild.
4. Create a Gesture using the Steps you provided in **https://ionicframework.com/docs/utilities/gestures**.
5.  Simulate in browser using "**ionic serve**" or run in real device using "**ionic cap run android -l --external**".
6. Swipe inside the page and get whats going on.

### Ionic Info

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.3
   @angular-devkit/build-angular : 12.2.14
   @angular-devkit/schematics    : 12.2.14
   @angular/cli                  : 12.2.14
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.2
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, android 9.1.0, browser
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   Android SDK Tools : 26.1.1 (/home/bambus/Android/Sdk)
   NodeJS            : v16.13.0 (/usr/local/bin/node)
   npm               : 8.1.0
   OS                : Linux 5.11

### Additional Information

Currently I am using basic addEventListener for the functionality temporarily. Its better if you fix it in angular environment. **Your documentation has so many mistakes**. Look after and solve it.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
