### ISSUE TITLE
bug: routerlink with null throws error in angular 13

### ISSUE THREAD

**Issue by marcovmun** [ionic-team/ionic-framework#24586]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

If I use routerLink with value null, I get console error.
```
<ion-item [routerLink]="null"></ion-item>
``` 

**Error**
```
core.mjs:6449 
        
       ERROR TypeError: Cannot read properties of null (reading 'root')
    at DefaultUrlSerializer.serialize (router.mjs:878:51)
    at Router.serializeUrl (router.mjs:4757:35)
    at RouterLinkDelegateDirective.updateTargetUrlAndHref (ionic-angular.js:3764:79)
    at RouterLinkDelegateDirective.ngOnInit (ionic-angular.js:3752:14)
    at callHook (core.mjs:2518:1)
    at callHooks (core.mjs:2487:1)
    at executeInitAndCheckHooks (core.mjs:2438:1)
    at selectIndexInternal (core.mjs:8368:1)
    at ɵɵadvance (core.mjs:8351:1)
```

I think it has something to do with:
> You can now disable the navigation of a routerLink by passing undefined and null. Previously the routerLink directive used to accept these two values as equivalent to an empty string.

https://update.angular.io/?l=3&v=12.0-13.0

### Expected Behavior

No error is visible in console and routerlink is disabled.

### Steps to Reproduce

1. Use Ionic 5.0.2 and angular 13
2. add view with [routerLink]="null" in an element
3. Run project and look in console.

**Comment by sean-perkins** [comment]
@marcovmun thanks for reporting this. I don't believe we've updated our internal `RouterLinkDelegate` to support that new feature change in v13 of Angular. 

I'll need to look into all aspects of what assigning `null` to the routerLink includes, so that we have alignment with the expected implementation.
