### ISSUE TITLE
feat: Bottom Sheet initial minHeight in pixel

### ISSUE THREAD

**Issue by davideas** [ionic-team/ionic-framework#24582]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

minHeight in pixel for initial opening.

### Describe the Use Case

Display header content that fits in all screen sizes.
By choosing a % for initial breakpoint this is not a valid value for all screens.
The header content should't be cut as it is now on smaller screens caused by initial % of breakpoint.

**Comment by sean-perkins** [comment]
Hello & thanks for the feature request!

Can you elaborate on this point:
> By choosing a % for initial breakpoint this is not a valid value for all screens.

The breakpoints are relative to the modal height, not the screen height. So the calculation of % should be the same regardless of the screen.

**Comment by davideas** [comment]
> The breakpoints are relative to the modal height, not the screen height. So the calculation of % should be the same regardless of the screen.

Ah ok, i did a new test, that confirms what you say. It wasn't clear before. Thanks.
That problem was caused by a non refresh in the browser when switching layout/phone.
