### ISSUE TITLE
bug: inputs above sheet modals cannot be focused

### ISSUE THREAD

**Issue by twittwer** [ionic-team/ionic-framework#24581]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Inputs in the visible area above a sheet modal cannot be used because of the modal's focus trap.

### Expected Behavior

The really nice new Sheet Modal provides the option to keep the not blocked part of the app interactive as described in the docs "This is useful when creating interfaces that have content underneath the sheet that should remain interactive.".
In this context, it should be possible to focus input elements outside the modal to ensure the real interactivity of the page.

### Steps to Reproduce

1. Go to the linked [stackblitz](https://stackblitz.com/edit/angular-ivy-itpjej)
2. Type in the searchbar 🟢 
3. Open the sheet modal
4. Try to type in the searchbar 🔴 

### Code Reproduction URL

https://stackblitz.com/edit/angular-ivy-itpjej

### Additional Information

The use case is a google maps like experience with a sheet modal and a searchbar at the top of the page:
![image](https://user-images.githubusercontent.com/8677948/149599020-338d4b7d-ea79-4806-a3cc-8c60cc7d80e2.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.0.9-dev.1645638296.7251a13
```

**Comment by twittwer** [comment]
Thx for working on it 👍 
I've forked the Stackblitz for the updated version: https://stackblitz.com/edit/angular-ivy-vpsppv
But the behaviour has not changed 😕

**Comment by liamdebeasi** [comment]
Can you try testing in a non-StackBlitz application? I had to download and run the project locally in order for the dev build to be installed correctly.

The issue still happens on the StackBlitz but does not happen on the local project.

**Comment by twittwer** [comment]
ok, will try it locally this evening

**Comment by twittwer** [comment]
Nice, it works 👍 
Thx for the fix 😃

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24840, and a fix will be available in an upcoming release of Ionic Framework. Thanks for testing!
