### ISSUE TITLE
bug: ion-back-button used in ion-nav child components outside of a modal will navigate to the previous page

### ISSUE THREAD

**Issue by nvahalik** [ionic-team/ionic-framework#24591]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

We are using `ion-nav` in two different locations within our application.

One is within a modal and the other is within a page.

Within the modal, the `ion-back-button` components works as expected: it allows one to go back into the stack of pushed components without issue.

However, we recently added a navigation page which is just a regular ionic page. Implemented the `ion-nav` in exactly the same way (copied and pasted the code, mostly).

However, when using `ion-back-button` on these pages, it always navigates back to the original page.

For example:

```
DashboardPage
DashboardPage -(navigate)-> Settings Page
DashboardPage -(navigate)-> Settings Page -> -(ion-nav.push())-> SettingChooserComponent
```

at this point, when tapping the back button on the setting chooser component I would expect the navigation to be:

```
DashboardPage -(navigate)-> Settings Page
```

However, I end up going back to `DashboardPage` instead.

### Expected Behavior

I expect it actually go back to previous item that is on the `ion-nav` stack.

### Steps to Reproduce

Create a `Page` with an `ion-nav` and two components. The last component should have an `ion-back-button`.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.3
   @angular-devkit/build-angular : 12.2.10
   @angular-devkit/schematics    : 12.2.10
   @angular/cli                  : 12.2.10
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 26 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.2
   native-run (update available: 1.5.0)   : 0.2.8

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v14.17.3 (/usr/local/Cellar/node@14/14.17.3/bin/node)
   npm        : 6.14.13
   OS         : macOS Big Sur
   Xcode      : Xcode 13.2.1 Build version 13C100

### Additional Information

Adding

`private nav: IonNav` in each component and then not using `ion-back-button` but instead using `this.nav.pop()` works as a workaround.

**Comment by nvahalik** [comment]
I will just note that there doesn't appear to be anything in the documentation which says that `ion-nav` can only be used in modals. A lot of the literature does use modals as examples, but nothing seems to explicitly say you cannot use them in regular pages.

**Comment by amandaesmith3** [comment]
Thanks for the issue. Could you create a starter app showing the issue and post a link here? This will help not only with reproducing the issue, but also verifying it's fixed down the road.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
