### ISSUE TITLE
bug: upstream dependency conflict with ionic angular server

### ISSUE THREAD

**Issue by samizarraa** [ionic-team/ionic-framework#24592]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ionic-test@2.0.0
npm ERR! Found: @ionic/angular@6.0.2
npm ERR! node_modules/@ionic/angular
npm ERR!   @ionic/angular@"^6.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @ionic/angular@"6.0.0" from @ionic/angular-server@6.0.2
npm ERR! node_modules/@ionic/angular-server
npm ERR!   @ionic/angular-server@"*" from the root project

### Expected Behavior

Just try to install ionic angular server on fresh ionic app
ionic 6.0.2

### Steps to Reproduce

npm i @ionic/angular-server

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24593, and a fix will be available in an upcoming release of Ionic Framework.
