### ISSUE TITLE
bug: Android build using Vue is missing styles and odd CSS behaviour

### ISSUE THREAD

**Issue by VizuaaLOG** [ionic-team/ionic-framework#24612]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Running an Ionic Vue project in a web browser, even on mobile, shows everything as expected. However, when building for Android using `ionic capacitor run android` on an emulator or physical device some CSS properties do not appear to work and also components like `ion-input`, `ion-note` and `ion-label` have completely lost their functionality and styling.

Inputs can have text typed into them but the floating label / bottom border highlight does not work.

The two images below show the issue happening in my project, the first is the CSS gap property not having any effect, but being listed in the dev tools. The second shows the ion-input, ion-label and ion-note components losing all of their styling. Left is in a browser on my PC and the right is running inside the Android emulator.

![example-gap-css-property](https://user-images.githubusercontent.com/4404472/150402413-32735092-b424-4bd5-98c9-fbaa2f54744c.png)
![example-inout](https://user-images.githubusercontent.com/4404472/150402420-612f5c4e-2196-4238-99f1-341cc5284570.png)

This screenshot is the same process but using a brand new Ionic 6 project and copying in the ion-input example source.
![example-ionic-docs](https://user-images.githubusercontent.com/4404472/150403451-b515d713-c073-4087-9a2a-2a9d592f119d.jpg)

### Expected Behavior

I would expect the output of the build to mimic the functionality shown inside a browser, especially the mobile browser. Even where some CSS properties might not be supported by the WK browser used in Capacitor I would expect the Ionic components to still behave as they do in the browser.

### Steps to Reproduce

1. Use the Ionic Getting Started wizard to setup a Ionic Vue project
2. Edit the Ionic Vue project replacing the Tab1Page.vue file's content with the ion-input content available on https://github.com/ionic-team/ionic-docs/blob/main/static/demos/api/input/index.html (importing any Vue components as needed)
3. Run `ionic serve` to see how the project should look, basically matches the demo shown on the docs
4. Run `ionic capacitor run android` and see the inputs lose their functionality / styling

### Code Reproduction URL

https://github.com/VizuaaLOG/ionic-v6-test-input

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\vizua\AppData\Roaming\nvm\v14.18.1\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\vizua\AppData\Roaming\nvm\v14.18.1\node_modules\@ionic\cli\lib\index.js
       - C:\Users\vizua\AppData\Roaming\nvm\v14.18.1\node_modules\@ionic\cli\index.js
       - C:\Users\vizua\AppData\Roaming\nvm\v14.18.1\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\vizua\AppData\Roaming\nvm\v14.18.1\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.0.2

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.18.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.15
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. What version of the Android webview are you using when you run your app? You can find this out by logging `window.navigator.userAgent` when inspecting your app with Chrome Dev Tools.

**Comment by VizuaaLOG** [comment]
Hey @liamdebeasi ,

The output of `window.navigator.userAgent` is `'Mozilla/5.0 (Linux; Android 11; sdk_gphone_x86_64_arm64 Build/RSR1.201211.001.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36'`

This is running in the emulator on Android 11 API 30

**Comment by liamdebeasi** [comment]
Thanks! Have you noticed any of your own custom styles go missing too? Or is it just with Ionic's built in styles?

**Comment by VizuaaLOG** [comment]
I haven't noticed any custom styles go missing. The only weird one I've seen is a gap utility class that applies `gap: 0.75rem` doesn't seem to apply but I do still see it in the debugger.

I would assume that is browser support issue but assuming it's running inside a WK browser it seems odd, especially when using the browser in the emulator it looks fine.

**Comment by liamdebeasi** [comment]
It looks like you forgot to import `IonItem` in `Tab1Page.vue`, causing all of the code for `IonItem` to be removed from your bundle by the compiler. Can you try importing `IonItem` and providing it to the `component` object and see if that fixes the issue?

**Comment by VizuaaLOG** [comment]
I don't know how I missed that in both my project and the example one 🤦 . It works fine after including `IonItem`.

I am surprised it works okay in the browser and doesn't throw any Vue or complier errors though.

Thank you for looking into it 👍

**Comment by liamdebeasi** [comment]
Glad the issue is fixed! In the browser, Vue only logs a warning not an error. If you open up the console you should see a warning that looks something like this:

```
[Vue warn]: Failed to resolve component: ion-item
```

**Comment by VizuaaLOG** [comment]
Yeah I didn't remember seeing it but entirely possible I missed it, I missed the include after all 😅 .

Thanks again for your help!
