### ISSUE TITLE
bug: IonLabel in position = "stacked" and in Right-To-Left direction Problem

### ISSUE THREAD

**Issue by OHELLEL** [ionic-team/ionic-framework#24629]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Ion Label is not aligned to the right....and it doesn't span the full width...

### Expected Behavior

I should span the full width.

### Steps to Reproduce

1. set dir attribute in the body tag to 'rtl'
2. add IonItem and IonInput inside it and IonLabel with position = 'stacked'
3  ionic serve

**Comment by sean-perkins** [comment]
Hello @OHELLEL thanks for opening an issue.

You will need to set the `dir` on the HTML element:
```html
<html dir="rtl">
  ...
</html>
```

RTL support for the Ionic UI components looks at the root document's direction or if the `dir` attribute is directly assigned to the element tag. 

|Body|HTML|
|---|---|
|`<body dir="rtl">`|`<html dir="rtl">`|
|<img src="https://user-images.githubusercontent.com/13732623/150862948-00ae3b56-bf77-4684-8991-128a88830882.png" />| <img src="https://user-images.githubusercontent.com/13732623/150862829-b235f5c4-3f46-4ac5-8be4-365c32740e07.png" /> |

Let me know if this resolves your issue.

**Comment by OHELLEL** [comment]
thank you, that was the problem.
