### ISSUE TITLE
bug: popover arrow on desktop does not display

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-framework#24624]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Until Ionic v6, popover with mode set to `iOS` were presented with an `arrow` regardless of the device i.e. arrows were displayed for popover even on desktop.

Ionic v6 breaks this behavior and do not display arrows on desktop anymore and thus in any case i.e even if the `@Prop() arrow` is set to true (see [code](https://github.com/ionic-team/ionic-framework/blob/43c5977d48cb12331c1d3107eb73f29b92c5e049/core/src/components/popover/popover.tsx#L570)).

This changes may have been introduced in PR [#23258](https://github.com/ionic-team/ionic-framework/pull/23258).

### Expected Behavior

As in Ionic v5 and previous versions, being able to present popover on desktop with an `arrow`

### Steps to Reproduce

Ionic sample app, open popover with `arrow` to true or/and `mode=ios` on desktop.

**Comment by sean-perkins** [comment]
Thanks for reporting this issue @peterpeterparker!

This decision was made to alleviate some design flaws in the desktop implementation and work around a breaking change of changing the default value of `arrow` on popover. 

Discussing with the team, we don't think that was the best solution. 

We'll track this as a bug & regression from v5 behavior, likely removing the opinionation for desktop platform and requiring implementations to manually set that flag based on their design patterns. 

We'll share an update when we have a decision. Thanks 👍

**Comment by peterpeterparker** [comment]
Thanks for the feedback @sean-perkins

**Comment by jansgescheit** [comment]
We missing the arrow on desktop too. We use the popover as a tooltip and it is an important orientation aid on the screen.

**Comment by amandaesmith3** [comment]
This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25056 and the fix will be available in a future release of Ionic 👍
