### ISSUE TITLE
bug: Toast impacts the display of other elements

### ISSUE THREAD

**Issue by titib** [ionic-team/ionic-framework#24628]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

While the display of a toast trigger is presented, the display of the button above it goes to the top (=> "Hello at the top")

### Expected Behavior

Nothing should be displayed at the top of the page (no "Hello at the top")

### Steps to Reproduce

- Create a blank React app with ionic start
- in the Home component(Home.tsx), add an IonFooter after the IonContent : 
`<IonFooter>
        <IonToolbar>
          <IonItem>
            <IonLabel>Cocuuo</IonLabel>
          </IonItem>
          <IonButton
            expand="full"
            fill="clear"
            onClick={() => presentToast("test Hello", 2000)}
          >
            Hello at the top
          </IonButton>
          <IonButton
            expand="full"
            fill="clear"
            onClick={() => presentToast("test Ckick", 2000)}
          >
            click
          </IonButton>
        </IonToolbar>
      </IonFooter>`

- ionic serve
- click on the button "CLICK"

### Code Reproduction URL

https://gitlab.com/thbanh/bug-ionic-toast

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/home/thierry/.nvm/versions/node/v14.17.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.17.0 (/home/thierry/.nvm/versions/node/v14.17.0/bin/node)
   npm    : 8.3.0
   OS     : Linux 5.15

**Comment by amandaesmith3** [comment]
Thanks for the issue. I tried your linked repo, but when I click on "CLICK," the toast seems to show as normal. Could you post a screencast to help me better understand the issue?

**Comment by titib** [comment]
> Thanks for the issue. I tried your linked repo, but when I click on "CLICK," the toast seems to show as normal. Could you post a screencast to help me better understand the issue?

Actually, you can see the toast as epected but the display of the toast shifts the display of " "Hello at the top" to the top.

**Comment by titib** [comment]
The screencast is there : [ionic-toast-bug](https://adeducation-my.sharepoint.com/:v:/g/personal/thierry_banh_mail-ecv_fr/EWL3mhE5Dl5BgQ_4NPrZoSkBbK-5qkTdBYtbH4lks6K3UA?e=ZyPaRu)

**Comment by amandaesmith3** [comment]
Thank you for the screencast. Is that Chrome you're testing on? What version of Chrome is it? I am unable to replicate the issue on Chrome 97.0.4692.71; here's what I see: https://user-images.githubusercontent.com/90629384/151184452-9d5cbc10-493f-4969-8a9f-fadc66556d8c.mp4

**Comment by titib** [comment]
Yes, it's on Chrome.
Chrome version : Version 97.0.4692.99 (Official Build) (64-bit)
OS : linux

**Comment by titib** [comment]
> Thank you for the screencast. Is that Chrome you're testing on? What version of Chrome is it? I am unable to replicate the issue on Chrome 97.0.4692.71; here's what I see: https://user-images.githubusercontent.com/90629384/151184452-9d5cbc10-493f-4969-8a9f-fadc66556d8c.mp4

To reproduce, maybe, you should switch to the mobile view (I chose Pixel 4)

**Comment by amandaesmith3** [comment]
Can I ask what Linux distro and version you're using?

**Comment by titib** [comment]
Pop OS 21.10

**Comment by amandaesmith3** [comment]
I've met internally with the team, and so far we've been unable to reproduce the issue. Collectively, we've tried:
- Windows
- Mac
- Pop OS 21.04 and 21.10
- Ubuntu 18

... all running Chrome 97, and at various mobile view sizes. So far, it's seeming like this is either a Chrome bug, or an issue with that particular machine, rather than something Ionic is doing. Here are a few things you can try:
- Try and replicate on a different browser
- Try and replicate on a different machine entirely
- Make sure your graphics drivers are up to date

Could you give these a go, and let me know your findings?
