### ISSUE TITLE
bug: Card/Sheet modal dismiss - route navigation Issue

### ISSUE THREAD

**Issue by pgmoftexas** [ionic-team/ionic-framework#24625]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Upon presenting a Card or Sheet modal with a nested Card or Sheet modal, upon dismissal, router navigate would bug out. It would update the router url but it would not actually render the page and route completely.

### Expected Behavior

Expectations would be able to dismiss nested Card or Sheet modal and parent Card or Sheet modal and still be able to router navigate as usual and render the routed page.

### Steps to Reproduce

- Setup blank page with 2 pages. Login & home for example.
- Create button on Login that on press router navigates to home.
- Do a modal card popup on login page, which contains a nested modal card inside the 1st modal card popup.
- Dismiss both modal cards and the press the button on login that should route your to home.
(this seemed to apply on nested modals of cards or sheets)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.0 (C:\Users\Blah\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.3
   @angular-devkit/build-angular : 13.1.4
   @angular-devkit/schematics    : 13.1.4
   @angular/cli                  : 13.1.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.0
   OS     : Windows 10

### Additional Information

Traditionally when presenting a modal, it has been normal in the past to always set the following:

`presentingElement: await this.modalController.getTop()`

When you setup Card or Sheet, you must actually change it and do it this way to get the expected effects:

`presentingElement: this.routerOutlet.nativeEl`

To prevent the issue when for example calling component 1 Card, then calling a component 2 Card or Sheet inside component 1, upon dismissal all modals and performing a router navigate, it will not work.
To fix this, component 1 Modal Card or Sheet will always be routerOutlet.nativeEl and then any following nested Card or Sheet modals will be modalController.getTop() or whatever modalController.xxxx (3 total options here).

Proper example code:

component 1:

```
const modal = await this.modalController.create({

      component: MainComponent,

      componentProps: { blah: this.blah},

      swipeToClose: false,

      presentingElement: this.routerOutlet.nativeEl,

    });
```

component 2 inside component 1:

```
const modal = await this.modalController.create({

      component: ChildComponent,

      componentProps: { blahblah: this.blahblah },

      swipeToClose: true,

      presentingElement: await this.modalController.getTop()

    });
```

**Comment by pmarkoulidakis** [comment]
Here is an example https://github.com/pmarkoulidakis/bug24583 
When modal is dismissed, you can no longer swipe the menu.

**Comment by pgmoftexas** [comment]
> Here is an example https://github.com/pmarkoulidakis/bug24583 
> 
> When modal is dismissed, you can no longer swipe the menu.

Thank you for making an example. Been meaning to make one but have not had free time to. I am getting a 404 no page found on your link. Unsure if you made it private on accident or if it is just not available to view yet.

**Comment by pmarkoulidakis** [comment]
private...

**Comment by pmarkoulidakis** [comment]
This bug is also reported on is[23979](https://github.com/ionic-team/ionic-framework/issues/23979) sue

**Comment by pgmoftexas** [comment]
I also discovered that if you do multiple card modals stacked on top of each other and dismiss 1, reopen it again, it automatically dismisses its parent. Super annoying unless I am doing something wrong but I strictly followed documentation. I stopped using child modal cards. Only using 1 parent modal card.

**Comment by sean-perkins** [comment]
@pmarkoulidakis your reproduction app appears to cover different behavior than the reported issue. Please open a new issue with your specific issue (menu swipe is disabled after dismissing a modal).

@pgmoftexas without a reproduction app on your use case, I'm unable to debug further. Can you please provide a reproduction app or close this issue if it's no longer applicable? Thanks!

**Comment by pgmoftexas** [comment]
I never made a reproduction application. Thanks.

**Comment by sean-perkins** [comment]
@pgmoftexas I have tested the other reproduction app provided in this thread, but it does not replicate the issue you have described in your original post ([comment](https://github.com/ionic-team/ionic-framework/issues/24625#issuecomment-1031799153))

No one is requiring you to provide a reproduction. If you are unwilling or unable to provide one for the issue, I will be closing this issue out; as I cannot replicate the behavior describe in your original report. 

Feel free to comment a reproduction and I will be more than happy to re-open this issue and diagnose the issue you are facing. Thank you.
