### ISSUE TITLE
feat: use ion-tab-bar outside ion-tabs

### ISSUE THREAD

**Issue by SmallhillCZ** [ionic-team/ionic-framework#24637]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Allow for using `ion-tab-bar` outside of `ion-tabs` as a pure UI element (no routing features included).

Using ion-tab-bar is not supported outside of ion tabs and will lead to an error: https://github.com/ionic-team/ionic-framework/issues/21882#issuecomment-669938114

### Describe the Use Case

`ion-tabs` is defined as a **top-level** navigation element. The use case would be to use it in other scenarios, either nested routing or non routing tab components.

Using it in nested routing now causes history issues (e.g. back button ignores parent router history https://github.com/ionic-team/ionic-framework/issues/18759) and outside `ion-tabs` it stops working after first click (https://github.com/ionic-team/ionic-framework/issues/21882).

### Describe Preferred Solution

Fix clicking ion-tab-buttons when not in ion tabs (https://github.com/ionic-team/ionic-framework/issues/21882).

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am not sure I fully understand this request. `ion-tab-bar` should already be usable outside of `ion-tabs`. Is there an error you are running into when trying to do this? A code sample would help here.
