### ISSUE TITLE
feat: Create method to close all active dialogs and/or alerts

### ISSUE THREAD

**Issue by ndrakulic91** [ionic-team/ionic-framework#24630]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently ModalController and AlertController are able to dismiss one modal at the time. In case of stacked modals/alerts, closing all active ones is not possible unless we keep track of those that are shown.

It would be very helpful if there would be a dismissAll() method which would close all active modals for ModalController or alerts for AlertController.

### Describe the Use Case

A practical example is when user gets automatically logged out, all activr overlays should be closed. In case of stacked overlays it's impossible unless those are closed one by one using dismiss() method.

**Comment by amandaesmith3** [comment]
Thanks for the issue. Overlays can also be dismissed by calling `dismiss()` on the element itself. Could you try the below snippet and let me know if it solves your use case?
```tsx
import { HTMLIonOverlayElement } from '@ionic/core';

const closeAll = () => {
  // adjust selector to fit your needs
  const overlays = document.querySelectorAll('ion-alert, ion-action-sheet, ion-loading, ion-modal, ion-picker, ion-popover, ion-toast');
  const overlaysArr = Array.from(overlays) as HTMLIonOverlayElement[];
  overlaysArr.forEach(o => o.dismiss());
};
```
