### ISSUE TITLE
bug: ion-item horizontal scrolling inside angular virtual scroll

### ISSUE THREAD

**Issue by Spinnenzunge** [ionic-team/ionic-framework#24632]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

When migrating ion-virtual-scroll to angular scrolling module according to https://ionicframework.com/docs/angular/virtual-scroll the ion-item gets a horizontal scroll bar as soon as a text inside the item gets too large.

### Expected Behavior

The text should abbreviate with ellipses and wrap inside the ion-item as it does in an item without the angular virtual scroll module.

### Steps to Reproduce

- Create a new starter app
- Follow the migration guide https://ionicframework.com/docs/angular/virtual-scroll
- Add an item with a slotted icon, label and note
- Add a long text inside the ion-label

### Code Reproduction URL

https://github.com/DaniLopes2003/VirtualScroll-DemoApp

### Ionic Info
```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/pascalgraf/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.3
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   ios-deploy : 1.11.3
   NodeJS     : v14.17.6 (/Users/pascalgraf/.nvm/versions/node/v14.17.6/bin/node)
   npm        : 7.23.0
   OS         : macOS Big Sur
   Xcode      : Xcode 13.2.1 Build version 13C100
```

**Comment by Spinnenzunge** [comment]
hi @liamdebeasi
yes that is our fix at the moment as well. But I am not perfectly happy with that solution because it only really works when the list is not inside a container that has any spacing set. Otherwise we would have to start calculating the width.

Maybe that could be something to redirect to the angular team?

**Comment by liamdebeasi** [comment]
Yeah in this case I recommend filing an issue with the Angular team here: https://github.com/angular/components Does that work for you?

**Comment by Spinnenzunge** [comment]
Sure, that works for me, I submitted a new issue over there https://github.com/angular/components/issues/24277
