### ISSUE TITLE
bug: active ion-input hidden behind virtual keyboard in mobile Safari

### ISSUE THREAD

**Issue by mezoistvan** [ionic-team/ionic-framework#24647]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

1) On mobile Safari, `ion-input`s are not scrolled into view when virtual keyboard opens. `ion-input`s can get stuck behind the virtual keyboard.
2) On mobile Safari with the virtual keyboard open, there is some empty space under the content. This is also visible in the video.

https://user-images.githubusercontent.com/11316929/150961478-c852e9f2-d000-4128-af10-cbce019078ff.mov

### Expected Behavior

1) Focused inputs should be visible above the keyboard on mobile browsers.
2) There should not be an empty space under the content when the virtual keyboard is open.

### Steps to Reproduce

Use the `conference` ionic starter app. 
Use the latest iOS.
Try to enter a password on the login form. 

To make this bug more visible, the password input was moved more towards to the bottom of the page in the video. This code is available at the code reproduction url.

### Code Reproduction URL

https://github.com/mezoistvan/ionic-safari-issue

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (/Users/mezoistvan/.nvm/versions/node/v14.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.0-rc.2
   @angular-devkit/build-angular : 13.0.1
   @angular-devkit/schematics    : 13.0.1
   @angular/cli                  : 13.0.1
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   Android SDK Tools : 26.1.1 (/Users/mezoistvan/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v14.18.1 (/Users/mezoistvan/.nvm/versions/node/v14.18.1/bin/node)
   npm               : 8.1.1
   OS                : macOS Big Sur
   Xcode             : Xcode 13.1 Build version 13A1030d

### Additional Information

Thanks for your hard work, ionic rocks! 😎

**Comment by liamdebeasi** [comment]
Thanks for the issue. This appears to be related to https://github.com/ionic-team/ionic-framework/issues/23664, so I am going to consolidate the two.
