### ISSUE TITLE
bug: focus trap prevents focus from moving to overlays that do not use focus trapping

### ISSUE THREAD

**Issue by soroush-gh** [ionic-team/ionic-framework#24646]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I can not focus on search bar input for the "ngx-mat-select-search" or all inputs that they are using to add features such as add link in the MCE Editor when I am using them (mat-select / MCE-Editor) in the ionic-modal.

I thought it was for z-index conflicting and try different ways to solve it but I could not!

![image](https://user-images.githubusercontent.com/88440348/150868558-d275eecc-7342-48ef-907b-eb497ab5b6fd.png)

### Expected Behavior

The end-user should be type anything in the inputs that I explained on the top.

### Steps to Reproduce

.

**Comment by JeramieHallyburton** [comment]
I have created a simple reproduction of this issue. It appears if an ion-segment exists in the modal, any nested modal inputs cannot grab focus.

**Stackblitz of ion-modal with an ion-segment present and tinyMCE editor**
https://stackblitz.com/edit/modal-with-segment?file=src/app/app.component.html

1. Click Insert > Link
2. Observe the text inputs cannot gain focus

**Stackblitz of ion-modal without an ion-segment present and tinyMCE editor**
https://stackblitz.com/edit/modal-without-segment?file=src/app/app.component.html

1. Click Insert > Link
2. Observe you can focus and type into text inputs

**Comment by kalozoya-gregal** [comment]
I have the same problem with ngx-mat-select-search inside modal.

I have made an example where outside modal the input search of select works, but inside modal i can't search select values.

[https://stackblitz.com/edit/modal-without-segment-rhkczi?file=src/app/app.component.html](https://stackblitz.com/edit/modal-without-segment-rhkczi?file=src/app/app.component.html)

**Comment by liamdebeasi** [comment]
This appears to be an issue with focus trapping. When you present `ion-modal`, we prevent focus from leaving the modal for better accessibility. However, the tinyMCE editor is presented at the root of the app outside of the `ion-modal`. As a result, when you try to focus an input in the editor, `ion-modal` brings focus back to the first focusable element. In this case, that is the segment button.

**Comment by stuartpaulin** [comment]
I believe this is the same issue when I tried to paste text into an ion-textarea in a modal I could not get it to focus or extract caret / selection information.  Same when trying to  use a ngx-quill component.  It will not focus, so can't insert text into it.

**Comment by NeluQi** [comment]
is there a hack for this?

**Comment by inexuscore** [comment]
> This appears to be an issue with focus trapping. When you present `ion-modal`, we prevent focus from leaving the modal for better accessibility. However, the tinyMCE editor is presented at the root of the app outside of the `ion-modal`. As a result, when you try to focus an input in the editor, `ion-modal` brings focus back to the first focusable element. In this case, that is the segment button.

Is there a workaround to this issue? I'm using TinyMCE in an Ionic 7 project, the plugin dialogs (e.g. the TinyMCE Link Plugin) work fine on ionic pages, but not when I use an editor inside an ion-modal. Focus trapping! None of the input elements are focusable. Any ideas how I can get around this?

**Comment by soroush-gh** [comment]
> > This appears to be an issue with focus trapping. When you present `ion-modal`, we prevent focus from leaving the modal for better accessibility. However, the tinyMCE editor is presented at the root of the app outside of the `ion-modal`. As a result, when you try to focus an input in the editor, `ion-modal` brings focus back to the first focusable element. In this case, that is the segment button.
> 
> Is there a workaround to this issue? I'm using TinyMCE in an Ionic 7 project, the plugin dialogs (e.g. the TinyMCE Link Plugin) work fine on ionic pages, but not when I use an editor inside an ion-modal. Focus trapping! None of the input elements are focusable. Any ideas how I can get around this?

Use this CSS class `ion-disable-focus-trap` on creating ion-modal
![image](https://user-images.githubusercontent.com/88440348/236819612-da638cfe-9803-44b3-bac0-bc9bc68a03f4.png)

**Comment by hatsantos** [comment]
Regarding the recent closed issue https://github.com/ionic-team/ionic-framework/issues/29056, is there a recomended way to avoid the focus trap on modal?

**Comment by GerardoTovar** [comment]
Thanks in my case, adding it using cssClass did not work for me, but adding it using an id before opening the modal worked perfectly for me
`<ion-modal id="ionModals"`
`  addClass() {
    document.getElementById('ionModals')?.classList.add('ion-disable-focus-trap')
  }`

**Comment by liamdebeasi** [comment]
Hi everyone,

I have a dev build with a proposed feature to resolve this if anyone is interested in testing: `8.0.0-dev.11712850753.10c4a960`

Note that this is an Ionic 8 dev build and is subject to the [Ionic 8 breaking changes list](https://github.com/ionic-team/ionic-framework/blob/feature-8.0/BREAKING.md#version-8x).

To disable focus trapping, set the `focusTrap` property on either Modal or Popover to `false`. (Defaults to `true`)

**Comment by hatsantos** [comment]
Hi @liamdebeasi I will try to test it latter on.

My project in currently on version 7 so i will have to check what needs to be done to upgrade to version 8.

**Comment by kalozoya-gregal** [comment]
I have tested it with [ngx-mat-select-search](https://www.npmjs.com/package/ngx-mat-select-search) and it is fine.

https://stackblitz.com/edit/angular-4fujbn?file=src%2Fapp%2Fapp.component.html

Thanks.

**Comment by hatsantos** [comment]
I only had the opportunity to test it now.
I changed it from this:

![image](https://github.com/ionic-team/ionic-framework/assets/36542752/6cf7086e-78ab-462b-9a10-f9125a4383a0)

To this:

![image](https://github.com/ionic-team/ionic-framework/assets/36542752/95c9f963-2dab-42e1-ae01-85a27a4a5dd9)

No problems at all. ;)

But taking as an example by just disabling the focus trap when activating a certain component (dropdown) within the modal.
Previously, I used this technique:

```
onOpen(open: any) {
       this.ModalController.getTop().then(modal => modal?.classList.toggle('ion-disable-focus-trap', open));
}
```

Would there be any way to modify the focusTrap prop in this context?

**Comment by liamdebeasi** [comment]
> Would there be any way to modify the focusTrap prop in this context?

In this case you could do something like `modal.focusTrap = true` to re-enable the focus trapping behavior. `model` is a reference to the `ion-modal` element.

Alternatively, you could pass a prop to the modal component that toggles `focusTrap` when invoked.
