### ISSUE TITLE
bug: slow FPS performance of app with WebView 97 keeping it opened more than an hour

### ISSUE THREAD

**Issue by matteocappello94** [ionic-team/ionic-framework#24649]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I notice that my app (an app that record many data from bluetooth LE and use Maps Javascript API to show a map with some markers) with Keep Awake active, when running more than an hour, FPS of gui drop until app is unusable. It work with WebView 97 on Android but not with WebView 96 or 91.

### Expected Behavior

FPS doesn't drop also if app has Keeping Awake active

### Steps to Reproduce

There isn't a step to reproduce this, I post this issue checking if another people occurred in this problem with WebView 97. Thanks.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 7.5.6
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide a reproduction so we can investigate this issue? If you are looking to discuss this issue with other developers instead, the [Ionic Forum](https://forum.ionicframework.com/) may be a better place for this topic.

**Comment by matteocappello94** [comment]
I can't provide a reproduction now. I think I will post this inside the Ionic Forum to discuss it. Thanks
