### ISSUE TITLE
bug: router-outlet getRouteId() should returns the params

### ISSUE THREAD

**Issue by vicb** [ionic-team/ionic-framework#24652]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

`getRouteId()` should [returns the params](https://github.com/ionic-team/ionic-framework/blob/7d5c6afd180b0023de82f621ccab2421e61752ea/core/src/components/router-outlet/route-outlet.tsx#L154-L159) to be consistent with [`ion-nav`](https://github.com/ionic-team/ionic-framework/blob/7d5c6afd180b0023de82f621ccab2421e61752ea/core/src/components/nav/nav.tsx#L436-L444)

It will also enable fixing a bug (I'll create a separate one)

### Expected Behavior

Returns the params passed to `setRouteId()`.

### Steps to Reproduce

Call `getRouteId()` params are nor returned.

I'll create a PR with tests.

**Comment by liamdebeasi** [comment]
Fixed via https://github.com/ionic-team/ionic-framework/pull/24656
