### ISSUE TITLE
bug: classList of undefined, navigating between tabs and no tabs

### ISSUE THREAD

**Issue by jake-newsom** [ionic-team/ionic-framework#24654]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

After navigating between multiple pages within a tabbed view, then navigating to a non-tabbed view, and then navigating back into the tabbed view, the app throws a javascript error "Cannot read property 'classList' of undefined" (which breaks further page processing in our main app) 

### Expected Behavior

There should be no javascript error when navigating from the non-tabbed view back to the tabbed view 

### Steps to Reproduce

- Start the app from scratch
- Click "View Blog" 
- Go back
- Click "View Script" 
- Click "Open New Feature"
- Go back (should result in error) 

### Code Reproduction URL

https://github.com/jake-newsom/ionic-tab-example

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - C:\Users\Jake\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Jake\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Jake\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Jake\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - C:\Users\Jake\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Jake\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Jake\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Jake\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.17.0 (C:\Users\Jake\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 5.9.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.17.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

### Additional Information

Steps that weirdly don't result in the error: 

- Start the app from scratch
- Click "View Script"
- Click "Open New Feature"
- Go back

It only triggers if I view a sibling page within the tabbed view first

**Comment by jake-newsom** [comment]
@liamdebeasi Yes it appears so, I ran
`npm install @ionic/vue@6.0.1 @ionic/vue-router@6.0.1`

Reloaded my VSCode window and restarted ionic serve and can still reproduce the issue.

**Comment by mcpeakdb** [comment]
Hello @liamdebeasi, I work with @jake-newsom and was doing some research on this myself. I believe changing this line in vue/dist/index.esm.js prevents the issue but do not quite understand enough to confidently say it would not cause other problems

line 1054
if (enteringEl === undefined)

if(typeof enteringEl === undefined)

Thanks for looking into this!

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@6.0.5-dev.1643229606.6368b84 @ionic/vue-router@6.0.5-dev.1643229606.6368b84
```

**Comment by jake-newsom** [comment]
Tried it out on the sample project and it resolves the issue!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24665, and a fix will be available in an upcoming release of Ionic Framework.
