### ISSUE TITLE
bug: Unable to run application in Android/Emulator

### ISSUE THREAD

**Issue by luckyycool** [ionic-team/ionic-framework#24676]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When creating a new app using IONIC V6 we are getting error in android devices of 
**```
(index):287 SyntaxError: Unexpected token .
cap.handleError @ (index):287
/vendor.js:27274 Uncaught SyntaxError: Unexpected token .

And the code which is breaking in vendor.js is 

**this._platformLocation.historyGo?.(relativePosition);**
```**

Also if I load www folder (after build) in the browser  it works fine.


### Expected Behavior

App should run smoothly at least with fresh installation.

### Steps to Reproduce

Install IONIC V6 (6.18.1)

- Create new app - ionic start test --project-id=test --package-id=test.freeapp.sample

- Build app - npm run build

- Run in android - ionic capacitor run android




### Code Reproduction URL

https://github.com/luckyycool/ionic-16-not-working-in-android

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.4
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2 (/Users/username/.nvm/versions/node/v16.13.2/bin/node)
   npm    : 7.6.3
   OS     : macOS Mojave

### Additional Information

_No response_

**Comment by luckyycool** [comment]
I have added GitHub repo https://github.com/luckyycool/ionic-16-not-working-in-android though as already mentioned in the ticket it is breaking for all fresh ionic apps created.

**Comment by liamdebeasi** [comment]
Thanks. What version of the Chromium web view are you running? You can find this by logging `window.navigator.userAgent` in Chrome dev tools when inspecting the app.

The code that your app is erroring on is coming from Angular, not Ionic.

**Comment by luckyycool** [comment]
Thank you. 

The version : `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36'`

Also just if it helps,

When I run www folder directly in browser it works, ionic serve also works fine, it is just failing when run with ionic capacitor run android

**Comment by liamdebeasi** [comment]
Thanks. The code you specified is certainly coming from inside Angular and not Ionic: https://github.com/angular/angular/blob/master/packages/common/src/location/location.ts#L203-L205

It looks like the compiled JS still keeps the optional changing `?.`  which is only supported in Chrome 80: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

This is likely why you are running into this issue.

Does the issue go away if you update the webview?

**Comment by liamdebeasi** [comment]
I updated your app from 13.0.4 to 13.2.2 and the it looks like the optional chaining is no longer in the compiled output, so it is possible there was a bug in Angular that got resolved.

Can you try updating to the latest version of Angular and let me know if that resolves the issue? You can try doing this instead of updating your webview.

Here is the `package.json` diff so you can compare:

```diff
index 89a0149..24626eb 100644
--- a/package.json
+++ b/package.json
@@ -13,12 +13,12 @@
   },
   "private": true,
   "dependencies": {
-    "@angular/common": "~13.0.0",
-    "@angular/core": "~13.0.0",
-    "@angular/forms": "~13.0.0",
-    "@angular/platform-browser": "~13.0.0",
-    "@angular/platform-browser-dynamic": "~13.0.0",
-    "@angular/router": "~13.0.0",
+    "@angular/common": "~13.2.1",
+    "@angular/core": "~13.2.1",
+    "@angular/forms": "~13.2.1",
+    "@angular/platform-browser": "~13.2.1",
+    "@angular/platform-browser-dynamic": "~13.2.1",
+    "@angular/router": "~13.2.1",
     "@capacitor/app": "1.1.0",
     "@capacitor/core": "3.4.0",
     "@capacitor/haptics": "1.1.4",
@@ -30,15 +30,15 @@
     "zone.js": "~0.11.4"
   },
   "devDependencies": {
-    "@angular-devkit/build-angular": "~13.0.1",
+    "@angular-devkit/build-angular": "~13.2.2",
     "@angular-eslint/builder": "~13.0.1",
     "@angular-eslint/eslint-plugin": "~13.0.1",
     "@angular-eslint/eslint-plugin-template": "~13.0.1",
     "@angular-eslint/template-parser": "~13.0.1",
-    "@angular/cli": "~13.0.1",
-    "@angular/compiler": "~13.0.0",
-    "@angular/compiler-cli": "~13.0.0",
-    "@angular/language-service": "~13.0.0",
+    "@angular/cli": "~13.2.2",
+    "@angular/compiler": "~13.2.1",
+    "@angular/compiler-cli": "~13.2.1",
+    "@angular/language-service": "~13.2.1",
     "@capacitor/cli": "3.4.0",
     "@ionic/angular-toolkit": "^5.0.0",
     "@types/jasmine": "~3.6.0",
@@ -63,4 +63,4 @@
     "typescript": "~4.4.4"
   },
   "description": "An Ionic project"
-}
+}
```

**Comment by luckyycool** [comment]
I can't disagree with you anymore. Just wondering why I could not think of comparing package.json when I had both solutions with me (with ionic and one working one without ionic but with different package.json deps).

Thanks a lot. We can close the bug but would be good to document it for others to help.
