### ISSUE TITLE
bug: overlay getTop() does not return modal instance in lifecycle events

### ISSUE THREAD

**Issue by papagei-ma** [ionic-team/ionic-framework#24673]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

`getTop()` returns undefined in `ngOnInit` and `ngAfterViewInit`. Yet with a timer I get it after some milliseconds.

### Expected Behavior

`getTop()` should return the element as it is there and open in the DOM. 

### Steps to Reproduce

1.Run `ModalController.Create()` and pass the page. 
2.In the Page `ngOnInit` or even `ngAfterViewInit` try to get the modal through `modalController.getTop()` yet `undefined` in returned instead

### Code Reproduction URL

https://github.com/papageicom/ionic-6-test

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (.../lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.4
   @angular-devkit/build-angular : 13.1.4
   @angular-devkit/schematics    : 13.1.3
   @angular/cli                  : 13.1.3
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.3.4
   @capacitor/core    : 3.3.4
   @capacitor/ios     : 3.3.4

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.17.6 (/Users/.../.nvm/versions/node/v14.17.6/bin/node)
   npm    : 6.14.15
   OS     : macOS Monterey

### Additional Information

in the repo, theres two branches 
1. Master,  the issue is there, with ionic 6.0.x, angular 13.x.x.
2. ionic-5-9-3, the issue is not there, everything works just fine, with ionic 5.x.x, angular 12.x.x.

**Comment by papagei-ma** [comment]
In [https://github.com/ionic-team/ionic-framework/issues/24545](url), there was some discussion about a similar problem. I hope its fine, that I created a new issue :)

**Comment by sean-perkins** [comment]
@papagei-ma thanks for converting that conversation into this issue. Super helpful to be able to track it and understand what's happening.

I'm seeing the same behavior as you between 5.9.x vs. latest. I'll track as a bug and try to narrow which release regressed this behavior.

**Comment by sean-perkins** [comment]
Ok, looks like this change specifically occurred in v6.0.2. 

Installing 6.0.1 results in the modal element logging correctly in the life cycle hooks.

```
npm i @ionic/angular@6.0.1 --save-exact
```

There's a few changes in that release that could be related. We'll prioritize and figure it out 👍

**Comment by AE1NS** [comment]
In my case I need the modal reference inside an angular component, that gets displayed with the ModalController. I also used getTop() for this, but it stopped working after upgrading to v6 and a timer would be needed. I decided to use another way to get the instance:
```
constructor(private elementRef: ElementRef) {}

...

const modal = this.elementRef.nativeElement.closest('ion-modal');
```

**Comment by sean-perkins** [comment]
Hello everyone 👋  still actively investigating this issue. Seems to be a compound problem. With #24547, overlays that are hidden shouldn't be considered as the top overlay. 

Unfortunately, when `ngOnInit` fires in your modal component, the modal hasn't finished transitioning and is still considered hidden. Investigating how to support both behaviors.

**Comment by pabloservin** [comment]
Hello @sean-perkins any updates on this matter? We are facing the same issue, with ionic/angular 6.0.5

**Comment by sean-perkins** [comment]
Hello everyone, following up after investigating this issue further. 

I don't believe using `modalController.getTop()` is the correct API for accessing the modal instance at the time of initialization. The API intended to only return visible overlays, which wasn't the case until a change in 6.0.3. Because hidden overlays were not filtered out, you were able to use `getTop()` to return a modal instance before it was actually visible. 

Instead of this implementation pattern, I would recommend using the `modal` object that is set on each modal that is presented. 

For example:
```ts
@Component({
  ...
})
export class ModalComponent implements OnInit {
  modal: HTMLIonModalElement;

  ngOnInit() {
    console.log('modal', this.modal); // this returns the modal being displayed
  }
}
```

Does this work to resolve the issues everyone is facing? Or can someone provide a valid use case where you would need to use `getTop()` to access a modal instance _other than_ the modal you are calling `getTop()` from?

**Comment by NePheus** [comment]
Didnt know that this property exists. Its exactly what I am looking for and replaces the getTop call in my case! Thank you for that hint!
