### ISSUE TITLE
bug: Ionic live reload skips deploying app to phone

### ISSUE THREAD

**Issue by fershopls** [ionic-team/ionic-framework#24675]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Once live reload has been executed once then every livereload behaves like this:

When trying to use live reload feature
`ionic cap run android --external -l`

- It runs `cap sync android`
- It runs `ionic serve`

### Expected Behavior

When trying to use live reload feature
`ionic cap run android --external -l`

- It runs `cap sync android`
- **It should deploy the application to the android phone.**
- It runs `ionic serve`

### Steps to Reproduce

Create a new ionic project with
`ionic start sample-app`

Attempt to make a live reload with the command:
`ionic cap run android --external -l`

It will work the first time, and then if for example you run the app via Android Studio, and then again want to use the live reload feature it stops deploying the app to the phone. Even if the phone is connected and being detected ok.

Using the following command works well, but without live reload:
`ionic cap run android --external`

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'
       
       Require stack:
       - C:\Users\shaaf\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\shaaf\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js        
       - C:\Users\shaaf\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\shaaf\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\shaaf\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.0.4

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.0
   OS     : Windows 10

**Comment by Suxsem** [comment]
I'm experiencing the same issue

**Comment by fershopls** [comment]
@Suxsem

A work arround I found:

On terminal 1:
`ionic serve`
_Take note of your LAN ip and the port your ionic server is running_

On terminal 2:
`ionic cap run --livereload-url <your_ip>:<port>`
_Use the ip and the port of the command used on terminal 1_

**Comment by mhartington** [comment]
@fershopls Can you share the output from `ionic cap run android --livereload --external`? You should be seeing something like this.


<img width="735" alt="Screen Shot 2022-01-31 at 10 37 30 AM" src="https://user-images.githubusercontent.com/2835826/151823505-f5e77cc3-bd46-4b36-88a3-52d4b721556c.png">
