### ISSUE TITLE
bug: Ion-slides and overflow-y:scroll dont work together on mobile

### ISSUE THREAD

**Issue by nanafy** [ionic-team/ionic-framework#24680]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

**Need to try this on mobile or device emulation in browser**

If you try and slide the image inside the ion-slide component on the x-axis, the slider gets stuck, only if you refresh the app using f5 or by clearing cache on an actual device does the bug go away. But on every initial build, this bug occurs.  ( _never tested on ios)_

### Expected Behavior

The ion image should be able to slide horizontally regardless of the style property overflow-y attached to it on mobile without a page refresh.

### Steps to Reproduce

1.) Build app on device or browser and don't refresh app (f5) 
2.) Run this code anywhere

```
<ion-slides style="overflow-y:scroll;">


  <ion-slide >
      <ion-img src="insert something"></ion-img>
  </ion-slide>

</ion-slides>
```

### Additional Information

Holding down Shift as you scroll horizontally makes it work, I have no idea what that actually means when it comes to inputs on the browser emulator maybe that is a key to solving this.

**Comment by liamdebeasi** [comment]
Thanks for the issue!

Starting with Ionic 5.7.0, we deprecated `ion-slides` in favor of having developers install Swiper.js directly in their projects. This gives developers access to new features, an improved developer experience, and bug fixes that they did not have access to when using `ion-slides`.

As a result of this deprecation, we have suspended any new development on `ion-slides` with the exception of critical fixes, such as resolving security issues.

I am going to close this issue out, but we strongly encourage you to try out the latest version of Swiper.js in your project. We have found that upgrading to the latest version of Swiper.js resolved a large number of common problems that Ionic developers were running into.

Please see https://ionicframework.com/docs/api/slides for more information on this change as well as a step by step migration guide for your apps.
