### ISSUE TITLE
bug: Ionic Add requires a project type of "application"

### ISSUE THREAD

**Issue by sz274071580** [ionic-team/ionic-framework#24688]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When I execute "npx schematics @ionic/angular:ng-add" command I get error:
Error: Ionic Add requires a project type of "application".
at D:\mysoftware\scada2\mobile\scada\node_modules@ionic\angular\schematics\add\index.js:103:19

### Expected Behavior

pass normally

### Steps to Reproduce

Execute the following command
1.npm install @angular-devkit/schematics-cli    success
2.npm link @ionic/angular                                  success
3.npx schematics @ionic/angular:ng-add           error

When I execute "npx schematics @ionic/angular:ng-add" command I get error:
Error: Ionic Add requires a project type of "application".
at D:\mysoftware\scada2\mobile\scada\node_modules@ionic\angular\schematics\add\index.js:103:19

### Ionic Info

ionic + angular：
@angular-devkit/schematics-cli: "^13.2.0",
@angular/animations: "~13.1.0",
@angular/common: "~13.1.0",
@angular/compiler: "~13.1.0",
@angular/core: "~13.1.0",
@angular/forms: "~13.1.0",
@angular/platform-browser: "~13.1.0",
@angular/platform-browser-dynamic: "~13.1.0",
@angular/router: "~13.1.0",
@ionic/angular: "^6.0.4",
rxjs: "~7.4.0",
tslib: "^2.3.0",
zone.js: "~0.11.4"
typescript: "~4.5.2"

nodejs：v16.13.2
OS：windows 10
npm：8.1.2

**Comment by mhartington** [comment]
Hey there! So I'm a bit confused here. What are you trying to do? Are you trying to add ionic to an existing Angular project? 
Can you provide some more context?

**Comment by sz274071580** [comment]
> Hey there! So I'm a bit confused here. What are you trying to do? Are you trying to add ionic to an existing Angular project? Can you provide some more context?

**this is my package.json**
{
&nbsp;&nbsp;"name": "scada",
&nbsp;&nbsp;"version": "0.0.0",
&nbsp;&nbsp;"scripts": {
&nbsp;&nbsp;&nbsp;&nbsp;"ng": "ng",
&nbsp;&nbsp;&nbsp;&nbsp;"start": "ng serve",
&nbsp;&nbsp;&nbsp;&nbsp;"build": "ng build",
&nbsp;&nbsp;&nbsp;&nbsp;"watch": "ng build --watch --configuration development",
&nbsp;&nbsp;&nbsp;&nbsp;"test": "ng test"
&nbsp;&nbsp;},
&nbsp;&nbsp;"private": true,
&nbsp;&nbsp;"dependencies": {
&nbsp;&nbsp;&nbsp;&nbsp;"@angular-devkit/schematics-cli": "^13.2.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/animations": "~13.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/common": "~13.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/compiler": "~13.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/core": "~13.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/forms": "~13.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/platform-browser": "~13.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/platform-browser-dynamic": "~13.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/router": "~13.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@ionic/angular": "^6.0.4",
&nbsp;&nbsp;&nbsp;&nbsp;"rxjs": "~7.4.0",
&nbsp;&nbsp;&nbsp;&nbsp;"tslib": "^2.3.0",
&nbsp;&nbsp;&nbsp;&nbsp;"zone.js": "~0.11.4"
&nbsp;&nbsp;},
&nbsp;&nbsp;"devDependencies": {
&nbsp;&nbsp;&nbsp;&nbsp;"@angular-devkit/build-angular": "^13.2.1",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/cli": "~13.1.2",
&nbsp;&nbsp;&nbsp;&nbsp;"@angular/compiler-cli": "~13.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@types/jasmine": "~3.10.0",
&nbsp;&nbsp;&nbsp;&nbsp;"@types/node": "^12.11.1",
&nbsp;&nbsp;&nbsp;&nbsp;"jasmine-core": "~3.10.0",
&nbsp;&nbsp;&nbsp;&nbsp;"karma": "~6.3.0",
&nbsp;&nbsp;&nbsp;&nbsp;"karma-chrome-launcher": "~3.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"karma-coverage": "~2.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;"karma-jasmine": "~4.0.0",
&nbsp;&nbsp;&nbsp;&nbsp;"karma-jasmine-html-reporter": "~1.7.0",
&nbsp;&nbsp;"typescript": "~4.5.2"
&nbsp;&nbsp;}
}



**this is my angular.json**
{
&nbsp;&nbsp;"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
&nbsp;&nbsp;"version": 1,
&nbsp;&nbsp;"newProjectRoot": "projects",
&nbsp;&nbsp;"projects": {
&nbsp;&nbsp;&nbsp;&nbsp;"scada": {
&nbsp;&nbsp;&nbsp;&nbsp;"projectType": "application",
&nbsp;&nbsp;&nbsp;&nbsp;"schematics": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"@schematics/angular:application": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"strict": true
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;},
&nbsp;&nbsp;"root": "",
&nbsp;&nbsp;"sourceRoot": "src",
&nbsp;&nbsp;"prefix": "app",
&nbsp;&nbsp;"architect": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"build": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"builder": "@angular-devkit/build-angular:browser",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"options": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"outputPath": "dist/scada",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"index": "src/index.html",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"main": "src/main.ts",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"polyfills": "src/polyfills.ts",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"tsConfig": "tsconfig.app.json",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"assets": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"src/favicon.ico",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"src/assets"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"styles": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"src/styles.css"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"scripts": []
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"configurations": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"production": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"budgets": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"type": "initial",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"maximumWarning": "500kb",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"maximumError": "1mb"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"type": "anyComponentStyle",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"maximumWarning": "2kb",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"maximumError": "4kb"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"fileReplacements": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"replace":"src/environments/environment.ts",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"with":"src/environments/environment.prod.ts"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"outputHashing": "all"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"development": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"buildOptimizer": false,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"optimization": false,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"vendorChunk": true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"extractLicenses": false,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"sourceMap": true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"namedChunks": true
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"defaultConfiguration": "production"
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;"serve": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"builder": "@angular-devkit/build-angular:dev-server",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"configurations": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"production": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"browserTarget": "scada:build:production"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"development": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"browserTarget": "scada:build:development"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;"defaultConfiguration": "development"
&nbsp;&nbsp;},
&nbsp;&nbsp;"extract-i18n": {
&nbsp;&nbsp;&nbsp;&nbsp;"builder": "@angular-devkit/build-angular:extract-i18n",
&nbsp;&nbsp;&nbsp;&nbsp;"options": {
&nbsp;&nbsp;&nbsp;&nbsp;"browserTarget": "scada:build"
&nbsp;&nbsp;}
&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"test": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"builder": "@angular-devkit/build-angular:karma",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"options": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"main": "src/test.ts",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"polyfills": "src/polyfills.ts",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"tsConfig": "tsconfig.spec.json",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"karmaConfig": "karma.conf.js",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"assets": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"src/favicon.ico",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"src/assets"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"styles": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"src/styles.css"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"scripts": []
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;},
&nbsp;&nbsp;"defaultProject": "scada"
}

**Comment by sz274071580** [comment]
> Hey there! So I'm a bit confused here. What are you trying to do? Are you trying to add ionic to an existing Angular project? Can you provide some more context?

I want to add ionic to an angular project and want the directive "npx diagrams @ionic/angular:ng-add" to execute successfully

**Comment by sz274071580** [comment]
> @sz274071580 Please follow the guide here: https://ionicframework.com/docs/intro/cdn#ionic--angular
> 
> You should only need to do the following two steps in your existing Angular project:
> 
> 1. `npm install @ionic/angular@latest --save`
> 2. `ng add @ionic/angular`
> 
> I believe you are following the README for `@ionic/angular`: https://www.npmjs.com/package/@ionic/angular. Those instructions are for when you locally modify a clone of the repository, that you want to test on your machine against an Angular project.

Thank you very much for your reply, I have successfully added ionic to angular's project
