### ISSUE TITLE
feat: pass readonly input as class name for item (like disabled).

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#24689]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The readonly on `ion-input` should be set in the class name of `ion-item` as the `disabled` attribute does .

```html
<ion-item>
  <ion-label>Value</ion-label>
  <ion-input readonly></ion-input>
</ion-item>
```

### Describe the Use Case

Being able to style the item dependent on the readonly input element. Currently I have to set it twice. The attribute on input and as class name for item. Since css [:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) not yet works.

The disabled attribute on item generates the class `item-interactive-disabled` on item. The readonly should also generate a class here.

**Comment by liamdebeasi** [comment]
Thanks for the issue. The `item-interactive-disabled` is only set because we style the item/label differently based on the state of `ion-input`. (See https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/src/components/label/label.scss#L37-L41).

With the `readonly` property, we do not need to style the item and label differently which is why there is no `item-interactive-readonly` class.

In general, we are looking to move away from this approach as it adds a considerable amount of complexity to the code and is hard to maintain.

Can you please explain what you are trying to accomplish with styling the item based on the readonly state of the input?

**Comment by infacto** [comment]
I just want to indicate readonly input items to improve the ux. It reduce user trial and error interactions. 

In my particular case, the normal input items have custom styles to distinguish them from other items. Non-input items and inputs items (and readonly) in pure Ionic looks exactly the same. The user should know what items are interactive and what items are just readonly. So the readonly class is for `:not` selector in my case (exclude). I don't think that this is relevant for Ionic. I know that Ionic 6 revamped the input styles. But this does not matter in this case of mixed items, not a regular form.

But it's just a suggestion to automatically add the readonly class to the parent like disabled does. If you don't want classes without using them in styles, fine. I'll add the class manually. It's just redundant. So consider to add `.item-interactive-readonly` or not. No build in styles required.

The [Material Design](https://material.io/components/text-fields) read-only fields is styles in the same as a regular text field and is just labled as readonly. So following the spects, I should just add something like "(read-only)" to the label. But I don't like this solution. Especially for Ionic items (looks all the same). It's your decision to add the class or not. I can live with both. I just think, why not?

**Comment by liamdebeasi** [comment]
Thanks, the added context was helpful. After discussing with the team, we have decided that this feature is not a good fit for Ionic.

The main reason is we feel the root issue is that we need to offer a feature to better style form controls that does not rely on looking at the parent component. By adding this class, the root issue still remains. We are tracking these form control styling changes internally, and we will communicate any changes with the community as we have them.

Thanks!
