### ISSUE TITLE
[angular] When loading the page it loads all the Ionic icons even if not used #17886

### ISSUE THREAD

**Issue by WuglyakBolgoink** [ionic-team/ionic-framework#24682]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

if i visit page then I see in network tab loading some SVG files which we don't have in our codebase.

### Expected Behavior

not loading any icons if they not exists in the our codebase

### Steps to Reproduce

create app, probably, with navigation

### Code Reproduction URL

not necessary 

### Ionic Info

lates ionic capacitor version

### Additional Information

Related to https://github.com/ionic-team/ionic-framework/issues/17886

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
