### ISSUE TITLE
bug: ion-toast only show once and won't show again whenever the state changes.

### ISSUE THREAD

**Issue by ryansyrl** [ionic-team/ionic-framework#24685]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

So, make ion-toast to be a global component, with script like this

![code](https://user-images.githubusercontent.com/67872022/152023999-b36d6b5c-e0e2-4268-bd90-488db9652f29.png)

![code2](https://user-images.githubusercontent.com/67872022/152024337-27290fb2-be3d-4f86-9583-b9669b83dbaf.png)

then i use it on login page and passing down the state, the message, and the color. but the ion-toast only show once, and wont shows again whenever the state changes and i already tried using watch, it wont show either. What wen wrong with my script?

### Expected Behavior

i tried with same approach for ion-loading, it works just fine. the loading will show whenever the state changes

### Steps to Reproduce

i make it the ion-toast to be a global component, so i can use it if any page needs it

### Ionic Info
"vue": "^3.2.21",
"@ionic/vue": "^6.0.1",

**Comment by ryansyrl** [comment]
oops nevermind, i solve the problem.. it is definitely my bad, i did not set the state back to false. i wrote confusing code, i already using props so i should not use reusable composition API like that. cheers

**Comment by liamdebeasi** [comment]
Glad the issue is resolved 👍

**Comment by paulsancer** [comment]
hey guys, on a similar note since I can't find this around here: 

I am trying to change the message of the toast while its still open but i can't make it happen (my app loads multiple things one-by-one and I want to change what is being loaded at the time without closing and re-opening the toast). Is this at all possible?

v6/react, thanks!
