### ISSUE TITLE
bug: Ionic 6 animation with modal is not working

### ISSUE THREAD

**Issue by rathorrajnesh** [ionic-team/ionic-framework#24698]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

it is not showing any modal animation as now  Shadow DOM used

### Expected Behavior

It should show the modal animation mentioned in https://ionicframework.com/docs/utilities/animations but it stopped 

### Steps to Reproduce

You can find here https://ionicframework.com/docs/utilities/animations#modals  that now custom animation to modal is not working

**Comment by liamdebeasi** [comment]
Thanks! I have fixed this on the docs website. You may need to wait a few minutes before you can see the changes live on the website.
