### ISSUE TITLE
bug: @ionic/react-test-utils ionFireEvent isn't working

### ISSUE THREAD

**Issue by creativiii** [ionic-team/ionic-framework#24690]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Following [this ionic article](https://ionicframework.com/blog/testing-ionic-react-apps-with-jest-and-react-testing-library/), I should be able to interact with Ionic components by doing two things.

Add the following to my `setupTests.js`:

```
import { mockIonicReact } from '@ionic/react-test-utils';

mockIonicReact();
```

And then using:
```
import { ionFireEvent } from '@ionic/react-test-utils';
```

To fire events to my Ionic components.

Unfortunately this doesn't seem to be working.

## My component
```
        <IonList>
          <IonItemDivider>Sort by</IonItemDivider>
          <IonRadioGroup
            value={selected}
            onIonChange={(e) => setSelected(e.detail.value)}
          >
            <IonItem>
              <IonLabel>Boosted and Auto-Assign first</IonLabel>
              <IonRadio title="normal" slot="start" value="" />
            </IonItem>

            <IonItem>
              <IonLabel>Closest to you</IonLabel>
              <IonRadio title="distance" slot="start" value="Distance" />
            </IonItem>
          </IonRadioGroup>
        </IonList>
```

## My test
```
import { render } from '@testing-library/react';
import { ionFireEvent } from '@ionic/react-test-utils';
import Component from './index';

const setup = async () => {
  const utils = render(
      <Component />
  );

  const normal = await utils.findByTitle('normal');
  const distance = await utils.findByTitle('distance');

  return {
    ...utils,
    normal,
    distance,
  };
};

describe('Shift list sorting', () => {
  it('can select other options', async () => {
    const { distance} = await setup();

    ionFireEvent.click(distance);

    expect(distance).toHaveAttribute('aria-checked', 'true');
  });
});
```

When running the tests the outcome is:

![image](https://user-images.githubusercontent.com/23533178/152126205-ab4ea814-eb42-4750-a7c9-b7108980be0e.png)

### Expected Behavior

The tests should pass. 

So far I've tried clicking different parts of the Ionic component (Item, Label, Radio), but haven't been able to make it work.

### Steps to Reproduce

I've created a reproduction repository which you can find at: [ionic-testing-bug](https://github.com/creativiii/ionic-testing-bug)

To reproduce:

- Clone the repo locally
- `cd` into `ionic-testing-bug`
- run `npm install`
- run `npm run test`

The first test will pass, the second one will fail.

### Code Reproduction URL

https://github.com/creativiii/ionic-testing-bug

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here is you need to fire the `ionChange` event, not the `click` event. Components like `IonRadioGroup` are mocked which means the internals to handle firing `ionChange` from within the `IonRadioGroup` is not there. This is the intended behavior as we intend for developers to use this library to test their own code, not the internals of Ionic components.

Another way of looking at this is you should be testing what happens when `ionChange` is fired from `IonRadioGroup`, not what happens when `IonRadioGroup` is clicked. Ionic handles the click part internally when running your app in the browser.

In your test, I recommend doing the following:

```
ionFireEvent.ionChange(radioGroup, 'Distance');
```
`radioGroup` is a reference to the `IonRadioGroup` in your `component.js` file.

Does this address your concern?

**Comment by creativiii** [comment]
That works! Thank you for your help 😄
