### ISSUE TITLE
feat: option to show default buttons in time picker in date-time picker

### ISSUE THREAD

**Issue by scr2em** [ionic-team/ionic-framework#24703]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

<img width="259" alt="Screen Shot 2022-02-03 at 12 18 58 PM" src="https://user-images.githubusercontent.com/4671486/152323764-03437c20-f2e2-41b0-a0d1-498b44647bc8.png">

In date-time picker, we need an option to show default buttons (done, cancel) for time picker as well 

### Describe the Use Case

it's a little confusing to have that option in all pickers except time picker in date-time picker

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe the problem you are running into by not having buttons in the picker? This decision was made to align with now the native picker works on iOS.

**Comment by scr2em** [comment]
@liamdebeasi thank you for your reply, It's not an issue, It was just confusing because we already have that option in time pickers but not in the time picker inside date-time. Will this be considered in the future ?

**Comment by liamdebeasi** [comment]
Thanks! I spoke with the team and we do not feel that this feature would be a good fit for Ionic. We have a couple concerns:

1. Having two layers of confirm/cancel buttons may be confusing for users. (Confirm/cancel on the time picker and confirm/cancel on the underlying date picker)
2. Adding this feature would mean the time picker is not aligned with the native implementation on iOS.

Instead what we recommend is having a separate time picker that is displayed inline. This will allow you to avoid the popover and have the confirm/cancel buttons you want:

```html
<ion-datetime
  presentation="time"
></ion-datetime>
```

From here you can either slot in your own buttons or use the `showDefaultButtons` prop. I am going to close this issue. Thanks!
