### ISSUE TITLE
bug: last item in list is covered in a inline modal if header is also present

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionic-framework#24706]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Opening an inline modal which contains a header and also a list of items are not able to scroll to the bottom of the list. Last item in list is covered and not shown.
If I remove the `ion-header` part from the modal anything is fine

Look at the picture you can see that at the bottom of the modal an item is cut, its the item with the number 16

![image](https://user-images.githubusercontent.com/3778892/152363108-b4d81181-a1b7-4fe6-bd6c-dbe2888d2f1f.png)

```
<ion-modal [isOpen]="true">
  <ng-template>
    <ion-header translucent>
      <ion-toolbar>
        <ion-title>Modal Content</ion-title>
        <ion-buttons slot="end">
          <ion-button>Close</ion-button>
        </ion-buttons>
      </ion-toolbar>
    </ion-header>
    <ion-content fullscreen>
      <ion-list>
        <ion-item>
          <ion-avatar slot="start">
          </ion-avatar>
          <ion-label>
            <h2>Gollum</h2>
            <p>Sneaky little hobbitses!</p>
          </ion-label>
        </ion-item>
        <ion-item>
          <ion-avatar slot="start">
          </ion-avatar>
          <ion-label>
            <h2>Frodo</h2>
            <p>Go back, Sam! I'm going to Mordor alone!</p>
          </ion-label>
        </ion-item>
        <ion-item>
          <ion-avatar slot="start">
          </ion-avatar>
          <ion-label>
            <h2>Samwise</h2>
            <p>What we need is a few good taters. 1</p>
          </ion-label>
        </ion-item>
        <ion-item>
          <ion-avatar slot="start">
          </ion-avatar>
          <ion-label>
            <h2>Samwise</h2>
            <p>What we need is a few good taters. 2</p>
          </ion-label>
        </ion-item>
........
        <ion-item>
          <ion-avatar slot="start">
          </ion-avatar>
          <ion-label>
            <h2>Samwise</h2>
            <p>What we need is a few good taters. 15</p>
          </ion-label>
        </ion-item>
        <ion-item>
          <ion-avatar slot="start">
          </ion-avatar>
          <ion-label>
            <h2>Samwise</h2>
            <p>What we need is a few good taters. 16</p>
          </ion-label>
        </ion-item>
      </ion-list>
    </ion-content>
  </ng-template>
</ion-modal>


```

### Expected Behavior

The last item in the list should not be covered if the modal has a header

### Steps to Reproduce

You can just download and run my sample project to simulate it

### Code Reproduction URL

- https://github.com/mburger81/ion6-modal

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.5
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.6 (/usr/local/bin/node)
   npm    : 8.4.0
   OS     : macOS Monterey

```

**Comment by sean-perkins** [comment]
Hello @mburger81,

A workaround to your issue, is to wrap the inner contents of your inline-modal with the `.ion-page` class.

For example:
```html
<ion-modal [isOpen]="true">
  <ng-template>
    <div class="ion-page">
      <ion-header translucent>
        ...
      </ion-header>
      <ion-content fullscreen>
        ...
      </ion-content>
    </div>
  </ng-template>
</ion-modal>
```

This may be an implementation details/docs issue. I'll discuss with the team and determine.

**Comment by sean-perkins** [comment]
Confirmed with the team that this is **not** an implementation detail and should be accounted for automatically be the inline modal. 

I've created a PR to address this behavior: #24723.
