### ISSUE TITLE
bug: wrong type hint for Popover Controller alignment prop  

### ISSUE THREAD

**Issue by treighmawaka** [ionic-team/ionic-framework#24709]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When creating a Popover Controller, the `alignment` option of the `popoverController.create()` method has the wrong type hint.  

### Expected Behavior

The `PopoverOptions.align` prop should be `PopoverOptions.alignment` as [noted in the docs ](https://ionicframework.com/docs/api/popover#alignment-1)

### Steps to Reproduce

```ts
async function openPopover(ev: Event) {
  const popover = await popoverController.create({
   // ...
    align: "center", // ❌ this is wrong, but passes type validation
    //alignment: "center", // ✅ this is valid, but triggers a type error
  });

  await popover.present();
}
```

### Code Reproduction URL

https://stackblitz.com/edit/vitejs-vite-pudsq6?file=src/App.vue

### Ionic Info

Ionic:

   Ionic CLI : 6.16.3

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.5.0) : 1.3.0

System:

   NodeJS : v16.13.1
   npm    : 8.1.2
   OS     : macOS Big Sur

  ─────────────────────────────────────────────────

     Ionic CLI update available: 6.16.3 → 6.17.1
          Run npm i -g @ionic/cli to update

**Comment by sean-perkins** [comment]
@treighmawaka thanks for reporting this issue!

I've updated the title, since this problem stems from the interfaces from our core package.
