### ISSUE TITLE
feat: ion-modal sheet to be optionally draggable by only handle

### ISSUE THREAD

**Issue by Lxstr** [ionic-team/ionic-framework#24715]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

A way to prevent the sheet modal from dragging up and down when touches are made the the content area.

### Describe the Use Case

Currently I wish to use handwriting within a sheet modal and vertical strokes result in the whole sheet dragging up and down.

### Describe Preferred Solution

Simply add another option for draggable content in the same way as there is an option for the handle to show.

### Describe Alternatives

I have tried a number of methods involving stopPropogation() on pointer events but to no success.

### Related Code

https://ionicframework.com/docs/api/modal

### Additional Information

If this could either be an option or someone knows how I could fix this I would appreciate it.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe the problem you are running into with the current behavior? The sheet modal was designed to mimic the native sheets found on iOS and Android, both of which allow gestures on the content.

**Comment by brice-noowu** [comment]
Problem is : with the actual behavior it's impossible to have any kind of vertical overflowing content inside the sheet modal, or any kind of vertical swipe based component inside it, because it conflicts with the swipe event on the modal body. So yeah it could be really nice to have an option to drag it only via the handle !

**Comment by Lxstr** [comment]
Yeah I can see overflow content being a reasonable use case. Mine would be handwriting like this jumpshare demo. Currently it is only useable at full height.

[https://jmp.sh/K5hp4jz](url)
