### ISSUE TITLE
bug: back-button icon is not flipped in RTL

### ISSUE THREAD

**Issue by Hizabr** [ionic-team/ionic-framework#24729]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

After updating from 6.0.4 to 6.0.5 the back button direction is no longer respect right to left language
![03CFF307-3FF8-4885-9276-AA40144E149E](https://user-images.githubusercontent.com/5300932/152702250-5f16c1cd-4038-41df-8b12-367369981475.jpeg)

### Expected Behavior

![Expected Behavior](https://user-images.githubusercontent.com/5300932/152800671-a968f771-882f-4824-8170-a602947b50f8.png)

### Steps to Reproduce

Update to 6.0.5

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.5
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : 3.4.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by amandaesmith3** [comment]
The aforementioned PR has been merged, so I'll go ahead and close this out. The fix will be available in a future release of Ionic 👍
