### ISSUE TITLE
bug: ios, input not prompting for password manager when running on device

### ISSUE THREAD

**Issue by sarathi0333** [ionic-team/ionic-framework#24739]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Given a simple form with 2 IonInput elements (user/password login). It can be set up to be recognized by iOS Password Manager to fill in credentials from iOS Keychain.

Input elements are actually filled with data, BUT the IonInput of type password does not recognize the changed value of the underlying native html input element. This can be visually seen as the delete input element is not shown. Also when reading the value from IonInput it is just empty.

Current workaround: On form submit, I get the value from the underlying native html input, which is correctly set and works without a problem.

### Expected Behavior

When values are set by iOS Password Manager, the value should be reflected in the IonInput element. should be accessible from component on submit. 

### Steps to Reproduce

- Basic IonPage with a form and 2 IonInput (user/password login)
- Build the App for iOS and deploy an a device
- autofill credentials from iOS Password Manager
- value of IonInput of password is empty, while value of html input of password contains the correct value

### Code Reproduction URL

https://stackblitz.com/edit/ionic-angular-v5-obz6qy?devtoolsheight=33&file=src/app/app.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 6.14.0 
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 21 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

### Additional Information

Please auto fill the input fields by using password managers and don't fill it manually.
Click on submit the data should appear below.

**Comment by jansgescheit** [comment]
our customer reports same behaviour on ios devices, with iOS built in or 3party password-managers

**Comment by Siedlerchr** [comment]
I experience the same as @sarathi0333 on an iPad Air 3 with iOS15.3,  the autocomplete works, but the password is empty on submit. 
I'm using ionic 5 + cordova

**Comment by WolfWalter** [comment]
A customer reported the same behavior. As a workaround I sync the native password input with the angular form when the username changes. Here is the code:

```html
<ion-input formControlName="password" #passwordInput [type]="showPassword ? 'text' : 'password'"></ion-input>
```

```ts
@ViewChild('passwordInput', { read: ElementRef }) passwordInput!: ElementRef<HTMLElement>;
  private _subscriptions: Subscription[];

  constructor(
    private formBuilder: FormBuilder,
  ) {
    this.signInForm = this.formBuilder.group({
      username: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
    });

    this._subscriptions = [];
    const signInFormUsernameSubscription = this.signInForm.get('username')?.valueChanges.subscribe((x) => {
      const nativeInput = this.passwordInput.nativeElement.querySelector('.native-input') as HTMLInputElement | null;
      const currentPasswort = this.signInForm.value.password;
      const nativeElementPassoword = nativeInput?.value;
      if ((nativeElementPassoword?.length ?? 0) > 0 && currentPasswort !== nativeElementPassoword) {
        this.signInForm.get('password')?.setValue(nativeElementPassoword);
      }
    });
    if (signInFormUsernameSubscription != null) this._subscriptions.push(signInFormUsernameSubscription);
  }
```

**Comment by liamdebeasi** [comment]
If this issue impacts any production apps you have, I definitely recommend posting a comment on https://bugs.webkit.org/show_bug.cgi?id=203299. Having a link to a production app that the WebKit team can use helps them with prioritizing which bugs to fix.

**Comment by sarathi0333** [comment]
> A customer reported the same behavior. As a workaround I sync the native password input with the angular form when the username changes. Here is the code:
> 
> ```
> <ion-input formControlName="password" #passwordInput [type]="showPassword ? 'text' : 'password'"></ion-input>
> ```
> 
> ```ts
> @ViewChild('passwordInput', { read: ElementRef }) passwordInput!: ElementRef<HTMLElement>;
>   private _subscriptions: Subscription[];
> 
>   constructor(
>     private formBuilder: FormBuilder,
>   ) {
>     this.signInForm = this.formBuilder.group({
>       username: ['', [Validators.required, Validators.email]],
>       password: ['', Validators.required],
>     });
> 
>     this._subscriptions = [];
>     const signInFormUsernameSubscription = this.signInForm.get('username')?.valueChanges.subscribe((x) => {
>       const nativeInput = this.passwordInput.nativeElement.querySelector('.native-input') as HTMLInputElement | null;
>       const currentPasswort = this.signInForm.value.password;
>       const nativeElementPassoword = nativeInput?.value;
>       if ((nativeElementPassoword?.length ?? 0) > 0 && currentPasswort !== nativeElementPassoword) {
>         this.signInForm.get('password')?.setValue(nativeElementPassoword);
>       }
>     });
>     if (signInFormUsernameSubscription != null) this._subscriptions.push(signInFormUsernameSubscription);
>   }
> ```

**Comment by sarathi0333** [comment]
Closed by mistake, reopening

**Comment by sarathi0333** [comment]
@WolfWalter the subscription triggers only if the value changes on the username field, what if the user places the cursor on the password field and auto-fills both username and password? This way angular could not detect the value changes though it is filled that's the issue.

**Comment by Siedlerchr** [comment]
@sarathi0333  I used the following approach:
```
     <ion-input type="password" [(ngModel)]="password" placeholder="Passwort" id="pwdinput" #pwd autocomplete="current-password" (change)="setPwd($event)"></ion-input>

  setPwd(event){
    this.password = event.target.value;
  }
```

**Comment by Saqib92** [comment]
facing same issue.

**Comment by liamdebeasi** [comment]
@Saqib92 What version of iOS are you testing this on? This issue should have been fixed in iOS already. I am trying to figure out the exact version that the fix shipped in and will post here when I figure that out.

**Comment by Saqib92** [comment]
> @Saqib92 What version of iOS are you testing this on? This issue should have been fixed in iOS already. I am trying to figure out the exact version that the fix shipped in and will post here when I figure that out.

I tested on iOS v15.4
