### ISSUE TITLE
bug: Inline Modal doesn't allow full scrolling of content, but Modal Controller does

### ISSUE THREAD

**Issue by billygerhard** [ionic-team/ionic-framework#24745]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When using Modal Controller, the modal allows scrolling to bottom.
![image](https://user-images.githubusercontent.com/2285204/153078191-37a4f719-0091-44fd-9141-e46b59973f2d.png)

When using inline modal, it clips the bottom of the content off screen, and doesn't allow full scrolling.
![image](https://user-images.githubusercontent.com/2285204/153078093-31eceb40-fa79-4e12-ae24-23b7a907dd2a.png)

### Expected Behavior

Both types of modals should perform the same behavior.

### Steps to Reproduce

Inline: 
```HTML
<ion-modal
    [swipeToClose]="true"
    [presentingElement]="routerOutlet.nativeEl"
    mode="ios" trigger="trigger-button">
    <ng-template>
      <app-modal></app-modal>
    </ng-template>
  </ion-modal>
```
Controller:
```TS
  async openModal(){
    const modal = await this.modalController.create({
      component: ModalComponent,
      swipeToClose: true,
      presentingElement: this.routerOutlet.nativeEl,
      mode:"ios",
      backdropDismiss:true,
      componentProps: {
        isModal: true
      }
    });
    return await modal.present();
  }
```

### Code Reproduction URL

https://github.com/billygerhard/IonicModalBugDemo

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (C:\Program Files\nodejs\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.5
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.18.0 (C:\Program Files\nodejs\node.exe)
   npm    : 7.11.2
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Hello @billygerhard thanks for reporting this issue!

This has been reported here #24706 and has been resolved here #24723.

It will be publicly available in v6.0.6 which releases this week.

Thanks!
