### ISSUE TITLE
bug: release 6.0.6 breaks my ion-datetime modal  - should this method still work?

### ISSUE THREAD

**Issue by richardkshergold** [ionic-team/ionic-framework#24750]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

In 6.0.5 my date picker appeared and worked.

In 6.0.6 but none of the buttons work and the app is unresponsive.

The date item uses a modal for display and is part of a form layout and this is my current code which is broken in 6.0.6 but worked in 6.0.5

```
<div *ngFor="let option of widget['options']">
      <ion-grid>
        <ion-row>
          <ion-col size="8">
            <ion-item detail = "false">
              <ion-label>{{formatDate(form.controls[option._id].value)}}</ion-label>
            </ion-item>
          </ion-col>
          <ion-col size="2">
            <ion-icon
              name="calendar-outline"
              size="large"
              [id]="option._id">
            </ion-icon>
          </ion-col>
          <ion-col size="2">
            <ion-button
              size="small"
              (click)="clearSelection(option._id)"
              fill="outline">
              Clear
            </ion-button>
          </ion-col>
        </ion-row>
      </ion-grid>
      <ion-modal mode="md" [trigger]="option._id">
        <ng-template mode="md">
          <ion-content mode="md" force-overscroll="false">
            <ion-datetime
              showDefaultButtons="true"
              presentation="date"
              [formControlName]="option._id">
            </ion-datetime>
          </ion-content>
        </ng-template>
      </ion-modal>
    </div>
```

### Expected Behavior

The date-time modal should display.

### Steps to Reproduce

Try something similar to the code above.

Should this method (opening with a modal) still work in 6.0.6 ?

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/xxx/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.6
   @angular-devkit/build-angular : 13.2.2
   @angular-devkit/schematics    : 13.2.2
   @angular/cli                  : 13.2.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : 3.4.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/Users/xxx/.nvm/versions/node/v16.13.0/bin/node)
   npm    : 8.1.0
   OS     : macOS Monterey

### Additional Information

I have switched back to 6.0.5 and my ion-datetime modal is working fine

**Comment by richardkshergold** [comment]
Testing on an iPhone SE by the way (iOS 15.2)

**Comment by liamdebeasi** [comment]
Thanks! I was able to reproduce the issue. I will work on a fix and get an update shipped out. Thanks for the report.
