### ISSUE TITLE
bug: ion-input with type number throws error on value change

### ISSUE THREAD

**Issue by AlessandroFBK** [ionic-team/ionic-framework#24753]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behaviour

Given an `ion-input` with type `number` 
```html
<ion-input
  inputmode="decimal"
  type="number"
></ion-input>
```
the following error is thrown on each value change:
```
Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
```

I notice that version 6.0.6 has recently changed the code that performs `setSelectionRange` on input element ([link](https://github.com/ionic-team/ionic-framework/blob/v6.0.6/core/src/components/input/input.tsx#L248)).

The bug does not occur on previous version (6.0.5).
 

### Expected Behavior

Typing in an `ion-input` with type `number` should not result into an error.

### Steps to Reproduce

In an Angular application, add 
```html
<ion-input
  inputmode="decimal"
  type="number"
></ion-input>
```
Then type some value in the input element and check out the console log.

### Code Reproduction URL

[GitHub repository](https://github.com/AlessandroFBK/ion-input-bug)

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/home/alessandro/.nvm/versions/node/v16.11.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.6
   @angular-devkit/build-angular : 12.2.12
   @angular-devkit/schematics    : 12.2.16
   @angular/cli                  : 12.2.16
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : 3.4.0

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v16.11.1 (/home/alessandro/.nvm/versions/node/v16.11.1/bin/node)
   npm    : 8.0.0
   OS     : Linux 5.4
```

**Comment by sean-perkins** [comment]
PR is open to address this issue.

You can test/use the dev build in the interim:
```
6.0.8-dev.1644430127.1b9bb92
```

Supports all `@ionic/*` packages. (react/angular/vue/core).

**Comment by spicemix** [comment]
I get a similar bug in `@ionic/angular@6.0.7` I will roll back for now. Surprised this made it all the way out to release.

```
DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.
    at Input.valueChanged (http://localhost:4200/node_modules_ionic_core_dist_esm_ion-input_entry_js.js:236:24)
    at http://localhost:4200/vendor.js:81534:40
    at Array.map (<anonymous>)
    at setValue (http://localhost:4200/vendor.js:81531:24)
    at Input.set [as value] (http://localhost:4200/vendor.js:81585:13)
    at HTMLInputElement.Input.onInput (http://localhost:4200/node_modules_ionic_core_dist_esm_ion-input_entry_js.js:124:20) 
```

**Comment by sean-perkins** [comment]
@spicemix appreciate you testing and verifying. This bug making it into v6.0.7 was my fault. I wasn't aware that the `setSelectionRange` API was only applicable to certain input types.

I'll likely be introducing tests to validate that no console errors happen in our examples (currently researching the best mechanism to handle this well). Goof-ups are always an opportunity to strengthen the process to prevent future ones!

**Comment by papagei-ma** [comment]
@sean-perkins the patch doesn't seem to fix the bug on Chrome :(. But on Safari it's fixed.

**Comment by papagei-ma** [comment]
@Santisosa404 yarn add @ionic/angular@6.0.8-dev.1644430127.1b9bb92  In case you have an ionic/angular app. I mean you can use this patch, until there is a stable release with the fix.

**Comment by MilotH2** [comment]
this happens with input type email also. 
I upgraded from 6.0.4 to 6.0.7, downgraded and trying different versions without success on this issue.

This happens only on Android and not on iOS.

Updating to 6.0.8-dev.1644430127.1b9bb92 it did the trick.

**Comment by ciccilleju** [comment]
same problem here: ionic 6.0.7 and email input field

![image](https://user-images.githubusercontent.com/42606234/153493796-e2abcebc-5ceb-45ba-95fb-9af629aba27c.png)

**Comment by philkonick** [comment]
I had the same problem with field type email, using 6.0.2 and Angular 13.2.2.

The 6.0.8-dev.1644430127.1b9bb92 branch fixed it for me.

**Comment by cromdev** [comment]
6.0.8-dev.1644430127.1b9bb92 fixed it for me as well, though I see other issue - on ion-input with type="number" pressing dot clears the input. Exactly same issue as here:  https://github.com/ionic-team/ionic-framework/issues/18864 
I was able to reproduce it both in desktop chrome and cordova based app on android.
Any chance it's connected with  latest changes?

**Comment by andreas-aeschlimann** [comment]
The bug appeared since 6.0.2, I encountered it with the e-mail input. Due to another bug (memory leak in modals, #24460) I strongly discourage from downgrading to <6.0.3.

I tried the dev build and it works for me.

**Comment by 1beb** [comment]
Same issue appears to be happening for `ion-input` with `type="date"`

**Comment by cromdev** [comment]
> 6.0.8-dev.1644430127.1b9bb92 fixed it for me as well, though I see other issue - on ion-input with type="number" pressing dot clears the input. Exactly same issue as here: #18864 I was able to reproduce it both in desktop chrome and cordova based app on android. Any chance it's connected with latest changes?

FYI, version 6.1.0-dev.202112152233.e254a3a solves both issues for me

**Comment by mariossavva** [comment]
This is not an issue on iOS 15 but the setSelectionRange does cause a side effect of setting the focus to the input box that the value changed even if it doesn't have focus. For example if you change dynamically the ngModel value of an input box that doesn't have focus it will automatically get focus. This was not an issue before.

**Comment by ltahiri** [comment]
same problem here: ionic 6.0.7 and email input field
![image](https://user-images.githubusercontent.com/10163615/153846437-12e0bea8-7f07-4bc8-a607-4377b27cb869.png)

**Comment by sean-perkins** [comment]
Hello everyone, here's an updated dev build to verify with: `6.0.8-dev.1644851030.7f38ebb`.

You can install it for your respective `@ionic/*` packages.  This dev build re-works the approach that required the `setSelectionRange` method to be used. It should resolve both the exception that developers are experiencing with 6.0.7 as well as fix the cursor position issues with dynamically setting the value on an input.

I will update my original comment above, so that anyone coming across this issue does not install the outdated dev build. Thanks!

**Comment by bggabriele** [comment]
I've got same error using ionic/vue on 
`<ion-input type="email"></ion-input>`

**Comment by ArcadeMode** [comment]
Dev build `6.0.8-dev.1644851030.7f38ebb` resolves the issue for me (angular). Before this version my ngModels on email and numeric fields would break too, the dev build resolves it.

**Comment by sean-perkins** [comment]
The PR to address this issue has been merged and will be available in 6.0.8 (tentative release date is Feb 16, this Wednesday).

Thank you everyone for testing the dev builds and organizing the conversation in this thread!

**Comment by ciccilleju** [comment]
Thank you so muco for your commitment

Il Lun 14 Feb 2022, 20:35 Sean Perkins ***@***.***> ha
scritto:

**Comment by sjdrew** [comment]
> > This is not an issue on iOS 15 but the setSelectionRange does cause a side effect of setting the focus to the input box that the value changed even if it doesn't have focus. For example if you change dynamically the ngModel value of an input box that doesn't have focus it will automatically get focus. This was not an issue before.
> > Can we make sure that the setSelectionRange is called only if the input has focus?
> 
> Since I updated to 6.0.8-dev, the focus of input fields is messed up when I programmatically change its value. For example, if I add 2 chars to an input when the user starts typing, the cursor will not stay at the end of the value but instead stay before the two added values like this:
> 
> Telephone: ________
> 
> User types a 0, I programmatically add +41 instead of the 0, the cursor | is like this now:
> 
> Telephone: +|41_____
> 
> Expected:
> 
> Telephone: +41|_____

I noticed same thing with that IOS fix it seems to rely on selectionStart/End and any directive like a phone number field on top of an ion-input is now not working as cursor position gets messed up.

**Comment by liamdebeasi** [comment]
Hi everyone,

A fix for this issue has been released as part of Ionic 6.0.8. Please update your apps to receive this fix.

Note: This issue only impacts Ionic 6. Ionic 4 and 5 apps are not impacted.

Thank you for your patience as we worked to resolve this issue.

**Comment by andreas-aeschlimann** [comment]
Thank you @liamdebeasi, do you know if https://github.com/ionic-team/ionic-framework/issues/24753#issuecomment-1038104285 is also fixed? I think it is related to or even caused in the same way as this issue.

**Comment by sean-perkins** [comment]
> Hello,
> 
> I am seeing the same issue in 6.18.1.
> 
> DOMException: An attempt was made to use an object that is not, or is no longer, usable
> 
> Thank you. E

@etiennebon the latest production release of Ionic is `6.0.10`. The code that was causing the original issue has been completely removed from the codebase.

Can you double check that you are on the latest version of Ionic dependencies?

Please feel free to open a new issue if you are able to create a reproduction of the problem.

Thanks!

**Comment by etiennebon** [comment]
Hello Sean,

Thank you.
Indeed, my version was not good:
 Ionic CLI                     : 5.4.16 
   Ionic Framework               : @ionic/angular 6.0.7
   
   I just upgraded and now everything goes very well.
   
Thank you very much for your quick response.

   Regards,
   Etienne.
