### ISSUE TITLE
feat: sheet style modal breakpoints should be reactive

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#24752]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The breakpoints of a sheet style modal should be reactive

### Describe the Use Case

Our Sheet has some breakpoints that should be only available in a specific state

### Describe Preferred Solution

The best solution would be a method `setBreakpoint` which takes the new breakpoints array and a new initalBreakpoint that is used only if the current breakpoint is not included in the new array.  

### Describe Alternatives

Just be able to set `this.modal.breakpoints = [...]`. The users then has to check by their self to maybe move to another breakpoint manually (via #24648)

**Comment by liamdebeasi** [comment]
Can you provide an example of the problem you are running into with the current behavior?

**Comment by EinfachHans** [comment]
Reassign the breakpoints from within the Modal like `this.modal.breakpoints = [...]` doesn't work, because the Gesture is not recreated

**Comment by liamdebeasi** [comment]
I understand the issue, but what is the use case for re-configuring the breakpoints?

**Comment by EinfachHans** [comment]
In our use case we have a Sheet with three different states. But depending on a specific condition (20 seconds left of an auction) we want to disable/skip one of these and only show the other two. 

I may should add that the content of the sheet depends on the current breakpoint

**Comment by liamdebeasi** [comment]
Thanks! Do you know of any native apps that have a similar behavior that we could follow?

**Comment by EinfachHans** [comment]
Honestly no 🤔 But guess it's possible and would be easy to add for users building similar use cases as mine

**Comment by liamdebeasi** [comment]
Thanks. Can you tell me more about your use case in https://github.com/ionic-team/ionic-framework/issues/24752#issuecomment-1034027495? I'm wondering if https://github.com/ionic-team/ionic-framework/issues/22297 with a card modal would be a better UI for this.

Sheet modals are very dynamic/temporary, so restricting both of those seem to go against what the sheet is designed for.

**Comment by DwieDima** [comment]
we also have a use case for our customer, where you go through an transaction (breakpoint 0.25) and more information (breakpoint 0.5) is only revealed, when user agrees to terms of service.

**Comment by liamdebeasi** [comment]
@DwieDima Are there any native apps you can think of that do this?

I talked more with the team and we still feel that the card modal with https://github.com/ionic-team/ionic-framework/issues/22297 is more appropriate given the dynamic nature of the sheet modal.

**Comment by ruiminxu** [comment]
@liamdebeasi Hey, I think if you were to use apple map and when you click on the search bar, the modal expand up reviewing more information. I think it is good to add something to interactive with the breakpoint.

**Comment by EinfachHans** [comment]
@liamdebeasi what do you say to my message? Thats not possible with a card style modal

**Comment by DwieDima** [comment]
@liamdebeasi i haven't found a native app which provides this functionality.
But if we were able to trigger modal position programmatically and also disable/enable drag gesture programmatically this would also be perfect.

Like @ruiminxu mentioned, in apple maps the sheet modal is set to 100% height, if you focus the searchbar. There is already a [PR](https://github.com/ionic-team/ionic-framework/pull/24648) for that.

i think there was also a feature request for disabling the sheet modal gestures programmatically, but havent found it.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I discussed this with the team, and we do not think that this feature is a good fit for Ionic.

We think that limiting breakpoints goes against the intention of how the bottom sheet is designed to work as it is a very dynamic component. In other words, being able to snap to `0.5` at one instance but not at another instance seems to be a confusing experience. Additionally, we were unable to find examples of native apps that do this, so it is hard to gauge exactly how this feature should work.

In terms of alternatives, we have a couple ideas.

1. Preventing a modal from being closed seems to be a common pain point here. This would be solved by https://github.com/ionic-team/ionic-framework/issues/22297 and is something we are interested in adding to Ionic.
2. Programmatically snapping to a breakpoint seems to be common as well. This would be solved by https://github.com/ionic-team/ionic-framework/issues/23917 and is also something we are interested in adding.

I am going to close this. Thanks!

**Comment by EinfachHans** [comment]
@sean-perkins okay, it's sad that this is not possible on native, but the "workaround" you provided would not look good in our solution. Also the question you had about changing the breakpoints  and the current one not beeing into the new breakpoints isn't really a thing ionic really need to think about. Just thro out a warning and the developers has to check that this not happens from their code 🤷🏼‍♂️

Let me describe one scenario in our app:

As said it's a app where you can bid on auctions. If you open an auction that you won but have not paid yet there is a sheet style modal with two breakpoints:

1. Shows information about the price, net, date, invoice, etc. 

2. additionally Shows the iban where you need to send the money to and also a "confirm" button

If you press this confirm button we show a toast and the sheet should move to the lower breakpoint again (possible through our pr from 6.1 now) - but then the user should not be able to enter the upper breakpoint again because he already send the money...

And there are more scenarios like this 😅

i understand that it may not be able in native **but** i also think it's a really small code change for a really cool feature!
