### ISSUE TITLE
bug: Datepicker can't change the month if the previously selected date belongs to the outside of available dates to select

### ISSUE THREAD

**Issue by Yura13** [ionic-team/ionic-framework#24756]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I can't change the date from 19 January to 9 February because navigation to next month doesn't work but the next month button is enabled.
![image](https://user-images.githubusercontent.com/17030431/153252439-0debeeaa-dc09-4ac3-ad2b-6dff13c8e7eb.png)

### Expected Behavior

I should be able to change the month.

### Steps to Reproduce

I've set a date to 19 January and saved it. User is able to change the date only during the current month (min date - the start of current month / max date - the end of current month)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\Xiaomi\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 13.1.3
   @angular-devkit/schematics    : 13.1.3
   @angular/cli                  : 13.1.3
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.5.1, (and 28 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm               : 8.1.2
   OS                : Windows 10

**Comment by sean-perkins** [comment]
@Yura13 thanks for reporting this issue!

I'm going to close and consolidate this issue with #24757. You can 👍  that issue to follow the activity.

Thank you!
