### ISSUE TITLE
bug: datetime month navigation blocked with min attribute

### ISSUE THREAD

**Issue by antoine92190** [ionic-team/ionic-framework#24757]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When I set a min date, for example `min="2022-02-09"`, the datetime picker opens correctly, and January is correctly disabled.
But if I navigate to march, I cannot go back to February.

https://user-images.githubusercontent.com/16256207/153254693-e2508753-aa73-4c89-96c3-79aa42f543b7.mov

### Expected Behavior

We should be able to go back to previous month as it is and was not disabled.

### Steps to Reproduce

- Add a min date to the datetime picker component
- Open the datetime picker
- Navigate to the next month
- Try to navigate back to the previous month => Not possible

### Ionic Info

Ionic:

   Ionic CLI                     : 6.12.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 12.2.4 (/Users/antoine/Dev/agorapulse/platform/frontend/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 11.2.18
   @angular/cli                  : 12.2.4 (/Users/antoine/Dev/agorapulse/platform/frontend/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI   : 3.2.4
   @capacitor/core : 3.2.4

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 1.5.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS
   Xcode  : Xcode 13.2.1 Build version 13C100

**Comment by sean-perkins** [comment]
@antoine92190 thanks for reporting this issue! I can replicate the same behavior in our `minmax` test file.

**Comment by sean-perkins** [comment]
Anyone that runs into this issue can temporarily use this dev build:
```
6.0.8-dev.1644432569.937206e
```

You can install it for your necessary package (react/vue/angular/core).

Thanks!

**Comment by antoine92190** [comment]
@sean-perkins Is it safe tu use the dev build in production?

**Comment by Yura13** [comment]
@sean-perkins 
Thanks! I am starting to use 6.0.8-dev.1644432569.937206e.
The is the same issue with the max attribute.

**Comment by Yura13** [comment]
The same bug is reproduced if use the max attribute.
```
<ion-popover class="popover-datepicker" trigger="open-date-input" show-backdrop="false" mode="md">
            <ng-template>
                <ion-datetime #popoverDatetime
                              hour-cycle="h12"
                              [showDefaultButtons]="true"
                              [minuteValues]="minuteValues"
                              [hourValues]="hourValues"
                              [min]="minStartsAt"
                              [max]="maxStartsAt"
                              mode="ios"
                              [value]="partialForm.get('schedule_time').value"
                              (ionChange)="setScheduleTime()"></ion-datetime>
            </ng-template>
        </ion-popover>
```
![datepicker-max-attribute](https://user-images.githubusercontent.com/17030431/154243095-75d44fa5-0677-4ea6-965e-b6bd7c196296.gif)

**Comment by philkonick** [comment]
This is still happening to me too, for min and max dates. Ionic Angular 6.0.11.
