### ISSUE TITLE
bug: ion-radio-group freaks out when removing elements

### ISSUE THREAD

**Issue by chrisspiegl** [ionic-team/ionic-framework#24761]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I have the following `ion-radio-group` with `ion-radio` and other `ion-input` elements:

```html
<ion-radio-group v-model="newShortPrimarySlugPath" @ionChange="submitSlugPrimary">
  <ion-item v-for="(slug, index) in shortSlugs" :key="index" fill="outline" class="ion-margin">
    <ion-radio slot="start" :value="slug.ref.path" />
    <ion-input type="text" :value="slug.ShortDomain.domain" />
    <ion-input type="text" :value="slug.slug" />

    <ion-button @click="submitDeleteSlug(slug)" slot="end" color="danger" :disabled="shortData.slugPrimary.refShortSlug.path === slug.ref.path">Delete</ion-button>
  </ion-item>
</ion-radio-group>
```

Everything works fine until I remove one of the `ion-item` elements via the `ion-button` to delete it.

When this is done, the `ion-radio` for some reason get's deselected and the `newShortPrimarySlugPath` is the value of the last `slug.slug` object (aka the last `ion-input`… despite that not being the `ion-radio`).

### Expected Behavior

I am expecting the `ion-radio-group` to only look at the values of the `ion-radio` and not at the `ion-input` elements.

### Steps to Reproduce

As described with the code example.

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/Users/chrisspiegl/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.5

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.13.0 (/Users/chrisspiegl/.nvm/versions/node/v16.13.0/bin/node)
   npm    : 8.1.3
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo I can use to verify this issue?

**Comment by chrisspiegl** [comment]
@liamdebeasi thanks for the response. I have somehow managed to get around this.

It had something todo with firebase objects in the stored in the `this` context of the vue component. Took me a while to figure this out.

But for now, it's cleared up and I will close this issue.
