### ISSUE TITLE
bug: R6.0.7 date-time default buttons in modal do not show on Android device

### ISSUE THREAD

**Issue by richardkshergold** [ionic-team/ionic-framework#24765]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The below code shows the two default buttons (Cancel and Done) on iOS but no buttons display on an Android device (testing on Pixel 4 running Android 12)

```
<ion-modal [trigger]="datetime">
        <ng-template>
          <ion-content force-overscroll="false">
            <ion-datetime
              showDefaultButtons="true"
              presentation="date"
              [formControlName]="option._id">
            </ion-datetime>
          </ion-content>
        </ng-template>
</ion-modal>
```

### Expected Behavior

Buttons should also show on Android (presumably?)

### Steps to Reproduce

Try the above code on Android

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/xxx/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 13.2.2
   @angular-devkit/schematics    : 13.2.2
   @angular/cli                  : 13.2.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : 3.4.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/Users/xxx/.nvm/versions/node/v16.13.0/bin/node)
   npm    : 8.1.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue. I cannot reproduce this on my end. Can you provide a GitHub repo I can use to verify this issue?

**Comment by richardshergold** [comment]
I’m off work for a week now so won’t be able to look at it - it’s definitely happening though!

**Comment by richardkshergold** [comment]
Just upgraded the app to 3.0.8 and this is definitely still happening on my Pixel 4 (Android 12) with this code:

 ```
<ion-modal [trigger]="option._id">
        <ng-template>
          <ion-content force-overscroll="false">
            <ion-datetime
              showDefaultButtons="true"
              presentation="date"
              [formControlName]="option._id"
              [class.invalid]="!isValid(option._id) && item.read !== 1"
              [class.valid]="isValid(option._id)">
            </ion-datetime>
          </ion-content>
        </ng-template>
      </ion-modal>
```

screenshot attache
![Screenshot_20220222-135853](https://user-images.githubusercontent.com/62251118/155149154-08c8c2dd-64b5-435b-9188-98937bdd8d39.png)
d

**Comment by richardkshergold** [comment]
This might be a styling issue on my side - I will investigate more

**Comment by richardkshergold** [comment]
Closing as I think it's a styling height issue
