### ISSUE TITLE
bug: users cannot log into app using Google Chrome  

### ISSUE THREAD

**Issue by burggraf** [ionic-team/ionic-framework#24778]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Starting with 6.0.2, users cannot log into my Ionic React app when using Google Chrome.

Chrome email/password autofill does fill out the email address and password, but does not trigger a page update so the underlying code that validates a minimum password length is not triggered, so the user can't press the "Login" button (since it is disabled, as the form does not pass validation).

**Even worse, if the user tries to type an email address and password manually, as soon as the user types in the password field, the email address field is cleared.  This behavior started in 6.0.2 and did not occur in 6.0.1.**

As it stands, on 6.0.2 and later, my users cannot log in.  6.0.1 is fine.

### Expected Behavior

Chrome auto-fill should correctly fill the email address and password fields, and the size of each field (length) should be updated correctly so form validation can validate that the email is valid and the password passes a minimum length check.

In addition, a user should be able to type in the email input and password input without the other field being cleared automatically.

### Steps to Reproduce

Here's the relevant code that works fine on 6.0.1 but fails on 6.0.2:

```
            <IonRow>
                <IonCol>
                    <IonLabel>Email Address</IonLabel>
                </IonCol>
            </IonRow>
            <IonRow>
                <IonCol>

                    <IonItem className="loginItem" lines="none">
                        <IonInput type="email"
                        placeholder="Email" 
                        onIonChange={e => setEmail(e.detail.value!)}
                        value={email} className="loginInputBoxWithIcon">
                        <IonIcon className="inputIcon" icon={mailOutline} slot="start" size="large" color="medium"></IonIcon>
                        </IonInput>
                    </IonItem>

                </IonCol>
            </IonRow>
            {!validateEmail(email) && email.length > 0 && 
                <IonRow>
                    <IonCol>
                        <IonLabel color="danger"><b>Invalid email format</b></IonLabel>
                    </IonCol>
                </IonRow>
            }
            <IonRow>
                <IonCol>
                    <IonLabel>Password</IonLabel>
                </IonCol>
            </IonRow>
            <IonRow>
                <IonCol>
                    <IonItem className="loginItem" lines="none">
                        <IonInput type="password" 
                        placeholder="Password" 
                        onIonChange={e => setPassword(e.detail.value!)}
                        value={password} className="loginInputBoxWithIcon">
                        <IonIcon className="inputIcon" 
                        icon={password.length ? lockOpenOutline: lockClosedOutline} 
                        slot="start" size="large" color="medium"></IonIcon>
                        </IonInput> 
                    </IonItem>
                    <div onClick={resetPassword} className="ion-text-right" style={{paddingTop:'10px'}}>
                        <IonLabel><b>Forgot password?</b></IonLabel>
                    </div>
                </IonCol>
            </IonRow>
            {password.length > 0 && password.length < 6 && 
                <IonRow>
                    <IonCol>
                        <IonLabel color="danger"><b>Password too short</b></IonLabel>
                    </IonCol>
                </IonRow>
            }

```

### Ionic Info

This is pretty irrelevant because I already narrowed this down to a specific Ionic version (6.0.2 and above) and I tested with several versions of node before filing this.
```
Ionic:

   Ionic CLI       : 6.18.1 (/Users/markb/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.1

Capacitor:

   Capacitor CLI      : 3.2.5
   @capacitor/android : 3.3.0
   @capacitor/core    : 3.3.3
   @capacitor/ios     : 3.3.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.0 (/Users/markb/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey


```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a sample GitHub repo I can use to verify this behavior?

**Comment by burggraf** [comment]
Here's a repo with a duplication of the issue:

https://github.com/burggraf/ionic-login-bug

**Comment by rdlabo** [comment]
This seem same issue: https://github.com/ionic-team/ionic-framework/issues/24753

my env is fixed by using ionic@6.1.0-dev.202112152233.e254a3a

**Comment by hatsantos** [comment]
I'm facing the same issue on my ionic angular app... @rdlabo  How can I use that version?

**Comment by rdlabo** [comment]
@hatsantos  

```bash
% npm i @ionic/angular@6.1.0-dev.202112152233.e254a3a
```

**Comment by Julien-Marcou** [comment]
Despite what the version numbering could tell us, the 6.1.0-dev (November 21, 2021)  is actually older than the 6.0.8-dev (February 9, 2022).

It probably is better to use the `6.0.8-dev.1644430127.1b9bb92` version instead of the `6.1.0-dev.202112152233.e254a3a` version and if fixed the problem for me.

**Comment by sean-perkins** [comment]
Hello all,

As mentioned directly above, the `6.1.0-dev.*` build is not the appropriate tag. This tag should not exist and is likely a result of a manual deploy or a test deploy to NPM.

If this issue overlaps with #24753, the most up-to-date build to test with is: `6.0.8-dev.1644851030.7f38ebb`. This version reverts the need to use `setSelectionRange`, which resulted in a variety of regressed behaviors with features that dynamically set the value of an input element. 

The PR for this dev build should be merged prior to this week's release and will be publicly available for 6.0.8. 

Thanks!

**Comment by amandaesmith3** [comment]
Hi folks, I gave the provided repo from [here](https://github.com/ionic-team/ionic-framework/issues/24778#issuecomment-1036675871) a try and it looks like things are resolved on the latest version of Ionic. @burggraf Could you confirm whether things look good on your end?

**Comment by burggraf** [comment]
Yes, 6.0.8 resolves the issue and it works great in production.  Thank you.

**Comment by amandaesmith3** [comment]
Excellent 👍 I'll go ahead and close this out then. Thank you for using Ionic!
