### ISSUE TITLE
feat: ion-datetime (ionic 5) behavior to ionic 6+

### ISSUE THREAD

**Issue by rodrigoguariento** [ionic-team/ionic-framework#24779]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add an option to bring back ion-datetime behavior from ionic 5 to Ionic 6+.

### Describe the Use Case

In Ionic 5 it was easy to manipulate date and time with ion-datetime. In Ionic 6 it became complex and difficult to manipulate date and time with ion-datetime, besides, it is not possible to faithfully reproduce the behavior of the ion-datetime of Ionic 5, making the end-user experience bad.

### Describe Preferred Solution

Despite the evolution of ion-datetime in Ionic 6, I suggest adding an option that brings back the ion-datetime behavior of Ionic 5. Both behaviors could work together?!

### Describe Alternatives

Rollback to ion-datetime Ionic 5?

### Related Code

Try this in Ionic 5 and Ionic 6:

```
<ion-content>
  <ion-item>
    <ion-label>default behavior</ion-label>
    <ion-datetime></ion-datetime>
  </ion-item>
</ion-content>
```

### Additional Information

Because of changes like this I find it difficult to convince my customers to use Ionic. No offense, but these are the words of my customers: "every upgrade is a surprise and that's why I can't trust it". Thank you for comprehension.

**Comment by sean-perkins** [comment]
Hello @rodrigoguariento thank you for voicing your concerns. 

We have no intention on bringing back the exact implementation of Ionic 5, into v6. That being said, if there are features that are missing or not functioning correctly, please open issues reporting those gaps.

When migrating from v5 to v6, it is advised to follow our migration guides:
- Guide: https://ionicframework.com/docs/intro/upgrading-to-ionic-6#datetime
- Sample apps demonstrating migrating: https://github.com/ionic-team/datetime-migration-samples

The big change from v5 to v6, is that we recommend using `date-fns` for formatting the dates. Prior to v6, we were repeating a lot of the functionality already covered by that library and with sub-par results. For the maintenance and stability of the eco-system, it was the best call. 

Major changes are big upgrades, including breaking changes. I'm unsure how to proactively respond to your customer complaints, other than you always have the option to stay on a previous version (we support critical issues on previous major releases for a relative long time to work through migrations). 

Is there specific issues you would like to discuss surrounding the v5 to v6 challenges?

**Comment by liamdebeasi** [comment]
A couple other things that might be helpful here:

1. While we do not have plans to bring back the exact Ionic 5 datetime implementation, we do have plans to bring back the wheel style picker (https://github.com/ionic-team/ionic-framework/issues/23981). The existing wheel picker was incompatible with the new datetime and we wanted to give it the proper development time to re-work it correctly.
2. We also have plans to introduce a "compact" style datetime (https://github.com/ionic-team/ionic-framework/issues/24402). This would let you render a button that would automatically present a date/time picker in an overlay. We think this will reduce the amount of boilerplate required to show datetimes in overlay components.

**Comment by rodrigoguariento** [comment]
Thank you very much for the clarification and understanding. I perfectly understand how our (dev) side works. I will apply our efforts to reproduce exactly the result that users used to have in version 5 regarding the use of ion-datetime, even if it causes delays in our planning. Anyway, here's my suggestion for future "big" updates like this one: keep the next version still compatible until the old behavior is completely eliminated, then we'll have time to fully resolve usability issues calmly and unhurriedly. Don't worry about our customers, we'll find a way to explain this to our commercial team, but I thought it was interesting to pass along the feedback of our efforts with the end user, because when we create something that the end user finds simple and easy to use, and uses daily, any change in habits generates a lot of stress. Above all, thanks for your work, you guys helped us a lot in app development, congratulations to the whole Ionic team for their creativity and effort.
