### ISSUE TITLE
bug: ionic 6  ionic-angular version  ionic-angular.metadata.json file    not exist 

### ISSUE THREAD

**Issue by 12ahmed12** [ionic-team/ionic-framework#24789]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

in ionic 5 and version before it  there  was a file add with installation for metadata to make it easy for coding and navigation ,tracing the exist html tags and ionic components for all templates like(ion-list , ion-row ) 
 that was helping to check if that temple is  exist or it just wrong 
or there is spelling mistakes to fix it or search about the correct one .
but when i created new ionic 6 project  i get ide error and warning about this html tags is unknown !  i keep searching and trying different ide like (VS code , phpstrom )  but all same behavior ! 
i searched about this metadata file in node modules but it didn't exist anymore and  no idea how to add it even hard copy it there didnt fix the issue 

### Expected Behavior

I believe it was easy while developing and coding to  check all the ionic html templets and components if it written correctly or something wrong  , and that metadata file was doing this part  for us ? 

### Steps to Reproduce

create new ionic 6 project 
open project with any ide  i try (VS code and Phpstorm ) 
 all html templets shown warning of unknown html tags  and no navigation for that html templets anymore .

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : not installed
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.0
   OS     : Windows 10

### Additional Information

![image](https://user-images.githubusercontent.com/14850196/154045466-6a5aa2b0-1b6b-4dc4-9d1d-fae72e2132fb.png)
![image](https://user-images.githubusercontent.com/14850196/154045708-fc692093-449a-4b67-ad2b-0b34046952b2.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide some additional steps for how I can reproduce this issue? I do not use VSCode or PHP/WebStorm, so I am not familiar with this functionality.

**Comment by indraraj26** [comment]
This is causing due to one of your extension.

**Comment by 12ahmed12** [comment]
@indraraj26 @liamdebeasi   how could it be ? 
it only happened in new projects  (ionic 6)  i check both ide extensions to see if there is something missing  but nothing , 
same ide with old versions  project work normally  the only different i found from searching and investigation is that metadata file not exist , i don't know but how could extension work with one app and not work with another ! 

![image](https://user-images.githubusercontent.com/14850196/154078525-14944a88-f043-484d-8ca5-59ac3c2fa0b8.png)
![image](https://user-images.githubusercontent.com/14850196/154078606-14a4eb41-9c40-41b9-a97f-aa55f857f1dd.png)

**Comment by 12ahmed12** [comment]
@liamdebeasi   thanks for your answers and your time  , i don't have specific repo to share it just happen even with empty new projects  
don't know if that metadata isn't  important  but what tell ide about ionic templets or angular directives for autocomplete or correcting  ? and  if I may ask you about the editor  recommended for ionic ?

**Comment by mhartington** [comment]
@12ahmed12 so this happens with every project you create? How are you creating these projects? If you can recreate it a new project and push that to github, we can look into this more.

**Comment by 12ahmed12** [comment]
@mhartington  i created GitLab repo 
HYG
https://gitlab.com/ahmedgaber/empty-ionic6

**Comment by mhartington** [comment]
So I'm not sure what I should be looking for, but in a vscode instance with no extension, everything appears to be working as expected.

I don't have Webstorm or use it, but I don't expect there to be any issues in there either.

**Comment by 12ahmed12** [comment]
@mhartington  ok sir , thanks for your time investigating   i really appreciated  , anyway  I will try different ide maybe its ide related issue , but the thing I don't understand is why old versions  or old project work normally !   thanks .
