### ISSUE TITLE
bug: (iOS) Relaunching app and tapping ion-menu freezes app TypeError: undefined is not an object (evaluating 'this.menuInnerEl.offsetWidth')

### ISSUE THREAD

**Issue by christopherdiuyan** [ionic-team/ionic-framework#24787]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

After the app is installed in the simulator/device the ion-menu is working fine, but after relaunching the app and tapping the ion-menu is not responding anymore and throws an error: `TypeError: undefined is not an object (evaluating 'this.menuInnerEl.offsetWidth')`

### Expected Behavior

After relaunching the app I should be able to tap the ion-menu and display the sidebar menu

### Steps to Reproduce

1. Create a sample app
2. **app.component.html** code
```typescript
<ion-app>
    <ion-router-outlet id="main-content"></ion-router-outlet>
</ion-app>
```

3.  **sidebar.component.html** code as widget component under shared module
```typescript
<ion-menu side="end"
      swipeGesture="true"
      type="overlay"
      contentId="main-content"
      class="sidebar-container"
      menuId="sidebarId">

     <ion-header>
        <ion-toolbar>
            <ion-img src="/assets/icons/side-bar/side-bar-logo.svg"></ion-img>
        </ion-toolbar>
    </ion-header>
</ion-menu>
```

4.  **main.component.html** code
```typescript
<app-sidebar menuId="sidebarId"></app-sidebar>
<div>
  <ion-header class="header">
     <ion-button slot="start">
        <ion-menu-button></ion-menu-button>
      </ion-button>
  </ion-header>
</div>
```

5. After building and installing the app in the simulator/device and tap the menu icon
6. Sidebar will show
7. If I close the app/terminate and open it again
8. Tap the menu icon, and the app got froze

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1
   Ionic Framework               : @ionic/angular 5.6.10
   @angular-devkit/build-angular : 0.1102.5
   @angular-devkit/schematics    : 11.2.5
   @angular/cli                  : 11.2.5
   @ionic/angular-toolkit        : 3.1.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.5.0)   : 1.4.1

System:

   NodeJS : v14.17.6 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.15
   OS     : Windows 10

**Comment by davebanguilan** [comment]
I'm experiencing that too. I have an `@ionic/angular 5.6.9`. There's a lot of suggested solution online but none of it works for me. I hope this will get sorted out.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo I can use to reproduce this issue? I am not able to reproduce this behavior on my end.
