### ISSUE TITLE
bug: ion-textarea autogrow with long text

### ISSUE THREAD

**Issue by tetkosimi** [ionic-team/ionic-framework#24793]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

When textarea contains long text, and auto-grow function is turned on, a big gap remains at the bottom of textarea. The gap is getting bigger as the text gets longer.

### Expected Behavior

Calculate the size of the content properly, even for long texts.

### Steps to Reproduce

1. Clone the [repo](https://github.com/tetkosimi/bug-ionic-textarea) below and run `npm i`

2. Start the project and open in desktop resolution. (It was tested on Google Chrome).

3. Scroll to the bottom of page.

4. You can write edit the content of textarea, the gap will remain.

### Code Reproduction URL

https://github.com/tetkosimi/bug-ionic-textarea

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.2.9
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI   : 3.2.4
   @capacitor/core : 3.2.4

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run (update available: 1.5.0)   : 1.4.1

System:

   NodeJS : v16.13.0 (/home/bekkeri/.nvm/versions/node/v16.13.0/bin/node)
   npm    : 8.1.0
   OS     : Linux 5.10
```

### Additional Information

I think, an `overflow-y` on the native textarea would be enough to solve this issue, as you can see on the right in the example.

**Comment by tetkosimi** [comment]
Hi @sean-perkins, here's a screenshot:
[https://github.com/tetkosimi/bug-ionic-textarea/blob/main/screenshot.png](https://github.com/tetkosimi/bug-ionic-textarea/blob/main/screenshot.png)

You're right, I just checked this issue on macOS with the latest Google Chrome and also couldn't reproduce, but I can still reproduce it on Window 10 with the latest Google Chrome.

**Comment by tetkosimi** [comment]
I've also checked on Windows 10 with Firefox, and the big gap is there, however I can't reproduce it on Android.

It seems like this is just some kind of native scroll or scrollbar related issue on Windows.

**Comment by tetkosimi** [comment]
I've tried the dev build and it resolves the issue on Windows too.
Nice job, thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24205 and a fix will be available in an upcoming release of Ionic.
