### ISSUE TITLE
bug: select is not defining popover which causes it to not show in production builds

### ISSUE THREAD

**Issue by HipyCas** [ionic-team/ionic-framework#24807]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The  `ion-select` does not work in android after updating the version of Ionic to 6.0.8. It works on web and displays the current value. Also, no error is risen when interacting with the popover, the item has the ripple effect which means it detects the tap, but the select does no trigger.

### Expected Behavior

Simply work as the select should, showing the popover and letting me select

### Steps to Reproduce

Create a Vue Ionic project with Ionic v6.0.8. Create a select element with popover style, which in my case renders elements dinamically with a v-for instruction, wrapped inside an `ion-item` with a label. You should see that it doesn't work on Android, though it does on web.

### Code Reproduction URL

https://github.com/biocienciasgrx/ceebi/tree/v0.6.5-alpha (package.json shows a different version, as it is not updated in the repository

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/home/hipy/.nvm/versions/node/v16.4.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.8

Capacitor:

   Capacitor CLI      : 3.3.2
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.2
   @capacitor/ios     : 3.3.3

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v16.4.1 (/home/hipy/.nvm/versions/node/v16.4.1/bin/node)
   npm    : 7.20.2
   OS     : Linux 5.15

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue6.0.9-dev.1645109128.222168b @ionic/vue-router@6.0.9-dev.1645109128.222168b
```

**Comment by wsamoht** [comment]
I just came across this issue as well. I tried installing the dev version to test that you linked @liamdebeasi but npm says it is not found.

**Comment by wsamoht** [comment]
I've confirmed that the dev version does fix this on Android (emulator) when built for prod.

**Comment by liamdebeasi** [comment]
Thanks for testing! Also whoops, sorry about the typo 😅
