### ISSUE TITLE
bug: when opening ion-datetime within a ion-modal it will create an infinite number of pages

### ISSUE THREAD

**Issue by MNFreundT** [ionic-team/ionic-framework#24809]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When opening `ion-datetime` within a `ion-modal` it will create an infinite number of pages.

When opening the datepicker, a page is created in the DOM, but it is not removed from the DOM when the datepicker is closed. Each time the Datepicker is opened, an infinite number of pages can be created. Due to these many pages, visual bugs continue to arise within the datepicker
![Bug](https://user-images.githubusercontent.com/99644321/154485287-b122d81e-8e0c-43e0-b33e-69720f6f0f67.png)
.

### Expected Behavior

After the datepicker has been opened, a page should be generated. If you click in the empty space, the created page should be removed from the DOM.

### Steps to Reproduce

1. Clone the Repository
2. Run the Project with ionic serve
3. watch the small video

https://user-images.githubusercontent.com/99644321/154482985-1f933043-d9cc-4e6d-9813-80f168e2ecf2.mp4

### Code Reproduction URL

https://github.com/MNFreundT/ion-datetime

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : not installed
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.19.0 (/usr/bin/node)
   npm    : 6.14.16
   OS     : Linux 5.10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.0.9-dev.1645113595.6f48cc2
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/24811, and a fix will be available in an upcoming release of Ionic Framework.

Please feel free to continue testing, and let me know if you run into any issues.
