### ISSUE TITLE
bug: Swipe gesture (left to right) on overlay menu not working after showing a modal

### ISSUE THREAD

**Issue by MawsFr** [ionic-team/ionic-framework#24817]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Hello,

I have a splitpane with a menu that I can open with a swipe gesture (left to right) . In the content of the splitpane I have a button that opens a modal. When I open the modal and I close it (manually or with the backdrop), I can't open the menu with the swipe gesture anymore.

### Expected Behavior

I would like to still be able to open the menu with the swipe gesture even after closing the modal.

So what I expect (Without the workaround I found) :
- [Go here](https://dashboard.ionicframework.com/preview/134aecb4/p5ozjlwzv6)
- Swipe from left to right to show the menu
- Swipe right to left to hide it
- Click on "open modal"
- Click on "close modal and remove show-modal class
- Be able to swipe the menu like here

### Steps to Reproduce

- [Go here](https://dashboard.ionicframework.com/preview/134aecb4/p5ozjlwzv6)
- Swipe from left to right to show the menu
- Swipe right to left to hide it
- (Until here the menu works fine)
- Click on "open modal"
- Close it by any mean (button "close modal" or backdrop or swipe down)
- Try to open the menu with the swipe gesture
- => Not working anymore

### Code Reproduction URL

https://github.com/MawsFr/test-modal-with-menu-swipe-gesture

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'
       
       Require stack:
       -
       /Users/maws/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli/lib/project/index.js
       -
       /Users/maws/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli/lib/index.js
       -
       /Users/maws/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli/index.js
       -
       /Users/maws/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package'
       
       Require stack:
       -
       /Users/maws/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli/lib/project/index.js
       -
       /Users/maws/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli/lib/index.js
       -
       /Users/maws/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli/index.js
       -
       /Users/maws/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.18.1 (/Users/maws/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.8

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : not installed
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v12.18.3 (/Users/maws/.nvm/versions/node/v12.18.3/bin/node)
   npm    : 6.14.6
   OS     : macOS Mojave
```

### Additional Information

I looked up the ionic framework code and noticed that when we open the modal we add the `show-modal` class to the modal but when we dismiss it we do not remove it and when I remove it manually from the DOM I can open the menu again.

And In the menu component we tell it to ignore swipe gestures if there is a modal with the `show-modal` class.

https://github.com/ionic-team/ionic-framework/blob/928c5fbfcbf3ef1b2c3074464fc20dcf1fe143ae/core/src/components/modal/modal.tsx#L373

https://github.com/ionic-team/ionic-framework/blob/632dafcd57de5086deebdc7d586b01710aa1a3ce/core/src/components/menu/menu.tsx#L459-L462

I found a workaround which is to manually remove the show-modal class on the didDismiss callback
```ts
const onDidDismiss= () => {
      modal.value.$el.classList.remove("show-modal");
    };
```

**Comment by sean-perkins** [comment]
@MawsFr thanks for reporting this issue. It appears the link to your repository is unavailable. Can you make sure that it is public?

Thanks!

**Comment by MawsFr** [comment]
Sorry ^^" Done !

**Comment by sean-perkins** [comment]
@MawsFr awesome, thanks! I'm able to reproduce on my end. 

Appreciate the extra triaging you did to narrow the `.show-modal` class behavior. Liam's out on vacation today, but tomorrow I'll connect with him and discuss any implications I'm unaware of with simply removing the class when the modal is dismissed.

Thanks!

**Comment by MawsFr** [comment]
No problem I totally understand ;) As you I don't know what are the side effects, otherwise I would have made a pull request ^^

**Comment by sean-perkins** [comment]
Hello @MawsFr can you test with this dev build in your project and let me know if you run into any issues?

```
npm i @ionic/vue@6.0.10-dev.1645727760.16b0a89
```

I've confirmed that it resolves the issue in your reproduction app. 

Thanks!

**Comment by MawsFr** [comment]
Hello @sean-perkins I tested your version and it seems to be working !
I removed all workarounds I did on my app and and I can't reproduce the bug so it's good for me :)

Thanks for the quick fix !

**Comment by sean-perkins** [comment]
Awesome, thanks for confirming 👍  I'll let the team know while reviewing the PR.
