### ISSUE TITLE
bug: lifecycle events do not fire in footer

### ISSUE THREAD

**Issue by Webrow** [ionic-team/ionic-framework#24824]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

ion lifecycle events do not fire in footer

### Expected Behavior

they should fite

### Steps to Reproduce

Checkout repo, click the buttons at the bottom. There should be multiple statements, the second.page.ts has working lifecycle events. The footer (which is in the ion-router, but outside the content, as stated per documentation) does not fire events. 

### Code Reproduction URL

https://github.com/Webrow/footer-no-events.git

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\rdegraaf\AppData\Roaming\nvm\v16.13.1\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.8
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : not installed
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.2
   OS     : Windows 10

### Additional Information

It could be that I am misinterpreting the documents. Id like to use the events to keep track of on "which"  page I am by giving a color to the icons on the footer bar.

**Comment by sean-perkins** [comment]
@Webrow the `ion` lifecycle events will only fire for routed page components.

This means that in your reproduction app example, the life cycle events will fire when navigating between:
- `/home` -> `/second` (both home and second page will fire life cycle events)

The internal components to your pages will only fire the respective lifecycle events of your framework, such as in your case since it is Angular, they will fire `ngOnInit`, `ngAfterViewInit`, `ngOnChanges`, `ngOnDestroy`, etc.

Does this help answer your question?

**Comment by Webrow** [comment]
@sean-perkins  Thank you for your reply. 
I understand it, I solved it in my case by passing an input value from the page (I wanted to know which of the buttons was active).
