### ISSUE TITLE
bug: datetime do not persist selected value after month change

### ISSUE THREAD

**Issue by antoine92190** [ionic-team/ionic-framework#24823]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

After selecting a date in the calendar, then changing month without selecting a new date and confirm using `this.datetime.nativeEl.confirm();` to confirm the value, the date value is correct, but the month value is the one from the month currently displayed, not the one we selected.

https://user-images.githubusercontent.com/16256207/154930505-ccce7b0e-24b1-47f6-a4eb-cfcc443e1691.mov

### Expected Behavior

The selected day should be kept even if we are navigating through months.

### Steps to Reproduce

- Select the last day of a month (28 February) then swipe to next month (March) without selecting any date.
- Confirm the date using `this.datetime.nativeEl.confirm()`
- The selected date is `28 March` instead of `28 February`

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/antoinedupont/.npm-packages/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.8-dev.1644432569.937206e
   @angular-devkit/build-angular : 12.2.4 (/Users/antoinedupont/dev/agorapulse/platform/frontend/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 11.2.18
   @angular/cli                  : 12.2.4 (/Users/antoinedupont/dev/agorapulse/platform/frontend/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : 3.2.4
   @capacitor/core    : 3.2.4
   @capacitor/ios     : 3.2.4

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Monterey
   Xcode  : Xcode 13.2.1 Build version 13C100
```

**Comment by sean-perkins** [comment]
Hello @antoine92190 thanks for reporting this issue! 

I have an open PR to address the issue causing this bug (#24827). When confirming the date selection, we were incorrectly using the visible calendar date instead of the selected calendar date.

I've created a dev build, if you would like to test and confirm the problem is resolved on your end:

```
6.0.9-dev.1645468846.3ebb3ac
```

You can install any of the `@ionic/*` packages with the dev build (excluding SSR packages). 

Thanks!

**Comment by antoine92190** [comment]
Yes the issue seems to be fixed in the dev build. Thanks!
