### ISSUE TITLE
bug: router popstate does not work with hooks

### ISSUE THREAD

**Issue by vicb** [ionic-team/ionic-framework#24831]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

## First scenario (S1):
1) you are on `/page1`
2) you go to `/page2`
3) you setup the `beforeEnter` hook of page1 to return `false` (to block the navigation)
4) you hit the browser back button
5) you will see the page2 (component are not updated) but the url is `/page1`

## Second scenario (S1):
1) you are on `/page1`
2) you go to `/page2`
3) you setup the `beforeEnter` hook of page1 to return `{redirect: '/page3'}` (to redirect to page3)
4) you hit the browser back button
5) you will see the page3 (redirect works) but the url is `/page1`

### Expected Behavior

The history and URL must be updated according to the hook return value.

I'll submit a PR that fixes the 2 scenarios above (with an e2e test case for each of the scenarios)

### Steps to Reproduce

See current behavior

### Ionic Info

n/a

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo we can use to verify this behavior?
