### ISSUE TITLE
bug: Backdrop not visible in fixed height sheet modal with backdropBreakpoint value of 1

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#24834]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Hi, If the maximum height of the Sheet Modal is not 100% the backdropBreakpoint attribute does not work and you cannot interact with what is below the modal.

### Expected Behavior

When ion-modal has a height in the css, it should let it interact with the part below.

### Steps to Reproduce

Create a Sheet Modal and put a height in the css, then put backdropBreakpoint on it to try to interact with the part below.

### Code Reproduction URL

https://stackblitz.com/edit/ionic-angular-v5-ub95tq?file=src%2Fapp%2Fapp.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.0.8
   @angular-devkit/build-angular : 13.2.4
   @angular-devkit/schematics    : 13.2.4
   @angular/cli                  : 13.2.4
   @ionic/angular-toolkit        : 6.0.0

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : 3.4.1
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2
   npm    : 8.5.1
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Hello @Marius-Romanus,

Sheet modal heights are controlled through the breakpoints, which allows the modal to display at a specific height, but still have gesture interactivity to "move" the sheet with it snapping to the correct breakpoint. 

In your usage example, is there a reason or use case where you cannot do this:

```html
<ion-modal
  [isOpen]="true"
  [breakpoints]="[0, 0.3]"
  [initialBreakpoint]="0.4"
  [showBackdrop]="false"
  [backdropDismiss]="false"
  [backdropBreakpoint]="1"
>
```

Manually setting the height of the modal through the CSS variable, seems like it would directly conflict with the mentality of how breakpoints are consumed.

**Comment by Marius-Romanus** [comment]
Hello, I have it like this because of @liamdebeasi answer in this issue:
https://github.com/ionic-team/ionic-framework/issues/24631#issuecomment-1021422042

**Comment by sean-perkins** [comment]
@Marius-Romanus thanks for the link. Discussed with the team and this indeed is a bug. 

In the interim you can set `backdropBreakpoint` to `0.99` to workaround this issue.

We will track this and prioritize. Thanks!

**Comment by Marius-Romanus** [comment]
Hello, it seems that this https://github.com/ionic-team/ionic-framework/pull/24798 has solved what I was referring to, now it allows you to interact with the part below. Thanks

**Comment by liamdebeasi** [comment]
Here is a dev build for #24798. Can you test it in your app and let me know if this resolves the issue?

```
6.0.10-dev.11646065555.9e09175
```

**Comment by Marius-Romanus** [comment]
> Hello, it seems that this #24798 has solved what I was referring to, now it allows you to interact with the part below. Thanks

Yes, everything works as expected in version 6.0.10. Thank you very much!
