### ISSUE TITLE
bug: Ion datetime max time don't work in France during winter time

### ISSUE THREAD

**Issue by pseudooriginal** [ionic-team/ionic-framework#24849]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

In France during winter time, ISO date 2022-02-25T09:19:51.000Z is Fri Feb 25 2022 10:19:51 GMT+0100 in GMT, but the time picker is locked to 9:19 instead of 10:19 with 2022-02-25T09:19:51.000Z ISO max date.

### Expected Behavior

Max time should be 10:19.

### Steps to Reproduce

Try to select time in stackblitz repro.

### Code Reproduction URL

https://stackblitz.com/edit/angular-ivy-63u9i2?file=src/app/app.component.html

### Ionic Info

[@angular/animations](https://www.npmjs.com/package/@angular/animations)
13.2.4

[@angular/common](https://www.npmjs.com/package/@angular/common)
13.2.4

[@angular/compiler](https://www.npmjs.com/package/@angular/compiler)
13.2.4

[@angular/core](https://www.npmjs.com/package/@angular/core)
13.2.4

[@angular/forms](https://www.npmjs.com/package/@angular/forms)
13.2.4

[@angular/platform-browser](https://www.npmjs.com/package/@angular/platform-browser)
13.2.4

[@angular/platform-browser-dynamic](https://www.npmjs.com/package/@angular/platform-browser-dynamic)
13.2.4

[@angular/router](https://www.npmjs.com/package/@angular/router)
13.2.4

[@ionic/angular](https://www.npmjs.com/package/@ionic/angular)
6.0.9

[@types/moment](https://www.npmjs.com/package/@types/moment)
2.13.0

[moment](https://www.npmjs.com/package/moment)
2.29.1

[rxjs](https://www.npmjs.com/package/rxjs)
7.5.4

[tslib](https://www.npmjs.com/package/tslib)
2.3.1

[zone.js](https://www.npmjs.com/package/zone.js)
0.11.4

**Comment by pseudooriginal** [comment]
This bug seems to be inside this method : https://github.com/ionic-team/ionic-framework/blob/836c01c73e42caab0101ac4988f0a9b27cf96a5b/core/src/components/datetime/utils/parse.ts#L53

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify what the issue is? `ion-datetime` intentionally does not look at timezones and only renders the value you give it. It is up to the developer to ensure `ion-datetime` gets a timezone-aware value.

**Comment by pseudooriginal** [comment]
So I need to give it a value without timezone offset infos and not UTC. So the format should be `2022-02-25T09:19:51.000+01:00`.
Thank you for the informations.

**Comment by liamdebeasi** [comment]
We also added new info to our docs to make this behavior clearer. There is also a code sample you can use in your apps: https://ionicframework.com/docs/api/datetime#time-zones
