### ISSUE TITLE
bug: ENOENT-bug with libraries on Ionic 6 

### ISSUE THREAD

**Issue by villepaananen** [ionic-team/ionic-framework#24848]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Libraries ([Ionic storage](https://github.com/ionic-team/ionic-storage), [Capacitor Radar](https://github.com/radarlabs/capacitor-radar), [Capacitor Community Camera Preview](https://github.com/capacitor-community/camera-preview)) don't load correctly. For Ionic Storage, `ionic serve` gives an error:
```
[react-scripts] Failed to parse source map from 'C:\Users\USER\Desktop\FOLDER\ionic-6-testing\node_modules\@ionic\storage\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\USER\Desktop\FOLDER\ionic-6-testing\node_modules\@ionic\storage\src\index.ts'
```

### Expected Behavior

In Ionic 5 the same process doesn't produce an error and the libraries work.

### Steps to Reproduce

```
ionic start bug-testing blank --type=ionic-react
cd bug-testing
npm install @ionic/storage
```

Add the following line to Home.tsx:
```
import { Storage } from "@ionic/storage";
const store = new Storage();
```

### Code Reproduction URL

https://github.com/villepaananen/ionic-6-enoent-error

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.0.9

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : not installed
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.2
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks! I am going to move this to the @ionic/storage repository.

The problem here is that Ionic React 6 uses `react-scripts@5`. This new version of react-scripts has sourcemap parsing enabled and will log a warning when no sourcemaps are found for a library. This did not happen in Ionic React 5 as that version required `react-scripts@4` which did not have sourcemap parsing.

Since this is a warning, it should not impact your ability to build/compile applications. I get the following warning on build, but the build completes successfully:

```
Creating an optimized production build...
Compiled with warnings.

Failed to parse source map from '/Users/liamdebeasi/Ionic/ionic-6-enoent-error/node_modules/@ionic/storage/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/liamdebeasi/Ionic/ionic-6-enoent-error/node_modules/@ionic/storage/src/index.ts'
```

**Comment by liamdebeasi** [comment]
I can't seem to transfer the issue at the moment, so I am going to close this in favor of https://github.com/ionic-team/ionic-storage/issues/247. Please follow that thread for updates on this issue. Thanks!
