### ISSUE TITLE
feat: cancelled swipe-back gesture should emit event

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#24854]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently when you start swiping back the `ionViewWillDismiss` will be emitted immediately. If you complete the gesture the `ionViewDidDismiss` is called and everything is fine, but if you cancel the gesture no more event or something is emitted, so i don't know if the gesture is still in process or cancelled.

In the [Ionic Lifecycle Documentation Page](https://ionicframework.com/docs/angular/lifecycle) it says:

> ionViewWillLeave - Can be used for cleanup, like unsubscribing from observables. 

This is then not optimal, because if you unsubscribe everything and the user cancels the gesture and stays on the page, the logic will be broken

### Describe the Use Case

In my case i have a sheet style modal with backdrop breakpoint, so it kinda belongs to the page. I still think it would be best if the swipe back and destroy of the page would also destroy the modal, but i remember liam said this is not indent how it should work. So i want to hide the modal in `ionViewWillLeave`, but then i have to show it again if the gesture is cancelled!

### Describe Preferred Solution

Maybe call `ionViewWillEnter` and `ionViewDidEnter` again? Or add a new Event?

**Comment by EinfachHans** [comment]
Yes that would be exactly what i meant 😃 In the best case this should be added to ionic build in gestures, so if you swipe back or navigate back the modal (added as a child of the page) should also move to bottom and dismiss with it. Also when you navigate forward the new page should be over the modal. For this part i currently have a workaround by dismissing the modal before navigating forward and showing it again on going back.

**Comment by liamdebeasi** [comment]
Great. I will close this in favor of https://github.com/ionic-team/ionic-framework/issues/24198 and will track progress there. I don't have a timeline for when this will be implemented, but I will post any updates on that thread.
