### ISSUE TITLE
bug: Image in Header not showing in centre in MD mode and Cutting in IOS Mode. 

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/ionic-framework#24864]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Using image in ion-header not showing / aligning correctly. 

### Expected Behavior

Image should show Correctly in ion-header

### Steps to Reproduce

```
<ion-header class="ion-no-border">
      <ion-toolbar mode="ios" class="tbar">
        <ion-buttons slot="start">
          <ion-button>
            <ion-icon name="arrow-back-outline"></ion-icon>
          </ion-button>
        </ion-buttons>
        <ion-title class="ion-text-center">
          <img
            src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
            class="head-img"
          />
        </ion-title>
      </ion-toolbar>
    </ion-header>
```

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-pvb8ty?file=src/app/app.component.html

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/fahadaslam/.nvm/versions/node/v16.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.2
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.4
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : 3.4.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/Users/fahadaslam/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey
```

### Additional Information

Check Stackblitz

**Comment by liamdebeasi** [comment]
Thanks for the issue. `ion-title` is only intended for a text title, not an image.

Removing the `ion-title` and adding `display: flex` and `margin: 0 auto` to the `img` fixes the issue. Can you give that a try?

**Comment by shahzeibali** [comment]
> Thanks for the issue. `ion-title` is only intended for a text title, not an image.
> 
> Removing the `ion-title` and adding `display: flex` and `margin: 0 auto` to the `img` fixes the issue. Can you give that a try?

I tried it but still same issue. in MD mode it is still not centred. can you fork stackblitz and make example
