### ISSUE TITLE
bug: Buttons inside IonModal are not clickable

### ISSUE THREAD

**Issue by rimonnassory** [ionic-team/ionic-framework#24875]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I have created a simple Bottom Sheet Modal that has a single button. 

`<IonPage>

      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab 1</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
          <IonButton onClick={() => setOpenModal(true)}>Open Sheet Modal</IonButton>
          <IonModal isOpen={openModal} onDidDismiss={() => setOpenModal(false)} breakpoints={[0.2, 0.5, 1]} initialBreakpoint={0.5} backdropBreakpoint={0.2}>
              <Modal dismiss={() => setOpenModal(false)}/>
          </IonModal>
      </IonContent>
    </IonPage>
`

This is my Modal component

` <IonContent>
    
    <IonHeader translucent>
            <IonToolbar>
                <IonTitle>
                    Sheet modal
                </IonTitle>
                <IonButtons slot="end">
                    <IonButton onClick={() => props.dismiss}>Close</IonButton>
                </IonButtons>
            </IonToolbar>
        </IonHeader>
    </IonContent>
`

Nothing happens when I click on the button

### Expected Behavior

Click on the button should dismiss the Modal

### Steps to Reproduce

1. Click on the button to open the Modal sheet
2. Click on close button to dismiss Modal sheet

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1
   Ionic Framework : @ionic/react 6.0.10

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : not installed
   @capacitor/core    : 3.3.1
   @capacitor/ios     : 3.3.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v12.22.0
   npm    : 6.14.11
   OS     : macOS Big Sur

**Comment by lukegardiner** [comment]
I have this issue too. Modals that worked fine in ionic v5 now don't work in v6

**Comment by rimonnassory** [comment]
It turns out I forgot to wrap my routing in <IonApp></IonApp> after upgrading to Ionic 6.
