### ISSUE TITLE
feat(AnimationController):  intercept ngOnDestroy

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#24893]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I'm not sure if this is possible, but my current use-case is to create a animation using `AnimationController` inside a directive, where the the parent provides the view.

- inside the directive the animation should call `animation.play()` inside `ngOnInit()`
- inside the directive the animation should call `animation.direction('reverse').play()` inside `ngOnDestroy()` 

Before i was using Angular animations where i define a trigger for `:enter` and `:leave` animation which works as expected. Since `:leave` trigger before `ngOnDestroy`, the animation will execute.
This behaviour doesn't fit for AnimationController.

### Describe the Use Case

The ability to call Animations before the View get destroyed, so you can use the animationController like the angular Animations with `:enter` and `:leave`

### Describe Preferred Solution

**directive.ts**
```typescript

import { Directive, ElementRef, Input, OnDestroy, OnInit } from '@angular/core';
import { Animation } from '@ionic/angular';

@Directive({
  selector: '[customAnimation]',
})
export class AnimationDirective implements OnInit, OnDestroy {
  @Input('customAnimation') private animation: Animation;

  public constructor(private elementRef: ElementRef) {}

  public async ngOnInit(): Promise<void> {
    const element = this.elementRef.nativeElement;
    await this.animation.addElement(element).play();
  }

  public async ngOnDestroy(): Promise<void> {
    await this.animation.direction('reverse').play();
  }
}
```
**page.ts**
```typescript
...

public show = true;
public fadeInTopAnimation: Animation;

constructor(private animationController: Animationcontroller) {}

ngOnInit() {
    this.fadeInTopAnimation = this.animationController
      .create('fadeInTop')
      .duration(1000)
      .easing('ease-out')
      .fromTo('opacity', 0, 1)
      .fromTo('transform', 'translateY(-50%)', 'translateY(0)');
}

public toggleShow() {
  this.show = !this.show;
}
...
```

```html
<ion-button (click)="toggleShow()">toggle<ion-button>
<div *ngIf="show" style="height: 200px; width: 100%; background: red" [customAnimation]="fadeInTopAnimation">
   <p>The Content</p>
</div>
```

### Describe Alternatives

Using Angular animations

### Additional Information

The provided code works if you initially call the page and `show` is set to `true`. If you call `toggleShow()` multiple times, the animation will break.
[Documentation](https://angular.io/guide/transition-and-triggers#use-of-ngif-and-ngfor-with-enter-and-leave) for `:enter` and `:leave`

**Comment by liamdebeasi** [comment]
I am not aware of any public Angular API that lets us tap into this, so I do not think this can be easily done. I found this article that allegedly does a leave animation with a 3rd party library: https://dev.to/nicolalc/gsap-animations-in-angular-handle-animateout-38ej

Can you try that and let me know if it works?

**Comment by DwieDima** [comment]
I was not able to reproduce this with your provided link.
Is there any workaround, so i can use the ionic lifecycles, where i can listen for `ionViewDidEnter()` and `IonViewWillLeave() `inside the directive?

I tried to wrap `ion-router-outlet` but this is not working.

```typescript
import { Directive, ElementRef, Input, OnInit, Renderer2 } from '@angular/core';
import { Animation } from '@ionic/angular';

@Directive({
  selector: '[customAnimation]',
})
export class AnimationDirective implements OnInit {
  @Input('customAnimation') private animation: Animation;

  public constructor(private elementRef: ElementRef, private renderer: Renderer2) {}

  public ngOnInit(): void {
    const element = this.renderer.createElement('ion-router-outlet');
    this.renderer.appendChild(element, this.elementRef.nativeElement);
  }

  public async ionViewDidEnter(): Promise<void> {
    await this.animation.play();
  }

  public async ionViewWillLeave(): Promise<void> {
    await this.animation.direction('reverse').play();
  }
}
```

**Comment by liamdebeasi** [comment]
The `ionViewDidEnter` and `ionViewDidLeave` functions only fire on Ionic pages as per https://ionicframework.com/docs/angular/lifecycle. You would need to have the page component fire the animation in that case.

At the moment we do not have plans to add Angular lifecycle integration into the Ionic animations utility.

**Comment by sean-perkins** [comment]
Apologies if I am misunderstanding your ask, but the following should be possible in an Angular project:

```ts
import { Directive, ElementRef, Input, OnDestroy, ViewContainerRef } from '@angular/core';
import { IonRouterOutlet, Animation } from '@ionic/angular';
import { Subject } from 'rxjs';
import { filter, takeUntil, tap } from 'rxjs/operators';

@Directive({
  selector: '[customAnimation]'
})
export class AnimationDirective implements OnDestroy {

  @Input('customAnimation') animation: Animation;
  @Input() viewContainerRef: ViewContainerRef;

  private destroy$ = new Subject<void>();

  constructor(
    ionRouterOutlet: IonRouterOutlet,
    private element: ElementRef) {
    ionRouterOutlet
      .activateEvents
      .pipe(
        takeUntil(this.destroy$),
        filter(ev => ev.viewContainerRef === this.viewContainerRef),
        tap(ev => this.onActivate(ev))
      )
      .subscribe();
    ionRouterOutlet
      .deactivateEvents
      .pipe(
        takeUntil(this.destroy$),
        filter(ev => ev.viewContainerRef === this.viewContainerRef),
        tap(ev => this.onDeactivate(ev))
      )
      .subscribe();
  }

  ngOnDestroy() {
    this.destroy$.next();
  }

  async onActivate(event: any) {
    console.log('onActivate', event);
    const element = this.element.nativeElement;
    await this.animation
      .addElement(element)
      .direction('normal').play();
  }

  async onDeactivate(event: any) {
    console.log('onDeactivate', event);
    await this.animation.direction('reverse').play();
  }

}
```

Your page component should have the following in its constructor:
```ts
constructor(
    public viewContainerRef: ViewContainerRef,
    private animationCtrl: AnimationController) { }
```

The page template implementation:

```html
<button [customAnimation]="fadeInTopAnimation" [viewContainerRef]="viewContainerRef">I am a button</button>
```

There is likely a simpler way to do this, but what the above code is doing is:
- Injecting the nearest instance in the DI tree for `IonRouterOutlet`
- Subscribing to all activate/deactivate events from the router outlet that match the page view container that our directive is embedded in
- Performing the animations

This works well for enter animations, I don't think it will be effective for deactivating, as you cannot block our transitions and I don't believe we intend for that functionality.

<video src="https://user-images.githubusercontent.com/13732623/157115596-2e607c53-bffe-4a4d-8a80-09a865679deb.mp4"></video>

**Comment by indraraj26** [comment]
I think on `ngOnDestroy` we should complete the observable otherwise takeUntill isnt working as it should

```
 ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }
```
OR
```
 ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.unsubscribe();
  }
```

**Comment by DwieDima** [comment]
@sean-perkins thanks a lot for your code example.
In my use-case i want to trigger an animation when a div inside a page is created or destroyed by evaluating `*ngIf` to `true` and  `false`. The animation shouldn't execute when the routerOutlet emit.
As you said, your approach works for enter, but not for leave animations.

On the current project i'm working on, we use a lot of Angular animations which trigger conditionally by *ngIf combined with observables where animations for `:enter` and `:leave` are defined.
The only workaround i see here is to refactor the whole `.html` and `.ts` where i have to subscribe to that observable inside .ts and trigger the ionic animation, which result in a lot of boilerplate code.

> I am not aware of any public Angular API that lets us tap into this, so I do not think this can be easily done. I found this article that allegedly does a leave animation with a 3rd party library: https://dev.to/nicolalc/gsap-animations-in-angular-handle-animateout-38ej
> 
> Can you try that and let me know if it works?

I'll give this one another try, which is my last hope, since i don't see an alternative which does not result in boilerplate code and refactoring.

I can't be the only one who wants to refactor Angular animations to Ionic Animations. Is there really no approved approach for this?

If i find a solution, i'll let you know.

**Comment by liamdebeasi** [comment]
At the moment, we do not have plans to tightly integrate Ionic Animations with the Angular lifecycle system. The main issue here is that Angular does not expose an API for us to do this.

I am going to close this issue for now, but I definitely encourage you to give that `dev.to` link a try again. Thanks!

**Comment by DwieDima** [comment]
@liamdebeasi i tried it again and was able to trigger the leave animation.
Now one problem is, that enter and leave animation works only once. The second time the htmlelement just shows without animation.
Heres a reproduction repo:

https://github.com/DwieDima/animationcontroller-directive-example

https://user-images.githubusercontent.com/26873275/157263046-ae5da827-4fc7-4ba1-9b22-77cf32d08bf2.mov

**Comment by DwieDima** [comment]
i found a working solution which only works when you don't have any parent elements with `*ngIf` which evaluate to `false` while animation is running.
This requires to implement your own *ngIf [directive](https://github.com/DwieDima/animationcontroller-directive-example/blob/main/src/app/ng-if-animated.directive.ts), so the element get destroyed, when animation is over.

I had to reinitialize the animation since it got destroyed. So i applied an output event to the directive when element got destroyed, where i recreate the animation.

**directive.ts**
```typescript
@Input('appAnimation') private animation: Animation;
  @Output() private destroy: EventEmitter<null> = new EventEmitter();
  private destroy$ = new Subject<void>();

  public constructor(
    private elementRef: ElementRef,
    private cdr: ChangeDetectorRef
  ) {
    fromEvent(this.elementRef.nativeElement, 'animate-out')
      .pipe(
        switchMap(({ detail }) => this.animateOut(detail.parentViewRef)),
        takeUntil(this.destroy$)
      )
      .subscribe();
  }

  public async ngOnInit(): Promise<void> {
    console.log('init');
    const element = this.elementRef.nativeElement;
    this.animation.addElement(element);
    await this.animateIn();
  }

  public animateIn(): Promise<void> {
    return this.animation.play();
  }

  public animateOut(parentViewRef: ViewContainerRef): Promise<void> {
    return this.animation
      .direction('reverse')
      .play()
      .then(() => {
        if (parentViewRef) {
          parentViewRef.clear();
          this.cdr.markForCheck();
          return;
        }
        return;
      });
  }

  public ngOnDestroy(): void {
    this.destroy.emit();
    this.destroy$.next();
    this.destroy$.complete();
  }
```
**parent .html**
```html
<div
  style="height: 50px; background: red"
  [appAnimation]="fadeInTopAnimation"
  *appNgIfAnimated="show"
  (destroy)="initFadeInTopAnimation()"
>
  custom content
</div>
```

```typescript

  public initFadeInTopAnimation(): void {
    this.fadeInTopAnimation = this.animationController
      .create('fadeInTop')
      .beforeStyles({ position: 'absolute', top: 0, 'z-index': '1000' })
      .duration(1000)
      .easing('ease-out')
      .fromTo('opacity', 0, 1)
      .fromTo('transform', 'translateY(-50%)', 'translateY(0)');
  }
```

Full implementation can be found here:
https://github.com/DwieDima/animationcontroller-directive-example

@liamdebeasi is there a way to check if the animation of animationController is still running?
Something like: `animation.isActive()` ?
Use-Case is to check if current animation is still running, so i don't call `.play()` again.
