### ISSUE TITLE
bug: ion-datetime, md, highlight circle cut off on months with six rows

### ISSUE THREAD

**Issue by AE1NS** [ionic-team/ionic-framework#24891]
### Ionic Framework Version

- [X] v6.x

### Current Behavior

![grafik](https://user-images.githubusercontent.com/47378799/157057557-ed09d8c6-e945-4901-a837-683c1ba86a22.png)
When using the ion-datetime component as date picker only, the highlight circle in the last row of some months is cut off. 

### Expected Behavior

The circle in the last row should not be cut off.

### Steps to Reproduce

Open the official demo, switch to android and scroll to 'Time First, Date Second'. Select a month, where the last row is filled and select any day in the last row.

### Reproduction URL

https://ionicframework.com/docs/api/datetime

**Comment by amandaesmith3** [comment]
Thanks for the issue, I'm able to reproduce this. It looks like the issue is with months that wrap to six rows, such as January 2022. The `ion-datetime` doesn't properly account for the extra height on `md` mode.

**Comment by snowwolfjay** [comment]
Hey , this might cause by datetime.md.scss:

:host .calendar-body .calendar-month .calendar-month-grid {
  /**
   * 3px top padding adds enough spacing at
   * the top of the container for the selected
   * day box shadow to display without clipping.
   */
  @include padding(3px, 10px, 0px, 10px);

this fix make the last line cut more obviously;

better to apply padding(top and bottom , or betther solution) to :host .calendar-body .calendar-month element and I fix in my project use cssStyleSheet hack, hope will update soon, thx
