### ISSUE TITLE
bug: menuInnerEl is undefined in menu when routing back a page

### ISSUE THREAD

**Issue by KANekT** [ionic-team/ionic-framework#24907]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [X] v7.x

### Current Behavior

    "@ionic/vue": "^6.0.10",
    
 
ion-menu.js not sync with core

### Expected Behavior

in  "@ionic/vue": "6.0.10"
![image](https://user-images.githubusercontent.com/580273/157399468-cbebd3f9-3226-4b59-92d4-9773381c4454.png)
const width = this.menuInnerEl.offsetWidth;

in code 
https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/menu/menu.tsx#L406
const width = this.menuInnerEl!.offsetWidth; - with !

### Steps to Reproduce

npm install
go to 
..\node_modules\@ionic\core\components\ion-menu.js

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\KANekT\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.0.10

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.4
   OS     : Windows 10

**Comment by KANekT** [comment]
await this.loadAnimation();
why it exec loadAnimation if animated = false ?

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe the issue you are running into?

**Comment by KANekT** [comment]
@liamdebeasi 

i have ion-menu on page

then i go to another page where there is no menu

then i go back

ion-menu not work - in console "this.menuInnerEl.offsetWidth is undefined"

**Comment by liamdebeasi** [comment]
Can you please provide a GitHub repo I can use to verify this behavior?

**Comment by KANekT** [comment]
@liamdebeasi https://github.com/KANekT/ion-menu-bug

**Comment by KANekT** [comment]
![image](https://user-images.githubusercontent.com/580273/157812029-d7599408-371e-4034-8758-1b5382ad087e.png)

**Comment by danielehrhardt** [comment]
@liamdebeasi 
Same Problem with Angular. Should i create a sample repo or can you reproduce?

**Comment by liamdebeasi** [comment]
I can reproduce the issue, thanks!

**Comment by KANekT** [comment]
@liamdebeasi you have any plan to fixed this Error ?

**Comment by nodiced922** [comment]
Is this being worked on? Is there a timeframe for the patch? This has been 3 months and is a major bug that breaks the menu. Its issues like these, that make me want to move on from ionic.

**Comment by nodiced922** [comment]
Any  work arounds?

**Comment by danielehrhardt** [comment]
> Any work arounds?
```
<ion-menu
      [disabled]="true"
       menuId="main"
```

app.component.ts:
```
ngAfterViewInit() {
       this.menuCtrl.enable(true, "main");
}
```

**Comment by ErnestoArtime** [comment]
Same problem, any solutions?

**Comment by nodiced922** [comment]
> 

I had previously been Including my header which contained my menu on each page. I moved this to a single Instance up to my app component and I haven't had an issue with any bugs. I did have to rewire some events, etc triggered by the headed but was worth the small amount of work to make this change

**Comment by KANekT** [comment]
@liamdebeasi you planed or not fixed this bug ?

6 month ago it confirmed

**Comment by yurizem** [comment]
Hi, I'm facing the same problem, any solution?

**Comment by dbertolini** [comment]
Same bug here!

**Comment by massitashakori** [comment]
Seeing the same bug on my app. 
The app got frozen with the first interaction after/while loading

**Comment by StavM** [comment]
is there any progress on this one ? seems kind of absurd not to fix this one

**Comment by KANekT** [comment]
we must suffer and be in pain :)

**Comment by liamdebeasi** [comment]
Can everyone try the following dev build and let me know if it resolves the issue?

**Angular**
```
npm install @ionic/angular@7.0.2-dev.11680882251.16cd0c1a
```

**React**
```
npm install @ionic/react@7.0.2-dev.11680882251.16cd0c1a @ionic/react-router@7.0.2-dev.11680882251.16cd0c1a
```

**Vue**
```
npm install @ionic/vue@7.0.2-dev.11680882251.16cd0c1a @ionic/vue-router@7.0.2-dev.11680882251.16cd0c1a
```

**Comment by KANekT** [comment]
how I can use this on v6 ?

**Comment by liamdebeasi** [comment]
Normally we don't release bug fixes to previous major versions of Ionic, but this is a high impact bug so I'd like to backport this patch to v6.

Here is a v6 dev build you can try: `6.7.3-dev.11680889549.1f830ade`

**Comment by KANekT** [comment]
@liamdebeasi yes it fixed error in may application on v6, thanks

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27141, and a fix will be available in an upcoming release of Ionic Framework.
