### ISSUE TITLE
bug: #23873 still not fixed in v5

### ISSUE THREAD

**Issue by luxterful** [ionic-team/ionic-framework#24915]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

A while ago i opened a bug report for Ionic 5: https://github.com/ionic-team/ionic-framework/issues/23873

The issue is marked as resolved but the bug still exists in ionic 5 (but is solved in ionic 6). Can't update to ionic 6 right now because there are to many breaking changes.

### Expected Behavior

I expected this issue to be resolved in ionic 5 as well.

### Steps to Reproduce

See https://github.com/ionic-team/ionic-framework/issues/23873

### Ionic Info

Ionic:

   Ionic CLI       : 5.4.16 (/Users/XXX/.asdf/installs/nodejs/16.13.2/.npm/lib/node_modules/ionic)
   Ionic Framework : @ionic/vue 5.9.3

Capacitor:

   Capacitor CLI   : not installed
   @capacitor/core : 3.2.0

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.5.0)   : 1.4.0

System:

   NodeJS : v16.13.2 (/Users/XXX/.asdf/installs/nodejs/16.13.2/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Hi there,

When a major release of Ionic ships, the previous major version goes into maintenance mode and only receives critical security fixes.

At this time we do not have plans to back port this patch to Ionic 5.

As for updating to Ionic 6, there is a step by step migration guide that may help: https://ionicframework.com/docs/intro/upgrading-to-ionic-6
