### ISSUE TITLE
🐞 Bug: internal server error when reload routes with query params

### ISSUE THREAD

**Issue by iAnkurBiswas** [ionic-team/ionic-framework#24933]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

When I try to reload routes with query params like this localhost:4200/u?u=6222d4fd021b3080bc4aa6d4, it shows me this message.
![](https://i.stack.imgur.com/4QdBw.png)

### Expected Behavior

This is how the page normally looks 
![](https://i.imgur.com/1GM59EP.png)

### Steps to Reproduce

1. Open a route with query params (Ex. localhost:4200/u?u=6222d4fd021b3080bc4aa6d4)
2. Hit reload (Cmd + R)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.2.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 6.0.0

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.5.0)   : 1.3.0

System:

   NodeJS : v16.14.0 (/usr/local/Cellar/node@16/16.14.0_1/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

### Additional Information

This project consists Angular universal and I run this with `npm run dev:ssr`. 
When I reload the desired page this issue pronted in browser console. 
![](https://i.imgur.com/O0XtlEd.png)

Although I already added the following code in my `index.html`
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; media-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: sha256-ACotEtBlkqjCUAsddlA/3p2h7Q0iHuDXxk577uNsXwA=; font-src 'self' data: https:; connect-src 'self' wss: https:" />
```

**Comment by amandaesmith3** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
