### ISSUE TITLE
bug: cannot dismiss nested popover via backdrop

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#24954]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I use `ion-popover`'s to create a Header Component for a Website. The main Items should expand on click, the subitems may contain nested children items which should then be displayed on hover. This works so far, but after a "hovered"-popover is presented it never dismisses and the focus seems to be lost.

### Expected Behavior

See the attached repo.

What i expect is:

1. Click on `Main 1` --> Open Popover below: ✅ works
2. Hover on `Item with children 1` --> Open popover next to it: ✅ works
3. Hover on `item with children 2` --> First popover should be dismissed and new one shown: ❌ doesn't work
4. Hover on `item 2` --> First popover should be dismissed: ❌ doesn't work
5. Click on the backdrop --> Dismiss all popovers: ❌ doesn't work if a hover popover is present

### Steps to Reproduce

1. `ionic serve` the linke code repo
2. Click on one of the main items
3. Hover one of the `item with children`

### Code Reproduction URL

https://github.com/EinfachHans/ionic-popover-header-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/hans/.nvm/versions/node/v16.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.12
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.5.0

System:

   NodeJS : v16.13.1 (/Users/hans/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.4.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. The container for the nested popover received pointer events, so clicking/hovering over the root backdrop did not cause the nested popover to dismiss.

Here's a dev build if you want to test:

```
6.0.13-dev.11647533300.104828dc
```

**Comment by EinfachHans** [comment]
works like a charm 🎉
