### ISSUE TITLE
bug: open new page from sidemenu see the animation

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#24953]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

Animation is not smooth as it should, Still i see previous page 

![image](https://user-images.githubusercontent.com/23274631/158745038-4965c9f1-190d-40da-84e0-1fcbfc795a44.png)

### Expected Behavior

It should have smooth animation when you will open a new page from side menu

### Steps to Reproduce

Repo: https://github.com/indraraj26/sidemenu-new-page-anmiation-bug

1. npm i
2. ionic serve
3. open sidemenu and click on complete
4. repeat 3 step few times

### Code Reproduction URL

https://github.com/indraraj26/sidemenu-new-page-anmiation-bug

### Ionic Info

ionic info

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.8.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.4
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.2.4
   @capacitor/ios     : 3.3.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.4.1

System:

   NodeJS : v14.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by sean-perkins** [comment]
@indraraj26 the issue appears to be that the `ion-header` element does not have a background color applied to it. This gives it the appearance of briefly displaying the previous page header during the navigation. 

If you manually apply the black background color to ion-header:

```
ion-header {
  background: #000;
}
```

For both of the page components, it appears to resolve the issue that I am seeing.

Can you confirm?

**Comment by indraraj26** [comment]
Hi @sean-perkins,

I did the changes but still i see flicker when you will navigate to complete 

Look at the hello hello section of dashboard
![image](https://user-images.githubusercontent.com/23274631/158978557-9322a8df-5feb-4f47-8756-9fdca0f86b54.png)

Same dependency and it is working fine

**NO ISSUE:** https://github.com/indraraj26/sidemenu-new-page-animation-no-issue
**ISSUE REPO:** https://github.com/indraraj26/sidemenu-new-page-anmiation-bug

Thank you

**Comment by indraraj26** [comment]
Fixed: 

`--ion-color-black` this was **not defined** in variable.scss and --background of ion-content was set to `--ion-color-black` of complete-order.scss

I should use `--ion-background-color` to set background for entire app instead of setting at body {}

Thank you
