### ISSUE TITLE
feat: Add part to ion-datetime component to allow CSS customization

### ISSUE THREAD

**Issue by iwoogy** [ionic-team/ionic-framework#24963]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like to customize the CSS styles of the ion-datetime in a more precise way.

I read this article that explain how to access styles inside the shadow dom.
https://ionicframework.com/docs/theming/css-shadow-parts

I noticed that parts are not exposed in the  ion-datetime
![image](https://user-images.githubusercontent.com/479162/158950153-b4c606bb-5f6e-45de-b73d-acbeb282eda6.png)

### Describe the Use Case

I would like to implement that kind of styling 

![image](https://user-images.githubusercontent.com/479162/158950254-a2dae397-d9ec-47a9-bb9a-a473ce8f3a32.png)

### Describe Preferred Solution

Adding part attribtues to the shadow root children will help to access the styling of ion-datetime component

### Describe Alternatives

No alternative for now.

### Related Code

The code is pretty simple

![image](https://user-images.githubusercontent.com/479162/158950604-ce13ccdb-8657-4d48-afd6-efe9775b6d52.png)

![image](https://user-images.githubusercontent.com/479162/158950394-2b353b85-e239-49b9-8bd7-193382aec0da.png)

![image](https://user-images.githubusercontent.com/479162/158950421-cb5a2433-7860-4d3b-a826-a848458af946.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Could you help me understand which parts of `ion-datetime` you are unable to style?

Datetime has several CSS Variables that you can use as well as the `color` property to customize the overall theme of the component.

**Comment by iwoogy** [comment]
I would need for instance to change the style of the selectable dates

![image](https://user-images.githubusercontent.com/479162/159100534-5eed4800-7854-4d2c-9a9f-8029aad6bdc9.png)



From the documentation, it seems like there are only 3 custom css properties available

![image](https://user-images.githubusercontent.com/479162/159100504-e5e705e5-1215-4231-810f-f39407d1cc93.png)

**Comment by indraraj26** [comment]
Look like there are multiple event as per event, You want to apply background.

@iwoogy Is purple square selected one ?

**Comment by iwoogy** [comment]
The purple square is just an annotation.
This new legend will help understand the feature as the designer intended it.

![image](https://user-images.githubusercontent.com/479162/159146270-3460482f-5617-4046-a76c-8463d8c60e6a.png)

**Comment by liamdebeasi** [comment]
We encourage developers to theme components in a way that matches the overall theme of their application. To this, you can generate a new custom color theme and use the `color` property to apply these styles. I used https://ionicframework.com/docs/theming/colors#new-color-creator to do this.

Here is an example: https://codepen.io/liamdebeasi/pen/YzYWBgV

The `:root` and `.ion-color-custom` classes are a bit involved, but the idea is that these styles are used across your entire application, not just for `ion-datetime`. From there, you can style `ion-datetime` specific styles in the `ion-datetime` selector block.

Can you try this and let me know if it works?

**Comment by iwoogy** [comment]
Thanks for your support.

It works to fulfill 50% of the designer requirements.

The today date and the selected date have to be the same color using the color attribute.
The disabled dates do not seem to be configurable.
The selectables dates styles cannot be changed.

Does the styling of the shadow parts could help allowing more control over the styling ?

Is it possible to hide the weekdays in order to have many ion-date components on the same page with only one weekdays header ?

**Comment by liamdebeasi** [comment]
Can you provide your use cases for these additional customizations? We intended for `ion-datetime` to match the native calendar picker components as closely as possible.

At the moment it is not possible to hide the weekdays on the datetime component.

**Comment by iwoogy** [comment]
> Can you provide your use cases for these additional customizations? We intended for ion-datetime to match the native calendar picker components as closely as possible.

I'm in the process of converting a NativeScript into Ionic. I used to implement the graphic designer requirements in NativeScript in a custom calendar. I was wondering if the new component can help reproduce the same requirements.

![image](https://user-images.githubusercontent.com/479162/159146270-3460482f-5617-4046-a76c-8463d8c60e6a.png)

> At the moment it is not possible to hide the weekdays on the datetime component.

Ok. Noted.

**Comment by ckang777** [comment]
+1

**Comment by ckang777** [comment]
Hello @iwoogy. Looks like you closed this issue. Were you able to resolve this issue? If so how did you achieve this? I'm in the same boat and wanted a solution for this use case. Thanks.

**Comment by iwoogy** [comment]
Hello @ckang777 

I didn't solve the issue. I negociated with the graphic designer to scale down the customisation ambition to fit the current constraint.
