### ISSUE TITLE
bug: ion-refresh isn't working in nested ion-content

### ISSUE THREAD

**Issue by aaadipop** [ionic-team/ionic-framework#24965]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

ion-refresh isn't working inside nested ion-content, 

sometime just happen to work, but only 2-3 times, is the same if I add `swipeLeft` or `right` to nested component

### Expected Behavior

be able to have the following structure

app.component.html
```
<ion-app>
  <ion-content>   <<< --- withou this element is working as expected, but without the footer will be messed up
    <ion-router-outlet id="main" [swipeGesture]="true"></ion-router-outlet>
  </ion-content>
  <ion-footer>
    <ion-toolbar>
      <ion-tabs>
        ...
      </ion-tabs>
    </ion-toolbar>
  </ion-footer>
</ion-app>
```

other.component.html
```
<ion-header>
  <ion-toolbar>
    <ion-title>
      {{authUser.name}}
    </ion-title>
    <ion-buttons slot="end">
      <ion-item>
        <ion-button ><ion-icon name="create-outline"></ion-icon></ion-button>
      </ion-item>
    </ion-buttons>
  </ion-toolbar>
  <ion-progress-bar value="1" type="{{loadingRequest ? 'indeterminate' : ''}}"></ion-progress-bar>
</ion-header>

<ion-content class="ion-padding bg" padding>

  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>

  <h4><ion-text color="primary">sub</ion-text></h4>
  <h2>{{title}}</h2>

  <ion-list *ngIf="showTeam">
    <ion-item-sliding *ngFor="let t of team.sort(compare)">
      <ion-item>
          ... some items that can be reloaded here
      </ion-item>
  </ion-list>

</ion-content>
```

### Steps to Reproduce

like above

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.7
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 6 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v14.18.1 (/opt/homebrew/Cellar/node@14/14.18.1/bin/node)
   npm        : 6.14.15
   OS         : macOS Big Sur
   Xcode      : Xcode 13.2.1 Build version 13C100

**Comment by amandaesmith3** [comment]
Could you create a Github repo and post a link to it? There is a guide here: https://github.com/ionic-team/ionic-framework/issues/24965#issuecomment-1073167562
