### ISSUE TITLE
bug: Ion-datetime desktop disable text select

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic-framework#24973]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

This is more for cosmetics but in the latest version of ion-datetime in desktop mode when you try to select a year/month, text select is on and select the characters. Visually I think it would be better if text-select was disabled to make the UI look clean.

<img width="225" alt="Screen Shot 2022-03-22 at 3 17 36 pm" src="https://user-images.githubusercontent.com/10624315/159408360-60db70e2-2acc-49c6-b7cc-9d82bdecff83.png">

- [ ] 

### Expected Behavior

Text select disabled on month/year picker

### Steps to Reproduce

Use ion-datetim in desktop mode and select year/month with mouse.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.15.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.12
   @angular-devkit/build-angular : 13.2.2
   @angular-devkit/schematics    : 13.2.2
   @angular/cli                  : 13.2.2
   @ionic/angular-toolkit        : 6.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.4.1
   OS     : macOS Big Sur
   Xcode  : Xcode 13.2.1 Build version 13C100

**Comment by liamdebeasi** [comment]
Thanks for the issue. Text selection is automatically disabled on mobile devices, but we leave text selection up to the user when it comes to desktop apps. You can customize this by setting `user-select: none` in your app. (I usually set it on `body`).

Can you try that and let me know if it resolves the issue?
