### ISSUE TITLE
bug: a href="tel:12345678" not opening the phone app

### ISSUE THREAD

**Issue by sharutza** [ionic-team/ionic-framework#24981]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

a simple link with a phone number won't work on I6. Worked on i4

### Expected Behavior

when accessed open the phone app to make a call

### Steps to Reproduce

`  <a href="tel:458555" class="group-radio-phone">testCall:123456789</a>`

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (C:\Users\ita\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.10
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 20 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.14.0
   native-run                             : 1.0.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\ita\AppData\Local\Android\Sdk)
   NodeJS            : v14.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.8
   OS                : Windows 10

**Comment by liamdebeasi** [comment]
Also, check to see that the following line is not in your `index.html`:

```html
<meta name="format-detection" content="telephone=no" />
```

This will disable the telephone link detection

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
