### ISSUE TITLE
bug: Error going to previous page in Ionic with Angular (Android)

### ISSUE THREAD

**Issue by emmacias** [ionic-team/ionic-framework#24986]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I have an application developed with Ionic + Capacitor + Angular. Everything works correctly until I install a cordova plugin (for example cordova-plugin-fingerprint-aio), from here, when I compile for android, when trying to go back, the pages do not load correctly and are displayed one below the other. This error only occurs when I install a cordova plugin, if I uninstall the plugin everything returns to normal. The error occurs on the android platform, on the web it works correctly.

In the following image I navigated from page one to four and then when I go back one page is not replaced by another but they are shown below.

![1648059157610](https://user-images.githubusercontent.com/10861250/159771303-dd360643-a568-4c88-93d0-2c271bcf8d0b.jpg)

### Expected Behavior

Going back in the browsing history should only load the current page. 

### Steps to Reproduce

Create an Ionic + Capacitor + Angular project.
Define several pages with their routes.
Install some cordova plugins for example cordova-plugin-fingerprint-aio.
Compile for android platform.
Navigate between pages on the device.
Try to go back on the cell phone. 

### Code Reproduction URL

(https://github.com/emmacias/test)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\USUARIO\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.12
   @angular-devkit/build-angular : 13.3.0
   @angular-devkit/schematics    : 13.3.0
   @angular/cli                  : 13.3.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v12.22.10 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10

**Comment by indraraj26** [comment]
There must be an error from cordova plugins, inspect the device and see. It is not actionable on this repository as it is not reproducible without the cordova plugin.

Thank you

**Comment by emmacias** [comment]
Here I share the example code of the identified error. It is worth mentioning that the error has only been detected on the android platform.

https://github.com/emmacias/test
