### ISSUE TITLE
bug: datetime, month/year selection with cancel/done buttons has confusing UX

### ISSUE THREAD

**Issue by vladimirSnapAddy** [ionic-team/ionic-framework#24998]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Event should be emitted when user changes view from default to month/year selection opened when clicked on top left button in the datepicker and back to default view.

### Describe the Use Case

I am showing ion-datetime in a modal. When I want to select a date in one of the past years, I must click on the month/date button in top left corner. If I then select wanted month and year, and click on done, modal closes and value is set to previously select date. This behaviour is frustrating, because many users don't expect modal to be closed with previously selected value.

### Describe Preferred Solution

If an event is emitted when these views are toggled, we can handle custom behaviour (show and hide DONE button for example) and prevent users from exiting modal unintentionally. 

### Related Code

```
<ion-button id="open-modal">Open Datetime Modal</ion-button>
<ion-modal trigger="open-modal" [backdropDismiss]="false">
  <ng-template>
    <ion-content>
      <ion-datetime
        size="cover"
        [disabled]="false"
        [max]="'2050-12-31'"
        [(ngModel)]="date"
        (ionChange)="updateValue($event)"
        [showDefaultButtons]="true"
      >
      </ion-datetime>
    </ion-content>
  </ng-template>
</ion-modal>
```

### Additional Information

https://user-images.githubusercontent.com/85163599/160097525-deb50edf-1c29-4f08-9c72-6fe5d7cc979a.mov

**Comment by sean-perkins** [comment]
@vladimirSnapAddy thanks for the feature request!

I think there is a few different areas to dig into here:

1. The "Done" action is confusing to users when changing month/year:

This appears to be reoccurring feedback we are receiving. While the top-left month/year selector does show an arrow indicator that it is expanded, it is unclear to users that the "Done" action is attached to the date picker and not to the expanded view.

We should likely either update the design of the date picker to add a separator between the bar of "Done" and "Cancel" to help users understand it is tied to the main container or potentially discuss changing the default behavior here. I would argue that in this interaction, very few users would expect the picker to dismiss when clicking "Done" from the expanded view. They would only expect that action when viewing the calendar.

2. Emitting an event when the month/year selection is changed.

While it does not currently behave this way, `ionChange` would be the ideal event here. When the value is changed internally, we should be emitting `ionChange` to align with HTML form control behavior. This would allow you to listen and handle any custom logic based on year/month/day/etc. changing. Currently we only update the value when the confirm action is selected, which prevents you from responding to input change (and needing this custom event). 

---

I'll let other team members & community members add thoughts/feedback as well, but I would advocate for changing the default behavior of the "Done" action in this context and wait on emitting an event until we have a chance to rework form behaviors at scale.

**Comment by vladimirSnapAddy** [comment]
Thank you for the response. If you need any further information, please let me know.

**Comment by realappie** [comment]
Thanks @amandaesmith3. We are receiving complaints from our customers regarding this piece of UI too, do you have any idea when this will get fixed? And is there anything we can do to expedite this process, thanks!

**Comment by babycourageous** [comment]
@realappie if it is any help I have used a variation on this suggestion while the ionic team works on tackling this bug   - https://github.com/ionic-team/ionic-framework/issues/24962#issuecomment-1093108511

**Comment by amandaejohnston** [comment]
Hi folks, I've merged in https://github.com/ionic-team/ionic-framework/pull/25205 which eases the UX issues described here. You can see more details in the PR description. The update will be available in a future release of Ionic 👍
