### ISSUE TITLE
bug: flickering of the ion-header on ios while using "$route.fullPath" in ion-router-outlet

### ISSUE THREAD

**Issue by alfilimonov** [ionic-team/ionic-framework#24996]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

**Hello there :)**
And thanks a lot for such a wonderful framework! 🔥

I am using Vue3 and my problem is:
annoying flickering of the ion-header in ios while using `:key="$route.fullPath"` param in the `ion-router-outlet` 

Example with basic tabs template:
![ionic header flickering](https://user-images.githubusercontent.com/33881784/160023088-9623e521-c3ff-464f-a8d9-0ef96a8bc0be.gif)

### Expected Behavior

No flickering oh the header on view refresh.

### Steps to Reproduce

1. Start a new ionic project with Vue3 and Tabs template

2. Add `:key="$route.fullPath"` to the `ion-router-outlet` in the `src/views/TabsPage.vue`
            like so: ` <ion-router-outlet :key="$route.fullPath"></ion-router-outlet>`
            
3. Run `ionic serve` or deploy to the ios device

4. Switch between tabs in your ios emulator, browser or physical device 

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.13

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v17.5.0 (/usr/local/Cellar/node/17.5.0/bin/node)
   npm    : 8.4.1
   OS     : macOS Monterey

**Comment by amandaesmith3** [comment]
This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
