### ISSUE TITLE
bug: ion-select with interface popover shows no scrollbar in popover on Android

### ISSUE THREAD

**Issue by baspapen** [ionic-team/ionic-framework#25019]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

ion-select with interface popover shows no scrollbar in popover on Android when the list is longer then the available height.

![Schermafbeelding 2022-03-30 om 12 23 39](https://user-images.githubusercontent.com/10433810/160811014-2434209a-9c9e-4a5d-857b-c72ff9b53b09.png)

### Expected Behavior

Popover should show a scrollbar

### Steps to Reproduce

Created a new project, added just an ion-select with interface popover and added a lot of ion-select-options

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/Users/ixiondesign/.nvm/versions/node/v14.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.13
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.18.2 (/Users/ixiondesign/.nvm/versions/node/v14.18.2/bin/node)
   npm    : 6.14.15
   OS     : macOS Catalina

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
