### ISSUE TITLE
bug: ion-datetime numeric keyboard is adding a white background on top of the datetime picker on Android

### ISSUE THREAD

**Issue by mandis2010** [ionic-team/ionic-framework#25016]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When clicking on the minute or hour value it will open the numeric keyboard and adding a white space on top of datetime picker.

### Expected Behavior

It should not display a white space on top of datetime picker.

### Steps to Reproduce

1. Use ion-datetime and generate the android apk using cordova.
`<ion-datetime></ion-datetime>`

2. Click on the minute column or hour column to open the numeric keyboard.

### Code Reproduction URL

[Reproduction URL](https://github.com/mandis2010/datePicker)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.15.0 
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v14.17.6
   npm               : 6.14.15
   OS                : Windows 10

### Additional Information

![Screen_GalaxyS20FE_2022_March_30_7_32_am__125-16486258339-F](https://user-images.githubusercontent.com/102654303/160785614-20661c88-ab19-4d27-bc77-eb5f4834b8f2.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo I can use to verify this behavior?

**Comment by mandis2010** [comment]
@liamdebeasi Thank you for reply. 
Here is the GitRepo URL.
[Click Here](https://github.com/mandis2010/datePicker)
Steps:
npm install
ionic cordova platform add android
ionic cordova build android
Then install the apk on android device and click on the hour or minute column to open the numeric keyboard.

**Comment by liamdebeasi** [comment]
This seems to be the same underlying issue as https://github.com/ionic-team/ionic-framework/issues/24780, so I am going to merge the two threads. The datetime is being rendered partially offscreen, resulting in the white space you are seeing. However, the datetime should not be rendered offscreen to begin with. You can track progress on this issue on #24780.
