### ISSUE TITLE
bug: cordova-plugin-camera" for android : Plugin doesn't support this project's cordova-android version. cordova-android: 9.1.0, failed version requirement: >=10.0.0

### ISSUE THREAD

**Issue by shaileshpendam** [ionic-team/ionic-framework#25026]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Current Behavior

  "cordova-android": "^9.1.0",
   "@ionic-native/camera": "^5.36.0",
     "cordova-plugin-camera": "^6.0.0",

when I try to add a plugin: ionic cordova plugin add cordova-plugin-camera
Installing "cordova-plugin-camera" for android 
Plugin doesn't support this project's cordova-android version. cordova-android: 9.1.0, failed version requirement: >=10.0.0

but IOS its working properly 

### Expected Behavior

it should be add

### Steps to Reproduce

 ionic cordova plugin add cordova-plugin-camera

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.5
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 11 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (/Users/avplat/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v14.18.1 (/usr/local/bin/node)
   npm               : 6.14.15
   OS                : macOS Monterey
   Xcode             : Xcode 13.2.1 Build version 13C100

**Comment by indraraj26** [comment]
updated cordova android platform

https://cordova.apache.org/announcements/2021/07/20/cordova-android-10.0.0.html

**Comment by shaileshpendam** [comment]
> updated cordova android platform
> 
> https://cordova.apache.org/announcements/2021/07/20/cordova-android-10.0.0.html

@indraraj26 thanks for responding but if i use Cordova Android 10.0.0 , then build not happening in my case.
