### ISSUE TITLE
bug: Animation promise never completes when animation is stopped or destroyed

### ISSUE THREAD

**Issue by hakimio** [ionic-team/ionic-framework#25028]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

If you stop animation mid-way with `animation.stop()`, promise returned by `animation.play()` neither completes, nor throws any errors. The same result when using `animation.destroy()` as well.

### Expected Behavior

Promise should either complete (preferred behavior) or throw an error.

### Steps to Reproduce

Try the StackBlitz demo.

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-zdwgrc?file=src/app/app.component.ts

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\PC1\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.13
   @angular-devkit/build-angular : 13.3.0
   @angular-devkit/schematics    : 13.2.4
   @angular/cli                  : 13.3.0
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.3
   OS     : Windows 10
```

**Comment by hakimio** [comment]
@liamdebeasi then it should throw an error if it can not complete. Something should happen. The promise should not be left just hanging there.

**Comment by liamdebeasi** [comment]
Do you have an example of another animation library that does this? Doing `animation.play()` and then `animation.stop()` is correct usage, so I think throwing an error would be confusing.

**Comment by hakimio** [comment]
Why would it be confusing? Resolved promise indicates that the animation completed successfully, promise rejection indicates that the animation could not be completed. Cancelled animation is an edge case, not normal behavior.

**Comment by liamdebeasi** [comment]
You comment in https://github.com/ionic-team/ionic-framework/issues/25028#issuecomment-1084575632 suggested throwing an error which is different from rejecting the promise. Throwing an error implies that something went wrong and I do not think that would be good to do.

I am open to rejecting the promise though. Can you please describe your use case for how you are using the animation library now?

**Comment by hakimio** [comment]
> Your comment suggested throwing an error which is different from rejecting the promise.

If you `await` for a promise which gets rejected, you get an exception. That's why I was saying "throw an error".

> Can you please describe your use case for how you are using the animation library now?

Animating an element on value change. When value changes are happening faster than the animation completes, I want to cancel previous animation. After the animation finishes (successfully or not), there is a "clean-up" step. If the animation promise is never resolved or rejected, the "clean-up" code is not executed.

**Comment by liamdebeasi** [comment]
Thanks for the additional information. I took a look at other animation libraries and I cannot find any initial examples of other libraries that follow this pattern.

For example, here is GreenSock (GSAP): https://codepen.io/liamdebeasi/pen/vYpebvW

When calling the `kill()` method on the active tween, the `play()` neither resolves nor rejects. Additionally, the `onComplete` callback does not fire.

Do you know of other animation libraries that follow this pattern?
