### ISSUE TITLE
bug: Infinite scroll doesnt's work with Vue Vite

### ISSUE THREAD

**Issue by NeroN7F** [ionic-team/ionic-framework#25024]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Tried to implement Ionic Infinite Scroll, which would fetch data from axios, but faced with an issue, it just doesn’t work. Seems like an integrational issue with Ionic itself. Same code works fine with Vue Cli. Checked everything and noticed, that problem might be with positional property. Perhaps it just doesnt detects event when viewport hits the bottom of container, eventually data doesnt fetches

### Expected Behavior

Detect event when viewport hits the bottom of container, then fetch data from axios

### Steps to Reproduce

Same code, but with Vue cli: 
https://github.com/whitersun/ion-inifinite-scroll-example-with-api/blob/main/src/views/Home.vue

Vite version:
https://stackblitz.com/edit/vitejs-vite-vsj5ir?file=package.json

### Code Reproduction URL

https://stackblitz.com/edit/vitejs-vite-vsj5ir?file=package.json

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0
   Ionic Framework : @ionic/vue 6.0.14

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.19.0 (/usr/local/bin/node)
   npm    : 7.17.0
   OS     : Linux 5.0

**Comment by liamdebeasi** [comment]
Thanks for the issue. The problem here appears to be in your initialization of Ionic.

In `main.js` you mount the app before initializing Ionic:

```js
createApp(App).mount('#app').use(router, axios).use(IonicVue);

router.isReady().then(() => {
  app.mount('#app');
});
```

Your code should look something like this:

```js
const app = createApp(App).use(router, axios, IonicVue);

router.isReady().then(() => {
  app.mount('#app');
});
```

Making that change fixed the issue on my end. Can you give that a try?

**Comment by NeroN7F** [comment]
> 



> Thanks for the issue. The problem here appears to be in your initialization of Ionic.
> 
> In `main.js` you mount the app before initializing Ionic:
> 
> ```js
> createApp(App).mount('#app').use(router, axios).use(IonicVue);
> 
> router.isReady().then(() => {
>   app.mount('#app');
> });
> ```
> 
> Your code should look something like this:
> 
> ```js
> const app = createApp(App).use(router, axios, IonicVue);
> 
> router.isReady().then(() => {
>   app.mount('#app');
> });
> ```
> 
> Making that change fixed the issue on my end. Can you give that a try?

Thanks for the reply

Tried to change main.js in both stackblitz and main project, still nothing. Loading shows up, but doesnt fetches next data

https://imgur.com/a/5XK8GTK

In main project: 

```
const app = createApp(App).use(IonicVue).use(store).use(router, axios)

router.isReady().then(() => {
    app.mount('#app');
});
```

**Comment by liamdebeasi** [comment]
I created https://stackblitz.com/edit/vitejs-vite-z9fjbb which is working on my end. Data is fetched up until the 20th entry and which point the infinite scroll is disabled.

**Comment by NeroN7F** [comment]
Thank you for help. Managed to resolve as well. 

```
const app = createApp(App).use(IonicVue).use(router, axios);

router.isReady().then(() => {
  app.mount('#app');
});

```
Strangely, it doesnt works in my project. Literally same actions 

```
const app = createApp(App).use(IonicVue).use(router, axios).use(store)

router.isReady().then(() => {
    app.mount('#app');
});
```
In this case, if position property not set to the top, loader doesnt even appear. May it be because of initialization order of vuex etc? Tried everything, just doesnt get it right 

  "dependencies": {
    "@fawmi/vue-google-maps": "^0.9.4",
    "@googlemaps/js-api-loader": "^1.13.10",
    "@ionic/vue": "^6.0.11",
    "@ionic/vue-router": "^6.0.11",
    "@vitejs/plugin-vue": "^2.2.0",
    "axios": "^0.26.1",
    "bulma-toast": "^2.4.1",
    "chart.js": "^3.7.0",
    "chartjs-chart-matrix": "^1.1.1",
    "swiper": "^8.0.5",
    "vite": "^2.8.0",
    "vue": "^3.2.25",
    "vue-accessible-color-picker": "^3.3.1",
    "vue-chart-3": "^3.0.4",
    "vue-chartjs": "^3.5.1",
    "vue-recaptcha": "^2.0.1",
    "vue-router": "^4.0.14",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@vue/compiler-sfc": "^3.2.31",
    "eslint": "^8.9.0",
    "eslint-plugin-vue": "^8.4.1",
    "sass": "^1.49.7"
  }


Ionic:

   Ionic CLI       : 6.19.0 (C:\Users\dark0\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.0.11

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 11
