### ISSUE TITLE
bug: modal closing animation issue if keyboard open

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#25042]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

This bug was already mentioned [here](https://github.com/ionic-team/ionic-framework/issues/20686).
This issue still persists in `"@ionic/angular": "6.0.8"`

### Expected Behavior

see in ticket [20686](https://github.com/ionic-team/ionic-framework/issues/20686)

### Steps to Reproduce

see in ticket [20686](https://github.com/ionic-team/ionic-framework/issues/20686)

### Ionic Info

Ionic:

   Ionic CLI : 6.18.2

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.11.1
   npm    : 8.5.2
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
