### ISSUE TITLE
bug: [React] basename on IonReactRouter and basePath on IonRouterOutlet not working

### ISSUE THREAD

**Issue by GCnomore** [ionic-team/ionic-framework#25048]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I'm trying to build a PWA using ionic-react.
I am trying to set `basename` on my `IonReactRouter` just like when I'm using `React-router-dom` but it seems like it is not working. I've tested this on `gh-page` and confirmed when routing, only the `Route`'s path appears.  

I've tried:
1. `basename` on `IonReactRouter` only.
2. `basePath` on `IonRouterOutlet` only.
3. Both `basename` and `basePath`

### Expected Behavior

Routes to  `domain/basename/path`

### Steps to Reproduce

Router.tsx

```javascript
import { Route, Redirect } from "react-router-dom";
import { IonRouterOutlet } from "@ionic/react";
import { IonReactRouter } from "@ionic/react-router";
import Home from "./pages/Home/Home";
import Dashboard from "./pages/Dashboard/Dashboard";

export default function Router(): JSX.Element {
  return (
    <IonReactRouter basename="/moneyApp">
      <IonRouterOutlet basePath="/moneyApp">
        <Route exact path="/home" component={Home} />
        <Route exact path="/dashboard" component={Dashboard} />
        <Redirect exact from="/" to="/home" />
      </IonRouterOutlet>
    </IonReactRouter>
  );
}

```

App.tsx
```javascript
import { IonApp, setupIonicReact } from "@ionic/react";

/* Core CSS required for Ionic components to work properly */
import "@ionic/react/css/core.css";

/* Basic CSS for apps built with Ionic */
import "@ionic/react/css/normalize.css";
import "@ionic/react/css/structure.css";
import "@ionic/react/css/typography.css";

/* Optional CSS utils that can be commented out */
import "@ionic/react/css/padding.css";
import "@ionic/react/css/float-elements.css";
import "@ionic/react/css/text-alignment.css";
import "@ionic/react/css/text-transformation.css";
import "@ionic/react/css/flex-utils.css";
import "@ionic/react/css/display.css";

/* Theme variables */
import "./theme/variables.css";
import Router from "./Router";
import { Layout } from "./components/Layout/Layout";

setupIonicReact();

const App: React.FC = () => (
  <IonApp>
    <Layout>
      <Router />
    </Layout>
  </IonApp>
);

export default App;

```

Layout.tsx
```javascript
import { IonContent, IonFab, IonFabButton, IonIcon } from "@ionic/react";
import { add } from "ionicons/icons";
import React, { ReactNode } from "react";
import { AppBar } from "../AppBar/AppBar";
import NavBar from "../NavBar/NavBar";

interface ILayout {
  children?: ReactNode;
}

export const Layout: React.FC = ({ children }: ILayout) => {
  return (
    <>
      <AppBar />
      <IonContent>{children}</IonContent>
      <NavBar />
      <IonFab
        vertical="bottom"
        horizontal="end"
        slot="fixed"
        style={{ bottom: "70px", right: "20px" }}
      >
        <IonFabButton>
          <IonIcon icon={add} />
        </IonFabButton>
      </IonFab>
    </>
  );
};

```

NavBar.tsx (bottom tab navigation)
```javascript
import React, { useEffect, useState } from "react";
import {
  IonTabs,
  IonTabBar,
  IonTabButton,
  IonIcon,
  IonLabel,
  IonBadge,
} from "@ionic/react";
import { calendar, personCircle, map, informationCircle } from "ionicons/icons";

const NavBar: React.FC = () => {
  return (
    <IonTabBar slot="bottom">
      <IonTabButton tab="home" href="/home">
        <IonIcon icon={calendar} />
        <IonLabel>Schedule</IonLabel>
        <IonBadge>6</IonBadge>
      </IonTabButton>
      <IonTabButton tab="dashboard" href="/dashboard">
        <IonIcon icon={personCircle} />
        <IonLabel>Dashboard</IonLabel>
      </IonTabButton>

      <IonTabButton tab="map">
        <IonIcon icon={map} />
        <IonLabel>Map</IonLabel>
      </IonTabButton>

      <IonTabButton tab="about">
        <IonIcon icon={informationCircle} />
        <IonLabel>About</IonLabel>
      </IonTabButton>
    </IonTabBar>
  );
};

export default NavBar;

```

### Code Reproduction URL

https://github.com/GCnomore/moneyApp

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.14

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v17.5.0 (/usr/local/bin/node)
   npm    : 8.4.1
   OS     : Linux 5.13

**Comment by sean-perkins** [comment]
@GCnomore in your example, you should be receiving a warning in the console when navigating between tabs:

> Warning: You are attempting to use a basename on a page whose URL path does not begin with the basename. Expected path "/dashboard" to begin with "/moneyApp".

If you update your `href` value on your tab buttons to reference the custom defined `basename` you are using, navigation will be successful, the warning will go away and the URL will match your expected behavior:

```tsx
<IonTabButton tab="home" href="/moneyApp/home">
  <IonIcon icon={calendar} />
  <IonLabel>Schedule</IonLabel>
  <IonBadge>6</IonBadge>
</IonTabButton>
<IonTabButton tab="dashboard" href="/moneyApp/dashboard">
  <IonIcon icon={personCircle} />
  <IonLabel>Dashboard</IonLabel>
</IonTabButton>
```

Can you confirm if this resolves your issue?

**Comment by GCnomore** [comment]
I've updated my `href` and it is working as expected!
