### ISSUE TITLE
bug: IonToast button Icon not working 

### ISSUE THREAD

**Issue by SaroGFX** [ionic-team/ionic-framework#25050]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Defining an icon to the button in a toast is not working. It gives a console error: `Uncaught TypeError: Failed to construct 'URL': Invalid base URL`

```

  <IonToast
        icon={trash} // This works 
        buttons={[
            { 
                side: 'end',
                icon: 'trash' // This doesn't work (reference error) and {trash} is not allowed
            }
        ]}
```

![Screenshot 2022-04-04 at 13 39 29](https://user-images.githubusercontent.com/3781800/161536200-ef6a2f3f-db77-461b-8f1d-0445429fc827.png)

### Expected Behavior

Display the Icon

### Steps to Reproduce

Use react with Ionic and add an icon to the IonToast button. 

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.13

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : 3.4.1
   @capacitor/core    : 3.4.1
   @capacitor/ios     : 3.4.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.14.0 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

**Comment by sean-perkins** [comment]
@SaroGFX can you try importing the icon and supplying that to your configuration?

```tsx
import { trash } from 'ionicons/icons';

...

<IonToast 
  buttons={[
    { 
      side: 'end',
      icon: trash
    }
  ]} />
```

**Comment by SaroGFX** [comment]
@sean-perkins Oh woops, why didn't I try that 😅 Thanks! Might want to edit the example on the docs, where `icon: 'star'` is a string. https://ionicframework.com/docs/api/toast

**Comment by sean-perkins** [comment]
Good call @SaroGFX, I opened a PR to correct that here: https://github.com/ionic-team/ionic-docs/pull/2254.

I will close out this issue, thanks!
