### ISSUE TITLE
bug: Unexpected behavior of ion-datetime on iOS 14

### ISSUE THREAD

**Issue by Wade-Moerke** [ionic-team/ionic-framework#25067]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When initially loading a page with an ion-datetime element on iOS v14 the datetime will start on the current month and then immediately display the previous month.  Each time I navigate to a new page and back it goes back another month.

I am seeing this result using both a physical IPod touch running iOS 14.7.2 and the xcode IPod touch 7th gen running iOS 14.5.  When testing on chrome and android I do not see this behavior.  Also, on iOS 15 it does not seem to happen.

```
<ion-content>
  <ion-datetime
      presentation="date"
      size="cover"
      class="calendar-style"
      slot="fixed"
      color="primary"
      mode="md"
    >
</ion-content>
```

scss I am using:
```
.calendar-style {
    width: 100%;
    overflow: hidden;
    height: 50%;
    --background: #e5ebf2;
}

ion-datetime {
    color: black;
}
```

### Expected Behavior

The datetime should stay on the current month until changed by a user.

### Steps to Reproduce

Create a datetime element with the given code and use on iOS 14.

### Ionic Info

<img width="595" alt="Screen Shot 2022-04-06 at 2 23 57 PM" src="https://user-images.githubusercontent.com/103143527/162055159-87a49401-62b9-43c6-aa3d-635a1b1bb41e.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
