### ISSUE TITLE
bug: `ion-datetime` selecting a day past the max day value will disable arrow navigation on previous month

### ISSUE THREAD

**Issue by alexooi** [ionic-team/ionic-framework#25073]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

In ion-datetime with min and max values set, when a date other than the default date value is selected, the navigation arrow is incorrectly disabled. 

### Expected Behavior

In ion-datetime with min and max values set, when a date other than the default date value is selected, the navigation arrow is not disabled. 

### Steps to Reproduce

https://user-images.githubusercontent.com/9407445/162442230-7430aaf1-a81c-45a3-944c-5514107b63e2.mp4

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\alexo\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.14
   @angular-devkit/build-angular : 12.2.16
   @angular-devkit/schematics    : 12.1.1
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 2.4.6
   @capacitor/android : 2.5.0
   @capacitor/core    : 2.4.6
   @capacitor/ios     : 2.5.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.3.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by hardmaster92** [comment]
I confirm to have the same problem and it's really weird how and when happens. It appears to me that happens when you bind properties for `min`, `max` and `value` instead of directly passing string attributes.
Here's a stackblitz project where I notice the issue
https://stackblitz.com/edit/ionic6-angular13-hn7ytp

**Comment by sean-perkins** [comment]
@hardmaster92 thanks for the added detail & the reproduction! That is very strange behavior, but reproducible. I'm going to track this specific to Angular for now.

I will need to dig in a little further to find the exact cause, but we can track this as a bug in the interim so others can find/follow it.

**Comment by sean-perkins** [comment]
@hardmaster92 apologies as I didn't catch this the first time reviewing, in your stackblitz example you are setting the `min` and `max` of the datetime to your `min` property. This is causing your navigation to be disabled.

Updating:
```html
<ion-datetime [min]="min" [max]="min" [value]="initialDate"></ion-datetime>
```

to:

```html
<ion-datetime [min]="min" [max]="max" [value]="initialDate"></ion-datetime>
```

Should resolve your issue.

@alexooi could you provide a reproduction for your issue?

**Comment by alexooi** [comment]
@sean-perkins I am able to reproduce the issue with @hardmaster92's link. I changed "min" to "max" for [max] and the arrows is disabled if I select 8 Mar onwards. The arrow is not disabled for 7 Mar and before.

**Comment by hardmaster92** [comment]
@sean-perkins  sorry for the mistake, I fixed it and updated to the latest ionic, check the example again. Now the arrows are enabled (not sure if updating ionic also helped) but if you select a date from March then the navigation becomes disabled which is also weird

**Comment by sean-perkins** [comment]
Thank you both for following up! I've been able to discover "what is happening". When calculating if the next/previous month should be disabled, we offset the active (working parts) month value +/- 1 and check if the date is before or after your `min` and `max` date. 

This is problematic, because if the `max` value is April 7th, but you selected March 16th, our offset logic is comparing April 7th vs. April 16th, which would disable the button.

I need to update the comparison logic to ignore days of the month, for next/previous logic. I'll post a dev build when that is available.

Thanks!

**Comment by sean-perkins** [comment]
Could either of you test with this dev build and let me know if you have any issues?
```bash
6.1.3-dev.11650481711.1ca044fb
```

**Comment by sean-perkins** [comment]
@alexooi can you clone this repo and adjust the parameters to match the behavior you are seeing?

https://github.com/sean-perkins/ion-datetime-min-max-25073

I've been having issues with Stackblitz recently and it not actually installing the dev build, even though it is specified in the project dependencies in their interface. 

The repo above uses the dev build. I was unable to get the previous navigation to be disabled in the max month.

**Comment by alexooi** [comment]
@sean-perkins I can't push to your repo, might be due to the fact that I have yet to set up the SSH key for my github account. It's getting late here so I will just paste the date that I tested with, hope that's ok with you.
`  min = '2022-04-22';`
 `max = '2022-05-21';`
 `initialDate = '2022-04-22T10:00:00';`

**Comment by sean-perkins** [comment]
@alexooi thanks for the extra information, that was super helpful!

Here is an updated dev build:
```
6.1.3-dev.11650654723.120c74ee
```

I've also updated the Github repo with your reproduction data & the latest dev build, if you could also confirm for me.

**Comment by alexooi** [comment]
@sean-perkins I can confirm that the dev build works perfectly! Thank you so much for your time and effort into resolving this. Much appreciated!
