### ISSUE TITLE
bug: Ion-item-sliding issue on IOS (only)

### ISSUE THREAD

**Issue by calmadeveloper** [ionic-team/ionic-framework#25082]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

`IonItemSliding` does not work correctly. It works now and then it does not work (once of 9 times, absolutely random). On Android it works great.

![issue (1)](https://user-images.githubusercontent.com/31864417/162414298-e5aaff2a-e6e8-47c6-8e29-b3673b4fcd7d.gif)

### Expected Behavior

Sliding works on IOS all the time

### Steps to Reproduce

1) open modal via `modalController`
2) inside modal component -> 

```
<template>
    <modal title="Reports">
        <template #mainToolbarEnd>
            <ion-buttons slot="primary">
                <ion-button @click="onCreateNewReport">
                    <ion-icon slot="icon-only" :icon="addOutline"></ion-icon>
                </ion-button>
            </ion-buttons>
        </template>

        <template #content>
            <ion-list>
                <ion-item-sliding>
                    <ion-item>Some item</ion-item>
                    <ion-item-options>
                        <ion-item-option>
                            Some options
                        </ion-item-option>
                    </ion-item-options>
                </ion-item-sliding>
            </ion-list>
        </template>
    </modal>
</template>
```

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/Users/bogdanpiskun/.nvm/versions/node/v14.15.4/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.0.15

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.4.0
   @capacitor/ios     : 3.4.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.15.4 (/Users/bogdanpiskun/.nvm/versions/node/v14.15.4/bin/node)
   npm    : 6.14.10
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
