### ISSUE TITLE
feat: Swipeable Cards like IonItemSliding

### ISSUE THREAD

**Issue by im-me** [ionic-team/ionic-framework#25093]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like to use IonItelSliding with ionCards. 

### Describe the Use Case

It would be very useful to use cards as a list of items and then be able to swipe those cards to trigger some actions.

![image](https://user-images.githubusercontent.com/31402099/162579493-88eacd0e-5a9a-431b-b335-9b6f4fddf002.png)

### Additional Information

An example of it can be found here: https://codepen.io/crturcan/pen/WNeoNNj

**Comment by DwieDima** [comment]
appying `inset=true` to your `ion-list` where your ion-item-sliding is wrapped will create that "swipeable cards" look.

**Comment by im-me** [comment]
Do i need any other configurations or styling? Because it does not work for me in react.

` <IonList inset={true}>
                    <IonItemSliding>
                        <IonItem>
                            <IonLabel>Item Options</IonLabel>
                        </IonItem>

                        <IonItemOptions side="end">
                            <IonItemOption>Unread</IonItemOption>
                        </IonItemOptions>
                    </IonItemSliding>

                    <IonItemSliding>
                        <IonItem>
                            <IonLabel>Item Options</IonLabel>
                        </IonItem>

                        <IonItemOptions side="end">
                            <IonItemOption>Unread</IonItemOption>
                        </IonItemOptions>
                    </IonItemSliding>
                </IonList>`
                
                
![image](https://user-images.githubusercontent.com/31402099/162692901-dc615dd2-7c1c-408c-aa2d-721268c579e5.png)

**Comment by DwieDima** [comment]
You should change the `background-color` of your `ion-content` or `ion-list` to see the border, since both elements are white.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Cards are not meant to be swiped, so I do not think this feature is a good fit for Ionic. However, if you are looking to have a rounded element be swiped, you can apply a border radius to your `ion-item` via the `--border-radius` CSS Variable.
