### ISSUE TITLE
bug: IonRipple is no longer working v6.0.15 and later (regression)

### ISSUE THREAD

**Issue by Nikkolas-Cage** [ionic-team/ionic-framework#25094]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

doesnt show ripple on div i tried it in different os and tried uninstalling cli and the whole npm the ripple effect stopped working 

### Expected Behavior

show ripple 

### Steps to Reproduce

   <IonContent>
      <div className="ion-activatable ripple-parent">
        A plain div with a bounded ripple effect
        <IonRippleEffect></IonRippleEffect>
      </div>

      <button className="ion-activatable ripple-parent">
        A button with a bounded ripple effect
        <IonRippleEffect></IonRippleEffect>
      </button>

      <div className="ion-activatable ripple-parent">
        A plain div with an unbounded ripple effect
        <IonRippleEffect type="unbounded"></IonRippleEffect>
      </div>

      <button className="ion-activatable ripple-parent">
        A button with an unbounded ripple effect
        <IonRippleEffect type="unbounded"></IonRippleEffect>
      </button>
    </IonContent>

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.16

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.14.0 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS Big Sur

**Comment by Nikkolas-Cage** [comment]
After reviewing
ion-ripple-effect is not working #17477 issue
it stopped working again in this version

**Comment by SSimbah** [comment]
Even in angular it is not working

**Comment by ZaDarkSide** [comment]
I can confirm.
Affected versions are 6.0.15 - 6.0.16 last know working version is 6.0.14

**Comment by Nikkolas-Cage** [comment]
> I can confirm.
> Affected versions are 6.0.15 - 6.0.16 last known working version is 6.0.14

I agree, the last known version working was below 6.0.15 however it seems that even when i rollback, ion ripple is still not working i also tried vue and angular versions yesterday and it wont work, it seems that the issue is in the ionripple itself.

**Comment by robholden** [comment]
I can also confirm it's not working for me on 6.0.16, and also cannot revert it back. 

For me it's also broken on the ionic framework docs site for both v5 & v6:
- v5: https://ionicframework.com/docs/v5/api/button 
- v6: https://ionicframework.com/docs/api/button

**Comment by stewones** [comment]
+1

**Comment by matheusdavidson** [comment]
I had `v6.0.7` and it was working, after upgrading to latest version(`6.0.16`) it didn't work anymore, reverting to the old version didn't work but found that ionic/core was also latest after my upgrade.

The fix for now is downgrading to `@ionic/angular@6.0.7` and more importantly `@ionic/core@6.0.7`

**Comment by stewones** [comment]
alright got a workaround

```
"@ionic/angular": "6.0.14",
"@ionic/core": "6.0.14",
```

**Comment by stewones** [comment]
alright got a workaround

```
"@ionic/angular": "6.0.14",
"@ionic/core": "6.0.14",
```

thx to @danielprrazevedo]

**Comment by stewones** [comment]
alright got a workaround

```
"@ionic/angular": "6.0.14",
"@ionic/core": "6.0.14",
```

thx to @danielprrazevedo

**Comment by Nikkolas-Cage** [comment]
> alright got a workaround
> 
> ```
> "@ionic/angular": "6.0.14",
> "@ionic/core": "6.0.14",
> ```
> 
> thx to @danielprrazevedo

How do i make this work in ionic react

**Comment by Nikkolas-Cage** [comment]
> @Nikkolas-Cage 
> 
> For now, just try to downgrade core and react packages manually 
> 
> `npm install @ionic/core@6.0.14 @ionic/react@6.0.14`

Great 😃👍 thanks for the immediate solution! i hope the issue will be fixed soon .

**Comment by sean-perkins** [comment]
Hello everyone 👋 I've been able to isolate the commit that regressed this behavior. Unfortunately it was during our tslint to eslint & prettier migration, which includes a lot of files touched and modified (826) with the autofix command. 

I'll post a dev build for testing once I am able to narrow the exact file change. 

In the interim, it is recommended to stay on 6.0.14.

Thanks!

**Comment by Nikkolas-Cage** [comment]
> Ok, here is a dev build to test with: `6.0.17-dev.11649730310.17726968`. I've confirmed locally with our ripple effect example. Would someone like to test within their applications and let me know if the problem is fixed?
> 
> Thanks!

Tested in ionic react, worked great 😁

**Comment by HenriquueSouzza** [comment]
> Ok, aqui está uma compilação dev para testar com: `6.0.17-dev.11649730310.17726968`. Confirmei localmente com nosso exemplo de efeito cascata. Alguém gostaria de testar dentro de seus aplicativos e me informar se o problema foi corrigido?
> 
> Obrigado!

**Worked**, thank you !!
