### ISSUE TITLE
bug: Modal over Modal backdrop issue 

### ISSUE THREAD

**Issue by SaroGFX** [ionic-team/ionic-framework#25098]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The sheet modal on iOS has a backdrop but when you show to modals over each other (modal over modal) the backdrop becomes animated (narrower). Which looks like a glitch.

- Is there a way to turn off the backdrop or background scaling. 
- Or is there perhaps another way to fix it

For now, I can turn off the backdrop overlay, but it would be nice to have a fix.

![Screenshot 2022-04-11 at 09 36 59](https://user-images.githubusercontent.com/3781800/162725009-1082e26e-e182-4634-b28e-63cbd1c4b2ef.png)
 

### Expected Behavior

The backdrop shouldn't scale or the ability to turn off the scaling all-together. 

### Steps to Reproduce

Implement a modal over modal

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.13

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : 3.4.1
   @capacitor/core    : 3.4.1
   @capacitor/ios     : 3.4.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.14.0 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
