### ISSUE TITLE
Ionic Modal On Dismiss Bug: 

### ISSUE THREAD

**Issue by alexskrms** [ionic-team/ionic-framework#25103]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

modal.onDismiss() passing data is not fired on the page when I'm on the web. It only fires when is a mobile and the modal is full screen.

### Expected Behavior

modal.onDismiss() passing data should be fired on the page when I'm on the web. It only fires when is a mobile and the modal is full screen.

### Steps to Reproduce

The method that opens the modal:

async showLoginModal() {
const modal = await this.modalController.create({
  component: LoginModalComponent
});
await modal.present();
this.menuController.close();
modal.onDidDismiss().then((data) => {
  console.log(data)
  Storage.get({ key: 'user' }).then( response => {
    let user: User = JSON.parse(response.value);
    console.log(user);
    if(user.email != null){
      this.logged = true;
    }
  });
});
}

login method fired on submit inside the modal.

async login(){
let user: User = {
  email: this.credentials.controls['email'].value
}
await Storage.set({ key: 'user', value: JSON.stringify(user) });
await this.modalController.dismiss(user);
}

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\alexm\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.15
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
