### ISSUE TITLE
ion-datetime calendar mode not work

### ISSUE THREAD

**Issue by jackdaniel9** [ionic-team/ionic-framework#25105]
Ionic:
Ionic CLI: 6.17.1)
Ionic Framework: @ionic/angular 5.8.0
@angular-devkit/build-angular: 12.1.4
@angular-devkit/schematics: 12.1.4
@angular/cli: 12.1.4
@ionic/angular-toolkit: 4.0.0

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Current behavior:**
ion-datetime

Hi,

The documentation shows a calendar mode. 

When we insert the datetime code :

`<ion-datetime monthValues="6,7,8" yearValues="2014,2015" dayValues="01,02,03,04,05,06,08,09,10,11,12,13,14"></ion-datetime>
`
The calendar does not appear, but when we click there is a list to choose year, month and day.

No mention of calendar mode in the documentation.

Also, presentation="time" or presentation="date-time" doesn't seem to work.

No way to choose hours and minutes only a date.

Thank you

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
