### ISSUE TITLE
bug: IonAlert not rendering in develop mode (yarn start) when using React 18.0.0 and using createRoot.

### ISSUE THREAD

**Issue by raythree** [ionic-team/ionic-framework#25118]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

Upgraded application use to Ionic 6 and React 18.0.0. Changed initial app render to use react-dom/client createRoot, instead of ReactDOM.render, as this gives deprecation warnings in React 18. Noticed that IonAlerts were not rendering.  Basically, getting a blank screen when isOpen = true. This only manifests when running in dev mode using "yarn start", the IonAlerts do render when running from a production build, "yarn build". Changing back to use ReactDOM.render works in both modes.

### Expected Behavior

Expect IonAlert to render in both develop and production modes.

### Steps to Reproduce

Our application alerts are all the same, so rather than add IonAlert markup on all pages, the App has a single IonAlert which is then rendered by individual pages using a "confirm" method, exposed on AppContext like:

```
const App = () => {
  let [confirmState, setConfirmState] = React.useState(null);

  function confirm(message, handler, context = null) {
    setConfirmState({message, handler, context});
  }

  function handleConfirm() {
    confirmState.handler(confirmState.context);
    setConfirmState(null);
  }

  return (
    <AppContext.Provider value={{confirm}}>
      <IonApp>
        <IonReactRouter>
          <IonRouterOutlet>
            <Route exact path="/home">
              <Home />
            </Route>
            <Route exact path="/">
              <Redirect to="/home" />
            </Route>
        </IonRouterOutlet>
        </IonReactRouter>
        <IonAlert
          id="app-alert-main"
          isOpen={confirmState !== null}
          onDidDismiss={() => setConfirmState(null)}
          cssClass="hydra-alert"
          header="Confirm"
          message={confirmState && confirmState.message}
          buttons={[{text: 'Cancel', role: 'cancel'}, {text: 'OK', handler: () => handleConfirm()}]}
          position="top"
      />
      </IonApp>
    </AppContext.Provider>  
  );
}

```

This was replicated in the Ionic starter template, where the ExplorerContainer showed an alert as:

```
import AppContext from '../AppContext';

const ExploreContainer = () => {
  const {confirm} = React.useContext(AppContext);

  function yesImSure() {
    console.log('CONFIRMED');
  }

  return (
    <div className="container">      
      <strong>Ready to create an app?</strong>
      <p>Start with Ionic <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
      <IonButton onClick={() => confirm('Are you sure?', yesImSure)}>Show Alert</IonButton>
    </div>
  );
};
```

The above works fine using ReactDOM.render, but gives a blank screen when using createRoot in index.js:

```
import React from 'react';
import {createRoot} from 'react-dom/client'
import App from './App';
import * as serviceWorkerRegistration from './serviceWorkerRegistration';
import reportWebVitals from './reportWebVitals';

const container = document.getElementById('root');
const root = createRoot(container);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
```

As noted, it only fails when running "yarn start", and renders fine when using the production build. 

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/Users/bill/.nvm/versions/node/v16.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/Users/bill/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.1.2
   OS     : macOS Mojave

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
