### ISSUE TITLE
bug: stencil, alias import not working when using stencil app

### ISSUE THREAD

**Issue by selodev** [ionic-team/ionic-framework#25122]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When running `"start": "stencil build --dev --watch --serve",`, I get the following errors.

`
[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/content' is imported by
           ./node_modules/@ionic/core/dist/collection/components/infinite-scroll/infinite-scroll.js, but could not be
           resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/content' is imported by
           ./node_modules/@ionic/core/dist/collection/components/refresher/refresher.js, but could not be resolved –
           treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/content' is imported by
           ./node_modules/@ionic/core/dist/collection/components/reorder-group/reorder-group.js, but could not be
           resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/content' is imported by ./node_modules/@ionic/core/dist/collection/components/footer/footer.js, but
           could not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/content' is imported by ./node_modules/@ionic/core/dist/collection/components/header/header.js, but
           could not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/content' is imported by ./node_modules/@ionic/core/dist/collection/utils/status-tap.js, but could
           not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/content' is imported by ./node_modules/@ionic/core/dist/collection/utils/input-shims/input-shims.js,
           but could not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/content' is imported by
           ./node_modules/@ionic/core/dist/collection/utils/input-shims/hacks/scroll-padding.js, but could not be
           resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/content' is imported by
           ./node_modules/@ionic/core/dist/collection/utils/input-shims/hacks/scroll-assist.js, but could not be
           resolved – treating it as an external dependency
`### 

### Expected Behavior

I should be able to use the latest version of @ionic/core with latest version of stencil as my UI library.

### Steps to Reproduce

`npm start` in Stencil project.

### Ionic Info

N/A

**Comment by popcorn245** [comment]
Same, has been happening with only one warning as of 6.0.14 or so, and today had lots more.

![image](https://user-images.githubusercontent.com/4184680/163267424-27e10ef9-10d2-4e6d-8c69-6b090b03a972.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/core@6.1.1-dev.11649883188.15e1465b
```

**Comment by popcorn245** [comment]
@liamdebeasi I can confirm all is well with that build, thanks for the ⚡response and not making me make a new repo LOL

![image](https://user-images.githubusercontent.com/4184680/163276440-6a10a5c9-bf28-459c-a422-700c30cf2b0b.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25123, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by selodev** [comment]
Thanks for resolving it so quick :)

**Comment by liamdebeasi** [comment]
A fix for this has been released in Ionic v6.1.1.

**Comment by atomassoni** [comment]
THANK YOU!
