### ISSUE TITLE
feat: allow disabling keep-alive for Ionic VueJS application

### ISSUE THREAD

**Issue by maelp** [ionic-team/ionic-framework#25121]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I'm using Ionic v5

There are many issues in my app with components and views (even though they use IonPage) which are cached by keep-alive, but for which the `onIonViewWillEnter` method is **not** called when the view is put back on screen, nor the `onBeforeMount` method, which are the methods that I use to update the content of those view. This results in the user having a different content for the views, which is unacceptable.

I couldn't do a reproducible test case, because it seems that for simple enough applications the bug doesn't happen.

I guess the easiest for me would be to remove the "keep-alive" feature of the components, so every time the router navigates to a page, it creates a new view, and calls correctly the `onIonViewWillEnter` or `onBeforeMount` methods

### Describe the Use Case

I want my app to show the actual content in the views, and not use cached content which is then not updated

### Describe Preferred Solution

The preferred solution would be that the `onIonViewWillEnter` method be correctly called, but this seems to not be the case, perhaps because of a bug in the implementation of Ionic v5

### Describe Alternatives

The alternative would be to allow disabling keep-alive on views and components

**Comment by liamdebeasi** [comment]
Thanks for the issue. `onIonViewWillEnter` should be called for every view wrapped in `<ion-page>` that is put back on the screen, so this seems like a bug. Can you provide a GitHub repo I can use to reproduce the issue?

**Comment by maelp** [comment]
That's the problem, unfortunately I can't because it's quite a complex and proprietary app that we have built at my company, but when I tried reproducing the bug on a smaller scale it did not happen, so I'm not sure exactly how the bug is triggered.

The views are in <IonPage> components, and the `onIonViewWillEnter` method is only called the first time the view is created, but not on subsequent times where the view enters the screen (once cached)

**Comment by liamdebeasi** [comment]
Unfortunately it's hard for me to help unless I can reproduce the issue on my end. Are you able to provide a minimal reproduction with the proprietary content removed?
