### ISSUE TITLE
bug: ‘ion-toolbar’ is not a known element angular 13 ionic 6

### ISSUE THREAD

**Issue by alitalaee** [ionic-team/ionic-framework#25128]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

upgraded to ionic version 6 and get 'ion-toolbar(all components)’ is not a known element] so please help me to fix that
![](https://aws1.discourse-cdn.com/ionicframework/original/3X/0/5/05e8290b6dc696dbecfe393e7f23df64496683c9.jpeg)

this is information 
![](https://aws1.discourse-cdn.com/ionicframework/original/3X/3/5/35231431280cb6ee3e946e63f3050bea8db3b526.png)

so what should i do? 

### Expected Behavior

Check to fix unknow element 

### Steps to Reproduce

Check to fix unknow element 

### Code Reproduction URL

https://github.com/alitalaee/ionicTest.git

### Ionic Info

<img width="720" alt="Screen Shot 1401-01-25 at 19 07 17" src="https://user-images.githubusercontent.com/77755450/163413506-b807e28b-8652-42b5-b5e0-09580ba50dce.png">

**Comment by DwieDima** [comment]
have you tried restarting vscode?

**Comment by liamdebeasi** [comment]
Hey there,

I recommend posting this question on the [Ionic Forums](https://forum.ionicframework.com/) as this is more of a support question. We use this tracker exclusively for bug reports and feature requests. Thanks!

**Comment by alitalaee** [comment]
> Hey there,
> 
> I recommend posting this question on the [Ionic Forums](https://forum.ionicframework.com/) as this is more of a support question. We use this tracker exclusively for bug reports and feature requests. Thanks!

i did but does not help
