### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by leomds94** [ionic-team/ionic-framework#25129]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I want the possibility of using ion-tab-bar without ion-tabs. 

### Describe the Use Case

When I try to use the 'ion-tab-bar' without the 'ion-tabs' component, it doesn't work. I only want the possibility of using the UI of 'ion-tab-bar' and the 'ion-tab-button' component with an input called 'active' that would color ion-tab-button with Ionic primary color if returned true.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify the problem you are running into? You should be able to use the `ion-tab-bar` component outside of `ion-tabs` (though you will need to manually select the tab).
