### ISSUE TITLE
bug: EventSource Not Closed

### ISSUE THREAD

**Issue by godenji** [ionic-team/ionic-framework#25139]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

With SSE (Server Sent Events) the backend API server is *not* notified on `EventSource` close event when using Express.js.

### Expected Behavior

That `EventSource` close event is propagated to backend API.

### Steps to Reproduce

Initiate SSE stream to backend API:
```typescript
const ev = new EventSource('http://localhost/sse')
// confirm api sse stream opened;
// now, close the event stream
ev.close()
```
Backend event stream continues to emit keep-alive hearbeats indefinitely as frontend never terminates the stream.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (/path/to/.npm/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.12
   @angular-devkit/build-angular : 13.3.0
   @angular-devkit/schematics    : 13.3.0
   @angular/cli                  : 13.3.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (/path/to/Android/Sdk)
   NodeJS            : v16.14.0 (/usr/bin/node)
   npm               : 8.3.1
   OS                : Linux 5.15

### Additional Information

I suspect this is due to Ionic development mode proxy not propagating close event to backend API.

When opening event stream (via browser console) to backend API with nginx as web server proxy, then close event is propagated and the stream terminates immediately on backend.

Ideally deployment environments run (near) identically. Definitely concerning seeing SSE state build up indefinitely due to non-closure of client connections :)

**Comment by sean-perkins** [comment]
@godenji could you share an example repo of this issue? I am a little unsure how this is related to the Ionic UI components. There should not be a "development mode proxy"; that is likely facilitated through your framework of choice, when using Ionic.

**Comment by godenji** [comment]
Ionic + Angular, proxy.json.

Dev mode uses Express, and for some reason close event on SSE stream
doesn't propagate to the backend.

I have yet to deploy to production or staging, but my hunch is that with
nginx as proxy server to backend this issue doesn't occur.

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a separate issue and ensure the template is fully filled out. Thank you!
