### ISSUE TITLE
bug: Inline modals not applying .ion-page wrapper- causing sizing/overflow issues

### ISSUE THREAD

**Issue by ni-vo** [ionic-team/ionic-framework#25138]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When displaying an inline modal, there is no .ion-page wrapper applied to the inner content. When a modal is opened from a controller and has a component class passed in, that component is given a .ion-page class. This does not happen with inline modals, perhaps due to how ng-template works (this I am unclear of). 

This causes the height of the ion-content to not be adjusted to fit any other content in the modal (header/footer), pushing the bottom of the content down by whatever the height of the content outside of the ion-content element.

In my example I am trying to display a modal with an ion-header, ion-content (with list), and an ion-footer. Pretty straightforward, and when shown from ModalController and  and Angular component is passed in, the same modal works fine (footer is not pushed down and ion-content scrolls correctly).

<img width="495" alt="Screen Shot 2022-04-15 at 3 38 53 PM" src="https://user-images.githubusercontent.com/29442320/163624828-fbfef365-e158-4d5c-9592-7559e439c0d0.png">

<img width="494" alt="Screen Shot 2022-04-15 at 3 46 06 PM" src="https://user-images.githubusercontent.com/29442320/163625297-087e352c-befd-49f7-bba7-1c1a2657a7a9.png">

<img width="469" alt="Screen Shot 2022-04-15 at 3 55 37 PM" src="https://user-images.githubusercontent.com/29442320/163626299-23a32ea1-cfae-48d8-8b10-04428cba69b4.png">

### Expected Behavior

The expected behavior should be the same as when a modal is presented from the ModalController and an Angular component class is passed in. See screenshots:

<img width="497" alt="Screen Shot 2022-04-15 at 3 44 24 PM" src="https://user-images.githubusercontent.com/29442320/163625149-33785522-c7ba-425a-8f47-86e55b3104d6.png">

<img width="499" alt="Screen Shot 2022-04-15 at 3 45 12 PM" src="https://user-images.githubusercontent.com/29442320/163625221-f3882304-59a7-49b8-b674-aa518f06e2e9.png">

<img width="469" alt="Screen Shot 2022-04-15 at 3 48 45 PM" src="https://user-images.githubusercontent.com/29442320/163626133-89a912d3-b6e1-4e9d-891b-952c04f9caa0.png">

### Steps to Reproduce

```
<ion-button id="filterTrigger" fill="clear">
	<ion-icon slot="icon-only" name="filter-outline"></ion-icon>
</ion-button>

<ion-modal trigger="filterTrigger">
	<ng-template>
		<!-- <div class="ion-page"> -->
			<ion-header>
				<ion-toolbar>
					<ion-title>Filter</ion-title>
				
					<ion-buttons slot="primary">
					        <ion-button>
						        <ion-icon slot="icon-only" name="close"></ion-icon>
					        </ion-button>
					</ion-buttons>
				</ion-toolbar>
			</ion-header>
			
			<ion-content>
				<ion-list>	
					<ion-item>
						<ion-label>Test</ion-label>
					</ion-item>
				</ion-list>
			</ion-content>
		
			<ion-footer>
				<ion-toolbar>
					<ion-buttons slot="end">
						<ion-button>Reset</ion-button>
						<ion-button color="primary" fill="solid">Apply</ion-button>
					</ion-buttons>
				</ion-toolbar>
			</ion-footer>
		<!-- </div> -->
	</ng-template>
</ion-modal>
```

### Ionic Info

N/A - using angular CLI - ionic command not found. Project runs with ng serve

I am running Ionic version 6.0.1 on OSx Monterey

### Additional Information

**Comment by sean-perkins** [comment]
@ni-vo can you update to the latest version of Ionic? This problem was previously addressed/resolved: https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#607-2022-02-09

**Comment by ni-vo** [comment]
> @ni-vo can you update to the latest version of Ionic? This problem was previously addressed/resolved: https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#607-2022-02-09

Ah, thank you, I was unaware!
