### ISSUE TITLE
bug: ios, pressing next/prev buttons in datetime in accordion does not work

### ISSUE THREAD

**Issue by DawidWetzler** [ionic-team/ionic-framework#25149]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The arrows on ion-datetime do not work on iOS devices (tested on iPhone 11 and iPhone 11 Pro) when wrapped by ion-accordion.

### Expected Behavior

The arrows should be able to change months like on every other device.

### Steps to Reproduce

Use `ion-accordion-group` to wrap `ion-accordion` and place inside the content slot `ion-datetime` component. The arrows should not work on iOS devices.

### Code Reproduction URL

https://github.com/DawidWetzler/ionic-accordion-datetime-bug

### Ionic Info

ionic info
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /Users/wecler/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/wecler/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/wecler/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli/index.js
       - /Users/wecler/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.19.0 (/Users/wecler/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.1.1

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.0 (/Users/wecler/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

### Additional Information

I've been looking at the issue to fix it myself but I couldn't figure out how to fix it in a "elegant" way with preserving smooth sliding animation when changing a month.

In ion-datetime.js within the nextMonth and prevMonth methods you coul delete `behaviour: 'smooth'` and the issue should be gone.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This appears to be a bug in WebKit. `IonAccordion` has "delegatesFocus" set to `true` on its shadow root. This means that focusing the accordion will forward focus to the first focusable element inside of the accordion.

For most cases, this should not impact scrolling. However, WebKit has a new smooth scrolling functionality that appears to be impacted by this.

As a temporary workaround, you can disable "CSSOM View Smooth Scrolling" on your iPhone:

Settings --> Safari --> Experimental Features --> Uncheck CSSOM View Smooth Scrolling. I will look into reporting this bug to the WebKit team.

**Comment by liamdebeasi** [comment]
The primary problem here is that we add `tabindex="0"` onto the calendar body element: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/datetime/datetime.tsx#L1463

This allows for the use of the keyboard arrow keys to navigate the calendar body dates. That calendar body is also the scroll container. It seems that focusing the scroll container while it is trying to smooth scroll causes smooth scrolling to break. Non-smooth scrolling works as expected.

**Comment by liamdebeasi** [comment]
Good news: The WebKit team has fixed the issue: https://bugs.webkit.org/show_bug.cgi?id=239605

The fix should be available in an upcoming release of iOS. I will close out this thread when the fix ships.
