### ISSUE TITLE
bug: canDismiss is missing in modal interface

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#25143]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

The new `canDismiss` from #24928 is missing in the `ModalOptions` interface:

<img width="692" alt="Bildschirmfoto 2022-04-18 um 12 46 15" src="https://user-images.githubusercontent.com/20899975/163797924-18864e32-8a76-45cd-8eaa-413fcf90632b.png">

### Expected Behavior

It should be add 😃 

### Steps to Reproduce

No need i guess

### Ionic Info

.

**Comment by sean-perkins** [comment]
Thanks @EinfachHans!

Could you test with this dev-build and let me know if all the types are coming through as expected?

```
6.1.2-dev.11650303569.14bacac1
```

**Comment by EinfachHans** [comment]
@sean-perkins  `canDismiss` is available in the dev build , yes 🎉
