### ISSUE TITLE
bug: wrong popover arrow position

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#25142]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

I experience a wrong popover arrow positioning in our app and created a small reproducible repository. The wrong positioning looks like:

<img width="325" alt="Bildschirmfoto 2022-04-18 um 12 34 00" src="https://user-images.githubusercontent.com/20899975/163796744-6eaebe86-f960-4b25-b488-55856615f01a.png">

### Expected Behavior

I'm not 100% sure if the arrow is wrong or if the popover itself is wrong (to much at the right side here). But i guess i_s clear what the expected behavior is 😃 

### Steps to Reproduce

Checkout the linked Repo and click on the label, that's it

### Code Reproduction URL

https://github.com/EinfachHans/ionic-popover-arrow-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/Users/hans/.nvm/versions/node/v16.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.1
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.5.0

System:

   NodeJS : v16.13.1 (/Users/hans/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.4.0
   OS     : macOS Monterey

**Comment by amandaesmith3** [comment]
Thanks for the issue. This is happening because of the `popover-fit-content` class being added to the popover, specifically the `--width: fit-content` line in the CSS. If I remove that, the popover positioning goes back to normal. Does that solve things for you?

**Comment by EinfachHans** [comment]
Hi @amandaesmith3 . Yes it does solve something. Without that the popover has a fixed width from `200px` and e.g. looks like this:

<img width="243" alt="Bildschirmfoto 2022-04-19 um 16 24 21" src="https://user-images.githubusercontent.com/20899975/164026454-d0a9de09-7739-4175-b4c7-0b35cea56b00.png">

The "(Netto)" belongs into the first line here

**Comment by EinfachHans** [comment]
okay thanks 😊
