### ISSUE TITLE
🐛  IonModal onDidDismiss function is not being called

### ISSUE THREAD

**Issue by TadasMil** [ionic-team/ionic-framework#25145]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

IonModal UI component once dismissing by clicking anywhere out of modal the modal itself is closed, but **onDidDismiss** function never gets called.

### Expected Behavior

IonModal UI component once dismissing by clicking anywhere out of modal the modal itself is closed, but **onDidDismiss** function gets called.

### Steps to Reproduce

1. Create new clean ionic project
2. Import IonModal component and a button to trigger modal visibility
3. Add **onDidDismiss** function as a prop to IonModal component
4. Click on the button to trigger Modal visibility
5. Dismiss modal by clicking anywhere outside of modal
6. The **onDidDismiss** never gets called.

### Ionic Info

`
<ion-button @click="setIsOpen"> Open Modal </ion-button>
`

`<IonModal
        trigger="open-modal"
        :isOpen="isOpen"
        @onDidDismiss="() => onDissmiss()"
      >
        <IonContent force-overscroll="false"> </IonContent>
      </IonModal>
`

`const isOpen = ref(false);

    const setIsOpen = () => {
      isOpen.value = true;
    };

    const setIsClosed = () => {
      isOpen.value = false;
    };

    const onDissmiss = () => {
      console.log("Dismissing modal");
    };`

### Additional Information

I've did not added any code examples as there's no functionality going on and its pretty straightforward. If you need one, let me know I'll create a codepen :)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo I can use to reproduce this behavior?

**Comment by TadasMil** [comment]
Yes, sure. [https://github.com/TadasMil/ion-modal-not-working](link). Thanks for fast reply!

**Comment by liamdebeasi** [comment]
Thanks! The syntax in your app is wrong. It should be `@didDismiss`, not `@onDidDismiss`. Note that this was a breaking change in Ionic 6: https://ionicframework.com/docs/intro/upgrading-to-ionic-6#vue
