### ISSUE TITLE
feat: modal isOpen automatically set to false on dismiss

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#25166]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi, I'm not sure if this is intentional or a bug.

Dismissing a modal with drag, backdrop, Esc, or Hardware Back Button android. The modal cannot be reopened unless you listen to the didDismiss event and manually update isOpen to false. I think this can be confusing and should automatically be set to false in order to reopen it.

regards!

### Describe the Use Case

It should automatically be set to false in order to reopen it.

### Related Code

With modals A and B, they don't reopen.
With modal C is the current solution.

https://stackblitz.com/edit/ionic-angular-v5-cfcek7?file=src%2Fapp%2Fapp.component.html

**Comment by liamdebeasi** [comment]
Thanks for the issue. I discussed this with the team, and we do not think this feature is a good fit for Ionic.

The `isOpen` property allows developers to control the state of a modal through the state of their application. This is helpful for opening a modal after a state change without needing to explicitly call the `present` method on `ion-modal`.

However, `isOpen` intentionally uses a one way data binding. The reason for this is it prevents the internals of `ion-modal` from being tightly coupled with the state of the application. 

With a one way data binding, the modal only needs to concern itself with the boolean value that the reactive variable provides. 

With a two way data binding, the modal needs to concern itself with both the boolean value as well as the existence of the reactive variable itself. This can lead to non-deterministic behaviors and make applications harder to debug.

You can still get this two way data binding flow, but Ionic puts developers in control of both directions to make it easier to a) reason about the code and b) debug the code if a bug occurs.

-----

The documentation on `isOpen` is not clear about this behavior, so I have created https://github.com/ionic-team/ionic-docs/pull/2284.

These docs should be live shortly on the docs website: https://ionicframework.com/docs/api/modal#inline-modals
