### ISSUE TITLE
bug: CSRF warnings in vue, menu starter app

### ISSUE THREAD

**Issue by ericis** [ionic-team/ionic-framework#25177]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Multiple CSRF warnings from any new, starter Vue application.

![image](https://user-images.githubusercontent.com/974919/164878525-75a20190-fa2a-4a72-abdd-cf98ff4a45f2.png)

### Expected Behavior

Zero warnings from any new, starter application.

### Steps to Reproduce

1. `npm exec -- @ionic/cli start vue-sidemenu sidemenu --type=vue`
2. `cd ./vue-sidemenu`
3. `yarn && yarn serve`
4. http://localhost:8080/
5. Open developer tools to "Console"
6. Observe multiple CSRF warnings

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.19.0 (C:\Users\iseri\AppData\Local\npm-cache\_npx\f6fddb685269761d\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.1.2

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : not installed
   @capacitor/core    : 3.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.1
   OS     : Windows 10
```

**Comment by sean-perkins** [comment]
Hello @ericis thank you for reporting this issue.

Following your reproduction steps, I am unable to reproduce these warnings. 

Based on your screenshot, it seems likely you have another application that you locally develop against `localhost:8080` and that write cookie values to. Ionic's UI does not reference nor create any cookies with `R_` conventions and would never capture and store usernames on your behalf. 

Can you please try in an incognito tab and let me know if the problem persists?

**Comment by ericis** [comment]
Thanks @sean-perkins . I should have tried that first as these cookies were simply already attached to "localhost" and had nothing to do with the Vue app. Closing...
