### ISSUE TITLE
bug: ion-picker not showing all options on Chrome

### ISSUE THREAD

**Issue by Artfloriani** [ionic-team/ionic-framework#25179]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [X] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When opening an ion-picker, the 3rd option below the selected value is not shown on Chrome. After scrolling the option renders properly. See the gif below, taken from the [ion-picker docs](https://ionicframework.com/docs/api/picker):

![Screen Recording 2022-04-23 at 14 30 11](https://user-images.githubusercontent.com/6491691/164923293-82380562-4124-4e07-a385-739030d84c4f.gif)

### Expected Behavior

By default, I expected to be able to see 2 options below and above the selected value on ion-picker, without having to scroll.

### Steps to Reproduce

On the latest version of Google Chrome:
1. Open the [Picker Docs](https://ionicframework.com/docs/api/picker);
2. Click on "Show Single Column Picker" on the example; 
3. You should be able to see that not all options are visible before scrolling;

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/***/.nvm/versions/node/v14.17.5/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.13
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI      : 2.4.7
   @capacitor/android : 2.4.7
   @capacitor/core    : 2.4.7
   @capacitor/ios     : 2.4.7

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   ios-sim : 8.0.2
   NodeJS  : v14.17.5 (/Users/***/.nvm/versions/node/v14.17.5/bin/node)
   npm     : 6.14.13
   OS      : macOS Monterey
   Xcode   : Xcode 13.3.1 Build version 13E500a
 ```

**Comment by sean-perkins** [comment]
Logged the root issue with the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1327051

We will be able to resolve this issue without them fixing the issue, but associating it for visibility.

**Comment by sean-perkins** [comment]
After investigating internals fixes we could make to resolve this issue, we have opted for waiting on the Chromium team's fix instead. Changing the `contain` styles causing this issue, changes the appearance of the rendered UI. 

Since this issue was recently shipped (Oct 2021) of Chrome and the team has already identified the likely commit introducing that change, we will wait on their resolution to avoid changing the visual experience for Ionic users.

**Comment by liamdebeasi** [comment]
Thanks for the report. I am going to close this as the issue has been fixed in the latest version of Google Chrome.
