### ISSUE TITLE
bug: Ionic animation / transitions not as smooth as should be 

### ISSUE THREAD

**Issue by NeroN7F** [ionic-team/ionic-framework#25181]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Ionic components like IonModal, sliders are having sharp transitions around 30 - 40 fps on mobile. They really smooth on desktop, but noticeably sharper on mobile [ iPhone XS Max, Safari 15.2 ]. Ion router transitions on ios in capacitor application with vue and ionic also feels jaggy, even if application has several pages. Should it work this way ? 30 - 45 fps are considered as normal for the animations? Thought that it might be caused because of the optimizational problems, but empty project representing the same issue

### Expected Behavior

60 fps animations and transitions on mobile platforms

### Steps to Reproduce

- Create ionic app on vue 3 
- Add Ion-modal component with ios mode

### Code Reproduction URL

https://codesandbox.io/s/ionic-6-vue-3-forked-wl8r9n?file=/src/components/IonSplit.vue&resolutionWidth=320&resolutionHeight=675

Video representing the problem:

https://user-images.githubusercontent.com/49721208/164988577-9b557e38-0780-43de-b3f5-abc144fc34f6.MP4

It is not that much noticable, as video recorded in 30fps, but in real its feels sharper

### Ionic Info

Ionic:

Ionic CLI : 6.19.0
Ionic Framework : @ionic/vue 6.0.14

Utility:

cordova-res : not installed globally
native-run : not installed globally

System:

NodeJS : v14.19.0 (/usr/local/bin/node)
npm : 7.17.0
OS : Linux 5.0

**Comment by NeroN7F** [comment]
> Thanks for the issue! This issue has been labeled as `needs reproduction`. This label is added to issues that need a code reproduction.
> 
> Please reproduce this issue in an Ionic starter application and provide a way for us to access it (GitHub repo, StackBlitz, etc). Without a reliable code reproduction, it is unlikely we will be able to resolve the issue, leading to it being closed.
> 
> If you have already provided a code snippet and are seeing this message, it is likely that the code snippet was not enough for our team to reproduce the issue.
> 
> For a guide on how to create a good reproduction, see our [Contributing Guide](https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction).

https://codesandbox.io/s/ionic-6-vue-3-forked-wl8r9n?file=/src/components/IonSplit.vue&resolutionWidth=320&resolutionHeight=675

**Comment by liamdebeasi** [comment]
Can you please clarify which part of the modal you are experiencing this issue with?

The modal opening animation is pretty smooth when testing on my iPhone 11 (iOS 15.2):

https://user-images.githubusercontent.com/2721089/165190746-d373022e-b5ab-462d-bf2b-63f2022700e3.MP4

 I do notice a framerate drop when dragging the modal. That is a matter of device performance and not a bug with Ionic. For context, I ran into something similar and reported this to the WebKit team at Apple: https://bugs.webkit.org/show_bug.cgi?id=205454

**Comment by liamdebeasi** [comment]
Here is the swiping gesture on my iPhone 11. There is a slight framerate drop, but it is still pretty smooth overall.

https://user-images.githubusercontent.com/2721089/165191082-6bd18e3d-84d7-4e85-ab64-b2af195589da.MP4

**Comment by NeroN7F** [comment]
Modal opens and closes smoothly, but while dragging, fps might suddenly drop down. I've tested on 11 pro and drops are slightly less noticeable, it is up to the performance. Turning off the swipe to close gesture is the only way for now. Are there any ways to make dragging faster maybe?

**Comment by NeroN7F** [comment]
> Modal opens and closes smoothly, but while dragging, fps might suddenly drop down. I've tested on 11 pro and drops are slightly less noticeable, it is up to the performance. Turning off the swipe to close gesture is the only way for now. Are there any ways to make dragging faster maybe?



> Here is the swiping gesture on my iPhone 11. There is a slight framerate drop, but it is still pretty smooth overall.
> 
>  RPReplay_Final1650929528.MP4

Modal opens and closes smoothly, but while dragging, fps might suddenly drop down. I've tested on 11 pro and drops are slightly less noticeable, it is up to the performance. Turning off the swipe to close gesture is the only way for now. Are there any ways to make dragging faster maybe?

**Comment by liamdebeasi** [comment]
Thanks for the follow up - that aligns with what I am seeing as well.

Unfortunately, this is a matter of device performance and not something Ionic is able to fix. From my previous observations this issue is limited to the following device families (including the pro/max models):

iPhone X
iPhone XS
iPhone 11

Any models before or after those devices seem to not be affected.

To further demonstrate how this issue is not related to Ionic's code, see this code sample on an affect iPhone: https://codepen.io/liamdebeasi/full/dyPvGPw. Dragging the blue squares with your finger also reproduces the issue in this simple test case.

You can also see the same behavior in another library like Framer Motion: https://www.framer.com/motion/. Drag the circle in the "Complex events and gestures" section to see the same issue.

------

The underlying issue appears to be a performance issue with touch event dispatch vs. rendering. This would explain why the modal opening/close animation is smooth, but the dragging gesture is not.

Does that answer your question?
