### ISSUE TITLE
feat: There should be an event for ion-accordion for handling whether ion-accordion is collapsed or expanded.

### ISSUE THREAD

**Issue by adnanganie** [ionic-team/ionic-framework#25193]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

There should be an event for ion-accordion for handling whether ion-accordion is collapsed or expanded.

### Describe the Use Case

isCollapsed or isExpanded.

**Comment by liamdebeasi** [comment]
Thanks for the issue. The `ionChange` event on `ion-accordion-group` tells you which accordion is expanded.

The event has type `AccordionGroupCustomEvent`: https://ionicframework.com/docs/api/accordion-group#accordiongroupcustomevent

This event includes a `detail` payload which includes the string value of the selected accordion(s). Any accordions included in that payload are expanded. Any accordions that are excluded from that payload are collapsed.

Does that work for your use case?
