### ISSUE TITLE
bug: styling issues when ion-split-pane is open

### ISSUE THREAD

**Issue by maelp** [ionic-team/ionic-framework#25210]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

When ion-split-pane is open, and to the left of the page, it shifts the content of the page in such a way that it's no longer possible to know where an element is on the screen.

For instance, I'm adding a D3.js visualization to my page, with a tooltip which is realized as a `div` with a `position: absolute` or `position: fixed`, and which moves the `div` style to `top: {curMouseEventPos.y}px; left: {curMouseEventPos.x}px` when there is a mouseover event

This works fine if the menu is not displayed

<img width="958" alt="image" src="https://user-images.githubusercontent.com/15458/165735653-a004db22-267b-4638-ac97-094ca8dae778.png">

But as soon as the menu is displayed, it seems that the mouseEventPos is not the correct one (or that setting it on my div does not have the proper effect)

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/15458/165734996-77782018-c967-4218-b97f-ec07feffa526.png">

and I have no idea how to set the div `position` and `top, left` parameters to account for the fact that the pane is open (also I'm not sure whether we can know if it's open)

### Expected Behavior

I would like to be able to set a `div` to `position: absolute` or `position: fixed`, and that its `top` and `left` position really correspond to what is on the screen, and not be shifted by the pane

For now, even setting the side-menu to "overlay", "reveal" or "push" does not change the issue. The only thing I could do is to set it's `side="end"` but I'd rather keep the menu on the left.

Is there a way to fix this? (have a `div` with an `absolute` position on the page where updating the `left, top` of the `div` corresponds to the actual position on the page, and is not shifted by the size of the side menu?)

### Steps to Reproduce

- create a side menu
- create an element on the page which is displayed at the location of the mouse cursor when hovering on another element, using `position: fixed`, and the `top, left` styles
- when the menu is closed, this works fine
- when the menu is open, the `div` position is shifted by the size of the side menu

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/Users/primet/.node/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.8.5

Capacitor:

   Capacitor CLI      : 3.3.1
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.1
   @capacitor/ios     : 3.3.1

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v16.14.0 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo I can use to verify this behavior?

**Comment by maelp** [comment]
There's no repo for this, but perhaps you have an idea of how to know whether the sidemenu is open or not, and how to correct for the size of the menu

**Comment by liamdebeasi** [comment]
Unfortunately it is going to be hard for us to verify/fix this behavior if we cannot reproduce the issue. 

The split pane component has an `ionSplitPaneVisible` event that fires whenever the split pane is expanded/collapsed: https://ionicframework.com/docs/api/split-pane#events

The menu itself has several lifecycle events you can use as well: https://ionicframework.com/docs/api/menu#events

**Comment by maelp** [comment]
(not sure how to capture mousemove so for now the tooltip only appears when you enter the hover div)

**Comment by maelp** [comment]
There are three tooltips, centering on either `event.screenX`, `event.pageX` or `event.clientX` to see if there was a difference. It seems the one we should use is `clientX`.

When the sidemenu is closed, this shows the tooltip at the location of the mouse when it enters the div (for instance if I enter next to the "hover" word):
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/15458/165775290-41f29c53-b01b-41ca-8326-adda48415469.png">

when the sidemenu is open however, it seems that the width of the menu is added when setting the position

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/15458/165775495-1e36ac44-0f4b-4b51-8490-c0266e39e1b1.png">

**Comment by liamdebeasi** [comment]
Thanks! This is not an Ionic bug. The issue here is where the tooltips are being added to the DOM.

The tooltip elements are placed inside of `ion-content`, so all of your `top` and `left` coordinates are going to be relative to the `ion-content`. However, the coordinates you are using are relative to the entire document (pageX and pageY), the entire screen (screenX and screenY), or the current layer (the "Hover me" element indicated by layerX and layerY, which is non-standard).

I recommend placing your tooltips in the root of your application (inside `App.vue`). This will allow you to use the coordinates returned in `mouseover` and it will also allow you to use tooltips across multiple containers.

Can you try that and let me know if it resolves the issue?

**Comment by liamdebeasi** [comment]
It depends on how you want to use the tooltips. If you want the tooltips to be used all over your app, it might be better to define them at the root of your application. (I assumed this use case, which might not be true for your app)

If you only need the tooltips inside of a single component then you can probably keep it where it is. The challenge here is you need to add additional logic to ensure that the tooltips are positioned correctly relative to its container. Alternatively, you could use something like Tippy.js (https://atomiks.github.io/tippyjs/).

**Comment by maelp** [comment]
I don't think this library would work because I have a specific use-case: I'm using tooltip over elements in an SVG built using d3

Is there a way for me to create an element in the root of the VueJS / ionic app from a specific Vuejs component?

**Comment by maelp** [comment]
As a reference, I solved it by adding an element in the body, and removing it on unmount:

```
let tooltip = undefined;

onMounted(() => {
  tooltip = document.createElement("div");
  document.body.appendChild(tooltip);
});

onBeforeUnmount(() => {
  tooltip !== undefined && tooltip.parentNode.removeChild(tooltip);
});
```
