### ISSUE TITLE
bug: long floating label text is not truncate and overflows out of input

### ISSUE THREAD

**Issue by holmio** [ionic-team/ionic-framework#25214]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

ion-label text is out of ion-item container.
<img width="346" alt="Screenshot 2022-04-29 at 11 25 20" src="https://user-images.githubusercontent.com/12999579/165919816-4f76cb2c-54fc-492e-bdc3-7315b44eb25f.png">

### Expected Behavior

The text should have an ellipsis if it is too long.

### Steps to Reproduce

`
    <ion-item fill="outline" mode="md">
      <ion-label position="floating">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In in erat
        eget libero rutrum commodo. Duis sed pharetra enim.</ion-label>
      <ion-input type="text"></ion-input>
    </ion-item>
`

### Ionic Info

Ionic:

   Ionic CLI: 6.19.0 (/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework: @ionic/angular 6.1.3
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli: 13.2.6
   @ionic/angular-toolkit: 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : not installed
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (/Users/user/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey

**Comment by enriqueloz88** [comment]
Any news on this?

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with ion-input. This issue is fixed when using that new syntax. Ionic 7 is currently in beta, and developers can find a migration guide on our documentation website: https://ionicframework.com/docs/v7/updating/7-0


The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
