### ISSUE TITLE
bug: React ionic build browser

### ISSUE THREAD

**Issue by Sano123456** [ionic-team/ionic-framework#25225]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I am following Ionic guides https://ionicframework.com/docs/react to create a samples project

when I use the command

ionic build browser
it generates a public/ directory with a blank HTML or without a proper configurated worker service

any idea on how I can build ionic react app?

### Expected Behavior

have a react project  ready to browser platform as done in angular

### Steps to Reproduce

ionic start myApp tabs --type react
ionic build browser

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.8

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : not installed
   @capacitor/core    : 3.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 8.5.4
   OS     : Linux 5.4

**Comment by liamdebeasi** [comment]
Thanks for the issue. Please see https://ionicframework.com/docs/react/pwa#service-worker-configuration for info on how to configure a service worker in your Ionic React app.

This is more of a support question, so I encourage you to post on the [Ionic Forums](https://forum.ionicframework.com/) with any additional questions you may have. Thanks!

**Comment by Sano123456** [comment]
@liamdebeasi I am not sure if it's about support

the generated HTML doesen't include any reference of service worker

`    
<script defer src="/static/js/bundle.js"></script>
`    
this script it present in the command ionic server it's not present  in the generate HTML 

What I mean is that the building of official demo project it's not working

**Comment by liamdebeasi** [comment]
The service worker is loaded from the `main.js` chunk in `build/static/js/main.[hash].js`. It is not added to `index.html`

In your `build` directory, there should be a `service-worker.js` file that `main.js` will reference. (You can search the main file for `service-worker.js`.
