### ISSUE TITLE
bug: scroll assist calls stopPropagation which can cause swipe to go back to break

### ISSUE THREAD

**Issue by colmunel** [ionic-team/ionic-framework#25229]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

Swiping right on a form with ion-input and ion-label that has position stacked or floating sometimes causes the app to get stuck between two pages. 

https://user-images.githubusercontent.com/104857648/166508595-324b1156-b862-4917-8869-f07e0e742cb1.MP4

### Expected Behavior

- If the user performs a "full swipe" the user get routed to the previous page.
- If the user aborts the swipe he/she stays on the page.
- In neither case the user is stuck between two pages.

### Steps to Reproduce

1. Create an `ion-content` containing multiple `ion-item`s with `ion-label` and `ion-input`. The `ion-label`s must have `position="stacked"` or `position="floating"`.
2. Put it on a page where you can swipe to get back to a previous page.
3. Click into an `ion-input`
4. Swipe right fast from the middle of the screen while the `ion-input` have focus. Sometimes this has to be done multiple times before the bug appears. 

It happens when swiping from the left of the screen or even scrolling fast too (probably slightly swiping right) but not as frequently and thus harder to reproduce. 

### Code Reproduction URL

[https://github.com/colmunel/test](https://github.com/colmunel/test)

### Ionic Info

Ionic:

   Ionic CLI: 6.18.2
   Ionic Framework: @ionic/angular 5.8.5
   @angular-devkit/build-angular: 0.1101.4
   @angular-devkit/schematics: 9.1.15
   @angular/cli: 11.1.4
   @ionic/angular-toolkit: 2.3.3

Capacitor:

   Capacitor CLI: 3.2.5
   @capacitor/android: 3.3.2
   @capacitor/core: 3.2.5
   @capacitor/ios: 3.3.2

Utility:

   cordova-res: not installed globally
   native-run: 1.5.0

System:

   NodeJS: v14.19.0
   npm: 6.14.15
   OS: Windows 10

### Additional Information

Bug appeared on iOS. Not tested on Android.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo I can use to verify this behavior? I am not seeing this on my end.

**Comment by colmunel** [comment]
I've updated the issue with a link to a repo. Note that it is difficult to reproduce. Try selecting another input field and swipe again a few times and eventually it will happen.

**Comment by liamdebeasi** [comment]
Did you push the entire reproduction? It looks like this is just a blank start app.

**Comment by colmunel** [comment]
Sorry. Now everything is committed.

**Comment by liamdebeasi** [comment]
We add a `touchend` listener on `ev.target` here: https://github.com/ionic-team/ionic-framework/blob/main/core/src/utils/gesture/pointer-events.ts#L43

When the bug reproduces, the `ev.target` is the native `input` element inside of `ion-input`. If you tap the label, the item, etc the issue does not reproduce.

**Comment by colmunel** [comment]
Thanks for looking in to it! I tested tapping the input again and it does complete the gesture but only if the input is the first thing that I click after the bug appears. But if I click elsewhere, I'm stuck.. Will this be fixed in a later release?

**Comment by colmunel** [comment]
Alright!

**Comment by liamdebeasi** [comment]
Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.1.6-dev.11652373111.19917404
```

Note: This is an Ionic 6 build. As a result, it is subject to the [Ionic 6 Breaking Changes](https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#version-6x).

**Comment by colmunel** [comment]
Yes, it seems to work, thank you. Will this only be fixed in version 6 or in version 5 as well?

**Comment by liamdebeasi** [comment]
This fix will only be applied to v6. Active development on v5 ended December 8, 2021.

See our [Maintenance and Support Page](https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status) for more info.

**Comment by colmunel** [comment]
Ok! Thanks for all the help, much appreciated!
