### ISSUE TITLE
bug: Property 'pinFormatter' does not exist on type IntrinsicAttributes & IonRange & Pick<HTMLAttributes<HTMLIonRangeElement>

### ISSUE THREAD

**Issue by brunogtds** [ionic-team/ionic-framework#25228]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

When I try to create a custom pin using Ion Rage with pinFormatter prop this bug appears. 

### Expected Behavior

Format the pin on Ion Range utilizing pin Formatter from the default integers to a time range.

### Steps to Reproduce

I'm using React, Typescript and Ionic 5.
My IonRange looks like this:

`<IonRange min={6} max={18} dual-knobs={true} step={0.5} ticks={true} pinFormatter={customFormatter} pin snaps dualKnobs={true} color="primary"> </IonRange>`

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0
   Ionic Framework : @ionic/react 5.5.2

System:

   NodeJS : v16.14.0
   npm    : 8.3.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. The `pinFormatter` property was added in Ionic 6: https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#600-beta2-2021-07-21

You will need to update to Ionic 6.0 or newer to use this feature.
