### ISSUE TITLE
bug: error using two events on ion-img

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#25233]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using multiple `ion-img` events such as `ionError` and `ionImgDidLoad` I will get an error on the console and the image flickers infinitely. Code as shown below

```
<ion-img #image [src]="'assets/img/loading-placeholder.png'" (ionError)="image.src = 'assets/img/loading-placeholder.png'" (ionImgDidLoad)="image.src = c.images.icon"></ion-img>
```

### Expected Behavior

Developers should be able to use multiple events and as for me, this is my use case

1. The `src` is used to show a placeholder image until the image from an API finish loading.
2. `ionError` is used when an image has an error from API, whatever set to `ionError` will be used.
3. `ionImgDidLoad` is used to show the finished loading image from an API

### Steps to Reproduce

1. Create a new Ionic Angular project
2. Paste the following code
```
<ion-img #image [src]="'assets/img/loading-placeholder.png'" (ionError)="image.src = 'assets/img/loading-placeholder.png'" (ionImgDidLoad)="image.src = c.images.icon"></ion-img>
```
3. Create a few `ion-item` and try to get a success image and error image from an API

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.3
   @angular-devkit/build-angular : 13.3.4
   @angular-devkit/schematics    : 13.3.4
   @angular/cli                  : 13.3.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : not installed
   @capacitor/core    : 3.5.0
   @capacitor/ios     : 3.5.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey

**Comment by farisfaisalthena** [comment]
`<ion-img #image [src]="'assets/img/loading-placeholder.png'" (ionError)="image.src = 'assets/img/loading-placeholder.png'" (ionImgDidLoad)="image.src = c.images.icon"></ion-img>`

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
