### ISSUE TITLE
bug: iOS card modal over card modal backdrop issue

### ISSUE THREAD

**Issue by SaroGFX** [ionic-team/ionic-framework#25236]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The sheet modal on iOS has a backdrop natively, but when you add this and show 2 or more modals over each other (modal over modal) the backdrop gets a bit of the glitch. 

<img width="419" alt="Screenshot 2022-05-04 at 15 44 09" src="https://user-images.githubusercontent.com/3781800/166694461-552bd399-4107-46fc-bdac-ca66e18a7d82.png">

I know that by default the backdrop is removed in Ionic. But since we have a light background, this just isn't an option for us, it just seems to connect too much with the background). So I'm looking for a solution or a workaround. 

### Expected Behavior

Only show backdrop of top layer modal

### Steps to Reproduce

1. Create a card modal and then another one with that previous modal as presentingElement 
2. Add backdrop opacity to modal 

```
ion-modal::part(backdrop) {
    opacity: 0.3;
}
````

### Code Reproduction URL

https://github.com/SaroGFX/modal-over-modal.git

### Ionic Info

Ionic:

Ionic CLI : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/react 6.0.13

Capacitor:

Capacitor CLI : 3.4.1
@capacitor/android : 3.4.1
@capacitor/core : 3.4.1
@capacitor/ios : 3.4.1

Utility:

cordova-res : 0.15.4
native-run : 1.5.0

System:

NodeJS : v16.14.0 (/usr/local/bin/node)
npm : 8.3.1
OS : macOS Monterey

### Additional Information

Created demo - see repo

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you help me understand why you need to force the backdrop to be visible with the card modal? The backdrop is not utilized in a native card modal too.

**Comment by liamdebeasi** [comment]
In general we do not recommend changing the background color of `ion-app` when using the card. Native iOS apps set a black background for this reason, and we do not recommend overriding it.

**Comment by SaroGFX** [comment]
We changed the the ion-page background to white because it was showing black during transitions of pages, between splash screen, etc. Also our header is not part of the `presentingElement` so it doesn't move and will not show the ion-page color anyways. 

I understand this is more of a feature request maybe, but if you have any ideas on how to work around this, that would be appreciated!

**Comment by liamdebeasi** [comment]
> We changed the the ion-page background to white because it was showing black during transitions of pages, between splash screen

Do you have an example of this? If you are seeing flashes of black during page transitions that sounds like a bug.

**Comment by SaroGFX** [comment]
So i didn't spot this black flashing issue in person, but another dev added this line of css for that reason. I will remove that background color, and see if i can reproduce the issue, and create a relevant bug report for it.  But it is unrelated for this issue, as we use a fixed header and use the content below it as a presentingElement. So this means that the header is never animated, only the content below it (see screenshot in OP). So we never see the ion-app background in this case. 

So as I understand it we could use the entire app as a presentingElement. But I'm not sure if this is desired UX wise as we have a toolbar header with a burger menu button. The native examples i've seen only kinda do this with 

Another option could be if we could turn off the background scaling animation somehow. This would also stop the scaling of the background. I think we could just do that by using sheet modals with a breakpoint at 1. 

But the nicest solution would be if we could somehow only show the backdrop of the top modal OR not scale the backdrop in the animation. I understand now that this is more of a feature request, so feel free to address is at such and close this bug ticket. Thank you!
