### ISSUE TITLE
bug: @axe-core/playwright should not be a dependency of @ionic/core

### ISSUE THREAD

**Issue by emeryao** [ionic-team/ionic-framework#25242]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

the package of `@axe-core/playwright` is now a dependency of `@ionic/core` `v6.1.4` in [core/package.json](https://github.com/ionic-team/ionic-framework/commit/87f584001ba4714b297a03dfddd8ae308d6aa2e6#diff-7f67769260741e2563407af949f7e54fbf0431d1c607933f6e8a8094e3219e26R34) which made my CI failed during downloading the playwright executable binaries 
and IMHO this package and binaries are not nessary for building my ionic/angular project

### Expected Behavior

move the dependency of `@axe-core/playwright` from `@ionic/core` to `devDependencies` in package.json

### Steps to Reproduce

install the package of `@ionic/angular`@v6.1.4

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\me\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.4
   @angular-devkit/build-angular : 13.3.5
   @angular-devkit/schematics    : 13.3.5
   @angular/cli                  : 13.3.5
   @ionic/angular-toolkit        : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.1.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.9.0
   OS     : Windows 10

---
Sorry for my poor English 😄

**Comment by marceloluzbmo** [comment]
Yeah I agree, this broke our CI build process as well. We are now version locking the dependencies (which we probably should have done in the first place) but this shouldnt be a required dependency

**Comment by sean-perkins** [comment]
This has been merged in and will be available in the `nightly` builds. Liam is out on vacation for the remainder of the week, but will discuss on Monday if we should push out a new patch fix for this before our regular Wednesday release. 

Appreciate the timely reporting of this problem. Let me know if a dev-build would be helpful in the interim and I can provide one (if there a is bug fix in the latest patch that you need to take advantage of).
