### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by matthew-berends** [ionic-team/ionic-framework#25241]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Apologies I don't know how to re-open an issue 
Issue #24704
When selecting time in a sheet modal, the value does not appear or update at times. 
I am using android device.

### Expected Behavior

Current value to display, value to be updated.

### Steps to Reproduce

As in Issue #24704

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\Matthew.berends\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 6.1.2
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 20 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 1.5.0

System:

   NodeJS : v14.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.11
   OS     : Windows 10

**Comment by amandaejohnston** [comment]
Thanks for the issue. Would it be possible to provide a screen recording of the behavior? I am unable to reproduce the issue following the provided steps, so a recording may help ensure we're on the same page.

**Comment by matthew-berends** [comment]
https://user-images.githubusercontent.com/104947425/167074357-38be57e3-cfa1-4735-ae25-16e8c61fa38b.mp4

**Comment by matthew-berends** [comment]
The issue comes from trying to do the ion-datetime 'time' within an inline modal sheet (other modals work).
Running on android.

**Comment by liamdebeasi** [comment]
What is the version of the Chrome webview you are using on the Android device? You can find this by logging `window.navigator.userAgent` when debugging the app using Chrome Dev Tools.

Also do you have a GitHub repo we can use to verify this behavior?
