### ISSUE TITLE
feat(nav-animations): export default ios and md transitions 

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#25243]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The default page transitions for ios and md should be exposed to the developers so we can use them to create custom animations.

### Describe the Use Case

I have a page transition, where the forward animation is just a fade-in effect. The back navigation should stay as it is (on ios transition from right to left).
Currently i have to inspect the ionic core code and paste the code to my method where i apply the animation.

```typescript
    const enterAnimation = (baseEl: HTMLElement, opts: any): Animation => {
      if (opts.direction === 'forward') {
        return this.animationController
          .create()
          .addElement(opts.enteringEl)
          .duration(1000)
          .easing('ease-in')
          .fromTo('opacity', '0', '1');
      }
      // default ios back transition
      return null;
    };
```

### Describe Preferred Solution

the ability to import the default ios transition to my page

```typescript

  import { ..., iosTransitionAnimation } from '@ionic/core'

  private async navigateToPage(): Promise<void> {
    const enterAnimation = (baseEl: HTMLElement, opts: any): Animation => {
      if (opts.direction === 'forward') {
        return this.animationController
          .create()
          .addElement(opts.enteringEl)
          .duration(1000)
          .easing('ease-in')
          .fromTo('opacity', '0', '1');
      }
      // default ios back transition
      return iosTransitionAnimation.direction('reverse');
    };

    await this.ionNav.push(TransferPointsPage, null, {
      animationBuilder: enterAnimation,
    });
  }
```

**Comment by sean-perkins** [comment]
Hello @DwieDima thanks for opening this feature request! I think this has a lot of overlap with #24964 and would like to combine the two feature requests. 

Can you upvote that feature request to let us know you want it?

I will close this request out, but will comment on the other request regarding details from this thread. Thanks!
