### ISSUE TITLE
bug: `ion-datetime` cannot navigate to previous months after presenting and re-opening in a popover

### ISSUE THREAD

**Issue by Agular** [ionic-team/ionic-framework#25257]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The user opens the ion-datetime in a popover, selects a date and closes it.
When the use opens it again and tries to navigate the months via arrows, the rows change with the animation, but the month label does not change. Also, when the user clicks on the date, it causes the month to change
![inlineDatetimeMonthChangeBug](https://user-images.githubusercontent.com/18621326/167408492-728e6240-26d3-479a-8489-aaf80a89543a.gif)

### Expected Behavior

The user opens the ion-datetime in a popover, selects a date and closes it.
When the use opens it again and tries to navigate the months via arrows, the rows change with the animation and the month label changes accordingly. Also, when a date is selected, no change to month selection occurs.

### Steps to Reproduce

1) Click on button to open ion-datetime in a popover.
2) Select some date
3) Click on backdrop to dismiss
4) Open ion-datetime again from the button
5) Try navigating the months from the arrows
6) Previous / next month rows are displayed, but month label does not change
7) Clicking on a date after trying to navigate the months causes the month to change.

Code reproduction
```
<ion-app>
  <ion-content>
    <ion-button id="randomId">
      <ion-icon icon="calendar"/>
    </ion-button>
    <ion-popover trigger="randomId">
      <ion-content>
        <ion-datetime/>
      </ion-content>
    </ion-popover>
  </ion-content>
</ion-app>
```

### Code Reproduction URL

https://codepen.io/agular/pen/PoQNZQB

### Ionic Info

Ionic used as a dependency.

### Additional Information

Occurs with the latest version of Ionic, 6.1.4

**Comment by sean-perkins** [comment]
Thanks for reporting this issue! I am able to reproduce the problem as well.

It appears that after you select a date and close the popover, when re-opening the popover, the back navigation will get stuck/present navigating to the previous month. This behavior does not happen for navigating forward. If when you cannot return to the previous month, you instead navigate forward, you can now navigate back to the previous months freely.

We will capture this as a bug and prioritize.

**Comment by Agular** [comment]
@sean-perkins I would say that this bug occurs also when navigating forward. And in order to get past the stuck month, you need to move backwards and then you can again move forwards past the stuck month.

**Comment by Agular** [comment]
@sean-perkins , can you please give a status update on this bug?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25586, and a fix will be available in an upcoming release of Ionic Framework.
