### ISSUE TITLE
bug: vue, switching tabs causes wrong view to be unmounted

### ISSUE THREAD

**Issue by Jannik-KJ** [ionic-team/ionic-framework#25255]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

App crashes when navigating between tabs and tabs child pages.

Error thrown:

` Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'mount')
    at Object.unmountLeavingViews (index.esm.js?ba1f:802:1)
    at handlePageTransition (index.esm.js?58b7:1320:1)`

### Expected Behavior

The application can navigate between tabs and child pages of tabsThe application

### Steps to Reproduce

on start page (tab 1) ->
1) Click "go to child page"
2) click TAB 2
3) click TAB 1
4) click TAB 1 again
5) click TAB 2
6) click TAB 1
7) Click "go to child page"
8) click TAB 2
9) click TAB 1
10) click TAB 1 agina

### Code Reproduction URL

https://github.com/Jannik-KJ/ionic-6-router

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.1.3

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : not installed
   @capacitor/core    : 3.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by anttironty** [comment]
Hi, this issue is present in our app aswell with Ionic versions over 6.0.8-dev.1644430127.1b9bb92

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/vue@6.1.5-dev.11652207609.1ba60afe @ionic/vue-router@6.1.5-dev.11652207609.1ba60afe
```

**Comment by Jannik-KJ** [comment]
@liamdebeasi I can confirm that this build solves our issues as well! 👍

**Comment by liamdebeasi** [comment]
You can keep the issue open for now. We will close the issue once the fix has been merged into the `main` branch.
