### ISSUE TITLE
bug: Degraded modal transition performance on Safari with card modal

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#25251]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When opening a card modal on Safari vs. other browsers, Safari is noticeably slow and presents the transition in an extremely long period of time.

|Browser|Time|
|---|---|
|Chrome|`557.368896484375 ms`|
|Chrome|`538.986328125 ms`|
|Chrome|`539.40625 ms`|
|Firefox|`548ms`|
|Firefox|`547ms`|
|Firefox|`546ms`|
|Safari|`1747.175ms`|
|Safari|`2017.969ms`|
|Safari|`2016.167ms`|

This seems to be tied to the `presentingElement` being set. If the `presentingElement` is `null`, the modal transitions at a regular interval.

### Expected Behavior

Card modal should transition open at a respective time interval. 

### Steps to Reproduce

1. Clone our private repo: https://github.com/ionic-team/ioniconf-app
2. Checkout the `debugging` branch
3. Run/open the app and visit the second tab (Speakers tab)
4. Tap the speaker card
5. See the degraded performance on Safari
6. Compare against other browsers

Time logging is enabled to display the time it takes to present the modal, in the console.

### Code Reproduction URL

https://github.com/ionic-team/ioniconf-app

### Ionic Info

N/A

### Additional Information

This may be a webkit bug, but we need to identify what is causing it.

**Comment by sean-perkins** [comment]
This may be an implementation issue. I removed the filter applied on the host element and that greatly improved performance:

```css
filter: drop-shadow(0px 0px 1px rgba(1, 5, 14, 0.08))
    drop-shadow(0px 4px 8px rgba(1, 5, 14, 0.06))
    drop-shadow(0px 8px 32px rgba(1, 5, 14, 0.04));
```

**Comment by sean-perkins** [comment]
Safari (Web) Version 15.4 (17613.1.17.1.13). 

Also tested with iPhone XS Max (iOS 15.4.1). I believe Connor was on iPhone 12 and also had this same performance hit.

**Comment by liamdebeasi** [comment]
I'm getting some errors on the repro:

```
ng] ./src/app/app.module.ts:9:0-58 - Error: Module not found: Error: Can't resolve '../environments/environment' in '/Users/liamdebeasi/Ionic/ioniconf-app/src/app'
[ng] 
[ng] ./src/app/services/hubspot.service.ts:4:0-59 - Error: Module not found: Error: Can't resolve 'src/environments/environment' in '/Users/liamdebeasi/Ionic/ioniconf-app/src/app/services'
[ng] 
[ng] ./src/app/services/prismic.service.ts:6:0-59 - Error: Module not found: Error: Can't resolve 'src/environments/environment' in '/Users/liamdebeasi/Ionic/ioniconf-app/src/app/services'
[ng] 
[ng] ./src/main.ts:4:0-57 - Error: Module not found: Error: Can't resolve './environments/environment' in '/Users/liamdebeasi/Ionic/ioniconf-app/src'
[ng] 
[ng] Error: src/app/app.module.ts:8:29 - error TS2307: Cannot find module '../environments/environment' or its corresponding type declarations.
[ng] 
[ng] 8 import { environment } from '../environments/environment';
[ng]                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: src/app/services/hubspot.service.ts:3:29 - error TS2307: Cannot find module 'src/environments/environment' or its corresponding type declarations.
[ng] 
[ng] 3 import { environment } from 'src/environments/environment';
[ng]                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: src/app/services/prismic.service.ts:5:29 - error TS2307: Cannot find module 'src/environments/environment' or its corresponding type declarations.
[ng] 
[ng] 5 import { environment } from 'src/environments/environment';
[ng]                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: 9msrc/main.ts:5:29 - error TS2307: Cannot find module './environments/environment' or its corresponding type declarations.
[ng] 
[ng] 5 import { environment } from './environments/environment';
[ng]                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng] 
```

**Comment by liamdebeasi** [comment]
Discussed offline with Sean. This was an implementation issue. There is likely some improvements Safari can make when handling `filter`, but Ionic is not the cause of the issue.

As an alternative, we discussed using `box-shadow` instead of `filter`.
