### ISSUE TITLE
bug: item counter has poor visibility on dark mode

### ISSUE THREAD

**Issue by enriqueloz88** [ionic-team/ionic-framework#25262]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The ion-note that contains the counter has not the proper contrast in dark mode. This is due to the opacity effect that the color has on the .item-counter class. If we delete the rule `color: rgba(0,0,0,0.6)`, the counter now looks good in both modes, dark and light

![image](https://user-images.githubusercontent.com/61509169/167504227-9855244d-5174-4a2f-bff0-a76b92ae17d1.png)

The counter looks like this in light and dark mode right now (current behavior):

![image](https://user-images.githubusercontent.com/61509169/167505283-d1d30087-0254-40a8-a47e-1e5444e9843f.png)
![image](https://user-images.githubusercontent.com/61509169/167505361-28ab5bd1-68cc-4bd6-915f-099608d20fc2.png)

And without this opacity:

![image](https://user-images.githubusercontent.com/61509169/167505465-d4e65489-d9b0-4728-99e5-358d3cec0266.png)
![image](https://user-images.githubusercontent.com/61509169/167505435-28d459b7-5e68-4260-b900-3cdea76177b4.png)

### Expected Behavior

Ion-note should appear with the proper contrast in dark and light mode

### Steps to Reproduce

Just type an ion-item with the [counter]="true", and set the dark-mode in your navigator:

```
    <ion-item fill="outline" [counter]="true">
      <ion-label position="floating">Label</ion-label>
      <ion-input maxlength="20" type="text" placeholder="My placeholder"></ion-input>
    </ion-item>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (C:\Users\kikel\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.4
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.1.5-dev.11652188603.1840a797
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25266, and a fix will be available in an upcoming release of Ionic Framework.
