### ISSUE TITLE
bug: ion-datetime - the next and previous buttons occasionally omit a month

### ISSUE THREAD

**Issue by LuyCki** [ionic-team/ionic-framework#25265]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The user opens the ion-datetime in a modal, tap the next and previous buttons (< and >) and occasionally a month is skipped when these buttons are tapped.

https://user-images.githubusercontent.com/33394650/167609741-01343f04-ab79-48ae-b65f-2ac56d97fe12.mp4

We reproduced it on Xiaomi MI9, MIUI 12, Android 10. 

On iOS, browsers and Android emulators it's working fine.

On physical device with Android 12, seems to be working fine, very rarely when I randomly press the buttons, seems to skip a month. 

### Expected Behavior

Every time the button is tap, the next / previous month is displayed.

### Steps to Reproduce

1. The user opens the ion-datetime in a modal
2. Tap the next and previous buttons (< and >)
3. Watch how, occasionally, a month is skipped when these buttons are tapped

Code reproduction

```
  <ion-item button [detail]="false" id="open-date-birth-modal">
    <div class="register__date-input">
      <div>
        <ion-label position="floating">Date of birth</ion-label>
        <ion-input readonly type="text" formControlName="dateOfBirth"></ion-input>
      </div>
      <ion-icon class="text-color" name="calendar-clear-outline"></ion-icon>
    </div>
  </ion-item>

  <ion-modal trigger="open-date-birth-modal">
    <ng-template>
      <ion-content>
        <ion-datetime formControlName="dateOfBirth" color="tertiary" #dateBirthModal showDefaultTitle="true" presentation="date"
          (ionChange)="onBirthDateChange(dateBirthModal)">
          <div slot="title">Select the date of birth</div>
        </ion-datetime>
      </ion-content>
    </ng-template>
  </ion-modal>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.11
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.2 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by LuyCki** [comment]
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/33394650/168264665-60560b01-269d-44af-a912-d74d32036c71.png)

**Comment by liamdebeasi** [comment]
Thanks! Can you also provide a GitHub repo I can use to verify this behavior? I am unable to reproduce this issue on my end.
