### ISSUE TITLE
feat: Support for chromium target on IOS

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/ionic-framework#25275]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The WKwebview which Ionic currently target, is webkit based, which leads to many inconsistencies with the android chromium webviews, performance limitations and an increasing number of missing features/interop.
As you know it, Apple is doing the crazily anticompetitive practice of disallowing other browsers to be installed on the platform.
However, this is changing:
The European Union has almost finished a [document](https://www.theregister.com/2022/04/26/apple_ios_browser/) that would obligate Apple to allow other browsers, effective in 2024, so in 2 year.
This is disruptive and will greatly increase the value propositions of Ionic apps vs native.
Therefore this issue is a request for you to anticipate in advance, desirable changes including API changes, that would make it easier for Ionic to bring support for shipping a chromium webview on IOS in 2024, as an optin target.

### Describe the Use Case

Improve the quality/performance/correctness of apps.

### Describe Preferred Solution

proactive reflexion for how to best support it, e.g. API wise from the Ionic POV.

### Describe Alternatives

Not being competitive and let the web stay stagnant

### Related Code

.

### Additional Information

.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is not the correct place to make this feature request. Ionic Framework manages the UI layer of the app and does not control the webview itself.

Additionally, Ionic Framework is already compatible with the Chromium engine. If the Chromium engine were to come to iOS, Ionic Framework should work fine.

[Capacitor](https://github.com/ionic-team/capacitor) might need to make some changes, but any changes required cannot be made preemptively as they likely would require new APIs from Apple or Google. As a result, there is nothing actionable from the Ionic Team until this change actually happens.

I am going to close this. Thanks!
