### ISSUE TITLE
bug: inset list forces extra border on item when no border is needed

### ISSUE THREAD

**Issue by dexster** [ionic-team/ionic-framework#25278]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

ion-accordion bottom border on an expanded item has normal 1px height and then 2px height after about 10px across.

Look underneath the "Red" text in the image.
  
![accordion style](https://user-images.githubusercontent.com/6392334/167869788-0329e4a6-842e-462f-84e3-3c7d135f350b.png)
 

### Expected Behavior

Expect consistent border height 

### Steps to Reproduce

Look at the android simulator on this page. Expand "Colors". It only seems to happen underneath the first item (Red).

https://ionicframework.com/docs/api/accordion
![replicate](https://user-images.githubusercontent.com/6392334/167870885-33cd6b66-f09b-46f1-8932-51d29a7e1b4b.png)

### Ionic Info

Ionic:

   Ionic CLI : 6.18.2

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.0
   npm    : 8.3.1
   OS     : macOS Monterey

@ionic/angular@6.1.4

**Comment by liamdebeasi** [comment]
Thanks for the issue. This line appears to be the culprit: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/list/list.md.scss#L29

Inset lists on MD should remove the top border from the first item and the bottom border from the last item. However, the fix was done such that it forced the bottom border on the first item and assumed that it would never be removed.
