### ISSUE TITLE
bug: macbook m1 run ios simulator (IOS 15)

### ISSUE THREAD

**Issue by gautamsinh** [ionic-team/ionic-framework#25281]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I have developed my using ionic it working fine Iphone and other real device but when I run APP in simulatore (IOS 15) style and images not being loaded, it is working fine in Simulatore(IOS 13) 

My machine: Macbook M1 silicon
you can find my ionic info and bug screenshot in attachment 
IONIC info: 
![image](https://user-images.githubusercontent.com/20943477/168008384-8db64287-0506-4325-8af3-c6648e6a5bfe.png)

ISSUE in SImulator(IOS 15) 
![image](https://user-images.githubusercontent.com/20943477/168008591-53dc46cf-91d6-4b86-af64-c3b017abd613.png)

Working in Simulator(IOS 13)
![image](https://user-images.githubusercontent.com/20943477/168009312-2889f220-50f8-4034-b951-a4cc270129bd.png)

Note: I setup Fresh project just with ionic starter and it is not working in it also 

Thank you

### Expected Behavior

CSS and Image should work in SIMULATOR (IOS 15)

Working in Simulator(IOS 13)
![image](https://user-images.githubusercontent.com/20943477/168009312-2889f220-50f8-4034-b951-a4cc270129bd.png)

### Steps to Reproduce

You can start with IONIC starter, you can find issue in M1 simulator (IOS 15)

### Ionic Info

![image](https://user-images.githubusercontent.com/20943477/168009865-b4149871-50c3-45de-a5a1-0ddfca79cb56.png)

### Additional Information

I found issue  reported here  [24658](https://github.com/ionic-team/ionic-framework/issues/24658)  but can not find solution in it

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are any errors in the console?

I tested this on an M1 Mac with the iPhone 11 Pro Max simulator with iOS 15.4 and was unable to reproduce this issue:
![Screen Shot 2022-05-12 at 9 25 56 AM](https://user-images.githubusercontent.com/2721089/168085680-93249089-b3e6-497e-bd77-b5efbccf3b4b.png)

**Comment by gautamsinh** [comment]
Hello 

Is there any special setup of XCODE version or anything else ?


as you can see I can not view icons and style anything in html 

In console it only display style is not found 
![image](https://user-images.githubusercontent.com/20943477/168235064-edc2937a-7c39-41d7-b31c-3dad188de64e.png)

CSS is blank 
![image](https://user-images.githubusercontent.com/20943477/168235238-97d4b455-5b93-4758-86ef-4450a9998358.png)

**Comment by liamdebeasi** [comment]
It looks like there are no styles in `styles.css` which would explain why there is no styling in your application. I would recommend looking in your built project to make sure the styles are being generated correctly.
