### ISSUE TITLE
bug: :host selector on element combined with rtl mixins does not create the proper selector

### ISSUE THREAD

**Issue by crazyserver** [ionic-team/ionic-framework#25285]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x
- [X] Nightly

### Current Behavior

With the following CSS:

```css
:host .element-selector {
    @include position(0, 0, null, null);
}
```

When using the `rtl` mixin so, also `add-root-selector` it translates the selector as:

```css
:host-context([dir=rtl])
```

So part of it is lost.

### Expected Behavior

With the following CSS:

```css
:host .element-selector {
@include position(0, 0, null, null);
}
```

When using the rtl mixin so, also add-root-selector it translates the selector as:

```css
:host-context([dir=rtl]) .element-selector
```

Maintaining the whole selector.

### Steps to Reproduce

1. Create a blank template
2. Add a div.test-element to the HTML
3. Add the following code to the related CSS:
```css
:host .test-element {
    @include position(0, 0, null, null);
}
```
4. Run the app, inspect code of the created div and check css is not included on the element.
5. You can also check the resulting selector is not correct on the generated css.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/Users/pau/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, (and 22 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.5.0)   : 1.4.0

System:

   ios-sim : 8.0.2
   NodeJS  : v16.14.2 (/Users/pau/.nvm/versions/node/v16.14.2/bin/node)
   npm     : 8.5.0
   OS      : macOS Monterey
   Xcode   : Xcode 13.3 Build version 13E113

**Comment by liamdebeasi** [comment]
Some clarified steps to reproduce:

1. Open an existing E2E HTML file in core.
2. Set the body to the following:
```html
<ion-img src="https://picsum.photos/200/300"></ion-img>
```

3. In `src/components/img/img.tsx` add the following right before the `<img>` declaration:
```html
<div class="test-element">my test element</div>
```

4. In `src/components/img/img.scss` add the following styles:
```css
@import "../../themes/ionic.globals";

...

:host {
  width: 300px;
  height: 300px;
}

:host .test-element {
  @include position(null, null, null, 50px);

  position: relative;

  background: red;
}
```

5. Open the E2E HTML file in the browser. Observe that the image and the test element are adjusted on the left by 50px.
6. Add `?rtl=true` to the URL and press "Enter". Observe that the image is adjusted on the right by 50px, but the test element is not.
7. Apply the fix in https://github.com/ionic-team/ionic-framework/pull/25264. Observe that both the image and the test element are adjusted on the right by 50px.
