### ISSUE TITLE
feat: Optimize ion-img by leveraging the image decoding API

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/ionic-framework#25284]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Note: This issue is totally unrelated with the issue I opened about ion-img event listener leaks.

The asynchronous image decoding API is an alternative to the img tag alone, which prevents image insertion in the DOM blocking the main JS thread, which is a major cause of stutter/jank
https://medium.com/dailyjs/image-loading-with-image-decode-b03652e7d2d2
It is supported in chromium derivatives since a while https://chromestatus.com/feature/5637156160667648
actually it's supported in every browsers.
Of course benchmarking would be nice.
@liamdebeasi friendly ping

### Describe the Use Case

> prevents image insertion in the DOM blocking the main JS thread, which is a major cause of stutter/jank
more performance is good, and a compeititve advantage for Ionic

### Describe Preferred Solution

benchmarking/profiling showing it works as intended without reducing throughput

### Describe Alternatives

blocking the DOM

### Related Code

The linked blog post has examples of this very simple API.

### Additional Information

https://chromestatus.com/feature/5637156160667648 contains useful external links, such as demos
and documentation

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify what you would like changed in `ion-img`? `ion-img` already uses async decoding: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/img/img.tsx#L116

**Comment by liamdebeasi** [comment]
Also, you do not need to ping me for every issue you create. The team regularly reviews open issues, so we will see any issue you open.
