### ISSUE TITLE
bug: actionsheet does not match iOS device

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#25297]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The Actionsheet component looks like it does not match with the iOS ActionSheet. Screenshot is as below
![IMG_2576](https://user-images.githubusercontent.com/61012396/168732396-cdeef3d5-24d4-405a-975c-93355cbeb057.PNG)

### Expected Behavior

Below are the comparison

Ionic Actionsheet
![IMG_2576](https://user-images.githubusercontent.com/61012396/168732632-086cd27a-3273-4104-b420-b7076361ec8c.PNG) 

Apple iOS 15 Actionsheet
![IMG_2575](https://user-images.githubusercontent.com/61012396/168732696-bc7827be-2261-48cb-be98-e1aa8eb3e146.PNG)

### Steps to Reproduce

Create a fresh Ionic Angular Project

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.5
   @angular-devkit/build-angular : 13.3.5
   @angular-devkit/schematics    : 13.3.5
   @angular/cli                  : 13.3.5
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
