### ISSUE TITLE
bug: react, parameterized routes causing cloned elements to be misplaced

### ISSUE THREAD

**Issue by ckubitza** [ionic-team/ionic-framework#25321]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Using react. When going from a page to the same page (with a different parameter) an IonInput is jumping to the right while the page transition is active.

![bug-screencast](https://user-images.githubusercontent.com/13765635/169325114-71a57ae9-dc28-46b0-83c9-9219eab15055.gif)

### Expected Behavior

The IonInput should not jump.

### Steps to Reproduce

Have an IonInput on a page with a route parameter and navigate (by routerLink) to the same page with another parameter value.

### Code Reproduction URL

https://github.com/ckubitza/ionic-input-page-transition-bug

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.1
   Ionic Framework : @ionic/react 6.1.6

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.14.0
   npm    : 8.3.1
   OS     : Windows 10

### Additional Information

From my observations, the IonInput component accidently has two native inputs inside while the transition is happening (you can break execution on ionViewWillEnter to see it).

![duplicate-input](https://user-images.githubusercontent.com/13765635/169325029-eec7973f-b138-4278-bdcf-b1f2d5045e36.png)

**Comment by liamdebeasi** [comment]
This appears to be the culprit: https://github.com/ionic-team/ionic-framework/blob/main/packages/react-router/src/ReactRouter/StackManager.tsx#L230-L234

When we transition to another instances of the same component `@ionic/react-router` attempts to clone the DOM nodes. This results in a duplicate `input` element inside of `ion-input`.

**Comment by puopg** [comment]
@liamdebeasi Could you help me understand, what's the design choice for cloning the page element for transitions to the same component? 

To me, it seems weird to have a page leave, and the same page with all the same elements and state of those elements also come back in.

**Comment by liamdebeasi** [comment]
Hey there,

Apologies for the delay. This issue was resolved in https://github.com/ionic-team/ionic-framework/pull/28616. The fix is available in Ionic 7.5.8, so I am going to close this.
