### ISSUE TITLE
bug: clicking trigger for nested popover closes parent popover (React and Vue only)

### ISSUE THREAD

**Issue by amandaejohnston** [ionic-team/ionic-framework#25324]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When clicking an item in a popover that, using `trigger`, opens a nested popover, and the parent popover has `dismissOnSelect` set, the parent popover closes as the nested one opens.

This only triggers in React or Vue. In Angular and core, the parent popover stays open.

### Expected Behavior

The parent popover should stay open, per the docs: https://ionicframework.com/docs/api/popover#nested-popovers

> This behavior does not apply when clicking a trigger element for another popover.

### Steps to Reproduce

1. https://github.com/amandaejohnston/sandbox-ionic-react/tree/nested-popovers
2. Click "Click to Open Popover"
3. Click "More options..."
4. Observe that parent popover closes

### Code Reproduction URL

https://github.com/amandaejohnston/sandbox-ionic-react/tree/nested-popovers

### Ionic Info

```
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\moogl\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.1.6

Capacitor:

   Capacitor CLI      : 3.3.2
   @capacitor/android : not installed
   @capacitor/core    : 3.3.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 10
```

### Additional Information

In React, the issue reproduces as far back as `6.0.0-beta.6` and no further, so it's likely CE related. Note that `dismissOnSelect` was added in `6.0.0-beta.0`.

**Comment by liamdebeasi** [comment]
This issue reproduces on Ionic 6 but not on Ionic 7. Going to close this as it appears to have been resolved. Thanks!
