### ISSUE TITLE
bug: not clear that helper/error text slots should only be used with text inputs

### ISSUE THREAD

**Issue by dimitarmar** [ionic-team/ionic-framework#25332]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I am trying slot error , it works for ion-input fields, but seems it doesn’t work for ion-checkbox and for the ion-radio-group .

### Expected Behavior

in the .ts file 
```
private buildForm() {
        this.form = this.formBuilder.group({
            'checkBox':[null, [Validators.required]],
            'radioButtonGroup':[null, [Validators.required]],
        });
    }
```

in the .html template 
```

<ion-item>
        <ion-label position="stacked">Check box</ion-label>
        <ion-checkbox position="fixed" formControlName="checkBox"></ion-checkbox>
        <ion-note slot="error"> Please select</ion-note>
    </ion-item>

    <ion-list >
        <ion-radio-group formControlName="radioButtonGroup" >
            <ion-list-header>
                <ion-label>Radio button Group</ion-label>
            </ion-list-header>

            <ion-item>
                <ion-label>Selection1</ion-label>
                <ion-radio slot="start" value="Selection1"></ion-radio>
            </ion-item>
            <ion-item>
                <ion-label>Selection3</ion-label>
                <ion-radio slot="start" value="Selection3"></ion-radio>
            </ion-item>
        </ion-radio-group>
        <ion-note slot="error"> Please select</ion-note>
    </ion-list>

```
The expected behaivor is to be shown "Please select" under the check-box field and under the list of radio buttons in the case there is no checked or not selected an option

### Steps to Reproduce

crete a component with reactive forms  
form : FormGroup;

and add 
in the .ts file 
```
private buildForm() {
        this.form = this.formBuilder.group({
            'checkBox':[null, [Validators.required]],
            'radioButtonGroup':[null, [Validators.required]],
        });
    }
```

in the .html template 
```

<ion-item>
        <ion-label position="stacked">Check box</ion-label>
        <ion-checkbox position="fixed" formControlName="checkBox"></ion-checkbox>
        <ion-note slot="error"> Please select</ion-note>
    </ion-item>

    <ion-list >
        <ion-radio-group formControlName="radioButtonGroup" >
            <ion-list-header>
                <ion-label>Radio button Group</ion-label>
            </ion-list-header>

            <ion-item>
                <ion-label>Selection1</ion-label>
                <ion-radio slot="start" value="Selection1"></ion-radio>
            </ion-item>
            <ion-item>
                <ion-label>Selection3</ion-label>
                <ion-radio slot="start" value="Selection3"></ion-radio>
            </ion-item>
        </ion-radio-group>
        <ion-note slot="error"> Please select</ion-note>
    </ion-list>

```

### Ionic Info

info
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 6.19.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.19.1
   npm    : 8.9.0
   OS     : macOS Monterey

  ─────────────────────────────────────────────────

     Ionic CLI update available: 6.19.0 → 6.19.1
          Run npm i -g @ionic/cli to update

  ─────────────────────────────────────────────────

**Comment by dimitarmar** [comment]
Hello , so here its the link to github project code 
https://github.com/dimitarmar/photo-gallery/tree/main/src/app/home 

So as you could see there for the inputText field slot="error" is working corretly , means showing in red when there the field is empty , so means detect the error status and shows the error message in ion-note. But this is not happen for the other two fields radioButtonGroup and checkBox . 

Also the full projects is at https://github.com/dimitarmar/photo-gallery

**Comment by liamdebeasi** [comment]
Thanks! The helper and error text slots were only intended to be used with text inputs. However, our documentation does not make this clear.

**Comment by Saqib92** [comment]
> Thanks! The helper and error text slots were only intended to be used with text inputs. However, our documentation does not make this clear. The API is also misleading since it is available on `ion-item`, implying that it can be used with any form control in `ion-item`.

adding `display: block` on `ion-note` makes it work with `ion-checkbox` inside `ion-item`.

**Comment by drubarth** [comment]
Any recommendations from the Ionic team or others on best practices to display errors on non-input form controls?  In particular, looking for good ideas for errors related to a child form group (e.g. - we have an account edit page with a child form group containing the country code drop-down and phone number, which need to be validated together).  Any ideas are appreciated.

**Comment by liamdebeasi** [comment]
Hi everyone,

In Ionic 7 we are shipping new helper/error text APIs on `ion-input` and `ion-textarea`. This should help clarify that these features are only meant for text inputs. Additionally, we are deprecating the helper/error slots on `ion-item`. We have a migration guide available here: https://ionicframework.com/docs/v7/api/input#migrating-from-legacy-input-syntax. Developers will also receive deprecation warnings in their console when upgrading to Ionic 7.

The work required to resolve this has been completed, so I am going to close this issue. Let me know if there are any questions.
