### ISSUE TITLE
bug: The order of the alert buttons on android is reversed

### ISSUE THREAD

**Issue by yudateNoriyuki** [ionic-team/ionic-framework#25348]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [X] v5.x
- [X] v6.x
- [x] Nightly

### Current Behavior

The order of the alert buttons on android is reversed from iOS.

# RESULT
## Android
![スクリーンショット 2022-05-25 16 41 48](https://user-images.githubusercontent.com/50348650/170208682-a9b65b43-0c56-4a86-b55e-b8593f9b6908.png)

## iOS
![image](https://user-images.githubusercontent.com/50348650/170208562-cd0ce797-0501-4c94-b25a-ba51565faa5f.png)

# CAUSE
It's because the value of flex-wrap is different between iOS and android

## Android
` flex-wrap:wrap-reverse`
https://github.com/ionic-team/ionic-framework/blob/a26275378f10835343ad8a6cdea50303e6c10a14/core/src/components/alert/alert.md.vars.scss#L122

## iOS
`flex-wrap: wrap`
https://github.com/ionic-team/ionic-framework/blob/a26275378f10835343ad8a6cdea50303e6c10a14/core/src/components/alert/alert.ios.vars.scss#L128

### Expected Behavior

Should be in the same order as iOS.

Why is android the opposite?
Even with the material guidelines, the cancel button is at the bottom, just like iOS.
https://material.io/components/dialogs#anatomy

### Steps to Reproduce

1. Make the alert button name longer so that flex-wrap will work
2. Set `order:1` for the disagree button

### Ionic Info

have nothing to do with

**Comment by sean-perkins** [comment]
Thanks for reporting this issue. I am confused why you are manually setting the `order` value on the button?

Comparing with the MD spec, this is the display for longer buttons:
<img src="https://lh3.googleusercontent.com/S5PCCw_o0NFyj7o7JOcigomy4Avy8X_-wa2pMVv0bBAPok5-_lQO40uETzqbKI6n_vdAoXdKTqSMOebpJZ9H_3gLiYv8Zx4jzqnoIA=w1064-v0" />

and this is the display within Ionic, without modification: 

<img width="370" alt="Screen Shot 2022-05-25 at 9 37 27 AM" src="https://user-images.githubusercontent.com/13732623/170275616-98c90528-987b-4930-bc6c-2d9dd2de4039.png">

In both examples, the confirmation button is on top and the cancel button is on the bottom. This behavior is consistent, regardless of which button is flex wrapping.

Can you help me understand where the issue is? Thanks!

**Comment by yudateNoriyuki** [comment]
@sean-perkins 
Thank you for contacting me.

> I am confused why you are manually setting the order value on the button?

### 1
First of all, I tried it on iOS.
![スクリーンショット 2022-05-26 10 26 58](https://user-images.githubusercontent.com/50348650/170396680-103eaf76-c1b2-454f-b8c8-0ae0f0ddce45.png)

### 2
In iOS, the cancel button was on top.  So I set the order value so that the cancel button is at the bottom.
`order: 1`
![スクリーンショット 2022-05-26 10 26 58](https://user-images.githubusercontent.com/50348650/170396814-a088edd6-47ff-4628-91ef-aa8e9df8a738.png)

### 3
But when I did this on android, the order was reversed.
![スクリーンショット 2022-05-26 10 27 50](https://user-images.githubusercontent.com/50348650/170396882-bd5efbe0-1327-4cf1-ab74-a3b8f5ec2813.png)

The reason for the reverse is that the flex-wrap value is different between IOS and android.

Thanks!

**Comment by sean-perkins** [comment]
@yudateNoriyuki the button order is defined by the order of the array that you supply to the `buttons` property. You should not be modifying this order with CSS. 

```ts
const alert = await alertController.create({
  ...
  buttons: [
    'Agree',
    'Disagree'
  ]
});
```

The example on the docs has them in the inverse order: https://github.com/ionic-team/ionic-docs/blob/main/static/demos/api/alert/index.html#L42.

I've confirmed if you supply the buttons in the desired order, no style customization is required.
