### ISSUE TITLE
bug: IonInput fails to resize window properly when keyboard is opened iOS & React 

### ISSUE THREAD

**Issue by TylerAHolden** [ionic-team/ionic-framework#25354]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When clicking on an IonInput, the window size is not resized to account for the keyboard height. This results in the ability to scroll 2 different view panes (the IonContent scroll view AND the entire IonApp).

It kind of appears like --keyboard-offset is never being updated? I tried putting the IonInput in different components (IonItem, inside scroll view, outside ion content, ionfooter etc) and I can't seem to figure out the preferred way to make the input work. 

**_What I'm really try to do is attach the input to the keyboard for chat._**

https://user-images.githubusercontent.com/38476278/170355568-90ca6e49-bfac-49af-915f-e66aa2b64a15.MP4

### Expected Behavior

I would expect the view height to shrink to account for the keyboard or at least prevent the entire app from being scrolled.

### Steps to Reproduce

Click IonInput, scroll on header to see entire app scrolling

### Code Reproduction URL

https://github.com/TylerAHolden/ionic-input-test/blob/master/src/pages/Tab1.tsx

### Ionic Info

Ionic:

   Ionic CLI       : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.6

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.10.0 (/usr/local/Cellar/node/16.10.0/bin/node)
   npm    : 7.24.1
   OS     : macOS Monterey

### Additional Information

https://github.com/ionic-team/ionic-framework/issues/23179 possible duplicate
https://github.com/ionic-team/ionic-framework/issues/18532 underlying issue maybe? But it's still open with no obvious solution that I found since that issue talks about removing the resize - I DO want resize though, I think... I want the input to be "attached" to the keyboard for chat.

**Comment by liamdebeasi** [comment]
Thanks for the issue. On iOS, the keyboard is designed to overlay your entire app -- the window never resizes. This is true of all webpages in iOS Safari, not just Ionic apps.

In a Capacitor app, the webview can resize based on your Keyboard plugins config settings.

There is a utility called "scroll padding" which should add padding to the bottom of `ion-content` so that we can scroll the input above the keyboard. However, that is not working as you noted with your reference to https://github.com/ionic-team/ionic-framework/issues/18532.

Resolving #18532 should resolve the issue here. Does this clarify things?

**Comment by liamdebeasi** [comment]
For your exact use case (attaching the input to the keyboard), I recommend looking at [Ionic's Keyboard Lifecycle Events](https://ionicframework.com/docs/developing/keyboard#keyboard-lifecycle-events). These were designed to tell you the height of the keyboard when not in a Cordova/Capacitor environment.

I wrote a blog a couple years ago that shows you how to use them: https://ionicframework.com/blog/keyboard-improvements-for-ionic-apps/

**Comment by TylerAHolden** [comment]
@liamdebeasi thanks for the blog link - ill take a look! Some CSS trickery to get the input attached to the keyboard seems reasonable but is #18532 related to the issue where the entire app can be scrolled? I guess what I'm thinking is that, you would want the IonHeader to remain at the very top and not ever be scrolled above the view, right? Am I missing something there? Is there a way to force the IonHeader to be "fixed" at the top?

**Comment by TylerAHolden** [comment]
I also dont understand the webview mechanics underneath because it appears that even if everything was set to a fixed height less than the height of the screen, the entire <html /> content can get scrolled if the keyboard is up - if that makes sense

**Comment by liamdebeasi** [comment]
> @liamdebeasi thanks for the blog link - ill take a look! Some CSS trickery to get the input attached to the keyboard seems reasonable but is #18532 related to the issue where the entire app can be scrolled? I guess what I'm thinking is that, you would want the IonHeader to remain at the very top and not ever be scrolled above the view, right? Am I missing something there? Is there a way to force the IonHeader to be "fixed" at the top?

Yeah the entire app should not be scrollable, but due to #18532 this issue is happening.

> I also dont understand the webview mechanics underneath because it appears that even if everything was set to a fixed height less than the height of the screen, the entire <html /> content can get scrolled if the keyboard is up - if that makes sense

I would check out https://capacitorjs.com/docs/apis/keyboard#keyboardresize if you are using Capacitor. There are several options for resizing the webview. It sounds like the default value may not be appropriate for your use case.
