### ISSUE TITLE
bug: ion-modal `swipeToClose` no longer has any effect when `mode=ios` without `presentingElement`

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#25362]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [X] Nightly

### Current Behavior

Using `swipeToClose` on modals no longer works unless using the new `card` style modal. We had previously used this function even on normal modals to allow users to swipe and dismiss.

### Expected Behavior

`swipeToClose` should stay available without `presentingElement`. (Note, I see this is deprecated, but the functionality has been removed in a breaking way and it would be nice if this could stay available (not just for the new card-style modals.)

### Steps to Reproduce

Create a modal that does not have a `presentingElement` (e.g. just a plain modal, not a card, not a bottom-sheet).

```
        this.modal = await this.modalCtrl.create({
          component: MyModalComponent,
          swipeToClose: true,
          showBackdrop: true,
          animated: true,
          mode: 'ios',
        });
```

The modal will display but not be swipable. This previously worked in Ionic 6.1.1 but is now broken in 6.1.7.

Working 6.1.1:
https://user-images.githubusercontent.com/362329/170589579-22176427-8a7c-4a2a-abb6-675f3f7765c8.mov

Broken 6.1.7:
https://user-images.githubusercontent.com/362329/170589426-a23668cc-6a28-4361-b23e-da29bb0dfcfd.mov

### Ionic Info

mshark:topdecked-unified lincoln$ ionic info
[WARN] Error loading @ionic/angular package.json: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package' is
       not defined by "exports" in
       /Users/lincoln/projects/maritlabs/topdecked-unified/node_modules/@ionic/angular/package.json

Ionic:

   Ionic CLI                     : 6.19.0 (/Users/lincoln/.nvm/versions/node/v14.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 14.0.0-rc.2
   @angular-devkit/schematics    : 14.0.0-rc.2
   @angular/cli                  : 14.0.0-rc.2
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v14.19.0 (/Users/lincoln/.nvm/versions/node/v14.19.0/bin/node)
   npm    : 6.14.16
   OS     : macOS Monterey

  ─────────────────────────────────────────────────

     Ionic CLI update available: 6.19.0 → 6.19.1
          Run npm i -g @ionic/cli to update

  ─────────────────────────────────────────────────

mshark:topdecked-unified lincoln$

**Comment by lincolnthree** [comment]
I believe this may have introduced the breaking change: https://github.com/ionic-team/ionic-framework/pull/25185

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo? This is working fine on my end.

**Comment by lincolnthree** [comment]
Sure @liamdebeasi - Here you go: https://github.com/lincolnthree/ionic-issue-25362-modal-swipe-to-close

**Comment by lincolnthree** [comment]
Ok @liamdebeasi - I have an update. It looks like the breaking change is that a wrapper element with `class="ion-content-scroll-host"` is now required for `swipeToClose` to locate a modal element on which to bind gestures. Any reason this doesn't just fall back to the `<ion-modal>` element itself like I believe it used to? (I'm sure there's a good reason, but I'm on the outside looking in.) 

E.g. I'm this appears to be new requirement / pre-req? Or at least newly enforced?

**Comment by liamdebeasi** [comment]
If you'd like all modals to be swipeable, you could certainly create a feature request and we'd be happy to review.

However, our main concern with allowing "regular" modals to be swipeable is that there is no visual cue that the modal can be swiped, so it may be unexpected to some. The sheet modal has the handle, and the card modal has the underlying content "peeking out" from behind the modal, which makes those good candidates for the swipe gesture.

**Comment by lincolnthree** [comment]
@liamdebeasi Bummer. Sorry to see this functionality go away. It's something we've relied on heavily. The card-style modal doesn't seem to work for us in all situations since we require transparency on some modals. Regarding UX of gestures, our testing has shown that when modals slide up from the bottom, that's enough of a cue for users to try to swipe it down again. Particularly when combined with transparency.

I'll certainly open a feature request, here you go. I can only do my best to emphasize how important of a feature this is for us :)

https://github.com/ionic-team/ionic-framework/issues/25371

Example of why card-modal won't work for us, particularly without `showBackdrop`:
https://user-images.githubusercontent.com/362329/170766530-0ed91687-a563-4e6f-8eb4-f1ef0584c7c7.mov

If there's another option I'm missing here that would allow us to continue using `ModalController` for our use case once these features go through, I'd of course love to hear it!

**Comment by liamdebeasi** [comment]
Have you tried making that a sheet modal instead? Breakpoints would be `[0, 1]` and you could turn off the handle with `handle="false"`.

**Comment by lincolnthree** [comment]
@liamdebeasi You really got my hopes up with that one! I hadn't considered it, but alas... it won't work without supporting `showBackdrop: true` on sheet-style (or card-style) modals.

I think sheet-style is definitely preferred here if I had to pick one, since card-style causes weird layout breaking effects at the bottom of the screen when modals are transparent.

https://github.com/ionic-team/ionic-framework/issues/25372

**Comment by lincolnthree** [comment]
PS. These new modals are really fantastic overall. I'm just thrilled with what you've been able to do with these components.

**Comment by liamdebeasi** [comment]
Have you tried `backdropBreakpoint`? It's a feature exclusive to the sheet modal that lets you determine the point at which the backdrop becomes active: https://ionicframework.com/docs/api/modal#backdropbreakpoint

`backdropBreakpoint="0"` means that the backdrop will become active the moment the card opens.
`backdropBreakpoint="1"` means that the backdrop will never become active.

It was intended for views where you have a modal on top of other content that should still be selected (think Apple Maps/Google Maps with the sheet overlaying the map view).

**Comment by liamdebeasi** [comment]
If you need more control over the backdrop, you can also use the `--backdrop-opacity` CSS Variable or the `backdrop` CSS Shadow Part if you just want to access the entire `ion-backdrop`.

**Comment by lincolnthree** [comment]
@liamdebeasi Actually, backdrop breakpoint seems to have done the trick on that, but I just realized for some reason it looks like the sheet modal is not swipe-able unless `swipeToClose` is true:


https://user-images.githubusercontent.com/362329/170769979-f251d97a-8352-476d-b347-b4a7b05698e8.mov

**Comment by liamdebeasi** [comment]
`backdropBreakpoint` is a feature exclusive to the sheet modal, so I would not expect it to work with the card modal.

**Comment by lincolnthree** [comment]
> `backdropBreakpoint` is a feature exclusive to the sheet modal, so I would not expect it to work with the card modal.

Right, just had to say it out loud :)

**Comment by liamdebeasi** [comment]
`swipeToClose` should have no impact on the sheet modal as per https://ionicframework.com/docs/api/modal#sheet-modal. Do you have a repo I can look at? Also make sure you are using `ion-content` in the sheet modal too.

**Comment by lincolnthree** [comment]
I think I may have forgotten 'initialBreakpoint', hang tight.

**Comment by lincolnthree** [comment]
OKAY. I need to do a bit more testing now, but I believe your initial suggestion of "use sheet-style modal at [0,1] with no handle" is the magic sauce. 

Apologies for the subsequent confusion, I missed the fact that `initialBreakpoint` is required (maybe just pick one by default and issue a warning? or perhaps issue a warning that the modal is mis-configured?) There are a lot of options that do or do not do anything if the modal is configured in different ways. A bit more feedback here might help at the development-time stage.

This seems to do the magic trick:
```
          this.modal = await this.modalCtrl.create({
            animated: true,
            backdropDismiss: true,
            backdropBreakpoint: 0,
            breakpoints: [0, 1],
            initialBreakpoint: 1,
            handle: false,
            showBackdrop: true,
            canDismiss: true,
            component: TdModalCardImageViewer,
            cssClass: 'modal-large modal-transparent modal-force-fg',
            mode: 'ios'
          });
```

Phew.

**Comment by lincolnthree** [comment]
Thank you for holding my hand through this one. Haha.

**Comment by lincolnthree** [comment]
That said, it looks like momentum/velocity is not being taken into account when swiping sheet-style modals away:

https://user-images.githubusercontent.com/362329/170772866-a4b92816-32b9-49a0-8a19-a05b71a62526.mov

Want an issue for that?

**Comment by lincolnthree** [comment]
@liamdebeasi It also appears that the breakpoint of `1` is not enough to get the sheet-modal all the way to the top of the viewport, even with the handle disabled. Any ideas around that?:

https://user-images.githubusercontent.com/362329/170774431-bf65014e-3fdf-41b1-8c8c-f30d3f03b917.mov

**Comment by lincolnthree** [comment]
Velocity/momentum not working: https://github.com/ionic-team/ionic-framework/issues/25373
Can't get to 100% of viewport height: https://github.com/ionic-team/ionic-framework/issues/25374

**Comment by liamdebeasi** [comment]
#25374 is by design: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/modal/modal.scss#L137 You can override this by setting `--height: 100%`.

#25373 is already being tracked in https://github.com/ionic-team/ionic-framework/issues/24296.

**Comment by lincolnthree** [comment]
Thanks, Liam. That's the conclusion I reached as well for height. 

As for the other - sorry, it didn't come up in my search, but it definitely is the same thing.

**Comment by liamdebeasi** [comment]
No problem. Is the original issue resolved, or are there lingering concerns?

**Comment by lincolnthree** [comment]
I think the last issue preventing this as a solution is #25373 / #24296

Technically I guess this will work, but without momentum I think users will be confused as a 100% breakpoint swipe is quite a bit longer than the current behavior.

**Comment by liamdebeasi** [comment]
Perhaps we could track this issue in #24296 just to keep the discussion centralized? I posted a dev build there that should resolve the issue.

**Comment by lincolnthree** [comment]
Sounds good to me :) Closing this. Much appreciated for everything as always, Liam.
