### ISSUE TITLE
bug: sheet-style modals with `breakpoint: 1, handle: false` do not take up 100% of viewport.

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#25374]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [X] Nightly

### Current Behavior

Sheet-style modals cannot be forced to take 100% of the viewport, even when the final breakpoint is set to 1. Notice the gap between the top of the modal and the top of the viewport:

https://user-images.githubusercontent.com/362329/170776122-1f4f823f-43d7-433f-9660-7ceb293a47cf.mov

### Expected Behavior

A breakpoint of 1 should take 100% of the viewport.

### Steps to Reproduce

Render a sheet style modal with breakpoint of 1. It won't get to the top of the viewport.

```
        this.modal = await this.modalCtrl.create({
          component: MyModalComponent,
          canDismiss: true,
          breakpoints: [0, 1],
          initialBreakpoint: 1,
          handle: false,
        });
```

### Code Reproduction URL

https://github.com/lincolnthree/ionic-issue-25362-modal-swipe-to-close

### Ionic Info

mshark:ionic-issue-modal-swipe-to-close lincoln$ ionic info

Ionic:

   Ionic CLI                     : 6.19.1 (/Users/lincoln/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.7
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.0 (/Users/lincoln/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

mshark:ionic-issue-modal-swipe-to-close lincoln$

**Comment by lincolnthree** [comment]
This seems to be due to the following style on `ion-modal`:

```
:host(.modal-sheet) {
    --height: calc(100% - (var(--ion-safe-area-top) + 10px));
}
```

**Comment by lincolnthree** [comment]
Note for others who find this. This can be worked around by adding a custom style:

```
    &.modal-full-height {
      --min-height: 100%;
    }
```

And applying it when creating the modal:

```
  this.modal = await this.modalCtrl.create({
          component: MyModalComponent,
          canDismiss: true,
          breakpoints: [0, 1],
          initialBreakpoint: 1,
          handle: false,
          cssClass: 'modal-full-height',
        });
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. As we discussed in our other thread, this is by design: https://github.com/ionic-team/ionic-framework/issues/25362#issuecomment-1139972438

You can use `--height: 100%` to override this behavior.
