### ISSUE TITLE
bug: `ion-datetime` with presentation `time` does not emit ionChange when initial value is not set

### ISSUE THREAD

**Issue by langy** [ionic-team/ionic-framework#25375]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Changing or attempting to set the time in an ion-datetime component doesn't fire a change event so it is unusable.

### Expected Behavior

After changing or setting a time using the ion-datetime component, it should fire a change event (like it used to do).

### Steps to Reproduce

- Add an ion-datetime component with the `presentation="date-time"` or `presentation="time"` attribute
- Choose the 'Time' button
- Select a time
- Note that the time does not update or get set (no change event)

### Code Reproduction URL

https://stackblitz.com/edit/angular-1ez814

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.7

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.1.0
   OS     : macOS Big Sur

### Additional Information

Reported by another user in the Ionic Discord server on 28th May 2022, https://discordapp.com/channels/520266681499779082/938816942750449704/979783252413935616

I found the above message when searching Discord for 'datetime' to see if anyone else was having these issues. I hadn't changed any of my own code that uses this component and already hooked into the change event, so was wondering why it no longer worked. I think it became broken with a recent core update.

**Comment by andreaslarssen** [comment]
Like this #25365?

**Comment by langy** [comment]
> Like this #25365?

Yes like that, except you reference the presentation="year" in your example, so perhaps it's only for the scrolling parts of this component? I noticed that if it's a full calendar, changing the date using the buttons for the days does actually set the date correctly. Strange how it works perfectly for some versions of the component but not others!

**Comment by andreaslarssen** [comment]
You sure it's not just when the initial value is null/undefined?

**Comment by langy** [comment]
> You sure it's not just when the initial value is null/undefined?

You're right. If I set it to '00:00' first up, it works. Not ideal as I never used to do this, but it's a temporary solution. Thanks for the heads up!

**Comment by MaximSedov** [comment]
> > You sure it's not just when the initial value is null/undefined?
> 
> You're right. If I set it to '00:00' first up, it works. Not ideal as I never used to do this, but it's a temporary solution. Thanks for the heads up!

Please, tell me, how did you set the time to '00:00'?

**Comment by langy** [comment]
> > > You sure it's not just when the initial value is null/undefined?
> > 
> > 
> > You're right. If I set it to '00:00' first up, it works. Not ideal as I never used to do this, but it's a temporary solution. Thanks for the heads up!
> 
> Please, tell me, how did you set the time to '00:00'?
If you're using Ionic React and Moment.js (I know, it's old but it works for me), then this will mimic the default behaviour before this bug crept in:
```<IonDatetime
  presentation="time"
  showDefaultButtons={true}
  value={moment().format('HH:mm')} />```

**Comment by pauloanalista** [comment]
Bug only occurs if you do not inform the
showDefaultButtons={true}

**Comment by andreaslarssen** [comment]
@pauloanalista No? At least not in the Angular package

**Comment by langy** [comment]
> Bug only occurs if you do not inform the showDefaultButtons={true}

Sorry but this doesn't affect the outcome for me. showDefaultButtons was always true and the bug still occurred.

**Comment by pauloanalista** [comment]
If you do not inform this property, it will not allow you to select the time correctly

showDefaultButtons={true}

that was my problem

**Comment by sean-perkins** [comment]
Thank you for reporting this issue, I have been able to reproduce here: https://stackblitz.com/edit/angular-1ez814

When `showDefaultButtons` is `false`, the `ion-datetime` should emit an `ionChange` event whenever the value is modified. When `showDefaultButtons` is `true`, the `ion-datetime` will only emit `ionChange` when the confirm button is selected.

**Comment by sean-perkins** [comment]
I have been able to identify that this behavior regressed in this commit: https://github.com/ionic-team/ionic-framework/pull/25338

Downgrading to 6.1.6 will avoid the problem in the interim.

**Comment by sean-perkins** [comment]
Can someone test with this dev-build: `6.1.8-dev.11654024993.1c2aa477` and let me know if the problem persists? Thanks!

**Comment by andreaslarssen** [comment]
> Thank you for reporting this issue, I have been able to reproduce here: https://stackblitz.com/edit/angular-1ez814
> 
> When `showDefaultButtons` is `false`, the `ion-datetime` should emit an `ionChange` event whenever the value is modified. When `showDefaultButtons` is `true`, the `ion-datetime` will only emit `ionChange` when the confirm button is selected.

@sean-perkins Was that the behavior in Ionic 5? Seems very strange to me that the presence of buttons should determine whether a change event fires or not.

**Comment by sean-perkins** [comment]
@andreaslarssen when a date picker is presented with buttons (usually "Cancel" and "Done"), and a user selects a date, you do not want to immediately emit a change event, as the user may select the cancel operation. Inversely, if the user doesn't use buttons, there is no cancel/undo like action, so we can safely emit a change event as the user interacts with the date picker. This is the lowest friction and most common implementation pattern for developers/applications. 

I would be curious of an use case where a user has a datetime with buttons, selects a date, and you would immediately want to respond to that change event, knowing the user can select cancel. 

The check for the calendar picker is necessary, as this bug applies to all the presentation modes that are not a calendar picker (`month`, `year`, `month-year` and `time`). As shown in your stackblitz, it applies to those presentation modes as well. It does not apply to calendar pickers, as the recent patch in 6.1.7, adjusts the behavior to emit `ionChange` when the user manually selects a calendar day. You can read more about that change in the original PR description referenced (#25338).

**Comment by andreaslarssen** [comment]
> @andreaslarssen when a date picker is presented with buttons (usually "Cancel" and "Done"), and a user selects a date, you do not want to immediately emit a change event, as the user may select the cancel operation. Inversely, if the user doesn't use buttons, there is no cancel/undo like action, so we can safely emit a change event as the user interacts with the date picker. This is the lowest friction and most common implementation pattern for developers/applications.
> 
> I would be curious of an use case where a user has a datetime with buttons, selects a date, and you would immediately want to respond to that change event, knowing the user can select cancel.

In my opinion, a change is a change, and confirm / cancel are something else. Instead of trying to make up a use case where listening to the change event when the buttons are present makes sense, I'm more fan of giving developers tools, and then let them decide how to use it. If they don't need an event firing every time there's a change, just don't listen to the event. 

Having different behavior based on the presumed use case of the developer only leads to more complex business logic, which in turns turns to more  complex code, which again turns to bugs like this. 

Anyways, that's all just design choices. 

> The check for the calendar picker is necessary, as this bug applies to all the presentation modes that are not a calendar picker (`month`, `year`, `month-year` and `time`). As shown in your stackblitz, it applies to those presentation modes as well (although without showing default buttons). It does not apply to calendar pickers, as the recent patch in 6.1.7, adjusts the behavior to emit `ionChange` when the user manually selects a calendar day. You can read more about that change in the original PR description referenced (#25338).

Forgive me if I'm slow, but it seems like you're saying that the bug doesn't apply to date presentation modes, but it applies to those as well, but it does not apply to them?

What I essentially want to figure out is if this bug is something else than #25365

**Comment by sean-perkins** [comment]
@andreaslarssen the resolution for this bug should address #25365. I locally re-created your Stackblitz and tested with the dev-build. When the user clicks "Done", the alert prompts for the change event. 

The decision to have different behaviors for the `ionChange` emission, is because the usage of `showDefaultButtons` is aligned with the modal presentation pattern of date time in Material Design's spec. When interacting with a modal overlay, you would not want the change event to be fired and modifying contents in the background. Luckily, if there is a specific use case that can be demonstrated that needs this behavior; you can implement your own buttons that do whatever behavior you would expect of "Cancel" and "Done", that is not emitting a change event. Ideally you should not be using `showDefaultButtons` in datetime UI that isn't a popover or a modal.

**Comment by andreaslarssen** [comment]
@sean-perkins Will you then tag issue https://github.com/ionic-team/ionic-framework/issues/25365 in the PR that fixes it?
