### ISSUE TITLE
bug: sheet-style modals do not take velocity/momentum into account when swiping between breakpoints

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#25373]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [X] Nightly

### Current Behavior

Particularly in the scenario when breakpoints have been set at `[0, 1]`, to allow swiping a sheet-style modal closed, momentum is not taken into account and the swipe gesture becomes difficult (as the user needs to swipe quite a distance to get the modal to close.

https://user-images.githubusercontent.com/362329/170775132-c0719a4c-5f63-4e95-b873-2204baa274ee.mov

### Expected Behavior

The sheet-modal should be 'flickable' so that users can dismiss sheets using velocity/momentum. This is how `swipeToClose` currently works:

https://user-images.githubusercontent.com/362329/170775328-8f36fbdf-ec6a-48eb-abfa-d28c68ae9dc3.mov

Quickly flicking a sheet modal down to breakpoint 0 should dismiss it.

### Steps to Reproduce

Create a sheet modal with breakpoints `[0,1]`, try to flick the modal down (see video above). It won't dismiss.

```
        this.modal = await this.modalCtrl.create({
          component: MyModalComponent,
          canDismiss: true,
          breakpoints: [0, 1],
          initialBreakpoint: 1,
          handle: false,
        });
```

### Code Reproduction URL

https://github.com/lincolnthree/ionic-issue-25362-modal-swipe-to-close

### Ionic Info

mshark:ionic-issue-modal-swipe-to-close lincoln$ ionic info

Ionic:

   Ionic CLI                     : 6.19.1 (/Users/lincoln/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.7
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.0 (/Users/lincoln/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

mshark:ionic-issue-modal-swipe-to-close lincoln$

**Comment by lincolnthree** [comment]
Related: https://github.com/ionic-team/ionic-framework/issues/24296

**Comment by liamdebeasi** [comment]
Closing in favor of https://github.com/ionic-team/ionic-framework/issues/24296. For anyone else who finds this issue, there is a dev build in the linked issue. Please give it a try and provide feedback on that thread.
