### ISSUE TITLE
bug: input number arrow

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#25390]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When trying to remove the arrow on number input from `ion-input` it does not change unless i use `input` directly. Below is the attachment.

<img width="599" alt="Screenshot 2022-06-02 at 9 05 25 PM" src="https://user-images.githubusercontent.com/61012396/171640322-6504367b-8a89-450d-96c5-ee1b8a12e71b.png">

### Expected Behavior

The arrow should not be visible once appropriate css has been applied

### Steps to Reproduce

1. `<ion-input type="number" inputmode="numeric" ></ion-input>`
2. CSS as below

```css
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}

input[type=number] {
    -moz-appearance:textfield;
}
```

### Ionic Info

```typescript
Ionic:

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.7
   @angular-devkit/build-angular : 13.3.7
   @angular-devkit/schematics    : 13.3.7
   @angular/cli                  : 13.3.7
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey
```

**Comment by liamdebeasi** [comment]
I recommend verifying that your CSS is getting applied correctly and to the proper element.

Here is a CodePen of the spinner being removed via CSS: https://codepen.io/liamdebeasi/pen/jOZKVWG This is the same code you provided in your original post.
