### ISSUE TITLE
bug: Date time doesnt work with ngmodel/formcontrol when presentation=time is used

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/ionic-framework#25397]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

  time: any 

  <ion-datetime presentation="time"   [(ngModel)]="time"     ></ion-datetime>  

{{ time }} time value never updates

### Expected Behavior

that the time value binds to ngmodel and outputs

### Steps to Reproduce

as above, when using presentation=time  it doesnt work with ngmodel, all other presentation options seem to work

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/xxxxx/.nvm/versions/node/v12.20.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.5.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   Android SDK Tools : 26.1.1 (/xxxxx/Library/Android/sdk)
   NodeJS            : v12.20.2 (/xxxxx/.nvm/versions/node/v12.20.2/bin/node)
   npm               : 6.14.11
   OS                : macOS Monterey
   Xcode             : Xcode 13.4 Build version 13F17a

  ─────────────────────────────────────────────────

     Ionic CLI update available: 6.19.0 → 6.19.1
          Run npm i -g @ionic/cli to update

  ─────────────────────────────────────────────────

**Comment by liamdebeasi** [comment]
Can you try this again with the latest nightly build? According to https://github.com/ionic-team/ionic-framework/releases/tag/v6.1.9-nightly.20220603 this should be fixed in a recent commit.

**Comment by liamdebeasi** [comment]
There is a separate feature request for this that we are interested in working on: https://github.com/ionic-team/ionic-framework/issues/23981

**Comment by jjacobs33589** [comment]
I was having this issue as well. Updating to 6.1.10 fixed it for me

**Comment by liamdebeasi** [comment]
Thanks! This issue was resolved with v6.1.9: https://github.com/ionic-team/ionic-framework/commit/4e6a60b6a42287e5091728aecb61f6097e131b83 Please update to the latest version of Ionic to receive a fix for this.
