### ISSUE TITLE
bug:  Collapsed Header Flashes Content @ionic/core

### ISSUE THREAD

**Issue by seanaguinaga** [ionic-team/ionic-framework#25399]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Content in the collapsed header flashes when changing pages when in iOS mode

### Expected Behavior

Content would not flash and would only show once the page is scrolled when in iOS mode

### Steps to Reproduce

npm install from repo

npm run dev

open iOS or iPad emulator view in a browser

navigate by clicking on a cat card between "/" and "/two"

see flash in header

### Code Reproduction URL

https://github.com/Round-Technologies/internal-ui-spike

### Ionic Info

Ionic:

   Ionic CLI : 6.19.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.14.2
   npm    : 8.5.0
   OS     : macOS Monterey

### Additional Information

https://internal-ui-spike.vercel.app/two

change pages in iOS mode

I have tried useHasMounted, but have not tried css to fix

any ideas?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This behavior is to be expected in an application setup such as yours. 

When using Ionic's routing solution, Ionic is able to wait for a page to be fully rendered before displaying it. As a result, this flicker does not happen. Your application does not make use of this, so none of the proper waits happen.

Is there a reason why you are not using `@ionic/react` with the routing setup here? That package was designed for React apps (even with Next). You may have more luck with that approach.

**Comment by liamdebeasi** [comment]
Yeah, you would need to use `@ionic/react-router` to properly fix the issue. There is definitely some opportunity for improvement on our end, but since we need JS to correctly set up the collapsable header there will likely always be a flicker if an app does not wait properly.
