### ISSUE TITLE
bug: radio-group doesn't show the checked radio

### ISSUE THREAD

**Issue by mariossavva** [ionic-team/ionic-framework#25407]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When changing the value on the radio group the radio doesn't show as checked. The class

:host(.radio-checked) .radio-inner {
    transform: scale3d(1, 1, 1);
}

does not get set on the checked radio item

### Expected Behavior

Show the checkbox as filled (checked)

### Steps to Reproduce

Add radio group with 2 radio items. One starts as checked but when the other is checked they both display as not checked

### Ionic Info

Ionic:
   Ionic CLI                     : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.5
   @angular-devkit/build-angular : 13.3.5
   @angular-devkit/schematics    : 13.3.5
   @angular/cli                  : 13.3.5
   @ionic/angular-toolkit        : 6.1.0

Capacitor:
   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
