### ISSUE TITLE
bug: ion-accordion rendering strange lines with border-radius

### ISSUE THREAD

**Issue by sander-spruit** [ionic-team/ionic-framework#25408]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using an ion-accordion-group with an ion-accordion, where a border-radius is used, the browser renders weird diagonal lines. 

### Expected Behavior

Border radius should be applied without gimmicky issues.

### Steps to Reproduce

Create an ion-accordion, inside an ion-accordion with a group inside. Apply the following styling, 

```
ion-accordion-group ion-accordion-group {
background-color: var(--white);
--border-width: 0;
padding: 0 15px;
box-shadow: 0px 1px 0px 1px rgb(11 23 57 / 8%);
border-radius:5px;
}

```
and an ion-accordion with the following styling
```
ion-accordion {
border-radius: 5px;
}
```

Result is the following
<img width="502" alt="Schermafbeelding 2022-06-05 222111" src="https://user-images.githubusercontent.com/54065344/172069035-1ca285c6-7eeb-434d-9c54-ec15b929b1f3.png">

### Ionic Info

Ionic:

   Ionic CLI                     : 6.13.1 (\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.3
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
