### ISSUE TITLE
bug: sheet modal backdrop animation is incorrect when backdropBreakpoint is 1

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#25402]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using a Sheet Style Modal with `backdropBreakpoint: 1` the backdrop is buggy when the modal snaps back:

<img src="https://user-images.githubusercontent.com/20899975/171913852-54c59c13-322c-4543-b904-c063852abb4c.gif" width="300">

### Expected Behavior

The backdrop should not be shown here of course

### Steps to Reproduce

See attached Repo. Just drag the sheet down and release it

### Code Reproduction URL

https://github.com/EinfachHans/ionic-sheet-modal-issue

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (/Users/hans/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.6.0

System:

   NodeJS : v16.14.2 (/Users/hans/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.6.0
   OS     : macOS Monterey

**Comment by sean-perkins** [comment]
Hello @EinfachHans can you describe the visual requirements of your app that caused you to use `[backdropBreakpoint]="1"` here?

It appears that you are wanting the background content to always be interact-able when the sheet modal is expanded. If this is the case, wouldn't you be using this with a combination of `[showBackdrop]="false"`?

Is the expectation that when using a value of `1`, the sheet modal behaves as if the backdrop is not visible?

**Comment by EinfachHans** [comment]
Hey @sean-perkins ,

yes that's right. Sheets are created very dynamically in our app and with the fact that in the guture vreakpointa may be reactive, I feel like this should work automatically.

**Comment by sean-perkins** [comment]
Thanks for the added detail! Can you test with this dev-build and let me know if the problem is resolved:
```
6.1.9-dev.11654617845.1b4d9725
```

Our calculation for the animation was evaluating to `NaN`, since `1 / 1 - backdropBreakpoint` becomes `Infinity`.

**Comment by EinfachHans** [comment]
@sean-perkins works 😊

**Comment by sean-perkins** [comment]
Updated dev-build: `6.1.10-dev.11654886605.11e4eab6`

Previous build had issues with transitions when using partial backdrop breakpoint values.
