### ISSUE TITLE
bug: vscode extension show error allDependencies[library].startsWith is not a function

### ISSUE THREAD

**Issue by mhamri** [ionic-team/ionic-framework#25406]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

not sure it's a good repo but couldn't find another repo for the vscode extension. 

when I install the ionic extension, I get this error 

```
TypeError: allDependencies[library].startsWith is not a function
	at processDependencies (c:\Users\user\.vscode\extensions\ionic.ionic-1.8.5\out\process-packages.js:383:38)
	at processPackages (c:\Users\user\.vscode\extensions\ionic.ionic-1.8.5\out\process-packages.js:80:22)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async load (c:\Users\user\.vscode\extensions\ionic.ionic-1.8.5\out\analyzer.js:113:12)
	at async reviewProject (c:\Users\user\.vscode\extensions\ionic.ionic-1.8.5\out\project.js:385:20)
	at async E.fetchChildrenNodes (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:19679)
	at async E.getChildren (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:15898)
```

this prevent the extension works at all at it stay in this state 
![image](https://user-images.githubusercontent.com/8991783/172017243-dffc4e28-740f-4f89-baca-d0001accceea.png)

### Expected Behavior

the vscode extension works as intended

### Steps to Reproduce

not sure what is the cause, I don't have a reproducible example but let me know if you need any information I gather from the repo

### Ionic Info

❯ ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\amrim\AppData\Roaming\nvm\v16.14.2\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\amrim\AppData\Roaming\nvm\v16.14.2\node_modules\@ionic\cli\lib\index.js
       - C:\Users\amrim\AppData\Roaming\nvm\v16.14.2\node_modules\@ionic\cli\index.js
       - C:\Users\amrim\AppData\Roaming\nvm\v16.14.2\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.19.1 (C:\Users\amrim\AppData\Roaming\nvm\v16.14.2\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.16
   @angular-devkit/build-angular : 13.3.3
   @angular-devkit/schematics    : 13.3.3
   @angular/cli                  : 13.3.3
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.0
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Hello @mhamri, you can report issues and feature requests with the VS code extension here: https://github.com/ionic-team/vscode-extension/issues

Since different teams manage these projects, I am going to close this issue, but encourage you to open the issue there. 

Thanks!
