### ISSUE TITLE
feat(refresher): toggle refresh programmatically

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#25405]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The ability to toggle `ion-refresher` programmatically.
Currently `ion-refresher` can only be toggled by pull-to-refresh

This is probably related to this feature request  #22558.

### Describe the Use Case

In native applications you can scroll to top on tab button press.
If the scrollheight of viewport is 0, tab button press will trigger the refresher instead of scrolling to top.
You can find this behaviour in Reddit or Facebook app.

### Describe Preferred Solution

extending `ion-refresher` by method `toggle()`

### Related Code

```typescript
  @ViewChild(IonTabs, { static: true }) private ionTabs: IonTabs;
  ...
  public ionViewDidEnter(): void {
    const tabs = document.querySelectorAll('ion-tab-button');
    tabs.forEach(tab => {
      tab.addEventListener('click', () => {
        const selectedTab = this.ionTabs.outlet.getActiveStackId();
        const tabPage = this.ionTabs.outlet.getRootView(selectedTab);
        const ionContent = tabPage.element.querySelector('ion-content');
        if(ionContent.scrollTop === 0) {
           const refresher = ionContent.querySelector('ion-refresher');
           if(refresher) {
              refresher.toggle();
           }
        }
        ionContent.scrollToTop(450);
      });
    });
  }
```

**Comment by EinfachHans** [comment]
@DwieDima duplicate of #16542 - i already created a pr some time ago: #21972 😊

**Comment by DwieDima** [comment]
@EinfachHans alright, I’ll close this issue 😊.
