### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by cumpstey** [ionic-team/ionic-framework#25419]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

In the ion-datetime component, tapping the left/right arrows to change month will sometimes (randomly, as far as I can tell) change two months as if the button has been tapped twice. You see a double transition - it's not single transition from, say, June to August, but July will appear for a moment.

### Expected Behavior

When the arrow is tapped, the view should change to the month before or after.

### Steps to Reproduce

Run the minimal reproduction app, url below, on an Android or iOS device. Tap on the timestamp to open the ion-datetime picker, and tap the left or right arrow. You may need to tap several times to see the double transition, as sometimes it'll work fine.

### Code Reproduction URL

https://github.com/cumpstey/demo.ion-datetime

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /Users/ncumpstey/.nvm/versions/node/v16.13.2/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/ncumpstey/.nvm/versions/node/v16.13.2/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/ncumpstey/.nvm/versions/node/v16.13.2/lib/node_modules/@ionic/cli/index.js
       - /Users/ncumpstey/.nvm/versions/node/v16.13.2/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.19.0 (/Users/ncumpstey/.nvm/versions/node/v16.13.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.13.2 (/Users/ncumpstey/.nvm/versions/node/v16.13.2/bin/node)
   npm    : 8.3.2
   OS     : macOS Monterey

### Additional Information

We've only ever seen this on a mobile device - it's always worked perfectly in a browser run from `ionic serve`. I've seen it myself on an Android Nokia 7.2; it's been reported to me on other Android and iOS devices.

See screen recording here: https://www.youtube.com/shorts/sOGIedZ71gE

**Comment by liamdebeasi** [comment]
Thanks for the issue. What browser version/webview version are you testing this on? I am testing this on Chrome 102 and cannot reproduce the issue.
