### ISSUE TITLE
bug: refresher, quickly scrolling after cancelling refresh causes duplicate refresh

### ISSUE THREAD

**Issue by milanharia** [ionic-team/ionic-framework#25418]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using an Ion Refresher on android, if you pull the refresher down partially (so it does not trigger the onIonRefresh event) and then scroll down quickly, the refresher animation triggers (but does not fire the refresh event) which causes the scroll to jank. 

### Expected Behavior

Scrolling down rapidly should not cause the refresher to appear.

### Steps to Reproduce

Take any ionic app page which has enough content so the page can scroll and add an `IonRefresher`. Swipe **down** on the page slightly so the refresher icon begins to enter the page (but do not trigger it). Swipe **up** rapidly to scroll the page down quickly and the refresher icon will enter the page and cause the scrolling to jank.

### Video Example

https://user-images.githubusercontent.com/76167627/172366889-3a36fa23-1e68-429f-aa8f-b771daccfc6f.mp4

### An example of the code:

```

function doRefresh(event: CustomEvent<RefresherEventDetail>) {
  console.log("Begin async operation");

  setTimeout(() => {
    console.log('Async operation has ended');
    event.detail.complete();
  }, 2000);
}

const Tab1: React.FC = () => {
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab 1</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Tab 1</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonRefresher slot="fixed" onIonRefresh={doRefresh}>
          <IonRefresherContent />
        </IonRefresher>
           {*/ ...Page Content */}
      </IonContent>
    </IonPage>
  );
};
```

### Code Reproduction URL

https://github.com/milanharia/ionic-android-refresher

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.8

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.7.0
   OS     : macOS Monterey

**Comment by milanharia** [comment]
I have created a repo which has this issue within it [here](https://github.com/milanharia/ionic-android-refresher). Make sure after pulling the refresher down slightly you scroll down quickly for the bug to occur.

https://user-images.githubusercontent.com/76167627/172831544-dcd0aef9-8232-475f-b26c-9eb515467bc9.mp4

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. The refresher has a guard built in to protect from the gesture activating when dragging up: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/refresher/refresher.tsx#L343

However, it requires that the overall progress of the gesture be `0` (I.e. not started). This is done to still allow for users to cancel the gesture by dragging up mid-gesture.

When you do not pull enough for the gesture to complete, the browser executes this section of the code: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/refresher/refresher.tsx#L379-L383

While we do wait for the animation to finish, we never reset the overall progress of the animation. As a result, the guard mentioned above never kicks in and another gesture begins. Setting `this.progress = 0;` in the `onStart` callback fixes the issue.

**Comment by milanharia** [comment]
I can confirm it is fixed in the dev build!
