### ISSUE TITLE
bug: ion-tabs change screen

### ISSUE THREAD

**Issue by KarimQaderi** [ionic-team/ionic-framework#25414]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

click tab 1 > Sub 1 Page > Sub 2 Page > tab 2

Show tab 1 which should show tab 2

https://user-images.githubusercontent.com/32425175/172234318-1ecbb340-9006-4c31-94c7-fceca1a723f9.mp4

### Expected Behavior

click tab 1 > Sub 1 Page > Sub 2 Page > tab 2

Show tab 2

### Steps to Reproduce

The code simple repo is [here](https://github.com/KarimQaderi/demo-bug-tabs), it's same as the origin tabs project.

### Code Reproduction URL

https://github.com/KarimQaderi/demo-bug-tabs

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /home/wins/.npm-global/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/wins/.npm-global/lib/node_modules/@ionic/cli/lib/index.js
       - /home/wins/.npm-global/lib/node_modules/@ionic/cli/index.js
       - /home/wins/.npm-global/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /home/wins/.npm-global/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/wins/.npm-global/lib/node_modules/@ionic/cli/lib/index.js
       - /home/wins/.npm-global/lib/node_modules/@ionic/cli/index.js
       - /home/wins/.npm-global/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.19.1 (/home/wins/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.1.8

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v14.17.2 (/usr/local/bin/node)
   npm    : 8.2.0
   OS     : Linux 5.13

**Comment by sean-perkins** [comment]
Hello @KarimQaderi can you explain why you are re-using the `TabsPage` component on a new route tree, for your `/sub/two` path?

This specific code:
```
{
    path: '/sub',
    component: TabsPage,
    children: [
      {
        path: 'two',
        component: () => import('@/views/Sub2Page.vue')
      },
    ]
  }
```

If you expect "Sub2Page" to display within a tab, it should be a child of that tab in the route definition here: https://github.com/KarimQaderi/demo-bug-tabs/blob/master/src/router/index.ts#L18-L29.

Or if you would like it to be a full-height page separate from the tab-bar UI, it should match the definition you've modeled for "Sub1Page": https://github.com/KarimQaderi/demo-bug-tabs/blob/master/src/router/index.ts#L32-L35

**Comment by KarimQaderi** [comment]
Thankful

I noticed something else

`<div @click="$router.push('/tabs/tab2')">Tab 2 Page</div>`

Put it on the `Sub2Page.vue` page

click tab 1> Sub 1 Page> Sub 2 Page> Tab 2 Page

It does not work again 

https://user-images.githubusercontent.com/32425175/172249352-c4eef969-a840-41c6-9fb1-85922b1b658b.mp4

**Comment by sean-perkins** [comment]
@KarimQaderi there should not be any navigation actions that route across tabs, see: https://ionicframework.com/docs/angular/navigation#switching-between-tabs for more information. 

The only time the user should be navigate from "Tab 1" to "Tab 2" is through manually selecting the tab button from the tab bar.

Based on your screen recordings, this appears to be an implementation issue, not an issue with Ionic's routing integration. Can you confirm?

Thanks!

**Comment by KarimQaderi** [comment]
Thank you, my problem is solved
