### ISSUE TITLE
ionic tabs project can't backstack correctly in android

### ISSUE THREAD

**Issue by lcy19** [ionic-team/ionic-framework#25410]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

After running tabs project on android, I click tab1 -> tab2 -> tab3, and then click back key, and page changed to tab3 -> tab2 -> tab1. 

### Expected Behavior

But the expected is that when l click back key, don't change to previous tab, and when I click twice back keys, app return to device home. I had read [Hardware Back Button](https://ionicframework.com/docs/developing/hardware-back-button), and I added it on `app.component.ts`, but it doesn't work. And googlging for this, I saw this [issue](https://github.com/ionic-team/starters/issues/1698), but there isn't useful ways.  

### Steps to Reproduce

The code simple repo is [here](https://github.com/lcy19/tabs-demo), it's same as the origin tabs project. Thx for any suggestions.

### Code Reproduction URL

https://github.com/lcy19/tabs-demohttps://github.com/lcy19/tabs-demo

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (C:\Users\lcy\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 9.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 3 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\lcy\AppData\Local\Android\Sdk)
   NodeJS            : v16.14.2 (D:\programs\nodejs\node.exe)
   npm               : 8.5.0
   OS                : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is your repo public? I cannot access it.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Just so I understand: After going from Tab 1 to Tab 2, you are expecting to **not** be brought back to Tab 1 when you press the hardware back button. Instead, you are expecting to remain on Tab 2. Did I understand you correctly?

**Comment by lcy19** [comment]
> Thanks for the issue. Just so I understand: After going from Tab 1 to Tab 2, you are expecting to **not** be brought back to Tab 1 when you press the hardware back button. Instead, you are expecting to remain on Tab 2. Did I understand you correctly?

yes, it is. And When I click back button twice, the software should quit.

**Comment by lcy19** [comment]
> 

sorry for typing error, the Code Reproduction URL is https://github.com/lcy19/tabs-demo

**Comment by lcy19** [comment]
Thanks for your advice! I'll try it.
