### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by xzetic05** [ionic-team/ionic-framework#25425]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When click on button to present an **ion-modal component** which contains **ion-datetime** inside the component html. There are some time specially when press/click the button faster and then it will throw error exception as shown below, and calendar component UI will not display.

![image](https://user-images.githubusercontent.com/92197694/172512281-85c105d4-25bd-452b-b3af-f59f9dcc16b3.png)
![image](https://user-images.githubusercontent.com/92197694/172512339-8d0eaa2d-4d4a-4e48-a057-cb8c309d5632.png)

****

### Expected Behavior

No error exception shown and calendar UI will display successfully when opening **ion-modal component** with **ion-datetime** inside the component html.

### Steps to Reproduce

- Create a button or ion-item that have click event which have this code:
  public async onPresentExpensesDetailDate(expenseDetailsField: ExpenseDetailsField): Promise<void> {
    if (expenseDetailsField && expenseDetailsField.key && expenseDetailsField.uiType === UIType.Date) {
      await this.modalService.presentFadeModal(ModalConstant.onPresentExpensesDetailDate(expenseDetailsField));
    }
  }

- Create a new modal component html that have ion-datetime inside like below:
ion-content class="expenses-detail-date-content" color="lightest" role="main" fullscreen="true">
  <ion-datetime class="expenses-detail-date-calendar" size="cover" presentation="date" [min]="getDateMin(expenseDetailsField.value)" [max]="getDateMax(expenseDetailsField.value)" [value]="expenseDetailsField.value | customDate:'YYYY-MM-DD'" (ionChange)="onChangeExpenseDetailsFieldValue($event)"></ion-datetime>
</ion-content

- Click the button or ion-item rapidly many times and there will be some time it will trigger error exception but most of time is working fine.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (C:\Users\christian.j.m.palcon\AppData\Roaming\nvm\v16.15.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.3.7
   @angular-devkit/schematics    : 13.3.7
   @angular/cli                  : 13.3.7
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.10.0
   OS     : Windows 10

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a separate issue and ensure the template is fully filled out. Thank you!
