### ISSUE TITLE
bug: Date Picker automatically changes months when date picker open 

### ISSUE THREAD

**Issue by ShubhamKhatri2** [ionic-team/ionic-framework#25426]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`<ion-datetime></ion-datetime>`

this tag is working fine in most of devices but in some specific devices are not supporting it well.
the problem is happening when this picker loads; It changes months automatically, for testing we have change month for stop the process, we selected different month and it's stop. but after that when we use **< >**  to change month it changes month automatically. its happing like ghost touch.
for more information you can see the video attached here with.

https://user-images.githubusercontent.com/104985658/172558863-72236a5f-604a-4744-9285-624b5000eef7.mp4

### Expected Behavior

on date picker load month should not switch automatically and also on clicking **< >**  for month change.

### Steps to Reproduce

Shown in video. However, cant be reproduced in a browser.
error occurs in specific devices like our device is... 
Android version: 7.1.1
device name: Sun Mi V2 
build number: 3.2.41
Sun Me OS version: 1.6.0

similarly not working on other devices with different configuration. 

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (C:\Users\Shubham Khatri\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 14.0.0 (C:\Users\Shubham Khatri\AppData\Roaming\npm\node_modules\@angular\cli)
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.0
   OS     : Windows 10

### Additional Information

almost similar issue has been closed by issuer but the problem is still in the specified version of ionic. #25007
https://github.com/ionic-team/ionic-framework/issues/25007#issue-1183046584

**Comment by alammanasia** [comment]
yes i also got the issue , ion-date picker  is not working properly in some devices like vivo and oppo phones with some specific configuration

**Comment by ShubhamKhatri2** [comment]
Is there any solution for it? because date picker is very important for any application

**Comment by liamdebeasi** [comment]
Thanks for the issue. What version of the Chrome webview are you running on the affected device?

You can find this by logging `window.navigator.userAgent` when inspecting the app in Chrome Dev tools.

**Comment by ShubhamKhatri2** [comment]
> window.navigator.userAgent

'Mozilla/5.0 (Linux; Android 7.1.1; V2 Build/N6F26Q; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.84 Mobile Safari/537.36'

**Comment by liamdebeasi** [comment]
Thanks! The Chrome webview you have is version 62, which is quite old (it was released in 2017). Are you able to update the webview in the Google Play Store?

**Comment by ShubhamKhatri2** [comment]
Thank you for your Solution,
your solution is working by updating the web view from play store as you said.
but what about that devices where we can't update web view. I am asking this because wee have some devices where  we are not able to update web view because of non availability of google play store.

please resolve this issue for older web view versions

**Comment by HealthyPizza** [comment]
`"Mozilla/5.0 (Linux; Android 8.0.0; Android SDK built for x86 Build/OSR1.180418.019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36"`

Same issue.

**Comment by liamdebeasi** [comment]
Thanks! This looks to be the same underlying issue as https://github.com/ionic-team/ionic-framework/issues/24980, so I am going to merge the two threads.
