### ISSUE TITLE
bug: md, outline select long label overflows outside of container

### ISSUE THREAD

**Issue by enrique-lozano** [ionic-team/ionic-framework#25449]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When you create an item with an ion-select multiple inside it, if there are many options selected, the displayed text overflows outside the item.

![image](https://user-images.githubusercontent.com/61509169/173087320-3e6d4e31-84b7-4a5f-abe1-3e7ebf967b97.png)

This does not happen when there are already fewer options selected (the text to display is shorter). This makes me think that it is not a problem with the select, but with the ion-item when it is in fill=outline mode and has a very long text to display.

![image](https://user-images.githubusercontent.com/61509169/173087708-6e32b940-4d1f-4180-a90e-1d68db8c8b97.png)

### Expected Behavior

The ion-item component should always look like in case 2, discussed above

### Steps to Reproduce

```
<ion-item fill="outline" >

    <ion-label>My select</ion-label>

    <ion-select [value]="['1','2','3','4','5']" multiple="true">
        <ion-select-option value="1">Lorem 1</ion-select-option>
        <ion-select-option value="2">Lorem 2</ion-select-option>
        <ion-select-option value="3">Lorem 3</ion-select-option>
        <ion-select-option value="4">Lorem 4</ion-select-option>
        <ion-select-option value="5">Lorem 5</ion-select-option>
    </ion-select>

</ion-item>
```

At startup all default options are checked, causing the component to fail. As soon as you uncheck a couple of options, the component is already displayed correctly

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (C:\Users\kikel\AppData\Roaming\npm\node_modules\@ionic\cli)  
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. I can reproduce this. We can fix this by setting `width: fit-content` on `ion-select` and removing the `overflow: visible` on the host `ion-item`. However, we need to be careful when removing `overflow: visible`. It appears to be a Material Design-specific style, but it may not be needed anymore.

**Comment by enriqueloz88** [comment]
Any news on this? @liamdebeasi

**Comment by EinfachHans** [comment]
@liamdebeasi Removing `overflow: visible` doesn't work in combination with a floating label:

![Bildschirm­foto 2022-11-01 um 18 06 07](https://user-images.githubusercontent.com/20899975/199293399-6daf33dd-e0ad-4be8-bd13-5374e1947a2a.png)

Wouldn't it work to set a `max-width: 100%` on `.item-inner` and `.input-wrapper`?:

![Bildschirm­foto 2022-11-01 um 18 07 45](https://user-images.githubusercontent.com/20899975/199293755-c703620f-867a-4146-a9cd-fda729507ef7.png)

**Comment by Joaovm3** [comment]
@EinfachHans can you help me how to set the max-width: 100% in the .item-inner and .input-wrapper properties of the ion-item?

The code below doesn't work for me
![image](https://user-images.githubusercontent.com/59749960/202460771-764df05d-2120-441d-9971-0d8dd18b4b2b.png)

**Comment by EinfachHans** [comment]
@Joaovm3 i guess you can't nest styles within a part selector. This is something ionic would need to adjust, or you can add these styles via javascript

**Comment by Joaovm3** [comment]
Sure @EinfachHans. I found a workaround for this bug:

Adding the width property with any value in pixels, the text reverts to behaving as it should.
![image](https://user-images.githubusercontent.com/59749960/202470053-11b4ae42-c7c5-4800-8b4b-319fbd572445.png)

![image](https://user-images.githubusercontent.com/59749960/202470167-381e2e60-7ab2-40f3-84c4-01ba385ae5c0.png)

However, how could I add this property manually using js?

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with ion-select. This issue is fixed when using that new syntax. We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new select syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
