### ISSUE TITLE
bug: View Child returns null for directive

### ISSUE THREAD

**Issue by swernimo** [ionic-team/ionic-framework#25457]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

ViewChild is always returning undefined when searching for a directive. I have created a custom directive that I want to use as an anchor to inject custom components at runtime, see [angular guide](https://angular.io/guide/dynamic-component-loader). When the page loads the ViewChild property on the page itself is always undefined.

### Expected Behavior

ViewChild should return the control(s) that match the supplied directive.

### Steps to Reproduce

- Open the Menu
- Tap on 'New Page'
- Check that value of this.oppMetric in newPage.page.ts's ngAfterViewInit function
- this.oppMetric is always undefined.

### Code Reproduction URL

https://github.com/swernimo/ionicDemo

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.9
   @angular-devkit/build-angular : 14.0.1
   @angular-devkit/schematics    : 14.0.1
   @angular/cli                  : 14.0.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v14.15.3 (/usr/local/bin/node)
   npm    : 8.0.0
   OS     : macOS Monterey

### Additional Information

I also cloned the stackblitz of a default angular app that does work, [github](https://github.com/swernimo/angularDemo). The github demo app is for latest ionic & angular, but I also have the same issue with an Ionic 5/Angular 10 app, below is the ionic info for that app.

Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.8.5
   @angular-devkit/build-angular : 0.1000.0
   @angular-devkit/schematics    : 10.0.0
   @angular/cli                  : 10.0.5
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   Capacitor CLI      : 2.4.9
   @capacitor/android : 2.4.9
   @capacitor/core    : 2.4.9
   @capacitor/ios     : 2.4.9

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : not installed globally

System:

   NodeJS : v14.15.3 (/usr/local/bin/node)
   npm    : 8.0.0
   OS     : macOS Monterey

**Comment by sean-perkins** [comment]
@swernimo this doesn't appear to really be an issue with Ionic.

Declarations on the `AppModule`, do not apply to lazy-loaded routes/components/modules. 

If you refactor you implementation so that the directive is encompassed in a module:
```ts
import { NgModule } from '@angular/core';
import { OppMetricDirective } from './opp-metric.directive';

@NgModule({
  declarations: [OppMetricDirective],
  exports: [OppMetricDirective]
})
export class OppMetricModule { }
```

& import that into your `new-page-module.ts` (and your `AppModule` if you want), your app functions as expected. 

Let me know if that helps.

Thanks!

**Comment by swernimo** [comment]
thanks, I'll give that a try.

**Comment by swernimo** [comment]
yes, that was the issue. thanks for your help. For anybody else that comes across this later, I updated my [repo](https://github.com/swernimo/ionicDemo) with the fix.
