### ISSUE TITLE
bug: Wrong error message when using `ion-modal`

### ISSUE THREAD

**Issue by maguirre-tribalyte** [ionic-team/ionic-framework#25454]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using Angular 12 and Ionic v6.1, and running the following code:
´´´
<ion-modal class="charts-datepicker" [isOpen]="isDatePickerOpen" [swipeToClose]="true">
        <ng-template>
            <ion-header>
                <ion-button>GO</ion-button>
                <ion-button>TODAY</ion-button>
                <ion-button>CANCEL</ion-button>

            </ion-header>
            <ion-content>
                <ion-datetime *ngIf="isDatePickerShown" class="charts-datepicker" [(ngModel)]="selectedDate">
                </ion-datetime>
            </ion-content>
        </ng-template>
    </ion-modal>
´´´

The following error occurs in the browser console:

![image](https://user-images.githubusercontent.com/100680845/173323943-0529c796-4476-4577-8732-1ab14cc93bd7.png)
 

### Expected Behavior

After tinkering with it for a while, I arrived to the conclusion that the only child of an `ion-modal` element must be an `ion-content` element. The error should be the other way around

### Steps to Reproduce

Put anything other than `ion-content` inside of an `ion-modal`

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 12.2.17
   @angular-devkit/schematics    : 12.2.17
   @angular/cli                  : 12.2.17
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   Android SDK Tools : 26.1.1 (/home/maguirre/Android/Sdk)
   NodeJS            : v16.15.1 (/home/maguirre/.nvm/versions/node/v16.15.1/bin/node)
   npm               : 7.5.6
   OS                : Linux 5.13

**Comment by amandaejohnston** [comment]
Thanks for the issue. `ion-modal` needs to be used inside `ion-content` when using `swipeToClose`. If you are getting this error despite having your modal inside an `ion-content`, could you post a Github repo reproducing the behavior?

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If the error is occurring on the latest version of Ionic without the modal being inside an `ion-content`, please create a new issue and ensure the template is fully filled out. Thank you!
