### ISSUE TITLE
bug: Error: Unknown argument: platform [ERROR] An error occurred while running subprocess ng.

### ISSUE THREAD

**Issue by emilkitua** [ionic-team/ionic-framework#25460]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

Whenever I am compiling an Ionic app for android devices I am getting an error:
`Error: Unknown argument: platform
[ERROR] An error occurred while running subprocess ng.`

![image](https://user-images.githubusercontent.com/10283136/173434832-301fe4db-5fc4-4a89-a9c3-193bd6cb1bec.png)

### Expected Behavior

I expected the app to build to the desired platform

### Steps to Reproduce

Current Ionic version is 5.4.16
Angular CLI version: 14.0.1
Node: 16.14.2

run `ionic cordova platform build android` 

### Ionic Info

Ionic:
Ionic CLI: 5.4.16 (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework               : @ionic/angular 6.1.9
@angular-devkit/build-angular : 14.0.1
@angular-devkit/schematics    : 14.0.1
@angular/cli                  : 14.0.1
@ionic/angular-toolkit        : 6.1.0
Cordova:
Cordova CLI       : 11.0.0
Cordova Platforms : android 10.1.2
Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 4 other plugins)
Utility:
cordova-res : 0.15.4
native-run  : 1.5.0
System:
Android SDK Tools : 26.1.1 (C:\Users\Lenovo\AppData\Local\Android\Sdk)
NodeJS            : v16.14.2 (C:\Program Files\nodejs\node.exe)
npm               : 8.5.0
OS                : Windows 10

**Comment by sean-perkins** [comment]
@emilkitua the Ionic Framework repository is for the iOS/MD UI components.

You can report an issue with the Ionic CLI here: https://github.com/ionic-team/ionic-cli

Thanks!

**Comment by emilkitua** [comment]
thank you
