### ISSUE TITLE
feat: aria-labelledby and other ARIA (Accessibility) related attribute

### ISSUE THREAD

**Issue by shivamssh** [ionic-team/ionic-framework#25506]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

If I am adding <ion-input> then ionic add internally aria-labelledby which we are not able to edit or remove and some it doesn't find its reference. Ionic has given ariaLabel and ariaHidden same way if we can such attributes that will be helpful.

### Describe the Use Case

For Accessibility purpose

### Describe Preferred Solution

Provide the way ariaLabel or ariaHidden is given

### Related Code

<ion-label [ariaLabel]="abc" [for]="abc">abc</ion-label>
<div>
 <ion-input id="abc"></ion-input>
</div>

### Additional Information

https://stackoverflow.com/questions/50708701/override-aria-label-of-ionic3-ion-icon/55264952?noredirect=1#comment128394170_55264952

https://equalizedigital.com/accessibility-checker/empty-missing-form-label/#2-what-is-a-form-label
https://github.com/ionic-team/ionic-framework/issues/21569#issuecomment-652448854

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify what the issue you are reporting is? A GitHub repo that we can look at would also be helpful.
