### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Yura13** [ionic-team/ionic-framework#25509]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When trying to type text in input field inside modal the next issue happens:
![image](https://user-images.githubusercontent.com/17030431/174823261-1f61aa5a-c135-4560-b102-57610d147962.png)

The issue appears on IOS 15.5. 
After closing the modal dialog and opening again the issue is gone.

### Expected Behavior

The focus should be inside the field and the gray background shouldn't be shifted.

### Steps to Reproduce

I use the next behavior to scroll to the focused field:
```
           window.addEventListener('keyboardDidShow', (event) => {
                if (document.activeElement) {
                    document.activeElement.scrollIntoView(false);
                }
            });
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.10
   @angular-devkit/build-angular : 13.3.2
   @angular-devkit/schematics    : 13.3.2
   @angular/cli                  : 13.3.2
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.5.2, (and 30 other plugins)

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.6.0) : 1.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/testuser/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v16.13.2 (/usr/local/bin/node)
   npm               : 8.1.2
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100

**Comment by Yura13** [comment]
Unfortunately,  I is only reproducing inside an installed IOS app on the first opening of modal with inputs.
After updating IOS on tablet from v.15.4 to v.15,5 this issue appears.
No such issue in desktop/mobile browser or android app.
I use next code to scroll to the field in app.component.ts:
```
            window.addEventListener('keyboardDidShow', (event) => {
                if (document.activeElement) {
                    document.activeElement.scrollIntoView(false);
                }
            });
```
In config.xml:
```
<preference name="KeyboardResize" value="false" />
```

**Comment by amandaejohnston** [comment]
Could you create a minimal reproduction app and post a link to the Github repo here? This will help with both reproducing the issue, and confirming the fix down the road.
