### ISSUE TITLE
bug: react 18, page hides on hot reload

### ISSUE THREAD

**Issue by philjones88** [ionic-team/ionic-framework#25507]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The page works fine but when you save a file and the react server reloads part of the UI the react router outlet (`IonRouterOutlet`) goes blank.

### Expected Behavior

The UI to be updated and not blank

### Steps to Reproduce

I put together this code sandbox.

Simply change say `hello` to `hello!` and save the file, the page goes blank and you see `UNMOUNTED` in the console but no `MOUNTED`

This also happens locally with the CRA dev server.

https://codesandbox.io/s/ionic-router-issue-test-ovee4z?file=/src/app.tsx

i.e. this is the state after a save:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/677167/174802355-cc7cd1f0-3ddf-4f8c-a270-bb516e4a4d8d.png">

You then have to physically refresh the browser page to get the UI to work again.

### Code Reproduction URL

https://codesandbox.io/s/ionic-router-issue-test-ovee4z?file=/src/app.tsx

### Ionic Info

Can't do this on a sandbox, but locally with the same issue:

```
➜  broadway git:(main) ✗ ionic info
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - /Users/philjones/.config/yarn/global/node_modules/@ionic/cli/lib/project/index.js
       - /Users/philjones/.config/yarn/global/node_modules/@ionic/cli/lib/index.js
       - /Users/philjones/.config/yarn/global/node_modules/@ionic/cli/index.js
       - /Users/philjones/.config/yarn/global/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.18.1 (/Users/philjones/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.10

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : 3.6.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.14.2 (/usr/local/Cellar/node@16/16.14.2/bin/node)
   npm    : 8.5.0
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks! This appears to be specific to React 18. Using React 17 does not reproduce this behavior.

**Comment by philjones88** [comment]
> Thanks! This appears to be specific to React 18. Using React 17 does not reproduce this behavior.

Yup. I know Ionic Router doesn't support v6 of `react-router` so I left those in the v5 range. I only upgraded `react` and `react-dom` to 18.x.x.

**Comment by philjones88** [comment]
If you disable StrictMode the issue seems to go away.

See: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by sean-perkins** [comment]
I've been able to narrow the responsible code to here: https://github.com/ionic-team/ionic-framework/blob/main/packages/react/src/routing/ViewLifeCycleManager.tsx#L47

**Comment by sean-perkins** [comment]
Hello @philjones88 can you test with this dev-build and let me know if you run into any issues?

```
6.2.1-dev.11659463817.1943a7f4
```

The fix is across both `@ionic/react` and `@ionic/react-router`, so you will need to install that version of the dev-build for both packages. 

Thanks!

**Comment by philjones88** [comment]
@sean-perkins many thanks, those versions seem to perfectly fix the issue. The blank page is gone!
