### ISSUE TITLE
bug: disable datetime haptics on android

### ISSUE THREAD

**Issue by NoxFly** [ionic-team/ionic-framework#25508]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Creating an `<ion-datetime>` for time is spamming vibrations when scrolling (on mobile).
This is dreadful.

I've read #23584, #16630, [forum#217901](https://forum.ionicframework.com/t/ion-datetime-vibrates-while-scrolling/217901), [forum#203783/13](https://forum.ionicframework.com/t/disable-ion-datetime-picker-scroll-vibration/203783/13).

None of these are offering a viable solution to the problem, or are too old whereof about an older version.

### Expected Behavior

Have (at least) an option to tell if vibrations are desired or not ?

### Steps to Reproduce

`<ion-datetime presentation="time"></ion-datetime>`

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.13
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.3
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.3
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.12.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Is this happening on iOS or Android?

**Comment by NoxFly** [comment]
I can't test for iOS for now, so I've only tested for Android.

**Comment by NoxFly** [comment]
I'm just scrolling over the numbers to select hour and minutes. Each time it passes to a next or previous slot, it's vibrating. So scrolling fast is vibrating a lot. The expected behavior would be that there's no vibration at all (or in an option though).

**Comment by thomasyu929** [comment]
> Thanks. The haptics are supposed to be there on iOS as that is what the native date picker component does. Can you please clarify what the expected behavior is on Android?

I have the same issue on Android. and also after time scroll and close it the month will jump to previous month.

**Comment by liamdebeasi** [comment]
I think it makes sense to disable the haptics for the wheel picker on Android for now.

**Comment by aparajita** [comment]
> The haptics are supposed to be there on iOS

No doubt haptics on iOS/iPhones are a lot more subtle. 😁

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26370, and a fix will be available in an upcoming major release of Ionic Framework.
