### ISSUE TITLE
bug(react): IonInput doesn't allow to use type="file"

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/ionic-framework#25500]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

In angular you can use `<ion-input type="file" ></ion-input>`, but on react you can't use `<IonInput type="file" />`.

### Expected Behavior

users should be able to use `<IonInput type="file" />` in react apps

### Steps to Reproduce

create an ionic react app and add this to any tsx file
`<IonInput type="file" />`
it will complain about file not being a valid type

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.1 (/Users/julionic/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.10

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.14.2 (/Users/julionic/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey

### Additional Information

There is an issue open on the docs repository, but I don't think the problem is on the docs since it works on Angular
https://github.com/ionic-team/ionic-docs/issues/814

**Comment by liamdebeasi** [comment]
We do make reference to the `'file'` type in other props such as `accept`: https://ionicframework.com/docs/api/input#accept

However, it looks like this property was added by mistake: https://github.com/ionic-team/ionic-framework/commit/fe99d1958bf806392200b4dae0277acf03eb044c

`ion-input` is meant for text input only and has never supported file inputs.

**Comment by jcesarmobile** [comment]
I created the app `ionic start inputfiletest tabs --type angular --capacitor`, I guess it doesn't use strict mode by default.
If it was added by mistake it should be removed and the props that make reference of it on next major version (since it would be breaking for people using it).

**Comment by liamdebeasi** [comment]
Yes, we plan on deprecating this. I will put up a PR that addresses this issue and close out https://github.com/ionic-team/ionic-docs/issues/814 when it is resolved.

Thanks!
