### ISSUE TITLE
bug: Ionic lifecycle method doesn't work in tests with Jest

### ISSUE THREAD

**Issue by GersonDantas** [ionic-team/ionic-framework#25533]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When I try to test a react component that uses the useIonViewWillEnter lifecycle method, the lifecycle method doesn't get executed.
I even tried mocking the method:
`jest.mock('@ionic/react', () => ({ ...jest.requireActual('@ionic/react'), useIonViewWillEnter: async (componentCallback: Function) => { await componentCallback(); }, }));`
I can see the state change in the executed component but not in the test

### Expected Behavior

Ionic lifecycle method should be executed when jest renders the component.

### Steps to Reproduce

1. Create any method that uses the useIonViewWillEnter Ionic Lifecycle method(A modal for example)
2. Trigger a state change within the lifecycle method
3. test to see if the change has happened

### Code Reproduction URL

https://github.com/GersonDantas/portal-suri/blob/master/src/__tests__/presentation/page/login/forgot-password-modal.spec.tsx

### Ionic Info

[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc.json — 6 files
[STARTED] *.{ts,tsx} — 5 files
[STARTED] eslint 'src/**' --fix
[SUCCESS] eslint 'src/**' --fix
[STARTED] npm run test:staged
[SUCCESS] npm run test:staged
[SUCCESS] *.{ts,tsx} — 5 files
[SUCCESS] .lintstagedrc.json — 6 files
[SUCCESS] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SUCCESS] Applying modifications from tasks...
[STARTED] Cleaning up temporary files...
[SUCCESS] Cleaning up temporary files...
[master 8c12a83] fix: resolution bug from ForgotModalPassword initialization
 6 files changed, 22 insertions(+), 11 deletions(-)
❯ ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /home/gordim/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/gordim/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/lib/index.js
       - /home/gordim/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/index.js
       - /home/gordim/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /home/gordim/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/gordim/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/lib/index.js
       - /home/gordim/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/index.js
       - /home/gordim/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.19.1 (/home/gordim/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.0.0

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : not installed
   @capacitor/core    : 3.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.15.0 (/home/gordim/.nvm/versions/node/v16.15.0/bin/node)
   npm    : 8.5.5
   OS     : Linux 5.4

### Additional Information

The test file I put in "Playback URL" is my mock attempt (line 26) and my test attempt (line 79). Both commented.

When I run the code, it doesn't reproduce the error that occurred in the test.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a minimal reproduction of the issue? The provided app is a bit hard to debug given its size.

**Comment by GersonDantas** [comment]
> Obrigado pelo problema. Você pode fornecer uma reprodução mínima da edição? O aplicativo fornecido é um pouco difícil de depurar devido ao seu tamanho.

Hi, I will try to reproduce and post here as soon as possible

**Comment by GersonDantas** [comment]
1. first I validate the form field with a validator I created and if it is valid or not it shows valid or invalid in the data-status field of the input.
![code](https://user-images.githubusercontent.com/53773325/177041466-50e49484-3c91-427e-9114-1a1ca91dfa8e.png)
I call "useIonViewWillEnter" to validate the field of an Ionic modal before it is rendered.

I use a state of react so that it waits for the user to type
![code1](https://user-images.githubusercontent.com/53773325/177041609-229a80e6-91e8-4790-9951-b6b0e955998d.png)

when the user opens the Ionic modal, there will be 
an error in the input, because the field will be empty, but it will assign the state "invalid" with a value "" (empty text)

This actually plays when the code starts

[Gravação de tela de 07-03-2022 09:36:04 AM.webm](https://user-images.githubusercontent.com/53773325/177041786-1de89231-526c-4ff6-ac78-d9fadfc1b45c.webm)

the gray border of the input indicates that its data-status is ""(empty text). If it were red it would be invalid and blue would be valid.


when I test test this, the input is not validated in the same way

![coded](https://user-images.githubusercontent.com/53773325/177042070-d12ce0b4-1762-4544-823a-fa6f85262163.png)

and I get this output
[Gravação de tela de 07-03-2022 09:50:30 AM.webm](https://user-images.githubusercontent.com/53773325/177043185-5ec25147-659c-4f8f-83ee-2c8b3a147a09.webm)

I tried to use the mock before each of the tests too
![code4](https://user-images.githubusercontent.com/53773325/177042871-a0442d93-ec54-4f8f-9919-618f19824f5a.png)

just like I tried after the imports, at the beginning of the file.

I don't know if this is really a bug, or if I still haven't found the correct way to solve it. I just wanted to put it here because I found very few things on the internet about this subject. I found a report of this same bug a while ago, but it had been closed. Anyway, if I made a mistake, I'm sorry, I just wanted to solve my problem and other people who have the same.

Thanks for your attention. = )

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please provide this as a GitHub repo that I can run instead of code snippets?

**Comment by GersonDantas** [comment]
> Obrigado pela resposta. Você pode fornecer isso como um repositório mínimo do GitHub que eu possa executar em vez de trechos de código?

ok i will try to do it this weekend

**Comment by GersonDantas** [comment]
[this](https://github.com/GersonDantas/project-ionic-to-test-bug) is small project with just one input but it is very similar to the part I tested in the other project Sorry for the disorganization of the folders, I made the code quickly to be able to pass it on to you

**Comment by liamdebeasi** [comment]
Is there a particular error or behavior I should be looking out for? 

When running the tests I get the following error:

```
ReferenceError: Cannot access 'validate' before initialization
```

This is because the `validate` function in `Tab1.tsx` is defined after it is referenced in `useIonViewWillEnter`. Fixing that error yields the following error:

```
Too many re-renders. React limits the number of renders to prevent an infinite loop.
```

Is this the error you are reporting?

**Comment by GersonDantas** [comment]
> Existe algum erro ou comportamento específico que eu deveria estar atento?
> 
> Ao executar os testes recebo o seguinte erro:
> 
> ```
> ReferenceError: Cannot access 'validate' before initialization
> ```
> 
> Isso ocorre porque a `validate`função em `Tab1.tsx`é definida após ser referenciada em `useIonViewWillEnter`. A correção desse erro gera o seguinte erro:
> 
> ```
> Too many re-renders. React limits the number of renders to prevent an infinite loop.
> ```
> 
> Esse é o erro que você está relatando?
