### ISSUE TITLE
An error occurs when you repeatedly enable Ionic-modal of  to load Amap(ion-vue)

### ISSUE THREAD

**Issue by hexianggui** [ionic-team/ionic-framework#25543]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

An error occurs when you repeatedly enable Ionic-modal of  to load Amap. It's normal to use custom modal.
I'm a vue beginner ,do not know the cause of the error is what.
 Custom Modal is used to host Amap, but focus cannot be obtained.
How do I get focus in custom Modals when I have multiple IonicModals?
The reason for the error is not Ionic, but I hope it can load AMAP normally. Or how can I get the CustomModal activity focus trapping

### Expected Behavior

The reason for the error is not Ionic, but I hope it can load AMAP normally. Or how can I get the CustomModal activity focus trapping

### Steps to Reproduce

Thank you!Please help me!
[reproduce repository](https://github.com/hexianggui/custom-modal)

About [Amap](https://lbs.amap.com/api/jsapi-v2/summary/)

### Code Reproduction URL

https://github.com/hexianggui/custom-modal

### Ionic Info

Uncaught Error: Invalid Object: LngLat(NaN, NaN)
![2022-06-28_154254](https://user-images.githubusercontent.com/30622318/176122486-5254ff62-7015-414c-8c89-a754e0d4a770.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This error appears to be coming from your Amap library, not Ionic. I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/) for help debugging this issue.

This GitHub issue tracker is dedicated to bugs and features for Ionic, so the forums would be a better place to post about this error. Thanks!

**Comment by hexianggui** [comment]
> Thanks for the issue. This error appears to be coming from your Amap library, not Ionic. I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/) for help debugging this issue.
> 
> This GitHub issue tracker is dedicated to bugs and features for Ionic, so the forums would be a better place to post about this error. Thanks!

thank you!
but,I can't log in to forum

![2022-06-29_090254](https://user-images.githubusercontent.com/30622318/176329059-abf44a3d-9705-440d-97d1-9588fa4cde6c.png)

**Comment by hexianggui** [comment]
I haven't registered my account yet.I didn't find a registration entry.The page above appears after I click 'Log In'

**Comment by liamdebeasi** [comment]
Thanks! What browser + version of the browser are you using? Also do you have any ad-block/pop up blocking extensions enabled?
