### ISSUE TITLE
bug: java.lang.RuntimeException: Unable to instantiate application android.hardware.bluetooth

### ISSUE THREAD

**Issue by FractalMind** [ionic-team/ionic-framework#25553]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [ ] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

I want to use Ionic 4 to compile a Android 12 app.

When I compile my ionic v4 project with JDK8 + SDK Level 27.0.3 for Android <= 10 **and it works.**

But for Android 12 I need to use SDK level 31.0.0 + JDK 11 + Gradle 7.* **and it crashes**

After the update when I open my app I see the splash screen for half a second then it crashes.

After I `adb shell` > `logcat` I get

    E AndroidRuntime: FATAL EXCEPTION: main
    E AndroidRuntime: Process: com.myapp, PID: 28761
    E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application android.hardware.bluetooth package com.myapp: java.lang.ClassNotFoundException: Didn't find class "android.hardware.bluetooth" on path: DexPathList[[zip file "/data/app/~~8T8KfSjt3r4E8wgw-yQ0KA==/com.myapp-3qG2CR3HTq76WQg0MM5V1Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~8T8KfSjt3r4E8wgw-yQ0KA==/com.myapp-3qG2CR3HTq76WQg0MM5V1Q==/lib/arm64, /data/app/~~8T8KfSjt3r4E8wgw-yQ0KA==/com.myapp-3qG2CR3HTq76WQg0MM5V1Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
    E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1464)
    E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7458)
    E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:310)
    E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
    E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
    E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
    E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
    E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
    E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
    E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.hardware.bluetooth" on path: DexPathList[[zip file "/data/app/~~8T8KfSjt3r4E8wgw-yQ0KA==/com.myapp-3qG2CR3HTq76WQg0MM5V1Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~8T8KfSjt3r4E8wgw-yQ0KA==/com.myapp-3qG2CR3HTq76WQg0MM5V1Q==/lib/arm64, /data/app/~~8T8KfSjt3r4E8wgw-yQ0KA==/com.myapp-3qG2CR3HTq76WQg0MM5V1Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
    E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
    E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
    E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
    E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1177)
    E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1456)
    E AndroidRuntime: 	... 10 more

I use in *config.xml*

    <?xml version='1.0' encoding='utf-8'?>
    <widget id="com.myappid" version="4.4.49" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android">
        <name>My app Title</name>
        <description>Blablabla</description>
        <author email="sales@myapp.com" href="http://myapp.com/">MyApp</author>
        <content src="index.html" />
        <access origin="*" />
        <allow-navigation href="*" />
        <allow-intent href="http://*/*" />
        <allow-intent href="https://*/*" />
        <allow-intent href="ws://*/*" />
        <allow-intent href="tel:*" />
        <allow-intent href="sms:*" />
        <allow-intent href="mailto:*" />
        <allow-intent href="geo:*" />
        <preference name="ScrollEnabled" value="false" />
        <preference name="android-minSdkVersion" value="28" />
        <preference name="android-targetSdkVersion" value="31" />
        <preference name="BackupWebStorage" value="none" />
        <preference name="SplashMaintainAspectRatio" value="true" />
        <preference name="FadeSplashScreenDuration" value="300" />
        <preference name="SplashShowOnlyFirstTime" value="false" />
        <preference name="SplashScreen" value="screen" />
        <preference name="SplashScreenDelay" value="3000" />
        <preference name="loadUrlTimeoutValue" value="700000" />
        <platform name="android">
            <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
                <application android:usesCleartextTraffic="true" />
                <application android:requestLegacyExternalStorage="true" />
                <activity android:exported="true" />
                <uses-permission android:name="android.permission.BLUETOOTH" />
                <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
                <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
                <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
                <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
                <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
                <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
                <uses-feature android:name="android.hardware.bluetooth" android:required="true" />
            </edit-config>
            <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
            <preference name="SplashMaintainAspectRatio" value="true" />
            <preference name="SplashShowOnlyFirstTime" value="true" />
            <preference name="AndroidPersistentFileLocation" value="Compatibility" />
            <preference name="loadUrlTimeoutValue" value="700000" />
            <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
            <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
            <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
            <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
            <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
            <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        </platform>

And it translate to my *AndroidManifest.xml*

    <?xml version='1.0' encoding='utf-8'?>
    <manifest android:hardwareAccelerated="true" android:versionCode="40449" android:versionName="4.4.49" package="com.myapp" xmlns:android="http://schemas.android.com/apk/res/android">
        <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
        <uses-permission android:name="android.permission.INTERNET" />
        <application android:exported="true" android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:name="android.hardware.bluetooth" android:requestLegacyExternalStorage="true" android:required="true" android:supportsRtl="true" android:usesCleartextTraffic="true">
            <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:exported="true" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@style/Theme.AppCompat.NoActionBar" android:windowSoftInputMode="adjustResize">
                <intent-filter android:label="@string/launcher_name">
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
            </activity>
            <provider android:authorities="${applicationId}.cordova.plugin.camera.provider" android:exported="false" android:grantUriPermissions="true" android:name="org.apache.cordova.camera.FileProvider">
                <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths" />
            </provider>
            <activity android:clearTaskOnLaunch="true" android:configChanges="orientation|keyboardHidden|screenSize" android:exported="false" android:name="com.google.zxing.client.android.CaptureActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:windowSoftInputMode="stateAlwaysHidden" />
            <activity android:label="Share" android:name="com.google.zxing.client.android.encode.EncodeActivity" />
        </application>
        <uses-permission android:name="android.permission.BLUETOOTH" />
        <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
        <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
        <queries>
            <intent>
                <action android:name="android.media.action.IMAGE_CAPTURE" />
            </intent>
            <intent>
                <action android:name="android.intent.action.GET_CONTENT" />
            </intent>
            <intent>
                <action android:name="android.intent.action.PICK" />
            </intent>
            <intent>
                <action android:name="com.android.camera.action.CROP" />
                <data android:mimeType="image/*" android:scheme="content" />
            </intent>
        </queries>
        <uses-permission android:name="android.permission.CAMERA" />
        <uses-permission android:name="android.permission.FLASHLIGHT" />
        <uses-feature android:name="android.hardware.camera" android:required="true" />
    </manifest>

**As you can see I think I have all the right permission for bluetooth but why on earth it crash on Android 12!?**

### Expected Behavior

It should behave like Android 10 and just run the app

### Steps to Reproduce

Install and run in fresh debian container

```
apt-get update
apt install -y openjdk-11-jdk
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

export ANDROID_HOME=/app/shared/GIT_IGNORED/Android
export ANDROID_SDK_ROOT=/app/shared/GIT_IGNORED/AndroidDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/cmdline-tools/latest:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

yes | sdkmanager "build-tools;31.0.0" "platform-tools" "platforms;android-31" "tools"

export VERSIONGRADLE=7.4.2
export CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=https://services.gradle.org/distributions/gradle-${VERSIONGRADLE}-bin.zip
export GRADLE_HOME=/opt/gradle/latest
export PATH=${GRADLE_HOME}/bin:${PATH}

export NG_CLI_ANALYTICS=ci
npm install -g @ionic/cli --force
npm install -g cordova --force
cordova telemetry off

ionic cordova build android --prod --release --buildConfig=/app/shared/GIT_IGNORED/build.json --packageType=apk --verbose
```

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.803.20
   @angular-devkit/schematics    : 8.3.20
   @angular/cli                  : 8.3.20
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.2, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 15 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.19.3 (/usr/bin/node)
   npm    : 6.14.17
   OS     : Linux 5.13

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This error is coming from a native component inside of your application, not Ionic Framework.

Ionic Framework only concerns itself with the web UI/visual part of your application, so we are unable to help with this issue. I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/) for help with this.
