### ISSUE TITLE
bug: react documentation "working with tabs" actually not working

### ISSUE THREAD

**Issue by thirteenthstep** [ionic-team/ionic-framework#25562]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Taking a blank starter project (react) and applying the suggested source code from [https://ionicframework.com/docs/react/navigation#working-with-tabs](https://ionicframework.com/docs/react/navigation#working-with-tabs) results in invisible content: [https://dashboard.ionicframework.com/app/4b0cb229/preview/8061730](https://dashboard.ionicframework.com/app/4b0cb229/preview/8061730)

### Expected Behavior

Source code taken from documentation should not break the application.

### Steps to Reproduce

Create a blank starter project and add source code from https://ionicframework.com/docs/react/navigation#working-with-tabs

### Code Reproduction URL

https://github.com/thirteenthstep/tabtest

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1
   Ionic Framework : @ionic/react 6.1.12

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.14.0 
   npm    : 8.13.1
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you make your repo public?

**Comment by thirteenthstep** [comment]
Yeah sorry (;

**Comment by liamdebeasi** [comment]
This should be fixed now: https://ionicframework.com/docs/react/navigation#working-with-tabs (may need to clear your browser cache). Thanks for the report!
