### ISSUE TITLE
bug: Ionic PWA application is not working on iOS 14.5 and higher

### ISSUE THREAD

**Issue by somnathdegmailcom** [ionic-team/ionic-framework#25566]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The page has a set of Ion Inputs with a Ion Button which fires a seach function when onClick. This works perfectly on Windows machines and Android Mobile phones. But when we test it on iOS no matter where we press it always focus the first input of the page and opens up the on screen keyboard. We have tried to disable tap but that does not resolve this issue. The applicatin do run on iOS 13.7 as expected. But higher version it is not working.

Details of the tests done-
Tested the application with iOS 12.4, iOS 13.7, iOS 14.5 and iOS 15.4

Device used iPhone 12 pro (iOS 14.5 and iOS 15.4) and iPhone 8 Plus (iOS 12.4, iOS 13.7, iOS 14.5 and iOS 15.4).

For 12.4 no issue is present application works just like Android.

For 13.7 no issue is present application works just like Android.

For 14.5 the application does not work. The focus is going to the 1st text input and the popup key board is opening. Clicking on search button has same effect.

For 15.4 the focus still going to the 1st text input but no popup is opening. Clicking on search botton is working as expected and results are coming.

### Expected Behavior

The onClick methods should run the function intended and not just focus on the first input text box and open the on screen keyboard.

### Steps to Reproduce

1. Creat an IonPage with a set of input fields like IonInput
2. Create an IonButton to do some activity using the values of those inputs.
3. Now go to the page and click anywhere including the button. The first input button will be focused and the onscreen keypad will be visible. No actual onClick action will take place.

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\systcsyv\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\systcsyv\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\systcsyv\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\systcsyv\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\systcsyv\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\systcsyv\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\systcsyv\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\systcsyv\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.19.1 (C:\Users\systcsyv\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.1.6

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.15.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.10
   OS     : Windows 10

**Comment by mariusbolik** [comment]
Hello,

have you tried to add `[autofocus]="false"` to the desired ion-input element?

**Comment by somnathdegmailcom** [comment]
@mariusbolik 
I am new to React JS and Ionic. I have tried that option but it does not change the behaviour.
The IonInput are like this in my page ->

<IonRow>
                  <IonCol size="4" style={{ minWidth: "200px" }}>
                    <IonLabel>Product Name</IonLabel>
                  </IonCol>
                  <IonCol size="6" style={{ minWidth: "350px" }}>
                    <IonInput
                      **autofocus={false}**
                      type="text"
                      placeholder="Please Enter Product Name"
                      onIonChange={(e) => {
                        if (e.detail.value) {
                          productNameOnly();
                          setItemName(e.detail.value);
                        } else {
                          productNameOnly();
                          setItemName(undefined);
                        }
                      }}
                    />
                  </IonCol>
                </IonRow>
No matter where you press on the page the 1st input is getting focused. Even buttons are not responding to onClick events but focusing on the 1st input field.

Code for the IonButton ->
<IonRow>
                  <IonCol>
                    <IonButton
                      className="menu-button"
                      onClick={search}
                      disabled={isDisableSearchButtopn()}
                    >
                      Search
                    </IonButton>
                  </IonCol>
                </IonRow>

Thanks,
Somnath

**Comment by somnathdegmailcom** [comment]
Initial Search Page 
![one](https://user-images.githubusercontent.com/105421527/177007860-46d1f1ce-41ce-4650-afd5-57b56fc4d3d4.png)
Scroll Down The Search Page To Get The Search Button
![two](https://user-images.githubusercontent.com/105421527/177007874-8661f05c-23cf-40e2-8b03-eb3ccbea350a.png)
Once the button is pressed the first Input Box (MIN) is focused and the onscreen key pad is visible. No call to onClick event on iOS 14 and 15.
![three](https://user-images.githubusercontent.com/105421527/177007920-e55345cf-411b-4de7-8266-cb36da40a188.png)
Same thing happens when I click on any area of the screen.
All IonInput are inside an IonGrid<>IonRow<>IonCol structure which is under an IonAccordion under an IonAccordionGroup.

**Comment by somnathdegmailcom** [comment]
I am able to resolve the issue as per the suggesions made on [https://github.com/ionic-team/ionic-framework/issues/21982](url). I have to set the tabIndex many places on the application to avoid the autofocus issue.
