### ISSUE TITLE
bug: box-shadow not working on ion-item

### ISSUE THREAD

**Issue by thomasyu929** [ionic-team/ionic-framework#25574]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hi Team,

CSS property `box-shadow` not working on `ion-item`, I read the doc, didn't found specific property for ion-item like `--box-shadow`.

### Expected Behavior

box-shadow should be working on ion-item

### Steps to Reproduce

just try to add box-shadow on `ion-item`

### Ionic Info

`@ionic/angular@6.1.12`

**Comment by DwieDima** [comment]
you can use is directly on `ion-item`

```html
      <div class="ion-margin">
        <ion-item class="custom-item">
          <ion-label> box shadow </ion-label>
        </ion-item>
      </div>
```

```scss
.custom-item {
  box-shadow: 1px 5px 10px rgba(0, 0, 0, 0.2);
}
```

![image](https://user-images.githubusercontent.com/26873275/177292980-d70e9d9f-3aac-4af2-a2b8-c675a6832548.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. https://github.com/ionic-team/ionic-framework/issues/25574#issuecomment-1174814605 is the correct solution here. Not every CSS property has an equivalent CSS Variable. In this case, you can set `box-shadow` directly on `ion-item`.
