### ISSUE TITLE
bug: ScreenOrientation lock API wrong angle in iOS

### ISSUE THREAD

**Issue by socialsnobbish** [ionic-team/ionic-framework#25572]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Issue: Screen is turning towards anticlockwise (landscape-secondary) while calling *this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE)*

I can't use   *this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE_PRIMARY);* hardcoded as I want to support both LANDSCAPE_PRIMARY and LANDSCAPE_Secondary. 

Goal: To lock the screen in landscape mode, but the app should turn towards clockwise direction (landscape-primary) while lockinng the screen in landscape mode.

I want the screen to go towards clockwise direction when I call this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE);

Details of my sample project:

I have created an Ionic app from starter template:

    ionic start myApp tabs --capacitor

Added the [Screen Orientation][1] plugin by running these commands:

    npm install cordova-plugin-screen-orientation 
    npm install @awesome-cordova-plugins/screen-orientation 
    ionic cap sync

Added iOS target via these commands:

    ionic build --prod
    npm install @capacitor/ios
    npx cap add ios
    npx cap copy ios 
    npx cap sync ios
    

app.module.ts:

    import { NgModule } from '@angular/core';
    import { BrowserModule } from '@angular/platform-browser';
    import { RouteReuseStrategy } from '@angular/router';
    
    import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
    
    import { AppRoutingModule } from './app-routing.module';
    import { AppComponent } from './app.component';
    import { ScreenOrientation } from '@awesome-cordova-plugins/screen-orientation/ngx';
    
    @NgModule({
      declarations: [AppComponent],
      imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule],
      providers: [
        { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
        ScreenOrientation,
      ],
      bootstrap: [AppComponent],
    })
    export class AppModule {}

App component.ts code:

    import { Component } from '@angular/core';
    import { ScreenOrientation } from '@awesome-cordova-plugins/screen-orientation/ngx';
    
    @Component({
      selector: 'app-root',
      templateUrl: 'app.component.html',
      styleUrls: ['app.component.scss'],
    })
    export class AppComponent {
      constructor(private screenOrientation: ScreenOrientation) {
        // get current
        console.log(this.screenOrientation.type); // logs the current orientation, example: 'landscape'
    
        // set to landscape
        this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE);
    
        // detect orientation changes
        this.screenOrientation.onChange().subscribe(() => {
          console.log('Orientation Changed');
        });
      }
    }

After making the above change I have build the solution for iOS with these commands:

    ionic build --prod
    npx cap copy ios 
    npx cap sync ios
    npx cap run ios

Running the above code in iPhone simulator I am getting the screen like this:

[![enter image description here][2]][2]

My goal is to turn the screen initially to right side i.e in clockwise direction while locking the screen into landscape mode while keeping both landscape primary and secondary supported. I want the screen to turn like this instead of what is coming as default in my previous screenshot:

[![enter image description here][3]][3]

Do note, that the same code has no issues while running the code against Android target in Ioinc project, i.e the following code    this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE); turns the screen to right side i.e in clock wise direction.

Is this a bug in Cordova/iOS mapper for screen orientation?

  [1]: https://ionicframework.com/docs/native/screen-orientation
  [2]: https://i.stack.imgur.com/dss3O.png
  [3]: https://i.stack.imgur.com/FmN3n.png

### Expected Behavior

The following code this.screenOrientation.lock(this.screenOrientation.ORIENTATIONS.LANDSCAPE); should turn the screen to right side i.e in clock wise direction, the way it is doing on Android.

### Steps to Reproduce

Run the app in iOS and you will reproduce the issue.

### Ionic Info

Ionic:

   Ionic CLI : 6.19.1

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v16.15.1
   npm    : 8.11.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue. We do not manage the Screen Orientation Lock plugin, so I am unable to assist with this. Additionally, Ionic Framework does not manage any native plugins, so the issue is not likely in Ionic Framework. 

I recommend posting an issue on the [Screen Orientation Lock plugin repo](https://github.com/apache/cordova-plugin-screen-orientation/issues) or a thread on the [Ionic Forums](https://forum.ionicframework.com/).
