### ISSUE TITLE
feat: allow the user to customize what is disabled when the disabled property is set to true on an ion-button

### ISSUE THREAD

**Issue by joaopfg** [ionic-team/ionic-framework#25581]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I want to be able to smooth the disabled status on an `ion-button`.

### Describe the Use Case

For example, if I want to trigger hover events on disabled buttons, it would be something like:

```
<ion-button (mouseover)="OnButtonHover()" [disabled]="true" [disabled-hover]="false"> Test  </ion-button>
```

### Describe Preferred Solution

New properties on ion-button allowing to smooth the disabled status.

### Describe Alternatives

For now, the only alternative I can figure out is to not use the `disabled` property and instead disable stuff with flags on the corresponding events. For example, if I want to disable click but not hover, something like:

```
<ion-button (mouseover)="OnButtonHover()" (click)="isClickDisabled ? pass() : OnButtonClick()"> Test  </ion-button>
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. It sounds like the request here is to allow for hover events even when the `ion-button` is disabled. Did I understand the request correctly?

**Comment by joaopfg** [comment]
@liamdebeasi Hello, yes, it's exactly that.

**Comment by liamdebeasi** [comment]
Thanks! While we do not recommend doing this, you can achieve this behavior by setting `pointer-events: auto` on `ion-button`.

CodePen Example: https://codepen.io/liamdebeasi/pen/XWEXRXO

Note that enabling pointer events will also re-enabled activated states, so you may need to manually override those.

**Comment by liamdebeasi** [comment]
You can do that as well by adding `title` on to `ion-button`. Alternatively, you may want to create a tooltip which may give you a bit more flexibility in terms of customization. We recommend something like [Popper.js](https://popper.js.org/) or [Tippy.js](https://atomiks.github.io/tippyjs/).

**Comment by joaopfg** [comment]
@liamdebeasi Thanks!
