### ISSUE TITLE
bug: ion-button in Alert IonicSafeString events not firing

### ISSUE THREAD

**Issue by elvece** [ionic-team/ionic-framework#25584]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When creating a new alert using `AlertController` and passing in an `IonicSafeString` with an `<ion-button></ion-button>` element, the `ion-button` rendered in the alert modal does run any click actions or any `routerLink` directive navigations. The button click event is a no-op. 

If `ion-buttons` cannot be used in this way, then the documentation is incorrect [here](https://ionicframework.com/docs/techniques/security):

```
import { IonicSafeString, ToastController } from '@ionic/angular';

...

constructor(private toastController: ToastController) {}

async presentToast() {
  const toast = await this.toastController.create({
      message: new IonicSafeString('<ion-button>Hello!</ion-button>'),
      duration: 2000
  });
  toast.present();
}
```

### Expected Behavior

When you want to create an alert with additional `ion-button` elements with `routerLink` navigations within the alert modal (as opposed to in the buttons array), this should be enabled when using an `IonicSafeString`

### Steps to Reproduce

Create an alert as follows and see that the `ion-button` element will not route to the desired path (or handle any click event).

```
    private readonly alertCtrl: AlertController
    ...
    const alert = await this.alertCtrl.create({
      header: 'Title',
      message: new IonicSafeString(`Some other details, click here:
        <ion-button routerLink="desired/path/">Button</ion-button>`),
      buttons: [
        {
          text: 'Cancel',
          role: 'cancel',
        },
      ],
    })
    await alert.present()
```

### Ionic Info

```

Ionic:

   Ionic CLI: 6.20.1
   Ionic Framework: @ionic/angular 6.0.13
   @angular-devkit/build-angular : 13.3.0 
   @angular-devkit/schematics : 13.3.0 
   @angular/cli : 13.3.0 
   @ionic/angular-toolkit : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.11.0
   npm : 8.0.0
   OS : macOS Catalina

### Additional Information

_No response_

**Comment by DwieDima** [comment]
I don't think `ion-alert` is made for that. `IonSafeString` should be used for string formatting like bold text or breaks inside the message or header.

Actions should be performed using the buttons attribute.

```typescript
  async presentAlert() {
    const alert = await this.alertController.create({
      header: 'Alert!',
      message: new IonSafeString('<b>this</b> is some <br><br> formatted string')
      buttons: [
        {
          text: 'Cancel',
          role: 'cancel',
        },
        {
          text: 'Go to page',
          handler: () => { this.navController.navigateForward(['desired/path/']) }
        }
      ]
    });

    await alert.present();
  }
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo I can use to verify this behavior?

**Comment by liamdebeasi** [comment]
Though I will note, `routerLink` probably will not work as expected. When using `IonicSafeString` you are going to end up using the raw Web Component for `ion-button`, not the Angular component. The Angular component is where the `routerLink` logic lives as it integrates with the Angular Router.

**Comment by elvece** [comment]
> Thanks for the issue. Can you provide a GitHub repo I can use to verify this behavior?

I don't have this committed in a project as I ended up writing a custom component. I could spin up a demo repo if that is necessary?

**Comment by elvece** [comment]
> Though I will note, `routerLink` probably will not work as expected. When using `IonicSafeString` you are going to end up using the raw Web Component for `ion-button`, not the Angular component. The Angular component is where the `routerLink` logic lives as it integrates with the Angular Router.
> 
> edit: Also, `ion-toast` already has a built-in button feature that you may find better for your use case: https://ionicframework.com/docs/api/toast#toastbutton

I see, good to know. That probably explains the lack of action. Thanks for the explanation.

**Comment by liamdebeasi** [comment]
Does this resolve your concern, or are there other events not firing?

**Comment by elvece** [comment]
This resolves, I am fine closing this issue. Thanks!
