### ISSUE TITLE
bug: ion-input password value is empty when autofill by password Managers. 

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/ionic-framework#25596]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`ion-input` password field is not getting value when autofill from Password Manager on both android and iOS.  on other hand email field is getting value and working fine. this issue is happening only on `type="password"`.  I am using Angular reactive form to get values after auto filling email have correct value but password is empty string until user manually edit it. after editing password is working fine.   

### Expected Behavior

`ion-input` should get correct values by auto filling from password managers and pass it to `.ts` file.

### Steps to Reproduce

1). Create simple reactive form with `Email` and `Password` fields,
2). Make build for iOS or Android platform
3). Autofill application from Password Managers.
4) check console if Value is correct. 

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-rvl2cy?file=src/app/app.component.html

### Ionic Info

```

Ionic:

   Ionic CLI                     : 6.20.1 (C:\Users\IDEA\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.6.10
   @angular-devkit/build-angular : 12.0.5
   @angular-devkit/schematics    : 12.0.5
   @angular/cli                  : 12.0.5
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.2
   @capacitor/android : 3.2.2
   @capacitor/core    : 3.2.2
   @capacitor/ios     : 3.2.2

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.1

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.13.2
   OS     : Windows 10
```

### Additional Information

only password field is showing empty string on auto filling form from password manager. 

Almost Identical Issue here: 
[Ion-input issue](https://github.com/ionic-team/ionic-framework/issues/22682)

**Comment by liamdebeasi** [comment]
Thanks for the issue. Does this issue happen when running in a mobile browser or does it only happen when running in a Cordova/Capacitor app?

**Comment by liamdebeasi** [comment]
Ah my apologies, I see you had already posted on an open issue here: https://github.com/ionic-team/ionic-framework/issues/24739#issuecomment-1179242952. Let's try to keep the discussions in one place. I am going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/24739.
