### ISSUE TITLE
bug: Ripple color is getting darkness

### ISSUE THREAD

**Issue by Akash280899** [ionic-team/ionic-framework#25607]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

I am having the ionic segment button and having the ripple effect when we click on the tab**(Image 1)**.  Also, having the ion-tabs where each tab represent each SSPA modules. When I go to any other module and come back to the present module , the ion-segment-button's ripple-color is getting darkness. Every time I switch the modules and comes back, ripple color darkness is getting high and at one point of time can't able to see the text of the button itself**(Image 2).**

**Image-1:**
![image](https://user-images.githubusercontent.com/101315153/178275579-0bdda49d-45e0-402c-8f55-719cc1c4d66a.png)

**Image-2:**
![image](https://user-images.githubusercontent.com/58515715/178277178-efe421d1-03d9-4aa1-98e6-3a8b5143b25e.png)

### Expected Behavior

Even switch between SSPA modules , the ripple color should be same.

The color should be as the image-1.

### Steps to Reproduce

1. Create SSPA module .
2. Install Angular, Ionic and other dependencies.
3. Make a tab at the bottom for switching the modules.
4. Create a segment buttons to switch the tabs inside the modules.

### Ionic Info

**Ionic:**

   Ionic CLI : 6.20.1

**Utility:**

   cordova-res : not installed globally
   native-run  : not installed globally

**System:**

   NodeJS : v16.14.2
   npm    : 8.1.1
   OS     : Linux 5.10
   
  Running wsl2 in windows 10.

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
