### ISSUE TITLE
Ionic not working on webserver after being updated to Ionic 6 from Ionic 5

### ISSUE THREAD

**Issue by aardrasystems** [ionic-team/ionic-framework#25604]
Hi

I have recently updated my App from Ionic 5 to the recent Ionic 6.

I usually copy the entire www folder onto my ftp and then it works on my web domain.

But on my recent transfer after the update. It seems like its not longer working.

Has anything changed? This is the output i am getting.
```
GET https://aardra.app/vendor-es2015.js net::ERR_ABORTED 404
GET https://aardra.app/styles-es2015.js net::ERR_ABORTED 404
main-es2015.js:1 ERROR Error: Uncaught (in promise): Error: Not implemented on web.
polyfills-es2015.js:1          POST https://aardraapi.azurewebsites.net/api/Auth 500 (Internal Server Error)
```

What has changed ? Is this bug?

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
