### ISSUE TITLE
bug: URGENT! Kindly Provide https (ssl certificate handshake) PROCEDURE for certifying server trusted certificate and self-signed certificate in IONIC +React framework.

### ISSUE THREAD

**Issue by demoprojects123** [ionic-team/ionic-framework#25605]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

 There is no proper procedure provided for both trusted certificate and self-signed certificate . 
When I am converting code with Android Studio , it is throwing EEROR: SSLHandshakeError.
And not hitting API(using library:http-community).
Kindly instruct the procedure with optimal method in IONIC for handling https(ssl certificate) api calling feature.

### Expected Behavior

It should hit api correctly and provide data. 

### Steps to Reproduce

Follow your any method of certifying SSL Certificate(.cer). And inform me too. it is creating chaos at work. kindly HELP!!!!!!
urgent!!!!!!!!!!!

### Ionic Info

Please tell me the proper procedure first as there is nothing much working related to certifying SSL Certificate and getting data from server.

**Comment by sean-perkins** [comment]
@demoprojects123 this repository is responsible for the UI components used for building web-native applications. This repository has zero responsibility for anything related to Android Studio, SSL certificates or getting data from a server. 

Please open this issue in the respective repository that is causing this issue. I would also recommend providing an example project and steps that you tried to resolve the problem. Removing excess language and exclamation points would also be preferred by maintainers of open source projects.

Thanks!
