### ISSUE TITLE
bug: ion-datetime does not emit ionChange if presentation="month-year"

### ISSUE THREAD

**Issue by bot101** [ionic-team/ionic-framework#25606]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When I define a datetime like so:
`<ion-datetime #datetime2 (ionChange)="onDateChange($event)" [hidden]="!(rangeType === 'month')" presentation="month-year">`, it does not emit `ionChange` when the month or year changes. I thought it was due to an initialization issue as I used the same date time in multiple scenerios (allowing the user select a date range my month or custom dates) but realized that wasn't the issue after added a new datetime solely for the `month` use case.

### Expected Behavior

The date-time shoule emit `ionChange` when the date changes if presentation is `month-year`

### Steps to Reproduce

Add datetime element and change handler:\<ion-datetime #datetime2 (ionChange)="onDateChange($event)" [hidden]="!(rangeType === 'month')" presentation="month-year">

reload browser to initalize.

### Ionic Info

 Ionic CLI                     : 6.19.1 (C:\Users\robot\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe) 
   npm    : 8.5.5
   OS     : Windows 10

### Additional Information

OS is currently Windows 11 ( happened with windows 10 too, just updated windows today), but Ionic Info shows Windows 10

**Comment by sean-perkins** [comment]
@bot101 can you please create a reproduction for this issue? We have tests that cover this behavior and I am unable to reproduce: https://stackblitz.com/edit/pa2kpl?file=index.html

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
