### ISSUE TITLE
bug: The overflow-x 'hidden' attribute is not workin on iOS devices

### ISSUE THREAD

**Issue by migue99angel** [ionic-team/ionic-framework#25615]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I have some text which overflow I want to be hidden. Every Android device and navigator is working with this class: 

```css
.hide_text{
  overflow: hidden;
  position: relative;
  text-overflow: ellipsis;
}
```
To make it works on Safari and iOS devices I had to inject the styles in a setTimeout (and add a few more rules),
```ts
      // This timeout is needed due to a render problem with iOS devices
      setTimeout(() => {
        const elements = document.getElementsByTagName('h3');
        Array.from(elements).forEach((element) => {
          element.style.height = '44px';
          element.style.overflowX = 'hidden';
          element.style.position = 'relative';
          element.style.textOverflow = 'ellipsis';
          element.style.webkitLineClamp = '2';
          element.style.display = ' -webkit-box';
        });
        this.ref.detectChanges();
      }, 200); 
  
```

I think there is a rendering problem with those elements because when I interact with that elements they get hidden automatically.

### Expected Behavior

It is expected the text be hidden just with the CSS styles.

### Steps to Reproduce

Set the styles to hide a text to an HTML element (an h3, for example).

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/euroinnova/.nvm/versions/node/v14.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.11
   @angular-devkit/build-angular : 12.2.16
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.0
   @capacitor/android : 3.4.1
   @capacitor/core    : 3.3.0
   @capacitor/ios     : 3.4.1

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v14.19.0 (/Users/euroinnova/.nvm/versions/node/v14.19.0/bin/node)
   npm    : 6.14.16
   OS     : macOS Monterey

### Additional Information

I wrote this post https://forum.ionicframework.com/t/problem-in-lazy-load-ion-list-render/224760

**Comment by pablojjimenez** [comment]
I have faced with the same _bug_...

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
