### ISSUE TITLE
feat: accept rxjs ^7.0.0

### ISSUE THREAD

**Issue by rbalet** [ionic-team/ionic-framework#25614]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Make  `@ionic-native/core` accept `rxjs&7.0.0`

### Describe the Use Case

While working with angular ^14.0.0, some of the repo I use are requesting rxjs v^7.0.0 to be installed while the `@ionic-native/core@5.36.0` is requiring  `rxjs@"^5.5.0 || ^6.5.0"` which create an error

### Related Code

npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/core@5.36.0
npm ERR! node_modules/@ionic-native/core
npm ERR!   @ionic-native/core@"5.36.0" from the root project
npm ERR!   peer @ionic-native/core@"^5.1.0" from @ionic-native/app-version@5.36.0
npm ERR!   node_modules/@ionic-native/app-version
npm ERR!     @ionic-native/app-version@"5.36.0" from the root project

**Comment by liamdebeasi** [comment]
Thanks for the issue. We do not manage `@ionic-native` anymore, so we are unable to fix this. I recommend creating this issue on https://github.com/danielsogl/awesome-cordova-plugins. This is the new `@ionic-native` repo.

See https://ionicframework.com/blog/a-new-chapter-for-ionic-native/ for more context.
