### ISSUE TITLE
bug: ion-select don't show

### ISSUE THREAD

**Issue by msxmy** [ionic-team/ionic-framework#25613]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

ion-select interface set to popover, when select window is showing, click other area to dismiss, and open ion-select quickly，the select window don't show

### Expected Behavior

showing right

### Steps to Reproduce

ion-select interface set to popover, when select window is showing, click other area to dismiss, and open ion-select quickly，the select window don't show

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\malata\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.9.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, (and 21 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.6.0) : 1.4.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\malata\AppData\Local\Android\Sdk)
   NodeJS            : v14.15.3 (D:\nodejs\node.exe)
   npm               : 6.14.9
   OS                : Windows 10

  ────────────────────────────────────────────────────────────

          Ionic CLI update available: 5.4.16 → 6.20.1

     The package name has changed from ionic to @ionic/cli!

             To update, run: npm uninstall -g ionic
                 Then run: npm i -g @ionic/cli

  ────────────────────────────────────────────────────────────

**Comment by msxmy** [comment]
https://user-images.githubusercontent.com/21231968/178442470-d5cd3b90-5363-48a3-909a-958c13c28307.mp4

**Comment by msxmy** [comment]
if  interface set to alert , it looks right

**Comment by msxmy** [comment]
https://ionicframework.com/docs/api/select#popover  this code can reproduction

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify what the issue is? The video in https://github.com/ionic-team/ionic-framework/issues/25613#issuecomment-1181457562 appears to show `ion-select` working correctly.

**Comment by msxmy** [comment]
1: When the selection box is displayed, click around to make the selection box disappear.

2: Click the ion-select quickly within 1s. At this time, the selection box is not displayed

**Comment by liamdebeasi** [comment]
Thanks. What browser are you testing this on? I am testing this with Chrome 103 on macOS, and the popover opens correctly. I will note that double clicking the select when dismissing does not immediately open a new select, but that is to be expected as the popover's backdrop continues to receive pointer events until the popover is fully dismissed.

**Comment by msxmy** [comment]
Thank you for your answer， i testing this on Microsoft Edge 103.0.1264.37, I think the next click does not show because the animation has not really disappeared. Can you tell me how to modify the duration of this animation. and  if interface set to alert , it looks right

**Comment by msxmy** [comment]
Thank you for your answer

**Comment by msxmy** [comment]
Thank you for your answer
