### ISSUE TITLE
feat: setCookie persisting until cleared

### ISSUE THREAD

**Issue by shaneAPT** [ionic-team/ionic-framework#25611]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Make it more visible that setCookie() will persist the cookie you set across local storage (?) and it will not be removed until you explicitly call clearCookies() or removeCookies().

https://ionicframework.com/docs/v3/native/http/#setCookie

### Describe the Use Case

After getting stung with this. In a http-interceptor there is a check to see if a cookie is being passed as a header, if so setCookie() that cookie. I thought this worked fine, however logging out and logging into different users was passing incorrect cookies to my API's from whatever user I originally logged in with. This is a big no-no. Eventually I narrowed it down to setCookie persisting the cookie in local storage (?) and not removing this cookie until clearCookies() is called on logout. Even when the new user would log in and setCookie() themselves, it would not overwrite the original user cookie.

This seems to work fine now by calling clearCookies() on logout, it just took me a while to figure out that this was happening and I think it's something easy to get caught on. I could be wrong, but I couldn't find anything in the documentation giving any indication that this is the behaviour of setCookie(). My assumption was on get() the cookies would reset themselves and not persist for every subsequent call - although I do understand this may be desired.

### Describe Preferred Solution

Add a toggle in setCookie() whether or not you want the given cookie to persist after it is first used in a HTTP call. If set to false, clear the cookie after the first call. This is a single-use cookie.

### Describe Alternatives

Perhaps updating the documentation to explain that setCookie() cookies will not be removed until removeCookies() or clearCookies() is called.

**Comment by sean-perkins** [comment]
@shaneAPT please open an issue on the repository for that plugin: https://github.com/silkimen/cordova-plugin-advanced-http
