### ISSUE TITLE
bug: ion-datetime color customization issues

### ISSUE THREAD

**Issue by sandrafreihofer** [ionic-team/ionic-framework#25619]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

In our project we are providing a light and dark theme. The `ion-datetime` is using the CSS var `--ion-color-step-300` to define the font color for the day of week part in the area of the calendar and for the background color in the time picker area. This leads to the problem that the time for the dark theme is no longer displayed legibly. Furthermore we ran into a contrast problem where we are not able to meet some accessibility requirements.

`ion-datetime` with our light theme applied:

![ion-datetime-light-mode](https://user-images.githubusercontent.com/402543/178525018-9d22a8b6-32e0-4440-ba3b-5f96e18f6f9c.png)

`ion-datetime` with our dark theme applied:

![ion-datetime-dark-mode](https://user-images.githubusercontent.com/402543/178525109-a9245cc9-4d9c-4486-afe7-17bdc0c85b16.png)

### Expected Behavior

It would help if the `ion-datetime` component supports some additional CSS vars which could be set by the consumer. There should be one CSS var to set the color of the "day of the week" part and another to set the background for the time picker separately.

I thought that with this issue I would first ask if there is another option for my use case and if at all I can create a PR to fix the "problem" we have.

### Steps to Reproduce

If I change the CSS variable accordingly, the font color for the area in the calendar also changes. Which is not always the best way to do it.

`ion-datetime` with our dark theme applied and a different color definition for `ion-color-step-300`:

![ion-datetime-dark-mode-custom](https://user-images.githubusercontent.com/402543/178527012-556b5107-e5c8-42af-a0f3-9c723a4971c4.png)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (/Users/sandra/.nvm/versions/node/v16.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.13
   @angular-devkit/build-angular : 13.2.3
   @angular-devkit/schematics    : 13.2.3
   @angular/cli                  : 13.2.3
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0 (/Users/sandra/.nvm/versions/node/v16.13.0/bin/node)
   npm    : 8.1.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue. Do you have a sample app I can try? It is a bit hard to help without being able to reproduce the issue on my end.

**Comment by sandrafreihofer** [comment]
@liamdebeasi Since the project I am working on is not public it is a bit hard to show you something, but let me try to provide a sample app which shows what I am talking from.

**Comment by sandrafreihofer** [comment]
@liamdebeasi After debugging and checking how the `ion-datetime` component is implemented, I found out that the original problem is rather that we don't have definitions for stepped colors in our theme. I think by setting these additional colors we can solve our use case.

Please excuse the creation of this issue, I initially thought that the problem was on Ionic's side. Let's close it.
