### ISSUE TITLE
bug: window.Ionic.platforms returns ['mobile', 'mobileweb'] instead of ['desktop'] on chromium based browser

### ISSUE THREAD

**Issue by cyril-colin** [ionic-team/ionic-framework#25625]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

On Chrome desktop browser, I use `isPlatform('desktop')` but it always return false and my app always behaves as a mobile one.
Same problem with recent Chromium or Edge browser but no problems on Firefox.

### Expected Behavior

`isPlatform('desktop')` should return `true` on chromium desktop browsers

### Steps to Reproduce

- Build an Ionic project
- run it on a chrome browser
- open console and type :  `window.Ionic.platforms `

You can try it on any Ionic project, like https://www.justwatch.com/ (not mine, just an example)

You will see that this return ['mobile', 'mobileweb']

### Ionic Info

Ionic:

   Ionic CLI : 6.10.1

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   NodeJS : v16.13.2
   npm    : 8.1.2
   OS     : Windows 10

### Additional Information

When I browse source code here [const isMobile = (win: Window) => matchMedia(win, '(any-pointer:coarse)');](https://github.com/ionic-team/ionic-framework/blob/5676bab31614200bc07229e3720a9d2f34029925/core/src/utils/platform.ts#L90)

I tried `window.matchMedia?.('(any-pointer:coarse)').matches` in both Chrome and Firefox: Chrome returns `true`, and Firefox `false`

Maybe it is problem with Chromium ?

Chrome version:  103.0.5060.114
Firefox version: 102.0.1

PS: I checked that I am not in a mobile debug mode before posting this issue :P

**Comment by cyril-colin** [comment]
Ow... the bug seems to be only on my computer: an other windows 11 PC with same chrome version has no problem...

I'll be back with more information.

**Comment by liamdebeasi** [comment]
Does the affected Windows machine have a touch screen by any chance?
