### ISSUE TITLE
bug: ion-picker: PickerColumn refresh() private

### ISSUE THREAD

**Issue by Gargamil** [ionic-team/ionic-framework#25631]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Version: @ionic/angular: ^6.1.13

If i try to access refresh() on a PickerColumn the following error occours:

```
Uncaught (in promise): TypeError: picker.columns[0].refresh is not a function
TypeError: picker.columns[0].refresh is not a function
```

### Expected Behavior

Call refresh() and get the column updated.

### Steps to Reproduce

1. Create a picker with `PickerController` with at least one column
2. present picker with `await picker.present();` 
3. Call `picker.columns[0].refresh();`
4. Fail

### Ionic Info

```
Ionic:

   Ionic CLI                     : 5.4.16 (/Users/tobi/.nvm/versions/node/v16.15.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.1.13
   @angular-devkit/build-angular : 14.0.5
   @angular-devkit/schematics    : 14.0.5
   @angular/cli                  : 14.0.5
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 9.1.0, browser 6.0.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 18 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.6.0) : 0.2.8

System:

   Android SDK Tools : 26.1.1 (/Users/tobi/Library/Android/sdk)
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v14.20.0 (/Users/tobi/.nvm/versions/node/v14.20.0/bin/node)
   npm               : 6.14.17
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. There is no `refresh` method on `ion-picker-column`, so this is to be expected. Can you clarify what you are trying to do?
