### ISSUE TITLE
ionic generate Error

### ISSUE THREAD

**Issue by eqcb** [ionic-team/ionic-framework#25636]
**Ionic version:**

[x] **5.9.4**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

Cannot generate pages/component
**Expected behavior:**

Be able to generate page/component
**Steps to reproduce:**

Trying to generate a page/component on an existing Ionic 5 app using "ionic generate page pageName" or "ionic generate component componentName" commands gets me this:

> ng.cmd generate page cupons --project=app
validation_1.validateName is not a function
[ERROR] Could not generate page.

**Other information:**

This was working as expected the last time I had to create a new page, no so long ago.

**Ionic info:** 

```
Ionic:

   Ionic CLI                     : 6.20.1 (C:\Users\xxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.9.4
   @angular-devkit/build-angular : 0.901.15
   @angular-devkit/schematics    : 13.2.5
   @angular/cli                  : 9.1.15
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : 3.4.3
   @capacitor/core    : 3.4.1
   @capacitor/ios     : 3.4.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.2
   OS     : Windows 10
```

**Comment by eqcb** [comment]
Sure, here it is:

{
  "name": "",
  "version": "1.4.7",
  "author": "",
  "description": "",
  "homepage": "",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~9.1.13",
    "@angular/core": "~9.1.13",
    "@angular/forms": "~9.1.13",
    "@angular/localize": "^9.1.13",
    "@angular/platform-browser": "~9.1.13",
    "@angular/platform-browser-dynamic": "~9.1.13",
    "@angular/router": "~9.1.13",
    "@capacitor-community/apple-sign-in": "^1.0.1",
    "@capacitor-community/facebook-login": "^3.1.1",
    "@capacitor/android": "3.4.3",
    "@capacitor/app": "^1.1.0",
    "@capacitor/core": "^3.4.1",
    "@capacitor/device": "^1.1.2",
    "@capacitor/geolocation": "^1.3.1",
    "@capacitor/ios": "^3.4.1",
    "@capacitor/local-notifications": "^1.1.0",
    "@capacitor/network": "^1.0.7",
    "@capacitor/push-notifications": "^1.0.9",
    "@capacitor/share": "^1.1.1",
    "@capacitor/splash-screen": "^1.2.2",
    "@fortawesome/angular-fontawesome": "^0.6.1",
    "@fortawesome/fontawesome-svg-core": "^1.3.0",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@ionic-native/core": "^5.36.0",
    "@ionic-native/status-bar": "^5.36.0",
    "@ionic/angular": "^5.9.4",
    "@ionic/storage": "^2.3.1",
    "breeze-client": "^2.1.2",
    "capacitor-native-settings": "^0.1.0",
    "core-js": "^2.6.12",
    "countup.js": "^2.0.8",
    "es6-promise-plugin": "^4.2.2",
    "moment": "^2.29.1",
    "ngx-countup": "^7.3.3",
    "rxjs": "~6.5.1",
    "zone.js": "~0.10.2"
  },
  "optionalDependencies": {
    "ios-deploy": "1.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.15",
    "@angular/cli": "~9.1.15",
    "@angular/compiler": "~9.1.13",
    "@angular/compiler-cli": "~9.1.13",
    "@angular/language-service": "~9.1.13",
    "@capacitor/cli": "^3.4.1",
    "@ionic/angular-toolkit": "^2.3.3",
    "@ionic/cli": "^6.20.1",
    "@ionic/lab": "3.2.10",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "^2.0.10",
    "@types/node": "^12.20.46",
    "codelyzer": "^5.1.2",
    "jasmine-core": "^3.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jetifier": "^2.0.0",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.7.0",
    "protractor": "^5.4.4",
    "ts-node": "~7.0.0",
    "tslib": "^1",
    "tslint": "~5.15.0",
    "typescript": "^3.8.3"
  }
}

**Comment by mhartington** [comment]
So I just tested out a sample project with this package.json, and it was working fine on my end.


https://github.com/mhartington/schematics-test/tree/main

**Comment by eqcb** [comment]
Any suggestion? Maybe update/downgrade some dependencies?

**Comment by mhartington** [comment]
I would delete your node_modules/package-lock just to have a clean slate.

**Comment by Somasekhar1712** [comment]
Try it with typescript@^4 @liamdebeasi

**Comment by eqcb** [comment]
Sorry for late answer, I created that page I needed manually but had a new one to create so I tried deleting node_module/package-lock and it worked!
Thanks!
