### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by prabhakarsingh1992** [ionic-team/ionic-framework#25651]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hi,
I am working with ionic **6.1.14** and capacitor **3.6.0**. Hardware backbutton is not working.

`this.platform.backButton.subscribeWithPriority(
          10,
          async () => {
           
            this.location.back()
            
          }
        )`

this code is not getting called but same code works for capacitor 2.X.X. Can you have it out how to resolve this.

### Expected Behavior

`this.platform.backButton.subscribeWithPriority(
          10,
          async () => {
           
            this.location.back()
            
          }
        )`

this code should work with capacitor 3.X.X

### Steps to Reproduce

`this.platform.backButton.subscribeWithPriority(
          10,
          async () => {
           
            this.location.back()
            
          }
        )`

this code is not getting called but same code works for capacitor 2.X.X.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.14
   @angular-devkit/build-angular : 14.0.6
   @angular-devkit/schematics    : 13.3.8
   @angular/cli                  : 14.0.3
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : 3.6.0
   @capacitor/core    : 3.6.0
   @capacitor/ios     : 3.6.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.15.1 (/usr/local/bin/node)
   npm    : 8.13.2
   OS     : Linux 5.15

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
