### ISSUE TITLE
feat: datetime multiple select needs a label on how many dates are selected

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-framework#25668]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

In Ionic 6.2 we introduced a feature for `ion-datetime` that lets users select multiple dates (with `presentation="date"`). As part of these changes, we found that the header in MD mode was confusing as it only showed one date:
![image](https://user-images.githubusercontent.com/2721089/180315784-57389923-1854-4751-ab0c-2896ae022a64.png).

We considered other options such as:

1. Showing all selected dates.
2. Showing the current selected dates and then a count for the remaining n-1 (I.e. Thu, Jul 21 and 4 other dates)
3. Showing the number of dates selected (I.e. 5 dates)

Additional considerations such as how localization will work for this feature made us decide to not move forward with changes to the header text until we could do more research and collect feedback from the community. As a result, the selected date will not appear on the MD datetime when `multiple="true"`. This temporary restriction also applies to the new `ion-datetime-button`.

We plan to prioritize addressing this, and we would also appreciate feedback from the community regarding this behavior.

**Comment by amandaejohnston** [comment]
This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25817 and the update will be available in the upcoming release of Ionic 6.3 👍 See the PR description for details on what we decided.
