### ISSUE TITLE
bug: Ionic React page transitions not working with history.push

### ISSUE THREAD

**Issue by benallfree** [ionic-team/ionic-framework#25664]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When transitioning between pages, it appears that the pages transition by sliding upward rather than coming in from the right.

### Expected Behavior

Two `<Route>` components in an `<IonRouterOutlet>` should transition from left to right using `useHistory().push()`

### Steps to Reproduce

Please see the codesandbox URL.

```tsx
  <IonApp>
    <IonReactRouter >
      <IonRouterOutlet animated >
        <Route exact path="/page1" >
          <Page1 />
        </Route>
        <Route exact path="/page2">
          <Page2 />
        </Route>
        <Route exact path="/">
          <Redirect to="/page1" />
        </Route>
      </IonRouterOutlet>
    </IonReactRouter>
  </IonApp>
```

### Code Reproduction URL

https://codesandbox.io/s/ionic6-react-typescript-page-transitions-veifn6?file=/src/App.tsx

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.15

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.14.0
   OS     : macOS Monterey
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you referring to the Material Design (MD) vs. iOS transitions? When running in MD mode, the pages fade/transition in from bottom to top. On iOS they slide in from side to side.

**Comment by benallfree** [comment]
Ah, that was it. It seems the browser defaults to android then?

For anyone else who finds their way here, using `?ionic-mode=ios` or `?ionic:mode=android` on the querystring will change the transition styles.

@liamdebeasi Is there anywhere this behavior is documented? I'm hitting some friction with API docs having limited examples in React, particularly the demos. I'd be glad to help with this sort of thing if it would be helpful to you all.

**Comment by liamdebeasi** [comment]
Yes, the browser defaults to Material Design mode. You can also set the mode using the global config: https://ionicframework.com/docs/react/config#config-options

```tsx
setupIonicReact({
  mode: 'ios'
});
```

**Comment by benallfree** [comment]
Thank you for the help!
