### ISSUE TITLE
feat: IonIcon component should support 3rd party Icons like react-icons -- IonicReact

### ISSUE THREAD

**Issue by I-am-abdulazeez** [ionic-team/ionic-framework#25670]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I want to make `IonIcon` use `react-icons`.

![image](https://user-images.githubusercontent.com/38980212/180408473-10936473-5084-46a2-b0ec-87e7fccc630d.png)

This will throw an error because

`Type 'IconType' is not assignable to type 'string'.`

### Describe the Use Case

![image](https://user-images.githubusercontent.com/38980212/180408896-fede87ce-948a-418c-bdcb-ac4acd3ebf02.png)

### Describe Preferred Solution

It will be nice if we can have the `IonIcon` component to have a type of `IconType` or `string` to be able to use a 3rd party icon library.

Of course we can use it like normal

`<RiHomeLine />` in our component, but it will be nice if `ionic-react` `IonIcon` component can have that ability.

### Describe Alternatives

React-Native: `react-native-vector-icons`

**Comment by sean-perkins** [comment]
@I-am-abdulazeez `IonIcon` does support 3rd party SVGs to be used with the component. We do not support passing a React component as an SVG however. 

Can you explain why you would need `IonIcon` to do this? It would create additional overhead in your application vs. using their component directly.

**Comment by I-am-abdulazeez** [comment]
Hi @sean-perkins , thanks for your reply.

I created an array of objects for my `sidemenu component`, and `i` was hoping to mix both `Ionicons` and react-icons together because some icons i need does not exist in `ionicons` and it exist in react-icons. That is my reason.

Thanks.
