### ISSUE TITLE
feat: new calendar component

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#25672]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I used to use this component https://github.com/HsuanXyz/ion2-calendar which seems to be great with ionic apps however the developer has no longer maintain this which is why I think it would be great if Ionic creates a component like this.

### Describe the Use Case

Some of my apps require users to select like a range between the dates

**Comment by sean-perkins** [comment]
@farisfaisalthena thanks for this feature request. Selecting a range of dates within the date/calendar picker is a duplicate of #23572. I am going to close out this feature request and you can follow the status of the feature there.

Thanks!
