### ISSUE TITLE
bug: navigation inside of ion nav is buggy

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#25677]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Navigation in a `<ion-nav>` inside a Modal appears to be very buggy for me:

1. The **IonTitle** of the root page animates wrong -> To the bottom of the side
2. The entering of the next page is buggy and stucks a short time in the animation

### Expected Behavior

The animation should work without bugs 😃 

### Steps to Reproduce

See attached Repo:

1. Open Modal
2. Navigate forward (buggy enter animation)
3. Navigate back via click or swipe (buggy leave animation)

### Code Reproduction URL

https://github.com/EinfachHans/ionic-modal-nav-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/hans/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.15
   @angular-devkit/build-angular : 14.1.0
   @angular-devkit/schematics    : 14.1.0
   @angular/cli                  : 14.1.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.6.0

System:

   NodeJS : v16.14.2 (/Users/hans/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.6.0
   OS     : macOS Monterey

**Comment by sean-perkins** [comment]
@EinfachHans thanks for reporting this issue!

This appears to work in `6.1.14`, but broke in `6.1.15`. We will classify this as a bug and figure out what caused the regression.

**Comment by sean-perkins** [comment]
@EinfachHans If you update your example template for `modal.component.html` to:

```html
<ion-content>
  <ion-nav [root]="root"></ion-nav>
</ion-content>
```

This will solve the problem in your project. The change to support custom sized dialogs affects implementations of modal that don't use `ion-content`. Discussing with the team of the best options here. Ideally we would like to recommend developers use the template sample provided above when using `ion-nav` in a modal, but this may also cause issues with existing applications built without it.

**Comment by liamdebeasi** [comment]
Here is a dev build if you would like to test the fix: `6.1.16-dev.11658962095.1f24647d`

**Comment by EinfachHans** [comment]
Works, thank you! 😊

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25689, and a fix will be available in an upcoming release of Ionic Framework.
