### ISSUE TITLE
bug: No Internet cause Ionic App freeze

### ISSUE THREAD

**Issue by thomasyu929** [ionic-team/ionic-framework#25676]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

On my application, I want to test no internet scenario. but If disabled network. make any action will cause the whole app freeze.

seems like ionic dependency need something from online.
see screenshot:
![image](https://user-images.githubusercontent.com/43472214/180914162-c294473f-4d18-4a60-a567-cecd5dc233f3.png)

### Expected Behavior

I use `navigator.onLine` to handle no internet in interceptor file.
It shouldn't freeze the application when no internet available.

### Steps to Reproduce

just create a normal ionic app. and cut off your network see what's going on.

### Ionic Info

`@ionic/angular@6.1.12`

**Comment by indraraj26** [comment]
Looks like similar issue https://github.com/angular/angular/issues/46636

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a separate issue and ensure the template is fully filled out. Thank you!
