### ISSUE TITLE
bug: ionBlur emitted on focus after scroll assist

### ISSUE THREAD

**Issue by florian72810** [ionic-team/ionic-framework#25673]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [x] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When a ion-input is touched, and Scroll Assist does scroll the content, a ionBlur is emitted.

### Expected Behavior

ionBlur should emit when losin focus, regardless of scrollAssist

### Steps to Reproduce

You need to have a ion-input and a big ion-content with scroll.

For example, an ion-input with 400px top and 1000px bottom.

⚠️ if you already scroll to position ion-input in about 40% top of the page, scrollAssist does nothing and the bug does not happen.

### Code Reproduction URL

https://github.com/florian72810/ion-blur-with-scroll-assist

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (/Users/foxer/.nvm/versions/node/v14.19.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.15
   @angular-devkit/build-angular : 14.1.0
   @angular-devkit/schematics    : 14.1.0
   @angular/cli                  : 14.1.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v14.19.1 (/Users/foxer/.nvm/versions/node/v14.19.1/bin/node)
   npm    : 8.14.0
   OS     : macOS Monterey

### Additional Information

I initially found the bug on Ionic 5.9. I reproduced it on Ionic 6.

https://user-images.githubusercontent.com/20518933/180608978-ed93d59a-00f0-46b3-8ff6-39d981af2de2.mov

**Comment by sean-perkins** [comment]
@florian72810 thanks for reporting this issue. I am able to reproduce when emulating in browser with an iPhone SE emulation. It does not happen consistently, but occasionally the blur event will be fired when the input is focused (while scrolling into view). 

We will track this as a bug.
