### ISSUE TITLE
bug:  click on ion-item will select below or upper ion-item

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-framework#25696]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

 click on ion-item or minus button will select below or upper ion-item

![image](https://user-images.githubusercontent.com/23274631/182015838-c71b5b00-9dc1-4a2c-b5da-77a6f5d89089.png)

html: 
```
<ion-content>
      <ion-item class="item-desc">
        <ion-checkbox slot="start" mode="md" (ionChange)="onRadioValueChanged($event)"></ion-checkbox>
          <ion-row class="ion-align-items-center"  style="    width: 100%;">
            <ion-col size="4">Apple</ion-col>
            <ion-col size="8">
              <ion-item lines="none">
                <ion-button size="small" color="primary" slot="start"
                  (click)="onIncreaseValue($event)" [disabled]="true">
                  <ion-icon name="remove"></ion-icon>
                </ion-button>
                <ion-text class="test-text">{{test}}</ion-text>
                <ion-button  size="small" color="primary" slot="end"
                  (click)="onIncreaseValue($event)">
                  <ion-icon slot="icon-only" name="add"></ion-icon>
                </ion-button>
              </ion-item>
              </ion-col>
          </ion-row>
        <ion-text slot="end" color="dark">Henlo</ion-text>
      </ion-item>
      <ion-item class="item-desc">
        <ion-checkbox slot="start" mode="md" (ionChange)="onRadioValueChanged($event)"></ion-checkbox>
          <ion-row class="ion-align-items-center" style="    width: 100%;">
              <ion-col size="4">Ball</ion-col>
              <ion-col  size="8" *ngIf="false">
                <ion-item lines="none">
                <ion-button size="small" color="primary" slot="start"
                  (click)="onIncreaseValue($event)" [disabled]="true">
                  <ion-icon name="remove"></ion-icon>
                </ion-button>
                <ion-text class="test-text">{{test}}</ion-text>
                <ion-button  size="small" color="primary" slot="end"
                  (click)="onIncreaseValue($event)">
                  <ion-icon slot="icon-only" name="add"></ion-icon>
                </ion-button>
              </ion-item>
              </ion-col>
          </ion-row>
        <ion-text slot="end" color="dark">Henlo</ion-text>
      </ion-item>
</ion-content>
```

ts: 
```
 onRadioValueChanged(event: any) {
    console.log('radio trigger');
    console.log(event);
  }


  onIncreaseValue(event: any) {
    // event.preventDefault();
    // event.stopPropagation();
    console.log('on increase value');
    this.test += 1;
    // return false;
  }

```

### Expected Behavior

It should not select below/upper ion-item whereas i am clicking on different ion-item

### Steps to Reproduce

1. npm i && ionic serve
2. click on minus button of ion-item

### Code Reproduction URL

https://github.com/indraraj26/storage-boolean-issue/tree/iy-checkbox-trigger

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.3
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : 3.6.0
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. What browser are you testing this on? I am only able to reproduce this on desktop Chrome while in mobile emulation mode.

**Comment by indraraj26** [comment]
Hi Liam,

I did not test in desktop chrome and mobile. 

You are correct this is happening in mobile emulation mode. 

I will close this for now. 

Thank you

**Comment by liamdebeasi** [comment]
Sounds good. This appears to be an issue with how Chrome emulates touch events when using the developer tools. If you notice this happening on desktop or mobile Chrome (without any emulation) let us know, and I will be happy to take another look.
