### ISSUE TITLE
feat(ionLabel): Add prop to specify 'for' value 

### ISSUE THREAD

**Issue by 0xRenshaw** [ionic-team/ionic-framework#25692]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

To be able to specify the 'for' on the ionLabel to have greater control over the field the ionLabel should target/focus. 

### Describe the Use Case

Enables the use of standard ionic form components and decouples the ionLabel from needing to be wrapped in an ionItem in order for the label to target the form field.

### Describe Alternatives

Alternatively, update all form components to pass the id to the shadow DOM element so they become targetable via the standard label element.

### Additional Information

I have been unable to find a suitable, scalable solution to this issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue. We have an alternative proposal here which should accomplish the same goal: https://github.com/ionic-team/ionic-framework/discussions/25661

Can you give this a look and let me know if it works for your use case?
