### ISSUE TITLE
bug: DateTime component modifies timezone

### ISSUE THREAD

**Issue by pvo13** [ionic-team/ionic-framework#25698]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [X] Nightly

### Current Behavior

I initialize the DateTime component with this example string "2022-07-31T12:00:00+01:00". So it contains timezone information. When I now change the date/time of the component, the change event gives me the updated value like this: "2022-07-31T13:00:00+02:00"

So the timezone has been changed from +01:00 to +02:00. 

### Expected Behavior

 I think the timezone should not be changed/touched by the component after it has been initialized.

### Steps to Reproduce

Initialize the DateTime component with an initial date. It actually doesn't matter if a timezone is set or not.
Now change the date or time via the component.
See the changed value that is delivered by the ionChange event. It contains timezone that is not related to the initial timezone setting. 

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.1-dev.11659121131.15481a1f
   @angular-devkit/build-angular : 14.1.0
   @angular-devkit/schematics    : 14.1.0
   @angular/cli                  : 14.1.0
   @ionic/angular-toolkit        : 7.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.16.0 (/usr/bin/node)
   npm    : 8.11.0
   OS     : Linux 5.4

**Comment by pvo13** [comment]
Oh sorry, this is a duplicate of #25577

**Comment by liamdebeasi** [comment]
Thanks for the report! Yep, looks like this is the same as https://github.com/ionic-team/ionic-framework/issues/25577. I am going to merge the two.
