### ISSUE TITLE
bug: Incorrect time displayed after selection in Datetime

### ISSUE THREAD

**Issue by pvo13** [ionic-team/ionic-framework#25693]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I use an ion-datetime component to select a date and time.

When I click on the current time to change it, scroll wheels appear and I can change the hour. If I do that, the selected value is being propagated back to the underlying component and displayed, but not the value I have chosen, but a different one. This offset in my case is two, it seems to depend on the browsers timezone.  So I choose 22 and the within the component the hour part shows 20
![ion-datetime_bug](https://user-images.githubusercontent.com/10052420/181810639-4d7000a7-501f-4b99-a6ee-e2d665d7e5d1.png)

### Expected Behavior

I expect the time that I select to be exactly to be the time I then see in the component.

### Steps to Reproduce

Open the ion-datetime description page and use one oft he examples that contain the time part, e.g. https://ionicframework.com/docs/api/datetime#showing-the-default-title

When I click on the current time to change it, scroll wheels appear and I can change the hour. If I do that, the selected value is being propagated back to the underlying component and displayed, but not the value I have chosen, but another one with an offset. The offset in my case is two, it seems to depend on the browsers timezone.  

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.0
   @angular-devkit/build-angular : 14.1.0
   @angular-devkit/schematics    : 14.1.0
   @angular/cli                  : 14.1.0
   @ionic/angular-toolkit        : 7.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.16.0 (/usr/bin/node)
   npm    : 8.11.0
   OS     : Linux 5.4

**Comment by sean-perkins** [comment]
@pvo13 thanks for reporting this issue! When formatting the text to be displayed, we are not accounting for the timezone offset that `toISOString()` performs. 

Can you test with this dev-build and let me know if you run into any issues?
```
6.2.1-dev.11659117540.13ffd984
```

Thanks!

**Comment by pvo13** [comment]
I tested it with 6.2.1-dev.11659121131.15481a1f
> Can you test with this dev-build and let me know if you run into any issues?
> 
> ```
> 6.2.1-dev.11659121131.15481a1f

This build works fine, issue seems to be resolved here. Thank you!

**Comment by sean-perkins** [comment]
Thanks for confirming! I'm going to keep the issue open until a PR is added to fix this in main. The issue will auto close when it is released in an upcoming patch release.
