### ISSUE TITLE
bug: ionic cap run android -l  opens android studio and fails to target the emulator. Same happens with iOS (x-code)

### ISSUE THREAD

**Issue by paulosllvn** [ionic-team/ionic-framework#25701]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

I cannot for the life of me figure out why my colleague cannot get live reload working on android or ios. I have had it working on android but trying to setup someone new has proven painful.

Running `ionic cap run android -l --external` simply opens up android studio or x-code and does not target the emulator/simulator. 

I have also tried `ionic cap run ios --livereload --external --host=0.0.0.0`

Running `ionic cap ios --list` does not list anything, it simply builds the project again and opens x-code

### Expected Behavior

Running this command should target the emulator and open the app in the emulator and reload once a change is made.

Running `ionic cap ios --list` should show available emulators

### Steps to Reproduce

Create an environment with similar as my ionic info

### Ionic Info

```
Ionic:
   Ionic CLI                     : 5.4.16 (C:\Users\user\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.6.0
   @angular-devkit/build-angular : 0.1102.19
   @angular-devkit/schematics    : 11.2.19
   @angular/cli                  : 11.2.19
   @ionic/angular-toolkit        : 3.1.1
Capacitor:
   Capacitor CLI   : 3.5.0
   @capacitor/core : 3.5.0
Cordova:
   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available
Utility:
   cordova-res : not installed
   native-run  : 1.5.0
System:
   NodeJS : v16.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework manages the UI layer of your app and does not manage the native dependencies of your application. As a result, it is unlikely that this error is coming from Ionic Framework.

This could be an issue with the Ionic CLI or Capacitor, however I do notice that the Ionic CLI you have installed is very outdated. Can you try this again using the latest version of the Ionic CLI?

```
npm uninstall -g ionic
npm install -g @ionic/cli
```
