### ISSUE TITLE
bug: caret color for inputs should only be applied on md mode

### ISSUE THREAD

**Issue by ekrapfl** [ionic-team/ionic-framework#25719]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

After upgrading to ionic 6, we noticed that our inputs (which are usually inside of an ion-item) end up with a colored caret like so:
![image](https://user-images.githubusercontent.com/5939413/182955298-c5b54b77-e2fa-47d4-a8b3-57b8928d7f01.png)

### Expected Behavior

The caret should match the color of the text.  Honestly, I can't think of any time I would ever want the cursor a different color from the text.

Using `caret-color: auto;` accomplishes this.  If you change the color of the text, the color of the caret changes with it.

### Steps to Reproduce

Go to https://ionicframework.com/docs/api/input
Open up the inspector
Start typing in one of the input fields
Notice that the caret color does not match the text color
This is made much worse if you have your input in a form and it is using the valid color (green by default)
![image](https://user-images.githubusercontent.com/5939413/182957706-f9e23a3c-c6b4-47f7-90aa-2723a595b446.png)

### Code Reproduction URL

https://ionicframework.com/docs/api/input

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1
   Ionic Framework               : @ionic/angular 6.2.1
   @angular-devkit/build-angular : 12.2.17
   @angular-devkit/schematics    : 12.2.17
   @angular/cli                  : 12.2.17
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : 3.4.1
   @capacitor/core    : 3.4.1
   @capacitor/ios     : 3.4.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.10.0 (/Users/krapfl/.nvm/versions/node/v16.10.0/bin/node)
   npm    : 7.24.0
   OS     : macOS Monterey

### Additional Information

Upon further inspection, it looks like the thought was to make the caret match the validity state:
![image](https://user-images.githubusercontent.com/5939413/182955069-8946bb07-42b7-49ff-8afa-ef9e2b3b5020.png)

![image](https://user-images.githubusercontent.com/5939413/182955187-1bd61b31-d2dc-406a-88de-8e6f85e65a04.png)

![image](https://user-images.githubusercontent.com/5939413/182955065-b3a9b416-1ca6-4f42-bb8f-0631d1485dec.png)

Looks like the change was introduced in this commit: https://github.com/ionic-team/ionic-framework/commit/5ca2ce91971408218d7bdc52509ce61a6ebb46aa

But again, why not let the cursor match whatever the text color is?  Isn't that the best way to ensure that users don't get a funky color when they don't expect it?

Fwiw, I was able to work around the issue with a global css rule like so:
```css
ion-item::part(native) {
  caret-color: auto;
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. It looks like this was added to try and match https://material.io/components/text-fields#usage. However, this probably should only show up in MD mode.

**Comment by ekrapfl** [comment]
That seems to make sense.  I didn't realize that MD does that now.  Can't say that I find it attractive, personally, but I'll settle for the caret remaining the text color in iOS mode ;)

Thanks for the quick response!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25725, and a fix will be available in an upcoming release of Ionic Framework.
