### ISSUE TITLE
bug: wheel picker month/day order should account for locale

### ISSUE THREAD

**Issue by BurkusCat** [ionic-team/ionic-framework#25722]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The ion-datepicker when using `preferWheel` uses an American date format with the month first. Changing the locale of the picker doesn't fix this. It should be possible to have the following formats:
- Day/month/year
- Year/month/day

![image](https://user-images.githubusercontent.com/7528322/183075096-fd3d37f0-bf86-4fd3-b3b8-46a150787125.png)

### Expected Behavior

Locale should change the order of the columns. Or there should be a separate property that also allows setting the year first.

### Steps to Reproduce

1. Add an ion-datepicker with [preferWheel] and Locale en-GB
2. Open it and observe the wrong order of columns for this locale

### Ionic Info

``` bash
$ ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.0
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Here is a dev build with a fix if you would like to test:

```
6.2.2-dev.11659710120.1586c47e
```

**Comment by BurkusCat** [comment]
Wow, that was fast! 🤯 Thank you @liamdebeasi it is looking great!

![image](https://user-images.githubusercontent.com/7528322/183108725-232e4c57-6423-4547-9cbd-0bfa5de8d926.png)

Initially, after installing the package it did not fix the issue. This is because the wrong package was installed into the `@ionic/angular` node modules. Is there a way to install these packages better in the future (I just copy and pasted the one that did install correctly to the `@ionic/angular` node modules which worked)
![image](https://user-images.githubusercontent.com/7528322/183109002-2ef3e6fe-7d1a-4e4c-84aa-99b80a60d133.png)

**Comment by liamdebeasi** [comment]
It depends on the project setup. Installing `@ionic/angular@6.2.2-dev.11659710120.1586c47e` should also install `@ionic/core@6.2.2-dev.11659710120.1586c47e` unless you have `@ionic/core` explicitly installed (which apps generally should not have). The exception here is if you are using a StackBlitz starter app. There are some issues with version caching in non-web container setups that we are trying to better understand.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25726, and a fix will be available in an upcoming release of Ionic Framework.
