### ISSUE TITLE
bug: ion-datepicker [preferWheel] range only goes back 100 years

### ISSUE THREAD

**Issue by BurkusCat** [ionic-team/ionic-framework#25724]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The ion-datepicker only allows dates being selected up until 100 years ago (1922).

### Expected Behavior

Ideally, the picker should allow selection of years from 1900 onwards to facilitate date of birth entry for people over 100 years old (13k+ people in the UK).

### Steps to Reproduce

1. Create an ion-datepicker with [preferWheel]
2. Scroll back to the earliest year possible

### Ionic Info

``` bash
$ ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.0
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This is the intended behavior and is mentioned in our documentation: https://ionicframework.com/docs/api/datetime#min

> The minimum datetime allowed. Value must be a date string following the [ISO 8601 datetime format standard](https://www.w3.org/TR/NOTE-datetime), such as 1996-12-19. The format does not have to be specific to an exact datetime. For example, the minimum could just be the year, such as 1994. Defaults to the beginning of the year, 100 years ago from today.

You can customize this by setting the `min` date in your application:

```html
<ion-datetime min="01-01-1900"></ion-datetime>
```

That being said, we do not recommend using date pickers for selecting birthdays due to the amount of scrolling/selection that it requires. (For context, even Google does not recommend doing this: https://material.io/components/date-pickers#mobile-pickers)

**Comment by BurkusCat** [comment]
Thanks @liamdebeasi ! `min="01-01-1900"` did not work for me but `min="1900"` did.

RE: birthdays and datepickers. I think Google's advice only applies to the Calendar picker which is best for recent or near future dates. The spinner/wheel picker is a lot better for specific dates in the past.
