### ISSUE TITLE
bug: FileReader onloadend works on browser but not in mobile

### ISSUE THREAD

**Issue by almaz1213** [ionic-team/ionic-framework#25734]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

FileReader onloadend works on browser but not in mobile

### Expected Behavior

should work as in browser

### Steps to Reproduce

```
....
download() {
      let r = new FileReader();
        r.onloadend = () => {
          console.error('it never happens on ionic android app');
          this.c.saveImg(this.c.sideDialogs[this.dialogKey].title + '.png', null, r.result as string, res => {
            try {
              this.c.msg(res.uri)
            } catch (e) {
              this.c.err(res)
            }
          })
        }
        r.readAsDataURL(this.qrImgBlob);
....
```

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /home/diamo/.nvm/versions/node/v16.15.1/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/diamo/.nvm/versions/node/v16.15.1/lib/node_modules/@ionic/cli/lib/index.js
       - /home/diamo/.nvm/versions/node/v16.15.1/lib/node_modules/@ionic/cli/index.js
       - /home/diamo/.nvm/versions/node/v16.15.1/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.20.1 (/home/diamo/.nvm/versions/node/v16.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.12
   @angular-devkit/build-angular : 14.0.3
   @angular-devkit/schematics    : 14.0.3
   @angular/cli                  : 14.0.3
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : 3.6.0
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.15.1 (/home/diamo/.nvm/versions/node/v16.15.1/bin/node)
   npm    : 8.13.1
   OS     : Linux 5.4

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework does not manage any native dependencies, so it is unlikely that Ionic is causing this issue. I am going to close this, but I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/) for assistance with this issue.

**Comment by almaz1213** [comment]
There is the same question in the Ionic Forums, but no answers. it seems to connected to zone.js of angular that includede in ionic. So, it's likely issue releted to ionic release. Please, check it more deep
