### ISSUE TITLE
bug: ion-modal is not prerendered

### ISSUE THREAD

**Issue by Tvde1** [ionic-team/ionic-framework#25739]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I created a blank app, added prerendering and added the following modal:
```html
<ion-modal [isOpen]="true">
  <ng-template>
    <ion-header>
      <ion-toolbar>
        <ion-title>Modal</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content class="ion-padding">
      <p>
        Unfortunately this modal is not prerendered.
      </p>
    </ion-content>
  </ng-template>
</ion-modal>
```
When running the SPA, the modal opens instantly. However when the MRE is prerendered, the resulting html file contains:
```
...<ion-modal _ngcontent-sc143=""><!----></ion-modal>...
```
Which doesn't contain the content.

### Expected Behavior

I expect the prerendered HTML files to contain the modal content and also have it displayed.

### Steps to Reproduce

The repository with a brand new project is located here: https://github.com/Tvde1/modal-prerender-bug

<details>
  <summary>Click to see the steps to create the project.</summary>

### 1. Create the project
```sh
npx ionic start modalprerender blank --type angular
cd modalprerender
npm install @angular/animations
ng add @nguniversal/express-engine
npm install @ionic/angular-server
```
### 2. Enable Ionic SSR
And updating `app.server.module.ts` with:
```diff
import { NgModule } from '@angular/core';
import { ServerModule } from '@angular/platform-server';

import { AppModule } from './app.module';
import { AppComponent } from './app.component';

+import { IonicServerModule } from '@ionic/angular-server';

@NgModule({
  imports: [
    AppModule,
    ServerModule,
+   IonicServerModule
  ],
  bootstrap: [AppComponent],
})
export class AppServerModule {}
```
### 3. Run
Build & serve the application with:
```sh
npm run prerender
```
</details>

### Code Reproduction URL

https://github.com/Tvde1/modal-prerender-bug

### Ionic Info
<details>
  <summary>Click to see the `npx ionic info` output.</summary>

```
pwsh> npx ionic info
Ionic:

   Ionic CLI                     : 6.20.1 (C:\Users\[hidden]\AppData\Roaming\nvm\v16.16.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.1
   @angular-devkit/build-angular : 14.1.1
   @angular-devkit/schematics    : 14.1.1
   @angular/cli                  : 14.1.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.13.2
   OS     : Windows 10
```

</details>

### Additional Information

Possibly related to #24714? Though this shows no errors in the console.

**Comment by sean-perkins** [comment]
@Tvde1 thanks for this issue. Can you try with the `keepContentsMounted` option enabled and let me know if the problem persists?

e.g.:
```html
<ion-modal [keepContentsMounted]="true" [isOpen]="true">
 <!-- Existing content --> 
</ion-modal>
```

**Comment by Tvde1** [comment]
That did the job! I thought I tried it but apparently not. Thanks for the swift response!
