### ISSUE TITLE
 [ion-datetime] / ionic 6.2.2 / capacitor 4 - weird flickering on ios 

### ISSUE THREAD

**Issue by ciccilleju** [ionic-team/ionic-framework#25757]
Hello,
i’ve faced a weird issue using iOS (both on simulator and real device, Android and Web work fine)

If I open the datetime popover and i drag it from left to right for changing the current displayed month, it starts going back and forth from the current month to the next month (ex. august and september)

Here you can see the video.

[VIDEO](https://www.dropbox.com/s/vde64mt2vem5hqt/flickering%20-%20datetime.mov?dl=0)

this is my ionic info output:
`Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.2
   @angular-devkit/build-angular : 14.0.7
   @angular-devkit/schematics    : 14.1.2
   @angular/cli                  : 14.1.2
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : 4.0.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v14.18.3 (/usr/local/bin/node)
   npm    : 8.13.1
   OS     : macOS Monterey`

thank you!

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionic-framework/issues/25752.

**Comment by ciccilleju** [comment]
thank you!
