### ISSUE TITLE
bug: Different color on ion-datetime when inside ion-modal and ion-content with scroll-y="false"

### ISSUE THREAD

**Issue by raksakaindra** [ionic-team/ionic-framework#25755]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When implement ```ion-datetime``` inside ```ion-modal``` and ```ion-content``` with ```scroll-y="false"```, the color of all month-year presentation is same. The issue happened on Safari when dev with Responsive Design Mode (iOS 14.0-iPhone) and same condition on real device iPhone X iOS 15.6.

Here is the code:
```
  <ion-modal id="date-modal-log" trigger="open-modal-log">
    <ion-content scroll-y="false">
      <ion-toolbar class="modal">
        <ion-title>Pilih Periode</ion-title>
      </ion-toolbar>
      <ion-datetime
        locale="id-ID"
        max="2022-08"
        presentation="month-year"
        ref="datetime"
        v-model="resp.dateSelected"
      >
        <ion-buttons slot="buttons">
          <ion-button color="danger" fill="clear" @click="cancel"
            >Batal</ion-button
          >
          <ion-button color="hijau" fill="outline" type="submit" @click="today"
            >Hari Ini</ion-button
          >
          <ion-button color="hijau" fill="solid" type="submit" @click="confirm"
            >Cari</ion-button
          >
        </ion-buttons>
      </ion-datetime>
    </ion-content>
  </ion-modal>
```
The result:
<img width="351" alt="Bug datetime" src="https://user-images.githubusercontent.com/1322744/184349322-a64bf211-7081-4fa4-9bf7-a1128bf01b18.png">

### Expected Behavior

```ion-datetime``` should be same color with ```ion-content scroll-y="true"``` inside the ```ion-modal```

### Steps to Reproduce

If I implement it on ```ion-modal``` and ```ion-content``` with ```scroll-y="true"``` or without parameter, the color are normal and same with Ionic documentation.
<img width="351" alt="Normal condition" src="https://user-images.githubusercontent.com/1322744/184349744-08801301-b35f-4bfd-81b2-06aa6af2485d.png">

### Ionic Info

Ionic:
   Ionic CLI       : 6.20.1 (/Users/bmkg/.nvm/versions/node/v16.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.2.2

Capacitor:
   Capacitor CLI      : 3.7.0
   @capacitor/android : 3.7.0
   @capacitor/core    : 3.7.0
   @capacitor/ios     : 3.7.0

Utility:
   cordova-res : 0.15.4
   native-run  : 1.6.0

System:
   NodeJS : v16.16.0 (/Users/bmkg/.nvm/versions/node/v16.16.0/bin/node)
   npm    : 8.16.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25756, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by raksakaindra** [comment]
@liamdebeasi Thanks and great job!
