### ISSUE TITLE
bug: datetime, ios, looping between months when minimum date is set

### ISSUE THREAD

**Issue by luqasmateus** [ionic-team/ionic-framework#25752]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Changing the selected month causes the component to loop between two months indefinitely, but only if a minimum date is set. This problem happens on iOS. I tested on iOS 14.6 (real device) and on iOS 15.0 (emulator).

### Expected Behavior

The user should be able to select a date after the set minimum without any problems.

### Steps to Reproduce

Add an ion-datetime and set a minimum date:

    <ion-datetime min="2022-08-11"></ion-datetime>

On the app, click on one of the arrows or swipe to change the selected month. The bug happens when entering/leaving the month set in the min value (in the example above, when selecting or deselecting August).

### Code Reproduction URL

https://github.com/luqasmateus/ion-datetime-jumping-months

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.2.2
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 13.3.9
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 3 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.6.0

System:

   ios-sim : 8.0.2
   NodeJS  : v16.15.0 (/usr/local/bin/node)
   npm     : 8.5.5
   OS      : macOS Monterey
   Xcode   : Xcode 13.0 Build version 13A233

**Comment by sagun-gautam** [comment]
Faced the same issue in iOS today, set min date and click previous or next arrow for month navigation. Loops between current month and previous/next month.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I can reproduce this behavior. Let me take a closer look and see what is going on.

**Comment by sagun-gautam** [comment]
@liamdebeasi with **ionic 6.2.3** this issue wont occur when navigating using the next arrow, but occurs when you touch swipe to next month from the month set in the min value.

**Comment by IhorHolovatsky** [comment]
It's affecting us too,
`ionic 6.2.2`, same bug as @sagun-gautam described. 
Reproducable only on IOS, and only when swiping between months (when min value is set)

**Comment by derickfelix** [comment]
the same is happening to me

`"@ionic/angular": "^6.1.9"`

Not only that but on android browser months are being skipped when using the arrows.

**Comment by liamdebeasi** [comment]
Can everyone try the following dev build and let me know if it resolves the issue?

```
6.2.5-dev.11661888592.1e9d3972
```

Example:

```
npm install @ionic/angular@6.2.5-dev.11661888592.1e9d3972
```

**Comment by ciccilleju** [comment]
Sure Liam, tomorrow as soon as I will be in my studio I will try it.
Thank you for your help

Il Mar 30 Ago 2022, 21:48 Liam DeBeasi ***@***.***> ha
scritto:

**Comment by luqasmateus** [comment]
It works for me. Thank you!

**Comment by ciccilleju** [comment]
I can confirm: it works now on iOS real devices and simulator

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25857, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by TiBz0u** [comment]
Hi, 
I can reproduce it too on iOS 15.0 (iPhone 6S) on the documentation page.
However, on my application (@ionic/angular ^6.1.12), it seems that if a default value is defined on ion-datetime, the loop stop by itself (only a quick visual glitch) => less impact.

Thanks @liamdebeasi for the fix :)
