### ISSUE TITLE
bug: Ionic changes are not being captured in safari dev inspector

### ISSUE THREAD

**Issue by pedrumgolriz** [ionic-team/ionic-framework#25761]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Safari developer tools scripts and elements no longer up to date after live reload renders changes.
Each time I make a code change, I have to close my current web inspector and reopen it to see the changes. Breakpoints will not trigger and the dom isn't searchable.

I have tried in safari + safari developer preview (both up to date, no success)

### Expected Behavior

Safari should be able to break on breakpoints without reopening dev tools.

### Steps to Reproduce

Run a project in capacitor iOS
Make any code change in html or js and see you can no longer break on breakpoints or see any rendered dom elements.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.0
   @angular-devkit/build-angular : 14.1.0
   @angular-devkit/schematics    : 14.1.0
   @angular/cli                  : 14.1.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.0
   @capacitor/android : 4.0.0
   @capacitor/core    : 4.0.0
   @capacitor/ios     : 4.0.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v14.19.3 (/usr/local/bin/node)
   npm    : 6.14.17
   OS     : macOS Monterey

### Additional Information

This might be a capacitor bug, so I am unsure where to post this. This could also be a safari bug. But I have only had this behavior in the lasest ionic/capacitor builds. When using older capacitor builds or Cordova builds, everything worked as expected.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework does not handle live reloads, so I am not sure this is a bug in Ionic.

Did this issue start with a particular Ionic or Capacitor version?

**Comment by pedrumgolriz** [comment]
As it turns out, this is not only happening during a live reload. If I refresh the page during a build the same issue occurs. I am unable to trigger breakpoints and the dom is unsearchable until dev tools is reopened

**Comment by liamdebeasi** [comment]
Is there a way I can reproduce this issue? A minimal GitHub repo that I can clone and run is best.

**Comment by pedrumgolriz** [comment]
This seems to be a bug with MacOS 12.4. Upgrading to 12.5 has fixed the issue.
