### ISSUE TITLE
feat: <IonDatetime> button position, or allow developers to control the datetime to require confirmation before triggering update

### ISSUE THREAD

**Issue by puopg** [ionic-team/ionic-framework#25777]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I like how the date picker when buttons are shown, requires confirmation before triggering the update, which enables a user to interact with the calendar, but unless triggering confirm, no update will actually happen.

However, this requires buttons to be enabled or exist. And positioning the buttons above for example is pretty simple, those can be rendered independently from the Ion-datetime, but you either get updates always now that there are no buttons, or you can trick the ion-datetime to think there are buttons but it still renders the padding around an empty element, which visually looks wrong.

![Screen Shot 2022-08-17 at 12 25 57 PM](https://user-images.githubusercontent.com/7741481/185225701-b9b2d3d5-4584-42c1-bb44-fc61ba27fe67.png)

(I guess there is prolly a way to simply make it so that updates are ignored from the developer's side, until some other trigger is made and interact directly with the instance of ion-datetime to do so.)

But I want to propose a request, would it make sense to adjust updating and controls to work like:
- If the ion-datetime is rendering its default buttons, then treat things they way they work today. Only emit updates on confirm.
- If the ion-datetime is rendering a slotted button, also treat it the same way today
- But, if the developer wants full control around updates, maybe provide a prop called `requireConfirmation`
    - if `true`, events are only emit on confirm
    - if `false`, events are always emit, regardless of buttons being rendered or not
    - if `undefined`, the current behavior is good.

So this moves the component to operate under some typical defaults as it does today, but allows developers the option to show buttons and trigger updates always (for whatever reason). Or, show no buttons, but updates are triggered by the developer manually using the imperative API.

### Describe the Use Case

Use case is to allow a developer total control over the rendering of confirmation buttons for date picking, by separating the announcement of updates from the visibility of buttons as a result of some blend of configuration. Instead, providing an explicit control prop around when updates should be announced.

### Describe Preferred Solution

Something maybe like:

```
<button onClick={() => { this.ionDatetime.confirm() }}>Confirm</button>
<IonDatetime ref={this.ionDatetime} requireConfirmation />
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. One of the requirements of the datetime buttons is that they visually render within the datetime container so that it is clear that the buttons are associated with the datetime. Moving the buttons outside of the container risks creating a disconnect between the buttons and the datetime that the buttons control.

I think it might be better to create a custom component for this use case. For example, you can create a component that wraps `ion-datetime` and your custom buttons. Clicking the custom confirm button would emit an event from the component with the value of the datetime. Have you tried that approach in your app?

**Comment by puopg** [comment]
Yea thats pretty much what I did, but something that I ran into is when those buttons are clicked, there is a change event that is triggered and the value of which is `""`. Iono if its like a blur kinda thing, since I know I see a hidden input in the DOM inside of the ion-datetime?

Anyways, the way I worked around it is by just tracking changes that have a value, and then when I trigger my click, I commit a change using the last seen value from IonDatetime. So it works, but feels more like a workaround. 

Maybe I should just read the value of the ionDatetime (which if possible, I havent tried or know how to do haha)? Then I don't need to listen to ion events at all, just let it change, and read it when needed?

**Comment by liamdebeasi** [comment]
> Yea thats pretty much what I did, but something that I ran into is when those buttons are clicked, there is a change event that is triggered and the value of which is "". Iono if its like a blur kinda thing, since I know I see a hidden input in the DOM inside of the ion-datetime?

It is hard to say where that is coming from without being able to reproduce the behavior myself. However, the hidden input is there so that the value of `ion-datetime` is submitted along with other form data.

> Maybe I should just read the value of the ionDatetime (which if possible, I havent tried or know how to do haha)? Then I don't need to listen to ion events at all, just let it change, and read it when needed?

You can read the value of `ion-datetime` by getting a reference to the element and accessing the `value` prop. That should give you the most flexibility in terms of when to emit a change event from your custom component.

**Comment by puopg** [comment]
Awesome, I can close this feature request then, as reading the value prop, basically allows me to build whatever version of this that I need. Thanks!
