### ISSUE TITLE
bug: Setting ion-datetime value does not update selected day

### ISSUE THREAD

**Issue by aktivdigital-frontend** [ionic-team/ionic-framework#25776]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [X] Nightly

### Current Behavior

When setting the value of an `ion-datetime` in a `setTimeout`, the display date updates, but after opening the datetime, the selected day does not display.

### Expected Behavior

After setting the value of a `ion-datetime`, the selected day should also update.

### Steps to Reproduce

1. Have an `ion-datetime` (example uses `ion-datetime-button`)
2. Update the value after a few seconds
3. Open the date picker
4. Observe: The new value does not show as the selected day
5. Expected: The new value would display as the highlighted/selected day

### Code Reproduction URL

https://stackblitz.com/edit/angular-ramjpp?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

### Ionic Info

N/A

**Comment by sean-perkins** [comment]
@aktivdigital-frontend thanks for reporting this issue. I am seeing the same behavior as well. 

The datetime has internal logic that requires the date be active & that we should highlight the day:
https://github.com/ionic-team/ionic-framework/blob/436a8ce50847d26f8fb63ce64ea85be6f5c0bc8e/core/src/components/datetime/datetime.tsx#L1927

`highlightActiveParts` is unfortunately never set when the value is dynamically changed, so the day will never show as selected unless the user manually taps the day again.

**Comment by liamdebeasi** [comment]
@aktivdigital-frontend Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.2.10-dev.11664900496.1d961808
```

Note: You may need to install this in a local Ionic app. StackBlitz sometimes has issues installing dev builds of Ionic.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26070, and a fix will be available in an upcoming release of Ionic Framework. Feel free to continue testing the dev build and let me know if you run into any issues.

**Comment by charlesj1** [comment]
Should this problem be fixed now? When I update the above StackBlitz to 6.3.2, I get the same issue...
[https://stackblitz.com/edit/angular-ramjpp-squwwg?file=src%2Fapp%2Fapp.component.ts,package.json](url)

**Comment by aktivdigital-frontend** [comment]
@liamdebeasi Highlight is OK, thanks, but the picker show the current month, not the set month. This issue is only partially finished.

**Comment by jonathan-chin** [comment]
I'm experiencing the same issue. initially on 6.1.9 and again trying 6.3.6

**Comment by sean-perkins** [comment]
Please open a new issue with a reproduction if you are experiencing an issue on a closed issue.

The original reported issue with highlighting the active day when the value changes is working as expected in 6.3.6: https://stackblitz.com/edit/angular-qfjs5s

The issue discussed by @aktivdigital-frontend appears to be a different problem, where `preferWheel` does not set the position to the active value: https://stackblitz.com/edit/angular-qfjs5s-bm5rpn
