### ISSUE TITLE
Bug: Swipe back doesn't work on iOS

### ISSUE THREAD

**Issue by ollydixon** [ionic-team/ionic-framework#25781]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

Created a basic Svelte app, going though Ionic. On Safari browser Swipe back works fine. On WebView via default iOS app it works. On Ionic it doesn't work.

### Expected Behavior

Swipe back on iOS should work by default, no matter what is rendering via the platform.

### Steps to Reproduce

Make Ionic app.
Host HTML app with a link.
Observe that swipe back doesn't work.

### Ionic Info

```
Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.15.1
   npm    : 8.11.0
   OS     : macOS Monterey
```

**Comment by ollydixon** [comment]
https://github.com/ollydixon/svelte-cap-testing

Look at package.json for the run commands.

Also, we don't want to use ionic components as it will be a website as well.

**Comment by ollydixon** [comment]
@liamdebeasi I provided a basic app. Note that we are not using Ionic special elements as we don’t want to pollute the main web app.

**Comment by liamdebeasi** [comment]
I'm not sure I understand what the bug is here. Are you trying to use Ionic's swipe back gesture on `ion-router-outlet` or `ion-nav`? Or are you trying to use the swipe back gesture that is built into iOS?

**Comment by ollydixon** [comment]
@liamdebeasi we are not using "ion" components as we don't want to pollute the main web app as mentioned above. You asked for a reproduction so I provided one, if you run it and try to swipe back on the iOS emulator you can see that it doesn't work; that's the bug. Super basic functionality that doesn't work...

**Comment by liamdebeasi** [comment]
I think there may be a misunderstanding here. This is the repo for Ionic Framework, which is an optional UI toolkit that you can use with Capacitor. Your application does not use Ionic Framework, so this is not the correct repo for this bug report.

I think you may want the [Capacitor repo](https://github.com/ionic-team/capacitor) instead. However, I do know that Capacitor disables the swipe to go back gesture on WKWebView. The built-in swipe to go back gesture tends to interfere with any custom gesture logic that developers may have added to their applications which is why it is disabled. If you are looking for a way to re-enable it or you have more questions about Capacitor you will probably have more luck [creating a new discussion on the Capacitor repo](https://github.com/ionic-team/capacitor/discussions).

**Comment by ollydixon** [comment]
@liamdebeasi aaaah great thanks

**Comment by Steven0351** [comment]
@ollydixon you should be able to achieve what you want with an approach similar to this: https://github.com/ionic-team/capacitor/issues/1097#issuecomment-1077649377

**Comment by ollydixon** [comment]
@Steven0351 awesome thanks, I implement this with "svelte-navigator" but it doesn't seem to work; any ideas?

**Comment by Steven0351** [comment]
@ollydixon Did you also follow the [documentation](https://capacitorjs.com/docs/ios/viewcontroller#edit-mainstoryboard) linked in that comment as well?

**Comment by ollydixon** [comment]
@Steven0351 yeah, I switched it too a custom view controller and added ```webView!.allowsBackForwardNavigationGestures = true```, all out of ideas now 🙈

**Comment by Steven0351** [comment]
@ollydixon I was able to clone your [repo](https://github.com/ollydixon/svelte-cap-testing], make the necessary changes, and got backward and forward swiping to work (starts at about 6 seconds in):

https://user-images.githubusercontent.com/24440751/185662611-fd08d5ea-4f1b-4faa-bff0-b5104751cdea.mp4

Not sure if you're testing on a device or simulator, but the simulator is finicky and your mouse cursor needs to be _exactly_ on the edge that you're swiping from.

**Comment by ollydixon** [comment]
@Steven0351 Ah yes it was the simulator, thank you so much for your help!

**Comment by ollydixon** [comment]
@Steven0351 do you have ideas on how we could implement a forward animation?

**Comment by Steven0351** [comment]
@ollydixon not something you could do natively, you’d have to implement it in CSS. That’s what ionic framework does.

**Comment by ollydixon** [comment]
@Steven0351 thanks, ah well that's a shame. We had a few Ionic apps a while ago but there were janky/buggy. The web versions were broken cause of the special tags 🙈. Maybe it's gotten better, but Svelte -> React 😎
