### ISSUE TITLE
bug: month/year picker is not closed when datetime is dismissed

### ISSUE THREAD

**Issue by tirooo** [ionic-team/ionic-framework#25787]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I use "ion-datetime-button" to select date , but I discover  when i open modal and go to "Month and Year Selection"  then close modal.
when i open modal again and back to "Date Selection". At this time when i select day but month will change(Change to last month)

### Expected Behavior

Modify the corresponding data

### Steps to Reproduce

1：click ion-datetime-button to open modal box
2：go to "year-month selection" Interface
3：click backdrop  to close modal
4：click ion-datetime-button to open modal box again
5：go to "date selection" Interface
6： select any day， at this time month will be changed

### Related code
```
<ion-datetime-button datetime="datetime"></ion-datetime-button>

<ion-modal [keepContentsMounted]="true">
  <ng-template>
    <ion-datetime id="datetime"></ion-datetime>
  </ng-template>
</ion-modal>
```
### Ionic Info

 Ionic CLI                     : 6.20.1 (C:\Users\****\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.2
   @angular-devkit/build-angular : 14.0.6
   @angular-devkit/schematics    : 14.0.6
   @angular/cli                  : 14.0.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.7.0
   @capacitor/android : 3.7.0
   @capacitor/core    : 3.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v14.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.9
   OS     : Windows 10

### Additional Information

My English is not good. I try my best to express myself

**Comment by liamdebeasi** [comment]
Thanks for the issue. Here is a dev build with a proposed fix for the issue if you are interested in testing:

```
npm install @ionic/angular@6.2.4-dev.11660920030.163a18e7
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25789, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue to test the dev build.
