### ISSUE TITLE
bug: Refresher throws an exception in React/Vue on load

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#25782]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The Refresher component throws an exception in the console when it loads, preventing the component from being usable. 

![An error from IonRefresher](https://github.com/jameson-w-taylor/vue-refresher-error/raw/main/documentation/images/refresher_error.png)

### Expected Behavior

The refresher should not throw any exceptions on load and should be interactive. 

### Steps to Reproduce

1. Include `ion-refresher` in React/Vue template
2. Observe: Exception is thrown when component loads

### Code Reproduction URL

https://github.com/jameson-w-taylor/vue-refresher-error

### Ionic Info

N/A

**Comment by sean-perkins** [comment]
Dev-build to resolve this issue: `6.2.4-dev.11660836281.1a11712b`.

You can also downgrade to 6.2.2 in the interim. This bug only effects 6.2.3.

**Comment by Janaka-Steph** [comment]
> Dev-build to resolve this issue: `6.2.4-dev.11660836281.1a11712b`.
> 
> You can also downgrade to 6.2.2 in the interim. This bug only effects 6.2.3.

@sean-perkins Not related to this issue but trying `6.2.2` and `6.2.4-nightly.20220822` I have a new issue where `useIonViewWillEnter` is not executed...

**Comment by sean-perkins** [comment]
@Janaka-Steph can you open a new issue with a reproduction so we can take a look?

**Comment by milanharia** [comment]
@sean-perkins seems like there is an issue with the refreshers on pages with `IonContent` fullscreen which have a color. 


https://user-images.githubusercontent.com/76167627/185972771-4a341a7e-4ce7-46be-b420-7192866ef191.mp4

Code to reproduce this issue:

```
const Tab1: React.FC = () => {
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab 1</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent color="warning" fullscreen>
        <IonHeader collapse="condense">
          <IonToolbar color="warning">
            <IonTitle size="large">Tab 1</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonRefresher slot="fixed" onIonRefresh={doRefresh}>
          <IonRefresherContent></IonRefresherContent>
        </IonRefresher>
        <div className="center">
          <h1>Tab 1</h1>
        </div>
      </IonContent>
    </IonPage>
  );
};
```

**Comment by sean-perkins** [comment]
@milanharia can you open a new issue with your expected behavior and a reproduction repository? This issue is focused on the exception that is currently thrown in React/Vue applications. This issue will automatically close when the associated PR is merged.
