### ISSUE TITLE
如何将现有的ionic项目打包为web端？

### ISSUE THREAD

**Issue by AugTang** [ionic-team/ionic-framework#25795]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

已开发的ios/android项目，使用什么命令转换为web端。

### Describe the Use Case

已开发的ios/android项目，使用什么命令转换为web端。

**Comment by liamdebeasi** [comment]
Hi there,

Ionic Framework is built with web technology, so there is no additional command needed to output an Ionic project for a web browser other than `ionic build`. The iOS, Android, and Web app bundles you generate all use the same codebase. 

If you need additional help building your Ionic app, I recommend posting on the [Ionic Forums](https://forum.ionicframework.com). Thanks!
