### ISSUE TITLE
bug(icon): validation method does not properly check attributes starting with 'on'

### ISSUE THREAD

**Issue by dauriamarco** [ionic-team/ionic-framework#25830]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I found a bug related to the icon sanitize method that could affect the security of the component.

Basically, in the isValid method, where you should check that no attribute starts with on, what actually happens is that the value is checked and not the name of the attribute itself. In this way, as shown below, you could render an icon that on click triggers a function:

![image](https://user-images.githubusercontent.com/101181211/186775791-01f68d2d-39d7-4810-938e-ef2fcbfd2e45.png)

I would also suggest, as you can see from the image above, to add two new icons to show in the "Sanitized (shouldn't show)" and "Not Sanitized (should show)" sections (e.g. sanitize-attr.svg and no-sanitize-attr.svg).

I've already opened an issue in the ion-icon repo: [https://github.com/ionic-team/ionicons/issues/1088](https://github.com/ionic-team/ionicons/issues/1088).
There is also a PR to fix the problem: [https://github.com/ionic-team/ionicons/pull/1087](https://github.com/ionic-team/ionicons/pull/1087).

### Expected Behavior

The validation method should properly check attributes starting with 'on' on the icons.

### Steps to Reproduce

Add to an `svg` any attribute starting with 'on' (e.g. 'onclick').

### Ionic Info

Ionic:

Ionic CLI : 6.19.0
Ionic Framework : @ionic/react 6.2.3-dev.11660337759.18ea0f7e

Capacitor:

Capacitor CLI : 1.3.0
@capacitor/android : not installed
@capacitor/core : 1.3.0
@capacitor/ios : not installed

Utility:

cordova-res : not installed globally
native-run : not installed globally

System:

NodeJS : v14.18.2
npm : 6.14.15
OS : macOS BigSur

**Comment by liamdebeasi** [comment]
Thank you for the issue, and apologies for not replying to your other report sooner. Yes, I can confirm that we should be checking name instead of value. Given an example of onclick="alert('abc')", the sanitizer would look at the value alert('abc') instead of onclick which is what it should be doing.

**Comment by dauriamarco** [comment]
No worries, no need to apologize. I didn't imagine that you would actually check for the value and not the name of the attribute; it seems a bit strange to me to have this approach, since you could inject functions even if `sanitize = true` and the comment on the `@Prop() sanitize` reads like this:

```js
/**
 * When set to `false`, SVG content that is HTTP fetched will not be checked
 * if the response SVG content has any `<script>` elements, or any attributes
 * that start with `on`, such as `onclick`.
 * @default true
 */
@Prop() sanitize = true;
```

Thank you very much for your response.

**Comment by liamdebeasi** [comment]
Ionic Framework now installs Ionicons 6.0.3 or newer (within version 6.x). An update will go out in the next release of Ionic Framework that will upgrade all apps to Ionicons 6.0.3 or newer.

Developers can get Ionicons 6.0.3 right now by explicitly installing `ionicons@6.0.3` in their project.

Thanks again for the report and fix! I am going to close this as the issue has been resolved.

**Comment by dauriamarco** [comment]
Thank you very much! ❤️
