### ISSUE TITLE
bug: useIonRouter doesn't use animation on replace

### ISSUE THREAD

**Issue by dkern** [ionic-team/ionic-framework#25831]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using `replace` on `ionRouter` no animation is used. Wherever using `push` and a custom animation works fine. When adding a `console.log` inside the custom animation, it seems that the function is not even called on `replace`.

### Expected Behavior

As seen in the [documentation](https://ionicframework.com/docs/vue/navigation#navigating-using-useionrouter), even replace should use custom animations. Also, the definition file shows that `replace` uses a custom animation:

```ts
export interface UseIonRouterResult {
    // ...
    push: (location: any, routerAnimation?: AnimationBuilder) => void;
    replace: (location: any, routerAnimation?: AnimationBuilder) => void;
    // ...
}
```

### Steps to Reproduce

```ts
import { useIonRouter, createAnimation } from '@ionic/vue';

// ...

setup() {
    const ionRouter = useIonRouter();

    const customAnimation = (baseEl: any, opts?: any) => {
        return createAnimation()
            .addElement(baseEl)
            .duration(2500)
            .fromTo('opacity', '1', '0');
    };

    ionRouter.replace('/route', customAnimation);
}
```

### Code Reproduction URL

https://github.com/dkern/router-bug

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.1 (C:\Users\daker\AppData\Roaming\nvm\v14.17.0\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.2.4

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Do you have a GitHub repo that I can use to verify this behavior?

**Comment by dkern** [comment]
> Thanks for the issue. Do you have a GitHub repo that I can use to verify this behavior?

I made one now.
https://github.com/dkern/router-bug

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build, and let me know if it resolves the issue? 

```
npm install @ionic/vue@6.2.5-dev.11661955528.139d8be6 @ionic/vue-router@6.2.5-dev.11661955528.139d8be6
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25863, and a fix will be available in an upcoming release of Ionic Framework.
