### ISSUE TITLE
bug: ion-icon do not load icon if pnpm is used

### ISSUE THREAD

**Issue by eduboxgithub** [ionic-team/ionic-framework#25846]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

If **npm** is used and ion-icon refer to a ion-icon name the svg icon loads correctly.

In this example a ion-icon is used and the icon is loaded correctly:

`<ion-icon name="eye-off-outline"></ion-icon>`

![image](https://user-images.githubusercontent.com/13800439/187216570-47354c0c-9d64-4728-85bf-6ed69c7973aa.png)

If **pnpm** is used and ion-icon refer to a ion-icon name the svg icon does not loads correctly.

![image](https://user-images.githubusercontent.com/13800439/187224041-56cabc29-d958-4762-89f1-893f61781f50.png)

### Expected Behavior

It should work with pnpm the same way as npm.

### Steps to Reproduce

Setup an ionic project or use your current project where and ion-icon is used.

Remove node_modules and package-lock.json.

Install dependencies using pnpm.

Run ionic serve.

### Ionic Info

$ ionic info
   Ionic:
   Ionic CLI                     : 6.20.1 (C:\Users\hsantos\AppData\Roaming\nvm\v14.20.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.4
   @angular-devkit/build-angular : 14.2.1
   @angular-devkit/schematics    : 14.2.1
   @angular/cli                  : 14.2.1
   @ionic/angular-toolkit        : 7.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.20.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.17
   OS     : Windows 10

**Comment by eduboxgithub** [comment]
You can just create a ionic starter app:

> ionic start (angular app, template sidemenu)
> cd <name-app>
> ionic start

The app will start and you will see the ion-icons on the side menu. Now you can stop ionic start.
Delete node_modules and packaged-lock.json.

> npm install -g pnpm (if pnpm not installed already)

> pnpm install
> ionic start

The app will start and you not be able to see the icon-icon on the side menu.

A clean ionic angular app with sidemenu template is attached below... you can simple do a pnpm install and ion-icons will not show/be loeaded.

[SamplePNPMvsNPM.zip](https://github.com/ionic-team/ionic-framework/files/9446020/SamplePNPMvsNPM.zip)

**Comment by maroon1** [comment]
@eduboxgithub You can explicitly add `ionicons` as a dependency in `package.json`. Because `ionicons` is a "ghost" dependency, so Angular can not find the `ionicons` in the root of `node_modules` directory.

```sh
pnpm add ionicons
```

**Comment by eduboxgithub** [comment]
Thank you @maroon1, this seems to have solved the problem, at least the ion-icons appear in the application.

But is it supposed to be like that? Shouldn't it work out-of-the-box, without having to re-declare dependencies?

This leads me to think if there could be any other lib that exists as a sub-dependency and the application is "broken" for that reason.

**Comment by liamdebeasi** [comment]
Thanks! `ionicons` should be listed as a direct dependency in our starter applications. 

Ionicons is required by `@ionic/angular` and `@ionic/core`, so it gets installed to the top level `node_modules` when using npm. For pnpm this causes issues since `ionicons` is not installed to the top level `node_modules`.

I merged a fix to resolve this for new starter applications: https://github.com/ionic-team/starters/pull/1731

For existing applications, the fix is to manually add `ionicons` as a dependency. As noted in https://github.com/ionic-team/ionic-framework/issues/25846#issuecomment-1231108651.
