### ISSUE TITLE
bug: size of ion-checkbox

### ISSUE THREAD

**Issue by aktivdigital-frontend** [ionic-team/ionic-framework#25850]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

ion-checkbox width is not correct when it is in the flex container. It is smaller than --size.

Example: https://ibb.co/JF1MCsZ

### Expected Behavior

I would like to: https://ibb.co/jZ29KGf

I fixed it by:

```
ion-checkbox {
	--size: 28px;

	&::part(container) {
		min-width: var(--size);
	}
}
```

### Steps to Reproduce

Add display:flex to an item and add to the ion-chekcbox to it and another element to it. If another element is too long, the ckeckbox will smaller.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (C:\Users\AKTIVD~1\AppData\Roaming\nvm\v14.15.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.4
   @angular-devkit/build-angular : 14.0.4
   @angular-devkit/schematics    : 14.0.4
   @angular/cli                  : 14.0.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : 4.0.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v14.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
