### ISSUE TITLE
bug: ion-back-button not working with vue 3.2.38

### ISSUE THREAD

**Issue by RobinHavre** [ionic-team/ionic-framework#25861]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

After upgrading vue from version 3.2.37 to version 3.2.38, ion-back-button stops working if the user has visited more that one page.

No errors in console, and no navigation is performed.

### Expected Behavior

The ion-back-button should always navigate the user back.

### Steps to Reproduce

After upgrading vue from version 3.2.37 to version 3.2.38, ion-back-button stops working:

- Install ``vue@3.2.38``
- Navigate to **any page**
- Clicking ion-back-button works
- Navigate forward to that same page again works
- Clicking ion-back-button works
- Navigate to any **other page** works
- Then clicking ion-back-button **does not work**

I have tried a combination of package versions (ionic, ionic/vue, vue, vue-router) and this error always happens if ``vue`` is version 3.2.38.

Programmatic navigation (for example ``router.go(-1)``) works just fine, it is only when using ``ion-back-button`` that it doesn't work.

I get no erros in console.

### Ionic Info

Ionic:

   Ionic CLI       : 5.4.16
   Ionic Framework : @ionic/vue 6.2.4

Capacitor:

   Capacitor CLI   : 4.1.0
   @capacitor/core : 4.1.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v14.18.1 (/Users/***********/.nvm/versions/node/v14.18.1/bin/node)
   npm    : 6.14.15
   OS     : macOS Monterey

### Additional Information

- The error happens regardless of which @ionic-vue or @ionic version is installed, as long as ``vue@3.2.38`` is installed
- Installing ``vue@3.2.37`` fixes the issue
- Other forms of navigation works, like pushing a page, ``router.go(-1)``etc.
- The error happens regardless of which history mode is used by the router

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
