### ISSUE TITLE
bug: Property 'alignment' ignores for ion-select with interface="popover"

### ISSUE THREAD

**Issue by Yura13** [ionic-team/ionic-framework#25876]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Property 'alignment'  doesn't impact to ion-select if interface="popover":
```
<ion-select
      interface="popover"
      [interfaceOptions]="{ side: 'bottom', mode: 'md', alignment: 'end' }"
    >
```
Popover always shows like aligment="start"

![image](https://user-images.githubusercontent.com/17030431/188177078-f094a4d8-4435-4689-a0c6-f1ca657d84a0.png)

### Expected Behavior

Property 'alignment'  should impact ion-select if interface="popover".

### Steps to Reproduce

https://stackblitz.com/edit/angular-3xxuyw?file=src%2Fapp%2Fexample.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 (C:\Users\User1\AppData\Roaming\nvm\v16.13.2\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.14
   @angular-devkit/build-angular : 13.3.8
   @angular-devkit/schematics    : 13.3.8
   @angular/cli                  : 13.3.8
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 10.1.1, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.5.2, (and 32 other plugins)

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.6.0) : 1.5.0

System:

   Android SDK Tools : 26.1.1 (C:\Android\android-sdk)
   NodeJS            : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm               : 8.1.2
   OS                : Windows 10

**Comment by sean-perkins** [comment]
@Yura13 the `alignment` property is correct in this implementation. 

In your example, the `ion-select` is not full width. Even though you specify `alignment="end"`, the popover positions in a way that will prevent it from displaying off the visible viewport. If you want the popover to display on the right-hand of the screen, apply `width: 100%` styling to your `ion-select` in the item.
