### ISSUE TITLE
feat: ion-card support for ion-accordion

### ISSUE THREAD

**Issue by codewithtushar** [ionic-team/ionic-framework#25879]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I tried using ion-card with ion-accordion but both components hides itself and nothing works

### Describe the Use Case

showing map, image thumbnails, order info etc & i also need gutter spaces between ion-items for which i have to again customise ion-items to look like ion-card

### Describe Preferred Solution

modify ion-item to look like ion-card, which is kind of a hacky solution for me

### Related Code

https://stackblitz.com/edit/angular-nfqpf4?file=src/app/example.component.html

**Comment by liamdebeasi** [comment]
Thanks for the report. The card can already be used with `ion-accordion`. The issue in the provided demo is that `ion-card` is a child of `ion-accordion`. The card should wrap the accordion instead.

Demo: https://codepen.io/liamdebeasi/pen/OJZVqWb
