### ISSUE TITLE
bug: ion-datetime time wheel is getting hidden when click on the time value on the time wheel and keyboards open in Iphone 11, 12, XS Max

### ISSUE THREAD

**Issue by mandis2010** [ionic-team/ionic-framework#25881]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When clicking on a value of the time wheel, time wheel getting hidden automatically when keyboard is opening. Noticed this issue so far on iPhone 11, 12 and XS Max.

### Expected Behavior

When the keyboard is opening time wheel should not close or hidden. Time wheel should be visible to the users.

### Steps to Reproduce

1. Use ion-datetime and generate the ios ipa using cordova.

<ion-datetime></ion-datetime>

3. Click on the minute column or hour column to open the numeric keyboard.

### Code Reproduction URL

https://github.com/mandis2010/datePicker

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.0 
   Ionic Framework               : @ionic/angular 6.2.4
   @angular-devkit/build-angular : 13.2.5
   @angular-devkit/schematics    : 13.2.5
   @angular/cli                  : 13.2.5
   @ionic/angular-toolkit        : 6.0.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 14 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v16.14.2
   npm        : 8.18.0
   OS         : macOS Big Sur
   Xcode      : Xcode 13.0 Build version 13A233

### Additional Information

![time-picker](https://user-images.githubusercontent.com/102654303/188530666-2e730599-799f-48ae-b245-54fd190dff84.PNG)

**Comment by sean-perkins** [comment]
Hello @mandis2010 thank you for this issue!

With the reproduction app and serving it on my iPhone 12 Pro Max, I am unable to reproduce.

Can you attach a recording of this issue? Does the popover present initially, but dismiss after selecting a column?
