### ISSUE TITLE
bug: ionic/react Duplicate firing of onClick handlers during rapid click in Firefox responsive design mode

### ISSUE THREAD

**Issue by benallfree** [ionic-team/ionic-framework#25882]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

This only happens in Firefox (not Chrome). Here's a visual demo: https://user-images.githubusercontent.com/1068356/188532214-96950c3a-236a-49d7-87ec-5072ca97adf4.mp4

Using the following code, or using this Codesandbox demo (https://codesandbox.io/s/determined-bohr-s30zng?file=/src/App.tsx:913-1244&resolutionWidth=320&resolutionHeight=675). 

Open the Firefox debugger and set the device size to iPhone or something similar. Observe that rapid clicks produce duplicate `onClick` events.

```jsx
const App: React.FC = () => {
  const handleClick = (() => {
    let i = 0;
    return () => {
      i++;
      console.log(i);
    };
  })();

  return (
    <IonApp>
      <IonPage>
        <IonContent>
          <IonButton onClick={handleClick}>Click me</IonButton>
        </IonContent>
      </IonPage>
    </IonApp>
  );
};
```

### Expected Behavior

One `onClick` event per click

### Steps to Reproduce

See above

### Code Reproduction URL

https://codesandbox.io/s/determined-bohr-s30zng?file=/src/App.tsx:913-1244&resolutionWidth=320&resolutionHeight=675

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.2.5

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : not installed
   @capacitor/core    : 3.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.14.0
   OS     : macOS Monterey
```

### Additional Information

Could be related to #17321?

**Comment by liamdebeasi** [comment]
Thanks for the report. This may be a browser quirk as I am able to reproduce this outside of Ionic: https://codesandbox.io/s/nice-dawn-f1l43c?file=/src/App.tsx

Is this issue impacting any apps your have running in production?

**Comment by benallfree** [comment]
Hmm, I'm not seeing the duplicate events in the sample you provided, even when I put it in responsive mode. When I run https://f1l43c.csb.app/ with the FF debugger open in responsive mode, I get the expected behavior of one event per click.

As far as prod impact, I'd say negligible. It's a production app, but it seems unlikely that people would be running it with the Firefox debugger open in mobile/responsive mode. I only noticed because I run that way for responsive testing.

I haven't tested for this behavior on a mobile device running Firefox.

Ionic uses webkit for native apps anyway, right?

Thanks for the quick look!

**Comment by liamdebeasi** [comment]
> As far as prod impact, I'd say negligible. It's a production app, but it seems unlikely that people would be running it with the Firefox debugger open in mobile/responsive mode. I only noticed because I run that way for responsive testing.

Thanks! This helps better identify the impact. At this point, I am able to reproduce this issue outside of Ionic, so I am not sure this is something we are able to fix. It might be better to file some feedback on [Mozilla's Bug Reporter](https://bugzilla.mozilla.org/home).

I will note that I was missing some necessary code in my original reproduction that I have since added: 


https://user-images.githubusercontent.com/2721089/188887358-cf57bebe-9dfe-43fd-a2cc-2549b8ef517e.mov

I did notice that this issue only happens when the "Touch simulation" button is enabled, further indicating that this may be a quirk with the mobile simulation on Firefox.

-----

> Ionic uses webkit for native apps anyway, right?

WebKit is only used on iOS. Android will use Chromium when running as a standalone native app.

**Comment by benallfree** [comment]
Ok thanks, I think we can close this.

**Comment by benallfree** [comment]
Filed with Mozilla https://bugzilla.mozilla.org/show_bug.cgi?id=1789674

**Comment by liamdebeasi** [comment]
Thanks for filing a ticket!
