### ISSUE TITLE
bug: item and card buttons should inherit aria-label attribute

### ISSUE THREAD

**Issue by DeyBo** [ionic-team/ionic-framework#25885]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hi !

I saw that there are already some components that reflect _aria-label_ property on their native element (i.e. ion-button).
In my case, I use _ion-card_ and _ion-item_. Sometimes, I set _button_ to true for these, but my custom _aria-label_ is not extended to native button.

### Expected Behavior

I wanted to know if it is possible to use _aria-label_ with another way ?
Or maybe make it possible to extend _aria-label_ to native button when _ion-item_ and _ion-card_ has _button_ to true ?

### Steps to Reproduce

To see it, you can use _ion-item_ or _ion-card_ with _button_ property to true. Set a custom _aria-label_ to your _ion-item_ or _ion-card_ and check accessibility name.

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.0.9
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 12.2.15
   @angular/cli                  : 13.1.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.15.1 (/usr/local/bin/node)
   npm    : 8.12.1
   OS     : macOS Monterey

### Additional Information

Thanks and sorry for my medium english !

**Comment by sean-perkins** [comment]
Hello @DeyBo! Can you try with this dev-build and let me know if you run into any issues?

```shell
npm install @ionic/angular@6.2.9-dev.11664315083.10f0210f
```

In this build any `aria-label` specified on the host of `ion-item` or `ion-card` when using `button`, will be reflected to the inner button.

**Comment by DeyBo** [comment]
Hello @sean-perkins !

It seams that it's reflecting "arialabel" and not "aria-label" so it doesn't work properly for web accessibility.

There is some screenshots of Firefox Devtools to illustrate !

What it does :
DOM view
![SCR-20220928-ciu](https://user-images.githubusercontent.com/32773025/192710820-12074d1e-3557-44a8-97b7-0a8fff0cc88d.png)
Accessibility view
![SCR-20220928-cjc](https://user-images.githubusercontent.com/32773025/192710857-6aaca514-88b6-4edb-a995-2c2da5fd29c8.png)

What it should do :
DOM view
![SCR-20220928-cmb](https://user-images.githubusercontent.com/32773025/192711165-9eb6cd1e-6cb1-4221-a0bb-83878271e44a.png)
Accessibility view
![SCR-20220928-cjs](https://user-images.githubusercontent.com/32773025/192710938-65514eab-6fb3-42b5-8c40-4372d6899d58.png)

Thank you very much for your time !

**Comment by sean-perkins** [comment]
@DeyBo thanks for testing and confirming that problem. It would definitely help if I had assigned to the correct key!

Here is an updated dev-build that assigns to `aria-label`, not `ariaLabel`. 

```shell
npm install @ionic/angular@6.2.10-dev.11664382391.15516e55 
```

**Comment by DeyBo** [comment]
Thank you very much @sean-perkins !
It's working very well !

**Comment by sean-perkins** [comment]
This will be available in the next patch release of Ionic.
