### ISSUE TITLE
bug: Using 2 ion-datetimes linked by min/max causes unexpected re-renders

### ISSUE THREAD

**Issue by Chronos77** [ionic-team/ionic-framework#25894]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

the bug appears when you have two ion-datetimes (with presentation="date-time") linked (by min and max) and you try to put an end date lower than the start date.

For more precision: on the first ion-datetime(startDate) have a max value and the second(endDate) have min date(startDate) and max date (current date)

The app freezes completely

### Expected Behavior

normally it should put us the day before with the corresponding time and don't have a freeze

### Steps to Reproduce

URL to reproduce : https://stackblitz.com/edit/angular-ivy-zh9eog?file=src/app/app.component.ts

- have 2 ion-datetime with 3 days between and with presentation="date-time"
- on the first (startDate) select day - 1 (in the example you can click on 20) and add 1 hours (04:00)
- on the other (endDate) select 20 
- the app freezes completely

### Code Reproduction URL

https://stackblitz.com/edit/angular-ivy-zh9eog?file=src/app/app.component.ts

### Ionic Info

Ionic CLI                     : 6.20.1 (/home/ssa-dw/.nvm/versions/node/v14.15.5/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.5
   @angular-devkit/build-angular : 13.2.3
   @angular-devkit/schematics    : 13.3.7
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.0) : 1.6.0

System:

   Android SDK Tools : 26.1.1 (/home/ssa-dw/Android/Sdk)
   NodeJS            : v14.15.5 (/home/ssa-dw/.nvm/versions/node/v14.15.5/bin/node)
   npm               : 6.14.11
   OS                : Linux 5.1

**Comment by acommend** [comment]
Ran into a similar issue using ionic vue v6.2.9 when using 2 datetimes with min and max however for me the problem manifests when trying to select a start time value past that of the end time. In the attached image the app is froze during an attempt to select a start time that was past the end time
![starttime_datetime_freezes_app](https://user-images.githubusercontent.com/35347165/193662318-cdf40674-7ba3-46cb-ad0c-a66cda293050.PNG)

**Comment by liamdebeasi** [comment]
Hi there,

Can everyone try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.3.2-dev.11665693413.14672b1c
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26125, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue testing the dev build, and let me know if there are any issues.
