### ISSUE TITLE
bug: ion-datetime presentation="date-time" preferwheel="true" date range limited to same year

### ISSUE THREAD

**Issue by mCassanoQuix** [ionic-team/ionic-framework#25895]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Using component ion-datetime with properties "presentation" set to "date-time" and "preferwheel" set to "true" allows picking days with the wheel interface one by one, e.g. "January 1st, January 2nd, ..."; selecting a day results in an output date that reflects selected day/month and time, but output year is always the initial date's year

### Expected Behavior

Scrolling a date before January 1st or December 31st should either regress or progress the year by one, respectively, e.g. "December 31st 2020" > "January 1st 2021".

### Steps to Reproduce

In the included repo, select the dateTo field and scroll one day forward to january 1st

### Code Reproduction URL

https://ionic6-angular14-bn9qzc.stackblitz.io

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.0 (/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.5
   @angular-devkit/build-angular : 14.2.1
   @angular-devkit/schematics    : 14.2.1
   @angular/cli                  : 14.2.1
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.14.2 (/Users/user/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey

  ─────────────────────────────────────────────────

     Ionic CLI update available: 6.20.0 → 6.20.1
          Run npm i -g @ionic/cli to update

  ─────────────────────────────────────────────────

### Additional Information

The requested behavior could be given as an option to not limit use cases. It could also be solved by giving the option to select year, month and day individually as the old component could be configured to do.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Here is a dev build if you would like to test a proposed fix:

```
npm install @ionic/angular@6.2.6-dev.11662567359.1c1beed4
```

Note: You may need to install this in a local Ionic app. StackBlitz sometimes has issues installing dev builds of Ionic.

**Comment by mCassanoQuix** [comment]
Hello, thanks for the rapid response, i have tested the fix locally with the aforementioned version and it looks to be working fine now, years advance and regress correctly using the wheel. I will eagerly wait for the upcoming release including the fix.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25896, and a fix will be available in an upcoming release of Ionic Framework.
