### ISSUE TITLE
bug: Unnecessary padding for ion-item when creating ion-inputs

### ISSUE THREAD

**Issue by trinathkatari** [ionic-team/ionic-framework#25899]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

 Unnecessary padding for ion-item when creating ion-inputs

### Expected Behavior

 <ion-item  class="width-100" >

            <ion-label position="stacked" style="font-size:16px;">Integration Name

                <span class="">* : </span>

            </ion-label>

            <ion-input

           ></ion-input>

        </ion-item>

        <ion-item  class="width-100" >

          <ion-label position="stacked" style="font-size:16px;">Integration Type

              <span class="">* : </span>

          </ion-label>

          <ion-input

              ></ion-input>

      </ion-item>

### Steps to Reproduce

<img src="blob:https://teams.microsoft.com/630f4c26-22ef-44fa-9255-40a315ea4a66" width="1223" height="166" key="static-image_0">

### Ionic Info

 Unnecessary padding for ion-item when creating ion-inputs

**Comment by trinathkatari** [comment]
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/104483892/189134477-966ab5dd-a43b-468d-8798-b1f5b4663b6c.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
