### ISSUE TITLE
bug: unresolved import on ionic 6.2.6

### ISSUE THREAD

**Issue by corysmc** [ionic-team/ionic-framework#25897]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When running a stencil application with the latest `@ionic/core@6.2.6` the ion-tab-bar component has an unresolved import:
```
Bundling Warning UNRESOLVED_IMPORT '@utils/keyboard/keyboard-controller' is imported by ./node_modules/@ionic/core/dist/collection/components/tab-bar/tab-bar.js, but could not be resolved – treating it as an external dependency
```

### Expected Behavior

imports are resolved

### Steps to Reproduce

Create stencil application that uses ion-tab-bar, and see error

### Ionic Info

```
Ionic:

   Ionic CLI : 6.20.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.18.0
   npm    : 6.14.15
   OS     : macOS Big Sur
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25898, and a fix will be available in an upcoming release of Ionic Framework. Thank you for putting up the PR!
