### ISSUE TITLE
fix: IonInput does not support data-form-type attribute used by password managers

### ISSUE THREAD

**Issue by aleneri97** [ionic-team/ionic-framework#25908]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Would be great to be able to add a `data-form-type` attribute to the `input` tag while using the `ion-input` component to have long forms auto-filled with a password manager such as Dashlane.

Here's the Dashlane [article](https://blog.dashlane.com/dashlane-integration-forms) explaining the correct implementation to have the auto-fill feature in fields like name, birthday, address, gender, etc.

### Describe the Use Case

With this implementation, users could:
* **Have their forms (almost) completely auto-filled** using password managers such as Dashlane.
* **Improve their experience** filling out forms since these would be _automagically_ filled. 

### Describe Preferred Solution

Would be great to add the attribute `data-form-type` to `ion-input` to be passed to the input.

### Describe Alternatives

Another solution could be to use the `autocomplete` attribute that already exists but use it to fill out other types of input

**Comment by sean-perkins** [comment]
Hello @aleneri97 can you try with this dev build and let me know if the password auto-fill behavior works as you are expecting:

```bash
npm install @ionic/angular@6.2.7-dev.11662746386.1ddae515
```

This should reflect the attribute from the `ion-input` host to the inner element:
```html
<ion-input data-form-type="test">
   <!-- internals -->
   <input data-form-type="test" />
</ion-input>
```

**Comment by aleneri97** [comment]
Hi, @sean-perkins I've just tested it and it works as expected.

Thank you very much for the support.

**Comment by sean-perkins** [comment]
Great to hear @aleneri97, I'll open a pull request for this change.
