### ISSUE TITLE
bug:Ionic Datetime populating wrong year when selecting 31 december

### ISSUE THREAD

**Issue by ffahadMalikk** [ionic-team/ionic-framework#25903]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

While selecting a DateTime from the ion modal, the date picker populates the wrong year in case of some dates. i.e. 29-30-31 December.
e.g if i select 31-12-2001 it will show 31-12-2002 on my input field. 
<img width="1153" alt="Screenshot 2022-09-09 at 11 14 34 AM" src="https://user-images.githubusercontent.com/25727339/189283719-d046e833-3c43-488e-9e18-ceb1cd81a255.png">

### Expected Behavior

It should show the exact date that's been select on the calendar to my input filed.selected

### Steps to Reproduce

Bind ion-DateTime to an input field. 
open with type preference date and time 
select date 31 December and a year(it's happening in case of some years e.g it will not replicate in case of 22)
check the date populated on the input

### Ionic Info

[WARN] Error loading @ionic/angular-toolkit package.json: Error: Cannot find module '@ionic/angular-toolkit/package'
       
       Require stack:
       - /Users/fahad/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/fahad/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/fahad/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/index.js
       - /Users/fahad/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/fahad/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.6
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 13.3.9
   @ionic/angular-toolkit        : not installed

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 10.1.2, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, cordova-plugin-ionic 5.5.2, (and 22 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.0) : 1.6.0

System:

   Android SDK Tools : 26.1.1 (/Users/fahad/Library/Android/sdk/)
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v16.15.0 (/Users/fahad/.nvm/versions/node/v16.15.0/bin/node)
   npm               : 8.5.5
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100

**Comment by ffahadMalikk** [comment]
the issue can be replicated by cloning this one-page application and also i have uploaded a  [Sample video](https://www.loom.com/share/3269755bcf674803846c80427d1dd526) for sample reference.

**Comment by amandaejohnston** [comment]
@ffahadMalikk Could you post a link to the Github repo? If you intended to in that last comment, the link is missing.

**Comment by ffahadMalikk** [comment]
@amandaejohnston yeah i might be mixed up with video lnk here you can fidn the repo 
https://github.com/ffahadMalikk/Ionic-Date-time-startup/tree/yearIssue

**Comment by RajuDangol45** [comment]
Facing the same issue. Could have to do with how ionic parses the date on view because the value received on (ionChange) is correct.

**Comment by ffahadMalikk** [comment]
@amandaejohnston is there any update regarding this? its a blocker for us and we don't want to switch to another plugin.

**Comment by liamdebeasi** [comment]
Apologies for the delay. This appears to be an implementation issue in the provided application. For example, when I select December 31, 2001 I receive this value from the `ionChange` event: `2001-12-31T14:47:00-05:00`. However, the date is rendered as `31/12/2002` after the `formattedAnswer` method runs.

As an additional test, I hard coded `return formatDate('2001-12-31', 'dd/MM/YYYY', this.locale);` in your app and got the same `31/12/2002` result. Can you double check to make sure the `formatDate` function is being used correctly?
