### ISSUE TITLE
bug: `onDidPresent` and `onWillPresent` missing on modal

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#25917]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`onDidPresent` and `onWillPresent` are missing on`HTMLIonModalElement`.

Current workaround:
```ts
this.modal.addEventListener('didPresent', () => { ... });
```

### Expected Behavior

Expose them directly, as the `dismiss` one's

### Steps to Reproduce

No steps needed i guess

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/hans/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.5
   @angular-devkit/build-angular : 14.2.1
   @angular-devkit/schematics    : 14.2.1
   @angular/cli                  : 14.2.1
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.0) : 1.6.0

System:

   Android SDK Tools : 25.2.3 (/Users/hans/Library/Android/sdk)
   ios-deploy        : 1.10.0
   NodeJS            : v16.14.2 (/Users/hans/.nvm/versions/node/v16.14.2/bin/node)
   npm               : 8.17.0
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you requesting `onDidPresent` and `onWillPresent` methods to be added?

**Comment by EinfachHans** [comment]
Yes exactly 🙌🏼

**Comment by liamdebeasi** [comment]
Thanks for the follow up. The existing `onDidDismiss` and `onWillDismiss` methods are intended to be used with controllers. For example, they make it easy to run code when a controller modal has been dismissed:

```js
const modal = await modalController.create({ ... });

await modal.present();

await modal.onDidDismiss();

// run some code
```

`onDidPresent` and `onWillPresent` methods are not needed here because the developer already knows when the modal is about to open. For example, running code immediately before `await modal.present()` is the equivalent of an `onWillPresent` method. Similarly, running code immediately after `await modal.present()` is the equivalent of an `onDidPresent` method.

**Comment by EinfachHans** [comment]
What i'm trying to do is within the ModalComponent to wait for the modal to be presented and then do something 🤔

**Comment by EinfachHans** [comment]
I'm implementing a Scanner via the Camera Preview Plugin. This opens a Camera under the webview and i have to make the webview transparent to make it visible. In our app the user should have the feeling of this camera beeing inside of this modal, so the modal' header and overlay are not hidden, only the content is by a transparent background.

This "invisible" setting should only be applied after the modal is opened up **AND** the camera is started (in my tests this is not always the same first as the camera starts up faster/slower sometimes) so i need to wait for the modal to be presented here.

**Comment by liamdebeasi** [comment]
Thanks for the follow up. I discussed this with the team, and we are not looking to add `onDidPresent` or `onWillPresent` methods at this time. The main reason is listening for the `didPresent` event should yield the same results that are needed for your application.
