### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by mohakalgo** [ionic-team/ionic-framework#25936]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I am using IonModel with IonNav with react code. 
My current behaviour is the button click will not work inside the Model for any kind of button. I have added IonButton, IonBackButton and with IocIcon onClick events, But even the console log not working which is written in the onClick event. 
The button click will be visible when we click on the button. So there is no Z-Index issue. 

### Expected Behavior

The expected result is button click should work with the IonNavbar which we have take in the app.tsx. 

### Steps to Reproduce

1) Take any sample project with the IonNav bar with a toolbar at bottom
2) Create IonCard inside it opens the IonModel with the state. 
3) Take any button inside it and the click is not working.  

### Ionic Info

We have used the ionic 6 versions to develop our project.

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
