### ISSUE TITLE
bug: redundant rerender when switch router

### ISSUE THREAD

**Issue by F3n67u** [ionic-team/ionic-framework#25951]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] Nightly

### Current Behavior

When switching the router between two pages, both page components will rerender 4 times.

### Expected Behavior

When switching the router between two pages, the target page should only render 1 time. The old page should not be rerendered.

### Steps to Reproduce

1. Go to https://codesandbox.io/s/ionic-react-rerender-5vf2lj
2. Click the "Brew" tab
3. then switch to the "Settings" tab
4. You will see the "render Brew" and "render Settings" log will print 4 times each

### Code Reproduction URL

https://codesandbox.io/s/ionic-react-rerender-5vf2lj

### Ionic Info

Because the repro is in codesandbox, I cannot run `ionic info`. 

```json
    "@ionic/react": "6.2.8-nightly.20220915",
    "@ionic/react-router": "6.2.8-nightly.20220915",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-router": "5.2.0",
    "react-router-dom": "5.2.0",
```

### Additional Information

Maybe duplicated with https://github.com/ionic-team/ionic-framework/issues/22426 and https://github.com/ionic-team/ionic-framework/issues/24107, but those issue is still not fixed even in the latest release version. so I created this new issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. Can you clarify the issue you are running into? Are these additional renders negatively impacting you app's performance? Currently, multiple renders are necessary when setting up tabs, switching the active tab, performing page transitions, etc. There are multiple operations done internally that potentially require the visual state to be updated.
