### ISSUE TITLE
bug: IonItemSliding open() method not working

### ISSUE THREAD

**Issue by npearson72** [ionic-team/ionic-framework#25963]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The `close` method seems to work, but the `open` method does not. Here is an example of using the `close` method:

```ts
const handleSlide = async (event: any) => {
    const ratio = await event.target.getSlidingRatio();

    if (ratio >= 3) {
      await event.target.close();
    }
  };

  return (
    <IonItemSliding onIonDrag={handleSlide}>
      <IonItem>Testing...</IonItem>

      <IonItemOptions side="end">
        <IonItemOption color="danger" expandable>
          <Icon icon="icons8:trash" className="icon" />
        </IonItemOption>
      </IonItemOptions>
    </IonItemSliding>
  );
```

Here is the behavior:

![close](https://user-images.githubusercontent.com/1323414/190881778-f3291423-62d0-4ef0-8b00-6916342daeab.gif)

Works as expected.

But when I change to the open method, it does not work.

```ts
const handleSlide = async (event: any) => {
    const ratio = await event.target.getSlidingRatio();

    if (ratio >= 3) {
      await event.target.open();
    }
  };

  return (
    <IonItemSliding onIonDrag={handleSlide}>
      <IonItem>Testing...</IonItem>

      <IonItemOptions side="end">
        <IonItemOption color="danger" expandable>
          <Icon icon="icons8:trash" className="icon" />
        </IonItemOption>
      </IonItemOptions>
    </IonItemSliding>
  );
```

Here is the behavior:

![open](https://user-images.githubusercontent.com/1323414/190881794-941fd0b4-8f9f-488a-8bc7-c5532e34fb7c.gif)

As you can see, when I drag past the 30% mark, nothing happens.

I would expect it slide open.

PS: I’ve also tried with open('end') and open('start') but nothing.

### Expected Behavior

I would expect that once the `open` method is invoked, the `IonItemSliding` slides open completely.

### Steps to Reproduce

Please see what I posted in the "Current Behavior" section.

### Ionic Info

```
Ionic:

   Ionic CLI : 6.20.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.15.1
   npm    : 8.11.0
   OS     : macOS Monterey
```

### Additional Information

I've also posted in the community forum:

https://forum.ionicframework.com/t/ionitemsliding-open-method-not-working/226975

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
