### ISSUE TITLE
bug: ion-datetime "confirm" button is not shown properly on wheelpicker on iOS device with small screen

### ISSUE THREAD

**Issue by chrisvor** [ionic-team/ionic-framework#25968]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using the new ion-datetime to show a "wheelpicker" date & time popover, and also using the "showdefaultbuttons" property, the buttons are shown properly on Android, but on iOS with a smaller screen, the "confirm" button is cropped (see picture)

![image](https://user-images.githubusercontent.com/2786551/191049956-9fec5e17-ecd2-4988-a86b-9ccf456d20d6.png)

### Expected Behavior

The "confirm" button should be placed using a margin to the right equal to the margin-left of the "Cancel" button"

### Steps to Reproduce

1. use the below markup to place a popover datetime on a page

```
<ion-input value="{{ deliveryDateDate | localizedDate:'EEEE dd/MM/yyyy HH:mm' }}" id="deliveryDate">
            </ion-input>
            <ion-popover #deliveryPopOver trigger="deliveryDate" size="cover" alignment="end" [dismissOnSelect]="true">
              <ng-template>
                <ion-datetime #deliveryDateTime id="delivery_datetime" presentation="date-time" preferWheel="true" class="text-left" 
                    min="{{ minDate }}"
                    max="{{ maxDate }}"
                    hourCycle="h23"
                    showDefaultButtons="true"
                    [doneText]="OK"
                    [cancelText]="Cancel"
                    [(ngModel)]="deliveryDate" (ionChange)="changeDeliveryTime()"></ion-datetime>
              </ng-template>
            </ion-popover>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.2
   @angular-devkit/build-angular : 14.1.2
   @angular-devkit/schematics    : 14.1.2
   @angular/cli                  : 14.1.2
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.0) : 1.6.0

System:

   NodeJS : v16.14.0 (/Users/chris/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.18.0
   OS     : macOS Monterey

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
