### ISSUE TITLE
bug: IonLoading not displaying spinner on Android (React)

### ISSUE THREAD

**Issue by Traxx2012** [ionic-team/ionic-framework#25966]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I'm trying to show an IonLoading popup while my app gets parameters from a server.

Calling the IonLoading element works fine, dismissing too, but it just refuses to show the spinner on Android. In web it works fine. This is the element:

`<IonLoading spinner="crescent" isOpen={showLoading} onDidDismiss={() => setShowLoading(false)} message={loadingText} />`

I tried manually setting the spinner color, but that didn't help. When looking into chrome://inspect , I noticed the size of the spinner element was set to zero:
![image](https://user-images.githubusercontent.com/31518769/191027529-f0bf426f-1463-48e1-ad97-f32d99ca9b96.png)
![image](https://user-images.githubusercontent.com/31518769/191027558-04ac591b-13fc-4d54-9b4f-6b75f180ad53.png)

Again, I want to stress that this is a screenshot of chrome://inspect of the Android WebView.
As you can see, in PWA there is actual content for the spinner; the whole SVG tag is missing in android:
![image](https://user-images.githubusercontent.com/31518769/191027906-86f21513-487d-4d14-97df-b50b96a8c6ac.png)

### Expected Behavior

Spinner should show on Android as it does on PWA.

### Steps to Reproduce

Create Ionic-React app, configure IonLoading as shown above, show with
`const [showLoading, setShowLoading} = useState(true);`

### Ionic Info

Ionic:
   Ionic CLI       : 6.14.1 (C:\Users\fabia\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.2.7

Utility:
   cordova-res : 0.15.4
   native-run  : 1.7.0

System:
   NodeJS : v18.8.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.18.0
   OS     : Windows 10

### Additional Information

I tried updating Ionic without success, the behavior persists.

**Comment by Traxx2012** [comment]
### Reproduction of the issue

Minimal App provided here: [https://github.com/Traxx2012/spinnerReproduction/](url)

Steps to error:
- ionic build
- npx cap run android
- run on any android device or emulator (at least for me, it doesn't make any difference)

**Comment by liamdebeasi** [comment]
Thanks! Apologies, I should have referenced https://github.com/ionic-team/ionic-framework/issues/25962 sooner. I am going to merge the two issues, but there is a dev build with a proposed fix in https://github.com/ionic-team/ionic-framework/issues/25962#issuecomment-1251099418.

The PR is available in https://github.com/ionic-team/ionic-framework/pull/25967.

**Comment by Traxx2012** [comment]
No worries. But isn't that different behavior? I have seen #25962, but I thought it is a different issue, especially because #25962 states that no backdrop is shown, which is no issue for me.

**Comment by liamdebeasi** [comment]
The problem here is that `IonLoading` does not automatically define child Ionic components used internally. Both `IonBackdrop` and `IonSpinner` are used in `IonLoading`.
