### ISSUE TITLE
feat: SolidJS support

### ISSUE THREAD

**Issue by pashvin** [ionic-team/ionic-framework#25970]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

SolidJS (https://www.solidjs.com/) is like ReactJs but has better performance. In terms of code syntax, it is much easy to use.
Providing support of ionic for SolidJS will help improve the popularity of the SolidJS framework. Also SolidJS port from ReactJs should be not that hard as the syntax of SolidJS and ReactJS are very similar.

### Describe the Use Case

Giving more choice to developers along with Angular , React & VueJs

**Comment by liamdebeasi** [comment]
Thanks for the issue. Ionic Framework is built with Web Components which can be used is many different JavaScript Frameworks. As a result, you should already be able to use Ionic's components in a SolidJS app. Is there a particular problem you are running into?

**Comment by pashvin** [comment]
@liamdebeasi I am looking for "Page Navigate" in solidJS + Capacitor project. For ReactJS project, you can do this (https://ionicframework.com/docs/react/navigation) but not sure how to get the same thing in solidJS.

I thought React/Vue/Angular wrappers are created to address the framework-specific requirement (like routing) and providing one for SolidJS will help solidJS developers too.

**Comment by liamdebeasi** [comment]
Thanks for the clarification. I will leave this open for a period of time to collect feedback from the community.

-----

For other developers: If this is a feature you want, please upvote/react to the original feature request to avoid "+1" comments.

If you have any specific feedback regarding issues you are running into using Ionic with SolidJS or what you would like to see with an Ionic SolidJS integration, please post a comment.

**Comment by TheCollinCashio** [comment]
I would really like this feature. I am big on solid-js and would love to see support for it in the ionic UI framework

**Comment by pashvin** [comment]
@TheCollinCashio Please vote using the "thums up" reaction on the main post.

**Comment by g5becks** [comment]
As someone who has wanted to use Ionic with different "non supported" frameworks over the years. I really wish Ionic would migrate to using a framework agnostic routing solution in the future. This would probably benefit both them and the community. It would probably cut their development time down by quite a bit, and it would allow users to use the components with more frameworks.

Supporting all these different custom routers which are moving targets doesn't seem to make much sense IMO.

**Comment by PaulOst** [comment]
I also would really love to see first class DX for SolidJS in the ionic UI framework and on equal footing with Vue, React, and Angular.

**Comment by Odas0R** [comment]
@liamdebeasi Can you point me/us in a direction of how one should implement a router to perform navigation animations?

I've mimicked most of Ionic components into SolidJS, got the `IonRouterLink` component going but I'm stuck on how should I implement the page transitions.

I believe I should create a _context_ so that I store all router data and perform the animations e.g `context.navigate(routerLink, ...)`.

Should I wrap the whole `App` with a `MyCustomRouter`?

```tsx
const App: Component = () => {
  return (
   <MyCustomRouter>
      <IonApp>
        <IonRouterOutlet />
      </IonApp>
   </MyCustomRouter>
  );
};
```

and then perform all the operations?

What would be like a pseudo-code to implement the router logic, any advice?

**Comment by liamdebeasi** [comment]
Hi everyone,

We greatly appreciate everyone who provided feedback on this feature request. The team revisited this feature request, and we do not have plans to implement SolidJS support for Ionic components at this time. You can still use Ionic components with SolidJS, but it means you are interacting with the Web Components directly and not Solid components.

We are happy to reconsider this decision in the future as SolidJS gains more popularity. However, we currently would like to focus our efforts on improving the experience of using Ionic with our existing integrations (Angular, React, and Vue). In general, we'd like to see the SolidJS community grow before we commit to adding a full SolidJS integration.

**Comment by PaulOst** [comment]
My company is disappointed that you are not planning support for SolidJS [as Solid components]. Wasn't 44 upvotes and 8 hearts enough after you sought community feedback? We have lots of existing projects built using React and some using Angular, but all new projects are being built using SolidJS. Please reconsider in the future.

**Comment by Odas0R** [comment]
> My company is disappointed that you are not planning support for SolidJS [as Solid components]. Wasn't 44 upvotes and 8 hearts enough after you sought community feedback? We have lots of existing projects built using React and some using Angular, but all new projects are being built using SolidJS. Please reconsider in the future.

I agree completely. I'm currently just using web components + solidjs on the side so it's okay.

But coming from React is a way better experience for us (we've too merged to solidjs)
