### ISSUE TITLE
feat(refresher): use refresher in custom scroll content

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#25977]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

`ion-refresher` should be attachable to custom scroll content, so it can be triggered independend of ion-content

### Describe the Use Case

I have an application with segments. Depending on which segment is selected, a corresponding scrollable element should be displayed in `ion-content`, so that the scroll positions of scroll areas are maintained when the segment is changed.

Currently when ion-refresher is next child of `ion-content`, the custom scroll-area get sometimes stuck if you scroll too fast.
Also sometimes the `ion-refresher` circle freezes and get stuck on screen.

This behavior can only be reproduces on native build (testet on ios)

### Describe Preferred Solution

`ion-refresher` is attachable to custom scroll content

### Related Code

https://stackblitz.com/edit/angular-3cg7gs

**Comment by liamdebeasi** [comment]
Do you have a sample reproduction?

**Comment by DwieDima** [comment]
Thank you for your response. I've wrapped both scroll content elements inside another div with the `.ion-content-scroll-host` class. 
Now `ion-refresher` won't trigger at all (see updated stackblitz).

**Comment by liamdebeasi** [comment]
Your StackBlitz still has two scrollable containers (the `.scroll-content` class) which could be causing the issue. The `.ion-content-scroll-host` should be placed on a single scrollable container.

```html
<div class="scroll-content ion-content-scroll-host">
  <div *ngIf="segment.value === 'dogs'">
    <div
      *ngFor="
        let something of [].constructor(20);
        let even = even;
        let i = index
      "
      [style.background]="even ? 'black' : 'yellow'"
      class="item"
    >
      <span>Dog {{ i }}</span>
    </div>
  </div>
  <div *ngIf="segment.value === 'cats'">
    <div
      *ngFor="
        let something of [].constructor(20);
        let even = even;
        let i = index
      "
      [style.background]="even ? 'blue' : 'grey'"
      class="item"
    >
      <span>Cat {{ i }}</span>
    </div>
  </div>
</div>
```

https://user-images.githubusercontent.com/2721089/191761095-ff6ed755-f490-40cf-83d2-fa3d6a379320.mov

**Comment by DwieDima** [comment]
With your code sample you'll lose the scroll position of cats and dogs (they have now the same scroll position).
My intention was to preserve the scroll position for cats and dogs.

- scroll dogs to Dog 15
- scoll cat to Cat 6
- change segment back to dog (is still 15)
- change segment back to car (is still 6)

**Comment by liamdebeasi** [comment]
IonContent + IonRefresher are not designed to be used with multiple scroll containers within a single `IonContent` instance. You could make it work by showing or hiding multiple `ion-content`, but that may have additional side effects when using features such as the collapsible large title:

```html
<ion-content [hidden]="segment.value !== 'dogs'">
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
  <div
    *ngFor="
      let something of [].constructor(20);
      let even = even;
      let i = index
    "
    [style.background]="even ? 'black' : 'yellow'"
    class="item"
  >
    <span>Dog {{ i }}</span>
  </div>
</ion-content>

<ion-content [hidden]="segment.value !== 'cats'">
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
  <div
    *ngFor="
      let something of [].constructor(20);
      let even = even;
      let i = index
    "
    [style.background]="even ? 'blue' : 'grey'"
    class="item"
  >
    <span>Cat {{ i }}</span>
  </div>
</ion-content>
```

If you need to use a single `IonContent`, then you could use JavaScript to cache and restore the scroll position. 

-----

Alternatively, it may be beneficial to align with how native segments behave. I attached two examples of segments in the iTunes Store app on iOS.

| main page | album page |
| ----------- | ----------- |
| <video src="https://user-images.githubusercontent.com/2721089/191800835-dbfa3f36-9fa5-4e91-86f0-eea424d7ca47.mp4"></video> | <video src="https://user-images.githubusercontent.com/2721089/191801657-9c135205-c1ed-4a1d-a84b-29c7de6e9575.mp4"></video> |

The "main page" example resets the scroll position on segment change, and the "album page" example has a shared scroll position.

We do not have plans to add the requested feature to Ionic at the moment.
