### ISSUE TITLE
bug: on some devices everything gets bigger when the app is downloaded from Play Store.

### ISSUE THREAD

**Issue by ionichelp** [ionic-team/ionic-framework#25983]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Only on some devices, when the app is downloaded from PlayStore, it gets closer to 25%. By the way, even the ads, everything is getting bigger.

<img src="https://user-images.githubusercontent.com/113116313/191476164-d011d754-97a0-41a7-9b04-884b56dd3f31.JPG" width="300">

### Expected Behavior

When I change the package name and send the apk to the same phone, it appears in normal size.

<img src="https://user-images.githubusercontent.com/113116313/191476211-627232f6-eca4-4dae-ad50-b63c76bdff8f.JPG" width="300">

### Steps to Reproduce

After installing the app on PlayStore, the problem started on some devices. As far as I can see it happens on Samsung Galaxy A72.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/user/.nvm/versions/node/v18.3.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.0
   @angular-devkit/build-angular : 14.1.0
   @angular-devkit/schematics    : 14.1.0
   @angular/cli                  : 14.1.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : 4.0.1

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.0) : 1.6.0

System:

   NodeJS : v18.3.0 (/Users/user/.nvm/versions/node/v18.3.0/bin/node)
   npm    : 8.19.1
   OS     : macOS Monterey

### Additional Information

I think it's related with game booster mod

https://www.reddit.com/r/assholedesign/comments/u9e9a5/pretty_sure_this_counts_mobile_ads_being_zoomed/

https://www.reddit.com/r/softwaregore/comments/odpnyc/this_mobile_games_ads_zoom_in_to_fit_my_phone/

https://www.reddit.com/r/StarTrekTimelines/comments/omuoyx/new_scummy_trend_with_ads_intentionally_zoomed_in/

**Comment by liamdebeasi** [comment]
Thanks for the issue. Are you able to identify an Ionic-related part of your app that could be responsible for this? I would also recommend checking the "Display size" setting in Settings -> Display.

**Comment by ionichelp** [comment]
Hey @liamdebeasi thanks for your reply.  Actually i'm not sure this problem is related to Ionic, i wanted to get some support from your experience here. 

These two screenshots were taken on the same phone, same apk and same day. The only difference between them is the package names. So if it was related to device settings, I would expect both apks to be problematic.

The other difference between them is the Game Booster mode found in the Samsung Galaxy series. If you pay attention to the zoomed version, there is an icon for it under the tabs. This mod started to open when the application was published on the Play Store. By the way, I thought for a while that the problem was in my code, but I noticed that the ads also have zoom.

<div>
<img src="https://user-images.githubusercontent.com/113116313/191476211-627232f6-eca4-4dae-ad50-b63c76bdff8f.JPG" width="300">

<img src="https://user-images.githubusercontent.com/113116313/191476164-d011d754-97a0-41a7-9b04-884b56dd3f31.JPG" width="300">
</div>

**Comment by liamdebeasi** [comment]
Hey there,

Unfortunately we do not provide support for general development issues. I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/) instead. One thing that may help is figuring out where the scaling exists: Is there CSS being applied or this a system-level modification?

If you are able to identify something in Ionic Framework that is causing this issue, feel free to reply and I can take another look.
