### ISSUE TITLE
feat: allow specifying a time along with multiple date selection

### ISSUE THREAD

**Issue by manu2504** [ionic-team/ionic-framework#25989]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The ion-datetime component allows to select a date and a time in the same view. Since Ionic 6.2, selecting multiple dates is possible, but the time selection is not possible in that case in the same datetime input, meaning the time selection must be created in another datetime component with `presentation="time"`.

Could we allow time selection when selecting multiple dates with `multiple="true"`?

### Describe the Use Case

One typical use case is selecting a recurring event that occur at a set time (eg. shifts every day from Mon-Fri that start at 9.30)

### Describe Preferred Solution

```html
<ion-datetime
  [multiple]="true"
  [value]="[['2022-06-03', '2022-06-13', '2022-06-29'], '09:30']"
></ion-datetime>
```
Note the absence of the `presentation="date"` attribute in the above example.

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please clarify your use case for selecting a time with multiple dates? The multiple date selection feature is currently only intended to work with date selection.

**Comment by liamdebeasi** [comment]
Thanks for the additional information. Do you have examples of apps/websites that implement this pattern?
