### ISSUE TITLE
bug: Tab bar is unhidden too quickly after keyboard dismiss

### ISSUE THREAD

**Issue by milanharia** [ionic-team/ionic-framework#25990]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When the keyboard is dismissed the tab bar temporarily flashes on the screen as it is unhidden before the webview has expanded back to the full size of the viewport.

https://user-images.githubusercontent.com/76167627/191752633-e4068d12-a205-421b-9005-ba5194948679.mp4

### Expected Behavior

The tab bar should not be unhidden until the web view has expanded back to its full size so that the tab bar does not flash in the center of the screen.

### Steps to Reproduce

Use the default capacitor keyboard config:
```
// capacitor-config.ts
Keyboard: {
    resize: KeyboardResize.Native,
    resizeOnFullScreen: true,
},
```
This happens on any page with an `IonTabBar`.

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.2.8

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : not installed
   @capacitor/core    : 4.3.0
   @capacitor/ios     : 4.3.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.0

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.7.0
   OS     : macOS Monterey

**Comment by maccman** [comment]
We just ran into this too (cc @mlynch )

**Comment by vojto** [comment]
Still breaking in 6.3.8.

**Comment by aginvlad** [comment]
Same for me in 6.3.9
I temporarily fixed it with Capacitor Keyboard

```
useEffect(() => {
    Keyboard.addListener('keyboardWillShow', () => setKeyboardShown(true));
    Keyboard.addListener('keyboardWillHide', () =>
      setTimeout(() => {
        setKeyboardShown(false);
      }, 10)
    );

    return () => {
      Keyboard.removeAllListeners();
    };
  }, []);
```

And then provided `keyboardShown` variable to IonTab `hidden` prop

**Comment by milanharia** [comment]
@aginvlad thanks for sharing. I seem to see the tab bar flash still because the tab bar is being unhidden a little too soon so I have changed the timeout delay to 100ms and seems to work consistently. The full code for anybody interested:

```
const App: React.FC = () => {
  const [keyboardIsOpen, setKeyboardIsOpen] = useState(false);

  useEffect(() => {
    Keyboard.addListener("keyboardWillShow", () => {
      setKeyboardIsOpen(true);
    });
    Keyboard.addListener("keyboardWillHide", () => {
      setTimeout(() => setKeyboardIsOpen(false), 100);
    });

    return () => {
      Keyboard.removeAllListeners();
    };
  }, []);

  return (
    <IonApp>
      <IonReactRouter>
        <IonTabs>
          <IonRouterOutlet>
            <Route exact path="/tab1">
              <Tab1 />
            </Route>
            <Route exact path="/tab2">
              <Tab2 />
            </Route>
            <Route path="/tab3">
              <Tab3 />
            </Route>
            <Route exact path="/">
              <Redirect to="/tab1" />
            </Route>
          </IonRouterOutlet>
          <IonTabBar hidden={keyboardIsOpen} slot="bottom">
            <IonTabButton tab="tab1" href="/tab1">
              <IonIcon icon={triangle} />
              <IonLabel>Tab 1</IonLabel>
            </IonTabButton>
            <IonTabButton tab="tab2" href="/tab2">
              <IonIcon icon={ellipse} />
              <IonLabel>Tab 2</IonLabel>
            </IonTabButton>
            <IonTabButton tab="tab3" href="/tab3">
              <IonIcon icon={square} />
              <IonLabel>Tab 3</IonLabel>
            </IonTabButton>
          </IonTabBar>
        </IonTabs>
      </IonReactRouter>
    </IonApp>
  );
};

export default App;
``` 

@liamdebeasi can you give any insight into when this issue will be resolved in production?

**Comment by vojto** [comment]
> Still breaking in 6.3.8.

No improvement in 6.4.2.

**Comment by maccman** [comment]
@mlynch this one seems worth looking at :)

**Comment by mlynch** [comment]
@maccman talked to the team and it's currently being looked at. Hope to have an update soon

**Comment by informatikTirol** [comment]
I have the same issue with Ionic 7, see #27386

**Comment by liamdebeasi** [comment]
Can everyone try the following dev build and let me know if it resolves the issue?

```
7.0.6-dev.11683570324.1500173d
```

Install Example:

```
npm install @ionic/angular@7.0.6-dev.11683570324.1500173d
```

**Comment by informatikTirol** [comment]
> Can everyone try the following dev build and let me know if it resolves the issue?
> 
> ```
> 7.0.6-dev.11683572927.1bfe3920
> ```
> 
> Install Example:
> 
> ```
> npm install @ionic/angular@7.0.6-dev.11683572927.1bfe3920
> ```

HI @liamdebeasi, the problem still exists for me after installing "7.0.6-dev.11683572927.1bfe3920".

**Comment by liamdebeasi** [comment]
Can you run `npm ls @ionic/core` and provide the result? Also, do you have a screen recording of the issue with the dev build installed?

**Comment by informatikTirol** [comment]
Here you go

` npm ls @ionic/core
`

`
└─┬ @ionic/angular@7.0.6-dev.11683572927.1bfe3920
  └── @ionic/core@7.0.6-dev.11683572927.1bfe3920
`



https://github.com/ionic-team/ionic-framework/assets/16346085/88a3d1cf-d1a5-47d6-a2d6-caad7c1bfdb5

**Comment by liamdebeasi** [comment]
Thanks! Can you send over a sample app that reproduces the issue? The sample app I have no longer reproduces the issue with the dev build installed.

**Comment by informatikTirol** [comment]
Here a minimal reproduction: 
https://www.dropbox.com/s/ut6xwokezcmeww0/IONIC7Flicker_GithubIssue_25990.zip?dl=0

**Comment by informatikTirol** [comment]
Here a minimal reproduction: 
https://www.dropbox.com/s/ut6xwokezcmeww0/IONIC7Flicker_GithubIssue_25990.zip?dl=0

**Comment by liamdebeasi** [comment]
The issue appears resolved when using the dev build and your sample reproduction:

https://github.com/ionic-team/ionic-framework/assets/2721089/20757f02-6f92-451d-98ba-dc7db24aed4b

Can you make sure you do a clean build/sync when testing in your application?

```
npm run build && npx cap copy ios
```

**Comment by informatikTirol** [comment]
It is better, but not completely gone. 
It seems to me that it happens even more often when using "ion-split-pane" with "tabs", at least the APP "https://github.com/ionic-team/ionic-framework/issues/25990#issuecomment-1540108855" flickers more...

**Comment by liamdebeasi** [comment]
Do you have an example of this issue happening when using split pane?

**Comment by informatikTirol** [comment]
Here is the App with the split pane. I removed a few packages, so 
`npm install`
should work on your machine. 

https://www.dropbox.com/s/qbr278uqe8x9p5r/APP_RL_GITHUB_ISSUE_25990_2.zip?dl=0

Please a short response, then I will delete the File, thanks!

Here you see the bug:
![zglx](https://github.com/ionic-team/ionic-framework/assets/16346085/4993330a-ebd7-4b53-b6a4-b353d5b6ab1e)


Most likely the error occurs when going from tab 1 to tab 2, then directly activating the input.

**Comment by liamdebeasi** [comment]
Thanks for testing. I think I have resolved the lingering issues if you are interested in giving this another test:

```
npm install @ionic/angular@7.0.6-dev.11683905366.13943af0
```

**Comment by informatikTirol** [comment]
Works, thank you!
