### ISSUE TITLE
bug: Ion-chip outline does not have enough contrast in dark mode

### ISSUE THREAD

**Issue by enriqueloz88** [ionic-team/ionic-framework#25997]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

There is not much more to say apart from the description of the title. In light mode it is seen correctly, but in dark mode the lines and icons inside the chip are not distinguishable:

Light mode:
![image](https://user-images.githubusercontent.com/61509169/191959487-72b6d764-48d3-4e4b-b1d7-c3abd4cd42fa.png)

Dark mode:
![image](https://user-images.githubusercontent.com/61509169/191959538-b6ee035f-023a-4868-9693-1b4e52a53028.png)

### Expected Behavior

The chip in dark mode should look something like this:

![image](https://user-images.githubusercontent.com/61509169/191959734-532ca6a4-68fb-4ca9-864f-bd939ba76c8b.png)

### Steps to Reproduce

Just insert this anywhere inside your ionic app, with the dark mode activated:

```
    <ion-chip [outline]="true">
      <ion-label>Label</ion-label>
      <ion-icon name="caret-down"></ion-icon>
    </ion-chip>
```

### Ionic Info

   Ionic CLI                     : 6.20.1 (C:\Users\kikel\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.6
   @angular-devkit/build-angular : 14.2.1
   @angular-devkit/schematics    : 14.2.1
   @angular/cli                  : 14.2.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.2.0
   @capacitor/android : 4.2.0
   @capacitor/core    : 4.2.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.11.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. Here is a dev build with a proposed fix if you are interested in testing: 

```
npm install @ionic/angular@6.2.9-dev.11663945723.1ffc0d88
```

**Comment by enriqueloz88** [comment]
Thank you very much! Now it looks correct

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/25998, and a fix will be available in an upcoming release of Ionic Framework.
