### ISSUE TITLE
bug: datetime, multiple ionChange emissions and incorrect display on Vue3

### ISSUE THREAD

**Issue by brunoinds** [ionic-team/ionic-framework#26007]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Same bug of #24967, still reproduciable in Vue

### Expected Behavior

Same bug of #24967, still reproduciable in Vue

### Steps to Reproduce

Same bug of #24967, still reproduciable in Vue

### Ionic Info

[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - C:\Users\Bruno\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Bruno\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Bruno\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Bruno\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.19.1 (C:\Users\Bruno\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.2.6

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : not installed
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v14.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.12.0
   OS     : Windows 10

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
