### ISSUE TITLE
bug: Ionic toolbar triggers popover out of viewport when app is inside a div

### ISSUE THREAD

**Issue by zeuscronos** [ionic-team/ionic-framework#26016]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

If we enclose an `Ionic 6` app inside a `DIV` with a toolbar with a button at the end which opens up a popover, the popover is not inside the viewable area as you can see on the image below:

![image](https://user-images.githubusercontent.com/3321307/192321121-c09b2cc2-d47e-4870-ab51-e95efaae7273.png)

### Expected Behavior

The popover should appear inside the viewable area.

### Steps to Reproduce

- Create new project with:
```
$ ionic start happy-meal tabs --type=react
```

- Then replace the content of file: `App.tsx` with:
```
import {
  IonApp,
  IonButton,
  IonButtons,
  IonContent,
  IonHeader,
  IonPage,
  IonRow,
  IonTitle,
  IonToolbar,
  setupIonicReact,
  useIonPopover
} from '@ionic/react';

/* Core CSS required for Ionic components to work properly */
import '@ionic/react/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css';
import '@ionic/react/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/react/css/padding.css';
import '@ionic/react/css/float-elements.css';
import '@ionic/react/css/text-alignment.css';
import '@ionic/react/css/text-transformation.css';
import '@ionic/react/css/flex-utils.css';
import '@ionic/react/css/display.css';

/* Theme variables */
import './theme/variables.css';

setupIonicReact();

const Navbar = () => {
  const Popover = () => <IonContent className="ion-padding">Hello World!</IonContent>;
  const [present, dismiss] = useIonPopover(Popover, {
    onDismiss: (data: any, role: string) => dismiss(data, role),
  });
  return (
    <IonHeader>
      <IonToolbar>
        <IonTitle size="large">Happy Meal</IonTitle>
        <IonButtons slot="end">
          <IonButton onClick={
            (e: any) => present({
              event: e,
            })
          }>Menu</IonButton>
        </IonButtons>
      </IonToolbar>
    </IonHeader>
  );
};

const Screen = () => {
  return (
    <IonPage>
      <Navbar />
      <IonContent fullscreen>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Screen</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonRow>
          You are on the main Screen.
        </IonRow>
      </IonContent>
    </IonPage>
  );
};

const App = () =>
  <div style={{ textAlign: 'center' }}>
    <div style={{
      display: 'inline-block',
      margin: '20px auto',
      textAlign: 'left',
      position: 'relative',
      width: '400px',
      height: '750px',
      fontSize: '0.9em',
      border: 'solid 2px #bfbfbf',
    }}>
      <IonApp>
        <Screen />
      </IonApp>
    </div>
  </div>;

export default App;
```

- Then run the app.

- Then click the `MENU` button at the end of the toolbar.

- You will see that the popover is not inside the viewable area.

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.1 (C:\Users\Will\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.2.7

Capacitor:

   Capacitor CLI      : 4.2.0
   @capacitor/android : not installed
   @capacitor/core    : 4.2.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.0

System:

   NodeJS : v16.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.15.0
   OS     : Windows 10
```

**Comment by sean-perkins** [comment]
@zeuscronos the popover uses `position: fixed`, as it expects `ion-app` to fill the entire viewport. 

Can you explain your use case in more detail? I may be able to suggest an alternative implementation pattern to solve your challenge.

**Comment by zeuscronos** [comment]
@sean-perkins you gave me an idea. I think I'm gonna wrap the app into an iframe instead. Something similar to what you guys have on the documentation, where you wrap the examples inside an iframe. Thank you!

**Comment by zeuscronos** [comment]
Using an iframe did the trick.
