### ISSUE TITLE
bug: Safari overscroll prevents sheet modal to close

### ISSUE THREAD

**Issue by iBobik** [ionic-team/ionic-framework#26040]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When app is opened in iOS Safari it is not possible to close by swipe sheet modal.

When touch is started on sheet header it almost always trigger bounce so can never be closed. When touch is started on the sheet content it triggers bounce only sometimes (in demo sometimes, but in my app always).

Video:
https://user-images.githubusercontent.com/614232/193016884-b940c70e-51ed-4de6-8ed2-7efff37be916.MP4

### Expected Behavior

Bounce will not be triggered like in native apps.

### Steps to Reproduce

1. Open [demo](https://ionicframework.com/docs/usage/modal/card/basic/demo.html?ionic:mode=ios)
2. Open modal
3. Try to close it by swipe down on modal header

### Code Reproduction URL

https://ionicframework.com/docs/usage/modal/card/basic/demo.html?ionic:mode=ios

### Ionic Info

```
> npx ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.
```
(But I am, maybe because I does not use Ionic CLI, but Vue CLI?)

### Additional Information

It bounces only when browser tab is newly created. When you switch to another tab and return it stops bouncing and behaves as expected.

**Comment by liamdebeasi** [comment]
Thanks for the report. What version of iOS are you testing this on? I am testing this on iOS 16 and I cannot reproduce the reported behavior.

**Comment by iBobik** [comment]
I currently use 16.0, but found it few weeks ago on previous one.

29. 9. 2022 17:07:51, Liam DeBeasi ***@***.***> napsal:

**Comment by liamdebeasi** [comment]
This is the behavior I see on my end:

https://user-images.githubusercontent.com/2721089/193070240-0ee7e716-87e9-438e-bae7-4b257d97b4fc.mp4


What device are you testing this on?

**Comment by iBobik** [comment]
Are you sure you tried it in the new tab where you copied the URL? On my side when tab is not new (has history or reload of the same page) it works well.

**Comment by iBobik** [comment]
Btw, just updated to iOS 16.0.2, behaves the same.

**Comment by liamdebeasi** [comment]
I tried in a new tab and a tab with history, and neither reproduced the issue. I was testing on the iOS 16.1 beta, but I was unable to reproduce the issue on iOS 15.6 as well.
