### ISSUE TITLE
bug: 6.19.1 Swipe Back broken in IOS React

### ISSUE THREAD

**Issue by javiersoto15** [ionic-team/ionic-framework#26058]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When swiping back using the gesture the navigation does a weird animation that goes back different pages. Sometimes it lands in the page previous the one it's expected (2 pages before)

### Expected Behavior

The swipe right gesture to go back should return to the previous page

### Steps to Reproduce

Can't share the code, button is using router link to direct to the page. The pages are defined in the App.tsx as recommended in the ionic react navigation doc. See gif for a visual representation

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.1 (/Users/javiersoto/.nvm/versions/node/v18.3.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.2.1

Capacitor:

   Capacitor CLI      : 3.7.0
   @capacitor/android : not installed
   @capacitor/core    : 3.7.0
   @capacitor/ios     : 3.7.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v18.3.0 (/Users/javiersoto/.nvm/versions/node/v18.3.0/bin/node)
   npm    : 8.12.1
   OS     : macOS Monterey

### Additional Information

https://user-images.githubusercontent.com/25832599/193340839-55fb19df-f80c-4497-9df9-fb35fdcd1d7d.mov

This is the behavior i am seeing

**Comment by sean-perkins** [comment]
@javiersoto15 can you create reproduction that mimics the routing structure you have in your application? Without a reproduction, it is difficult for the team to diagnose the issue. An Ionic starter that has a few basic pages that can reproduce the problem is all that we would need. 

Also, is this a recent change in behavior you are observing or does it happen on any published v6 version of Ionic?

**Comment by heblol** [comment]
Hi there, I have the same. 

```
// This is my routing component. Im kinda new to IonicFramework (used CapacitorJS before). I added this to my existing React Website. Also using MUI

function Routing() {
  const currentUser = useSelector(selectCurrentUser);

  return (
    <IonApp>
      <IonReactRouter>
        <IonRouterOutlet>
          <Route path="/" exact>
            <IonPageWrapper title="Home">
              <NewPage />
            </IonPageWrapper>
          </Route>
          <Route path="/about" exact>
            <IonPageWrapper title="About">
              <SecondPage />
            </IonPageWrapper>
          </Route>
        </IonRouterOutlet>
      </IonReactRouter>
    </IonApp>
  );
}

function IonPageWrapper({
  title,
  children,
}: PropsWithChildren<{ title: string }>) {
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonButtons slot="start">
            <IonBackButton />
          </IonButtons>
          <IonTitle>{title}</IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent>{children}</IonContent>
    </IonPage>
  );
}
```

This is my package.json
```
"dependencies": {
    "@auth0/auth0-react": "^1.5.0",
    "@auth0/cordova": "^0.4.4",
    "@awesome-cordova-plugins/app-version": "^5.41.0",
    "@bugsnag/js": "^7.16.2",
    "@bugsnag/plugin-react": "^7.16.2",
    "@capacitor/android": "^3.0.0",
    "@capacitor/app": "^1.0.0",
    "@capacitor/browser": "^1.0.3",
    "@capacitor/cli": "^3.0.0",
    "@capacitor/core": "^3.0.0",
    "@capacitor/device": "^1.0.0",
    "@capacitor/haptics": "^1.1.0",
    "@capacitor/ios": "^3.0.0",
    "@capacitor/keyboard": "^1.1.2",
    "@capacitor/network": "^1.0.7",
    "@capacitor/push-notifications": "^1.0.8",
    "@capacitor/share": "^1.1.2",
    "@capacitor/storage": "^1.0.0",
    "@date-io/moment": "^1.3.13",
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@ionic-native/safari-view-controller": "^5.36.0",
    "@ionic/react": "^6.2.9",
    "@ionic/react-router": "^6.2.9",
    "@ionic/storage": "^3.0.4",
    "@mui/base": "^5.0.0-alpha.69",
    "@mui/icons-material": "^5.4.1",
    "@mui/joy": "^5.0.0-alpha.44",
    "@mui/lab": "^5.0.0-alpha.46",
    "@mui/material": "^5.0.0-rc.1",
    "@mui/styles": "^5.0.0-rc.1",
    "@mui/x-data-grid": "^5.11.0",
    "@reduxjs/toolkit": "^1.7.1",
    "@rtk-query/graphql-request-base-query": "^2.1.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "Base64": "^1.1.0",
    "auth0-js": "^9.16.2",
    "axios": "^0.23.0",
    "bootstrap": "^5.0.0",
    "cordova-plugin-app-version": "^0.1.14",
    "cordova-plugin-customurlscheme": "^5.0.2",
    "cordova-plugin-safariviewcontroller": "^2.0.0",
    "crypto-js": "^4.0.0",
    "crypto-random-string": "^1.0.0",
    "dayjs": "^1.11.2",
    "dotenv": "^9.0.2",
    "env-cmd": "^10.1.0",
    "firebase": "^8.6.2",
    "firebase-functions": "^3.15.7",
    "formik": "^2.2.9",
    "graphql": "^15.5.0",
    "graphql-request": "^4.3.0",
    "graphql-ws": "^5.10.1",
    "lint-staged": "^10.5.4",
    "localforage": "^1.10.0",
    "moment": "^2.29.1",
    "numeric-keyboard": "^0.7.0",
    "prettier": "^2.6.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-markdown": "^8.0.2",
    "react-redux": "^7.2.6",
    "react-router-dom": "5.3.3",
    "react-scripts": "4.0.3",
    "react-swipeable-views": "^0.14.0",
    "react-toastify": "9.0.3",
    "redux": "^4.1.2",
    "redux-persist": "^6.0.0",
    "source-map-explorer": "^2.5.2",
    "swiper": "6.8.4",
    "typescript": "^4.3.2",
    "web-vitals": "^1.0.1",
    "winston": "^3.6.0",
    "yup": "^0.32.11"
  },
```

**Comment by javiersoto15** [comment]
@sean-perkins the above case would that work? It's a simplified version of what I have, if not, I can work on a full sample app this week and send it to you guys

**Comment by liamdebeasi** [comment]
A code snippet and a `package.json` does not tell us much about how the app is structured, so having a runnable app would be very helpful.
