### ISSUE TITLE
bug: iOS 16 layout is lag and black out happens 

### ISSUE THREAD

**Issue by dodomui** [ionic-team/ionic-framework#26064]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

After upgrade to iOS 16, the App layout is lagging and it happens black out on parts of the screen randomly.
It could be solved by waiting and sometime it need to leave and reenter the view only can display the layout properly.

### Expected Behavior

The app is working just fine on others iOS version and platform.
But after upgrade of iOS 16.0 / 16.0.2, the layout starting went wrong.
It should works as other iOS version or platform. Which no lagging of layout and no black out happens.

### Steps to Reproduce

Tried to run on iOS 16.0 and iOS 16.0.2, the black out can happens within several steps.

### Ionic Info

Nothing happens when I ran ionic info. No any msg / error return.

ionic version return 
6.20.2

### Additional Information
Not sure this issue is related to ionic / capacitor. Therefore I had submitted both places.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
