### ISSUE TITLE
feat: add toggle's `enableOnOffLabels` to config

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#26082]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Expose `toggleEnableOnOffLabels` in ionic config

### Describe the Use Case

I want to have consistency in my app without adding `enableOnOffLabels` to every single toggle. It would be great to be able to configure it via the ionic config.

**Comment by sean-perkins** [comment]
Thanks for this feature request @EinfachHans! 

We originally had this in our "nice to haves" with the feature scope in 6.2. Likely the property would following existing config key naming conventions, so: `onOffLabelsEnabled`. 

I'll include our comments around this, if anyone is interested in working on this feature prior to the team having time to work on it. 

**Dev notes**

The on/off appearance should be a global config option that developers can configure from `IonicConfig`, to apply for all toggles. 
 - This will simplify the implementation for developers as well as make the integration with an Accessibility plugin much easier.
 - Usage: `window.Ionic.config.onOffLabelsEnabled = true;`
   - Accessed via: `config.get('onOffLabelsEnabled')` in the implementation.
 - Default value should be `undefined`.

**Comment by EinfachHans** [comment]
PR created ✌🏼

**Comment by amandaejohnston** [comment]
This feature has been added in https://github.com/ionic-team/ionic-framework/pull/26087 and will be available in the upcoming 6.4 release. Thanks again for the PR!
