### ISSUE TITLE
`disabled` and form-associated custom elements

### ISSUE THREAD

**Issue by bennypowers** [ionic-team/ionic-framework#26096]
**Ionic version:**
The form-associated custom elements spec [goes out of its way to break](https://github.com/whatwg/html/issues/8365#issuecomment-1271259061) the long standing practice of reflecting `disabled` as a boolean attribute. Ionic will have to remove that attr reflection when it wires up FACEs.

**Current behavior:**
Elements reflect `disabled`

**Expected behavior:**
Elements don't reflect `disabled`

**Other information:**
The long-established practice of reflecting `disabled` as an attribute on the host element will break form-associated custom elements. See above-linked thread for details.

**Comment by liamdebeasi** [comment]
Thanks for the report, Benny. I appreciate the heads up about this. At the moment we do not have plans to integrate with form-associated custom elements, but we will definitely keep this in mind if we move forward with FACEs in the future. I am going to close this for now, but let me know if you have any questions. Thanks!
