### ISSUE TITLE
bug:unhandled exception occurred: getaddrinfo ENOTFOUND localhost

### ISSUE THREAD

**Issue by edocbuhtig** [ionic-team/ionic-framework#26091]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

ionic serve command  throwing error:
```
\W$: ionic serve
> ng run app:serve --host=localhost --port=8100
[ng] An unhandled exception occurred: getaddrinfo ENOTFOUND localhost

### Expected Behavior

ionic serve should boot a dev server and run the default base blank template ionic theme app in the browser.

### Steps to Reproduce

Create a new  ionic 6.x Blank project and in the terminal run `ionic serve`you get below error in cli terminal

### Code Reproduction URL

_No response_

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.0
   @angular-devkit/build-angular : 14.2.5
   @angular-devkit/schematics    : 14.2.5
   @angular/cli                  : 14.2.5
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : not installed
   @capacitor/core    : 4.3.0
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.7.1

System:

   NodeJS : v16.17.1 (/usr/local/bin/node)
   npm    : 8.15.0
   OS     : macOS Monterey12.6
`


### Additional Information

\W $node
Welcome to Node.js v16.17.1.
Type ".help" for more information.
>

**Comment by liamdebeasi** [comment]
Thanks for the issue. The error appears to be coming from the Angular CLI, not the Ionic CLI (The Ionic CLI will call the Angular CLI for you). This is more of a support question, so I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/).
