### ISSUE TITLE
feat: Style the IonRefresher 

### ISSUE THREAD

**Issue by SaroGFX** [ionic-team/ionic-framework#26098]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Changing the color is possible and shows find in the browser. But on the emulator, the refresher background will overlay. Cannot be controlled with z-Index. 

### Describe the Use Case

Changing the background, without changing the whole page background. This is needed when the re-fresher is inside of a different color header. 

![f491379e45b56cb5e5aedabb9d961092aae55a97_2_690x307](https://user-images.githubusercontent.com/3781800/195117116-0553c502-fcb7-49a6-9eaf-74bc0e558206.jpeg)

It works perfect in browser ( made IonRefresher purple for comparison)

![Screenshot 2022-10-11 at 16 41 35](https://user-images.githubusercontent.com/3781800/195122285-aca4c5ec-aa36-4054-802e-ac5a388e37c3.png)

### Describe Preferred Solution

Being able to style the background (CSS) without the ion-refresher overlaying everything. 

```scss

ion-refresher:global(.ios) {

        ion-refresher-content {
            background-color: var(--dark-gray);
        }

        :global(.refresher-pulling-icon) {
            color: white;
        }

        ion-spinner {
            color: white;
        }
}
```

### Describe Alternatives

Putting the ion-refresher inside a component, which then inherits that color, could also be an option.

### Reproduction repo
https://github.com/SaroGFX/ion-refresher-styles

**Comment by liamdebeasi** [comment]
Did you push your code changes? I only see a blank repo.

**Comment by SaroGFX** [comment]
@liamdebeasi Sorry about that, something went wrong indeed, should be fixed. 

The repo is just from the demo, all my changes are in here: https://github.com/SaroGFX/ion-refresher-colors/blob/master/src/theme/styles.css

**Comment by liamdebeasi** [comment]
Hey there,

Apologies for the delay. Is you repo still public? I cannot access it anymore: https://github.com/SaroGFX/ion-refresher-colors/

**Comment by SaroGFX** [comment]
@liamdebeasi , apologies again, should be public now.

**Comment by liamdebeasi** [comment]
Hey there,

Apologies for the delay. I took a look at your application, and I can reproduce the reported behavior. Can you help me understand why the refresher needs a background color for this use case? This is the layout you provided in the original post:

![image](https://user-images.githubusercontent.com/2721089/204613569-80db00a9-088b-4aa4-a520-c8db18653c93.png)

In this case, that darker toned background should be applied on a background element, not the refresher. I revised the `Home.tsx` file to have the following content:

```tsx
<IonContent fullscreen>
  <div className="welcome-hero">
    Welcome, User
  </div>
  <IonRefresher slot="fixed" onIonRefresh={refresh}>
    <IonRefresherContent></IonRefresherContent>
  </IonRefresher>

  <IonList>
    {messages.map(m => <MessageListItem key={m.id} message={m} />)}
  </IonList>
</IonContent>
```

This change resulted in the following behavior: <video src="https://user-images.githubusercontent.com/2721089/204615350-e869a6c4-ee77-409e-9c4a-2c9644cb866b.mp4"></video>

The refresher no longer has a background color, so it does not overlap with the content.

As an alternative, if you want to give the appearance that the darker toned background "expands" when you pull to refresh, you could set `--background` on `ion-content`. That change results in the following behavior:

https://user-images.githubusercontent.com/2721089/204615124-4624dcfa-984b-4ca5-90a6-ad304c726565.mp4

Can you try one of these approaches and let me know if it resolves the issue?

**Comment by SaroGFX** [comment]
Hi @liamdebeasi, thank you for taking the time looking into this.

Unfortunately I can't get the same result, could you share your steps?

**I tried this with the following steps:**

1. Create a new Ionic project with the 'list' starter template
2. Added the .welcome-hero `div` in `Home.tsx`
3. Added these styles 

```css
.welcome-hero {
    background: gray;
    color: white;
    height: 100px;  
}

ion-content {
    --background: gray;
}
```

And this is my result (Chrome and Safari): 


https://user-images.githubusercontent.com/3781800/204645485-71f8408f-5af0-4c8e-9c32-e4cee9b7a50e.mov



Very curious how you did this and got a different result!

**Comment by liamdebeasi** [comment]
You are using a different refresher style. The [Native Refresher Docs](https://ionicframework.com/docs/api/refresher#native-refreshers) explains the difference.

The native refresher for iOS is only available when running on an iOS device or simulator. This is the refresher style I was demoing in https://github.com/ionic-team/ionic-framework/issues/26098#issuecomment-1331112083 and what the original issue referenced ("But on the emulator, the refresher background will overlay.")

When running in a browser, even if that browser is Safari, you will get the legacy/non-native refresher. If you are deploying to both iOS as well as desktop you will need to account for both variants in slightly different ways due to how each style is constructed. We expose the "refresher-native" class on `ion-refresher` for this purpose.

You can also force the refresher to _only_ use a particular style by setting the `pullingIcon` property on `ion-refresher-content`. This may be preferable due to how your page is laid out.
