### ISSUE TITLE
bug: firefox, arrow keys moves wheel picker by more than 1 element

### ISSUE THREAD

**Issue by DeyBo** [ionic-team/ionic-framework#26104]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hello !

I'm working on accessibility of my app and i'm facing a weird issue...

See in this video (took from [ion-datetime doc](https://ionicframework.com/docs/api/datetime)) :
https://user-images.githubusercontent.com/32773025/195287493-a7527643-5add-4714-8f0f-c1b821c66fe6.mov

This was tested on Google Chrome and Firefox, and on Windows and MacOS, it appears only on Firefox for all OS.

### Expected Behavior

I think the expected behavior is to change by 1 and not by 2 😄 

### Steps to Reproduce

To reproduce :
- Open this page  [ion-datetime doc](https://ionicframework.com/docs/api/datetime) on Firefox ;
- On datetime wheel, pass into with TAB and use arrow keys to navigate into values.

### Code Reproduction URL

https://ionicframework.com/docs/api/datetime

### Ionic Info

N/A (Ionic Docs)

**Comment by liamdebeasi** [comment]
Thanks for the report. This is a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1719330 I recommend posting on that thread if this is an important fix for you.

**Comment by liamdebeasi** [comment]
Hey there,

This issue has been fixed according to https://bugzilla.mozilla.org/show_bug.cgi?id=1719330, so I am going to close this.
