### ISSUE TITLE
bug: sheet modal jumps to max breakpoint on dismiss

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#26108]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The sheet modal dismiss animation is buggy. May be relevant for card and normal modal as well?

### Expected Behavior

To not jump to the top before dismissing

### Steps to Reproduce

1. Open Stackblitz
2. Open MOdal via Button
3. Dismiss via Backdrop Click

### Code Reproduction URL

https://ionic6-angular13-knmztx.stackblitz.io

### Ionic Info

See stackblitz

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you try the following dev build and let me know if it resolves the issue?

```
npm install @ionic/angular@6.3.2-dev.11665599303.178cf126
```

Note: You may need to install this in a local Ionic app as StackBlitz sometimes has trouble installing dev builds.

**Comment by EinfachHans** [comment]
@liamdebeasi works, thanks!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26110, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by jadsy2107** [comment]
Can confirm that i was having an issue with modal dismiss when it had an initial breakpoint 0.4 and breakpoints [0,0.4]
On dismiss , it would start the dismiss animation as if the modal was breakpoint 1

now with npm install @ionic/angular@6.3.2-dev.11665599303.178cf126
issue is resolved, thank you @liamdebeasi
