### ISSUE TITLE
Request more documentation and example(s) for 6.x VanillaJS "Navigation/Routing" of Ionic Docs

### ISSUE THREAD

**Issue by 1618employment** [ionic-team/ionic-framework#26115]
I can't tell if there is an "issue/bug" or if I am just doing it wrong  because there isn't adequate documentation for VanillaJS "Routing and Navigation" comparable to the Angular, React, and Vue sections of Docs.

When I use the following in index.html it works as expected, no issues...

```
    <ion-app>

        <ion-router>

	    <ion-route url="/" component="home-view"></ion-route>

        </ion-router>

        <ion-router-outlet></ion-router-outlet>

    </ion-app>

```

However when I create an "app-root" component (similar to the ionic-stencil-conference-app example) and move this code to it and then insert the "app-root" component into index.html it no longer routes as expected and instead I get an empty "slot"?

I suspect I'm missing something, but despite looking all over the internet I am unable to determine what because of the lack of documentation.

Yes I realize Vanilla JS is not a popular as Angular, React, and Vue so isn't a top priority.

Thank You!

**Comment by 1618employment** [comment]
I found a similar "issue"...[#24664](https://github.com/ionic-team/ionic-framework/pull/24664)

but doesn't appear to resolve my issue?

**Comment by 1618employment** [comment]
So I'm catching up, "ion-router-outlet" isn't for vanilla or framework-less projects and I'm suppose to use "ion-nav" or "ion-tab".

But what's the point of using "ion-router" with "ion-nav" or "ion-tab" in this way (html), because as far as I can tell I'm losing dynamic or url parameter based routing? 

Whichever "ion-tab" I place first under "ionic-tabs" is my "landing page" regardless of what "ion-route" plural are in my "ion-router"

How do I keep the dynamic behavior of "ion-router-outlet" without a framework? And why does it work correctly if I do it in index.html?

What isn't getting passed down from index.html to my custom component (app-root) to make this work?

**Comment by 1618employment** [comment]
[Repo](https://github.com/1618employment/ionic-router-issue) as requested

So after further analysis it appears all routing components (router-outlet, nav, and tabs) do not work from my Lit web component "app-root", but do work when used directly in index.html

If they are working in other implementation like stencil and the frameworks then maybe its something I'm doing or an incompatibility with Lit?

Thank You!

**Comment by laxerrrr** [comment]
Bump. I'm trying to do the exact same thing and had to rely on adding `ion-router-outlet` to index.html without wrapping it into a component. Not a flexible solution at all.

https://github.com/laxerrrr/lit-ionic-vanilla

**Comment by sean-perkins** [comment]
Hello @1618employment thanks for the reproduction. I was able to get a working routing implementation by doing the following:

1. Use local dom instead of shadow dom for `app-root`.

e.g.:
```ts
protected createRenderRoot() {
  return this;
}
```

2. Assign the `root` path to the served path `src` and disable hash-based routing.

e.g.:
```html
<ion-app>
  <ion-router root="src" use-hash="false">
    <ion-route url="/" component="home-view"></ion-route>
    <ion-route url="/about" component="about-view"></ion-route>
  </ion-router>
  <ion-router-outlet></ion-router-outlet>
</ion-app>
```

Reproduction: https://github.com/sean-perkins/ionic-gh-26115

Can you test with this and let me know if that resolves your issue?
