### ISSUE TITLE
bug: DatetimeButton with modal results in nested ion-page elements

### ISSUE THREAD

**Issue by loopezz** [ionic-team/ionic-framework#26117]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Using the ion-datetime-button in combination with inline ion-modal creates infinite nested ion-page elements after opening and closing it multiple times.

### Expected Behavior

The ion-page element must not be rendered or only rendered once.

### Steps to Reproduce

1. https://ionicframework.com/docs/api/datetime-button#basic-usage
2. Open the browser's inspector
3. Inspect 'ion-modal' in the StackBlitz example
4. Verify there is no ion-page element rendered
5. Toggle the datetime selector multiple times
6. Inspect 'ion-modal' in the StackBlitz example again

Before:
<img width="378" alt="Screenshot 2022-10-13 at 10 55 09" src="https://user-images.githubusercontent.com/11312418/195552029-ddf7aceb-6de0-4f00-990b-1e8db2a4ce66.png">

After:
<img width="381" alt="Screenshot 2022-10-13 at 10 55 47" src="https://user-images.githubusercontent.com/11312418/195552155-504766d8-8520-4986-8c03-4b7f1b3795e9.png">

### Ionic Info

Example code from the Ionic docs

**Comment by sean-perkins** [comment]
@loopezz thanks for reporting this issue! I am able to reproduce the same. 

A fix that I have proposed for v7 appears to resolve this issue as well. Would you mind testing with this dev-build and let me know if you experience any issues?

```bash
6.3.3-dev.11666207854.1e96b6a8
```

I've split out that specific change into a new pull request so that we could resolve this in v6.

**Comment by loopezz** [comment]
@sean-perkins I'm not able to reproduce it anymore. Thanks for the fix. 👍

**Comment by sean-perkins** [comment]
This issue has been resolved and will be available in both the `nightly` build as well as the next patch release `6.3.5`.

Thanks again for reporting this!
