### ISSUE TITLE
feat: datetime-button, add placeholder attribute to support empty values

### ISSUE THREAD

**Issue by mstichweh** [ionic-team/ionic-framework#26119]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

When using the datetime-button component with an empty value, it shows the current date and time. Instead it would be nice to provide a placeholder which is shown in a placeholder styling, like it is implemented for other input components. 

### Describe the Use Case

With the current implementation it is not possible to have an empty value when using the datetime-button. Therefore a date or time value can never be optional within a form.  
Furthermore, a value is always preselected so that the user can easily forget to select a correct value because of a missing required field error.

### Describe Preferred Solution

Add a `placeholder` attribute to the `ion-datetime-button` component. If it is set and an empty value is provided, the button label should be the placeholder with a corresponding styling (light grey), like for other components.

If the datetime component is configured with date and time, the time button should be hidden while the placeholder is shown. After selecting a date, the time button should be shown with the current time. As soon as a default value can be provided to the datetime component, which would preselect a date when the popover is opened for an empty value, its time could be used instead of the current time.

**Comment by wellwoller** [comment]
Would this take long to implement?

**Comment by wellwoller** [comment]
Highly requested feature btw

**Comment by aktivdigital-frontend** [comment]
Hi! It is very important (the placeholder). Now, it is not user-friendly. Users don't understant they need select a date. Thank you!
