### ISSUE TITLE
bug: datetime header shows 0 days selected with no value even if multiple="false"

### ISSUE THREAD

**Issue by olaisen81** [ionic-team/ionic-framework#26116]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

DateTime showing 0 Days when initialized with formcontrol and string empty value, with Ionic version 6.2.9 all works fine.
Version 6.3.0 introduce some buggy behavior for DateTime, fixed partially with 6.3.1

### Expected Behavior

DateTime show current date if initialized with string empty value in FormControl as version 6.2.9

### Steps to Reproduce

Add dateTime control and init with formcontrol and empty value

### Code Reproduction URL

https://github.com/olaisen81/ionic-datetime-issue_6.3.1

### Ionic Info

Ionic:

   Ionic CLI                     : 6.17.1 (C:\Users\fabio.perfetti\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.3.1
   @angular-devkit/build-angular : 14.2.5
   @angular-devkit/schematics    : 14.2.5
   @angular/cli                  : 14.2.5
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.8.0
   @capacitor/android : 3.8.0
   @capacitor/core    : 3.8.0
   @capacitor/ios     : 3.8.0

Utility:

   cordova-res : 0.15.1
   native-run  : 1.7.1

System:

   NodeJS : v14.18.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.15
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this. Here is a dev build if you are interested in testing the proposed fix:

```
npm install @ionic/angular@6.3.2-dev.11665667373.1a3ecede
```

**Comment by liamdebeasi** [comment]
This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26120, and a fix will be available in an upcoming release of Ionic Framework. Feel free to continue testing this dev build, and let me know if you run into any issues.

**Comment by olaisen81** [comment]
> Thanks for the report. I can reproduce this. Here is a dev build if you are interested in testing the proposed fix:
> 
> ```
> npm install @ionic/angular@6.3.2-dev.11665667373.1a3ecede
> ```

Hi Liam, after the fix header showing current date correctly ('Thu 13 Oct' in locale it) but the button for selecting months and years showing May 2021 instead of October 2022.

**Comment by liamdebeasi** [comment]
This is unrelated to the reported issue, but still something we can fix. I'll dig into this a bit more.
