### ISSUE TITLE
bug: Swipe-to-back will cause whole app stuck forever if swipe too fast

### ISSUE THREAD

**Issue by zhangriyueming** [ionic-team/ionic-framework#26128]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

playTransition function returns a promise which resolved with the 'onFinish' callbacks from the animation, but if the gesture ended too early before these codes run:
```js
  const promise = new Promise((resolve) => {
    trans.onFinish((currentStep) => {
      resolve(currentStep === 1);
    })
  });
```
the whole app just wait a never end animation. Because the nav onEnd called before the callback sets up.

### Expected Behavior

Do not stuck if the gesture ends too fast.

### Steps to Reproduce

Setup a IonNav with swipeToBackEnabled, and do a fast tiny swipe, the whole app stucks. If add console.log on nav.onEnd function and playTransition function, you can see the onEnd called before playTransition called.

### Ionic Info

Ionic:

   Ionic CLI : 6.18.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.11.1
   npm    : 8.1.0
   OS     : macOS Monterey

**Comment by zhangriyueming** [comment]
workaround: 

```js
  onEnd(shouldComplete, stepValue, dur) {
    if (this.sbAni) {
      this.animationEnabled = false;
      this.sbAni.onFinish(() => {
        this.animationEnabled = true;
      }, { oneTimeCallback: true });
      // Account for rounding errors in JS
      let newStepValue = shouldComplete ? -0.001 : 0.001;
      /**
       * Animation will be reversed here, so need to
       * reverse the easing curve as well
       *
       * Additionally, we need to account for the time relative
       * to the new easing curve, as `stepValue` is going to be given
       * in terms of a linear curve.
       */
      if (!shouldComplete) {
        this.sbAni.easing('cubic-bezier(1, 0, 0.68, 0.28)');
        newStepValue += getTimeGivenProgression([0, 0], [1, 0], [0.68, 0.28], [1, 1], stepValue)[0];
      }
      else {
        newStepValue += getTimeGivenProgression([0, 0], [0.32, 0.72], [0, 1], [1, 1], stepValue)[0];
      }
      this.sbAni.progressEnd(shouldComplete ? 1 : 0, newStepValue, dur);
    } else {
      if (!this.canStart()) {
        setTimeout(() => this.onEnd(shouldComplete, stepValue, dur), 50)
      }
    }
  }
```

added 
```js
 else {
      if (!this.canStart()) {
        setTimeout(() => this.onEnd(shouldComplete, stepValue, dur), 50)
      }
    }
```

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
