### ISSUE TITLE
bug: ion-alert keyboardclose option

### ISSUE THREAD

**Issue by andreas20** [ionic-team/ionic-framework#26126]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The keyboardclose option doesn't work for ion-alert.
When focus is on input and then alert is present, the keyboard is hidden, and there is a <screen flash> since the modal moves when the keyboard is hidden.

### Expected Behavior

the keyboard should not be hidden if  keyboardclose is false.

### Steps to Reproduce

     const alert = await this.alertCtrl.create({
        header: this.alertHeader,
        message: this.alertMessage,
        mode: 'ios',
        keyboardClose: false,
        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.handlerMessage = 'Alert canceled';
              console.log('---ALERT---CANCEL');
            },
          },
          {
            text: 'OK',
            role: 'confirm',
            handler: () => {
              this.handlerMessage = 'Alert confirmed';
              console.log('---ALERT---CONFIRMED');
            },
          },
        ],
      });

      await alert.present();

### Ionic Info

onic:

   Ionic CLI                     : 6.20.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.1
   @angular-devkit/build-angular : 14.1.1
   @angular-devkit/schematics    : 14.1.1
   @angular/cli                  : 14.1.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : not installed
   @capacitor/core    : 4.0.1
   @capacitor/ios     : 4.0.1

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
