### ISSUE TITLE
bug: dependency to @ionic/core

### ISSUE THREAD

**Issue by TiBz0u** [ionic-team/ionic-framework#26137]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hi,
We discover, due to the lot of fixes on the `ion-datetime` component (thanks by the way), that the @ionic/angular package depends on the @ionic/core version with a ^ (Compatible with version).

Due to this, even if we choose a specific version of the @ionic/angular, it will automatically download the last version of the @ionic/core package that contains all the components and thus the fix/new behavior.

### Expected Behavior

@ionic/angular and @ionic/core use the same version or approximately equivalent version (~)

### Steps to Reproduce

ionic start myApp tabs

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/Users/mainsys/.nvm/versions/node/v12.22.6/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.1
   @angular-devkit/build-angular : 14.2.6
   @angular-devkit/schematics    : 14.2.6
   @angular/cli                  : 14.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : not installed
   @capacitor/core    : 4.3.0
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.14.0
   native-run                             : 1.7.1

System:

   NodeJS : v12.22.6 (/Users/mainsys/.nvm/versions/node/v12.22.6/bin/node)
   npm    : 6.14.15
   OS     : macOS Catalina

**Comment by liamdebeasi** [comment]
Thanks! This should be fixed in an upcoming release of Ionic. I changed it so that the same version of Ionic is always installed. This means that if you install `@ionic/angular@6.3.0`, then `@ionic/core@6.3.0` will be installed.

**Comment by TiBz0u** [comment]
Thanks @liamdebeasi. I suppose this change is not retroactive. Package already shipped will have the old behavior.

**Comment by liamdebeasi** [comment]
Correct, this fix will apply starting in Ionic 6.3.3.

**Comment by TiBz0u** [comment]
Hi @liamdebeasi, by testing issue https://github.com/ionic-team/ionic-framework/issues/26146 on stackblitz, I discover that your correction regarding this bug in 6.3.3 has disappeared...

Below the dependency when installing Ionic 6.3.6
```
  "dependencies": {
    "@ionic/core": "^6.3.6",
    "jsonc-parser": "^3.0.0",
    "tslib": "^2.0.0"
  }
```
=> 6.3.7 and thus, cannot test the bug on stackblitz anymore.

Kr.

**Comment by liamdebeasi** [comment]
This PR should fix it: https://github.com/ionic-team/ionic-framework/pull/26349

The original PR was wrong in that I only applied the result of `lerna version --exact` instead of having our release process run `lerna version --exact`. The new PR fixes that.
