### ISSUE TITLE
bug: datetime max and min do not consider time when showDefaultButtons={true}

### ISSUE THREAD

**Issue by Facj** [ionic-team/ionic-framework#26146]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

If option _showDefaultButtons={true}_ is included in IonDatetime, attributes _max_ and _min_ stop working correctly.
Only date is considered, time is not taking into account to set min and max selectable values.

If option _showDefaultButtons={true}_ is commented out, attributes _max_ and _min_ work fine for date and time.

### Expected Behavior

Attributtes min and max of IonDatetime should work correctly when option showDefaultButtons={true} is included.

### Steps to Reproduce

1.  Load page in Codesandbox
2. Select Birth Time
3. When the modal opens, check that all times are selected all available days even though max and min atrributes impose time restrictions.

Comment out line _showDefaultButtons={true}_  (line 48) and repeat the steps above.
Time restrictions imposed by max and min attributes are now working fine.

### Code Reproduction URL

https://codesandbox.io/s/ionic6-datetime-and-react-hook-form-me36n2

### Ionic Info

**ionic info**

Ionic:

   Ionic CLI       : 6.6.0 (C:\Users\MyUser\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.2.9

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.12.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. Does this issue still happen on the latest version of Ionic (v6.3.3 as of writing)? Also, can you please clarify what the expected behavior is here?

**Comment by Facj** [comment]
I can confirm that the issue still happens in Ionic 6.3.3. I have updated the Ionic version in the Codesanbox included in my initial post.

The expected behavior is that time values in `max` and `min` parameters are correctly considered.

For instance, in the example in the Codesandbox the parameters are the following:

- min="2022-09-18T12:23"
- max="2022-10-12T17:22"

Date restriction is correctly applied, I cannot select any  day before 2022-09-18 or after 2022-10-21. 
However, time restriction is not correctly applied, I can select any time in the limit days, while times before 12:23 should not be allowed in 2022-09-18 and times after 17:22 should not be allowed in 2022-10-12. 

This problem does not appear if showDefaultButtons={false}.

**Comment by liamdebeasi** [comment]
Thanks! I can reproduce this behavior.

**Comment by liamdebeasi** [comment]
Hey there,

Here is a dev build with a proposed fix if you are interested in testing it:

```
6.3.6-dev.11668029832.1cf48a01
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26257, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue testing the dev build, and let me know if you run into any issues.
