### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by JulienLecoq** [ionic-team/ionic-framework#26158]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add a css custom property or another shadow part to the ion-button component allowing to customise the placement of the content inside the ion-button.

### Describe the Use Case

Buttons in iOS "list form" have very often their content placed on the left.
I would like to have the same behaviour easily.

### Describe Preferred Solution

I see two solutions, a custom shadow part that give access to the span inside the native button that allows to customize the span css. Or, give a add a --justify-content custom property that allows to place the content inside the button.

### Describe Alternatives

We can add an extra html span tag inside the button and customize its css. It's not very convenient.

**Comment by DwieDima** [comment]
Is this something that would fit your requirement?

https://stackblitz.com/edit/angular-lw6qre?file=src/app/example.component.html

![image](https://user-images.githubusercontent.com/26873275/197485866-c018961c-3d63-4bc4-8f63-cdfe00014f2b.png)

**Comment by JulienLecoq** [comment]
Not really, that's the alternative I described. That force you to add a new html tag inside the component which I don't find very convenient.

But I just noticed something, ion-item has a click effect. But when developing, I'm using the web browser and the click effect does not appears when using the browser in 'ios' mode because the hover effect overrides the click effect.
So I can just use the ion-item instead of a button with the "list item form". But yeah, really annoying to not see the click effect

**Comment by JulienLecoq** [comment]
Oh my bad, I got confused. I forgot to put the button prop on ion-item. And if you pass in "mobile view" on Brave, this removes the hover effect that overrides the click effect.

**Comment by JulienLecoq** [comment]
So I don't really need to be able to move the button text anymore (I can just use a ion-item) but I still think it could be useful to someone else.

**Comment by liamdebeasi** [comment]
Thanks for the report. I am going to close this since you are no longer running into the issue described in https://github.com/ionic-team/ionic-framework/issues/26158#issue-1419968723. However, if anyone else would like this feature please feel free to reply or open a new issue.
