### ISSUE TITLE
bug: Disable swipe back in specific page on Android device.

### ISSUE THREAD

**Issue by smhemel** [ionic-team/ionic-framework#26151]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

I have tried this - 

```
import { IonRouterOutlet } from '@ionic/angular';

export class MyPage {
  constructor(private routerOutlet: IonRouterOutlet) {}

  ionViewWillEnter() {
    this.routerOutlet.swipeGesture = false;
  }

  ionViewWillLeave() {
    this.routerOutlet.swipeGesture = true;
  }
}
```

These codes are worked on iOS devices but do not work on Android.

### Expected Behavior

I want to disable swipe-back gestures on Android devices.

### Steps to Reproduce

Just use the code on a page, then build the project for the Android and iOS platforms. Now, try the gesture swipe on two different apps, you can see the problem.

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\hemel\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.9.4
   @angular-devkit/build-angular : 0.1102.19
   @angular-devkit/schematics    : 11.2.19
   @angular/cli                  : 11.2.19
   @ionic/angular-toolkit        : 3.1.1

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.2
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 19 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v14.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.11
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the report. The swipe to go back behavior only exists on iOS, so this config will not have any effect when running in MD mode. Can you please clarify the issue you are running into?
