### ISSUE TITLE
Click event on `ion-loading` to hide it via user interaction. 

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/ionic-framework#26160]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Is there any User interaction event for `ion-loading` presented via `LoadingController`. 

I can show my custom HTMl template inside loading `message` property. But in my scenario I want to give user an option where they can hide loading. 

### Expected Behavior

There should be an option to hide `ion-loading`

### Steps to Reproduce

My current Function:

```
async presentLoading(m = 'Please Wait') {
    this.loading = await this.loadingController.create({
      cssClass: 'myLoader',
      spinner: null,
      mode: 'md',
      message: `
        <div class="loader">
          <img src="assets/imgs/loading.gif" class="loading-img" />
          <div class="earth"></div>
        </div>
      `,
      showBackdrop: true
    });
    await this.loading.present();
  }
```

i want an event to trigger for users to hide it . 
I tried added `(click)` event on on my divs or img tags but none is working. 

in android let say i can catch hardware back-button to hide. but what about IOS? 

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.3 (/Users/fahadaslam/.nvm/versions/node/v16.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.12
   @angular-devkit/build-angular : 14.0.4
   @angular-devkit/schematics    : 14.0.4
   @angular/cli                  : 14.0.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : 4.3.0
   @capacitor/core    : 4.3.0
   @capacitor/ios     : 4.3.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v16.13.1 (/Users/fahadaslam/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey
```

**Comment by amandaejohnston** [comment]
Thanks for the request. This can be done via the `htmlAttributes` property; here is an example: https://stackblitz.com/edit/angular-oulitv?file=src%2Fapp%2Fexample.component.ts Could you let me know if this solves your issue?

**Comment by Saqib92** [comment]
> Thanks for the request. This can be done via the `htmlAttributes` property; here is an example: https://stackblitz.com/edit/angular-oulitv?file=src%2Fapp%2Fexample.component.ts Could you let me know if this solves your issue?

Yes, it worked. that was easy. I wasted 2 days on this. There should be more in docs about this or at-least an example in docs.
