### ISSUE TITLE
bug: Modal not in fullscreen if adressbar is hidden

### ISSUE THREAD

**Issue by tobiloeb** [ionic-team/ionic-framework#26166]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

We build an ionic application for iOS and Android and as SPA for our website. 
Opened Ionic modals in the browser (website) on mobile devices like Google Pixel 6 do not fill the full browser screen, in case the adressbar is hidden. 

![Bildschirmfoto 2022-10-25 um 14 18 55](https://user-images.githubusercontent.com/8022875/197771474-0d549ba2-a6f4-4710-8809-ac8daebcd544.png)

### Expected Behavior

The modals should have the full height even if the adressbar on mobile devices is hidden.

### Steps to Reproduce

We build a small example app to verify that this issue and make it reproducible for you.

https://stackblitz.com/edit/ionic6-angular13-9ldb8l 

Open the preview of this Stackblitz at a mobile device. We tested it with an Google Pixel 6 and a Samsung S10 in Chrome. First scroll down a little bit, until the browser address bar is hidden. Now click the button „Open Modal“ to open the Ionic modal. 

You see like in the screenshot above, that the modal didn’t fill the full browser. There is space at the bottom of the modal (the green background). This space seems to be exactly the space of the hidden address bar from browser. If you scroll up in the modal and the address bar appears, the modal has the right full height.

![Bildschirmfoto 2022-10-25 um 14 20 30](https://user-images.githubusercontent.com/8022875/197772039-f6b37363-6fce-4be7-9423-bf5103ce4fd2.png)

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-9ldb8l 

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (/Users/tobias/.npm/_npx/7132/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.2.5
   @angular-devkit/build-angular : 14.2.1
   @angular-devkit/schematics    : 14.2.1
   @angular/cli                  : 14.2.1
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI   : 3.4.0
   @capacitor/core : 3.4.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 1.5.0

System:

   NodeJS : v14.19.3 (/Users/tobias/.nvm/versions/node/v14.19.3/bin/node)
   npm    : 6.14.17
   OS     : macOS Monterey
   Xcode  : Xcode 14.0.1 Build version 14A400

**Comment by liamdebeasi** [comment]
Thanks for the report. This does not appear to be a bug in Ionic. Ionic apps are designed to have `ion-app` as the root node. Your example adds green boxes below the `ion-app` which adds overflow.

Modals are presented as children of `ion-app`, so their sizing is relative to that element. As a result, when you scroll down and then present the modal, the modal does not appear to be fullscreen.

**Comment by tobiloeb** [comment]
Hi thanks for the fast reply. Yeah the green boxes should represent our website footer, thats why we have an overflow.
Oh no I see, the height didn't change when the address bar hides or appears, thats why the modal has always the same height. 

So I think this can be closed and we need to check how to solve this, thanks!
