### ISSUE TITLE
bug: Can't use Ionic inside a Vue SSR project

### ISSUE THREAD

**Issue by marcoschwartz** [ionic-team/ionic-framework#26177]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I am trying to use Ionic Vue inside a Vue SSR project and since moving to Ionic 6 something breaks with the SSR side, I have the following bug:

> import { proxyCustomElement, HTMLElement, h, Host } from '@stencil/core/internal/client';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module

It seems to come with several components that are using the @stencil module, and it's strange because I am in a 100% ES6 project using Vite. I tried it in ES5 project using only Vue SSR, same issue. Without SSR, works fine.

### Expected Behavior

The error should not show when using SSR.

### Steps to Reproduce

Any Vue SSR project using the following main.js file will show the error:

```
import { createSSRApp } from 'vue'
import App from './App.vue'

import { IonicVue } from '@ionic/vue';

export function createVueApp() {

    // Use
    const app = createSSRApp(App);

    app.use(IonicVue)

    return { app }
}
```

### Ionic Info

Ionic:

   Ionic CLI : 6.20.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.11.0
   npm    : 8.19.2
   OS     : macOS

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
