### ISSUE TITLE
bug: input outline does not take on background color of page

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#26178]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Using an outline input with a floating label on a different background looks weird, because the label has a background to archive the "label over border" look:

![Bildschirmfoto 2022-10-27 um 09 54 18](https://user-images.githubusercontent.com/20899975/198224084-c3296216-2308-4775-b576-6740172f7b60.png)
(taken from ionic docs and changed the background color)

### Expected Behavior

The label should have no background color itself. Maybe this is solvable similar to https://material.angular.io/components/form-field/overview

They seem to create 3 borders:
- left
- top & bottom for the width that the label has
- the rest on the right side

The second one then has a `border-top-color: rgba(0,0,0,0);` to not show the border over the label 🤔

**QQ:** Why is the outline style not available in ios mode? Would be cool to have them there as well.

### Steps to Reproduce

As described for the image above, you can easily see the label's background in the ionic docs, by just changing the container's background color

### Ionic Info

Let me know if you need this

**Comment by EinfachHans** [comment]
Alternative solution could be a background of the label as an gradient so the half is the same color as the item, the other half is transparent

**Comment by liamdebeasi** [comment]
Thanks for the report. In Ionic 7 we are introducing a new syntax for working with ion-input. This issue is fixed when using that new syntax. We will have an Ionic 7 beta in the future where developers can test and provide feedback. There will also be a migration guide to show how to update to the new input syntax.

The work required to resolve this has been completed, so I am going to close this thread. Let me know if there are any questions.
