### ISSUE TITLE
bug: issues with datetime example on website

### ISSUE THREAD

**Issue by twoco** [ionic-team/ionic-framework#26184]
https://ionicframework.com/docs/api/datetime#multiple-date-selection

![demo](https://user-images.githubusercontent.com/53160891/198383699-ceb12890-9c66-4ef3-ac51-0493c79492df.gif)

The iOS color is another issue. I mainly created this issue because of MD example on your website. Not yet tested in my app.

**Comment by sean-perkins** [comment]
@twoco which browser and browser version are you testing with?

I am unable to reproduce the MD issue on Google Chrome Version 106.0.5249.119 (Official Build) (arm64).

The iOS focus design will require more investigation from the team. Comparing with iOS's date picker:

**Native**
- Focused button is grey background, white foreground
- Selected button is red background, bolded white foreground

**Ionic**
- Focused button is blue background
- Selected button is blue background, bolded, blue foreground

**Comment by twoco** [comment]
I use Chrome 106.0.5249.119, too. But today it works. I swear, reloaded the page multiple times (including browser restart). Weird... The MD example dates 3, 19, 29 are not preset. I thought it's the same code base. Anyway... 

![demo](https://user-images.githubusercontent.com/53160891/198705123-941a1599-779d-48bb-a1d7-6625a6fc6552.gif)

MD looks better for me. Especially the selection color. Btw. Ionic could combine MD and iOS and create its own great design. One design is maybe easier to develop and better to use. Personally I set the theme fixed to md mode on iOS devices too. Anyway, I just thinking aloud. ^^ I close this. Thanks for investigating. Fell free to reopen if want to fix the iOS theme color here.
