### ISSUE TITLE
bug: Ionic breaks the default behavior of ctrl+click in a browser

### ISSUE THREAD

**Issue by maelp** [ionic-team/ionic-framework#26186]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When doing a `ionic start` project with VueJS and the List sample, ctrl+clicking on an item in the list opens the link in the same tab, rather than in a different tab.

### Expected Behavior

The link should open in a different tab

### Steps to Reproduce

- `npm start`
- choose VueJS and List example
- run `ionic serve`
- try to ctrl+click on a list item

### Ionic Info

```
Ionic:

   Ionic CLI : 6.20.3

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.7.1)   : 1.5.0

System:

   NodeJS : v16.18.0
   npm    : 8.19.2
   OS     : macOS Monterey
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you clarify what the expected behavior is? I tested this with the list starter app and things appear to be working as intended. The `ion-item` in this app does not render an anchor (`a`) element, so I would not expect a Ctrl+Click on `ion-item` to open the page in a new tab.

**Comment by maelp** [comment]
I expect most links on browser to open in a new tab. Would it work if we were adding a `<a>` element beneath?

**Comment by liamdebeasi** [comment]
If you use `href` on `ion-item`, Ionic will render an `<a>` element instead of a button. In your reproduction, the page is not opening in a new tab because you are not rendering a link.

**Comment by maelp** [comment]
Okay :)
