### ISSUE TITLE
bug: web-types are not generated for @ionic/vue

### ISSUE THREAD

**Issue by TechAkayy** [ionic-team/ionic-framework#26198]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`@ionic/vue/dist/web-types.json` is empty and not generated correctly using script under `./scripts/build-web-types.js`

This line is looking for a usage flag for vue and is skipping all components - https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/scripts/build-web-types.js#L8

### Expected Behavior

`@ionic/vue/dist/web-types.json` should contain all the components and their meta-data and get auto-generated correctly using script under `./scripts/build-web-types.js`

### Steps to Reproduce

Scaffold a new ionic cli based vue project (or) use Aaron's github repo from here - https://github.com/aaronksaunders/ionicv6-beta-vue-vite-project

`npm install`

Check `node_modules/@ionic/vue/dist/web-types.json`

### Code Reproduction URL

https://github.com/aaronksaunders/ionicv6-beta-vue-vite-project

### Ionic Info

Ionic:

   Ionic CLI : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : 4.0.1

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v16.17.1 (/usr/local/bin/node)
   npm    : 8.15.0
   OS     : macOS

**Comment by sean-perkins** [comment]
@TechAkayy thank you for reporting this issue! 

I'll look into this further. The `usage` flag is no longer being generated in the `docs.json` file that that script runs off of. I'll see why that is the case and find a consistent way of generating those types moving forward.

**Comment by sean-perkins** [comment]
This issue has been resolved and will be available in the `nightly` build of Ionic as well as the next patch release (`6.3.5`). Thank you again for reporting this!

**Comment by TechAkayy** [comment]
Thanks bunch :-)
