### ISSUE TITLE
Failed to install '@ionic-enterprise/auth' while running 'ionic cordova platform add android'

### ISSUE THREAD

**Issue by hiteshwork08** [ionic-team/ionic-framework#26199]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Cordova is not able to add '@ionic-enterprise/auth' plugin.
![image](https://user-images.githubusercontent.com/99509628/199178861-88ccbbb5-38b8-45a7-ba25-4e0504b161c3.png)

### Expected Behavior

Ideally it should BUILD the app Successfully with '@ionic-enterprise/auth' plugin.

### Steps to Reproduce

install @ionic-enterprise/auth (configure it with Auth0)

ionic cordova platform add android

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (C:\Users\ViP\AppData\Roaming\nvm\v14.15.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.13
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.2
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 13 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   Android SDK Tools : 26.1.1 (C:\Users\ViP\AppData\Local\Android\Sdk)
   NodeJS            : v14.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.8
   OS                : Windows 10

**Comment by kensodemann** [comment]
This issue list is only for the Ionic Framework, which is an open source project.

Auth Connect is a paid product, so you should utilize paid support via https://ionic.zendesk.com/hc/en-us. It is best if you are logged in over there when you create the issue so the issue will be  properly associated with your organization.

If you have any questions, please let me know.
