### ISSUE TITLE
bug: In iOS, if the input item is cleared by clearInput of ion-input while the Japanese or other keyboard is activated, text input will be disabled afterwards.

### ISSUE THREAD

**Issue by acn-masatadakurihara** [ionic-team/ionic-framework#26208]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

In iOS, if the input item is cleared by clearInput of ion-input while the Japanese or other keyboard is activated, text input will be disabled afterwards.
It is difficult to convey in words, so we have prepared a video.
https://user-images.githubusercontent.com/30038715/199422091-c35c6071-fb02-4f93-9f4f-38c4525b7b7c.mov

Sample code:
https://stackblitz.com/edit/angular-pmwmee?file=src%2Fapp%2Fapp.component.ts

### Expected Behavior

Accepts keyboard input even after clearInput.

### Steps to Reproduce

1. Focus on ion-input.
2. Switch to a keyboard such as Japanese to input characters.
3. Press the clear button displayed by clearInput.
4. Continue keyboard input.

### Code Reproduction URL

https://stackblitz.com/edit/angular-pmwmee?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/Users/masatada.kurihara/.asdf/installs/nodejs/18.12.0/.npm/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.3
   @angular-devkit/build-angular : 14.2.7
   @angular-devkit/schematics    : 14.2.7
   @angular/cli                  : 14.2.7
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : not installed
   @capacitor/core    : 4.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.12.0 (/Users/masatada.kurihara/.asdf/installs/nodejs/18.12.0/bin/node)
   npm    : 8.19.2
   OS     : macOS Monterey

**Comment by sean-perkins** [comment]
Hello @masatada-kurihara thank you for reporting this bug. 

I have identified that this is an issue with Mobile Safari: https://bugs.webkit.org/show_bug.cgi?id=247374

When the focus is changed to the clear button when clearing the button, the IME/keyboard does not re-attach to the manually focused element (the input). This results in the input being focused, the cursor to blink, but additional keyboard input will not register. Blurring the control and re-focusing results in the keyboard working appropriately. 

In the interim, I would recommend disabling the use of the clear button in your application, if users predominately use an IME.
