### ISSUE TITLE
bug: Modal does not dismiss when tap on IOS

### ISSUE THREAD

**Issue by pedrinAlplab** [ionic-team/ionic-framework#26213]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

showing the modal but when tapping the backdrop it does not dismiss in IOS

### Expected Behavior

to close the modal when tapping the backdrop

### Steps to Reproduce

const modal = await this.modalCtrl.create({
      component: AlertasDetailModalPage,
      componentProps: {
        alert: this.alert,
      },
      showBackdrop: true,
      backdropDismiss: true,
      cssClass: 'alert-modal'
    });

on global.scss
.alert-modal {
  &::part(content) {
    position: absolute;
    top: 65%;
    width: 70%;
    height: 30%;
    border-radius: 10px;
    -webkit-box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.75);
    -moz-box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.75);
    box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.75);
  }
}

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.7
   @angular-devkit/build-angular : 14.2.3
   @angular-devkit/schematics    : 14.2.3
   @angular/cli                  : 14.2.3
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.2.0
   @capacitor/android : 4.2.0
   @capacitor/core    : 4.2.0
   @capacitor/ios     : 4.2.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v18.11.0 (/usr/local/bin/node)
   npm    : 8.19.2
   OS     : macOS Monterey

### Additional Information

Only Happens in IOS

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
