### ISSUE TITLE
bug: Datetime time missing PM option and time values when using min/max

### ISSUE THREAD

**Issue by acommend** [ionic-team/ionic-framework#26216]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Datetime time missing PM option and time values when using min/max. In the attached repo the user is unable to select time values from 12:00 thru 12:14 PM.

### Expected Behavior

Expected all time values between the min and max to be be selectable.

### Steps to Reproduce

1. Add Datetime component with min and max set crossing the 12 PM boundary and time set to a time before 12 PM
2. Select the time value. No PM value present in time picker

### Code Reproduction URL

https://github.com/acommend/datetime-missing-time-values

### Ionic Info

C:\Git\datetime-missing-time-values>ionic info

Ionic:

   Ionic CLI       : 6.18.1 (C:\Users\Tony\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.3.4

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : not installed
   @capacitor/core    : 4.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.7.1

System:

   NodeJS : v16.9.1 (C:\Program Files\nodejs\node.exe)
   npm    : 7.21.1
   OS     : Windows 10

### Additional Information

https://dashboard.ionicframework.com/app/786e62f7/preview/8282836

**Comment by liamdebeasi** [comment]
Thanks for the report. Did you make your repo public? I cannot access it.

**Comment by liamdebeasi** [comment]
Hey there,

I am still unable to access https://github.com/acommend/datetime-missing-time-values. Can you double check the repo?

**Comment by acommend** [comment]
I apologize again, I'm not familiar with github and didn't perform all of the steps needed.  I think I've fixed the issue. Please try again when you have some time.

**Comment by sean-perkins** [comment]
@acommend thank you for your reproduction. I am also able to reproduce this in our JS implementation: https://stackblitz.com/edit/ty3b6j?file=index.html.

The additional options for the "12" hour are unavailable when the max value is set to 12pm, even when the datetime is configured to accept values within 12pm, eg. 12:00-12:14.

**Comment by sean-perkins** [comment]
Hello @acommend can you test with this dev-build and let me know if you run into any isssues?

```bash
npm install @ionic/vue@6.3.5-dev.11667857244.18413739 @ionic/vue-router@6.3.5-dev.11667857244.18413739
```

**Comment by acommend** [comment]
@sean-perkins, I've tested with the dev-build and it fixes the issue. Thanks for fixing it.

**Comment by sean-perkins** [comment]
Apologies, I saw your original reply, but did not see your most recent prior to merging. I'll re-open and evaluate in the morning.

**Comment by sean-perkins** [comment]
@acommend this appears to be from a typo in the example. In the template the `min` value is bound to `minIsoIsoTime`, but the property name is in fact `minIsoTime`.

Can you try updating that variable name and let me know if there are any issues?

Testing locally on my end, everything looks good after that change.

**Comment by acommend** [comment]
@sean-perkins , great catch and thanks for finding my bug. Everything works as expected after fixing the variable name.  Thanks again for fixing the issue.
