### ISSUE TITLE
bug: Popovers won't open after routerlink in multiple instances of same component

### ISSUE THREAD

**Issue by Joep-DDQ** [ionic-team/ionic-framework#26211]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I have created a datetime picker component with an input with popover and a datetime picker inside. I am using it in multiple pages. I start with either page 1 or page 2. On the page where I clicked the input (with popover) to open the datepicker FIRST it will open the popover. 
Then I go to the other page by clicking on a button with a routerLink, and the popover doesn't show when I click on the (same) input. 

If I manually goto the pages (without a routerlink) by changing the URL in the address bar the popover works correctly. 

I have also added code with a modal and this works correctly on both pages. 

It seems 2 other people had a similar issue but it was never addressed

### Expected Behavior

Pop over opens on both pages after navigating with routerLink. 

### Steps to Reproduce

1. Run the application. 
2. goto page 1
![afbeelding](https://user-images.githubusercontent.com/85735582/199516525-1f7f5514-4162-4d84-9aac-7993547145d1.png)

4. Click on the date input for start date
![afbeelding](https://user-images.githubusercontent.com/85735582/199516617-7092249c-2d6a-4025-bcd6-e5302de68172.png)
Pop over Shows

5. Select a date and see it in the input
![afbeelding](https://user-images.githubusercontent.com/85735582/199518536-465b243a-d13d-4358-b46d-19dd330459d3.png)

6. Click the button to goto Page 2
![afbeelding](https://user-images.githubusercontent.com/85735582/199516991-6cf180fb-3186-4d6d-bbfa-1546428dbe0e.png)

7. Click the input for start date (again)
![afbeelding](https://user-images.githubusercontent.com/85735582/199517114-341afac4-ba64-4db8-9da3-031072e11b4d.png)

No matter what I click the popover will not show anymore. 
Going back to page 1 will still have a working popover, but on page 2 it doesn't work. 

If you start by going to page 2 first and then to page 1, the popover will work on page 2, but not on page 1. 

### Code Reproduction URL

https://github.com/DDQ-NL/datetimepopoverissue

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (C:\Users\joepv\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.3.3
   @angular-devkit/build-angular : 14.2.7
   @angular-devkit/schematics    : 14.2.7
   @angular/cli                  : 14.2.7
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : not installed
   @capacitor/core    : 4.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.13.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.0
   OS     : Windows 10

### Additional Information

Related issues (from my google search)

https://forum.ionicframework.com/t/ionic-inline-popover-and-routerlink-angular/222271
https://github.com/ionic-team/ionic-framework/issues/25946

BTW a little history: I resorted to this popover 'solution' because the datetime picker had so many issues and big changes going to Ionic version 6...
Initial code copied from here: https://www.damirscorner.com/blog/posts/20220107-DatePickerPopupInIonic6.html

**Comment by sean-perkins** [comment]
@Joep-DDQ thanks for opening this issue!

The issue here is a combination of how Ionic routing and overlay triggers function. 

In your example, the `app-datepicker` component is using static values for the id for the two controls: `dateFrom` and `dateTo`. The popover, when using a trigger, will query the DOM for this selector to attach event listeners to. 

When you then navigate, you are rendering another instance of `app-datepicker`, but Ionic routing doesn't unmount the leaving view, so the previous instance of `app-datepicker` is still in the DOM. We do this to handle page transitions and swipe-to-go-back behavior. The new instance of `app-datepicker` then queries the DOM and attaches to the other instance's elements. 

My recommendation would be to generate unique id selectors for each instance of `app-datepicker`. 

For example (pseudocode):
```ts
let id = 0;

@Component({
  selector: 'app-datepicker'
})
export class DatepickerComponent {
  dateFromId = `datepicker-${id++}`;
  dateToId = `datepicker-${id++}`;
}
```

```html
<ion-input [id]="dateFromid"></ion-input>
<ion-popover [trigger]="dateFromId" size="auto">
  ...
</ion-popover>

<ion-input [id]="dateToId"></ion-input>
<ion-popover [trigger]="dateToId" size="auto">
  ...
</ion-popover>
```

Can you try that and let me know if you run into any issues or have any questions?

**Comment by Joep-DDQ** [comment]
Hi @sean-perkins : Thank you for the clarification. Explained like that it makes a lot of sense. 
I have implemented your code example and it solved the issue. The popover presents in both instances of the component so this 'bug' can be closed.
