### ISSUE TITLE
useIonRouter push state bug

### ISSUE THREAD

**Issue by FernetB** [ionic-team/ionic-framework#26220]
**Ionic version:**

[x] **4.x**
[ ] **5.x**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
if you navigate with `push` with routeAction `pop` to a page that was already mounted with an state from another page, then this overrates it with undefined

**Expected behavior:**
Do not change the state, I think that `push` or `navigate` (from ionRouter context) with routeAction `pop` must behave like goBack from `history` that does not changes the state

**Steps to reproduce:**

Go from A to B with an state, then go from B to C, and then go from C to B with `navigate` or `push` with routeAction`pop`

PD: I know that in this example u could use simply `history.goBack()` but there are more intricates scenaries when u really cant use `history.goBack()`

**Ionic info:** 

```
Ionic:

   Ionic CLI       : 6.19.0
   Ionic Framework : @ionic/react 5.9.1

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res : 0.15.1
   native-run  : 1.7.0

System:

   NodeJS : v14.17.0 
   npm    : 6.14.13
   OS     : Windows 10
```

**Comment by amandaejohnston** [comment]
I noticed that according to `ionic info`, your project is on Ionic v5. Maintenance for that version ended on [June 8th](https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status), with active development currently on v6. Could you confirm if this issue occurs on the latest version of Ionic? There is a [migration guide here](https://ionicframework.com/docs/intro/upgrading-to-ionic-6) if you need it.
