### ISSUE TITLE
CRITICAL BUG: sourcecode protection (obfuscatation feature) in release builds doesnt work on Ionic 6

### ISSUE THREAD

**Issue by nhuhuynh102** [ionic-team/ionic-framework#26235]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Complied static sourcebase is not osfuscated as expected
```ionic build --release```
```ionic build --prod```

### Expected Behavior

the output sourcebase for static site should be osfuscated in production build

### Steps to Reproduce

```ionic build --release```
```ionic build --prod```

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.3 (D:\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.3.4

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : not installed
   @capacitor/core    : 4.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.13.2 (D:\Program Files\nodejs\node.exe)
   npm    : 8.15.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please clarify the issue you are reporting? Running `ionic build --prod` does minify the code (remove whitespace, shorten variable names, etc) but is not supposed to perform code obfuscation.

**Comment by nhuhuynh102** [comment]
build 

> Thanks for the report. Can you please clarify the issue you are reporting? Running `ionic build --prod` does minify the code (remove whitespace, shorten variable names, etc) but is not supposed to perform code obfuscation.

production build should be supported code obfuscation options Dear

**Comment by liamdebeasi** [comment]
When you call `ionic build`, the Ionic CLI calls `react-scripts build` under the hood. In other words, the Ionic CLI does not handle the building of your app, so this is more of a react-scripts request. I recommend filing an issue on https://github.com/facebook/create-react-app instead.
