### ISSUE TITLE
Popover is always in the middel of the page and can't be moved

### ISSUE THREAD

**Issue by chr1soscl** [ionic-team/ionic-framework#26239]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Unable to override the popover-content attributes, I am passing a cssClass as:

this.popover = await this.popoverController.create({
      component: MovieSelectorComponent,
      cssClass: 'movie-selector-popover',

.movie-selector-popover {
  --background: white;
  .popover-content {
    top: 10px !important;
    left: 8px !important;
    right: 8px !important;
  }
}

### Expected Behavior

Should be able to override the popover-content position, to place the popover 10px from the start of the screen.

### Steps to Reproduce

click on button to programmatically open the modal and pass the component name for the popup.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/Users/.../.nvm/versions/node/v14.20.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.2
   @angular-devkit/build-angular : 14.2.6
   @angular-devkit/schematics    : 14.2.6
   @angular/cli                  : 14.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 11.0.0
   Cordova Plugins   : no whitelisted plugins (10 plugins total)

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v14.20.0 (/Users/.../.nvm/versions/node/v14.20.0/bin/node)
   npm    : 6.14.17
   OS     : macOS Monterey
   Xcode  : Xcode 13.2.1 Build version 13C100

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
