### ISSUE TITLE
CRITICAL BUG: cannot dismiss IonLoading by useIonLoading hook

### ISSUE THREAD

**Issue by nhuhuynh102** [ionic-team/ionic-framework#26233]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

useIonicLoading - dismissLoading doesnt work
```const [showLoading, hideLoading] = useIonLoading();```

### Expected Behavior

useIonicLoading - dismissLoading should work

### Steps to Reproduce

```
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonLoading, useIonLoading,useIonAlert } from '@ionic/react';
import { useEffect, useState } from 'react';
const Privacy: React.FC = () => {
  const [showLoading, hideLoading] = useIonLoading();
    useEffect(()=>{
      showLoading({message:'Loading ...',spinner: 'circles'});
    },[]);
    
    const onPlay = async() => {
      console.log('onPlay called');
      hideLoading().then(()=>{
        console.log('hideLoading');
      },()=>{});
    }
    
    const onWaiting = () =>{
      console.log('onWaiting');
    }
  
    return (
      <IonPage>
        <IonHeader>
          <IonToolbar>
            <IonTitle>Bug</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonContent fullscreen>
          <IonHeader collapse="condense">
            <IonToolbar>
              <IonTitle size="large">ToDos</IonTitle>
            </IonToolbar>
          </IonHeader>
         
        </IonContent>
      </IonPage>
  );
```

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.3 (D:\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.3.3

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : not installed
   @capacitor/core    : 4.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.13.2 (D:\Program Files\nodejs\node.exe)
   npm    : 8.15.1
   OS     : Windows 10
```

**Comment by sean-perkins** [comment]
Dismissing the loading overlays with the `useIonLoading` hook works as expected: https://stackblitz.com/edit/angular-8f4eqy?file=src%2Fmain.tsx.

Please provide a reproduction app.

**Comment by nhuhuynh102** [comment]
> Dismissing the loading overlays with the `useIonLoading` hook works as expected: https://stackblitz.com/edit/angular-8f4eqy?file=src%2Fmain.tsx.
> 
> Please provide a reproduction app.

https://user-images.githubusercontent.com/117076964/200446643-d1fd446f-5e17-458c-80b4-59095d497b64.MP4

**Comment by sean-perkins** [comment]
@nhuhuynh102 making live changes in Stackblitz editor will result in an HMR build. This means the presented overlay will remain presented and then the new changes will take effect (the new loading indicator will be presented with the updated message). This is not a bug with the implementation. If you click the refresh icon to reload the iframe/example between changes to the code, this will not occur.

**Comment by ApayRus** [comment]
Hi. I have the same issue. It looks like 2 overlays appears, then 1 disappears, and another 1 still is showed.

**Comment by ApayRus** [comment]
```jsx
import React, { useContext, useEffect } from 'react'

import { IonMenu, useIonLoading } from '@ionic/react'

// import { useLocation } from 'react-router-dom'

import './Menu.css'

import TableOfContent from './TableOfContent'

import { NavigationContext } from './TableOfContentProvider'

const Menu: React.FC = () => {
	// const location = useLocation()

	const { tableOfContent, loaded } = useContext(NavigationContext)

	const [present, dismiss] = useIonLoading()

	useEffect(() => {
		console.log(loaded)
		if (loaded) {
			dismiss()
		}
		if (!loaded) {
			present({ message: 'loading' })
		}
	}, [loaded, dismiss, present])

	return (
		<IonMenu contentId='main' type='overlay'>
			<TableOfContent content={tableOfContent} parents={[]} />
		</IonMenu>
	)
}

export default Menu

```

**Comment by sean-perkins** [comment]
I reworked my example, as it was presenting the overlay twice as a result of the React 18 change for `useEffect` to fire twice in strict mode

https://stackblitz.com/edit/angular-8f4eqy-s2dbzm?file=src%2Fmain.tsx

Without a reproduction it is hard to say for certain, but I suspect the issue here is that React change: https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode/61897567#61897567

If this is the case, this isn't really a problem with Ionic. Your application should track the state of if the overlay has been presented and prevent calling `present` again, if it is already presented. Ionic has internal logic to do this for a single instance, but how the code is invoked, it is treated as presenting two separate overlays, which Ionic does not have control over.
