### ISSUE TITLE
bug: ion-datetime inside modal  appears differently when ion-datetime-button is present vs absent on the page

### ISSUE THREAD

**Issue by shaifulborhan** [ionic-team/ionic-framework#26247]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`ion-datetime` with `[preferWheel]=true` inside modal  appears differently when `ion-datetime-button` is present vs absent on the page.

When `ion-datetime-button` is present, the modal positioning looks as expected in the middle of the screen.

When `ion-datetime-button` is not present, the modal positioning is off centre from the screen.

### Expected Behavior

I expected the modal styling to not be affected by the presence or absence of `ion-datetime-button`.

### Steps to Reproduce

Stackblitz https://stackblitz.com/edit/angular-e1wzhj?file=src/app/example.component.html

Test how the `ion-datetime` modal looks by commenting and uncommenting the `ion-datetime-button` in the example.component.html template.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (/.nvm/versions/node/v14.20.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.4
   @angular-devkit/build-angular : 14.2.8
   @angular-devkit/schematics    : 14.2.8
   @angular/cli                  : 14.2.8
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : 4.4.0
   @capacitor/core    : 4.4.0
   @capacitor/ios     : 4.4.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v14.20.0 (/Users/shaifulborhan/.nvm/versions/node/v14.20.0/bin/node)
   npm    : 6.14.17
   OS     : macOS

**Comment by sean-perkins** [comment]
@shaifulborhan thanks for this issue.

In your example, you are linking the `ion-datetime-button` to the datetime instance with the id of `datetime`.

e.g.:
```html
<ion-datetime-button
  datetime="datetime"
  style="display:none;"
></ion-datetime-button>
```

The datetime button will append a class to the overlay of the datetime it is linked to, to handle necessary style changes.

If you do not want this behavior, either do not render `ion-datetime-button` in the DOM with a linked `ion-datetime`, or use an unique instance of `ion-datetime` with a different id for the `ion-input` implementation.

**Comment by shaifulborhan** [comment]
Hi @sean-perkins understood. 

What if I need the display the modal in the centre like the case for `ion-datetime-button` without using `ion-datetime-button`? I would like to trigger it with the `ion-input` only.

Thank you.

**Comment by shaifulborhan** [comment]
Adding `class=ion-datetime-button-overlay` to the `ion-modal` seems to do it.

Thanks!
