### ISSUE TITLE
bug: Action sheet icon is not centered on MD

### ISSUE THREAD

**Issue by twoco** [ionic-team/ionic-framework#26249]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Currently the icon in action sheet appears not centered. After debugging I found the following: 

https://github.com/ionic-team/ionic-framework/blob/1a0b9ed3bacffa9f602637c204f52cb3face5a3e/core/src/components/action-sheet/action-sheet.md.scss#L81

Why 4px padding? I removed it and voila, it's good center.

### Expected Behavior

Icon should be centered. 

### Steps to Reproduce

Create action sheet with icons in md mode and see that the icon are slighly moved up / not centered. Inspect that icon and see that there is 4px padding at the bottom. Wonder why.

**Current**
![current](https://user-images.githubusercontent.com/53160891/200688785-a3a6def7-a159-473f-a477-c5aeca8b5936.png)

**Expected** (fixed by removed padding)
![expected](https://user-images.githubusercontent.com/53160891/200688817-53914e77-07eb-41e6-be6e-70cc633d278a.png)

![image](https://user-images.githubusercontent.com/53160891/200689899-fa027f7f-0237-4901-b2eb-069529d6093b.png)

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework/blob/1a0b9ed3bacffa9f602637c204f52cb3face5a3e/core/src/components/action-sheet/action-sheet.md.scss#L81

### Ionic Info

Ionic Angular 6.2.6. But just see the source code on GitHub. There is padding for unknown reason.

**Comment by sean-perkins** [comment]
@twoco thank you for this issue.

I looked into why this was added and it isn't very clear. It was 4+ years ago and likely to align the content with other UI in the action sheet. Those changes seem to no longer apply.

We will track this as a bug.

**Comment by liamdebeasi** [comment]
Hey there,

Here is a dev build with a proposed fix if you are interested in testing:

```
6.3.6-dev.11668031717.1f4524fc
```

**Comment by twoco** [comment]
Thanks, I don't need to test. It's already in my fixes.scss ^^

Btw: Centering icons is not always trivial as one might think. It depends on several things. For example the typography or HTML elements behavior like line-height, etc. 

<img src="https://user-images.githubusercontent.com/53160891/201194115-390b0b6d-1861-4fab-8394-3f1c5286b811.png" height="50" />

I also had some issues with the Ionic Icons (Ionicons)

| Current | Edited |
| :-: | :-: |
| ![1](https://user-images.githubusercontent.com/53160891/201194477-4b5d2871-871e-4d85-9585-9d20a3aab369.png) | ![3](https://user-images.githubusercontent.com/53160891/201194483-153ea9c0-363b-4a7f-b6b0-92db61b99cc3.png) |
| ![2](https://user-images.githubusercontent.com/53160891/201194480-f63f17b3-f0a8-47fb-ad35-efccb2989e0a.png) | ![4](https://user-images.githubusercontent.com/53160891/201194484-87e93826-599b-4362-acf0-e4363ef24df2.png) |
| Logically perfectly centered. All edges same padding to the rect. | Optically centered. Depends on shape. | 

```html
<ion-icon name="play-outline"></ion-icon>
```

To be honest I have no idea how to call this optical phenomenon. Is there an algorithm to compute this center or is it only possible to do it manually? Maybe subjective. In this case all edges of the triangle needs the same distance to the circle? Anyway, just some thoughts ... think aloud. I faced this issue some time ago. I just created my own custom icon to fix this. Or add some margin / padding to it. Maybe I'm just a meticulous perfectionist. ^^ 

Anyway,... back to this issue... I think now it looks more professional. Maybe I only noticed it because I had customized the action sheet to have the appearance of iOS with MD touch feedback (ripple effect). And reduced the right margin between icon and text. Ok, merge and close this...

**Comment by liamdebeasi** [comment]
Thanks for the report. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26256, and a fix will be available in an upcoming release of Ionic Framework.
