### ISSUE TITLE
bug: platform#is('desktop') returning true on new Pixel 7 phones

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#26240]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

On new pixel 7 phones, when the devices screen resolution is set to factory defaults (e.g. "highest" / "smallest" or "make everything as small as possible to show as much as possible" ... max resolution), Ionic apps are reporting that the platform is 'desktop'.

If screen resolution is dropped down by one notch, the platform is properly reported as 'mobile'.

Not sure how best to report this, but this is what we're seeing.

### Expected Behavior

The platform should be reported as 'mobile', not 'desktop'.

### Steps to Reproduce

Run any ionic app on a Google Pixel 7 with default factory display settings. Platforms will contain 'desktop'.

### Ionic Info

```
mshark:topdecked-unified lincoln$ ionic info

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/lincoln/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.4
   @angular-devkit/build-angular : 14.2.8
   @angular-devkit/schematics    : 14.2.8
   @angular/cli                  : 14.2.8
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : 4.4.0
   @capacitor/core    : 4.4.0
   @capacitor/ios     : 4.4.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.14.0 (/Users/lincoln/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.3.1
   OS     : macOS Monterey

```

### Additional Information

None. Not sure if this issue is related: https://github.com/ionic-team/ionic-framework/issues/24179

**Comment by lincolnthree** [comment]
Thanks @liamdebeasi, I'll need to get that phone back into my hands so I can try this. (I do not have one, but I can get access to one as needed.)

Anything else you'd like me to record once I can do it all at once? (So I don't need to ask this person back over and over :)  )

**Comment by liamdebeasi** [comment]
If you could also check `pointer:none` for both, that would be great. Thanks!

The `isDesktop` function negates the result of `isMobile`: https://github.com/ionic-team/ionic-framework/blob/57105d54ea259fc9cd1a63e3d361ec8a57dd2971/core/src/utils/platform.ts#L92

`isMobile` checks if `any-pointer:coarse` matches on the device: https://github.com/ionic-team/ionic-framework/blob/57105d54ea259fc9cd1a63e3d361ec8a57dd2971/core/src/utils/platform.ts#L90 

This check should return `true` when a touch screen is present causing `isDesktop` to return `false`.

If `any-pointer:coarse` is returning `false`, then it could be that the device is incorrectly reporting the available pointers or something else is happening.

**Comment by lincolnthree** [comment]
Okay... I finally got my hands on a Pixel 7 again:

These are reported both in Chrome and also in Capacitor w/Default factory settings,

- '(any-pointer:coarse)': false
- '(pointer:coarse)': false
- '(any-pointer:fine)': true
- '(pointer:fine)': true
- '(any-pointer:none)': false
- '(pointer:none)': false

And some extra debug info: 
```
{"pixelRatio":2.625,"resolution":{"innerHeight":915,"outerHeight":915,"innerWidth":412,"outerWidth":412},"safeArea":{"top":"45px","bottom":"48px","left":"0px","right":"0px"}}
```

Versions:
```
Android 13
Chrome/WebView: 107.0.5304.105
Pixel 7 Build: TD1A.220804.031
```

**Comment by lincolnthree** [comment]
And for reference, as I'm sure you would expect, on my Pixel 6, it appears that the pointers are reported properly:

- '(any-pointer:coarse)': false
- '(pointer:coarse)': false
- '(any-pointer:fine)': true
- '(pointer:fine)': true
- '(any-pointer:none)': false
- '(pointer:none)': false

**Comment by liamdebeasi** [comment]
> And for reference, as I'm sure you would expect, on my Pixel 6, it appears that the pointers are reported properly:
> 
> * '(any-pointer:coarse)': false
> * '(pointer:coarse)': false
> * '(any-pointer:fine)': true
> * '(pointer:fine)': true
> * '(any-pointer:none)': false
> * '(pointer:none)': false

The Pixel 6 results look the same as the Pixel 7 results. Did you mean to copy something else?

Here are the results from my Pixel 4a:

- '(any-pointer:coarse)': true
- '(pointer:coarse)': true
- '(any-pointer:fine)': false
- '(pointer:fine)': false
- '(any-pointer:none)': false
- '(pointer:none)': false

-----

I recommend filing some feedback on https://bugs.chromium.org/p/chromium/issues/list regarding this. I don't have access to a Pixel 7 but I will see if someone else on the team has one.

**Comment by liamdebeasi** [comment]
I am also able to reproduce this using Pixel 7 through browserstack:

| Pixel 6 | Pixel 7 |
| - | - |
| ![Screen Shot 2022-11-11 at 4 32 01 PM](https://user-images.githubusercontent.com/2721089/201433888-fd0a93bf-e9ac-4057-8fec-d35ca446eaa1.png) | ![Screen Shot 2022-11-11 at 4 30 53 PM](https://user-images.githubusercontent.com/2721089/201433902-92fd53d2-c225-4093-a0bf-0550888695ad.png) |

**Comment by lincolnthree** [comment]
Weird. Yeah looks like I pasted the wrong results. My pixel 6 shows the same as your 4a.

**Comment by lincolnthree** [comment]
> I recommend filing some feedback on https://bugs.chromium.org/p/chromium/issues/list regarding this. I don't have access to a Pixel 7 but I will see if someone else on the team has one.

Yep, sigh.. will do on Monday. Though I have not had good luck with any of my issues being resolved IN Chromium :(

**Comment by lincolnthree** [comment]
Filed: https://bugs.chromium.org/p/chromium/issues/detail?id=1384181

**Comment by ajgomezrivera** [comment]
We're getting the same behavior for pixel 7 and 7 Pro. is Desktop is returned true.

**Comment by lincolnthree** [comment]
@ajgomezrivera Thanks. Please go to the chromium issue and add your vote to that too if you don't mind. We need Google to know it's an issue :)

**Comment by jsBiztech** [comment]
Is there any update on above issue.
When I create build using Ionic 6 and capacitor in pixel 7 our app is running in desktop mode instead of pure native app.

**Comment by vaibhav65577** [comment]
For anyone who faces this issue, currently you can make temporary changes in app.module.ts and override methods which returns browser and mobile properties .

you can make changes in App.module file
```
    IonicModule.forRoot(
      {
      spinner: platform == "core" ? "crescent" : platform == "ios" ? "lines" : "circles",
      platform : {
        'desktop':(win)=>{
          return false
        },
        'mobile':(win)=>{
          return true
        }
      }
    })
```

**Comment by skidrow88** [comment]
I confirm on the Pixel 7 pro my app is acting like Desktop => isDesktop is returned true. 

Thanks for @vaibhav65577 for your temporary fix, I will try. 

Any capacitor permanent update expected ?
