### ISSUE TITLE
bug: Datetime with showClearButton does not clear when selected date is from active month

### ISSUE THREAD

**Issue by sagun-gautam** [ionic-team/ionic-framework#26258]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [x] v6.x
- [ ] Nightly

### Current Behavior

ion-datetime picker with 'Clear' button enabled, does not clear the datetime picker if selected date is from current month.
Should the modal be closed after clear event? Does not close modal after clear event.

### Expected Behavior

Should clear the current date value selection and close the datetime picker modal.

### Steps to Reproduce

```
    <ion-input
      id="myDatePicker"
      class="ion-text-start"
      [formControlName]="fieldID"
      readonly="true"
    ></ion-input>

    <ion-modal
      trigger="myDatePicker"
      size="cover"
      alignment="center"
    >
      <ng-template>
        <ion-content>
          <ion-datetime
            #datetime
            presentation="date"
            [value]="pickerCurrentDate"
            [max]="field.max"
            [min]="field.min"
            [cancelText]="field.cancelText | translate"
            [doneText]="field.doneText | translate"
            [clearText]="field.clearText | translate"
            showDefaultButtons="true"
            showClearButton="true"
            (ionChange)="onChange(datetime.value)"
          >
          </ion-datetime>
        </ion-content>
      </ng-template>
    </ion-modal>
```

### Code Reproduction URL

https://stackblitz.com/edit/angular-dgizef

### Ionic Info

**Ionic:**
   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.3.5 
   @angular-devkit/build-angular : 12.2.18
   @angular-devkit/schematics    : not installed
   @angular/cli                  : 12.2.18 
   @ionic/angular-toolkit        : 2.3.3

**Cordova**:
   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.2, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 19 other plugins)

**Utility**:
   cordova-res : 0.15.4
   native-run  : not installed globally

**System**:
   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v14.19.0 
   npm               : 6.14.16
   OS                : macOS Monterey
   Xcode             : Xcode 14.1 Build version 14B47b

**Comment by sean-perkins** [comment]
@sagun-gautam thank you for reporting this issue. I am able to reproduce and have attached a reproduction to the original issue.

We will track this as a bug.

**Comment by sean-perkins** [comment]
Here is a dev-build to test with: `6.3.7-dev.11668105872.16a97bcc`

Thanks!
