### ISSUE TITLE
feat: Ability to develop third-party platform integration like iOS and Android

### ISSUE THREAD

**Issue by Losses** [ionic-team/ionic-framework#26259]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Since Cordova supports developing a new platform, we are considering if Capacitor could provide similar capacity.

### Describe the Use Case

We have successfully integrated GeckoView with Ionic, but it's pretty hard to make the integration play well with the ionic framework, what we want is bundle the platform based on GeckoView into an independent package, similar to `@capacitor/android`, we want to build a package called `@recative/ionic-android-geckoview`, 
in this way, we can build package based on Chromium WebView and GeckoView at the same time for different market. 

#### Why?
It's pretty important for us to build an Android Application based on GeckoView for some country like China, since Google Play is not available in these countries, as a result, a lot of Android devices have a pretty old WebView (Like Chromium 72 or Chromium 64).

some vendors like MI are also troublemakers which tried to modify the UA and pretend their WebView is newer than what it actually is.

To handle complex problems, we think ship GeckoView with the application is a better solution. But for the market that covered by Google Play, we still want to use Android WebView since it's smaller, has a better performance. 

For these reasons, treat the combination of Android and GeckoView as an independent platform is more practical for us, so we drafted this issue.

**Comment by sean-perkins** [comment]
@Losses does this feature request belong with Capacitor: https://github.com/ionic-team/capacitor?

The Ionic Framework is a collection of UI web components for building interfaces that look like Material or iOS.

**Comment by jcesarmobile** [comment]
This is already possible.
Take a look into the two community platforms
https://github.com/capacitor-community/electron
https://github.com/capacitor-community/tauri
