### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by leocharrua** [ionic-team/ionic-framework#26254]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hello. I have a form with a ion-datetime-button and a ion-datetime binded:

```
        <ion-datetime-button datetime="datetimepicker"></ion-datetime-button>
        <ion-modal [keepContentsMounted]="true">
          <ng-template>
            <ion-datetime id="datetimepicker" formControlName="report_at"
              presentation="date"
            ></ion-datetime>
          </ng-template>
        </ion-modal>

```

When editing a item (with report_at info), I get this error in the console:

instrument.js:108 TypeError: Cannot destructure property 'month' of '(0 , _data_64bc531e_js__WEBPACK_IMPORTED_MODULE_9__.P)(...)' as it is undefined.
    at Datetime.processValue (ion-datetime_3.entry.js:698:15)
    at Datetime.componentWillLoad (ion-datetime_3.entry.js:1070:10)
    at safeCall (index-8e692445.js:1458:20)
    at dispatchHooks (index-8e692445.js:1315:23)
    at Array.dispatch (index-8e692445.js:1299:28)
    at consume (index-8e692445.js:2242:13)
    at flush (index-8e692445.js:2257:9) undefined
(anonymous) @ instrument.js:108
consoleError @ index-8e692445.js:2200
safeCall @ index-8e692445.js:1461
dispatchHooks @ index-8e692445.js:1315
dispatch @ index-8e692445.js:1299
consume @ index-8e692445.js:2242
flush @ index-8e692445.js:2257
requestAnimationFrame (async)
raf @ ionic-angular.js:17
(anonymous) @ index-8e692445.js:2235
scheduleUpdate @ index-8e692445.js:1300
setValue @ index-8e692445.js:1761
set @ index-8e692445.js:1785
(anonymous) @ ion-button_2.entry.js:423
invoke @ zone.js:375
run @ zone.js:134
(anonymous) @ zone.js:1278
invokeTask @ zone.js:409
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:588
Promise.then (async)
nativeScheduleMicroTask @ zone.js:564
scheduleMicroTask @ zone.js:575
scheduleTask @ zone.js:399
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1268
resolvePromise @ zone.js:1205
(anonymous) @ zone.js:1121
(anonymous) @ zone.js:1137
Promise.then (async)
(anonymous) @ zone.js:1512
ZoneAwarePromise @ zone.js:1432
Ctor.then @ zone.js:1511
(anonymous) @ ion-button_2.entry.js:328
invoke @ zone.js:375
run @ zone.js:134
(anonymous) @ zone.js:1278
invokeTask @ zone.js:409
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:588
Promise.then (async)
nativeScheduleMicroTask @ zone.js:564
scheduleMicroTask @ zone.js:575
scheduleTask @ zone.js:399
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1268
resolvePromise @ zone.js:1205
(anonymous) @ zone.js:1121
(anonymous) @ zone.js:1137
Promise.then (async)
(anonymous) @ zone.js:1512
ZoneAwarePromise @ zone.js:1432
Ctor.then @ zone.js:1511
(anonymous) @ instrument.js:137
getSvgContent @ ion-button_2.entry.js:326
loadIcon @ ion-button_2.entry.js:423
(anonymous) @ ion-button_2.entry.js:387
waitUntilVisible @ ion-button_2.entry.js:410
connectedCallback @ ion-button_2.entry.js:385
safeCall @ index-8e692445.js:1458
fireConnectedCallback @ index-8e692445.js:1955
(anonymous) @ index-8e692445.js:1921
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
ZoneAwarePromise @ zone.js:1432
(anonymous) @ asyncToGenerator.js:21
initializeComponent @ index-8e692445.js:1871
(anonymous) @ index-8e692445.js:2021
invoke @ zone.js:375
run @ zone.js:134
(anonymous) @ zone.js:1278
invokeTask @ zone.js:409
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:588
invokeTask @ zone.js:494
invokeTask @ zone.js:1664
globalCallback @ zone.js:1707
globalZoneAwareCallback @ zone.js:1728
Show 76 more frames
node_modules_ionic_core_dist_esm_ion-picker-internal_entry_js.js:2 Unhandled Promise rejection: Cannot set properties of undefined (setting 'tzOffset') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set properties of undefined (setting 'tzOffset')
    at ion-datetime-button.entry.js:76:9
    at Array.forEach (<anonymous>)
    at DatetimeButton.setDateTimeText (ion-datetime-button.entry.js:75:23)
    at ion-datetime-button.entry.js:303:12
    at helpers-3b390e48.js:62:48
    at _ZoneDelegate.invoke (zone.js:375:26)
    at Zone.run (zone.js:134:43)
    at zone.js:1278:36
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:588:35) TypeError: Cannot set properties of undefined (setting 'tzOffset')
    at http://localhost:8100/node_modules_ionic_core_dist_esm_ion-datetime-button_entry_js.js:118:33
    at Array.forEach (<anonymous>)
    at DatetimeButton.setDateTimeText (http://localhost:8100/node_modules_ionic_core_dist_esm_ion-datetime-button_entry_js.js:117:23)
    at http://localhost:8100/node_modules_ionic_core_dist_esm_ion-datetime-button_entry_js.js:424:16
    at http://localhost:8100/vendor.js:13076:46
    at _ZoneDelegate.invoke (http://localhost:8100/polyfills.js:8207:158)
    at Zone.run (http://localhost:8100/polyfills.js:7944:35)
    at http://localhost:8100/polyfills.js:9292:28
    at _ZoneDelegate.invokeTask (http://localhost:8100/polyfills.js:8240:171)
    at Zone.runTask (http://localhost:8100/polyfills.js:7997:37)
    at drainMicroTaskQueue (http://localhost:8100/polyfills.js:8449:23)
(anonymous) @ instrument.js:108
api.onUnhandledError @ zone.js:1064
handleUnhandledRejection @ zone.js:1089
api.microtaskDrainDone @ zone.js:1083
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
nativeScheduleMicroTask @ zone.js:564
scheduleMicroTask @ zone.js:575
scheduleTask @ zone.js:399
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1268
resolvePromise @ zone.js:1205
(anonymous) @ zone.js:1121
(anonymous) @ zone.js:1137
postUpdateComponent @ index-8e692445.js:1423
postUpdate @ index-8e692445.js:1348
(anonymous) @ index-8e692445.js:1350
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
ZoneAwarePromise @ zone.js:1432
(anonymous) @ asyncToGenerator.js:21
updateComponent @ index-8e692445.js:1324
(anonymous) @ index-8e692445.js:1322
then @ index-8e692445.js:1467
dispatchHooks @ index-8e692445.js:1322
dispatch @ index-8e692445.js:1299
consume @ index-8e692445.js:2242
flush @ index-8e692445.js:2257
requestAnimationFrame (async)
raf @ ionic-angular.js:17
(anonymous) @ index-8e692445.js:2235
scheduleUpdate @ index-8e692445.js:1300
schedule @ index-8e692445.js:1939
(anonymous) @ index-8e692445.js:1950
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
invoke @ zone.js:375
run @ zone.js:134
(anonymous) @ zone.js:1278
invokeTask @ zone.js:409
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:588
Promise.then (async)
nativeScheduleMicroTask @ zone.js:564
scheduleMicroTask @ zone.js:575
scheduleTask @ zone.js:399
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1268
resolvePromise @ zone.js:1205
(anonymous) @ zone.js:1121
(anonymous) @ zone.js:1137
webpackJsonpCallback @ jsonp chunk loading:77
(anonymous) @ node_modules_ionic_core_dist_esm_ion-picker-internal_entry_js.js:2
Show 52 more frames
zone.js:375 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'tzOffset')
    at ion-datetime-button.entry.js:76:9
    at Array.forEach (<anonymous>)
    at DatetimeButton.setDateTimeText (ion-datetime-button.entry.js:75:23)
    at ion-datetime-button.entry.js:303:12
    at helpers-3b390e48.js:62:48
    at _ZoneDelegate.invoke (zone.js:375:26)
    at Zone.run (zone.js:134:43)
    at zone.js:1278:36
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:588:35)

The value of report_at is "2021-05-13 00:00:00", but fails with any date with the same format.

Can you help me?

### Expected Behavior

I suppose, the control must handle the date format.

### Steps to Reproduce

Please, see the behavior description.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (C:\Users\leoch\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.3.4
   @angular-devkit/build-angular : 14.2.8
   @angular-devkit/schematics    : 14.2.8
   @angular/cli                  : 14.2.8
   @ionic/angular-toolkit        : 7.0.0

**Comment by sean-perkins** [comment]
@leocharrua thank you for this issue.

The date string you provided is not a valid ISO 8601 format. 

Can you try with `2021-05-13T00:00:00` and let me know if the problem persists?

Reproduction: https://stackblitz.com/edit/angular-uwg4dp

**Comment by leocharrua** [comment]
Hello. Thanks for the answer.
Yes, I converted the date to ISO format and works! Thanks

But this is the concern: I'm migrating from Ionic 5 to Ionic 6, and with the previous version, I have a ion-datetime with the same binding and works ok with the date in format yyyy-mm-dd HH:MM:ss. Now, with the new version of the control, not.

Thanks again

**Comment by sean-perkins** [comment]
@leocharrua the Ionic 5 to Ionic 6 migration is a major release cycle and includes a significant change to the `ion-datetime` component. In Ionic 6, we only accept ISO-8601 date strings, as accepting any raw formatting and converting it, is extremely complex to do correct across all instances and existing libraries already solve this problem space (e.g. `date-fns`). 

In your scenario, you should be able to format the date values in the form group and it will work as expected: https://stackblitz.com/edit/angular-uwg4dp-v5tnw2?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fexample.component.ts
