### ISSUE TITLE
bug: Textarea does not show scrollbars when contents overflow

### ISSUE THREAD

**Issue by ReneZeidler** [ionic-team/ionic-framework#26278]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`ion-textarea`s with a fixed or max height do not show a scrollbar when the text height exceeds the textarea height. Scrolling with the scroll wheel also doesn't work.

### Expected Behavior

A vertical scrollbar appears when the textarea contains more text than the vertical available space. The user can scroll inside the textarea using the scroll wheel or scrollbar.

### Steps to Reproduce

1. Clone the reproduction repository
2. Start the project
3. Observe that the textareas under "Current behavior" cannot be scrolled, making the full contents unreadable
4. The textareas under "Expected behavior" have "overflow: unset" applied to them via a global style, allowing normal scroll behavior.

Alternatively, visit https://ionicframework.com/docs/api/textarea and enter more than 3 lines in the first live example under "Basic Usage" (labelled "Regular textarea"). You're unable to scroll inside the textarea.

### Code Reproduction URL

https://github.com/ReneZeidler/bug-textarea-scroll

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/usr/local/share/npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.6
   @angular-devkit/build-angular : 14.2.9
   @angular-devkit/schematics    : 14.2.9
   @angular/cli                  : 14.2.9
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.18.0 (/usr/local/bin/node)
   npm    : 9.1.1
   OS     : Linux 5.10

### Additional Information

The regression was introduced by commit https://github.com/ionic-team/ionic-framework/commit/a9cf2ab87012cdb6360d10536a29213adda3f585 as a fix for #24793.

However, fixing the bug for textareas with `autoGrow="true"` broke scrolling for textareas with `autoGrow="false"` (the default) by [setting `overflow: hidden`](https://github.com/ionic-team/ionic-framework/commit/a9cf2ab87012cdb6360d10536a29213adda3f585#diff-62d8555c25840ae9b6fc66ac7fa63eb8fa2f653acf0a89fd43001356c2e50ed7R125) on the native `textarea` element.

**Comment by sean-perkins** [comment]
@ReneZeidler thank you for reporting this issue.

Yes, we likely need to apply the `overflow: hidden` style only for when auto grow is used on the textarea.

We will capture this as a bug and prioritize. Thanks!

**Comment by sean-perkins** [comment]
Hello @ReneZeidler can you test with this dev-build and let me know if you run into any issues?

```bash
npm install @ionic/angular@6.3.7-dev.11668447091.1afa4f71
```

**Comment by ReneZeidler** [comment]
@sean-perkins Thank you for the very quick response!

I can confirm that this build fixes the issue.

**Comment by sean-perkins** [comment]
Awesome, thank you for testing!

This bug has been resolved and will be available in the next patch release of Ionic (6.3.7).
