### ISSUE TITLE
bug: Failed to load resource: The file “core.css.map” couldn’t be opened because there is no such file error shown in the browser console on iOS

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#26277]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When the application runs on an iOS device there is error logged saying that it can not find source map file. For example
```
Failed to load resource: The file “core.css.map” couldn’t be opened because there is no such file.
```
or see below
<img width="1379" alt="Screen Shot 2022-11-14 at 14 51 24" src="https://user-images.githubusercontent.com/3608222/201665540-f312e651-8112-4a53-af1d-868fd43527c2.png">

### Expected Behavior

No error must be thrown/logged

### Steps to Reproduce

1) create new ionic project from one of the started template projects
2) in **src/global.scss** replace @import to @use (and update the imported links accordingly)
3) build and run the application on iOS device
Note that there is the below error shown in the console
```
Failed to load resource: The file “core.css.map” couldn’t be opened because there is no such file.
```

OR, you can clone this project https://github.com/ryaa/scss-use-issue-demo, change to the project directory, run `npm install` and then `ionic capacitor build ios` (assuming that you have all the required tools installed/configured), build/run the project on an iOS simulator or a real device and check the console for the above error.
This change/commit makes the error to appear https://github.com/ryaa/scss-use-issue-demo/commit/e63717ffd10e169fd4237db64c548ec273052cd5

### Code Reproduction URL

https://github.com/ryaa/scss-use-issue-demo

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.3 (/Users/alexryltsov/.nvm/versions/node/v18.12.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.6
   @angular-devkit/build-angular : 14.2.9
   @angular-devkit/schematics    : 14.2.9
   @angular/cli                  : 14.2.9
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : not installed
   @capacitor/core    : 4.4.0
   @capacitor/ios     : 4.4.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.12.0 (/Users/alexryltsov/.nvm/versions/node/v18.12.0/bin/node)
   npm    : 9.0.0
   OS     : macOS Monterey
```

### Additional Information

Please note that everything works fine with @import but replacing it to @use in **src/global.scss** makes the generated **www/style.css** file to contain links to the source maps files which fail to load - see below

Here is the **www/style.css** file with @import  in **src/global.scss**. Note that there is only one and the correct **sourceMappingURL** entry in the file
<img width="1076" alt="Screen Shot 2022-11-14 at 14 40 47" src="https://user-images.githubusercontent.com/3608222/201667215-abe2a021-f8f8-4e1b-b044-38756f71f3f1.png">

Here is the **www/style.css** file with @use  in **src/global.scss**. Note that there are multiple and the invalid **sourceMappingURL** entries in the file
<img width="1257" alt="Screen Shot 2022-11-14 at 14 50 13" src="https://user-images.githubusercontent.com/3608222/201667561-afd8a941-cda4-462e-8a35-ee2e3e91ed86.png">
The above **sourceMappingURL** fails when the app runs.

**Comment by liamdebeasi** [comment]
Thanks for the issue. While I can reproduce this behavior, this does not appear to be a bug in Ionic. All application compilation is handled by the Angular CLI, so I recommend filing an issue with them.

It looks like the compiler decided to inline all the source maps in `styles.css.map` but did not remove the other source map reference comments.

**Comment by ryaa** [comment]
> Thanks for the issue. While I can reproduce this behavior, this does not appear to be a bug in Ionic. All application compilation is handled by the Angular CLI, so I recommend filing an issue with them.

That's what I thought and will open an issue with Angular CLI.

**Comment by mobilityvalley** [comment]
Is there a solution for this error or a way to get rid of this error in the console debugger ?

**Comment by liamdebeasi** [comment]
Hi everyone,

This was a bug with the Sass compiler that has since been fixed: https://github.com/sass/dart-sass/commit/aceb1e8c51788b9e225bcb0762a138ceb099034d

Developers should update to Angular 15 or newer to receive this fix since `sass` is a dependency of Angular.
