### ISSUE TITLE
bug: Tabs show empty header during activation (Angular)

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#26280]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When a tab is activated for the first time, the header will briefly display. This does not occur when navigating between tabs a second time. 

This issue is only present in Angular. Observed back to `6.1.9` (when we supported Angular 14). Would need to downgrade an app to v13 to validate earlier versions. 

<video src="https://user-images.githubusercontent.com/13732623/201712309-e0e85ccc-9f76-4ff0-ac6a-ef33a0793cc9.mp4"></video>

Direct video link: https://user-images.githubusercontent.com/13732623/201712309-e0e85ccc-9f76-4ff0-ac6a-ef33a0793cc9.mp4

### Expected Behavior

The header should not be visible when activating a tab, if a tab does not have contents within the header. 

### Steps to Reproduce

1. Clone tabs starter for Angular
2. Click between the tabs
3. Observe: Header briefly appears
4. Click between the tabs
5. Observe: Header does not appear (expected)

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.18.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.6
   @angular-devkit/build-angular : 14.2.9
   @angular-devkit/schematics    : 14.2.9
   @angular/cli                  : 14.2.9
   @ionic/angular-toolkit        : 6.1.0
```

**Comment by liamdebeasi** [comment]
Hi everyone,

This issue was resolved in Ionic 7.5.5: https://github.com/ionic-team/ionic-framework/pull/28472. If you are still running into this problem please create a new issue and include a reproduction.
