### ISSUE TITLE
feat: `canDismiss` handler for modal should accept `role`

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#26292]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The `canDismiss` handler for `ion-modal` should accept an argument for `role`.

```ts
canDismiss(role?: string): boolean;
```

### Describe the Use Case

With `swipeToClose` being deprecated and removed in the near future, developers will need to migrate their implementation to use `canDismiss`. `canDismiss` while similar to the behavior of `swipeToClose`, behaves differently and can require additional code for developers.

For example, if a user is presenting a card modal, but wants to disable swiping to dismiss the overlay they will need to set `canDismiss` to `false`. But when a button is clicked to dismiss the overlay, developers will now need to set `canDismiss` to `true`. This requires an additional property in the implementation to keep track of the state of `canDismiss`. Prior to the deprecation of `swipeToClose`, developers would just set `swipeToClose` to `false` and when dismissing the overlay, the overlay would dismiss without any additional action required by the developer. 

### Describe Preferred Solution

```html
<ion-modal [canDismiss]="canDismiss"></ion-modal>
```

```ts
canDismiss = (role?: string) => {
  // roles tied to clicking a "Confirm" button or "Cancel" button.
  return role === 'confirm' || role === 'cancel';
}
```

### Additional Information

This feature was split from discussion started here: https://github.com/ionic-team/ionic-framework/issues/26173#issuecomment-1315333147

**Comment by liamdebeasi** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/26384
