### ISSUE TITLE
No smooth and overlapping when navcontroller.pop()

### ISSUE THREAD

**Issue by goltra** [ionic-team/ionic-framework#26309]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I've created a sample application to demonstrate the problem that only happen in Android. I have test with cordova and capacitor but this sample is with capacitor and with two differents terminales, Xiaomi Mi A1 and Motorola g30

I have two pages, one with a list an other for detail.

You have a list of <ion-item> (93  items) that you can click and go to detail page.  Items is a variable with an array with objects set manually (no loading from database or api).

```html
<ion-item (click)="edit()" *ngFor="let o of data; let i=index; trackBy: trackBy">
     {{o._id}} - {{o.name}}
</ion-item>
```

Once in the detail, whose --background is red to see better what I mean, I have two buttons, one that returns to the list page using router.navigate and another using navController.pop().
```html
<ion-button (click)="salir()">salir router</ion-button>
<ion-button (click)="salirPop()">salir pop</ion-button>
```
```javascript
salir(){
    this.router.navigate(['/']);
 }
salirPop(){
    this.navCtrl.pop()
}
```

Both, when animating is running to back from detail to list, the detail page is overlapping for a few moments over list and transition animation is not smooth.  You can see is most noticiable with pop. If a left only one item in list then works smooth and without overlapping.

I have recorded the screen to better understand what I mean. In the video I click in one item, after in detail I click first in pop button, second time in router button..  (I explain because in video yo can't see where I'm touching).

Xiaomi

https://user-images.githubusercontent.com/1634767/202385209-f4522173-13bb-496c-8c65-42588fa893cf.mp4

Motorola

https://user-images.githubusercontent.com/1634767/202386845-2bf435ca-9eab-40df-aeae-d19cf6d49dcc.mp4

This is only an example to show you the problem. I detect it in a project I'm migrating from ionic3 to ionic6. I'm finishing migration and I check my new project in iOS and web and works fine but not in android.

### Expected Behavior

Should work smooth and without overlapping in Android like is doing in web and iOS.

### Steps to Reproduce

I have prepare a repo to you where you can reproduce this issue.

### Code Reproduction URL

https://github.com/goltra/ionic6-test-pop-route

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.6
   @angular-devkit/build-angular : 14.2.9
   @angular-devkit/schematics    : 14.2.9
   @angular/cli                  : 14.2.9
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : 4.4.0
   @capacitor/core    : 4.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v14.17.0 (/usr/local/bin/node)
   npm    : 6.14.13
   OS     : macOS Catalina

**Comment by liamdebeasi** [comment]
Thanks for the report. Are you able to point to a particular piece of Ionic that could be responsible for this? I test this on a Samsung Galaxy S3 as well as a Moto G4 and was unable to reproduce the reported behavior.

**Comment by goltra** [comment]
> Thanks for the report. Are you able to point to a particular piece of Ionic that could be responsible for this? I test this on a Samsung Galaxy S3 as well as a Moto G4 and was unable to reproduce the reported behavior.

You can see in the repo the project is so simple.. only have a data object with 93 items,  I load it in a page with an ngFor painting <ion-item> and when click on one it navigate to detail component.. when you click un button push or route it return to list as you can see in videos... I test it in to diferents models.. 

Have you tried the project from my report?

**Comment by liamdebeasi** [comment]
Yes, I ran the project on the devices I noted but was unable to reproduce the behavior. Here is what I see on a Motorola Moto G4:

https://user-images.githubusercontent.com/2721089/202486654-314d1b12-a763-4cff-bc8d-72091921b76f.mp4

**Comment by liamdebeasi** [comment]
What version of the Chrome webview are you running on the affected devices? You can find this by logging `window.navigator.userAgent` when debugging the app with Chrome Dev Tools.

**Comment by goltra** [comment]
> Member

In Xiaomi Mi A1 
'Mozilla/5.0 (Linux; Android 9; Mi A1 Build/PKQ1.180917.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Mobile Safari/537.36'

Moto G3
'Mozilla/5.0 (Linux; Android 12; moto g(30) Build/S0RCS32.41-10-9-2-4; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Mobile Safari/537.36'

**Comment by goltra** [comment]
I can't believe it.. in G3 now works fine but not in Xiaomi but better than this morning.. goodness I have record the screen because in other hand I will believe I was getting crazy.
Nevertheless is not smooth and I still have an overlapping in Xiaomi.

**Comment by liamdebeasi** [comment]
Does the issue persist if you reboot the Xiaomi device?

**Comment by goltra** [comment]
I attach again the video after restart.. now in less smooth when I use route to back to previous than pop.. I can't understand
(firs touch in router, second in pop)

https://user-images.githubusercontent.com/1634767/202688682-c5fb3cd9-1703-436b-bd6f-fe662f3314bb.mp4

**Comment by liamdebeasi** [comment]
Can you do some debugging with Chrome Dev Tools to see what is happening when the slow down occurs?
