### ISSUE TITLE
bug: ion-picker doesn't support disabled options between enabled options

### ISSUE THREAD

**Issue by austinrzg** [ionic-team/ionic-framework#26308]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using an ion-picker with a list of options that begins with 1+ enabled, contains 1+ disabled options in the middle, then ends with 1+ enabled options, the selector doesn't correctly auto-select an enabled option. Further the selector allows the user to select a disabled option.

### Expected Behavior

Users should not be able to select a disabled PickerColumnOption.
PickerColumn should auto-select a valid option if the user attempts to choose a disabled option.

### Steps to Reproduce

1. Create a simple ion-picker with a set of options - recommend 7 options to easily see the issue.
2. Set the options as follows:
- 0: disabled = false
- 1: disabled = false
- 2: disabled = true
- 3: disabled = true
- 4: disabled = true
- 5: disabled = false
- 6: disabled = 6
3. Attempt to select a disabled option.

*Note, you may need to adjust the CSS for .picker-opt-disabled in order to see the disabled options more easily.

### Code Reproduction URL

https://github.com/austinrzg/angular-fqvgd8

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.18.1
   npm    : 8.1.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you double check your sample app? I get this error when trying to run it:

```
This version of CLI is only compatible with Angular versions 0.0.0 || ^11.0.0-beta || >=11.0.0 <12.0.0,
but Angular version 12.1.0 was found instead.

Please visit the link below to find instructions on how to update Angular.
https://update.angular.io/
```
