### ISSUE TITLE
feat: ion-popover dismissOnLeave

### ISSUE THREAD

**Issue by KANekT** [ionic-team/ionic-framework#26324]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

need close popover on leave element

### Describe the Use Case

if use trigger action trigger-action="hover" for element by id

need event on leave from popover-content for hide popover in web browser

in hover -> show popover
in leave -> hide popover

### Describe Alternatives

https://dev-bay.com/popover-on-hover-in-vuejs/

**Comment by KANekT** [comment]
@liamdebeasi in web app in standard use case for popover

https://dev-bay.com/popover-on-hover-in-vuejs/

I use app in iOS/android mobile and planed use in electron and web site

**Comment by liamdebeasi** [comment]
Is this use case primarily targeting desktop applications?

**Comment by KANekT** [comment]
Decstop web applications 

And browser web applications - spa

**Comment by liamdebeasi** [comment]
Thanks! Ionic Framework focuses on mobile applications, so features that target desktop web applications are out of scope for this project. Previously we have added desktop-focused features, but moving forward our focus is going to be on mobile.

However, you should be able to implement this functionality with a `mouseleave` listener on your popover content.

Here is a vanilla JS example: https://codepen.io/liamdebeasi/pen/dyKdPmp?editors=1010
@sean-perkins Also made an Angular example too: https://stackblitz.com/edit/p3gqlu?file=index.html

Can you give this a try and let me know if it works for your application?

**Comment by KANekT** [comment]
Thanks for the answer and solution.

The popover implementation is not suitable in my project, ion-backdrop full page (even hidden) is not the best solution for the web

https://valgeirb.github.io/vue3-popper/ - for web is better and has small code

**Comment by liamdebeasi** [comment]
Are you able to use Vue 3 Poppoer for this use case?

**Comment by KANekT** [comment]
may be you added current example for doc's to another users

**Comment by liamdebeasi** [comment]
Thanks for the additional information. I am going to close this as the original issue is resolved by using Vue 3 Popper. Let me know if you have any questions.
