### ISSUE TITLE
feat(grid): replace padding with gap 

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#26321]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I really like the Grid Component. The most often issue i have with this is the usage of the padding which i would like to discuss here.

Because of the usage of the padding for every column it is not possible to have left items at the containers left and the right items completly right, there will always be a small "gap" for the column's content. Also removing the passing is not an option as then the space iin between of the items is gone.

So i played around with `gap` a bit and i guess it could be an alternative by removing the column's padding and replacing the style attributes to reflect the width accordantly. 

Is this possible or is there any other solution for my problem?

### Describe the Use Case

Text in a grid column should be possible to align at the containers border

### Describe Preferred Solution

To be discussed

**Comment by liamdebeasi** [comment]
Do you have an example of the problem you are running into?

**Comment by EinfachHans** [comment]
In our designs we have many "components" where a grid makes sense for me to use. Have a look at this stackblitz: https://stackblitz.com/edit/ionic6-angular13?file=src/app/app.component.html

I can't easily use the Grid here, as the usage of the padding makes the texts not aligned.

**Comment by liamdebeasi** [comment]
Are you able to use CSS Grid with its gap feature as an alternative? We are not able to utilize `gap` in flexbox since it has newer browser support: https://caniuse.com/flexbox-gap.

**Comment by EinfachHans** [comment]
Ah okay that browser support is to new i see 😕 Yeah there are custom solutions of course but i really like the grid component thats why it would be great to somehow be able to have it aligned completely to the containers edges. Any other ideas?

**Comment by liamdebeasi** [comment]
Sounds good. I am going to close this, but let me know if you have any questions.
