### ISSUE TITLE
bug: ion-datetime can't set current time with confirm() method

### ISSUE THREAD

**Issue by dragermrb** [ionic-team/ionic-framework#26338]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

ion-datetime doesn't allow to confirm current time without change any values (hours or minutes).

If you have one variable **with null value** assigned to `ion-datetime` ngModel, when you try to confirm the time, variable doesn't get updated.

### Expected Behavior

Allow to select and confirm current time.

### Steps to Reproduce

```html
<ion-datetime #datetime presentation="time" [(ngModel)]="myDate">
  <ion-buttons slot="buttons">
    <ion-button color="danger" (click)="datetime.reset()">Reset</ion-button>
    <ion-button color="primary" (click)="datetime.cancel()"
      >Never mind</ion-button
    >
    <ion-button color="primary" (click)="datetime.confirm()"
      >All Set</ion-button
    >
  </ion-buttons>
</ion-datetime>

<!-- myDate = null initially -->
<p>My Date: _{{ myDate }}_</p>

```

- Visit code reproduction url: [Demo](https://stackblitz.com/edit/angular-uba3ym?file=src/app/example.component.html)
- Click on `All set`. Variable is not updated.
- Click on current time and click on `All set`. Variable is not updated.
- Click on another time and click on `All set`. Variable is updated.
- You can change to another time and back to current time and then variable is updated.

### Code Reproduction URL

https://stackblitz.com/edit/angular-uba3ym?file=src/app/example.component.html

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.4
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0
```

**Comment by liamdebeasi** [comment]
Thanks for the report. This appears to be another instance of https://github.com/ionic-team/ionic-framework/issues/25839, so I am going to merge the two threads. The problem here is the wheel picker does not auto-select the first item (even though it is visually selected).
