### ISSUE TITLE
bug: clear button does not change color when color is set on item

### ISSUE THREAD

**Issue by Mathieu-COSYNS** [ionic-team/ionic-framework#26337]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I recently took a look at issue https://github.com/ionic-team/ionic-framework/issues/19178 and submitted a pull request to solve it https://github.com/ionic-team/ionic-framework/pull/26217 (still pending).

I thought that it could be nice if the clear button could take the color specified on the ion-input element as shown in the picture below.

![image](https://user-images.githubusercontent.com/64072917/203358937-0b4d64b0-0349-435f-b6c6-628254daa73e.png)

An other idea that could be more interesting is to change the color base on the text color use. It will provide a better contrast and improve accessibility of color blind people. 

![image](https://user-images.githubusercontent.com/64072917/203358535-015f02f5-854f-46b2-9d90-0a281a18f81a.png)

### Describe the Use Case

Customization of the clear button and/or improvement on color contrast because the current gray color in not very well visible on some background.

### Additional Information

Current behavior
![image](https://user-images.githubusercontent.com/64072917/203362553-f7c33b08-1eda-4615-86f5-40306edfb0a3.png)

**Comment by liamdebeasi** [comment]
Thanks for the report. Is this a different request than https://github.com/ionic-team/ionic-framework/issues/19178?

**Comment by Mathieu-COSYNS** [comment]
> Thanks for the report. Is this a different request than #19178?

In https://github.com/ionic-team/ionic-framework/issues/19178 @SidiBecker wish to change the color of the clear button by setting the --ion-color-step-600 prop in CSS.

What I would like to have is, in case of the first screen, that the color change base on the ion-input color attribute like at <ion-input color="primary" />. In the case of the second screen I don't know how it could be achieved but the color should changed base on the color contrast provided by the <ion-item> who wrap around the <ion-input />.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26592, and a fix will be available in an upcoming release of Ionic Framework.
