### ISSUE TITLE
bug: ionic/vue router life cycle hook fired many time when swich tab with dynamic route 

### ISSUE THREAD

**Issue by t871631092** [ionic-team/ionic-framework#26355]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

routing structure:
```
/:lang/tabs/tab1
           /tab2
           /tab3
```
when en/tabs/tab1 -> en/tabs/tab2
the life cycle fired 4 times.

### Expected Behavior

life cycle hook should fired only once

### Steps to Reproduce

Full minimal example here: https://stackblitz.com/github/t871631092/ionic-bug
open console and switch to tab3 , there is 4 time "onIonViewWillEnter".

### Code Reproduction URL

https://stackblitz.com/github/t871631092/ionic-bug

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\kqq-pc\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\kqq-pc\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\kqq-pc\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\kqq-pc\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\kqq-pc\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\kqq-pc\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\kqq-pc\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\kqq-pc\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.20.1 (C:\Users\kqq-pc\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.3.8

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : not installed
   @capacitor/core    : 4.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.2
   OS     : Windows 10

### Additional Information

I have saw https://github.com/ionic-team/ionic-framework/issues/26325,but i am not sure is it a same problem.

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce the reported behavior, but your app does not appear to be using IonTabs and nested outlets correctly. As noted in the Ionic Vue documentation, nested routes should only be used when you want to render content in multiple outlets at the same time: https://ionicframework.com/docs/vue/navigation#shared-urls-versus-nested-routes

In this case, your `langPage.vue` component renders a second router outlet, and you never render content in multiple outlets. As a result, `langPage.vue` should not be needed. Removing `langPage.vue` and having the `TabsPage` component be used in the top level tabs route resolves the issue.

```js
const routes: Array<RouteRecordRaw> = [
  {
    path: "/",
    redirect: "/aa/tabs/tab1",
  },
  {
    path: "/url/:abg",
    component: () => import("@/views/Tab4Page.vue"),
  },
  {
    path: "/aa/tabs",
    component: TabsPage,
    children: [
      {
        path: "",
        redirect: "/aa/tabs/tab1",
      },
      {
        path: "tab1",
        component: () => import("@/views/Tab1Page.vue"),
      },
      {
        path: "tab2",
        component: () => import("@/views/Tab2Page.vue"),
      },
      {
        path: "tab3",
        component: () => import("@/views/Tab3Page.vue"),
      },
    ],
  },
];
```

**Comment by t871631092** [comment]
Thanks for looking into it ! Don't know if i understand right.
It seem to be i can't use /:lang in front of tabs ?
```
// not work
const routes: Array<RouteRecordRaw> = [
  {
    path: "/",
    redirect: "/en/tabs/tab1",
  },
  {
    path: "/:lang/tabs",
    component: TabsPage,
    children: [
      {
        path: "",
        redirect: "/en/tabs/tab1",
      },
      {
        path: "tab1",
        component: () => import("@/views/Tab1Page.vue"),
      },
      {
        path: "tab2",
        component: () => import("@/views/Tab2Page.vue"),
      },
    ],
  },
];
```
if i want to use lang key in the path , i have to give up tabs.
```
const routes: Array<RouteRecordRaw> = [
  {
    path: "/",
    redirect: "/en/tab1",
  },
  {
    path: "/:lang/tab4",
    name: "tab4",
    component: () => import("@/views/Tab4Page.vue"),
  },
  {
    path: "/:lang/tab1",
    name: "tab1",
    component: () => import("@/views/Tab1Page.vue"),
  },
  {
    path: "/:lang/tab2",
    name: "tab2",
    component: () => import("@/views/Tab2Page.vue"),
  },
];
```

**Comment by liamdebeasi** [comment]
That is correct, we do not support parameterized routes with tabs. The reason is that a mobile app should have at most one instance of tabs. Multiple tabs (especially nested tabs instances) make for a confusing user experience. This is also true for mobile apps not built with Ionic, so we aligned with that pattern. By using `/:lang` there can potentially be multiple tabs instances.

If you would still like to use tabs, I recommend passing `lang` as a state in your application logic instead of encoding that state into the URL.

**Comment by t871631092** [comment]
Got it, thank you very much ！@liamdebeasi
