### ISSUE TITLE
feat: display customized notes for dates in component "<IonDatetime />", e.g. holiday

### ISSUE THREAD

**Issue by creatxrgithub** [ionic-team/ionic-framework#26361]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I wish that I can add some notes to the component "<IonDatetime />".

e.g. specify a holiday and display it in the calendar by a function

### Describe the Use Case

to display holiday or lunar date in calendar

### Describe Preferred Solution

by setting a function or a array or a key-value (date-notes) object in a attribute of "<IonDatetime />"

### Related Code

```
let notes = { "2022-11-25": "初二", "2022-11-26": "one's birthday"}
<IonDatetime notes={notes} />
```
![IMG_20221125_142305](https://user-images.githubusercontent.com/27437178/204044668-6ce6e50b-df04-43fd-b268-af5fe6ef6b33.jpg)

**Comment by sean-perkins** [comment]
Hello @creatxrgithub, thank you for this feature request!

The individual date cell is a pretty small space to render additional UI within. We have a feature to track rendering a dot indicator in each cell, that developers could use for indicating additional information (https://github.com/ionic-team/ionic-framework/issues/25832).

Does that feature request solve your core need or are you explicitly looking to render text within the date cells?

**Comment by creatxrgithub** [comment]
It's similar, but not really.
I wish to display some notes at the "dot" position.
His code:
```
<ion-datetime></ion-datetime>

<script>
  const datetime = document.querySelector('ion-datetime');
  datetime.displayDotForDate = (dateIsoString) => {
    const date = new Date(dateIsoString);
    // check for a specific date
    return true;
  }
</script>
```
could be:
```
<ion-datetime></ion-datetime>

<script>
  const datetime = document.querySelector('ion-datetime');
  datetime.displayDotForDate = (dateIsoString) => {
    const date = new Date(dateIsoString);
    // check for a specific date
    return dotNotes; //or empty string ""
  }
</script>
```
or like this:
```
<IonDatetime displayDotForDate={ (dateIsoString) => { return dotNotes || "" }}/>
```
thanks.



> Hello @creatxrgithub, thank you for this feature request!
> 
> The individual date cell is a pretty small space to render additional UI within. We have a feature to track rendering a dot indicator in each cell, that developers could use for indicating additional information (#25832).
> 
> Does that feature request solve your core need or are you explicitly looking to render text within the date cells?

**Comment by sean-perkins** [comment]
Thanks for the follow-up @creatxrgithub!

While I understand the desire to display more complex information (notes, etc.) in the same position as the dot, I do not think this would align with the native calendar interface (e.g. Apple iOS Events) and wouldn't work with variable height custom content (e.g. text vs. a dot).

Here is a mocked example of how introducing text would cause a shift to the rendered text:

![Screen Shot 2022-11-30 at 2 15 15 PM](https://user-images.githubusercontent.com/13732623/204888122-b2f4575a-985a-4c88-8d14-79ed304d171d.png)

This would also impact the selected/highlighted day appearance. In your example you have rounded borders, whereas in our design it is a full circle (tighter edges). 

My recommendation would be if we move forward with the dot indicator for datetime, you would follow a pattern similar to iOS where selecting a day with a dot would display additional information alongside the interface, such as the holiday or lunar date.

Alternatively, a different calendar component from another library may be a better fit for this use case. The benefit of Ionic is that it does not prevent you from pulling in 3rd party components for complex use cases that do not currently align with our component design. 

I am going to close this feature request for now and we can reevaluate after the dot indicator feature is supported in Ionic Framework. 

If you have any additional thoughts or questions, feel free to reply and I can answer.

**Comment by creatxrgithub** [comment]
> Here is a mocked example of how introducing text would cause a shift to the rendered text:

It's easy to resolve that: to display a text or empty string at the position for all the dates to shift all the rendered texts. 

> This would also impact the selected/highlighted day appearance. In your example you have rounded borders, whereas in our design it is a full circle (tighter edges).

Let the date and "dot" in a same circle. It could have a pre-defined align style. The difference is the number is not in the center.  

Other option is to have a extra line between dates lines, the "dot" display in it below the dates. The number is still in the center of circle. In the image of calendar,  it has enough space between lines.
