### ISSUE TITLE
feat(checkbox): update style for ios spec

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#26399]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The UI of IOS checkbox has been changed in version 16. Here are some samples of Email, Notes and Calendar app:

![IMG_4193](https://user-images.githubusercontent.com/26873275/205263816-9311f2cf-b05a-4103-b5e5-a591a1bcaa1b.jpg)
![IMG_4194](https://user-images.githubusercontent.com/26873275/205263824-77e5cb5c-2dc5-4173-a19e-b396938f519d.jpg)
![IMG_4195](https://user-images.githubusercontent.com/26873275/205263830-bdb9d492-84bb-4178-8a76-11a57cf9bc01.jpg)
![IMG_4196](https://user-images.githubusercontent.com/26873275/205263831-c5c1bcb2-db45-43fa-964e-66f9be5a531a.jpg)
![IMG_4197](https://user-images.githubusercontent.com/26873275/205263832-e3c32baa-c688-4073-8710-0513896b43ea.jpg)

Current Ionic checkbox:

![image](https://user-images.githubusercontent.com/26873275/205264982-0b528bfe-c9a1-4994-b12e-b48ba13a41a4.png)

### Describe the Use Case

To match latest IOS 16 checkbox styles

### Describe Preferred Solution

- smaller circle
- thicker border
- new checked icon
- new input property `borderColor`: `string` to also respect unchecked colored boxes (see calendar app). If `borderColor` is `undefined`, `borderColor` is grey (see email app)

### Additional Information

https://developer.apple.com/design/human-interface-guidelines/components/layout-and-organization/lists-and-tables

**Comment by liamdebeasi** [comment]
This was completed in https://github.com/ionic-team/ionic-framework/pull/28729 back in December, but the PR was not linked to this issue.
