### ISSUE TITLE
bug(back-button): wrong spacing and icon size / font-weight

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#26393]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

- the distance between icon and text is too small. 
- the icon size and font-weight is not correct compared to ios

### Expected Behavior

| Reminder App | Ionic |
|--------------|-------|
| <img src="https://user-images.githubusercontent.com/26873275/205030691-35adb790-aa89-4b9a-83b1-a34d29f9663c.jpg" width="350"> | <img src="https://user-images.githubusercontent.com/26873275/205030636-37f0732e-e449-4258-a9bf-520fc950866d.jpg" width="350"> |

### Steps to Reproduce

see stackblitz

### Code Reproduction URL

https://stackblitz.com/edit/angular-4mvdgd

### Ionic Info

see stackblitz

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26395, and a fix will be available in an upcoming release of Ionic Framework.
