### ISSUE TITLE
feat(datetime): allow styling wheel picker

### ISSUE THREAD

**Issue by mCassanoQuix** [ionic-team/ionic-framework#26402]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be useful to be able to style the internal wheel picker for ion-datetime, maybe by being able to forward a class list to the inner component.

### Describe the Use Case

I have a month picker for which I'm trying to style the month labels, as Intl.DateTime provides italian and other months with all lowercase labels and I need them to be capitalized to standardize the experience between languages. It was previously possible in Ionic <6, as the label list could be provided separately, so it is technically a fix for a regression.

**Comment by mCassanoQuix** [comment]
I just found this issue https://github.com/ionic-team/ionic-framework/issues/25945, my use case is slightly different, but since it would satisfy my need I leave up to you to close this issue as duplicate.

**Comment by liamdebeasi** [comment]
Thanks! I will merge the two threads, but we will be sure to consider both use cases if this feature gets implemented.
