### ISSUE TITLE
bug:  datetime, cannot entry 00 for time entry

### ISSUE THREAD

**Issue by iStoha** [ionic-team/ionic-framework#26409]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

When clicking on time picker trying to change time a number keypad opens on mobile phone but you can change the hour value to everything but 00 for some reason.  I can change minutes to 00 for some of the times. 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/119839331/205583670-b65b39db-54a0-4748-8ced-1861cfb78128.png">

https://user-images.githubusercontent.com/119839331/205586111-7b83a0cd-b7c8-42cf-9089-23bbf6dfbc0f.mp4

### Expected Behavior

00 shoud be an expected value for hour or minutes field when entering via a keypad just like any other numbers. 
for e.g 00:00 ( Not alllowed via keypad. )

### Steps to Reproduce

Steps to Reproduce

**Android** 

- Use ion-datetime and generate the apk using cordova. 
- Click on the hour column or minute column to open the numeric keyboard in phone.
- Enter 00 from keypad and the value is not accepted while other numbers can be entered.  

_You can observe the same behaviour on browsers using the keyboard._ 

[https://angular-yxrjrr.stackblitz.io](url)

### Code Reproduction URL

https://github.com/iStoha/time-picker

### Ionic Info

Ionic:

Ionic CLI : 5.4.13
Ionic Framework : @ionic/angular 13.2.2
@angular-devkit/build-angular : 13.2.2
@angular-devkit/schematics : 13.2.2
@angular/cli : 13.2.2
@ionic/angular-toolkit : 6.0.0

Cordova:

Cordova CLI : 11.0.0
Cordova Platforms : android 9.1.0
Cordova Plugins : cordova-plugin-ionic-keyboard , cordova-plugin-ionic-webview (and other plugins)

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this behavior. We use a regex to clean up the wheel picker values when trying to best match your keyboard entry to an item in the wheel. The regex does this by stripping out leading zeros. This allows you to type `'2'` and get `'02'` selected without having to type the leading zero. This regex had a flaw where it stripped all leading zeros from a string, including when the string was only zeros (i.e `'00'`). As a result, your entry of `'0'` never matched `'00'`.

I fixed this by having the regex allow at least one 0 when the string it was processing was all zeros. As a result, `'00'` becomes `'0'` and will now match your keyboard entry of `'0'`.

Here is a dev build if you would like to test the proposed fix:

```
6.3.10-dev.11670337426.126ffd2c
```

**Comment by iStoha** [comment]
@liamdebeasi    I am sorry if i sound i out of depth here. 
How would i go about testing this dev build  ` 6.3.10-dev.11670337426.126ffd2c`  ?

**Comment by liamdebeasi** [comment]
No worries, I should have provided more instructions. That dev build points to a pre-release version of Ionic on npm that contains the fix for this issue. You can run the following command to install it:

```
npm install @ionic/angular@6.3.10-dev.11670337426.126ffd2c
```

(This dev build also works for other packages such as `@ionic/react` too)

**Comment by iStoha** [comment]
Hi @liamdebeasi 
I just tested.  It is working now.  Thanks a lot!
