### ISSUE TITLE
bug: [Vue] "ionic capacitor run" & "ionic capacitor build" default to production mode

### ISSUE THREAD

**Issue by tetsuwanadam** [ionic-team/ionic-framework#26411]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Running the "ionic capacitor build" command or the "ionic capacitor run" command in Ionic Vue build in production mode by default.

### Expected Behavior

Both commands should build in development mode, unless the --prod flag is set.

### Steps to Reproduce

Run "ionic capacitor build" or "ionic capacitor run" in an Ionic Vue project.

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.3.8

Capacitor:

   Capacitor CLI      : 4.5.0
   @capacitor/android : 4.5.0
   @capacitor/core    : 4.5.0
   @capacitor/ios     : 4.5.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.1.0 (/usr/local/bin/node)
   npm    : 8.19.2
   OS     : macOS

**Comment by tetsuwanadam** [comment]
Thanks for clarifying, @sean-perkins.
The [documentation](https://ionicframework.com/docs/cli/commands/capacitor-run) states that --prod is the "flag to use the production configuration", which implies to me that production is not the default.
Could the documentation be made more clear or am I just reading it wrong?

**Comment by sean-perkins** [comment]
@tetsuwanadam that option does appear to be specific the the angular build: https://github.com/ionic-team/ionic-cli/blob/develop/packages/%40ionic/cli/src/lib/project/angular/build.ts#L81

The documentation could be updated to clarify this. If you would like to submit a suggested change, I believe that information originates from here: https://github.com/ionic-team/ionic-docs/blob/main/scripts/data/cli.json

**Comment by sean-perkins** [comment]
I have created: https://github.com/ionic-team/ionic-docs/issues/2674 to track the documentation changes. 

I am going to close this issue for now.

Thanks!
