### ISSUE TITLE
bug: bundle includes custom styles to support very old IE versions which cause UI issues

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#26464]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The latest ionic 6.x does not support old IE browser versions - see https://ionicframework.com/docs/reference/browser-support, however, the bundle created still includes styles to fix some UI issues for old IE  browser versions. For example, https://github.com/ionic-team/ionic-framework/blob/main/core/src/css/normalize.scss#L37

Please note that those styles are still included even though the **.browserslistrc** does not include the line to support for IE or Edge altogether. For example, here is my **.browserslistrc* file
```
Chrome >=60
# Firefox >=63
# Edge >=79
Safari >=13
iOS >=13
```

The problem is that those fixes breaks some UI in my application (specifically, makes the images displayed with the wrong aspect ratio)

### Expected Behavior

Not to include styles/fixes for unsupported/very old browsers

### Steps to Reproduce

1) create new ionic project from one of the started template projects
2) add an image to the main page
3) exclude support for IE/Edge browser from **.browserslistrc**
3) build and run the application
4) check that the image added has **max-width: 100%" style applied from **normalize.css**, which is the fix for IE 8/9/10 - see https://github.com/ionic-team/ionic-framework/blob/main/core/src/css/normalize.scss#L37

OR, you can clone this project https://github.com/ryaa/ionic-includes-old-ie-browser-styles, change to the project directory, run `npm install` and then `ionic serve` and check the styles applied to the image displayed on the main page (see the step 4 above).

### Code Reproduction URL

https://github.com/ryaa/ionic-includes-old-ie-browser-styles

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.3 (/Users/alexryltsov/.nvm/versions/node/v18.12.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.4.0
   @angular-devkit/build-angular : 15.0.3
   @angular-devkit/schematics    : 15.0.3
   @angular/cli                  : 15.0.3
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.12.0 (/Users/alexryltsov/.nvm/versions/node/v18.12.0/bin/node)
   npm    : 9.0.0
   OS     : macOS Monterey
```

### Additional Information
See the style from from **normalize.css** applied to the image
<img width="1661" alt="Screen Shot 2022-12-12 at 09 40 55" src="https://user-images.githubusercontent.com/3608222/206993197-397eea3e-9db8-450d-96a2-235ec155d2ed.png">
<img width="1664" alt="Screen Shot 2022-12-12 at 09 41 45" src="https://user-images.githubusercontent.com/3608222/206993229-8c6e460c-4923-422b-b351-15a1ba0d6fcc.png">

**Comment by liamdebeasi** [comment]
Thanks for the report. The `border: 0` is for older versions of IE, not the `max-width`. The `max-width` makes it so that `img` does not flow outside of `ion-content`.

I do see that `max-width` is applied to the image in your example, but I do not see any visible differences when removing `max-width`. Do you have a screenshot of the incorrect behavior?

**Comment by ryaa** [comment]
> I do see that max-width is applied to the image in your example, but I do not see any visible differences when removing max-width. Do you have a screenshot of the incorrect behavior?

In my case, this breaks the map ArcGIS layer displayed, it is not visible because its images have 0 width (this is due to the _max-width: 100%;_ applied to the image which is rendered a child element of the leaflet canvas with width/height equal to 0)
<img width="1652" alt="206993601-6fce583b-2141-4922-968d-d70191a08b78" src="https://user-images.githubusercontent.com/3608222/207083710-eea38b60-0851-4d23-a751-fdac6fd4463d.png">

When I apply max-width: none; to the images everything starts to work. This is unchecked below because i have not done more appropriate screenshot, but once _max-width: none;_ is applied, the image width is correct and it becomes visible.
<img width="1645" alt="Screen Shot 2022-12-12 at 08 56 22" src="https://user-images.githubusercontent.com/3608222/207084361-f0ffe8f8-56a3-4079-8af6-246dc8f5fcb5.png">

Please let me know if you need more details.

P.S. I understand that this might need to be fixed on my end, but, why do we need those old IE fixes still being added (even if **.browserslistrc** says not to add IE support)?

Thank you for the quick feedback.

**Comment by liamdebeasi** [comment]
Thanks for the reply. Are you able to ensure `.leaflet-marker-icon` has a higher selector specificity that way it overrides `max-width: 100%`?

> P.S. I understand that this might need to be fixed on my end, but, why do we need those old IE fixes still being added (even if .browserslistrc says not to add IE support)?

We do not need this anymore, so I am removing the IE-specific code in https://github.com/ionic-team/ionic-framework/pull/26465. It looks like this was added years ago and never reevaluated when we dropped IE support.

**Comment by ryaa** [comment]
> Thanks for the reply. Are you able to ensure `.leaflet-marker-icon` has a higher selector specificity that way it overrides `max-width: 100%`?

yes. adding the below to my app wide scss fixed my problem
```
.leaflet-marker-icon {
    max-width: none;
}
```

> We do not need this anymore, so I am removing the IE-specific code in https://github.com/ionic-team/ionic-framework/pull/26465. It looks like this was added years ago and never reevaluated when we dropped IE support.

Awesome. Thank you very much for the great support!!!

P.S. if you don't mind, i will remove the screenshots from my previous post for the security reasons. thank you again

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26465, and a fix will be available in an upcoming release of Ionic Framework.
