### ISSUE TITLE
bug: setFocus() doesn't work on page load and/or ngAfterViewInit

### ISSUE THREAD

**Issue by Gkleinereva** [ionic-team/ionic-framework#26474]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I have an `@ionic/angular` project where a call to `<my-ionic-input>.setFocus()` in the `ngAfterViewInit()` lifecycle hook behaves intermittently at best (with a timeout), and doesn't work at all at worst.

### Expected Behavior

A call to `<my-ionic-input>.setFocus()` in the `ngAfterViewInit()` lifecycle hook should focus the element as intended, since the lifecycle hook should guarantee that the view has been rendered at that point.

If this is a known or expected problem, then I believe it should be documented here: https://ionicframework.com/docs/api/input#setfocus

### Steps to Reproduce

1. Clone the repo below (note the reproduction is not on the main branch, but on 'ion-input-set-focus')
2. Install/serve and open the app
3. Check the console to verify that the ngAfterViewInit lifecycle hook is running and that the setFocus() method is defined
4. Peek at `src/app/explore-container/explore-container.component.ts`  to see the code and another test I tried

### Code Reproduction URL

https://github.com/Gkleinereva/ion-repros/tree/ion-input-set-focus

### Ionic Info

npx ionic info

Ionic:

   Ionic CLI                     : 5.4.16 (/home/ekleiner/.npm/_npx/864a9e3c2cd0cf50/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.4.0
   @angular-devkit/build-angular : 14.2.10
   @angular-devkit/schematics    : 13.3.10
   @angular/cli                  : 14.2.10
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI   : 4.4.0
   @capacitor/core : 4.4.0

Utility:

   cordova-res : not installed
   native-run  : 1.7.1

System:

   NodeJS : v16.16.0 (/home/ekleiner/.nvm/versions/node/v16.16.0/bin/node)
   npm    : 8.11.0
   OS     : Linux 5.10

### Additional Information

I'm running the project in WSL2 on Windows.

**Comment by liamdebeasi** [comment]
Thanks for the report. Does the issue persist if you focus the element in the `ionViewDidEnter` lifecycle method instead? The `setFocus` method relies on the browser's native focus implementation. As a result, we are subject to any restrictions that browsers place on programmatically focusing elements.

**Comment by Gkleinereva** [comment]
Hmm, it seems to generally work if it's called from `ionViewDidEnter()`.  I pushed a new branch on the reproduction repository demonstrating this that can be found here: https://github.com/Gkleinereva/ion-repros/tree/ion-input-set-focus-ionic-lifecycle.

It's strange to me that this works in Ionic's lifecycle method but not in Angular's (even though I've verified that the element is defined and has the `setFocus` method defined inside of Angular's `ngAfterViewInit()` call. 

That being said, I understand that there are additional constraints imposed by the browser that I'm not aware of.  Could we possibly mention in the docs that `setFocus()` doesn't work in `ngAfterViewInit()`?  I would be happy to submit a pull request with the change, but I'm having trouble finding the appropriate file in the documentation to update for the current Ionic version: https://github.com/ionic-team/ionic-docs/search?q=setFocus

**Comment by liamdebeasi** [comment]
Ionic's components are lazily loaded, so `ngAfterViewInit` having been called does not mean the inner contents of an Ionic component has been loaded (and therefore can be focused). For example, `ngAfterViewInit` will be called when `ion-input` is added to the DOM, but the native `<input />` inside of `ion-input` may be rendered in the following frame.

I realize this is not a very developer-friendly behavior. We plan to move away from this lazy load approach in the future, so this experience should improve when that happens. We are tracking work for this in https://github.com/ionic-team/ionic-framework/issues/25646.

**Comment by Gkleinereva** [comment]
Thanks for very much your input, @liamdebeasi  :)  The difference in behavior of `setFocus()` when called from `ngAfterViewInit` and `ionViewDidEnter` now makes sense to me.  

I take it that updating the appropriate JSDoc in this file (https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/input/input.tsx) would be an overly cumbersome process, considering that this issue will very likely be fixed in v7 anyway?  Again, I'd be happy to submit a PR if that would be useful.

Otherwise, feel free to close this issue or link it to the v7 release.  Thanks again for your help!!

**Comment by liamdebeasi** [comment]
We'd be happy to accept a PR. There are two ways you can change the docs:

1. If you want to only update the `setFocus` method description, you can update the comment here: https://github.com/ionic-team/ionic-framework/blob/b0fee77f9472c70cc50c5d07040d4a6b7fedf209/core/src/components/input/input.tsx#L305-L308. Be sure to run `npm run build`, then commit and push your changes.
2. If you want the flexibility to go a bit more in depth with your documentation. You could modify https://github.com/ionic-team/ionic-docs/blob/main/docs/api/input.md and create a separate section. Maybe a "Best Practices" section?

-----

I will merge this with https://github.com/ionic-team/ionic-framework/issues/25646, so you can follow that thread for updates on the issue. I do not know if this will be addressed in the 7.0.0 release, but it is something that is high on our priority list. Let me know if you have other questions. Thanks again for filing an issue!
