### ISSUE TITLE
feat: Add label to ion-accordion toggle icon

### ISSUE THREAD

**Issue by daxter44** [ionic-team/ionic-framework#26488]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi, 
I read the documentation but did not find a solution. 
So it would be nice to give developers posibility to set label near ion-accordion toggle icon. 
Now I can do that only by adding additional label and placed this label at the end of line. 
Aproach which I described is not good because I have to manually remove left margin from toggle icon and it not looks good.   

### Describe the Use Case

From the UX perspective, alone icon with chevron down don't say a lot to user. Also when the tabs button are  inconspicuous. 
"Show" label near the icon could help in keep best UX, but it should be configurable I think. 
<img width="431" alt="Zrzut ekranu 2022-12-14 o 22 07 49" src="https://user-images.githubusercontent.com/9075439/207714091-5b798637-26ba-469d-be59-b4b978fbffe3.png">

**Comment by DwieDima** [comment]
Hi @daxter44 
This is already possible, you need to use `slot="end"` for your text-element which is inside `ion-item` with `slot="header"`.

![image](https://user-images.githubusercontent.com/26873275/207810362-f6792581-f208-473a-b40a-64d471cbae3e.png)

https://stackblitz.com/edit/angular-cteeab?file=src/app/example.component.html

**Comment by amandaejohnston** [comment]
Thank you for the feature request. I talked about this with the team, and we agree this is a feature worth investigating. We do already have an issue for similar accordion improvements here: https://github.com/ionic-team/ionic-framework/issues/23548 Resolving that issue would likely resolve this one in the process, or at least the two would make sense to work on in tandem. So, I'm going to close this issue out in favor of that one and add a comment over there with more details.
