### ISSUE TITLE
bug: Android 13 Gesture/Action Bar covering app content (tabs)

### ISSUE THREAD

**Issue by philmmoore** [ionic-team/ionic-framework#26509]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I'm not sure if this is a known issue or it's specific to my current project. But since Android 13 the ActionBar is now visible and overlaid on top of the app view, the first screenshot is Android 13 (API 33) with the System -> Gestures -> System Navigation set to Gesture navigation and you'll see it is slightly covering the tabs. The second screenshot shows it set with 2/3 button navigation set and you can just about see the tabs peeking above the Action Bar.

![Screenshot_20221216_233015](https://user-images.githubusercontent.com/2862059/208207590-bfdf1458-d5ef-41fd-804c-86e78145aa78.png)

![Screenshot_20221216_233253](https://user-images.githubusercontent.com/2862059/208207546-0b788af5-e5e2-4f23-a562-bf31f8dbb6b3.png)

### Expected Behavior

I would expect the ActionBar in whichever setting to not sit fixed on top of the view but push the apps content into view so nothing is lost or hidden behind the Action Bar regardless of its setting.

### Steps to Reproduce

If this is not a known issue I will create a blank tabs project and run in Android 13.

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1 (/Users/philmmoore/.nvm/versions/node/v16.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.1.13

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : 4.4.0
   @capacitor/core    : 4.4.0
   @capacitor/ios     : 4.4.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v16.16.0 (/Users/philmmoore/.nvm/versions/node/v16.16.0/bin/node)
   npm    : 8.11.0
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you provide a GitHub repo I can use to verify this behavior? I am unable to reproduce this using an Ionic tabs starter application on a Pixel 4a with Android 13:

| actionbar | gesture |
| - | - |
| ![actionbar](https://user-images.githubusercontent.com/2721089/208453356-44b2f6ee-9c4b-4e6c-b0b4-cd65e15f892b.png) | ![gesture](https://user-images.githubusercontent.com/2721089/208453382-4c94e653-4ef9-4ebf-b6ac-23cf6df946d3.png) |

**Comment by philmmoore** [comment]
Thanks @liamdebeasi I spun up an empty project myself and can confirm this issue isn't present so must be something in my implementation/setup on this particular app so I'll close this off :)
