### ISSUE TITLE
App breaks if ion-menu is used as per docs, navigation breaks if not

### ISSUE THREAD

**Issue by jcosta33** [ionic-team/ionic-framework#26515]
**Ionic version:**
[x] **6.4.1**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**
If I setup the navigation as is shown in the docs (https://ionicframework.com/docs/api/menu), this error will occur when navigating between pages:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/8978270/208688884-3bde713c-9553-43c1-a68f-fcfb49d95048.png">
This happens because ionic needs a single wrapper for the whole page in order to do the animations. If I change this structure to  this: 
![image](https://user-images.githubusercontent.com/8978270/208689304-06f78b61-89f0-4997-8b16-b3e7c13c694d.png)
then the navigation randomly stops working after jumping back and forward for a while but no errors are outputted. 

**Expected behavior:**
The structure shown in the documentation should not lead to a fundamental flaw in the structure of the page.

**Steps to reproduce:**
Just try to use the navigation on a Vue Ionic app by following the documentation by the book. That should do it.

**Comment by liamdebeasi** [comment]
Thanks for the report. Do you have a code reproduction I can look at? The demos in https://ionicframework.com/docs/api/menu show how to use the component at the root of the application. If you are using the menu in a wrapped page that you route to, this component will need `IonPage` as noted in https://ionicframework.com/docs/vue/navigation#ionpage.

**Comment by liamdebeasi** [comment]
Thanks for the reply. I think this is similar to https://github.com/ionic-team/ionic-framework/issues/18974. The errors appear to be slightly different, but I believe the underlying issues are related. I'll merge these two threads together. Let me know if you have any additional questions.
