### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by SirZemar** [ionic-team/ionic-framework#26526]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

Very similar behaviour described in this issue, but using ion-radio instead o accordion: https://github.com/ionic-team/ionic-framework/issues/25307

I use ion-radio-group inside a group form within its own modal component. First time I open it everything works fine. The issue comes when I close the modal and reopen it. This time all the check icon disappear, even though the right fields are still selected.

### Expected Behavior

When the modal reopens the radio-group should re render.

### Steps to Reproduce

Using the example givenn here: https://github.com/ionic-team/ionic-framework/issues/25307. And by replacing the accordion-group by radio-group.

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/.nvm/versions/node/v16.14.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.2.7
   @angular-devkit/build-angular : 14.2.2
   @angular-devkit/schematics    : 14.2.2
   @angular/cli                  : 14.2.2
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v16.14.0 (/usr/local/.nvm/versions/node/v16.14.0/bin/node)
   npm     : 8.3.1
   OS      : macOS Monterey
   Xcode   : Xcode 14.1 Build version 14B47b

**Comment by sean-perkins** [comment]
Hello @SirZemar thank you for reporting this issue.

I took the reproduction you called out and modified it for `ion-radio-group`: https://github.com/sean-perkins/ionic-gh-26526

I'm able to open/close the modal multiple times with the checked state displaying correctly. 

Can you modify this reproduction or describe how to reproduce the issue?

Thanks!
