### ISSUE TITLE
feat: Support of One UI

### ISSUE THREAD

**Issue by xnousnow** [ionic-team/ionic-framework#26534]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Is there any plans to support One UI, used on Samsung devices.

### Describe the Use Case

For native look and feel for samsung users.

### Additional Information

As far as I know, there is no other web implementation of One UI. There was 'One UI web' official style pack, but I see 404 error even if I browse snapshot on wayback machine. You can check design guidelines and more in here: https://developer.samsung.com/one-ui

**Comment by sean-perkins** [comment]
Hello @xnousnow thanks for this feature request.

At this time we are not anticipating adding a new set of designed components specifically for Samsung's design system. 

We currently target the latest iOS and MD2, while actively tracking the interest behind MD3: https://github.com/ionic-team/ionic-framework/issues/24282. 

Ionic is continuing to make improvements to our components that effects the design flexibility and customization. Our recommendation would be that developers use these mechanics, once they are available, if they need to style an application to align with OneUI.

**Comment by xnousnow** [comment]
Thanks, I support ionic!
