### ISSUE TITLE
bug: Android does not toggle between dark & light mode while app is open (2)

### ISSUE THREAD

**Issue by tetsuwanadam** [ionic-team/ionic-framework#26535]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

- When opening an Ionic app in Android, the app theme accurately matches the system setting for dark or light mode.
- ...And when switching the mode for the first time the Ionic app changes accordingly.
- ...BUT from the 2nd time onward the Ionic app doesn't change between dark or light mode to match the system setting.
- Additionally, the color in the system tray never changes to match the system's dark or light mode setting after the app has been opened.

### Expected Behavior

When you change the Android dark or light mode setting, the Ionic app theme should change accordingly every time, and the system tray color should change as well.

### Steps to Reproduce

- Create a new Ionic app and run it on an Android device.
- Switch from dark to light mode or vice versa. (The first time, the app theme will change accordingly, however the system tray color won't.)
- Switch from light to dark mode or vice versa again. (Neither the app theme nor the system tray color will change.)

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.6 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.4.1

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.1.0 (/usr/local/bin/node)
   npm    : 8.19.2
   OS     : macOS

### Additional Information

This is a repost of [#25731](https://github.com/ionic-team/ionic-framework/issues/25731) as it is still an issue.

There's a [similar issue](https://github.com/ionic-team/capacitor/issues/6100) in the Capacitor repo, however it was said to not be a Capacitor issue and closed.

It's occurring on my Android 13 Pixel 4a, however I experienced the issue previously on Android 12 as well.
Webview version is the Dec 13 2022 update 108.0.5359.128.

**Comment by tetsuwanadam** [comment]
... And after updating to the latest version of Android 13 it's fixed. The system tray color still doesn't change when changing to dark/light mode while the app is open but at least the app itself does. Closing.

**Comment by Ibni-Amin** [comment]
> ... And after updating to the latest version of Android 13 it's fixed. The system tray color still doesn't change when changing to dark/light mode while the app is open but at least the app itself does. Closing.



> ... And after updating to the latest version of Android 13 it's fixed. The system tray color still doesn't change when changing to dark/light mode while the app is open but at least the app itself does. Closing.

I think it belongs to device theme but not for sure
