### ISSUE TITLE
bug: Aria attributes are not reflected to ion-item in Vue

### ISSUE THREAD

**Issue by pablo7798** [ionic-team/ionic-framework#26538]
@DeyBo thanks for testing and confirming that problem. It would definitely help if I had assigned to the correct key!

Here is an updated dev-build that assigns to `aria-label`, not `ariaLabel`. 

```shell
npm install @ionic/angular@6.2.10-dev.11664382391.15516e55 
```

_Originally posted by @sean-perkins in https://github.com/ionic-team/ionic-framework/issues/25885#issuecomment-1261161611_
      
Hi @sean-perkins,

Im using "@ionic/vue": "^6.4.1", and still having the problem with aria-label on ion-item elements. Does this fix included on the vue version?

Thank you.

**Comment by sean-perkins** [comment]
Hello @pablo7798 thanks for reporting this issue.

I've confirmed that there is an issue with our `@ionic/vue` component wrappers, where reflected aria attributes are not available properties to assign.

For example, this should be valid usage:
```html
<ion-item aria-label="Hello world">
 
</ion-item>
```

We will capture this as a bug and prioritize in the backlog.

**Comment by pablo7798** [comment]
> Hello @pablo7798 thanks for reporting this issue.
> 
> I've confirmed that there is an issue with our `@ionic/vue` component wrappers, where reflected aria attributes are not available properties to assign.
> 
> For example, this should be valid usage:
> 
> ```
> <ion-item aria-label="Hello world">
>  
> </ion-item>
> ```
> 
> We will capture this as a bug and prioritize in the backlog.

Thank you @sean-perkins.

I was trying to use it like you say but never worked :(

**Comment by sean-perkins** [comment]
Hello @pablo7798 can you test with this dev-build and let me know if you run into any issues?

```
npm install @ionic/vue@6.4.2-dev.11672266146.111c9c07 @ionic/vue-router@6.4.2-dev.11672266146.111c9c07
```

This is based on updates to the framework wrappers: https://github.com/ionic-team/stencil-ds-output-targets/pull/316

**Comment by pablo7798** [comment]
> Hello @pablo7798 can you test with this dev-build and let me know if you run into any issues?
> 
> ```
> npm install @ionic/vue@6.4.2-dev.11672266146.111c9c07 @ionic/vue-router@6.4.2-dev.11672266146.111c9c07
> ```
> 
> This is based on updates to the framework wrappers: [ionic-team/stencil-ds-output-targets#316](https://github.com/ionic-team/stencil-ds-output-targets/pull/316)

Hello @sean-perkins,

I have tested this build but the problem still there. I will try to explain it better: 

In my case, the ion-item is transformed to a button, and there is where i want to put the aria-label attibute.

First, a capture of the original code fragment:
![image](https://user-images.githubusercontent.com/20256594/209924809-b329ef59-47aa-4cff-983a-dae0eaa0625f.png)

And here, the generated code:
![image](https://user-images.githubusercontent.com/20256594/209924902-31666bdf-0dfb-436d-bdaa-a6f4a8524e3c.png)

I hope it's clearer, i am trying to make my site more accesible :)

**Comment by sean-perkins** [comment]
Thank you for testing that dev-build and providing extra context @pablo7798!

Here is an updated version to test with:
```
npm install @ionic/vue@6.4.2-dev.11672338764.1def15a7
```

This should reflect the `aria-label` for both simple `ion-item` usages and when the `ion-item` is rendered as a button/clickable target. I've tested locally for both scenarios. 

When installing the new version, I'd recommend deleting the `node_modules/.cache/` directory, if it exists locally.

**Comment by pablo7798** [comment]
Solved now! So thankful!

I have diferent problem with the ion-accordion, it generates a duplicated role attributes and dont provide aria-labels: 

The code fragment is the same than on my last post, and here is the problem (green color, yellow ones are correct)

![image](https://user-images.githubusercontent.com/20256594/210056685-a3d70adb-ac10-4488-98e1-9ebe56965baa.png)

This might be on another thread, tell me if you prefer to start another one.
