### ISSUE TITLE
bug: Use react 18 render IonModal, all event listening is invalid

### ISSUE THREAD

**Issue by xuehaoyu** [ionic-team/ionic-framework#26540]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

i use react 18 render IonModal, all event listening is invalid

### Expected Behavior

Hope to solve this problem

### Steps to Reproduce

use ionic6
I placed code in git

### Code Reproduction URL

https://github.com/xuehaoyu/ionic6-bug-demo

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.5 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.4.1

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v14.17.5 (/usr/local/bin/node)
   npm    : 6.14.14
   OS     : macOS

### Additional Information

```
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonModal, IonList, IonItem, IonLabel } from '@ionic/react';
import { useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import ExploreContainer from '../components/ExploreContainer';
import './Tab1.css';

const Dom: React.FC = (props: any) => {
  return <IonModal isOpen>
    <IonContent>
      <IonList>
        <IonItem onClick={() => {
          console.log('11111')
        }}>
          <IonLabel>Pokémon Yellow</IonLabel>
        </IonItem>
      </IonList>
    </IonContent>
  </IonModal>
}

const Tab1: React.FC = () => {
  useEffect(() => {
    const createDiv = document.createElement('div')
    const parentDom = document.body
    parentDom.appendChild(createDiv)
    const root = createRoot(createDiv);
    root.render(<Dom></Dom>)
  }, [])
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab 1</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Tab 1</IonTitle>
          </IonToolbar>
        </IonHeader>
        <ExploreContainer name="Tab 1 page" />
      </IonContent>
      {/* <Dom></Dom> */}
    </IonPage>
  );
};

export default Tab1;

```

**Comment by xuehaoyu** [comment]
You can see that the click event has no response, no console

**Comment by sean-perkins** [comment]
@xuehaoyu the event listeners are being detached due to this custom code in your implementation:

```tsx
useEffect(() => {
  const createDiv = document.createElement("div");
  const parentDom = document.body;
  parentDom.appendChild(createDiv);
  const root = createRoot(createDiv);
  root.render(<Dom></Dom>);
}, []);
```

To render a modal, either use the hook: `useIonModal` or render the component directly in the mark-up:

```tsx
<Dom></Dom>
```

Doing this correctly attaches event listeners.

**Comment by xuehaoyu** [comment]
useIonModal need component environment
I hope to render the modal at any time
It may be in a piece of logic code
```
In the old version, I always encapsulated a method to use, like this:

import { CommonModal } from 'components'
import { modalLayer } from 'layer'
 modalLayer(CommonModal, {
      title: ‘标题’,
    })
```
Is there any way I can solve this problem in the new version

**Comment by xuehaoyu** [comment]
I am upgrading the project. There is a lot of old code in the project，
Is there a quick solution to this problem

**Comment by xuehaoyu** [comment]
I temporarily solved the needs of the project with the method of the old version,
use createOverlayComponent
```
import { ModalOptions, modalController } from '@ionic/core';
import { createOverlayComponent } from 'common/react-component-lib';

export type ReactModalOptions = Omit<ModalOptions, 'component' | 'componentProps'> & {
  children: React.ReactNode;
};

export const IonModal = /*@__PURE__*/ createOverlayComponent<
  ReactModalOptions,
  HTMLIonModalElement
>('IonModal', modalController);
```
But I still hope that the new version can solve the problem of event separation,
Thank you.

**Comment by sean-perkins** [comment]
Hello @xuehaoyu thank you for the added context!

From Ionic 5 to Ionic 6, `IonModal` moved to an inline overlay component, no longer using `React.createPortal` for the implementation.

I'm looking into alternative usages that support creating a modal outside of the component context/environment, with the current Ionic 6 implementation.

**Comment by sean-perkins** [comment]
Hello @xuehaoyu thank you for your patience here. 

With Ionic v6, the ideal implementation would be to migrate to the `useIonModal` hook, which uses the `modalController` internally. This is the same base behavior that the `createOverlayComponent` uses in v5.

```tsx
import { useIonModal } from '@ionic/react';

...

const [present] = useIonModal(Dom);

useEffect(() => {
  present();
}, [present]);
```

Note: When using `useIonModal`, you do not need to specify the `IonModal` component in your presented overlay.

e.g.:

```tsx
const Dom: React.FC = (props: any) => {
  return (
    <IonContent>
      <IonList>
        <IonItem
          onClick={() => {
            console.log("11111");
          }}
        >
          <IonLabel>Pokémon Yellow</IonLabel>
        </IonItem>
      </IonList>
    </IonContent>
  );
};
```

This will maintain the event listeners when presenting the overlay. 

Thanks!
