### ISSUE TITLE
 @capacitor/preferences cleared after a few hours of running the application in the background

### ISSUE THREAD

**Issue by proyoli** [ionic-team/ionic-framework#26545]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [x] v4.x
- [ ] v5.x
- [ ] v6.x
- [ ] Nightly

### Current Behavior

@ionic/angular: 6.x
@capacitor/ios : 4.x
Platform: ios 
***It's only for iOS devices, it's not reproducible on Android

iOS clear my app storage when it is in the background for an extended period (3-4 hours) resulting in the loss of all storage data and kicking me back to the login.

For storing data, we use @capacitor/preferences

In my mind, it would remain suspended indefinitely
it looks like all storage data cleared after 3-4 hours

Would you be able to fix it or provide a workaround?  

Regards

### Expected Behavior

Data stored in storage(@capacitor/preferences) should not be cleared 

### Steps to Reproduce

1. Start the application 
2. Leave it in the background for at least 3-4 hours
3. The storage is empty after taking the application to the foreground

### Ionic Info

-

**Comment by sean-perkins** [comment]
@proyoli this repository is for the UI components of Ionic Framework. 

For Capacitor plugin issues, please open an issue here: https://github.com/ionic-team/capacitor-plugins

Thanks!
