### ISSUE TITLE
bug: ion-back-button does not show up when setting a common header in app.component.ts, outside of ion-router-outlet.

### ISSUE THREAD

**Issue by glemiere** [ionic-team/ionic-framework#26549]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The following code:

```
  <div class="ion-page" id="main-content">
    <ion-header [translucent]="true">
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button></ion-back-button>
        </ion-buttons>
        <ion-title>
          {{pageTitle}}
        </ion-title>
        <ion-chip slot="end" (click)="toggleMenu()">
          <ion-avatar>
            <img alt="Silhouette of a person's head" src="https://ionicframework.com/docs/demos/api/avatar/avatar.svg" />
          </ion-avatar>
          <ion-label>{{user ? user.email : "My Account"}}</ion-label>
        </ion-chip>
      </ion-toolbar>
    </ion-header>
    <ion-content [scrollEvents]="true">
      <ion-router-outlet></ion-router-outlet>
    </ion-content>
  </div>
```

Does not behave as expected. It seems like it never see that the navigation stack is increasing, and this results in the back button never showing up. It seems like the only way for the ion-back-button component to show up is to copy/paste the same code in different pages which is really not ideal.

### Expected Behavior

the ion-back-button component should be able to read the navigation stack and show up regardless of where it lives in the DOM.

### Steps to Reproduce

Generate a new project and set a back button in the app.component.html.

### Code Reproduction URL
https://github.com/glemiere/ionic-backbutton-bug-repro

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.4 (/home/glm/.nvm/versions/node/v19.2.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.4.1
   @angular-devkit/build-angular : 15.0.4
   @angular-devkit/schematics    : 15.0.4
   @angular/cli                  : 15.0.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v19.2.0 (/home/glm/.nvm/versions/node/v19.2.0/bin/node)
   npm    : 9.2.0
   OS     : Linux 5.19

**Comment by lostdev** [comment]
Same issue happening here. I worked around it by adding some CSS for now. The .can-go-back class was added at a higher level and was not the parent of the ion-header?

```
.can-go-back ion-header ion-back-button {
  display: block;
}
```

**Comment by glemiere** [comment]
@sean-perkins here is the repro link: https://github.com/glemiere/ionic-backbutton-bug-repro

**Comment by glemiere** [comment]
@lostdev on my end it's more than a styling issue, the navigation history stack simply isn't filling up. You can check out the reproduction above, your case might be different.

**Comment by lostdev** [comment]
You're right. I just revisited my code and turns out I am handling the `click` event and manually calling the `NavController`'s `back` method.

It took me close to a day to get the ion-back-button working as nothing I did would work.

**Comment by glemiere** [comment]
@lostdev if you don't mind me asking, how do you know when to show the button and when not to? Do you have a way of seeing if the stack is empty? I searched but I didn't find anything, though it seemed possible on a former version of Ionic but is now handled by Angular who is very poorly documented in my opinion 😬

**Comment by lostdev** [comment]
@glemiere I have a hacked solution in place - I have a single homepage that leads to all other pages, so the button is visible on all pages except the home page. Sorry I couldn't help more!

**Comment by sean-perkins** [comment]
Hello @glemiere thanks for the reproduction!

The `ion-back-button` will only appear if there is another view in the current stack to navigate back to. This stack is managed by an `ion-router-outlet`. If you place the `ion-back-button` outside of the `ion-router-outlet`, it will not appear because there is no page to go back to. To fix this, the `ion-back-button` should be placed within the `ion-router-outlet`. It's important to note that the `ion-back-button` is different from the browser's back button. The `ion-back-button` navigates within a single stack, whereas the browser back button does not.

Unfortunately your expected behavior is not how the back button is intended to work. Our recommendation is to render the header and back button inside of your outlet.

**Comment by glemiere** [comment]
@lostdev no worries, was just curious. On my end I'm tracking the history stack manually and set the root (or roots if the app is tabs based). That's how I know how to show the button or not.

Here is the NavigationService part that handles that, I'll post it if it can help someone else.

```
import { Injectable } from '@angular/core';
import { Router, NavigationEnd } from "@angular/router";
import { Location } from '@angular/common';

@Injectable({
  providedIn: 'root'
})
export class NavigationService {
  public pageTitle: string;
  public navigationStack: Array<string>;
  public roots: Array<string>;

  constructor(
    public router: Router,
    public location: Location,
  ) {
    this._trackPageTitle();
    this._recordNavigationStack();
  }

  public setRoots(roots: Array<string>) {
    this.roots = roots;
  }

  public goBack(): void {
    this.navigationStack.pop();

    if (this.canGoBack())
      this.location.back();
  }

  public canGoBack(): boolean {
    if (this.navigationStack.length > 0 && !this.roots.includes(this.pageTitle))
      return true;
    return false;
  }

  private _trackPageTitle(): void {
    this.router.events.subscribe(event => {
      this.pageTitle = this.location.path().replace(/\/.*?\//g, "").replace(/[-\/]/g, ' ');
    });
  }

  private _recordNavigationStack(): void {
    this.navigationStack = new Array();

    this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd)
        this.navigationStack.push(event.urlAfterRedirects);
    });
  }
}
```

And then just a little templating:

```
    <ion-header [translucent]="true">
      <ion-toolbar>
        <ion-buttons *ngIf="navigation.canGoBack()" slot="start">
          <ion-back-button (click)="navigation.goBack()"></ion-back-button>
        </ion-buttons>
        <ion-title>
          {{navigation.pageTitle}}
        </ion-title>
        <ion-chip slot="end" (click)="toggleMenu()">
          <ion-avatar>
            <img alt="Silhouette of a person's head" src="https://ionicframework.com/docs/demos/api/avatar/avatar.svg" />
          </ion-avatar>
          <ion-label>{{user ? user.email : "My Account"}}</ion-label>
        </ion-chip>
      </ion-toolbar>
    </ion-header>
```

**Comment by glemiere** [comment]
@sean-perkins how do you have a common header for the whole app as part of your layout in this case?

**Comment by sean-perkins** [comment]
@glemiere there are two practices that may work:

1. Create a new navigation stack with the template component containing the common header and an outlet for the dynamic content. Demo: https://github.com/sean-perkins/ionic-gh-26549
2. Create a shared UI component for the header, apply it to each page individually. 

Each approach has different advantages/disadvantages. Having the header abstracted from the page requires more logical services to sync page titles, actions, etc. Whereas the shared UI component allows direct access to the component in each implementation, to customize for one-off scenarios or features.

**Comment by glemiere** [comment]
Right, I basically did the first option then. Alrighty, sounds good. I think this conversation will probably help others in the future.

Thanks!
