### ISSUE TITLE
bug: IonBackButton does not show in SvelteKit project

### ISSUE THREAD

**Issue by Tommertom** [ionic-team/ionic-framework#26550]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

An ion-back-button will not show in a SvelteKit project - if it does not have an explicit `default-href` or `initialize` does not have explicit default path.

Example:
```
<script lang="ts">
	import { close } from 'ionicons/icons';
</script>

<ion-header>
	<ion-toolbar>
		<ion-back-button text="Volver" icon={close} on:click={console.log} />
	</ion-toolbar>
</ion-header>
```
Will not show the back-button.

This will work:

`  <ion-back-button default-href="/"></ion-back-button>`

But is boilerplate also given earlier issue - https://github.com/ionic-team/ionic/issues/19305

So when I add `{ backButtonDefaultHref: '' }` to `initialize()` taken from `@ionic/core`, it does show. A bit more experimentation down the road shows that it should not be necessary to default this in `initialize()` - as `window.Ionic` is almost the same as the one available in an Ionic Angular project (except for 1 entry related to zone). And Ionic Angular projects do show Ionic Backbutton. So I wonder where `default-href` is defaulted in core, so `showBackButton` becomes true in `back-button.tsx` of core?

I have a project that implements a ion-nav, the button also does not show, without `default-href="/"`:
ion-nav page - https://github.com/Tommertom/svelte-ionic-app/blob/main/src/routes/components/Nav/%2Bpage.svelte
nav-home - https://github.com/Tommertom/svelte-ionic-app/blob/main/src/lib/components/NavHome.svelte
nav-deteail - https://github.com/Tommertom/svelte-ionic-app/blob/main/src/lib/components/NavDetail.svelte

NavDetail holds the back-button
NavHome holds a list of items that lead to a push to ion-nav
ion-nav page has the logic to instantiate the ion-nav in the svelte context.

Working demo - https://ionicsvelte.firebaseapp.com/components/Nav

### Expected Behavior

ion-back-button to show without being given an explicit defaul href

### Steps to Reproduce

See earlier description

### Code Reproduction URL

https://github.com/Tommertom/svelte-ionic-app/blob/main/src/routes/components/Nav/%2Bpage.svelte

### Ionic Info

package.json:

```
{
	"name": "IonicSvelteKit",
	"version": "0.0.1",
	"private": true,
	"homepage": "https://ionicsvelte.firebaseapp.com",
	"repository": {
		"type": "git",
		"url": "https://github.com/Tommertom/svelte-ionic-npm.git"
	},
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write .",
		"doctoc": "doctoc README.md"
	},
	"devDependencies": {
		"@sveltejs/adapter-static": "^1.0.0-next.44",
		"@sveltejs/kit": "next",
		"@typescript-eslint/eslint-plugin": "^5.27.0",
		"@typescript-eslint/parser": "^5.27.0",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.44.0",
		"svelte-check": "^2.7.1",
		"svelte-preprocess": "^4.10.6",
		"tslib": "^2.3.1",
		"typescript": "^4.7.4",
		"vite": "^3.1.0",
		"vite-plugin-pwa": "^0.13.1"
	},
	"type": "module",
	"dependencies": {
		"@ionic/core": "^6.3.0",
		"ionic-svelte": "^0.5.13",
		"localforage": "^1.10.0"
	}
}


```

### Additional Information

Can this be related to https://github.com/ionic-team/ionic-framework/issues/26466 given lifecycle hooks of Stencil?

**Comment by DwieDima** [comment]
Hi @Tommertom 

`ion-back-button` is only visible, if your page component element has the class `can-go-back`.
This class will be appended on page transition, where i noticed i missing on your page.

see [here](https://github.com/ionic-team/ionic-framework/blob/f0f6b39dfd18a42427132ca8042ec0321e4e5bf6/core/src/utils/transition/index.ts#L43)

the `can-go-back` [class](https://github.com/ionic-team/ionic-framework/blob/f0f6b39dfd18a42427132ca8042ec0321e4e5bf6/core/src/css/core.scss#L202) just set the ion-back-button to `display: block`

So i think this [method](https://github.com/ionic-team/ionic-framework/blob/f0f6b39dfd18a42427132ca8042ec0321e4e5bf6/core/src/components/nav/nav.tsx#L615) does not correctly execute on your side, where the [variable](https://github.com/ionic-team/ionic-framework/blob/f0f6b39dfd18a42427132ca8042ec0321e4e5bf6/core/src/components/nav/nav.tsx#L635) `requiresTransition` is somehow `false` or `undefined`.

**Comment by Tommertom** [comment]
Thx @DwieDima for your reply (not sure why I can't see it here). Great pointers to continue figuring out what is happening, especially why the ion-nav animations are not triggering.

And it might even relate to another struggle I am having: getting the ios/md transition hooked to the SvelteKit router (leaving/entering elements). 

Hope it is ok to keep this issue open while I try to figure out? Possibly not a bug with Ionic.

**Comment by liamdebeasi** [comment]
Thanks for the report. The `ion-back-button` component will not be visible unless there is a view to go back to: https://github.com/ionic-team/ionic-framework/blob/f0f6b39dfd18a42427132ca8042ec0321e4e5bf6/core/src/css/core.scss#L202-L204

When using routing, it is the responsibility of the router to assign this `.can-go-back` class to the component that contains the `ion-back-button`. Assigning a `defaultHref` forcibly shows the back button as you noted.

**Comment by Tommertom** [comment]
Ok thx @liamdebeasi for the clarification

More advanced integration with the kit router is the next big challenge on my list

So there this behaviour needs to be implemented.

I might drop some questions on how to - for instance I see that IOS and Android transitions are exported via the core surface, but the transition method isnt.

Which I may want to try to use 

Which brings me to the question how to generate a dev build of ionic-core (a q on discord). Just a npm run build only gives dist folder - not full package

**Comment by liamdebeasi** [comment]
You can use `npm link` to create a symlink of the development build of Ionic in your project. We also use a sync script when automating tests that you could adapt: https://github.com/ionic-team/ionic-framework/blob/main/angular/test/base/scripts/sync.sh

**Comment by Tommertom** [comment]
Ok thx

Will close this issue - not a bug here
