### ISSUE TITLE
bug: ion-datetime-button select year and Months of the year

### ISSUE THREAD

**Issue by francolondra** [ionic-team/ionic-framework#26552]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Not exist button for select a year and Months of the year.I upload a file.If yoy can see , I don't have any button for select.This datetime is a modal.
<img width="304" alt="Captura de pantalla 2022-12-28 a la(s) 20 12 38" src="https://user-images.githubusercontent.com/40376158/210192002-6379e5b9-12b0-4a79-8228-227b97f32918.png">

### Expected Behavior

it should have a button and return to the calendar with the year and month selected for that you can choose a day.

### Steps to Reproduce

1 - open the modal
2 - select the date 
3 - select the year and the month and for return you should press again in the year that it came back.

### Ionic Info

File Html 
<ion-item id="modal-datetime">
  <ion-label position="stacked">Fecha de Nacimiento</ion-label>
  <ion-input #input></ion-input>
  <ion-modal trigger="modal-datetime">
    <ng-template>
      <ion-content>
        <ion-datetime
        #datetime
        presentation="date"
        min="1900-01-01"
        max="2050-01-01"
        (ionChange)="dateChanged(datetime.value)"
        display-format="DD-MM-YYYY"
      >
      <div slot="title">Fecha de Nacimiento</div>
      <ion-buttons slot="buttons">
        <ion-button (click)="close()">Cancelar</ion-button>
        <ion-button (click)="select()">Selecccionar</ion-button>
      </ion-buttons>
    </ion-datetime>                
    </ion-content>
    </ng-template>
  </ion-modal>
</ion-item>

File TS 

import {
  Component, Input, OnInit, Self, ViewChild,
} from '@angular/core';
import {
  ControlValueAccessor, NgControl, ValidatorFn, Validators,
} from '@angular/forms';
import { IonDatetime, IonInput } from '@ionic/angular';
import { CustomValidatorService } from '@shared/helpers/validator/customValidator.service';
import { format, parseISO } from 'date-fns';

@Component({
  selector: 'app-datetime-custom',
  templateUrl: './datetime-custom.component.html',
  styleUrls: ['./datetime-custom.component.scss'],
})
export class DatetimeCustomComponent implements ControlValueAccessor, OnInit {
  @ViewChild(IonInput, { static: true }) input: IonInput;

  @ViewChild(IonDatetime) datetime: IonDatetime;

  @Input() isRequired = false;

  disabled;

  constructor(@Self() public controlDir: NgControl) {
    this.controlDir.valueAccessor = this;
  }

  ngOnInit(): void {
    const { control } = this.controlDir;
    const validators: ValidatorFn[] = [];
    validators.push(CustomValidatorService.dateOfBirth());
    if (this.isRequired) {
      validators.push(Validators.required);
    }

    control.setValidators(validators);
    control.updateValueAndValidity();
  }

  writeValue(obj: any): void {
    if (obj) {
      this.input.value = obj;
    }
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }

  onChange() {
  }

  onTouched() {
  }

  dateChanged(value) {
    if (value !== undefined) {
      const formatterDate = format(parseISO(value), 'dd-MM-yyyy');
      this.controlDir.control.setValue(formatterDate);
      this.controlDir.control.markAsTouched();
      this.writeValue(formatterDate);
    }
  }

  close() {
    this.datetime.cancel(true);
  }

  select() {
    this.datetime.confirm(true);
  }
}

File Css
ion-datetime {
    background: var(--ion-color-primary-contrast);
    border-radius: 8px;
  }
  
  ion-modal {
    --background: rgba(44, 39, 45, 0.2);
  
    &::part(content) {
      backdrop-filter: blur(6px);
    }
  
    ion-content {
      --background: transparent;
  
      --padding-top: 25vh;
      --pading-start: 20px;
      --padding-end: 20px;
  
      --padding-left: 20vh;
      --padding-start: 20px;
      --padding-end: 20px;
    }
  }

  ion-item {
    --padding-start:0
  }

**Comment by sean-perkins** [comment]
Hello @francolondra thanks for opening this issue!

This is currently expected behavior. In iOS, when opening up the "New Event" UI in the Calendar, selecting the header shows a picker similar to Ionic's. You will observe there is no "Cancel" or "Done" action in their UI.

<img src="https://user-images.githubusercontent.com/13732623/210444641-ad1a681e-350f-4700-b81a-71ea4ede2093.PNG" width="350px" />

In Ionic 6.1.4 we hid the parent datetime's "Cancel"/"Done" actions, as to not confuse users to select the "Done" action when the month/year picker was expanded and accidentally dismissing the datetime in an overlay: https://github.com/ionic-team/ionic-framework/pull/25205

Is there a native application or a human interface guideline you can reference that has a "Done" action in the month/year picker?
