### ISSUE TITLE
bug: json5  <2.2.2 Severity: high tsconfig-paths  3.5.0 - 3.9.0 || 3.11.0 - 3.14.1

### ISSUE THREAD

**Issue by thameurr** [ionic-team/ionic-framework#26555]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

`# npm audit report

json5  <2.2.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix`
node_modules/tsconfig-paths/node_modules/json5
  tsconfig-paths  3.5.0 - 3.9.0 || 3.11.0 - 3.14.1
  Depends on vulnerable versions of json5
  node_modules/tsconfig-paths

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix`

### Expected Behavior

Getting this error one i create ionic project, or when I try to install a new package, and `npm audit fix` doesn't make any change. 

### Steps to Reproduce

Getting this error one i create ionic project, or when I try to install a new package, and `npm audit fix` doesn't make any change. 

### Ionic Info

Ionic info :

   Ionic CLI                     : 6.20.6 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.4.1
   @angular-devkit/build-angular : 15.0.4
   @angular-devkit/schematics    : 15.0.4
   @angular/cli                  : 15.0.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.13.0 (/usr/local/bin/node)
   npm    : 8.19.2
   OS     : macOS

**Comment by sean-perkins** [comment]
@thameurr are you creating new projects with `ionic start`? If so, can you share which template you are selecting?

With the blank template, I am not receiving any vulnerabilities:
> found 0 vulnerabilities

**Comment by thameurr** [comment]
@sean-perkins  Please note that this error showing once creating a new project Blank, or when trying to install a new package using npm ...

**Comment by sean-perkins** [comment]
@thameurr can you provide a Github reproduction of the issue?

Here is my debug steps:

```
ionic start
? Starter template: blank
✔ Preparing directory ./ionic-gh-26555 in 1.17ms
✔ Downloading and extracting blank starter in 617.11ms
> npm i

up to date, audited 1145 packages in 2s

156 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

cd ionic-gh-26555/

npm audit fix

up to date, audited 1145 packages in 2s

156 packages are looking for funding
  run `npm fund` for details

```

I omitted some of the extra sections.

Does the new package you are trying to install have this vulnerability instead of Ionic?
