### ISSUE TITLE
bug: node16 moduleresolution fails with v6.2.4

### ISSUE THREAD

**Issue by hlehmann** [ionic-team/ionic-framework#26554]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

New versions of ionic broke types when using moduleResolution: "node16". Components like IonCard or IonButton doesnot have typings anymore.

Works with 6.2.3

### Expected Behavior

Allow moduleResolution node16 and have component typings

### Steps to Reproduce

Add moduleResolution: "node16" in tsconfig.json.

### Ionic Info

Ionic:

   Ionic CLI       : 6.18.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.2.3

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v19.3.0 (/opt/homebrew/Cellar/node/19.3.0/bin/node)
   npm    : 9.2.0
   OS     : macOS

**Comment by sean-perkins** [comment]
Hello @hlehmann thanks for reporting this issue!

In Ionic 6.2.4 we upgraded our Stencil dependency to `^2.17.4` from `^2.16.0`: https://github.com/ionic-team/ionic-framework/commit/4f24b0e9e366eda9194fb474c1a0922e2f89feb6.

I'll need to consult with the Stencil team to see what changed between these versions that may have resulted in this.

In the interim, can you share your use case for needing to be using `node16` over `node`?

**Comment by hlehmann** [comment]
I don't think this is caused by stencil as it work with 2.20.0 which match ^2.17.4 and ^2.16.0.

In 6.2.3 you have
```tsx
/* node_modules/@ionic/react/dist/types/components/routing-proxies.d.ts */
import type { JSX } from '@ionic/core/components';

/* node_modules/@ionic/core/components/index.d.ts */
import type { Components, JSX } from "../dist/types/interface";
export type { Components, JSX };
```

Since 6.2.4 you have 
```tsx
/* node_modules/@ionic/react/dist/types/components/routing-proxies.d.ts */
import type { JSX } from '@ionic/core/components';

/* node_modules/@ionic/core/components/index.d.ts */
// no more JSX exports
```

In both versions you have 
```tsx
/* node_modules/@ionic/core/components/custom-elements.d.ts */
export * from '../dist/types/interface'; // with JSX export 

/* node_modules/@ionic/core/components/package.json */
{
  "name": "@ionic/core/components",
  "version": "0.0.0",
  "description": "Ionic Components exported as custom elements, extending HTMLElement.",
  "main": "./index.js",
  "types": "./custom-elements.d.ts",
  "private": true,
  "sideEffects": false
}
```

The issue is caused by `node_modules/@ionic/core/components/package.json`:
- with `moduleResolution: "node"`, typescript will consider `node_modules/@ionic/core/components/package.json` and resolve `@ionic/core/components` to `node_modules/@ionic/core/components/custom-elements.d.ts`
- with `moduleResolution: "node16"`, typescript will not consider `node_modules/@ionic/core/components/package.json` because `node_modules/@ionic/core/package.json` exists and resolve `@ionic/core/components` to `node_modules/@ionic/core/components/index.d.ts` which have no more JSX exports since 6.2.4

**Comment by hlehmann** [comment]
A solution could be to use "exports" in node_modules/@ionic/core/package.json

see: 
https://webpack.js.org/guides/package-exports/
https://nodejs.org/api/packages.html#subpath-exports

**Comment by liamdebeasi** [comment]
I spoke with the Stencil team and can confirm that this is something that will need to be resolved on the Stencil end. I will post a reply here when I have an update.
