### ISSUE TITLE
bug: Refresher overwrites virtual scroll overflow styling

### ISSUE THREAD

**Issue by piotr-cz** [ionic-team/ionic-framework#26553]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The `ion-refresher` prevents contents of Virtual Scroll to be scrolled.

### Expected Behavior

The `ion-refresher` doesn't prevent contents of Virtual Scroll to be scrolled.

### Steps to Reproduce

1. Install `@ionic/react` and `@ionic/core` in version 6.2.2 (correct behaviour)
   ```console
   npm install --save-exact @ionic/react@6.2.2 @ionic/core@6.2.2
   ```
1. Create list with Virtual Scroll as in Ionic Docs > [Virtual Scroll](https://ionicframework.com/docs/react/virtual-scroll)
1. Add Refresher component above the list as in Ionic Docs > Refresher > ion-refresher > [Usage with Virtual Scroll](https://ionicframework.com/docs/api/refresher#usage-with-virtual-scroll)
1. Make sure it's possible to scroll contents and pull to refresh
3. Install `@ionic/react` and `@ionic/core` in version 6.2.4 or higher (bug introduced)
   ```console
   npm install --save-exact @ionic/react^@6.4.1 @ionic/core@^6.4.1
   ```
2. See that it's not possible to scroll contents

### Code Reproduction URL

https://stackblitz.com/edit/angular-4uocfn (Forked from docs > ion-refresher > [Advanced Usage](https://ionicframework.com/docs/api/refresher#advanced-usage))

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.6 (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 6.4.1

Capacitor:

   Capacitor CLI      : 3.7.0
   @capacitor/android : 3.7.0
   @capacitor/core    : 3.7.0
   @capacitor/ios     : 3.7.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.18.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.2
   OS     : Windows 10

### Additional Information

Bug introduced in @ionic/core [6.2.3](https://github.com/ionic-team/ionic-framework/releases/tag/v6.2.3) (#25750) or [6.2.4](https://github.com/ionic-team/ionic-framework/releases/tag/v6.2.4) (#25783)

**Comment by piotr-cz** [comment]
Workaround:
Do not add `ion-content-scroll-host` class to `<Virtuoso>` component, even that it's stated that it's required in Ionic Docs > Virtual Scroll > [Usage with Ionic Components](https://ionicframework.com/docs/react/virtual-scroll#usage-with-ionic-components), use state to watch scroll position:

```tsx
const StationsPage: React.FC = () =  {

  const [ isListAtTop, setIsListAtTop ] = useState<boolean>(true)

  return (
    <IonPage scrollY={false}>
      <IonRefresher
        slot="fixed"
        onIonRefresh={refresh}
        disabled={!isListAtTop}
      >
        <IonRefresherContent />
      </IonRefresher>

      <Virtuoso
        atTopStateChange={setIsListAtTop}
      />
    </IonPage>
  )
}
```

**Comment by sean-perkins** [comment]
Hello @piotr-cz thanks for reporting this issue. 

Adding the `ion-content-scroll-host` class to the scroll element is required for `ion-refresher`, to calculate the scroll position for the gesture. 

In your reproduction you will additionally need these styles:
```css
.ion-content-scroll-host {
  overflow-y: auto;
}
```

You can also add them directly as an inline style, as you are for the `height` of the element. 

For some reason when not supplying our class, the `Virtuoso` element has `overflow-y: auto`, but when specifying the class the style is removed. We do not ship custom styles for this class, so it is possible that the React library behind `Virutoso` has additional logic that conditionally applies those styles. 

Can you try this and let me know if it resolves your issue?

**Comment by piotr-cz** [comment]
@sean-perkins
Thanks, adding this style fixes the issue.

I think it should be added to docs in both places.

**Comment by piotr-cz** [comment]
I've tried to look up Virtuoso source to find what's causing this. May be that something is resetting default `overflowY: auto` in `style` object here:

https://github.com/petyosi/react-virtuoso/blob/aa4df5ae1657303fa599706c0c507607e463b638/src/Virtuoso.tsx#L274

**Comment by sean-perkins** [comment]
Thanks for looking into this further @piotr-cz! 

I have a suspicion that using `componentOnReady` is causing this line: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/refresher/refresher.tsx#L732 to execute after Virtuoso sets overflow styling rules. 

Likely we need to do something similar to:
```ts
if (overflowVisible) {
  scrollStyle.overflow = 'hidden';
}
```

and not clear out any existing style rules. 

I'll log this as a bug so the team can prioritize in our backlog.

**Comment by piotr-cz** [comment]
@sean-perkins
Now it makes sense. The `scrollStyle` should not overwrite `overflow` style to it's initial value (`''`).
Before 6.2.4 this was happening immediately and Virtuoso set it's styles afterwards.

Since #25783 it's happening on `componentOnReady` event and overwrites Virtuoso styles (`overflow-y: auto` -> `overflow-y: initial`).

I think your suggested change from https://github.com/ionic-team/ionic-framework/issues/26553#issuecomment-1372518363 would fix the issue.

**Comment by sean-perkins** [comment]
Hello @piotr-cz can you test with this dev-build and let me know if you run into any issues?

```
npm install @ionic/react@6.4.3-dev.11673974834.12ba19dc @ionic/react-router@6.4.3-dev.11673974834.12ba19dc
```

I've forked the reproduction and modified the initial rendered items to test the scroll behavior: https://stackblitz.com/edit/angular-4uocfn-ldtit3

Thanks!

**Comment by piotr-cz** [comment]
@sean-perkins 
I've just tested the dev build and it fixes issue in stackblitz forked repo as well in the my app.
Thank you!

**Comment by piotr-cz** [comment]
@sean-perkins
Can you please add a comment here when bugfix will land in a stable release?
I'd like to remove workarounds from code then.

**Comment by sean-perkins** [comment]
@piotr-cz Ionic Framework releases weekly on Wednesday (as long as there is something to release). 

v6.5.3 released today and includes the fix for this issue: https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md

**Comment by piotr-cz** [comment]
Great, thank you!
