### ISSUE TITLE
bug: Unable to modify a page animation after a replace with Vue

### ISSUE THREAD

**Issue by corentincouq** [ionic-team/ionic-framework#26556]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When changing the page, with `ionRouter.replace`, my animation is not updated on its second call. 
If I make a custom animation during the replace, then I can't change the animation at the next replace. 

### Expected Behavior

I would like to swipe left and trigger a page change to the left. Once the page has changed, I would like to drag to the right and trigger an animation to the right.

### Steps to Reproduce

My animations : 
```javascript
import { createAnimation } from '@ionic/vue';

export const animationOpacity0to1 = (element, duration) =>
  createAnimation().addElement(element).duration(duration).fromTo('opacity', '0', '1');

export const animationTranslateXOpacity = (element, duration, direction = 'right') =>
  createAnimation()
    .addElement(element)
    .duration(duration)
    .fromTo('opacity', '0', '1')
    .fromTo('transform', 'translateX(0px)', direction === 'right' ? 'translateX(100%)' : 'translateX(-100%)');
```

My animation builder : 
```javascript
const recupereAnimationBuilder = (direction) => (baseEl, opts) =>
  createAnimation().addAnimation([
    animationOpacity0to1(opts.enteringEl, 300),
    animationTranslateXOpacity(opts.leavingEl, 200, direction),
  ]);
```

My gesture (call from `onIonViewWillEnter`): 
```javascript
const activeChangementDePageSwipe = () => {
  createGesture({
    el: swiperZone.value,
    threshold: 150,
    gestureName: 'change-page',
    onMove: (ev) => onSwipePage(ev),
  }).enable();
};
```

onMove event : 
```javascript
const onSwipePage = (ev) => {
  const nouvelId = ev.deltaX < 0 ? 'id_1' : 'id_1';

  const animation =
    ev.deltaX > 0
      ? recupereAnimationBuilder('right')
      : recupereAnimationBuilder('left');

  router.replace({ name: 'Vetement', params: { id: nouvelId } }, animation);

  return true;
}
```

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.1.4

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v16.17.1 (/opt/homebrew/Cellar/node@16/16.17.1/bin/node)
   npm    : 8.15.0
   OS     : macOS
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
