### ISSUE TITLE
feat: tab-button - ability to navigate directly to root

### ISSUE THREAD

**Issue by TiBz0u** [ionic-team/ionic-framework#26573]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi,

For the moment, once you navigate deeper into a tab, the navigation level remains even if you switch tab and comes back to the initial tab.

The video below illustrate the current situation and after, the new feature request.
https://user-images.githubusercontent.com/459963/210977847-78158513-c2f3-4ac0-be3e-440fe41c808d.mov

### Describe the Use Case

This actual behavior is clearly correct.

However, for some users, it's not very intuitive to click a second times on the tab to see the root page.

To avoid the double click, we can imagine work with forward navigation. but there is two major downsides:
- We have to go back until we see the tabs to see the root page.
- We can't navigate directly to other tab

When I look existing applications on the store, both behaviors seems coexist.

### Describe Preferred Solution

An attribute on the `ion-tab-button` (specific by tab) or a global attribute on `ion-tab-bar`.

The code to navigate to root page already exist. It will be a new conditional block. 

### Related Code

- Start a new tab Ionic project
https://ionicframework.com/docs/cli/commands/start

- Add a (click) event on the ion-tab-button (instead of the tab attribute). Link this event to a redirect function 
```
  openTab(i: number): void {
    const tab = 'tab'+i;
    this.navCtrl.navigateRoot(['tabs',tab]);
  }
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you help me understand what you are trying to accomplish? Each tab is meant to be its own stack, so the state of a particular tab should be preserved when you navigate away from it. While this is different from how tabs in traditional web apps behave, this is how tabs in native mobile apps behave. Ionic is designed to match the native tabs behavior.

**Comment by TiBz0u** [comment]
Hi @liamdebeasi, first, happy new year and thanks again for the great work on Ionic.

I though my example was clear but gives some confusion due to page naming (I'll try to send a new video to be more clear).

In reality, I never change tab programmatically. The only way to change tab is to click on the tabButton into the tabBar.

Actual Tab System is :
- Show Tab 1 root
- Open Child Page link
- Show Child Page (still on Tab 1)
- Click on Tab 2
- Show Tab 2 root
- Click on Tab1 (first click)
- Show Child Page
- Click on Tab1 (second click)
- Show Tab 1 root

The feature is to have a system to **directly** go to the last step :
- Show Tab 1 root
- Open Child page link
- Show Child Page (still on Tab 1)
- Click on Tab 2
- Show Tab 2 root
- Click on Tab1 (first click)
- Show **Tab 1 root**

Hope it's clearer. Don't hesitate if you have any questions.

Kr.

**Comment by liamdebeasi** [comment]
Thanks for the clarification, and happy new year! Do you have any examples of native mobile apps that implement this pattern?

**Comment by TiBz0u** [comment]
No problem :)

Two examples : 
- Spotify on Android (Select Search Tab > Choose a card > New Page Open on Search Tab > Switch Tab to Home > Switch again to Search > I'm again on the Search Root).
- A Belgian bank use this pattern too but you need to be client (no demo mode).

If I found another application, I'll tell you.

Kr.

**Comment by liamdebeasi** [comment]
Thanks! I am going to discuss this with the team.

**Comment by liamdebeasi** [comment]
Quick update: We compared the iOS and Android Spotify app behaviors, and the reported behavior seems to only happen on Android. We are reaching out to someone at Spotify to get clarification on the intent of this behavior difference.
