### ISSUE TITLE
feat: Ionic popover after hover no auto close

### ISSUE THREAD

**Issue by Kaiyen725** [ionic-team/ionic-framework#26587]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

After hover on the button and popover show out and hover leave the button the popover will auto close

### Describe the Use Case

Cause when I develop the menu I using button and popover to let user navigation the menu bar to select which page they want to redirect but current the user hover the button and popover come out but user still need to click other place to close popover it's no user friendly.

**Comment by Kaiyen725** [comment]
![image](https://user-images.githubusercontent.com/59947801/211774881-757942c2-cdca-47ad-a2b4-8572a08102a6.png)
So what I trying to say is now already hover the button and come out popover after that I move to hover another button, but I still need to click the page one time then can do hover action.

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please describe your use case?

**Comment by Kaiyen725** [comment]
I am using the popover as a dropdown menu, but it is not so user friendly, I mean when hover the button and trigger popover, if I going to hover another button, I need to click the blank place then I can hover another button to trigger the popover. I think when hover out the button or popover should be auto dismiss/close the popover without any clicks. This application is target for desktop.

**Comment by KANekT** [comment]
It's duplicate https://github.com/ionic-team/ionic-framework/issues/26324?

**Comment by Kaiyen725** [comment]
> It's duplicate #26324?

if got two buttons and two popover, user accidentally hover the first button and then to the second button, the user need go to the first button's popover content to close then continue to the second button? is there a better solution for multi-hover popover?

**Comment by liamdebeasi** [comment]
Thanks for the follow up. In the past we have added desktop-focused features. However, we are focusing our efforts on mobile applications moving forward. Since this request targets desktop devices, we do not have plans to add this feature. I am going to close this, but let me know if you have any questions.
