### ISSUE TITLE
feat: datetime, access month/year button via css

### ISSUE THREAD

**Issue by samuelrebuelta** [ionic-team/ionic-framework#26596]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I cannot change the calendar-month-year color.
<img width="315" alt="image" src="https://user-images.githubusercontent.com/31918772/211905539-247a1a5b-1ccd-4731-ae7d-a23a00a8ec7f.png">

### Expected Behavior

Be able to change this color with a css custom propery.

### Steps to Reproduce

Ion datetime in presentation date.
<img width="315" alt="image" src="https://user-images.githubusercontent.com/31918772/211905800-577ef349-122c-433b-9fc9-1619c78a2abe.png">

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.6
   Ionic Framework               : @ionic/angular 6.4.1
   @angular-devkit/build-angular : 15.0.4
   @angular-devkit/schematics    : 15.0.4
   @angular/cli                  : 15.0.4
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.2.0
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v14.17.5
   npm    : 6.14.14
   OS     : macOS Monterey
   Xcode  : Xcode 14.2 Build version 14C18

**Comment by SanjeevSingh08** [comment]
Where is the url where this issue can be found?
