### ISSUE TITLE
bug: swipe to go back / forward guesture on Safari causing page flicker (while having Ionic's STGB turned off)  

### ISSUE THREAD

**Issue by typefox09** [ionic-team/ionic-framework#26598]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When using the app in Safari on iPhone devices, using the native swipe to go back + forward gestures (that Safari provide) cause a flashing / janking effect for both back and forward navigation.

This issue has been mentioned on a previous issue (pasted below), however their solution mentions to turn off Ionic's STGB gesture, however I have tried this and the problem still persists.

https://github.com/ionic-team/ionic-framework/issues/22299

It appears that turning Ionic's STGB has no effect on the above issue at all. Using router.replace is not an option as we need history stack when being used in the browser.....

I have tried turning off the default animation effect on the ion-router-outlet, and the Ionic STGB feature, however this creates more of a jank effect as apposed to a flash in, flash out.

Have attached recording of this behaviour, the recording has Ionic's STGB function, and Ionic's default animation turned off.

https://user-images.githubusercontent.com/61811299/211972261-9f76c2ae-d0ee-40fa-80c0-64098ef4de0d.MP4

Live URL for testing:
https://ionic-swipe-test.web.app/home

This does not occur on Android devices, or on the native Capacitor app.

### Expected Behavior

The page should transition as normally expected. 

### Steps to Reproduce

1. Create a new project following the following tutorial:

https://ionicframework.com/docs/vue/quickstart

ionic start myApp blank --type vue

2. Add a link on the home page to a test page 2

3. Modify configuration to turn off Ionic's STGB:

```
const app = createApp(App)
  .use(IonicVue, {
    swipeBackEnabled: false
  })
  .use(router);
  

```  4. Turn off animation on ion-router-outlet:
  
`  <ion-router-outlet :animated="false"/>`
  

### Code Reproduction URL

https://github.com/typefox09/ionic-swipe-test

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.6 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.4.2

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v14.20.0 (/opt/homebrew/Cellar/node@14/14.20.0/bin/node)
   npm    : 6.14.17
   OS     : macOS

### Additional Information

_No response_

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this behavior. Fortunately, this bug has already been fixed in the upcoming Ionic 7 release.

The work required to fix this has been completed, so I am going to close this thread. We will have a beta period for Ionic 7 in the future where developers can test and provide feedback. I have attached a dev build of Ionic 7 below if you are interested in testing now:

```
npm install @ionic/vue@6.4.2-dev.11673981545.1e612253 @ionic/vue-router@6.4.2-dev.11673981545.1e612253
```

Note that this dev build is subject to the [Ionic 7 Breaking Changes](https://github.com/ionic-team/ionic-framework/blob/feature-7.0/BREAKING.md#version-7x). Let me know if there are any questions.
