### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by seirafiH** [ionic-team/ionic-framework#26608]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

the ion-datetime component outside my shadow dom works correctly. All of the of css variables are defined. However, inside 'my-compoenent' variables like --ion-color-contrast, are not set. The Ion-datetime component is not behaving as expected.  How do I fix this so the ion-datetime component works correctly inside my-component?
```html

<html>

<head>
  <link rel="stylesheet" type="text/css" href="https://cdn.skypack.dev/@ionic/core/css/core.css" />
  <link rel="stylesheet" type="text/css" href="https://cdn.skypack.dev/@ionic/core/css/ionic.bundle.css" />

  <script>
    window.Ionic = {
      config: {
        mode: 'ios'
      }
    }
  </script>
</head>

<body>
  <ion-app>
    <ion-content class="ion-padding">
      <ion-datetime></ion-datetime>
<my-component></my-component>
    </ion-content>
  </ion-app>
</body>

</html>
```

```ts
import { defineCustomElements } from '@ionic/core/loader';

import { loadingController, modalController, pickerController, toastController } from '@ionic/core';

/* Core CSS required for Ionic components to work properly */
import '@ionic/core/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/core/css/normalize.css';
import '@ionic/core/css/structure.css';
import '@ionic/core/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/core/css/padding.css';
import '@ionic/core/css/float-elements.css';
import '@ionic/core/css/text-alignment.css';
import '@ionic/core/css/text-transformation.css';
import '@ionic/core/css/flex-utils.css';
import '@ionic/core/css/display.css';

/* Theme variables */
import './theme/variables.css';

defineCustomElements();

(window as any).loadingController = loadingController;
(window as any).modalController = modalController;
(window as any).pickerController = pickerController;
(window as any).toastController = toastController;
class MyComponent extends HTMLElement {
  constructor() {
    super();
    this._shadowRoot = this.attachShadow({ mode: 'open' });
    this._shadowRoot.innerHTML = `
      <style>
        /* CSS styles for the component */
      </style>
      <div>
      
        <!-- Other HTML elements and content for the component -->
        <ion-item>
        <ion-datetime></ion-datetime>
        </ion-item>
      </div>
    `;
  }
}
customElements.define('my-component', MyComponent);


```

### Expected Behavior

the ion-datetime component outside my shadow dom works correctly. All of the of css variables are defined. However, inside 'my-compoenent' variables like --ion-color-contrast, are not set. The Ion-datetime component is not behaving as expected.  How do I fix this so the ion-datetime component works correctly inside my-component?

### Steps to Reproduce

You can go to https://ionicframework.com/docs/api/datetime and paste the above code inside of the javascript example under basic usage to see the broken behavior inside of the shadow dom component. 

### Ionic Info

Ionic:

   Ionic CLI : 6.20.4

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v19.1.0
   npm    : 8.19.3
   OS     : Linux 5.15

**Comment by liamdebeasi** [comment]
Thanks for the report. This is more of a support question, so I recommend you ask this on the [Ionic Forums](https://forum.ionicframework.com/) instead. We use this repo to track bugs and feature requests in Ionic. If you think this is a bug in Ionic, feel free to reply, and I will be more than happy to reopen this issue.

That being said, I do not recommend using a Shadow DOM component within another Shadow DOM component in this way as it can interfere with styling inheritance. Instead, I recommend keeping `my-component` in the light DOM.
