### ISSUE TITLE
bug: ion-datetime title is not displayed when presentation="month-year"

### ISSUE THREAD

**Issue by Serg-Mois** [ionic-team/ionic-framework#26600]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

slot="title" is not displayed when presentation="month-year" and [preferWheel]="true"

### Expected Behavior

Title is displayed

### Steps to Reproduce

```
<ion-datetime-button datetime="datetime"></ion-datetime-button>

<ion-modal [keepContentsMounted]="true">
  <ng-template>
    <ion-datetime presentation="month-year" id="datetime" [preferWheel]="true">
      <div slot="title">MY TITLE</div>
    </ion-datetime>
  </ng-template>
</ion-modal>
```

But if you change  the presentation to "date" - everything works as expected

### Code Reproduction URL

https://stackblitz.com/edit/angular-4shiwd-7qhimw?file=src%2Fapp%2Fexample.component.html

### Ionic Info

    "@ionic/angular": "6.4.1",
    "@ionic/core": "6.4.1"

**Comment by amandaejohnston** [comment]
Thank you for the issue. Sure enough, we aren't currently rendering the header for the `month-year` presentation (among others), but this should be adjusted. I'll get a fix up soon.

**Comment by amandaejohnston** [comment]
Here's an Ionic dev build if you're interested in testing the proposed fix:
```
npm install @ionic/angular@6.4.3-dev.11673985390.12798de9
```

**Comment by amandaejohnston** [comment]
I've gone ahead and merged in the fix: https://github.com/ionic-team/ionic-framework/pull/26616 It will be available in an upcoming patch release of Ionic Framework, but feel free to take a look at the dev build if you'd like to try it sooner.
