### ISSUE TITLE
bug: ion-tab child route broken after redirection on root page

### ISSUE THREAD

**Issue by loopezz** [ionic-team/ionic-framework#26603]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Navigation to a child page doesn't work as intented after clicking on the ion-tab-button while on the tab's root page with a specific routing configuration*. Navigating to the child page does work as long the user does not press the ion-tab-button as described.

----
Short screen recording:
https://user-images.githubusercontent.com/11312418/212339653-bc6570c0-7c42-4731-9548-05b7c2515542.mov

----
*Example code
Tab1Page routes:
```
const routes: Routes = [
  {
    path: '',
    component: Tab1Page,
  },
  {
    path: 'child',
    loadChildren: () => import('../child/child.module').then(m => m.ChildPageModule),
  },
];
```

Tabs routes:
```
const routes: Routes = [
  {
    path: 'tabs',
    component: TabsPage,
    children: [
      // Works
      {
        path: 'tab1',
        loadChildren: () => import('../tab1/tab1.module').then(m => m.Tab1PageModule),
      },

      // Works
      {
        path: 'tab1',
        children: [
          {
            path: '',
            loadChildren: () => import('../tab1/tab1.module').then(m => m.Tab1PageModule),
          },
        ]
      },

      // Works, but navigation to child page is broken after clicking on the tab button while on tab's root page
      {
        path: 'tab1',
        children: [
          {
            path: 'home',
            loadChildren: () => import('../tab1/tab1.module').then(m => m.Tab1PageModule),
          },
          {
            path: '**',
            redirectTo: 'home',
          },
        ]
      },

      {
        path: 'tab2',
        loadChildren: () => import('../tab2/tab2.module').then(m => m.Tab2PageModule)
      },
      {
        path: 'tab3',
        loadChildren: () => import('../tab3/tab3.module').then(m => m.Tab3PageModule)
      },
      {
        path: '**',
        redirectTo: 'tab1',
      }
    ]
  },
  {
    path: '**',
    redirectTo: 'tabs',
  }
];
```

### Expected Behavior

Navigation should keep working even if the user clicks on the ion-tab-button while on the tab's root page.

### Steps to Reproduce

1. Click on 'Navigate to child page'
2. Navigate back to the 'Tab 1' root page
3. Click on 'Tab 1' in the ion-tabs bar
4. Click on 'Navigate to child page'

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.6 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.4.2
   @angular-devkit/build-angular : 15.1.1
   @angular-devkit/schematics    : 15.1.1
   @angular/cli                  : 15.1.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.15.1 (/usr/local/bin/node)
   npm    : 8.11.0
   OS     : macOS
```

### Additional Information

Reproduction code:
[myApp.zip](https://github.com/ionic-team/ionic-framework/files/10412380/myApp.zip)

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce the reported behavior, but this does not appear to be a bug in Ionic. Views that appear within tabs should be written as sibling routes with the parent tab as the path prefix: https://ionicframework.com/docs/angular/navigation#child-routes-within-tabs

The reason for this is nested routes in mobile apps should only be used when you want to render multiple views in multiple outlets. Tabs is a great example of this because `ion-tab-bar` is rendered in the top-level `ion-router-outlet`, but the actual tab content (Tab 1, Tab 2, etc) is rendered in the `ion-router-outlet` that is inside of `ion-tabs.`

Your routing config in `tabs-routing.module.ts` should look something like this instead:

```js
children: [
  {
    path: 'tab1',
    loadChildren: () => import('../tab1/tab1.module').then(m => m.Tab1PageModule)
  },
  {
    path: 'tab1/child',
    loadChildren: () => import('../child/child.module').then(m => m.ChildPageModule),
  },
  {
    path: 'tab2',
    loadChildren: () => import('../tab2/tab2.module').then(m => m.Tab2PageModule)
  },
  {
    path: 'tab3',
    loadChildren: () => import('../tab3/tab3.module').then(m => m.Tab3PageModule)
  },
  {
    path: '**',
    redirectTo: 'tab1',
  }
]
```

(As part of this, you would remove the `child` route declaration from `tab1-routing.module.ts`
