### ISSUE TITLE
bug:  Ionic component should not be clickable during scroll

### ISSUE THREAD

**Issue by zakuru** [ionic-team/ionic-framework#26609]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hi,

I have a page which container Ioncard within a Ionlist with the infiniscroll
While scroll is happening if i click one a card the  scroll stops and fires immediately  the event of the card: transition to the a page
Normally the first click should only stop the scroll - a second click on the card should then fire the event from the card

### Expected Behavior

Expected behavior:
While scrolling on click should only stop the scroll and not fire the click event from the card 

### Steps to Reproduce

I dont have a repro repo but i can add one.
But the steps  are described in the bug section

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.6
   Ionic Framework : @ionic/react 6.4.1

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.15.0
   OS     : Windows 10

**Comment by ar-ushi** [comment]
Hi @zakuru, can you provide a way to reproduce this? A generic version of the code you were running when you noticed the bug would be helpful.

**Comment by zakuru** [comment]
Ok @ar-ushi will do soon thanks

**Comment by zakuru** [comment]
@ar-ushi here is a repo that reproduces the issue https://github.com/zakuru/ionic-playgroud

**Comment by liamdebeasi** [comment]
Thanks for the report. I tested this on a Motorola G4 and a Pixel 4a, but I was unable to reproduce the reported behavior:

https://user-images.githubusercontent.com/2721089/214859414-59b5c893-c94e-4071-b533-76459d71f353.mp4


It's possible that this is a device-specific bug. In that case, I recommend reporting this to the Chromium team: https://bugs.chromium.org/p/chromium/issues/list

**Comment by zakuru** [comment]
Issue fixed. Congrats for ionic 7!
