### ISSUE TITLE
bug: ion-datetime cancel and done buttons are not aligned

### ISSUE THREAD

**Issue by pkunszt** [ionic-team/ionic-framework#26601]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

![image](https://user-images.githubusercontent.com/10047646/212268967-ad33b878-6ce0-4592-aa81-8741e9e450cc.png)

if you create ion-datetime with showDefaultButtons="true" and with cancelText and doneText also set (to cancel and OK), then the buttons shown are not properly aligned vertically, see picture. this gives the app a non-professional look and feel.

### Expected Behavior

The buttons are properly aligned vertically.

### Steps to Reproduce

see current behavior

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.6 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.2
   @angular-devkit/build-angular : 14.2.6
   @angular-devkit/schematics    : 14.2.6
   @angular/cli                  : 14.2.6
   @ionic/angular-toolkit        : 6.1.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.10.0 (/opt/homebrew/Cellar/node/18.10.0/bin/node)
   npm    : 8.19.2
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
