### ISSUE TITLE
bug: Ionic v6 with React : Page transitions are not working

### ISSUE THREAD

**Issue by LouisLecouturier** [ionic-team/ionic-framework#26606]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I tried to implement Page transitions following the documentation but no transitions are showing when my pages are changing...

I can navigate between my pages but there's no transition between them.

### Expected Behavior

Page transition should be working... I should see some animations when I am navigating through my app

### App.tsx

```jsx
<IonApp>
  <QueryClientProvider client={queryClient}>
    <IonReactRouter>
      <IonRouterOutlet>
        <Route exact path="/login">
          <>
            <Header />
            <Login />
          </>
        </Route>
        <Route path="/app/" render={(props) => <AppRouter {...props} />} />
        <Route render={() => <Redirect to={"/app/"} />} />
      </IonRouterOutlet>
    </IonReactRouter>
</IonApp>
```

### AppRouter.tsx
(This the router which should provide page transitions)

```jsx
<IonPage>
    <Header isAuth />
    <IonRouterOutlet animated={true} animation={RouterAnimation}>
      <Route path={`${match.url}/home`} component={Home} />
      <Route path={`${match.url}/planning`} component={Planning} />
      <Route path={`${match.url}/notes`} component={Grades} />
      <Route path={`${match.url}/absences`} component={Absences} />
      <Route path={`${match.url}/settings`} component={Settings} />
      <Route render={() => <Redirect to={`${match.url}/home`} />} />
    </IonRouterOutlet>
    <Footer />
  </IonPage>
```

### RouterAnimation.ts

```ts
import { createAnimation } from "@ionic/react";

export const RouterAnimation = (baseEl: HTMLElement, opts?: any) => {
  const enteringAnimation = createAnimation()
    .addElement(opts.enteringEl)
    .fromTo("opacity", "0", "1")
    .fromTo("transform", "translateX(100%)", "translateX(0%)")
    .duration(600)
    .easing("cubic-bezier(0.85, 0, 0.15, 1)");

  const leavingAnimation = createAnimation()
    .addElement(opts.leavingEl)
    .fromTo("opacity", "1", "0")
    .fromTo("transform", "translateX(0%)", "translateX(-100%)")
    .duration(600)
    .easing("cubic-bezier(0.85, 0, 0.15, 1)");

  return createAnimation().addAnimation([enteringAnimation, leavingAnimation]);
};
```

### A page component

```jsx
<IonPage>
  <div className="mock-header"></div>
  <IonContent>
    <h1 className="title">Absences</h1>
  </IonContent>
  <div className="mock-footer"></div>
</IonPage>
```

To navigate through pages, I use `<Link to="myUrl">` from **React-Router-Dom**

### Ionic Info

**Ionic:**

   Ionic CLI       : 6.20.8 (/Users/louislecouturier/.nvm/versions/node/v16.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.4.2

**Capacitor:**

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

**Utility:**

   cordova-res : 0.15.4
   native-run  : 1.7.1

**System:**

   NodeJS : v16.15.1 (/Users/louislecouturier/.nvm/versions/node/v16.15.1/bin/node)
   npm    : 8.15.0
   OS     : macOS

### Additional Information

I don't get it... everything should work fine according to the documentation...

**Comment by LouisLecouturier** [comment]
Here's a reproduction of the error

[Ionic-Transition-Issue-on-nested-routes](https://github.com/LouisLecouturier/Ionic-Transition-Issue-on-nested-routes)

**Comment by liamdebeasi** [comment]
Thanks for the additional information and apologies for the delay. I can reproduce the reported behavior, but this does not appear to be a bug in Ionic.

The nested CompOne, CompTwo, and CompThree pages do not have any transitions because you are not using the `IonPage` component. As noted in https://ionicframework.com/docs/react/navigation#ionpage, this component is necessary for transitions to function correctly. Adding `IonPage` to these components resolved the issue on my end.
