### ISSUE TITLE
bug: iOS button activated styling doesn't show when button is hovered

### ISSUE THREAD

**Issue by xnousnow** [ionic-team/ionic-framework#26623]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

in the [Documentation of ion-button](https://ionicframework.com/docs/api/button#fill), when I click or hover 'outline' version, it works fine, but when I **drag** the button using cursor, the button fills with primary color. The bug is only on ios mode.

### Expected Behavior

It should not be filled.

### Steps to Reproduce

1. Go to [Documentation of ion-button](https://ionicframework.com/docs/api/button#fill)
2. 'Drag' the outlined button. look at the example:
```
    [Correct]
+---------------+
|    Outline ===+==> Cursor is not in the button
+---------------+

   [Incorrect]
+---------------+
|    Outline => | Cursor is in the button
+---------------+
```

### Ionic Info

It was on the official ionic documentation.

**Comment by liamdebeasi** [comment]
Thanks for the report. The outline buttons should become filled when the button is activated. However, it looks like the activated state is not being applied if the cursor is hovering over the button.

**Comment by amandaejohnston** [comment]
I've confirmed that this only happens in `ios` mode, but occurs with all button styles. Checking locally, the `ion-activated` class is being applied correctly, so it's likely that our hover styling has a higher specificity than the activated styling somewhere.

**Comment by xnousnow** [comment]
So, should the button be light when hovered and dark when clicked?

**Comment by liamdebeasi** [comment]
Hi everyone,

It looks like we already have this report logged in https://github.com/ionic-team/ionic-framework/issues/22468, so I am going to merge the two threads. Please follow #22468 for updates on this issue. Thanks!
