### ISSUE TITLE
i-datetime like input

### ISSUE THREAD

**Issue by hohnworld** [ionic-team/ionic-framework#26621]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

is there some way to let i-datetime like version4  which when click the input then popup datetime picker

### Describe the Use Case

I don't want to show like popped datetime picker，I just want it like input ,when tapped it then show the datetime picker

**Comment by sean-perkins** [comment]
@hohnworld you could use an `ion-input` as the trigger element to present the new `ion-datetime` in a popover.

Here is an example to get you started: 
- https://stackblitz.com/edit/3hzbba?file=index.html

I would recommend using a library like `date-fns` to format the date inside of the `ion-input`.
