### ISSUE TITLE
bug: breadcrumbs has documentation for non-existent css variables

### ISSUE THREAD

**Issue by fbrun** [ionic-team/ionic-framework#26625]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Setting the `--background` or `--color` custom css propertie on `ion-breadcrumbs` in **Angular** results in the propertie being missing from the final render. This means the inner ion-breadcrumbs elements don't detect the color or background applied to the element.

In [breadcrumbs.scss](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/breadcrumbs/breadcrumbs.scss), we can see the properties never used !

### Expected Behavior

Setting `--color` or `--background` on `ion-breadcrumbs` should change the color or background on the element.

### Steps to Reproduce

[https://stackblitz.com/edit/angular-je8ihl?file=src%2Fapp%2Fexample.component.css](https://stackblitz.com/edit/angular-je8ihl?file=src%2Fapp%2Fexample.component.css)

### Code Reproduction URL

https://stackblitz.com/edit/angular-je8ihl?file=src%2Fapp%2Fexample.component.css

### Ionic Info

`Ionic:

   Ionic CLI                     : 6.20.8
   Ionic Framework               : @ionic/angular 6.4.1
   @angular-devkit/build-angular : 14.2.10
   @angular-devkit/schematics    : 14.2.10
   @angular/cli                  : 14.2.10
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.17.0
   npm    : 8.15.0
   OS     : Linux 5.15`

**Comment by liamdebeasi** [comment]
Thanks for the report. It looks like the CSS Variables were removed during development as they were not needed. However, the documentation for them was not removed. Special CSS Variable APIs are not needed here since the normal `background` works as expected. Note that `color` should be set `ion-breadcrumb`, since that is where the text is.

**Comment by liamdebeasi** [comment]
This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26630. Thanks for the report!
