### ISSUE TITLE
feat: Add "part" to ion-datetime, to be more flexible for special requirements

### ISSUE THREAD

**Issue by Schwankenson** [ionic-team/ionic-framework#26624]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like to add something to closed task: https://github.com/ionic-team/ionic-framework/issues/24963

It would be great to have "part=xyz" defined in ion-datetime element, to be more flexible for special requirements. Read my use case to understand what I e.g. mean

### Describe the Use Case

I needed to build a date wheel like that, were user can choose a day within the next few days comfortable while showing the weekday.

![image](https://user-images.githubusercontent.com/803955/213145078-b6e4f256-b755-4b62-bae6-fc52a1751412.png)

I needed to do something like that for it:

```
<ion-datetime 
    presentation="date-time"
    [hourValues]="[]"
    [minuteValues]="[]"
    [min]="dateNow"          
    [preferWheel]="true" 
></ion-datetime>
```

And then put it do a container with `overflow: hidden` and margin top of `-40px`. That code is a freak of nature. I think it would be much easier to style it with parts. I could hide things and change height and so on.

### Describe Preferred Solution

Add `part=` to parts of ion-datetime, to be able to style it from outside

### Describe Alternatives

- More options for datewheel: A height and option to input date format or something like that
- Template parts to override ion-datetime parts with?

### Related Code

See code in "use case" part

### Additional Information

I don\`t really get why you won`t let us style elements like that, or add template parts to add custom template parts. 

I understand, that the idea is that you normally should not have to change the ionic elements, because you have a theme. But there will always be special things for some UIs, and it`s not a good idea that I have to install external component libraries with npm then only because customizing ionic components is limited strongly.

**Comment by liamdebeasi** [comment]
Thanks for the report. We have two existing feature requests for this, so I am going to close this ticket in favor of the existing tickets: https://github.com/ionic-team/ionic-framework/issues/25945 and https://github.com/ionic-team/ionic-framework/issues/25340 (The first issue seems to be more relevant to your request than the second issue)
