### ISSUE TITLE
bug: firefox, animation playback flickers at the end

### ISSUE THREAD

**Issue by MadsKelberg** [ionic-team/ionic-framework#26620]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

It seems to quickly re-render or not correctly transitioning from the current page to another page inside the same tab.
Let's say we have a route **/home** and another one **/home/detail**. When a button in **/tab3** is pressed with a `routerLink` pointing to **/home/detail** it flashes the content from the previous page. I have tried a few different Ionic components. It seems to happen on IonItem and IonCard. It also happens with normal `<a></a>` tags.

Sometimes the transition animation doesn't even work properly.

### Expected Behavior

I expect it to transition cleanly from one page to another.

### Steps to Reproduce

Press the item **Some Item** on the home page. It should flash the same content at the end of the transition. If it doesn't try it a few times. 

### Code Reproduction URL

https://github.com/MadsKK/IonicReact-RerenderingIssue

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /home/madsk/.config/yarn/global/node_modules/@ionic/cli/lib/project/index.js
       - /home/madsk/.config/yarn/global/node_modules/@ionic/cli/lib/index.js
       - /home/madsk/.config/yarn/global/node_modules/@ionic/cli/index.js
       - /home/madsk/.config/yarn/global/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /home/madsk/.config/yarn/global/node_modules/@ionic/cli/lib/project/index.js
       - /home/madsk/.config/yarn/global/node_modules/@ionic/cli/lib/index.js
       - /home/madsk/.config/yarn/global/node_modules/@ionic/cli/index.js
       - /home/madsk/.config/yarn/global/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.20.6 (/home/madsk/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.4.2

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : not installed
   @capacitor/core    : 4.6.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1 (/home/madsk/.nvm/versions/node/v18.12.1/bin/node)
   npm    : 9.3.1
   OS     : Linux 6.1

**Comment by liamdebeasi** [comment]
Thanks for the report. What device are you testing this on? I am unable to reproduce the reported behavior.

**Comment by liamdebeasi** [comment]
Does this happen on a physical iOS or Android device?

**Comment by MadsKK** [comment]
Haven't thought about testing that. It just happened on the browser, so I didn't try to build it to Android nor IOS.
You want me to try and build it to Android?

**Comment by liamdebeasi** [comment]
If you could test on a device that would be great. I tested your sample repo on macOS, iOS, and Android but was unable to reproduce the reported behavior.

**Comment by MadsKK** [comment]
I have a video of the behavior I have attached to this comment.
It is on the web browser on Firefox Linux.
I'm currently building it to android to test.
[Issue on webbrowser.webm](https://user-images.githubusercontent.com/35922365/213229849-20b23cc0-781f-4556-be3c-4d06718878c9.webm)

**Comment by liamdebeasi** [comment]
Thanks for checking on Android. I just checked Firefox on macOS and I can now reproduce this behavior only in Firefox (I was checking Chrome and Safari before). Let me do some digging here.

**Comment by liamdebeasi** [comment]
This appears to be a bug in Firefox as I can reproduce this behavior outside of Ionic. I have reported this issue to the Firefox team: https://bugzilla.mozilla.org/show_bug.cgi?id=1811099

**Comment by MadsKK** [comment]
Alright, thanks for the help @liamdebeasi :)

**Comment by MadsKK** [comment]
It seems like the problem only occurs when using the `<IonGrid>` component. With that being said I haven't tested what exactly it is inside the component that causes this issue.

**Comment by jansgescheit** [comment]
It also happens when you change pages and you briefly see flicker the previous page

**Comment by liamdebeasi** [comment]
This issue will likely impact any animation where an element is being hidden when the animation ends. It appears certain conditions (`contain`, CSS Variables, Shadow DOM, etc) cause the browser to do a repaint at the end of the transition. However, it looks like it is painting using an outdated state of the DOM.
