### ISSUE TITLE
bug: Teleported components are not unmounted in Vue

### ISSUE THREAD

**Issue by raymer** [ionic-team/ionic-framework#26644]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

As of 6.4.2, when modals are opened (at least via modalController) they aren't unmounted on dismiss, causing stale data on creation of the modal again. (All previous refs, etc still have their data from last time the modal was created)

### Expected Behavior

On dismiss, modals should unmount, causing all refs and other data to clear.

### Steps to Reproduce

- Install 6.4.2 or newer of ionic.
- Create a modal via modalController.create
- Add input field with ref to modal
- type data in the input
- dismiss the modal
- create a modal via modalController.create again
- see old input values in the input field

### Code Reproduction URL

https://github.com/raymer/ionic-modal-bug

### Ionic Info

Ionic:

   Ionic CLI       : 5.4.16 (C:\Users\rayme\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/vue 6.4.2

Capacitor:

   Capacitor CLI   : 4.6.1
   @capacitor/core : 3.9.0

Utility:

   cordova-res : not installed
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.2
   OS     : Windows 10

**Comment by sean-perkins** [comment]
@raymer thanks for reporting this issue! I'm able to reproduce and have narrowed it to the changes I recently made here: https://github.com/ionic-team/ionic-framework/pull/26543.

I'll log this as a bug and dig deeper into why there is an objective difference between the filter and splice usage and how to solve the original bug and restore the regressed behavior.

**Comment by sean-perkins** [comment]
@raymer can you test with this dev-build and let me know if you run into issues?

```
npm install @ionic/vue@6.5.1-dev.11674170004.1a4e4ede @ionic/vue-router@6.5.1-dev.11674170004.1a4e4ede
```

**Comment by raymer** [comment]
@sean-perkins that looks like the fix. Didn't notice any other issues 👍
