### ISSUE TITLE
feat: Allow configuring confirmation behavior of `ion-datetime` when using buttons.

### ISSUE THREAD

**Issue by diesieben07** [ionic-team/ionic-framework#26642]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

`ion-datetime` behaves differently depending on whether it has buttons inside it or not. If there any buttons (either implicitly via `showDefaultButtons` or manually using a nested `ion-buttons`) then `ion-datetime` will only emit the change when it is explicitly confirmed using the `confirm` method. It should be possible to enable the current behavior for when no buttons are present (emit the change event immediately when the user inputs a date) even when a custom set of buttons has been nested.

### Describe the Use Case

When implementing a form element using `ion-datetime` I would like to allow the user to reset the form element back to its default value. To do this I can slot a button using `ion-buttons` and use `reset(defaultDate)`. However in doing so the user is no longer able to actually select a date, unless I also provide a confirmation button. I would like the more intuitive behavior of not having to tap a confirm button but also slot in a custom button.

### Describe Preferred Solution

Provide a prop on `ion-datetime` that configures whether or not a slotted button has confirm functionality, such as `hasConfirmButton`. This prop only has an effect when an `ion-buttons` element is slotted and if so, configures whether or not the slotted buttons have a confirm button. If set to false, `ion-datetime` will immediately emit a change event when the user taps on a date, like `ion-datetime` already does by default when there are no buttons.

**Comment by liamdebeasi** [comment]
Thanks for the report. Have you tried the [showClearButton](https://ionicframework.com/docs/api/datetime#showclearbutton) property? This property lets you render a button to reset the state of the datetime without requiring a confirmation button. You can also change the text that is rendered using the [clearText](https://ionicframework.com/docs/api/datetime#cleartext) property.

**Comment by diesieben07** [comment]
I know about showClearButton, however it sets the selected date to _today_, not whatever default value I want.

**Comment by liamdebeasi** [comment]
Clicking the clear button sets the datetime value to undefined. You can listen for `ionChange` to then set the `value` to the date you want. Here is an example: https://codepen.io/liamdebeasi/pen/jOpapPQ

A datetime is only set to `undefined` when the clear button is clicked (or when the application sets it manually).

**Comment by diesieben07** [comment]
Interesting, thank you for the demo. The ion-datetime-button shows today's date when you click the clear button normally, but you can intercept the change event like you showed. Seems like a bit of a hack to me, but it does solve my problem.
It might be worth allowing more than one button, but my immediate use-case is solved by intercepting ionChange.

**Comment by liamdebeasi** [comment]
Glad to hear the solution works for your use case. I am going to close the thread for now, but we will be sure to keep this use case in mind as we explore further improvements to the datetime API. Let me know if you have any other questions.
