### ISSUE TITLE
bug: ion-input ignores disabled attribute when using Reactive forms in a nested child component

### ISSUE THREAD

**Issue by RRGT19** [ionic-team/ionic-framework#26645]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Using Reactive forms, the `disabled` attribute is ignore in a nested child component.

This was working good using these versions:
```json

{
"dependencies": {
"@angular/common": "~14.2.9",
"@angular/core": "~14.2.9",
"@angular/forms": "~14.2.9",
"@angular/platform-browser": "~14.2.9",
"@angular/platform-browser-dynamic": "~14.2.9",
"@angular/router": "~14.2.9",
"@capacitor/android": "^4.5.0",
"@capacitor/core": "^4.5.0",
"@capacitor/ios": "^4.5.0",
"@ionic/angular": "^6.3.8",
"rxjs": "^7.5.7",
"tslib": "^2.4.1",
"zone.js": "^0.11.8"
},
"devDependencies": {
"@angular-devkit/build-angular": "~14.2.8",
"@angular-eslint/builder": "14.1.2",
"@angular-eslint/eslint-plugin": "14.1.2",
"@angular-eslint/eslint-plugin-template": "14.1.2",
"@angular-eslint/template-parser": "14.1.2",
"@angular/cli": "~14.2.8",
"@angular/compiler": "~14.2.9",
"@angular/compiler-cli": "~14.2.9",
"@angular/language-service": "~14.2.9",
"@capacitor/cli": "^4.5.0",
"@ionic/angular-toolkit": "^7.0.0",
"typescript": "^4.8.4"
}
}
```

_Some dependencies were omitted for brevity._

But now, the issue is present using these versions (latest so far):

```json

{
  "dependencies": {
    "@angular/common": "~15.1.1",
    "@angular/core": "~15.1.1",
    "@angular/forms": "~15.1.1",
    "@angular/platform-browser": "~15.1.1",
    "@angular/platform-browser-dynamic": "~15.1.1",
    "@angular/router": "~15.1.1",
    "@capacitor/android": "^4.6.2",
    "@capacitor/core": "^4.6.2",
    "@capacitor/ios": "^4.6.2",
    "@ionic/angular": "^6.5.0",
    "rxjs": "^7.8.0",
    "tslib": "^2.4.1",
    "zone.js": "^0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~15.1.1",
    "@angular-eslint/builder": "15.2.0",
    "@angular-eslint/eslint-plugin": "15.2.0",
    "@angular-eslint/eslint-plugin-template": "15.2.0",
    "@angular-eslint/template-parser": "15.2.0",
    "@angular/cli": "~15.1.1",
    "@angular/compiler": "~15.1.1",
    "@angular/compiler-cli": "~15.1.1",
    "@angular/language-service": "~15.1.1",
    "@capacitor/cli": "^4.6.2",
    "@ionic/angular-toolkit": "^7.0.0",
    "typescript": "^4.8.4"
  },
}
```

Using just 1 child component, is working good:

```
this.form = this.fb.group({
      firstName: [{value: null, disabled: true}, Validators.required],
});

<app-input-form-control formControlName="firstName" label="Name(s)">
</app-input-form-control>
```

`app-input-form-control` is a component that implements `ControlValueAccessor`.

Using a child component that internally has another child component, is not working anymore:

```
<app-credit-card-details formControlName="creditCard"></app-credit-card-details>
```

The above has a child component like this:

```
this.form = this.fb.group({
      firstName: [{value: null, disabled: true}, Validators.required],
});

<app-input-form-control formControlName="firstName" label="Name(s)">
</app-input-form-control>
```

In this case, the `item-interactive-disabled` class is not added to the `ion-item`.

```html
<ion-item _ngcontent-nql-c147="" class="item-has-value ion-untouched ion-pristine ion-valid item md item-lines-default item-fill-none hydrated item-interactive item-input item-has-placeholder">
  ........
  .....
</ion-item>
```

### Expected Behavior

The `item-interactive-disabled` class should be added to `ion-item`.

### Steps to Reproduce

Try to use `{value: null, disabled: true}` in a nested child component. See code reproduction...

### Code Reproduction URL

https://github.com/RRGT19/ionic-example-disabled-att

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.8 (/Users/robert/.nvm/versions/node/v16.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.5.0
   @angular-devkit/build-angular : 15.1.1
   @angular-devkit/schematics    : 15.1.1
   @angular/cli                  : 15.1.1
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.6.2
   @capacitor/ios     : 4.6.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.18.1 (/Users/robert/.nvm/versions/node/v16.18.1/bin/node)
   npm    : 9.3.0
   OS     : macOS

### Additional Information

I have found a similar issue, but it's locked for comments: https://github.com/ionic-team/ionic-framework/issues/9834

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce the reported behavior, but this does not seem to be a bug in Ionic. I logged the `ngControl` for the Credit Card field in `input-form-control.component.ts`, and it has `disabled: false` set. You will need to disable the form control in order for the associated input to be disabled.

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce the reported behavior, but this does not seem to be a bug in Ionic. I logged the `ngControl` for the Credit Card field in `input-form-control.component.ts`, and it has `disabled: false` set. You will need to disable the form control in order for the associated input to be disabled.

Adding `{value: null, disabled: true}` to the `creditCard` form control does disable the input.

**Comment by RRGT19** [comment]
Inside the `CreditCardDetailsComponent`, the `FormControl` has `{value: 'This is not working, should be disabled', disabled: true}`, but still it's not disabled visually.  Imagine that this component is for entering all the credit card details like name, cvv, etc.. but in this case, the CVV is a fixed number and it's disabled. This disabled field is not changing visually.

If I do:
`creditCard: [{value: null, disabled: true}],`
inside of the `HomePage`, all the fields will be disabled, but that is not what I want to achieve. I want to disable a nested field inside of a custom component and here is when is not working visually.

I have added more fields to the `CreditCardDetailsComponent` to better express the issue, one of them is disabled.
Check here: https://github.com/RRGT19/ionic-example-disabled-att/blob/master/src/app/components/credit-card-details/credit-card-details.component.ts#L27

**Comment by RRGT19** [comment]
By the way, as I said above in the original post, it was working good using old versions of Ionic (6.3.8) and Angular (14.2.9).

See working code reproduction here in another branch:
https://github.com/RRGT19/ionic-example-disabled-att/blob/working-version/src/app/components/credit-card-details/credit-card-details.component.ts#L27

**Comment by liamdebeasi** [comment]
Thanks for the reply. I do see that `disabled: true` using the following code: 

```js
creditCardCVV: [{value: 'I should be disabled', disabled: true}],
```

However, logging the `ngControl` in `InputFormControlComponent` shows that `disabled` is still set to `false` on the form control. I replaced `ion-input` with `input`, and the reported behavior persists.

In `home.page.html` you are still passing `formControlName="creditCard"` to `app-credit-card-details` which does not have `disabled: true`. It appears that this is interfering with the state of `creditCardCVV` in `CreditCardDetailsComponent`. Removing `formControlName="creditCard"` resolves the issue on my end.

**Comment by liamdebeasi** [comment]
I also tried your `working-version` branch. However, the difference in behavior between `working-version` and `master` persists even when both apps are running `@ionic/angular@6.5.1`. 

The reported behavior only occurs after updating the application from Angular 14 to Angular 15.

**Comment by RRGT19** [comment]
Is correct, testing more versions of Ionic, the issue is still present using Angular 15. That being said, Ionic is working fine, we can closed this issue here.

Apparently, Angular 15 introduced changes about this topic. I don't know for sure what is it, but I will ask for help on the Angular repo or maybe stackoverflow. 

_Maybe what I'm trying to accomplish is done in a different way now using angular 15, We'll see..._

Thanks for all your help and support so far, helped me a lot to find the guilty.

**Comment by liamdebeasi** [comment]
The Angular 15 changelog notes the following:


> setDisabledState will always be called when a ControlValueAccessor is attached. You can opt-out with FormsModule.withConfig or ReactiveFormsModule.withConfig.

It's possible that the parent `creditCard` formControlName was causing `disabled` to be set to `false` since `setDisabledState` is now called.

https://github.com/angular/angular/blob/main/CHANGELOG.md#forms-2

**Comment by RRGT19** [comment]
Awesome, thanks for pointing that out.

I have found the PR of this change here https://github.com/angular/angular/pull/47576

This setup inside of the `home.module.ts `did the trick:

```typescript
ReactiveFormsModule.withConfig({
      callSetDisabledState: 'whenDisabledForLegacyCode'
})
```

Now, just need to understand the new way and adjust my code accordingly.

Thanks again @liamdebeasi

**Comment by RRGT19** [comment]
For future readers, another way that works is calling `disable()` on the `FormControl` that we want to **disabled** inside of the `ngAfterViewInit` hook.

Example:
```typescript
ngOnInit() {
    this.form = this.fb.group({
      creditCardName: [null],
      creditCardCVV: [null],
    });
  }

ngAfterViewInit() {
    this.form.get('creditCardCVV').disable({emitEvent: false});
}
```

This way, we don't need to set `callSetDisabledState` as a config to the ReactiveFormsModule.
