### ISSUE TITLE
feat: ion-picker description

### ISSUE THREAD

**Issue by dkern** [ionic-team/ionic-framework#26652]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It is possible to use prefix/suffix to describe columns. But what is missing in my opinion is a text/label above all columns.

### Describe the Use Case

For example, I have two columns to select the integral and fraction part of a number. It would be nice to have some text above both columns like "select your number". If you have multiple Picker in one form, the user might be wondering what picker he has click (maybe by accident). There is no description when the picker is opend.

**Comment by liamdebeasi** [comment]
Thanks for the report. Do you a sample app I can run that shows the issue you are running into?
