### ISSUE TITLE
bug: ion-picker cssClass not setting class to column

### ISSUE THREAD

**Issue by dkern** [ionic-team/ionic-framework#26653]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The `PickerColumn` interface has an option `cssClass`: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/picker/picker-interface.ts#L40

But this class is not set onto the rendered column. In the picker class I also can't find anything related to setting the class.
https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/picker/picker.tsx#L268

For the buttons (where `cssClass` is working correct) there is a deticated function for adding the class to the buttons.
https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/picker/picker.tsx#L259

I think something like `class={...getClassMap(c)}` is missing there.

### Expected Behavior

To render the `cssClass` option of `PickerColumn` in the column.

### Steps to Reproduce

Create a simple `ion-picker` and add a `cssClass` to any column.

```js
{
  // ...
  columns: [
    {
      name: 'custom-column',
      cssClass: 'custom-class',
      options: [
        // ...
      ],
    },
  ],
 }
```

### Ionic Info

Ionic:

   Ionic CLI       : 6.13.1 (C:\Users\daker\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.2.4

Capacitor:

   Capacitor CLI   : 4.0.1
   @capacitor/core : 4.1.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.7.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce the reported behavior.

Here is a dev build with a proposed fix if you are interested in testing it:

```
npm install @ionic/vue@6.5.1-dev.11674483857.1978274b @ionic/vue-router@6.5.1-dev.11674483857.1978274b
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26658, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue testing the dev build, and let me know if you run into any issues.
