### ISSUE TITLE
Ion range doul knobs NAN issue

### ISSUE THREAD

**Issue by GaneshSinghPapola** [ionic-team/ionic-framework#26657]
`@ionic/react": "^6.3.2"`
ionRange with dualKnobs giving NAN on lower and upper value

**Comment by liamdebeasi** [comment]
Hi there,

Please fill out the issue template. It exists so we can better verify and fix bugs. You can create a new bug report here: https://github.com/ionic-team/ionic-framework/issues/new?assignees=&labels=&template=bug_report.yml&title=bug%3A+

We are unable to verify the reported behavior without more information. Let me know if you have questions.
