### ISSUE TITLE
bug:  IonList Scrolling too fast 

### ISSUE THREAD

**Issue by zakuru** [ionic-team/ionic-framework#26655]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

While scrolling an IonList the scroll can go way too fast - native apps usually dont show that way

### Expected Behavior

Keep scrolling smooth regardless of the scroll speed momentum or give an option for it 

### Steps to Reproduce

Just use an IonList and scroll "fast" - Repo link to reproduce:
https://github.com/zakuru/ionic-playgroud

### Code Reproduction URL

https://github.com/zakuru/ionic-playgroud

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.4
   Ionic Framework : @ionic/react 6.3.7

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.6.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.16.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. Which device are you testing this on? Ionic does not control scrolling. The scrolling used in Ionic apps is the same scrolling that is used in traditional native apps (i.e. apps built with Kotlin/Swift and compiled to native binaries).

**Comment by zakuru** [comment]
Hi @liamdebeasi  I am using the android system webview version 108.0.5359.128
![Screenshot_20230123_210046_Settings.jpg](https://user-images.githubusercontent.com/171174/214058735-62d11dd1-f252-4e0d-8345-a585d76ef7aa.jpg)

![Screenshot_20230123_210051_Settings.jpg](https://user-images.githubusercontent.com/171174/214058795-36dc1aac-b3bf-4f1e-b374-e77cf584c6d6.jpg)

Phone samsunf s20 5G

**Comment by zakuru** [comment]
I will try tomorrow on pixel 4 and will let you know thanks

**Comment by zakuru** [comment]
hi @liamdebeasi  sorry for delay - tried many devices all same issue :( 
But very strange you don't reproduce from your side  - cause in the video you posted the scroll is too fast for an app - its smooth but too fast 
Benchmarking other apps on the market the scroll speed is always / most of the time under control - impossible to go faster than X 
This is the behavior we want

**Comment by liamdebeasi** [comment]
Do you have a video sample of what you are expecting to see? 

As I mentioned in https://github.com/ionic-team/ionic-framework/issues/26655#issuecomment-1400381878, Ionic does not control how scrolling works. This is implemented by the browser. If you think there is a bug in how scrolling is implemented, I recommend filing an issue with the browser vendor. In this case, that would be the Chromium team: https://bugs.chromium.org/p/chromium/issues/list

**Comment by liamdebeasi** [comment]
Also is the scrolling different than when you are scrolling on a website in Chrome for Android? (any website, not necessarily an Ionic app)

**Comment by zakuru** [comment]
Issue fixed closing it
