### ISSUE TITLE
bug: dismissing controller modal doesn't unmount inner component

### ISSUE THREAD

**Issue by a-Leong** [ionic-team/ionic-framework#26665]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Dismissing a controller modal does not trigger onUnmounted Vue lifecycle hook on the inner component. In my case there is init/deinit logic that occurs in modal inner component lifecycle hooks which isn't running as expected.

In reproduction repo you will notice opening a message mounts the first message, but subsequent modal presentations use the first component with its initalized data as opposed to remounting and reinitializing.

### Expected Behavior

As described in [ion-modal docs](https://ionicframework.com/docs/api/modal#mounting-inner-contents), controller modals should not persist the inner component across presentations. The inner component should unmount when the modal is dismissed.

### Steps to Reproduce

1. Present component in modal and dismiss modal.
2. Present modal again with the same component and different componentProps
3. Initial values from first modal presentation persist

Note the componentProps update as expected, however any initialization that occurs in `setup script` or lifecycle hooks fails to run.

### Code Reproduction URL

https://github.com/a-Leong/vue-modal-behavior

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.6 (/Users/****/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.5.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : not installed
   @capacitor/core    : 4.6.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.15.0 (/Users/****/.nvm/versions/node/v16.15.0/bin/node)
   npm    : 9.1.2
   OS     : macOS

### Additional Information

It's not clear to me whether this is expected behavior, however it contradicts my expectations based on the controller modal documentation. Is there a way to force the inner component to unmount on modal dismiss?

**Comment by liamdebeasi** [comment]
Thanks for the report. This appears to be the same as https://github.com/ionic-team/ionic-framework/issues/26644. The modal contents should unmount when dismissing the modal.

There is a dev build with a fix here: https://github.com/ionic-team/ionic-framework/issues/26644#issuecomment-1397738855. This fix should be available in the next patch release later this week.

I am going to close this since the code required to fix the issue has been completed, but let me know if you have any questions.

**Comment by a-Leong** [comment]
Perfect, thank you. I'll make a note to check closed issues in the future.
