### ISSUE TITLE
bug: ion-item click event is called twice

### ISSUE THREAD

**Issue by RRGT19** [ionic-team/ionic-framework#26671]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

After upgrading all my dependencies, the click event of the ion-item is called twice, sometimes...

Example:
![Logs](https://i.ibb.co/h96xngF/Screenshot-2023-01-24-at-3-14-24-PM.png)

```html
<ion-item button
            detail
            detailIcon="caret-down-sharp"
            (click)="callMe()">

    <ion-input [value]="value"
               [readonly]="true">
    </ion-input>

</ion-item>
```

Component:

```typescript
export class HomePage {

  value = 'Click me in the middle of the input';

  constructor() {}

  callMe() {
    console.log('Called...');
  }

}

```

Logs:
![Logs](https://i.ibb.co/XJqsypr/Screenshot-2023-01-24-at-3-10-37-PM.png)

### Expected Behavior

The click event should be fired only once.

### Steps to Reproduce

1. Configure a click event for the ion-item
2. Check the console logs

### Code Reproduction URL

https://github.com/RRGT19/Ionic-ion-item-click-event-test

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.8 (/Users/rob/.nvm/versions/node/v16.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.5.0
   @angular-devkit/build-angular : 15.1.1
   @angular-devkit/schematics    : 15.1.1
   @angular/cli                  : 15.1.1
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.6.2
   @capacitor/ios     : 4.6.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.18.1 (/Users/rob/.nvm/versions/node/v16.18.1/bin/node)
   npm    : 9.3.0
   OS     : macOS

### Additional Information

With older versions of the dependencies, I did not experience this problem. For example with these:

```

{
"dependencies": {
"@angular/cdk": "^14.2.6",
"@angular/common": "~14.2.9",
"@angular/core": "~14.2.9",
"@angular/fire": "^7.4.1",
"@angular/forms": "~14.2.9",
"@angular/platform-browser": "~14.2.9",
"@angular/platform-browser-dynamic": "~14.2.9",
"@angular/router": "~14.2.9",
"@capacitor/android": "^4.5.0",
"@capacitor/app": "^4.1.1",
"@capacitor/browser": "^4.1.0",
"@capacitor/core": "^4.5.0",
"@capacitor/device": "^4.1.0",
"@capacitor/geolocation": "^4.1.0",
"@capacitor/haptics": "^4.1.0",
"@capacitor/ios": "^4.5.0",
"@capacitor/keyboard": "^4.1.0",
"@capacitor/local-notifications": "^4.1.3",
"@capacitor/preferences": "^4.0.2",
"@capacitor/splash-screen": "^4.1.2",
"@capacitor/status-bar": "^4.1.0",
"@ionic/angular": "^6.3.8",
"rxjs": "^7.5.7",
"tslib": "^2.4.1",
"zone.js": "^0.11.8"
},
"devDependencies": {
"@angular-devkit/build-angular": "~14.2.8",
"@angular-eslint/builder": "14.1.2",
"@angular-eslint/eslint-plugin": "14.1.2",
"@angular-eslint/eslint-plugin-template": "14.1.2",
"@angular-eslint/template-parser": "14.1.2",
"@angular/cli": "~14.2.8",
"@angular/compiler": "~14.2.9",
"@angular/compiler-cli": "~14.2.9",
"@angular/language-service": "~14.2.9",
"@capacitor/cli": "^4.5.0",
"@ionic/angular-toolkit": "^7.0.0",
"@types/jasmine": "~4.3.0",
"@types/jasminewd2": "~2.0.10",
"@types/node": "^18.11.9",
"@typescript-eslint/eslint-plugin": "5.42.1",
"@typescript-eslint/parser": "5.42.1",
"eslint": "^8.27.0",
"eslint-plugin-import": "2.26.0",
"eslint-plugin-jsdoc": "39.6.2",
"eslint-plugin-prefer-arrow": "1.2.3",
"jasmine-core": "~4.5.0",
"jasmine-spec-reporter": "~7.0.0",
"karma": "~6.4.1",
"karma-chrome-launcher": "~3.1.1",
"karma-coverage": "~2.2.0",
"karma-coverage-istanbul-reporter": "~3.0.3",
"karma-jasmine": "~5.1.0",
"karma-jasmine-html-reporter": "^2.0.0",
"protractor": "~7.0.0",
"ts-node": "~10.9.1",
"typescript": "^4.8.4"
},
}
```

**Comment by liamdebeasi** [comment]
Thanks for the report. I am not able to reproduce the reported behavior. Which devices/browsers does this reproduce on? Also, is there a version of Ionic where this behavior does not occur?

**Comment by RRGT19** [comment]
Hi @liamdebeasi,

Thanks for your reply.

I'm testing on Google Chrome Version 109.0.5414.119 (Official Build) (arm64). On mobile, Galaxy A52s with Android 12.

The version I had of ionic was `6.3.8` with angular `14`. With these versions, I didn't have this problem. Now, with angular `15` and the latest version of ionic, I experience the inconvenience. It makes me think that the problem came with the angular 15, but I'm not sure.

See recording:

![](https://streamable.com/e/ce8n4f)

This recording is using the code reproduction that I have provided.

**Comment by RRGT19** [comment]
I have tried it using angular 14.2.8 and ionic 6.5.0 and the issue is still present. Maybe my Google chrome version is the guilty?

I have tried using Safari 16.2 and is working good.

**Comment by liamdebeasi** [comment]
Does the issue reproduce if you downgrade Ionic to v6.0.0?

```
npm install @ionic/angular@6.0.0
```

**Comment by RRGT19** [comment]
@liamdebeasi 

Using the `6.0.0 `and Angular `14.2.8 | 15.0.0`, I received the following error in console logs:

```

src_app_home_home_module_ts.js:2 ERROR Error: Uncaught (in promise): TypeError: resolver.resolveComponentFactory is not a function
TypeError: resolver.resolveComponentFactory is not a function
    at IonRouterOutlet.activateWith (ionic-angular.js:3371:38)
    at ActivateRoutes.activateRoutes (router.mjs:3023:40)
    at router.mjs:2972:18
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (router.mjs:2971:29)
    at ActivateRoutes.activateRoutes (router.mjs:3030:22)
    at router.mjs:2972:18
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (router.mjs:2971:29)
    at ActivateRoutes.activate (router.mjs:2885:14)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at core.mjs:23999:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23999:36)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Object.onInvokeTask (core.mjs:24300:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
```

I have tried from 6.0.0 to 6.1.0, one by one, still no luck....

**Comment by liamdebeasi** [comment]
My apologies. Angular 14 support started in Ionic 6.1.9.

Are you able to isolate this test case a bit more? In particular, it would be good to find a way to consistently reproduce the issue.

**Comment by RRGT19** [comment]
Angular 14 and Ionic 6.1.9 [issue is present]
Angular 13.0.0 and Ionic 6.0.0 [issue is present] (dependencies borrowed from https://github.com/ionic-team/starters/blob/21b734082df7f1a6b06723bd8264f86b62bbb7d0/angular/base/package.json)

Don't know what else to test. Should I test with lower versions of Ionic and Angular?

**Comment by liamdebeasi** [comment]
You mentioned that this issue only reproduce sometimes. Can you find a way to reproduce the issue consistently?

**Comment by RRGT19** [comment]
I have found a way that triggers the issue all the time, it's a little weird thought.

Look at this image:

![Logs](https://i.ibb.co/h96xngF/Screenshot-2023-01-24-at-3-14-24-PM.png)

The detail icon at the right side, using Google Chrome and an Android device for example Samsung Galaxy S20 Ultra, if you click right above the icon, the click event fires just once. All good here.

But, if you click above the ion-input, the click event is always fired twice (the first time within that browser tab). Is weird because for the event to fire twice, you need to refresh the browser tab to reset everything. If you continue to click the ion-input for a second time, in the same tab/session, the event just fires once. The -twice- thing happens just the first time you click on it.

See recording:
https://streamable.com/zarzsq

**Comment by amandaejohnston** [comment]
Hello and thank you again for the issue. I am also unable to reproduce the behavior, unfortunately. I've tried clicking in various places on the item and input, refreshing the browser each time. I'm using the same Chrome version as you. Recording: https://user-images.githubusercontent.com/90629384/217285608-0edc87a1-de89-4721-9edd-2c76c7267623.mp4

The recording you linked is no longer available. Would you be able to re-upload it?
