### ISSUE TITLE
bug: v7 input, do not show highlight in item

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-framework#26687]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

The underlines that appear when focused do not extend the full width.

![66c0babb10716b38fcc9b6a1d6132d04](https://user-images.githubusercontent.com/9690024/214779956-613fd44d-f907-44fc-98e6-afee900b4a86.gif)

### Expected Behavior

Same behavior as when using ion-label

### Steps to Reproduce

```
<ion-list lines="full">
  <ion-item>
    <ion-input type="text" label="New Label" labelPlacement='fixed'></ion-input>
  </ion-item>
  <ion-item>
    <ion-label position="fixed">Old Label</ion-label>
    <ion-input type="text"></ion-input>
  </ion-item>
</ion-list>
```

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.0-beta.0
   @angular-devkit/build-angular : 15.1.2
   @angular-devkit/schematics    : 15.1.2
   @angular/cli                  : 15.1.2
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : not installed
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v18.12.1 (/usr/local/bin/node)
   npm    : 8.19.3
   OS     : macOS
```

**Comment by liamdebeasi** [comment]
Thanks for testing the v7 beta! This is indeed a bug. However, the MD highlight should not be shown using the inputs in `ion-item`. I will work on a fix for this.

**Comment by liamdebeasi** [comment]
I should also note that v6 does show the highlight when used in an item, but this is not correct. As an example, here is what the non-filled inputs look like in Gmail for Android:
![Screenshot_20230126-085319](https://user-images.githubusercontent.com/2721089/214853163-fcb9565c-57bd-4a8b-a884-ae952ad49a98.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26689, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by rdlabo** [comment]
Thanks for the quick fix!😁
