### ISSUE TITLE
ion-input type=number  Setting Max and min does not take effect

### ISSUE THREAD

**Issue by MarkGaozhq** [ionic-team/ionic-framework#26691]
Setting Max and min does not take effect

**Comment by amandaejohnston** [comment]
Hello, and thanks again for the issue. If this is still a problem you are running into, could you provide a minimal reproduction we can use? Can you also confirm if this still happens on the latest version of Ionic?

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue in the `ionic-framework` repo and ensure the template is fully filled out. Thank you!
