### ISSUE TITLE
bug: warning on ionic/core  '@utils/logging' 

### ISSUE THREAD

**Issue by Scan0815** [ionic-team/ionic-framework#26704]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

on stencil (3.0.0) building with ionic/core (6.5.1) 

Bundling Warning UNRESOLVED_IMPORT
           '@utils/logging' is imported by ./node_modules/@ionic/core/dist/collection/components/popover/popover.js,
           but could not be resolved – treating it as an external dependency

### Expected Behavior

the warning is not displayed in the console

### Steps to Reproduce

Include @ionic/core in a Stencil app

### Ionic Info

Ionic:

   Ionic CLI : 6.20.4

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v19.0.0
   npm    : 9.1.2
   OS     : Linux 5.11

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26705, and a fix will be available in an upcoming release of Ionic Framework.
