### ISSUE TITLE
bug: v7 vue v-model not updating until input is blurred

### ISSUE THREAD

**Issue by MimyyK** [ionic-team/ionic-framework#26700]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

Hello,
I have a question about v7-beta with Vue, I did a test and it seems that the `v-model` doesn't work like before (v6.5.1).
With v6.5.1, when the user is writing in a `ion-input` it was updating my variable directly, with v7-beta, the user has to leave the field in order to update my variable.

If I replace `v-model` with `:value="myFieldValueOnInput" @input="event => myFieldValueOnInput = event.target.value"` it works.

Here is a video to see the current behavior:

https://user-images.githubusercontent.com/1482715/215501341-b60ac654-dfbc-4301-8f92-4f40fd9d101f.mov

It leads to undesired behavior from my point of view where a user have to leave the input focus to get the expected behavior from the form (when I want to know if my form is valid):

https://user-images.githubusercontent.com/1482715/215510306-44265ca3-80ba-4140-96cc-7ea13378a9fd.mov

### Expected Behavior

I'm not sure if this is a bug, maybe it's an expected change? But it seems to me that the `v-model` should update my variable.

### Steps to Reproduce

- Open the Vue devtools
- Enter text in the field with `v-model` without leaving the field -> you can see in the devtools that the variable is not updated
- Click outside the field -> you can see in the devtools that the variable is now updated

### Code Reproduction URL

https://github.com/MimyyK/test-ionic-v7

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.6 
   Ionic Framework : @ionic/vue 7.0.0-beta.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : not installed
   @capacitor/core    : 4.6.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1
   npm    : 9.2.0
   OS     : macOS

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this bug. The problem here is we need to listen for `ionInput` to update the `v-model` binding instead of `ionChange`. We updated `ionChange` to only fire when the value of the input is committed by the user (via a blur) in order to align with `<input />`. I will work on a fix for this.

**Comment by liamdebeasi** [comment]
Here is a dev build with a proposed fix if you are interested in testing:

```
npm install @ionic/vue@7.0.0-dev.11677608949.16e25264 @ionic/vue-router@7.0.0-dev.11677608949.16e25264
```

**Comment by MimyyK** [comment]
Hello,
Thanks for the fix, it works well! 👍🏻

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26876, and a fix will be available in an upcoming release of Ionic Framework.
