### ISSUE TITLE
bug: ionicons md/ios props are not reactive

### ISSUE THREAD

**Issue by fbrun** [ionic-team/ionic-framework#26712]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

Prop binding on `ion-icon` name was resolved on ticket [18707](https://github.com/ionic-team/ionic-framework/issues/18707), but it's not possible to do same thing with attributes `md` and `ios`.

```
<ion-button (click)="isPlaying ? onPause() : onPlay()" fill="clear" class="base-btn solid-btn">
	<ion-icon slot="icon-only" [ios]="isPlaying ? 'pause-outline' : 'play-outline'" [md]="isPlaying ? 'pause-sharp' : 'play-sharp'"></ion-icon>
</ion-button>
```

### Expected Behavior

When binding is updated, ion-icon must update `ios` / `md` attributes values

### Steps to Reproduce

See [demo](https://stackblitz.com/edit/angular-3qteob?file=src%2Fapp%2Fexample.component.html)

### Code Reproduction URL

https://stackblitz.com/edit/angular-3qteob?file=src%2Fapp%2Fexample.component.html

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.8
   Ionic Framework               : @ionic/angular 6.5.0
   @angular-devkit/build-angular : 14.2.10
   @angular-devkit/schematics    : 14.2.10
   @angular/cli                  : 14.2.10
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.6.2
   @capacitor/ios     : 4.6.2

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.17.0
   npm    : 8.15.0
   OS     : Linux 5.15

```

**Comment by liamdebeasi** [comment]
Thanks for the report. I can verify this behavior. Here is a dev build if you would like to test the proposed fix:

```
npm install @ionic/angular@6.5.3-dev.11675347661.18d86784
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionicons/pull/1174. This fix will be available in an upcoming release of Ionicons.

**Comment by fbrun** [comment]
Thanks for the resolved. I try under `@ionic/angular@6.5.3-dev.11675347661.18d86784`, it's ok !
