### ISSUE TITLE
bug: Refresher with custom scroll target does not assign overflow styles to scroll container

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#26725]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

The `ion-refresher` usage in MD mode with a custom virtual scroll target, does not set the correct overflow styles to the scroll container. 

Currently, `ion-refresher` in MD mode expects to be used with `ion-content` and assigns the CSS variables that Ionic uses for the scroll container overflow styles: `--overflow`. 

https://github.com/ionic-team/ionic-framework/blob/9c95d370b81809939cbc641481932199a879329d/core/src/components/refresher/refresher.tsx#L356

### Expected Behavior

If `ion-refresher` is being used with a custom scroll target, it should assign the `overflow` styles directly, instead of using the CSS variables. The CSS variables should only be used with the `ion-content` usage, with the built-in scroll container. 

### Steps to Reproduce

1. Use `ion-refresher` with a custom scroll target
2. In MD mode, inspect the scroll target
3. Perform a pull to refresh
4. Observe: `--overflow` styles are applied to the scroll container, but this does not impact the container's overflow styling. 

### Ionic Info

N/A

### Additional Information

Related to: https://github.com/ionic-team/ionic-framework/pull/26613

**Comment by liamdebeasi** [comment]
This was fixed in https://github.com/ionic-team/ionic-framework/pull/27058
