### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/ionic-framework#26724]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

Modal displays on desktop, but when ran in android studio only the overlay can be seen, no actual time component

### Expected Behavior

time component is functional and visible

### Steps to Reproduce

rendering the modal as follows:

`<ion-modal [keepContentsMounted]="true">
  <ng-template>
    <ion-datetime
    id="datetime"
    size="cover"
    prefer-wheel="true"
    presentation="date"
    locale="sv-SE"
    value="{{defaultDOB}}"
    [(ngModel)]="defaultDOB"
    [showDefaultButtons]="true"            
    doneText="done"
    cancelText="cancel"  
    >
  </ion-datetime>
  </ng-template>
</ion-modal>`

and using this to trigger it 

`  <ion-datetime-button #dobPicker id="dobPicker"  datetime="datetime"></ion-datetime-button>  `

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (/Users/svoboda/.nvm/versions/node/v16.19.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.4.0
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI   : 4.6.1
   @capacitor/core : 4.6.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 1.7.1

System:

   Android SDK Tools : 26.1.1 (/Users/svoboda/Library/Android/sdk)
   NodeJS            : v16.19.0 (/Users/svoboda/.nvm/versions/node/v16.19.0/bin/node)
   npm               : 8.19.3
   OS                : macOS Monterey
   Xcode             : Xcode 14.2 Build version 14C18

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
