### ISSUE TITLE
bug: see https://github.com/ionic-team/ionic-framework/issues/25301#issue-1239169263

### ISSUE THREAD

**Issue by gterminator** [ionic-team/ionic-framework#26720]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [X] v5.x
- [X] v6.x
- [X] v7.x
- [X] Nightly

### Current Behavior

see https://github.com/ionic-team/ionic-framework/issues/25301#issue-1239169263

### Expected Behavior

see https://github.com/ionic-team/ionic-framework/issues/25301#issue-1239169263

### Steps to Reproduce

see https://github.com/ionic-team/ionic-framework/issues/25301#issue-1239169263

### Ionic Info

see https://github.com/ionic-team/ionic-framework/issues/25301#issue-1239169263

### Additional Information

see https://github.com/ionic-team/ionic-framework/issues/25301#issue-1239169263

AND Please this time not a statement that this is "already handled". It's not. 
There is a architectural flaw in the implementation my last bugticket is no.1 in google and many people asking me how I solved it.

**Comment by liamdebeasi** [comment]
Hi there,

Can you please provide a GitHub repo with the minimal amount of code required to reproduce this issue? The original ticket does not have a reproduction case, so it is hard to say where this issue is coming from.
