### ISSUE TITLE
bug: Ion toast needs a ::part on the toast-content to fix a overflowing issue 

### ISSUE THREAD

**Issue by SaroGFX** [ionic-team/ionic-framework#26723]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

When there is a long string inside of an IonToast, it will overflow the toast. There is no way to fix this issue because the `<div class="toast-content"></div>` is in the shadow dom and doesn't have a part attribute. 

![Screenshot 2023-02-02 at 10 18 59](https://user-images.githubusercontent.com/3781800/216287740-999d92bb-347e-4140-96cb-77ae88ae22e8.png)

### Expected Behavior

- The toast content should also have a ::part. 
- The toast should not be able to overflow. The toast-content needs a property of `min-width: 0` instead of the default `min-width: auto`

![Screenshot 2023-02-02 at 10 39 22](https://user-images.githubusercontent.com/3781800/216287926-845299ec-1ff8-4e39-9fde-3b55c74c3490.png)

### Steps to Reproduce

1. Add a toast message
2. Add a very long string without spaces. 

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.2.7

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.1) : 1.6.0

System:

   NodeJS : v16.14.0 (/usr/local/bin/node)
   npm    : 8.3.1
   OS     : macOS

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please provide a reproduction case? I am unable to reproduce this locally: https://codepen.io/liamdebeasi/pen/ZEjVOwG

**Comment by SaroGFX** [comment]
Hi @liamdebeasi ,

It happens when the text does not have any spaces in between. In our use case, we are showing a user file name, which therefor can be very long. 

https://codepen.io/SaroGFX/pen/zYLyZOo

**Comment by liamdebeasi** [comment]
You can target the `message` Shadow Part to specify how text should wrap:

```css
ion-toast::part(message) {
  overflow-wrap: anywhere;
}
```

**Comment by SaroGFX** [comment]
Aha, thanks, perfect. Didn't know about this property, and it addresses the issue.
