### ISSUE TITLE
bug: Ionic 6 angular 15 ssr not working , is platform server not working

### ISSUE THREAD

**Issue by khaled-elrifaay** [ionic-team/ionic-framework#26721]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

  detectAds() {
        if (isPlatformServer(this.platformId)){
            console.log("platform server detectAds")
        }else{
            return detectAnyAdblocker();
        }
    }
    
    return Error: export 'detectAnyAdblocker' (imported as 'detectAnyAdblocker') was not found in 'just-detect-adblock' (possible exports: default)

### Expected Behavior

not access client side 

### Steps to Reproduce

ng run app:serve-ssr

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.4.1
   @angular-devkit/build-angular : 15.0.4
   @angular-devkit/schematics    : 15.0.4
   @angular/cli                  : 15.0.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.17.0 (/usr/local/bin/node)
   npm    : 8.15.0
   OS     : macOS
   Xcode  : Xcode 14.2 Build version 14C18

### Additional Information

error appears to me : 
1- Generating browser application bundles (phase: building)...this.debug is not a function
2- self is not defined

**Comment by liamdebeasi** [comment]
Thanks for the report. The error you included does not appear to come from Ionic:

> return Error: export 'detectAnyAdblocker' (imported as 'detectAnyAdblocker') was not found in 'just-detect-adblock' 

`just-detect-adblock` is not a package that we maintain.
