### ISSUE TITLE
bug: ability to override platform detection methods does not work as expected

### ISSUE THREAD

**Issue by expcapitaldev** [ionic-team/ionic-framework#26727]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

if I use https://ionicframework.com/docs/angular/platform with
import { IonicModule } from '@ionic/angular';

@NgModule({
  ...
  imports: [
    BrowserModule,
    IonicModule.forRoot({
      platform: {
        /** The default `desktop` function returns false for devices with a touchscreen.
        * This is not always wanted, so this function tests the User Agent instead.
        **/
        'desktop': (win) => {
// for testing only
          return true;
        },
        'ios': (win) => {
// for testing only
          return false;
        },
mode: 'ios',
      },
    }),
    AppRoutingModule
  ],
  ...
})

+ with
```
providers: [
{
			provide: APP_INITIALIZER,
			useFactory: initializeApp,
			deps: [Platform, appInitializerToken],
			multi: true,
		},]
...

function initializeApp (platform, initService) {
return () => {return platform.ready().then(() => service.start()) }; 
}
```

and If I will call in project isPlatform('desktop'); or this.platform.is('desktop') in chrome browser with mobile view in dev tools every time I will have is `false` but ios is true

### Expected Behavior

how it works correctly that MR https://github.com/ionic-team/ionic-framework/commit/45cabae04bf9236cd069793fbf2ac8f68c372cc3 if we can not override platform detection.
override platform detection should work correctly

### Steps to Reproduce

see my config above

### Ionic Info

"@ionic/angular": "6.5.0",
"@ionic/core": "6.5.0",

### Additional Information

maybe better to update documentation with correctly example for https://ionicframework.com/docs/angular/platform#customizing-platform-detection-functions, and  it is not really good test for 'override platform detection' https://github.com/ionic-team/ionic-framework/commit/45cabae04bf9236cd069793fbf2ac8f68c372cc3#diff-caa8868a8b258d6dc46bea6fea71379b9cc017af0cc9b2af863d599ca72802e1R149

**Comment by liamdebeasi** [comment]
Hey there,

Do you have a sample app I can run? I'm not sure I fully understand what the bug is here.

**Comment by expcapitaldev** [comment]
issue with 
```
{
			provide: APP_INITIALIZER,
			useFactory: initializeApp,
			deps: [appInitializerToken],
			multi: true,
		},
```
if you provide APP_INITIALIZER => override platform detection methods does not work

**Comment by liamdebeasi** [comment]
Are you able to reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by expcapitaldev** [comment]
yep easy. see https://stackblitz.com/edit/ionic6-angular13-5df3h4?file=src/app/app.module.ts
pls check console.log ,only if I will try to call platform.is('any') in initializeApp function you will have unexpected case
also, see video
If I will ask only `platform.is` after that I will have unexpected response

https://user-images.githubusercontent.com/19390317/216758374-a0f9ea88-9706-4db5-8d98-59f8029e02e9.mp4

<img width="802" alt="Ionic 6 Angular 13 (forked) - StackBlitz 2023-02-04 09-54-08" src="https://user-images.githubusercontent.com/19390317/216758413-fd491eb1-2e57-4949-9371-4fda317c01f3.png">

**Comment by liamdebeasi** [comment]
Thanks for the additional information. I can reproduce the reported behavior, but this does not appear to be a bug in Ionic. Your `platform.is` code in `initializeApp` is running before Ionic has been setup. During this setup, we apply the results of your custom `platform` config. Since your code is running before this setup has completed you are getting the default platform detection implementation.

Additionally, we cache the results of platform detection. This means that running `platform.is('ios')` in `app.component.ts` will return the cached result that was computed in `initializeApp`. The `platform.ready` method is misleading as it is a legacy method to ensure that Cordova is ready. If you are not using Cordova then you do not need to use this method.

**Comment by expcapitaldev** [comment]
thank you for feedback. platform.ready() do not connect to our issue but thanks for updates .
Problem that you can not check what is platform now while initializeApp because our config will be provided later. Of course we can update logic for that .For example do not cache while `app initializing` looks like it is easy fix, what do you think?

**Comment by liamdebeasi** [comment]
Can you clarify why you need to do platform detection when initializing the app before Ionic is configured?

**Comment by expcapitaldev** [comment]
it is business issue, if you want to understand and get information from native part about: date time pattern/ wallet pattern/ check any information from native part (you need to understand is it cordova  ios or android and etc) prepare some data, after that show only user can work for UI. How you can start with APP_INITIALIZER it you can not understand what  is kind of platform now?

**Comment by liamdebeasi** [comment]
Are you able to do this work in `app.component.ts`? Alternatively, if you need to do this work in `app.module.ts` can you reference the platform methods in a variable? Something like this:

```typescript
import { IonicModule } from '@ionic/angular';

const isIOS = () => {

  // Stubbed function
  // Replace this with your implementation/
  return true;
}

@NgModule({
  imports: [
    IonicModule.forRoot({
      platform: {
        ios: isIOS,
      },
    }),
  ],
  ...
})

export function initializeApp(): () => Promise<string> {
  return (): Promise<string> => {
    if (isIOS()) {
      return Promise.resolve('ios');
    } else {
      return Promise.resolve('android');
    }
  };
}
```

The problem here is that you are trying to use your customized platform detection methods before they have been set. This an app-level issue, not an Ionic bug.
