### ISSUE TITLE
HTMLIonAlertElement inside HTMLIonModalElement not working on iOS

### ISSUE THREAD

**Issue by Keelback** [ionic-team/ionic-framework#26730]
I am using the new ionic 6 Controller Modal Dialog. In my Component (that is used for the modal Dialog) I have a button that is used to show an alert (AlertController). On Android an Web everything works fine. On iOS (15.7.3) the Alert Dialog is not shown.

```
public async openModal(  ): Promise<void> {
    let modal: HTMLIonModalElement;
      modal = await this.modalController.create({
        component: AlertComponent,
        canDismiss: true,
        initialBreakpoint: 0.85,
      });
    modal.present();
  }
```

The code when pressing the button inside the modal Component (AlertComponent):
```
public async showAlert(): Promise<void> {
    const alert: HTMLIonAlertElement = await this.alertController.create({
      header: 'Attention',
      message:
        'Doesn't matter.',
      buttons: [
        {
          text: 'OK',
        },
      ],
    });
    await alert.present();
  }
```

**Comment by liamdebeasi** [comment]
Hi @Keelback, Please fill out the template as it helps us triage issues faster: https://github.com/ionic-team/ionic-framework/issues/new?assignees=&labels=&template=bug_report.yml&title=bug%3A+

Also, if you can attach a runnable app with the bug reproduced that would be great. Let me know if you have any questions.
