### ISSUE TITLE
bug: ion-datetime is not reflecting min Immediately  

### ISSUE THREAD

**Issue by HiteshDutt** [ionic-team/ionic-framework#26734]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

I am trying to use ion-datetime for considering input (startDate, Enddate). I am setting min property as well to restrict user.
there is toggle to change between options to have hourly selection or daily selection. [daily selection is not an issue].
the min date time is working good for startDate, but for endDate the min date get into effect during scroll.

adding screens:
![image](https://user-images.githubusercontent.com/14161283/216759328-8f863255-3d7d-4a9d-8ec3-c009104cad8a.png)
screen loaded with endDate having time 15:00, this is also the min value for endDate

if endDate minutes are scrolled, few extra values can be seen (adding image)
![github_ionic_2](https://user-images.githubusercontent.com/14161283/216759550-c449f812-a820-42a1-bbf0-c282c53cbf6b.jpg)

just while scrolling the popup goes down and values are fixed
![image](https://user-images.githubusercontent.com/14161283/216759538-0fc53daf-3b4f-4762-ae64-518675788560.png)

### Expected Behavior

min date for EndDate should reflect the him date on screen as soon as data loading is finished.

 

### Steps to Reproduce

HTML CODE:
 <ion-item>
      <ion-label position="stacked" color="primary">Start Date</ion-label>
      <ion-datetime-button datetime="startDatetime"></ion-datetime-button>
      <ion-modal [keepContentsMounted]="true" #startDateTime>
        <ng-template>
          <ion-datetime [(ngModel)]="startDate" name="startDate" presentation="time-date" id="startDatetime"
            [min]="startDateMin" [hourValues]="getHourValues()" minuteValues="0" (ionChange)="startDateChange()"
            hourCycle="h23"></ion-datetime>
        </ng-template>
      </ion-modal>
    </ion-item>
    <ion-item>
      <ion-label position="stacked" color="primary">End Date</ion-label>
      <ion-datetime-button datetime="endDatetime"></ion-datetime-button>
      <ion-modal [keepContentsMounted]="true" #endDateTime>
        <ng-template>
          <ion-datetime [(ngModel)]="endDate" name="endDate" presentation="time-date" id="endDatetime"
            [min]="endDateMin" [hourValues]="getHourValues()" minuteValues="0" (ionChange)="cancel()"
            hourCycle="h23"></ion-datetime>
        </ng-template>
      </ion-modal>
    </ion-item>
    
   TS Code:
   startDate: string = this.setDateTime(0,0,10).replace("Z", "");
  endDate: string = this.setDateTime(1,0,10).replace("Z", "");
  startDateMin: string = this.setDateTime(0,0,10).replace("Z", "");
  endDateMin: string = this.setDateTime(1,0,10).replace("Z", "");
  
  setDateTime(addDays: number, addHours: number, setHours?: number){
    let date = new Date();
    date.setMinutes(0,0,0);
    let returnVal  = this.dateTime.getDateTimeinIsoFormat(date, addDays, setHours, addHours);
    return returnVal;
  }
  
  getHourValues(): string{
    if(this.hourlyBooking){
    return "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23";
    }
    else{
      return "10"
    }
  }

toggleChange() {
    if (this.hourlyBooking) {
      this.endDate = this.setDateTime(0,1,null).replace("Z", "");
      this.endDateMin = this.setDateTime(0,1,null).replace("Z", "");    
      this.startDate = this.setDateTime(0,0,null).replace("Z", "");
      this.startDateMin = this.setDateTime(0,0,null).replace("Z", "");
      
    }
    else {
      this.startDate = this.setDateTime(0,0,10).replace("Z", "");
      this.startDateMin = this.setDateTime(0,0,10).replace("Z", "");
      this.endDate = this.setDateTime(1,0,10).replace("Z", "");
      this.endDateMin = this.setDateTime(1,0,10).replace("Z", "");
    }
  }
  
  
  

### Ionic Info

Ionic:

   Ionic CLI : 6.20.1

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v14.18.0
   npm    : 8.17.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
