### ISSUE TITLE
bug: ion-content fullscreen --offset-top not recalculated after rotate

### ISSUE THREAD

**Issue by digaus** [ionic-team/ionic-framework#26743]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

When displaying a page on iOS in  landscape mode and then rotate to portrait, the --offset-top is not recalculated so we get a black bar and not the content background on the top 

### Expected Behavior

Recalculate --offset-top when rotating

### Steps to Reproduce

```
<ion-header></ion-header>
<ion-content [fullscreen]= "true" style="--background: red"></ion-content>
```

This should display fullscreen red background on iOS when rotating from landscape to portrait (have to open the page while in landscape mode to see the effect).

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.5
   Ionic Framework               : @ionic/angular 6.5.2
   @angular-devkit/build-angular : 14.1.0
   @angular-devkit/schematics    : 14.1.0
   @angular/cli                  : 14.1.0
   @ionic/angular-toolkit        : not installed

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.14.0 
   npm    : 8.3.1
   OS     : macOS

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you reproduce this in an Ionic starter app and provide a link to the repo?

**Comment by digaus** [comment]
You need to test on iOS because of androids issue (can prevent it with another plugin but its easier to test on ios):
So the root is in this issue: https://github.com/ionic-team/capacitor/issues/2840

Now it seems that the calculation of the offset is only done on `appload` event or when initializing the `ion-content`

https://github.com/ionic-team/ionic-framework/blob/2707289b36883ae495f86cfb2f2b6c84e090551b/core/src/components/content/content.tsx#L109

I was able to fix it by adding this to my app:

```
           window.addEventListener('resize', () => {
                window.dispatchEvent(new Event('appload'));
            })
```

However this event should be handled by the `ion-content` itself

Here is the issue reproduced with starter app: https://github.com/digaus/toolbar-test

To test it: Open App -> rotate landscape -> navigate to me `view-message` page -> rotate portrait
![Screen Shot 2023-02-07 at 13 39 27](https://user-images.githubusercontent.com/15358538/217247467-518d1190-ac16-4e2a-b139-24569384188e.png)

![Screen Shot 2023-02-07 at 13 38 03](https://user-images.githubusercontent.com/15358538/217247269-66790170-3a2a-4a46-a886-f892b563e2d3.png)

![Screen Shot 2023-02-07 at 13 39 17](https://user-images.githubusercontent.com/15358538/217247437-8fe79bc2-1a68-42fa-ac18-38022fd3d4de.png)

**Comment by liamdebeasi** [comment]
Thanks! I can reproduce this behavior. Here is a dev build if you would like to test the proposed fix:

```
npm install @ionic/angular@6.5.4-dev.11676042504.1f4b8b02
```

**Comment by greg-md** [comment]
@liamdebeasi the same issue happens when you leave a tab and then get back to it. Can it be fixed as well?
