### ISSUE TITLE
bug: ionRefresh emits object typed as RefresherEventDetail but actually emits RefresherCustomEvent

### ISSUE THREAD

**Issue by Tommertom** [ionic-team/ionic-framework#26747]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

The tsx to ion-refresher specifies it emits RefresherEventDetails:
`  @Event() ionRefresh!: EventEmitter<RefresherEventDetail>;` 

this exposes the `complete` method to the user to complete the refreshing.

So this would mean something like this needs to work:

(pseudo code)
`on:ionRefresh={refresher}` where `refresher` would be like `function refresher(ev:RefresherEventDetails) {.. ev.complete() }`

This code complies to typings, but will give a runtime error as the correct way is `ev.target.complete()`. 

But that that will give a typings error in the IDE. 

Changing to
`function refresher(ev: RefresherCustomEvent) {.. ev.target.complete() }` will fix this, but gives IDE errors because of type mismatch.

The workaround is to remove typings or use any keyword.

Notably the docs state that you must use  `complete()` where the code example say `target.complete()`. So if you take things very literally, it could become confusing and error prone.

![image](https://user-images.githubusercontent.com/16119174/217286875-f6a5c434-dca3-44d1-9937-0d627c11d2fc.png)
(meaning you need to bind to the ion-refresher component and then call its `complete()` method)

![image](https://user-images.githubusercontent.com/16119174/217286726-fd625ab7-09d8-48c2-abe6-5ba859ec27fb.png)
(take the event object and call `ev.target.complete()`.

So possibly a documentation improvement (happy to do PR) but maybe a code fix in refresher.tsx? 

### Expected Behavior

No runtime issue when calling `ev.complete()` or no typings error when using type on the `ionRefresh` event.

### Steps to Reproduce

See above

### Code Reproduction URL

None available - the code examples on ion-refresher have the issue

### Ionic Info

Occurs in angular project: 
Ionic:

   Ionic CLI                     : 6.20.6 (C:\Users\xxxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.5.2
   @angular-devkit/build-angular : 15.1.4
   @angular-devkit/schematics    : 15.1.4
   @angular/cli                  : 15.1.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.3
   @capacitor/android : not installed
   @capacitor/core    : 4.6.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.10.0
   OS     : Windows 10

And also ionic svelte (no ionic info)

### Additional Information

https://discordapp.com/channels/520266681499779082/1049388501629681675/1072243939635122187

https://github.com/ionic-team/ionic-framework/issues/20221

**Comment by liamdebeasi** [comment]
Thanks for the report. The correct type is `RefresherCustomEvent` because of how the custom event payload is formatted:

```javascript
{
  target: ...,
  detail: {
    complete: () => { ... }
  },
  ...
}
```

Both `ev.target.complete()` and `ev.detail.complete()` are correct since `ev.target` is `ion-refresher`. We happen to also provide the `complete` method in the `detail` payload. However, there are some slight typing differences due to https://github.com/ionic-team/ionic-framework/issues/24245.

**Comment by Tommertom** [comment]
So that means the refresher.tsx code needs to be changed?

`  @Event() ionRefresh!: EventEmitter<RefresherCustomEvent> ;`

possibly giving a type error on line 701?

```
 this.ionRefresh.emit({
      complete: this.complete.bind(this),
    });
```

**Comment by liamdebeasi** [comment]
No, the code is correct. `EventEmitter<RefresherEventDetail>` means that the event will emit a event of type `CustomEvent<RefresherEventDetail>`.

We ship a `RefresherCustomEvent` interface which extends `CustomEvent` and explicitly types the `target` field. This was done so developers can do `ev.target.complete()`. If we did not add that explicit type then TypeScript would say that `complete` is not a method on `HTMLElement`.

**Comment by Tommertom** [comment]
Ok - will put two code examples here in coming minutes. Angular and Svelte - with the errors. For me to understand what I need to fix in the code and/or the typings definition which now says. ` "on:ionRefresh"?: (event: RefresherEventDetail) => void;`

**Comment by Tommertom** [comment]
Svelte issue:

![image](https://user-images.githubusercontent.com/16119174/217307313-bfbee003-4ba5-4c33-a632-7a9253e37bae.png)

Typescript error, but working runtime. 

![image](https://user-images.githubusercontent.com/16119174/217307486-92fee927-7ab8-4982-b48b-f8c921252f6f.png)

No typescript error, but runtime error (ev.prompt() does not exist)

![image](https://user-images.githubusercontent.com/16119174/217307702-3681cac3-b29d-4740-bdc2-f98aaffab25e.png)


Typescript error different place, but no runtime error.

Angular:
Explicit typing in receiving function
![image](https://user-images.githubusercontent.com/16119174/217308495-1ed0a05f-5773-490b-8dbb-d7c9a9904a0f.png)

Will not compile -  `Error: src/app/home/home.page.html:8:59 - error TS2345: Argument of type 'Event' is not assignable to parameter of type 'RefresherCustomEvent'.
[ng]   Type 'Event' is missing the following properties from type 'RefresherCustomEvent': detail, initCustomEvent
[ng]
[ng] 8   <ion-refresher slot="fixed" (ionRefresh)="handleRefresh($event)">`

Changing typing gives typescript error in TS file:
![image](https://user-images.githubusercontent.com/16119174/217308882-c72aefe3-1d89-4eb4-a2bd-fb7404c541e5.png)

And this also fails to compile:

![image](https://user-images.githubusercontent.com/16119174/217309077-f1f714f2-3e13-44de-b381-f6b208f6de66.png)

All issues can be avoided by not typing the receiving function. As per example in documentation. 

So question is how to get explicit typings working in the angular version. And maybe a suggestion for the svelte one?

**Comment by liamdebeasi** [comment]
Do you have a sample app I can try? It's hard to understand what is going on here from only screenshots.

> Will not compile - Error: src/app/home/home.page.html:8:59 - error TS2345: Argument of type 'Event' is not assignable to parameter of type 'RefresherCustomEvent'. [ng]   Type 'Event' is missing the following properties from type 'RefresherCustomEvent': detail, initCustomEvent [ng] [ng] 8   <ion-refresher slot="fixed" (ionRefresh)="handleRefresh($event)">

This is an issue with our Angular compatibility: https://github.com/ionic-team/ionic-framework/issues/24245. The reason is the event type is assumed to always be `Event` which is not the case here.

**Comment by Tommertom** [comment]
> Do you have a sample app I can try? It's hard to understand what is going on here from only screenshots.

Sorry about that - svelte I reckon, given that the angular part is a known issue

Svelte: https://github.com/Tommertom/ionicrefresher

**Comment by Tommertom** [comment]
Ok  - thx for the debugging - just for my info - you expect this to be happening other places as well? It is the first type I am seeing this issue. Or as you say - it is happening everywhere so I need to wrap all events in  `CustomEvent<....>`?

Now - I am quite bluntly using the core.json data to generate this type. So for this situation it was 

```
  "events": [
                {
                    "event": "ionRefresh",
                    "detail": "RefresherEventDetail",
                    "bubbles": true,
                    "cancelable": true,
                    "composed": true,
                    "docs": "Emitted when the user lets go of the content and has pulled down\nfurther than the `pullMin` or pulls the content down and exceeds the pullMax.\nUpdates the refresher state to `refreshing`. The `complete()` method should be\ncalled when the async operation has completed.",
                    "docsTags": []
                },

```

Thx  again - will close the issue.

**Comment by liamdebeasi** [comment]
Yes, every event emitted from Ionic components is a `CustomEvent`. The "detail" key in the `core.json` snippet you post describes the [detail payload of `CustomEvent`](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/detail) not the type of the event itself.

**Comment by Tommertom** [comment]
Nice - thx- will change the script and generate new typings.

**Comment by liamdebeasi** [comment]
The team also looked at the Ionic Svelte source. The issue appears to be around here: https://github.com/Tommertom/svelte-ionic-npm/blob/main/scripts/generate.js#L242-L251

Should minimally be:
`"on:${event.event}"?: CustomEvent<${event.detail}>;`

But ideally you can do the following to get the `target` typing too:
`"on:${event.event}"?: CustomEvent<${event.detail}> & { target: ${htmlElementType};`

**Comment by Tommertom** [comment]
ok - thx- that I will include in the generate script. And clean up the repo as there are a few experimental generator scripts. Appreciate all the help!

**Comment by Tommertom** [comment]
I am now generating for all events
`  "on:ionRefresh"?: (event: CustomEvent<RefresherEventDetail>) => void;`

What is  `htmlElementType` in this respect? Everything is using HTMLBaseElement so that would make:

`  "on:ionRefresh"?: (event: CustomEvent<RefresherEventDetail> & {target: <HTMLBaseElement>}) => void;`

**Comment by Tommertom** [comment]
new version published - and scripts updated - generator.js is the go-to script

**Comment by liamdebeasi** [comment]
`htmlElementType` is a combination of `HTML`, the tag name as pascal case, and `Element`. Example: `HTMLIonRefresherElement`

**Comment by Tommertom** [comment]
Sorry to bother again - but I am now a bit confused what to do in the demo repo:

This will not generate any typescript issue(as I am using RefresherCustomEvent), but will be friction for developers to find as it is not specified in the docs nor can be inferred from the type definition in the IDE or typings file:
```
function refresher(ev:RefresherCustomEvent) {
		console.log('Refreshed.', ev);
		setTimeout(() => {
			ev.target.complete();
		}, 2000);
	}
```

Whereas if you use ev:RefresherEventDetail, there is a typescript error on `ev.target.complete()` and `ionRefresh` in the template.,
```
	function refresher(ev:RefresherEventDetail) {
		console.log('Refreshed.', ev);
		setTimeout(() => {
			ev.target.complete();
		}, 2000);
	}
```

**Comment by liamdebeasi** [comment]
`RefresherCustomEvent` is documented here: https://ionicframework.com/docs/api/refresher#refreshercustomevent. Unfortunately, `RefresherCustomEvent` is not included as part of our automatic `core.json` generation. However, devs do not have to use `RefresherCustomEvent`. They could use `CustomEvent<RefresherEventDetail>` and do `ev.detail.complete()`.

**Comment by Tommertom** [comment]
CustomEvent<RefresherEventDetail> still gives typescript errors

```
	function refresher(ev: CustomEvent<RefresherEventDetail>) {
		console.log('Refreshed.', ev);
		setTimeout(() => {
			if (ev.target) ev.target.complete();
		}, 2000);
	}
```

Error- `Property 'complete' does not exist on type 'EventTarget'.ts(2339)`

The `if` is to avoid `'ev.target' is possibly 'null'.ts(18047)`

If this is the only event where this is happening, I am happy to overrule `RefresherEventDetail` with `RefresherCustomEvent `

**Comment by liamdebeasi** [comment]
> Property 'complete' does not exist on type 'EventTarget'.ts(2339)

Yes, this is why `RefresherCustomEvent` exists as it correctly types `target`. As I noted in https://github.com/ionic-team/ionic-framework/issues/26747#issuecomment-1421285690, if you want to use `CustomEvent<RefresherEventDetail> ` you will need to also use `ev.detail.complete()` since `detail` has the correct type information (`RefresherEventDetail`).

You don't necessarily need to use these custom event interfaces. As I mentioned in https://github.com/ionic-team/ionic-framework/issues/26747#issuecomment-1421199351, you could do something like `& {target: HTMLIonRefresherElement}` when creating the type. This would also allow you to correctly type `target` so developers can continue to use `ev.target.complete()` and avoid the `if` check.
