### ISSUE TITLE
bug: ion-input has no option to contain a button or icon

### ISSUE THREAD

**Issue by paul-schweng** [ionic-team/ionic-framework#26750]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

In Ionic v7 you can use the ion-input without ion-item wrapper:
```html
<ion-input
  label="Username"
  shape="round"
  fill="outline"
  label-placement="floating"
  placeholder="Username eingeben...">
</ion-input>
```
But there is no parameter to set a button or icon, so that the button is contained in the input field. 

If you try to make it the old-fashioned way with the ion-item wrapper the button is inside of the input field, but the style is different.

![grafik](https://user-images.githubusercontent.com/72137146/217346871-e2d7be7f-3269-40db-9dea-b9394bdf34ec.png)
Username field is the code above and password field is the code below. As you can see the styles are different:
```html
<ion-item shape="round" lines="none" fill="outline">
  <ion-input
    label="Passwort"
    label-placement="floating"
    [clearOnEdit]="false"
    placeholder="Passwort eingeben...">
  </ion-input>
  <ion-button slot="end" fill="clear">
    <ion-icon size="large" [name]="'eye-outline'"></ion-icon>
  </ion-button>
</ion-item>
```

### Expected Behavior

You should use the ion-input the same way like in v6 with the ion-item wrapper and buttons. They should also look the same.

### Steps to Reproduce

See the code above

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.8 (C:\Users\pauls\AppData\Roaming\nvm\v18.12.1\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.0-beta.1
   @angular-devkit/build-angular : 14.2.10
   @angular-devkit/schematics    : 14.2.10
   @angular/cli                  : 14.2.10
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.6.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1 (C:\Program Files\nodejs\node.exe)
   npm    : 9.3.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for testing Ionic 7! We have an open feature request at https://github.com/ionic-team/ionic-framework/issues/26297, so I am going to merge these threads.
