### ISSUE TITLE
feat: Ability to set ion-segment set to position sticky on vertical scrolling of content

### ISSUE THREAD

**Issue by lazmeister** [ionic-team/ionic-framework#26768]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

When setting up a standard ion-segment and ion-segment-buttons within it and using the segments to toggle content below, the segments scroll within the content. It would be great to set a "sticky" setting on the segment buttons so they stay on top.

### Describe the Use Case

When using ion-segment to toggle content below and outside of the segment

Here is what the segment looks like before a scroll is started vertically 
![image](https://user-images.githubusercontent.com/3281599/217600413-25544e0d-77ed-4bf1-9970-956c4f37d7b6.png)
and after scrolling
![image](https://user-images.githubusercontent.com/3281599/217600498-3f5caf4f-5498-47e2-89ae-b422ba5e4c81.png)

### Describe Preferred Solution

provide a Position: sticky option that would allow the segment buttons to stay on top always

### Describe Alternatives

for now you have to wrap the ion-segment tags inside a ion-item-divider with sticky="true" setting to work

### Related Code

```
<ion-content [fullscreen]="true" [scrollEvents]="true">
  <ion-item-divider sticky="true"> <!-- Required for stickyness -->
    <ion-segment (ionChange)="segmentChanged($event)" value="tab1"> <!-- would be nice to have a sticky=true option here -->
      <ion-segment-button value="tab1">
        <ion-label>Tab 1</ion-label>
      </ion-segment-button>
      <ion-segment-button value="tab2">
        <ion-label>Tab 2</ion-label>
      </ion-segment-button>
    </ion-segment>
  </ion-item-divider>

  <ion-list *ngIf="segmentOption==='tab1'">
....
  </ion-list>

  <ion-list *ngIf="!segmentOption==='tab2'">
...
</ion-content>
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Have you tried adding the segment inside of a toolbar? The toolbar will scroll over the content.

**Comment by lazmeister** [comment]
I have thanks. I find the UI ordering and possibly padding is odd. Here is our current app with it in the toolbar: 
![image](https://user-images.githubusercontent.com/3281599/217602985-899de427-e908-4efe-b5e1-cd37301d8b80.png)

**Comment by lazmeister** [comment]
It could because of the segment tabs are centered but the title is aligned left. It seems like the ideal organization would be to have the segment take up the whole width of the window instead of just under the title if possible

**Comment by liamdebeasi** [comment]
Apologies, I meant to say "separate toolbar". So something like this:

```
<ion-header>
  <ion-toolbar>
    <ion-title>My Title</ion-title>
  </ion-toolbar>
  <ion-toolbar>
    <ion-segment>
      ...
    </ion-segment>
  </ion-toolbar>
</ion-header>
```

**Comment by lazmeister** [comment]
that works! Thanks @liamdebeasi  and sorry for the waste of time!

**Comment by liamdebeasi** [comment]
No problem at all, happy to help!
