### ISSUE TITLE
bug: Enabling the keyboard will cause the whole page to move up and cannot be recovered

### ISSUE THREAD

**Issue by Arkitect-z** [ionic-team/ionic-framework#26779]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

https://user-images.githubusercontent.com/53122135/218080801-7176d52f-5082-4bd1-b591-3f6b6beae607.mp4

You can see a demonstration of this in the video with highlighting of the touch.
At the beginning of the run, the blue buttons can be displayed in full, and when the virtual keyboard of Android is opened, the overall interface automatically moves up, but after that it cannot automatically return to its original position.

### Expected Behavior

I hope to make the digital input does not affect the top interface rendering, like the native Android

### Steps to Reproduce

my code: 
<template>
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-title>Tab 1</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content ref="content" :fullscreen="true" class="ion-padding">
      <ion-card color="light" v-if="photos.length == 0" mode="ios">
        <img src="../image/homeInstructPix2Pix.png" />
        <ion-card-header>
          <ion-card-title style="margin-bottom: 5px;">Select image</ion-card-title>
          <ion-card-subtitle class="ion-text-capitalize" style="margin-right: 50px;">
            The system will follow the instructions to edit the image
          </ion-card-subtitle>
        </ion-card-header>
        <ion-fab vertical="bottom" horizontal="end" style="margin-bottom: 10px;">
          <ion-fab-button>
            <ion-icon :icon="arrowUpOutline"></ion-icon>
          </ion-fab-button>
          <ion-fab-list side="top">
            <ion-fab-button @click="takePhotoPhotos()">
              <ion-icon :icon="imageOutline"></ion-icon>
            </ion-fab-button>
            <ion-fab-button @click="takePhotoCamera()">
              <ion-icon :icon="cameraOutline"></ion-icon>
            </ion-fab-button>
          </ion-fab-list>
        </ion-fab>
      </ion-card>

      <ion-grid v-if="photos.length > 0">

        <ion-button color="primary" @click="withDraw()">
          <ion-icon slot="icon-only" :icon="returnDownBackOutline"></ion-icon>
        </ion-button>

        <ion-img :src="photos[0].webviewPath"></ion-img>

        <ion-card mode="ios" style="margin-inline: 0;">
          <ion-card-header>
            <ion-card-title>Input</ion-card-title>
          </ion-card-header>

          <ion-item fill="outline" mode="md" spellcheck="true" style="padding: 8px 16px;">
            <ion-label position="floating">Input your command</ion-label>
            <ion-input :clear-input="true" placeholder="The system will edit the image"></ion-input>
          </ion-item>
          <ion-item class="input-ion-item">
            <input type="number" min="1" max="500" name="num_inference_steps" step="1" v-model=num_inference_steps class="num_input">
            <input type="range" min="1" max="500" name="num_inference_steps" step="1" v-model=num_inference_steps class="range_input">
          </ion-item>
          <ion-item class="input-ion-item">
            <input type="number" min="1" max="20" name="guidance_scale" step="0.1" v-model=guidance_scale class="num_input">
            <input type="range" min="1" max="20" name="guidance_scale" step="0.1" v-model=guidance_scale class="range_input">
          </ion-item>
          <ion-item class="input-ion-item">
            <input type="number" min="1" max="500" name="num_inference_steps" step="1" v-model=num_inference_steps class="num_input">
            <input type="range" min="1" max="500" name="num_inference_steps" step="1" v-model=num_inference_steps class="range_input">
          </ion-item>
          <ion-button style="margin: 8px 16px 16px 16px;">Submit</ion-button>

        </ion-card>
      </ion-grid>
    </ion-content>

  </ion-page>

<script setup lang="ts">
import { ref } from 'vue';
import {
  IonPage, IonHeader, IonToolbar, IonTitle,
  IonContent, IonButton, IonCard, IonGrid, IonFab,
  IonImg, IonItem, IonFabButton, IonFabList, IonLabel,
  IonInput, IonIcon, IonCardHeader, IonCardTitle, IonCardSubtitle
} from '@ionic/vue';
import { arrowUpOutline, imageOutline, cameraOutline, returnDownBackOutline } from 'ionicons/icons';
import { usePhotoGallery, UserPhoto } from '@/composables/usePhotoGallery';
import { handlerPredict } from "@/api/predictions/index";

const num_inference_steps = ref(100);
const guidance_scale = ref(7.5);

// Disable return to prevent confusing tabs jumping
history.pushState(null, "", document.URL);
window.addEventListener("popstate", function (e) {
  history.pushState(null, "", document.URL);
}, false);

const prompt = "";
const { photos, takePhotoCamera, takePhotoPhotos } = usePhotoGallery();

// Deselect images
const withDraw = () => {
  photos.value.pop();
};

</script>

### Ionic Info

Require stack:
       - C:\Users\*\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\*\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\*\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\*\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.20.8 (C:\Users\*\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.5.2

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : 4.6.2
   @capacitor/core    : 4.6.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.3
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you reproduce this issue in an Ionic starter app and provide a link to the repo? Keyboard-related issues can be a bit tricky to debug, so having a runnable sample is helpful.

**Comment by sean-perkins** [comment]
In addition to a runnable sample, you may want to use `ion-input` components in the places in your snippet where you are using `input` directly. Ionic includes a scroll assist utility that works with the keyboard to reposition the UI to avoid the layout shift you are experiencing.
