### ISSUE TITLE
bug: "ionic cap run ios" does not deploy to device

### ISSUE THREAD

**Issue by rgustavsson** [ionic-team/ionic-framework#26785]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

I am trying to run my ionic app on my iPhone device through the terminal in order to work with live reload but the `ionic cap run ios -l --external` does not deploy the app to the device, even though the logs state that it has been done.

I tried with with just `ionic cap run ios`, without the live-reload, and that doesn't work either.

### Expected Behavior

The app should be deployed to my physical device and I should be able to utilise live reload.

### Steps to Reproduce

1. Connect your iOS device to your macos
2. In your terminal, type `ionic cap run ios -l --external`
3. When prompted to pick which device to run on, pick the physical device your just recently connected

You'll see the following in your terminal log;

```
capacitor] ✔ Deploying App.app to 00008030-000E71081480802E in 752.53ms

[INFO] App deployed to device!
       
       Development server will continue running until manually stopped.
       
       Use Ctrl+C to quit this process
```
but the app is in fact not deployed.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.5.3
   @angular-devkit/build-angular : 15.0.4
   @angular-devkit/schematics    : 15.0.4
   @angular/cli                  : 15.0.4
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.3
   @capacitor/android : 4.6.3
   @capacitor/core    : 4.6.3
   @capacitor/ios     : 4.6.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1 (/usr/local/bin/node)
   npm    : 9.4.0
   OS     : macOS

### Additional Information

Tried running with --verbose but couldn't see any errors tied to deploying to device.

**Comment by liamdebeasi** [comment]
Thanks for the report. I think you might be looking for https://github.com/ionic-team/capacitor instead. This is the repo for Ionic Framework, a collection of UI components and utilities used to build mobile apps. While the Ionic CLI is being used to invoke Capacitor commands here, the actual code responsible for syncing your code with the native project is handled by Capacitor.

I am going to close this, but I recommend opening an issue with the Capacitor team using the link above. Let me know if you have any questions.

**Comment by rgustavsson** [comment]
Sorry for posting in the incorrect repo @liamdebeasi 

Just found the issue though! :) 

We simply downgraded from node 18/19 to the latest node 16.X version. Deployment is now working.
