### ISSUE TITLE
bug: opened page does not properly react on changes of dir attribute

### ISSUE THREAD

**Issue by stanislavkulibaba** [ionic-team/ionic-framework#26794]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

When setting `dir="rtl"` or `dir="ltr"`, an active page(pages which are already opened as well) does not change swipe gesture direction but animation direction does.

### Expected Behavior

Swipe gesture should change it's direction from rtl to ltr and vice versa

### Steps to Reproduce

1. Open page
2. Change language direction in the app (dir attribute)
3. Check opened page

### Ionic Info

"@ionic/angular": "6.5.0",
"@ionic/core": "6.5.0",

### Additional Information

Happens because the **rtl** property calculated only once during page init and never recalculated.
```
export const createSwipeBackGesture = (
  el: HTMLElement,
  canStartHandler: () => boolean,
  onStartHandler: () => void,
  onMoveHandler: (step: number) => void,
  onEndHandler: (shouldComplete: boolean, step: number, dur: number) => void
): Gesture => {
  const win = el.ownerDocument!.defaultView!;
  const rtl = isRTL(el); <----

```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26795, and a fix will be available in an upcoming release of Ionic Framework.
