### ISSUE TITLE
feat: Sheet Modal​ behind ion-tabs

### ISSUE THREAD

**Issue by Phil0xFF** [ionic-team/ionic-framework#26792]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The feature request is to add a new setting for the ion-modal that allows the modal to remain behind the ion-tabs, enabling users to navigate the app while still using the modal.

### Describe the Use Case

The use case involves a scenario where a user needs to interact with a modal in an Ionic app, but also needs to navigate through the app while the modal is still visible. For example, the user may need to reference some information on a different page or perform an action before returning to the modal. By allowing the modal to stay behind the ion-tabs, the user can continue to use the app without the modal obstructing their view, leading to a more seamless and efficient user experience.

### Describe Preferred Solution

The preferred solution would be to add a new setting or property to the ion-modal component in Ionic, such as "stay-behind-tabs", that can be set to "true" to enable the desired behavior. When this setting is enabled, the modal should be positioned behind the ion-tabs and should not prevent the user from interacting with the app's content.

**Comment by DwieDima** [comment]
probably this feature request describes what you need: #24198 

you could try this snippet:

```typescript
 public async showModalInsideIonContent(): Promise<void> {
    const modal = await this.modalController.create({
      component: SomePage,
    });

    // render modal inside active tab page, so tab switch is possible with opened modal
    const activeTabPage = document.querySelector('ion-content').closest('.ion-page');
    activeTabPage.appendChild(modal);

    await modal.present();
  }
```

**Comment by Phil0xFF** [comment]
Thank you very much @DwieDima. This workaround works great! 
Nevertheless it would be a great addition for Ionic 7 to have this feature.

**Comment by liamdebeasi** [comment]
Thanks for the report. As noted in https://github.com/ionic-team/ionic-framework/issues/26792#issuecomment-1429319622, this is the same feature request as https://github.com/ionic-team/ionic-framework/issues/24198. I am going to merge the two threads. Closing in favor of https://github.com/ionic-team/ionic-framework/issues/24198

**Comment by Phil0xFF** [comment]
@DwieDima I experienced some issues with your solution. From time to time the activeTabPage object is not defined. I fixed this issue by defining a specific ion-page id.

`const activeTabPage = document.querySelector('#home-view');`
