### ISSUE TITLE
feat: Add more breakpoint for ion-grid

### ISSUE THREAD

**Issue by Bandito11** [ionic-team/ionic-framework#26791]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Ionic Framework is being recommended for developing PWAs and even Electron. In order to be able to use the `ion-grid` faster, I think more breakpoint should be added. Right now it goes up to 1200px. 

### Describe the Use Case

Making the Developing using the ion-grids for desktop faster. 

### Describe Preferred Solution

I  think there should be breakpoints for width 1368px, 2880px, 3024px and 3456px. The last two belong the Macbook Pro 14 and 16 respectively and the first two were chosen by many laptops resolution I tend to see the most. I think those belong to the Surface Pro 7 and 9 if I am not mistaken (2880px is the width of the Surface Pro 9). 

The breakpoints are not what is important, is making it easier to make developing for desktops easier.

I think adding a xxl, xxxl, ivxl, etc...

### Describe Alternatives

The size of the breakpoint can be any size, the sizes I wrote shouldn't be set in stone. Same with the naming of the sizes, I am not that good at ancient Greek numbering 🤣

### Related Code

<ion-grid>
  <ion-row>
    <ion-col size="2">1</ion-col>
    <ion-col size-xl="5">2</ion-col>
    <ion-col size-xxxl="4">3</ion-col>
  </ion-row>
</ion-grid>

**Comment by liamdebeasi** [comment]
Thanks for the report. Is this the same as https://github.com/ionic-team/ionic-framework/issues/22413?

**Comment by Bandito11** [comment]
Pretty much, yes.

Esteban Morales

On Feb 13, 2023, at 5:48 PM, Liam DeBeasi ***@***.***> wrote:

﻿

Thanks for the report. Is this the same as #22413<https://github.com/ionic-team/ionic-framework/issues/22413>?

**Comment by liamdebeasi** [comment]
Thanks! I am going to merge the two threads. Closing in favor of https://github.com/ionic-team/ionic-framework/issues/22413.
