### ISSUE TITLE
bug: compositionend event is not removed from native input element

### ISSUE THREAD

**Issue by joewoodhouse** [ionic-team/ionic-framework#26805]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

When an <ion-input/> element is removed from the DOM, the native input element is not freed because the `compositionend`  event listener has not been removed. This is due to a typo in the code.

### Expected Behavior

The proper event listener should be removed.

### Steps to Reproduce

Add an <ion-input/> element to the document
Remove the element

Take a heap snapshot and inspect the heap. You will find a "Detached HTMLInputElement". Inspecting it's retainers you'll see an event listener.

### Ionic Info

Ionic:

   Ionic CLI : 6.20.6

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.14.2
   npm    : 8.7.0
   OS     : macOS

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26806, and a fix will be available in an upcoming release of Ionic Framework. Thanks for the PR!
