### ISSUE TITLE
bug: hide caret shim does not properly remove itself

### ISSUE THREAD

**Issue by joewoodhouse** [ionic-team/ionic-framework#26807]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

The shim for hiding the caret on scroll (detailed here https://github.com/ionic-team/ionic-framework/wiki/Utilities#hide-caret) does not remove itself properly, leaving an attached event listener on the ion-content object, which means it is never free/released by the GC

### Expected Behavior

The shim should properly remove itself from the element

## Setup

* Add an <ion-input/> inside of an <ion-content/> element
* Remove then ion-input and the ion-content

## Analysis

Take a snapshot of the heap. You will see a "Detached HTMLElement" in the objects relating to the ion-content object. In the list of retainers you will see the hide-caret shims

### Ionic Info

Ionic:

   Ionic CLI : 6.20.6

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.14.2
   npm    : 8.7.0
   OS     : macOS

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26808, and a fix will be available in an upcoming release of Ionic Framework. Thanks for the PR!
