### ISSUE TITLE
bug: Input field (viewport) is scrolled to the middle of the screen in 7.0.0-beta.2

### ISSUE THREAD

**Issue by mpaland** [ionic-team/ionic-framework#26804]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

For testing I migrated our app from 6.5.4 to 7.0.0-beta.2. The app is running and tested as Vue-PWA on an Android 9.0 device. 
When clicking (focusing) an input field, the viewport tries to scroll the input field in the middle of the screen.
This is worse if there is an input at the bottom of the page, the whole page (viewport) scrolls up until the bottom input is in the middle of the screen.
This is no issue and working fine in 6.5.4

### Expected Behavior

No unnecessary scrolling of the viewport (behavior like in 6.x) when focusing an input field

### Steps to Reproduce

Click on any <ion-input> or <ion-textarea> near the screen bottom.

### Ionic Info

Ionic:
   Ionic CLI       : 6.20.4 (C:\Users\Marco\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.0.0-dev.11676402953.118c3b36

Capacitor:
   Capacitor CLI      : 4.6.3
   @capacitor/android : not installed
   @capacitor/core    : 4.6.3
   @capacitor/ios     : not installed

Utility:
   cordova-res : not installed globally
   native-run  : 1.7.1

System:
   NodeJS : v16.15.1 (D:\nodejs\node.exe)
   npm    : 9.1.2
   OS     : Windows 10

### Additional Information

capacitor.config.json:
```
	"plugins": {
		"Keyboard": {
		  "resize": "native",
		  "style": "dark",
		  "resizeOnFullScreen": true
		}
	}
```
_No response_

**Comment by mpaland** [comment]
Perhaps related to #26803

**Comment by liamdebeasi** [comment]
Thanks for the report and thanks for testing Ionic 7! Can you reproduce this in an Ionic starter app and provide a link to the repo?
