### ISSUE TITLE
bug: ion-datetime-button dialog not opened on some devices

### ISSUE THREAD

**Issue by Keelback** [ionic-team/ionic-framework#26816]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

A customer uses an huawei smartphome. On his device the modal dialog to choose the time is not shown. When clicking on the button, nothing happens. On other devices everything works fine.
My code:
```
<ion-item>
      <ion-label position="stacked"
        >Time<ion-text color="danger">*</ion-text></ion-label
      >
      <ion-datetime-button datetime="uhrzeitBis"></ion-datetime-button>
      <ion-modal [keepContentsMounted]="true">
        <ng-template>
          <ion-datetime
            id="uhrzeitBis"
            size="cover"
            formControlName="uhrzeitBis"
            done-text="OK"
            cancelText="Abbrechen"
            minute-values="00, 15, 30, 45"
            presentation="time"
            show-default-buttons="true"
            show-default-time-label="false"
          >
          </ion-datetime>
        </ng-template>
      </ion-modal>
    </ion-item>
```

### Expected Behavior

Dialog is opening.

### Steps to Reproduce

It is not possible to reproduce it locally. 

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.6 (C:\Users\Maik\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.4.2
   @angular-devkit/build-angular : 12.2.18
   @angular-devkit/schematics    : 12.2.18
   @angular/cli                  : 12.2.18
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.3

Utility:

   cordova-res : 0.15.3
   native-run  : 1.7.1

System:

   NodeJS : v16.19.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.3.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you also post the webview version of the impacted devices? You can find this by logging `window.navigator.userAgent` when inspecting the app using Chrome dev tools.

**Comment by gdeamicis** [comment]
Hi! I am experimenting the same behaviour on a Huawei device. The webview versions that I am seeing are:

`'Mozilla/5.0 (Linux; Android 10; COL-L29 Build/HUAWEICOL-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.86 Mobile Safari/537.36'`

**Comment by liamdebeasi** [comment]
Are there any errors in the console? I can't reproduce this issue on my end, so you may need to do a bit of debugging here.

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
