### ISSUE TITLE
bug: How to programmatically use ion-nav-link

### ISSUE THREAD

**Issue by Jannik-KJ** [ionic-team/ionic-framework#26824]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

I want to make some api calls in the code before the user gets redirected to the next component. But I can't seem to find a way to use ionic component stack programmatically.

This is my component currently, 

**Root component**

```
<template>
  <ion-page>
    <Loading :showLoading="showLoading" message=""></Loading>
    <ion-nav :root="PageOne"></ion-nav>
  </ion-page>
</template>
```

**PageOne component**

```
<template>
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-title>Page One</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content class="ion-padding">
      <h1>Page One</h1>
<!--      <ion-nav-link router-direction="forward" :component="component">-->
        <ion-button @click="goToPageTwo()">Go to Page Two</ion-button>
<!--      </ion-nav-link>-->
    </ion-content>
  </ion-page>
</template>
```

It works with the ion-nav-link, but not sure how to implement the same functionality programmatically.
This is what goToPageTwo currently does on PageOne, which doesn’t do anything and doesn’t give me any errors either

```
const ionRouter = useIonRouter();

    function goToPageTwo() {
      ionRouter.navigate(PageTwo, 'forward', 'push');
    }
```

### Expected Behavior

Be able to create an instance of ion nav class and push a component to the stack without using routing

### Steps to Reproduce

No documentation 

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.4 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.5.3

Capacitor:

   Capacitor CLI      : 4.6.3
   @capacitor/android : not installed
   @capacitor/core    : 4.6.3
   @capacitor/ios     : 4.6.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v19.6.0 (/opt/homebrew/Cellar/node/19.6.0/bin/node)
   npm    : 9.4.0
   OS     : macOS

**Comment by liamdebeasi** [comment]
Thanks for the report. If you want to programmatically push pages in `ion-nav`, you should use the `push` method on `ion-nav`: https://ionicframework.com/docs/api/nav#methods

**Comment by Jannik-KJ** [comment]
Can you give an example? It seems to throw an error no matter what I do.
```
 import { IonNav } from "@ionic/core/components";
  const ionNav = new IonNav()
  await ionNav.push(PageOne)
```

**Comment by liamdebeasi** [comment]
You'll want to get a reference to the actual `ion-nav` element. Your code snippet is creating a new instance of the `IonNav` class that is separate from the one you are using in the DOM.

Here is an example: https://stackblitz.com/edit/angular-1cpz9c?file=src%2Fcomponents%2FPageOne.vue

The relevant code is in the `goToPageTwo` function. I get a reference to the `ion-nav` component in the DOM. I then call the `push` method, passing in `PageTwo` as the page I want to go to. 

Note: I used a querySelector to get the nav instance, but you could also pass this as a property to the page. You could achieve this using the [rootParams property](https://ionicframework.com/docs/api/nav#rootparams) and a [Vue ref](https://vuejs.org/guide/essentials/template-refs.html#template-refs).

**Comment by Jannik-KJ** [comment]
Perfect. I will try that. Thank you!
