### ISSUE TITLE
bug: vue back-button cannot get config backButtonDefaultHref

### ISSUE THREAD

**Issue by Anberm** [ionic-team/ionic-framework#26823]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

set global config backButtonDefaultHref, but back button cannot get
![image](https://user-images.githubusercontent.com/34148806/219853169-1a663e69-2400-4595-a95d-91dcba1d3faf.png)

### Expected Behavior

The page can be returned to the specified page

### Steps to Reproduce

1.  app.use(IonicVue, {
    mode: 'ios',
    backButtonDefaultHref: '/tabs/workbench',
  });
2.page set 
<ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-buttons>
          <ion-back-button slot="start" />
        </ion-buttons>
        <ion-title>主题设置</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content>
    </ion-content>
</ion-page>
3. Refresh current page

### Ionic Info

onic:

   Ionic CLI       : 6.20.8 (D:\nvm\nvm\v16.15.0\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.5.4

Capacitor:

   Capacitor CLI      : 4.6.3
   @capacitor/android : 4.6.3
   @capacitor/core    : 4.6.3
   @capacitor/ios     : 4.6.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.15.0 (D:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
