### ISSUE TITLE
bug: ion-datetime-button doesn't work with time only value (value="22:20") (ion-datetime works OK with time only value)

### ISSUE THREAD

**Issue by sachingarg05** [ionic-team/ionic-framework#26851]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

1) Works OK with **value="22:20"** without ion-datetime-button + ion-model

```
<div>
  <ion-datetime id="datetime"  value="22:20"  presentation="time"></ion-datetime>
</div>
```
![image](https://user-images.githubusercontent.com/4737179/221181624-570dcd15-ebac-45f3-8147-ff4506f4a8b7.png)

2) Works OK with **value="2022-04-21T22:20:00"** with ion-datetime-button + ion-model

```
<div>
  <ion-datetime-button datetime="datetime1"></ion-datetime-button>

  <ion-modal [keepContentsMounted]="true">
    <ng-template>
      <ion-datetime id="datetime1" value="2022-04-21T22:20:00"  presentation="time"></ion-datetime>
    </ng-template>
  </ion-modal>
</div>
```

![image](https://user-images.githubusercontent.com/4737179/221181666-9a5bf3c0-2648-4c1b-8a8a-4c9b79bc25b1.png)

3) Doesn't works with **value="22:20"** with ion-datetime-button + ion-model

```
<div>
  <ion-datetime-button datetime="datetime2"></ion-datetime-button>

  <ion-modal [keepContentsMounted]="true">
    <ng-template>
      <ion-datetime id="datetime2" value="22:20"  presentation="time"></ion-datetime>
    </ng-template>
  </ion-modal>
</div>

```
![image](https://user-images.githubusercontent.com/4737179/221181182-580e6a3f-492b-42a2-b2e1-26c7b89a7906.png)

### Expected Behavior

It should be possible to use ion-datetime-button with time only value.

### Steps to Reproduce

https://stackblitz.com/edit/angular-tmuu5n?file=src%2Fapp%2Fexample.component.html

### Code Reproduction URL

https://stackblitz.com/edit/angular-tmuu5n?file=src%2Fapp%2Fexample.component.html

### Ionic Info

```
    "@ionic/angular": "6.5.6",
    "@ionic/core": "6.5.6"
```

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this behavior. Here is a dev build with a proposed fix if you are interested in testing:

```
npm install @ionic/angular@6.5.7-dev.11677248874.1a3f2fcc
```

You can also work around the issue in your application by providing a date value. (i.e. `value="2023-01-01T22:20"`). The date values should not impact the time picker output.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26852, and a fix will be available in an upcoming release of Ionic Framework.
