### ISSUE TITLE
bug: Tabs behind chrome navigation bar at the bottom

### ISSUE THREAD

**Issue by kesava-cams** [ionic-team/ionic-framework#26850]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

When we open the Ionic application in Mobile Chrome/Safari, the tabs are behind the chrome navigation bar. 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/69981711/221034096-1a7f9358-6d9b-41b9-a061-b7d44a661b9f.png)

### Expected Behavior

Unless I go full screen in chrome or install it as an app, tabs doesn't show up. Below is the expected behavior

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/69981711/221037397-7c43863e-9290-441b-bc6e-23797bebad99.png)

### Steps to Reproduce

Here's the code I have

<ion-tabs style="display: contents;">

  <ion-tab-bar slot="bottom">
    <ion-tab-button tab="my-team">
      <ion-icon name="people-outline"></ion-icon>
      <ion-label>My Team</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="not-submitted">
      <ion-icon name="people-outline"></ion-icon>
      <ion-label>Not submitted</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="alt-approver">
      <ion-icon name="repeat-outline"></ion-icon>
      <ion-label>Alternate Approver</ion-label>
    </ion-tab-button>

    <ion-tab-button tab="message">
      <ion-icon name="mail-outline"></ion-icon>
      <ion-label>Message</ion-label>
    </ion-tab-button>
  </ion-tab-bar>

</ion-tabs>

### Ionic Info

Ionic:

   Ionic CLI                                     : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework                        : @ionic/angular 6.5.6
   @angular-devkit/build-angular : 14.2.10
   @angular-devkit/schematics     : 14.2.10
   @angular/cli                              : 14.2.10
   @ionic/angular-toolkit              : 6.1.0

Capacitor:

   Capacitor CLI            : 4.4.0
   @capacitor/android : not installed
   @capacitor/core       : 4.4.0
   @capacitor/ios         : not installed

Utility:

   cordova-res : not installed globally
   native-run    : 1.7.1

System:

   NodeJS : v18.14.1 (/usr/local/bin/node)
   npm      : 9.3.1
   OS        : Linux 5.15

Cordova: 10.0.0 (cordova-lib@10.1.0)

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you reproduce this in an Ionic starter app and provide a link to the repo?
