### ISSUE TITLE
bug: ionic serve doesn't support javascript symlink

### ISSUE THREAD

**Issue by gregoiregentil** [ionic-team/ionic-framework#26859]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [X] v4.x
- [X] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

A javascript file, located in assets and injected in index.html is properly rendered by "ionic serve".

A javascript symlink located in assets and injected in index.html triggers an error by "ionic serve":

Refused to execute script from 'http://localhost:8100/assets/b.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### Expected Behavior

Any javascript symlink should be rendered like for instance "php -S localhost:8101" is properly doing.

### Steps to Reproduce

ionic start test blank --type angular
cd test
echo "alert(1);" > src/assets/a.js
ln -s a.js src/assets/b.js

#Add the following two lines in the header of src/index.html:
<script src="assets/a.js"></script>
<script src="assets/b.js"></script>

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module
       '@capacitor/ios/package'
       
       Require stack:
       - /opt/libs/nodejs/lib/node_modules/@ionic/cli/lib/project/index.js
       - /opt/libs/nodejs/lib/node_modules/@ionic/cli/lib/index.js
       - /opt/libs/nodejs/lib/node_modules/@ionic/cli/index.js
       - /opt/libs/nodejs/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module
       '@capacitor/android/package'
       
       Require stack:
       - /opt/libs/nodejs/lib/node_modules/@ionic/cli/lib/project/index.js
       - /opt/libs/nodejs/lib/node_modules/@ionic/cli/lib/index.js
       - /opt/libs/nodejs/lib/node_modules/@ionic/cli/index.js
       - /opt/libs/nodejs/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 6.20.8 (/opt/libs/nodejs/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.5.6
   @angular-devkit/build-angular : 15.2.0
   @angular-devkit/schematics    : 15.2.0
   @angular/cli                  : 15.2.0
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : not installed
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v18.13.0 (/opt/libs/nodejs/bin/node)
   npm    : 8.19.3
   OS     : Linux 5.15

### Additional Information

Note that "ionic build" works because it converts the symlink into a real file. So www/assets/b.js is a physical file instead of a symlink.

**Comment by liamdebeasi** [comment]
Thanks for the report. The Angular CLI is the tooling that is responsible for compiling/bundling your app, not Ionic Framework. Calling `ionic build` calls `ng build` under the hood. Have you tried filing an issue on https://github.com/angular/angular-cli/issues?

**Comment by gregoiregentil** [comment]
You are pushing me away ;-)
Note that my problem is with ionic serve not ionic build.

I understand your point. I guess that you are going to tell me that ionic serve calls ng serve. Yes, the underlying angular is probably the culprit...

**Comment by liamdebeasi** [comment]
Does the issue reproduce if you use `ng serve` instead of `ionic serve`? If so, it's likely either a misconfiguration or an Angular CLI bug.
