### ISSUE TITLE
feat: Circular progress bar. 

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#26866]
Consider to include a circular progress bar into this framework. It's a part of Material Design. Like the spinner, just with a value and responsive size in width and height.

![circular-progress](https://user-images.githubusercontent.com/60390085/221650046-da52a5d3-2948-4ca0-9e60-524c2db6f190.gif)

- https://m2.material.io/components/progress-indicators/android#circular-progress-indicators
- https://material.angular.io/components/progress-spinner/examples

**Comment by liamdebeasi** [comment]
Thanks for the report. Looks like we have the same request in https://github.com/ionic-team/ionic-framework/issues/21868, so I am going to merge the two tickets.
