### ISSUE TITLE
bug: React IonLoading is no longer dismissed when used in Suspense

### ISSUE THREAD

**Issue by ptmkenny** [ionic-team/ionic-framework#26861]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

I just updated from v6 to the v7 beta.

My app uses the tanstack-query library and `<Suspense>` to fetch data.

In v6, I can fetch data with Suspense and use `<Loading>` as the fallback, but in v7, **the loading component continues to be displayed after the data has loaded and is only dismissed after the loading timeout.**

### Expected Behavior

I expect IonLoading to be dismissed when data is finished loading with `<Suspense>`.  Or the upgrade documentation should describe how to handle this case.

### Steps to Reproduce

In the following code, in v6, `IonLoading` is dismissed when the data is loaded.  But in v7, `IonLoading` is displayed until `5000` milliseconds have passed, even when data is loaded much faster.

```
const QueryAppPages: React.FC<MyProps> = ({ children }: MyProps) => {
  const { data } = useAppPages();

  return (
    <Suspense fallback={<IonLoading isOpen duration={5000} />}>
      {data ? children : <p>Error: Could not load app pages.</p>}
    </Suspense>
  );
};
```

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.8 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.0-beta.4

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.7.0
   @capacitor/ios     : 4.7.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v19.6.0 (/opt/homebrew/Cellar/node/19.6.0/bin/node)
   npm    : 9.4.0
   OS     : macOS

```

**Comment by liamdebeasi** [comment]
Thanks for testing the Ionic v7 beta! Do you have a sample app I can try? I think this is the same as https://github.com/ionic-team/ionic-framework/issues/26185, but I'd like to be certain before I merge the two tickets.

**Comment by ptmkenny** [comment]
Thanks for the reply.  It may not be the same as the other issue because I never saw this behavior in V6-- in V6, the loading component is hidden when loading is finished, but in V7, it's sticking around.

I'll try to get a sample app but it may take a few days.

**Comment by liamdebeasi** [comment]
The IonLoading component in v6 is different than the one in v7. In Ionic v6, the IonLoading React component isn't the actual Web Component. Instead, it is a placeholder `<div>` that is controlled internally by `loadingController`. On the other hand, the IonModal React component is controlled by the `ion-modal` Web Component. In Ionic 7 we updated the IonLoading React component to behave more like the IonModal React component.

**Comment by ptmkenny** [comment]
Ok I may have identified the issue.

My app uses `useState()` to control the display of `ion-loading` as [described in the v5 docs](https://ionicframework.com/docs/v5/api/loading):

```
/* Using with IonLoading Component */

import React, { useState } from 'react';
import { IonLoading, IonButton, IonContent } from '@ionic/react';

export const LoadingExample: React.FC = () => {
  const [showLoading, setShowLoading] = useState(true);

  setTimeout(() => {
    setShowLoading(false);
  }, 2000);

  return (
    <IonContent>
      <IonButton onClick={() => setShowLoading(true)}>Show Loading</IonButton>
      <IonLoading
        cssClass="my-custom-class"
        isOpen={showLoading}
        onDidDismiss={() => setShowLoading(false)}
        message={'Please wait...'}
        duration={5000}
      />
    </IonContent>
  );
};
```

But in the most recent docs, the Controller example uses the `useIonLoading()` hook.  Is the generic `useState()` hook no longer supported?

**Comment by liamdebeasi** [comment]
`useState` is still supported: https://ionicframework.com/docs/api/loading#inline

In Ionic v7 we updated the docs to show the `trigger` property instead, but you can continue to use `isOpen`: https://ionicframework.com/docs/v7/api/loading#inline-recommended

**Comment by ptmkenny** [comment]
Ok here's an example repo:

https://github.com/ptmkenny/ionic-26861

`ion-loading` continuing to display even after data has been loaded can be seen on Tab 2.

Tab 2 fires two queries, each suspended separately.  You can see the data get displayed behind `ion-loading`, but `ion-loading` isn't hidden until the `duration` elapses

Tab 3 uses a `<p>Text</p>` instead of `<IonLoading>`.  This behaves as expected (the `<p>text</p>` is hidden as soon as the data loads).

I originally reported that this behavior occurs on version 7 but not version 6.  However, this sample can be used to reproduce the behavior on both 6 and 7.  So, I am not sure why my v6 app can hide the `ion-loading` successfully but this sample repo fails for both v6 and v7-- I will continue to investigate.

**Comment by liamdebeasi** [comment]
Thanks! It does appear that this is the same problem as https://github.com/ionic-team/ionic-framework/issues/26185, so I am going to merge the two. Note that the issue references modals, but this bug applies to all overlays.

A few things:

1. There is an Ionic v6 dev build that fixes this issue for IonModal and IonPopover in https://github.com/ionic-team/ionic-framework/issues/26185#issuecomment-1307673452.
2. As I noted in https://github.com/ionic-team/ionic-framework/issues/26861#issuecomment-1446463074, IonLoading has a different architecture than IonModal/IonPopover in Ionic v6, so the dev build will not fix the issue for IonLoading in Ionic v6.
3. We revised the architecture of IonLoading in Ionic v7 to be more like IonModal/IonPopover. This means that once https://github.com/ionic-team/ionic-framework/issues/26185 is fixed, the next release of Ionic v7 will have this fix too.

Going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/26185. In terms of next steps, I recommend following the linked issue for updates. Once that issue is marked as "resolved" the following Ionic v7 release should have that fix and the issue should be resolved for IonLoading. Let me know if you have any questions.
