### ISSUE TITLE
bug: disabled={false} applies disabled styling

### ISSUE THREAD

**Issue by ptmkenny** [ionic-team/ionic-framework#26881]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [ ] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

Adding `disabled={false}` changes the styling of IonInput.

```
        <IonInput label="Input (disabled=false)" disabled={false} />
        <IonInput label="Input (disabled not set)" />
```

![Screenshot 2023-03-01 at 14 12 58](https://user-images.githubusercontent.com/1451472/222051061-30f5d494-cc22-4e52-84fa-c71113355c35.png)

### Expected Behavior

In Ionic React, I expect the following `ion-input` to have the same styles:

```
        <IonInput label="Input (disabled=false)" disabled={false} />
        <IonInput label="Input (disabled not set)" />
```

### Steps to Reproduce

Create components as shown above.

Check out the sample repo on Tab 2.

### Code Reproduction URL

https://github.com/ptmkenny/ionic-26861/tree/inputDisabled

### Ionic Info

```

Ionic:

   Ionic CLI       : 6.20.8 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.0-dev.11677608949.16e25264

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : not installed
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v19.6.0 (/opt/homebrew/Cellar/node/19.6.0/bin/node)
   npm    : 9.4.0
   OS     : macOS


```

### Additional Information

Potentially related: https://github.com/ionic-team/ionic-framework/issues/26706

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26892, and a fix will be available in an upcoming release of Ionic Framework.
