### ISSUE TITLE
Unresolved Import warnings when building in Stencil for latest date changes

### ISSUE THREAD

**Issue by joewoodhouse** [ionic-team/ionic-framework#26908]
https://github.com/ionic-team/ionic-framework/blob/c0e1bf92c4487c2ec8a117957cf84a2ce00f5fd8/core/src/components/datetime/utils/state.ts#L1

When building with @ionic/core@6.6.0 and @stenci/core get following warning:

```
[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@utils/logging' is imported by
           ./node_modules/@ionic/core/dist/collection/components/datetime/utils/state.js, but could not be resolved –
           treating it as an external dependency
```
And runtime issues

Think the above line should be 

```
import { printIonError } from '../../utils/logging';
```

These errors have been introduced quite a few times in the past, I wonder if there's some sort of lint check you can do to make sure they aren't re-introduced?

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26909, and a fix will be available in an upcoming release of Ionic Framework.
