### ISSUE TITLE
Ion-datetime selects disabeled day when changing month with month year picker

### ISSUE THREAD

**Issue by eazyenno** [ionic-team/ionic-framework#26904]
https://ionicframework.com/docs/api/datetime

**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **6.6.0**

**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

It selects a date in the next or previous month even though they are disabled, when changing the month with the month-year picker.

**Expected behavior:**

It should just change the month without selecting any dates in the month.

**Steps to reproduce:**

I want to select multiple days in a ion-datetime to save the selection. When i select a Month like this
![grafik](https://user-images.githubusercontent.com/72606409/222730083-b5f42940-842e-4a79-918c-c46ab2440b77.png)

and then use this view at the top left and select for example february:
![grafik](https://user-images.githubusercontent.com/72606409/222730301-cc815c37-f5ad-414a-911a-f6bb9dfedb57.png)

i get the message:
````shell
[Ionic Warning]: The value provided to ion-datetime is out of bounds.

Min: {"month":2,"day":15,"year":2023,"hour":23,"minute":0}
Max: {"month":4,"day":15,"year":2023,"hour":22,"minute":0}
Value: [{"year":2023,"month":3,"day":2,"tzOffset":0,"ampm":"pm"},{"year":2023,"month":2,"day":2,"tzOffset":0,"ampm":"pm"}]
````

and this happens:
![grafik](https://user-images.githubusercontent.com/72606409/222731308-98b3b0a5-907c-4857-8604-b2420207f880.png)

it selects a day it shouldn't select due to the fact that its disabled.

**Related code:**

```
This is my html:
    <ion-datetime
      mode="ios"
      min="{{this.lastMonth.toISOString()}}"
      max="{{this.nextMonth.toISOString()}}"
      multiple="true"
      color="secondary"
      presentation="date"
      first-day-of-week="1"
      [highlightedDates]="highlightedDates"
    >
    </ion-datetime>
```

Last Month in this case is the 15. of the last month and next Month the 15. of the next Month

**Other information:**

**Ionic info:** 

```
[Ionic Warning]: The value provided to ion-datetime is out of bounds.

Min: {"month":2,"day":15,"year":2023,"hour":23,"minute":0}
Max: {"month":4,"day":15,"year":2023,"hour":22,"minute":0}
Value: [{"year":2023,"month":3,"day":2,"tzOffset":0,"ampm":"pm"},{"year":2023,"month":2,"day":2,"tzOffset":0,"ampm":"pm"}]
```

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
