### ISSUE TITLE
bug: ion-datetime-button doesn't open ion-datetime modal

### ISSUE THREAD

**Issue by de-dan** [ionic-team/ionic-framework#26916]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

When I click on ion-datetime-button, the darker overlay is shown, but no modal with datetime.

I use chrome 110.0.5481.77 on a Mac 13.2.1 but I have this bug reported from users with different OS's and browsers.
This problem occured after I upgraded to 6.6.0. Downgrading to 6.5.7 resolved the issue!

### Expected Behavior

Show the modal when I click on date or time of ion-datetime-button.

### Steps to Reproduce

Create a new ionic project
`ionic start`
I used the blank starter, angular

in home.page.html paste in the ion-datetime-button example from the docs

```
<ion-datetime-button datetime="datetime"></ion-datetime-button>

<ion-modal [keepContentsMounted]="true">
  <ng-template>
    <ion-datetime id="datetime"></ion-datetime>
  </ng-template>
</ion-modal>
```

Run it and click on the date or time. Only overlay is shown.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.6.0
   @angular-devkit/build-angular : 15.2.1
   @angular-devkit/schematics    : 15.2.1
   @angular/cli                  : 15.2.1
   @ionic/angular-toolkit        : 8.0.0

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : not installed
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.14.2 (/usr/local/bin/node)
   npm    : 9.5.0
   OS     : macOS

**Comment by dudynets** [comment]
I can confirm that the bug also exists in version 7.0.0-rc.0 of the Ionic Framework.

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this. It looks the fix in https://github.com/ionic-team/ionic-framework/commit/00d10f5f6ad53850505bdad94b659b8801a3309d uncovered another bug with our modals. I'll take a closer look.

**Comment by liamdebeasi** [comment]
Here is a dev build if anyone is interested in testing the proposed fix:

```
npm install @ionic/angular@6.6.1-dev.11678112836.1733c8ec
```

**Comment by dudynets** [comment]
> Here is a dev build if anyone is interested in testing the proposed fix:
> 
> ```
> npm install @ionic/angular@6.6.1-dev.11678112836.1733c8ec
> ```

Everything works as expected, and the issue seems to have been resolved.

**Comment by vadimwe** [comment]
I confirm issue. ionic/angular 6.6.0

**Comment by moose4lord** [comment]
I also ran into this issue when I upgraded to @ionic/angular 6.6.0.
The fix proposed by @dudynets worked for me.
Thanks for looking into this and turning it around so quickly.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26917, and a fix will be available in an upcoming release of Ionic Framework.
