### ISSUE TITLE
bug: React IonAlert/useIonAlert  input label does not display

### ISSUE THREAD

**Issue by babycourageous** [ionic-team/ionic-framework#26915]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] v7.x
- [ ] Nightly

### Current Behavior

setting the label of an input using the config passet to the `present` fn from `useIonAlert` or an inline Alert does not result in a label for the input in the alert.

### Expected Behavior

Alert input label should be visible and match the label set in config.

### Steps to Reproduce

present an alert with `useIonAlert()` or inline and as part of the config set an input with a label.
open the alert and see the input - but no label.

### Code Reproduction URL

https://github.com/babycourageous/ionic-alert-input-label-bug

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.1 (/Users/renedellefont/.fnm/node-versions/v16.13.1/installation/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.6.0

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : not installed
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.13.1 (/Users/renedellefont/.fnm/node-versions/v16.13.1/installation/bin/node)
   npm    : 8.1.2
   OS     : macOS

### Additional Information

the docs don't describe what each config item corresponds to (https://ionicframework.com/docs/api/alert#alertinput) so I am making the assumption `label` should correspond to the label for the input. If that's not the case, happy to close this as a non-issue!.

Thanks!

**Comment by sean-perkins** [comment]
Hello @babycourageous thanks for this issue!

The `label` property for alert inputs is only applied to [checkboxes](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/alert/alert.tsx#L440) and [radios](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/alert/alert.tsx#L480).

We can do a better job of documenting this. I'll open a PR to correct this.

**Comment by babycourageous** [comment]
Thanks for that update @sean-perkins ! I peeked at #26923 and 👍 to why it isn't implemented for text inputs.
