### ISSUE TITLE
bug: '@utils/logging' 

### ISSUE THREAD

**Issue by Scan0815** [ionic-team/ionic-framework#26929]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

'@utils/logging' is imported by
           ./node_modules/@ionic/core/dist/collection/components/datetime/utils/state.js, but could not be resolved –
           treating it as an external dependency

### Expected Behavior

'@utils/logging' is imported by
           ./node_modules/@ionic/core/dist/collection/components/datetime/utils/state.js, but could not be resolved –
           treating it as an external dependency

### Steps to Reproduce

build

### Ionic Info

ionic 6.6.0 core

**Comment by liamdebeasi** [comment]
Thanks for the report. This was recently fixed in v6.6.1, so I recommend updating your application. I am going to close this since the reported issue has already been resolved.
