### ISSUE TITLE
bug: ion-input new v7 errorText displayed right away

### ISSUE THREAD

**Issue by cyrilletuzi** [ionic-team/ionic-framework#26939]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

v7 introduced `errorText` property to `<ion-input>`. But if the input has the `required` attribute, which is one of the most basic and common control, the `errorText` will be displayed right away when the form is displayed. This is problematic for several reason:
- it's bad UX (we should not annoy the user right away, only once the user touched the input and moved to another one)
- it's inconsistent with the visual behavior: on first display, the CSS is normal, and it turns red only if the input is invalid *and* touched and the user has moved to another input, as expected
- it ruins all the new simpler `<ion-input>` behavior introduced in v7, as it forces to add back a `<ion-item>` with `<ion-note slot="error" *ngIf="emailControl.invalid && emailControl.dirty">` (assuming it's still possible, which is not even sure, it doesn't work in v7 in my application anymore, probably because you can't mix the 2 systems)

### Expected Behavior

`<ion-input>` `errorText` should behave like CSS, ie. be displayed only when the input is invalid *and* touched and moved away to another input.

### Steps to Reproduce

1. Add a `<ion-input type="text" label="text" name="hello" required errorText="Error" [(ngModel)]="hello">`

(sorry I tried to do a stackblitz but I couldn't make it work with ionic v7 and I have no more time to create a full github repo)

### Ionic Info

`@ionic/angular` v7.0.0-rc.1
`@angular/*` v15.2.2x
node v18.15.0
npm v9.6.0

**Comment by cyrilletuzi** [comment]
(Another solution would be to introduce a new property, like `errorTextTrigger` with values like `touched`, `dirty`...).

**Comment by liamdebeasi** [comment]
Thanks for the report. Here is a dev build if you are interested in testing the proposed fix:

```
npm install @ionic/angular@7.0.0-dev.11678373650.1975657a
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26940, and a fix will be available in an upcoming release of Ionic Framework.
