### ISSUE TITLE
bug: Issue with the ion-datetime display

### ISSUE THREAD

**Issue by maelp** [ionic-team/ionic-framework#26943]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

The documentation mentions that ion-datetime accepts a date in ISO format, but when using `new Date().toISOString()` in a location with a non-null UTC-offset, it seems that the date displayed by the ion-datetime is actually the UTC time and not the local time

### Expected Behavior

I would expect that given a `value=iso_datetime`, the value actually displayed in the widget is the time in the local timezone (with UTC offset applied)

### Steps to Reproduce

```
            <ion-datetime-button datetime="curTimestamp" />
            <ion-modal :keep-contents-mounted="true">
              <ion-datetime
                id="curTimestamp"
                :value="new Date(curTimestamp * 1000).toISOString()"
                :show-default-buttons="true"
                @ion-change="(event) => setCurTimestamp(event)"
              ></ion-datetime>
            </ion-modal>
```

this results in the datetime component showing "16:52" although it's "17:52" at my local timezone (GMT+1)

### Ionic Info

Ionic:

   Ionic CLI : 6.20.4

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.7.1)   : 1.5.0

System:

   NodeJS : v16.18.0
   npm    : 9.1.2
   OS     : macOS

**Comment by liamdebeasi** [comment]
Thanks for the report. As noted in https://ionicframework.com/docs/api/datetime#time-zones, `ion-datetime` does not adjust values according to different time zones. In other words, it interprets values exactly as they are provided. Developers need to account for timezones themselves when passing values to datetime.

Here is another example: https://codepen.io/liamdebeasi/pen/JjaMWYw?editors=1010

**Comment by maelp** [comment]
Okay, but then the documentation should perhaps not mention that the date that ion-datetime accept must be given in UTC (with the "Z" at the end) since this is confusing (the fact that we give a datetime in UTC makes user think that the widget will handle local timezone itself), but rather to just say, "give a date in the format YYYY/MM/DD hh:mm:ss and the widget will display this"
