### ISSUE TITLE
bug(angular): ion-textarea loses focus switching desktop windows

### ISSUE THREAD

**Issue by ericis** [ionic-team/ionic-framework#26947]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

On a Windows desktop, when scrolling down to and selecting an `<ion-textarea ...>` that is displayed in an `<ion-split-pane><ion-menu><ion-content><ion-list>...<ion-item>` and then switching to another application and back again (e.g. `Alt-Tab`), the textarea has lost focus entirely and the view has automatically scrolled to the top.

### Expected Behavior

Focus remains on the `<ion-textarea ...>`.

### Steps to Reproduce

1. On Windows (11 Pro)
2. In an Ionic Angular application version `6.5.3`
3. Build an `<ion-split-pane><ion-menu><ion-content><ion-list>...<ion-item><ion-textarea...>...`, where the textarea is located below several list items and below the initial view, requiring scrolling
4. Add some content to the split pane as well `<ion-split-pane><div><ion-header>...</ion-header><ion-content...>...</ion-content>...`
5. In a browser (e.g. Firefox), scroll down to and select the `<ion-textarea>` and type some characters
6. Switch to another application using the `Alt-Tab` keyboard sequence
7. Switch back to the browser
8. Notice the textarea has lost focus and the view has automatically scrolled back to the top

### Ionic Info

$ ionic info

Ionic:

   Ionic CLI                     : 6.20.8
   Ionic Framework               : @ionic/angular 6.5.3
   @angular-devkit/build-angular : 15.1.5
   @angular-devkit/schematics    : 14.2.10
   @angular/cli                  : 15.1.5
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.3
   @capacitor/android : not installed
   @capacitor/core    : 4.6.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.12.1 (C:\Program Files\nodejs\node.exe)
   npm    : 9.1.2
   OS     : Windows 10

### Additional Information

I have discovered many sources from several years ago that refer to issues and code examples covering textarea-related things like iOS and Safari, mobile keyboard display and viewport resizing, calling `setFocus()`, etc. But, none of these seem to be directly related to an issue like this.

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
