### ISSUE TITLE
bug: Skip focus on <ion-textarea> elements when using tabindex=-1

### ISSUE THREAD

**Issue by AppGonder** [ionic-team/ionic-framework#26944]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

when using tabindex=-1 to avoid a focus on input, it works fine on `<ion-input>` but on `<ion-textarea>` is not working on ionic versions greather then v4.

<ion-item>
      <ion-textarea placeholder="Test" tabindex="-1"></ion-textarea>
    </ion-item>

    <ion-item>
      <ion-textarea placeholder="Test" tabindex="-1"></ion-textarea>
    </ion-item>

    <ion-item>
      <ion-input placeholder="Test" tabindex="-1"></ion-input>
    </ion-item

### Expected Behavior

Pressing tab or enter key, the behavior is expected to not focus on next inputs or text areas. Inspecting the html element the attribute tabindex is not passing for the `<textarea>` element.

### Steps to Reproduce

add tabindex=-1 to html tags `<ion-input>` and `<ion-textarea> `and press tab key on keyboard, the focus is skipped on the forms

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1
   Ionic Framework               : @ionic/angular 6.1.8
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.14.0
   npm    : 8.19.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/26945, and a fix will be available in an upcoming release of Ionic Framework.
