### ISSUE TITLE
bug: ion-select shows items below the iPhone "header" which makes them unaccessible on iPhone 13 mini

### ISSUE THREAD

**Issue by maelp** [ionic-team/ionic-framework#26952]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When adding a modal with a ion-select with interface="popover", the list goes under the iPhone top header, which makes it unselectable

<img width="352" alt="image" src="https://user-images.githubusercontent.com/15458/224994737-ea90a25a-d5fb-4ef8-895b-da50d17266ea.png">

### Expected Behavior

It should limit the list height to below the iPhone header and make it scrollable

### Steps to Reproduce

Create a modal (not sure if needed), create a ion-select with interface="popover", add many items to it, compile it on the iPhone simulator (bugs also happens when deployed to a real device) for iPhone 13 mini

### Ionic Info

Ionic:

   Ionic CLI : 6.20.4

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.7.1)   : 1.5.0

System:

   NodeJS : v16.18.0
   npm    : 9.1.2
   OS     : macOS

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
