### ISSUE TITLE
bug: ion-backdrop not dismissing when visible property set to false

### ISSUE THREAD

**Issue by timstoute** [ionic-team/ionic-framework#26953]
### Describe the Bug

the ion-backdrop component is not dismissing when the visible property is set to false  

I observe this even with the linked Ionic documentation stackblitz: https://stackblitz.com/edit/angular-vrhkzg?file=src%2Fapp%2Fexample.component.html

myionic info output included below

### Expected Behavior

i expect that when the ion-backdrop visible property is set to false that the overlay will disappear

### Steps to Reproduce

This is reproducible for me with the StackBlitz code included in the Ionic Documentation (v6) linked form this page: https://ionicframework.com/docs/api/backdrop#properties

Ionic Info

   Ionic CLI                     : 6.20.8 (/home/xxx/.nvm/versions/node/v17.9.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.4.1
   @angular-devkit/build-angular : 15.0.1
   @angular-devkit/schematics    : 15.0.1
   @angular/cli                  : 15.0.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : not installed
   @capacitor/core    : 4.3.0
   @capacitor/ios     : 4.3.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v17.9.0 (/home/xxx/.nvm/versions/node/v17.9.0/bin/node)
   npm    : 8.12.2
   OS     : Linux 5.15

### Operating System

Linux Ubuntu 20.04.5

### Browser

Chrome

### Version

Version 111.0.5563.64 (Official Build) (64-bit)

**Comment by amandaejohnston** [comment]
Thank you for the issue. Just to make sure I understand, do you mean that the blue backdrop remains visible even with `visible="false"`?

If so, this is due to the following CSS in that playground, in `example.component.css`:
```
ion-backdrop {
  opacity: 0.9;
  background: var(--ion-color-primary);
}
```
This overrides the CSS that hides the backdrop when the `visible` property is set. If I remove that CSS, the backdrop disappears.

**Comment by timstoute** [comment]
Ok, thanks for looking at this; perhaps I'm misunderstanding the intended behavior of the component. 

But, even with the Basic Usage example [from the documentation ](https://ionicframework.com/docs/api/backdrop#properties), looking at the [StackBlitz](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts),  I'm still unable to interact with the button or the checkbox control unless I completely remove the `<ion-backdrop [visible]="false"></ion-backdrop>` tag from the page.  Setting [visible]="false" does not allow me to interact with the button or the checkbox. 

I expected that if I set the [visible]="false" I would be able to interact with the page elements.
