### ISSUE TITLE
bug: broken material style with ion-item button lines=full

### ISSUE THREAD

**Issue by AnTiiK** [ionic-team/ionic-framework#26955]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

The following focused ion-item is display with a large black bottom border

```html
<ion-list>
  <ion-item button lines="full">
    <ion-label position="stacked"> Item 2 </ion-label>
  </ion-item>
</ion-list>
```

### Expected Behavior

The same style has following code (lines property on ion-list instead of ion-item)

```html
<ion-list lines="full">
  <ion-item button>
    <ion-label position="stacked"> Item 2 </ion-label>
  </ion-item>
</ion-list>
```

### Steps to Reproduce

1. Create a new ionic angular project
2. Add code from "Current Behavior" section
3. Run the dev env
4. Focus the ion-item button
5. See the black border

### Ionic Info

Ionic:
   Ionic CLI                     : 6.20.8
   Ionic Framework               : @ionic/angular 6.6.1
   @angular-devkit/build-angular : 15.2.2
   @angular-devkit/schematics    : 15.2.2
   @angular/cli                  : 15.2.2
   @ionic/angular-toolkit        : 8.0.0

Capacitor:
   Capacitor CLI      : 4.7.0
   @capacitor/android : not installed
   @capacitor/core    : 4.7.0
   @capacitor/ios     : not installed

Utility:
   cordova-res : 0.15.3
   native-run  : 1.7.2

System:
   NodeJS : v16.19.0 
   npm    : 8.19.1
   OS     : Windows 10

**Comment by sean-perkins** [comment]
An additional community member reported this issue, including the details in this comment:

> Reproduction: https://github.com/fschuetz04/ionic-input-button-highlight
> 
> If:
> 
> An item has lines="full"
> - The item contains an input with a button in its start or end slot
> - The input or its button is focused with the keyboard
> 
> The item shows a black highlight line.
> 
> <img src="https://github.com/ionic-team/ionic-framework/assets/6752601/36f51398-1620-42d5-a7b9-5f596183e8df" width="300" />

**Comment by liamdebeasi** [comment]
Thanks for the report. This will be fixed in the upcoming Ionic 8 release: https://github.com/ionic-team/ionic-framework/pull/29055
