### ISSUE TITLE
bug: Setting an undefined slot causes the IonButton to disappear when it is a child of IonContent 

### ISSUE THREAD

**Issue by aidanm1999** [ionic-team/ionic-framework#26964]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When you pass in `undefined` to an `<IonButton />`'s `slot` property, this gets passed to the DOM and the button does not appear.

### Expected Behavior

The `slot` property should not appear in the DOM as `slot="undefined"` and the button should be visible.

### Steps to Reproduce

Check out the Codesandbox URL below. In our projects, we wrap the `<IonButton />` component with our custom `<Button />`, which pre-sets many attributes to reduce noise and repetitiveness on other documents. 

```typescript
const Button = ({ slot, [...] }) => <IonButton slot={slot} [...] />

// Does not appear
<Button /> 

// Does appear
<Button slot="start" />
```

This seems to be an issue when the `<IonButton />` is a direct descendant of `<IonContent />` however if we wrap the button in an `<IonList />` the button appears.

### Code Reproduction URL

https://codesandbox.io/s/naughty-boyd-3bf20r?file=/src/pages/Home.tsx

### Ionic Info

Ionic:

    Ionic CLI       : 6.20.8
    Ionic Framework : @ionic/react 6.6.1

Capacitor:

    Capacitor CLI      : 4.7.0
    @capacitor/android : 4.7.0
    @capacitor/core    : 4.7.0
    @capacitor/ios     : 4.7.0

Utility:

    cordova-res                          : 0.15.4
    native-run (update available: 1.7.2) : 1.7.1

System:

    NodeJS : v16.17.0
    npm    : 8.18.0
    OS     : macOS

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this, but this does not appear to be a bug in Ionic. Passing a non-existent slot to a Web Component causes it to be hidden.

Here is an example outside of Ionic: https://codepen.io/liamdebeasi/pen/ExeLWob

The "Button with invalid slot" has a non-existent slot of "invalid" which causes it to be hidden.

**Comment by aidanm1999** [comment]
Hi @liamdebeasi, thanks for the quick reply. Fair enough providing a string that the slot does not accept. The main issue is that if we don't pass anything, the slot is set to a string of `"undefined"` where it should not be present in the DOM. 

If you take my example in the Codesandbox, creating a component that wraps the IonButton and does not pass in the slot, the slot will still be present in the DOM `<ion-button slot="undefined" [...]`. The issue is that I am not passing in `"undefined"` as a string, I am just not passing anything in as it would be an optional parameter within `CustomButton`:

```typescript
const CustomButton = ({ slot, [...] }) => <IonButton [...] slot={slot} />;

<CustomButton />
```

and that would render: `<ion-button slot="undefined"></ion-button>` and not `<ion-button></ion-button>`

**Comment by liamdebeasi** [comment]
It's the same reasoning for `undefined` slots too. I'd recommend defaulting to the empty string instead as that seems to work: : https://codepen.io/liamdebeasi/pen/ExeLWob

**Comment by robations** [comment]
https://github.com/ionic-team/ionic-framework/blob/b02190d71f7462b72d93d7793848f1c4416a5a6e/core/src/components/button/button.tsx

I notice there isn't any code for handling slot here. Could the change in behaviour have come from @stencil/core?

**Comment by liamdebeasi** [comment]
There is no behavior change as this is the standard Web Component slot behavior. See https://github.com/ionic-team/ionic-framework/issues/26964#issuecomment-1472049508.

The default value for the `slot` property is the empty string, so I recommend setting "unset" values to that instead of `undefined`.

**Comment by robations** [comment]
We saw the behaviour change in our app on a page where the code has been untouched since mid 2022.

@ionic/core was upgraded (minor/patch update) in February and we recently found the issue above when we found a submit button had disappeared. The core upgrade was the only relevant change that could be causing the issue.

Not particularly disagreeing about standard behaviour for slots, just that there has been a change somewhere, somehow.

**Comment by liamdebeasi** [comment]
Do you have a repo I can try?

**Comment by robations** [comment]
No problem, will try to create/find 👍

**Comment by aidanm1999** [comment]
Thanks @liamdebeasi for the help, will close issue.

> The default value for the slot property is the empty string, so I recommend setting "unset" values to that instead of undefined.

We have added the above and working successfully. Would it be more logical having:

```html
<IonButton slot={undefined} /> => <ion-button />
and
<IonButton slot="" /> => <ion-button slot="" />
```

Just a thought!
