### ISSUE TITLE
bug: `start` hits type errors unless `skipLibCheck` is true in tsconfig

### ISSUE THREAD

**Issue by NoelLH** [ionic-team/ionic-framework#26969]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

It seems like the built-in dev mode `start` command from upgraded projects has stopped being able to compile unless `skipLibCheck` (not on by default) is set. This used to work.

I found some issues here & on Stack Exchange from ~2020 but no indication of work to address the root cause.

The output is very long, with many similar errors, but ends something like:

```
Error: ../../../node_modules/@types/react/index.d.ts:3127:19 - error TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component<any, {}, any>' and 'Component<any, {}, any>'.
  Named property 'refs' of types 'Component<any, {}, any>' and 'Component<any, {}, any>' are not identical.

3127         interface ElementClass extends React.Component<any> {
                       ~~~~~~~~~~~~


Error: ../../../node_modules/@types/react/index.d.ts:3135:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

3135         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  ../../../node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:3089:14
    3089         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.
```

The simplest way to replicate the issue is to run this branch of this open source app: https://github.com/webful-ltd/passwordmaker/tree/demo-no-skiplibs

### Expected Behavior

`npm run start` works without turning off library type checking.

### Steps to Reproduce

1. Clone from https://github.com/webful-ltd/passwordmaker/tree/demo-no-skiplibs
2. Check out remote branch `demo-no-skiplibs`
3. `npm install`
4. `npm run start`

### Code Reproduction URL

https://github.com/webful-ltd/passwordmaker/tree/demo-no-skiplibs

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/Users/noel/.nvm/versions/node/v16.18.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.6.2
   @angular-devkit/build-angular : 15.2.3
   @angular-devkit/schematics    : 15.2.3
   @angular/cli                  : 15.2.3
   @ionic/angular-toolkit        : 8.0.0

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.7.0
   @capacitor/ios     : 4.7.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   ios-sim : 8.0.2
   NodeJS  : v16.18.0 (/Users/noel/.nvm/versions/node/v16.18.0/bin/node)
   npm     : 8.19.2
   OS      : macOS Monterey
   Xcode   : Xcode 14.2 Build version 14C18

**Comment by liamdebeasi** [comment]
Thanks for the report. I'm not able to reproduce this issue in the provided repo. Can you double check to ensure you have pushed all the code required to reproduce the issue?

**Comment by NoelLH** [comment]
> Thanks for the report. I'm not able to reproduce this issue in the provided repo. Can you double check to ensure you have pushed all the code required to reproduce the issue?

@liamdebeasi Yes, I just cloned it again and get the same result. Did you switch to the `demo-no-skiplibs` branch after cloning?

I wondered if something about my global Node version could be involved, so also tried varying that (via nvm). I've now seen the problem on new installs on all of:
* Node v16.18.0 per my original report, and
* Node v16.19.1 with the same global packages and links
* Node v18.15.0 on a completely clean install with no global packages or symlinks

**Comment by NoelLH** [comment]
@liamdebeasi My app itself didn't have those dependencies in its dependency tree or installed packages – but you're right, it's very odd that anything found React packages.

I tried traversing the path 2 levels up to get to where my last crash had its error trace, and found that in my OS-wide home directory's `node_modules`, these type packages were installed – despite the active Node in use / `npm -g` not reporting them as globally installed. Manually deleting the type package directories fixed the problem.

I still have no idea why `ng` would care about typing in these libraries, but my issue is fixed in any case, and is confirmed not Ionic-specific. Thanks for your help!
