### ISSUE TITLE
feat: able to define backButtonText globally and dynamically

### ISSUE THREAD

**Issue by pierresh** [ionic-team/ionic-framework#26963]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently, there are 2 ways to localize the backButtonText.

1. Define the translation in `IonicModule.forRoot()`, see this [message](https://github.com/ionic-team/ionic-framework/issues/17279#issuecomment-1215345519) 
Pro: it works
Cons: it works only for 1 language only, defined before the runtime

2. Define the translation in the HTML element like this `<ion-back-button text="{{ 'BACK' | translate }}"></ion-back-button>`, see this [message](https://github.com/ionic-team/ionic-framework/issues/23672#issuecomment-884893583) 
Pro: it works
Cons: it adds the text for Android also, and it defeats the DRY principle

We need a way to define the translation of the back button after the app's runtime, so that it could be set dynamically according to the language of the end-user, and shown only for iOS

### Describe the Use Case

Multi-lingual app having back buttons built for Android and iOS, in which the language displayed can be configured by the end-user

### Describe Preferred Solution

Something like in Ionic v3, that worked fine. Example:

```
if (this.platform.is('ios')) {
	this.translate.get('BACK').subscribe((value) => {
		this.config.set('backButtonText', value);
	});
}
```

**Comment by liamdebeasi** [comment]
Thanks for the report. How are you handling this right now in your app?

**Comment by pierresh** [comment]
So far, I created a branch in GIT only for iOS, in which we replaced every `<ion-back-button></ion-back-button>` to `<ion-back-button text="{{ 'BACK' | translate }}"></ion-back-button>`. We build our iOS app from this branch.

In the future, I might consider encapsulating the back button into one component, and replacing the back button with that component so that the translation logic would be centralized in one piece of code.

**Comment by liamdebeasi** [comment]
Does wrapping `ion-back-button` in a component and re-using that component work for your use case?

**Comment by pierresh** [comment]
> Does wrapping `ion-back-button` in a component and re-using that component work for your use case?

So far no because it adds HTML tags that break the display in the `ion-toolbar`

**Comment by pierresh** [comment]
> Do you have a repo I can try?

Sorry, we do not use github, but here is my code:

```ts
// back-button.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-back-button',
	template: `
		<ion-buttons slot="start">
			<ion-back-button></ion-back-button>
		</ion-buttons>
	`,
	styles: [],
})
export class BackButtonComponent {}
```

```ts
// back-button.module.ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { TranslateModule } from '@ngx-translate/core';

import { BackButtonComponent } from './back-button.component';

@NgModule({
	declarations: [BackButtonComponent],
	exports: [BackButtonComponent],
	imports: [CommonModule, IonicModule, TranslateModule],
})
export class BackButtonModule {}
```

Then import `BackButtonModule` in the page's module and add the component's HTML tags `<app-back-button></app-back-button>` in `ion-toolbar`

**Comment by pierresh** [comment]
Ah, yes it seems working well, thanks! :)

I have done that way:
```ts
// back-button.component.ts
import { Component } from '@angular/core';
import { Platform } from '@ionic/angular';

@Component({
	selector: 'app-back-button',
	template: `
		<ion-back-button
			[text]="(platform.is('ios') ? 'BACK' : '') | translate"
		></ion-back-button>
	`,
	styles: [],
})
export class BackButtonComponent {
	constructor(private platform: Platform) {}
}
```

And in the HTML page:
```html
<ion-toolbar>
	<ion-buttons slot="start">
		<app-back-button></app-back-button>
	</ion-buttons>
	<ion-title>{{ 'MY_TITLE' | translate }}</ion-title>
</ion-toolbar>
```
