### ISSUE TITLE
bug: ion-datetime errors crashes in basic usage

### ISSUE THREAD

**Issue by haikyuu** [ionic-team/ionic-framework#26988]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Loading `ion-content` in an Imba project crashes with the following error

```
Uncaught TypeError: Cannot read properties of undefined (reading 'month')
    at isSameDay (chunk-DFGB2I4G.js?v=0883b739:316:43)
    at getCalendarDayState (chunk-DFGB2I4G.js?v=0883b739:4263:19)
    at chunk-DFGB2I4G.js?v=0883b739:5139:78
    at Array.map (<anonymous>)
    at proxyCustomElement.color.renderMonth (chunk-DFGB2I4G.js?v=0883b739:5134:106)
    at chunk-DFGB2I4G.js?v=0883b739:5189:19
    at Array.map (<anonymous>)
    at proxyCustomElement.color.renderCalendarBody (chunk-DFGB2I4G.js?v=0883b739:5188:152)
    at proxyCustomElement.color.renderCalendar (chunk-DFGB2I4G.js?v=0883b739:5193:117)
    at proxyCustomElement.color.renderDatetime (chunk-DFGB2I4G.js?v=0883b739:5305:16)
```

### Expected Behavior

It should work

### Steps to Reproduce

stackblitz reproduction

### Code Reproduction URL

https://stackblitz.com/edit/vitejs-ionic-date-bug?file=main.js,vite.config.js,main.imba&terminal=dev

### Ionic Info

[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.14.2
   npm    : 7.17.0
   OS     : Linux 5.0

### Additional Information

Since this seems like an external bug (related to using Ionic in Imba projects), I'm interested in fixing it. I'd appreciate some pointers.

I tried to investigate but I don't see the root of the issue

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this behavior, but this does not appear to be an Ionic bug. Imba appears to be calling the `render` method on `ion-datetime` before Stencil, the Web Component compiler Ionic uses, has a chance to set up the component: https://github.com/imba/imba/blob/b3c98c39ce5834cf1b3ab44817596a34091be984/packages/imba/src/imba/dom/component.imba#L140

The code inside of datetime's render method relies on data that is setup in `componentWillLoad` which Stencil calls before it calls `render` for the first time.

There probably needs to be a check here to exclude custom elements.

**Comment by haikyuu** [comment]
Thanks for your help @liamdebeasi I will fix the bug in Imba then. 🤩
