### ISSUE TITLE
bug: ion-datetime month and year changes when trying to select a date on none english locale

### ISSUE THREAD

**Issue by eranf91** [ionic-team/ionic-framework#26992]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

https://user-images.githubusercontent.com/23518521/226718776-8e45ed76-be8f-4f13-b3a8-96c92b1c7806.mp4

### Ionic Framework Version

v6.x

### Current Behavior

when configuring a device or browser on none English locale, the ion-date-time is completely unstable, clicking the day, changes the month to the previous one.

### Expected Behavior

month should be changed only when user wants to change it and by using the relevant dialog.

### Steps to Reproduce

1. put the following in the html (with relevant fixes:
2. `  <ion-item (click)="showPicker = !showPicker">
    <ion-label>title</ion-label>
    <ion-text slot="end">{{ date }}</ion-text>
  </ion-item>
  <ion-datetime *ngIf="showPicker"  presentation="date" [value]="date" size="cover" (ionChange)="updateValue($event)"></ion-datetime>`

3. start the project with the none english locale (in my case it was Hebrew)
4. start play with component and see for the strange behavior.

### Ionic Info

    "@ionic-native/fcm": "5.36.0",
    "@ionic-native/globalization": "5.36.0",
    "@ionic-native/in-app-browser": "5.36.0",
    "@ionic-native/splash-screen": "5.36.0",
    "@ionic-native/status-bar": "5.36.0",
    "@ionic/angular": "6.6.2",

### Additional Information

angular version:
    "@angular/animations": "12.2.17",
    "@angular/common": "12.2.17",
    "@angular/core": "12.2.17",
    "@angular/forms": "12.2.17",
    "@angular/platform-browser": "12.2.17",
    "@angular/platform-browser-dynamic": "12.2.17",
    "@angular/router": "12.2.17",

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
