### ISSUE TITLE
feat: Provide support for positioning of confirmation buttons in ion-datetime

### ISSUE THREAD

**Issue by Draganlazarev90** [ionic-team/ionic-framework#26993]
**Ionic version:**

[x ] **6.x**

**I'm submitting a ...** 

[ ] bug report
[x ] feature request

It would be nice to have support for positioning of confirmation buttons for example [confirmationButtonsPos]="'top'", or have some shadow dom elements exposed like: datetime-header datetime-footer

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please provide a use case for this feature request?

**Comment by Draganlazarev90** [comment]
Lets say I update Ionic v5 to v6, all of a sudden ion-datetime looks a lot different than in v5. In v5 it was creating a picker component in the background where the confirmation actions were on top. Now I can wrap ion-datetime in a modal, which is fine, but if I use [showDefaultButtons]="true", or even if I make my own buttons they will still show bottom. The whole idea is to mimic the same design as v5 without manually creating picker
![v5](https://user-images.githubusercontent.com/23295567/227226511-19542b12-14b1-4bfe-a786-1b733e330fe0.png)
![v6](https://user-images.githubusercontent.com/23295567/227226514-012b0b08-53ad-4f6e-bd46-83a52c0bbc99.png)
