### ISSUE TITLE
bug: ion-segment does not fire (ionChange) when [value] is toggled after programmatic value change

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#27002]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

`ion-segment` is not firing value changes when values are changed programmatically, then changed via a click back to the previous value. See video:

https://user-images.githubusercontent.com/362329/227047304-b162c33c-ac6a-4cec-b36a-1d39566ec80b.mov

### Expected Behavior

`ionChange` should be fired when the segment is changed.

### Steps to Reproduce

1. Run reproduction app
2. Value of segment should start on 'General'
3. Click the `ion-button` for "versions" under the segment 
![Screenshot 2023-03-22 at 5 56 07 PM](https://user-images.githubusercontent.com/362329/227047628-6c3bf76c-e7c3-41a4-a60b-517adb914088.png)
4. Click the `ion-segment` 'General' button to return to the previous segment
5. The `ion-segment` will appear to change back to the "General" value
6. Notice that the value of the back-end BehaviorSubject has not updated because the `updateSegment` method has not been called when it should have been. The segment changed but the `(ionChange)` event never fired

### Code Reproduction URL

https://github.com/lincolnthree/ionic-bug-ion-segment/tree/value-changes

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (/Users/lincoln/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.0-dev.11676644846.156e8507
   @angular-devkit/build-angular : 15.1.6
   @angular-devkit/schematics    : 15.1.6
   @angular/cli                  : 15.1.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.3
   @capacitor/android : not installed
   @capacitor/core    : 4.6.3
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v16.14.0 (/Users/lincoln/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.3.1
   OS     : macOS

  ─────────────────────────────────────────────────

**Comment by liamdebeasi** [comment]
Thanks! Can you give this dev build a shot?

```
npm install @ionic/angular@7.0.0-dev.11679581404.151a30f6
```

**Comment by lincolnthree** [comment]
It works :) Thanks @liamdebeasi - Starting to need a new RC so I can test all these fixes at once, lol.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27010, and a fix will be available in an upcoming release of Ionic Framework.
