### ISSUE TITLE
bug: radio group does not participate in form submission

### ISSUE THREAD

**Issue by kristojorg** [ionic-team/ionic-framework#27016]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Using react, I render a form with radio options and a submit handler. I would expect the radio options to be included in the form data on submit, but this is not the case. It appears this is because the `IonRadio` element does not properly render an `<input type="radio" />` element. 

### Expected Behavior

The formdata should include the value of the selected radio.

### Steps to Reproduce

1. Open the stackblitz link
2. select a radio option
3. click sumbit
4. check the console log to see the empty form data object.

### Code Reproduction URL

https://stackblitz.com/edit/angular-kzrgpo?file=src/main.tsx

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.8 (/Users/kristo/.nvm/versions/node/v16.13.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.4.1 (/Users/kristo/d/ereading-clients/node_modules/@ionic/react)

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : 4.6.1 (/Users/kristo/d/ereading-clients/node_modules/@capacitor/android)
   @capacitor/core    : 4.6.1 (/Users/kristo/d/ereading-clients/node_modules/@capacitor/core)
   @capacitor/ios     : 4.6.1 (/Users/kristo/d/ereading-clients/node_modules/@capacitor/ios)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.13.1 (/Users/kristo/.nvm/versions/node/v16.13.1/bin/node)
   npm    : 9.6.2
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the report. Here is a dev build with a proposed fix if you are interested in testing:

```
npm install @ionic/react@6.7.1-dev.11679668518.1b8db647 @ionic/react-router@6.7.1-dev.11679668518.1b8db647
```

**Comment by kristojorg** [comment]
Nice, thanks so much for the quick fix! Just tested and it works great : )

**Comment by liamdebeasi** [comment]
Glad the dev build works! I am going to keep this open until https://github.com/ionic-team/ionic-framework/pull/27018 is merged.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27018, and a fix will be available in an upcoming release of Ionic Framework.
