### ISSUE TITLE
bug: ion-select label not displayed in the header of the alert

### ISSUE THREAD

**Issue by MimyyK** [ionic-team/ionic-framework#27028]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In v7 with Vue, when I use `label` on `ion-select`, the label is not displayed in the header of the alert:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/1482715/227892258-87142968-e51f-49f7-8544-a573518fb5eb.png">

```
      <ion-select label="Default label" placeholder="Favorite Fruit">
        <ion-select-option value="apple">Apple</ion-select-option>
        <ion-select-option value="banana">Banana</ion-select-option>
        <ion-select-option value="orange">Orange</ion-select-option>
      </ion-select>
```

In v6, the label was displayed:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/1482715/227902530-a540f0aa-330d-4a55-8c35-2624693d75e5.png">

### Expected Behavior

Display label in alert header

### Steps to Reproduce

1. click on the select field "Default label"
2. an alert is opened to select a fruit -> there is no "Default label" alert header

### Code Reproduction URL

https://stackblitz.com/edit/angular-uzcxdk?file=src%2Fcomponents%2FExample.vue

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.20.6 
   Ionic Framework : @ionic/vue 7.0.0-rc.3

Capacitor:

   Capacitor CLI      : 4.7.1
   @capacitor/android : 4.7.1
   @capacitor/core    : 4.7.1
   @capacitor/ios     : 4.7.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.12.1 
   npm    : 9.2.0
   OS     : macOS
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Here is a dev build if you are interested in testing a proposed fix:

```
npm install @ionic/vue@7.0.0-dev.11679946879.11de5665 @ionic/vue-router@7.0.0-dev.11679946879.11de5665
```

(You may need to manually run `npm install` in your StackBlitz sample)

**Comment by MimyyK** [comment]
Thanks for the fix and it works great ^^

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27034, and a fix will be available in an upcoming release of Ionic Framework.
