### ISSUE TITLE
bug: Ionic Angular Modal not working when content is heigher than device height

### ISSUE THREAD

**Issue by herobarua** [ionic-team/ionic-framework#27020]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When content is heigher than device height, that it crop on bottom of the screen and as well we are not able to scroll end of the page.

https://user-images.githubusercontent.com/1532317/227568609-aa22eb27-43f2-4d3e-aa34-f5b1c30221d1.MP4

### Expected Behavior

When content is heigher than device height, it should scrollable and bottom should not be cropped.

### Steps to Reproduce

1. Create any ionic Modal and put the long content which will be heigher than deivce height
2. Add initalbreakpoint 0.96 and breakpoint [0, 0.96], that time you can see it will not scrolable and bottom content crop.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.7.0
   @angular-devkit/build-angular : 13.3.10
   @angular-devkit/schematics    : 13.3.10
   @angular/cli                  : 13.3.10
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.7.0
   @capacitor/ios     : 4.7.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v14.20.0 (/usr/local/bin/node)
   npm    : 6.14.17
   OS     : macOS

**Comment by ipehimanshu** [comment]
yes true, 

same issue our end.

**Comment by sean-perkins** [comment]
@herobarua thank you for reporting this issue.

Is your issue different than https://github.com/ionic-team/ionic-framework/issues/24583 or https://github.com/ionic-team/ionic-framework/issues/24631?

**Comment by herobarua** [comment]
@sean-perkins yes issue alost same. but issue is showing when it started to test real device. Long content never be scrollable.

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
