### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by SossenSystems** [ionic-team/ionic-framework#27039]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have two inputs under each other, when I switch between the default input and the password input on ios (also only tested on ios), I have the problem with the keyboard, because I have a "save" button that is always at the bottom and when the keyboard is opened, it automatically adjusts so that the button is always visible. Now the real problem is that something is wrong with the keyboard, because as soon as I click into another input, the button is on the actual floor instead of above the keyboard, as far as I could see, it's somehow because the hide event is triggered, even though a new keyboard opens

### Expected Behavior

The button should always be on the floor, unless the keyboard is up, in which case it should be above the keyboard.

### Steps to Reproduce

1.) Create two inputs.
2.) Create a button

<template>
  <ion-page>
    <ion-content :fullscreen="true" :scroll-x="false" :scroll-y="false">
      [...]
        <ion-item lines="none" color="none" class="bg-gray-100/20 px-4 rounded-2xl">
          <ion-label position="stacked">E-Mail Address</ion-label>
          <ion-input v-model="input.email"></ion-input>
        </ion-item>
        <ion-item lines="none" color="none" class="bg-gray-100/20 px-4 rounded-2xl mt-5">
          <ion-label position="stacked">Password</ion-label>
          <ion-input v-model="input.password" type="password"></ion-input>
        </ion-item>
       [...]
    </ion-content>
    <ion-footer>
      <FixedButton text="Continue" :disabled="input.email.length <= 5 || input.password.length <= 6" />
    </ion-footer>
  </ion-page>
</template>

FixedButton.vue:
<template>
  <div ref="button" class="button-keyboard safe-area-bottom animate__animated animate__fadeInUp">
    <form @submit.prevent="confirm">
      <button class="ev-button inline-block w-full mx-auto animate__animated animate__fadeInUp" type="submit"
              :disabled="disabled">{{ text }}
      </button>
    </form>
  </div>
</template>
.button-keyboard {
  @apply absolute left-0 bottom-0 right-0 mb-4 px-8 w-full;
  transition: all .2s ease;
}

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.9 (/Users/boss/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.6.1

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.7.1
   @capacitor/ios     : 4.7.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/Users/boss/.nvm/versions/node/v18.15.0/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
