### ISSUE TITLE
feat: ion-datetime highlightedDates allows either array or callback not both. 

### ISSUE THREAD

**Issue by seatechdev** [ionic-team/ionic-framework#27046]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The recently added feature highlightedDates allows either an array or callback but not both.  I would like to request another option that can be used along with highlightedDates called decoratedDates.  

### Describe the Use Case

Use Case:
1. I want every mon, wed, friday highlighted as blue when the calendar is displayed.  
2. But if I have events on mon, wed, friday, saturday - I want to set those dates in orange.  Or show a a dot below those dates indicating that there is an event.  The dot treatment is preferred.

### Describe Preferred Solution

<ion-datetime
  presentation="date"
  value="2023-01-01"
  [highlightedDates]="highlightedDates" // For callbacks
  [decoratedDates]="decoratedDates" // for Events that come from an array (or a web service). 
></ion-datetime>

**Comment by seatechdev** [comment]
I tried using the examples posted on[ionic datetime documentation](https://ionicframework.com/docs/api/datetime).  In one case highlightedDates is an array in the example.component.ts file and in the other it is a function.  If you go to the [angular calendar kitchen sink  ](https://mattlewis92.github.io/angular-calendar/#/kitchen-sink) all these examples are feasible.

**Comment by liamdebeasi** [comment]
You should be able to get the desired behavior using `highlightedDates`. Here is an example: https://codepen.io/liamdebeasi/pen/LYJvrzK?editors=1010

**Comment by seatechdev** [comment]
Thanks for the codepen.  I looked at it.  A question about the switch statement.   

const hasEvent = (isoDate) => {
  switch(isoDate) {
    case "2023-03-13":
    case "2023-03-17":
    case "2023-03-08":
      return true;
    default:
      return false;  
  }


How would you make a switch statement from an array received from an API response with lets say more than 100 records.  For example, the format can be:

mydata = [
    {
      date: '2023-01-05',
      eventname: 'some event name',
      location: 'some location',
    },
    {
      date: '2023-01-10',
      eventname: 'some event name',
      location: 'some location',
    },
    {
      date: '2023-01-20',
      eventname: 'some event name',
      location: 'some location',
    },
    {
      date: '2023-01-29',
      eventname: 'some event name',
      location: 'some location',
    }
  ];

And obviously when I tap on one of dates, I want to see the events detail.  That is out of scope for this request.  But I need to get around the switch statement.

**Comment by liamdebeasi** [comment]
`ion-datetime` is not meant to be used in this way. The highlighted dates feature is useful for calling out recurring dates (such as birthdays) or a handful of dates in the future (such as a due date). It's not really meant to be used for a calendar interface that could have large amounts of data on each month that you would need to load asynchronously. For this, you're probably better off using a different component like the one you mentioned in https://github.com/ionic-team/ionic-framework/issues/27046#issuecomment-1488764985.

**Comment by seatechdev** [comment]
Thanks!  I guess then the feature request should be that we need a calendar like capability in Ionic.  It is a very common use case and so many developers can use it.  The ion-datetime interface is almost there. And it is not difficult to display a list of events below the ion-datetime component.  The third party components are great but they still have limitations and developers update them as they wish. Not to mention that they can abandon them anytime. Theoretically, I can use the angular calendar but even that requires so many css changes to make it fit in an Ionic app.

**Comment by liamdebeasi** [comment]
We don't have plans to add calendar functionality to Ionic at this time. As similar as they may seem, a date picker and a calendar interface are very different in terms of requirements.

We've gotten similar requests like this in the past where developers want to use `ion-datetime` as a calendar interface (example: https://github.com/ionic-team/ionic-framework/issues/25730). The calendar requirements significantly increase the scope of `ion-datetime`, and it's not something we have the bandwidth to do at the moment.
