### ISSUE TITLE
bug: ion-accordion-group animations not completely disabled with animated="false" and expand="inset"

### ISSUE THREAD

**Issue by ReneZeidler** [ionic-team/ionic-framework#27047]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Setting `animated="false"` on an `ion-accordion-group` with `expand="inset"` does not completely disable animations in MD mode.

Specifically, the extra margin for expanded `ion-accordion`s still gets animated, while all other animations are disabled.

### Expected Behavior

Setting `animated="false"` should disable all animations, including the extra margin in MD mode.

### Steps to Reproduce

1. Create an `ion-accordion-group` with `animated="false"` and `expand="inset"` with at least two items (see Stackblitz example)
2. Open the application in MD mode
3. Toggle one of the accordions

### Code Reproduction URL

https://stackblitz.com/edit/ion-accordion-inset-animation

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.8 (/usr/local/share/npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.7.0
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 8.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.12.1 (/usr/local/bin/node)
   npm    : 9.6.2
   OS     : Linux 5.10
```

### Additional Information

The `accordion-animated` class is still present on `ion-accordion`s even when the `ion-accordion-group` has `animated="false"`. The extra margin gets animated with a CSS transition depending only on that class. Removing the class manually with the browser dev tools fixes this issue.

**Comment by amandaejohnston** [comment]
Thank you for the issue, and for the additional investigation into the cause 👀 I'm able to reproduce this behavior. The issue is that the `accordion-animated` class does not account for setting the `animated` property on the accordion group itself, as you described. ([Relevant line](https://github.com/ionic-team/ionic-framework/blob/4b822eac5df9e5caa09d56cd1603486996d41429/core/src/components/accordion/accordion.tsx#L420))
