### ISSUE TITLE
bug: Black screen on production apps (iOS + Android) without an update: Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function

### ISSUE THREAD

**Issue by iAMkVIN-S** [ionic-team/ionic-framework#27059]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v5.x

### Current Behavior

Production apps on iOS and Android are now a black screen for all users. This app has not been updated since January 5th 2023.

Same issue with `ionic serve`

Error in console:
`Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

<img width="965" alt="image" src="https://user-images.githubusercontent.com/40800721/228676306-adef92d7-200f-4301-9948-c5d5b45a7ed9.png">

### Expected Behavior

Not having a black screen

### Steps to Reproduce

Open the production app on iOS or Android -> Get a black screen
Open the ionic project locally and run `ionic serve` -> Get a black screen

### Ionic Info

onic:

   Ionic CLI       : 6.12.4 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.9.4

Capacitor:

   Capacitor CLI   : 4.7.0
   @capacitor/core : 4.7.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v16.17.1 (/usr/local/bin/node)
   npm    : 8.15.0
   OS     : macOS

**Comment by mlynch** [comment]
Are you using Google maps? This tweet suggests the issue in in their JS library: https://twitter.com/luisdalopez56/status/1641196286035591168?s=20

**Comment by iAMkVIN-S** [comment]
We indeed have Google Maps in the App.

Moving to their github.

**Comment by iAMkVIN-S** [comment]
To be honest, it's taking me a bit to even find the proper github repo... **so many**

**Comment by liamdebeasi** [comment]
This appears to be the bug report: https://issuetracker.google.com/issues/275849045
