### ISSUE TITLE
feat: Expose scss breakpoints

### ISSUE THREAD

**Issue by realappie** [ionic-team/ionic-framework#27063]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Simply expose this through a const or CSS variable construction of sorts

https://github.com/ionic-team/ionic-framework/blob/5e030f996a463b5ff0eea22cef3bcbec21426c1f/core/src/themes/ionic.globals.scss#L27-L33

Or

https://github.com/ionic-team/ionic-framework/blob/451d2204e79a4a10c1eb829ab0bd75c137b02475/core/src/components/split-pane/split-pane.tsx#L10-L17

### Describe the Use Case

I want to show / hide elements based on the split pane hiding, right now I have to hardcode the breakpoint which the split pane uses which is 576px. Ideally I use the same value the split pane uses under the hood, to avoid risking out of sync problems should the team update the 576px value to something else internally.

### Describe Preferred Solution

~~There seems to be duplication in your own codebase, the SASS `$screen-breakpoints` is sometimes used, and in the case of split pane component its hardcoded. Ideally you simplify this by using CSS variables.~~

**Edit**

CSS variables dont work in media queries, so exposing the CSS map is only viable solution here

https://stackoverflow.com/questions/40722882/css-native-variables-not-working-in-media-queries

**Comment by sean-perkins** [comment]
Hello @realappie thanks for this feature request!

In your use case, is there a reason that the [`ionSplitPaneVisible`](https://ionicframework.com/docs/api/split-pane#events) event on `ion-split-pane` wouldn't provide the information you are needing of responding to elements showing/hiding in the split pane?

Are you needing to know what breakpoint is being shown? If so, that information could be added to the event detail.
