### ISSUE TITLE
bug: Ionic 7 - 'hidden' attribute no longer has effect on ion-progress-bar

### ISSUE THREAD

**Issue by NorthFred** [ionic-team/ionic-framework#27065]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

```
<ion-progress-bar [hidden]="true" type="indeterminate"></ion-progress-bar>
```

The  [hidden] attribute no longer has any effect on the <ion-progress-bar> component. It is always shown.

### Expected Behavior

Observed when migrating from Ionic 6 to Ionic 7.  In Ionic 6, the progress bar was successfully hidden. In Ionic 7, the progress bar can no longer be hidden from the view.

### Steps to Reproduce

1. Create an Ionic Angular page with a progress bar
2. Add the 'hidden' attribute to the progress bar and set it to 'true'
3. Serve the project
4. Verify that the progress bar can be hidden from view

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.0 (C:\Users\xxxxxxxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 9.0.0

**Comment by liamdebeasi** [comment]
Thanks for the report. This is a documented breaking change in Ionic v7: https://github.com/ionic-team/ionic-framework/blob/feature-7.0/BREAKING.md#version-7x-hidden-attribute

There is code on this page to get the old behavior.

**Comment by NorthFred** [comment]
@liamdebeasi Thanks, I totally overlooked that one...
