### ISSUE TITLE
bug: `ion-select` with popover interface shows warnings when opened

### ISSUE THREAD

**Issue by StefanNedelchev** [ionic-team/ionic-framework#27071]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When we have `<ion-select>` input with `interface="popover"` and we open the popover, the following warnings are thrown for each option:
```
[Ionic Warning]: ion-radio is being used with the "legacy" property enabled which will forcibly enable the legacy form markup. This property will be removed in an upcoming major release of Ionic where this form control will use the modern form markup.

Developers can dismiss this warning by removing their usage of the "legacy" property and using the new radio syntax. 
<ion-radio class="sc-ion-select-popover-ios">
```
This can be observed even on the official components docs: 
https://ionicframework.com/docs/api/select#popover

### Expected Behavior

No errors or warnings to be logged.

### Steps to Reproduce

1. Add `<ion-select>` component with a popover interface (`interface="popover"`) and add a few options inside. You can also just open the official example at 
https://ionicframework.com/docs/api/select#popover
2. Open the browser console
3. Click on the select to open the popover

### Code Reproduction URL

 https://ionicframework.com/docs/api/select#popover

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.9 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.1
   @capacitor/android : not installed
   @capacitor/core    : 4.7.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/usr/bin/node)
   npm    : 9.6.2
   OS     : Linux 5.19

**Comment by sean-perkins** [comment]
Hello @StefanNedelchev thanks for reporting this issue!

We have a ticket internally to track this (FW-3480). The modern syntax of `ion-select` with `interface="popover"` has some extra style conditions that we needed to account for, that we were unable to complete prior to the v7 release. 

Fortunately the warning is just notifying developers that the legacy syntax is being used. Your applications should continue to function as expect with the select in the interim of Ionic updating the internal usage to use the modern syntax.

I'll track this as a bug for visibility of similar reports.

**Comment by snr-lab** [comment]
This bug is reproducible with ionic version 7.1.1
Is there any estimated timeline to fix it?

**Comment by simaxme** [comment]
I do also have this bug.
With 40-50 options in the ion-select, the messages do really get quite annoying.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27818, and a fix will be available in an upcoming release of Ionic Framework.
