### ISSUE TITLE
feat: Browser Push component (permissions request/messages)

### ISSUE THREAD

**Issue by strarsis** [ionic-team/ionic-framework#27082]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

With iOS/iPad OS/Safari now also supporting Browser Push / Web Notifications API support, 
it would be great when Ionic Framework adds a component for handling Browser Push.

### Describe the Use Case

Browser Push handling, as requesting permissions and processing and displaying inbound push messages.

### Describe Preferred Solution

A dedicated browser push component.

### Describe Alternatives

Adding an external component for handling browser push.

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please detail what you have already tried and why those do not work for your use case? I'm not sure I understand what the request is here. Most of the work required to get Web Push working is done through JS, so no UI component should be needed here.

**Comment by strarsis** [comment]
So ideally a component that can be added that accepts a notification endpoint it can use for notifications (even better: Server Side Events (SSE) or Web Sockets or Polling as fallback). New push notifications would be made available as hook or something else in e.g. React and then the notification can be shown as web notification, using a separate, Web Notification component (as not all notifications may come from browser push).
But as a worker needs to be set up for this and run in the background I am not sure whether just a component would suffice.

**Comment by liamdebeasi** [comment]
Thanks for the additional information. This is outside the scope of what Ionic Framework handles, so we do not have plans to add this kind of functionality. Ionic Framework is responsible for the user interface of your application, and does not handle any native permissions or functionality. I am going to close this, but let me know if you have questions.
