### ISSUE TITLE
bug: Can't bind to 'environmentInjector' since it isn't a known property of 'ion-router-outlet'

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-framework#27088]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have upgraded my Angular application to standalone components (not updated my routes modules yet) and Ionic to v7, everything works except when I add the required `environmentInjector`.

### Expected Behavior

Thought the env injector is globally injectable so should work on tabs and ion router.

### Steps to Reproduce

```ts
import { Component, EnvironmentInjector } from '@angular/core'
import { IonicModule } from '@ionic/angular'

import { AppTheme } from '@/core/theme'

import { AppService } from './app.service'
import { MenuComponent } from './features/menu/menu.component'

@Component({
  selector: 'app-root',
  template: `
<ion-app>
  <ion-split-pane contentId="main-content">
    <app-menu contentId="main-content"></app-menu>
    <ion-router-outlet
      id="main-content"
      [environmentInjector]="environmentInjector"
    ></ion-router-outlet>
  </ion-split-pane>
</ion-app>
  `,
  standalone: true,
  imports: [IonicModule, MenuComponent],
})
export class AppComponent {
  constructor(public environmentInjector: EnvironmentInjector) {}
}
```

### Code Reproduction URL

Working on it

### Ionic Info

[WARN] Error loading @ionic/angular package.json: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package' is
       not defined by "exports" in /Users/marvin/Developer/M8FINDER/M8FINDER/node_modules/@ionic/angular/package.json

Ionic:

   Ionic CLI                     : 7.0.0
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.7.3
   @capacitor/core    : 4.7.3
   @capacitor/ios     : 4.7.3

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.15.0 (/Users/marvin/.local/share/pnpm/nodejs/18.15.0/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown

**Comment by StefanNedelchev** [comment]
You don't need it anymore, please read the breaking changes of v7. Just remove it

**Comment by muuvmuuv** [comment]
Oh, sorry, I did read it, but not the complete list.

> For anyone else: https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#javascript-frameworks
