### ISSUE TITLE
bug: Superflous nodes added to container components

### ISSUE THREAD

**Issue by Erudition** [ionic-team/ionic-framework#27089]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When I use e.g. `ion-footer`, I have this in my HTML:

```
<ion-footer translucent="true" role="contentinfo" class="md footer-md footer-translucent footer-translucent-md footer-toolbar-padding hydrated">
<!---->
<ion-tab-bar role="tablist" class="md hydrated" style="width: 100%;"> {...}
</ion-footer>
```

That `<!---->` is not mine, it's added by the webcomponent.

Unfortunately, the node then [requires cleaning](https://www.sitepoint.com/removing-useless-nodes-from-the-dom/) before I can use it with my framework (Elm), because it shifts the offset of all the children off by one, causing the virtual DOM diffing engine to lose track of it! (This crashes my app with rapid error spam)

### Expected Behavior

No superfluous nodes are added to the DOM by the components or their hydration process.
In my framework, if a dom node really must be added that was not defined declaratively in advance, it's only safe to add it to the end of the node list, or better yet, inside Shadow DOM.

### Steps to Reproduce

1. Define an ion-footer and let the app hydrate.

### Ionic Info

Using the latest js file directly for now, so no `ionic` command.
`https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js`

**Comment by Erudition** [comment]
![image](https://user-images.githubusercontent.com/3915447/229979087-65acc042-ff62-4fad-95d2-cf7d65970eec.png)

This is what I'm talking about. You can reproduce it in any page that pulls in the CDN scripts.

Here's an example on Ellie:
https://ellie-app.com/msh9vwTgp5xa1
Hit compile to run the elm application. Inspect the "Footer" element to see the above, with the stray html comment.
https://ellie-app.com/mshpfJn3WXGa1

**Comment by liamdebeasi** [comment]
Thanks for the additional info. Stencil, the project that Ionic Framework uses under the hood, uses comment nodes to keep track of certain information at runtime. One example is keeping track of encapsulation "boundaries" for components that do not use Shadow DOM (such as `ion-footer`).

Ionic Framework is working as intended here, but perhaps you could open an issue with the Elm author to see if there is something they are able to account for?

**Comment by Erudition** [comment]
Well, Elm needs the (non-shadow) DOM to not arbitrarily shift indexes, so it can keep track of it, that's by design as Elm is what's building and diffing my DOM in the first place. Elm won't change that any time soon, so you could punt it to an Elm issue, but I see this potentially being a problem with other solutions as well...

Can you elaborate on the justification for `<!---->` here? As described, I now remove these nodes immediately upon creation and I'm not running into any problems with "loosing track of encapsulation boundaries" that I know of. 

Is there a way I can add that comment in advance, so Stencil can reuse it? That would be a good workaround.

**Comment by liamdebeasi** [comment]
Stencil uses `<!---->` as a way of tracking component boundaries for non-Shadow DOM components. This is done so it knows where to append elements such as `<style>`. This is not needed for Shadow DOM components since Stencil uses the Shadow Root as the boundary.

> Is there a way I can add that comment in advance, so Stencil can reuse it? That would be a good workaround.

You could certainly request a feature from the Stencil team here: https://github.com/ionic-team/stencil However, this comment node seems pretty crucial to non-Shadow DOM component behavior, so I'm not sure if they would make changes to it.
