### ISSUE TITLE
bug: Label not aligned properly between ion input and ion select when in card component

### ISSUE THREAD

**Issue by judsonmusic** [ionic-team/ionic-framework#27086]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Notice in the screen shot when every i put inputs inside of an ion card side by side the select label is pushed down by a few pixels.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/2080617/229339149-cc9002ee-873c-4ffc-ab4b-e5c1f133f12a.png">

Code:
```
 <form>
    <ion-card #cardmedtype>
      <ion-card-header color="primary">
        <ion-card-title><strong>Choose a Medication Type</strong></ion-card-title>
      </ion-card-header>
      <ion-card-content>
        <ion-grid>
          <ion-row>
            <ion-col>
              <ion-item>
                <ion-input label="input" labelPlacement="stacked"></ion-input>
              </ion-item>
            </ion-col>
            <ion-col>
              <ion-item>
                <ion-select label="select" labelPlacement="stacked"></ion-select>
              </ion-item>
            </ion-col>
          </ion-row>
        </ion-grid>
      </ion-card-content>
    </ion-card>
  </form>
```

However removing it from the ion card solves the issue. 

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/2080617/229339241-e921f1aa-1903-4e3a-a19e-cd1ed1f3a703.png">

Code:
```
  <form>
    <ion-grid>
      <ion-row>
        <ion-col>
          <ion-item>
            <ion-input label="input" labelPlacement="stacked"></ion-input>
          </ion-item>
        </ion-col>
        <ion-col>
          <ion-item>
            <ion-select label="select" labelPlacement="stacked"></ion-select>
          </ion-item>
        </ion-col>
      </ion-row>
    </ion-grid>
  </form>
```

### Expected Behavior

I should be able to see the labels aligned on the same horizontal axis regardless of whether or not they are in a card.

### Steps to Reproduce

Create ion input with label and ion select with label side by side using ion-col (grid)
You will see the label are aligned horizontally.
However inside a card this is not the case.

[https://stackblitz.com/edit/ionic7-label-test?file=src/app/app.component.html](https://stackblitz.com/edit/ionic7-label-test?file=src/app/app.component.html)

<img width="805" alt="image" src="https://user-images.githubusercontent.com/2080617/229339452-cededf45-9117-461d-abe7-c3166ba0acbb.png">

My workaround for now...

```
import { Directive, ElementRef } from '@angular/core';

@Directive({
  standalone: true,
  selector: 'ion-select'
})
export class SelectLabelFixDirective {
  constructor(private el: ElementRef) {
    // console.warn('We have an ion select!', el.nativeElement);
    const shadowRoot: DocumentFragment = this.el.nativeElement.shadowRoot;
    if (shadowRoot) {
      // console.warn('Fix Stacked Element Nested.: ', shadowRoot);
      var style = document.createElement('style');
      style.innerHTML = '.select-wrapper{ line-height: 18px; }';
      shadowRoot.appendChild(style);
    }
  }
}

```

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.0 (/Users/asd/.nvm/versions/node/v16.18.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v16.18.0 (/Users/asd/.nvm/versions/node/v16.18.0/bin/node)
   npm    : 9.6.2
   OS     : macOS Unknown

**Comment by judsonmusic** [comment]
@sean-perkins this is a good one for you :) My work around is sketchy but it works. Hope this can get solved. Super weird.

**Comment by liamdebeasi** [comment]
Thanks for the report. It looks like the `ion-card` line height styles are being inherited to `ion-select`. 

Our global normalize styles applies `line-height: normal` to `label` elements: https://github.com/ionic-team/ionic-framework/blob/1638749be341ec05a96e74f46e65c5f72ad587a9/core/src/css/normalize.scss#L84

This works for `ion-input` because the `<label>` is in the Light DOM. The label on `ion-select` is in the Shadow DOM.

To fix this we should probably apply `line-height: normal` to the labels on input, textarea, and select. (There should be no visible change to input/textarea, but this avoids the issue in the event we move those components to use the Shadow DOM in the future)
