### ISSUE TITLE
bug: TypeError: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by devzakir** [ionic-team/ionic-framework#27091]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Gives an error while navigating on certain pages, sometime it gives an error sometimes not. odd behavier. 
On my mac, I am getting this error sometimes, but My team members are getting this error very often. 

Detailed Loom
https://www.loom.com/share/dfcf5e59aa2b4d578d71fb6ca20873e0

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pathname')
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/33604077/229424440-0574f446-1ce1-46e2-81e7-f51d4f09c251.png">

### Expected Behavior

Smoth Routing Experience across all OS

### Steps to Reproduce

1. Run the project 
2. Go to Browse Jobs and then Job Details
3. Reload the page few times or go back to homepage and try to visit again. 

### Code Reproduction URL

https://github.com/devzakir/ionic-nuxt-mobile-app

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/index.js
       - /Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 6.20.9 (/Users/devzakir/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.6.2

Capacitor:

   Capacitor CLI      : 4.7.1
   @capacitor/android : 4.7.1
   @capacitor/core    : 4.7.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.19.0 (/Users/devzakir/.nvm/versions/node/v16.19.0/bin/node)
   npm    : 8.19.3
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please create a minimal reproduction of the bug that includes only the code required to reproduce the issue? It might be easiest to start with an Ionic Vue tabs starter application.

**Comment by devzakir** [comment]
Thanks for the quick response, I have deleted all the unnecessary 32 files, project is light weight now. Repo has been updated. Please check now!

**Comment by devzakir** [comment]
Hello @liamdebeasi Can you the issue, I update the repository yesterday.

**Comment by devzakir** [comment]
Hello @liamdebeasi Can you check the issue, I update the repository yesterday.
