### ISSUE TITLE
documentation: configuration for 'innerHTMLTemplatesEnabled'

### ISSUE THREAD

**Issue by NorthFred** [ionic-team/ionic-framework#27092]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

From documentation of breaking changes (section "config"):

`innerHTMLTemplatesEnabled` defaults to `false`. Developers who wish to use the `innerHTML` functionality inside of `ion-alert`, `ion-infinite-scroll-content`, `ion-loading`, `ion-refresher-content`, and `ion-toast` must set this config to `true` and properly sanitize their content.

### Expected Behavior

I am trying to use a custom HTML loader for `ion-loading` and can't make it work in Ionic 7. Where does this configuration need to be placed exactly?   I am trying to make it work in the `ionic.config.json` file as follows:

```
{
  "name": "my-awesome-application",
  "integrations": {},
  "type": "angular",
  "innerHTMLTemplatesEnabled": true
}
```

### Steps to Reproduce

Documentation is unclear about where to place the `innerHTMLTemplatesEnabled` configuration parameter in order to use custom HTML for e.g. loading indicators.

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.0
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 9.0.0

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v16.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.1
   OS     : Windows 11

**Comment by liamdebeasi** [comment]
Thanks for the report. This gets added to the Ionic Config inside of your application. The docs have an example for how to do this in Angular: https://ionicframework.com/docs/developing/config#global-config

**Comment by NorthFred** [comment]
@liamdebeasi Got it, thanks.
