### ISSUE TITLE
bug: --border-radius custom css style is not applied to left hand corners of controls

### ISSUE THREAD

**Issue by mp035** [ionic-team/ionic-framework#27116]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Setting `--border-radius:30px;` in vue.js scoped css  does not apply the full radius to the left hand side of ion-input, ion-select, and ion-textarea. Resulting in the following shapes (respectively):
![image](https://user-images.githubusercontent.com/9688384/229952214-6e106879-81bf-4b88-90f4-fbaaea93d293.png)

### Expected Behavior

Setting `--border-radius:30px;` in the css should render an input similar to this image:
![image](https://user-images.githubusercontent.com/9688384/229949697-aa157f36-d911-4867-9822-67c9114c2e5e.png)

### Steps to Reproduce

Start a new blank ionic-vue project, and replace the content of `src/views/HomePage.vue` with the following content:
```
<template>
  <ion-page>
    <ion-content :fullscreen="true">
      <ion-grid style="max-width: 500px;">
        <ion-row>
          <ion-col style="padding: 20px;">
            <ion-input aria-label="" class="custom-input" fill="outline"></ion-input> 
          </ion-col>
        </ion-row>
        <ion-row>
          <ion-col style="padding: 20px;">
            <ion-select class="custom-select" aria-label="" fill="outline">
              <ion-select-option v-for="[value, text] in choices" :value="value" :key="value">{{ text }}</ion-select-option>
            </ion-select> 
          </ion-col>
        </ion-row>
        <ion-row>
          <ion-col style="padding: 20px;">
            <ion-textarea class="custom-textarea" aria-label="" fill="outline"></ion-textarea> 
          </ion-col>
        </ion-row>
      </ion-grid>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { IonPage, IonContent, IonInput, IonGrid, IonRow, IonCol, IonSelect, IonSelectOption, IonTextarea } from '@ionic/vue';

const choices = new Map([
  ['1', 'Choice 1'],
  ['2', 'Choice 2'],
  ['3', 'Choice 3'],
  ['4', 'Choice 4'],
]);

</script>

<style scoped>
  ion-input.custom-input{
    --border-radius: 30px; /* does not apply to top left and bottom left corners */
    --border-width: 2px;
  }

  ion-select.custom-select{
    --border-radius: 30px; /* does not apply to top left and bottom left corners */
    --border-width: 2px;
  }

  ion-textarea.custom-textarea{
    --border-radius: 30px; /* does not apply to top left and bottom left corners */
    --border-width: 2px;
  }

</style>
```
Run the Created project.

### Code Reproduction URL

https://github.com/mp035/ionic_2023_04_05

### Ionic Info

[```
WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /home/mark/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/mark/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/lib/index.js
       - /home/mark/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/index.js
       - /home/mark/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'
       
       Require stack:
       - /home/mark/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /home/mark/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/lib/index.js
       - /home/mark/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/index.js
       - /home/mark/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.0.0 (/home/mark/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.19.0 (/home/mark/.nvm/versions/node/v16.19.0/bin/node)
   npm    : 8.19.3
   OS     : Linux 5.10

```

### Additional Information

_No response_

**Comment by amandaejohnston** [comment]
Thanks for the issue, I'm able to reproduce this. I'm seeing it in core, which means it happens in all three frameworks (Angular, React, Vue), and I'm able to reproduce with just the form control and custom CSS (no grid or other components necessary).

**Comment by amandaejohnston** [comment]
After talking with the team on this, we decided not to have Ionic automatically fix this behavior. If a large `--border-radius` is needed with `fill="outline"` like this, we would recommend either setting a large `--padding-start` as well, or using `shape="round"` to do both automatically. This has been documented in https://github.com/ionic-team/ionic-framework/pull/27467, which also includes further details on the problem and fixes considered.

Thank you again for the issue. I'm going to close this out, but let me know if you have any questions.

**Comment by mp035** [comment]
Just FYI, shape="round" is the workaround that I ended up using, it however, for some unknown reason does not work on the left hand corners if type="time" or type="date".  But I am guessing that is a separate issue, so I'll address it separately.
