### ISSUE TITLE
feat: ion-select v7 expose label and select container as shadow part

### ISSUE THREAD

**Issue by dobripet** [ionic-team/ionic-framework#27112]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

With new style how labels are defined for form inputs in v7, it would be great if label for ion-select would be exposed as shadow part to allow CSS styling. I am able to style ion-input label but not ion-select.

### Describe the Use Case

We need to be able apply CSS styling for labels in our forms. I don't see way how to style ion-select label as it is currently under ion-select #shadowroot.

### Describe Preferred Solution

Expose ion-select label same way as already text, icon and placeholder are exposed.

### Describe Alternatives

Remove label from ion-select #shadowroot so it is accessible by CSS.

**Comment by sean-perkins** [comment]
@dobripet thank you for requesting this feature! 

Can you tell us a little more about what styling customizations you are trying to make with the `ion-select` label? If you have screenshots/design mocks that would also be very helpful. Thanks!

**Comment by dobripet** [comment]
@sean-perkins 
Thank you for response, I will try that.
Our current use case is that we want kind of different look for form for web desktop that ionic provides out of box.

We use fixed position for labels because default position looks bad as inputs are not aligned and we do not want labels above control(stacked/floating which we use for mobiles). So we are trying to achieve the controls alignment as can be seen in attached example (which was WIP in ionic 6 so it was not aligned perfectly yet),  but we not were happy with the fixed default width value which causes ellipsis for most longer labels. So we implemented wrapper, that allows us to specify label width as number from 1 to 12 (so we keep 12 columns grid layout that ionic uses as well) and then it overrides width, min-width and max-width on label so the actual controls for fields are aligned under each other. 

It was much easier when label was not part of input in legacy mode, I am little afraid that we might need to give up on our goal to have single component that works for both web and mobile.

![image](https://user-images.githubusercontent.com/11678095/229875258-1a9ddb82-59af-42b7-a087-0982d1463851.png)

**Comment by sean-perkins** [comment]
@dobripet appreciate the response! 

> We use fixed position for labels because default position looks bad as inputs are not aligned

This may be considered a bug in v7. I would need to do a little more investigation, but my initial thoughts are that controls should have similar alignment and spacing (especially when used in an item). 

...

We did originally spec shadow parts as part of the feature changes in v7, but cut them due to timing with the release. We are still open to considering them. 

To clarify on the problem, the default max width of the label is too low for your application. This causes truncation for long labels. As a result, you would like to increase the width to account for longer labels, so you added the ability to set the width based on the grid size, so that you can have different default widths to account for the labels?

For context, in v7 we set the `max-width` for the label container to `200px`: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/input/input.scss#L445

**Comment by sean-perkins** [comment]
I'm going to go ahead and classify this as a feature request to get added into our backlog. I do think there is value in exposing the shadow part so that developers can customize the label appearance similar to how they can for input and textareas.

I think more investigation is needed around the fixed label styling. Today, it is focused on aligning the labels in a list, but not for aligning the controls in a list. The appearance of rendering a label alongside a control is also a discouraged practice in certain UI/UX blogs: 

![Label placement UI trend](https://cdn.uiuxtrend.com/wp-content/uploads/UIUXTrend-UX-Tips-Forms-Labels-On-Top-Fields.jpg)

Source: https://uiuxtrend.com/5-ui-ux-tips-mobile-form-design-best-practices/

It is also a less used display style in popular apps and system design, so we would need more screenshots of other applications before making a determination on if we should change the appearance in Ionic. 

For reference, this is the element we should expose with the shadow part: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/select/select.tsx#L704

**Comment by dobripet** [comment]
@sean-perkins 
Thank you.

Regarding that ui/ux you posted it is mobile focused and I agree that Ionic works for that flawessly. I was hoping (saw some tutorials) that we can use Ionic both for mobile and desktop. I guess we always can create custom components for desktop that will focus on desktop UI/UX that our wrapper could use alongside with ion components but I was trying to avoid that.

**Comment by judsonmusic** [comment]
@sean-perkins how can we get the label to stack on top of the ion-item or ion-select currently? Do we have to use a label tag above the element like in v6 and use aria-labelledby?

What i was used to doing:
```
<ion-col>
    <ion-item>
        <ion-label position="stacked">Unit</ion-label>
         <ion-select required formControlName="medunits" placeholder="Please Select">
          <ion-select-option [value]="msm.medunitid" *ngFor="let msm of medicationUnits">{{msm.medunit}}</ion-select-option>
    </ion-select>
  </ion-item>
</ion-col>
```

Which resulted in:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/2080617/229916086-6209075b-af65-4128-a658-ff9e635ee0c2.png">

But with the new syntax:
```
<ion-col>
    <ion-item>
      <ion-select required label="Unit" labelPlacement="stacked" formControlName="medunits" placeholder="Please Select">
        <ion-select-option [value]="msm.medunitid" *ngFor="let msm of medicationUnits">{{msm.medunit}}</ion-select-option>
      </ion-select>
   </ion-item>
</ion-col>
```
<img width="425" alt="image" src="https://user-images.githubusercontent.com/2080617/229916598-4b0a9e90-f4de-4c65-9a13-a4007de5bae7.png">

My UX team wants the labels back on top of the inputs. How can I achieve this in v7 current state?

**Comment by sean-perkins** [comment]
@judsonmusic the discord or the forums is likely the best place to ask support related questions, otherwise the thread conversation becomes disconnected from the original feature request. 

You can see an example here to accomplish what you are trying to do: https://stackblitz.com/edit/3we1ad?file=index.html

**Comment by judsonmusic** [comment]
> @judsonmusic the discord or the forums is likely the best place to ask support related questions, otherwise the thread conversation becomes disconnected from the original feature request. 
> 
> 
> 
> You can see an example here to accomplish what you are trying to do: https://stackblitz.com/edit/3we1ad?file=index.html 

I appreciate your response, but isn't the area labeled by property along with an ID on the label field required to avoid warnings in v7?

**Comment by sean-perkins** [comment]
The warnings will only be logged if the component mark-up is not using the `label` property (if the component supports it), is not using the label slot (if the component supports it) or doesn't have the `aria-label` or `aria-labelledby` attribute assigned to the host of the element. 

The warning is intended to guide accessibility best practices. Interactive controls either need a visible label associated to the control (handled by the `label` prop/slot) or an `aria-label`/`aria-labelledby` assigned. Shadow DOM and screen readers have had mixed levels of support and these changes help drive the most accessible experience for all users. 

In the Stackblitz example you will see the `aria-label` usage without a warning logged to the console.

**Comment by rdlabo** [comment]
I have same issue. I want to set "required" next to label:
https://github.com/ionic-team/ionic-framework/discussions/25661#discussioncomment-3302706

`ion-input`, and `ion-textarea` work well. But `ion-select` can't work, because this use shadowDOM. So I want to get shadow parts. Thanks.

**Comment by ntorrey** [comment]
@dobripet I'm really sorry for pinging you, but can I ask how your were able to style the ion-input label? I can't seem to get any styles to apply to it in v7.

**Comment by sean-perkins** [comment]
@ntorrey `ion-input` does not use the shadow dom, so you can target the internal elements directly: https://stackblitz.com/edit/3we1ad-zbbn65?file=index.html

**Comment by dobripet** [comment]
@ntorrey In the end I was able to style even the select label with this directive which I place on the select. It is hack which can break any time and not thoroughly tested yet but worked so far in cases I had.

`import { AfterViewInit, Directive, ElementRef, OnDestroy } from '@angular/core';

// This is total hack that breaks ion-select encapsulation so we can display correctly select for desktop web
@Directive({
    selector: '[lalIonFixIonSelectWidth]',
})
export class FixIonSelectWidthDirective implements AfterViewInit, OnDestroy {
    constructor(private el: ElementRef) {}

    observer: MutationObserver;

    ngAfterViewInit() {
        const shadowRoot = this.el.nativeElement.shadowRoot;
        if (shadowRoot.querySelector('.native-wrapper')) {
            this.fix(shadowRoot.querySelector('.native-wrapper'));
            return;
        }

        this.observer = new MutationObserver(() => {
            if (shadowRoot.querySelector('.native-wrapper')) {
                this.fix(shadowRoot.querySelector('.native-wrapper'));

                this.observer.disconnect();
                this.observer = null;
            }
        });

        this.observer.observe(shadowRoot, {
            childList: true,
            subtree: true,
        });
    }

    ngOnDestroy() {
        if (this.observer) {
            this.observer.disconnect();
        }
    }

    private fix(element: HTMLDivElement) {
        element.style.width = '100%';
    }
}
`

**Comment by ntorrey** [comment]
Thank you @sean-perkins and @dobripet for your quick responses! Argh... In the end it was a ViewEncapsulation issue. I don't have a full understanding of how ViewEnapsulation works, but setting the encapsulation in my angular component to ViewEncapsulation.None worked.

**Comment by judsonmusic** [comment]
> Thank you @sean-perkins and @dobripet for your quick responses! Argh... In the end it was a ViewEncapsulation issue. I don't have a full understanding of how ViewEnapsulation works, but setting the encapsulation in my angular component to ViewEncapsulation.None worked.

When you turn off view encapsulation, you are basically exposing the CSS for that particular view to the global Dom. You have to be very careful in doing that. I try never to do this. You may want to use an alternative like NgDeep or creating a custom class in the global state for overrides. View encapsulation basically encapsulates the view as well as the CSS associated with it so it only applies to the view. If you inspect the DOM, you will notice that your custom tag for your component wraps everything inside that view and all of the CSS within the associated stylesheet, for that component gets applied only to that component, but when you turn it off, therefore becomes part of the global scope.

**Comment by emmernme** [comment]
As the legacy implementation allows for significant styling of the `<ion-label>`-element, the change to Ionic 7 and Shadow DOM-implementation of labels should definitely expose the label as a Shadow DOM part. Upgrading to Ionic 7 has made a lot of these small design changes we're unable to override again later.

**Comment by emmernme** [comment]
This should also be implemented for ion-checkbox, ion-radio, ion-input, etc. For example, an ion-checkbox with long text will overflow with ellipsis, and there is no way to ensure the text wraps if it's too long.

**Comment by liamdebeasi** [comment]
Hi everyone,

We implemented this in https://github.com/ionic-team/ionic-framework/pull/27541. This feature will be available in an upcoming minor release of Ionic.

**Comment by mingxin-yang** [comment]
https://github.com/ionic-team/ionic-framework/issues/27392#issuecomment-1534916859 i want to use this, i use 7.0.14, but your method is not for me good @liamdebeasi

**Comment by mingxin-yang** [comment]
https://github.com/ionic-team/ionic-framework/issues/27242#issuecomment-1515157706 It's don't work

**Comment by mingxin-yang** [comment]
@liamdebeasi

**Comment by mingxin-yang** [comment]
Sorry, thank you for your reply, I thought you were talking about version 7.0.14, sorry
