### ISSUE TITLE
bug: IonToast with IonicSafeString display 'undefined'

### ISSUE THREAD

**Issue by beppemac** [ionic-team/ionic-framework#27118]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When I try to display an IonToast with a message containing an IonicSafeString, the text "undefined" is displayed inside the ion-toast, instead of the contents of the IonicSafeString

### Expected Behavior

The IonToast must display the contents of the IonicSafeString

### Steps to Reproduce

1. Create an IonToast with the use of ToastController
2. In message property set a IonicSafeString with '<ion-button>Hello!</ion-button>'
3. Present the IonToast and see the message 'undefined' in it

### Code Reproduction URL

https://stackblitz.com/edit/angular-sxv7cl?file=src/app/example.component.ts

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.0
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.6.2
   @capacitor/android : not installed
   @capacitor/core    : 4.6.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.20.0
   npm    : 8.19.4
   OS     : Windows 10

### Additional Information

With previous versions of Ionic (for example 6) the issue does not occur

**Comment by beppemac** [comment]
Thank you @liamdebeasi, problem solved with your suggestion. I apologize for not checking the breaking changes earlier.

**Comment by liamdebeasi** [comment]
Not a problem, glad the issue is resolved!

**Comment by bkleineibst** [comment]
The documentation is not really clear on this. It states that you can disable this on a case-by-case basis using IonicSafeString, after mentioning the global config option. (https://ionicframework.com/docs/techniques/security#bypassing-the-sanitizer-on-a-case-by-case-basis) However, as pointed out, this doesn't work. 

Shouldn't this option still be available, as opposed to enabling it for all innerHTML, which is unsafe?

**Comment by liamdebeasi** [comment]
Do you have a reproduction case?

I am testing this with the latest Ionic 7 and an alert: https://codepen.io/liamdebeasi/pen/mdzerZe

The "script" tag is being removed when the alert is presented.

**Comment by bkleineibst** [comment]
Maybe it is the case that the sanitizer is more selective.

I have a string with "<br/>" in it. https://codepen.io/bkleineibst/pen/JjmYboq

If leaves the plain text if it innerHTMLTemplates is not enabled, and replaces with line breaks if it is.

**Comment by liamdebeasi** [comment]
That is the intended behavior. 

When `innerHTMLTemplatesEnabled` is `true` any content passed to the `message` property will be interpreted as HTML.
When `innerHTMLTemplatesEnabled` is `false` any content passed to the `message` property will be interpreted as a string.

-----

The sanitizer in this case only applies when `innerHTMLTemplatesEnabled` is `true` since content is interpreted as custom HTML. Using `IonicSafeString` lets you bypass the sanitizer step, but content will still be interpreted as HTML.
