### ISSUE TITLE
bug: Uncaught SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by EwertonRicardo** [ionic-team/ionic-framework#27117]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When creating a new app using IONIC V7 i'M getting errors in Android devices:

![image](https://user-images.githubusercontent.com/51102292/229975574-359c6912-bc11-4f4c-b94b-9478f5032587.png)

### Expected Behavior

The app should open

### Steps to Reproduce

When I log window.navigator.userAgent in the chrome://inspect console I got this information:

Mozilla/5.0 (Linux; Android 7.1.1; A930 Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/52.0.2743.100 Mobile Safari/537.36

### Ionic Info

<img width="329" alt="image" src="https://user-images.githubusercontent.com/51102292/229977367-cade1399-3d25-4d88-9698-f9989413d33e.png">

**Comment by liamdebeasi** [comment]
Thanks for the report. Ionic v7 requires a minimum of Chrome 79. This is noted in the [Ionic 7 Breaking Changes Guide](https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#version-7x-browser-platform-support). This version requirement applied to the Chromium webview version as well.

Running Ionic 7 on unsupported browsers may result in the unexpected errors such as the one reported here. I am going to close this, but let me know if you have questions.
