### ISSUE TITLE
Bug: ng has unexpectedly closed (exit code 1).

### ISSUE THREAD

**Issue by edocbuhtig** [ionic-team/ionic-framework#27111]
**Ionic version:**

[x] **7.x**

**I'm submitting a ...** 

[ x] bug report
[ ] feature request

**Current behavior:**

Install Ionic CLI, TO CREATE A BLANK VER7.0 starter app

**Expected behavior:**

the blank angular starter app should, be created to run with the command : ionic serve

**Steps to reproduce:**

**Related code:**
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[ng]   library: 'digital envelope routines',
[ng]   reason: 'unsupported',
[ng]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[ng] }
[ng] Node.js v18.15.0

[ERROR] ng has unexpectedly closed (exit code 1).
        
        The Ionic CLI will exit. Please check any output above for error
        details.

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
Ionic Framework               : @ionic/angular 5.6.14
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.2.0
   @capacitor/android : not installed
   @capacitor/core    : 3.2.0
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.7.2)   : 1.4.0

System:

   NodeJS : v18.15.0 (/usr/local/bin/node)
   npm    : 9.5.0
   OS     : macOS Monterey
```

**Comment by edocbuhtig** [comment]
after research i found this was a NPM  related issue i cleared my previous CLI  npm cache then re installed ionic CLI and it worked lika charm sorry guys it took me many hours t figure out the root cause please close it at your will

**Comment by amandaejohnston** [comment]
Closing this out per the above, but please let us know if you spot this again and can track it down to something Ionic is doing, and we'll take another look 👀
