### ISSUE TITLE
bug: ionic-native/* modules not supported

### ISSUE THREAD

**Issue by NilsFrkal** [ionic-team/ionic-framework#27120]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

All ionic-native modules have to be removed before upgrade to ionic 7.  ionic-native/core has a peer dependency on rxjs@"^5.5.0 || ^6.5.0" but update requires  rxjs@7.5.0. Unfortunately there do not seem to be compatible version. This is not mentioned in breaking changes doc.

### Expected Behavior

Add comment/instructions around handling of ionic-native modules to upgrade guide.

### Steps to Reproduce

1. Start with ionic version 6 with ionic-native/* modules
2. Perform upgrade to ionic 7

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (d:\Development\Nodist\bin\node_modules\@ionic\cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.7.3
   @capacitor/core    : 4.7.3
   @capacitor/ios     : 4.7.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (D:\Development\Nodist\v-x64\18.15.0\node.exe)
   npm    : 9.5.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. As noted in https://ionic.io/blog/a-new-chapter-for-ionic-native, the Ionic Native plugins have become Awesome Cordova Plugins and the old Ionic Native packages are no longer maintained. We recommend migrating to Awesome Cordova Plugins so you can continue to use the plugins with Ionic 7. I am going to close this, but let me know if you have any questions.
