### ISSUE TITLE
feat: make 'clearInput' work for 'ion-textarea'

### ISSUE THREAD

**Issue by AndriiNeverov** [ionic-team/ionic-framework#27137]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Provide `clearInput` support for `ion-textarea` just like for `ion-input`.

### Describe the Use Case

Currently, there's no convenient way for the user to clear `ion-textarea`, especially with a lot of text entered. `clearOnEdit` forces them to always clear which is not what many users want, especially when they've already entered a lot of text which they will lose.

`ion-input` already supports this nicely with `clearInput`.

This is a follow up on https://github.com/ionic-team/ionic-framework/issues/14164 and https://github.com/ionic-team/ionic-v3/issues/775 which have never been resolved.

### Describe Alternatives

The user is forced to manually select the text which can be cumbersome with a lot of text, e.g. with large text areas and `autoGrow`.

**Comment by sean-perkins** [comment]
Hello @AndriiNeverov thanks for this feature request! 

Can you provide screenshots or an example app that has a clear action for a textarea on native?

For reference, I cannot find an example on iOS (Events > Notes and Reminder > Notes both do not provide a clear action for the textarea, but do for the input fields).

**Comment by AndriiNeverov** [comment]
@sean-perkins Thanks for getting back. I can't find such a screenshot and so it's likely not provided out of the box. 

That said, is there a technical or other limitation why Ionic can't do better than that?

From https://github.com/ionic-team/ionic-v3/blob/master/src/components/input/input.ts#L128 I can see that the button is a separate element rendered as an overlay anyway, i.e. doesn't rely on any native HTML element properties.

**Comment by liamdebeasi** [comment]
Thanks for filing the feature request. I discussed this request with the team, and we are not looking to implement the feature at this time. The clearInput feature on `ion-input` was primarily intended for use with password fields where you cannot see the text you have entered. The clearInput feature on that component makes it easy to clear an incorrect password and type it in again.

Textareas typically do not deal with passwords, so the clearInput feature does not apply in the same way that it did to inputs. Additionally, we try to align with native iOS and Android patterns, and neither platform implements a clearInput feature on the textarea.
