### ISSUE TITLE
bug: ion-textarea

### ISSUE THREAD

**Issue by software-OSG** [ionic-team/ionic-framework#27132]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hello,

here is my code:
`<ion-textarea label="Billing Notes" labelPlacement="stacked" fill="outline" rows="6" [(ngModel)]="customer.billing.note"></ion-textarea>`

There are 2 problems:
- the height of the textarea in ion-textarea
- the overflow of the text in texarea

![Capture d’écran 2023-04-06 à 09 40 52](https://user-images.githubusercontent.com/87468749/230308837-234d8bd6-9236-4902-8881-b7d9a47c7856.jpg)

### Expected Behavior

Same height for textarea and ion-textarea
Scroll auto inside textarea when content overflow

### Steps to Reproduce

Simply use ion-textarea with fill="outline"

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.0
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.4
   @angular/cli                  : 15.2.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.18.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you reproduce this in an Ionic starter app and provide a link to the repo? I am unable to reproduce this behavior using the code snippet provided.

**Comment by ceotrammell** [comment]
Having same issue

**Comment by typefox09** [comment]
This exact same thing happened to me also, in my case it covered the submit button below it so the form couldn't be completed. Will upload a code sample when get time
