### ISSUE TITLE
bug: Unselected segment button has incorrect font weight on iOS

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#27136]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

When an `ion-segment` is rendered on iOS, both the selected and unselected buttons have the same font weight (`450`). 

This can be seen in the basic playground: https://ionicframework.com/docs/api/segment#basic-usage

### Expected Behavior

Only the selected button should have a font weight of `450`. Unselected segment buttons should have a lower font weight (`400`). 

This can be seen in the iOS reminders app:

<img src="https://user-images.githubusercontent.com/13732623/230464518-1a58f888-e078-4a10-a0c4-b239cc7e45c6.PNG" width="400px" />

### Steps to Reproduce

1. Renders an `ion-segment` with at least two buttons.
2. Select one of the segment buttons
3. Observe: The font weight of both the selected and unselected buttons is the same
4. Compare to iOS (e.g. Reminders app > "Add List" modal)
5. Observe: The font weight of the selected and unselected buttons is different. 

### Code Reproduction URL

https://ionicframework.com/docs/api/segment#basic-usage

### Ionic Info

N/A

**Comment by liamdebeasi** [comment]
I think this was already reported in https://github.com/ionic-team/ionic-framework/issues/26825#issuecomment-1438379870.

**Comment by sean-perkins** [comment]
Should we be tracking that as a bug instead of a feature request? There is two aspects that are incorrect as mentioned in that ticket:
1. The animation is incorrect when compared against iOS 16 (unknown effort)
2. The font weight scale is incorrect (font weight style adjustment for unselected options)

**Comment by liamdebeasi** [comment]
Yes good catch! That ticket should be a bug.

**Comment by sean-perkins** [comment]
Ok closing this issue as a duplicate of: https://github.com/ionic-team/ionic-framework/issues/26825#issuecomment-1438379870.
