### ISSUE TITLE
bug: IonItem --background-activated is too dim on iOS

### ISSUE THREAD

**Issue by eugr** [ionic-team/ionic-framework#27130]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

On iOS, when you tap on a list item, it doesn't highlight because the default highlight color (step-150) in combination with activated background opacity results in the same black color as default background.

I've fixed this by defining the following style in variables.css:

```css
  .ios ion-item {
    --background-activated: var(--ion-color-step-500); /* because otherwise opacity is too low */
  }
```

However, it would be great if it was fixed on the framework level.

### Expected Behavior

Visual feedback is perceivable by a regular person with normal eyesight.

### Steps to Reproduce

1. Run any app that displays clickable list items on iOS simulator or real device with dark mode activated
2. Click on the item and observe lack of visual feedback

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.1

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.7.3
   @capacitor/core    : 4.7.3
   @capacitor/ios     : 4.7.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v19.7.0 (/opt/homebrew/Cellar/node/19.7.0/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this behavior. It looks like the activated color of the item is always `#000` even in dark mode. It should probably change to be `#fff` in dark mode so the item gets lighter when tapped (since the default background itself is `#000` on dark mode)

**Comment by liamdebeasi** [comment]
Here is a dev build if you would like to give it a shot in your app: `7.0.2-dev.11680787869.125aa3a3`

**Comment by eugr** [comment]
Just checked, seems to be working fine!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27134, and a fix will be available in an upcoming release of Ionic Framework.
