### ISSUE TITLE
bug: IonRow hidden property doesnt work

### ISSUE THREAD

**Issue by blue-eyed-devil** [ionic-team/ionic-framework#27140]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have several pages  with hidden IonRows which should show up on button click. It was perfectly working with v6. I just updated and it doesnt work anymore, however work with ion-col and possibly other elements.
I am using Ionic/React

### Expected Behavior

IonRow should be not visible when property hidden is set to true

### Steps to Reproduce

- create IonRow element
- give it property hidden
- preview

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.1

Capacitor:

   Capacitor CLI      : 5.0.0-beta.1
   @capacitor/android : 5.0.0-beta.1
   @capacitor/core    : 5.0.0-beta.1
   @capacitor/ios     : 5.0.0-beta.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.6.0 (/usr/local/bin/node)
   npm    : 9.6.1
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the report. Are the `hidden` styles not being applied or does some style have higher priority? In Ionic 7 we removed the custom `hidden` attribute in favor of the `hidden` attribute built into the browser: https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#version-7x-hidden-attribute

**Comment by blue-eyed-devil** [comment]
looks like :host is overwriting the ion-row[Attributes Style] 
```
:host {
    display: flex;
    flex-wrap: wrap;
}
ion-row[Attributes Style] {
    display: none;
}
```
<img width="442" alt="Screen Shot 2023-04-08 at 2 40 36 am" src="https://user-images.githubusercontent.com/19608742/230645454-85495b6a-4ce9-4e30-9885-f3846e49afbc.png">

**Comment by liamdebeasi** [comment]
If you'd like to keep the old `hidden` behavior then you can add the following to your global stylesheet:

```css
[hidden] {
  display: none !important;
}
```

**Comment by blue-eyed-devil** [comment]
That worked fine. Thanks

**Comment by liamdebeasi** [comment]
Great! I am going to close this, but let me know if you have other questions.
