### ISSUE TITLE
bug: Ionic 7 toggle has width auto

### ISSUE THREAD

**Issue by blue-eyed-devil** [ionic-team/ionic-framework#27149]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

IonToggle with label has width auto which makes it misaligned with rest of the form and does not show full label

<img width="548" alt="Screen Shot 2023-04-09 at 3 10 05 pm" src="https://user-images.githubusercontent.com/19608742/230755663-32170122-3cb5-4ce5-a06c-eee31fc9fcec.png">
<img width="451" alt="Screen Shot 2023-04-09 at 3 11 13 pm" src="https://user-images.githubusercontent.com/19608742/230755673-3c4b1a6c-9117-4c7e-bf5c-5631c2e6204d.png">

### Expected Behavior

to have width 100% of it's parent container

### Steps to Reproduce

 create IonToggle element
preview in browser

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.1

Capacitor:

   Capacitor CLI      : 5.0.0-beta.1
   @capacitor/android : 5.0.0-beta.1
   @capacitor/core    : 5.0.0-beta.1
   @capacitor/ios     : 5.0.0-beta.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.6.0 (/usr/local/bin/node)
   npm    : 9.6.1
   OS     : macOS Monterey

**Comment by rdlabo** [comment]
@blue-eyed-devil Please try to set justify attribute:

```html
<ion-toggle justify="space-between">Space Between Label and Control</ion-toggle>
```

Thanks.

**Comment by liamdebeasi** [comment]
Thanks for the report. Try removing the `slot="start"` from `ion-toggle`. Items in the start slot are not designed to take up the full width of the item.
