### ISSUE TITLE
bug: Nested ion-tabs breaks detection of selected tab in the parent one

### ISSUE THREAD

**Issue by haikyuu** [ionic-team/ionic-framework#27150]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have a structure that looks like this
```
<ion-tabs>
  <ion-tab>
    <ion-content>
      <ion-modal>
        <ion-tabs>
```
This breaks because of [this handler](https://github.com/ionic-team/ionic-framework/blob/ca9b9b65d2b738bac9e29017039e4d14cf8400d2/core/src/components/tab-button/tab-button.tsx#L88-L96)
```
  @Listen('ionTabBarChanged', { target: 'window' })
  onTabBarChanged(ev: CustomEvent<TabBarChangedEventDetail>) {
    const dispatchedFrom = ev.target as HTMLElement;
    const parent = this.el.parentElement as EventTarget;

    if (ev.composedPath().includes(parent) || dispatchedFrom?.contains(this.el)) {
      this.selected = this.tab === ev.detail.tab;
    }
  }
```

The top level tabs component doesn't highlight the selected tab.

### Expected Behavior

The top level ion-tabs component should not handle events coming from child ion-tabs components.

### Steps to Reproduce

- Run the code to see the current tab not being highlighted
- You can remove the modal code to see it working

### Code Reproduction URL

https://stackblitz.com/edit/6camlg?file=index.html,package.json,index.ts

### Ionic Info

Ionic:

   Ionic CLI : 6.20.8 (/usr/local/lib/node_modules/@ionic/cli)

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : 4.7.0
   @capacitor/core    : 4.7.0
   @capacitor/ios     : 4.7.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v18.14.2 (/usr/local/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown

**Comment by haikyuu** [comment]
A possible fix would be to introduce an autogenerated id for each ion-tabs, and include the ion-tabs id in the events. This way, these conflicts wouldn't occur.

I'm not too familiar with Stencil events, but `event.stopPropagation()` might fix it as well

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this behavior, but this does not appear to be a bug in Ionic. Tabs should not be used nested in a modal like this. It sounds like you want some kind of segmented control in the modal. In that case, you might want to try [ion-segment](https://ionicframework.com/docs/api/segment) instead.
