### ISSUE TITLE
bug: ion-content keyboard padding removed when switching inputs which lead to jumping fields

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-framework#27166]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v5.x, v6.x

### Current Behavior

When a form field is focused, the ion-content keyboard padding is applied accordingly, but after clicking on the next field it gets removed (look at the keyboard background color) and therefore scrolling is no longer possible. This also leads to another issue, that the view jumps.

https://user-images.githubusercontent.com/11534760/231189175-1651bb52-98ea-47e3-ba24-df2e95e09a65.mp4

### Expected Behavior

Padding stays applied 

### Steps to Reproduce

1. clone repl
2. pnpm install
3. pnpm ios
4. click in form field
5. click next form field
6. background flickers
7. scrolling not possible

> Have a look at commit "Problem", before and after, so Keyboard plugin with option "native" produces the background to flicker.

### Code Reproduction URL

https://github.com/muuvmuuv/Issues-Ionic-Angular

### Ionic Info

Its a nx workspace

[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 6.20.3

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.10.0
   npm    : 9.5.0
   OS     : macOS

  ────────────────────────────────────────────────

     Ionic CLI update available: 6.20.3 → 7.0.0
     Run pnpm add --global @ionic/cli to update

  ────────────────────────────────────────────────

**Comment by muuvmuuv** [comment]
Hey @liamdebeasi I was able to identify the issue. See my repl. Will update description as well later.

Before my commit "Problem" the ion-content scrolling is still broken and after it gets the background flickering on top of that.

**Comment by muuvmuuv** [comment]
Setting the resize to `Ionic` fixes the flickering, but now the next and prev button on the native keyboard function incorrect IMO.

**Comment by muuvmuuv** [comment]
Ok this option fixes all issues in the video: flickering, clicking and no scroll... didnt know that is required for Ionic to work with Cap keyboard.

**Comment by thetaPC** [comment]
@muuvmuuv Your latest [comment](https://github.com/ionic-team/ionic-framework/issues/27166#issuecomment-1504785944) mentions that all the issues in the video are fixed. Does that mean that this issue can be closed?

**Comment by muuvmuuv** [comment]
I am on vacation rn and wasn't able to deep test our app intesively but will next week.
