### ISSUE TITLE
feat: Popover provide stopPropagation for backdrop

### ISSUE THREAD

**Issue by Zane0816** [ionic-team/ionic-framework#27176]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

My Input component has a Popover prompting the user. When the user clicks the Backdrop of Popover, the input will lose the focus. So I want to provide a attribute. When clicking Backdrop, the user will not lose the focus of Input.

### Describe the Use Case

provide stopPropagation for backdrop of Popover

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you clarify why you want to prevent the input from losing focus? You should be able to use the `backdropDismiss` property to prevent dismissing when clicking the backdrop.

**Comment by Zane0816** [comment]
this is my demo code:

```typescript
import { IonButton, IonContent, IonHeader, IonInput, IonPage, IonTitle, IonToolbar, useIonPopover } from '@ionic/react';
import { FC, useState } from 'react';
import { IonInputCustomEvent } from '@ionic/core/dist/types/components';

const InputPopover: FC<{ text: string }> = ({ text }) => {
  return <IonButton>Create new Tag {text}</IonButton>;
};

const Demo = () => {
  const [tag, setTag] = useState<string>();
  const [present, dismiss] = useIonPopover(InputPopover, {
    text: tag,
  });
  const onInputChange = (e: IonInputCustomEvent<InputEvent>) => {
    const val = e.target.value as string;
    if (val && val.startsWith('#') && val.length > 1) {
      setTag(val);
      present({ event: e, cssClass: 'ion-disable-focus-trap' });
    }
  };
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>DEMO</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>
        <IonInput onIonInput={onInputChange} />
        <IonButton>Send</IonButton>
      </IonContent>
    </IonPage>
  );
};

export default Demo;
```

1. My Input component loses focus when the Popover component is shown
2. I can't hit the send button at this point even though the Input component doesn't lose focus

**Comment by liamdebeasi** [comment]
For the input, you can set [keyboardClose](https://ionicframework.com/docs/api/popover#keyboardclose) to `false` to prevent the keyboard from dismissing. Note that browsers may still automatically blur inputs when tapping other buttons. This is not an Ionic Framework behavior, and you will need to account for this in your application.

-----

Popovers are designed to overlay the entire application and prevent interaction with the content underneath it. If you would like to show an element while still keeping the content underneath interactive, then popover is likely not the correct UI component to use here. Instead, I would recommend creating an component that displays locally within the `Demo` component.

Alternatively, you could set `pointer-events: none` on both `ion-popover` and `ion-popover::part(backdrop)` to make this work, but the user experience will likely be confusing.

-----

We don't have plans to introduce a `stopPropagation` feature for backdrop, so I am going to close this. If you would like to keep the backdrop visible but prevent the "click to dismiss" behavior, you can use the `backdropDismiss` property. If you would like to remove the backdrop altogether, you can use the steps I provided above. Let me know if you have questions.
