### ISSUE TITLE
bug: Range knob is clipped with modern form syntax in ion-item

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#27199]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When a modern `ion-range` is rendered inside of `ion-item`, the range knob is clipped when at the start or end of the control.

Comparison of standalone vs. inside `ion-item`:
![CleanShot 2023-04-13 at 11 44 51](https://user-images.githubusercontent.com/13732623/231813760-1cc5512f-6576-42de-9e1f-56686114cb43.png)

Note: This behavior only happens when rendered inside `ion-item`. When `ion-range` is rendered by itself, it does not clip. 

### Expected Behavior

The range should adjust styling when used inside of `ion-item`, so that the range knob is always visible and never clipped.

### Steps to Reproduce

1. Render `<ion-range aria-label="Volume"></ion-range>` inside of `ion-item`.
2. Observe: The range knob is clipped (for both iOS and MD)

### Code Reproduction URL

https://stackblitz.com/edit/angular-9scsxd?file=src%2Fapp%2Fexample.component.html

### Ionic Info

N/A

**Comment by liamdebeasi** [comment]
Looks like these legacy range styles still apply when used in an item: 

MD: https://github.com/ionic-team/ionic-framework/blob/7ad84cbbc5e9527f4888a12782ca2b65c521fdf4/core/src/components/range/range.md.scss#L32
iOS: https://github.com/ionic-team/ionic-framework/blob/7ad84cbbc5e9527f4888a12782ca2b65c521fdf4/core/src/components/range/range.ios.scss#L22
