### ISSUE TITLE
bug: dynamic popover width is not aligned with inline popover

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#27190]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Extending to #24716 i guess...

I'm using `--width: fit-content` for all my popover's. I mentioned this bug for inline popovers (with `<ion-list>` in it):

|Event|Screenshot|
|----|----|
|**First inline popover opening:**|<img width="125" alt="Bildschirmfoto 2023-04-13 um 11 45 59" src="https://user-images.githubusercontent.com/20899975/231723528-74ab389d-fd45-47e9-b16f-c0d17d146b80.png">|
|**Second inline popover opening:**|<img width="148" alt="Bildschirmfoto 2023-04-13 um 11 46 03" src="https://user-images.githubusercontent.com/20899975/231723728-60a6e0ca-93c5-4392-b8fa-d2341d182bac.png">|
|**First controller popover opening:**|<img width="145" alt="Bildschirmfoto 2023-04-13 um 11 46 08" src="https://user-images.githubusercontent.com/20899975/231723966-d9ba5945-c2a8-4948-b368-07b82f081350.png">|

What also works is if i first open it via the controller and then the inline popover. Only when i open the inline popover first it breaks the layout.

### Expected Behavior

The positioning should be always correct of course 😃 

### Steps to Reproduce

1. Check out the repo
2. Run `ionic serve`
3. Click through the buttons as described above

May be wrong but in my tests this only is a bug on ios 🤔

### Code Reproduction URL

https://github.com/EinfachHans/ionic-popover-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1 (/Users/hans/.nvm/versions/node/v18.12.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.2
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.6
   @angular/cli                  : 15.2.6
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.7.2

System:

   NodeJS : v18.12.1 (/Users/hans/.nvm/versions/node/v18.12.1/bin/node)
   npm    : 8.19.2
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the issue. Does the issue reproduce if you use `keepContentsMounted`?

**Comment by EinfachHans** [comment]
No, then it works! 🤔

**Comment by liamdebeasi** [comment]
Here is a dev build with a proposed fix if you are interested in testing:

```
npm install @ionic/angular@7.3.2-dev.11693321763.15a54694
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28072, and a fix will be available in an upcoming release of Ionic Framework. Please feel free to continue testing the dev build, and let me know if you run into any issues.
