### ISSUE TITLE
bug: select label does not cover placeholder

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#27201]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When you have an floating md select with label and placeholder and no value selected the select appears buggy (see linked stackblitz)

### Expected Behavior

I added to the stackblitz the current implementation of the same thing in the input coponent. That's how the select should work as well, so: Only show the label, if the select has focus: show the placeholder

### Steps to Reproduce

Open attached stackblitz

### Code Reproduction URL

https://github-1mgkjv-k38jrw.stackblitz.io

### Ionic Info

Starter project

**Comment by munnokd** [comment]
@EinfachHans can you assign this issue to me?

**Comment by EinfachHans** [comment]
> @EinfachHans can you assign this issue to me?

I'm not working on the ionic framework but created a cuple of merged pull requests myself. So if you are interested in fixing this bug you can create a PR of course 😊 

Just follow the contribution guideline and the team will appreciate it
