### ISSUE TITLE
bug: ion-tab ionTabsWillChange event is fired after the tab component ngOnInit, ionViewWillEnter and ionViewDidEnter are fired

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-framework#27212]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

ion-tab ionTabsWillChange event is fired after the tab component ngOnInit, ionViewWillEnter and ionViewDidEnter are fired

### Expected Behavior

ion-tab ionTabsWillChange event must be fired BEFORE the tab component ngOnInit, ionViewWillEnter and ionViewDidEnter are fired

### Steps to Reproduce

1. open https://stackblitz.com/edit/angular-jddxdk-zlkkrz?file=src/app/example.component.html
2. open console
3. navigate between tabs
Note that the ion-tab ionTabsWillChange event is fired after the tab component ngOnInit, ionViewWillEnter and ionViewDidEnter are fired - see below
<img width="1658" alt="Screenshot 2023-04-17 at 3 13 01 PM" src="https://user-images.githubusercontent.com/3608222/232495208-b2cefbfc-bba0-4fd6-a7fb-f4da4b6caa49.png">

### Code Reproduction URL

https://stackblitz.com/edit/angular-jddxdk-zlkkrz

### Ionic Info

See https://stackblitz.com/edit/angular-jddxdk-zlkkrz

### Additional Information

None

**Comment by sean-perkins** [comment]
Hello @ryaa thanks for reporting this issue!

Can you explain why `ionTabsWillChange` should be emitted before the other lifecycle events? In the current implementation, the event fires after the active tab is set (either manually through the API or from a user interaction). It isn't directly coupled to the child component's lifecycle. 

This was a recent change here: https://github.com/ionic-team/ionic-framework/pull/24910

This was done in response to this issue: https://github.com/ionic-team/ionic-framework/issues/18900

**Comment by ryaa** [comment]
> Can you explain why ionTabsWillChange should be emitted before the other lifecycle events? In the current implementation, the event fires after the active tab is set (either manually through the API or from a user interaction). It isn't directly coupled to the child component's lifecycle.

The problem is that, in each tab component **ngOnInit** method, I need to get the active/selected tab and this is not available yet (as this is set in ionTabsWillChange which fired after the tab child component life cycle events invoked). My assumption, based on the event name **ionTabsWillChange** (note that it **will** change), this should happen before the tab components are loaded/initialized.

**Comment by sean-perkins** [comment]
@ryaa appreciate the follow-up. I agree the event ordering here is not correct. The `ion-tabs` implementation is listening for the result from `stackEvents`, but this is emitted after the child component is mounted in the DOM and `ngOnInit` resolves.

`ion-router-outlet` should emit another event prior to setting the active view, allowing `ion-tabs` to emit `ionTabsWillChange` with the selected tab **before** it is activated. I do not believe our original resolution in #24910 was correct after reviewing this again.

Can you share your ideal implementation for accessing the selected tab from within the `ngOnInit`? Currently the child components would not have access to the `ion-tabs` event emission, even if we changed the ordering of when they fired. This data would need to be stored in a provider and shared between the component rendering `ion-tabs` and the inner child component.

**Comment by ryaa** [comment]
> Can you share your ideal implementation for accessing the selected tab from within the `ngOnInit`? Currently the child components would not have access to the `ion-tabs` event emission, even if we changed the ordering of when they fired. This data would need to be stored in a provider and shared between the component rendering `ion-tabs` and the inner child component.

Here is the sample showing a simplified implementation that I have in my application now - see https://stackblitz.com/edit/angular-jddxdk-qrddgc?file=src%2Fapp%2Fhome%2Fhome-page.component.ts

Note that each tab component has a workaround in `ngOnInit` to set the correct value for the activeTab in `Share` provider. Ideally, this should be set once in `onTabsWillChange` in the main tabs page, so that all the individual tab child components etc. can read the correct activeTab value from `Share` provider.

I hope that it makes sense. Please let me know if you have any questions or comments. Thank you

**Comment by ryaa** [comment]
> Hello @ryaa, would you be available to test this dev-build and let me know if it resolves your issue?

sure. I will try to test in this week
