### ISSUE TITLE
feat: Simplify custom styles for components in Ionic 7 (Angular)

### ISSUE THREAD

**Issue by ntorrey** [ionic-team/ionic-framework#27214]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

In version 7 of @ionic/angular, it has become more difficult to customize styling of various ionic components. For example, currently in version 7, if I want to customize an ion-input label or the input text itself, I need to either create a style definition in my global stylesheet or turn off ViewEncapsulation in Angular for that particular component, neither of which are ideal since both are unwieldy to manage.
Is there no way to enable styling on a component level without resorting to cumbersome workarounds?

### Describe the Use Case

It would greatly simplify the styling of ionic components like it used to be in version 6.

### Describe Preferred Solution

I would prefer to be able to style ionic components from within angular components like this:
```ts
@Component({
  selector: 'my-component',
  standalone: true,
  imports: [CommonModule, IonicModule],
  template: `
    <ion-item>
      <ion-input label="Name"></ion-input>
    </ion-item>
  `,
  styles: [
    `
      ion-input.label {
        width: 150px;
      }
      ion-input.input-text {
        color: blue;
        text-align: right;
      }
    `
  ]
})
export class MyComponent {}
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you help me understand how you customized these components before v7?

**Comment by ntorrey** [comment]
> Thanks for the report. Can you help me understand how you customized these components before v7? Also, make sure you are targeting the input using a class so you have a higher specificity than Ionic's styles: https://ionicframework.com/docs/api/input#css-custom-properties
> 
> Your preferred solution should work if you use a custom class: https://codepen.io/liamdebeasi/pen/abRZLLK

I will try this and get back to you.

**Comment by liamdebeasi** [comment]
The markup should be a bit simpler with v7:

```html
<ion-card>
   <ion-item>
     <ion-checkbox>Check</ion-checkbox>
   </ion-item>
   <ion-item>
     <ion-input label="Green to yellow" class="days text-end" type="number"></ion-input>
     <ion-text slot="end">days</ion-text>
   </ion-item>
   <ion-item>
     <ion-input label="Yellow to Red after" class="days text-end" type="number"></ion-input>
     <ion-text slot="end">days</ion-text>
   </ion-item>
</ion-card>
```

Notable changes:

1. `ion-label` was moved to the slot for `ion-checkbox` or the `label` prop for `ion-input`.
2. The `slot="end"` usage was removed.
3. The `::after` code could be achieved by adding `ion-text` with `slot="end"`.

The `.text-end` class should still work.

Here's an example: https://codepen.io/liamdebeasi/pen/abRZLLK

**Comment by liamdebeasi** [comment]
So the problem here is Angular is generating a selector that looks like this:

```css
ion-input[_ngcontent-dln-c84]   .label-text[_ngcontent-dln-c84] {
  color: red;
}
```

However, `.label-text` is inside `ion-input` and never receives that `_ngcontent` attribute. As a result, your custom styles never apply. You could try using `::ng-deep` (i.e. `ion-input ::ng-deep .label-text`), but that feature has been deprecated for some time.

Alternatively, you might want to consider adding a class to `ion-input` and moving the style to a global stylesheet:

```css
ion-input.custom-label .label-text {
  color: red;
}
```

The `.custom-label` class prevents this style from applying to every instance of `ion-input`.
