### ISSUE TITLE
Side menu combined with ion-split-pane and ion-menu is heavy only in Safari

### ISSUE THREAD

**Issue by ohtanzcom** [ionic-team/ionic-framework#27210]
**Ionic version:**
6.20.4

**I'm submitting a ...** 
[x ] bug report
[ ] feature request

**Current behavior:**
Safari becomes sluggish.

macOS
Monterey 12.6.4
Safari: 16.4 (17615.1.26.101.9, 17615)

iOS
16.4.1
Safari: 604.1

**Expected behavior:**
I want lightweight operation.

**Steps to reproduce:**
I implemented a side menu that combines ion-split-pane and ion-menu, but the side menu becomes unusually heavy when opened from hidden state only in Safari.

After clicking the button to open the side menu and the side menu opens, clicking a link or button does not respond for a few seconds.

The problem does not occur in Chrome, Edge, or FireFox.

https://user-images.githubusercontent.com/69287535/232418516-d6c5bf79-705f-48e2-b670-09eae82b6341.mp4

**Comment by ohtanzcom** [comment]
I have built and verified the minimum configuration and there seems to be a problem elsewhere, so I will close this one.
(We don't know the cause yet...)

**Comment by amandaejohnston** [comment]
Closing this out per the above, but please let us know if you're able to track the problem to something in Ionic and we'll take another look.
