### ISSUE TITLE
Safari is showing very big content on "ng run app:serve"

### ISSUE THREAD

**Issue by MaxLeggieri** [ionic-team/ionic-framework#27225]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When running `ng run app:serve` and run the app on Safari the page shows big content, kind of mobile view. This is not happening in other browsers like Chrome, Brave, Firefox etc. When building in production mode this is not happening.

<img width="1511" alt="Screenshot 2023-04-18 at 09 04 49" src="https://user-images.githubusercontent.com/1042620/232698009-13530fa4-40e0-4b66-8e0c-74383053dbd3.png">

### Expected Behavior

Expecting the app to show in desktop mode like in other browsers (Chrome, Brave, Firefox etc)

### Steps to Reproduce

1. ionic start --type=angular --capacitor
2. ionic build
3. ng run app:serve

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.7.3
   @angular-devkit/build-angular : 14.2.11
   @angular-devkit/schematics    : 14.2.11
   @angular/cli                  : 14.2.11
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.3.0
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.14.2 (/usr/local/bin/node)
   npm    : 8.5.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Did you adjust the font size in Safari? https://support.apple.com/en-gb/HT207209

**Comment by MaxLeggieri** [comment]
> Did you adjust the font size in Safari? https://support.apple.com/en-gb/HT207209

Hi Liam,
No, as i mentioned in production the components are smaller and the layout is optimized for the web.

**Comment by liamdebeasi** [comment]
Can you reproduce this issue in an Ionic starter app and provide a link to the repo?

**Comment by MaxLeggieri** [comment]
> Can you reproduce this issue in an Ionic starter app and provide a link to the repo?

Sure: https://github.com/MaxLeggieri/safari-bug-test.git

Here screenshots of Safari and Chrome also:

<img width="1512" alt="Screenshot 2023-04-19 at 09 42 54" src="https://user-images.githubusercontent.com/1042620/233006338-76b5086d-3e6d-450d-b3ed-f5496e53f871.png">

<img width="1512" alt="Screenshot 2023-04-19 at 09 43 16" src="https://user-images.githubusercontent.com/1042620/233006417-e50489a3-cb6a-4d3f-a494-850c246c9a2f.png">


Thanks!

**Comment by MaxLeggieri** [comment]
> I'm not able to reproduce the issue on my end:
> 
> ![Screenshot 2023-04-19 at 8 56 12 AM](https://user-images.githubusercontent.com/2721089/233081503-958aa578-be91-40c3-b96f-0b35e079d252.png)
> 
> Can you try clearing your browser history in Safari? That should reset websites back to their default zoom level. Alternatively, you can press Command and Minus (-).

Jesus... you were right, the zoom was saved in some way. Didn't know zooming was saved on Safari.
Thanks for your time 

Max

**Comment by liamdebeasi** [comment]
No problem, glad the issue is resolved!
