### ISSUE TITLE
feat: stacked labels for form controls

### ISSUE THREAD

**Issue by anddorua** [ionic-team/ionic-framework#27229]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Controls should be able to work with external labels. I.e. for any control sibling `<label for="control-id">Text</label>` might be attached and pressing on this label should apply focus on the control.

### Describe the Use Case

Right now in v.7.0.1 I can't attach labels to the `ion-checkbox` elements to implement the following layout:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/5493450/232874794-a68753ca-6434-4f76-b851-9e5f174e72af.png">

with this code:
```
<div class="week-container" formGroupName="weekDays">
  <label
    *ngFor="let day of weekDays; let i = index"
    for="day{{ i }}"
    class="label"
    >{{ day }}</label
  >
  <ion-checkbox
    *ngFor="let control of dayArray.controls; let i = index"
    formControlName="{{ i }}"
    id="day{{ i }}"
  ></ion-checkbox>
</div>
```

**Comment by RRGT19** [comment]
@liamdebeasi 
Any update on this feat? It would be really helpful. In fact, I'm waiting for this to finish our migration from v6 to v7.

**Comment by thetaPC** [comment]
Thanks for the issue! This has been implemented via PR https://github.com/ionic-team/ionic-framework/pull/28075 and will be available in an upcoming minor release of Ionic.

**Comment by RRGT19** [comment]
Hi team, @thetaPC @liamdebeasi 

Saw a new minor release (7.3.4) without this fix. A friendly reminder of this.

**Comment by liamdebeasi** [comment]
This is a feature, so it will be in a minor release of Ionic as noted in https://github.com/ionic-team/ionic-framework/issues/27229#issuecomment-1708563701.
