### ISSUE TITLE
bug: Unable to add multiple line of errors in ion-input using the new syntax

### ISSUE THREAD

**Issue by Ema96** [ionic-team/ionic-framework#27235]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In Ionic 6 you can wrap an ion-input with an ion-item (I know it still possible in ionic 7 but it would break the styling between the other inputs I have in a form). 
This allows you to specify the error inside an ion-note that can be html or plain text.
Inside the ion-note I can add a series of div to show all the errors I need (in my case password validation errors).

### Expected Behavior

Be able to add inside an ion-input "errorText" some html code or at least that if I specify a new line character in the string that it would be rendered correctly.
Also adding an error slot inside the ion-input like an ion-item would be nice.

### Steps to Reproduce

1. Create an ion input inside a form
2. Try to add multiple line of errors

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1 (C:\Users\Emanuele\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.2
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.6
   @angular/cli                  : 15.2.6
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.6.4
   OS     : Windows 10

### Additional Information

If someone else has the same problem a workaround is to keep everything in the ion-input using the new syntax omitting the "errorText".
Then you can add all the messages below the input and putting them inside a div and style it like this:
`.error-message {
        color: var(--ion-color-danger);
        font-size: 0.8em;
}
`

**Comment by liamdebeasi** [comment]
Thanks for the report. I'm not able to reproduce the reported behavior: https://codepen.io/liamdebeasi/pen/xxyEaPV

In the example above, the error text is wrapping to the next line.

**Comment by Ema96** [comment]
Thanks @liamdebeasi for the answer. I'm not talking about text wrapping. I'm talking about having a list of errors shown in the error field.

This is what I get adding an html list in the `<ion-note slot="error">LIST_OF_ERRORS</ion-note>` using the old syntax.
![FormPasswordValidation](https://user-images.githubusercontent.com/22667064/233117608-958575eb-1dd7-479d-a56f-b4d252af2f48.png)

Now I can only add a string as you shown in your example.
Is there a way to do the same using the new syntax and without using the ion-item?

**Comment by liamdebeasi** [comment]
The `errorText` feature is not supposed to be used this way. If there are multiple errors, the error text should describe how to avoid the most likely error. This was done to align with the Material Design spec: https://m2.material.io/components/text-fields#anatomy (See "Error text" section).

**Comment by Ema96** [comment]
Ok. Thanks @liamdebeasi for your help.
