### ISSUE TITLE
feat: support disabling ionic warnings / non-error logs in production

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-framework#27231]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

We'd like to be able to globally disable Ionic Developer logs in production, via a config flag, like this (Angular example):

app.module.ts
```
    IonicModule.forRoot({
      logsEnabled: !environment.production
    }),
```

### Describe the Use Case

Currently, various warnings like these are logged for the benefit of developers, however, they get pulled into production log tracing systems like https://sentry.io, and other aggregators. And they're artificially inflating our debug/production issue logs, creating distractions, and clutter:

![image](https://user-images.githubusercontent.com/362329/232906299-cd3efbfb-2b89-4e30-9913-2ef63dc2e41b.png)
Can you spot the actual error?

### Describe Preferred Solution

app.module.ts
```
    IonicModule.forRoot({
      logsEnabled: !environment.production
    }),
```

### Describe Alternatives

Logs can be filtered out when debugging in Chrome/Safari, etc. But you have to remember to do this, and it doesn't solve the problem for production log aggregating services/systems.

**Comment by lincolnthree** [comment]
> Have you tried updating your Sentry config to not capture `warn`? https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#captureconsole
> 
> If the issue is that Sentry is picking up warnings that you do want reported then I think this solution is better implemented in the Sentry config rather than Ionic.

Yeah, but wouldn't that filter out other warning-level logs that might still be relevant to issues. I'm not sure I see how we could use that to filter out just the Ionic warnings?

I think the core issue here is that we are getting development-time logs at production-time. And that's usually not great. E.g. This is why things like log-levels and environments were established as design patterns/practices.

These logs really don't matter to end users or people snooping in the console, as they are intended for developers writing framework-specific template syntax, and even more narrowly, only required when performing migration actions between major framework versions.

**Comment by liamdebeasi** [comment]
The purpose of the warning is to a) inform developers about upcoming form control changes and b) encourage them to migrate now before the breaking changes are made in the future. Having these warnings be a bit persistent is intended so developers are discouraged from ignoring them.

> Yeah, but wouldn't that filter out other warning-level logs that might still be relevant to issues. I'm not sure I see how we could use that to filter out just the Ionic warnings?

Sentry has several tools for filtering out unwanted logs: https://docs.sentry.io/platforms/javascript/configuration/filtering/

A couple that you might want to try:

1. [ignoreErrors](https://docs.sentry.io/platforms/javascript/configuration/filtering/#using-platformidentifier-nameignore-errors-) lets you filter out errors that match a certain pattern, though I am unclear if this _only_ applies to `Error` objects.
2. [beforeSend](https://docs.sentry.io/platforms/javascript/configuration/filtering/#using-platformidentifier-namebefore-send-) lets you modify event payloads before they are sent to Sentry. Returning `null` causes the event to be dropped entirely.

------

The main issue being reported here is that Sentry is picking up unwanted logs. We could certainly add the requested feature to Ionic, but that only avoids the root issue for a single library. For example, another library used in your application could start adding deprecation warnings of their own, and the root issue would appear again. As a result, I don't think adding this feature is a good fit for Ionic. I recommend using one of the above APIs to configure Sentry to filter out unwanted console warnings.

**Comment by lincolnthree** [comment]
Sentry was just an example, but. Sure, that's 100% fine. Just thought I'd suggest it :) There are also third party tools (and hacking window.console) that can disable logging in production. Appreciate you taking the time to look at this and suggest a workaround.

**Comment by timkemper** [comment]
Wow talk about passing the buck!
