### ISSUE TITLE
bug: ion-footer disappears/appears when switching between ion-input  

### ISSUE THREAD

**Issue by gianbasagre** [ionic-team/ionic-framework#27233]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The `ion-footer` disappears when switching between `ion-input` 

https://user-images.githubusercontent.com/165565/232966266-ecb7de26-2112-427a-b051-39190f73272b.mp4

### Expected Behavior

The `ion-footer` should stay visible when switching between `ion-input` elements

### Steps to Reproduce

1. Create a list of `ion-input` elements
2. Add an `ion-footer` with an `ion-button` 
3. Launch the app on iOS simulator

### Code Reproduction URL

https://github.com/gianbasagre/ionic-example-app-switching-input-ion-footer-bug

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.0.1 (/Users/<user>/.npm/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.2
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.6
   @angular/cli                  : 15.2.6
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : 4.7.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.19.1 (/usr/local/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown
```

**Comment by mapsandapps** [comment]
Hi, the default behavior of the Capacitor keyboard is to resize the entire webview. You could try changing [the `KeyboardResize` setting for the Capacitor keyboard](https://capacitorjs.com/docs/apis/keyboard#keyboardresize) to see if it solves your problem, e.g. by adding the following to your capacitor.config.ts:

```ts
  plugins: {
    Keyboard: {
      resize: 'Ionic',
    },
  },
```

**Comment by gianbasagre** [comment]
@mapsandapps Thanks that fixed the issue!
