### ISSUE TITLE
feat: Option for visibility of placeholder (ion-input)

### ISSUE THREAD

**Issue by Wasenshi123** [ionic-team/ionic-framework#27240]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Related to this: #27239

I would like to request that the placeholder has the option to make it always show (like current behavior) or "only show when get 'focus' (like original, when wrapped in ion-item)"

### Describe the Use Case

https://stackblitz.com/edit/3we1ad-kzmne4?file=index.html

I tried to use the new syntax for label and achieve the original look and behavior like demonstrated in this link.

**Comment by liamdebeasi** [comment]
Thanks for the report. In the "Try to use new syntax" section did you mean to use `label-placement="floating"` instead of `label-placement="fixed"`? The legacy syntax in your example is using the `"floating"` label placement.

**Comment by Wasenshi123** [comment]
I mean, if the placement is floating, it's behave correctly and same with legacy.

But if the placement is fixed, and if you expand the window screen size, you will see that the label always show, unlike the legacy, which also hide placeholder first, then only show when focus.

**Comment by liamdebeasi** [comment]
You should be able to hide the placeholder with CSS: 

```css
ion-input.custom-input {
  --placeholder-opacity: 0;
}
```

The input placeholder is not meant to be programmatically shown/hidden, so I don't recommend doing this. For your particular use case, I'd encourage you to not change the label layout based on screen size. If you are concerned about screen space, the `"floating"` label placement is designed with screen space in mind. Switching the labels based on screen size adds considerable complexity to your forms and isn't really how these components are intended to be used.
