### ISSUE TITLE
bug: Alert Controller does not accept IonicSafeString

### ISSUE THREAD

**Issue by znotdead** [ionic-team/ionic-framework#27245]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

By docs https://ionicframework.com/docs/api/alert you may use as message IonicSafeString.

    const safeString = new IonicSafeString('<b>Some Html Text</b>');
    const alert = await this.alertController.create({
      header: 'Error!',
      message: safeString,
      buttons: ['OK'],
    });

Shows message 'undefined'

### Expected Behavior

Code above should show text 'Some Html Text' in bold.

### Steps to Reproduce

1. Create an alert with message `new IonicSafeString('<b>Some Html Text</b>')`
2. Open alert

### Ionic Info

Ionic:

   Ionic CLI                     : 7.0.1
   Ionic Framework               : @ionic/angular 7.0.3
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.6
   @angular/cli                  : 15.2.6
   @ionic/angular-toolkit        : 9.0.0

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : android 11.0.0, browser 6.0.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 11 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v18.13.0 
   npm    : 8.19.3
   OS     : Linux 5.19

**Comment by liamdebeasi** [comment]
Thanks for the report. Do you have `innerHTMLTemplatesEnabled` set to `true` in your config? You need that in order to use custom HTML in `ion-alert`: https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#config

**Comment by znotdead** [comment]
Good point. It will be nice to do not enable this globally but have it only in case by case with SafeIonicString.

If I enable in config by innerHTMLTemplatesEnabled I don't need SafeIonicString at all. As I understand the whole point of SafeIonicString is to use it in case by case without globally enabling. So expected behavior either enable in IonicConfig or use SafeIonicString. 
https://ionicframework.com/docs/techniques/security#bypassing-the-sanitizer-on-a-case-by-case-basis

**Comment by liamdebeasi** [comment]
In order to use custom HTML, regardless of your `IonicSafeString` usage, you need to set `innerHTMLTemplatesEnabled: true` in your Ionic Config.

Ionic comes with a basic DOM sanitizer that is used when `innerHTMLTemplatesEnabled: true`. Using `IonicSafeString` lets you bypass the basic DOM sanitizer and (dangerously) set custom HTML content.

**Comment by liamdebeasi** [comment]
That's the existing behavior as using `IonicSafeString` skips the sanitizer.

**Comment by znotdead** [comment]
it's skips only if innerHTMLTemplatesEnabled: true, it will be nice to have behavior when innerHTMLTemplatesEnabled: false, so only in particular place it will be passed. or option individually enabling innerHTMLTemplatesEnabled per ion-alert component instead of globally for the config. So all app will be protected and only in few places sanitation will be passed.

**Comment by liamdebeasi** [comment]
The `innerHTMLTemplatesEnabled` feature was designed to be a way for developers to opt-in to the custom HTML behavior globally while understanding the risks of setting content using `innerHTML`. At the moment we don't have plans to add a feature to configure `innerHTMLTemplatesEnabled` per-component.

Long term we'd like to find a way to allow for custom HTML in a safer way without the use of `innerHTML`, so the `innerHTMLTemplatesEnabled` feature will hopefully not be needed in the future. I am going to close this, but let me know if you have questions.
