### ISSUE TITLE
feat: More option for justify (ion-select)

### ISSUE THREAD

**Issue by Wasenshi123** [ionic-team/ionic-framework#27242]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Related to this: #27239

I would like to request that ion-select's justify has more option to make the placeholder appear after the label, but the arrow at the end.

### Describe the Use Case

https://stackblitz.com/edit/3we1ad-kzmne4?file=index.html

I am trying to use new modern syntax for label and as you can see in the link, ion-select 's placeholder is aligned at the end of the box. Unlike the original, it's aligned at the start.

(If I use justify="start", the arrow is also moved too, I don't want that)

### Additional Information

Perhaps it would be better if we can control each elements individually (placeholder alignment and arrow alignment separately)

**Comment by liamdebeasi** [comment]
Thanks for the report. I'm going to fold this into: https://github.com/ionic-team/ionic-framework/issues/27112

If you had access to the native select wrapper you would be able to do something like this to get the desired result:

```html
<ion-select justify="start" label="My Label">...</ion-select>
```

```css
ion-select::part(wrapper) {
  width: 100%;
}
```

We plan on adding #27112 in an upcoming feature release of Ionic.
