### ISSUE TITLE
bug: popover interface of ion-select not working in Ionic v6 for Vue

### ISSUE THREAD

**Issue by pogiako21301** [ionic-team/ionic-framework#27252]
### Describe the Bug

The pop-over in ionic 6 is not working in my project, what I mean is its not displaying when I click but the other interface is working, just the popover is not working.

### Expected Behavior

When I click the ion-select it display the ion-select-option in the interface of pop-over

### Steps to Reproduce

Its not working

### Screenshots

![image](https://user-images.githubusercontent.com/84213968/233237500-4ccfb41a-b898-4c5c-bf51-dad2121a34e7.png)
![image](https://user-images.githubusercontent.com/84213968/233237531-38a34ab7-27cb-4317-b45a-f7cf7b014b16.png)

### Operating System

Windows 10

### Browser

Chrome

### Version

112.0.5615.137

**Comment by mapsandapps** [comment]
Hi, @pogiako21301 I am unable to reproduce this issue in Ionic Framework v7. Could you please try updating to v7 and see if that resolves the issue? If that does not fix the problem, please include a [code reproduction](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-a-good-code-reproduction) using v7. Thank you.

**Comment by AkliOnet** [comment]
hi , i use the version "@ionic/vue": "^7.0.4",  "@ionic/vue-router": "^7.0.4" and i encounter the same proplem. the popover seems to be behind.

**Comment by amandaejohnston** [comment]
This issue is being closed due to only being reproducible in Ionic v6, and missing a reproduction in the latest version of Ionic. If this is still a problem you're running into in Ionic v7, please create a new issue and ensure the template is fully filled out. Thank you!
