### ISSUE TITLE
feat: Option to disable scroll position restoration for cached pages

### ISSUE THREAD

**Issue by hakimio** [ionic-team/ionic-framework#27250]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

When navigating to a cached page, I would like the `scrollTop` to always be reset to zero. Right now Ionic restores the previous position on navigation and there doesn't seem to be a way to opt-out of this behavior.

### Describe the Use Case

I am reusing the same page with different content and, when I programmatically navigate to a cached page, I expect the scroll position to be reset instead of keeping the previous one. When content changes it doesn't make sense to reuse old scroll position.

### Describe Preferred Solution

```ts
IonicModule.forRoot({
    mode: 'md',
    scrollRestore: false
})
```

### Describe Alternatives

AFAIK, right now the only way to achieve the desired behavior is to listen to `ionViewDidLeave` event and manually reset scroll position in the event listener.

### Additional Information

```
@ionic/angular: 7.0.0

Angular CLI: 15.2.5
Node: 18.15.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 15.2.5
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.5
@angular-devkit/build-angular   15.2.5
@angular-devkit/core            15.2.5
@angular-devkit/schematics      15.2.5
@schematics/angular             15.2.5
rxjs                            7.8.0
typescript                      4.9.5
webpack                         5.77.0
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you explain your use case? Preserving scroll location is typically an important part of the mobile app UX since previous pages can be accessed.

**Comment by hakimio** [comment]
The application has a wizard like flow similar to the following:

1. The user is presented with `Page1` with information `1A`
2. After pressing "Next", the app navigates to `Page2` with information `2A`
3. Pressing "Next" again, returns to `Page1` but the information has changed to `1B` (the query or matrix params haven't changed)
4. On next step it returns back again to `Page2` with information `2B`

**Comment by liamdebeasi** [comment]
You should be able to reset the scroll position in the `ionViewWillEnter` lifecycle by calling [scrollToTop](https://ionicframework.com/docs/api/content#scrolltotop) on `ion-content`. Can you give that a try?

**Comment by liamdebeasi** [comment]
The requested behavior seems specific to your app's use case, so I'm not sure this feature would be a good fit for Ionic. The typical approach for mobile apps is to preserve the scroll position, so we'd like to encourage the behavior that most users are going to expect.

**Comment by liamdebeasi** [comment]
Another idea you could try is using a parameterized route to create a new instance of Page 1. That would allow you to create a new instance of the page and not worry about resetting the scroll position.

**Comment by hakimio** [comment]
Yes, parameterized route is another valid workaround, but in this case page won't be cached anymore.

Anyway, I agree that it makes sense to restore scroll position in most Ionic apps and my use case is not very common, but, since `ion-router-outlet` is trying to keep compatibility with Angular `router-outlet`, I would argue that allowing users to choose whether to restore the scroll position (Ionic behavior) or not (Angular default behavior) makes a lot of sense.

If you don't agree and think the effort to implement this outweighs the benefit for most users, feel free to close this issue.
