### ISSUE TITLE
bug(scroll-assist): wrong keyboard offset applied

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#27257]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Noticed a strange behavior with scroll assist and keyboard offset, which is **absolutly breaking our apps** right now.

See attached stackblitz and open it somewhere where you have a keyboard. Clicking through the inputs adds a increasing keyboard offset which increases until the inputs are completly out of screen.

**Additional question**: I meantioned that this bug also appears on my ipad while a external keyboard is connected, so there should no shifting at all. Is this possible to detect?

### Expected Behavior

The scroll assist should work correctly

### Steps to Reproduce

1. Open attached stackblitz on a device with keyboard
2. Click through the inputs
3. See the keyboard offset on the ion content element increasing

### Code Reproduction URL

https://github-1mgkjv-2v6hef.stackblitz.io/home

### Ionic Info

Starter template in stackblitz

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you try the following dev build and let me know if it resolve the issue?

```
7.0.4-dev.11682093009.1ad4d136
```

Note that this dev build only resolves the keyboard offset continually increasing. The behavior should be better with an external keyboard though.

**Comment by EinfachHans** [comment]
@liamdebeasi i updated the stackblitz with the dev build, doesn't looks like it is resolved 🤔

**Comment by liamdebeasi** [comment]
StackBlitz has a bug with non-Web Containers applications where it always installs the latest version. Try the dev build in an Ionic starter app instead.

**Comment by EinfachHans** [comment]
Ahh good to know, thanks! I just tested in on of our apps where i mentioned this bug the first time.

Seems like the initial bug is fixed, but see attached video:

1. i focus the username field and then the password field. The scroll assists moves it up.
2. i focus directly the password field, it does not move into the same state as in 1
3. i focus another time the password input. Now the scroll assist moves up correctly, so it's inconsistent to 2 - after i dismiss the keyboard via finish the input kinda keeps focused why the content stays shifted up

https://user-images.githubusercontent.com/20899975/233709122-98881c09-d612-49d9-a10c-1e686311fb8c.MOV

**Comment by liamdebeasi** [comment]
Why is the keyboard disappearing in the video? It looks like something is happening in the app unrelated to Ionic.

**Comment by EinfachHans** [comment]
You mean why the keyboard is not visible in the video all the time? it was 100% visible while recording, looks more like a ios screen recording thing. There is no custom logic applied here

**Comment by liamdebeasi** [comment]
Do you have a repro app I can test with? The resize behavior in your video does not look like it's coming from Ionic. The scroll assist utility adds padding to the bottom and then scrolls instead of changing the height of the content.

**Comment by EinfachHans** [comment]
i will create a repo for you to reproduce tomorrow!

**Comment by EinfachHans** [comment]
Here is a very simple reproducable repo, which appears as buggy as in the video above: https://github.com/EinfachHans/ionic-scroll-assist-bug

I tested via `ionic serve` & ngrok on safari on my iPhone 13 Pro (iOS 16.4.1)

**Comment by mpaland** [comment]
I can observe a similar problem in our app, I already reported this in #26804 but had to postpone this issue.
Anyway, I don't suspect the capacitor/keyboard plugin here. 
There seems to be a problem with --keyboard-offset applied to `<ion-content>`. I can observe this behavior in a Chrome browser on Windows in responsive mode, so it's not related to a mobile device.

Clicking in an `<ion-input>` field adds a `style="--keyboard-offset: 290px"` to `<ion-content>`.
Clicking again on any input field increments the offset by 290 to `style="--keyboard-offset: 580px"`, and so on.

This was fine in v6, the offset was always zero.

**Comment by liamdebeasi** [comment]
@EinfachHans Good catch! Here's a new dev build: `7.0.4-dev.11682349733.1a34cc9b`

Note that the content jumping is the correct behavior due to how padding impacts the flex container in your app.

**Comment by mpaland** [comment]
> Here's a new dev build: `7.0.4-dev.11682349733.1a34cc9b`

I tested this build, it makes thinks partially better.

There is still the (unnecessary) --keybord-offset of 290px on `ion-content`, but this offset is not incremented anymore when clicking on `ion-input` several times.

**Comment by liamdebeasi** [comment]
> There is still the (unnecessary) --keyboard-offset of 290px on ion-content, but this offset is not incremented anymore when clicking on ion-input several times.

The keyboard offset is there to ensure that inputs have enough scroll space such that the inputs are not hidden by the keyboard. When running in a browser we don't know the exact keyboard size ahead of time, so we estimate it to be 290px.

**Comment by mpaland** [comment]
I see, and I don't want to open the old discussion about the keyboard offset and scrollassist again.
But on my Android mobile, opening the keyboard now pushes the whole viewport up so that there is a gap between the bottom element and the top of the keyboard of 290px. Visually unpleasant.

**Comment by liamdebeasi** [comment]
> I see, and I don't want to open the old discussion about the keyboard offset and scrollassist again. But on my Android mobile, opening the keyboard now pushes the whole viewport up so that there is a gap between the bottom element and the top of the keyboard of 290px. Visually unpleasant.

Does this happen on the latest stable version of Ionic too? If so, please file a new issue.
