### ISSUE TITLE
bug: Popover CSS Shadow Parts not work on android 8.0

### ISSUE THREAD

**Issue by Lyfei** [ionic-team/ionic-framework#27264]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Modify the CSS Shadow Parts of a content, worked on android 11, but not work on android 8.0;

### Expected Behavior

Worked on android 8.0

### Steps to Reproduce

html:
```html
<ion-popover [isOpen]="isOpenPopOver" (ionPopoverDidDismiss)="selectOnDidDismiss($event)">
    <ng-template>
        <!-- custom component-->
        <app-multiple-select [selectOptions]="selectOptions"></app-multiple-select>
    </ng-template>
</ion-popover>
```

add css on global.scss
```css
ion-popover::part(content){
  border-radius: 0;
  width: 100%;
  left: 0 !important;
  box-shadow: none;
}
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.9 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.7.3
   @angular-devkit/build-angular : 12.2.17
   @angular-devkit/schematics    : 12.2.17
   @angular/cli                  : 12.2.17
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : 4.6.1
   @capacitor/core    : 4.6.1
   @capacitor/ios     : 4.6.1

Utility:

   cordova-res (update available: 0.15.4) : 0.8.1
   native-run                             : 1.7.2

System:

   NodeJS : v12.14.1 (/usr/local/bin/node)
   npm    : 6.13.4
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Thanks for the report. The webview version is what determined support, not the Android version. What is the webview version on your Android 8.0 device? You can find this by logging `window.navigator.userAgent` when inspecting the app using Chrome dev tools.

**Comment by Lyfei** [comment]
> Thanks for the report. The webview version is what determined support, not the Android version. What is the webview version on your Android 8.0 device? You can find this by logging `window.navigator.userAgent` when inspecting the app using Chrome dev tools.

version:
Chrome/70.0.3538.110
