### ISSUE TITLE
bug: Loading doesn't stop after upgrading to ionic 7.0 

### ISSUE THREAD

**Issue by MassimilianoOreto** [ionic-team/ionic-framework#27279]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have an interceptor that start loading when a new request start and close the loading when the request end. After upgrading from Ionic 6 to 7 this Loading doesn't stop.

### Expected Behavior

The loading stop like in 6.0 version

### Steps to Reproduce

I have installed a fresh solution, then i put this intercpetor on my project:

`@Injectable()
export class LoaderManagerInterceptor implements HttpInterceptor {
  loading = this.loadingController.create({
    spinner: 'circles',
  });
  constructor(private loadingController: LoadingController) {}

  intercept(
    httpRequest: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    this.startLoading().then();
    return next.handle(httpRequest).pipe(
      finalize(() => {
        this.stopLoading().then();
      })
    );
  }

  async startLoading() {
    const loader = await this.loading;
    loader.present().then();
  }

  async stopLoading() {
    const loader = await this.loading;
    loader.dismiss().then();
  }
}`

When the first request processed by intercept start, the loading start and never stop

### Ionic Info

Ionic CLI : 7.0.1 
   Ionic Framework               : @ionic/angular 7.0.3
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.6
   @angular/cli                  : 15.2.6
   @ionic/angular-toolkit        : 9.0.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.14.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10

### Additional Information

Can't upload a repo because it needs a backend system for the request response.

**Comment by hakimio** [comment]
Why are you calling `then()` on methods returning `Promise` from your `async` functions?

**Comment by MassimilianoOreto** [comment]
> Why are you calling `then()` on methods returning `Promise` from your `async` functions?

Just because my IDE give me a warking of promise ignored. Only to stop ide warning. The problem still remain also without then()

**Comment by hakimio** [comment]
Why don't you just `await` those promises since you are using `async` function?

**Comment by MassimilianoOreto** [comment]
> Why don't you just `await` those promises since you are using `async` function?

Just do it for clear code, but obviously the problem is still here

**Comment by MassimilianoOreto** [comment]
https://github.com/MassimilianoOreto/testionic7

Added this repo to reproduce the problem

**Comment by liamdebeasi** [comment]
Did you push your changes? I only see a blank starter app.

**Comment by MassimilianoOreto** [comment]
Yes is ok. To replicate the error i create a new Ionic7 app without contents and i insert there the loadercomponent and a simple request on appcomponent. 
I will try this and i see that the loader doesn't stop after the request. The project is just to replicate error

**Comment by liamdebeasi** [comment]
I'm not able to reproduce the reported behavior. The loader correctly dismisses after a timeout. Can you provide some steps to reproduce?

**Comment by MassimilianoOreto** [comment]
I see that i can reproduce if i have chrome consolle opened (f12)

**Comment by liamdebeasi** [comment]
Does this issue reproduce without dev tools open?

**Comment by MassimilianoOreto** [comment]
No, the solution i provide doesn't reproduce with or without dev tools. I have the problem only with Loadingcontroller

**Comment by liamdebeasi** [comment]
I understand that the issue does not reproduce with the solution you provided, but does the original issue (without your solution) still reproduce even if dev tools is closed?

**Comment by liamdebeasi** [comment]
Thanks for the reply. This appears to be related to https://github.com/ionic-team/ionic-framework/issues/27200, so I am going to merge the two threads.
