### ISSUE TITLE
bug: Scroll Assist - Focus on ion-input moves input up visually

### ISSUE THREAD

**Issue by mpaland** [ionic-team/ionic-framework#27286]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

This issue can be observed on an Android phone using Chrome or Firefox. I tested this on a Blackberry Key which has a hardware keyboard and opens no virtual keyboard in the first place.

Clicking (focus) on an ion-input adds 290px of keyboard offset at the end of the screen
Clicking another ion-input adds 290px again (580px now).

This was fine (no offset) with Ionic v6, nor can this behavior observed in other apps.
Related issues are: #27257 and #26804

### Expected Behavior

No offset added when not necessary.

### Steps to Reproduce

Create a simple page with <ion-content> and multiple <ion-input>.
Focus different inputs .

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.1 (C:\Users\Marco\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.0.4

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.15.1 (D:\nodejs\node.exe)
   npm    : 9.1.2
   OS     : Windows 10

### Additional Information

Setting --keyboard-offset fix to 0 mitigates the problem, but I guess not on all platforms.

**Comment by liamdebeasi** [comment]
Thanks for the report. We were able to fix this in https://github.com/ionic-team/ionic-framework/commit/7e1f996dc63cd414b30b22aebbfc09b0b6b4f6fc, and the fix should be available in an upcoming release of Ionic. I am going to close this since the work required to fix this has been completed, but let me know if you have questions.
