### ISSUE TITLE
bug: ion-action-sheet cancel-button not visible in long option list

### ISSUE THREAD

**Issue by mpaland** [ionic-team/ionic-framework#27285]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Create a long ion-action-sheet or ion-select with action-sheet interface with options > viewport height, like

``` html
        <ion-select label="City / Zone" label-placement="start" interface="action-sheet">
          <ion-select-option>Test 1</ion-select-option>
          <ion-select-option>Test 2</ion-select-option>
          <ion-select-option>Test 3</ion-select-option>
          <ion-select-option>Test 4</ion-select-option>
          <ion-select-option>Test 5</ion-select-option>
          <ion-select-option>Test 6</ion-select-option>
          <ion-select-option>Test 7</ion-select-option>
          <ion-select-option>Test 8</ion-select-option>
          <ion-select-option>Test 9</ion-select-option>
          <ion-select-option>Test 10</ion-select-option>
          <ion-select-option>Test 11</ion-select-option>
          <ion-select-option>Test 12</ion-select-option>
          <ion-select-option>Test 13</ion-select-option>
          <ion-select-option>Test 14</ion-select-option>
          <ion-select-option>Test 15</ion-select-option>
        </ion-select>
```

On my Android phone this is looking like:
![Screenshot_20230426-154521](https://user-images.githubusercontent.com/763140/234617569-0b0a9b29-e0f9-4545-a16e-452e68b02b69.png)
The cancel button is not visible. Same on Chrome and Firefox.

Problem is, that I can't observe this behavior in Desktop browsers, not even in responsive mode.

### Expected Behavior

Cancel button must be visible.

### Steps to Reproduce

Use the code above and create an ion-action-sheet or in-select with options that do not fit on the screen.

### Ionic Info

onic:

   Ionic CLI       : 6.20.4 (C:\Users\Marco\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.0.4-dev.11682349733.1a34cc9b

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.15.1 (D:\nodejs\node.exe)
   npm    : 9.1.2
   OS     : Windows 10

### Additional Information

There seems to be a problem with  `--height` of the action-sheet-container, which is set to `auto` by default.

```
.sc-ion-action-sheet-ios-h {
  --height: auto;
}
```

Setting this to
  `--height: 100%;`
or
  `--height: 100vh;`
fixes the problem.

Using an ion-action-sheet, --height can be set as custom property, but this is not possible for ion-select.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. What version of the Chromium web view are you running? You can find this by logging `window.navigator.userAgent` when inspecting the app with dev tools.
