### ISSUE TITLE
feat: Add option "center" to attribute "justify"

### ISSUE THREAD

**Issue by Lechevallier** [ionic-team/ionic-framework#27296]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I wish `justify` could accept the option `center` which would have this behaviour (see last select)
![image](https://user-images.githubusercontent.com/10246002/234834140-4acb55bf-73fe-4e36-bdcf-54bc9c1b84f6.png)

### Describe the Use Case

This option would be useful in some use cases, when select doesn't have a label for example:
![image](https://user-images.githubusercontent.com/10246002/234834529-1f9b78b8-43f4-4d36-a922-aeb1d9387bdc.png)

### Describe Preferred Solution

Code:
```tsx
<IonSelect
     justify="center"
     ...
/>
```
Result:
![image](https://user-images.githubusercontent.com/10246002/234834785-8ceac48e-f167-4277-87a2-42141e8046cc.png)

### Describe Alternatives

Add `part="label"` on label element to allow developer style the shadow-root to fit their needs.

**Comment by amandaejohnston** [comment]
Thank you for the issue. This can be accomplished by setting `ion-select { width: auto; }` in the CSS, and then centering the select in the container. Here's an example: https://stackblitz.com/edit/angular-qp6cvc?file=src%2Fmain.tsx,src%2Fmain.css

Does this work for your use case? If not, do you have any examples of native apps that use this behavior?

**Comment by Lechevallier** [comment]
Hello @amandaejohnston, thanks for your reply.

It does actually solve my problem!!

I struggled half day trying to modify the shadow-root, resulting in an ugly solution:
```tsx
useEffect(() => selectElement.current?.shadowRoot?.children[0].setAttribute('style', 'display: flex; align-items: center; justify-content: center;'), [selectElement]);
```

You solution is clean, thanks a lot!

**Comment by amandaejohnston** [comment]
Excellent. In that case I'm going to go ahead and close this out, but let me know if you run into problems with the CSS approach and may want a feature added after all.
