### ISSUE TITLE
bug: broken reactivity with VueJS

### ISSUE THREAD

**Issue by submgr** [ionic-team/ionic-framework#27295]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

After a recent update, reactivity does not work in my Vue + Ionic projects (when changing a variable, it is updated on render).

### Expected Behavior

Reactivity should work (as in previous versions)

### Steps to Reproduce

1. Create a new clean project with VueJS (tabs template for example)
2.  Create a simple numeric variable and a method that increments it on click
3. Try it out

### Code Reproduction URL

https://github.com/submgr/AmcProject

### Ionic Info

```
PS C:\Users\aramt\OneDrive\Documents\VisualStudio Code\Projects\amcproject\AmcProject> ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\aramt\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\aramt\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\aramt\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\aramt\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package'

       Require stack:
       - C:\Users\aramt\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\aramt\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\aramt\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\aramt\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 6.20.9 (C:\Users\aramt\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.0.4

Capacitor:

   Capacitor CLI      : 4.8.0
   @capacitor/android : not installed
   @capacitor/core    : 4.8.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.17.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.2.0
   OS     : Windows 10
```

### Additional Information

Video: https://vimeo.com/821590324?share=copy

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you make your repo public?
