### ISSUE TITLE
feat: expose shadow components for styling inputs

### ISSUE THREAD

**Issue by Webrow** [ionic-team/ionic-framework#27316]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Expose a shadow component for native input element for CSS selection

### Describe the Use Case

To my understanding, with the coming of ionic 7, we have lost exposure to the input element (since everything is managed from the label with attributes now). Using our old designs where we modified the way an input looked 
![image](https://user-images.githubusercontent.com/3177853/235142892-c6d4ccfd-6bc7-4121-91f0-655c324ea016.png)
with the following CSS: 
```
ion-input {
  &.round-fill {
    border-radius: 8px;
    border: 1px var(--ion-color-medium) solid;
    --background: var(--ion-color-light);
  }
}
```
Now styling the input (for floating elements for example) has a complete wrapping .div and makes this styling unsuitable. I've instructed the designer to look at the designs to make them "ionic 7 proof" nevertheless, it was the small things that we could use to style elements with (we have a lot of shadow elements, but not always enough ;p). 

### Describe Preferred Solution

--

### Additional Information

Personally I am not the biggest fan of targetting shadow components, and prefer using the variables provided on the ionic-items. Nevertheless sometimes it is necessary. I prefer not to use ng-deep and such things to keep performance running.

**Comment by liamdebeasi** [comment]
Thanks for the report. You can currently target the internals of these components using CSS as you normally would, so no shadow parts should be needed. This is because `ion-input` and `ion-textarea` do not use the Shadow DOM so there is no hard style encapsulation. Just note that these are [scoped components](https://ionicframework.com/docs/reference/glossary#scoped) meaning you should apply a custom class on the host of the component to have higher specificity than the built-in styles.

```html
<ion-input class="custom-input"></ion-input>
```

```css
ion-input.custom-input {
  --background: red;
}
```

**Comment by Webrow** [comment]
Thanks Liam, if I am correct I am trying to target this part of the dom (sorry for the wide screenshots)  
![image](https://user-images.githubusercontent.com/3177853/235425944-07ae1b50-18ff-46d0-a32a-54bfafa3cf28.png)


Using the stackblitz from the relative documentation. I still dont seem to be able to target the input sepertly from the label 
![image](https://user-images.githubusercontent.com/3177853/235425977-2a575678-206a-4840-a2b4-03a981c9a298.png)

**Comment by liamdebeasi** [comment]
Try selecting `.native-input` which is the class assigned to `input`. Classes have a higher specificity than element tag names.

**Comment by Webrow** [comment]
See the worked out example. Same issue.
Looked for "blue" or rgb color in the inspector on the children of custom-input, it doesn't get applied anywhere. 

![image](https://user-images.githubusercontent.com/3177853/235456060-dde2f31a-3e94-40e7-b889-31a27e0080ce.png)

**Comment by liamdebeasi** [comment]
Are you using Angular? If so, you likely have component encapsulation enabled: https://angular.io/guide/view-encapsulation. Angular's view encapsulation is great if you control the templates of everything being rendered, but it can cause issues when trying to customize 3rd party components.

Try moving the `.native-input` CSS to a global stylesheet (like globals.css).
