### ISSUE TITLE
bug: no way to set color for <ion-input label>  - request for @labelColor

### ISSUE THREAD

**Issue by trakhimenok** [ionic-team/ionic-framework#27326]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Looks like the new implementation is a regression and we lose ability to customize label styling.

With new way of setting labels for inputs (_ion-input, ion-select, etc_) there is seems no way to set color for labels.

Previously:
```
<ion-item>
  <ion-label color=medium>My label<ion-label>
  <ionp input />
</ion-input>
```
![image](https://user-images.githubusercontent.com/533159/235176815-0846762b-0a55-477a-a721-326d6c80cc8b.png)

Now
```
<ion-item>
  <ion-input label="My label"/>
</ion-input>
```
![image](https://user-images.githubusercontent.com/533159/235176060-cd972830-06d1-43c3-8859-88db80612710.png)

### Expected Behavior

I believe an attribute `labelColor` should be provided to customize label.

This should be applied for all inputs that take label (_ion-input, ion-select, ion-radio, etc_)

### Steps to Reproduce

Simply check new label vs old with color.

### Ionic Info

I'm using NX so for some reason `ionic info` is not very informative:

```
➜  src git:(main) ✗ ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v18.2.0
   npm    : 8.9.0
   OS     : macOS Unknown
```

### Additional Information

It would be good to know what is the reason for the change.

**Comment by liamdebeasi** [comment]
Thanks for the report. You can set the label color already in Ionic: https://codepen.io/liamdebeasi/pen/mdzwNJa

Is there something that is not working on your end?

**Comment by trakhimenok** [comment]
@liamdebeasi this would work.

I just have not found this way in documentation. Is .label-text class documented anywhere?

I also kinda liked the way to set colors through ionic's color attribute but I can live with a custom class.

I'll give it a try over the weekend.

**Comment by liamdebeasi** [comment]
The internal structure of our components are not documented currently, but you can interact with `.label-text` in your preferred browser development tools.

As for components where you pass the label text directly inside of the component (i.e. checkbox, toggle, radio, etc) you can definitely continue to use `ion-label` to get the color behavior as long as you are passing the label inside of the component:

```html
<!-- Not Recommended -->
<ion-label color="danger">My Label</ion-label>
<ion-radio></ion-radio>

<!-- Recommended -->
<ion-radio>
  <ion-label color="danger">My Label</ion-label>
</ion-radio>
```

**Comment by liamdebeasi** [comment]
> The warning says should not be used at all:

Yeah that warning is a bit confusing. I'll look into clarifying that.

> Can I also pass ion-label inside ion-input & ion-textarea?

Not at the moment. See https://github.com/ionic-team/ionic-framework/issues/27061.

**Comment by trakhimenok** [comment]
Liam, below worked for me:
```
.sneat-label-color-medium .label-text {
  color: #92949c;
}

<ion-input class="sneat-label-color-medium" [label]="labelText()" labelPlacement="fixed"
```

But I wonder how to account for themes (_dark/light_)? Below does NOT work for me.

```
.sneat-label-color-medium .label-text {
	color: var(--ion-color-medium);
}
```

Previously `<ion-label color=medium>` would handle theming.

**Comment by liamdebeasi** [comment]
Is `--ion-color-medium` defined?

**Comment by trakhimenok** [comment]
You right, the variables file was not added to the app I've tested.

The `--ion-color-medium` works fine with custom CSS class. Closing this.
