### ISSUE TITLE
bug: ion-textarea is broken on IOS if label position "floating" or "stacked" is used

### ISSUE THREAD

**Issue by bhalbritter** [ionic-team/ionic-framework#27345]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If the ion-textarea is used on safari with the label position floating or stacked, the text goes outside the textarea and prevents elements behind from being clickable.

![image](https://user-images.githubusercontent.com/63356794/235498487-10130938-8a91-4396-b699-2a6dc5992cd4.png)

### Expected Behavior

I expect the same behavior as when I use the textarea with another label position (start). 

![image](https://user-images.githubusercontent.com/63356794/235499146-4e85039e-374c-477c-bc84-8cacdb1b2084.png)

### Steps to Reproduce

1. create new Textare with a label and label position floating or stacked
2. open the textarea in Safari and start adding multiple rows

### Code Reproduction URL

https://github.com/bhalbritter/IonicTextareaBug

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.4

Capacitor:

   Capacitor CLI      : 4.8.0
   @capacitor/android : not installed
   @capacitor/core    : 4.8.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v19.2.0 (/opt/homebrew/Cellar/node/19.2.0/bin/node)
   npm    : 9.6.0
   OS     : macOS Unknown

### Additional Information

Safari Version 16.3 (18614.4.6.1.6)

On Chrome everything works fine.

**Comment by liamdebeasi** [comment]
Thanks for the report. Here is a dev build with a proposed fix if you are interested in testing it:

```
npm install @ionic/react@7.1.3-dev.11688748118.18ff9e7d @ionic/react-router@7.1.3-dev.11688748118.18ff9e7d
```

The root issue is caused by a WebKit bug where children of grid elements placed inside flex elements have the wrong size: https://bugs.webkit.org/show_bug.cgi?id=256781

**Comment by bhalbritter** [comment]
I just testet it, works without any issues now 👍
