### ISSUE TITLE
feat: Add a css custom property to configure the ion-searchbar height

### ISSUE THREAD

**Issue by JulienLecoq** [ionic-team/ionic-framework#27342]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

There is currently no custom property to configure the ion-searchbar height.

### Describe the Use Case

Add the possibility to modify the height of the ion-searchbar via un custom property.

### Describe Preferred Solution

Add the --height custom property to the ion-searchbar component.

**Comment by sean-perkins** [comment]
Hello @JulienLecoq thanks for submitting this feature request! Can you share some examples of the type of UI you are trying to accomplish and/or the challenges with styling the search bar currently?

The search bar uses scoped encapsulation, meaning you can target and style any of the elements used internally, including changing the height of the search bar: https://stackblitz.com/edit/tk1ugg?file=index.html
