### ISSUE TITLE
feat: Return pop result from NavController

### ISSUE THREAD

**Issue by andrzejpindor** [ionic-team/ionic-framework#27403]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

NavController pop method does not return status (boolean) not allowing to ensure that pop was successful.

### Describe the Use Case

Custom navigation when using NavController, allowing user to go "back" using pop, but failover to default route when navigation stack is empty

**Comment by andrzejpindor** [comment]
Hi @sean-perkins I prepared a merge request to change the behavior for NavController https://github.com/ionic-team/ionic-framework/pull/27404

**Comment by liamdebeasi** [comment]
This was added via https://github.com/ionic-team/ionic-framework/pull/27404. The feature will be available in the next minor release of Ionic. Thank you again for the contribution!
