### ISSUE TITLE
feat: Qwik Support

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#27418]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi, now that Qwik is out of beta, it would be great if this framework was supported, just like Angular, React and Vue.

In addition, Manu Almeida from Stencil and Adam Bradley from Ionic are on the team, which I know he has nothing to do with but it is an encouragement.

For people like me who come from Angular it will be difficult for us to adapt because it is more like React, but it looks very good and I think it is worth it.😀

https://qwik.builder.io/

Greetings!

### Describe the Use Case

New framework for Ionic.

**Comment by liamdebeasi** [comment]
Could you clarify how you would plan to use Ionic with Qwik?

**Comment by Marius-Romanus** [comment]
Hi Liam, good question. As I have commented, I come from the Angular world without SSR. Although I have never explored it but I understand that Ionic has support for SSR in Angular https://ionic.io/blog/ssr-with-angular-universal-and-ionic, and I think that would be a key point for Qwik since it's power is in resumability, which I don't know if it's worth it in a native application... I'm no expert and I don't know how it works under the hood, I just launched too fast with a bit of hype, it would be nice if people who understand more about Qwik enlighten us a bit, if it's something that makes sense or not.

**Comment by liamdebeasi** [comment]
If developers are actively running into issues with building mobile apps that Qwik could solve, we'd love to hear more about it.

**Comment by Lxstr** [comment]
Qwik seems to solve a lot of the web performance issues of all Frameworks.

Could be the holy grail of performance to run qwik with ionic components and the option to use capacitor and PWA on mobile in one codebase

I'd like to learn it

**Comment by liamdebeasi** [comment]
Can you be more specific as to the kinds of web performance issues Qwik solves?

**Comment by Marius-Romanus** [comment]
Hi, even though I was the one who opened the change request, I'm starting to think that this is not a good approach, let me explain.

In Angular by default it is compiled as SPA and you have all the files in a static way, package together with Capacitor and show it in the webview (I imagine in React and Vue too), but with Qwik this is not possible at the moment.

I think that until Qwik doesn't support this, Ionic won't be able to create ui components... And even if it supports it, the best thing would be to create your own components with the help of tailwind for example or possible components that will come out in the future of qwik, and compile Qwik + Capacitor or Qwik + Cordova.

Here is a static files issue for Qwik: https://github.com/BuilderIO/qwik/issues/1340

**Comment by liamdebeasi** [comment]
Hi everyone,

I spoke with the team, and we do not have plans to add Qwik support to Ionic at the moment. There is not a lot of support for this from the Ionic community, and we are not aware of major mobile app development pain points that would be addressed by using Qwik.

I am going to close this, but we are happy to consider this again if there is more community support for it in the future.
