### ISSUE TITLE
bug: Ionic 7 React - Ionic classes are overwritten when changing class attribute on component

### ISSUE THREAD

**Issue by DevonStern** [ionic-team/ionic-framework#27415]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When changing the value of the class attribute on an Ionic component in Ionic 7 React, the Ionic-specific classes for that component are removed.

For example, in a blank Ionic 7 React project, I added an IonButton component to the Home page and set the class attribute based on the value of a state variable from the useState hook. I then set up the IonButton to toggle the value of the state variable when clicked.

Before toggling the state, inspecting the ion-button element shows the following classes:

> md button button-solid ion-activatable ion-focusable

After toggling the state for the first time and every time thereafter, the ion-button element shows only the class I applied (or no class if I applied an empty string). All of the classes applied by Ionic are gone.

### Expected Behavior

As happened in Ionic 6, the classes applied by Ionic should be retained even after changing the value of the class attribute. So any classes that I apply through the class attribute should be in addition to the Ionic-specific classes, even after changing the value of the class attribute.

### Steps to Reproduce

1. In an Ionic 7 React app, add an Ionic component to the page (for example, IonButton)
2. Add a useState hook that defaults to false
3. Set up the button onClick handler to toggle the value of the state variable using the setter
4. Depending on the value of the state variable, set the class attribute on the Ionic component (could be set to any string in either case, though at least one should not be an empty string)

### Code Reproduction URL

https://github.com/DevonStern/ionic-bug-ionic-classes-overwritten

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.0 (C:\Users\DevonStern\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.0.5

Capacitor:

   Capacitor CLI      : 5.0.1
   @capacitor/android : not installed
   @capacitor/core    : 5.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. The problem here is that your application is using `class` instead of `className`. React applications should be using `className` to apply classes. See https://react.dev/reference/react-dom/components/common#applying-css-styles for more information. Changing `class` to `className` in your application fixes the issue.

**Comment by DevonStern** [comment]
Thank you for clarifying, @liamdebeasi .

I assume that there is, but is there a need for Ionic components in React to expose the `class` attribute? We were unsure which attribute was the correct one to use in Ionic components and wrongly assumed that `class` was the Ionic-preferred attribute to use, similar to `onIonChange` in place of `onChange`. If `class` is not supposed to be used, then removing it (if possible) might reduce confusion. Then again, we might be the only ones who were confused about that. 🙃

**Comment by liamdebeasi** [comment]
Can you point to where Ionic is exposing a class attribute? It should not be doing that. Ionic React components are React components, so they follow the same patterns as any React application (such as using className).

**Comment by DevonStern** [comment]
![class-attribute-in-ionic-react](https://github.com/ionic-team/ionic-framework/assets/35042843/44698388-0d7c-423c-9bcc-8ee12edd7b0a)

I see `class` listed in autocomplete in both CodeSandbox and VS Code. It shows that it is part of IonicReactProps.

**Comment by liamdebeasi** [comment]
Thanks! Looks like that is some old code from the beta version of Ionic React that never got removed. I'll open a PR to remove it.
