### ISSUE TITLE
bug: ion-content fullscreen is not compatible with pre-rendering

### ISSUE THREAD

**Issue by WDrzewiecki** [ionic-team/ionic-framework#27411]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

SSR not working after upgrading to angular 16, even in ionic starter app. After starting dev server and opening the app, the page loads until the server throws out of memory. 
With a production build server throws "NotYetImplemented" error and returns only original index.html file without rendered page.

### Expected Behavior

SSR should work with angular 16.

### Steps to Reproduce

1. Start SSR dev server (npm run dev:ssr)
2. Visit app located on localhost:4200
3. Loading continues until the server throws out of memory 
 OR
1. Build app
2. Run npm run serve:ssr 
3. Visit app with disabled javascript

### Code Reproduction URL

https://github.com/WDrzewiecki/ionic-ssr

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.0.5
   @angular-devkit/build-angular : 16.0.0
   @angular-devkit/schematics    : 16.0.0
   @angular/cli                  : 16.0.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.1
   @capacitor/android : not installed
   @capacitor/core    : 5.0.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (/usr/local/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Are you able to identify which part of `IonicServerModule` is causing the issue? It's possible that the module is triggering a bug in Angular. It's also possible that there is an incompatibility with Angular 16, but there's not enough information here to make that determine that.

**Comment by WDrzewiecki** [comment]
Just change in angular.json file in serve-ssr from  `"browserTarget": "app:build:development",` to  `"browserTarget": "app:build",` and from `"serverTarget": "app:server:development"` to  `"serverTarget": "app:server"` and after running `npm run dev:ssr` you should have this logs. It may not be the most elegant way, but it should work temporarily

**Comment by WDrzewiecki** [comment]
And some more logs from debugger: 
<img width="612" alt="Zrzut ekranu 2023-05-8 o 16 50 12" src="https://user-images.githubusercontent.com/12089427/236856354-5ceb1da5-947a-452a-bf0a-6eaa59e19121.png">

**Comment by sean-perkins** [comment]
Hello @WDrzewiecki can you try with this dev-build and let me know if you experience any issues?

```
npm install @ionic/angular@7.0.6-dev.11683653232.1ddc5840 @ionic/angular-server@7.0.6-dev.11683653232.1ddc5840
```

The problematic UI was `<ion-content [fullscreen]="true">`. Our fullscreen implementation reads the element dimensions and force updates the element. This causes an issue in a SSR environment. The dev-build includes a change that only does this behavior in a browser environment.

**Comment by WDrzewiecki** [comment]
Everything seems to be working fine now, thank you so much for your assistance
