### ISSUE TITLE
feat: add option to control rotation amount of ion-accordion icon

### ISSUE THREAD

**Issue by ptmkenny** [ionic-team/ionic-framework#27410]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently, you can customize ion-accordion's icon by specifying `toggleIcon`, but the icon rotation is fixed at 180 degrees.  It would be great to be able to choose 180 or 90 degrees for the icon rotation.

### Describe the Use Case

The [HTML details element](https://web.dev/learn/html/details/) on most browsers uses an arrow facing right by default, and when you click it, it rotates to point downward.  This is a 90-degree rotation.  It would be great if there was an easy way to get the same behavior in ionic.

### Related Code

Something like this in ionic react:

```
      <IonAccordion
        toggleIcon={play}
        iconRotation="90" // Valid values: 180 || 90.
      >
```

**Comment by liamdebeasi** [comment]
Thanks for the report. I think this would be a good fit for https://github.com/ionic-team/ionic-framework/issues/23548, so I am going to merge the two threads. #23548 describes a feature that lets developers control the rotation.
