### ISSUE TITLE
bug: datetime year wheel is ordered backwards

### ISSUE THREAD

**Issue by craigstanton** [ionic-team/ionic-framework#27422]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

ion-datetime has wheel selectors for days, months and years. Days and months are in ascending order (smallest at the top), but years are in descending order

### Expected Behavior

All wheels should be in the same order so scrolling them in one direction consistently moves forward or backwards in time.

### Steps to Reproduce

<ion-datetime preferWheel="true" presentation="date"></ion-datetime> 

### Ionic Info

onic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.5.6
   @angular-devkit/build-angular : 14.2.10
   @angular-devkit/schematics    : 13.3.1
   @angular/cli                  : 14.2.10
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI   : 4.7.3
   @capacitor/core : 4.7.3

Utility:

   cordova-res (update available: 0.15.4) : 0.15.1
   native-run                             : 1.7.2

System:

   NodeJS : v18.14.1 (/Users/stantonca/.nvm/versions/node/v18.14.1/bin/node)
   npm    : 9.3.1
   OS     : macOS

**Comment by amandaejohnston** [comment]
Thank you for the issue. I double-checked this using the Reminders app on iOS, and confirmed that the year wheel should indeed go the same way as the other wheels. This applies to both `preferWheel="true" presentation="date"`, and the month/year picker in a grid datetime.

**Comment by mapsandapps** [comment]
Thanks for the issue! This has been resolved via #27551 and will be available in an upcoming release of Ionic.
