### ISSUE TITLE
bug: Encourage the library authors to publish an Ivy distribution.

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-framework#27437]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

> ng run app:build:production
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
(node:67096) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
- @ionic-native/core [module/esm5] (https://github.com/ionic-team/ionic-native.git)
- @ionic-native/call-number [module/esm5] (https://github.com/ionic-team/ionic-native.git)
- @ionic-native/social-sharing [module/esm5] (https://github.com/ionic-team/ionic-native.git)
- @ionic-native/screen-orientation [module/esm5] (https://github.com/ionic-team/ionic-native.git)
- @ionic-native/app-availability [module/esm5] (https://github.com/ionic-team/ionic-native.git)
- @ionic-native/in-app-browser [module/esm5] (https://github.com/ionic-team/ionic-native.git)
Encourage the library authors to publish an Ivy distribution.

### Expected Behavior

We do not need such warnings.

### Steps to Reproduce

ionic build --prod 

### Ionic Info

Ionic:

Ionic CLI : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 7.0.4
@angular-devkit/build-angular : 15.2.7
@angular-devkit/schematics : 15.2.7
@angular/cli : 15.2.7
@ionic/angular-toolkit : 8.0.0

Capacitor:

Capacitor CLI : 4.8.0
@capacitor/android : 4.8.0
@capacitor/core : 4.8.0
@capacitor/ios : 4.8.0

Utility:

cordova-res (update available: 0.15.4) : 0.15.3
native-run (update available: 1.7.2) : 1.7.1

System:

NodeJS : v18.16.0 (/usr/local/bin/node)
npm : 9.5.1
OS : macOS Unknown

### Additional Information

{
"name": "ME",
"version": "1.6.1",
"author": ME",
"homepage": "ME",
"scripts": {
"ng": "ng",
"start": "ng serve",
"build": "ng build --prod",
"lint": "ng lint"
},
"private": true,
"dependencies": {
"@angular/animations": "15.2.8",
"@angular/cdk": "15.2.8",
"@angular/common": "15.2.8",
"@angular/core": "15.2.8",
"@angular/fire": "7.5.0",
"@angular/forms": "15.2.8",
"@angular/google-maps": "15.2.8",
"@angular/platform-browser": "15.2.8",
"@angular/platform-browser-dynamic": "15.2.8",
"@angular/router": "15.2.8",
"@capacitor-community/fcm": "3.0.2",
"@capacitor-community/photoviewer": "2.0.5",
"@capacitor/android": "4.8.0",
"@capacitor/app": "4.0.1",
"@capacitor/browser": "4.0.0",
"@capacitor/camera": "4.0.0",
"@capacitor/core": "4.8.0",
"@capacitor/device": "4.1.0",
"@capacitor/geolocation": "4.0.0",
"@capacitor/haptics": "4.0.1",
"@capacitor/ios": "4.8.0",
"@capacitor/keyboard": "4.0.0",
"@capacitor/preferences": "4.0.1",
"@capacitor/push-notifications": "4.0.0",
"@capacitor/splash-screen": "4.0.0",
"@capacitor/status-bar": "4.0.0",
"@ionic-native/app-availability": "5.36.0",
"@ionic-native/call-number": "5.36.0",
"@ionic-native/core": "5.36.0",
"@ionic-native/in-app-browser": "5.36.0",
"@ionic-native/screen-orientation": "5.36.0",
"@ionic-native/social-sharing": "5.36.0",
"@ionic/angular": "7.0.4",
"@ionic/pwa-elements": "3.1.1",
"@lithiumjs/angular": "^7.2.2",
"@lithiumjs/ngx-virtual-scroll": "^0.2.3",
"@types/lodash": "4.14.172",
"call-number": "1.0.1",
"cordova-plugin-appavailability": "0.4.2",
"cordova-plugin-inappbrowser": "5.0.0",
"cordova-plugin-screen-orientation": "3.0.2",
"cordova-plugin-x-socialsharing": "6.0.4",
"es6-promise-plugin": "4.2.2",
"firebase": "9.8.2",
"lodash": "4.17.21",
"ng-cloudimage-responsive": "4.0.0",
"ngx-image-cropper": "6.2.2",
"primeicons": "5.0.0",
"primeng": "15.4.1",
"rxjs": "7.5.0",
"swiper": "^9.2.4",
"tslib": "2.2.0",
"zone.js": "0.11.4"
},
"devDependencies": {
"@angular-devkit/build-angular": "15.2.7",
"@angular-eslint/builder": "15.2.1",
"@angular-eslint/eslint-plugin": "15.2.1",
"@angular-eslint/eslint-plugin-template": "15.2.1",
"@angular-eslint/template-parser": "15.2.1",
"@angular/cli": "15.2.7",
"@angular/compiler": "15.2.8",
"@angular/compiler-cli": "15.2.8",
"@angular/language-service": "15.2.8",
"@capacitor/cli": "4.8.0",
"@ionic/angular-toolkit": "8.0.0",
"@types/node": "12.11.1",
"@typescript-eslint/eslint-plugin": "5.48.2",
"@typescript-eslint/parser": "5.48.2",
"eslint": "8.33.0",
"eslint-plugin-import": "2.22.1",
"eslint-plugin-jsdoc": "30.7.6",
"eslint-plugin-prefer-arrow": "1.2.2",
"jeep-photoviewer": "1.1.4",
"prettier": "2.3.2",
"ts-node": "8.3.0",
"typescript": "4.9.5"
},
"description": "ME"
}

**Comment by liamdebeasi** [comment]
Thanks for the report. As noted in https://ionic.io/blog/a-new-chapter-for-ionic-native, the Ionic Native plugins have become Awesome Cordova Plugins and the old Ionic Native packages are no longer maintained. We recommend migrating to Awesome Cordova Plugins so you can continue to use the plugins with Ionic 7. I am going to close this, but let me know if you have any questions.
