### ISSUE TITLE
bug: `ion-tabs` does not support "preserve" QueryParamsHandling

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-framework#27453]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When switching between tabs, all query parameters are being removed

### Expected Behavior

There should be a way to allow query parameter preservation (in angular, `queryParamsHandling="preserve"`)

### Steps to Reproduce

1. Go to [`/home?lang=de`](https://angular-68pwvy-bsrku7.stackblitz.io/home?lang=de)
2. Click on "Radio" (redirects to `/radio`, not `/radio?lang=de`)

### Code Reproduction URL

https://stackblitz.com/edit/angular-68pwvy-bsrku7?file=src/app/home/home-page.component.html

### Ionic Info

Ionic:

Ionic CLI : 7.1.1

Utility:

cordova-res : 0.15.4
native-run : 1.7.2

System:

NodeJS : v18.15.0
npm : 9.5.0
OS : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks! I am going to merge this with https://github.com/ionic-team/ionic-framework/issues/25470. The original report was about Ionic React, but it looks like none of our router integrations currently support query params on tabs. When we fix this, we should probably fix this for all integrations.
