### ISSUE TITLE
bug: lifecycle events not working when using pages outside tabs router

### ISSUE THREAD

**Issue by daniel-zero** [ionic-team/ionic-framework#27474]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When navigating to a page outside the router (page is in full screen mode not showing the tab navigation), the ionic lifecycle events are not firing. Only when navigating to a tab child page, the events are firing as they should.

### Expected Behavior

It should be possible to use the lifecycle events also when the page the user navigates is not a child route of the current tab

### Steps to Reproduce

1. create a bare ionic tab application
2. create a route and define it in the app.routes.ts file and not as a child page of any route
3. navigate to the child page and log the lifecycle events

### Ionic Info

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.16.0
   npm    : 9.6.5
   OS     : macOS Unknown

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
