### ISSUE TITLE
bug: React navigation animation

### ISSUE THREAD

**Issue by FernetB** [ionic-team/ionic-framework#27482]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Currently in ioni 7 and before, there are 3 cases of wrong animation transition between pages

Case 1: if you go from `tabs` to a page outside tabs and then comeback with `push("/tabs/tab1", "back", "pop")` from `useIonRouter` the `back` animation seems broken in both android and ios

Case 2: if you go from `tabs` to a page that is outside tabs and in an outlet by itself then both the in and out animation are broken also on android and ios

Case 3: if you go from 1 page to another in the same outlet, and that page has a background in the `IonPage` component, then on ios the animation transition is broken

### Expected Behavior

Animation behave like normal

### Steps to Reproduce

1. Create a tabs page
2. Create an outside page that is alone and in an outlet
3. navigte from tabs to the outside page and then go back with a  `push("/tabs/tab1", "back", "pop")`

### Code Reproduction URL

https://github.com/FernetB/ionic-tabs-bug

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.1
   Ionic Framework : @ionic/react 7.0.6

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : not installed
   @capacitor/core    : 5.0.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 
   npm    : 9.5.1
   OS     : Linux 5.15

### Additional Information

Surprisingly `history.goBack()` animation works fine (not exactly nice but is not buggy)

_No response_

**Comment by liamdebeasi** [comment]
Thanks for the report. The problem here is the "Outside" view is not being rendered inside of an `ion-router-outlet`. Both the entering and leaving views must be rendered inside of `ion-router-outlet` elements for transitions to work (They can be different `ion-router-outlet` instances though).

**Comment by FernetB** [comment]
Sorry my bad!

I pushed with the changes, the issue is still there.

In my project was with `IonRouterOutlet` but in this example repo I forgot to add it because of the tabs template

**Comment by FernetB** [comment]
Here is the video

In the "Go outside tabs" you can see wrong `forward` animation (the first page dissaperas on the animation), the `back` animation seems fine
In the "Go outside outlet tabs" you can see wrong `forward` animation and the `back` animation shows the first page leaving while the first page is entering

https://github.com/ionic-team/ionic-framework/assets/47339424/eab60f60-179a-4182-8cde-9a09ae1b335d

**Comment by FernetB** [comment]
And what about the back animation? (The second case when on going back shows de tabs pages leaving and entering at the same time)

**Comment by liamdebeasi** [comment]
This back animation behavior is likely happening because you are rendering another nested `ion-router-outlet` when you should not be:

![image](https://github.com/ionic-team/ionic-framework/assets/2721089/256edefe-e9eb-447c-8346-e161f0455c52)

The highlighted `ion-router-outlet` that is a child of the parent `ion-router-outlet` should not be there. Instead, you can just render your page component in that route.

**Comment by FernetB** [comment]
But there are cases in wich we want to navigate to an outlet and with that we have bad animations
Is there gonna be a fix for that?

**Comment by liamdebeasi** [comment]
In the example provided you should not be using nested outlets. Nested outlets should only be used when you want to render content in multiple outlets at the same time (such as a tab bar and tab content): https://ionicframework.com/docs/react/navigation#shared-urls-versus-nested-routes

Animations in nested outlets make assumptions about how the nested outlets are being used which can lead to visual glitches when the nested outlets are not used correctly.

**Comment by FernetB** [comment]
Yeah, i know is not the right way of using it, but we used that way because we want to unmount all the pages that are in an specifict outlet for performance and simplicity reasons

I guess we have to live with that until we find a workaround
