### ISSUE TITLE
feat: life cycle hooks to handle interrupted opening or closing page process

### ISSUE THREAD

**Issue by a1leks** [ionic-team/ionic-framework#27486]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I propose to add new life cycle methods to handle moments:

- opening page process is aborted, after ionViewWillEnter but ionViewDidEnter won't be reached. 
- closing page process is aborted, after ionViewWillLeave but ionViewDidLeave won't be reached.

It happens if I start swipe gesture but then abort it and stay on the initial page. 
It can be `ionViewWillEnterAborted`/`ionViewWillLeaveAborted` for example.

### Describe the Use Case

It will be useful for unsubscribe anything, free any resources. The idea is these hooks will usually contain the reverse logic for  ionViewWillEnter/ionViewWillLeave.

In my own case I need to disable 'android hardware back button' and 'swipe back gesture' in ionViewWillEnter but enable it back in case of navigation was prevented (user has aborted his swipe). It will be grate to manage it in one page.

 

### Describe Preferred Solution

https://github.com/ionic-team/ionic-framework/blob/13d2d115d44f109c3ea2a47bcb518c6090126325/angular/src/providers/angular-delegate.ts#L166

```
const LIFECYCLES = [
    LIFECYCLE_WILL_ENTER_ABORTED,
    LIFECYCLE_WILL_LEAVE_ABORTED,
    LIFECYCLE_WILL_ENTER,
    LIFECYCLE_DID_ENTER,
    LIFECYCLE_WILL_LEAVE,
    LIFECYCLE_DID_LEAVE,
    LIFECYCLE_WILL_UNLOAD,
];
```

https://github.com/ionic-team/ionic-framework/blob/13d2d115d44f109c3ea2a47bcb518c6090126325/core/src/utils/transition/index.ts#L102

```
const animation = async (animationBuilder: AnimationBuilder, opts: TransitionOptions): Promise<TransitionResult> => {
  // ...
  if (!didComplete) {
    lifecycle(opts.leavingEl, 'ionViewWillLeaveAborted');
    lifecycle(opts.enteringEl, 'ionViewWillEnterAborted');
  }
 // ...
```

**Comment by liamdebeasi** [comment]
Thanks for the report. I'm not sure I understand the root issue that these new lifecycle hooks would resolve. If you want to clean up any listeners, you should do them in `ionViewDidLeave`. This only fires when a swipe gesture has been completed, so you won't accidentally clean up listeners if the gesture is aborted.

**Comment by liamdebeasi** [comment]
For example 1 you can use `ionViewDidEnter` to create subscriptions on Page 1. The main focus should be on only creating/destroying subscriptions once navigation has been confirmed as there are numerous ways navigation can be cancelled (aborting a swipe gesture, router guard, etc). `ionViewDidEnter` and `ionViewDidLeave` are fired once navigation has been confirmed.

For example 2 you should be using a router guard instead. Pressing the hardware back button is only 1 way that users can navigate back a previous page. Router guards exist to prevent users from leaving a particular page. [canActivate](https://angular.io/api/router/CanActivateFn) may be useful here.

**Comment by a1leks** [comment]
Thank you! I see I can solve my issues like you described and It's a good solution. I still think these additional hooks can give more control during navigation and can be useful, but now I haven't more cases. I just leave it open for some time. Mb somebody else will see it and would like to comment.

**Comment by liamdebeasi** [comment]
Thanks for the reply. Glad to hear my previous suggestions helped. The original issue has been resolved, so I am going to close the thread. However, if anyone else has new use cases for the additional lifecycle hooks, please feel free to open a new issue. Thanks!
