### ISSUE TITLE
feat(accordion): disable collapse

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#27489]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I'm looking for a way to disable the full collapse of a accordion group. That means in simple words: There should be always one expanded accordion.

### Describe the Use Case

We use accordions in a side menu and our UI assumes that the accordions are never full collapsed.

### Describe Preferred Solution

Maybe an extra property on the `accordion-group` component that enabkles this behaviour

### Describe Alternatives

I also looked into a custom solution in our app, but for example adding a click handler on the accordion and "stopping" the event does not cancel the accordion change event

**Comment by liamdebeasi** [comment]
Thanks for the report. Have you tried using the [readonly property](https://ionicframework.com/docs/api/accordion-group#readonly)? This lets you prevent accordions from being interacted with. There also exists a `readonly` property on each accordion instance.

That being said, I don't recommend this pattern. The purpose of accordions is to be collapsible, so selectively preventing collapse will likely be confusing to users.
