### ISSUE TITLE
bug: slotted labels in radio, checkbox, and toggle are missing margin

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic-framework#27498]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using the modern syntax for inputs (e.g. `ion-radio`, `ion-checkbox`) the nice spacing inside an `ion-item` is not added anymore (as compared to the "legacy" syntax). This is an issue especially with long labels (`ion-text-wrap`).

| ios | md |
|--------|--------|
| <img width="190" alt="ion-item-spacing" src="https://github.com/ionic-team/ionic-framework/assets/7592254/9cbe81f2-39be-4f6c-8b61-6c5988e8a41c"> | <img width="200" alt="ion-item-spacing-md" src="https://github.com/ionic-team/ionic-framework/assets/7592254/2333d9f7-d893-418b-bca9-4d898e3aba99"> |

### Expected Behavior

I'd expect it to look the same as in previous versions of Ionic.

### Steps to Reproduce

1. Run reproduction
2. Check differences in `ion-item` spacing in legacy and modern syntax

### Code Reproduction URL

https://github.com/DavidStrausz/modern-input

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\dstrauss\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.7
   @angular-devkit/build-angular : 15.2.8
   @angular-devkit/schematics    : 15.2.8
   @angular/cli                  : 15.2.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : not installed
   @capacitor/core    : 5.0.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.12.1 (C:\Program Files\nodejs\node.exe)
   npm    : 9.4.1
   OS     : Windows 10
```

### Additional Information

I'm using `@ionic/angular`

**Comment by liamdebeasi** [comment]
Did you push your changes? I only see the default list starter app code.

**Comment by DavidStrausz** [comment]
@liamdebeasi Ah you're right, sorry about that - it should be available now :)

**Comment by liamdebeasi** [comment]
Thanks! it looks like we are missing margins that the `ion-item` used to apply: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/item/item.md.scss#L298-L301 and https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/item/item.ios.scss#L203-L206

**Comment by amandaejohnston** [comment]
This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27788 and the fix will be available in a future release of Ionic. Thank you!
