### ISSUE TITLE
bug: Why no found ion-slides？

### ISSUE THREAD

**Issue by yushengzhen** [ionic-team/ionic-framework#27497]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Why no found ion-slides？

### Expected Behavior

Why no found ion-slides？

### Steps to Reproduce

Why no found ion-slides？

### Ionic Info

Why no found ion-slides？

### Additional Information

Why no found ion-slides？

**Comment by liamdebeasi** [comment]
Please see the migration guide for Ionic 7 which notes that `ion-slides` has been replaced in favor of using Swiper.js directly: https://ionicframework.com/docs/updating/7-0#slides
