### ISSUE TITLE
bug: when list is inside ngForm, I cannot swap item in the list (display incorrectly)

### ISSUE THREAD

**Issue by Wasenshi123** [ionic-team/ionic-framework#27494]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Why my code works previously, but not anymore : I want to know what cause this behavior change (I'm aware that it might be angular related, but just to be sure)

I have a list of items that I map data to, using ngModel with ion-input. Previously I can have swap functionality with them.
But now when I swap, the items seem to update incorrectly.

From my investigation, this happens when I wrapped my elements inside ngForm. In my example code, if you leave out the <form #form="ngForm"> element, the bug's gone.

but this code works fine before. And I want validation functionality from it (user cannot hit save/submit button if some required field is missing value), so I don't want to delete the ngForm part.

### Expected Behavior

I should be able to swap my array item without any bug like before.

### Steps to Reproduce

1. create a list with ionic elements (ion-item, ion-input etc), bind and show data with ngModel
2. create swap functionality to swap the data in the data list (so that elements will be swapped also)
3. wrap them inside ngForm tag
4. the list update UI incorrectly when swap

### Code Reproduction URL

https://github.com/Wasenshi123/Ionic7/tree/list-swap-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\User\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.6
   @angular-devkit/build-angular : 15.2.8
   @angular-devkit/schematics    : 15.2.8
   @angular/cli                  : 15.2.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.7.3
   @capacitor/core    : 4.7.3
   @capacitor/ios     : 4.7.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
I'm not seeing this working on Ionic 6 either (I tested v6.7.4). The issue also persists even if I remove all Ionic components from the modal. Are you able to identify the part of Ionic that you think is causing this issue?

**Comment by Wasenshi123** [comment]
Then perhaps it may be affected by the changes from angular's recent version. (since I have just updated angular from 12 straight to 15 to use ionic 7)

**Comment by Wasenshi123** [comment]
Wait, I have replaced ion-input with pure <input> and the bug is gone also

**Comment by Wasenshi123** [comment]
ion-input & name attribute -> bug
ion-input & no name attribute (only ngModel) -> bug and trickery at first (no value shown), but after fill some new values, swapping fine
ion-input & no name attribute & [value] mapping -> trickery at first, but after that, swapping fine

input & name attribute -> bug
input & no name attribute (only ngModel) -> bug and trickery at first (no value shown), but after fill some new values, swapping fine
input & no name attribute && [value] mapping -> trickery at first, but after that, swapping fine

**Comment by liamdebeasi** [comment]
If the issue reproduces with just an `<input />` element, then I recommend reporting this to the Angular team with a code reproduction. Note that they will likely ask you for a code reproduction that does not include Ionic.

I'm not able to identify anything in Ionic that could be causing this change, so I am going to close this for now. If you are able to identify something in Ionic that could cause this change, let me know and I can re-open the issue.
