### ISSUE TITLE
 Incorrect Unit Test Results for AM/PM Indications

### ISSUE THREAD

**Issue by jon-pruessmeier** [ionic-team/ionic-framework#27516]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The unit tests for AM/PM indications are failing due to the use of regular spaces instead of slim spaces (U+202F). The assertions in the unit tests compare the expected values, which contain regular spaces, with the received values that include slim spaces. This mismatch leads to assertion failures and inaccurate test results.

### Expected Behavior

The unit tests for AM/PM indications should use slim spaces (U+202F) for proper formatting. The expected values in the unit tests should be updated to include slim spaces instead of regular spaces. This will ensure accurate and consistent test results.

### Steps to Reproduce

1. Run the unit tests for AM/PM indications using the command npm run test.spec.

### Ionic Info

Happens in the Ionic Directory itself

### Additional Information

It is important to use slim spaces (U+202F) for AM/PM indications to ensure proper localization and formatting of time values. The use of regular spaces in the unit tests leads to inconsistencies and test failures. Please update the unit tests to reflect the correct usage of slim spaces for AM/PM indications.

**Comment by liamdebeasi** [comment]
Hey there,

I replied to your PR in https://github.com/ionic-team/ionic-framework/pull/27517#issuecomment-1557166488, but I'm not able to reproduce the original issue. Could you provide some clarification around the errors you are receiving and the environment you are testing this on?

**Comment by liamdebeasi** [comment]
Thanks! I am able to reproduce this on Node 19 but not on earlier versions. Let me do some digging and see if I can identify what is causing this.

**Comment by liamdebeasi** [comment]
@jon-pruessmeier So it looks like this was a bug in the v8 engine that has since been fixed: https://bugs.chromium.org/p/v8/issues/detail?id=13494

I tried Node 19.9 and the error does not reproduce there, so I believe this has been fixed. Can you give Node 19.9 a try too?

**Comment by jon-pruessmeier** [comment]
Hey @liamdebeasi 

I have just tested this with Node versions 19.9 and 20.2. The tests ran smoothly without any issues in both Node versions. Therefore, it seems to be a problem specific to the V8 or Node version. I think we can then close this issue and the respective PR.

Thank you very much for your efforts and research!
