### ISSUE TITLE
Ionic 7 Navigation is overlapping previous page. 

### ISSUE THREAD

**Issue by ravimittal16** [ionic-team/ionic-framework#27518]
**Ionic version:**
[ ] **7.x**

**I'm submitting a ...** 

[ ] bug report

**Current behavior:**
Route navigation transition is not smooth and it's overlapping the login page during navigation.

**Expected behavior:**
Navigation should be smooth

**Steps to reproduce:**

**Related code:**

```
 logout(): Promise<boolean> {
    console.log('Logging out user');
    return new Promise(async (resolve) => {
      if (this.isAuthticated) {
        const _resp = await this._storageService.clearAll();
        this._navigationService.navigateToLogin();
        resolve(true);
      }
    });
  }

 navigateToLogin() {
    this._router.navigate(['/login'], { replaceUrl: true });
  }
}
```

**Other information:**

[Demo](https://drive.google.com/file/d/1-HC_MIdF9TeBwlqq3LnsiwQnby_ne9sY/view?usp=sharing)

**Comment by FernetB** [comment]
That happened to me when i was not using the `ÌonContent` component in the login page, could u show both the first and second page html code?

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
