### ISSUE TITLE
bug: Stack Modal cause render issue on Android devices

### ISSUE THREAD

**Issue by loicparent** [ionic-team/ionic-framework#27528]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When I'm closing the modal, there are some flashes with dark colors and the content looks a bit buggy.

Your can see the render [here](https://github.com/ionic-team/ionic-framework/assets/11327909/2b711fdc-437a-496a-8f51-2af7d74cd2fc).

### Expected Behavior

The modal close smoothly without any flashes or strange behavior.

### Steps to Reproduce

1. Init a new Ionic project (Angular + Capacitor).
2. Create a stack modal using a page component and the IOS mode (see below).
4. launch the command ionic capacitor run android in the terminal.
5. Open the modal.
6. Swipe down to close the modal or close the modal to see the buggy render.

Code to create the modal:
```.ts
const modal = await this.modalCtrl.create({
  component: ModalPage,
  mode: 'ios',
  presentingElement: document.getElementById('ion-router-outlet'),
});
````

### Ionic Info

Ionic:

Ionic CLI : 7.1.1 (/Users/username/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 7.0.4
@angular-devkit/build-angular : 15.2.7
@angular-devkit/schematics : 15.2.7
@angular/cli : 15.2.7
@ionic/angular-toolkit : 9.0.0

Capacitor:

Capacitor CLI : 5.0.3
@capacitor/android : 5.0.3
@capacitor/core : 5.0.3
@capacitor/ios : 5.0.3

Cordova:

Cordova CLI : not installed
Cordova Platforms : not available
Cordova Plugins : not available

Utility:

cordova-res : 0.15.4
native-run : 1.7.2

System:

ios-sim : 8.0.2
NodeJS : v16.15.0 (/Users/username/.nvm/versions/node/v16.15.0/bin/node)
npm : 8.19.2
OS : macOS Unknown
Xcode : Xcode 14.3 Build version 14E222b

### Additional Information

Thanks for your help :)
_Loïc_

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
