### ISSUE TITLE
bug: when exists multiple ion-item-sliding only works the first loaded

### ISSUE THREAD

**Issue by samuelrebuelta** [ionic-team/ionic-framework#27521]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When an app uses multiple ion-item-sliding components on different pages/modals, only works the first one.
For example, if I have page A and page B both with ion-item-sliding, only works on first page you visit.

### Expected Behavior

All ion-item-sliding components should works. I think I remember that before the migration to v7 it worked fine.

### Steps to Reproduce

1. Create an example app with 2 pages and add ion-item-sliding on both pages.
2. Load the page A and slide (it works)
3. Navigate to page B and slide (it does not work)

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1
   Ionic Framework               : @ionic/angular 7.0.7
   @angular-devkit/build-angular : 15.2.8
   @angular-devkit/schematics    : 15.2.0
   @angular/cli                  : 15.2.0
   @ionic/angular-toolkit        : 8.1.0

Capacitor:

   Capacitor CLI      : 5.0.1
   @capacitor/android : 5.0.1
   @capacitor/core    : 5.0.1
   @capacitor/ios     : 5.0.1

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.13.1
   npm    : 8.1.2
   OS     : macOS Unknown
   Xcode  : Xcode 14.3 Build version 14E222b

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
