### ISSUE TITLE
bug:  Ionic 7 React - Modals cannot consume context data

### ISSUE THREAD

**Issue by playaz87** [ionic-team/ionic-framework#27546]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Modals are unable to  consume data using React's context provider. All values provided by context are `undefined`.

### Expected Behavior

Receive provided context data in modals

### Steps to Reproduce

1. Create React context
2. Open modal
3. Consume context

### Code Reproduction URL

https://github.com/playaz87/ionic-7-modal-context

### Ionic Info

Ionic:

   Ionic CLI       : 5.4.16 
   Ionic Framework : @ionic/react 7.0.8

System:

   NodeJS : v20.0.0
   npm    : 8.1.0
   OS     : Linux 5.15

**Comment by liamdebeasi** [comment]
Thanks for the report. The problem here is you are adding `MyProvider` to everything inside of `IonRouterOutlet`. However, `IonModal` is mounted as a child of `IonApp` outside of `IonRouterOutlet`. As a result, `IonModal` cannot access your context. To fix this, you need to add `MyProvider` to `IonApp` as well:

```tsx
<MyProvider>
    <IonApp>
        <IonReactRouter>
            <IonRouterOutlet>
              <Route exact path="/home">
                  <Home/>
              </Route>
              <Route exact path="/">
                  <Redirect to="/home"/>
              </Route>
            </IonRouterOutlet>
        </IonReactRouter>
    </IonApp>
</MyProvider>
```

**Comment by playaz87** [comment]
@liamdebeasi Thanks for your reply.

I wanted to use a Context Provider to create a global modal.

If `IonModal` has to be a child of `IonRouterOutlet` to access context, and direct children of `IonRouterOutlet` should only be `Route` or `Redirect`, how can I mount a `Modal` inside of `IonRouterOutlet` and outside of a "page"?

**Comment by liamdebeasi** [comment]
Glad to hear the issue is resolved. Going to close, but let me know if you have questions.
