### ISSUE TITLE
bug: the ion-router does not work inside ShadowDom

### ISSUE THREAD

**Issue by vinyll** [ionic-team/ionic-framework#27552]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Using the Router inside a ShadowDom component does not trigger routes.

Moving that same route in a Light Dom reacts as expected.

### Expected Behavior

The Router should be able to work inside a ShadowDom as with the LightDom

### Steps to Reproduce

1. create an HTMLElement with shadowDom
3. insert the `<ion-router>` in that element
4. insert that HTMLElement in your index.html `<body>`
5. try to display the homepage from you web browser

### Ionic Info

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.1.0
   npm    : 9.6.4
   OS     : macOS Unknown

### Additional Information

I personnaly use [Lego](https://lego.js.org/) and I could work around after spending a few hours ending with the conclusion that IonRouter was incompatible with ShadowDom.

The issue is possibly due to the [`document.body` hardcoded here](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/router/utils/dom.ts#L83) or some hard dependency to the document.

One way to solve would be an attribute for the `ion-router` where we could reference the DOM; something like `<ion-router dom="this.shadowDom">` (where `this.shadowDom` is resolved on the VanillaJS side, by Lego in my usecase).

The following issue might be related: #26115

**Comment by vinyll** [comment]
Here's a working example: 
- ok with light DOM: https://polight.github.io/lego-mobile/?shadow=false
- issue with shadow DOM: https://polight.github.io/lego-mobile/?shadow=true

It's just an HTML page, so source code is straighforward from the browser.
The original copy is [here](https://github.com/Polight/lego-mobile/blob/main/index.html)

**Comment by liamdebeasi** [comment]
Thanks for the reproduction. Can you clarify why you need shadow DOM here?

**Comment by vinyll** [comment]
Just like Ionic itself bases some components on ShadowDOM, some frameworks are based on ShadowDOM also.
That's the case for [https://github.com/polight/lego] which I use for building my mobile app alongside with Ionic.
Some of the benefits are the CSS scoping.

It's been working all well with Ionic until using the `ion-router` component, probably because of hard-coding a `document.body` or so which is great for the sake of simplicity yet has it's limitation.

Thanks for your consideration about this 🐞!

**Comment by liamdebeasi** [comment]
Are you able to avoid using Shadow DOM for `my-router`? It is true that many of our components are designed to use Shadow DOM, but they weren't designed to be used _inside_ of another shadow root. Nesting shadow components can create issues with styling inheritance, so other components such as `ion-button` may not inherit public CSS variables correctly.

**Comment by vinyll** [comment]
Yes, [Ionic](ionicframework.com/) is well scoped and [Lego](lego.js.org/) permits to switch off the Shadow DOM so I'm OK.
Using Ionic with ShadowDOM has been running smooth all over so far until the router.
Because I spent quite a few hours understanding _why_ the router would not just route, I thought it could be useful either to clear off that limitation or to document it here or somewhere. Any thought?

**Comment by liamdebeasi** [comment]
The router needs to wait for the associated nav outlet to load. In order to do that it queries the DOM for an element such as `ion-nav` or `ion-router-outlet`. Since the nav outlet is in the Shadow DOM, the router cannot find the element. The router does not look inside of shadow roots because the contents of a shadow root is an implementation detail.
