### ISSUE TITLE
useIonViewWillEnter supporting a callback that will be invoked when exiting the view

### ISSUE THREAD

**Issue by raythree** [ionic-team/ionic-framework#27565]
### Feature Request

`useIonViewWillEnter` should have a user-defined cleanup function, just as `React.useEffect` does, but one that is paired with `useIonViewWillLeave`. Likewise, `useIonViewDidEnter` should have a user cleanup function paired with `useIonViewDidLeave`.  This is obvious when using React 18 with StrictMode in development mode, where React deliberately renders twice. For example, if using `React.useEffect` with a view that needs to periodically refresh:

```js
  React.useEffect(() => {
    query();
    const timer = setInterval(query, REFRESH_INTERVAL);
    return () => clearInterval(timer);
  }, []);
```
This works fine even with re-renders, and nicely uses function scope to hold the timer that needs to be canceled when unmounting. 

### Use Case

Need to set a refresh timer when a view enters, and clear it when the view exits. `React.useEffect` works fine if the component is mounted and unmounted, but if a view is entered and exited, we need a similar cleanup with `useIonViewWillEnter`.

### Preferred Solution

Add a third (optional) parameter to `useIonViewWillEnter`, that will get added to the internal context, and called when `useIonViewWillLeave` is invoked (similar idea for useIonViewDidEnter/useIonViewDidLeave). 

```js
export const useIonViewWillEnter = (callback: LifeCycleCallback, deps: any[] = [], cleanupFn: CleanupCallback = null)
```

### Describe Alternatives

Currently we are using a workaround like this:

```js
let timerHandle = null;

function MyComponent {
  useIonViewWillEnter(() => {
    query();
    if (!timerHandle) {
      // rendering again, don't start the timer again
      timerHandle = setInterval(query, REFRESH_TIME);
    }
  });

  useIonViewWillLeave(() => {
    clearInterval(timerHandle);
    timerHandle = null;
  });

  // rest... 
}
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please describe why `useIonViewWillLeave` does not work for this use case? `useIonViewWillLeave` was built as a way for doing any clean up work when a view is about to leave.

**Comment by raythree** [comment]
Closing the issue, as this works, it's just that the approach taken by `React.useEffect` seems cleaner, using in-scope variable for the cleanup, rather than defining externally, and accessing from two functions.
