### ISSUE TITLE
bug: JSX.IonDatetimeButton.datetimePresentation works but is not exposed in types

### ISSUE THREAD

**Issue by staff0rd** [ionic-team/ionic-framework#27588]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The [source of `datetime-button` reveals a `datetimePresentation` prop](https://github.com/ionic-team/ionic-framework/blob/d87e692c6c2c3d146514b093853d5e262137a9e5/core/src/components/datetime-button/datetime-button.tsx#L38), however this is [not exposed in the types](https://github.com/ionic-team/ionic-framework/blob/d87e692c6c2c3d146514b093853d5e262137a9e5/core/src/components.d.ts#L954-L971).

If you could indicate how I'd go about fixing this (or point me to stencil/ionic development build docs), I could open a PR with a fix rather than just report it.

Local workaround:

```ts
declare module "@ionic/core" {
  namespace JSX {
    interface IonDatetimeButton {
      datetimePresentation: JSX.IonDatetime["presentation"];
    }
  }
}
``` 

### Expected Behavior

I can write the following without type error:
```tsx
<IonDatetimeButton datetimePresentation="date"></IonDatetimeButton>
```

### Steps to Reproduce

Write the following:
```tsx
<IonDatetimeButton datetimePresentation="date"></IonDatetimeButton>
```

### Ionic Info

No project

**Comment by sean-perkins** [comment]
@staff0rd the `datetimePresentation` property is an internal state variable for `ion-datetime-button` (not intended to be exposed or configured by the developer). It is queried from the `ion-datetime` or defaults to `date-time`. 

```jsx
<IonDatetimeButton datetimePresentation="date"></IonDatetimeButton>
```

will not be expected/supported behavior. 

Instead associate the `ion-datetime` instance and set the property on that:
```jsx
<IonDatetimeButton datetime="datetime"></IonDatetimeButton>

<IonModal keepContentsMounted={true}>
  <IonDatetime id="datetime" presentation="date"></IonDatetime>
</IonModal>
```
