### ISSUE TITLE
bug: ios 17, popover disappears on subsequent presentations

### ISSUE THREAD

**Issue by MrMYHuang** [ionic-team/ionic-framework#27620]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

Using an IonButton to show an IonPopover multiple times, but only the first time works. In the following times, the IonPopover dismisses automatically without any user interaction.

### Expected Behavior

After the first time, the IonPopover shouldn't automatically dismiss without a user interaction.

### Steps to Reproduce

1. git clone https://github.com/MrMYHuang/IonPopoverBug
2. cd IonPopoverBug
3. npm i
4. ionic serve
5. open iOS 17 simulator
6. in iOS 17, open Safari
7. open http://localhost:8100/
8. click button ABC
9. dismiss the IonPopover
10. click button ABC again
11. The IonPopover automatically dismisses. Bug!

### Code Reproduction URL

https://github.com/MrMYHuang/IonPopoverBug

### Ionic Info

WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - /Users/myh/.nvm/versions/node/v20.0.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/myh/.nvm/versions/node/v20.0.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/myh/.nvm/versions/node/v20.0.0/lib/node_modules/@ionic/cli/index.js
       - /Users/myh/.nvm/versions/node/v20.0.0/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /Users/myh/.nvm/versions/node/v20.0.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/myh/.nvm/versions/node/v20.0.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/myh/.nvm/versions/node/v20.0.0/lib/node_modules/@ionic/cli/index.js
       - /Users/myh/.nvm/versions/node/v20.0.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.1.1 (/Users/myh/.nvm/versions/node/v20.0.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.10

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : not installed
   @capacitor/core    : 5.0.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v20.0.0 (/Users/myh/.nvm/versions/node/v20.0.0/bin/node)
   npm    : 9.6.4
   OS     : macOS Unknown

### Additional Information

By me test, the bug exists in Ionic framework v7 and v6 on iOS 17. The code to reveal the bug is setupIonicReact with mode 'md':
```
setupIonicReact(
  {
    mode: 'md'
  }
);
```

Additionally, IonModal has the same "works only once" problem on iOS 17, but can't be worked around by setupIonicReact mode to 'ios.'

Xcode 15 beta (with iOS 17 simulator): https://developer.apple.com/xcode/

**Comment by liamdebeasi** [comment]
Thanks for testing Ionic with iOS 17! I can reproduce this behavior, and it appears to be an iOS 17 bug. I reported this to Apple: https://bugs.webkit.org/show_bug.cgi?id=257861

I'll follow up here when the issue has been resolved on Apple's side.

**Comment by hank0923** [comment]
I've experienced this with using modals on iOS17 too

**Comment by leo-changliao** [comment]
Seem like it's animation issue, current work around is:
[animated]="false"

**Comment by rhoninhya** [comment]
This issue also occurs with ion-modal in ios 17

**Comment by liamdebeasi** [comment]
This bug was fixed by Apple, and the fix should be available in an upcoming iOS 17 beta. I'll follow up here when the fix is available.

**Comment by graphefruit** [comment]
I also got some user information, that having the popup with a textbox inside, and the keyboard slides up, that the view is hidden

**Comment by codybrom** [comment]
The issue has disappointed for me in iOS 17 Beta 5!

**Comment by r0hin** [comment]
> The issue has disappeared for me in iOS 17 Beta 5!

I concur. Seems to have been fixed.

**Comment by MrMYHuang** [comment]
Good news! The issues is fixed in iOS 17.0 (21A5303c) in Xcode 15 Beta 6.

**Comment by liamdebeasi** [comment]
Tested with iOS 17 beta 5 and I can confirm that this issue is resolved. I am going to close this. Thanks again for the report!
