### ISSUE TITLE
bug: routerLink on IonItem inside popover reloads whole page

### ISSUE THREAD

**Issue by blue-eyed-devil** [ionic-team/ionic-framework#27627]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have a popover item in the page header which is supposed to display user menu in a Popover.
This part is working fine.
But links inside the popover are reloading the whole page instead of rerendering.

### Expected Behavior

should have the same behavior as other components with `routerLink`

### Steps to Reproduce

1. create menu component:
```
  const UserMenu = () => (
    <IonContent>
      <IonItem routerLink="/my/favorites">Favorites</IonItem>
      <IonItem routerLink="/my/profile">Profile</IonItem>
      <IonItem routerLink="/my/account">Settings</IonItem>
      <IonItem button>Logout</IonItem>
    </IonContent>
  );
```
2. Initialize IonPopover
```
const [showUserMenu, dismiss] = useIonPopover(UserMenu, {
    onDismiss: (data: any, role: string) => dismiss(data, role),
  });
```
3. Create trigger button
```
<IonButton onClick={(e: any) => showUserMenu({
  event: e,
  showBackdrop: false,
})}>My Account</IonButton>
```

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.12

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : 5.0.0-nightly-20230428T150530.0
   @capacitor/core    : 5.0.4
   @capacitor/ios     : 5.0.0-nightly-20230428T150530.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.6.0 (/usr/local/bin/node)
   npm    : 9.6.5
   OS     : macOS Monterey

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
