### ISSUE TITLE
bug: LoadingController not removing overlay element if dismiss is called after create() but before present()

### ISSUE THREAD

**Issue by dexster** [ionic-team/ionic-framework#27638]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When dismiss() is called straight after a loader is created but not yet presented then the dynamically added overlay element is not removed from the HTML. 
```
this.loader = await this.loadingController.create();
this.loader.dismiss();
```

This is part of a larger issue I have with the async nature of the loader where showing or hiding may be called at anytime dependant on the state of my application. If loader.dismiss() is called immediately after loader.create() or loader.present() then the loader may not hide if these async methods return after dismiss().

### Expected Behavior

Element clean up should happen after create() and present() .

Also, there should possibly be checks in place to dismiss spinners appearing after dismiss() has been called. See my code in the example2.component.ts file below for how I currently handle this.

### Steps to Reproduce

Use reproduction URL below. Comment out example 1 or example 2 to view relevant console logs 

You may have to click the Stackblitz refresh a few times to see the issue due to the async nature. CPU throttling in dev tools may also help. 

### Example 1 - Spinner not dismissing

Observe console logs.

1. create() is called
2. dismiss() is called
3. create() returns
4. present() is called
5. spinner is displayed when it should be hidden 

![Example1](https://github.com/ionic-team/ionic-framework/assets/6392334/776a10eb-acb4-421e-9fe2-86b2b8b7e1b1)

### Example 2 - DOM not clearing

This screenshot below shows the element in DOM when dismiss() called after create().
![Example 2](https://github.com/ionic-team/ionic-framework/assets/6392334/76eedc4e-a22b-4beb-91c6-2ef4f342890f)

### Code Reproduction URL

https://stackblitz.com/edit/angular-hzdzno?file=src%2Fapp%2Fexample1%2Fexample1.component.ts

### Ionic Info

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.16.0
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by amandaejohnston** [comment]
Thank you for the issue. This looks to have the same root cause as https://github.com/ionic-team/ionic-framework/issues/27200, so I'm going to merge the two.
