### ISSUE TITLE
feat: Angular Universal non-destructive hydration support

### ISSUE THREAD

**Issue by WDrzewiecki** [ionic-team/ionic-framework#27653]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

In Angular 16 the developer preview of the non-destructive hydration was presented. https://angular.io/guide/hydration
It can greatly improve user experience and Google PageSpeed score by getting rid of the flickering when a page is loading. Also, this should resolve the problems mentioned in issue #21394.
However, in the current version of Ionic, this function throws errors and is not possible to use. 

Do you plan to make fixes to take full advantage of the non-destructive hydration?

### Describe the Use Case

Ionic angular server side rendering

**Comment by sean-perkins** [comment]
Hello @WDrzewiecki thanks for this feature request 👋 

The team needs to do some research on this feature before deciding if we can accept it or not. Server side solutions do not historically work with web components, which all Ionic components are built with.

**Comment by sean-perkins** [comment]
Hello 👋 after speaking with the Angular team, this is not a feature set that we can take advantage of currently with web components. The host nodes would be detected by hydration, but the inner content would not be processed. 

I'm going to close this issue as "not doing" for now, but if the state of web component support in server environments changes in the future, we will definitely reconsider. 

Thanks!
