### ISSUE TITLE
feat: Add role="log" or role="alert" to ion-toast when toast notifications appear

### ISSUE THREAD

**Issue by colabottles** [ionic-team/ionic-framework#27668]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Being able to add a `role="log"` (when notifications need to be read in order, _e.g., stacking toast notifications on each other_ or `role="alert"` to toast notifications that are being logged to make them more accessible.

### Describe the Use Case

This will ensure that when a toast is displayed on screen, its contents will be communicated correctly to assistive technologies, such as screen readers when using the correct `role` with the toast notification.

### Describe Preferred Solution

I know `role="status"` is et on the inner `.toast-content` element but since there is an option should the developer want the toasts to be logged, I think it would work better as an option.

* - Same with `aria-live="polite"` (another feature request later) if someone needed to use `aria-live="assertive"` (which clears the speech queue of previous updates. _"off"_ should be the default anyway).

### Related Code

```html
<ion-toast
  ...
  role="status | log | alert | off"
  ...
>
```

### Additional Information

[A toast to an accessible toast...](https://www.scottohara.me/blog/2019/07/08/a-toast-to-a11y-toasts.html)
[Defining ‘Toast’ Messages](https://adrianroselli.com/2020/01/defining-toast-messages.html)
[Designing Toast Messages for Accessibility](https://sheribyrnehaber.medium.com/designing-toast-messages-for-accessibility-fb610ac364be)

It is also acceptable to use `role="alert"` in a toast notification to stop the current reading and notify the user of an alert. Focus should not move there. It had a drawback in that it could make a user feel stranded because of the interruption and consequential stoppage of reading by the screen reader, however.

If the alert has interactive controls, then it should be a modal and not a toast notification. Toast notifications should never have interactive controls in them.

**Comment by colabottles** [comment]
Thanks, @liamdebeasi 

Snack bars, in my experience, have drawbacks that are far too many for them to be accessible to the minimum AA level of WCAG and generally have been poorly designed. So I am, as I build out an app with Ionic, trying to find a more accessible solution. 

Snack bars, for the most part can:

- Change state erratically
- Disappear too quickly 
- Can obscure other items and are hard to spot
- and can be inconsistent with where they are located

I would prefer to use an `ion-toast` at the top of the screen for consistency. If I am logging notifications (which my app may do) and if I have an `alert` (which it will), I would like to have those options to do so. 

Toasts and snack bars are very tricky when it comes to accessible experiences and getting them to conform to WCAG standards, but I’d like to have that option, if possible, to do so.

**Comment by liamdebeasi** [comment]
Thanks for the additional information. My main concern about this feature request is it goes against how toasts are supposed to be used. I've seen toasts frequently used for time-sensitive or important notifications which lead to many of the issues you described in https://github.com/ionic-team/ionic-framework/issues/27668#issuecomment-1598909052. We can add the ability to use `role="alert"` on `ion-toast`, but that does not resolve the other issues that you noted. 

Have you considered implementing a [banner](https://m2.material.io/components/banners#usage) instead? That UI component has a higher priority and avoids many of the issues you noted. Here's a code snippet of how it could work: https://codepen.io/liamdebeasi/pen/MWzexaN

A few benefits of banners:

1. They are persistent.
2. They appear inline with the content, so they do not obscure anything.
3. They can appear in a consistent location (like at the top of the screen).

**Comment by colabottles** [comment]
> Have you considered implementing a [banner](https://m2.material.io/components/banners#usage) instead? That UI component has a higher priority and avoids many of the issues you noted. Here's a code snippet of how it could work: https://codepen.io/liamdebeasi/pen/MWzexaN
> 
> A few benefits of banners:
> 
>     1. They are persistent.
> 
>     2. They appear inline with the content, so they do not obscure anything.
> 
>     3. They can appear in a consistent location (like at the top of the screen).
> 
> 
> edit: Here's the Material Design banner: https://m2.material.io/components/banners

Thanks, @liamdebeasi for those resources. It does look like `banner` is the way to go in my case. I took a look this morning and it is the solution that works for me.

Toasts can be very tricky so it is more than likely going to take a lot of work if those roles were implemented, I do know that much. Much appreciated, talking this through.

**Comment by liamdebeasi** [comment]
Glad to hear that works for your app. I'm going to re-open this because I think it would be good to have this component built-in to Ionic. We have `ion-toast` which is low priority and `ion-alert` which is high priority and disruptive, but we don't have anything for medium priority.

**Comment by colabottles** [comment]
@liamdebeasi Great, thanks. If there is any way I can help with this I'd be more than happy to contribute.
