### ISSUE TITLE
bug: When the page returns from ion-nav-link, a transparent mask appears

### ISSUE THREAD

**Issue by fatcarter** [ionic-team/ionic-framework#27674]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I want to customize the over-animation of ion-nav-link.

```html
<ion-nav-link router-direction="forward" :component="PageTwo" :router-animation="getRouterAnimation">
  <ion-button>Go to Page Two</ion-button>
</ion-nav-link>
```
```typescript
const getRouterAnimation = (baseEl: any, opts: any) => {
  console.log("opts", opts);
  const rootTransition = createAnimation()
      .addElement(baseEl)
      .duration(opts.duration || 333);

  const enterTransition = createAnimation().addElement(opts.enteringEl);
  const exitTransition = createAnimation().addElement(opts.leavingEl);

  enterTransition.fromTo('opacity', '0', '1');
  exitTransition.fromTo('opacity', '1', '0');

  if (opts.direction === 'forward') {
    enterTransition.fromTo('transform', 'translateX(-1.5%)', 'translateX(0%)');
    exitTransition.fromTo('transform', 'translateX(0%)', 'translateX(1.5%)');
  } else {
    enterTransition.fromTo('transform', 'translateX(1.5%)', 'translateX(0%)');
    exitTransition.fromTo('transform', 'translateX(0%)', 'translateX(-1.5%)');
  }
  rootTransition.addAnimation([enterTransition, exitTransition]);
  return rootTransition;
};
```
<img width="541" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/96217218/3eeb4cc8-ad66-482c-97e5-490cacfcb517">

If I don't set the `router-animation`  attribute, then this div will have a `display:none` style!

### Expected Behavior

remove the div or add `display:none` style

### Steps to Reproduce

reproduction

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 
   Ionic Framework : @ionic/vue 7.0.12

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : not installed
   @capacitor/core    : 5.0.5
   @capacitor/ios     : 5.0.5

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by fatcarter** [comment]
https://codesandbox.io/p/sandbox/serene-orla-hg27fk?file=%2F.eslintrc.js%3A10%2C5

**Comment by liamdebeasi** [comment]
Thanks for the report. I'm not able to run your sample because I get an "Task exited with code 130" error. Can you double check your reproduction?

**Comment by fatcarter** [comment]
check out this video 


https://github.com/ionic-team/ionic-framework/assets/96217218/ecc66786-ed10-44d2-ba77-ae3003ad05de

**Comment by fatcarter** [comment]
I can't click on any area on the page because there is a transparent mask at the top of the page

**Comment by liamdebeasi** [comment]
Are you able to provide the reproduction in a GitHub repo? I'm not able to run your sample, so I cannot verify if this is a bug in Ionic.

**Comment by fatcarter** [comment]
plz use this repo 

https://github.com/fatcarter/ionic-app-reproduction


run command `ionic server` and open  `http://localhost:8100` in browser

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this behavior. It looks like this is the same as https://github.com/ionic-team/ionic-framework/issues/27428, so I am going to merge the two threads.
