### ISSUE TITLE
feat: Add the ability to configure gesturePriority for ion-refresher component

### ISSUE THREAD

**Issue by mykola-pyvovar** [ionic-team/ionic-framework#27672]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be helpful to have the ability to change the default gesture priority for the ion-refresher component from "31" to any value

### Describe the Use Case

I'm facing a problem while working with the [swiper package](https://www.npmjs.com/package/swiper).
If I have both the swiper and ion-refresher on the same page - the refresh action won't be fired if I perform a "pull down" action in the area with the swiper
Here is the link where you can reproduce that problem: https://stackblitz.com/edit/ionic6-angular13-hpaxp7?file=README.md

When I was working with ion-slides and it was working fine but I switched to the swiper library since ion-slides were deprecated.

I was able to solve this problem by changing the gesturePriority to 999 in the source file of the Ionic 
![image](https://github.com/ionic-team/ionic-framework/assets/56599761/e50d7db6-d371-4c60-b256-faa36cc25f28)

That's why I'm asking for the ability to configure the default gesture priority for the ion-refresher component.
If there is a way to do it from my side and I missed it - please, let me know.

**Comment by liamdebeasi** [comment]
Thanks for the report. Have you tried filing an issue with the Swiper team? It sounds like the root issue is that Swiper is capturing the gesture first and not allowing it propagate. Depending on your use case you might also want to try [CSS Scroll Snapping](https://css-tricks.com/practical-css-scroll-snapping/).
