### ISSUE TITLE
bug: Ion-Textarea causing screen to shrink on focus when having multiple ion-contents

### ISSUE THREAD

**Issue by typefox09** [ionic-team/ionic-framework#27685]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

There's an issue where the screen shrinks when an ion-textarea is selected inside an ion-modal that contains an ion-content. The problem manifests itself specifically when ion-content is placed within ion-modal.

In my setup, I have an ion-modal that includes an ion-nav for multi-page modals. Each page has its individual ion-content. The primary modal is mounted on a page, specifically within ion-page, but outside that page's ion-content.

The official Ionic Framework documentation suggests that placing an ion-content inside an ion-modal is a common practice.

I've reproduced this problem in a minimal example repository. Upon launching the modal, you can observe the screen shrinking behavior.

https://github.com/ionic-team/ionic-framework/assets/61811299/235b32f4-54f0-4403-9b57-40da96f06f0b

### Expected Behavior

The viewport should not shrink

### Steps to Reproduce

1. Create blank ionic vue project
2. Create an ion-modal in a separate component
3. Place a ion-textarea inside of the middle of the view (with heading and button below to show the issue)
4. Click inside of the ion-textarea

Notes: Use floating or stacked label with a counter and rows, I noticed sometimes removing rows, counter and floating or stacked label can make the issue go away.

### Code Reproduction URL

https://github.com/typefox09/textarea

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.6 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.1.0

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : not installed
   @capacitor/core    : 5.0.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.20.0 (/opt/homebrew/Cellar/node@16/16.20.0/bin/node)
   npm    : 8.19.4
   OS     : macOS

**Comment by typefox09** [comment]
As a side note, I've noticed the Ion-textarea is very buggy in general, many issues are submitted about it.... Most of the time I feel it's just easier to use the native HTML textarea on it's own, at least it's reliable.

**Comment by mapsandapps** [comment]
Hi, thank you for the bug report! This is working as intended. When used on a real device, the on-screen keyboard will show up, and this behavior prevents the textarea from being hidden by the keyboard when it enters. It's generally a good idea to test any keyboard-related behavior on a physical device instead of an emulator, to see the real behavior.
