### ISSUE TITLE
feat: disable ion-datetime date-time-picker

### ISSUE THREAD

**Issue by daniel-zero** [ionic-team/ionic-framework#27687]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It should be possible to disable the date-time-picker inside of the ion-datetime component

<img width="402" alt="Screenshot 2023-06-23 at 10 36 35" src="https://github.com/ionic-team/ionic-framework/assets/95087607/d2c77f45-9b7d-4a6f-ab1d-8b01997cef41">
<img width="396" alt="Screenshot 2023-06-23 at 10 20 32" src="https://github.com/ionic-team/ionic-framework/assets/95087607/7437a291-d3bd-44b3-8ce4-0ba8f5eed871">

### Describe the Use Case

In our design system the date picker should not be available

**Comment by amandaejohnston** [comment]
Thank you for the request. Could you clarify what behavior you are looking for? Do you want to be able to set `disabled="true"` on the `ion-datetime`, similar to an `ion-input` or other form control components? Or do you want to only display a time picker, not a date picker?

**Comment by daniel-zero** [comment]
@amandaejohnston I missed to mark the exact element I want to disable. Here is an updated screenshot.
When the user clicks on this element the then shown date-time-wheel will be displayed. I want to disable this behaviour.

<img width="397" alt="Screenshot 2023-06-23 at 16 12 20" src="https://github.com/ionic-team/ionic-framework/assets/95087607/bd7381cf-e53c-4fec-bde1-6336e8863958">

**Comment by amandaejohnston** [comment]
Thank you for the details. In the recent 7.1 release, we added a shadow part to that button called `month-year-button`. You could use this to set `pointer-events: none` on the button, preventing interaction, and potentially include other CSS to make it look disabled as needed. Example: https://stackblitz.com/edit/angular-o9ezgz?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.css

Alternatively, if you are trying to restrict the user from selecting certain months or years, the [`monthValues` and `yearValues` props](https://ionicframework.com/docs/api/datetime#selecting-specific-values) may be useful to you. This would not disable the month/year picker entirely, however. Example: https://stackblitz.com/edit/angular-3xtu6r?file=src%2Fapp%2Fexample.component.html

Could you give one of these a try and let me know if it resolves your issue?
