### ISSUE TITLE
bug: Keyboard ionic 7 and IOS

### ISSUE THREAD

**Issue by ludonoel1** [ionic-team/ionic-framework#27693]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Android: OK
IOS: When open keyboard, fixed content is pushed and ion-content doesn't scroll to input. Input file dis hidden by keyboard.. IS there a fix or maybe I'm doing wrong

### Expected Behavior

Android as ios. Keyboard hide fixed content at bottom and ion-content scroll to input field.

### Steps to Reproduce

create a form with scroll and a fixed bottom button to continue form
click on input field and see

### Ionic Info

ionic 7.0.4
    "@capacitor/core": "^5.0.0",

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
