### ISSUE TITLE
bug: onIonInput event is not fired when changing  the value of the IonInput programatically

### ISSUE THREAD

**Issue by FernetB** [ionic-team/ionic-framework#27709]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If you change the value of a `<IonInput />` programatically, the `onIonInput` event is not fired

Docs:

![image](https://github.com/ionic-team/ionic-framework/assets/47339424/5f4bce92-546d-415b-8851-7fb03d9d34a2)

PD: it worked on  `@ionic/react 5.9.1` when we used the `onIonChange` that now changes to `onIonInput`

### Expected Behavior

The `onIonInput` being fired on `IonInput` programatically value change 

### Steps to Reproduce

Just add a `IonInput` component with logs in the `onIonInput` method and `button` component that change the value of the input by ref

### Code Reproduction URL

https://github.com/FernetB/ionic-tabs-bug

### Ionic Info

Ionic:

Ionic CLI : 7.0.1
Ionic Framework : @ionic/react 7.0.6

Capacitor:

Capacitor CLI : 5.0.3
@capacitor/android : not installed
@capacitor/core : 5.0.3
@capacitor/ios : not installed

Utility:

cordova-res : not installed globally
native-run : 1.7.2

System:

NodeJS : v18.16.0
npm : 9.5.1
OS : Linux 5.15

**Comment by liamdebeasi** [comment]
Thanks for the report. This is an intentional behavior of Ionic, though it looks like our docs are confusing. `ionInput` fires when the value of the input has changed as a result of user interaction, similar to the [native `input` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event). In other words, programmatically setting the `value` will not cause `ionInput` to fire. I will update the docs.

**Comment by liamdebeasi** [comment]
I updated the docs to make this behavior more clear: https://github.com/ionic-team/ionic-framework/pull/27710

Let me know if you have any questions.

**Comment by AleksandrRadik** [comment]
Hi there! In this case, if ionInput don't fires when value changed programmatically, which method or instrument we can use for watching this changes? I try use valueChanges observer, but this one don't working too. Thanks in advance for your reply)

**Comment by liamdebeasi** [comment]
We don't fire any events when the value is changed programmatically. This is the same behavior with a native `input` element even when not using Ionic. The reason for this is if a developer writes code in an app to change the value of an input, then they already know when the value changes.
