### ISSUE TITLE
bug?: no "label" property in <IonTextarea>

### ISSUE THREAD

**Issue by creatxrgithub** [ionic-team/ionic-framework#27714]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

1)

`
<IonTextarea label="" id="outputTextArea" style={{}} autoGrow={true} rows={1} placeholder=""></IonTextarea>
`

```
[react-scripts]   Property 'label' does not exist on type 'IntrinsicAttributes & IonTextarea & Pick<HTMLAttributes<HTMLIonTextareaElement>, "hidden" | ... 251 more ... | "onTransitionEndCapture"> & StyleReactProps & RefAttributes<...>'
```

maybe it's resolved after upgraded:

```
npm install react@latest react-dom@latest
npm install @ionic/react@7 @ionic/react-router@7
```

it's a feature of version 7.

### Steps to Reproduce

1. ionic start
2. ionic serve -w firefox
3. 

### Ionic Info

ionic info

Ionic:

   Ionic CLI       : 7.1.1 (/home/creatxr/.nvm/versions/node/v18.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.1.1

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : not installed
   @capacitor/core    : 5.0.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (/home/creatxr/.nvm/versions/node/v18.16.0/bin/node)
   npm    : 9.5.1
   OS     : Linux 6.2

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
