### ISSUE TITLE
bug?: display problem in chromium browser with style <IonItem style={{'overflowX': 'scroll'}}>

### ISSUE THREAD

**Issue by creatxrgithub** [ionic-team/ionic-framework#27715]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

the left picture is in chromium, the right picture is in firefox.

i don't know if ionic needs more style setting to show in chromium, or it's only the problem of chromium.

![Untitled](https://github.com/ionic-team/ionic-framework/assets/27437178/52564a86-3d57-4402-9861-0f9209ffdce3)

### Expected Behavior

ionic serve -w chromium
ionic serve -w firefox

### Steps to Reproduce

1. start a new project
2. add 
\<IonItem style={{'overflowX': 'scroll'}}>{/*todo: horizontal scroll*/}\</IonItem>
4. ionic serve -w chromium

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/home/creatxr/.nvm/versions/node/v18.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.1.1

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : not installed
   @capacitor/core    : 5.0.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (/home/creatxr/.nvm/versions/node/v18.16.0/bin/node)
   npm    : 9.5.1
   OS     : Linux 6.2

**Comment by creatxrgithub** [comment]
in opera browser, it has the same problem of chromium.

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
