### ISSUE TITLE
bug:  keyboard focus problem Ionic 6.5.1

### ISSUE THREAD

**Issue by evindev** [ionic-team/ionic-framework#27718]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Hi,
as suggested by ionic support, I open a request here, I have a problem with opening the keyboard in mobile for a simple login page (especially with ios), the content does not scroll up in the right way but the keyboard covers a part of the screen making it impossible to user interaction.

### Expected Behavior

Content must scroll up to the focus of an ion input

### Steps to Reproduce

In mobile press on the email input then press on the password input

### Code Reproduction URL

https://stackblitz.com/edit/ionic6-angular13-jw8pan?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

"@ionic/angular": "6.5.1",
"@capacitor/android": "^5.0.0",
"@capacitor/ios": "^5.0.0",
"@capacitor/keyboard": "^5.0.0",
"@capacitor/core": "^5.0.0",
"@angular/core": "^15.1.2",
"@angular/forms": "^15.1.2",

**Comment by liamdebeasi** [comment]
Thanks for the report. Does this issue reproduce in Ionic 7? We made a number of improvements to keyboard focus in Ionic 7.

**Comment by liamdebeasi** [comment]
Yes, if you are able to create a reproduction with Ionic 7 that would be great. We no longer maintain Ionic 6 except for critical security fixes.

**Comment by evindev** [comment]
I updated to "@ionic/angular": "7.1.1", but nothing changed, in android everything works fine, in ios changing from one input to another the whole view returns to the starting point (like when the keyboard is not open), while if I press on the single input and then manually close the keyboard everything behaves correctly.

**Comment by liamdebeasi** [comment]
Are you able to provide a reproduction with Ionic 7?

**Comment by evindev** [comment]
Yes i have created a new project with the frameworks i am using together with ionic, here is the link:

[https://stackblitz.com/edit/stackblitz-starters-clspur?file=src%2Flogin%2Flogin.page.html,src%2Flogin%2Flogin.page.ts](stackBlitz)

**Comment by liamdebeasi** [comment]
Are you able to send this as a GitHub repo that I can clone instead? For some reason the StackBlitz is hanging at "Starting dev server".
