### ISSUE TITLE
bug: upgrade rxjs version to 7.x.y

### ISSUE THREAD

**Issue by alex5956** [ionic-team/ionic-framework#27713]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

error with `npm i` command

### Expected Behavior

could you upgrade rxjs version to 7.x.y in all ionic-native packages ? please ?

### Steps to Reproduce

could you upgrade rxjs version to 7.x.y in all ionic-native packages ? please ?

### Ionic Info

could you upgrade rxjs version to 7.x.y in all ionic-native packages ? please ?

**Comment by liamdebeasi** [comment]
Hi there,

Ionic Native is now managed by a community member as `awesome-cordova-plugins` over on https://github.com/danielsogl/awesome-cordova-plugins. See https://ionic.io/blog/a-new-chapter-for-ionic-native for more information on the Ionic Native migration.

I see you have already filed an issue on https://github.com/danielsogl/awesome-cordova-plugins/issues/4583, so I recommend working with the maintainer on that thread to get this dependency issue resolved. Thanks!
