### ISSUE TITLE
bug: Ionic Uses "md" class for its components to render material design styling.

### ISSUE THREAD

**Issue by devusama99** [ionic-team/ionic-framework#27725]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I am using IONIC V7 with Quasar UI Framework. The issue i am facing is that Ionic app uses classname "md" to tell its components that they have to follow material design on android whereas same class "md" used in quasar to tell its component that they should only visible on Medium Size Screen. So i am not seeing any screen on android becuase "md" class of quasar is making it display none for the screens other than medium size.

I am Trying to use both IONIC and Quasar in a single Capictor app

### Expected Behavior

Ionic class "md" should be replaced with "android" as on IOS it is "ios" because most of the UI libs uses "md" to define screen size Range

### Steps to Reproduce

Create an Ionic Project.
Install Quasar Vite Plugin.

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/hashstack/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.1.1

Capacitor:

   Capacitor CLI      : 5.1.0
   @capacitor/android : 5.1.0
   @capacitor/core    : 5.1.0
   @capacitor/ios     : 5.1.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.1 (/Users/hashstack/.nvm/versions/node/v18.16.1/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the issue. While I understand this behavior is not desirable, Ionic Framework is working as intended here. The `md` class is used to indicate Material Design, not Android devices. Developers are able to use the Material Design theme on iOS devices too, so I think changing this to the `android` class would be confusing. Additionally, many developers target the `md` class in their CSS to style their app based on the theme. Changing this class would be a significant breaking change, which is not something we are looking to do at the moment.

I recommend looking to see if you can exclude the [breakpoint classes](https://quasar.dev/style/breakpoints/) from your build when using Quasar. This would avoid the naming collision.
