### ISSUE TITLE
feat ion-input, ion-toggle v7 expose label  as shadow part for color change

### ISSUE THREAD

**Issue by phyr0s** [ionic-team/ionic-framework#27729]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add CSS Custom Property to change the color of the label using ion-input or ion-toggle without ion-label

### Describe the Use Case

<ion-input 
          label="test"
          labelPlacement="stacked"
          type="text"
          placeholder="test place holder"
          name="test">
 </ion-input>
 
 Label text can't be changed  to orange for example like the image that I attach
 
<img width="645" alt="img" src="https://github.com/ionic-team/ionic-framework/assets/11390548/006e3a4d-d082-455c-a0b4-906e30aaedac">

**Comment by liamdebeasi** [comment]
Thanks for the report. You can pass in custom HTML for the label, so you can target those nodes to change the color: https://codepen.io/liamdebeasi/pen/KKrmXdK

**Comment by phyr0s** [comment]
@liamdebeasi  thanks for your answer!!
