### ISSUE TITLE
feat: add blurOnStart to true for swipe-to-go-back

### ISSUE THREAD

**Issue by mulhoon** [ionic-team/ionic-framework#27738]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I think the swipe flag `blurOnStart` should be either configurable for swipe-to-go-back or default to `true`. It is currently `true` when swiping a menu open, but`false` for swiping back between pages.

### Describe the Use Case

Sometimes the keyboard is open on a route, and the user swipes back. Currently, the keyboard does not automatically hide, and the caret/cursor stays on screen (ios) while swiping until the animation ends and the route has changed.

### Describe Preferred Solution

It would be preferred to set `blurOnStart` as true by default for swipe-to-go-back events

### Related Code

https://github.com/ionic-team/ionic-framework/blob/a4197a5c74393948af7f6c46d70b4dac055047e4/core/src/utils/gesture/swipe-back.ts#L79C1-L88C6

### Additional Information

I cannot find any mention of this in Issues, Forum or StackOverflow.

Thanks

**Comment by liamdebeasi** [comment]
Thanks for the report. Do you have a video sample of the caret issue happening on swipe?
