### ISSUE TITLE
bug: React Ionic lifecycle hooks run twice in dev mode

### ISSUE THREAD

**Issue by tallpants** [ionic-team/ionic-framework#27733]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The lifecycle hooks in Ionic React make use of `useEffect` ([code](https://github.com/ionic-team/ionic-framework/blob/a4197a5c74393948af7f6c46d70b4dac055047e4/packages/react/src/lifecycle/hooks.ts)), which coupled with React's strict mode in React 18 ([link](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-strict-mode)) mean they will run twice in development.

This makes it hard to do things like check a condition and present an alert on page enter, because the alert will be presented twice. Our use case right now can be condensed to:

```tsx
const HomeScreenComponent: React.FC = () => {
  const [presentAlert] = useIonAlert();

  useIonViewDidEnter(() => {
     if (deviceIsOnAirplaneMode()) {
       presentAlert('Some functionality is not available when Airplane Mode is on');
     }
  });
}
```

This running twice behaviour is not in the documentation, so I'm guessing it's not intentional: https://ionicframework.com/docs/react/lifecycle#lifecycle-methods-in-functional-components

The lifecycle hooks also seem to be setting a random ID on the callback ([code](https://github.com/ionic-team/ionic-framework/blob/a4197a5c74393948af7f6c46d70b4dac055047e4/packages/react/src/lifecycle/hooks.ts#L9)) which I'm assuming could be used to (and might already be meant to) de-duplicate these calls which would fix the problem?

### Expected Behavior

React Ionic lifecycle hooks only run once even in dev-mode.

### Steps to Reproduce

1. Create an Ionic React project
2. Wrap the root component in `<React.StrictMode></React.StrictMode>`
3. Use an Ionic lifecycle hook (`useIonViewWillEnter`, `useIonViewDidEnter`, etc.) in a page that's controlled by Ionic React Router 
4. Code inside the lifecycle hook will run twice when the lifecycle event is triggered.

### Ionic Info

```

Ionic:

   Ionic CLI       : 7.0.1 (/Users/adithya/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.10

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : 5.0.4
   @capacitor/core    : 5.0.4
   @capacitor/ios     : 5.0.4

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/Users/adithya/.n/bin/node)
   npm    : 9.5.0
   OS     : macOS
```

**Comment by liamdebeasi** [comment]
Thanks for the report. React 18 runs effects twice on mount when you are in development mode with strict mode enabled: https://stackoverflow.com/questions/72238175/why-useeffect-running-twice-and-how-to-handle-it-well-in-react.

Are you able to provide a reproduction of this issue happening? I can take a closer look and see if there is some way we can make this experience a bit smoother in Ionic apps.
