### ISSUE TITLE
bug: ion-checkbox is not interactable

### ISSUE THREAD

**Issue by Hurricane86** [ionic-team/ionic-framework#27739]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The ion-checkbox is not interactable if we click on the item but not on the label direclty. 
This happen when the checkbox _slot_ is set to "start".

### Expected Behavior

The entire item should be interactable.

### Steps to Reproduce

1. Open the Code Reproduction URL;
2. Click on the first row to verify the working case;
3. Click on the second row to the reproduce the issue.

### Code Reproduction URL

https://codepen.io/hurricane86/pen/WNYOEeZ

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\Martino\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.1.1 (D:\Unamedia\srt-html5\node_modules\@ionic\angular)
   @angular-devkit/build-angular : 16.1.3 (D:\Unamedia\srt-html5\node_modules\@angular-devkit\build-angular)
   @angular-devkit/schematics    : 16.1.3 (D:\Unamedia\srt-html5\node_modules\@angular-devkit\schematics)
   @angular/cli                  : 16.1.3 (D:\Unamedia\srt-html5\node_modules\@angular\cli)
   @ionic/angular-toolkit        : 9.0.0 (D:\Unamedia\srt-html5\node_modules\@ionic\angular-toolkit)

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.7.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. This is by design. The clickable area is only on the `ion-checkbox`, so putting the checkbox in the start slot means that only the start slot will be clickable.
