### ISSUE TITLE
bug: clearOnEdit should not clear input when tabbing to next input

### ISSUE THREAD

**Issue by jmedellinc** [ionic-team/ionic-framework#27746]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The clearOnEdit option of ion-input is supposed to clear the content of the ion-input when a new character is entered

If filling a form with the keyboard, if you tab into an input which has contents and then you tab into another input, the input clears, which i think is not what's expected?

### Expected Behavior

The input should not be erased if the input "entered" is the tab key..

### Steps to Reproduce

1. Go to https://ionicframework.com/docs/api/input#clear-options
2. Activate the text input which has clearOnEdit activated
3. tab change into the following input
4. Shift-Tab into the previous input, which results in the input with clearOnEdit option activated and it has already text
5. Tab again to change into the next input
6. ... the input clears.. 

### Code Reproduction URL

https://ionicframework.com/docs/api/input#clear-options

### Ionic Info

Latest.. Test based on ionic Docs

**Comment by liamdebeasi** [comment]
Thanks for the report. Here is a dev build with a proposed fix if you are interested in testing: `7.3.1-dev.11692202566.13cd16c4`

Install Example: `npm install @ionic/core@7.3.1-dev.11692202566.13cd16c4`

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28005, and a fix will be available in an upcoming release of Ionic Framework. Feel free to keep testing the dev build, and let me know if you have any questions.
