### ISSUE TITLE
bug: Cors error on ios only

### ISSUE THREAD

**Issue by drkhannah** [ionic-team/ionic-framework#27749]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Im getting an error when running on ios only

im trying to access firebase realtime database, this works on android and in a browser just fine

but on ios i get this error

[Error] TypeError: undefined is not an object (evaluating 'gapi.iframes.getContext')
	callback (main.cb86b0cb1b1543a2.js:1:156205)
	(anonymous function) (api.js:29)
	Ja (api.js:21:705)
	E (api.js:28:502)
	(anonymous function) (api.js:29:83)
	(anonymous function) (api.js:29:146)
	Global Code (cb=gapi.loaded_0:1)
[Error] Error: A`capacitor
	(anonymous function) (api.js:29:638)
	(anonymous function) (api.js:29)
	Ja (api.js:21:705)
	E (api.js:28:502)
	(anonymous function) (api.js:29:83)
	(anonymous function) (api.js:29:146)
	Global Code (cb=gapi.loaded_1:1)
[Error] Cross-origin redirection to http://developers.google.com/ denied by Cross-Origin Resource Sharing policy: Origin capacitor://localhost is not allowed by Access-Control-Allow-Origin. Status code: 301
[Error] XMLHttpRequest cannot load https://apis.google.com/_/jserror?script=https%3A%2F%2Fapis.google.com%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.lb.en.5o5-TAFr18s.O%2Fm%3Dgapi_iframes%2Frt%3Dj%2Fsv%3D1%2Fd%3D1%2Fed%3D1%2Frs%3DAHpOoo_qgszOsFrBH7bZ1Rmfwa9Mc03wLQ%2Fcb%3Dgapi.loaded_0&error=A%60capacitor&line=150 due to access control checks.
[Error] Failed to load resource: Cross-origin redirection to http://developers.google.com/ denied by Cross-Origin Resource Sharing policy: Origin capacitor://localhost is not allowed by Access-Control-Allow-Origin. Status code: 301 (jserror, line 0)

### Expected Behavior

should be able to connect to firebase realtime database without cors error

### Steps to Reproduce

make any connection to firebase realtime database or any https call on web and android, this wont work on ios, i get a cors error

### Ionic Info

ionic info

Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.1.1
   @angular-devkit/build-angular : 16.1.3
   @angular-devkit/schematics    : 16.1.3
   @angular/cli                  : 16.1.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.2
   @capacitor/android : 5.0.2
   @capacitor/core    : 5.0.2
   @capacitor/ios     : 5.0.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (/usr/local/Cellar/node@18/18.16.0/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Hey there,

That error is coming from a Google API, not Ionic. (see: `[Error] TypeError: undefined is not an object (evaluating 'gapi.iframes.getContext')`). I recommend creating a post on the [Ionic Forums](https://forum.ionicframework.com/) for help debugging this.
