### ISSUE TITLE
ion-datetime modal closes automatically while scrolling years wheel. 

### ISSUE THREAD

**Issue by groupla** [ionic-team/ionic-framework#27758]
As posted in the following link, I've implemented ion-datetime inside ion-modal and clicking on date, it closes modal. The problem is when we scroll years wheel, the modal gets closed and a date gets selected automatically. To simulate it, follow the link below, click on year and scroll the wheel... 

How can we avoid it? 

Here is an example: https://codepen.io/liamdebeasi/pen/jOpyoZq

_Originally posted by @liamdebeasi in https://github.com/ionic-team/ionic-framework/issues/26531#issuecomment-1375663949_

**Comment by liamdebeasi** [comment]
When you select new values with the wheel picker it is going to update the `value` on `ion-datetime`, causing `ionChange` to fire. As a result, `ionChange` being fired when the wheel picker is scrolled is the intended behavior. I also recommend posting this on the [Ionic Forums](https://forum.ionicframework.com/) for help with this. We use this GitHub tracker for bug fixes and feature requests.
