### ISSUE TITLE
bug: Ion-accordion unintentionally closing

### ISSUE THREAD

**Issue by rl-carno** [ionic-team/ionic-framework#27760]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When you have an ion-accordion with lots of content and it dramatically changes and you also have a ion-segment at the top, it automatically and unintentionally closes the accordion and opens a random other accordion item.

My component had the following code

`<ion-content>
  <ion-accordion-group>

    <ion-accordion [value]="1">
     CONTENT IN HERE
    </ion-accordion>
    <ion-accordion [value]="2">
     CONTENT IN HERE
    </ion-accordion>
    <ion-accordion [value]="3">

      <ion-segment (ionChange)="updateSelectedFruit($event)" [value]="selectedFruit">
        <ion-segment-button>
          Apples
        </ion-segment-button>
        <ion-segment-button>
          Oranges
        </ion-segment-button>
      </ion-segment>

      <ng-container *ngIf="selectedFruit === 'apples'">

        <h1>Apples</h1>
        <p>A little bit of content here, not enough to require scrolling.</p>

      </ng-container>

      <ng-container *ngIf="selectedFruit === 'oranges'">

        <h1>Oranges</h1>
        <p>Lots of content here, big enough to require scrolling.</p>

      </ng-container>

    </ion-accordion>

  </ion-accordion-group>
</ion-content>
`

Now when the content dramatically changes because of the segment being clicked, it for some reason randomly closes the accordion and opens another, obviously not intentionally.

### Expected Behavior

The accordion shouldn't close unless clicked / tapped directly or programmatically triggered by model change.

### Steps to Reproduce

See the above code.

What I've determined is that you need to have a distinctive change in content (so the parent container goes from big to small because of the dramatic size difference in content) at the point of which the segment is clicked to trigger the bug.

I've got around it for now by disabling the ion-accordion for a split second when ion change occurs on the segment, then reenabling it, a setTimeout of 10ms was required to make it reliable.

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\NodeJS\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.12
   @angular-devkit/build-angular : 16.0.5
   @angular-devkit/schematics    : 16.0.5
   @angular/cli                  : 16.0.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : not installed
   @capacitor/core    : 5.0.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.6.5
   OS     : Windows 10

**Comment by rl-carno** [comment]
Unfortunately, I do not have time to reproduce this, the code extract above should cause it to occur. I've found a workaround for now so this isn't a priority for me personally, I'm pointing it out purely out of courtesy. There is definitely an issue there.

For further context, my page was using an accordion with a sub accordion. (Nested accordions), this has caused a few other "quirks" to occur, such as ion-select (popup interface) causing the page to snap (scroll) to top of accordion view when trying to trigger the popup.

My recommendation is stress testing 2 tier nested accordion with both ion-select (popup interface) and the scenario outlined above.

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
