### ISSUE TITLE
bug: ios launchScreen white

### ISSUE THREAD

**Issue by TheSoils** [ionic-team/ionic-framework#27761]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

ios splash doesnt work, the initial blank project is also start with a white lanchun screen, the default screen doesn't work.

### Expected Behavior

the launch screen show splash success

### Steps to Reproduce

1.just ionic start an blank empty
2.add ios project
3.run ios client, the lanunch screen is only white with no splash.

### Code Reproduction URL

https://github.com/TheSoils/ion-tab-test

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/wyman/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.1.0

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : 5.0.5
   @capacitor/core    : 5.0.5
   @capacitor/ios     : 5.0.5

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.19.0 (/Users/wyman/.nvm/versions/node/v16.19.0/bin/node)
   npm    : 9.6.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
I'm not able to reproduce this using an iOS 16 device. I recommend checking the console for any errors. If the issue persists, I recommend posting on the [Ionic Forum](https://forum.ionicframework.com/) for help debugging this.
