### ISSUE TITLE
bug: long action sheet with safe area pushes cancel button off screen

### ISSUE THREAD

**Issue by wsamoht** [ionic-team/ionic-framework#27777]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

It appears starting in Ionic 7, the Cancel button for the `IonActionSheet` and `IonSelect` (with interface "action-sheet") is being pushed off screen when there is `--ion-safe-area-top` set.

![image](https://github.com/ionic-team/ionic-framework/assets/5725966/110cf4cf-52e4-45b3-9abe-07425af85df6)

### Expected Behavior

I would expect the Cancel button to be fixed at the bottom and fully visible.

### Steps to Reproduce

**Steps**
1. Create an `ion-action-sheet` (with a Cancel button) or `ion-select` (with `interface=action-sheet`) with enough items to force a scroll
2. Set `--ion-safe-area-top`

### Code Reproduction URL

**Stackblitz examples**
- [IonActionSheet](https://stackblitz.com/edit/oejis3?file=src%2Fcomponents%2FExample.vue)
- [IonSelect](https://stackblitz.com/edit/c3gq9c?file=src%2Fcomponents%2FExample.vue)

### Ionic Info

```
Ionic:

   Ionic CLI       : 7.1.1
   Ionic Framework : @ionic/vue 7.1.2

Capacitor:

   Capacitor CLI      : 4.8.1
   @capacitor/android : 4.8.1
   @capacitor/core    : 4.8.1
   @capacitor/ios     : 4.8.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.12.1
   npm    : 8.19.2
   OS     : Linux 5.15
```

### Additional Information

This is affecting both Android and iOS.

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. As a temporary workaround you can set `--height: 100%`, though note that the content will take slightly longer to appear on animate in due to the increase height on the inner wrapper element.
