### ISSUE TITLE
bug: Broken Ionic Page Transition on Initial Load 

### ISSUE THREAD

**Issue by ShanArosh** [ionic-team/ionic-framework#27776]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In both dev & prod [web,apk] environments, when transitioning to another page the animation lags and is broken into two visible parts (not seamless). 
`checkout the screen capture =>`  [screen-capture.webm](https://github.com/ionic-team/ionic-framework/assets/96517136/6edbd05c-989b-419d-b818-c1eb48150e67)

### Expected Behavior

seamless page transition. (Without having to hard reload the page)
`Expected Behaviour =>`  [expected-behaviour-capture.webm](https://github.com/ionic-team/ionic-framework/assets/96517136/93b771ed-ef55-4443-a733-0e302c920346)

### Steps to Reproduce

1. Generate a new project with ionic CLI [react-vite].
2. Setup 2 IonPages & try navigating between them with history.push('url').

### Code Reproduction URL

https://github.com/ShanArosh/Ionic-Page-Transition-Bug

### Ionic Info

```
Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\In-Motion\AppData\Roaming\npm\node_modules\@ionic\cli)   
   Ionic Framework : @ionic/react 7.1.2

Capacitor:

   Capacitor CLI      : 5.1.1
   @capacitor/android : not installed
   @capacitor/core    : 5.1.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.1
   OS     : Windows 10

```

### Additional Information

Doing A reload after the initial page load fixes the issue temporarily.

**Comment by liamdebeasi** [comment]
Thanks for the report. Does the issue reproduce if you do the following for the fallback route instead?

```js
<Route path="/" exact={true} render={() => <Redirect to="/login" />} />
```

**Comment by ShanArosh** [comment]
@liamdebeasi  Thanks for the quick reply. Replacing,
`<Route path="/" exact={true} render={() => <Redirect to="/login" />} />` solve the problem.

**Comment by liamdebeasi** [comment]
This behavior may be related to a quirk in the Ionic React Router where we clone the page node under certain circumstances so the page transition runs: https://github.com/ionic-team/ionic-framework/blob/82c568b8c8e1e9934e1928452aa5216619290e7b/packages/react-router/src/ReactRouter/StackManager.tsx#L368-L373

This is definitely not the idea behavior, and we would like to improve that experience.
