### ISSUE TITLE
bug: clicking backdrop on action sheet focuses first button

### ISSUE THREAD

**Issue by Forsakenrox** [ionic-team/ionic-framework#27773]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Сalling and dismissing the ion-action-sheet causes the effect of phantom clicking on the first item in the list

### Expected Behavior

The ion-action-sheet should open and close without any extraneous effects

### Steps to Reproduce

1. Go to [official docs of action-sheet](https://ionicframework.com/docs/api/action-sheet)
2. Press the button in middle of rendered example
3. Dismiss ion-action-sheet by clicking away
![animation](https://github.com/ionic-team/ionic-framework/assets/11795286/a2defef1-995b-4ada-a943-f88c5ae971e1)

### Code Reproduction URL

https://ionicframework.com/docs/api/action-sheet

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\admin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.1.1

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : not installed
   @capacitor/core    : 5.0.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. The problem here is our focus trapping utility moves focus back to the first button when the backdrop is clicked (and therefore receives focus). Our focus trap utility assumes that any focusable content will be as a child of `.ion-overlay-wrapper`. This is true _except_ for backdrops.
