### ISSUE TITLE
bug: Safari adjusts font size in landscape orientation

### ISSUE THREAD

**Issue by darrylnoakes** [ionic-team/ionic-framework#27782]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Safari does not support the unprefixed `text-size-adjust` CSS property, so that is never applied. In certain cases, Safari's resizing heuristics are triggered and it adjusts the font size after switching to landscape orientation.

### Expected Behavior

Text should not be resized.

### Steps to Reproduce

1. Create a simple page with two `div`s with some text:
    ```html
    <ion-page>
      <ion-content>
        <div>Test line 1</div>
        <div>Test line 2</div>
      </ion-content>
    </ion-page>
    ```
2. Open the page in landscape orientation or rotate to it.
3. The text will have a font size of `23px` instead of `16px`.

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.16.3 (C:\Users\Darryl\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.7.5

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.15.0 (C:\Users\Darryl\AppData\Local\Volta\tools\image\node\18.15.0\node.exe)
   npm    : 9.5.0
   OS     : Windows 10
```

### Additional Information

The fix: use `-webkit-text-size-adjust` as well as `text-size-adjust`.

[`text-size-adjust` - Can I use?](https://caniuse.com/text-size-adjust)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27787, and a fix will be available in an upcoming release of Ionic Framework.
