### ISSUE TITLE
bug: Collapsed header + Virtual scroll

### ISSUE THREAD

**Issue by noskovvkirill** [ionic-team/ionic-framework#27793]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hi! We use `<IonHeader collapse="condense" className="ion-padding-start"/>` with Virtuoso to create a collapsible header. 
```
  <GroupedVirtuoso
      className="ion-content-scroll-host h-full overflow-scroll"
      endReached={() => {
        if (hasNextPage) {
          fetchNextPage();
        }
      }}
      components={{
         Header: () => {
           return(
          <IonHeader collapse="condense" className="ion-padding-start">
              <IonToolbar>
                    <h1 className="text-h1 font-medium">Notifications</h1>
              </IonToolbar>
          </IonHeader>
        )
        }
        }} 
  ...
  /> 
```

However, it blinks when the new data is loaded and Virtuoso rerenders. We added a key, tried to memoize it, but nothing helps. Header rerenders, but doesn't disappear from the tree. I've attached a video to show the behaviour. 

https://github.com/ionic-team/ionic-framework/assets/50060130/09fd0cb0-e7a6-4460-a486-34619e971a5a

### Expected Behavior

No flickering on rerender for condensed Header 

### Steps to Reproduce

1. Add Virtual list 
2. Create collapsible Header inside the Virtual list 
3. Append data to Virtual list while you scroll

### Ionic Info

Ionic:

   Ionic CLI : 7.1.1
    "@ionic/core": "^7.1.1",
    "@ionic/pwa-elements": "^3.1.1",
    "@ionic/react": "7.1.0",
    "@ionic/react-router": "7.1.0",

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.16.0
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by noskovvkirill** [comment]
Reproduced it here @liamdebeasi 
Repo: https://github.com/noskovvkirill/ionic-reproduction-header-issue
Component: https://github.com/noskovvkirill/ionic-reproduction-header-issue/blob/main/components/pages/Feed.jsx

**Comment by liamdebeasi** [comment]
The problem here is the header passed in to `Header` for Virtuoso keeps getting re-created every so often. If the collapsible large title is removed from the DOM, then the main header needs to be updated too.

In this case, the component should be memoized. Instead of using an arrow function, you can use a React component:

```tsx
function Header() {
  return (
    <IonHeader collapse="condense">
      <IonToolbar>
        <IonTitle size="large">Feed</IonTitle>
      </IonToolbar>
    </IonHeader>
  )
}

....

<Virtuoso 
  components={({ Header })}
/>
```

**Comment by noskovvkirill** [comment]
Thanks @liamdebeasi 
We ended up keeping the function instead of the component and memoizing it using useCallback / useMemo
