### ISSUE TITLE
feat: export utils separate

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#27799]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Ionic includes a lot of very cool utils, that are used internally but also are exported for Ionic Users. It would be awesome if there are somehow exported separate. I'm mostly talking about:

- Animation & createAnimation
- Gesture & createGesture

### Describe the Use Case

We use Ionic in our main application and Stencil to create a company-wide design system. I wan to use these Animation and gesture controllers (which are awesome) in the design system stencil project without install the complete @ionic/core 🤔

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you clarify the feature request? You can already import `createAnimation` and `createGesture` without importing the rest of Ionic.

**Comment by EinfachHans** [comment]
That's awesome, didn't know that, Thanks
