### ISSUE TITLE
bug: Component mount repeatedly while invoking popTo or popToRoot of IonNav

### ISSUE THREAD

**Issue by zhbhun** [ionic-team/ionic-framework#27798]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hi,

I use IonNav in react, invoking `popTo` lead to component mount twice. 

1. Each element in IonNav views not have key —— https://github.com/ionic-team/ionic-framework/blob/main/packages/react/src/components/navigation/IonNav.tsx#L22
2. Each view is wrapped by Portal ——  https://github.com/ionic-team/ionic-framework/blob/main/packages/react/src/framework-delegate.tsx#L25
3. Page A => Page B  => Page C => Page D, from Page D popTo Page B. Page D would unmount, then mount agin, finally unmount, It causes to make multiple initialization requests of Page D.

### Expected Behavior

Page D unmount only once.

### Steps to Reproduce

1. Build a IonNav and four page - Page A, Page B, Page C, Page D;
2. Push page one by one;
3. popTo Page B from Page D;

### Code Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-zcyaaq

### Ionic Info

Ionic:
Ionic Framework : @ionic/react 7.1.2

System:
NodeJS : v16.19.1
npm : 8.19.3
OS : macOS

**Comment by zhbhun** [comment]
https://stackblitz.com/edit/stackblitz-starters-zcyaaq

When clicking "Go To Page One" in PageThree, PageThree would remount agin.

```log
page three mount
page three unmount
page three mount
page three unmount
```

**Comment by sean-perkins** [comment]
Thanks for reporting this issue and providing a reproduction @zhbhun! I see the same issue and I believe your assessment is correct regarding the lack of `key` for tracking the view instances. I'll label this as a bug and will prioritize taking a look at your pull request 👍 

Thanks!
