### ISSUE TITLE
bug: Ion item with input click event fires twice 

### ISSUE THREAD

**Issue by DanMakor** [ionic-team/ionic-framework#27796]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When adding an ion item with a nested ion input to your page, the click handler on the ion item will be fired twice when clicked once. 

### Expected Behavior

The ion item click handler should only be fired once for a single click.

### Steps to Reproduce

1. Ensure you are on mobile or mobile emulation
2. Add an ion item with a nested ion input to the top of the page (scroll assist must trigger)
3. Add a click handler to the ion item 
4. Click the ion item and note that the click handler fires twice for a single click

### Code Reproduction URL

https://github.com/DanMakor/ionic-scroll-assist-click

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - /Users/mcauliffe/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/mcauliffe/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/mcauliffe/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli/index.js
       - /Users/mcauliffe/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /Users/mcauliffe/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/mcauliffe/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/mcauliffe/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli/index.js
       - /Users/mcauliffe/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/mcauliffe/.nvm/versions/node/v18.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.1.3
   @angular-devkit/build-angular : 16.1.4
   @angular-devkit/schematics    : 16.1.4
   @angular/cli                  : 16.1.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.2.1
   @capacitor/android : not installed
   @capacitor/core    : 5.2.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.1 (/Users/mcauliffe/.nvm/versions/node/v18.16.1/bin/node)
   npm    : 9.5.1
   OS     : macOS Monterey

### Additional Information

This will only occur on the focus click of the input/item. If you keep clicking after the input has already been focused a single event will fire for each click. If you blur the input/item and then click it again, you will get the double click behaviour. I believe it is occurring due to the scroll assist functionality for mobile. 

`/**
   * Relocating/Focusing input causes the
   * click event to be cancelled, so
   * manually fire one here.
   */
  raf(() => componentEl.click());`

This line fires a click event manually because relocation/focusing of the input cancels the original click. Maybe the original click is no longer getting cancelled and it's doubling up?

**Comment by liamdebeasi** [comment]
Thanks for the report. It looks like this is the same as https://github.com/ionic-team/ionic-framework/issues/25200, so I am going to merge the two.
