### ISSUE TITLE
### Prerequisites

### ISSUE THREAD

**Issue by 5tiaowu** [ionic-team/ionic-framework#27800]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

![image](https://github.com/ionic-team/ionic-framework/assets/108533707/0bb0312f-a5e3-4f07-b246-59cc95ccce05)

### Expected Behavior

The effect displayed on the web terminal is the same as that displayed on the mobile terminal

### Steps to Reproduce

ionic build
ionic capacitor add android

### Ionic Info

没有任何输出

_最初由 @5tiaowu 在 https://github.com/ionic-team/ionic-framework/issues/27792 发布_

**Comment by liamdebeasi** [comment]
Please avoid creating the same issue twice. I see you created a reproduction on https://github.com/ionic-team/ionic-framework/issues/27792#issuecomment-1634216026, but the team needs time to look through the issue. We do a lot of other work in addition to triaging issues, so we may not always reply instantly.
