### ISSUE TITLE
bug: ion-input with type="number" accepts the letter 'e' as a valid input

### ISSUE THREAD

**Issue by sejalshah1107** [ionic-team/ionic-framework#27813]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

ion-input with type="number" accepts the letter 'e' as a valid input one time. all of the following are considered as acceptable inputts

e123
21312e234423

etc.

### Expected Behavior

the letter 'e' should be inadmissible when type="number" is set.

### Steps to Reproduce

1. visit 'https://ionicframework.com/docs/api/input#types'
2. enter the letter 'e' for number Input field

### Ionic Info

Ionic:

Ionic CLI : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 7.0.2
@angular-devkit/build-angular : 15.2.6
@angular-devkit/schematics : 15.2.8
@angular/cli : 15.2.8
@ionic/angular-toolkit : 9.0.0

Capacitor:

Capacitor CLI : 4.7.3
@capacitor/android : not installed
@capacitor/core : 4.7.3
@capacitor/ios : not installed

Utility:

cordova-res : not installed globally
native-run : 1.7.2

System:

NodeJS : v18.16.0 (/home/yg/.nvm/versions/node/v18.16.0/bin/node)
npm : 9.5.1
OS : Linux 5.15

**Comment by sean-perkins** [comment]
@sejalshah1107 this is expected browser behavior.

The same behavior can be observed with an html `input`: https://codepen.io/sean-perkins/pen/JjevPjp

`e` is used for exponential values.
