### ISSUE TITLE
bug:  vue router.replace() no animation

### ISSUE THREAD

**Issue by loremru** [ionic-team/ionic-framework#27834]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

router.replace("/privacy") has no animation

### Expected Behavior

should has ios page transition like router.push("/privacy")

### Steps to Reproduce

git clone https://github.com/loremru/ionic-replace-reproduction

### Code Reproduction URL

https://github.com/loremru/ionic-replace-reproduction

### Ionic Info

Ionic:

   Ionic CLI : 6.20.3

Capacitor:

   Capacitor CLI      : 5.2.1
   @capacitor/android : 5.2.1
   @capacitor/core    : 5.2.1
   @capacitor/ios     : 5.2.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (/Users/loremru/.nvm/versions/node/v18.16.0/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown

### Additional Information

was same for v6.x
useIonRouter() didnt help

**Comment by loremru** [comment]
@liamdebeasi so in my other project on ionic i have same ios page animation on .replace() as i have on .push()
I need this transition to show like we going to another page and also prevent go back (after auth go to app with transition and prevent go back to login with ios swipe) How can I do this?

**Comment by loremru** [comment]
@liamdebeasi 
I tried to reproduce, but it didn't work event with same versions of packages. So I haven't
So can you recommend another way to do it ?
`after auth go to app with transition and prevent go back to login with ios swipe`

**Comment by liamdebeasi** [comment]
I'm not able to fix the issue if I cannot reproduce it first. I recommend starting with the app where the issue reproduces and removing code little by little until you get a minimal sample.
