### ISSUE TITLE
bug: `background-color: black` not removed from body element when closing an inline modal with multiple inline modals with presentingElement in the DOM

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#27830]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When you have multiple inline React `<IonModal>`s with `presentingElement` setup, and then you open and close one, the `background-color: black` isn't being removed from `<body>`.

This can cause weird glitches in page transitions in light mode (iOS) where the pages fade out.

This is because `IonModal` is counting instances found in the DOM > 1 for whether to remove the `background-color: black` style, but not checking if these modals are open or not and whether it's an actual ion-modal being rendered or just the React inline declaration.

### Expected Behavior

`background-color: black` removed from `<body>` when modal closes.

### Steps to Reproduce

A minimum repro can be made by creating a normal `<IonModal presentingElement={p} isOpen={open} />` and a dummy `<IonModal presentingElement={p} isOpen={false} />`. When the modal is closed, the `background-color: black` isn't removed from the `<body>`. This causes some glitchy looking page transitions where the black shows through.

 1. Open https://stackblitz.com/edit/fuftcz
 2. Inspect body element
 3. Open modal, observe `background-color: black` added
 4. Close modal, observe `background-color: black` still there
 5. (optional) delete the dummy `IonModal` (`main.tsx:98`), repeat above, observe `background-color: black` successfully removed after closing

### Code Reproduction URL

https://stackblitz.com/edit/fuftcz

### Ionic Info

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.15.0
   npm    : 9.5.0
   OS     : macOS Unknown
```

### Additional Information

I'm so happy I got to the bottom of this bug, it took forever to figure out why `background-color: black` was being sporadically added to `<body>` and not removed. 😂

A potential fix: target modals that are visible (ignore any `.overlay-hidden`) and the existing logic would then be valid.

<img width="1598" alt="Screenshot 2023-07-19 at 2 41 15 PM" src="https://github.com/ionic-team/ionic-framework/assets/2166114/4fb3cb77-17b5-4ecf-b56d-cf0daf2a2c15">
<img width="1602" alt="Screenshot 2023-07-19 at 2 42 13 PM" src="https://github.com/ionic-team/ionic-framework/assets/2166114/834317c0-80ee-497f-9251-e3229fb16a29">

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27835, and a fix will be available in an upcoming release of Ionic Framework.
