### ISSUE TITLE
bug:  google.maps.places.AutocompleteService().getPlacePredictions in Android

### ISSUE THREAD

**Issue by MarlinaCarvid** [ionic-team/ionic-framework#27844]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

I have a code in which i am able with the input get the autocomplete from google.
The issue occurs in android, is not working -> I have "google is not defined" but is loading the image and more.

This is the code.
  `
    new google.maps.places.AutocompleteService().getPlacePredictions({ input: this.searchTerm },
      (predictions: google.maps.places.AutocompletePrediction[] | null, status: google.maps.places.PlacesServiceStatus) => {
        if (status === google.maps.places.PlacesServiceStatus.OK && predictions) {
          this.searchResults = predictions;
        } else {
          this.presentErrorToast("Autocomplete returned no results or status was not OK.");
        }
      })
    } catch (error) {
      alert(error)
    }`

Please help :(

### Expected Behavior

Show the results as the web version

### Steps to Reproduce

Just create in the constructor even empty  new google.maps.places.AutocompleteService()
Make sure you dont have any error in andoird

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.1.5
   @angular-devkit/schematics    : 16.1.5
   @angular/cli                  : 16.1.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : 5.2.2
   @capacitor/core    : 5.2.2
   @capacitor/ios     : 5.2.2

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.16.0 (C:\Program Files (x86)\nodejs\node.exe)
   npm    : 9.8.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Hey there,

We don't manage the native portion of your application, so this is not the correct place to file this bug report. I recommend posting about this on the [Ionic Forums](https://forum.ionicframework.com/) for help debugging this. Thanks!
