### ISSUE TITLE
feat: Choose order of dates in ion-datetime component with input for wheel style pick

### ISSUE THREAD

**Issue by PatrikHorvatic** [ionic-team/ionic-framework#27840]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hello!

I am proposing new feature for ion-datetime component for wheel stype picking.  What I think is missing is option of sorting values in picker. By default, highest day, month and year values ar displayed at the bottom of the wheel. It would be nice to have option for sorting values with single input.

### Describe the Use Case

Client wants different order of values

### Describe Preferred Solution

(Angular) Prefered solution is adding input to ion-datetime component named:
-> inverse (boolean) -> default false
-> order ('asc' | 'desc') -> default 'asc'

```
<ion-datetime #datetime presentation="date" [preferWheel]="true" [showDefaultButtons]="true" [inverse]="true">
<ion-datetime #datetime presentation="date" [preferWheel]="true" [showDefaultButtons]="true" [order]="'desc'">
```

Same can be manipulated with ViewChild():
```
  @ViewChild('datetime') datetime: IonDatetime;
  this.datetime.inverse = true;
  this.datetime.order = 'desc';
```

**Comment by mapsandapps** [comment]
Hi, thank you for the feature request! You can currently manually sort the order of the wheel segments using the monthValues, dayValues, yearValues, hourValues, and minuteValues properties, e.g.
`<ion-datetime [preferWheel]="true" presentation="month" monthValues="12,11,10,9,8,7,6,5,4,3,2,1"></ion-datetime>`

Does this work for your use case?

**Comment by PatrikHorvatic** [comment]
Hello, thank You for the reply.

I don't find this solution fully convenient. 

Let's say user has to input birth date and must be 18 years or older. In order to reverse all the wheel picker colums I would have to:
-> Add inversed values for days
-> Add inversed values for months
-> Calculate year values which would require next:
-> -> Get today's date and subtract 18 years.
-> -> Create an array of numbers and make it 100 in length.
-> -> Add it to component input

```
  protected maxDate: string;
  protected dayValues: Array<number> = [
    31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
    12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1
  ];
  protected monthValues: Array<number> = [
    12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1
  ];
  protected yearValues: Array<number> = [];

  ngOnInit() {
    let now = new Date();
    now.setFullYear(now.getFullYear() - 18);
    this.maxDate = now.toISOString();
    let maxYear = now.getFullYear();
    const minYear = now.getFullYear() - 100;
    
    while(maxYear >= minYear) {
      this.yearValues.push(maxYear);
      maxYear -= 1;
    }
  }

<ion-datetime
  presentation="date"
  [preferWheel]="true"
  [max]="maxDate"
  [dayValues]="dayValues"
  [monthValues]="monthValues"
  [yearValues]="yearValues"
></ion-datetime>
```

It seems like a lot of work for value order change.


With proposed change, code would look like this:
```
  protected maxDate: string;
  ngOnInit() {
    let now = new Date();
    now.setFullYear(now.getFullYear() - 18);
    this.maxDate = now.toISOString();
  }

<ion-datetime
  presentation="date"
  [preferWheel]="true"
  [max]="maxDate"
  [order]="'desc''"
></ion-datetime>
```

It looks much more simpler.

**Comment by amandaejohnston** [comment]
Can you give more details on the client's use case for this feature?

**Comment by PatrikHorvatic** [comment]
Hello,

client want all date inputs to be inversed wheel style pickers. Required dates are:
->Profile:
-> -> Birth date
-> -> Employment history and date ranges 
-> -> Education and date ranges
-> -> Certificates and date passed

-> Ads
-> -> Ad activity date range
-> -> Chat available date range (min 10 days difference)

**Comment by amandaejohnston** [comment]
If we implemented https://github.com/ionic-team/ionic-framework/issues/26268, would that solve things for them?

If not, could you give details on what specific benefits they had in mind? Alternatively, are there any existing mobile apps that order the wheels this way?
