### ISSUE TITLE
bug: Missing "./types/modules" specifier in swiper package

### ISSUE THREAD

**Issue by mahdi-above** [ionic-team/ionic-framework#27851]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I implemented swiper on my project, just like my old project. When I use Pagination or Navigation or any other modules, it returns this error:

`[plugin:vite:import-analysis] Missing "./types/modules" specifier in "swiper" package
`

### Expected Behavior

It should work like always. 

### Steps to Reproduce

Just use the following code:

```
                  //Why it tries to import from swiper/types? In old project, it was importing from swiper
                   import {Pagination, Navigation} from "swiper/types/modules";
                  <Swiper
                        slidesPerView={4.5}
                        modules={[Navigation, IonicSlides]}
                        pagination={true}
                        onSwiper={(swiper) => setSwiperInstance(swiper)}
                        navigation={{ nextEl: "#swiper-forward", prevEl: "#swiper-back" }}
                    >
                        <SwiperSlide>
                            <CityDetailTab />
                        </SwiperSlide>
                    </Swiper>
```

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\Mahdi\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.2.0

Capacitor:

   Capacitor CLI      : 5.2.1
   @capacitor/android : not installed
   @capacitor/core    : 5.2.1
   native-run  : 1.7.2

System:

   NodeJS : v16.13.2 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.2
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Hey there,

We don't maintain Swiper, so this is not the correct place to file this bug report. I recommend filing this feedback on https://github.com/nolimits4web/swiper instead. Thanks!
