### ISSUE TITLE
feat: on ios device ion-header is fading when page-transitioning

### ISSUE THREAD

**Issue by kosserin** [ionic-team/ionic-framework#27858]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

When navigating back on ios device, ion-header has this fade out effect.
I have read it's because on iOS that's the native behavior, but I would like to know is it possible to get rid only of that effect?

https://github.com/ionic-team/ionic-framework/assets/71221268/09cc938e-c944-42d4-89a7-b89d22f3f007

### Expected Behavior

I was wondering is it possible for header not to have that background with opacity while page transitioning.

Video I provided here is by wrapping ion-header inside ion-content, but that's the behaviour I would like to achieve without wrapping ion-header inside ion-content if possible.

https://github.com/ionic-team/ionic-framework/assets/71221268/78009d07-b494-494d-b863-e8558e472dcd

### Steps to Reproduce

- Use iOS device simulator on the browser
- Navigate from tab1 by clicking blue Continue button on the screen to the payments
- Swipe back and observe

### Code Reproduction URL

https://github.com/kosserin/testing-1098

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/admin/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.2.0
   @angular-devkit/build-angular : 16.1.5
   @angular-devkit/schematics    : 16.1.5
   @angular/cli                  : 16.1.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : not installed
   @capacitor/core    : 5.2.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (/Users/admin/.nvm/versions/node/v18.15.0/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown

### Additional Information

I know it's not a bug, it's just native behaviour of iOS header when page transitioning, but I was desperate to find the solution. Thanks in advance!

**Comment by liamdebeasi** [comment]
Thanks for the report. You can override this behavior by setting `opacity: 1 !important` on the `h1` element in your sample. 

The iOS transition works by fading children inside of `ion-toolbar` by setting `opacity`, so the above steps overrides this behavior: https://github.com/ionic-team/ionic-framework/blob/e9ee96a443d1686def484222b56caf5b8e2dde07/core/src/utils/transition/ios.transition.ts#L391-L394

**Comment by kosserin** [comment]
Thanks for your fast reply Liam!

I'm not sure we mean the same thing. I want header to not have this faded background when navigating back. I guess it's caused by ion-header element because that element alone causes this effect. 
In attachment I provided I think I'm a bit more clear.

Sorry for the confusion.

<img width="450" alt="Screenshot 2023-07-26 at 21 49 34" src="https://github.com/ionic-team/ionic-framework/assets/71221268/b18fec5f-ec4c-4fe9-873a-ae925edf5839">

**Comment by liamdebeasi** [comment]
This behavior is controlled by the iOS transition, so you'd need to provide your own if you wanted to customize how the iOS transition behaves: https://github.com/ionic-team/ionic-framework/blob/main/core/src/utils/transition/ios.transition.ts

**Comment by kosserin** [comment]
Alright, thanks!
