### ISSUE TITLE
bug: ion-infinite-scroll component + virtual list cannot scroll normally

### ISSUE THREAD

**Issue by OrdinarySF** [ionic-team/ionic-framework#27859]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

i tried to follow the tutorial(https://ionicframework.com/docs/vue/virtual-scroll), but its not work. I can't slide down.

### Expected Behavior

I want the list scroll normally.

### Steps to Reproduce

1. same as [guide](https://ionicframework.com/docs/vue/virtual-scroll).
2. code:
```vue
<script lang='ts' setup>
import {
  InfiniteScrollCustomEvent,
  IonButton,
  IonContent,
  IonInfiniteScroll,
  IonInfiniteScrollContent,
  IonItem,
  IonPage,
  IonRefresher,
  IonRefresherContent,
  RefresherCustomEvent,
  useIonRouter
} from '@ionic/vue';
import {chevronDownCircleOutline} from 'ionicons/icons';
import {reactive, ref} from "vue";

const router = useIonRouter();

const items = reactive<string[]>([]);
const loading = ref(false);

const generateItems = () => {
  const count = items.length + 1;
  for (let i = 0; i < 20; i++) {
    items.push(`Item ${count + i}`);
  }
};

const onRefresh = (ev: RefresherCustomEvent) => {
  setTimeout(() => {
    items.length = 0;
    generateItems();
    loading.value = false;
    ev.target.complete();
  }, 1000);
};

const ionInfinite = (ev: InfiniteScrollCustomEvent) => {
  setTimeout(() => {
    generateItems();
    ev.target.complete();
  }, 500);
};

generateItems();

</script>

<template>
  <ion-page>
    <ion-content >
      <ion-refresher slot='fixed' @ionRefresh='onRefresh($event)' :pull-factor='0.5' :pull-min='100' :pull-max='200'>
        <ion-refresher-content :pulling-icon='chevronDownCircleOutline' refreshing-spinner='circles'
                               pulling-text='下拉刷新' refreshing-text='刷新中...'/>
      </ion-refresher>
      <DynamicScroller class='ion-content-scroll-host ion-padding scroller h-full overflow-scroll'
                       :items='items' :min-item-size='54'>
        <template #before>
          Hey! I'm a message displayed before the items!
          <ion-item role='article'>固定内容</ion-item>
        </template>
        <template v-slot='{item,index,active}'>
          <DynamicScrollerItem :item='item' :active='active'
                               :size-dependencies='[ item.message, ]' :data-index='index'>
            <ion-item>
              <ion-button @click="router.push('/product')">前往产品</ion-button>
              <p>{{ item }}+{{ index + 1 }}</p>
            </ion-item>
          </DynamicScrollerItem>
        </template>
      </DynamicScroller>
      <ion-infinite-scroll @ionInfinite='ionInfinite'>
        <ion-infinite-scroll-content loadingSpinner='bubbles' loadingText='正在加载更多数据……'/>
      </ion-infinite-scroll>
    </ion-content>
  </ion-page>
</template>

<style scoped>

</style>
```

### Code Reproduction URL

https://github.com/OrdinarySF/ion-infinite-scroll-component-virtual-list

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - F:\Node\node_global\node_modules\@ionic\cli\lib\project\index.js
       - F:\Node\node_global\node_modules\@ionic\cli\lib\index.js
       - F:\Node\node_global\node_modules\@ionic\cli\index.js
       - F:\Node\node_global\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.1.1 (F:\Node\node_global\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.0.0

Capacitor:

   Capacitor CLI      : 5.1.0
   @capacitor/android : 5.1.0
   @capacitor/core    : 5.1.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.16.1 (D:\Program Files\nodejs\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Can you check your reproduction? The package.json file is referencing a local `capacitor-websocket-client`:

```
 "@ordinary/capacitor-websocket-client": "link:..\\capacitor-websocket-client",
```

I recommend including only the dependencies and code required to reproduce the issue.

**Comment by OrdinarySF** [comment]
> 

Sorry, this is my test demo plugin, I will modify package.json immediately.

**Comment by OrdinarySF** [comment]
I have already pushed the [commit](https://github.com/OrdinarySF/ion-infinite-scroll-component-virtual-list/commit/393e56910fbbf3f9f95cc2b12083ffbd532e5ab3), please take a look at the latest branch.

**Comment by liamdebeasi** [comment]
Thanks for the reproduction. I can reproduce the reported behavior, but this is not a bug in Ionic. Your application is missing the following CSS:

```css
.scroller {
  height: 100%;
}
```

The documentation notes that this CSS is required for the virtual scroll viewport to be sized correctly: https://ionicframework.com/docs/vue/virtual-scroll#usage

Adding the required CSS to your application fixed the issue on my end.

**Comment by liamdebeasi** [comment]
As noted on the docs, these components need to be used within the `.ion-content-scroll-host` element: https://ionicframework.com/docs/vue/virtual-scroll#usage-with-ionic-components

In this case, you will need to render the `ion-infinite-scroll` inside of the the "after" slot provided by `vue-virtual-scroller`.

**Comment by OrdinarySF** [comment]
Problem solved, thank you very much! @liamdebeasi
