### ISSUE TITLE
bug: Modal header gets displayed too high on new iPhone's

### ISSUE THREAD

**Issue by Sigmale1000** [ionic-team/ionic-framework#27860]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When opening a Modal with less than 100% of height the header is displayed too high. The bug seems to be happening only on newer iPhones with the newer status bar. 

**Wrong displays**
iPhone 11 pro: ![IMG_2972](https://github.com/ionic-team/ionic-framework/assets/112062588/ff672ac5-892e-4990-b34d-5b20a88faaeb)

iPhone 12 mini: 
![IMG_2968](https://github.com/ionic-team/ionic-framework/assets/112062588/1690a456-dff5-431b-9206-439bcf117242)

### Expected Behavior

Normally it should display not that high just so that it fits the content (text) on the header. 

**Correct display**
iPhone 6s: ![IMG_2969](https://github.com/ionic-team/ionic-framework/assets/112062588/8724999f-8020-4c7b-81a1-7e1dd637cc30)

### Steps to Reproduce

1. Create a Ionic/Angular component for the modal
2. Create a modal opener on your other component/page where you present the modal from:
```ts
  openUserInfoModal(userId: string) {
    this.modalController
      .create({
        component: UserInfoComponent,
        showBackdrop: true,
        backdropDismiss: true,
        initialBreakpoint: .9,
        handle: false,
        componentProps: {
          event$: this.event$,
          eventSettings$: this.eventSettings$,
          eventId: this.eventId,
          userId,
        },
      })
      .then((modal) => {
        modal.present();
      });
  }
  ```
3. Make sure to add the component (modal) module into the module (page/component where modal gets presented from) imports
4. Set initialBreakpoint to less than 100% (eg. 0.9)
5. Open the modal on a newer iPhone like: iPhone 11, iPhone 12 (bug only confirmed on those phones by me)

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.9 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.5.3
   @angular-devkit/build-angular : 13.3.10
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : 3.6.0
   @capacitor/core    : 3.6.0
   @capacitor/ios     : 3.6.0

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.2) : 1.7.1

System:

   NodeJS : v18.15.0 (/usr/local/bin/node)
   npm    : 9.6.2
   OS     : macOS Unknown

Environment:

   HTTP_PROXY  : http://localhost:3128
   http_proxy  : http://localhost:3128
   HTTPS_PROXY : http://localhost:3128
   https_proxy : http://localhost:3128

**Comment by Sigmale1000** [comment]
I just noticed that the header may be displayed "like a page/component" and keep the same height to cover the space. Because on the "working" iPhone 6s it displays the header the same height it would if it was 100% high.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I can reproduce this behavior, but this is an intentional behavior of Ionic. By default, modals take up the full height of the screen. This causes the header to appear under any safe area (such as a notch or a status bar). To account for this, the `--ion-safe-area-top` CSS variable is applied as padding on the toolbar in the header. If we did not do this, then the title in the toolbar would be partially hidden by the status bar.

In your application you are changing the height of the modal, so the safe area padding is not useful. You can remove the safe area padding by applying the following CSS to the toolbar in your modal:

```css
ion-header ion-toolbar:first-of-type {
  padding-top: 0;
}
```

**Comment by Sigmale1000** [comment]
Thanks for your help @liamdebeasi!
