### ISSUE TITLE
bug: Ion title condensed error positioning on go back

### ISSUE THREAD

**Issue by samuelrebuelta** [ionic-team/ionic-framework#27879]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When navigate from a page with ion title condensed, if go back to this page the title is not in the right position and change to the correct position with lag.

### Expected Behavior

On navigate the title should go up on the correct left/right position.

### Steps to Reproduce

https://github.com/ionic-team/ionic-framework/assets/31918772/aa78a363-a0e8-4ea5-b703-5bbab67bd0a1

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 
   Ionic Framework               : @ionic/angular 7.2.1
   @angular-devkit/build-angular : 16.0.3
   @angular-devkit/schematics    : 16.0.3
   @angular/cli                  : 16.0.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.2.1
   @capacitor/android : 5.2.1
   @capacitor/core    : 5.2.1
   @capacitor/ios     : 5.2.1

Cordova:

   Cordova CLI       : 12.0.0 (cordova-lib@12.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.14.2
   npm    : 8.5.0
   OS     : macOS Unknown
   Xcode  : Xcode 14.3.1 Build version 14E300c

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
