### ISSUE TITLE
bug: ion-item -> item-has-focus not workin in ionicv7

### ISSUE THREAD

**Issue by GusLAN** [ionic-team/ionic-framework#27878]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When we clicked ion-item, and focus is active not have this clases: item-has-focus

<ion-item class="item-interactive item-input item-has-placeholder item ios item-lines-default item-fill-none hydrated item-label">
       

### Expected Behavior

<ion-item class="item-interactive item-input item-has-placeholder item ios item-lines-default item-fill-none hydrated item-label  item-has-focus">

### Steps to Reproduce

In your documentation, if you inspect the ion-item that wraps the ion-input when the ion-input has focus, the item-has focus class appears. But in version 7 of ionic no.
v6 -> https://ionicframework.com/docs/v6/api/item#item-inputs
<img width="887" alt="Captura de pantalla 2023-07-28 a las 12 14 45" src="https://github.com/ionic-team/ionic-framework/assets/890703/04c8295a-f061-4d3d-b19b-6c239fb85cb6">

v7 -> https://ionicframework.com/docs/api/item#item-inputs
<img width="895" alt="Captura de pantalla 2023-07-28 a las 12 16 08" src="https://github.com/ionic-team/ionic-framework/assets/890703/e26a51ab-51a4-4301-8736-29b65810380b">

We use these classes, since we wrap your library.

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/.nvm/versions/node/v18.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.2.1
   @angular-devkit/build-angular : 16.1.5
   @angular-devkit/schematics    : 16.1.5
   @angular/cli                  : 16.1.5
   @ionic/angular-toolkit        : 10.0.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   Android SDK Tools : 26.1.1 (/Users/Library/Android/sdk)
   ios-deploy        : 1.12.1
   ios-sim           : 8.0.2
   NodeJS            : v18.15.0 (/Users/.nvm/versions/node/v18.15.0/bin/node)
   npm               : 6.14.16
   OS                : macOS Unknown
   Xcode             : Xcode 14.2 Build version 14C18

**Comment by phyr0s** [comment]
Same problem here editing styles in V7

**Comment by JacoboSegovia** [comment]
Same here, following for a solution

**Comment by juacuaza** [comment]
Same here!

**Comment by jomarti** [comment]
Same problem. Any solution?
