### ISSUE TITLE
bug: custom page transitions aren't working on history.goBack()

### ISSUE THREAD

**Issue by noskovvkirill** [ionic-team/ionic-framework#27873]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Custom page transition doesn't work for the deeply nested pages
This is video in our app 

https://github.com/ionic-team/ionic-framework/assets/50060130/70e93b9f-c7f9-4e7b-b162-6d25581caced

This is in reproduction

https://github.com/ionic-team/ionic-framework/assets/50060130/601afed9-ba1d-41e2-84e0-666acdc75c35

When user press (X) on Item page we run 

```
history.goBack(itemAnimation)
``` 
It works when we go back and forth to the page, but breaks when we go User Page -> Item Page -> User Page and all the way back. 

### Expected Behavior

Custom transitions should work. 

### Steps to Reproduce

1. Navigate (push) to the Home Page
2. Navigate to other Page (push)
3. Go Back to the previous page with custom transition (history.goBack(customTransition) 
4. Go back to the original page with custom transition  (history.goBack(customTransition) 

### Code Reproduction URL

https://github.com/noskovvkirill/ionic-reproduction-header-issue

### Ionic Info

Ionic:
   Ionic CLI : 7.1.1
  "@ionic/core": "^7.2.1",
  "@ionic/pwa-elements": "^3.2.2",
  "@ionic/react": "7.2.1",
  "@ionic/react-router": "7.2.1",

**Comment by liamdebeasi** [comment]
Thanks for the report. I'm not sure I follow what your application is doing. Your reproduction is using nested routing since there's an `ion-router-outlet` in `AppShell.jsx` and an `ion-router-outlet` in `Tabs.jsx`, but Tabbed navigation isn't actually implemented. If I slow down the animations it looks like two pages are being pushed as once (one outside tabs and one inside):

https://github.com/ionic-team/ionic-framework/assets/2721089/4e4008fd-92e3-462f-b9e3-30ff0b3b20c7

**Comment by noskovvkirill** [comment]
@liamdebeasi Thanks for the quick reply! I cleaned up the example a bit to remove unnecessary code and make it clear what is happening.

**Comment by liamdebeasi** [comment]
Thanks, it looks like we do not pass the custom animation to the navigation method: https://github.com/ionic-team/ionic-framework/blob/a08a5894baa862bab58cd19030682e6853dac1d6/packages/react-router/src/ReactRouter/IonRouter.tsx#L273-L280

Looks like this is the case for Vue too: https://github.com/ionic-team/ionic-framework/blob/a08a5894baa862bab58cd19030682e6853dac1d6/packages/vue-router/src/router.ts#L188-L192

**Comment by liamdebeasi** [comment]
Here is a dev build if you are interested in trying the proposed fix:

```
npm install @ionic/react@7.2.2-dev.11690810887.180000d1 @ionic/react-router@7.2.2-dev.11690810887.180000d1
```

**Comment by noskovvkirill** [comment]
Thanks @liamdebeasi it works as expected!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27895#event-9967385299, and a fix will be available in an upcoming release of Ionic Framework.
