### ISSUE TITLE
bug: ion-select .select-outline-notch

### ISSUE THREAD

**Issue by JustACodeMonkey** [ionic-team/ionic-framework#27875]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using ion-select with fill="outline" and labelPlacement="stacked | floating" and custom CSS that translates the label to a position above the outlined area, there is no way to override the div.select-outline-notch CSS property of border: none; as it is an unreachable shadow DOM element.

Both ion-input and ion-textarea can be overriden pretty easily because they don't use shadow DOM for the .select-outline-notch div.

![image](https://github.com/ionic-team/ionic-framework/assets/10424675/897bf100-f821-4407-879d-01a348814e23)

### Expected Behavior

There should either be ...
- a CSS variable exposed to override border: none on that element,
- a shadow part created on that element so it can be targeted directly,
- or the shadow DOM should be removed to match ion-input and ion-textarea

### Steps to Reproduce

1. Create an ion-select with fill="outline", labelPlacement="stacked", and label with any text inside
2. Add CSS to translate the ::part(label) above the fill outline

### Code Reproduction URL

https://stackblitz.com/edit/angular-ut4aqb

### Ionic Info

Can't run that from within StackBlitz, but here are the dependencies...

![image](https://github.com/ionic-team/ionic-framework/assets/10424675/8f98b764-63ed-4e02-a5fd-0d31b2c6d07a)

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you clarify what you are trying to accomplish with customizing the notch?

**Comment by JustACodeMonkey** [comment]
Our design spec has the stacked label above the outline box (as opposed to within the border like Material standard). Currently the notch is used to show the label within that area. Since our label is above that area, there is a large gap in the border (as shown in the original message and copied again here). Replacing the "border-top: none;" style  with "border-top-width: 1px;" (as we can do with ion-input and ion-textarea) solves the problem. We can't access that style in ion-select because it is hidden by the shadow DOM. Adding a part name to that DIV would allow us to target it and override the style. Or, if the component was modified to not use shadow DOM (like ion-input and ion-textarea), we could simply just override the style.

![image](https://github.com/ionic-team/ionic-framework/assets/10424675/f59351c4-a2fb-4006-bf37-328355bb73ed)

**Comment by amandaejohnston** [comment]
I think the easiest way to accomplish this would be to use a separate element for the label instead. Here's an example: https://stackblitz.com/edit/angular-ut4aqb-thy8qg?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.css Can you confirm whether this would work for your use case?

**Comment by liamdebeasi** [comment]
Also wanted to add that the `outline` fill style is pretty opinionated since it was implemented by following the Material Design spec. You might not want to use it if you need a lot of customization. Another option to consider is using the `label` and `container` shadow parts:

https://codepen.io/liamdebeasi/pen/eYQQgOm

**Comment by JustACodeMonkey** [comment]
> I think the easiest way to accomplish this would be to use a separate element for the label instead. Here's an example: https://stackblitz.com/edit/angular-ut4aqb-thy8qg?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.css Can you confirm whether this would work for your use case?

No, this won't work because it isn't AODA compliant.

> Also wanted to add that the `outline` fill style is pretty opinionated since it was implemented by following the Material Design spec. You might not want to use it if you need a lot of customization. Another option to consider is using the `label` and `container` shadow parts:
> 
> https://codepen.io/liamdebeasi/pen/eYQQgOm

This approach might work if we also implement all of the hover and focus styling that normally comes with Material. I'll look into that more next week.

**Comment by amandaejohnston** [comment]
Glad you were able to find a solution! I'll go ahead and close this out.
