### ISSUE TITLE
feat: Support for making the IonTabs more accessible

### ISSUE THREAD

**Issue by jsanes** [ionic-team/ionic-framework#27874]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Adding support for IonTabBar to be wrapped in another element, to increase accessibility.

### Describe the Use Case

Running cypress-axe, which helps you to identify accessibility issues, I get the "a11y error!region on 7 Nodes" error. This is caused because the IonLables inside the IonTabButtons are not contained inside an HTML landmark:

<img width="647" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/14299291/9ae2f79c-6261-405b-a4e6-448c293af7c8">

**Note:** See the attached code for context.

The problem is: 
- I can't wrap IonTabBar in a `nav` because IonTabs need to have IonTabBar as a direct child.
- I can't wrap the IonTabButtons in a `nav` because they don't get rendered.
- I can't wrap IonTabs in a `nav` because that will cause headers and footers to be inside the `nav`, since each Route renders a page component.
- I can't add `role="navigation"` to the IonTabBar because the IonTabButtons must be placed inside a `tablist` (the IonTabBar acts as a tablist).

### Describe Preferred Solution

Being able to wrap either the IonTabBar or the IonTabButtons inside a `nav` so the app is more accessible.

### Related Code

```
    <IonApp>
      <IonReactRouter>
        <IonTabs>
          <IonRouterOutlet>
            {/*All the routes go here*/}
          </IonRouterOutlet>

          <IonTabBar slot="bottom">
            <IonTabButton tab="home" href="/dashboard">
              <MdOutlineHome className="text-2xl" />
              <StyledLabel>Home</StyledLabel>
            </IonTabButton>
            <IonTabButton tab="find-ce" href="/find-ce">
              <MdOutlineMap className="text-2xl" />
              <StyledLabel>Find CE</StyledLabel>
            </IonTabButton>
            <IonTabButton
              tab="workplaces"
              href="/workplaces/1"
              selected={workplacesSelected}
              data-testid="workplaces-tab"
            >
              <MdBusiness className="text-2xl" />
              <StyledLabel>Workplaces</StyledLabel>
            </IonTabButton>
            <IonTabButton tab="inbox" href="/inbox">
              <MdOutlineMail className="text-2xl" />
              <StyledLabel>Inbox</StyledLabel>
            </IonTabButton>
            <IonTabButton tab="my-learning" href="/my-learning">
              <MdOutlineSchool className="text-2xl" />
              <StyledLabel>Learning</StyledLabel>
            </IonTabButton>
            <IonTabButton tab="my-ce" href="/my-ce">
              <MdBook className="text-2xl" />
              <StyledLabel>My CE</StyledLabel>
            </IonTabButton>
            <IonTabButton tab="my-records" href="/my-records">
              <MdPerson className="text-2xl" />
              <StyledLabel>Me</StyledLabel>
            </IonTabButton>
          </IonTabBar>
        </IonTabs>
      </IonReactRouter>
    </IonApp>
```

**Comment by liamdebeasi** [comment]
Thanks for the report. We have a similar report regarding IonTabButton and IonTabBar in Ionic React, so I am going to merge the two threads: https://github.com/ionic-team/ionic-framework/issues/23088

The goal here is to make it so IonTabs, IonTabBar, and IonTabButton can work with their dependent components as children even if they are not direct children.
