### ISSUE TITLE
bug: Tapping an <IonItem> with a focusable child on Android unexpectedly focuses child and scrolls the page down

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#27888]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

On Android, tapping an `<ion-item>` will focus the first focusable child. This can cause the page to unexpectedly scroll around on large `<ion-item>`s. This only happens on Android.

### Expected Behavior

Child should not receive focus.

### Steps to Reproduce

1. `git clone git@github.com:aeharding/ion-item-focus-issue.git`
2. `yarn`
3. `yarn start`
4. Open page on Android Chrome
5. Tap first Ion Item. Observe button at bottom of item receives focus
6. Additionally, observe page scrolls down to the button receiving focus if the `<button>` is off-screen
7. Finally, observe changing `<IonItem>` to a `<div>` causes the issue to stop

### Code Reproduction URL

https://github.com/aeharding/ion-item-focus-issue

### Ionic Info

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.15.0
   npm    : 9.5.0
   OS     : macOS Unknown
```

### Additional Information

End user bug report: https://github.com/aeharding/voyager/issues/287

Video:

https://github.com/ionic-team/ionic-framework/assets/2166114/11f90d7f-309f-484f-a978-d74d66449f16

**Comment by liamdebeasi** [comment]
This is to be expected. `ion-item` uses a feature called "delegatesFocus". When the item itself is tapped focus will be forwarded to the first focusable element. In this case, this is the button you have defined in `ion-item`.

This feature was added for the legacy form control syntax a few years ago, though we plan to remove it once the legacy form syntax has been removed in an upcoming major release of Ionic. 

We're tracking this in https://github.com/ionic-team/ionic-framework/issues/21982, so I am going to merge the two threads.

**Comment by aeharding** [comment]
@liamdebeasi I see, thanks!

Is there any workaround in the meantime? I've been trying with `tabIndex={-1}` to no avail
