### ISSUE TITLE
feat: Un-Deprecate ion-note for errors (Angular Reactive Forms)

### ISSUE THREAD

**Issue by blargism** [ionic-team/ionic-framework#27890]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Given that Angular Reactive Forms provide an easy API for dealing with forms, but does not simply integrate with the new `errorText` pattern in v7 I recommend allowing the continued use of `<ion-note slot="error">Error Text</ion-note>` and removing that pattern from the deprecation list.

### Describe the Use Case

When using Reactive Forms, a form group and the form builder are effective tools.

```typescript
profileForm = this.fb.group({
    firstName: [''],
    lastName: [''],
    address: this.fb.group({
      street: [''],
      city: [''],
      state: [''],
      zip: ['']
    }),
  });
```

The problem arrises when it comes to validation. Here is the model for validation errors.

```typescript
type ValidationErrors = {
    [key: string]: any;
};
```

Translating that to a single string requires some effort. Furthermore, the documentation for Reactive Forms indicates separate markup per key in the `ValidationErrors` object.

From the Reactive forms documentation:

```html
<input type="text" id="name" class="form-control"
      formControlName="name" required>

<div *ngIf="name.invalid && (name.dirty || name.touched)"
    class="alert alert-danger">

  <div *ngIf="name.errors?.['required']">
    Name is required.
  </div>
  <div *ngIf="name.errors?.['minlength']">
    Name must be at least 4 characters long.
  </div>
  <div *ngIf="name.errors?.['forbiddenName']">
    Name cannot be Bob.
  </div>
</div>
```

### Describe Preferred Solution

Given the above, Angular Reactive Forms works well within the v6 way of dealing with errors.

For example:

```html
<ion-input type="text" id="name" class="form-control"
      formControlName="name" required>

<ion-note *ngIf="name.invalid && (name.dirty || name.touched)" slot="error">

  <span *ngIf="name.errors?.['required']">
    Name is required.
  </span>
  <span *ngIf="name.errors?.['minlength']">
    Name must be at least 4 characters long.
  </span>
  <span *ngIf="name.errors?.['forbiddenName']">
    Name cannot be Bob.
  </span>
</ion-note>
```

This approach allows the user to display one or many potential errors for one field using a standardized approach to managing forms.

### Describe Alternatives

The alternative is to use the v7 way of doing things. Converting an object of key-value pairs can be cumbersome and cause issues with Angular change detection. To manage this, one must add complexity within the component code files, which is often considered an anti-pattern.

In my efforts to implement error text in the v7 way I found I was doing kludgy hacks to make it all work. As we all know, that usually ends badly 😢.

### Related Code

_The code examples should provide sufficient context, but I can add a sample project if required._

### Additional Information

My ask here is that we re-address the decision to deprecate using `ion-note` as a means to display errors. In certain cases, a single string is not enough to fully communicate what is wrong. The approach outlined above provides an "Angular approved" way of dealing with form errors. I think it a good idea to continue to support that.

Thank you for your consideration.

**Comment by liamdebeasi** [comment]
Thanks for the report. The error text feature follows the Material Design spec and was only intended for simple errors (at most 1 error). However, you can still implement that UI you want even though the error slot is going away. 

For example, you can use the preferred solution example, remove `slot="error"`, and add `color="danger"`:

```html
<ion-input type="text" id="name" class="form-control"
      formControlName="name" required></ion-input>

<ion-note *ngIf="name.invalid && (name.dirty || name.touched)" color="danger">

  <span *ngIf="name.errors?.['required']">
    Name is required.
  </span>
  <span *ngIf="name.errors?.['minlength']">
    Name must be at least 4 characters long.
  </span>
  <span *ngIf="name.errors?.['forbiddenName']">
    Name cannot be Bob.
  </span>
</ion-note>
```

**Comment by blargism** [comment]
I might be wrong here, but doesn't that just put the note next to the input? That was what I was finding as I was trying to get this to work. Does the `form-control` class on the input affect that behaviour?

**Comment by liamdebeasi** [comment]
If you are using this in `ion-item` then you can enable text wrapping to get the error on the next line: https://codepen.io/liamdebeasi/pen/YzRddeB

**Comment by blargism** [comment]
Ok, that's fair. I'll take that approach. Last question: do you want me to do a PR to update the documentation giving this as an alternative for Angular folks? If no, feel free to close.

**Comment by liamdebeasi** [comment]
I think it would be good to have an "Advanced" example on https://ionicframework.com/docs/api/input#helper--error-text if you are interested in contributing.

We'd likely want to add a playground so devs have an interactive sample You can generate by running `npm run playground:new` when developing in the [Ionic Docs repo](https://github.com/ionic-team/ionic-docs).

This will add a new playground in `static/usage/v7/input`. From there you can build the interactive demo and add the required code for each JS framework.

I'm going to close this since the original issue is resolved, but let me know if you have questions about updating the docs. Thanks!
