### ISSUE TITLE
bug: RTL not supported

### ISSUE THREAD

**Issue by mhmoudalaskalany** [ionic-team/ionic-framework#27891]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

- arrows are reverted in RTL and not working properly with ar-OM locale or any RTL locale
- when clicking on any day in RTL the month changes to random month

![image](https://github.com/ionic-team/ionic-framework/assets/45127300/ca97000f-1985-492e-a9cd-5ccb0b16b72a)

### Expected Behavior

- arrows should be displayed correctly in RTL
- when clicking on selected date it should be selected without changing the month to random month

### Steps to Reproduce

1.add <ion-datetime presentation="date" display-format="DD/MM/YYYY" pickerFormat="DD MMMM YYYY" [locale]="ar-OM" >
 </ion-datetime>
2- check the calendar the arrows are reverted 
3- click on any day , the month will be changed randomly

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\Mahmoud\AppData\Roaming\nvm\v16.19.0\node_modules\@ionic\cli)        
   Ionic Framework               : @ionic/angular 7.1.2
   @angular-devkit/build-angular : 16.1.4
   @angular-devkit/schematics    : 16.1.4
   @angular/cli                  : 16.1.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : 5.0.5
   @capacitor/core    : 5.1.1
   @capacitor/ios     : 5.1.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.19.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
I'm not able to reproduce this on my end. The arrows render correctly in Chrome 115 and Safari 16:

![image](https://github.com/ionic-team/ionic-framework/assets/2721089/c9e231e0-be6b-42dd-ba33-29a3fbbcbe08)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
