### ISSUE TITLE
bug: innerHTMLTemplatesEnabled config not working

### ISSUE THREAD

**Issue by leocharrua** [ionic-team/ionic-framework#27903]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In app.module.ts:

```
@NgModule({
  declarations: [AppComponent, MenuAccordionComponent],
  imports: [
       BrowserModule,
       ReactiveFormsModule,
       IonicModule.forRoot({
        innerHTMLTemplatesEnabled: true,
        mode: 'ios'        
       }),
```

When I need to show a html message in a Alert Controller:

```
const html = this.config.get('innerHTMLTemplatesEnabled');
const htmlBool = this.config.getBoolean('innerHTMLTemplatesEnabled');
const mode = this.config.get('mode');

console.log('CONFIG ***', mode, html, htmlBool);
```

This is the output in console:

_CONFIG *** ios undefined false_

Then, the html message in the AlertController shows in plain text.

### Expected Behavior

The innerHTMLTemplatesEnabled config must be true, and the html message in the Alert must be interpreted like html.

### Steps to Reproduce

1. Add config in the app.module.ts
2. Check the config value with console.log or similar

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\leoch\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.2.0
   @angular-devkit/build-angular : 16.1.5
   @angular-devkit/schematics    : 16.1.5
   @angular/cli                  : 16.1.5
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : not installed
   @capacitor/core    : 5.2.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.12.1 (C:\Program Files\nodejs\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
