### ISSUE TITLE
feat: How can I perform secondary packaging based on @ionic/core

### ISSUE THREAD

**Issue by unicape** [ionic-team/ionic-framework#27902]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Sorry, I can't find relevant information, I hope to get help

I want to encapsulate my own components based on `@ionic/core`, such as `ion-button`

But I don't know how to inherit it

My idea is that `MyButton` has all the properties of `ion-button` like below and I can extend it

### Describe the Use Case

```jsx
import { Component } from '@stencil/core'
import { Button } from '@ionic/core'

@Component({
  tag: 'my-button'
})
class MyButton extends Button {
  @Prop(): myProp: any
}
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Stencil does not currently support extending other Stencil components, so this is not something you can do currently. You can encapsulate one button inside of another, but that might be more work than it's worth.

If you'd like to see extending components supported in Stencil, I recommend opening a feature request on the Stencil repo: https://github.com/ionic-team/stencil
