### ISSUE TITLE
bug: vendor.js:185182 Error while parsing the 'sandbox' attribute: 'frame-ancestors', ''self'', 'https://sphere.aastrika.org;' are invalid sandbox flags.

### ISSUE THREAD

**Issue by amantarento** [ionic-team/ionic-framework#27914]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v5.x

### Current Behavior

i have iframe which i want to embedded  a html  <iframe #iframeElem title="HTML Content Viewer" i18n-title [src]="iframeUrl"
    (load)="onIframeLoadOrError('load',iframeElem,$event)" (error)="onIframeLoadOrError('error')"
    allow="fullscreen; accelerometer; autoplay; encrypted-media; gyroscope; microphone; camera;"
    class="html-iframe" sandbox="allow-scripts"></iframe> but i am getting the error vendor.js:185182 Error while parsing the 'sandbox' attribute: 'frame-ancestors', ''self'', 'https://sphere.aastrika.org;' are invalid sandbox flags. this one

### Expected Behavior

it should work .

### Steps to Reproduce

i have iframe which i want to embedded  a html  <iframe #iframeElem title="HTML Content Viewer" i18n-title [src]="iframeUrl"
    (load)="onIframeLoadOrError('load',iframeElem,$event)" (error)="onIframeLoadOrError('error')"
    allow="fullscreen; accelerometer; autoplay; encrypted-media; gyroscope; microphone; camera;"
    class="html-iframe" sandbox="allow-scripts"></iframe> but i am getting the error vendor.js:185182 Error while parsing the 'sandbox' attribute: 'frame-ancestors', ''self'', 'https://sphere.aastrika.org;' are invalid sandbox flags. this one

### Ionic Info

Ionic:

   Ionic CLI                     : 6.4.3 (/home/aman/.nvm/versions/node/v14.17.6/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.7.0
   @angular-devkit/build-angular : 0.901.15
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 9.1.15
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : android 10.1.2
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 49 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.2) : 1.7.1

System:

   Android SDK Tools : 26.1.1 (/home/aman/Android/Sdk)
   NodeJS            : v14.17.6 (/home/aman/.nvm/versions/node/v14.17.6/bin/node)
   npm               : 6.14.15
   OS                : Linux 5.14

### Additional Information

i have tried to add meta tag which is not working 
<meta http-equiv="Content-Security-Policy" content="font-src 'self' data:; img-src * data:; default-src * 'unsafe-eval' 'unsafe-inline'; frame-ancestors 'self' https://sphere.aastrika.org;">

**Comment by amantarento** [comment]
@aub  please tell me how to set the csp for iframe

**Comment by aub** [comment]
@amantarento I think you're asking the wrong person.

**Comment by amandaejohnston** [comment]
Thank you for the issue. As mentioned in https://github.com/ionic-team/ionic-framework/issues/27869, we will need a runnable reproduction in order to triage the issue. The repro should also be on the latest version of Ionic, as Ionic 5 is no longer supported. You can view our support table here: https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status

**Comment by amandaejohnston** [comment]
After talking with the team on this, we've agreed that this is more of a support question. I'd recommend asking on the [Ionic forums](https://forum.ionicframework.com/) or [Discord server](https://discord.com/invite/UPYYRhtyzp) for help. Closing this out with that in mind.
