### ISSUE TITLE
bug: ion-item-options added async are not shown

### ISSUE THREAD

**Issue by jongbonga** [ionic-team/ionic-framework#27910]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

**In a list of multiple ion-item-slidings**, when an `ion-item-sliding` with conditioned options is revealed, the item does not slide on the conditioned option side.

### Expected Behavior

The options should be able to respect the conditions when there is more than one ion-item-sliding in a list

### Steps to Reproduce

1. Have a list with 2 or more `ion-item-sliding` with options
2. Trigger a condition from 1 on one of the slider options that will reveal other ion-item-slidings from that list
3. Try to slide the newly revealed ion-item-sliding

### Code Reproduction URL

https://github.com/jongbonga/ion-item-sliding-issue

### Ionic Info

```
Ionic:

   Ionic CLI                     : 6.20.9 
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.1.6
   @angular-devkit/schematics    : 16.1.6
   @angular/cli                  : 16.1.6
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : not installed
   @capacitor/core    : 5.2.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.14.0 
   npm    : 8.3.1
   OS     : macOS Unknown
```

### Additional Information

I'm on the latest ionic v7.2.1

**Comment by liamdebeasi** [comment]
Here is a dev build with a proposed fix if you are interested in testing:

```
npm install @ionic/angular@7.2.2-dev.11690983626.19a2a8cb
```

**Comment by jongbonga** [comment]
> Here is a dev build with a proposed fix if you are interested in testing:
> 
> ```
> npm install @ionic/angular@7.2.2-dev.11690983626.19a2a8cb
> ```

Thank you

**Comment by jongbonga** [comment]
@liamdebeasi looks like it did the trick, working fine. Thank you

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27915, and a fix will be available in an upcoming release of Ionic Framework.
