### ISSUE TITLE
bug: setCurrentBreakpoint on sheet modal does not respect animated property

### ISSUE THREAD

**Issue by rossholdway** [ionic-team/ionic-framework#27923]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When creating a sheet modal and setting the animated property to false, using `setCurrentBreakpoint` still animates the sheet into place.

### Expected Behavior

When setting `animated: false` on a modal, I would have expected it to have disabled all modal animations.

### Steps to Reproduce

1. Click "Open Sheet Modal"
2. Click the search bar

### Code Reproduction URL

https://stackblitz.com/edit/angular-lxewxx?file=src%2Fapp%2Fexample.component.html

### Ionic Info

-

**Comment by liamdebeasi** [comment]
Thanks for the report. Here is a dev build with a proposed fix if you are interested in testing:

```
npm install @ionic/angular@7.2.3-dev.11691069391.1d91d2be
````

Note that you may need to test this in a local project as StackBlitz may not install the dev build dependency correctly.

**Comment by rossholdway** [comment]
@liamdebeasi Thank you for getting this fixed so quickly. Tested and works great.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27924, and a fix will be available in an upcoming release of Ionic Framework.
