### ISSUE TITLE
feat: toast, add shadow part to customize cancel button

### ISSUE THREAD

**Issue by luisbytes** [ionic-team/ionic-framework#27920]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like to independently modify the styles of the button with the role "cancel" without affecting the other buttons of the toasts.

### Describe the Use Case

Display the button with the role "cancel" in a different color than the others or modify its position.

### Describe Preferred Solution

To solve this problem, I would like the buttons with the role "cancel" to have a CSS Shadow Part called "button-cancel."

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/27921, and a fix will be available in an upcoming release of Ionic Framework.
