### ISSUE TITLE
bug: Input counter inside ion-item causes a border line to appear

### ISSUE THREAD

**Issue by RRGT19** [ionic-team/ionic-framework#27939]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

We are migrating from v6 to v7 and our inputs in v6 are like this:

![Screenshot 2023-08-04 at 7 43 05 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/9687095f-1ea7-4222-92ea-98b05805a262)

We have noticed that if the input has the counter property, and the input is under an ion-item, a new border line appears below.

```html
<ion-item>

  <ion-input labelPlacement="floating"
             [label]="label"
             [(ngModel)]="value"
             [minlength]="8"
             [maxlength]="63"
             [counter]="true">
  </ion-input>

</ion-item>
```

![Screenshot 2023-08-04 at 7 39 31 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/3ee25780-a37a-4aab-a9fc-cf696a87c8d7)

We set lines to none to the ion-item: `<ion-item lines="none">`

![Screenshot 2023-08-04 at 7 41 12 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/128eba95-b164-4df8-8f71-068f1a8b0e52)

But now, all our inputs does not have the default border below:

![Screenshot 2023-08-04 at 7 44 49 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/9f409250-4457-4a23-b505-8247f58f9286)

### Expected Behavior

Setting the counter should not add a border below the input.

### Steps to Reproduce

With this code:

```html
<ion-item>

  <ion-input labelPlacement="floating"
             [label]="label"
             [(ngModel)]="value"
             [minlength]="8"
             [maxlength]="63"
             [counter]="true">
  </ion-input>

</ion-item>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/.nvm/versions/node/v16.20.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.2.2
   @angular-devkit/build-angular : 16.1.6
   @angular-devkit/schematics    : 16.1.6
   @angular/cli                  : 16.1.6
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : 5.2.2
   @capacitor/core    : 5.2.2
   @capacitor/ios     : 5.2.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.20.1 (/.nvm/versions/node/v16.20.1/bin/node)
   npm    : 9.8.0
   OS     : macOS Unknown

**Comment by vennilamahalingam** [comment]
I am willing to work on this issue.

**Comment by RRGT19** [comment]
@amandaejohnston yeah, is working. Thanks for the explanation. Inside of the [input counter](https://ionicframework.com/docs/api/input#input-counter) section, there is not a mention about this. I thought that the example shown was not using ion-item because it's an example.

I agree that the docs can be improved on this topic.

Thanks again for all!

**Comment by mapsandapps** [comment]
Hi, we have updated the docs to clarify the usage of an ion-input with a counter: https://ionicframework.com/docs/api/input#input-counter Thanks for reporting this issue!
