### ISSUE TITLE
bug: Invalid onClick event type for IonTabButton in React

### ISSUE THREAD

**Issue by fab1o** [ionic-team/ionic-framework#27949]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Typescript is complaining about the onClick event type of the IonTabButton

```ts
const App: React.FC = () => {
  async function handleTabClick(e: CustomEvent<HTMLIonTabButtonElement>) {
    alert(e.detail.tab);
  }

  return (
    <IonTabButton tab="myTab" onClick={handleTabClick}>
  );
};
```

### Expected Behavior

Expects TypeScript to not complain

### Steps to Reproduce

Create a IonTabButton with ionic fremework v7, react and typescript and implement the onClick event as described above

### Ionic Info

       Require stack:
       - /Users/fabio/.nvm/versions/node/v20.4.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/fabio/.nvm/versions/node/v20.4.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/fabio/.nvm/versions/node/v20.4.0/lib/node_modules/@ionic/cli/index.js
       - /Users/fabio/.nvm/versions/node/v20.4.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.1.1 (/Users/fabio/.nvm/versions/node/v20.4.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.2.2

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : not installed
   @capacitor/core    : 5.2.2
   @capacitor/ios     : 5.2.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v20.4.0 (/Users/fabio/.nvm/versions/node/v20.4.0/bin/node)
   npm    : 9.7.2
   OS     : macOS Unknown

### Additional Information

[Should be a quick fix](https://github.com/ionic-team/ionic-framework/pull/27950)

**Comment by sean-perkins** [comment]
@fab1o thanks for reporting this issue & submitting a pull request for it! I've confirmed this behavior is incorrect, I'll take a look at your pull request next 👍
