### ISSUE TITLE
C:\Program Files\nodejs\node.exe .\app.js

### ISSUE THREAD

**Issue by Vishma98** [ionic-team/ionic-framework#27943]
**Ionic version:**

[x] **4.x**
[ ] **5.x**

**I'm submitting a ...** 

[ ] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** 

```
insert the output from ionic info here
```

**Comment by DimitarDevP** [comment]
This is not how issues work. I suggest you delete this in order to reduce the clutter and give way to actually pressing issues for the developers to sift through.
