### ISSUE TITLE
bug: Input does not support `size` attribute

### ISSUE THREAD

**Issue by clockwiser** [ionic-team/ionic-framework#27945]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior
The ion-input element  is 100% wide and no indication of any changes when adjust the size value.
```
<ion-input
    class="corner"
    type="number"
    v-model="sz"
    :maxlength="1"
    :max="8"
    :min="5"
    :size="50"
    required
   placeholder="?"
   >
</ion-input>
```

### Expected Behavior

The width of ion-input element should be 50 px as explained in the ionic doc site. 

### Steps to Reproduce

1. Create a view in vue framework.
2. In that view put codes similar to the following.

```
<form>
  <ion-list>
      <ion-item>
            <ion-label >
                Number of Letters
              </ion-label>
   
          <ion-input
                class="corner"
                type="number"
                v-model="sz"
                :maxlength="1"
                :max="8"
                :min="5"
                required
                placeholder="?"
              >
          </ion-input>
       </ion-item>
    </ion-list>
  </form>
```

### Ionic Info

> ionic info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - C:\wkvue\ioni\wordict\node_modules\@ionic\cli\lib\project\index.js
       - C:\wkvue\ioni\wordict\node_modules\@ionic\cli\lib\index.js
       - C:\wkvue\ioni\wordict\node_modules\@ionic\cli\index.js
       - C:\wkvue\ioni\wordict\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.1.1
   Ionic Framework : @ionic/vue 7.1.1

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : 5.0.5
   @capacitor/core    : 5.0.5
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.3
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Hello @clockwiser thanks for reporting this issue! 

The `size` attribute is not compatible with `ion-input`. We need to update our auto-generated documentation for this property and remove it in a major release. 

`ion-input` currently does not use the shadow DOM, so you can target the native input directly to override any desired styling: https://stackblitz.com/edit/3c8oty?file=index.html

Input masking or `maxlength` may be a more suitable approach to visually limit the contents of the input, while still allowing it expand the entire container space.
