### ISSUE TITLE
bug: IonPopover sometimes appears at the bottom of the screen instead of the middle of the screen on mobile devices

### ISSUE THREAD

**Issue by DimitarDevP** [ionic-team/ionic-framework#27944]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The popover doesn't always appear in the middle of the screen. From time to time, it will appear almost at the bottom of the screen and this issue seems to be solved by closing the popover, scrolling a bit up / down, and opening the popover again but it doesn't always work, some times I have to do this several times.

### Expected Behavior

The popover should always appear in the middle of the screen unless specifically specified otherwise by the developer.

### Steps to Reproduce

First, Create a ref to `HTMLIonPopoverElement` that defaults to `null`:
`const popover = useRef<HTMLIonPopoverElement>(null);`
Second, create a `state` that stores and controls the `open` status of the popover:
`const [showing, setShowing] = useState<true | false>(false)`
Third, create an IonPopover component that stores some `HTML` inside of it:
```
<IonPopover alignment="center" ref={popover} isOpen={showing} onDidDismiss={() => setShowing(false)}>
  <div className="transition-all transition-200 block md:hidden bg-white p-3 shadow-md rounded-md">
    <h1>Some HTML</h1>
  </div>
</IonPopover>
```

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'
       
       Require stack:
       - /usr/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/lib/node_modules/@ionic/cli/index.js
       - /usr/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.0.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.0.5

Capacitor:

   Capacitor CLI      : 5.0.0
   @capacitor/android : 5.0.0
   @capacitor/core    : 5.0.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v20.4.0 (/usr/bin/node)
   npm    : 9.8.1
   OS     : Linux 6.1

  ───────────────────────────────────────────────

     Ionic CLI update available: 7.0.0 → 7.1.1
         Run npm i -g @ionic/cli to update

  ───────────────────────────────────────────────

### Additional Information

As I mentioned before, this tends to happen on mobile devices, not on desktop. I have tried to reproduce it on `mobile view` within the desktop browser both on `Firefox` and `Chromium` but I could not reproduce it no matter what. I even tried to change `user agent` but no luck.

Notice the difference on the attached screenshots:

Works Properly:
![Screenshot_20230807_154924_Chrome](https://github.com/ionic-team/ionic-framework/assets/46571197/676f3601-cc50-4535-a974-3513e39b127e)

Popover is pushed down:
![Screenshot_20230807_154919_Chrome](https://github.com/ionic-team/ionic-framework/assets/46571197/53068393-9ca0-4ef1-a921-70d28328e3df)

**Comment by DimitarDevP** [comment]
I just asked Chat GPT and it suggested to add a timeout:

`setTimeout(() => setShowing(true), 100)`

which seems to have solved the problem but I think that this should still be looked into as this seems like a workaround not a solution.

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
