### ISSUE TITLE
bug: Ionic 7+ does not properly support `CanMatchFn` guards on Angular 16

### ISSUE THREAD

**Issue by julienfdev** [ionic-team/ionic-framework#27941]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hello !

Currently, it seems that the "canMatch" guards aren't being properly taken into account by Ionic : [CanMatchFn](https://angular.io/api/router/CanMatchFn)

When using vanilla Angular, if, after changing the outcome of the canMatchFns, we trigger a reload on the same route (with `onSameUrlNavigation` set to `reload`), the children are reloaded and the proper page is displayed. 
That is not the case with Ionic.

declaring this routing logic : 

```
const routes: Routes = [
  {
    path: '',
    canMatch: [adminMatch],
    loadChildren: () =>
      import('./admin/admin.module').then((m) => m.AdminPageModule),
  },
  {
    path: '',
    loadChildren: () =>
      import('./user/user.module').then((m) => m.UserPageModule),
  },
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules }),
  ],
  exports: [RouterModule],
})
export class AppRoutingModule {}
```

The component does not change when the result of `adminMatch` changes.
adminMatch is indeed called and the result is as expected : 

```

export function adminMatch() {
  const adminAuthService = inject(AdminAuthService);
  console.log(
    'GUARD HAS TRIGGERED, SHOULD DISPLAY ADMIN PAGE :',
    adminAuthService.loggedIn
  );
  return adminAuthService.loggedIn;
}
```

But the component loaded stays the one that has been loaded initially.
This is not the expected behaviour

### Expected Behavior

The same code without the Ionic Framework, vanilla Angular 16, works as expected : 

as the `AuthAdminService` `loggedIn` boolean changes, the route is reloaded and `loadChildren` yields the expected result : the component changes based on the result of the `CanMatchFn`s

### Steps to Reproduce

1) `ionic start canmatch-bug`, blank template
2) Add two pages, `admin` and `user`, and a service with a boolean the `CanMatchFn` function read
3) Declare the routes appropriately, e.g

```
const routes: Routes = [
  {
    path: '',
    canMatch: [adminMatch],
    loadChildren: () =>
      import('./admin/admin.module').then((m) => m.AdminPageModule),
  },
  {
    path: '',
    loadChildren: () =>
      import('./user/user.module').then((m) => m.UserPageModule),
  },
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules }),
  ],
  exports: [RouterModule],
})
export class AppRoutingModule {}
```

3) the `adminMatch` function should simply return the value of the boolean exposed by the service

4) after changing the boolean value, navigate to `/` using the extra option `onSameUrlNavigation: 'reload'` to force the `canMatch` routine

I've provided a repo with all the steps and a handy "Toggle" : 

### Code Reproduction URL

https://github.com/julienfdev/can-match-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/julien/.nvm/versions/node/v18.12.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.2.2
   @angular-devkit/build-angular : 16.1.8
   @angular-devkit/schematics    : 16.1.8
   @angular/cli                  : 16.1.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : not installed
   @capacitor/core    : 5.2.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.12.1 (/Users/julien/.nvm/versions/node/v18.12.1/bin/node)
   npm    : 9.8.0
   OS     : macOS Unknown

**Comment by sean-perkins** [comment]
Hello @julienfdev thanks for reporting this issue!

Your route configuration with a shared path (`''`) mapping to two different components it not valid with Ionic's routing. Ionic uses stacked navigation patterns to provide mobile routing within a web browser context. To do this, we cache what we call entering and leaving views, so we can "push" and "pop" components and provide experiences like swipe to go back. 

In your scenario, when toggling the state and routing to the same page, Ionic's routing is firing. However, the entering view is being restored from a cache: https://github.com/ionic-team/ionic-framework/blob/main/packages/angular/src/directives/navigation/ion-router-outlet.ts#L241 which means when navigating from `''` as a user, to `''` as an admin, the user entering view is reused. 

Angular does not provide an API mechanic for detecting if the view is activated as the result of a "reload" when routing to the same view. 

I would recommend splitting your route tree to have paths under a `user` namespace and an `admin` namespace.

**Comment by julienfdev** [comment]
Thanks for the head-up, I suspected something like that and that it would be a nightmare to do anything about it.
I indeed namespaced and guarded the routes with more conventional `CanActivateFn` 

Thanks !
