### ISSUE TITLE
feat: swipe down to go back gesture/animation

### ISSUE THREAD

**Issue by drakedeatonuk** [ionic-team/ionic-framework#27953]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Similar to how the current swipe-to-go-back gesture/animation works, it would be useful to be able to set the direction of the swipe from left-to-right, to top-to-bottom.

### Describe the Use Case

Some pages within mobile apps suit being closed from a swipe downwards rather than a swipe sideways.

### Describe Preferred Solution

A property similar to `swipeBackEnabled` API that enables a developer to change the direction. It could be called `swipeBackDirection`.

It would be good to be able to set this programmatically from within a component.

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please clarify your use case? Typically a swipe down gesture is reserved for components like a sheet or card modal.

**Comment by drakedeatonuk** [comment]
Hi @liamdebeasi, thanks for the response! Use case clarified below:

On some views, when a view's content is horizontally scrollable, it's fairly intuitive that when a user has scrolled to the top of the view, and continues trying to scroll upwards, that the view would go back to the previous view.

An example of this can be found in the airbnb app, when clicking on a listing:

https://github.com/ionic-team/ionic-framework/assets/41165256/7f3b8c51-0d92-4e4f-bb3a-c0a6c49606ef

As you can see, the view's content is scrollable, but when the user scrolls to the top of the view, and continues scrolling up, they're returned to the previous view.

---

In terms of why a modal isn't appropriate here - these views may be sufficiently complex, such that it wouldn't be appropriate to use a modal. For example, if you needed to navigate back/forwards to other views _after_ this view, using a modal would be problematic.

**Comment by liamdebeasi** [comment]
The view shown in the AirBnb app is a modal. The particular effect they use looks custom, but the scrolling behavior is found in Ionic's sheet modal. 

>  For example, if you needed to navigate back/forwards to other views after this view, using a modal would be problematic.

I'm not sure I understand this. Modals overlay the entire view, so you can navigate forward/backwards to other views once the modal is closed. Additionally, if you need to navigate within the page, you can use `ion-nav` to push a new view within the modal.

**Comment by drakedeatonuk** [comment]
Gotchya, I'll spend some time getting working with ion-nav as it sounds like this use case can be met with simply ion-modals & ion-navs already 👍 thanks Liam

**Comment by liamdebeasi** [comment]
Sounds good. I am going to close this, but let me know if you have any questions.
