### ISSUE TITLE
bug: Remove lastpass icon from formfield 

### ISSUE THREAD

**Issue by vaibhav65577** [ionic-team/ionic-framework#27954]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

I  am on Ionic version 6.

I install the lastpass manager extension in Chrome.

I want to disable that little three-dot icon on some of the fields throughout the app and website.

Can anyone share the solution to stop showing that icon throughput the app except for some of the fields like login page fields?
![image](https://github.com/ionic-team/ionic-framework/assets/127221096/269a41a2-eac2-4531-a77b-5144d0dbc00e)

### Expected Behavior

I can remove that three dot icon throughout  the app without disable that from chrome extension.

### Steps to Reproduce

1.Install nextpass extension in chrome browser.
2.Add 5 - 6 from field.
3.Some of the field show three dot icon shown like below image.
![image](https://github.com/ionic-team/ionic-framework/assets/127221096/318e0d85-8d45-496b-ab6b-2f51a6e75de0)

### Ionic Info

   Ionic CLI                     : 6.20.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.6
   @angular-devkit/build-angular : 12.2.17
   @angular-devkit/schematics    : 12.2.17
   @angular/cli                  : 12.2.17
   @ionic/angular-toolkit        : 3.0.0

**Comment by liamdebeasi** [comment]
Hey there,

This isn't something that Ionic manages, so it might be best to ask this on the [Ionic Forum](https://forum.ionicframework.com/) instead.
