### ISSUE TITLE
feat: Display a progress indicator in toast messages for time of `duration: number`

### ISSUE THREAD

**Issue by danieljancar** [ionic-team/ionic-framework#27957]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I'm suggesting a useful addition to the Ionic Framework – a progress indicator feature for toast messages. This would provide a visual representation of time passing and the remaining duration of the toast message, until it gets dismissed.

### Describe the Use Case

The main goal of this feature is to offer users real-time feedback on the progress and duration of a toast message. Imagine seeing a little progress bar that fills up as time goes by – this way, you'll always know how much longer the message will be visible before it disappears.

### Describe Preferred Solution

For implementing this, I propose these options for the toast controller:
- `progressIndicator?: boolean;` – This would control whether the progress indicator is shown or not. It would be off by default.
- `progressPosition?: 'top' | 'bottom';` – This lets you decide whether the progress indicator appears at the top or bottom of the toast message.
- `progressAnimation?: 'increasing' | 'decreasing';`- This lets you decide whether the bar should increase or decrease.  

The progress indicator would gradually fill up as the toast message's time progresses, giving you a visual sense of the remaining time.

### Describe Alternatives

-

### Related Code

-

### Additional Information

Similar issues for modernisation of Toasts: 20389, 21769

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you clarify your use case? You noted the following:

> The feature would give users a easier way to realise and see how much longer the message will be displayed, before being dismissed.

By informing users how much time is left, what does that enable them to do?

**Comment by danieljancar** [comment]
You're right, I didn't clarifiy enough. 🙈 I updated the description accordingly...

**Use Case:**
The main goal of this feature is to offer users real-time feedback on the progress and duration of a toast message. Imagine seeing a little progress bar that fills up as time goes by – this way, you'll always know how much longer the message will be visible before it disappears.

**Comment by liamdebeasi** [comment]
Can you give an example of the kinds of messages you are displaying in toasts? For example, are these toasts that require user feedback or are contain critical/very important information?

**Comment by danieljancar** [comment]
Imagine a user performs an action that triggers a toast message to notify them that an item has been deleted. The toast message contains an 'Undo' button, allowing the user to reverse the action within a specific timeframe (duration set on the toast) before the item is removed.

With the proposed progress indicator, the user can see a visual representation of how much time is left before the 'Undo' option expires.

**Comment by danieljancar** [comment]
I've found a good example of how it could look like https://codepen.io/gatoledo1/pen/mdXLReX

**Comment by danieljancar** [comment]
We can find good examples of how it could look like on:

- Mobile Discord version
- Codepen template by catoledo1 [here](https://codepen.io/gatoledo1/pen/mdXLReX)
- Youtube Tutorial by GreatStack [here](https://www.youtube.com/watch?v=mkNITfM1gm8&ab_channel=GreatStack)

In my opinion the progress bar should have a very small height by default, so it doesn't take up a lot of space on the toast.

**Comment by danieljancar** [comment]
Add label

**Comment by danieljancar** [comment]
Hey @liamdebeasi
How is the status of my issue? Thanks.

**Comment by liamdebeasi** [comment]
I spoke with the team, and we do not have plans to add this feature at the moment. The requested behavior is not found in the iOS/MD specs, so we think this is better implemented on a per-app basis.

However, we are interested in making it easier to pass custom HTML to overlays such as `ion-toast`. This would make it easy to pass an `ion-progress-bar` and control the element. You can follow https://github.com/ionic-team/ionic-framework/issues/18067 for updates on that. Thanks!
