### ISSUE TITLE
bug: How to use ion-segment outside of ionic?

### ISSUE THREAD

**Issue by bazuka5801** [ionic-team/ionic-framework#27980]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

![image](https://github.com/ionic-team/ionic-framework/assets/11452353/c374020c-5099-4564-8f97-eb557a3bad62)

### Expected Behavior

![image](https://github.com/ionic-team/ionic-framework/assets/11452353/17783d5c-5d62-431d-8072-ca392a58fbd6)

### Steps to Reproduce

1. View Codesandbox repro

### Code Reproduction URL

https://codesandbox.io/s/affectionate-parm-c5hm2x?file=/src/components/HelloWorld.vue

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/bazuka5801/.asdf/installs/nodejs/18.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.2.3

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : not installed
   @capacitor/core    : 5.2.2
   @capacitor/ios     : 5.2.2

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.14.0 (/Users/bazuka5801/.asdf/installs/nodejs/18.14.0/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

**Comment by NamanAg0502** [comment]
Hey Chandanch,

I solved this issue.

To implement the solution, I've added a new router.js file in the src/ directory. Additionally, I've made some necessary changes to the main.js file.

Here's a brief overview of the changes I've made:

```
// main.js

import { createApp } from "vue";
import { IonicVue } from "@ionic/vue";

import App from "./App.vue";
import router from "./router";

const app = createApp(App).use(IonicVue).use(router);

router.isReady().then(() => {
  app.mount("#app");
});

```

```
 // src/router.js

import { createRouter, createWebHistory } from 'vue-router';
import HomePage from './components/HelloWorld.vue';

const routes = [
  {
    path: '/',
    redirect: '/home',
  },
  {
    path: '/home',
    name: 'Home',
    component: HomePage,
  },
];

const router = createRouter({
  history: createWebHistory(""),
  routes,
});

export default router;
```

With these changes in place, the issue should be resolved, and the application should now perform as intended.

Feel free to review the code changes in the pull request. I'm open to any feedback or suggestions you might have. Let's work together to ensure the quality and effectiveness of this solution.

Thank you,
Naman

**Comment by sean-perkins** [comment]
Hello 👋 support related questions should be posted in the Discord or on the Ionic forums.

**Comment by bazuka5801** [comment]
@sean-perkins If someone (not using the ionic ecosystem) were to encounter the same problem, they would likely first turn to looking for issues on GitHub rather than Discord or the Ionic forums.

**Comment by bazuka5801** [comment]
@sean-perkins I followed all your steps, the md style works by default and I can't change it on iOS.
And the second problem with `use(IonicVue)` it spams a lot of ionic stuff in the root Dom (html element), how to avoid this? 
![image](https://github.com/ionic-team/ionic-framework/assets/11452353/32867a14-ef14-4dda-90e3-845afc33c07f)

**Comment by bazuka5801** [comment]
Update: After enabling the ion segment (without source maps)
I got an increase in packet size by 0.8mb, this is terrible!
![image](https://github.com/ionic-team/ionic-framework/assets/11452353/b07aa116-9a0d-43d3-a632-ba74aed967be)

**Comment by sean-perkins** [comment]
@bazuka5801 the checkbox that you select when submitting an issue asks if you read the contributing guidelines. Which clearly states:

![CleanShot 2023-08-28 at 15 20 13](https://github.com/ionic-team/ionic-framework/assets/13732623/4444191d-b533-44dc-b822-03ac6a86dad1)

As previously stated, please move this question to the other recommended forums if you require support. I am happy to answer those questions there. Bundle size increases are likely a result of using the `dist` output (lazy hydrated web components) vs. the `dist-custom-elements`, which only bundles the components explicitly referenced.
