### ISSUE TITLE
bug: Slowness in date picker selection in ION7

### ISSUE THREAD

**Issue by chandanch** [ionic-team/ionic-framework#27981]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Date picker becomes unresponsive when clicked on it, it takes around 2-3 seconds to render the data picker element in Ionic 7

### Expected Behavior

The date picker must open instantaneously

### Steps to Reproduce

1. Create a date picker element
2. Click on it
3. The lag is seen for the picker to appear

### Ionic Info

onic Framework : @ionic/angular 7.1.2
@angular-devkit/build-angular : 16.1.4
@angular-devkit/schematics : 16.1.4
@angular/cli : 16.1.4
@ionic/angular-toolkit : 9.0.0

Capacitor:

Capacitor CLI : 5.0.5
@capacitor/android : 5.0.5
@capacitor/core : 5.1.1
@capacitor/ios : 5.1.1

Utility:

cordova-res : not installed globally
native-run : 1.7.2

System:

NodeJS : v16.19.0 (C:\Program Files\nodejs\node.exe)
npm : 9.8.1
OS : Windows 10

**Comment by NamanAg0502** [comment]
Hey Chandanch,

I solved this issue.

To implement the solution, I've added a new router.js file in the src/ directory. Additionally, I've made some necessary changes to the main.js file.

Here's a brief overview of the changes I've made:

```
// main.js

import { createApp } from "vue";
import { IonicVue } from "@ionic/vue";

import App from "./App.vue";
import router from "./router";

const app = createApp(App).use(IonicVue).use(router);

router.isReady().then(() => {
  app.mount("#app");
});
```

```
// src/router.js

import { createRouter, createWebHistory } from 'vue-router';
import HomePage from './components/HelloWorld.vue';

const routes = [
  {
    path: '/',
    redirect: '/home',
  },
  {
    path: '/home',
    name: 'Home',
    component: HomePage,
  },
];

const router = createRouter({
  history: createWebHistory(""),
  routes,
});

export default router;
```


With these changes in place, the issue should be resolved, and the application should now perform as intended.

Feel free to review the code changes in the pull request. I'm open to any feedback or suggestions you might have. Let's work together to ensure the quality and effectiveness of this solution.

Thank you,
Naman

**Comment by sean-perkins** [comment]
Hello @chandanch thanks for reporting this issue. 

We will need a lot more information about your environment to triage this issue. Does this happen in a blank application with just the datetime? Which browsers and browser versions are you using?

If possible, can you provide a video recording of the experience? 

Thanks!
