### ISSUE TITLE
bug: Firefox reload the page when issuing a http request subscribe

### ISSUE THREAD

**Issue by heuism** [ionic-team/ionic-framework#27983]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

call the http request (for example in this case: login) and the app just immediately reload (or the page) like you haven't even triggered the button click to send request

### Expected Behavior

call http request subscribe for the return data then will return the data and trigger other part of the code and move forward

### Steps to Reproduce

1. Have directive to call for submit
2. ```
  override onSubmit(formGroup: WrapFormGroup<FormData>) {
    this._state.next('pending');

    const formData = formGroup.value as FormData;

    const req$ = this.onRequest(formData, formGroup);
    req$.pipe(takeUntil(this.destroy$)).subscribe({
      next: (res) => {
        this._state.next('success');
        this._data.next(res);
        this.onSuccess?.(formData, res, formGroup);
      },
      error: (err: unknown) => {
        this._state.next('error');
        if (err instanceof HttpErrorResponse) {
          const errors = this.onMapError?.(formData, err) ?? err.error?.errors;
          this._errors.next(errors);
        }
        this.onError?.(formData, err, formGroup);
      },
    });
  }
```
3. the code didn't pass the subscribe to go to next or error but just reload the page (or the app) in Firefox

### Code Reproduction URL

_No response_

### Ionic Info

Ionic 7.1.1

### Additional Information

Hi guys,

I am running into an issue in Firefox and potentially in Edge.

We are calling subscribe on a HttpRequest that will return data from BE and we use directive for this approach

I have done some debug and in the pipe().subscribe() the code keep waiting and doing some checking then it triggers page reload or something in a similar sense and the page is back to the original state (maybe?)

Video issue on Firefox

https://www.loom.com/share/dcb4ffa0a8164bdb94796a60c074dac6

**Comment by liamdebeasi** [comment]
Hi there,

The `HttpRequest` module is not something that Ionic manages, so it is unlikely that this is an Ionic bug. I recommend posting on the [Ionic Forums](https://forum.ionicframework.com/) for help debugging this.
