### ISSUE TITLE
bug: Autofocus is not working in mobile browser - Version 6

### ISSUE THREAD

**Issue by Blessina-L** [ionic-team/ionic-framework#28015]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Auto Focus is not working on ion-textarea and ion-input in ionic 6

### Expected Behavior

Auto Focus should work on ion-textarea and ion-input in ionic 6

### Steps to Reproduce

Add an ion-input or ion-textarea in template with autofocus = "true", 

### Ionic Info

Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\user\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 6.7.4
   @angular-devkit/build-angular : 16.0.0
   @angular-devkit/schematics    : 16.0.0
   @angular/cli                  : 16.0.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI   : 5.0.1
   @capacitor/core : 5.0.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
