### ISSUE TITLE
bug: IonAlert onDidDismiss and onWillPresent fires twice

### ISSUE THREAD

**Issue by chawes13** [ionic-team/ionic-framework#28010]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The `onDidDismiss` handler fires twice

### Expected Behavior

The `onDidDismiss` handler should fire once

### Steps to Reproduce

1. Add `IonAlert` and `IonButton` from `@ionic/react`
2. Add `buttons` (with or without a defined role)
3. Add a `onDidDismiss` handler
4. Trigger the alert
5. Click on one of the buttons

### Code Reproduction URL

https://stackblitz.com/edit/c6uhzp

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (~/.nvm/versions/node/v19.7.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.2.2

Capacitor:

   Capacitor CLI      : 5.0.5
   @capacitor/android : 5.0.5
   @capacitor/core    : 5.0.5
   @capacitor/ios     : 5.0.5

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v19.7.0 (/~/.nvm/versions/node/v19.7.0/bin/node)
   npm    : 9.5.0
   OS     : macOS Unknown

**Comment by sean-perkins** [comment]
👋 thanks for reporting this issue!

This applies to both `onDidDismiss` and `onWillPresent` due to the changes made here: https://github.com/ionic-team/ionic-framework/commit/c0e1bf92c4487c2ec8a117957cf84a2ce00f5fd8

We will track this as a bug and track accordingly 👍

**Comment by sean-perkins** [comment]
Hello again! 

Can you test with this dev-build and let me know if you experience any unexpected issues?

```
npm install @ionic/react@7.3.1-dev.11692305436.16a4008f
```

**Comment by chawes13** [comment]
Works as expected! 🚀

**Comment by behicsakar** [comment]
> Hello again!
> 
> Can you test with this dev-build and let me know if you experience any unexpected issues?
> 
> ```
> npm install @ionic/react@7.3.1-dev.11692305436.16a4008f
> ```

Works as expected as well! Big thanks
