### ISSUE TITLE
bug: Error in the .ion-valid of an input of a modal with animation, Angular

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#28011]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hello,

When an animated modal controller is opened and you have an ion-input with a formControl a strange green ".ion-valid" bar appears at the top of the input.

It seems that it only happens in webkit, at least in chrome and edge, in firefox it doesn't happen.

https://github.com/ionic-team/ionic-framework/assets/18282247/30e7be07-0945-4648-a9f2-76e4cacbcd97

Greetings!

### Expected Behavior

The green border at the top should not appear.

### Steps to Reproduce

1- Create a modal with modalController and input animation
2- Insert in ion-header -> ion-toolbar -> ion-title -> ion-input with a formControl

### Code Reproduction URL

https://stackblitz.com/edit/angular-gwbd1q?file=src%2Fapp%2Fexample.component.ts

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1
   Ionic Framework               : @ionic/angular 7.3.0
   @angular-devkit/build-angular : 16.2.0
   @angular-devkit/schematics    : 16.2.0
   @angular/cli                  : 16.2.0
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.2.3
   @capacitor/android : 5.2.3
   @capacitor/core    : 5.2.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.17.1
   npm    : 9.6.7
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Looks like this issue has already been reported to the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1341000

You can also avoid this browser bug by using a small starting scale. (i.e. `0.001` instead of `0`).

**Comment by Marius-Romanus** [comment]
Hello, thank you very much for such a quick response.

With a small value like 0.001 it makes a weird flicker at the end.
With will-change it works fine, but I'm concerned about possible memory issues according to MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
But I don't think it's that bad, right?

In any case, I will be attentive to see if they fix the bug in chromium to remove it as soon as possible from the CSS.

**Comment by liamdebeasi** [comment]
> With will-change it works fine, but I'm concerned about possible memory issues according to MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
But I don't think it's that bad, right?

It depends on how many elements you are rendering. `will-change` typically works in browsers by promoting the element into its own layer which can consume additional resources on the device. The `.input-highlight` element is pretty small, so it should not consume many additional resources. If your modal is only going to have a few then the performance impact should be minimal.

I'd recommend removing that code as soon as a fix is available in Chrome.

**Comment by Marius-Romanus** [comment]
Thank you, you can close the problem if you consider it so since it is not an Ionic problem.
