### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by DancingStar** [ionic-team/ionic-framework#28024]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I received an error message 'framework delegate is missing' when using modalController in the react+Ionic project。

### Expected Behavior

I hope that using modalController in the React project can also display modals normally, as I need to develop a common modalService using modalController

### Steps to Reproduce

1.Create a fresh react+Ionic project using @ionic/react@7 and react@18.
2.Use the modalController to create a new modal.
3.Try to present the created modal

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/zp/.nvm/versions/node/v16.20.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.2.3

Capacitor:

   Capacitor CLI      : 3.9.0
   @capacitor/android : 3.9.0
   @capacitor/core    : 3.9.0
   @capacitor/ios     : 3.9.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.20.1 (/Users/zp/.nvm/versions/node/v16.20.1/bin/node)
   npm    : 8.19.4
   OS     : macOS Monterey

**Comment by DancingStar** [comment]
Thank you for your reply. I have seen this section of the document, but useIonModal can only be used at the top level of the function.

And I need to dynamically generate modals based on the content returned by the request. Using useIonModal in this situation will result in an error.

**Comment by liamdebeasi** [comment]
You can use the inline modal for this purpose and conditionally render the inner contents: https://ionicframework.com/docs/api/modal#inline-modals-recommended

**Comment by amandaejohnston** [comment]
Another option is to pass custom state data into the `useIonModal` function. When new data is fetched, it can be updated like any other state, and the modal will update automatically in turn. For example, here is a modified version of the example from the docs which mirrors the dynamic message inside the modal: https://stackblitz.com/edit/6carn4?file=src%2Fmain.tsx

**Comment by DancingStar** [comment]
Thank you for your suggestion. I have tried 'pass custom state data into the useIonModal function'. But I found that when using useIonModal in different components, multiple IonModal nodes may be generated on the dom.

I don't know how to ensure that there is at most one IonModal instance globally when using useIonModal. So I chose inline Modal with mobx to implement global modal services.

Is this plan suitable? It doesn't feel elegant.

Today, I discovered a new issue where the didDismiss hook in ionModal triggers twice, while willDismss is normal and only triggers once

**Comment by liamdebeasi** [comment]
The `didDismiss` hook firing twice is being tracked in https://github.com/ionic-team/ionic-framework/issues/28010. There is a dev build that you can try in: https://github.com/ionic-team/ionic-framework/issues/28010#issuecomment-1682974259

> I don't know how to ensure that there is at most one IonModal instance globally when using useIonModal. So I chose inline Modal with mobx to implement global modal services.

This is the recommended solution for all of our JS Framework integrations, including React. The inline modal ensures that at most one `ion-modal` exists at a time. From there you can swap components out inside the modal as you need. The modalController does not easily expose that same flexibility. I am going to close this since this is the recommended solution, but let me know if you have any questions. Thanks!
