### ISSUE TITLE
feat: Support ion-popover inside of a label 

### ISSUE THREAD

**Issue by SaroGFX** [ionic-team/ionic-framework#28032]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

In our Ionic 6 project I had implemented labels that have an information icon with a popover that can provide additional information about the input. The legacy ion-label 6 this was compatible with ion-popover. But in ionic 7, the label will override the popover event. It would be nice if the popover would still work.

Here is a codepen with both new and old versions, showcasing the issue with the popover: 

https://codepen.io/SaroGFX/pen/jOXEyyR

### Describe the Use Case

For example: 
![Screenshot 2023-08-21 at 10 40 02](https://github.com/ionic-team/ionic-framework/assets/3781800/2dc01e44-cbeb-484a-b4b8-af6f2646f3e4)

### Describe Preferred Solution

Popover still works as label by default.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. Your Ionic 7 demo is creating a nested interactive which is why the behavior is not working as expected. Instead, you should add the `ion-toggle` to the end slot of `ion-item`:

```html
<ion-item>
  <ion-button id="click2">Hover Over Me</ion-button>
  <ion-popover trigger="click2" trigger-action="click">
    <ion-content class="ion-padding">Hello World!</ion-content>
  </ion-popover>
  
  <ion-toggle slot="end"></ion-toggle>
</ion-item>
```

This ensures that both the button and the toggle remain interactive without nesting them.

**Comment by SaroGFX** [comment]
Great, thanks @liamdebeasi
