### ISSUE TITLE
bug: ion-datetime display problem (mixed date and time)

### ISSUE THREAD

**Issue by orengavish** [ionic-team/ionic-framework#28042]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

 on iPhone 13/14 Pro Max 
1. Sometimes,  the datetime (date only)  window is a mix of date and time
2. In addition, sometimes, the datetime window is displayed in the middle of the screen instead of bottom
![datetimebug1](https://github.com/ionic-team/ionic-framework/assets/101519970/c3092cf8-4f1d-4419-a213-a9913ea85945)
![datetimebug2](https://github.com/ionic-team/ionic-framework/assets/101519970/c9e8bb64-2cef-4ca9-8824-b9f63defe919)

### Expected Behavior

1. This window should display date only
2. It is designed for the screen **bottom** only

### Steps to Reproduce

 add ion-date time :
<ion-datetime *ngIf="showPicker" name="reportStartShow" presentation="date" doneText="DONE" cancelText="CANCEL"
    clearText="CLEAR" showClearButton="true" showDefaultButtons="true" size="cover" [min]="minDate" max={{maxDate}}
    value="{{reportTime| date: 'MMM dd, YYYY'}}" (ionCancel)="onCancel()" (ionChange)="clearShow()"
    [(ngModel)]="reportTime">
</ion-datetime>

Run on iPhone 14 many times

### Ionic Info

    "@ionic/angular": "^7.0.0-rc.2",
    "@ionic/core": "^7.0.0-rc.2",

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
