### ISSUE TITLE
bug: Ionic react Modal will not delete HTML <ion-modal> on DOM after close

### ISSUE THREAD

**Issue by jaydenintusurg** [ionic-team/ionic-framework#28052]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v5.x

### Current Behavior

I am using 5.9.4 and IonModal like below.

`  const closeModal = () => {
    setIsModalOpen(false);
  };`

      <IonModal
        isOpen={isModalOpen}
        onDidDismiss={closeModal}
      >
        <div onClick={closeModal}>hello</div>
      </IonModal>

The first time I close the modal, it turns from 
<ion-modal class="ios modal-default hydrated show-modal" id="ion-overlay-1" no-router="" tabindex="-1" style="z-index: 20005;"></ion-modal> 

to 

<ion-modal class="ios modal-default hydrated overlay-hidden" id="ion-overlay-2" no-router="" tabindex="-1" style="z-index: 20007;"><div class="ion-page"></div></ion-modal>.

Then second time when I close it, it close the Modal and show a blank page. Now it has 2 <ion-modal> tags in the DOM. Why it doesn't get deleted after close?

### Expected Behavior

Expecting the <ion-modal> to be removed from DOM everytime it is closed.

### Steps to Reproduce

Copy and paste the code above and use 5.9.4.

### Ionic Info

N/A

**Comment by mapsandapps** [comment]
Hi, thank you for submitting this issue. Could you please confirm if this bug is still occurring in Ionic Framework v7, and if so, please provide [a reproduction](https://ionicframework.com/docs/contributing/how-to-contribute#creating-a-good-code-reproduction)? We are [no longer updating v5](https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status).

**Comment by jaydenintusurg** [comment]
There's another issue with v7. I can't even click to close the modal on v7. Like with code below. I can close with v5 but it has the DOM issue

`<IonModal
      isOpen={isFeedbackModalOpen}
      onDidDismiss={closeModal}
    >
      <div onClick={() => closeModal()}>hello world</div>
    </IonModal>`

**Comment by amandaejohnston** [comment]
Can you also create a separate issue for being unable to click to close in v7? Make sure to include a reproduction there as well. We'll use this issue to focus on the problem from your original post.

**Comment by jaydenintusurg** [comment]
Sure https://github.com/ionic-team/ionic-framework/issues/28055

**Comment by amandaejohnston** [comment]
Thanks! As for this issue, we'll still need a reproduction in the latest version of Ionic, as mentioned in https://github.com/ionic-team/ionic-framework/issues/28052#issuecomment-1690748455.

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
