### ISSUE TITLE
bug: Handling Ionic 6 Capacitor back button though gesture or hardware navigation. 

### ISSUE THREAD

**Issue by NooBitha0** [ionic-team/ionic-framework#28070]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Hello Team

I am using Ionic 6.20.1 and Angular 14.2.10, When I open a modal from component, I wanted to control the back button when hardware back button or hand gesture is used by the user to close the modal to show a confirmation pop-up, but when hardware back button or hand gesture is used, I am directly going to the component from where this modal is call. When user presses a back button in the UI if is working as expected, only this hardware and hand gesture back button is the issue.

### Expected Behavior

While I do hardware back or do back swipe using hand gesture I should stay in the same modal and see a popup asking for confirmation.

### Steps to Reproduce

Create a new component and call it from the app.component.ts as a modal using ModalController package of ionic.  In the constructor initialize Platform and listen to the backButton and call a cancel function which has confirmation dialog box. 
constructor(private platform: Platform) { 
    this.platform.backButton.subscribeWithPriority(10, () => {
      // this is like a backswipe or back button kistener
      console.log("trying to close modal using swipe functionality")
       this.cancel();
     });

  }
At the time of debugging when tried to close the app using hand gestures the control is not even coming to the part of the constructor where cancel() function is called.

### Ionic Info

Ionic:

   Ionic CLI : 6.20.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v19.3.0
   npm    : 9.4.2
   OS     : Windows 10

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
