### ISSUE TITLE
bug: Ion Item onClick doesn't work in popover

### ISSUE THREAD

**Issue by abdulrahman-centroid** [ionic-team/ionic-framework#28097]
### Describe the Bug

Ion Item onClick doesn't work in popuover

### Expected Behavior

Ion Item onClick  should work

### Steps to Reproduce

Ion Item onClick doesn't work

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
