### ISSUE TITLE
bug: Ion-Datetime month name uses different cases in different locales

### ISSUE THREAD

**Issue by FranciskoNeves** [ionic-team/ionic-framework#28095]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

The ion-datetime don't use the Title case in every locale. For example in Spanish and Portuguese it uses lowercase:
<img width="184" alt="Screenshot_1" src="https://github.com/ionic-team/ionic-framework/assets/22598113/e92e250f-f05d-46eb-b88f-49706881bd35">

### Expected Behavior

It's expected that the month Name would be in Titlecase like in English for example:
<img width="184" alt="Screenshot_2" src="https://github.com/ionic-team/ionic-framework/assets/22598113/567b003f-2587-4e87-83e0-c41d99095d06">
 
at least in Portuguese (it's my native language)

### Steps to Reproduce

You can got to Ionic docs to see the examples that I gave: https://ionicframework.com/docs/api/datetime#time-label

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3
   Ionic Framework               : @ionic/angular 6.7.5
   @angular-devkit/build-angular : 14.2.12
   @angular-devkit/schematics    : 14.2.10
   @angular/cli                  : 14.2.10
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 5.1.1
   @capacitor/android : 5.1.1
   @capacitor/core    : 5.1.1
   @capacitor/ios     : 5.1.1

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v16.13.0
   npm               : 9.8.1
   OS                : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. Just so I understand: The datepicker should read "Agosto" with a capital "A" not "agosto" with a lowercase "a"?

**Comment by FranciskoNeves** [comment]
Exactly

**Comment by FranciskoNeves** [comment]
Ok, that's weird... Maybe in the middle of a sentence, but isolated we use the month name Capitalized. Is there a way to edit month names in ion-datetime?

**Comment by liamdebeasi** [comment]
We don't provide a way to edit the month names. Instead, we take the values that the browser gives us. We do have an open feature request for using custom locales not supported by the browser, which may be relevant here: https://github.com/ionic-team/ionic-framework/issues/25568

**Comment by FranciskoNeves** [comment]
Ok, Thanks

**Comment by liamdebeasi** [comment]
I'm going to close this in favor of https://github.com/ionic-team/ionic-framework/issues/25568, but let me know if you have any other questions.
