### ISSUE TITLE
bug: IonModal content doesn't render in some cases

### ISSUE THREAD

**Issue by legendar** [ionic-team/ionic-framework#28102]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When navigating between modals alongside with router changed next modal content is not rendered. 
Additionally `useEffect` unmount callback is not called on when modal is closed.

### Expected Behavior

Modal content should be always rendered correctly. 
`useEffect` unmount callback should be called after modal is dismissed. 

### Steps to Reproduce

It's very hard to reproduce. 
1. Open modal. 
2. Open another modal from the previous one (nested modal)
3. Close both modals, open another modal at the root level and navigate to another router in parallel.
This is a minimal STR that I found. 

In the example repo:
1. On the home tab click "Open root modal"
2. In the root modal click "Open deep modal"
3. Click the red button "Close and go to result" 
4. See a blank modal, but expect to see "modal result" content. Also 'unmount' callback is not called. 
At the same time after clicking on the blue button "Close and go to result" in the root modal the "modal result" content is rendered correctly. 
When clicking on the "CLOSE" button in the "deep" modal then `useEffect` unmount callback is called. 

### Code Reproduction URL

https://github.com/legendar/ion-input-label-issue/

### Ionic Info

$ ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - /home/***/.config/yarn/global/node_modules/@ionic/cli/lib/project/index.js
       - /home/***/.config/yarn/global/node_modules/@ionic/cli/lib/index.js
       - /home/***/.config/yarn/global/node_modules/@ionic/cli/index.js
       - /home/***/.config/yarn/global/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'

       Require stack:
       - /home/***/.config/yarn/global/node_modules/@ionic/cli/lib/project/index.js
       - /home/***/.config/yarn/global/node_modules/@ionic/cli/lib/index.js
       - /home/***/.config/yarn/global/node_modules/@ionic/cli/index.js
       - /home/***/.config/yarn/global/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.1.1 (/home/***/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.3.2

Capacitor:

   Capacitor CLI      : 5.2.1
   @capacitor/android : not installed
   @capacitor/core    : 5.2.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.15.0 (/home/***/.nvm/versions/node/v16.15.0/bin/node)
   npm    : 8.5.5
   OS     : Linux 5.10

### Additional Information

This is a video with an issue: https://www.loom.com/share/ab28492d01ca43ab9357ccd0c843c79e

**Comment by liamdebeasi** [comment]
Thanks for the report. Here is a dev build with a proposed fix if you are interested in testing:

```
npm install @ionic/react@7.3.3-dev.11693592339.18e000af @ionic/react-router@7.3.3-dev.11693592339.18e000af
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28109, and a fix will be available in an upcoming release of Ionic Framework.

**Comment by atomassoni** [comment]
Will this be fixed on Ionic 6 as well?

**Comment by liamdebeasi** [comment]
No, this fix is only applied to Ionic 7. We are not actively developing Ionic 6 anymore.
