### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by hetao1024768** [ionic-team/ionic-framework#28117]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

<ion-datetime-button datetime="datetime" />
<ion-modal :keep-contents-mounted="true">
  <ion-datetime
    id="datetime"
    ref="datetime"
    presentation="date"
    show-default-title
    show-default-buttons
    done-text="Confirm"
    cancel-text="cancel"
    @ion-change="handleChange"
  />
</ion-modal>

<ion-datetime-button datetime="datetime" />
<ion-modal keep-contents-mounted>
  <ion-datetime
    id="datetime"
    ref="datetime"
    presentation="date"
    show-default-title
    show-default-buttons
    done-text="Confirm"
    cancel-text="cancel"
    @ion-change="handleChange"
  />
</ion-modal>

### Expected Behavior

[Ionic Error]: No ion-datetime instance found for ID 'datetime'.

### Steps to Reproduce

<ion-datetime-button datetime="datetime" />
<ion-modal :keep-contents-mounted="true">
  <ion-datetime
    id="datetime"
    ref="datetime"
    presentation="date"
    show-default-title
    show-default-buttons
    done-text="Confirm"
    cancel-text="cancel"
    @ion-change="handleChange"
  />
</ion-modal>

<ion-datetime-button datetime="datetime" />
<ion-modal keep-contents-mounted>
  <ion-datetime
    id="datetime"
    ref="datetime"
    presentation="date"
    show-default-title
    show-default-buttons
    done-text="Confirm"
    cancel-text="cancel"
    @ion-change="handleChange"
  />
</ion-modal>

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1
   Ionic Framework : @ionic/vue 7.3.2

Capacitor:

   Capacitor CLI      : 5.3.0
   @capacitor/android : 5.3.0
   @capacitor/core    : 5.3.0
   @capacitor/ios     : 5.3.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

**Comment by hetao1024768** [comment]
<template>
  
  <ion-datetime-button datetime="datetime" />
  <ion-modal :keep-contents-mounted="true">
    <ion-datetime
      id="datetime"
      ref="datetime"
      presentation="date"
      show-default-title
      show-default-buttons
      done-text="Confirm"
      cancel-text="cancel"
      @ion-change="handleChange"
    />
  </ion-modal>

  
  <ion-datetime-button datetime="datetime" />
  <ion-modal keep-contents-mounted>
    <ion-datetime
      id="datetime"
      ref="datetime"
      presentation="date"
      show-default-title
      show-default-buttons
      done-text="Confirm"
      cancel-text="cancel"
      @ion-change="handleChange"
    />
  </ion-modal>
</template>

**Comment by liamdebeasi** [comment]
Hey there,

There's not much information to go off here. However, that error is thrown when the datetime with the associated ID is not found in the DOM. Note that the datetime associated with your datetime button needs to be in the DOM when the datetime button is in the DOM too.

If you are still running into issue then feel free to open a new thread. However, please fill out the template and include steps to reproduce the issue.
