### ISSUE TITLE
bug: Popover calculation seems to be incorect

### ISSUE THREAD

**Issue by nstekovic** [ionic-team/ionic-framework#28119]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Currently, popover is determined using calculateWindowAdjustment and that relies on document body. This is all fine in theory but I think there might be a cases where we would like to actually exclude some elements from calculation instead of checking for `triggerTop + triggerHeight + contentHeight > bodyHeight` (https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/popover/utils.ts#L865) only. 

Currently, calculations were done only comparing to body height and nothing that could be done here. For example I don't want my popover to overlap footer when opening.

![image](https://github.com/ionic-team/ionic-framework/assets/135704500/2b5394da-8cdc-42cb-9e49-101e79d418ab)

### Expected Behavior

Imagine that we want to take tabs footer into consideration or some sticky element above it. We do have ion-content (main section) above it that is scrollable. In mobile devices, content that opens popover would be very close to the footer or some element that is above footer which we'd like to also take into account when determining whether popover should open towards bottom or top.
We'd like to have behaviour as following "set all popovers side to be 'bottom' but if it would overlap with that element - open it towards top".

### Steps to Reproduce

- Clone github repo that is attached
- npm install 
- npm run start
- Once it runs the browser, toggle mobile view in developer console  and select any mobile device (same behaviour is observed when running ios simulator)
- In tab1 view, scroll down where your button would be near footer
- open popover and observe behaviour
If `triggerTop + triggerHeight + contentHeight > bodyHeight` is actually true - it would open towards top / if not it would open towards bottom.
This doesn't necessarily need to be true if our trigger height is smaller eg (16px and our content is 20px).

### Code Reproduction URL

https://github.com/nstekovic/ionic-popover-issue

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.1.1 (/Users/[user]/.nvm/versions/node/v18.17.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.3.2
   @angular-devkit/build-angular : 16.2.1
   @angular-devkit/schematics    : 16.2.1
   @angular/cli                  : 16.2.1
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.3.0
   @capacitor/android : not installed
   @capacitor/core    : 5.3.0
   @capacitor/ios     : 5.3.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.17.0 (/Users/[user]/.nvm/versions/node/v18.17.0/bin/node)
   npm    : 9.6.7
   OS     : macOS Unknown

```

### Additional Information

Also, what i see as an issue/bug here is that we use `triggerTop` ([link](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/popover/utils.ts#L865)) and we add `triggerHeight` to it. 
`triggerHeight` is already added to `triggerTop` in [triggerTop definition](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/popover/utils.ts#L834). Not sure if this is relevant but something I noticed during debugging.

**Comment by liamdebeasi** [comment]
Thanks for the report. Popovers are designed to overlay your entire application and intentionally do not take specific UI elements into consideration when positioning. 

For comparison, the native context menu on iOS does not do this either:

<img src="https://github.com/ionic-team/ionic-framework/assets/2721089/d1c3b87e-389c-49fb-afba-088cecd0ea4a" width="300" />

Have you tried using the `--offset-y` CSS Variable on `ion-popover` to offset the popover position so it does not cover the element in question?

**Comment by nstekovic** [comment]
Thanks @liamdebeasi  for quick response. This does make a good point that overlay should be globally set and I guess our product will have to remain that way unless we manually do calculation on our end through directive.

--offset-y doesn't help in my use-case scenario, which is fine I guess.

On the other hand, I left my thoughts in "additional information" section up there, where I believe we add triggerHeight twice to the calculation when determining whether popover should be displayed towards bottom or top. Is that intentional?

**Comment by liamdebeasi** [comment]
Hey there! Sorry for the delay in response.

> On the other hand, I left my thoughts in "additional information" section up there, where I believe we add triggerHeight twice to the calculation when determining whether popover should be displayed towards bottom or top. Is that intentional?

Accounting for `triggerHeight` twice does seem to be suspect. We add the trigger height for the first time here: https://github.com/ionic-team/ionic-framework/blob/ac2c8e6c22da4d0d8224def24ddef56ee9d26246/core/src/components/popover/utils.ts#L834

This doesn't seem correct because that would actually get us the bottom coordinate of the trigger. However, this shouldn't be causing problems because we later subtract the `triggerHeight` from `triggerTop`: https://github.com/ionic-team/ionic-framework/blob/ac2c8e6c22da4d0d8224def24ddef56ee9d26246/core/src/components/popover/utils.ts#L877

I'll still get a PR up to remove it because we are doing work that we don't need to do.
