### ISSUE TITLE
bug: Ion-datetime when readonly=true, should able to navigate through calendar

### ISSUE THREAD

**Issue by FranciskoNeves** [ionic-team/ionic-framework#28121]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

 When readonly=true in ion-datetime component, we should be able to navigate between months and years.

### Describe the Use Case

If I'm using ion-datetime not to select dates, but to show multiple selected dates, if one of those dates is in another month, I can't see it.

### Describe Preferred Solution

With readonly=true, the selection of dates should be disabled, but not the navigation of the calendar.

### Describe Alternatives

Another solution would be to add a new property (viewOnlyMode, for example) to the component that disable selection of dates but let the user navigate to other months.

**Comment by mapsandapps** [comment]
Hi, thank you for submitting the bug report. This was fixed & released in version [7.5.3](https://github.com/ionic-team/ionic-framework/releases/tag/v7.5.3) of Ionic Framework.
