### ISSUE TITLE
feat: export TransitionOptions interface

### ISSUE THREAD

**Issue by hoi4** [ionic-team/ionic-framework#28137]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Export the `TransitionOptions` interface and helpful utils like `getIonPageElement` 

### Describe the Use Case

I would like to build my own page transition animation. The type of the `navAnimation` when configuring it via `IonicModule.forRoot({ navAnimation: myPageAnimation })` is `(baseEl: any, opts?: any) => Animation` aka `AnimationBuilder`.
This is unfortunately not type-safe.

### Describe Preferred Solution

I would love to have the same type safety as the default page transitions (e.g. [the one for android](https://github.com/ionic-team/ionic-framework/blob/ec4878ac085d8ff92cb8b2ea0852523f174ab01b/core/src/utils/transition/md.transition.ts)) which use the `TransitionOptions` interface. Furthermore exposing utils like in my case specifically `getIonPageElement` would also be extremely helpful to not have to copy the code into my project.

**Comment by liamdebeasi** [comment]
Thanks for the report. The team is open to exporting both `TransitionOptions` and `getIonPageElement`.

Are you interested in making a PR for this? We'll need to do the following things:

1. Export `TransitionOptions` and `getIonPageElement` in https://github.com/ionic-team/ionic-framework/blob/main/core/src/interface.d.ts.
2. Export `TransitionOptions` and `getIonPageElement` from `@ionic/core` in https://github.com/ionic-team/ionic-framework/blob/4b4ad75bf0b99a669575092cbd9377745048e003/packages/angular/src/index.ts#L132
3. Export `TransitionOptions` and `getIonPageElement` from `@ionic/core` in https://github.com/ionic-team/ionic-framework/blob/4b4ad75bf0b99a669575092cbd9377745048e003/packages/react/src/components/index.ts#L86.
4. Export `TransitionOptions` and `getIonPageElement` from `@ionic/core` in https://github.com/ionic-team/ionic-framework/blob/4b4ad75bf0b99a669575092cbd9377745048e003/packages/vue/src/index.ts#L126.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28140, and a fix will be available in an upcoming release of Ionic Framework.
