### ISSUE TITLE
feat: ModalController subscribe to component Outputs.

### ISSUE THREAD

**Issue by fudom** [ionic-team/ionic-framework#28141]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

```ts
@Component(/*...*/)
class MyComponent {
  @Input() foo?: string;
  @Output() bar = new EventEmitter<string>();
}

this.modalElement = await this.modalController.create({
  component: MyComponent,
  componentProps: { foo }
});
```

### Describe the Use Case

I want to subscribe to the component `Output` events. This is not about `onDidDismiss` result value. Just the counterpart of `componentProps` aka `Input`. For example get triggered inside the service who created the modal when something has changed the component (without dismiss). The component could import the service to call methods, but this results in circular dependency issue. And is not always possible.

### Describe Preferred Solution

We could define another property like `componentProps` (could be renamed to `componentInputs`) and use `componentOutputs` with an object of functions. Which the ModalController subscribes to (and automatically unsubscribe on dismiss.

```ts
this.modalElement = await this.modalController.create({
  component: MyComponent,
  componentInputs: { foo },
  componentOutputs: { bar: (value) => console.log(value) }
});
```

### Describe Alternatives

Or allow to get the component instance after present when it's ready. Then it would be possible to subscribe manually to the property.

```ts
this.modalElement.onPresented().then(componentInstance => {
  componentInstance.bar.subscribe(value => console.log(value));
})

await this.modalElement?.present();
```

### Additional Information

On web I found some similar solutions to get the instance on modal enter/ready. But it seems that this is not possible anymore.

**Comment by sean-perkins** [comment]
@fudom thanks for this feature request!

Have you considered passing through a subject from your calling implementation to the modal? This would allow you to support reactivity between those implementations, without any API modification. 

Example: https://stackblitz.com/edit/angular-txnjwp?file=src%2Fapp%2Fexample.component.ts,src%2Fapp%2Fmodal-example.component.ts,src%2Fapp%2Fmodal-example.component.html

Typing in the modal input will emit events in the parent implementation. 

> [!NOTE]
> In the example a new subscription is created every time the modal is presented. This subscription should be destroyed when you no longer need to listen to it.

**Comment by sean-perkins** [comment]
Hello @fudom,

Thanks for your feature request. After discussing it with the team, we've decided not to proceed with this feature at the moment.

In Ionic Framework, there are a few ways to achieve what you're looking for, such as passing subject instances between components or using callbacks. We recommend using the `data` feature on the modal's dismiss method for a more consistent user experience with existing native experiences with overlays.

While we won't be implementing this feature now, we appreciate your suggestion and value your input. Please feel free to share any other ideas you may have in the future.

Thanks again for your contribution!
