### ISSUE TITLE
bug:  (Angular - Chrome and Edge) Button click event is not registered while content is scrolling

### ISSUE THREAD

**Issue by rvlajcev** [ionic-team/ionic-framework#28154]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Chrome and Edge:
Not sure if this is intended or not,
but list scrolling via fling gesture blocks button click event detection,
instead it causes scrolling to stop.

Scrolling initiated programmatically is not affected.
Issue is not present in Firefox.

```
Chrome version 116.0.5845.180 (Official Build) (64-bit)
Microsoft Edge version 116.0.1938.76 (Official build) (64-bit)
Firefox version 117.0 (64-bit)
```

### Expected Behavior

Button click evet to be registered while list is scrolling via fling gesture.

### Steps to Reproduce

Clone github repo and run it in device mode in Chrome or Edge.
This is slightly modified Ionic built in `list template`.

### Code Reproduction URL

https://github.com/rvlajcev/Ionic_click_event

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\rvlaj\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.3.2
   @angular-devkit/build-angular : 16.2.1
   @angular-devkit/schematics    : 16.2.1
   @angular/cli                  : 16.2.1
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.3.0
   @capacitor/android : not installed
   @capacitor/core    : 5.3.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.12.1 (C:\Program Files\nodejs\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. Typically stopping a scroll does not trigger a click event to prevent accidental clicks. Additionally, Ionic does not handle click detection when scrolling. We register click listeners for several components, but it's up to the browser to determine whether a tap registered as a click. If you think this is a bug in Chrome/WebView then I recommend filing feedback on https://bugs.chromium.org/p/chromium/issues/list.

**Comment by rvlajcev** [comment]
I see, thank you for clarifying.
