### ISSUE TITLE
bug: cdns not works 

### ISSUE THREAD

**Issue by BasemYahia402** [ionic-team/ionic-framework#28150]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

Nightly

### Current Behavior

When opening this website https://ionicframework.com/ and opening the Console tab on dev tools will show cdns do not work
I think that bug is because section Modern UI paradigms. Ready for mobile.
Cdns bugs are :
https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css 
https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js
![2023-09-09 12_15_37-](https://github.com/ionic-team/ionic-framework/assets/123165852/5f2e947b-3be9-4bf3-9904-1b77211fe903)### 

### Expected Behavior

No cdns bugs

### Steps to Reproduce

Just open the page. The Console tab on dev tools will show cdns do not work.

### Ionic Info

The project uses CDN files, so Ionic is not installed on the project.

### Additional Information

the website is the home page

**Comment by sean-perkins** [comment]
Hello @BasemYahia402 thanks for reporting this issue.

There was likely a temporary network outage for the CDN resource. The site examples appear to load correctly now:

![CleanShot 2023-09-11 at 10 40 38@2x](https://github.com/ionic-team/ionic-framework/assets/13732623/51d332aa-5530-45a6-84e7-53ef819bf3f8)

I'm going to close this issue, but please ping me if this occurs again or is not consistent on your end.

Thanks!
