### ISSUE TITLE
bug: upgrade all of your packages to rxjs@7.8.1

### ISSUE THREAD

**Issue by alex5956** [ionic-team/ionic-framework#28155]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

hello,
i've this problem :
`npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @ionic-native/android-permissions@5.36.0
npm ERR! Found: rxjs@7.8.1
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"^7.8.1" from the root project
npm ERR!   rxjs@"7.8.1" from @angular-devkit/architect@0.1602.1
npm ERR!   node_modules/@angular-devkit/architect
npm ERR!     @angular-devkit/architect@"0.1602.1" from @angular-devkit/build-angular@16.2.1
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       @angular-devkit/build-angular@"^16.2.1" from the root project
npm ERR!       1 more (@ionic/cordova-builders)
npm ERR!     @angular-devkit/architect@"0.1602.1" from @angular-devkit/build-webpack@0.1602.1
npm ERR!     node_modules/@angular-devkit/build-webpack
npm ERR!       @angular-devkit/build-webpack@"0.1602.1" from @angular-devkit/build-angular@16.2.1
npm ERR!       node_modules/@angular-devkit/build-angular
npm ERR!         @angular-devkit/build-angular@"^16.2.1" from the root project
npm ERR!         1 more (@ionic/cordova-builders)
npm ERR!     1 more (@angular/cli)
npm ERR!   17 more (@angular-devkit/build-angular, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/android-permissions@5.36.0
npm ERR! node_modules/@ionic-native/android-permissions
npm ERR!   @ionic-native/android-permissions@"^5.36.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: rxjs@6.6.7
npm ERR! node_modules/rxjs
npm ERR!   peer rxjs@"^5.5.0 || ^6.5.0" from @ionic-native/android-permissions@5.36.0
npm ERR!   node_modules/@ionic-native/android-permissions
npm ERR!     @ionic-native/android-permissions@"^5.36.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/alexandre/.npm/_logs/2023-09-11T20_53_25_948Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/alexandre/.npm/_logs/2023-09-11T20_53_25_948Z-debug-0.log

`my package.json is:
`{
  "name": "FacilNdf",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "^16.2.1",
    "@angular-devkit/core": "^16.2.1",
    "@angular-eslint/eslint-plugin": "^16.1.2",
    "@angular/animations": "^16.2.4",
    "@angular/cdk": "^16.2.3",
    "@angular/common": "^16.2.4",
    "@angular/core": "^16.2.4",
    "@angular/forms": "^16.2.4",
    "@angular/platform-browser": "^16.2.4",
    "@angular/platform-browser-dynamic": "^16.2.4",
    "@angular/router": "^16.2.4",
    "@auth0/angular-jwt": "^5.1.2",
    "@awesome-cordova-plugins/calendar": "^6.4.0",
    "@babel/runtime": "^7.22.15",
    "@capacitor-community/http": "^1.4.1",
    "@capacitor/camera": "^5.0.7",
    "@capacitor/core": "^5.3.0",
    "@capacitor/filesystem": "^5.1.3",
    "@capacitor/ios": "5.3.0",
    "@capacitor/preferences": "^5.0.6",
    "@ionic-native/android-permissions": "^5.36.0",
    "@ionic-native/base64-to-gallery": "^5.36.0",
    "@ionic-native/camera": "^5.36.0",
    "@ionic-native/core": "^5.36.0",
    "@ionic-native/ftp": "^5.36.0",
    "@ionic-native/keyboard": "^5.36.0",
    "@ionic-native/native-storage": "^5.36.0",
    "@ionic-native/screen-orientation": "^5.36.0",
    "@ionic/angular": "^7.3.3",
    "@ionic/angular-toolkit": "^10.0.0",
    "@ionic/cordova-builders": "^10.0.0",
    "@ionic/storage-angular": "^4.0.0",
    "@jridgewell/sourcemap-codec": "^1.4.15",
    "@npmcli/fs": "^3.1.0",
    "@types/ssh2": "^1.11.13",
    "@types/ssh2-sftp-client": "^9.0.0",
    "@typescript-eslint/parser": "^6.7.0",
    "angular-calendar": "^0.31.0",
    "crypto-js": "^4.1.1",
    "date-fns": "^2.30.0",
    "ion7-calendar": "^3.6.29",
    "ionic-native-sftp-leapfroggr": "^1.0.1",
    "ionicons": "^7.1.2",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.4",
    "ngx-toastr": "^17.0.2",
    "odometer": "^0.4.8",
    "path-exists": "^5.0.0",
    "rxjs": "^7.8.1",
    "rxjs-compat": "^6.6.7",
    "rxjs-observable": "^0.0.7",
    "serve": "14.2.1",
    "signature_pad": "^4.1.6",
    "sweetalert2": "^11.7.27",
    "swiper": "^10.2.0",
    "ts-md5": "^1.3.1",
    "tslib": "^2.6.2",
    "uuid": "^9.0.0",
    "zone.js": "~0.13.2"
  },
  "description": "application mobile facile",
  "devDependencies": {
    "@angular/cli": "16.2.1",
    "@capacitor/android": "5.3.0",
    "@capacitor/cli": "^5.3.0",
    "@types/node": "^20.6.0",
    "cordova-android": "^12.0.1",
    "cordova-plugin-device": "2.1.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^5.0.1",
    "cordova-plugin-splashscreen": "6.0.2",
    "cordova-plugin-statusbar": "^3.0.0"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
}
`
can you update your packages to rxjs@7.8.1 please ?
Cordially

### Expected Behavior

update packages to :rxjs@7.8.1

### Steps to Reproduce

1. try to change version of rxjs with 6.5.y
2. help with chat gpt 4

### Ionic Info

ionic info

Ionic:

   Ionic CLI                     : 7.1.1 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.3.3
   @angular-devkit/build-angular : 16.2.1
   @angular-devkit/schematics    : 16.2.1
   @angular/cli                  : 16.2.1
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : 5.3.0
   @capacitor/core    : 5.3.0
   @capacitor/ios     : 5.3.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.17.1 (/usr/bin/node)
   npm    : 9.6.7
   OS     : Linux 6.4

**Comment by liamdebeasi** [comment]
Hi there,

Ionic Native is now managed by a community member as `awesome-cordova-plugins` over on https://github.com/danielsogl/awesome-cordova-plugins. See https://ionic.io/blog/a-new-chapter-for-ionic-native for more information on the Ionic Native migration.

There is an open issue on https://github.com/danielsogl/awesome-cordova-plugins/issues/4583, so I recommend working with the maintainer on that thread to get this dependency issue resolved. Thanks!
