### ISSUE TITLE
bug: ion-radio cannot remove line break when using label placement as stacked

### ISSUE THREAD

**Issue by RRGT19** [ionic-team/ionic-framework#28178]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

This issue is related to this one:
https://github.com/ionic-team/ionic-framework/issues/27929

After upgrading to **v7.4.0**, we still cannot achieve the desired UI result for the component.

When using the new `labelPlacement="stacked"`, this is the result:

![Screenshot 2023-09-14 at 2 39 39 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/4cbe2ad6-e344-475f-9e62-500c9a45052e)

The container `part`, or the `mark`, seems to be there even when we assigned **width and height to 0px**. In addition, the label seems to acquire a lower font-size when compared to `labelPlacement="start"`.

When using `labelPlacement="start"`, this is the result (bigger font-size):

![Screenshot 2023-09-14 at 2 42 30 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/41bada6e-4629-4da6-83e6-88a401b82ca7)

So far, we haven't find a way to delete the line break (second line) that `stacked` mode is causing.

### Expected Behavior

Our goal is to have a component like this one:

![258213325-f1ca155d-fc00-4b60-9179-c4c616e3b2ec](https://github.com/ionic-team/ionic-framework/assets/33521443/6479cd06-540e-4ad7-abf0-1fd2d0cd7bc8)

Label in the center, no container/mark part.

### Steps to Reproduce

1. Install v7.4.0
2. Use `labelPlacement="stacked"`
3. Try to delete the container/mark part

### Code Reproduction URL

https://github.com/RRGT19/demo-ion-radio-label-center

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/.nvm/versions/node/v16.20.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.0
   @angular-devkit/build-angular : 16.1.7
   @angular-devkit/schematics    : 16.1.7
   @angular/cli                  : 16.1.7
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.2.2
   @capacitor/android : not installed
   @capacitor/core    : 5.2.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.20.1 (/.nvm/versions/node/v16.20.1/bin/node)
   npm    : 9.8.0
   OS     : macOS Unknown

### Additional Information

Check the CSS [here](https://github.com/RRGT19/demo-ion-radio-label-center/blob/master/src/app/home/home.page.scss#L47).

**Comment by liamdebeasi** [comment]
Thanks for the report. The smaller font size on `labelPlacement="stacked"` is intentional and is designed to match the stacked label layout in other components such as `ion-input` and `ion-textarea`.

The UI you presented looks more like a segmented control than a radio, so I'm a little confused why you are using `ion-radio`. You can achieve the same design using a segmented control: https://codepen.io/liamdebeasi/pen/WNLEwMG

I don't know the intent of the UI, but it looks like you are trying to switch between two modes or views with this. If this is the same, then `ion-segment` is a more appropriate component than `ion-radio`.

**Comment by RRGT19** [comment]
Hi @liamdebeasi thanks for so quick response.

With the examples provided, maybe gives the impression that our intention is to set modes or switch between different views for the UI. In other parts of our application, we have the same style but with more options (ion-radios), for example with 5 and other screens with 11 options.

The options (ion-radios) we have are to configure things about your account/profile or modify filters for searches.

A good example I can show you is with the [Expedia](https://www.expedia.com/Hotel-Search?adults=2&d1=2023-10-13&d2=2023-10-15&destination=Universal%20Studios%20Florida%2C%20Orlando%2C%20Florida%2C%20United%20States%20of%20America&endDate=2023-10-15&latLong=28.47788%2C-81.470642&regionId=6049239&rooms=1&semdtl=&sort=RECOMMENDED&startDate=2023-10-13&theme=&useRewards=true&userIntent=) website. At the left side of the web, they have this component:

![Screenshot 2023-09-14 at 6 04 24 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/cc5cda18-a4f1-4350-a25e-1a75ea838c9e)

Using their mobile app, they have a similar style to what we are trying to achieve.

![IMG_8520](https://github.com/ionic-team/ionic-framework/assets/33521443/314520a7-6a74-4010-8562-c0439c9430c0)

_Using v6 of Ionic, we have the required UI perfectly, the same as the photo we shared above in the "Expected Behavior" section. We done that using `ion-radios`._

Another example is looking at this app: https://ionicthemes.com/templates/ionic6-full-starter-app-elite-version/live-preview

![Screenshot 2023-09-14 at 6 12 16 PM](https://github.com/ionic-team/ionic-framework/assets/33521443/f0d39e51-0e50-4d9b-b927-a2b25f34c05d)

The purpose of all the examples shown above is to configure/customize something about you or your account, not necessarily to change the view in the UI. For this reason, we did it in v6 with `ion-radios`.

It's a little confusing that to achieve that visual look you have to use `ion-segment`. It's not impossible, but mentally for that style, many always turn to use `ion-radios`, like us.

I would like to have the flexibility to give any style to the ion-radio, it allows any visual aspect to be achieved.

Finally, we can change `ion-radius` to `ion-segment` if this is the recommendation to follow.

**Comment by liamdebeasi** [comment]
Thanks for the additional information. I agree, `ion-segment` is not the right solution here. However, I'd probably go with a custom component in this case. Your application is essentially getting rid of all of `ion-radio`'s functionality.

For example, you can get the desired behavior in `ion-radio` here: https://codepen.io/liamdebeasi/pen/poqraPN

But to do so, you need to remove or disable most of the `ion-radio` functionality. The use case here is fairly custom, so I think you'll have better luck with a custom component.
