### ISSUE TITLE
bug: Error when compiling application for Ionic 6.7.5 - Angular 14.2.12 - Capacitor 5.3.0 on Android 5

### ISSUE THREAD

**Issue by FabriJuncal** [ionic-team/ionic-framework#28170]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Hello, I have a problem with Ionic on Android 5
I have developed an application in Ionic 6 where in newer versions of Android they work well, but when testing on devices smaller than Android 9 the app does not work, the screen remains blank and in the console I get the following messages:

```
Uncaught SyntaxError: Unexpected reserved word
(index):19226 The key "viewport-fit" is not recognized and ignored.
2VM33:1 Uncaught TypeError: Cannot read property 'triggerEvent' of undefined
```

### Expected Behavior

I was hoping to compile the app in the emulator and be able to see the blank page of the new Ionic project. Like in browser when` ionic serve` is running
![image](https://github.com/ionic-team/ionic-framework/assets/28323857/78eeadf1-7fad-4a0d-81af-3ebc1fe1c603)

### Steps to Reproduce

To replicate the error I did the following:
1. Create blank ionic project with angular.
`ionic start myAppIonic blank --type=angular`
2. copy and pasted the **_package.json_** file I had in my main project to this test project:
```
{
  "name": "my_app_ionic",
  "version": "1.0.0",
  "author": "Fabricio Juncal",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^14.3.0",
    "@angular/core": "^14.3.0",
    "@angular/forms": "^14.3.0",
    "@angular/platform-browser": "^14.3.0",
    "@angular/platform-browser-dynamic": "^14.3.0",
    "@angular/router": "^14.3.0",
    "@awesome-cordova-plugins/android-permissions": "^6.4.0",
    "@awesome-cordova-plugins/barcode-scanner": "^6.4.0",
    "@awesome-cordova-plugins/call-number": "^6.4.0",
    "@awesome-cordova-plugins/camera": "^6.4.0",
    "@awesome-cordova-plugins/clipboard": "^6.4.0",
    "@awesome-cordova-plugins/core": "^6.4.0",
    "@awesome-cordova-plugins/diagnostic": "^6.4.0",
    "@awesome-cordova-plugins/file": "^6.4.0",
    "@awesome-cordova-plugins/file-path": "^6.4.0",
    "@awesome-cordova-plugins/file-transfer": "^6.4.0",
    "@awesome-cordova-plugins/geolocation": "^6.4.0",
    "@awesome-cordova-plugins/google-analytics": "^6.4.0",
    "@awesome-cordova-plugins/http": "^6.4.0",
    "@awesome-cordova-plugins/in-app-browser": "^6.4.0",
    "@awesome-cordova-plugins/location-accuracy": "^6.4.0",
    "@awesome-cordova-plugins/native-geocoder": "^6.4.0",
    "@awesome-cordova-plugins/network": "^6.4.0",
    "@awesome-cordova-plugins/onesignal": "^6.4.0",
    "@awesome-cordova-plugins/open-native-settings": "^6.4.0",
    "@awesome-cordova-plugins/screen-orientation": "^6.4.0",
    "@awesome-cordova-plugins/splash-screen": "^6.4.0",
    "@awesome-cordova-plugins/sqlite": "^6.4.0",
    "@awesome-cordova-plugins/sqlite-porter": "^6.4.0",
    "@awesome-cordova-plugins/status-bar": "^6.4.0",
    "@awesome-cordova-plugins/wheel-selector": "^6.4.0",
    "@capacitor/android": "5.3.0",
    "@capacitor/app": "^5.0.0",
    "@capacitor/camera": "^5.0.7",
    "@capacitor/core": "^5.0.0",
    "@capacitor/haptics": "^5.0.0",
    "@capacitor/ios": "^5.0.0",
    "@capacitor/keyboard": "^5.0.0",
    "@capacitor/status-bar": "^5.0.0",
    "@ionic-native/market": "^5.36.0",
    "@ionic/angular": "^6.3.7",
    "@ionic/storage-angular": "^3.0.6",
    "call-number": "^1.0.1",
    "cordova-clipboard": "^1.3.0",
    "cordova-open-native-settings": "^1.5.5",
    "cordova-plugin-advanced-http": "^3.3.1",
    "cordova-plugin-android-permissions": "^1.1.5",
    "cordova-plugin-file": "^7.0.0",
    "cordova-plugin-file-transfer": "github:apache/cordova-plugin-file-transfer",
    "cordova-plugin-filepath": "^1.6.0",
    "cordova-plugin-geolocation": "^4.1.0",
    "cordova-plugin-google-analytics": "^1.9.3",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-market": "^1.2.0",
    "cordova-plugin-nativegeocoder": "^3.5.1",
    "cordova-plugin-network-information": "^3.0.0",
    "cordova-plugin-request-location-accuracy": "^2.3.0",
    "cordova-plugin-splashscreen": "^6.0.2",
    "cordova-sqlite-storage": "^6.1.0",
    "cordova-wheel-selector-plugin": "^1.1.7",
    "cordova.plugins.diagnostic": "^7.1.2",
    "jetifier": "^2.0.0",
    "moment": "^2.29.3",
    "ng-circle-progress": "^1.7.1",
    "onesignal-cordova-plugin": "^3.0.1",
    "phonegap-plugin-barcodescanner": "^8.1.0",
    "rxjs": "~6.6.0",
    "tinycolor2": "^1.6.0",
    "tslib": "^2.4.1",
    "uk.co.workingedge.cordova.plugin.sqliteporter": "^1.1.2",
    "zone.js": "~0.11.8"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.12",
    "@angular-eslint/builder": "~13.0.1",
    "@angular-eslint/eslint-plugin": "~13.0.1",
    "@angular-eslint/eslint-plugin-template": "~13.0.1",
    "@angular-eslint/template-parser": "~13.0.1",
    "@angular/cli": "^14.2.12",
    "@angular/compiler": "^14.3.0",
    "@angular/compiler-cli": "^14.3.0",
    "@angular/language-service": "^14.3.0",
    "@capacitor/cli": "^5.3.0",
    "@ionic/angular-toolkit": "^6.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "5.3.0",
    "@typescript-eslint/parser": "5.3.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.8.4"
  },
  "description": "An Ionic project"
}
```

3. I set the ECMAScript version in the `tsconfig.json` file in the `compilerOptions->target` field to **"es2020"**.
4. Clean the project from the bash console:
`rm -rf node_modules && rm package-lock.json && npm cache clean --force`
5. I installed the dependencies, compiled the app and synchronized the app with android, opened the project in android studio:
`npm install && npx jetify && ionic build && ionic cap add android && npx cap sync android && ionic cap open android`
6. When opening the project in android studio I am having a problem with a dependency when creating the project structure, which I solve by going to `File->Project Structure->Dependencies->Modules->app->barcodescanner-release -2.1.5` and change the value of the "**Configuration**" field to "**implementation**". Apply the changes.
7. Then I compile the app with an emulator with the **Pixer device** with **API 22**.

and this way I get the following error message in the Chrome DevKit console:

```
Uncaught SyntaxError: Unexpected reserved word
(index):19226 The key "viewport-fit" is not recognized and ignored.
2VM33:1 Uncaught TypeError: Cannot read property 'triggerEvent' of undefined
```

Error capture:
![image](https://github.com/ionic-team/ionic-framework/assets/28323857/5fcc49de-906b-4a2a-96b3-a6d39bf54968)

### Code Reproduction URL

https://github.com/FabriJuncal/myAppIonic

### Ionic Info

The environment I am working in is the following:

```
Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\Fabricio\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.7.5
   @angular-devkit/build-angular : 14.2.12
   @angular-devkit/schematics    : 14.2.12
   @angular/cli                  : 14.2.12
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 5.3.0
   @capacitor/android : 5.3.0
   @capacitor/core    : 5.3.0
   @capacitor/ios     : 5.3.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.8.1
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
What version of the Chromium webview are you using? You can find this by logging `window.navigator.userAgent` when inspecting the app with Chrome Dev Tools. The errors in the console might indicate you are using an outdated version of the webview.

I'd make sure the device you are testing on is using a supported version of the webview: https://ionicframework.com/docs/reference/browser-support#mobile-browsers

**Comment by FabriJuncal** [comment]
run the command you shared with me and I get the following output:

`Mozilla/5.0 (Linux; Android 5.1.1; Android SDK built for x86_64 Build/LMY48X) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36`

![image](https://github.com/ionic-team/ionic-framework/assets/28323857/75d7abe1-26f7-4ba2-93b2-7af65b3f1212)

**Comment by liamdebeasi** [comment]
We don't support Chromium 39. Ionic 7 expects a minimum of Chromium 79: https://ionicframework.com/docs/reference/browser-support#mobile-browsers

I will note that Android Simulators typically ship with very outdated webviews. I recommend using a physical device for testing instead. However, if you need to use a simulator then I recommend using one that has "Google Play Services" available as the webview can be updated via the Google Play Store on the simulator.

The errors you are seeing are due to your app using features that are not supported in Chromium 39, not Ionic. I am going to close this, but let me know if you have questions.

**Comment by FabriJuncal** [comment]
I no longer have any doubts, I'm going to look for a way to update the Chromium version of the emulator or try it on a physical device. Thank you very much for the help!

**Comment by FabriJuncal** [comment]
Hello, I'm talking about this topic again, since tests have been carried out on a physical device, the device is a Samsung S5 with Android 6.0.1 and Chromium 64 and I have the same problem.

`Mozilla/5.0 (Linux; Android 6.0.1; SM-G900H Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/64.0.3282.123 Mobile Safari/537.36`

![image](https://github.com/ionic-team/ionic-framework/assets/28323857/8f479d30-c406-4f73-8846-09fe00a9dd4a)

![image](https://github.com/ionic-team/ionic-framework/assets/28323857/35ad10fb-4db6-4610-a5c8-efbe7e8145bf)

**Comment by liamdebeasi** [comment]
As I noted in https://github.com/ionic-team/ionic-framework/issues/28170#issuecomment-1719404569, Ionic supports Chromium 79 and newer. You are using Chromium 64 which is an unsupported version.

You can update your browserslist file to potentially get Angular to generate polyfills for the missing applications. However note that your application may be slower as a result. https://angular.io/guide/build#configuring-browser-compatibility

**Comment by FabriJuncal** [comment]
Hello!

In the app I am using ionic 6, as you can see in the package.json file I shared. According to Ionic documentation, Ionic 6 supports up to Android 5+ with Chromium versions +60

**Comment by liamdebeasi** [comment]
That is accurate. However, your project is not configured to target those browsers: https://github.com/FabriJuncal/myAppIonic/blob/15757144ca9b70bc7b9b125b46adf6e436fbb08c/.browserslistrc#L11-L16

The browserslist file helps the Angular CLI ensure compatibility with different browser versions as I linked out to in https://github.com/ionic-team/ionic-framework/issues/28170#issuecomment-1720174118. Your browserslist file currently targets ChromeAndroid and Chrome 79+, so your project never receives the polyfills it needs to work correctly on Chromium 64.

**Comment by FabriJuncal** [comment]
Hello!

I added the configuration you suggested and also added some polyfills, but I still can't get a basic ionic app to work on a physical device running Android 6 and Chromium 64.

I share the link of the modifications I made:

https://github.com/FabriJuncal/myAppIonic/commit/0aa5a5e1bf9fc58e7d74288ae9762ed492e8aa62

**Comment by liamdebeasi** [comment]
What errors are you getting? I don't have a device using Chromium v64 device, so I'm not able to test this.

**Comment by FabriJuncal** [comment]
Comparto capturas de pantalla del error que me sale en la consola.
Normalmente, cuando abres la aplicación, solo muestra una pantalla en blanco.

![image](https://github.com/ionic-team/ionic-framework/assets/28323857/4f1cce4f-668f-4945-965a-e51e311bc716)
![image](https://github.com/ionic-team/ionic-framework/assets/28323857/4644b616-d45c-453b-bd24-420da3968a35)

**Comment by liamdebeasi** [comment]
There are either syntax errors or other polyfills that you are missing. This is more of a project configuration question than an Ionic bug, but my recommendation would be to see what parts of the code the browser is throwing errors on and proceed from there. There could be some additional feature that the polyfills aren't accounting for.

**Comment by LennonReid** [comment]
I had the same issue on Android 9 with Webview 64, similar to the one discussed in this forum thread: https://forum.ionicframework.com/t/support-android-8-9-in-ionic-7-and-angular-16/236150.

**Comment by LennonReid** [comment]
<img width="1249" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/43192276/beaf415a-9c03-4b14-b912-94365d5ccd78">

**Comment by LennonReid** [comment]
<img width="1375" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/43192276/74467e8a-c4d0-44f6-b973-5b0c0f61bc35">

I encountered this error in a different application while working in the development environment with the following versions:
Capacitor: v5
Ionic: v7
Angular: v16

**Comment by LennonReid** [comment]
The issue regarding the 'globalThis' error has been successfully resolved through the insightful discussion found at the following link: https://github.com/ionic-team/capacitor/discussions/3871. 
However, there is one more thing to note. <img width="1027" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/43192276/b9920a99-048e-45f5-9249-df0f1fea0ea3">

**Comment by LennonReid** [comment]
> https://github.com/FabriJuncal/myAppIonic/blob/15757144ca9b70bc7b9b125b46adf6e436fbb08c/.browserslistrc#L11-L16
I successfully resolved the syntax error by incorporating the following entries into my .browserslistrc file.
`Chrome >=60
ChromeAndroid >=60
Firefox >=63
Firefox ESR
Edge >=79
Safari >=13
iOS >=13
` I have decided not to make any more comments, as the initial issue I encountered has been successfully resolved. If I encounter any further issues, I will open a new one. I hope that my previous comments prove to be helpful.

**Comment by LennonReid** [comment]
> I share screenshots of the error that I get in the console. Normally, when you open the app, it just shows a blank screen.
> 
> ![image](https://user-images.githubusercontent.com/28323857/268676880-4f1cce4f-668f-4945-965a-e51e311bc716.png) ![image](https://user-images.githubusercontent.com/28323857/268676943-4644b616-d45c-453b-bd24-420da3968a35.png)

I successfully resolved the syntax error by incorporating the following entries into my .browserslistrc file.
```ts
Chrome >=60
ChromeAndroid >=60
Firefox >=63
Firefox ESR
Edge >=79
Safari >=13
iOS >=13
````

 I have decided not to make any more comments, as the initial issue I encountered has been successfully resolved. If I encounter any further issues, I will open a new one. I hope that my previous comments prove to be helpful.
