### ISSUE TITLE
bug: Ionic React lifecycle hooks should execute cleanup function when unmounted 

### ISSUE THREAD

**Issue by rabianr** [ionic-team/ionic-framework#28186]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Like ```useEffect``` hook, ```useIonViewWillEnter``` and ```useIonViewDidEnter``` hook should also support cleanup function.

### Describe the Use Case

In React 18, ```useIonViewWillEnter``` and ```useIonViewDidEnter``` run twice in development. Which makes any fetch requests run twice too.
If I make a fetch request in ```useEffect```, I can pass an abort signal to the request and abort it in the cleanup function.
I tried to do the same in ```useIonViewWillEnter``` hook, but the cleanup function isn't supported, so there's no way to abort the request.

I also tried to use the ```useIonViewWillLeave``` hook, but this hook won't get fired until you navigate to another page.

**Code Reproduction**
https://stackblitz.com/edit/qhjlkw

**Comment by sean-perkins** [comment]
Hello, thanks for reporting this issue!

Can you test with this dev-build and let me know if you experience any unexpected behaviors?

```
npm install @ionic/react@7.4.4-dev.11696895407.1bd7a380 @ionic/react-router@7.4.4-dev.11696895407.1bd7a380
```

**Comment by rabianr** [comment]
> Hello, thanks for reporting this issue!
> 
> Can you test with this dev-build and let me know if you experience any unexpected behaviors?
> 
> ```
> npm install @ionic/react@7.4.4-dev.11696895407.1bd7a380 @ionic/react-router@7.4.4-dev.11696895407.1bd7a380
> ```

Hi, I can confirm that with that dev-build, the cleanup function get executed properly in my production project. Also, there is no unexpected behaviors so far.
Code Reproduction: https://stackblitz.com/edit/qhjlkw-4aknkp?file=package.json,src%2Fmain.tsx
Thank you for your support.

**Comment by sean-perkins** [comment]
@rabianr thanks for testing! I'll get a PR open shortly for the changes. 

I have an updated dev-build if you want to continue testing with it: 
```
7.4.4-dev.11696956070.1faa3cfe
```

I realized that I did not need to call the lifecycle callback on the initial mount/unmount of the `useEffect`, so that will cut done on memory consumption while in dev mode.
