### ISSUE TITLE
feat: Qwik framework support

### ISSUE THREAD

**Issue by LazyClicks** [ionic-team/ionic-framework#28185]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

i've found that someone else has already created an [issue](https://github.com/ionic-team/ionic-framework/issues/27418) requesting the feature request for the qwik support but he they haven't explained why nor what benefit would supporting qwik provide anyways so hopefully ill be able to get some attention to it again 

### Describe the Use Case

so what qwik brings to the table is it's new method of rendering called resumeability, unlike other frameworks that rely on hydration where the app is rendered twice, once on the server and once on the client, qwik renders the app once on the server and the app simply resumes on the client, but i imagine apps wont benefit much from this due to them being downloaded fully?
well another major point that i think devs would love is automatic lazy execution and lazy loading, i imagine startup performance would be a lot better and the performance hit on larger apps to be almost none due to qwik innate way of handling lazy execution of code only on demand, so that so not all the code is executed right away, instead the service worker which is smart enough to guess which Ui element is more likely to get used more and therefore priorities it when prefetching it and also the lazy loading of such code, that is the code is only executed when the user needs it, and the best part is that this is automatically done for the developer and doesn't need any extra work which is a huge DX improvement i would say from what I've experienced first hand, I've yet to test it but i imagine web view 2 apps on android would get a decent performance boost that they need.

**Comment by liamdebeasi** [comment]
Hey there,

We appreciate the feature request, but the last request was closed only a month ago: https://github.com/ionic-team/ionic-framework/issues/27418#issuecomment-1679200624

There was not a lot of support from the Ionic community at the time, and I don't see that significantly changing over the course of a month.

------

If developers are actively running into issues with building mobile apps that Qwik could solve, we'd love to hear more about it. Some of the features noted like lazy loading are valuable, but they are also available in our other supported frameworks such as Angular and Vue.

I am going to close this, but let me know if you have any questions.

**Comment by LazyClicks** [comment]
the main point of the lazy loading and lazy execution is that its done automatically, thats the big difference
as i said with qwik u only need to add a $ to a component for it to be lazy loaded 
there's also another point, qwik does create a tree with the components but insteads creates a hashmap with all components, when a component changes not all the parents need to rerender
but again the main point for why qwik would be useful is the DX, the developer doesnt need to be the one to deal with making the app fast, the framework deals with that for him

**Comment by liamdebeasi** [comment]
> the main point for why qwik would be useful is the DX, the developer doesnt need to be the one to deal with making the app fast, the framework deals with that for him

That's not how Qwik works. Qwik brings several tools that help with performance (such as [Partytown](https://qwik.builder.io/docs/integrations/partytown/)), but it's still up to the developer to write performant code. The tools that Qwik provide are designed to target specific performance issues. For example, Partytown targets 3rd party scripts causing your initial page load to slow down. Using Qwik is not going to remove all the performance issues in an application.

One thing to note is that Ionic components are Web Components, meaning they can run on any modern web platform. You should be able to use Ionic components in Qwik today, though you may not get some of the SSR benefits.

As I noted above, we'd be interested in hearing about problems developers are actively running into and how Qwik can help (i.e. problems developers are having right now. Runnable code samples help.).

**Comment by LazyClicks** [comment]
partytown is separate from qwik
idk why u think qwik doesnt do that, i can go confirm with misko (one of qwik core team) that qwik does do that

**Comment by LazyClicks** [comment]
you can also very easily test that qwik does automatically lazy load and lazy executes code, just create a qwik app, run it and check the network tab, even in development, the only scripts that get downloaded and executed is the vite and service worker, and in production vite will not get shipped
like i said with qwik lazy loading is as easy as adding a $

**Comment by thejackshelton** [comment]
> That's not how Qwik works. Qwik brings several tools that help with performance (such as [Partytown](https://qwik.builder.io/docs/integrations/partytown/)), but it's still up to the developer to write performant code. For example, Partytown targets 3rd party scripts causing your initial page load to slow down.

Partytown is a separate project. What it does is trick the service worker into thinking it's synchronous / blocking and running your 3rd party scripts on a web worker. The problem before partytown was that service workers were notoriously asynchronous.

> The tools that Qwik provide are designed to target specific performance issues.

Qwik apps prefetch everything in a service worker in a separate thread. Then they lazily execute on interaction. This is resumability. There are many other optimizations such as automatic bundle optimization, lazy loading, signals, etc. 

More on resumability here:
https://www.builder.io/blog/hydration-tree-resumability-map#resumability-is-fundamentally-a-different-algorithm

Qwik's goal is to make it very easy to fall into the pit of performance success. Most of the time you are building your app and the framework is doing the heavy lifting.

> Using Qwik is not going to remove all the performance issues in an application.

While of course you can make anything slow if you try hard enough haha, I think you could say the same with DOM manipulation in React. It may not remove all the DOM manipulation you need to do, but it sure does help.

In the context of cross-app development I'm unsure of how resumability comes into play. @manucorporat would probably know better than anyone in the context of Ionic.

**Comment by liamdebeasi** [comment]
I appreciate the clarification. Yes, I understand that Partytown is a separate project, though that wasn't the point of me bringing it up. That's my fault for not being more clear.

My main point is that having a Qwik integration is not going to make it so developers don't have to worry about performance issues as argued in https://github.com/ionic-team/ionic-framework/issues/28185#issuecomment-1724476166. As mentioned in https://github.com/ionic-team/ionic-framework/issues/28185#issuecomment-1726336745, Qwik **does** bring some great features that help address performance issues. But as demonstrated in that same comment, Qwik focuses on addressing **specific performance issues** such as with the resumability feature.

------

I'm not saying Qwik and Ionic are a bad fit. I've spoken with Adam Bradley, one the Qwik team members, about Qwik and Ionic integrations before. What I'm saying is adding a Qwik integration is not in the best interest of the project at the moment. There are two reasons for this:

1. We don't have any concrete use cases for adding Qwik support to Ionic. The only feedback the team has received is how Qwik could hypothetically help Ionic applications. We need to see real-world examples of Ionic apps impacted by problems that Qwik can help solve.
2. There is low support from the Ionic community for this. I understand there are some developers that would like to see a formal Qwik integration, but adding a new framework integration is very resource-intensive particularly when it comes to routing/navigation support. There's not enough support from the community to justify allocating resources to work on this.

Again, I don't think Qwik is a bad project at all. I worked with both Adam and Manu for several years, and I'm always excited to see all the great stuff they are doing with Qwik and related projects. However, the team here at Ionic has limited resources, so we need to make sure we are allocating those resources to places where we can have the biggest positive impact on Ionic developers.

**Comment by thejackshelton** [comment]
> We don't have any concrete use cases for adding Qwik support to Ionic. The only feedback the team has received is how Qwik could hypothetically help Ionic applications. We need to see real-world examples of Ionic apps impacted by problems that Qwik can help solve.

Cross-app development is not my expertise either, so I don't know firsthand if signals, automatic bundle optimization, resumability, lazy loading, etc. would benefit mobile apps. When it comes to web app performance that I do know.

> There is low support from the Ionic community for this. I understand there are some developers that would like to see a formal Qwik integration, but adding a new framework integration is very resource-intensive particularly when it comes to routing/navigation support. There's not enough support from the community to justify allocating resources to work on this.

I see. If there was larger community support for an integration in the future, would you see a Qwik integration with Ionic as a possibility? 

> Again, I don't think Qwik is a bad project at all. I worked with both Adam and Manu for several years, and I'm always excited to see all the great stuff they are doing with Qwik and related projects. However, the team here at Ionic has limited resources, so we need to make sure we are allocating those resources to places where we can have the biggest positive impact on Ionic developers.

I want to say a massive thanks to the Ionic team for the work on this project, it's been a game changer for many developers, and thanks for your time Liam.

**Comment by liamdebeasi** [comment]
> I see. If there was larger community support for an integration in the future, would you see a Qwik integration with Ionic as a possibility?

If there was larger community support for this in the future we'd absolutely consider it. We realize as technology evolves so do use cases, so when we close feature requests we close them as "not right now" instead of "no we won't implement this ever".
