### ISSUE TITLE
feat: Ionic sheet modal bottom margin

### ISSUE THREAD

**Issue by lori2001** [ionic-team/ionic-framework#28191]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The ion-modal 'sheet' component's position from the bottom should be changeable.

### Describe the Use Case

Most UI designs require sheet-modals that aren't glued to the bottom of the page, but have a certain margin from the bottom of the page.

### Describe Preferred Solution

I'd prefer this to be set via a CSS variable, however any other alternative would be just fine.

### Related Code

This is an image describing the effects that the change would have:
![image](https://github.com/ionic-team/ionic-framework/assets/33576647/7258db4f-25fa-42a1-b069-c02c46c1e5f7)

### Additional Information

This feature request is related to [this question](https://stackoverflow.com/questions/77112849/how-to-implement-angular-ionic-7-sheet-modal-bottom-gap). If you know a hack/workaround for this, please feel free to answer.

**Comment by liamdebeasi** [comment]
Thanks for the report. You can achieve this by setting the margin on the `content` Shadow Part: https://stackblitz.com/edit/ymkck5

I am going to close this since this feature is already available in Ionic, but let me know if you have questions.
