### ISSUE TITLE
bug: ion-input weird behavior with CdkDrag

### ISSUE THREAD

**Issue by Spiff77** [ionic-team/ionic-framework#28200]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

As i have angular ionic and material cdk.

I want to have multiple list with sortable items.
I am having a weird behavior when i use ion-input (it work with other elements, just ion-input seems to be a problem):
I can't find anyone with this issue, i am a bit scared it's only on my side but really can't find the issue...
"item" here is a ion-input:
![Sep-20-2023 08-37-25](https://github.com/ionic-team/ionic-framework/assets/600608/74a9de4b-ea35-4bc1-be2d-481438f6f0da)

### Expected Behavior

I replaced with a standard input tag and the behavior is correct:
![Sep-20-2023 09-08-07](https://github.com/ionic-team/ionic-framework/assets/600608/6075ddcf-ae60-4db9-96a5-b7af05836187)

### Steps to Reproduce

Here is my html:
```
<div *ngFor="let group of formHelper.getArray(form, 'groups').controls; let i = index"  [formGroup]="group" #droplist [id]="'drop-' + i">
          <input type="text" formControlName="name"  appEmptyIfDefaulti18n translationKey="CHECKLIST.FORM.DEFAULT_GROUP_TITLE" class="ml-1 mb-1 borderless ion-inputtext-sm"><br>
          <ion-list cdkDropList #doneList="cdkDropList"
         [cdkDropListData]="formHelper.getArray(group, 'items').controls"
         (cdkDropListDropped)="drop($event)">>
                  <ion-item *ngFor="let cl of formHelper.getArray(group, 'items').controls; let j = index" [formGroup]="cl" [id]="'drag-'+i+'-'+j" cdkDrag>
                    <app-survey-checkbox formControlName="itemStatus"></app-survey-checkbox>
                    <input type="text">
                  </ion-item>
          </ion-list>
        <ion-button (click)="addItem(group)">{{'DEFAULT.ADD_ITEM' | translate}}</ion-button>
        </div>
        <ion-button (click)="addSurvey()">{{'DEFAULT.ADD' | translate}}</ion-button>
        <ion-button (click)="addGroup()">{{'DEFAULT.ADD_GROUP' | translate}}</ion-button>
  </form>
```

### Code Reproduction URL

(https://bitbucket.org/treelevel/dragioninput/src/master/)

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.0
   @angular-devkit/build-angular : 16.2.2
   @angular-devkit/schematics    : 16.2.2
   @angular/cli                  : 16.2.2
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.3.0
   @capacitor/android : not installed
   @capacitor/core    : 5.3.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.12.1 (/usr/local/bin/node)
   npm    : 9.6.7
   OS     : macOS Unknown

**Comment by Spiff77** [comment]
Here is the reproduction:
https://bitbucket.org/treelevel/dragioninput/src/master/

**Comment by Spiff77** [comment]
Thanks a lot.

*Thomas Lhomme.*
IT Consultant in Java/JEE technologies
(+33) 06.13.34.07.45
<https://www.linkedin.com/in/thomas-lhomme-03822895>


Le jeu. 21 sept. 2023 à 14:21, Liam DeBeasi ***@***.***> a
écrit :

**Comment by liamdebeasi** [comment]
You are welcome! I am going to close this since this is not an Ionic bug, but let me know if you have any questions.
