### ISSUE TITLE
bug: ion-datetime calendar days change to previous month's on change detection in child component with ion-card

### ISSUE THREAD

**Issue by Chudroy** [ionic-team/ionic-framework#28205]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

So, super specific bug. When the ion-datetime component is used in a parent component that also contains an ion-card via a child component, the ion-datetime changes to display dates for the previous month. The issue is not present when the ion-card is not rendered or when the child component contains elements other than ion-card.

The issue happens specifically when the child component is rendered after the initial rendering of the component. In the reproduction of my error, the child component is rendered by subscribing to an observable with a delay, using the async pipe in the html.

### Expected Behavior

for the ion-datetime to not change the calendar month days it displays, when rendering an ion-card in a child component, asynchronously.

### Steps to Reproduce

1. Create a parent component with an ion-datetime.
2. Create a child component containing an ion-card.
3. Use the child component within the parent component.
4. Render the child component after an initial delay
5. Observe that the ion-datetime shows the wrong month's dates.

### Code Reproduction URL

https://github.com/Chudroy/ion-datetime-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/home/ngaritagoitia/.nvm/versions/node/v18.17.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.1
   @angular-devkit/build-angular : 16.2.3
   @angular-devkit/schematics    : 16.2.3
   @angular/cli                  : 16.2.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.4.0
   @capacitor/android : not installed
   @capacitor/core    : 5.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.17.0 (/home/ngaritagoitia/.nvm/versions/node/v18.17.0/bin/node)
   npm    : 9.6.7
   OS     : Linux 6.2

**Comment by Chudroy** [comment]
[Grabación de pantalla desde 20-09-23 16:51:17.webm](https://github.com/ionic-team/ionic-framework/assets/73020686/9231998f-0d8a-4ce0-9320-5d4e75ac5d9d)

**Comment by liamdebeasi** [comment]
This appears to be a Firefox bug where the scroll position of the calendar body in datetime gets reset. I added a scroll listener to the scrollable month body. The event fires when I manually scroll it, but it does not fire when the card gets added which is why I think this is a browser bug. If Ionic was causing the scroll position to get reset I would expect the scroll listener to fire.

**Comment by Chudroy** [comment]
I understand, thanks

**Comment by liamdebeasi** [comment]
Since this is a browser bug that has a workaround, I'm going to close this. Let me know if you have questions, or if you find another instance of this where the workaround is not feasible. I can take a closer look and see if there's a better long term solution the team can come up with.

**Comment by Chudroy** [comment]
No worries! This workaround is fine for my needs. Thanks your your help 😄
