### ISSUE TITLE
bug: chrome bug with contain: strict

### ISSUE THREAD

**Issue by Airdevelopments** [ionic-team/ionic-framework#28207]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

At the moment certain Ionic components are not being cleared from memory when their wrapper element is conditionally added and removed from the dom (i.e. using *ngIf). This causes an application to accumulate detached dom elements over time which eat away the available RAM (especially on lower end devices) resulting in a crash of the application.

When placing the *ngIf directive on the component itself this behavior can not be observed.

This issue seems to scale very poorly with larger applications and deeply nested dom trees that often get removed and re-added using *ngIf, resulting in very high RAM usage in a short period of time. This is starting to cause serious issues for us in production.

**Here are some screenshots of my testing:**
(note: Garbage collection was run manually before taking each screenshot, to show that the elements are actually still referenced)

The directive was placed on a wrapper div element:
```html
<div *ngIf="searchbarVisible">
    <ion-searchbar></ion-searchbar>
</div>
```

1. After opening
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/0ab31a8f-fdbb-474f-9aec-8b342c5811bd)
2. After toggling the searchbar off and on again => + 23 DOM Nodes
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/07c1a20c-6882-430f-8391-c6f1611f9628)
3. After repeating step 2 => + 23 DOM Nodes
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/e01f9dea-43c1-4785-b085-480f00fba98d)
4. After repeating step 2 another 5 times => + (5 * 23) = 115 DOM Nodes
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/f3ac0721-ca2f-4f2f-87fb-c4ab3d22c48a)

Comparing two memory snapshots shows us the searchbars that should no longer exist:
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/f7c50670-228c-4af3-915e-e82471891958)

Here is the same sequence of actions with the directive applied directly to the `<ion-searchbar>` element:

```html
<div>
    <ion-searchbar *ngIf="searchbarVisible"></ion-searchbar>
</div>
```

1. 
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/85412513-e863-4ed8-af94-a41979734ded)
2.
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/b56bfa46-08b5-4051-8f9a-06aea3a05c37)
3.
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/5a9137c6-e780-495d-9f59-a74f61d16a78)
4.
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/984c07f3-f47a-48b0-83ae-86e843dd1af9)

It seems that this issue also applies to other ionic components (if more evidence for that is required, please let me know).

### Expected Behavior

It should not matter where the *ngIf directive is placed. In any case, the removed dom elements should no longer be referenced and freed from memory.

### Steps to Reproduce

1. Clone the provided repository
2. Serve the app locally using `npm run start`
3. Open the app in a web browser
4. Activate the browsers dev tools and use the memory inspection tool (in chrome 'Performance monitor' is useful as well)
5. Repeatedly press the button labled 'Toggle Searchbar' on the tab labled 'Tab 1 page' - observe the memory usage
6. (Optional) Edit the tab1.page.html and toggle the comments to the version that place the *ngIf directive directly onto the `<ion-searchbar>` and observe the memory usage

### Code Reproduction URL

https://github.com/Airdevelopments/ionic-memory-leak

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\nvm\v18.16.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.4.1
   @angular-devkit/build-angular : 16.2.3
   @angular-devkit/schematics    : 16.2.3
   @angular/cli                  : 16.2.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.4.0
   @capacitor/android : not installed
   @capacitor/core    : 5.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.8.0
   OS     : Windows 10

### Additional Information

This issue _might_ be related to this stencil issue: https://github.com/ionic-team/stencil/issues/3607 (as the memory tool seems to show the WeakMap as retainer of those detached elements).

This might also be a related cause of this issue: https://github.com/ionic-team/ionic-framework/issues/28189

**Comment by liamdebeasi** [comment]
Thanks for the report. Are you able to point to a part of Ionic that you think is causing this problem? I do see that using CSS containment is creating some retainers in Chrome only. I filed this feedback on https://bugs.chromium.org/p/chromium/issues/detail?id=1485629.

However, I don't see anything else that would point to Ionic being the source of the remaining retainers at the moment. Does this issue reproduce outside of an Angular environment?

**Comment by Airdevelopments** [comment]
Thanks for the quick response.

I did some more testing in Firefox (117.0.1) and the memory issue does seem to exist there as well (I am not too familiar with the Firefox dev-tools):

![image](https://github.com/ionic-team/ionic-framework/assets/20710097/5913bc69-0cfd-4d8b-9375-ba4345708894)
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/a6647de7-a9fc-4070-b6b8-ad52f5c16ed0)
![image](https://github.com/ionic-team/ionic-framework/assets/20710097/d6ac376b-661c-429c-a8c5-ed555dd42eb0)

I agree that the issue is not very likely caused by Ionic directly, but rather some of its dependencies. The goal would be to pin down what dependency (and in which circumstances) causes this kind of memory leak so that we can eliminate this issue.

Thanks again for your support!

**Comment by liamdebeasi** [comment]
Does the issue reproduce in Chrome if you set the following in a global stylesheet? This will help determine if there are issues other than the Chromium bug I noted in https://github.com/ionic-team/ionic-framework/issues/28207#issuecomment-1730054205.

```css
* {
  content-visibility: auto;
}
```

**Comment by Airdevelopments** [comment]
Interestingly enough, setting this style rule does seem to resolve the issue in Chrome.

Is this a production-ready workaround or should this only be used to classify the cause of the memory leak?

Thank you.

**Comment by liamdebeasi** [comment]
> Is this a production-ready workaround or should this only be used to classify the cause of the memory leak?

I haven't fully tested this, so I wouldn't use it in production on this scale. However, it should be safe to use on specific components such as `ion-searchbar`.


-----

I'll note that this bug is a Chrome regression starting in v115, so hopefully they fix it soon.
