### ISSUE TITLE
bug: Regarding the display of ion-datetime

### ISSUE THREAD

**Issue by tamuragenya** [ionic-team/ionic-framework#28217]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

encountered text truncation issues when displaying the ion-datetime.

The right edge is not displayed
![b053e0206fe792b7434fde9915a835f0c694282d_2_272x500](https://github.com/ionic-team/ionic-framework/assets/145751899/1aaaa05f-ee88-47ab-b071-746c94c8c66f)

The width becomes narrower from the second time onwards.
・First time
![0e402c0d9a706ba73f14bdf084e047f6684b4019_2_272x500](https://github.com/ionic-team/ionic-framework/assets/145751899/6d00375b-97cc-428e-86d3-582dd3c005f7)

・From the second time onwards
![bdcebcbef9eb44a8cab24e442f6a839628ad4c42_2_272x500](https://github.com/ionic-team/ionic-framework/assets/145751899/8d5b448b-34ab-456c-8a51-d47e7ab92caf)

### Expected Behavior

The right edge of ion-datetime is not be cut off
The first display and subsequent displays will be the same width.

### Steps to Reproduce

```
              <ion-popover trigger="S_01-004_bd" triggerAction="click" style="--width: 85%;">
                <ng-template>
                  <ion-datetime id="birthday" class="input-date"  displayFormat="YYYY.M.D" value="{{pickerDate || '1980-01-01'}}" (click)="onClickBirthday()"
                  presentation="date"
                  #popOverValue
                  mode="ios"
                  [showDefaultButtons]="true"
                  doneText="設定"
                  cancelText="キャンセル"
                  (ionChange)="birthday.date.setValue(popOverValue.value)"
                                preferWheel="true"
                  >
                  </ion-datetime>
                </ng-template>
              </ion-popover>
```

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/si/.nodebrew/node/v20.3.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.1.0
   @angular-devkit/build-angular : 16.1.1
   @angular-devkit/schematics    : 12.2.18
   @angular/cli                  : 16.1.1
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v20.3.1 (/Users/si/.nodebrew/node/v20.3.1/bin/node)
   npm        : 9.6.7
   OS         : macOS Unknown
   Xcode      : Xcode 14.2 Build version 14C18

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
