### ISSUE TITLE
bug: ion-radio not initializing properly

### ISSUE THREAD

**Issue by dandandelion** [ionic-team/ionic-framework#28216]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When initializing `ion-checkbox` using `*ngFor` with attribute `[checked]="true"`, the labels get does not get properly initialized. It doesn't display at all and throws in a bunch of warnings telling me to use the `legacy` (although it displays the checkbox itself, just not the label). This only happens if an item is initially set to `[checked]="true"`, otherwise, if it is `[checked]="false"`, it displays normally.

### Expected Behavior

To properly initialize the labels.

### Steps to Reproduce

This is my code to reproduce the problem:

Function from `home.page.ts` to initialize the items:
```typescript
async initRlas(){
    this.checkList.attached_rla.splice(0, 1);/
    let temporaryRLA: any = (this.status === "old_")? JSON.parse(this.data.attached_rla) || [] : this.data || [];
    
    this.checkList.attached_rla = await temporaryRLA.map((element: any) => ({
      "seedTag": element.seedTag,
      "selected": true
    }));
  }
``` 
if you add a `console.log(this.checkList.attached_rla)` on the bottom of the function, you would see that it is properly initialized.

This is the `html`:
```html
<ion-list class="transparent">
  <ion-item *ngFor="let item of checkList.attached_rla" class="transparent">
    <ion-checkbox [checked]="item.selected? true : false" (ionChange)="onSelectRLA(item)" [value]="item.seedTag"><span>{{item.seedTag}}</span></ion-checkbox>
  </ion-item>
</ion-list>
``` 

Additionally, as I suspected it to be a rendering issue, I tried setting the items to `false` initially which does properly initialize all the checkboxes and then added a `250ms timeout` to initialize their real proper value that is loaded.

This is the revised function: 
```typescript
async initRlas() {
    this.checkList.attached_rla.splice(0, 1);
    
    let temporaryRLA: any = (this.status === "old_")? JSON.parse(this.data.attached_rla) || [] : this.data || [];
    
    this.checkList.attached_rla = await temporaryRLA.map((element: any) => ({
      "seedTag": element.seedTag,
      "selected": false //intialize to false first
    }));

    //then I added a delay before properly initializing their true value
    setTimeout(() => {
      this.checkList.attached_rla.forEach((item: any, index) => {
        item.selected = temporaryRLA[index].selected;
      });
    }, 250);
  }
``` 

Which is, for right now, a working workaround.

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - C:\Users\Admin\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Admin\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Admin\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Admin\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\Admin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.0
   @angular-devkit/build-angular : 15.2.4
   @angular-devkit/schematics    : 15.2.8
   @angular/cli                  : 15.2.8
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : 4.7.3
   @capacitor/core    : 5.0.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.0
   OS     : Windows 10

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
