### ISSUE TITLE
feat: Support for customized vue-routers 

### ISSUE THREAD

**Issue by DellanX** [ionic-team/ionic-framework#28233]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Support for wrappers of vue-router.

Specifically, I am trying to use [unplugin-vue-router](https://github.com/posva/unplugin-vue-router), which has an alternative namespace used to get the createRouter method.

### Describe the Use Case

This would enable the configuration of unplugin-vue-router with this package. Unplugin Vue Router enables developers to define routes by filestructure.

### Describe Preferred Solution

I think this may possible via be a simple change to [vue-router/index.ts](https://github.com/ionic-team/ionic-framework/blob/main/packages/vue-router/src/index.ts), adding a config option to point to a different `createRouter` method.
```ts
  const router = opts.creatRouter(routerOptions) ?? createVueRouter(routerOptions);
```

### Describe Alternatives

I've considered approaching the unplugin-vue-router package to add support for wrapping instead; however, that package is far more complex, and I don't think it could be pulled off easily.

**Comment by DellanX** [comment]
I just realized that the original router object gets returned on line 32.
perhaps making router itself a config/param would better than the method.

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please clarify how you'd use this feature in Ionic? I see the unplugin router package is still experimental, and we typically don't support experimental 3rd party dependencies until they are stable.

**Comment by DellanX** [comment]
My actual need would be for a way to create a router from a file structure. Similar to that plugin, or NUXT.

I was hoping a slight modification to the ionic router could make this possible, but my experiments have shown otherwise.

I agree that implementing support for this specific plugin isn't a good path forward, and was hoping for a path for a more generic router is all.

Again, my real need is to be able to load routes based on a file structure.

**Comment by liamdebeasi** [comment]
Thanks for the clarification! I spoke with the team, and we don't have plans to support custom routers at this time. As noted, the desired router is experimental, and we typically do not support experimental 3rd party dependencies. The other consideration is that `@ionic/vue-router` was designed to support `vue-router`. While the library you want to use is based off this, adding this feature would potentially allow for any Vue-based router to be used. There could be behavior differences that are not accounted for when using custom routers.

I am going to close this, but let me know if you have questions.
