### ISSUE TITLE
bug: ion-accordion scrolling to top in chrome at first click

### ISSUE THREAD

**Issue by Cris13** [ionic-team/ionic-framework#28230]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

When opening a page with ion-accordion for the first time, and with the accordion open to display a list of items, if the user scrolls to click on an item that is not visible when the page is open. The first click is not received by the item and the page scrolls to the top pf the accordion.

The issue is reproducible only with **Chrome**, It works fine in Safari
The issue happens only the **first time**, if the user scrolls down and click again the click is behaving as expected.

### Expected Behavior

The click should be received by the item and the page schould not scroll to the top of the accordion.

### Steps to Reproduce

1. open a page with `ion-accordion` that is open by default
2. scroll to click on an element in the accordion that is not visible when the page is open
3. click on such element
4. the page scrolls up to the top

### Code Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-nfvdab?file=src%2Fapp%2Fapp.component.ts,package.json,src%2Fapp%2Fhome%2Fhome.page.html

### Ionic Info

  Ionic Framework               : @ionic/angular 7.4.1
   @angular-devkit/build-angular : 16.2.3
   @angular-devkit/schematics    : 16.2.3
   @angular/cli                  : 16.2.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.4.1
   @capacitor/android : not installed
   @capacitor/core    : 5.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.16.0
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by amandaejohnston** [comment]
Thank you for the issue. This looks to be the same bug as https://github.com/ionic-team/ionic-framework/issues/25064 -- the scroll is caused by the accordion's header being focused. I'll consolidate the two.
