### ISSUE TITLE
bug: Range should update its value in forms while dragging

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#28256]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Currently the `ion-range` component subscribes to the `ionChange` event to update it's value when participating in a form:
- Angular: https://github.com/ionic-team/ionic-framework/blob/51b7ceb5bef81dc5367e313c96e8937483c06753/packages/angular/src/directives/control-value-accessors/select-value-accessor.ts#L6-L32
- Vue: https://github.com/ionic-team/ionic-framework/blob/51b7ceb5bef81dc5367e313c96e8937483c06753/core/stencil.config.ts#L138-L143

This is confusing to users and limits how the `ion-range` component can be used in applications. A use case could be a volume control that you want to immediately adjust the setting as a user drags on the range. This currently is not possible without manually subscribing to the `ionInput` value and assigning it to the form.

### Expected Behavior

`ion-range` should subscribe to the `ionInput` event instead of `ionChange` so that the value is immediately update as the user interacts with the control.

### Steps to Reproduce

1. Open the reproduction link
2. Drag the range knob and do not release
3. Observe: As you drag, the value does not update.
4. Release the range knob
5. Observe: The value updates to the knob position

### Code Reproduction URL

https://stackblitz.com/edit/angular-2nzaub?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fexample.component.ts

### Ionic Info

N/A

**Comment by amandaejohnston** [comment]
Resolved via https://github.com/ionic-team/ionic-framework/pull/28422, thank you!
