### ISSUE TITLE
bug: Ion Back Button 

### ISSUE THREAD

**Issue by fbaholli** [ionic-team/ionic-framework#28252]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I am navigating from a form in a module but i want to destroy the form on leave but the lifecycle hooks dont fire since the back button stores the pages in the DOM thus making the form have the same state as when ion-back-button is clicked

### Expected Behavior

to be able to choose wether to clear the page or destroy it as in router-angular, make something as an option i.e. destroy=true on back button or something

### Steps to Reproduce

1. build a new ionic project
2. add a form in a page
3. complete some stuff in the form 
4. press back button 
5. go back to the form 
6. the form will  be as previously left

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/franci/.nvm/versions/node/v16.20.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.2
   @angular-devkit/build-angular : 16.2.4
   @angular-devkit/schematics    : 16.2.4
   @angular/cli                  : 16.2.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : 5.0.4
   @capacitor/core    : 5.0.4
   @capacitor/ios     : 5.0.4

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v16.20.0 (/Users/franci/.nvm/versions/node/v16.20.0/bin/node)
   npm    : 8.19.4
   OS     : macOS Unknown

### Additional Information
 
i worked around it somehow in my case and the doSomething() function resets the form but its clunky at best
```
    <ion-toolbar color="white">
      <ion-buttons (click)="doSomething()" slot="start">
        <ion-back-button style="font-weight: bold;" defaultHref="home"
          text="new request"> </ion-back-button>
      </ion-buttons>
    </ion-toolbar>
```

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
