### ISSUE TITLE
feat: Add 'custom' interface for ion-select component

### ISSUE THREAD

**Issue by stevecances** [ionic-team/ionic-framework#28255]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

`ion-select` would be more flexible with a `custom` interface.

### Describe the Use Case

In my case I would like to trigger a custom `ion-modal` to let the user choose an option. In addition, the modal would include an input that could help the user to filter listed options.

But the point of this `custom` interface would be to cover many cases as it is very open/flexible.
For exemple it may help to cover issue #20317.

### Describe Preferred Solution

It might be a new interface of type 'custom' working with a new `interfaceOptions` entry : `openCustom: (interfaceSettings: CustomInterfaceSettings) => Promise<Overlay>`

```
interface CustomInterfaceSettings {
  data: HTMLIonSelectOptionElement[];
  selectValue: any;
  setValue(value?: any | null);
}
```

The `openCustom` method would be trigged to delegate the creation of an overlay that would use a `CustomInterfaceSettings` to display and select options.

**Comment by liamdebeasi** [comment]
Thanks for the report. Have you tried incorporating https://ionicframework.com/docs/api/select#typeahead-component into your application? Our concern with the proposal is that it's a bit too open ended, which could lead to devs trying to force `ion-select` into doing things it was not designed to do. While the proposal works for this use case, it requires the developer to wire a lot of things up manually which goes against how `ion-select` was originally designed.

**Comment by stevecances** [comment]
Thanks for your response. I completely missed typeahead-component from the doc but it seems to covers my needs actually 👍
The only criticism I could make is that typeahead-component integrates less well into a form than a `ion-select` but I understand your concern about this too open ended solution.
Thanks for the great work 👍
