### ISSUE TITLE
bug: datetime jumping between months when min="" is added - iOS17

### ISSUE THREAD

**Issue by gatelli** [ionic-team/ionic-framework#28260]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

`<ion-datetime-button datetime="datetime" class="device_datetime" ></ion-datetime-button>
              <ion-modal [keepContentsMounted]="true" >
                <ng-template>
                  <ion-datetime [showDefaultButtons]="true" doneText="Search" cancelText="Cancel" id="datetime" [(ngModel)]="date.start" (ionChange)="seeDates()" firstDayOfWeek="1" min="2023-09-27"></ion-datetime>
                </ng-template>
              </ion-modal>`

the calendar is jumping from present month to next when arrow is pressed. Endless.

just like this old bug : https://github.com/ionic-team/ionic-framework/issues/25752

This is happening with iOS17 (not with iOS16)

### Expected Behavior

expected is just jumping to next month.

### Steps to Reproduce

1. Set a datetime button: `<ion-datetime-button datetime="datetime" class="device_datetime" ></ion-datetime-button>
              <ion-modal [keepContentsMounted]="true" >
                <ng-template>
                  <ion-datetime [showDefaultButtons]="true" doneText="Search" cancelText="Cancel" id="datetime" [(ngModel)]="date.start" (ionChange)="seeDates()" firstDayOfWeek="1" min="2023-09-27"></ion-datetime>
                </ng-template>
              </ion-modal>`
2. press the arrow, or slide to next month

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/xxx/.nvm/versions/node/v18.17.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.2
   @angular-devkit/build-angular : 15.2.6
   @angular-devkit/schematics    : 15.2.6
   @angular/cli                  : 15.2.6
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.3.0
   @capacitor/android : 5.3.0
   @capacitor/core    : 5.3.0
   @capacitor/ios     : 5.3.0

Cordova:

   Cordova CLI       : 12.0.0 (cordova-lib@12.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (6 plugins total)

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.3) : 1.7.2

System:

   NodeJS : v18.17.1 (/Users/xxx/.nvm/versions/node/v18.17.1/bin/node)
   npm    : 9.6.7
   OS     : macOS Unknown
   Xcode  : Xcode 15.0 Build version 15A240d

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
