### ISSUE TITLE
bug: Ionic Menu fails to load in some situations

### ISSUE THREAD

**Issue by pct-cclausen** [ionic-team/ionic-framework#28266]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

My ionic menu does not load in my Cypress Tests sometimes. When this happens I get this error in the console:

ionic-angular.mjs:4568 Uncaught TypeError: elm[aelFn] is not a function
    at Object.ael (ionic-angular.mjs:4568:35)
    at index-cb3f261d.js:2301:17
    at Array.map (<anonymous>)
    at addHostEventListeners (index-cb3f261d.js:2297:19)
    at registerHost (index-cb3f261d.js:2358:5)
    at new HostElement (index-cb3f261d.js:2229:21)
    at EmulatedEncapsulationDomRenderer2.createElement (platform-browser.mjs:538:25)
    at EmulatedEncapsulationDomRenderer2.createElement (platform-browser.mjs:756:26)
    at createElementNode (core.mjs:6786:21)
    at _locateOrCreateElementNode (core.mjs:15308:12)

It originates in this line of code:

https://github.com/ionic-team/ionic-framework/blob/8a9db8c9496be6c872376caa27ed04272afdc6d4/packages/angular/src/app-initialize.ts#L30

### Expected Behavior

No error and a working menu

### Steps to Reproduce

I am afraid I cant provide a working reproduction, as it happens pretty randomly. The line of code in question is also pretty hard to understand. It seems to have to do something with the app initialization, but how does the ion-menu need initialization? There seems to be a race condition.

Some info on what that line of code is supposed to do might help me produce a working reproduction.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.9 (/home/cclausen/.nvm/versions/node/v18.12.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.0.5 (/datadisk/splus/nx-abfall-app/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 16.0.5 (/datadisk/splus/nx-abfall-app/node_modules/@angular-devkit/schematics)
   @angular/cli                  : 16.0.5 (/datadisk/splus/nx-abfall-app/node_modules/@angular/cli)
   @ionic/angular-toolkit        : not installed

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : 5.0.5 (/datadisk/splus/nx-abfall-app/node_modules/@capacitor/android)
   @capacitor/core    : 5.2.1 (/datadisk/splus/nx-abfall-app/node_modules/@capacitor/core)
   @capacitor/ios     : 5.0.5 (/datadisk/splus/nx-abfall-app/node_modules/@capacitor/ios)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.12.1 (/home/cclausen/.nvm/versions/node/v18.12.1/bin/node)
   npm    : 8.19.2
   OS     : Linux 5.15

**Comment by liamdebeasi** [comment]
Thanks for the report. Unfortunately, there's not much we can do without a reproduction of the issue. The line of code in question bypasses NgZone when calling `addEventListener`.
