### ISSUE TITLE
bug: ion-accordion has no item bottom border when content is open

### ISSUE THREAD

**Issue by mpaland** [ionic-team/ionic-framework#28286]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

See the component example at https://ionicframework.com/docs/api/accordion

Click on the Second Accordion to open the content.
The bottom border to the third accordion header is missing while the content of  the second header is expanded.

This is not critical in the example due to different background colors, but when the header background is also white, the missing border is a problem.

### Expected Behavior

A Bottom border between the expanded content and the next header.

### Steps to Reproduce

See the current behavior.

### Ionic Info

Ionic:
   Ionic CLI       : 7.1.1 (C:\Users\Marco\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.4.3

Capacitor:
   Capacitor CLI      : 5.4.1
   @capacitor/android : not installed
   @capacitor/core    : 5.4.1
   @capacitor/ios     : not installed

**Comment by liamdebeasi** [comment]
Hey there,

Your expected behavior states the following:

>A Bottom border between the expanded content and the next header.

However, in the "current behavior" section you noted the problem is with the final accordion in the group. In that case, there would be no next header, so a border is not needed. Can you clarify which scenario you are having trouble with?

**Comment by LennonReid** [comment]
I assume the challenge he faced was similar to this.
<img width="1424" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/43192276/b704d08d-e1d2-45dc-bedd-6e888a6b7524"> 
It's challenging to discern which contents pertain to the second accordion.

**Comment by liamdebeasi** [comment]
I'm going to add "needs: reply" again just so I can get confirmation from the author. However, if this is indeed the challenge the author faced then I figure out next steps.
