### ISSUE TITLE
bug: V-Model on IonAccordion

### ISSUE THREAD

**Issue by Patsch36** [ionic-team/ionic-framework#28288]
### Describe the Bug

I used a v-model vor my accordion-group in vue3 to have the value in code. But on interacting with content-module, like checkboxes or buttons, the content of the v-model variable changes to something else. For example to "On", when clicking on a checkbox or even funnier: to the content of my searchbar when pressing a button.

### Expected Behavior

I expect the v-model not to change.

### Steps to Reproduce

You ca take a look on the profile View of this repository: https://github.com/Patsch36/SweatFlix at /src/view/...
Current Commit Version ist [a07783e](https://github.com/Patsch36/SweatFlix/commit/a07783e04762fea2b8649e1cf293e24f8a1384fa)

### Operating System

MacOS 14.0 Sonoma

### Browser

Iphone 15 Pro Simulator (And real device)

**Comment by amandaejohnston** [comment]
Could you make sure your reproduction only has the code necessary to reproduce the issue? The profile view has a lot of extra components and functionality that may be unrelated, making the source of the problem difficult to track down. It may be easiest to create a blank project using `ionic start` and add code to that piece by piece until the issue reproduces.
