### ISSUE TITLE
bug: Ionic Angular inline modal scrolls to top when something re-renders inside the modal

### ISSUE THREAD

**Issue by whyper-mateus** [ionic-team/ionic-framework#28306]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Currently I have a modal with some things like "Purchase Summary", "Delivery Options" and a stripe component for instant payments.

The current Behavior with the modal is: When the modal extends more than the current vh and I scroll the page, after I click to change a state of something inside the modal, the same modal scrolls all the way to the top, like re-rendering the entire page without saving the current scroll state.

https://github.com/ionic-team/ionic-framework/assets/107601953/9dd385ac-5ed5-46f5-8465-fcfa58be8b5b

### Expected Behavior

Stays in the same scroll state/position, without going to the top of the modal.

### Steps to Reproduce

1. Create an Inline Modal
2. Add content to the modal, going through the vh, adding a scroll
3. Add a state changing element in the end of the page
4. Click in the element (can be a checkbox with state being controlled in the ts side or a simple var that can be changed and is visible)
5. Try to stay in the same scroll position.

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\Mateus\AppData\Local\npm-cache\_npx\f6fddb685269761d\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.4.3
   @angular-devkit/build-angular : 16.2.5
   @angular-devkit/schematics    : 15.2.10
   @angular/cli                  : 16.2.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.4.2
   @capacitor/android : not installed
   @capacitor/core    : 5.4.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.3.1
   OS     : Windows 10

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
