### ISSUE TITLE
bug: ion-datetime-button can not be null

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/ionic-framework#28305]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using a `ion-datetime-button` the initial value is always the current date even when the form control value is `null`. This way optional form fields of the date/time type can not be empty

### Expected Behavior

I expect the `ion-datetime-button` to have a way to be empty for optional form types

### Steps to Reproduce

1. Create a form with a form control where the initial form field value is `null`
2. Add a ion-date-time button to the template

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.3.4
   @angular-devkit/build-angular : 16.2.1
   @angular-devkit/schematics    : 16.2.1
   @angular/cli                  : 16.2.1
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.3.0
   @capacitor/android : 5.3.0
   @capacitor/core    : 5.3.0
   @capacitor/ios     : 5.3.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.3) : 1.7.2

System:

   NodeJS : v18.16.1 (/usr/local/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown
```

**Comment by liamdebeasi** [comment]
Thanks for the report. What are you expecting to see inside of `ion-datetime-button` instead?

**Comment by basvdijk** [comment]
@liamdebeasi I am thinking of something like a calendar icon or 3 dots

**Comment by liamdebeasi** [comment]
`ion-datetime-button` has slots that allow you to set custom content when the associated `ion-datetime` does not have a value set. Would something like this work for your use case?

```html
<ion-datetime id="datetime" presentation="date" [(ngModel)]="dateValue"></ion-datetime>
<ion-datetime-button datetime="datetime">
  <ion-icon name="calendar" slot="date-target" *ngIf="dateValue === undefined"></ion-icon>
</ion-datetime-button>
```

**Comment by basvdijk** [comment]
@liamdebeasi Nice solution! Works perfectly, thanks! Maybe it is an idea to add this to the docs?

**Comment by liamdebeasi** [comment]
I think that would be great! Any interest in contributing a PR for that? We could probably add a new section on https://ionicframework.com/docs/api/datetime-button.

In terms of the changes we'd need to make:

1. Add new section on the page.
2. Add a new playground so other devs can try it out. You can use `npm run playground:new` from the Ionic Docs repo to generate a new playground.

I am going to close this since the original issue is resolved, but let me know if you have questions about the docs update.
