### ISSUE TITLE
bug: ion-item-sliding inconsistently clobbers page swipe back gesture

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#28303]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

This is inconsistent to reproduce (~50% of the time): Any ion-item-sliding will capture a swipe back gesture so that the user accidentally swipes the item instead of the page.

### Expected Behavior

Swipe back gesture should always have priority over ion-item-sliding

### Steps to Reproduce

- In repro below, tap to go to inner page
- Try to swipe back. Observe ion-item-sliding sometimes overrides swipe page back gesture

### Code Reproduction URL

https://github.com/aeharding/ionic-swipe-back-gesture-bug

### Ionic Info

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.15.0
   npm    : 9.5.0
   OS     : macOS Unknown
```

**Comment by liamdebeasi** [comment]
Fixed via https://github.com/ionic-team/ionic-framework/pull/28304. Thanks again!
