### ISSUE TITLE
bug: datetime, go button in number pad doesn't do anything

### ISSUE THREAD

**Issue by iStaha** [ionic-team/ionic-framework#28325]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

Go button ( -> )  doesn't do anything when you click it.

https://github.com/ionic-team/ionic-framework/assets/11216288/ec7decca-75d3-4cfc-9514-dab1fea8785f

### Expected Behavior

Go button ( -> ) should close the keyboard / date timepicker dialog. Basically, it should have some funtion.

![image](https://github.com/iStaha/time-picker/assets/11216288/fe694b95-f6f3-4d6b-8464-78ee969947ec)

<img width="289" alt="image" src="https://user-images.githubusercontent.com/119839331/205569087-3b7269f0-6bde-4c1c-9b46-98769620718c.png">

### Steps to Reproduce

1. Utilize ion-datetime and generate the APK using Cordova, or alternatively, use emulator.
2. Select the minute column to open the numeric keyboard on your mobile device.
3. Attempt to use the "Go" button or the "->" button that appears. Note that some devices may display a "Go" button, while others will show "->".

your can reproduce this issue in any ionic 5 or ionic 6 version.

### Code Reproduction URL

https://github.com/iStaha/time-picker/

### Ionic Info

<img width="832" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/11216288/b6ba0cc6-6485-4a7e-9018-2da89d4ea31e">

**Comment by liamdebeasi** [comment]
Thanks! The keyboard should close when the "Go" button is pressed. This aligns with the behavior of https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local on Android.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28848, and a fix will be available in an upcoming release of Ionic Framework. Feel free to keep testing the dev build, and let me know if you run into any issues.
