### ISSUE TITLE
bug: upable to open document website

### ISSUE THREAD

**Issue by hkrvikrant** [ionic-team/ionic-framework#28324]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When I tried to open "https://ionicframework.com/" framework URL to check something, this website was unable to open getting a "Bad gateway" error 

here is the screenshot:

<img width="1133" alt="Screenshot 2023-10-11 at 2 14 33 PM" src="https://github.com/ionic-team/ionic-framework/assets/71812400/b9244807-a149-45d0-8648-a53b5e89f230">

### Expected Behavior

It will open fine and we are able to check the document.

### Steps to Reproduce

1. Open your browser
2. write the framework URL: https://ionicframework.com/
3. Let see the error.

### Ionic Info

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v18.16.1
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by kletel** [comment]
same for me +1
