### ISSUE TITLE
bug: menuController close is not working on @ionic/angular@7.5.0

### ISSUE THREAD

**Issue by matthew2564** [ionic-team/ionic-framework#28342]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

After upgrade `@ionic/angular` from 7.4.2 to 7.5.0 MenuController.close() stop working.

### Expected Behavior

The menu should close automatically upon invoking the close method.

### Steps to Reproduce

1. Upgrade the following package `@ionic/angular` to 7.5.0 - `npm i @ionic/angular@7.5.0 -S`
2. Implement a Menu

// app.component.html
```
<ion-app>
  <ion-menu side="start" content-id="main-content">
       <ion-item (click)="navPage('Home')">
        <ion-label>Home}</ion-label>
      </ion-item>
  </ion-menu>
</ion-app
```

// app.component.ts
```
  navPage = async (page: string): Promise<void> => {
    await this.router.navigate([page]);
    await this.menuController.close();
  };
```

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.2.6
   @angular-devkit/schematics    : 16.2.6
   @angular/cli                  : 16.2.6
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : not installed
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   ios-sim : 8.0.2
   NodeJS  : v18.11.0 (/Users/matt/.n/bin/node)
   npm     : 8.19.2
   OS      : macOS Unknown
   Xcode   : Xcode 14.3 Build version 14E222b

**Comment by liamdebeasi** [comment]
Thanks for reporting this! Looks like this is the same problem as https://github.com/ionic-team/ionic-framework/issues/28337, so I am going to merge the two. I'll provide a temporary workaround in that thread.
