### ISSUE TITLE
bug: [7.5] standalone build size is bigger than standard version

### ISSUE THREAD

**Issue by hatsantos** [ionic-team/ionic-framework#28358]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When converted to a standalone components app, using Ionic standalone components, the app build size is not smaller as announced in the blog post.

Using a sample Ionic app from the CLI, such as "sidemenu," after converting it to standalone components (following the guide: https://ionicframework.com/docs/angular/build-options#migrating-from-modules-to-standalone), the initial app size is larger than the module version.

**Ionic "sidemenu" sample app and updated to Ionic 7.5 and Ionicons 7.2.1**

> ionic build --prod

![image](https://github.com/ionic-team/ionic-framework/assets/36542752/9131a6df-f9ce-40c9-8cd4-f973cd417462)

**Ionic "sidemenu" sample app updated to Ionic 7.5 and Ionicons 7.2.1 and migrated to standalone components**

> ionic build --prod

![image](https://github.com/ionic-team/ionic-framework/assets/36542752/84073f4f-d56f-41f4-9597-13ed22f30def)

Am i doing something wrong?

The migration effort is still high, and in doing so, I would like to ensure that it's worth it and that I'm doing it the right way.

### Expected Behavior

Initial bundle size to be smaller.

### Steps to Reproduce

1. ionic start > angular > standalone > sidemenu
3. build a prod app
4. update to standalone version of ionic components
5. build a prod app

### Code Reproduction URL

https://hatsbytes@bitbucket.org/hatslab/ionstandalone.git

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\username\AppData\Local\pnpm\global\5\.pnpm\@ionic+cli@7.1.1\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.5.0
   @angular-devkit/build-angular : 16.2.6
   @angular-devkit/schematics    : 16.2.6
   @angular/cli                  : 16.2.6
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : not installed
   @capacitor/core    : 5.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v20.8.1 (C:\Program Files\nodejs\node.exe)
   npm    : 10.1.0
   OS     : Windows 10

### Additional Information

Code Reproduction URL has a standalone ionic component converted app.

**Comment by gant02** [comment]
I have the exact same behavior with my app following the migration guide. All standalone components are imported in the main.js bundle. With the tab starter, everything is imported in a dedicated chunk but all at once.
<img width="836" alt="Capture d’écran 2023-10-16 à 10 53 17" src="https://github.com/ionic-team/ionic-framework/assets/6771123/7bbd992c-4d1b-4d9f-9cb9-4d29b106be2c">

**Comment by liamdebeasi** [comment]
It looks like this was introduced in https://github.com/ionic-team/ionic-framework/pull/28311/commits/28f2ec9c62fc301b432a7bca9a985b8ce90ef843. Ionic wasn't creating side effects, but the way `ng-packagr` generated the components caused a side effect. I was able to avoid the `ng-packagr` issue.

Here's a dev build with a proposed fix if you are interested in testing: `7.5.1-dev.11697476647.1a8e5f25`

**Comment by hatsantos** [comment]
@liamdebeasi Thank you, I'll test it and provide feedback as soon as possible.

**Comment by liamdebeasi** [comment]
Thanks! I found a bug in the dev build I posted, so make sure you grab the latest dev build in the edited comment above

**Comment by hatsantos** [comment]
I ran some tests. The raw size seems to have reduced by half and the gzip size improved; however, compared to the initial NgModule version, the size is still similar (slightly larger even). I thought it would be possible to achieve better results.

**Prod 7.5.0 build sidemenu sample app, NgModule version**
![image](https://github.com/ionic-team/ionic-framework/assets/36542752/95aa9437-90f0-46eb-a69f-dbe28e0a860b)


**Prod 7.5.0 build, sidemenu sample app converted to standalone components:**

![image](https://github.com/ionic-team/ionic-framework/assets/36542752/f8611914-f240-477b-8f83-10e1c3f38163)

![image](https://github.com/ionic-team/ionic-framework/assets/36542752/a0c10238-d997-4ede-b4c5-23a684c3e0cc)


**Dev 7.5.1-dev.11697480817.10fa2601 build, using sidemenu sample app converted to standalone components:**

![image](https://github.com/ionic-team/ionic-framework/assets/36542752/62035b0c-c449-46ac-a97d-da075c12892e)

![image](https://github.com/ionic-team/ionic-framework/assets/36542752/60db4e5a-3114-461d-b0cb-22b3e6e115bf)

**Comment by liamdebeasi** [comment]
Your NgModule test does not account for the "Lazy Chunk Files" which will significantly change the results of your test.  If you look at the size of `www`, you'll get (roughly) the following:

NgModules on 7.5.0: 7.2mb
Standalone on 7.5.0: 1.1mb
Standalone on 7.5.1-dev.11697480817.10fa2601: 631kb

**Comment by gant02** [comment]
On my side, the main.js bundle is still bigger than before. All ionic components used in the app (even in other pages) are included in the main.js. 

I generated a new project with side menu and we have:

![image](https://github.com/ionic-team/ionic-framework/assets/6771123/4cca4b49-add4-41d3-970f-e9fb2542b66f)

But if you add in the folder components <ion-textarea> for example, the components is added in the main.js. 

![image](https://github.com/ionic-team/ionic-framework/assets/6771123/cdc60bd3-e261-4602-a810-9628a31e5370)

It should be in a specific chunk no? it was the case in version prior 7.5.1.

With a large application, the main.js is bigger with v7.5.1 than before.

**Comment by liamdebeasi** [comment]
@gant02 Please provide a reproduction case so I can test.

**Comment by gant02** [comment]
Hello @liamdebeasi , 

code reproduction is available here: [https://github.com/gant02/test_standalone.git](https://github.com/gant02/test_standalone.git)

Ion-textarea is added in the main bundle instead of dedicated chunk although it's in a specific standalone component.

**Comment by liamdebeasi** [comment]
This isn't an Ionic bug. The Angular CLI opted to put this into the `main.js` chunk by default. There may be options to change which chunk this is added to, but Ionic doesn't control this.

This thread is dedicated to identifying Ionic components that are **not** being used in an application but are still being included in the bundle. Textarea is included in the bundle because you are using it in your application.

**Comment by gant02** [comment]
Oh ok so i misunderstood the interest of this feature, i thought that it would remove unnecessary components but keep the lazy loading feature/chunks. Project size is lower but main.js is bigger.

If a component is needed, angular CLI automatically add it in the main.js (and i don't see how to correct that) which is bad for a web app (but ok for a mobile app). 
With the IonicModule, angular CLI create specific chunk for each components so it's lazy loaded when needed.

So clearly this feature should be avoided for a web app. Maybe you can add this drawback in your docs? it would avoid me this migration if i knew it before.

But thanks for the explanation, i will stop looking for a solution and revert my code.

**Comment by liamdebeasi** [comment]
> Oh ok so i misunderstood the benefits of this feature, i thought that it would remove unnecessary components but keep the lazy loading feature/chunks. Project size is lower but main.js is bigger.

Thanks for the clarification with your project. We don't plan to note how the `main.js` chunk will change because that will vary per-app based on a) your Angular configuration, b) how many components you are using, and c) which bundler you are using (Webpack or ESBuild). Stating that the `main.js` chunk will always grow or shrink in size may be misleading.

----

That being said, the fix for the original bug has been merged in https://github.com/ionic-team/ionic-framework/pull/28359. This fix will be available in an upcoming release of Ionic. Thanks again!
