### ISSUE TITLE
bug:  v1 anchorScroll curElm.attributes error

### ISSUE THREAD

**Issue by rolinger** [ionic-team/ionic-framework#28355]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v4.x

### Current Behavior

I know this is v1, but the Ionic-v1 github is archived and I cannot open/submit an issue to it.  I am hoping someone here can help.

I am not using `collection-repeat` which is highlighted in this issue: https://github.com/ionic-team/ionic-framework/issues/3547 

I am using an ng-repeat that is listing about 160 options in a modal.  This is the first time my app needed to load more than 10 options so I had never seen this error before...but this time, with 160 options I am now getting the below error.   I have found NO other reference to anyone ever experiencing this error so I am really at a loss as to how troubleshoot this OR put in a work around

```
Exception = null is not an object (evaluating 'curElm.attributes')
Stack = @ionic://attendago/lib/ionic/js/ionic.bundle.js:60723:22
[processQueue@ionic://attendago/lib/ionic/js/ionic.bundle.js:29132:30](mailto:processQueue@ionic://attendago/lib/ionic/js/ionic.bundle.js:29132:30)
@ionic://attendago/lib/ionic/js/ionic.bundle.js:29148:39
[completeOutstandingRequest@ionic://attendago/lib/ionic/js/ionic.bundle.js:19199:15](mailto:completeOutstandingRequest@ionic://attendago/lib/ionic/js/ionic.bundle.js:19199:15)
@ionic://attendago/lib/ionic/js/ionic.bundle.js:19475:33
```

Which traces to this section of code:

```
  self.anchorScroll = function(shouldAnimate) {
    self.resize().then(function() {
      if (!scrollView) {
        return;
      }
      var hash = $location.hash();
      var elm = hash && $document[0].getElementById(hash);
      if (!(hash && elm)) {
        scrollView.scrollTo(0, 0, !!shouldAnimate);
        return;
      }
      var curElm = elm;
      var scrollLeft = 0, scrollTop = 0;
      do {
        if (curElm !== null) scrollLeft += curElm.offsetLeft;
        if (curElm !== null) scrollTop += curElm.offsetTop;
        curElm = curElm.offsetParent;  
      } while (curElm.attributes != self.element.attributes && curElm.offsetParent);  // ERROR HERE
      scrollView.scrollTo(scrollLeft, scrollTop, !!shouldAnimate);
    });
  };
```

### Expected Behavior

Scroll to work

### Steps to Reproduce

A long list of ng-repeat (over 100 items) in a modal.

### Ionic Info

Ionic:

   Ionic CLI         : 6.17.0 (C:\Users\rolin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 3.2.15

Cordova:

   Cordova CLI       : 11.1.0
   Cordova Platforms : android 11.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 28 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   Android SDK Tools : 26.1.1 (C:\Users\rolin\AppData\Local\Android\sdk)
   NodeJS            : v14.17.5 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.14
   OS                : Windows 10

**Comment by liamdebeasi** [comment]
Hey there,

This repo is dedicated to Ionic 4.0+. We do not maintain Ionic v1 anymore. I recommend posting on the [Ionic Forums]9https://forum.ionicframework.com/) if you need help with your Ionic v1 app.
