### ISSUE TITLE
bug: [v7.5] ion-radio-group doesn't work with variables with standalone components

### ISSUE THREAD

**Issue by petrot** [ionic-team/ionic-framework#28356]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.5

### Current Behavior

I refactored my app to use the new _**standalone**_ components. I found, that the radio-group doesn't work, if the "value" property comes from a variable.

I forked the original demo code from stackblitz, here is my updated code: https://stackblitz.com/edit/angular-vquurr

You can see: when we pass the value property from a variable, it doesn't work. With simple string, it works as expected.

### Expected Behavior

The radio group works as it works with module based version.

### Steps to Reproduce

See my code

### Code Reproduction URL

https://stackblitz.com/edit/angular-vquurr

### Ionic Info

Ionic 7.5

**Comment by medbenmakhlouf** [comment]
@liamdebeasi , is there any update on this issue please ? Thanks

**Comment by liamdebeasi** [comment]
Someone from the team will post on this thread when it is resolved. If someone has not posted here yet then it means we don't have an update.

**Comment by thetaPC** [comment]
We've fixed the problem, and you'll see the solution in an upcoming release. If you're excited to try it early, you can use the dev build: `npm install @ionic/angular@7.5.4-dev.11699404450.136700d7`

**Comment by thetaPC** [comment]
This issue was fixed in [v7.5.5](https://github.com/ionic-team/ionic-framework/releases/tag/v7.5.5)! Please update to the latest version to receive the fix.
