### ISSUE TITLE
bug: Stacked modals with breakpoint does not remove backdrop and shows wrong content

### ISSUE THREAD

**Issue by graphefruit** [ionic-team/ionic-framework#28357]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If you have an application which is using stacked modals and you open up the second modal, and dismiss this, the ion-backdrop overlay is still visible.
After clicking into the application, the backdrop disappears

### Expected Behavior

Like on Ionic 6 it already worked, with stacked modals, the backdrop is removed and the application doesn't have a shaded backdrop.

### Steps to Reproduce

1. Open https://stackblitz.com/edit/angular-tt8kjj-cpe7o1?file=src%2Fapp%2Fexample.component.ts
2. Click Open Modal
3. Click "Open Another"
4. Click "Close me"
5. You'll see the backdrop still existing, and is removed after some seconds or when you click inside it.

### Code Reproduction URL

https://stackblitz.com/edit/angular-tt8kjj-cpe7o1?file=src%2Fapp%2Fexample.component.ts

### Ionic Info

[@angular/animations](https://www.npmjs.com/package/@angular/animations)
16.0.1

[@angular/common](https://www.npmjs.com/package/@angular/common)
16.0.1

[@angular/compiler](https://www.npmjs.com/package/@angular/compiler)
16.0.1

[@angular/core](https://www.npmjs.com/package/@angular/core)
16.0.1

[@angular/forms](https://www.npmjs.com/package/@angular/forms)
16.0.1

[@angular/platform-browser](https://www.npmjs.com/package/@angular/platform-browser)
16.0.1

[@angular/platform-browser-dynamic](https://www.npmjs.com/package/@angular/platform-browser-dynamic)
16.0.1

[@angular/router](https://www.npmjs.com/package/@angular/router)
16.0.1

[@ionic/angular](https://www.npmjs.com/package/@ionic/angular)
7.5.0

[@ionic/core](https://www.npmjs.com/package/@ionic/core)
7.5.0

[rxjs](https://www.npmjs.com/package/rxjs)
7.8.1

[tslib](https://www.npmjs.com/package/tslib)
2.5.0

[zone.js](https://www.npmjs.com/package/zone.js)
0.13.0

### Additional Information

This worked without issues on Ionic 6.
When passing the 'animated:false' property, it works - so there needs something to be in the animation itself.

Also this just exists when using an overlay with breakpoints, without using breakpoints this works.

I tested it in chrome and safari, both same behaviour.

This is how it looks after dismissing the second modal:
<img width="1042" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/6260244/3e610bb0-4efb-4330-9331-1166af51cfce">

And thats what it should like after dismissing the second modal:
<img width="948" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/6260244/a167bf23-56b7-4bdb-8a6b-5150053ba9ef">

**Comment by liamdebeasi** [comment]
Thanks for the report. I'm not able to reproduce this on my end:

https://github.com/ionic-team/ionic-framework/assets/2721089/5de1d21d-4235-46a1-857d-475203a15377

I tested this in both Chrome 118 and Safari 17.

**Comment by graphefruit** [comment]
Hey @liamdebeasi, 
thanks for your fast response, thats super strange.
I have the same Chrome: 
<img width="358" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/6260244/a2780916-8bb5-4aea-a45c-9e74f6da846f">
And same Safari - But with safari I cant test it, because the Stackblitz is not working actually :<
<img width="235" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/6260244/7603d815-b9d2-453b-9ebd-097412b8ca7b">

I've also invalidated my cache on my Google Chrome - still doesn't work. 

Also I can reproduce this issue on my Google Pixel 2, which is using Google Chrome: 117.0.5938.115.
![WhatsApp Image 2023-10-16 at 20 08 44](https://github.com/ionic-team/ionic-framework/assets/6260244/efbf38cf-859d-4d0d-baff-10d3a97745c1)

The App (Beanconqueror) is using the latest Android System Webview 117.0.5938.153

I've attached you also a video how it looks on my system:
(Low quality, please make full size) 
https://github.com/ionic-team/ionic-framework/assets/6260244/bec0069b-a24c-4ca4-8e76-56e4b46ce2ad

When I use the mode: ios, its working aswell, but not with md.

https://github.com/ionic-team/ionic-framework/assets/6260244/f784f487-1e48-461d-852c-9166be104c05

My whole app is just using the MD mode so its still the issue there.

I've also just installed the latest EDGE, with this I don't have this issue aswell.


Any other possibility to help you out to reproduce this?
I just could let you set up my whole open source app, and guide you the way to trigger it there, but this means a lot more invest actually :O
Thanks 
Lars

**Comment by graphefruit** [comment]
Update: I've also just installed Safari Technology Preview - with this I didn't get this issue aswell.
So there must be something with Chrome and with the Animation thing. - Because like I wrote when I  set `animated:false` the issue does not appear

**Comment by liamdebeasi** [comment]
Is there a version of Ionic where this worked as expected?

**Comment by graphefruit** [comment]
It worked flawless on Ionic 6 (for some years now), i started upgrading my whole application to ionic 7 and this started yes.
I firstly thought it just would be a developing issue, but even when building my app --prod it appeared, so i digged deeper.

The stackblitz example is also on Ionic 7.5

**Comment by graphefruit** [comment]
Another thing I can add:
I've just tested from the docs the custom animation: https://ionicframework.com/docs/api/modal#animations
When I add the enter AND the leave animation it works. 
When I just add the enter but NOT the leave animation, it doensn't work. And shows the backdrop again.
When I don't add the enter but the leave animation it works.

So there must be something with the leaveAnimation, which is doing crazy things.

Also to mention: still going down to like 50ms animation time with the custom animations it works. (Even 1ms animation is working).

Is there any possibility to stack the CSS maybe which is doing the animation to hack a bit there?

**Comment by liamdebeasi** [comment]
There's not much the team can do if we can't reproduce the issue. Since you are updating across a major version, I'd try and isolate the exact version that this started happening in.

I'd start by testing the latest version of Ionic 6. If the issue does not reproduce, then update to Ionic 7.0.0. If the issue still does not reproduce then install the next minor release (Ionic 7.1.0). Once you reach a point where the issue reproduces, you'll need to install patch releases to find the exact version where the behavior changed.

**Comment by liamdebeasi** [comment]
Hey there,

I'm able to reproduce this. I could not reproduce this before because this issue reproduces only in Chrome and I was using Brave (Chromium-based). I'm going to merge this with https://github.com/ionic-team/ionic-framework/issues/28378. Please this thread for any updates.
