### ISSUE TITLE
bug: chrome, modals being cut off

### ISSUE THREAD

**Issue by 2K9FTwsc6Dt6** [ionic-team/ionic-framework#28378]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The backdrop area covered by a second sheet modal (controller or inline) remains partially visible and content is cropped when closing it and using `onWillDismiss` to handle data to the first sheet modal where it changes a reactive state:

![image](https://github.com/ionic-team/ionic-framework/assets/131704054/4d39cb1b-e990-4111-b7a8-5a0b70b6a89d)

![image](https://github.com/ionic-team/ionic-framework/assets/131704054/852d9f2a-82bc-472f-87ed-047b22bc6d04)

### Expected Behavior

The backdrop disappears completely and the content of the first sheet modal is not cropped like when using `onDidDismiss`:

![image](https://github.com/ionic-team/ionic-framework/assets/131704054/c7370207-174c-4dd6-a7b0-f3e399eac74e)

### Steps to Reproduce

Reproducible in Chrome 118 under Windows 10 (real hardware) and macOS Sonoma (BrowserStack).
In BrowserStack under Windows 10/11 this happens sometimes and sometimes not.
Not reproducible under Ubuntu 23.10 (VMware).
Turning Chrome hardware acceleration on/off does not change the behavior.
Safari and Firefox seem to be not affected.

**Maximum window width: 767px.**

The Chrome device emulation mode may not work, though it sometimes does work as well.
The Chrome device emulation mode sometimes leads to a window with blurry fonts (despite working with 100%) - these are exactly the times when this issue is not reproducible with the demo app!

**Please run the demo app from the repository below:**

1. Click one of the two buttons (both work): 
![image](https://github.com/ionic-team/ionic-framework/assets/131704054/04cd107c-d236-4b91-90c0-a4cc1e19fcb5)
2. Click the **Open Modal 2** button:
![image](https://github.com/ionic-team/ionic-framework/assets/131704054/3a7db592-3d7a-4b5f-87ff-a36c10dda0c4)
3. Click the **Confirm using "onWillDismiss" with data (bug)** button:
![image](https://github.com/ionic-team/ionic-framework/assets/131704054/36733841-04b1-44a9-900e-f753d62f2be9)
4. The result is a cropped first sheet modal with seemingly a remaining backdrop covering the area:
![image](https://github.com/ionic-team/ionic-framework/assets/131704054/85e48cf0-a87b-41f0-ac1b-2ed4c2420f24)

### Code Reproduction URL

https://github.com/2K9FTwsc6Dt6/stacked-modal-backdrop

### Ionic Info

**Ionic:**

Ionic CLI: 7.1.1 (C:\Users\...\scoop\persist\nodejs-lts\bin\node_modules\@ionic\cli)
Ionic Framework: @ionic/vue 7.5.0

**Capacitor:**

Capacitor CLI: 5.5.0
@capacitor/android: not installed
@capacitor/core: 5.5.0
@capacitor/ios: not installed

**Utility:**

cordova-res: not installed globally
native-run: 1.7.3

**System:**

NodeJS: v18.18.2 (C:\Users\...\scoop\apps\nodejs-lts\current\node.exe)
npm: 9.8.1
OS: Windows 10

### Additional Information

Maybe related to #28357 which shows a similar behaviour, but obviously under more general circumstances...

**Comment by clxx** [comment]
Maybe related to #28384 as well?

**Comment by 2K9FTwsc6Dt6** [comment]
Maybe related to #28384 as well?

**Comment by 2K9FTwsc6Dt6** [comment]
This happens down to at least Ionic 6.0.0 (which is the oldest version I tested, so I cannot make any assumptions on earlier versions).

**Comment by 2K9FTwsc6Dt6** [comment]
The mere presence of the Animation developer tools in Chrome makes a difference and prevents the glitchy behaviour:

https://github.com/ionic-team/ionic-framework/assets/131704054/66a0b13d-d0a5-4350-85df-7e76601af7e2

**Comment by 2K9FTwsc6Dt6** [comment]
For my colleague, switching from onWillDismiss to onDidDismiss didn't work at another spot. Where exactly this glitch occurs seems to be rather random...

**Comment by liamdebeasi** [comment]
It looks like this happens specifically in Chrome (I was using Brave which is Chromium based). I can reproduce the reported behavior, but it looks like this is a Chrome bug not an Ionic bug. I'll look into getting this issue reported to the Chrome team.

**Comment by graphefruit** [comment]
> It looks like this happens specifically in Chrome (I was using Brave which is Chromium based). I can reproduce the reported behavior, but it looks like this is a Chrome bug not an Ionic bug. I'll look into getting this issue reported to the Chrome team.

Thank you @liamdebeasi, super happy you could reproduce it! I was still working on how to get it to you.


<3 Big thanks!

**Comment by liamdebeasi** [comment]
Hi everyone, 

The Chrome team disabled the feature that caused this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1494045

You'll need to restart your browser to see any changes. Thanks for reporting this!
