### ISSUE TITLE
bug: MD inconsistency: ion-item height is different with some children

### ISSUE THREAD

**Issue by cmaas** [ionic-team/ionic-framework#28388]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In v7, some elements have a new mode that get their labels as props such as: `ion-input`, `ion-select`. This "non-legacy" mode sets their `min-height` to 56px (why though?), see here: https://github.com/ionic-team/ionic-framework/blob/c801e2ada9d1f36bbb8ed58d814afae94510e304/core/src/components/select/select.md.scss#L23

However, other elements such as `ion-toggle` or `ion-label` (used for navigation in an `ion-item`) do not have a label prop and hence, don't have this rule applied. This results in inconsistent vertical spacing. See the demo linked below.

### Expected Behavior

1. Make spacing consistent
2. Revert (or explain) the choice of setting a, imho, rather unpleasant min-height of 56px.

### Steps to Reproduce

See demo

### Code Reproduction URL

https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA87KAD4AOnQAEU4RAZIJ0mbPhl4MUQEleZWFIAqEMPEEB6NRohKVssLABOZAA7wp8AJ7OIAXnEhcbiQAVxh-KTAHWD8QHHhnMFQzM1gkOgwAKzAkaDIANwcMOgh4MzpnXDMAATJdWBTuBwgzJDITM1q6PQ66jGNcTLB-UXN7J1cbFUEoMjoAaykmqBiTD0osCBLwrCaSGLiEpJS0wZyZgqKSsorqzu6eJpSwMB6u2AwAI2C6JBgMWGe4TMk3MGwUSkEHyCHhBnQAtGCcg5JrZBPD4NxuFAPgwHFIeFBGjFnE5cLiPMNJLZqbJ0epNAAJbjMcx0qwoqavOEYrE45FU2RcxEQfnKNG8OE8PgQPj4qAMZ4xeHOBStOgAc0pylRzlEAHVoDxmO5uFIAMr8WAUKQAQWcznN8FxiEK5l1AtR8JmJg5NPFdDh6gguF9NKm8NmzmCbnlH2gMQAmtxgnjGMaABQAVgAbM4AB4ASnCnm8MUQefgw1ZEsj0dDqK5QZDHrD-sDiGb2rDnpr5WjUlj8f8SZTUjTECkWdzheLXl8-nLlZAI0bffg9c5EY7G5kbabI3R3HV6s0BiPJ4n8CwbUnABYABz5gvVgMY4+aF-t4M72k1jtSHInQoMsHGCCBtl2GIzBJbhyBgV49C1bs-S9Bg4zEAAFBxYIoCcMIYdUJ3TB8n0-QcxBbP1G23SjqT3Giu27NtIBgBABzQocQAAEQgEgGFCGMOKgSccyfcJnHlWAICwLEkRiAAxBg8kaIMpHk0D1CQ5CewDFi4HgOFuFcTopDyBgoDAmIGHtMJlztCSIE-PSEEM4zeB-HS4WcgyjLUXhTPMyz-BxRhGGGAAhBhQoYJzoH01y-LoDzwwlbyEpMsyLPnEBGiiwjhgAeQcPLHK5NLfM6ZLYtY9daIbLdv20mRaLItparFLkpX4drzChJAYUkUE8AouhJE4bzOiodAACZs1QTMAAYQAAX0IegmBYdBBk4LqZXgVgVrWkBx1Yf5nh23huoO5aAF1lqAA

### Ionic Info

CDN bundle current version

**Comment by liamdebeasi** [comment]
Thanks! Can you give this dev build a try? `7.5.2-dev.11697810676.1a4f965d`

I think the problem was we originally added `min-height: 56px` to align with the Material Design spec for the outlined/solid inputs. However, we accidentally applied it in the general MD stylesheet rather than the stylesheets specifically for the outline/solid inputs.

**Comment by cmaas** [comment]
> Thanks! Can you give this dev build a try? `7.5.2-dev.11697818830.1a33c881`

Looking good, thanks! [Demo](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA87KAD4AOnQAEU4RAZIJ0mbPhl4MUQEleZWFIAqEMPEEB6NRohKVssLABOZAA7wp8AJ7OIAXnEhcbiQAVxh-KTAHWD8QHHhnMFQzM1gkOgwAKzAkaDIANwcMOgh4MzpnXDMAATJdWBTuBwgqgHYMAFYMACYAWhy8jABGQYA2AE4WgA5BycmAZgAGIYY5udhZwbMkMhMzWro9PbqMY1xMsH9Rc3snVxsVQSgyOgBrKSaoGJMPSiwIEvCWCaJBicQSSRSaXOOSeBSKJTKFWq+0OPCarQ63T6EAGw3GUxm8yWgxWaw2KTAYCOB1gGAARsE6EgYBhYJTwmZ7uY-golII6UEPFz9j0eTkHPdbIIRfBuNwoHSGA4pDwoI0Ys4nLglR5LpJbAbZDL1JoABLcZjmY1WSUPak9WXyxUS-Wye1iiAu5TS3g9Hh8CB8FVQBiUmIi5wKbZ0ADmeuUUucogA6tAeMx3NwpABlfiwChSACCzmcOfgSsQhXMSddUpFTxMtsNProPXUEFwTcNDxFz2cwTcIbp0BiAE1uMFlYwMwAKdojZwADwAlOFPN4YohF-BLlbfX2B12pfb253a92W23EGeE926-vygOpEOR-5x5OpNOIFI5wuV2uvF8fwtx3EArhPR94CPO1e2vaCZEvU8rhlbgYxjTQDFQ9Dv3gLAdh-AAWSYl2XPdW1lNDNDIq8O3go192vKQcnLChNwcYIIEBYEYjMTVuHIGBqT0eM72besGGHMQAAUHH4ihvykhgY2-GciJI6iXzEc9mxPODtINRC9NvO9L0gGAEGfCTXxAAARCASAYUJBysqAf3nEjwmcENYAgLB5XFGIADEGDyRp2ykQL2PUETRPvVszLgeAem4Vx9ikPIGCgDiYgYEswjA4svIgaiEoQZLUt4Oi4p6UqkpStReHSzLsv8RVGEYS4ACEGHahgSugRLyoaugqp7X1aqGtKMqyoCQEaHrlMuAB5BwFuK+0Jvq-ZRv68yoP049YNo2KZH0jSdn2717X9fhLvMAUkCFSRuTwLS6EkThav2Kh0AI1BJgWEAAF9CHoJgWHQc5OBuwN4FYYHQZAL9WFZSlod4W74aBgBdIGgA)

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28390, and a fix will be available in an upcoming release of Ionic Framework.
