### ISSUE TITLE
bug: content is scrollable when opening menu on ios

### ISSUE THREAD

**Issue by arthurrmp** [ionic-team/ionic-framework#28399]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I'm able to reproduce the issue #21193 on my iPhone with a fresh project created using ionic start using @ionic/angular@7.5.1

But this should be fixed on PR #26976, so I'm opening this issue.

### Expected Behavior

To achieve the desired result, I added 'overflow-y: hidden' to the 'menu-content-open' class in my global.scss file. If necessary, I'd be happy to submit a pull request to include this change in [core.scss](https://github.com/ionic-team/ionic-framework/blob/60f3d6579498ebad75c4f5163fca3947ac2dadff/core/src/css/core.scss#L259) as well.

global.scss
```scss
.menu-content-open {
	overflow-y: hidden;
}
```

### Steps to Reproduce

1. create a new project with sidemenu template
2. install and open on an iPhone 
3. try to scroll down the main content while opening the side menu

https://github.com/ionic-team/ionic-framework/assets/44805300/91b00917-6cab-4313-93f8-9fad9c7ef007

### Code Reproduction URL

https://github.com/arthurrmp/sidemenu-test

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/arthur/.nvm/versions/node/v18.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.1
   @angular-devkit/build-angular : 16.2.7
   @angular-devkit/schematics    : 16.2.7
   @angular/cli                  : 16.2.7
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : not installed
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.16.0 (/Users/arthur/.nvm/versions/node/v18.16.0/bin/node)
   npm    : 9.5.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Here's a dev build with a proposed fix if you are interested in testing: `npm install @ionic/angular@7.6.5-dev.11705341148.1a550d3b`

**Comment by arthurrmp** [comment]
> Here's a dev build with a proposed fix if you are interested in testing: `npm install @ionic/angular@7.6.5-dev.11705341148.1a550d3b`

Thank you @liamdebeasi! I will check it out

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28829, and a fix will be available in an upcoming release of Ionic Framework. Feel free to keep testing the dev build, and let me know if you run into any issues.
