### ISSUE TITLE
bug: alert text does not break words when wrapping

### ISSUE THREAD

**Issue by csaar95** [ionic-team/ionic-framework#28406]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Long options aren't truncated and the "selected" icon is moved out to the left side.

<img width="332" alt="Bildschirmfoto 2023-10-25 um 10 34 10" src="https://github.com/ionic-team/ionic-framework/assets/40690270/22b0f5ef-d99e-475a-b4d0-a459d6ccc61d">
<br />
<img width="274" alt="Bildschirmfoto 2023-10-25 um 10 33 55" src="https://github.com/ionic-team/ionic-framework/assets/40690270/33979cab-1712-4291-bdd9-69329690a559">

### Expected Behavior

Long options should truncate (or wrap).

### Steps to Reproduce

```tsx
<IonItem>
  <IonSelect
    label="Favorite fruit"
    labelPlacement="floating"
    value="banana"
  >
    <IonSelectOption value="apple">Apple</IonSelectOption>
    <IonSelectOption value="banana">Babababananaaaaaaaaaaa</IonSelectOption>
    <IonSelectOption value="orange">Orange</IonSelectOption>
  </IonSelect>
</IonItem>
```

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.5.1

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : 5.5.0
   @capacitor/core    : 5.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.4

System:

   NodeJS : v18.18.2 (/opt/homebrew/Cellar/node@18/18.18.2/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the report. The problem here is text should be wrapping to the next line. We don't truncate text to keep the text readable for accessibility purposes. We do have text wrapping built in, however we do not break words to wrap to the next line (we break on whitespace though).

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28408, and a fix will be available in an upcoming release of Ionic Framework.
