### ISSUE TITLE
feat: ion-modal sheet handle background color

### ISSUE THREAD

**Issue by stevexm** [ionic-team/ionic-framework#28413]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Setting the background color of the ion-modal sheet handle. Currently the handle color is fixed and set using the css variable: --ion-color-step-350 (a medium gray).

### Describe the Use Case

While the medium-gray handle color works for most themes, it can clash with others or not provide enough contrast against the ion-toolbar background where the handle is embedded. This is the case in my application, a clash with the app theme.

### Describe Preferred Solution

A new css variable specific to the background color of the ion-modal sheet handle.

Instead of the current:
`
.modal-handle {
    ...
    background: var(--ion-color-step-350, #c0c0be);
}
`
maybe a new css variable:, --ion-handle-background-color:
`
.modal-handle {
   ...
    background: var(--ion-handle-background-color, var(--ion-color-step-350, #c0c0be));
}
`

### Additional Information

Thank you, Steve

**Comment by liamdebeasi** [comment]
Thanks for filing a feature request! We currently expose the handle using the `handle` shadow part which allows you to customize the color.

Example usage:

```css
ion-modal::part(handle) {
  background: red;
}
```

Here's a demo of what it looks like: https://codepen.io/liamdebeasi/pen/ZEwGMQr

I am going to close this since this functionality already exists in Ionic, but let me know if you have questions.
