### ISSUE TITLE
bug: last `ion-item-sliding` should not have a `border-bottom`

### ISSUE THREAD

**Issue by mrleblanc101** [ionic-team/ionic-framework#28435]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The last item has a border bottom if they are `ion-item-sliding` but not if they are `ion-item`.
![Screenshot 2023-10-30 at 3 02 13 PM](https://github.com/ionic-team/ionic-framework/assets/17392251/f54a3d13-0247-453c-b957-0fc537f568e4)

### Expected Behavior

The last item should not have a border bottom if they are `ion-item-sliding`, just like `ion-item`.
![Screenshot 2023-10-30 at 3 02 06 PM](https://github.com/ionic-team/ionic-framework/assets/17392251/6ad8893a-5ac0-45a2-b38a-02f25e74b760)

### Steps to Reproduce

Make two inset list, one with `ion-item-sliding` and one with regular `ion-item`.
The ion-item-sliding one will have a border-bottom on the last element, while the ion-item list won't have a border-bottom on the last element.

### Code Reproduction URL

https://stackblitz.com/run?file=package.json

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/sleblanc/.nvm/versions/node/v16.19.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.5.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : not installed
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.4) : 1.7.3

System:

   NodeJS : v16.19.1 (/Users/sleblanc/.nvm/versions/node/v16.19.1/bin/node)
   npm    : 8.19.3
   OS     : macOS Ventura 14.1

**Comment by liamdebeasi** [comment]
Thanks for the report. Here is a dev build if you are interested in testing a proposed fix: `7.5.3-dev.11698760841.12aff234`

Install Example: `npm install @ionic/vue@7.5.3-dev.11698760841.12aff234 @ionic/vue-router@7.5.3-dev.11698760841.12aff234`

**Comment by mrleblanc101** [comment]
@liamdebeasi I confirm this fix the issue

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28439, and a fix will be available in an upcoming release of Ionic Framework.
