### ISSUE TITLE
Cannot install latest version of Ionic from npm even with the @latest tag

### ISSUE THREAD

**Issue by nourkrimesh** [ionic-team/ionic-framework#28449]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I'm trying to update ionic version to the latest 7.5
but when i first run the command
npm install @ionic/cli
the version 7.1.1 is installed instead
then i tried to run this one
npm install @ionic/cli@latest
and still give me the version 7.1.1

I also tried to remove ionic and reinstall it again but it still getting the version 7.1.1

### Expected Behavior

updating to the latest version of ionic which is 7.5 right now.

### Steps to Reproduce

npm i @ionic/cli@latest

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.3
   @angular-devkit/build-angular : 16.2.5
   @angular-devkit/schematics    : 16.2.5
   @angular/cli                  : 16.2.5
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.4.2
   @capacitor/android : not installed
   @capacitor/core    : 5.4.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.18.0 (/usr/local/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Hey there, 

You are trying to install the Ionic CLI, not Ionic Framework.

The latest version of the Ionic CLI is v7.1.1: https://www.npmjs.com/package/@ionic/cli
The latest version of Ionic Framework is v7.5.3: https://www.npmjs.com/package/@ionic/core

It looks like you are using Ionic Angular, so you should be installing `npm install @ionic/angular` to get the latest version of Ionic Framework.
