### ISSUE TITLE
bug: `ion-input`'s `onIonInput` has different behaviour with decimals when `type="number"` on Safari.

### ISSUE THREAD

**Issue by raymondctc** [ionic-team/ionic-framework#28454]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Whenever a valid decimal place is input to `ion-input` component, `onIonInput` listener will always yield an empty string on Safari. This does not happen on Chromium or Firefox.

### Expected Behavior

`onIonInput` should yield the integral part of the intermediate input if the input is still a valid number instead of yielding an empty string.

### Steps to Reproduce

1. Create an `IonInput` component
2. Set `type="number"`, add `onIonInput` 
3. Type e.g. `1.` into the input and log the result

### Code Reproduction URL

```
          <IonInput
            size={1}
            min={0}
            type="number"
            errorText="Error"
            onIonInput={(input) => {
              console.log("IonInput, value=", input.target.value);
            }}
          />
```

### Ionic Info

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.7.3) : 1.7.2

System:

   NodeJS : v20.8.0
   npm    : 10.1.0
   OS     : macOS Unknown

### Additional Information

The one on left is Safari, right one is Firefox
https://github.com/ionic-team/ionic-framework/assets/13764117/16a84e75-4b52-4f99-bfad-10d453b51fe6

**Comment by liamdebeasi** [comment]
Hey there! Interestingly enough I ran into this a few weeks ago. This behavioral difference isn't something Ionic controls, and it happens with a regular `<input />` element too.

Here's a demo outside of Ionic: https://codepen.io/liamdebeasi/pen/dywNWoo

As far as I understand, the main problem is typing "1." is not a valid number, so browsers need to account for that. In Firefox/Chrome they will provide the last valid number which is "1" in this case. Safari, on the other hand, provides the empty string (`''`). This is not an Ionic bug, so I am going to close this. Let me know if you have questions.
