### ISSUE TITLE
bug: md, the back and search buttons are not aligned

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#28468]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hello,

It's a small design detail, in MD when you have a title with the back button and a search engine below, which are both a backwards arrow, they are not aligned and produces a slightly unpleasant visual effect.

<img width="137" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/18282247/ab258352-278e-49af-a68e-cf00b124ffd0">

greetings!

### Expected Behavior

That they are fully aligned.

### Steps to Reproduce

Put two ion-toolbar inside an ion-header, one with an ion-back-button and another with an ion-search.

### Code Reproduction URL

https://stackblitz.com/edit/angular-ygu7bs?file=src%2Fapp%2Fexample.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1
   Ionic Framework               : @ionic/angular 7.5.3
   @angular-devkit/build-angular : 16.2.9
   @angular-devkit/schematics    : 16.2.9
   @angular/cli                  : 16.2.9
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v20.9.0
   npm    : 10.1.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. It looks like this gradually regressed since v4.

v4: https://codepen.io/liamdebeasi/pen/vYbgWmo
v5: https://codepen.io/liamdebeasi/pen/LYqxOWq
v6: https://codepen.io/liamdebeasi/pen/zYeNPZa
v7: https://codepen.io/liamdebeasi/pen/ExrZbWp

**Comment by liamdebeasi** [comment]
Here's a dev build if you are interested in testing: `7.5.4-dev.11699310489.151b2717`

**Comment by Marius-Romanus** [comment]
Yes, it looks centered now, thank you very much!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28478, and a fix will be available in an upcoming release of Ionic Framework.
