### ISSUE TITLE
feat: `readonly` property on `ion-select`

### ISSUE THREAD

**Issue by oliveryasuna** [ionic-team/ionic-framework#28463]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

There is a closed issue: https://github.com/ionic-team/ionic-framework/issues/17439.

I think that this feature should be considered.
Isn't the point of the Ionic Framework to mimic the look-and-feel of iOS and Material?
Both iOS UI and Material UI support read-only select fields.

### Describe the Use Case

See above...

**Comment by liamdebeasi** [comment]
Hey there,

Do you have an example of native iOS and Material Design supporting the readonly select?

**Comment by oliveryasuna** [comment]
@liamdebeasi Hi Liam! Sorry, I do not have an example, I just know that I have filled out forms before on both UIs with read-only select/dropdown fields.

I think the use case is broad: Forms.

**Comment by liamdebeasi** [comment]
Hey there,

Thanks for the additional information. I spoke with the team, and we do not have plans to add this feature to Ionic. There are a few reasons:

1. We were not able to find a native equivalent which leads us to think this may not be recommended in mobile apps.
2. A readonly select may provide for a confusing user experience. There are two ways we can implement this:
  a. The select can be viewed, but clicking the select does not bring up a dialog. The behavioral difference between this readonly select and a disabled is select is minimal, and we're not confident this approach adds enough value Ionic Framework to warrant a new feature.
  b. The select can be viewed, and clicking the select brings up a dialog (alert, action sheet, etc) with disabled inputs. Buttons in dialogs such as action sheets should always be interactive, so we think disabling the buttons would make for a confusing user experience.
3. `readonly` is not supported on a native `select`: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly#overview 

In terms of a workaround, we recommend using a readonly input instead. I am going to close this, but let me know if you have any questions.
