### ISSUE TITLE
bug: IonContent in new Safari is not scrollable

### ISSUE THREAD

**Issue by DmitryBara** [ionic-team/ionic-framework#28461]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

My page have pretty straightforward structure:

```
const MyPage: React.FC = () => {
  return (
    <IonPage>
      <IonContent>
          ... some long content here
      </IonContent>
    </IonPage>
  );
};
```

it worked perfectly on a lot of platforms and browser.
But recently I updated my mac to OS Sonoma 14.1 and Safari to Version 17.1 (19616.2.9.11.7).

IonContent is not scrollable anymore. However other elements are scrollable (my custom divs for example).

### Expected Behavior

IonContent should be scrollable on every platform

### Steps to Reproduce

1. Install new OS and safari
2. Visit ionic application and try to scroll IonContent elements

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.9
   Ionic Framework : @ionic/react 7.4.2

Capacitor:

   Capacitor CLI      : 4.7.0
   @capacitor/android : not installed
   @capacitor/core    : 4.7.0
   @capacitor/ios     : 4.7.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
