### ISSUE TITLE
bug: Presenting element radius transition not working as expected

### ISSUE THREAD

**Issue by samuelrebuelta** [ionic-team/ionic-framework#28469]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

After updating to version 7.5.2, the element behind the modal does not make the border radius transition correctly.

https://github.com/ionic-team/ionic-framework/assets/31918772/dfb6298e-d7db-4f37-a6bb-69fde1d06359

### Expected Behavior

A smooth transition of border radius with no lag.

https://github.com/ionic-team/ionic-framework/assets/31918772/d7f22398-3d33-4311-8efa-9f739b8758aa

### Steps to Reproduce

Open a modal on iOS using the presentingElement attribute.

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1
   Ionic Framework               : @ionic/angular 7.5.2
   @angular-devkit/build-angular : 16.2.6
   @angular-devkit/schematics    : 16.2.6
   @angular/cli                  : 16.2.6
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : 5.5.0
   @capacitor/core    : 5.5.0
   @capacitor/ios     : 5.5.0

Cordova:

   Cordova CLI       : 12.0.0 (cordova-lib@12.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.3

System:

   NodeJS : v18.14.2
   npm    : 9.5.0
   OS     : macOS Unknown
   Xcode  : Xcode 15.0.1 Build version 15A507

**Comment by samuelrebuelta** [comment]
The only code needed to reproduce this is open a modal on iOS device: 
`await this.modalController.create({
      component,
      componentProps,
      id,
      canDismiss,
      backdropDismiss,
      presentingElement
    });`

**Comment by liamdebeasi** [comment]
I'm not able to reproduce this using the code snippet provided:

https://github.com/ionic-team/ionic-framework/assets/2721089/482680b2-8178-4bf3-91ee-24bbea000cfd

Can you please provide a full reproduction that I can use?

**Comment by samuelrebuelta** [comment]
It can only be played on an iOS device, but installed, not through the browser

**Comment by liamdebeasi** [comment]
Can you please provide a full reproduction that I can use as a standalone app?
