### ISSUE TITLE
bug: ion-range should not update value or lock scrolling until touchEnd or drag within the bar

### ISSUE THREAD

**Issue by cmaas** [ionic-team/ionic-framework#28487]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If you click/tap on an ion-range component somewhere on the bar (not on the knob), the knob will immediately jump to the place where you clicked or touched down. See video. The circle indicates the beginning of a click (onTouchStart):

![CleanShot 2023-11-07 at 21 05 54](https://github.com/ionic-team/ionic-framework/assets/6094364/829ab74d-a40e-4f98-865a-e1091f16095c)

This is "too sensitive", because it causes accidentally changing the ion-range value if the user just wants to scroll in some cases. In my app, there are several `ion-range` elements further down on the screen that get accidentally changed if the user merely wants to scroll.

On **native** iOS 17 and Android 14 UI elements, the behavior is different: if you touch down on the knob, you can start dragging it. But if you touch down on the bar somewhere else, the knob will move there only "onTouchEnd" when you lift your finger. This reduces the sensitivity of this element and prevents accidents. Furthermore, the value of the element will only be changed if you lift your finger while it's still hovering over it. If you touch down on the bar and move your finger somewhere else while keeping it touched down, the parent view starts to scroll vertically (most of the time at least).

The behavior is pretty consistent between native iOS and Android elements and feels quite off in Ionic.

### Expected Behavior

ion-range should mimic native behavior and trigger value adjustments only "onTouchEnd" and only, if the finger is still over the component. If the user touches down on the bar, but moves the finger to another place on the screen and lifts the finger there, ion-range value should not be changed.

### Steps to Reproduce

1. [Sample code](https://flems.io/#0=N4IgtglgJlA2CmIBcBmFA6ALANgDQgGd4EBjAF3imRHQAsyxYR8AzCBA5AbVADsBDMIiQ16jZiBIB7XhVnUAPGNgA+ADq8ABJqXx+UdVu06yEMghUBJGRBKaAKvAJkFAelPn4h4zoIkAThAADmSaZACeQfAAvGrgUlAArghxmgT+JLEg9GRBBEiuriRQvOgAVgRQxBAAbv7ovPBkrrxBYK4AAhA2JEVS-vCuUBDOrt28tmM96E5g5QRxKm5+gSHexgqwELwA1poDsFnO4Ry08E2ptAMsWTl5BUUl81VbdQ1NLW2d45PSA0UEAhTCYkdAAI0SvDg8HQJEBqVc6zcZ30hgUYIS4SR4wAtCiqv51j4FLiyFIpLAwfx-JppLB+lkgoEwNTwosND5OTpSWYLAAJKRCNw8zxEjbAnFkilUwkcnQS-HwWVGEkyHHSWTwWS02D8QFZXFBfTDXgAc3ZRmJQRUAHViNIhGEpJoAMpyEjsTQAQSCQVdZGpFHqbmtcqtaQiCFu8AgpvoSEwAAZE0EAB6LACy-B28E0NSVphI-FgaSNJFzZwGuDSAQpJagUgA7loggg9fAQ2LtKreDits4u5yezizPAwIOud3cf5+Gbc7qwcQca3+OWhLIjgH-GRUgviFkADL8Rcl-ihMhnf2BxbCtUzucT8W40fjsNPtX9siDhR+45RuJnLG8ZJim6YgCoWY5poYD9Lm+bbrYxalquFZKh2rihiqEoanIX4aG4GJQFi+GuMohgaBIRCkKYMicCIABMiZIAArAAnCAAC+uB8IIwg0BUEg4VqZDUJx3EgAIQjULCgKCTIuGiRxAC6HFAA) that gives you some vertical scrolling around `ion-range`.
2. Consider the **audio settings** on a real iOS or Android device to get a feeling for how a native range input should behave.

### Code Reproduction URL

[Here](https://flems.io/#0=N4IgtglgJlA2CmIBcBmFA6ALANgDQgGd4EBjAF3imRHQAsyxYR8AzCBA5AbVADsBDMIiQ16jZiBIB7XhVnUAPGNgA+ADq8ABJqXx+UdVu06yEMghUBJGRBKaAKvAJkFAelPn4h4zoIkAThAADmSaZACeQfAAvGrgUlAArghxmgT+JLEg9GRBBEiuriRQvOgAVgRQxBAAbv7ovPBkrrxBYK4AAhA2JEVS-vCuUBDOrt28tmM96E5g5QRxKm5+gSHexgqwELwA1poDsFnO4Ry08E2ptAMsWTl5BUUl81VbdQ1NLW2d45PSA0UEAhTCYkdAAI0SvDg8HQJEBqVc6zcZ30hgUYIS4SR4wAtCiqv51j4FLiyFIpLAwfx-JppLB+lkgoEwNTwosND5OTpSWYLAAJKRCNw8zxEjbAnFkilUwkcnQS-HwWVGEkyHHSWTwWS02D8QFZXFBfTDXgAc3ZRmJQRUAHViNIhGEpJoAMpyEjsTQAQSCQVdZGpFHqbmtcqtaQiCFu8AgpvoSEwAAZE0EAB6LACy-B28E0NSVphI-FgaSNJFzZwGuDSAQpJagUgA7loggg9fAQ2LtKreDits4u5yezizPAwIOud3cf5+Gbc7qwcQca3+OWhLIjgH-GRUgviFkADL8Rcl-ihMhnf2BxbCtUzucT8W40fjsNPtX9siDhR+45RuJnLG8ZJim6YgCoWY5poYD9Lm+bbrYxalquFZKh2rihiqEoanIX4aG4GJQFi+GuMohgaBIRCkKYMicCIABMiZIAArAAnCAAC+uB8IIwg0BUEg4VqZDUJx3EgAIQjULCgKCTIuGiRxAC6HFAA)

### Ionic Info

Latest via CDN

**Comment by amandaejohnston** [comment]
Thank you for the report! Looking into this, I agree that the experience could be improved. I've tested with the Volume settings on my Android device (video below) and come to the same conclusions as you. To summarize:

1. If the bar is tapped outside the knob, then released without dragging, the value only updates on touch end. (Ionic currently updates immediately on touch start.)
2. If the bar is tapped outside the knob, then dragged, the value will start updating. (This matches current Ionic behavior.)
3. If the bar is tapped outside the knob, but not dragged, the view can still be scrolled. (Ionic currently locks scrolling immediately on touch start.) At this point, if the touch is lifted while no longer on the range, the value is not changed.
4. If the bar is tapped outside the knob, then dragged, the view cannot be scrolled until the knob is released. (This matches current Ionic behavior.)

https://github.com/ionic-team/ionic-framework/assets/90629384/4ea10495-321a-4a8f-b6da-f7c97fb816de

**Comment by thetaPC** [comment]
Thanks for the issue! This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29005 and will be available in an upcoming release of Ionic.
