### ISSUE TITLE
bug: ion-menu change direction dynamically

### ISSUE THREAD

**Issue by Sagie501** [ionic-team/ionic-framework#28480]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When changing the `html` tag direction from `ltr` to `rtl` dynamically (`<html dir="rtl">...</html>`), the `ion-menu` on native devices opens on the wrong side. In addition, the gesture also works on the original direction.

### Expected Behavior

When changing the `html` tag direction from `ltr` to `rtl` dynamically (`<html dir="rtl">...</html>`), the `ion-menu` should opens on the correct side. In addition, the gesture also should work on the changed direction.

### Steps to Reproduce

The code for changing direction dynamically:
```typescript
@Component({
  selector: 'app-example',
  templateUrl: 'example.component.html',
  styleUrls: ['example.component.css'],
})
export class ExampleComponent {
  currentDirection: 'ltr' | 'rtl' = 'ltr';

  changeDirection() {
    if (this.currentDirection === 'ltr') document.documentElement.dir = 'rtl';
    else {
      document.documentElement.dir = 'ltr';
    }
  }
}
```

Check it on a native device.

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3
   Ionic Framework               : @ionic/angular 6.7.5
   @angular-devkit/build-angular : 14.2.6
   @angular-devkit/schematics    : 14.2.6
   @angular/cli                  : 14.2.6
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 5.0.3
   @capacitor/android : 5.0.3
   @capacitor/core    : 5.0.3
   @capacitor/ios     : 5.0.3

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.2

System:

   NodeJS : v18.18.0 (/Users/sagie.ivan/.nvm/versions/node/v18.18.0/bin/node)
   npm    : 9.8.1
   OS     : macOS

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
