### ISSUE TITLE
feat: Support Angular esbuild-builder to build Ionic production app

### ISSUE THREAD

**Issue by shessafridi** [ionic-team/ionic-framework#28500]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Ionic doesn't support the esbuild based Angular builder which is the default now for Angular 17 apps. When using the new builder the application doesn't run and throws a bunch of files now found errors.

### Describe the Use Case

We are forced to use the old builder with long build times and slow refreshes when using Ionic. 

### Describe Preferred Solution

Ionic should support the new esbuild based builder as it is the default for Angular now

**Comment by hakimio** [comment]
It does support `esbuild` if you use the [new standalone Ionic components](https://ionic.io/blog/announcing-ionic-7-5#:~:text=Since%20Ionic%20standalone%20components%20can%20be%20statically%20analyzed%2C%20developers%20will%20be%20able%20to%20make%20use%20of%20newer%20features%20in%20their%20Angular%20applications%20such%20as%20ESBuild.).

**Comment by liamdebeasi** [comment]
Hey there,

@hakimio is correct. We support ESBuild when using [Ionic standalone components](https://ionicframework.com/docs/angular/build-options#standalone). Ionic components using the `IonicModule` approach will not work with ESBuild because they cannot be statically analyzed.
