### ISSUE TITLE
bug: [v7.5] ion-accordion-group doesn't work with variables with standalone components

### ISSUE THREAD

**Issue by medbenmakhlouf** [ionic-team/ionic-framework#28506]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I refactored my app to use the new standalone components. I found, that the accordion-group doesn't work, if the "value" property comes from a variable.

I forked the original demo code from stackblitz, here is my updated code: https://stackblitz.com/edit/angular-vquurr-sddthd

You can see: when we pass the value property from a variable, it doesn't work. With simple string, it works as expected.****

### Expected Behavior

The accordion group works as it works with module based version.

### Steps to Reproduce

See my code

### Code Reproduction URL

https://stackblitz.com/edit/angular-vquurr-sddthd

### Ionic Info

v7.5

**Comment by liamdebeasi** [comment]
Thanks! Are you interested in submitting a PR for this? The fix should be to call `this.valueChanged()` in the `componentDidLoad` method on `ion-accordion-group`: https://github.com/ionic-team/ionic-framework/blob/d69ad434827ea56b777cc3af4e591362ce8bcd99/core/src/components/accordion-group/accordion-group.tsx#L78

**Comment by medbenmakhlouf** [comment]
Thanks @liamdebeasi ! just submitted a PR here : https://github.com/ionic-team/ionic-framework/pull/28510
