### ISSUE TITLE
bug: Card modal black background applied to entire body, not just app

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#28546]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When you present an Ionic card modal, the black background is applied to the entire `document.body`.

This can cause problems in light mode with resizing the `<ion-app>` for keyboard show/hide, for example. It causes a black area to be shown when the keyboard is being presented.

This will become a larger problem with Capacitor resize mode = "ionic" when https://github.com/ionic-team/capacitor-plugins/issues/1904 is resolved. (Currently, it's the black bottom area isn't shown because the app area doesn't resize until the keyboard is done animating.) I have found this problem because I am using a workaround to apply the keyboard resizing *before* the keyboard starts animation [here](https://github.com/ionic-team/capacitor/issues/1540#issuecomment-735221275).

### Expected Behavior

black background should be applied to `<ion-app>`

### Steps to Reproduce

1. Check out the repro
2. Add `margin-bottom: 300px` to `<ion-app>` to simulate keyboard resize mode `"ionic"`
3. Observe the bottom part of the document becomes black

### Code Reproduction URL

https://github.com/aeharding/ionic-drag

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/Users/aeharding/.nvm/versions/node/v20.8.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.5.5

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.8.1 (/Users/aeharding/.nvm/versions/node/v20.8.1/bin/node)
   npm    : 10.1.0
   OS     : macOS Unknown

### Additional Information

PR shortly!

**Comment by liamdebeasi** [comment]
Thanks for the report. I don't completely follow why this is an Ionic bug. Won't this behavior show up again once the device is in dark mode?

**Comment by aeharding** [comment]
> Thanks for the report. I don't completely follow why this is an Ionic bug. Won't this behavior show up again once the device is in dark mode (since the body and content background will be black)?

No, this bug doesn't apply (or at least, isn't that bad) in dark mode because the body is already black (or close to black), which makes Ionic's application of `background-color: black` to the body less apparent. I have some videos in #28547 demonstrating the problem, hopefully that helps!

**Comment by liamdebeasi** [comment]
I re-read your comment, and it sounds like this is only a problem if the behavior in the Capacitor Keyboard plugin is changed as per https://github.com/ionic-team/capacitor-plugins/issues/1904. Is that correct?

**Comment by aeharding** [comment]
@liamdebeasi That's correct, it's not currently a problem with Capacitor because the resize events wait for the keyboard to finish animating. However it is a problem with [if you use this workaround](https://github.com/ionic-team/capacitor/issues/1540#issuecomment-735221275) which is how I encountered this issue.

**Comment by RobertZetterlund** [comment]
I have a similar issue when opening keyboard inside of a card modal. Then I momentarily see through to the content behind the card modal. I am not using the workaround described in https://github.com/ionic-team/capacitor/issues/1540#issuecomment-735221275. 


https://github.com/ionic-team/ionic-framework/assets/31474146/8b4043b9-5a25-4704-a528-72a47b63af77

**Comment by liamdebeasi** [comment]
@RobertZetterlund This is unrelated to the reported issue. The problem described in this thread is users can see the background color of the body when adjusting how the keyboard plugin resizes the web view on iOS. Your demo shows the underlying page, not the body.

Ionic does not control the resize behavior of the webview. Adjusting when the webview resizes is best addressed with the Capacitor team.

**Comment by RobertZetterlund** [comment]
> @RobertZetterlund This is not the same issue. The problem described in this thread is users can see the background color of the body when adjusting how the keyboard plugin resizes the web view on iOS. Your demo shows the underlying page, not the body.
> 
> Ionic does not control the resize behavior of the webview. Adjusting when the webview resizes is best addressed with the Capacitor team.

Okay, thanks @liamdebeasi for letting me know!

**Comment by liamdebeasi** [comment]
Hey everyone,

According to https://github.com/ionic-team/ionic-framework/issues/28546#issuecomment-1819213801, this is only a problem in Ionic Framework if [this requested Capacitor change is made](https://github.com/ionic-team/capacitor-plugins/issues/1904). I'd like to hold off on considering this Ionic Framework change until the Capacitor team comes to a decision on whether or not they will make the related change on their end. I am going to close this as "Won't Do" for now, but the team is happy to re-evaluate if the Capacitor team decides to move forward with the requested change.
