### ISSUE TITLE
bug: ionic-vue (vite) - Service Worker in development mode is giving the error "Uncaught SyntaxError: Cannot use import statement outside a module." 

### ISSUE THREAD

**Issue by jandante** [ionic-team/ionic-framework#28554]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I've set up a blank Vite + Vite PWA plugin and created my own service worker. In development the docs state that you should set the config (vite.config.js) to these values to have service worker in dev mode:

```
    ...
    VitePWA({
      devOptions: {
        enabled: true,
        type: 'module'
      },
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.js',
  ...
```

When using the newly created Vite + Vite PWA plugin this works well.

However when I set up a new Ionic project I get the error "Uncaught SyntaxError: Cannot use import statement outside a module." 
At first I created an issue in the VitePWA repo https://github.com/vite-pwa/vite-plugin-pwa/issues/599 but after testing it's probably not related to VitePWA because like stated above in a newly created project without Ionic things work perfectly.

### Expected Behavior

I would expect the same behavior as in a normal Vite + Vite PWA project.

### Steps to Reproduce

1. You can clone this repo https://github.com/jandante/vite-pwa-sw-issue
2. Use chrome as your default browser (apparently only works with chrome)
3. Run 'ionic serve'
4. Chrome will give you the error and no service worker gets loaded.

### Code Reproduction URL

https://github.com/jandante/vite-pwa-sw-issue

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.5 (/Users/dante/Library/Application Support/fnm/node-versions/v16.17.1/installation/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.5.5

Capacitor:

   Capacitor CLI      : 5.4.2
   @capacitor/android : 5.4.2
   @capacitor/core    : 5.4.2
   @capacitor/ios     : 5.4.2

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v16.17.1 (/Users/dante/Library/Application Support/fnm/node-versions/v16.17.1/installation/bin/node)
   npm    : 8.15.0
   OS     : macOS Unknown

### Additional Information

1. Versions:

In Ionic there is vite@4.5.0 and vite-plugin-pwa@0.16.7
The newly set up vite + vite pwa is using 5.0.0 and 0.17.0 initially but I've changed that to 4.5 and 0.16.7 and it keeps working in this project without Ionic.

2. On production things work fine. But for now that means develop something and test on a staging environment and preferably I could test things locally.

**Comment by jandante** [comment]
Thank you for your reply. 
You are right the service worker loads... Really weird, I would have sworn it didn't work yesterday. (maybe because the ionic serve runs on the same url for the reproduction as on the project I have the problem with).

You can see the project where I have the error here: https://github.com/jandante/family-portal/

This will give an additional error in console for lacking of some .env variables but the sw error shows up.

**Comment by liamdebeasi** [comment]
I can reproduce the issue, but the error isn't pointing to anything Ionic related. Can you create a minimal reproduction that demonstrates how this error relates to Ionic?
