### ISSUE TITLE
Consider adding  Data Table  component ? 

### ISSUE THREAD

**Issue by vaynevayne** [ionic-team/ionic-framework#28557]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I have searched for issue, it was mentioned in 2019, you didn't have manpower at that time, now it's 23 years, I would like to ask, is the manpower problem solved now? Have you considered developing it?

### Describe the Use Case

same

**Comment by liamdebeasi** [comment]
Hey there,

Truthfully I don't see us adding a data table in the near future. While our team has grown in the last couple of years, data table components are complicated features. The team has other exciting things on the roadmap that we plan to prioritize. Additionally, there are some good solutions out there already such as https://www.ag-grid.com.

Components like data tables require significant investment which is one of the reasons why complex data tables such as AG Grid have entire teams dedicated to that feature. For these specialized components we tend to rely on 3rd party solutions. For example, we recommend SwiperJS for carousels and JS Framework-specific solutions for virtual scroll (Virtuoso for React, CDK Scroller for Angular, etc).

**Comment by vaynevayne** [comment]
Several open source table libraries do not work well, or do not support rn, so I want ionic to develop its own.

**Comment by liamdebeasi** [comment]
What is "rn"?

**Comment by vaynevayne** [comment]
> What is "rn"?

react-native

**Comment by liamdebeasi** [comment]
We don't make React Native components, so even if we did make a data table it would not work with React Native.
