### ISSUE TITLE
bug: Maskito/phone doesn't work properly (on strict:false)

### ISSUE THREAD

**Issue by donilearn** [ionic-team/ionic-framework#28575]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I'm using @maskito/phone library for input phone masking. But when I tried to enter the number into input field, the masking didn't work. Can't enter any numbers
![изображение](https://github.com/ionic-team/ionic-framework/assets/65765426/7cf8ce4d-9070-4600-ac7a-006a593d7591)

I use default mask code: with strict:false mode 
```
import {maskitoPhoneOptionsGenerator} from '@maskito/phone';
import metadata from 'libphonenumber-js/min/metadata';

export default maskitoPhoneOptionsGenerator({
    countryIsoCode: 'US', 
    metadata,
    strict: false
});
```
*. vue
<tempmlate>
`<ion-input 
          id="phone_mask" label="Phone Number"
          aria-label="Phone Number"
          clearInput
          enterkeyhint="next"
          label-placement="floating" fill="outline"
          @ionInput="onInput"
          v-maskito="options" />`
<script>
import { maskito as vMaskito } from '@maskito/vue';
import options from './mask';

### Expected Behavior

Must work as shown in docs .............

### Steps to Reproduce

1. install package @maskito/phone, @maskito/vue
2. create mask.js as shown in docs [Maskito](https://maskito.dev/addons/phone)
3. in view file import the mask

### Ionic Info

Ionic:
   Ionic CLI       : 7.1.5 (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.5.5

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.4

System:

   NodeJS : v21.2.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.2.4
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. As per the [input docs](https://ionicframework.com/docs/api/input#input-masking) issues with Maskito should be reported to the Maskito team: https://github.com/taiga-family/maskito/issues. We do not maintain this library, so we are unable to address any issues there.

**Comment by donilearn** [comment]
> Thanks for the report. As per the [input docs](https://ionicframework.com/docs/api/input#input-masking) issues with Maskito should be reported to the Maskito team: https://github.com/taiga-family/maskito/issues. We do not maintain this library, so we are unable to address any issues in that codebase.

It works in html tag <input> correctly, But with <ion-input> doesn't work

**Comment by liamdebeasi** [comment]
Can you provide a full reproduction I can use to test this?
