### ISSUE TITLE
bug: All Angular standalone components are not tree shaken from the main JS chunk

### ISSUE THREAD

**Issue by StefanNedelchev** [ionic-team/ionic-framework#28574]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I tried migrating my current app to Angular 17 and then migrating to Standalone Ionic components. I followed the official guideline and used the automated tool for help. Then I found out that the main JS chunk suddenly became ~1.3MB (compared to the previous ~600kb). 

All my modules and pages are lazy loaded and this was a surprise for me. I double checked that all instances of `IonicModule` are gone and all imports come from the `/standalone` path. I also double checked that I only import what is needed and where it's needed. Everything seems to be fine. The app is a mixture between modules and standalone components (if this matters).

After checking the bundle that's what I found:

![Screenshot from 2023-11-23 21-41-39](https://github.com/ionic-team/ionic-framework/assets/15238282/37ef7617-5677-4dea-9c36-3071863252e0)

As you can see - the main chink is full of Ionic components which are not tree-shaken.

Actually I could also reproduce this in a clean Ionic standalone project with the latest CLI:

![Screenshot from 2023-11-23 21-58-55](https://github.com/ionic-team/ionic-framework/assets/15238282/27895496-3303-445e-89a6-e4f2aa7a56ff)

The issue happens with both webpack and esbuild.

### Expected Behavior

I would expect all components to be tree-shaken and bundled in their respective places away from main JS.

### Steps to Reproduce

1. Generate a fresh Ionic project with the latest CLI - Chose Angular and Standalone. For template chose the one with the side menu (because it has an additional lazy loaded module).
2. Edit the App component by removing all Ionic components from the template, leaving the router outlet only
3. Remove the imports of these components from the TS file too
4. Do a production build

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.6
   @angular-devkit/build-angular : 17.0.3
   @angular-devkit/schematics    : 17.0.3
   @angular/cli                  : 17.0.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : not installed
   @capacitor/core    : 5.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v18.17.1 (/usr/bin/node)
   npm    : 9.8.1
   OS     : Linux 6.2

### Additional Information

The app has only Browser platform. It's a mixture between modules and standalone components and all routes are lazy loaded.

**Comment by hakimio** [comment]
See @liamdebeasi [answer](https://github.com/ionic-team/ionic-framework/issues/28483#issuecomment-1798635173).

**Comment by liamdebeasi** [comment]
Thanks for the report. The comment in https://github.com/ionic-team/ionic-framework/issues/28574#issuecomment-1827798891 has an explanation for the behavior you are seeing. Ionic is working correctly, but the problem is that the bundle analyzer tool is not showing you the complete picture. Using the tool I noted in the linked comment will give you a more accurate picture of your build size.

**Comment by StefanNedelchev** [comment]
@liamdebeasi  Thanks for the link, but I'm still confused :thinking: . Why are all components (even if it's just the ones that I use) included in the main chunk? This defies the very purpose of Angular standalone components. Yes, I believe you that this makes the overall size of the bundle smaller but this benefit is overshadowed by the overhead on my main.js. In the example that you show, the overhead is ~50kb (which I would willingly take) but in my case it's an increase from 600kb to almost 1.3 MB which is a deal breaker, especially for my web vitals.

It seems I'll stick to the "old" lazy loaded components for now until something changes. How long do you plan supporting them?

**Comment by liamdebeasi** [comment]
> Last I checked this behavior is controlled by the Angular CLI/bundler, not Ionic. I'll double check with the Angular team, but as far as I know this is not something Ionic is able to control.

I spoke with the Angular team and it sounds like Angular _should_ be doing the desired behavior automatically. I'm working with them to determine why that's not happening right now. I'll follow up here when I have more to share.

**Comment by StefanNedelchev** [comment]
> @StefanNedelchev is `1.3MB` with `esbuild` or `webpack`? In my case, `esbuild` production bundle is a lot bigger than `webpack` when using only standalone components and importing everything from `@ionic/angular/standalone`. There seems to be an issue with `esbuild`.

In my case it's almost similar in both webpack and esbuild. There was a difference but it seemed insignificant to me.

> We don't have any immediate plans to remove, but we do plan to slowly move away from IonicModule in favor of standalone components. If the team decides to ultimately remove IonicModule we will give the community ample notice (typically at least 1 year).

Thanks a lot, it will be appreciated. If it's an Angular CLI issue then I hope they will investigate it.

**Comment by hakimio** [comment]
[Angular Material library](https://material.angular.io/components/button/examples#button-overview) is currently using similar code splitting technique where you import `MatButtonModule` from `@angular/material/button`, but it's not as fine-grained  as proposed Ionic approach where all components are imported from different paths. For example, `MatCardModule` will contain all the card components. Also, transition from single import path was smooth because of `ng update` which automatically updated all the code.
Anyway, if you are going this route, there has to be a well documented and "advertised" reliable tool to do the migration automatically. After that I don't think it's such a great idea to leave 3 different paths to import components from. It's already pretty annoying having to choose between `@ionic/angular` and `@ionic/angular/standalone` every time when importing Ionic components.

**Comment by hakimio** [comment]
It does 🙂
![image](https://github.com/ionic-team/ionic-framework/assets/768105/24e8af27-7f1d-4607-a3bb-d2e517f0e86a)

**Comment by cwoebker** [comment]
First of all, big thanks for doing such a thorough investigation and solid summary.

> Ionic can change how components are imported to avoid this limitation, but it comes with breaking changes and a degraded developer experience. 

I can second the comment on the Angular Material library approach here, with automatic imports in most IDEs these days it doesn't really feel like a degraded developer experience. Of course you are right in that this means adapting all imports in a transition which is a bit of effort.

**Comment by StefanNedelchev** [comment]
@liamdebeasi  thank you for not ignoring the "issue" and diving into it. Your comment provides some good insights and also makes me understand why Angular Material imports work the way they do at the moment.
If Ionic is about to make that change and make us provide the additional paths of the import statements for the components, it won't be a problem for me (I hope the majority of the community agrees). Also I believe migrating existing projects to this approach can be automated with a script (but I'm just guessing).
Also something that I wonder - is it possible to actually support both ways of importing if you use a container `index.ts` file on the `/standalone` rot path? I'm not sure if my guess is correct but I think this will make it possible to not break currently imported components but still allow tree shaking if developers start refactoring their imports to be more specific.

**Comment by liamdebeasi** [comment]
>  Also I believe migrating existing projects to this approach can be automated with a script (but I'm just guessing).

I haven't tried this, but at first glance this does seem possible.. We'd be migrating the import syntax which I believe is mostly consistent across frameworks (i.e. `import { ... } from '@ionic/{angular/standalone, react, vue}'`.

>  is it possible to actually support both ways of importing if you use a container index.ts file on the /standalone root path that exports everything? I'm not sure if my guess is correct but I think this will make it possible to not break currently imported components but still allow tree shaking if developers start refactoring their imports to be more specific.

Yeah that's a good thought. My understanding is the optimized code splitting solution could never export anything from `@ionic/angular/standalone` (i.e. everything would need to be something like `@ionic/angular/standalone/[component]`) otherwise we'd be back to the original problem noted in this thread.

-------

Thanks for the feedback, everyone! As noted, our first step here is a public RFC to collect feedback from the community. We'll use that feedback to inform our decisions moving forward.

**Comment by stevebrowndotco** [comment]
> Can Ionic change to account for this behavior?
Yes, but it comes with breaking changes. To optimize for code splitting, each component would need to be in its own entry point. Developer code would need to change like so:

I think this is fine, I wonder if the Ionic team will go ahead and implement this now?

I personally consider it to be more of DX degradation if you **dont** let us code split. 

> Ideally we'd support both this import as well as the current import to avoid immediate breaking changes. However, this may be a significant maintenance burden for the team, so more research would be needed to determine if this is something we are reasonably able to do.

I'm not sure if it would be too much of a burden? Internally isn't it just allowing exports from the individual components vs an index exports? :/

Using `@ionic/angular/standalone`, I currently have an initial chunk that looks like this, which is pretty bad

<img width="908" alt="Screenshot 2023-12-07 at 00 07 32" src="https://github.com/ionic-team/ionic-framework/assets/1081099/83b8c786-329c-40ae-85ef-e06ad09a2110">
