### ISSUE TITLE
bug: ionInput event on ion-range does not fire, if the range value was changed programmatically

### ISSUE THREAD

**Issue by juliamobile** [ionic-team/ionic-framework#28578]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have two ion-ranges. The second range changes its value, if the first one is moved. There is an event listener on the ionInput event of the second range, that does not fire. I can see that it changes its value, when I set it programmatically, but the input event does not fire.

### Expected Behavior

If i set the range value programmatically, an ion input event should be fired.

### Steps to Reproduce

1. Create two ion ranges
2. If the first range was moved, set the value of the second one to a new value 
3. listen to the ion input event of the second ion range

### Ionic Info

Ionic:

   Ionic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.2.8 (/Users/jmikov/Projects/lbs/lbs-sales/node_modules/@angular-devkit/build-angular)
   @angular-devkit/schematics    : 16.2.8 (/Users/jmikov/Projects/lbs/lbs-sales/node_modules/@angular-devkit/schematics)
   @angular/cli                  : 16.2.8 (/Users/jmikov/Projects/lbs/lbs-sales/node_modules/@angular/cli)
   @ionic/angular-toolkit        : 10.0.0 (/Users/jmikov/Projects/lbs/lbs-sales/node_modules/@ionic/angular-toolkit)

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : 4.3.0 (/Users/jmikov/Projects/lbs/lbs-sales/node_modules/@capacitor/android)
   @capacitor/core    : 4.3.0 (/Users/jmikov/Projects/lbs/lbs-sales/node_modules/@capacitor/core)
   @capacitor/ios     : 4.3.0 (/Users/jmikov/Projects/lbs/lbs-sales/node_modules/@capacitor/ios)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.20.2 (/Users/jmikov/.nvm/versions/node/v16.20.2/bin/node)
   npm    : 8.19.4
   OS     : macOS

**Comment by juliamobile** [comment]
Here is the reproduction example:
[https://stackblitz.com/edit/ionic7-label-test-dyfz5n?file=src%2Fapp%2Fapp.module.ts](url)

1. enter a number in a range 0-200 in the input field and press Enter
2. the value of the range is set (the knob is moved), but the onInput event does not fire (see the related console log)

**Comment by sean-perkins** [comment]
@juliamobile thanks for reporting this issue. 

This is the intended behavior of form controls and aligns with browser equivalents: https://codepen.io/sean-perkins-ionic/pen/bGzxpLv?editors=1111

`input`/`ionInput` behaves the same as `change`/`ionChange` where it should only be the result of a user interaction. 

Logically your application already knows that the value of range has changed when you are assigning the value in `inputChanged`. This is where you should be handling any expected side effects for the range value changing, in addition to when the user interacts with the control from the `ionInput` event emission.

**Comment by juliamobile** [comment]
I don't agree. The value of the range is a source of truth here. In the previous ionic version we were listening to onChange events of it. But in the last version it does not fire anymore, neither by dragging the knob nor by changing the value programmatically. 

If I have every time to implement my own logic for listening to change events on the value in different components, it is not the right way to handle it.
