### ISSUE TITLE
bug: Unclear purpose of Ionic lifecycle hooks dependencies in React

### ISSUE THREAD

**Issue by mhryshkin** [ionic-team/ionic-framework#28572]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I'm struggling with understanding the purpose of lifecycle hooks dependencies in React.
An example from documentation https://ionicframework.com/docs/react/lifecycle where it says that: 
"Developers can also optionally pass reactive dependencies to each lifecycle hook. These are then passed to the underlying [React useEffect hook](https://react.dev/reference/react/useEffect#useeffect):"

```
const [data, setData] = useState('foo');

useIonViewDidEnter(() => {
  console.log('ionViewDidEnter event fired');
}, [data]);
```

But according to my research, it just behaves the same way either with deps specified or without them specified. There is no difference. It will run once the view is entered, left e.t.c. It will not be re-run again until one of the mentioned events happens. 

### Expected Behavior

The deps should be excluded from the source code as well as from documentation.

### Steps to Reproduce

Try to use any ionic lifecycle hook with deps and without deps and notice that there is no difference in behaviour.

### Ionic Info

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.16.1
   npm    : 9.5.1
   OS     : macOS Monterey

**Comment by mhryshkin** [comment]
> https://forum.ionicframework.com/t/obsolete-state-in-useionviewwillenter/210861

Thanks for your reply @liamdebeasi. As I see this is for the cases when the page component has not been unmounted but the view has been left. I guess in my case the thing that confused me is that i have the following router:

```
 <IonRouterOutlet>
     <Route path="/app" render={() => <AppTabs />} />
    <Route path={`/${Pages.Test}/:id`} render={() => <TestPage />} />        
</IonRouterOutlet>
```
And inside /app I have:

```
 <IonTabs>
      <IonRouterOutlet>
        <Route path={`/app/${Pages.NestedRouterTestPage}`} render={() => <NestedRouterTestComponent />} />
      </IonRouterOutlet>
      <IonTabBar selectedTab={activeTab} onIonTabsDidChange={handleTabSelect} slot="bottom">
        {tabs.map((tab) => {
          const { id, href } = tab;

          return (
            <IonTabButton key={id} tab={id} href={href}>
             {...}
            </IonTabButton>
          );
        })}
      </IonTabBar>
    </IonTabs>
```

The root level router always unmounts the page regardless I use `render` prop but the 'component' one. But in the case of the nested router within the 'Tabs', the page doesn't get unmounted when I leave it. Is it expected behavior for the router within 'Tabs' to not unmount the pages? I thought it could be applicable to `IonRouterOutlet` in general.

**Comment by liamdebeasi** [comment]
>  Is it expected behavior for the router within 'Tabs' to not unmount the pages? I thought it could be applicable to IonRouterOutlet in general.

Yes, views in `IonRouterOutlet` (regardless of `IonTabs` usage) should not be unmounted when leaving them. The exception here is if you go from PageA to PageB then press the back button. In that case, PageB should be unmounted. However, when going from PageA to PageB, PageA should not be unmounted. This behavior allows us to a) preserve the state of inactive view and b) allow swipe to go back to work on iOS.
