### ISSUE TITLE
bug: Angular does not build with esbuild

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-framework#28576]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When building an angualr 17 project with `@angular-devkit/build-angular:browser-esbuild` instead of `@angular-devkit/build-angular:browser`, the following warning is received:

```log
4:40:11 PM [vite] warning: 
.angular/cache/17.0.3/vite/deps/chunk-LYPINDT5.js
2585|      return i[n];
2586|    }
2587|    return import("./".concat(a, ".entry.js").concat("")).then(function(e2) {
   |                  ^
2588|      {
2589|        cmpModules.set(a, e2);
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.
```

This chunk is from `@ionic/core/dist/esm-es5/`

### Expected Behavior

Ionic should build without problems when using `webpack` or `vite` (either change the import or add the `vite-ignore`)

### Steps to Reproduce

1. create an angular project
2. use ionic
3. change builder to `browser-esbuild`

### Code Reproduction URL

https://github.com/sign/translate

### Ionic Info

    "@ionic/angular": "7.5.6",

[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 7.1.5

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 2.0.0) : 1.7.3

System:

   NodeJS : v18.15.0
   npm    : 9.6.7
   OS     : macOS Unknown

**Comment by hakimio** [comment]
Duplicate: https://github.com/ionic-team/ionic-framework/issues/28500
