### ISSUE TITLE
feat(refresher): add property "mode"

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#28587]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

This feature would allow developers to manually set the component's style to either Material Design (md) or iOS (ios), aligning it with the flexibility of other Ionic components.

### Describe the Use Case

In my specific use case, the app has a global setting of `mode: 'ios'`. This setting, while ensuring design consistency across platforms, leads to a limitation on Android devices where the ion-refresher uses a fallback refresher instead of the native Android style. The inability to toggle or override this setting for specific components like ion-refresher results in a less optimal user experience on Android devices. The addition of a mode property would allow for more granular control, enabling the use of the native Android refresher style on Android devices, while maintaining the iOS style globally across other components.

### Describe Preferred Solution

```html
<ion-refresher mode="md"></ion-refresher>

<ion-refresher [mode]="isIos ? 'ios' : 'md'"></ion-refresher>
```

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. All Ionic components that have per-mode stylesheets accept a virtual `mode` property. Here's an example of having an app run in iOS mode but have the MD native refresher: https://codepen.io/liamdebeasi/pen/OJdweYK

**Comment by DwieDima** [comment]
Thank you @liamdebeasi !
I've inspected it on my Chrome Browser with the iPhone 12 Pro frame.
Removing the iOS Frame will show the md refresher. 

![image](https://github.com/ionic-team/ionic-framework/assets/26873275/ed2f4185-be69-4ca3-8b95-0dcb40703edd)
