### ISSUE TITLE
bug: native ios refresher is not used on ipados

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#28617]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When loading an Ionic app on an iPad Pro, the fallback refresher is used, not the native one like used on iPhones.

### Expected Behavior

Native refresher used on iPad Pro

### Steps to Reproduce

1. Open https://docs-demo.ionic.io/component/refresher on an iPad Pro running iOS 17
2. Observe fallback refresher used

### Ionic Info

N/A

### Additional Information

https://github.com/ionic-team/ionic-framework/assets/2166114/0e7cd747-45ad-4757-9b69-b044877dcddf

Related: https://github.com/aeharding/voyager/issues/930

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28620, and a fix will be available in an upcoming release of Ionic Framework.
