### ISSUE TITLE
bug: RootParams of `ion-nav` not detected if in kebab-case

### ISSUE THREAD

**Issue by Ericlm** [ionic-team/ionic-framework#28611]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I created an Ionic-Vue project, and when using the `ion-nav` component, the root component doesn't get any props if `ion-nav` uses kebab-case but it works perfectly with camelCase.

### Expected Behavior

The `ion-nav` component should not be sensitive to casing, just like other Vue components, and recommended by the linter rules: https://eslint.vuejs.org/rules/attribute-hyphenation.html#vue-attribute-hyphenation

### Steps to Reproduce

1. Clone https://github.com/Ericlm/ionic-vue-nav-root-params
2. Go to `Tab1Page.vue` file and look for the two `IonNav` components in the template
3. The second one doesn't work (because it is in kebab-case)

### Code Reproduction URL

https://github.com/Ericlm/ionic-vue-nav-root-params

### Ionic Info

`ionic info` doesn't seem to work with my project (?)
```
[ERROR] Invalid project type: vue-vite (project config: ./ionic.config.json).
        
        Project type must be one of: angular, ionic-angular, ionic1, custom, react, vue

Bad project type: undefined
```

**Comment by Ericlm** [comment]
*Maybe the same issue with `componentProps` on `ion-nav-link`.

**Comment by liamdebeasi** [comment]
Can you make your repo public?

**Comment by Ericlm** [comment]
I may take a look at it! 🙂

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28615, and a fix will be available in an upcoming release of Ionic Framework.
