### ISSUE TITLE
bug: Rotating device incorrectly resizes text

### ISSUE THREAD

**Issue by SoCuul** [ionic-team/ionic-framework#28624]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v4.x, v5.x, v6.x, v7.x, Nightly

### Current Behavior

When a device is rotated, the text on-screen is incorrectly sized until the app is relaunched.

### Expected Behavior

The text should remain the same size no-matter the orientation of the device.

### Steps to Reproduce

Deploy an ionic app to your device, then rotate it any way other than 0º

### Ionic Info

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v21.2.0
   npm    : 10.2.3
   OS     : macOS Unknown

### Additional Information

It looks like this piece of code should be included within the default html page created with the ionic template, as this fixes the issue: https://stackoverflow.com/a/2711132/14239936

**Comment by liamdebeasi** [comment]
What version of Ionic are you on? The code that fixes this issue was added in Ionic 7.1.4: https://github.com/ionic-team/ionic-framework/releases/tag/v7.1.4

**Comment by SoCuul** [comment]
Oh I just realized I was on an outdated ionic version. Sorry about that!
