### ISSUE TITLE
bug: CapacitorHttp does not work with Angular withFetch() interceptor

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionic-framework#28684]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using withFetch from Angular 17, we can no longer use CapacitorHttp POST requests on Android, it does not proceed the request on native side but passes it without any more headers to native window.fetch.

### Expected Behavior

Don't break when using withFetch.

### Steps to Reproduce

1. Create ionic angular starter
2. Use CapacitorHttp
3. Make a POST request on Android

### Ionic Info

This command does not work in NX environments. But we have all Ionic and Capacitor dependencies on the latest release.

**Comment by liamdebeasi** [comment]
Hey there! This is the repo for Ionic Framework, the UI component library. CapacitorHTTP issues should be reported on https://github.com/ionic-team/capacitor. I'd also recommend creating a minimal reproduction app that the team can use to reproduce the issue.
