### ISSUE TITLE
feat: Please support the vue3 script setup syntax

### ISSUE THREAD

**Issue by Dangerous828** [ionic-team/ionic-framework#28681]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Support for the Vue3 <script setup> RFC (see: https://vuejs.org/api/sfc-script-setup.html)

### Describe the Use Case

Now with ionic lifecycle you have to go through setup() instead of just using it out of the box in <script setup>.

### Describe Preferred Solution

Support for the Vue3 <script setup>

**Comment by Dangerous828** [comment]
This issue has a problem with following the latest documentation on how to build vite ionic, and then removing ts does not and cannot work properly with the lifecycle and script setup.

**Comment by liamdebeasi** [comment]
Hi there,

Ionic supports `script setup` in Vue 3. If you are running into an issue using it with Ionic we need a description of the problem and a sample application we can use to reproduce the issue.

**Comment by sugar258596** [comment]
The iconic supports Vue3. Please check whether it is because of your version

**Comment by Dangerous828** [comment]
Sorry, I found out that when ionic is in vue3, for script setup syntax is only effective on page components, it is not triggered on subcomponents, it's my problem!
