### ISSUE TITLE
feat: Use CloseWatcher API for modals etc

### ISSUE THREAD

**Issue by lukewarlow** [ionic-team/ionic-framework#28703]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It could be useful for ionic to make use of the new close watcher api [1][2] to listen for close signals to close components such as alert dialogs. 

[1] https://html.spec.whatwg.org/multipage/interaction.html#the-closewatcher-interface
[2] https://developer.chrome.com/blog/new-in-chrome-120#close-watcher

### Describe the Use Case

This API allows listening for escape key presses, along with more platform specific close signals such as Android's back button/ gesture. This would provide a more native feel (matching both the native platform and the web).

It would also improve accesibility as it supports Talkback back gestures too.

### Describe Preferred Solution

The close watcher API being used when supported feels like the best solution.

**Comment by liamdebeasi** [comment]
Thanks, I think this would be good for us to support. I have an experimental version if you want to give it a try:

**Angular**
```
npm install @ionic/angular@7.6.1-dev.11702569564.1746fa9f
```

**React**
```
npm install @ionic/react@7.6.1-dev.11702569564.1746fa9f @ionic/react-router@7.6.1-dev.11702569564.1746fa9f
```

**Vue**
```
npm install @ionic/vue@7.6.1-dev.11702569564.1746fa9f @ionic/vue-router@7.6.1-dev.11702569564.1746fa9f
```

**Stencil/Vanilla JavaScript**
```
npm install @ionic/core@7.6.1-dev.11702569564.1746fa9f
```

The feature is added behind an `experimentalCloseWatcher` flag in the [IonicConfig](https://ionicframework.com/docs/developing/config), so you will need to set `experimentalCloseWatcher: true` before you can use it. Once enabled, you will be able to use this API to dismiss overlays, menus, and navigate in a non-Cordova/non-Capacitor environment on supported browsers (Chrome 120+ as of writing).

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28705, and the feature will be available in an upcoming release of Ionic Framework.
