### ISSUE TITLE
bug: Incorrect Toast position due to positionAnchor being hidden

### ISSUE THREAD

**Issue by loneoakdev** [ionic-team/ionic-framework#28707]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Defining a Toast with a position of 'top' and a positionAnchor of an HTML element places the Toast at the very top of the page instead of directly under the HTML element defined in the positionAnchor attribute. The following error appears in Xcode:

⚡️  [warn] - [Ionic Warning]: The positionAnchor element for ion-toast was found in the DOM, but appears to be hidden. This may lead to unexpected positioning of the toast. {"didPresent":{},"willPresent":{},"willDismiss":{},"didDismiss":{},"didPresentShorthand":{},"willPresentShorthand":{},"willDismissShorthand":{},"didDismissShorthand":{},"delegateController":{},"lockController":{},"triggerController":{},"customHTMLEnabled":false,"presented":false,"__zone_symbol__ionToastWillDismissfalse":[{"type":"eventTask","state":"scheduled","source":".addEventListener:ionToastWillDismiss","zone":"<root>","runCount":0}]}

### Expected Behavior

The Toast should be displayed directly under the HTML element specified in the positionAnchor attribute.

### Steps to Reproduce

1. Create an <ion-header> tag and specify an id: <ion-header id="header-anchor">Header</ion-header>
2. Create a Toast using ToastController. Specify position: 'top' and positionAnchor: 'header-anchor'
3. Call the Toast using toast.present()

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.1
   @angular-devkit/build-angular : 17.0.7
   @angular-devkit/schematics    : 17.0.7
   @angular/cli                  : 17.0.7
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v20.9.0 (/usr/local/bin/node)
   npm    : 10.2.5
   OS     : macOS Unknown

**Comment by loneoakdev** [comment]
In steps to reproduce, step 1, the GitHub markdown editor removed the ion-header tag example I put in there. The step should have shown that I created an ion-header tag with an id="header-anchor".

**Comment by liamdebeasi** [comment]
Can you please clarify why you think this is an Ionic bug and include a reproduction? Ionic is informing you that the anchor element is not visible in the DOM at the moment the Toast is being presented. Hidden elements have a dimension of 0x0, so Ionic has no way of knowing where to position the toast.

**Comment by loneoakdev** [comment]
I'm not hiding the ion-header element..it is visible in the DOM at the moment the Toast is presented. I will try to setup a reproduction of the bug for you to review.

**Comment by loneoakdev** [comment]
https://stackblitz.com/edit/ionic7-label-test-mezq3v?file=src%2Fapp%2Fapp.component.ts

**Comment by liamdebeasi** [comment]
Your demo is running a version of Ionic that does not support the `positionAnchor` property. However, even when I update the StackBlitz to a supported version, I cannot reproduce the reported behavior. Can you check your reproduction and verify that the code required to reproduce the issue is present?


https://github.com/ionic-team/ionic-framework/assets/2721089/7383cd18-d57c-4a5a-937a-d9f18324486d

**Comment by loneoakdev** [comment]
Thanks for updating the version…didn’t realize it was the older version. Let me modify the project a bit. My toolbar and header are in a standalone component. Also, this behavior occurred on an iOS device, so we’ll see if it’s specific to that or if it occurs in stackblitz as well.

**Comment by loneoakdev** [comment]
I confirmed locally that it works as intended in the browser, but not in the iOS simulator or when testing in Xcode on an actual iPhone. Please see attached screenshots of the same code being run in the browser vs simulator
<img width="1792" alt="Screenshot 2023-12-19 at 11 10 27 AM" src="https://github.com/ionic-team/ionic-framework/assets/137928068/c3a91d22-ee32-4ac2-9cc8-9708ed05af22">
<img width="1792" alt="Screenshot 2023-12-19 at 11 11 04 AM" src="https://github.com/ionic-team/ionic-framework/assets/137928068/220df90f-a80a-4002-8049-3fc4aa7c23a6">

**Comment by liamdebeasi** [comment]
Can you provide a reproduction I can run on an iOS device? The reproduction at https://stackblitz.com/edit/ionic7-label-test-mezq3v?file=src%2Fapp%2Fapp.component.ts no longer renders the header.

**Comment by loneoakdev** [comment]
Can you try this one?

https://stackblitz.com/edit/ionic7-label-test-h1vazk?file=src%2Fapp%2Fapp.component.html

The previous stopped working for some reason and I can't get it working again. Thanks

**Comment by liamdebeasi** [comment]
Does this reproduce on a physical device? I tested this on a physical iPhone 12 Pro running iOS 17, and I cannot reproduce the reported behavior:

https://github.com/ionic-team/ionic-framework/assets/2721089/c98ac98b-5be7-43d8-ada6-0ff74214e76d

**Comment by loneoakdev** [comment]
Yes...I'm able to see the issue in both the iOS simulator and on an actual iPhone when connected and running via Xcode. I don't have an Android device to test on a physical device at this point.

**Comment by liamdebeasi** [comment]
Is there any other information you can give me regarding how to reproduce the issue? We can't fix any potential issues unless we can reproduce them first.

Does this happen in mobile Safari on iOS, or only in a Capacitor app?

**Comment by loneoakdev** [comment]
It does not happen on Safari on a computer when I'm in developer mode. Unfortunately I don't have it setup to test with Safari on an actual mobile device.

The only other thing I can tell you about the setup is that I call an AlertService (injected in root) to display the toast. The ToastController in this service is imported from @ionic/angular/standalone. Importing it from @ionic/angular didn't work at all and the toast didn't display.

If there's anything else you think I can provide information-wise, please let me know. The really difficult part about this is that I can only reproduce the issue in the simulator or on a device.

**Comment by loneoakdev** [comment]
Just to make sure it wasn't my setup, I put EVERYTHING in a standalone component...the header with the ID that is used as the positionAnchor, I injected the ToastController in the component instead of using a service. I tried using ToastController from both @ionic/angular and @ionic/angular/standalone. Both of them still display the toast at the very top of the screen instead of under the anchor. 

I also tried adding mode="md" to the ion-header tag in case it was something with the way iOS renders the header-same issue.
I even tried adding a div tag under ion-content tag with the ID instead of having it on the ion-header tag - same issue.
I have a LoadingController that dismisses before the toast is displayed...I removed this to make sure it wasn't the overlay - same issue.

**Comment by liamdebeasi** [comment]
I recommend starting with the application in https://github.com/ionic-team/ionic-framework/issues/28707#issuecomment-1863336920 and removing code until you can no longer reproduce the issue. This will let you create a sample that reproduces the issue, and you'll know what is triggering the behavior.
