### ISSUE TITLE
feat: Allow justify-between for placeholder and arrow for ion-select when not using label

### ISSUE THREAD

**Issue by tofra** [ionic-team/ionic-framework#28734]
The option metioned by Liam in https://github.com/ionic-team/ionic-framework/issues/27752 doesn't work anymore.

--- 

You can use the `container` Shadow Part added in Ionic 7.1 to make the inner container extend the full width of the component.

Relevant CSS:

```css
ion-select::part(container) {
  width: 100%;
}
```

Demo: https://codepen.io/liamdebeasi/pen/vYQeBjW

_Originally posted by @liamdebeasi in https://github.com/ionic-team/ionic-framework/issues/27752#issuecomment-1623734736_

**Comment by liamdebeasi** [comment]
Thanks! The workaround I gave before was not great as it was dependent on the layout of the component internals. I think a better solution would be to apply `position: absolute` to the arrow. We do this for certain select layouts too, and it has worked well.

Here's a new demo you can use: https://codepen.io/liamdebeasi/pen/vYQeBjW

**Comment by tofra** [comment]
Thanks Liam!

For future readers, another way I found was adding `label-placement="floating"` to `ion-select` worked also.
