### ISSUE TITLE
bug: ion-searchbar does not fire ionInput event when user uses backspace to empty all input

### ISSUE THREAD

**Issue by Oostwegel** [ionic-team/ionic-framework#28739]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using the ion-searchbar component, it's expected that the ionInput event is triggered whenever the content of the search bar changes.
However, a bug is observed where the ionInput event is not fired if a user employs the backspace key to remove all text from the input field.
This issue occurs specifically when the last character is deleted, leaving the search bar empty.
Expected behavior is that the ionInput event should be triggered in all cases where the content of the search bar changes, including when it's cleared completely.

### Expected Behavior

The ionInput event should be consistently triggered in response to any change in the search bar's content, including when the input field is cleared entirely by using backspace.

### Steps to Reproduce

Add an ion-searchbar component to a page.
<ion-searchbar [animated]="true" [debounce]="600" (ionInput)="onSearch($event)" (ionClear)="onClear()"></ion-searchbar>
Implement an event listener for the ionInput event.

Enter text into the search bar.
Use backspace to remove all the text characters in one press.

Observe that the ionInput event is not fired upon the removal of all the characters.

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.2
   @angular-devkit/build-angular : 17.0.7
   @angular-devkit/schematics    : 17.0.7
   @angular/cli                  : 17.0.7
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : 5.6.0

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v20.10.0 (/usr/local/bin/node)
   npm    : 10.2.5
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the report. Are you having a problem with `ionChange` or `ionInput`? Your issue mentions `ionChange`, but only `ionInput` is used in the reproduction. 

I will note that in the example you provided `ionChange` should not fire when blurring the input after clearing. `ionChange` fires when the committed value of the input changes. If you type something into the input but do **not** blur the input then the value is never committed, so clearing the input would not fire `ionChange`. However, `ionInput` should still fire.

**Comment by Oostwegel** [comment]
I have updated the issue; sorry for that.

**Comment by liamdebeasi** [comment]
Can you provide a reproduction? The `ionInput` event is firing whenever backspace is pressed here: https://codepen.io/liamdebeasi/pen/GReKdoP

**Comment by Oostwegel** [comment]
I apologize; upon re-examining, I realize that I made a mistake in Angular.
