### ISSUE TITLE
bug: ion-select old syntax

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#28743]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hello, when creating a selector with the old syntax, the selector stays in the middle instead of snapping to the right.

Greetings!

<img width="609" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/18282247/0f4a7c51-dad0-4e1d-a68f-0393367ee026">

### Expected Behavior

It should fit to the side.

### Steps to Reproduce

Download the project and try. (If it doesn't appear the first time, reload the page)

### Code Reproduction URL

https://github.com/Marius-Romanus/bug-ionic-select

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.1.6
   Ionic Framework               : @ionic/angular 7.6.2
   @angular-devkit/build-angular : 17.0.7
   @angular-devkit/schematics    : 17.0.7
   @angular/cli                  : 17.0.7
   @ionic/angular-toolkit        : 10.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v20.9.0
   npm    : 10.1.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the report. We automatically opt developers in to the new form syntax, but the heuristic we use isn't 100% accurate. As a result, we provide the `legacy` prop as a way of explicitly opting in to the legacy syntax. Does the issue go away if you use `legacy="true"` on the first select in your demo?

**Comment by Marius-Romanus** [comment]
Hello, sorry I haven't explained myself well, I don't know why Stackblitz doesn't show the icons, but on the right you can click on them even if they aren't visible.

<img width="618" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/18282247/5bec23c7-ec12-407a-b69a-b45597712439">

**Comment by Marius-Romanus** [comment]
It seems that with the legacy tag it works well, sorry, I didn't know about it. Someday I will have to migrate everything ;) Thank you very much!
