### ISSUE TITLE
bug: incompatible reuse strategy

### ISSUE THREAD

**Issue by wangnatie** [ionic-team/ionic-framework#28752]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

 Has the issue  #17673  been resolved? This friend and I are facing the same issue, and I still have this issue in version 7.1.5，

### Expected Behavior

I want to avoid uninstalling displayed pages when switching tabs

### Steps to Reproduce

**route-strategy.service.ts**
`import { RouteReuseStrategy, DetachedRouteHandle, ActivatedRouteSnapshot } from '@angular/router';
export class RouteStrategyService implements RouteReuseStrategy {
  public static handlers: { [key: string]: DetachedRouteHandle } = {};
  public static deleteRouteSnapshot(path: string): void {
    const name = path.replace(/\//g, '_');
    if (RouteStrategyService.handlers[name]) {
      delete RouteStrategyService.handlers[name];
    }
  }

  public shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
    console.log('future:',future);
    console.log('curr:',curr);
    return future.routeConfig === curr.routeConfig && JSON.stringify(future.params) === JSON.stringify(curr.params);
  }

  public shouldDetach(route: ActivatedRouteSnapshot): boolean {
    console.log(route);
    return true;
  }

  public store(route: ActivatedRouteSnapshot, detachedTree: DetachedRouteHandle): void {
    console.log(route);
    console.log(detachedTree);
    RouteStrategyService.handlers[this.getPath(route)] = detachedTree;
  }

  public shouldAttach(route: ActivatedRouteSnapshot): boolean {
    console.log(route);
    return !!RouteStrategyService.handlers[this.getPath(route)];
  }

  public retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle | null {
    console.log(route);
    return RouteStrategyService.handlers[this.getPath(route)] || null;
  }
  
  private getPath(route: ActivatedRouteSnapshot): string {
    console.log(route);
    // tslint:disable-next-line: no-string-literal
    const path = route['_routerState'].url.replace(/\//g, '_');
    return path;
  }
}
`
**app.module.ts**
`providers: [{ provide: RouteReuseStrategy, useClass: RouteStrategyService }]`

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (C:\Users\dell\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.0.9
   @angular-devkit/build-angular : 16.0.3
   @angular-devkit/schematics    : 16.0.3
   @angular/cli                  : 16.0.3
   @ionic/angular-toolkit        : 9.0.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.5.5
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Hi there,

Can you please clarify your use case for this feature? We closed https://github.com/ionic-team/ionic-framework/issues/17673 because we did not have an explicit use case for the feature.
