### ISSUE TITLE
feat: Keep legacy property forever

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-framework#28755]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Keep legacy property forever. 

Ref: https://ionicframework.com/docs/api/checkbox#legacy

### Describe the Use Case

We do not need to use the latest form control apprence with our old apps. i.e. we like what we have now and we do not need to break all our UIs due to the removal of legacy property in the future. This will give nightmare DX to change all the UIs for huge enterprise-grade apps.

### Describe Preferred Solution

Keep legacy property forever for all the relevant controls.

**Comment by liamdebeasi** [comment]
Hi there,

We appreciate the feedback. However, we do plan to remove the legacy form control syntax. We understand that many developers liked the usage that they had before. However, that usage caused the Ionic experience to be broken for users that relied on assistive technology such as screen readers. The legacy form syntax also posed significant maintenance challenges for the team.

We also understand there were bugs and missing features with the modern form syntax, and we've been working hard over the past year to fill in those gaps. At the moment we've addressed the known feature gaps. A majority of the known bugs have been fixed, though there are a few small UI bugs that we plan to wrap up.

If there are specific bugs you are encountering or features that are missing with the modern syntax then I'd encourage you to file issues for each request. We're more than happy to take a look and see where we can improve our form components. Thanks!
