### ISSUE TITLE
bug: large title transition does not account for empty back button text

### ISSUE THREAD

**Issue by roman-rr** [ionic-team/ionic-framework#28751]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x, Nightly

### Current Behavior

Only with `@Ionic/angular` > `7.5.0`, when `ion-back-button` has empty text value:

<img width="375" alt="Screenshot 2023-12-21 at 15 28 40" src="https://github.com/ionic-team/ionic-framework/assets/10646478/7845ca6a-8727-44d6-9a5d-5a8e13895795">

Note that `text=" "` doesn't give a error.

### Expected Behavior

Allow `text=""` for `ion-back-button` component

### Steps to Reproduce

1. git clone https://github.com/roman-rr/bug-backbutton.git
2. cd bug-backbutton
3. npm i
4. ionic serve
5. Click button

### Code Reproduction URL

https://github.com/roman-rr/bug-backbutton/

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.2
   @angular-devkit/build-angular : 17.0.7
   @angular-devkit/schematics    : 17.0.7
   @angular/cli                  : 17.0.7
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.14.0
   native-run                             : 2.0.0

System:

   NodeJS : v20.10.0 (/usr/local/bin/node)
   npm    : 10.2.3
   OS     : macOS Unknown

**Comment by alexdabast** [comment]
Faced the same issue. A white space as "text" solve temporary the issue

`<ion-back-button text=" " [defaultHref]="defaultHref"></ion-back-button>`

**Comment by Mdemol** [comment]
For me this only occurs in iOS mode. Using the temporary solution of @alexdabast for now.

Visually the app will navigate to the desired page, but without any animations. On MD-mode the animations still occur.

**Comment by liamdebeasi** [comment]
Hi everyone,

Here is a dev build with a proposed fix if anyone is interested in testing: `7.8.5-dev.11712853167.1d02271c`

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29327, and a fix will be available in an upcoming release of Ionic Framework.
