### ISSUE TITLE
bug: long error-text forces end slot of ion-input to wrap under input-wrapper

### ISSUE THREAD

**Issue by harry-molyneux** [ionic-team/ionic-framework#28753]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The bug appears when using the `errorText` attribute on an `<ion-input>` whilst also having an element (eg. `<ion-button>`) slotted at the end.

If the `errorText` is long enough, it will force the `<slot name="end">` element to wrap under the `<div class="input-wrapper">` element causing disruption to the layout of the `<ion-input>` element.

![image](https://github.com/ionic-team/ionic-framework/assets/68756225/114fc648-aa1b-42e3-8c4b-0e5565860c48)

### Expected Behavior

The text content of the `<div class="error-text'>` element should wrap to new lines before making the `<slot name="end">` wrap within the container. Therefore, not disrupting the width and/or position of the `<slot name="end">` element.

![image](https://github.com/ionic-team/ionic-framework/assets/68756225/3fd79ac9-9ea2-4ab6-aec9-54f982c69906)

### Steps to Reproduce

1. Set up an `<ion-input>` element with `errorText` of a reasonable length (eg. 75 - 100 characters).
2. Add an `<ion-button>` with `slot="end"` attribute into the `<ion-input>` and add some contents to the `<ion-button>` (eg. an `<ion-icon>`).
3. Invalidate the `<ion-input>` to show the `errorText` and see that the `<ion-button>` is pushed to beneath the input.

### Code Reproduction URL

https://github.com/harry-molyneux/ionic-error-text-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.6 (/Users/harry/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.2
   @angular-devkit/build-angular : 17.0.7
   @angular-devkit/schematics    : 17.0.7
   @angular/cli                  : 17.0.7
   @ionic/angular-toolkit        : 10.0.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.18.2 (/Users/harry/.nvm/versions/node/v18.18.2/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

**Comment by mapsandapps** [comment]
Hi, thank you for submitting this issue. In order for the slots to be correctly positioned, they should be placed inside the `ion-input`, e.g.

```jsx
<ion-input
        [(ngModel)]="shortErrorText"
        errorText="Min. 8 characters"
        label="Short error-text"
        labelPlacement="stacked"
        mode="md"
        name="shortErrorText"
        pattern="^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$"
        placeholder="Short error-text"
        required="true"
        type="text">
        <ion-button
                aria-label="Show/hide"
                fill="clear"
                slot="end">
                <ion-icon
                        aria-hidden="true"
                        slot="icon-only"
                        name="eye" />
        </ion-button>
</ion-input>
```

Please let us know if you continue to have problems after making this change.

**Comment by harry-molyneux** [comment]
Thank you for the response, this makes sense and I can see that there was an issue with my placement of the `<ion-button>` element.

When placing the `<ion-button>` element correctly inside of the `<ion-input>` element, we now observe that the button is not clickable when the `<ion-input>` has focus.

In our use case, we include the `<ion-button>` to allow the user to toggle the visibility of their password. Therefore, it would be quite typical that they might want to use the `<ion-button>` while the `<ion-input>` has focus. Is there a way to allow the `<ion-button>` to be used while the `<ion-input>` has focus?
