### ISSUE TITLE
bug: click event not fired on slotted buttons inside an ion-input that has focus

### ISSUE THREAD

**Issue by chadweimer** [ionic-team/ionic-framework#28762]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using ion-button elements in the "end" slot of an ion-input, the buttons do not fire the click event when clicked while the ion-input has focus.

### Expected Behavior

The click event should fire whether the input control has focus or not.

### Steps to Reproduce

1. Add an ion-input like the following
   ```html
   <ion-item>
     <ion-input label="Input with buttons">
       <ion-button slot="end" onClick={...} >Click Me</ion-button>
     </ion-input>
   </ion-item>
   ```
2. Click the button when the input control does not have focus - onClick fires
3. Click the button when the input control has focus - onClick does not fire

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v20.10.0
   npm    : 10.2.3
   OS     : Linux 6.1

**Comment by chadweimer** [comment]
The workaround for this is to set the button with `pointer-events: auto`.

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. Looks like this code is the culprit: https://github.com/ionic-team/ionic-framework/blob/75ffeee933ae353d2601670178896116c81923e0/core/src/components/input/input.scss#L265

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28772, and a fix will be available in an upcoming release of Ionic Framework.
