### ISSUE TITLE
TLS 1.2 protocol implementation steps in Ionic 6 cordova app

### ISSUE THREAD

**Issue by sangramlnt** [ionic-team/ionic-framework#28764]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

is ionic cordova app integrated APIs supports TLS 1.2 protocol?
steps to implement in API or Supports TLS 1.2 protocol 

### Describe the Use Case

is ionic cordova app integrated APIs supports TLS 1.2 protocol?
steps to implement in API or Supports TLS 1.2 protocol

**Comment by sean-perkins** [comment]
The issue template must be completely filled out when filing issues. Support questions such as these should be asked in the Discord, with significantly more context. Ionic Framework has no opinionation on the TLS protocol. That question should be directed at the Cordova community.
