### ISSUE TITLE
feat: Success text for ion-input and ion-textarea

### ISSUE THREAD

**Issue by ymaheshwari1** [ionic-team/ionic-framework#28765]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently, ionic support to display a helper text and error text for input/textarea, but there are some scenarios in which a success message needs to be displayed for the inputted value.

### Describe the Use Case

Having a success text can be helpful for the user to know that the entered value is a accepted value by the system.

**Comment by sean-perkins** [comment]
Hello @ymaheshwari1 thank you for requesting this feature! 

Our implementation for helper/error text follows Material Design's guidelines: https://m2.material.io/components/text-fields#anatomy. They do not provide a variant state for success. 

The `ion-input` is a scoped encapsulated web component, so you can target any of the inner elements to style as you desire, for example with changing the helper text color when the `valid` class is on `ion-input`: https://stackblitz.com/edit/ec6jxg?file=index.html

Can you let me know if this resolves your request or if there is a reason you are unable to use targeted styles for this use case?

**Comment by ymaheshwari1** [comment]
Thanks for the clarification @sean-perkins 
Closing this as resolved.
