### ISSUE TITLE
bug: app restarting in background when InAppBrowser is opened (when low memory)

### ISSUE THREAD

**Issue by chvonrohr** [ionic-team/ionic-framework#28786]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When within the Ionic app a InAppBrowser is opened and user is closing the InAppBrowser, it may happen that original app is restarting (showing the splash screen of the app again). Clearly, this only affects devices that are low on memory, but I would expect, that the app which opens (and hosts?) the InAppBrowser can't be restarted.

As we use Auth0 Universal Login - and the recommended way opening the login in the InAppBrowser to have a https context - our users sometimes can't login as the deep link with the session information is sent back to the app that can't use that information. I assume, also Ionic Auth Connect has the same issue, because it's opening the login with InAppBrowser?

### Expected Behavior

App should now be allowed to restart.

### Steps to Reproduce

1. Use `ionic start` command to generate a new Ionic Capacitor app with Angular (tabs)
2. Install recommended packages from quick start guide: `npm i @capacitor/app @capacitor/haptics @capacitor/keyboard @capacitor/status-bar`
3. install browser plugin `npm i @capacitor/browser`
4. Add Android platform `ionic capacitor add android`
5. On Tab 3 add a link that opens a random page: `Browser.open({ url: 'https://www.google.com' });`
6. Start app in an Android emulator with low memory: I used Pixel 1 with API 28 and 1500MB RAM
7. Open the app, navigate to tab 3 and open the browser
8. Sometimes this is already enough and closing the InAppBrowser shows you the splash screen of your app. Sometimes, it needs a bit more like opening some other apps and returning to app (like user goes to SMS app to read OTP code). See video for example.

https://github.com/ionic-team/ionic-framework/assets/1733057/f04d12a1-0eba-45f2-a4f7-e4956c5706f1

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5 (/Users/chvonrohr/.nvm/versions/node/v18.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.3
   @angular-devkit/build-angular : 17.0.9
   @angular-devkit/schematics    : 17.0.9
   @angular/cli                  : 17.0.9
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v18.16.0 (/Users/chvonrohr/.nvm/versions/node/v18.16.0/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown

**Comment by chvonrohr** [comment]
@liamdebeasi here is the codebase I used for testing:
https://github.com/chvonrohr/ionic-issue-28786 (basically adding Android platform and button for opening Browser in Tab3).

Important to use low-memory emulator in tests.

**Comment by liamdebeasi** [comment]
I'm not able to reproduce the issue using a Pixel emulator with <1500MB of RAM. Are you able to identify the part of Ionic that is causing the added memory pressure?

**Comment by liamdebeasi** [comment]
The OS typically kills the web process (thus causing it to restart) when the memory usage is too high and hits a pre-determined threshold. For example, the starter app may use 80 MB of memory, but perhaps the InAppBrowser is causing a temporary spike that, under the right circumstances, causes the app to consume too much memory.

Unfortunately, I'm not going to be able to help unless I can reproduce the issue on my end. If a reproducible example can't be created, then you'll need to do some debugging to identify the root cause of the issue.
