### ISSUE TITLE
bug: Error from IonReactRouter when upgrading to v7

### ISSUE THREAD

**Issue by rene-mueller** [ionic-team/ionic-framework#28799]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

After upgrading from @ionic/react-router v6 to v7 the following error occurs on `<IonReactRouter />`:
> TS2559: Type `{children: Element;}` has no properties in common with type
> `IntrinsicAttributes & IntrinsicClassAttributes<IonReactRouter> & Readonly<IonReactRouterProps`

Code (reduced):
```tsx
...
import {IonReactRouter} from '@ionic/react-router';
import {Redirect, Route} from 'react-router';
...

const Navigator: FC = () => {
    ...
    const [navigation, setNavigation] = useState<...[]>(...);
    ...
    return (
        <IntlProvider ...>
            <IonReactRouter>
                <IonTabs>
                    <IonRouterOutlet ...>
                        <Redirect exact={true} from="/" to={... || '/'}/>
                        {navigation.map(item => (
                            <Route .../>
                        ))}
                    </IonRouterOutlet>
                    <IonTabBar slot="bottom">
                        ...
                    </IonTabBar>
                </IonTabs>
            </IonReactRouter>
       </IntlProvider>
    );
}

export default Navigator;
```

### Expected Behavior

There should no error occur

### Steps to Reproduce

1. upgrade an app from v6 to v7 (including types)
2. use `<IonReactRouter />` as i used

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0
   Ionic Framework : @ionic/react 7.6.3

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.0) : 1.7.4

System:

   NodeJS : v21.5.0 (/Users/renemuller/.nvm/versions/node/v21.5.0/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
