### ISSUE TITLE
bug: IonInput change triggers IonAccordionGroup ionOnChange event

### ISSUE THREAD

**Issue by nmspackman** [ionic-team/ionic-framework#28794]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x, v7.x

### Current Behavior

When nesting an `IonInput` in an `IonAccordionGroup`, the input change event triggers and updates the accordion groups change event.

So, code that relies on the `IonAccordionGroup`'s `ionOnChange` event is called and throws errors if the types are different.

This can be resolved by calling `stopPropagation` or `stopPropagationImmediately` in the `IonInput`'s `onIonChange` event.

### Expected Behavior

The `onIonChange` events of nested input components should not trigger the surrounding `IonAccordionGroup`'s events.

### Steps to Reproduce

1. Create an `IonAccordionGroup`
2. Add `onIonChange={(e) => console.log(e.detail.value)}` as a prop to `IonAccordionGroup` 
3. Create an `IonAccordion` in the group
4. Create an `IonInput` in the `IonAccordion`

It will look something like this:
![image](https://github.com/ionic-team/ionic-framework/assets/11526734/13149843-1e84-48c3-8e28-8ffc7a0cfdcf)

5. Open up the dev tools console
6. Click on the input, enter some text, then click on another section of the screen to cause the input to lose focus and trigger the change event.

Expected Behavior:
The console should be empty (the accordion group's event isn't triggered).

Actual Behavior:
The console shows the input value (the accordion group's event is triggered).

![image](https://github.com/ionic-team/ionic-framework/assets/11526734/3481da3d-56f5-4b4e-98e6-16b2549b3ba7)

Note: The screenshots included display the accordion group's value history.

### Code Reproduction URL

https://codesandbox.io/p/sandbox/accordion-group-onionchange-z8kycp?file=%2Fsrc%2Fpages%2FHomePage.tsx%3A54%2C46

### Ionic Info

N/A

### Additional Information

The codebase I work in is using v7 and the example is using v6.

To workaround, I can just add `stopPropagation` or `stopImmediatePropagation` to the `IonInput`'s `onIonChange` event.
```
<IonInput
    aria-label="Input 1"
    onIonChange={(e) => {
        e.stopPropagation();
    }}
    placeholder="Change me"
/>
```

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this behavior, but Ionic is working as intended here. 

`ionChange` events bubble, so when you add `onIonChange` to `ion-accordion-group`, you are essentially doing `accordionGroupEl.addEventListener('ionChange', () => { ... });`. In this case, the `ionChange` event from `ion-input` is bubbling up to the `ion-accordion-group`, causing your `ionChange` callback on `ion-accordion-group` to fire.

You can check `ev.target.tagName === 'ION-ACCORDION-GROUP'` to verify that the `ionChange` event you are seeing is indeed coming from `ion-accordion-group` and not a child element.
