### ISSUE TITLE
Router.push if ginving error in7.6.3 version

### ISSUE THREAD

**Issue by nitbrillio** [ionic-team/ionic-framework#28805]
**Ionic version:**

[ ] **4.x**
[ ] **5.x**
[x] **7.x**
**I'm submitting a ...** 

[x] bug report
[ ] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
import { useIonRouter } from '@ionic/react';
    const router = useIonRouter();
    const onClick = () => {
         router.push('/pathToPage')
    }
```

**Other information:**
router.push() is giving error

**Ionic info:** 

<img width="764" alt="Screenshot 2024-01-10 at 4 14 32 PM" src="https://github.com/ionic-team/ionic-framework/assets/108856927/ba60e531-e1a3-4caf-bbd7-b724d8441425">

```
```

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
