### ISSUE TITLE
bug: Active segment button not highlighted when nested into async container

### ISSUE THREAD

**Issue by leomazza** [ionic-team/ionic-framework#28816]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

A segment with dynamic value does not highlight the selected button when nested into an `async` container.

### Expected Behavior

It should be highlighted just as it is usually the case.

### Steps to Reproduce

1. Create an `<ion-segment [value]="customValue">` with at least 2 `<ion-segment-button>`s.
2. Nest that one into a `<div *ngIf="observable$ | async">`.
3. See error

### Code Reproduction URL

https://github.com/leomazza/ionic-segment-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/leomazza/.nvm/versions/node/v20.10.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.4
   @angular-devkit/build-angular : 17.0.10
   @angular-devkit/schematics    : 17.0.10
   @angular/cli                  : 17.0.10
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.0

System:

   NodeJS : v20.10.0 (/Users/leomazza/.nvm/versions/node/v20.10.0/bin/node)
   npm    : 10.2.3
   OS     : macOS Unknown

### Additional Information

![image](https://github.com/ionic-team/ionic-framework/assets/19129296/956ca0ef-de2a-41a3-8e13-39a37189b6cd)

NOTE: The issue is with the second segment block. The first segment button is the selected one but it is not shown as active/checked.

**Comment by liamdebeasi** [comment]
Thanks, I can reproduce this. Here is a dev build if you are interested in testing a proposed fix:

```
npm install @ionic/angular@7.6.5-dev.11705415448.16878103
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28837, and a fix will be available in an upcoming release of Ionic Framework. Feel free to keep testing the dev build, and let me know if you run into any issues.
