### ISSUE TITLE
bug: v7 - React - onClick doesn't work in ionButton inside ionSelect

### ISSUE THREAD

**Issue by julio-bandeira** [ionic-team/ionic-framework#28818]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The new functionality insert ionButton inside ionSelect work noramly to visualize but when is insert a function like the onClick dosen't work, the event isn't fired, have othen events that work normaly like onTouch(Start or End).

### Expected Behavior

Just when insert the onClick and click the event be fire.

### Steps to Reproduce

```
<IonSelect
        label='Level 1'
        placeholder="Select Level 1"
        labelPlacement="floating"
        fill="solid"
        value={'test'}
        onIonChange={e=>{}}
>
       <IonSelectOption value="test">Opt</IonSelectOption>
       <IonButton fill="clear" slot="end" onClick={e=>{alert('fire')}}>
          <IonIcon slot="icon-only" color='dark' icon={addCircle}></IonIcon>
       </IonButton>
</IonSelect>
```

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI       : 7.1.1 (C:\Users\Arcano\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.6.4

Capacitor:

   Capacitor CLI      : 5.4.1
   @capacitor/android : 5.4.1
   @capacitor/core    : 5.4.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.5.1
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/28839, and a fix will be available in an upcoming release of Ionic Framework.
