### ISSUE TITLE
bug: Swiper effects dont' work on Ionic 7 + Angular

### ISSUE THREAD

**Issue by beliven-davide-lorigliola** [ionic-team/ionic-framework#28822]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Adding whatever value to `effect` property of a <swiper-container>, the effect doesn't work, even starting from a blank project.

### Expected Behavior

Expected Behavior is that `effect` property works like in the official example repo [slides-migration-samples](https://github.com/ionic-team/slides-migration-samples/tree/swiper) that, however, has ` "@ionic/angular": "^6.7.0"`

### Steps to Reproduce

1. `ionic start myApp blank`
2.  follow instructions at https://ionicframework.com/docs/angular/slides
3. launch `npm run start`

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/davidelorigliola/Library/Application Support/fnm/node-versions/v18.15.0/installation/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.4
   @angular-devkit/build-angular : 17.0.10
   @angular-devkit/schematics    : 17.0.10
   @angular/cli                  : 17.0.10
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : 5.6.0

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v18.19.0 (/Users/davidelorigliola/Library/Application Support/fnm/node-versions/v18.19.0/installation/bin/node)
   npm    : 10.2.3
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
