### ISSUE TITLE
bug: [iOS] ionic modal backdrop delay when there is simultaneous animations happening at the same time

### ISSUE THREAD

**Issue by Sovai** [ionic-team/ionic-framework#28820]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Backdrop delay a bit before closing when there are other animation happening at the same time (on iOS device only)

### Expected Behavior

The backdrop, modal sheet and my other animations close/animate simultaneously without delay

### Steps to Reproduce

I have a modal sheet component where I emit onBeforeDismiss to the child 

``` vue
// SheetModal.vue
    <ion-modal
      :keep-contents-mounted="keepAlive"
      :is-open="state"
      animated
      mode="ios"
      handleBehavior="circle"
      :showBackdrop="showBackdrop"
      @didDismiss="didDismiss"
      ...
    >
      ...
  </ion-modal>
```
```js
const beforeDismiss = () => {
  emit("sheetClose");
};
```

And here's how I call it
``` vue
// HomePage.vue
<SheetModal
@sheetClose="animateOtherStuffs"
>
...
</SheetModal>

```

when the modal is closing the same time with my other animation (just rotate chevron icon) the sheet is closed but the backdrop is delay about 1 second then close. This happen on iOS only

### Ionic Info

not able to provide

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
