### ISSUE TITLE
bug: IonLabel text-wrap broken

### ISSUE THREAD

**Issue by chrissmejia** [ionic-team/ionic-framework#28825]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

text-wrap doesn't work

### Expected Behavior

text-wrap to work

### Steps to Reproduce

Compare v6 with v7 on the official docs:

https://ionicframework.com/docs/v6/api/label
<img width="923" alt="Screenshot 2024-01-13 at 12 14 59" src="https://github.com/ionic-team/ionic-framework/assets/3825991/bfb4771b-6c27-48d9-8b93-350413e1546e">

https://ionicframework.com/docs/api/label
<img width="1069" alt="Screenshot 2024-01-13 at 12 15 25" src="https://github.com/ionic-team/ionic-framework/assets/3825991/2b3af1e6-5721-4e1f-a7d1-ac24b95c52a1">

### Ionic Info

Same as in the docs, I'm personally having the same issue on "@ionic/vue": "^7.6.3" ant patched on my side, but leaving this here to improve the framework.

### Additional Information

I'm migrating from 6.x to 7.x, 6.x was fine.

**Comment by mapsandapps** [comment]
Hi, we changed the default text wrapping of a Label within an Item in 7.6.0 ([changelog](https://github.com/ionic-team/ionic-framework/blob/main/CHANGELOG.md#760-2023-12-06)). To have a Label truncate with an ellipsis, you can add the `"ion-text-nowrap"` class. E.g. 

```
<ion-item>
  <ion-label class="ion-text-nowrap">
    Multi-line text that should ellipsis when it is too long to fit on one line. Lorem ipsum dolor sit amet,
      consectetur adipiscing elit.
  </ion-label>
</ion-item>
```

I'll update the docs to apply this class where relevant. Thanks for pointing out that the docs are incorrect!
