### ISSUE TITLE
bug: ionic should not re-focus an element when focus already moved on overlay dismiss by developer

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#28849]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Allow developer to set custom focus during overlay dismissal.

### Describe the Use Case

In the `handler` of an `ion-action-sheet`  the developer may want to restore focus to a custom element, like a text box.

### Describe Preferred Solution

Ionic overlay should detect whether focus has been set by developer, and **not** restore focus if that is so.

### Describe Alternatives

None.

### Reproduction

https://github.com/aeharding/test-focus

### Additional Information

Not sure if this is considered a feature or a bug 😅

**Comment by liamdebeasi** [comment]
Thanks, I think this makes sense to have. However, you can provide a reproduction case so I can test your PR?

**Comment by aeharding** [comment]
No problem! https://github.com/aeharding/test-focus

**Comment by liamdebeasi** [comment]
Thanks! This request makes sense. Ionic tries to focus an element inside of the previous view. However, if focus is already in the previous view then we shouldn't attempt to move focus.

**Comment by liamdebeasi** [comment]
This was fixed in https://github.com/ionic-team/ionic-framework/pull/28850. Thanks again for making the PR!
