### ISSUE TITLE
feat: ion-datetime 为什么不支持手势操作左右滑动

### ISSUE THREAD

**Issue by yushengzhen** [ionic-team/ionic-framework#28856]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

ion-datetime 是否添加手势左右滑动切换，很常用功能

### Describe the Use Case

ion-datetime 是否添加手势左右滑动切换，很常用功能

**Comment by liamdebeasi** [comment]
Hi there,

Can you please clarify the feature you are requesting? Demos of the feature in other applications would be helpful.

**Comment by lvzhenbo** [comment]
@yushengzhen 兄弟，在英文的repo里最好说英文，实在不行就机器翻译一下，然后最好按照issue的模板来说明你的要求，这次我帮你弄一下吧。（PS：ionic项目里可以用其他ui框架的，我实测是可以的）

@liamdebeasi He wanted to implement a feature in the ion-datetime component that allows you to flip a page by swiping left or right with a gesture, similar to the Action in ion-item. The actual effect is similar to the time picker component in this ui framework
https://varlet.gitee.io/varlet-ui/#/en-US/date-picker

**Comment by liamdebeasi** [comment]
Thank you! The datetime component already has this functionality built in for mobile devices. Is it not working in some scenarios? 

https://github.com/ionic-team/ionic-framework/assets/2721089/bab4a71d-7ed0-4b88-91c8-4c77e4ae16f3
