### ISSUE TITLE
bug: collapsible large title header in modal is hidden with inline modals

### ISSUE THREAD

**Issue by wibimaster** [ionic-team/ionic-framework#28867]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Since #28277 

In a page with :
```html
<ion-header></ion-header>
<ion-content>
  <ion-header collapse="condense"></ion-header>
</ion-content>
```

If a modal is open, the `opacity: 0` is applied on the background header (was not the case before).
And, the style is not removed when the modal is closed.

### Expected Behavior

The style should not be applied when open a modal (or, at least, be removed after modal close).

### Steps to Reproduce

- Open a modal
- Close the modal

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0
   Ionic Framework               : @ionic/angular 7.6.5-dev.11704916749.1e64a3a7
   @angular-devkit/build-angular : 17.1.0
   @angular-devkit/schematics    : 17.1.0
   @angular/cli                  : 17.1.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : 5.6.0

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v20.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.3.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Can you provide a runnable sample I can use to reproduce the issue? I think I know what the issue is, but I want to be certain.

**Comment by wibimaster** [comment]
> Can you provide a runnable sample I can use to reproduce the issue? I think I know what the issue is, but I want to be certain.

Yep: https://github.com/wibimaster/debug-ionic-28867
Branch **main**, just clone, `npm i` and run `ionic serve`

I have created an Ionic Angular project
`ionic start debug blank --type=angular --capacitor`
Then updated the @ionic/angular branch
`npm i --save @ionic/angular@7.6.5-dev.11704916749.1e64a3a7`
Then updated home.page.ts and home.page.html to have a modal card, iOS style

Open it, close it, and the bug is here :)

**Comment by DavidStrausz** [comment]
You can use the following workaround until a fix is released. For me it's only happening when forcing iOS mode in an otherwise MD application for an `ion-header` element (`mode="ios"`). So you may want to apply the workaround only for `md`.

```css
ion-header:not(.header-collapse-main):has(
      ~ ion-content ion-header[collapse='condense'],
      ~ ion-content ion-header.header-collapse-condense
    ) {
    opacity: 1;
  }
  ```

**Comment by liamdebeasi** [comment]
Hi everyone,

Here is a dev build with a proposed fix if anyone is interested in testing: `7.8.1-dev.11710452743.1ca99e5e`

**Comment by DavidStrausz** [comment]
Thanks @liamdebeasi, the dev build fixes the issue in my apps!

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29164, and a fix will be available in an upcoming release of Ionic Framework. Feel free to keep testing the dev build, and let me know if you have any questions.
