### ISSUE TITLE
bug: componentProps of modalController does not work with Angular 17.1.0 signal inputs

### ISSUE THREAD

**Issue by ntorrey** [ionic-team/ionic-framework#28876]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Passing componentProps (when using a modalController) throws an error when the input of the component is a signal (Input signals are a feature of Angular 17.1.0).

### Expected Behavior

The componentProps should work even if the component input is a signal.

### Steps to Reproduce

1. Create a component to pass to a modalController which has signal inputs.
2. Create a modal controller with componentProps that correspond to the component's input signals.
3. Open the modal and observe the results with dismay.

### Code Reproduction URL

https://github.com/ntorrey/ionbug

### Ionic Info

Ionic:
   Ionic CLI                     : 7.2.0 
   Ionic Framework               : @ionic/angular 7.6.6
   @angular-devkit/build-angular : 17.1.1
   @angular-devkit/schematics    : 17.1.1
   @angular/cli                  : 17.1.1
   @ionic/angular-toolkit        : 11.0.0

Capacitor:
   Capacitor CLI      : not installed
   @capacitor/android : not installed
   @capacitor/core    : not installed
   @capacitor/ios     : not installed

Utility:
   cordova-res : not installed globally
   native-run  : not installed globally

System:
   NodeJS : v18.18.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.4.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks! Here's a dev build with a fix: `7.6.2-dev.11706202387.1dfcd9b8`

Note that this is an Ionic 8 build and is subject to [breaking changes](https://github.com/ionic-team/ionic-framework/tree/FW-5923).

**Comment by ntorrey** [comment]
Seems to work now - thanks for the quick response!

**Comment by liamdebeasi** [comment]
Thanks for testing! I'm going to keep this open until the linked PR is merged.

**Comment by muuvmuuv** [comment]
Which PR? Would like to subscribe to it :)

**Comment by EinfachHans** [comment]
Just mentioned it has not been included in v8?

**Comment by SadraRahmani** [comment]
I am also having issue with this, any fixes?

**Comment by ntorrey** [comment]
Woohoo! Can't wait for the 8.2 release. It will be good to finally move off of the dev version I've been using (not in production of course 😬). Thanks for your work on this!

**Comment by sean-perkins** [comment]
Thanks for reporting this issue! This has been resolved with https://github.com/ionic-team/ionic-framework/pull/29453 and will be available in the next minor release 🎉

**Comment by sean-perkins** [comment]
👋 this is now available in [v8.2.0](https://github.com/ionic-team/ionic-framework/releases/tag/v8.2.0). Upgrade your apps and let us know if you experience any issues!

**Comment by muuvmuuv** [comment]
Works! Thanks :)
