### ISSUE TITLE
bug: Detached nodes after dismissing modal

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#28898]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When using an Ionic Dialog, I see that HTML elements are retained after dismissal

### Expected Behavior

No detached elements

### Steps to Reproduce

1. `npm build` example app
2. Serve production build artifact (I use `http-server dist`)
3. Open Chrome devtools, garbage collect, take a heap snapshot
4. Open and dismiss dialog a few times
5. Garbage collect and take another heap snapshot
6. Compare snapshots
7. Observe there are many detached HTML elements, with `pair in WeakMap` retainers

### Code Reproduction URL

https://github.com/aeharding/ionic-modal-leak

### Ionic Info

```
Ionic:

   Ionic CLI       : 7.1.1 (/Users/aeharding/.nvm/versions/node/v20.8.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.6.6

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v20.8.1 (/Users/aeharding/.nvm/versions/node/v20.8.1/bin/node)
   npm    : 10.1.0
   OS     : macOS Unknown
```

### Additional Information

<img width="1067" alt="Screenshot 2024-01-28 at 12 09 28 PM" src="https://github.com/ionic-team/ionic-framework/assets/2166114/f4a01eb8-db9e-4d27-b00f-ec218a0a1b50">

**Comment by liamdebeasi** [comment]
Thanks for the report. There are two problems here:

1. We are not properly cleaning up the dismiss animation for overlays. This prevents the element from being garbage collected when using an inline overlay. This is being tracked in https://github.com/ionic-team/ionic-framework/issues/28352, and we have in-progress work to resolve this: https://github.com/ionic-team/ionic-framework/pull/28907
2. There is a problem when using light DOM components in Stencil. This is being tracked in https://github.com/ionic-team/ionic-framework/issues/28189. The Stencil team has a fix in place, and we are currently testing inside of Ionic.

I am going to close this issue in favor of the two linked ones. Let me know if you have questions.
