### ISSUE TITLE
bug: ion-reorder does not work with dynamic list (ngFor loop)

### ISSUE THREAD

**Issue by vgahlaut** [ionic-team/ionic-framework#28909]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hi Experts,

I followed example of ion-reorder as per [documentation](documentation ), drag and drop works fine. However if I change same example to dynamic list in use ngFor in the list, list items can be dragged but does not drop for reordering.

### Expected Behavior

Reordering should work both for static list and dynamic lists.

### Steps to Reproduce

I have create a reproducer and it can be accessed [here](https://stackblitz.com/edit/ionic-ng-menu-layout-9578r3)

### Code Reproduction URL

https://stackblitz.com/edit/ionic-ng-menu-layout-9578r3

### Ionic Info

Not Sure how to check ionic info on stackblitz.com (where I created the reproducer).  However I am providing ionic info from the system where I am facing the problem using ion-reorder with dynamic list. Here it is

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\vipin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.4.1
   @angular-devkit/build-angular : 16.2.3
   @angular-devkit/schematics    : 16.2.3
   @angular/cli                  : 16.2.3
   @ionic/angular-toolkit        : 9.0.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 12.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 17 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v18.18.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.1.0
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Hello @vgahlaut, thanks for reporting this issue.

Are you trying to have multiple reorder groups? The documentation examples show a single reorder group, which is compatible with a dynamic list of items: https://stackblitz.com/edit/ionic-ng-menu-layout-j1sdm3?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by vgahlaut** [comment]
I tried with following 2 ways to put for loop. First one will create multiple reorder group as it is inside loop. But second method should have only 1 reorder group. Both has same issue

First method:

`<ion-app>
  <ion-list  *ngFor="let myitem of mylist">
    <ion-reorder-group
      [disabled]="false"
      (ionItemReorder)="handleReorder($any($event))"
    >
      <ion-item>
        <ion-label> {{ myitem }} </ion-label>
        <ion-reorder slot="end"></ion-reorder>
      </ion-item>
    </ion-reorder-group>
  </ion-list>
</ion-app>`

Second Method:

`<ion-app>
  <ion-list>
    <ion-reorder-group
      [disabled]="false"
      (ionItemReorder)="handleReorder($any($event))"
      *ngFor="let myitem of mylist"
    >
      <ion-item>
        <ion-label> {{ myitem }} </ion-label>
        <ion-reorder slot="end"></ion-reorder>
      </ion-item>
    </ion-reorder-group>
  </ion-list>
</ion-app>`

Where should I put the loop to get it working ?

**Comment by sean-perkins** [comment]
@vgahlaut both those code snippets shared will create multiple reorder groups, one for each index of the array. 

The recommend approach is to follow the example shown in the comment above: https://github.com/ionic-team/ionic-framework/issues/28909#issuecomment-1915766860

**Comment by vgahlaut** [comment]
Ohh. Ok. Thank you so much.
