### ISSUE TITLE
bug: Reactive forms Angular checkbox

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#28900]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hello!

There is no reactivity in Angular reactive forms in checkboxes with the new syntax.

I'm surprised no one has complained about this with how long ionic 7 has been around, which makes me think I'm doing something wrong. 🤔

greetings!

### Expected Behavior

Anguar reactivity should work on forms

### Steps to Reproduce

- Clone project
- Go to tab 1
- Open the console inspector to see the different console.log()

### Code Reproduction URL

https://github.com/Marius-Romanus/ionic-checkbox

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0
   Ionic Framework               : @ionic/angular 7.6.6
   @angular-devkit/build-angular : 17.1.1
   @angular-devkit/schematics    : 17.1.1
   @angular/cli                  : 17.1.1
   @ionic/angular-toolkit        : 11.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : not installed
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.9.0
   npm    : 10.1.0
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Hello @Marius-Romanus,

In your reproduction you have mistyped `formConrtolName` instead of `formControlName` when binding the reactive control to the modern form control. 

Can you try changing that and let me know if that fixes your issue?

Thanks!

**Comment by Marius-Romanus** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️ I'm very sorry for wasting your time with this silly mistake on my part. Thank you so much Sean.

**Comment by sean-perkins** [comment]
No time wasted 🙂 reporting potential issues is very much appreciated. You have helped us identify and resolve over 12 bugs in Ionic Framework. I will always take the quick win of a small typo.

Happy coding!
