### ISSUE TITLE
bug:  Select on IOS mode will not show an error state on expand icon.

### ISSUE THREAD

**Issue by JasinRefiku** [ionic-team/ionic-framework#28978]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When you mark a form control as touched on Ionic's Angular, on the IOS version, the icon won't have a highlight when it does have an error, however, on the MD version, it will.
![IOS Mode Select Container](https://github.com/ionic-team/ionic-framework/assets/93801443/106e2ecb-1d92-493e-ba5e-d43e4ea48298)
![MD Mode Select Container](https://github.com/ionic-team/ionic-framework/assets/93801443/9a6b9a32-55ec-4ece-aee6-b465e39e9296)

### Expected Behavior

Both the IOS and MD mode selects should have a highlight with the error highlight color whenever they're touched & invalid.

### Steps to Reproduce

1. Use the select component with a form control on Angular,
2. Mark the form control as touched,
3. Switch between IOS and MD mode just to be sure.

### Code Reproduction URL

[StackBlitz](https://stackblitz.com/~/github.com/JasinRefiku/ionic-bug-reports)

### Ionic Info

```Ionic:

   Ionic CLI                     : 7.1.5 (REDACTED)
   Ionic Framework               : @ionic/angular 7.7.0 (REDACTED)
   @angular-devkit/build-angular : 17.1.2 (REDACTED)
   @angular-devkit/schematics    : 17.1.2 (REDACTED)
   @angular/cli                  : 17.1.2 (REDACTED)
   @ionic/angular-toolkit        : 10.1.1 (REDACTED)

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0 (REDACTED)
   @capacitor/core    : 5.6.0 (REDACTED)
   @capacitor/ios     : 5.6.0 (REDACTED)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally
```

**Comment by liamdebeasi** [comment]
Thanks for the reproduction! This is helpful. I can reproduce the reported behavior, but Ionic is working as intended here. The difference in validation highlighting is due to differences between the design systems themselves. In this case Material Design (typically used on Android) will highlight the arrow red whereas iOS does not. `ion-select` follows both design patterns depending on the design system used.

**Comment by JasinRefiku** [comment]
Oh, very well then, how do I best achieve displaying an error state on `ion-select` (when at least an option is required to be selected), as it doesn't have any attributes/bindings on it's own regarding errors (unlike `ion-input`/`ion-textarea`)? Or, any UI/UX ideas about other components?

Thanks in the meantime!

**Comment by liamdebeasi** [comment]
You could leverage the `ion-invalid` class that is placed on `ion-select` to apply the styling you want. Alternatively, you could conditionally render some text below the select if you wanted to give a more descriptive error.
