### ISSUE TITLE
bug: Ionic textarea disabled  no scroll allowed in Firefox browser

### ISSUE THREAD

**Issue by ahmedabdelhafez** [ionic-team/ionic-framework#28974]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

i use textarea in my app and it's behavior is disabled in some cases, when test and debug it in chrome and edge it's working fine and when try it in Firefox the scrollbar for disabled input disappears after about 500ms.

### Expected Behavior

the scroll is shown in disabled field and working as expected to scroll like other browsers

### Steps to Reproduce

1. inspect the field in Firefox browser
2. disabled the field
3. add extra values multiple line to exceed the defined rows
4. scroll must appear because it has a fixes height

### Ionic Info

i test in ionic v6

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
