### ISSUE TITLE
bug: Styles in ion-input texts

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#28975]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hello!

In the new ion-input syntax in ionic 7, the classes that affect the text affect both the label and the input. You may want it to only affect the input. It also does not behave the same in Chrome as in Firefox, for example, in Firefox the class "text-decoration-line: line-through;" It doesn't affect you.

Chrome:
<img width="389" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/18282247/8a5d4c53-459b-47dc-8861-ea3e0af3330e">

Firefox:
<img width="370" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/18282247/b014b3b5-620c-43d8-8d38-54134a68c093">

greetings!

### Expected Behavior

- Being able to choose what the class affects, between the label and the input.
- That the text-decorations work in Firefox (I don't know if there are more styles that don't work)

### Steps to Reproduce

Take the example from https://ionicframework.com/docs/api/input and put styles on the text. Test in different browsers.

### Code Reproduction URL

https://stackblitz.com/edit/angular-zxkpbf-w78agc?file=src%2Fapp%2Fexample.component.css,src%2Fapp%2Fexample.component.html

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.2.0
   Ionic Framework               : @ionic/angular 7.7.0
   @angular-devkit/build-angular : 17.1.2
   @angular-devkit/schematics    : 17.1.2
   @angular/cli                  : 17.1.2
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.0

System:

   NodeJS : v20.9.0
   npm    : 10.1.0
   OS     : Windows 10
```

**Comment by mapsandapps** [comment]
Hi, thank you for your report. To target elements within an ion-input using Angular, you'll need to use a global stylesheet because of encapsulation. You can take a look at the example [here](https://ionicframework.com/docs/api/input#css-custom-properties) – click over to Angular and then view the `src/global.css` file.

Your example will have lines through the input in Firefox after adding the following code to the `global.css` file in the Stackblitz:

```
.decoration .native-input {
  text-decoration-line: line-through;
  font-weight: bold;
}
```
