### ISSUE TITLE
feat: localization calendar (`ion-datetime`)

### ISSUE THREAD

**Issue by mikoloism** [ionic-team/ionic-framework#29057]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi, at the first, i'm used `locale` props in `IonDatetime` component, but not work actually for custom locale. only translated the numbers and month name and have not able to select date because these are unordered (for example not start from 1 to 31, instead started in 25 until 31 and continue order from 1 until 24)

is there possible to set two locale and region in-same time like Samsung Calendar or Google Calendar? such as Persian Calendar (jalali), Islamic Calendar (qamari), Hebrew Calendar, etc.

> [!NOTE]
> also, i searched and found #27891 issue about RTL direction, it not work exactly!

**Comment by thetaPC** [comment]
Thank you for submitting a feature request!

This request is a duplicate. You can follow updates through the [original request](https://github.com/ionic-team/ionic-framework/issues/25568).

Closing this issue because it a duplicate.
