### ISSUE TITLE
feat: Ability to reorder horizontally in `ion-reorder `

### ISSUE THREAD

**Issue by Cimlah** [ionic-team/ionic-framework#29067]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be great to be able to reorder items horizontally, too. Now it is possible to do it only vertically

### Describe the Use Case

For example, being able to reorder photos in a photo gallery app. Reordering in y and x axis.

### Describe Preferred Solution

Implement `x` and `y` axis reordering

**Comment by liamdebeasi** [comment]
Do you have an example of the UI you are trying to accomplish with this feature?
