### ISSUE TITLE
bug: IonAert button get empty value from input

### ISSUE THREAD

**Issue by TheSoils** [ionic-team/ionic-framework#29073]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

IonAlert button handler can not get input value,just empyt string

### Expected Behavior

expected get the correct value

### Steps to Reproduce

1. add a IonAlert with inputs and buttons
![image](https://github.com/ionic-team/ionic-framework/assets/29093597/9f8a7945-53a9-424b-aef4-6126f0c57537)
2. input and click button
![image](https://github.com/ionic-team/ionic-framework/assets/29093597/b6c46108-50e3-436d-a529-00520322db8f)
3. watch the console result
![image](https://github.com/ionic-team/ionic-framework/assets/29093597/2d588188-8e9e-4b0d-9e4b-7f98ae233ebd)

### Code Reproduction URL

[reproduce](https://github.com/TheSoils/test-ion-alert)

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0 (/Users/wyman/.nvm/versions/node/v16.19.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.7.2

Capacitor:

   Capacitor CLI      : 5.7.0
   @capacitor/android : not installed
   @capacitor/core    : 5.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v16.19.0 (/Users/wyman/.nvm/versions/node/v16.19.0/bin/node)
   npm    : 9.6.1
   OS     : macOS Unknown

**Comment by TheSoils** [comment]
i found the setInterval make value empty,here is test
[test](https://github.com/TheSoils/test-ion-alert)

**Comment by sean-perkins** [comment]
Hello @TheSoils thanks for this issue. This is an implementation issue, not an issue with the `ion-alert` component. 

Every 100ms, you are forcing a complete re-render of the view and the alert. This resets the value of all the form controls in the alert. This can best be seen if you render a radio button. The selected radio button will be immediately de-selected.

I would recommend separating the render responsibility for your countdown to a separate component:
```tsx
import { useEffect, useState } from "react";

const CountDown = () => {
  const [time, setTime] = useState<Date>(new Date());

  useEffect(() => {
    const interval = setInterval(() => {
      setTime(new Date());
    }, 100);

    return () => {
      clearInterval(interval);
    };
  }, []);

  return time?.toTimeString();
};

export default CountDown;
```

and render that component in place of doing the `setInterval` at the page level component.

Thanks!
