### ISSUE TITLE
bug: ion-infinite-scroll can't be re-enabled after updating to Ionic 7

### ISSUE THREAD

**Issue by eqcb** [ionic-team/ionic-framework#29087]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I recently updated Ionic 6 to Ionic 7 and from Angular 13 to Angular 16 on my app project. After the update my main business critical page stopped working properly.

I have a list of products inside a ion-list that take 10 and update at the end with ion-infinite-scroll. When there's no more items received after a fetch, I disable it (`this.infiniteScroll.disabled = true;`) to prevent unnecessary fetches.
When the user does a refresh(ion-refresher) or apply any filter to the list I do issue a `this.infiniteScroll.disabled = false;` to ensure it get back to work.

After updating to Ionic 7, setting the disabled property to false simply stopped working and the infiniteScroll never works again.

I believe this is a critical issue that sure does screw up UX and may even make them loose interest in the app.
Please help as soon as possible.
Thank you

### Expected Behavior

The ion-infinite-scroll should be re-enabled when setting its disabled property to false as with prior versions.

### Steps to Reproduce

I edited the StackBlitz ion-infinite-scroll example taken from the ion-infinite-scroll (v7) documentation to show the issue.

1. Scroll down the list and it will stop and disable the ion-infinite-scroll when it reaches 150 items.
2. Go up and pull list down for a refresh that will clear the list and populate with new 50 items.
3. Scroll down to verify it's actually disabled.
4. Go back to the top and click the "re enable infinite" button at the top of the list to that will set .disabled = false on the element.
5. Scroll down and you'll see that the ion-infinite-scroll is still disabled.

I noticed that before clicking the re-enable button the last item of the list will be on the bottom of the view. When clicking it, there will be a gap between the last item and the bottom of the view. As if it was partially re-enabled, maybe just re-inserted in the document but stays unresponsive.

### Code Reproduction URL

https://stackblitz.com/edit/angular-wqu2xl?file=src%2Fapp%2Fexample.component.html

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (C:\Users\xxx\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.7.3
   @angular-devkit/build-angular : 15.2.10
   @angular-devkit/schematics    : 15.2.10
   @angular/cli                  : 15.2.10
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.0
   @capacitor/android : 5.0.0
   @capacitor/core    : 5.0.0
   @capacitor/ios     : 5.0.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.4

System:

   NodeJS : v20.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.6.7
   OS     : Windows 10

**Comment by brandyscarney** [comment]
Thank you for the issue! The [`complete()` method](https://ionicframework.com/docs/api/infinite-scroll#complete) on Infinite Scroll is async, so what appears to be happening is `disabled` is being set before the `complete` method is finished. I have updated your provided example to reflect this and see it working now: https://stackblitz.com/edit/angular-wqu2xl-dpbszj?file=src%2Fapp%2Fexample.component.ts

I noticed that our documentation does not include an `await`, so I have made an internal ticket to get our documentation updated. Let me know if you have any questions!

**Comment by romanarangodev** [comment]
Hi, I was having the same issue with ion infinite scroll, but after a lot of hours trying to find a solution. I found that using this.infiniteScroll.complete().then(resp=>{
             this.infiniteScroll.disabled=true
          }) works.

**Comment by bkeepers** [comment]
I just ran into this and took way too long to figure out. Like @romanarangodev, I found that you can't disable the ion-infinte-scroll element between the ion-infinite event being fired and the complete callback being called. If you do,  it will not re-enable.

This is what I was doing in Vue, which worked great in Ionic 6:

```html
  <ion-infinite-scroll
    :disabled="isLoading || isDonePaginating"
    @ion-infinite="load().then($event.target.complete)"
  >
     …
  </ion-infinite-scroll>
```

I had to stop using `disabled`, and just remove the element entirely with `v-if` once the list was done paginating.

```diff
  <ion-infinite-scroll
-   :disabled="isLoading || isDonePaginating"
+   v-if="!isDonePaginating"
    @ion-infinite="load().then($event.target.complete)"
  >
     …
  </ion-infinite-scroll>
```

The side-effect of this thought is that there are times where it will kick off multiple `@ion-infinte` events in succession if the user continues to scroll once passing the threshold, so depending on your implementation, you may want to throttle those events.

It would be ideal if the Ionic 6 behavior was restored where the element could be disabled while loading.
