### ISSUE TITLE
IOS 17.4 will stop supporting PWA for Europe

### ISSUE THREAD

**Issue by fleboulch** [ionic-team/ionic-framework#29083]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

What do you plan following this news:https://dev.to/lilxyzz/ios-174-update-ends-pwa-support-in-the-european-union-3p95#:~:text=In%20the%20latest%20iOS%2017.4,PWAs)%20within%20the%20European%20Union.

### Describe the Use Case

I was using Ionic to build such PWAs on ios and Android. Now it seems Apple will turn off the support for european users... 

### Additional Information

I don't think it's the best place to discuss this topic but I cannot register in the ionic forum with my github account.
Forry for the noise

**Comment by sean-perkins** [comment]
Hello @fleboulch, this is not the appropriate place for this discussion. 

Ionic is owned by OutSystems, not Apple. We plan to continue to focus on all the same things, as PWAs are supported on Android and iOS (outside of Europe). 

You can write your legislator, submit feedback to Apple, etc.
