### ISSUE TITLE
bug:tabbar show wrong actived tab when click tab fast

### ISSUE THREAD

**Issue by Amoyens1s** [ionic-team/ionic-framework#29092]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

current tab is tab2, but tab bar show tab1.
![img_v3_028f_e031ddbf-0d92-4e17-ace2-5221b3e4d70g](https://github.com/ionic-team/ionic-framework/assets/37032347/fa9a4deb-2b90-4e63-98dd-56df187aac4e)

### Expected Behavior

tabbar should show correct tabs

### Steps to Reproduce

1. insert many div on tabs, like `<div v-for="e in 10000">tab 1 {{ e }}</div>`
2. click tabs fast，it may occur
![image](https://github.com/ionic-team/ionic-framework/assets/37032347/1123922c-a636-42c2-8384-0710f0efeeec)
![image](https://github.com/ionic-team/ionic-framework/assets/37032347/c525ef53-f89b-42c1-a72d-bbcfd0e4bb94)

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0 (C:\Software\nvm\v20.11.0\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 7.7.3

Capacitor:

   Capacitor CLI      : 5.1.0
   @capacitor/android : 5.1.0
   @capacitor/core    : 5.1.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v20.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.2.4
   OS     : Windows 10

### Additional Information

This issue has been present since I used 7.1.1. It tends to occur when there are a large number of DOM elements on the page. I attempted to reduce the DOM count using methods like virtual scrolling, but it still frequently occurs on low-end phones.

**Comment by Amoyens1s** [comment]
i created a reproduction:  https://github.com/Amoyens1s/ionic-tabs-issue-reproduction

**Comment by liamdebeasi** [comment]
Hey there,

Apologies for the delay. I'm not able to reproduce the issue using the sample application provided. Can you please double your steps to reproduce?
