### ISSUE TITLE
bug:  ion-datetime does not correctly show time inside the picker with a field that has a default date

### ISSUE THREAD

**Issue by shapebuster** [ionic-team/ionic-framework#29093]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If i have a date  and time field with a prefilled date and time (eg i'm reporting that an event took place at 2pm on 20th Feb 2024). If i select the field, the time inside the picker shows the current time.

### Expected Behavior

Time inside the picker should reflect what is in the field so that it can be adjusted from the previously saved value. In this example the time inside the picker should show 2pm when the field is clicked. 

### Steps to Reproduce

Prefill a ion-datetime field with a value in the past. Select the field and view the time inside the date/time picker

### Ionic Info

v7
angular 15

**Comment by shapebuster** [comment]
Some screenshots:

The original date-time string was provided by the server (preflled)

![image](https://github.com/ionic-team/ionic-framework/assets/43392498/0fd49112-7964-494a-9aba-b24e1ecee2be)

If I then press "done", the time changes to 1.30am

![image](https://github.com/ionic-team/ionic-framework/assets/43392498/f9fa7ebb-c373-4b84-9f29-c925b0a899e3)

If I re open it and change it to 10:30am, both then match
![image](https://github.com/ionic-team/ionic-framework/assets/43392498/c59c1f1d-8412-47da-b605-660960f430e0)

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out.

Thank you for using Ionic!
