### ISSUE TITLE
feat: Helper & Error Text slot support in inputs

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#29100]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Hello!

Previously the helpers and errors were separate tags:

```
  <div slot="helper">Enter an email</div>
  <div slot="error">Please enter a valid email</div>
```

with the new inputs this has become helperText and errorText as an attribute within the ion-input itself ([errorText](https://ionicframework.com/docs/api/input#helper--error-text)).
This is fine if you only have one type of error, but when you have more than one or even custom errors, it forces you to create monstrous things like this:

```
<ion-input 
[errorText]="getForm['email'].invalid && (getForm['email'].dirty || getForm['email'].touched) &&
         getForm['email'].errors?.['required'] ? 'Text error 1' : 
         getForm['email'].invalid && (getForm['email'].dirty || getForm['email'].touched) &&
         getForm['email'].errors?.['pattern'] ?
          'Text error 2' :  ..."
></ion-input>
```

In that example I have only put required and pattern errors, but there could be many more

It would be nice to at least have a slot to be able to add the if to each corresponding error message and not have to make ternaries within an attribute.

Greetings!

### Describe the Use Case

ion-inputs where you may have more than one type of error

### Describe Preferred Solution

Something similar to what there is now with label:
https://ionicframework.com/docs/api/input#label-slot-experimental

**Comment by liamdebeasi** [comment]
Thanks for the report. How were you doing things with the deprecated helper/error slots? From the example you provided it looks like you would still need to conditionally render text based on the validation state. For the `helprText` property, you could extract this logic into a function so you don't need to do nested ternaries.

**Comment by Marius-Romanus** [comment]
Hello, I have never really used the helper, I have put it because they go together in the documentation (although I suppose it could also be the case that you want different help depending on an if). The one I use is the error, in version 6 it had something similar to this:

```
<ion-item>
  <ion-label position="floating">Email</ion-label>
  <ion-input formControlName="email" type="email" clearOnEdit="false"></ion-input>
  <ion-icon
    *ngIf="getForm['email'].invalid && (getForm['email'].dirty || getForm['email'].touched) && (getForm['email'].errors?.['required'] || getForm['email'].errors?.['pattern'])"
    class="center-icon-item" slot="end" name="alert-circle" color="danger"></ion-icon>
  <ion-note
    *ngIf="getForm['email'].invalid && (getForm['email'].dirty || getForm['email'].touched) && getForm['email'].errors?.['required']"
    slot="error">email error 1</ion-note>
  <ion-note
    *ngIf="getForm['email'].invalid && (getForm['email'].dirty || getForm['email'].touched) && getForm['email'].errors?.['pattern']"
    slot="error">email error 2</ion-note>
  ...
</ion-item>
```

Or to make it a little less repetitive:

```
<ion-item>
  <ion-label position="floating">Email</ion-label>
  <ion-input formControlName="email" type="email" clearOnEdit="false"></ion-input>
  <ng-container *ngIf="getForm['email'].invalid && (getForm['email'].dirty || getForm['email'].touched)">
    <ion-icon *ngIf="getForm['email'].errors?.['required'] || getForm['email'].errors?.['pattern']"
      class="center-icon-item" slot="end" name="alert-circle" color="danger"></ion-icon>
    <ion-note *ngIf="getForm['email'].errors?.['required']" slot="error">email error 1</ion-note>
    <ion-note *ngIf="getForm['email'].errors?.['pattern']" slot="error">email error 2</ion-note>
    ...
  </ng-container>
</ion-item>
```

Greetings

**Comment by Marius-Romanus** [comment]
I add a little context, it would be very similar to the Angular documentation with error handling:

https://angular.io/guide/form-validation#validating-input-in-template-driven-forms

**Comment by liamdebeasi** [comment]
Does your application architecture support the ability to extract the logic to a helper function? The benefit here is it would let you achieve the desired result and also have a template that is a bit easier to parse. Some rough pseudo code:

```html
<ion-input [errorText]="getErrorText()"></ion-input>
```

```typescript
getErrorText() {
  if (email.invalid && (email.dirty || email.touched) && email.errors?.required) {
    return 'email error 1'
  }
  
  ...
}
```

**Comment by Marius-Romanus** [comment]
Hello, yes, that logic can be implemented, but does it seem cleaner to us in the html instead of in ts?
At least to me personally it seemed cleaner to have the error messages in the html.

It is also assumed that with zone.js it is better not to have a function in a template that affects performance, but well that would be minimal and I understand that the get form also does the same in terms of performance.
But in cases where the if comes from a variable and not a function, it would improve performance.

**Comment by Marius-Romanus** [comment]
Hello, I'm sorry I couldn't answer sooner. Yes, it would be another valid option. Personally, I find it more readable and concise as it was done in the past, in HTML. Please consider that option, if you do not feel free to close the issue. :)

**Comment by liamdebeasi** [comment]
Thanks for the added info! We don't have plans to add this new API at the moment because the desired behavior is achievable with the existing API. I am going to close this, but let me know if you have any questions.
