### ISSUE TITLE
bug: Properties ionNavWillChange and ionNavDidChange do not exist on IonNav

### ISSUE THREAD

**Issue by gerhardboer** [ionic-team/ionic-framework#29114]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When upgrading to latest Ionic (v7.7.3) the build fails with error:
```
 error TS2339: Property 'ionNavDidChange' does not exist on type 'IonNav'.

44     this.ionNav.ionNavDidChange.subscribe(async () => {
                   ~~~~~~~~~~~~~~~
```

### Expected Behavior

This was not added to the breaking changes, and is still referenced in the documentation.
so the code should still work

### Steps to Reproduce

1. create a property of type `IonNav`
2. try to access ionNavDidChange
3. (IDE will probably error here)
4. run build

### Code Reproduction URL

https://stackblitz.com/edit/ionic-ion-nav-issue-reproduction?file=src%2Fmain.ts

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v21.1.0
   npm    : 10.2.5
   OS     : macOS Unknown

### Additional Information

Bug was already mentioned in https://github.com/ionic-team/ionic-framework/issues/28863 but closed without checking it properly.

**Comment by sean-perkins** [comment]
Hello @gerhardboer thank you for this issue!

Here is a dev-build that adds the missing event properties to the Angular component wrapper for `ion-nav`: 
```
npm install @ionic/angular@7.7.5-dev.11709823131.1d3df428
```

Let me know if you experience any issues, thanks!

**Comment by gerhardboer** [comment]
@sean-perkins everything works great!
thanks for the fix, can't wait for the release so we can upgrade

**Comment by gerhardboer** [comment]
do i close the issue or is that automatic when merged / released?
