### ISSUE TITLE
bug: Ion datetime constantly loops between two months when min date is set on iOS 

### ISSUE THREAD

**Issue by DevarshiDave** [ionic-team/ionic-framework#29128]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Calendar starts Looping between two months when navigating from one month to another until abruptly closed.

### Expected Behavior

Calendar should not loop between months and stay on the navigated month

### Steps to Reproduce

1. Create ionic 7 project, capacitor version 5
2. Create a form with ion datetime button and use ion datetime as popup
3. Use a min date value (any date in current month)
4. Build project for ios
5. Open in ios simulator & open the datetime
6. Click next arrow in month selection

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.7.4
   @angular-devkit/build-angular : 15.2.10
   @angular-devkit/schematics    : 15.2.10
   @angular/cli                  : 15.2.10
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 5.7.2
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : 5.6.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.1) : 1.7.4

System:

   NodeJS : v21.6.1 (/opt/homebrew/Cellar/node/21.6.1/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown

### Additional Information

Ref: https://github.com/ionic-team/ionic-framework/issues/25752

This issue is still happening and affecting applications. I have wasted so many days to fix this issue, but unable to find a fix.
The only fix i have right now is to remove the min date value and do the server side validation, however this is not an ideal solution also not a good UX.

Please fix this.

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
