### ISSUE TITLE
bug: React navigation back and history.goBack()

### ISSUE THREAD

**Issue by FernetB** [ionic-team/ionic-framework#29130]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Hello!

Right know if u:
 go from HOME-> A -> B -> C
then from C do `navigation("/B", "back", "pop")`
then from B do  `navigation("/A", "back", "pop")`
the  from A do  `history.goBack()` A goes to B instead of HOME

I know that u would ask why are u doing that? but i have a custom goBack that uses the `pushedByRoute` from the `routeInfo` in the `useIonRouter`
something like this: 
```js
  const { routeInfo, push } = useIonRouter();
  const history = useHistory();

  const routePushed = useRef<string | undefined>(routeInfo.pushedByRoute);

  const goBack = useCallback(
    (path?: string) => {
      if (path) {
        push(path, "back", "pop");
      } else {
        if (routePushed.current) {
          push(routePushed.current, "back", "pop");
        } else {
          history.goBack();
        }
      }
    },
    [history, push]
  );
```

But clarly `push(routePushed.current, "back", "pop");` does not behave like an `history.goBack()` in terms of history stack

it would be nice if it is explained a litle bit more what does really do "pop" and also in other hand, what is the main difference between `history.goBack()` and `goBack()` from `useIonRouter` that in the docs only says 
![image](https://github.com/ionic-team/ionic-framework/assets/47339424/ae771a5f-dfa3-4d87-8bc7-c9e29b5751c3)
 but not fully explains what "Navigates backwards in history, using the IonRouter to determine history" means

EDIT: I fount that either push and navigates always push the next route into the stack, and pop only pops the current path from the stack

### Expected Behavior

I dont know if it is the expected behavior, but someone would think that `push(/route, "back", "pop");` or `navigate(/route, "back", "pop");` (if used from NavContext) will behave like a `history.goBack()`

### Steps to Reproduce

Is explained before

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1
   Ionic Framework : @ionic/react 7.7.4

Capacitor:

   Capacitor CLI      : 5.2.3
   @capacitor/android : 5.2.3
   @capacitor/core    : 5.2.3
   @capacitor/ios     : 5.2.3

Utility:

   cordova-res : 0.15.1
   native-run  : 1.7.2

System:

   NodeJS : v18.16.0
   npm    : 9.5.1
   OS     : Windows 10

**Comment by FernetB** [comment]
I don't think it need reproduction because clearly push and navigate adds one history entry intro the stack, but the docs of this and the goBack from ionRouter is poorly.
Could someone explain what is the meaning of the goBack using the IonRouter to determinate history? And what is the diferente with history.goBack()

**Comment by liamdebeasi** [comment]
We ask for a reproduction so we can be sure that we are verifying the same issue that you are reporting. Routing issues can be sometimes complex to debug, so a reproduction is very helpful here too.

**Comment by thetaPC** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
