### ISSUE TITLE
bug(refresher): mode does not account for child pages with global mode set

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#29137]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When global mode is defined e.g. in angular using `IonicModule.forRoot({ mode: 'ios' })`, `ion-refresher` does not respect custom mode ('md') defined on component level on child pages.

https://github.com/ionic-team/ionic-framework/assets/26873275/014979d4-8a19-4746-8874-2db6b8dff98d

### Expected Behavior

mode on component level for `ion-refresher` should be applied also on child pages

### Steps to Reproduce

See [Stackblitz](https://stackblitz.com/edit/angular-od4spf?file=src%2Fapp%2Fhome%2Fhome-page.component.html)

1. open "Listen Now" Tab
2. pull-to-refresh --> md refresher is visible
3. click button "detail"
4. pull-to-refresh --> web refresher is visible (iOS)

### Code Reproduction URL

https://stackblitz.com/edit/angular-od4spf?file=src%2Fapp%2Fhome%2Fhome-page.component.html

### Ionic Info

7.x

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

The issue is due to the `RouterModule.forChild()` setup in `src/app/home/home-page.module.ts`, it needs some adjustments to render the correct mode. You can use the code snippet below instead of your current one, and then you'll see that the `ion-refresher` will work properly, even if your page is nested inside other pages.

```ts
RouterModule.forChild([
  {
    path: '',
    component: HomePageComponent,
    children: [
      {
        path: 'detail',
        loadChildren: () => import('./home-page.module').then(m => m.HomePageModule)
      }
    ]
  }
])
```

If there are any other problems, please open a new issue.

**Comment by thetaPC** [comment]
@DwieDima Please start a new issue just for this particular bug. We need each problem to have its own space so we can fix them properly. I highly recommend stripping the project down by removing the child pages since the new issue would focus on the tab pages. Thanks for understanding!
