### ISSUE TITLE
bug: Overlays now have aria-hidden=true when displaying a Toast

### ISSUE THREAD

**Issue by dpalou** [ionic-team/ionic-framework#29139]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

In issue https://github.com/ionic-team/ionic-framework/issues/23472, the behaviour of overlays was modified to add `aria-hidden=true` to existing overlays when displaying a new overlay. IMO this makes sense for modals and popovers, but this shouldn't be done when displaying a Toast. Toasts are overlays that don't block the interaction with the other elements in the DOM, so the rest of overlays should remain active and visible.

### Expected Behavior

Displaying a Toast should not add aria-hidden=true to other overlays.

### Steps to Reproduce

1. In an Ionic app, display any modal using ModalController.create.
2. While the modal is displayed, show a toast with a long duration using ToastController.create.
3. Inspect the DOM and search for the ion-modal. Check that it has aria-hidden="true" while the Toast is displayed.

### Code Reproduction URL

https://github.com/dpalou/overlays-toast-bug

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/dpalou/.nvm/versions/node/v18.18.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.7.4
   @angular-devkit/build-angular : 17.2.3
   @angular-devkit/schematics    : 17.2.3
   @angular/cli                  : 17.2.3
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.7.2
   @capacitor/android : not installed
   @capacitor/core    : 5.7.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v18.18.2 (/Users/dpalou/.nvm/versions/node/v18.18.2/bin/node)
   npm    : 9.8.1
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
Thanks for the report. I can reproduce this behavior. I will look into a fix.

**Comment by liamdebeasi** [comment]
Here is a dev build with a proposed fix if you are interested in testing: `7.7.5-dev.11710260658.1fc29a6c`

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29140, and a fix will be available in an upcoming release of Ionic Framework. Feel free to continue testing the dev build, and let me know if you have any questions.
