### ISSUE TITLE
bug: ion-modal .modal-shadow z-index override not applying

### ISSUE THREAD

**Issue by katquinto-voya** [ionic-team/ionic-framework#29159]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

![image](https://github.com/ionic-team/ionic-framework/assets/84733042/6a01541b-3ad5-4f7e-b498-8f5cad90aece)

![image](https://github.com/ionic-team/ionic-framework/assets/84733042/45c23623-671e-4998-8ea4-3ff7a0dca2af)

### Expected Behavior

Need to be able to override stacking of ion-page and the backdrops

### Steps to Reproduce

Screenshot attached

### Code Reproduction URL

N/A

### Ionic Info

Ionic:

   Ionic CLI : 7.1.5 (C:\Program Files\nodejs\node_modules\@ionic\cli)

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.19.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.3
   OS     : Windows 10

### Additional Information

Having issues to stack  .modal-shadow and ion-page properly, because of this, cannot close modals from mobile devices

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out. Minimal reproductions help us quickly triage issues which is why we require one.

Thank you for using Ionic!
