### ISSUE TITLE
bug: IonRouterOutlet missing the properties onPointerEnterCapture, onPointerLeaveCapture

### ISSUE THREAD

**Issue by liuwin7** [ionic-team/ionic-framework#29178]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

TS2739: Type '{ children: Element[]; }' is missing the following properties from type 'Pick<IonRouterOutlet & { basePath?: string | undefined; ref?: Ref<any> | undefined; ionPage?: boolean | undefined; } & IonicReactProps & Omit<...>, "aria-busy" | ... 253 more ... | "ionPage">': onPointerEnterCapture, onPointerLeaveCapture

### Expected Behavior

Build successfully

### Steps to Reproduce

1. `ionic start myApp blank --type react --template typescript`
2. `npm run build`
3. failed 

### Code Reproduction URL

https://codesandbox.io/p/sandbox/dazzling-cache-5snljk

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'
       
       Require stack:
       - xxx/.nvm/versions/node/v20.10.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - xxx/.nvm/versions/node/v20.10.0/lib/node_modules/@ionic/cli/lib/index.js
       - xxx/.nvm/versions/node/v20.10.0/lib/node_modules/@ionic/cli/index.js
       - xxx/.nvm/versions/node/v20.10.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.2.0 (xxx/.nvm/versions/node/v20.10.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.8.0

Capacitor:

   Capacitor CLI      : 5.7.3
   @capacitor/android : 5.7.3
   @capacitor/core    : 5.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.10.0 (xxx/.nvm/versions/node/v20.10.0/bin/node)
   npm    : 10.2.3
   OS     : macOS Unknown

**Comment by liuwin7** [comment]
This issue is same as #29171

**Comment by sabrina-stangler** [comment]
> Hi everyone,
> 
> This has been fixed in #29182. An upcoming release of Ionic Framework will have this fix.

Hello, wondering if there is a workaround in the meantime. I have a package I'm trying to use that requires @capacitor/core of at least 5.0.0 (I formerly had 4.8.0), but upgrading to 5.0.0 introduces this bug, making my app non-functional. 

What do I do in the meantime? Also, which package should I update to get the fix from the "upcoming release of Ionic Framework"?

Thank you!

**Comment by sabrina-stangler** [comment]
> Hi everyone,
> 
> This has been fixed in #29182. An upcoming release of Ionic Framework will have this fix.

@liamdebeasi 
Hello, wondering if there is a workaround in the meantime. I have a package I'm trying to use that requires @capacitor/core of at least 5.0.0 (I formerly had 4.8.0), but upgrading to 5.0.0 introduces this bug, making my app non-functional. 
package: @capacitor-community/firebase-analytics

What do I do in the meantime? Also, which package should I update to get the fix from the "upcoming release of Ionic Framework"?

Thank you!

**Comment by liamdebeasi** [comment]
The Ionic Framework bug fix was released as part of [v7.8.1](https://github.com/ionic-team/ionic-framework/releases/tag/v7.8.1).

**Comment by khanirrfan** [comment]
Now there is another issue is because of the fix, its asking for the types eventCaptures which are optional in types
