### ISSUE TITLE
bug: IonTabButton doesn't have default HTML event attributes typed

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#29174]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

IonTabButton is missing regular HTML types (onPointerDown, onTouchEnd, onTouchMove, etc)

### Expected Behavior

Should have proper types.

### Steps to Reproduce

Try to add `onPointerDown` to `IonTabButton` in React. Typescript will complain, but the touch end handler will be properly connected/called.

### Code Reproduction URL

https://stackblitz.com/edit/wl7fhb-xaawyq?file=src%2Fmain.tsx

### Ionic Info

N/A - stackblitz

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

I was able to replicate it. I verified that `onClick` doesn't cause any type errors. I would recommend using that as a workaround.

**Comment by thetaPC** [comment]
Thanks for the issue! This has been resolved via PR https://github.com/ionic-team/ionic-framework/pull/29736 and will be available in an upcoming release of Ionic.
