### ISSUE TITLE
bug: autocapitalize is required in IonSearchbar types

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#29193]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Tried to upgrade to 7.8.1/8.0.0-beta.3, notice the following:

<img width="644" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/2166114/9f85f312-0d10-4d40-b9eb-75f7d120296c">

### Expected Behavior

`autocapitalize` is optional

### Steps to Reproduce

Click repro see type error

### Code Reproduction URL

https://stackblitz.com/edit/naskdu?file=src%2FApp.tsx,src%2Fmain.tsx

### Ionic Info

N/A

**Comment by liamdebeasi** [comment]
Thanks for the report. This was an attempt to add `autocapitalize` in a backwards compatible way (since autocapitalize is enabled by default on iOS), but looks like we need to do extra work to make this possible. I'll work on a fix.

**Comment by liamdebeasi** [comment]
Here's a dev build with a proposed fix if you are interested in testing: `7.8.2-dev.11711027016.13b2a920`

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/pull/29197, and a fix will be available in an upcoming release of Ionic Framework. Feel free to keep testing the dev build, and let me know if you have any questions.
