### ISSUE TITLE
Where is the dist folder containing code on your CDN?

### ISSUE THREAD

**Issue by GarryLowther** [ionic-team/ionic-framework#29196]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

These CDN links work, but this GitHub repo contains no DIST folder
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css">
<script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
<script nomodule="" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>

### Expected Behavior

Expected to find a DIST folder in GitHub repo

### Steps to Reproduce

Read above

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework

### Ionic Info

Ionic:

   Ionic CLI : 7.2.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.13.1
   npm    : 8.3.0
   OS     : Windows 10

### Additional Information

See above

**Comment by liamdebeasi** [comment]
The `dist` directory is not committed to the repository since it is a build artifact. Instead, it is created when building Ionic. If you want to generate this directory locally you should clone the repository and then run `npm install && npm run build` in the `core` directory.
