### ISSUE TITLE
bug: Ionic 7+ Angular LoadingController with Http Interceptor Loader Present and Dismiss issue

### ISSUE THREAD

**Issue by MedOussemaNjimi** [ionic-team/ionic-framework#29207]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Issue Description:

I'm encountering an issue with the LoadingController in Ionic 7 when used in conjunction with an HttpInterceptor. The LoadingController is not being presented or dismissed correctly in certain scenarios.

Steps to Reproduce:

With this logic in interceptor and with 2 call Api you will see the error that the loading dose't dismiss correctly

### Expected Behavior

The loading spinner should be dismissed when the HTTP request completes or encounters an error.

### Steps to Reproduce

try to integrate my Interceptor in your code

### Code Reproduction URL

https://gitlab.com/oussemanjimi93/clubi-mobile

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/mohamedoussemanjimi/.nvm/versions/node/v21.0.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.0
   @angular-devkit/build-angular : 16.2.6
   @angular-devkit/schematics    : 16.2.6
   @angular/cli                  : 16.2.6
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : 5.5.0

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v21.0.0 (/Users/mohamedoussemanjimi/.nvm/versions/node/v21.0.0/bin/node)
   npm    : 10.2.5
   OS     : macOS Unknown

**Comment by liamdebeasi** [comment]
I'm not able to access your repro. Can you ensure it is public?
