### ISSUE TITLE
bug: IonListHeader and IonButton inconsistent alignment

### ISSUE THREAD

**Issue by DunhamGitHub** [ionic-team/ionic-framework#29220]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Ionic 7:

<img width="387" alt="Screenshot 2024-03-26 at 10 11 32" src="https://github.com/ionic-team/ionic-framework/assets/6884752/8584a4c0-52e6-4260-ab2f-e47abf6c9826">

<img width="387" alt="Screenshot 2024-03-26 at 10 11 32" src="https://github.com/ionic-team/ionic-framework/assets/6884752/25f583bc-9510-45cb-aebb-53e26129742d">

### Expected Behavior

Ionic 4:

<img width="387" src="https://github.com/ionic-team/ionic-framework/assets/6884752/f4916d53-f26d-4357-aaf5-5b6e75966344">

<img width="387" src="https://github.com/ionic-team/ionic-framework/assets/6884752/3be9e341-ae66-4433-9dc6-28e90c17869d">

### Steps to Reproduce

```

                <IonItem routerLink="/main/client-list" routerDirection="back" detail={ false }>
                  <IonListHeader style={{ color: '#2A5AAD' }}>
                    <IonLabel>{ store.clientFilterName }</IonLabel>
                  </IonListHeader>
                  <IonButton fill="clear" slot="start">
                    <IonIcon slot="icon-only" icon={ arrowBack } />
                    <IonIcon slot="icon-only" icon={ personAdd } />
                  </IonButton>
                </IonItem>
```

### Code Reproduction URL

_

### Ionic Info

```
Ionic:

   Ionic CLI       : 7.2.0 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 7.8.1

Capacitor:

   Capacitor CLI      : 5.7.3
   @capacitor/android : not installed
   @capacitor/core    : 5.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v20.11.1 (/opt/homebrew/Cellar/node@20/20.11.1_1/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown
```

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

I was unable to replicate the issue using the provided code snippet in v7. It displays aligned for me:
![Screenshot 2024-03-26 at 5 08 52 PM](https://github.com/ionic-team/ionic-framework/assets/13530427/5ce72035-6b23-4a67-ac8b-c4955ecc7603)

Please provide a minimal repro in order for us to debug this issue.

**Comment by DunhamGitHub** [comment]
Thank you for your reply.
I have started a vanilla example and indeed it looks normal. But I noticed that when "ios" seems to be used for themes it does not look right...

Looks ok (md style):
<img width="843" alt="Screenshot 2024-03-27 at 06 37 35" src="https://github.com/ionic-team/ionic-framework/assets/6884752/e8a2c07c-6bbc-438f-8c86-3662ca901357">

Does not look ok (ios style):
<img width="856" alt="Screenshot 2024-03-27 at 06 39 27" src="https://github.com/ionic-team/ionic-framework/assets/6884752/9409b453-88de-4a2b-97e1-3c49738b4442">

Question then, if I may:
1. What makes the `ios` or `md` style being applied?
2. Seems the `ios` styling is wrong? (I can deliver my vanilla app as soon as 1. is answered)

**Comment by DunhamGitHub** [comment]
I was able to set `mode="ios"` to recreate the problem, in the vanilla example I created this page:

```
import { IonNote, IonLabel, IonListHeader, IonList, IonItem, IonButtons, IonMenuButton, IonIcon, IonButton, useIonLoading, IonContent, IonHeader, IonPage, IonTitle, IonToolbar } from '@ionic/react';
import ExploreContainer from '../components/ExploreContainer';
import {
  power,
  personAdd,
  arrowBack
} from 'ionicons/icons';



const Test_Menu: React.FC = () => {
  const [present, dismiss] = useIonLoading();
  return (
    <IonPage id="main-page">
          <IonHeader mode="ios">
            <IonToolbar mode="ios">
              <IonButtons slot="start">
                <IonMenuButton></IonMenuButton>
              </IonButtons>
              <IonTitle>Header test</IonTitle>
              <IonButton routerLink="/login" routerDirection="back" fill="clear" slot="end">
                <IonIcon slot="icon-only" icon={ power } />
              </IonButton>
            </IonToolbar> 
          </IonHeader>

          <IonContent className="ion-padding" forceOverscroll={ true }>
                <IonItem mode="ios" routerLink="/main/client-list" routerDirection="back" detail={ false }>
                  <IonListHeader mode="ios" style={{ color: '#2A5AAD' }}>
                    <IonLabel>test</IonLabel>
                  </IonListHeader>
                  <IonButton fill="clear" slot="start" >
                    <IonIcon slot="icon-only" icon={ arrowBack } />
                  </IonButton>
                </IonItem>
              
            <IonList>
              <IonItem routerLink="/main/cash" detail>
                <IonLabel>Cash</IonLabel>
                <IonNote slot="end">
                  test
                </IonNote>
              </IonItem>
            </IonList>
          </IonContent>

        </IonPage>
  );
};

export default Test_Menu;

```

<img width="486" alt="Screenshot 2024-03-27 at 07 06 50" src="https://github.com/ionic-team/ionic-framework/assets/6884752/ba7abce3-357c-4625-ab38-7ada70c35352">

**Comment by thetaPC** [comment]
After further inspection, I was able to replicate the issue. This is due to the way the code is being structured, not the mode being used. I would recommend reviewing the `ion-list-header` [docs page](https://ionicframework.com/docs/api/list-header), it has a great example on [how to add buttons](https://ionicframework.com/docs/api/list-header#buttons-in-list-headers).

![Screenshot 2024-03-27 at 10 38 04 AM](https://github.com/ionic-team/ionic-framework/assets/13530427/e036c0da-c62d-4778-a56f-a1dc2401c7f6)

This is the code snippet that will align the button and the list header:

```tsx
<IonList>
  <IonListHeader style={{ color: '#2A5AAD' }}>
    <IonButton fill="clear">
      <IonIcon slot="icon-only" icon={ arrowBack } />
      <IonIcon slot="icon-only" icon={ personAdd } />
    </IonButton>
    <IonLabel>Video Games</IonLabel>
  </IonListHeader>
  <IonItem>
    <IonLabel>Pokémon Yellow</IonLabel>
  </IonItem>
  <IonItem>
    <IonLabel>Mega Man X</IonLabel>
  </IonItem>
  <IonItem>
    <IonLabel>The Legend of Zelda</IonLabel>
  </IonItem>
  <IonItem>
    <IonLabel>Pac-Man</IonLabel>
  </IonItem>
  <IonItem>
    <IonLabel>Super Mario World</IonLabel>
  </IonItem>
</IonList>
```

There have been a lot of changes since Ionic 4 and code structures have changed. Here's an [upgrade guide](https://ionicframework.com/docs/updating/7-0) that might be useful to determine what those code changes can be.

I'm closing this issue since it was due to code structuring.
