### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by avatier-leonardoc** [ionic-team/ionic-framework#29242]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When running ionic serve / ionic build I get the following warnings

▲ [WARNING] 2 rules skipped due to selector errors:
[ng]   .modal-fullscreen::part(content) -> Pseudo-elements are not supported by css-select
[ng]   ion-select::part(container) -> Pseudo-elements are not supported by css-select

### Expected Behavior

Do not show these warnings

### Steps to Reproduce

1. Add a pseudo-elements explained on 'https://ionicframework.com/docs/ja/v6/theming/css-shadow-parts' to CSS
2. run ionic server or ionic build --prod
3. Get the warning

### Code Reproduction URL

https://ionicframework.com/start#basics

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (C:\Users\leoba\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.8.2
   @angular-devkit/build-angular : 17.3.2
   @angular-devkit/schematics    : 17.3.2
   @angular/cli                  : 17.3.2
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 5.7.4
   @capacitor/android : 5.7.4
   @capacitor/core    : 5.7.4
   @capacitor/ios     : 5.7.4

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.11.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.18.0
   OS     : Windows 10

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
