### ISSUE TITLE
bug: Layout fragment in Android is mispositioned

### ISSUE THREAD

**Issue by mezoistvan1** [ionic-team/ionic-framework#29254]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

We use a custom Android plugin that shows a full screen video on Android. After the Ionic 7 update, the position of the video is based upon the scroll position of the `ion-content` in the current page. This results in an off-screen video fragment if the page has been scrolled. This has not been a problem in previous versions of Ionic.

![image](https://github.com/ionic-team/ionic-framework/assets/92982033/89f28ef5-49d0-4258-b452-679a4a9483c9)

Weirdly, adding `overflow: hidden` to the `ion-content` solves this issue. This seems like a bug in `ion-content`, since adding `overflow: hidden` to the main elements (not the shadow parts!) has no impact on how `ion-content` works, and yet it solves this positioning issue.

### Expected Behavior

The video player fragment should be positioned correctly, always in the middle of the screen.

### Steps to Reproduce

In an android Ionic app, scroll the main `ion-content` and open a fullscreen video using https://www.npmjs.com/package/capacitor-brightcove-player. 

### Code Reproduction URL

https://github.com/mezoistvan1/ionic-android-video-fragment-layout

### Ionic Info

[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 6.20.9

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v20.11.1
   npm    : 10.2.4
   OS     : macOS Unknown

  ────────────────────────────────────────────────

     Ionic CLI update available: 6.20.9 → 7.1.1
         Run npm i -g @ionic/cli to update

  ────────────────────────────────────────────────

### Additional Information

We migrated the ionic app to an nx monorepo, and we don't use the ionic CLI directly anymore.

**Comment by amandaejohnston** [comment]
Thank you for the issue. Could you create a minimal code reproduction that shows the problem using `ion-content` and a plain HTML element, without any third party plugins? This way we can isolate the behavior to Ionic Framework. Can you also ensure that the new reproduction is public? (The repo currently linked is private.)
