### ISSUE TITLE
bug: ion-icons have different sizes when combined with ion-toggle, ion-checkbox or ion-radio inside of an ion-item

### ISSUE THREAD

**Issue by FranciskoNeves** [ionic-team/ionic-framework#29319]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I have a list off settings, and each setting (ion-item) have an icon at start (ion-icon) and a setting after the icon (ion-select, ion-label and ion-toggle). With ion-select and ion-label, the icon has the same width and height(ex: 24x24) but when I use the ion-toggle the icon has a different size(ex: 23x24).
![Screenshot 2024-04-10 163451](https://github.com/ionic-team/ionic-framework/assets/22598113/5fee16e4-cdc5-4fa1-aeda-ab9447baffb7)
![Screenshot 2024-04-10 163500](https://github.com/ionic-team/ionic-framework/assets/22598113/6b7e942b-262a-4d2a-a98d-d104753c7ea2)
![Screenshot 2024-04-10 163658](https://github.com/ionic-team/ionic-framework/assets/22598113/3eb3aaa1-0ee0-4f15-aaea-487391045856)
![Screenshot 2024-04-10 163517](https://github.com/ionic-team/ionic-framework/assets/22598113/a546c167-809c-4a96-9719-311766ec97b4)

### Expected Behavior

The icon should stay with the same size in every situation.

### Steps to Reproduce

This is the code to reproduce the behaviour:

    <ion-list>

    <ion-item lines="none" >
      <ion-icon name="school" color="primary"></ion-icon>
      <ion-select class="ion-item-end" interface="popover" (ionChange)="chooseIntro($event)" placeholder="{{ 'introPlaceholder' | translate }}" cancelText="{{ 'cancel' | translate }}"
        okText="{{ 'ok' | translate }}" label="{{ 'tutorial' | translate }}" labelPlacement="start">
        <ion-select-option *ngFor="let intro of globalService.tutorialPages" [value]="intro">
          {{ intro.Title | translate }}
        </ion-select-option>
      </ion-select>
    </ion-item>

    <ion-item lines="none">
      <ion-icon name="compass" color="primary"></ion-icon>
      <ion-toggle color="primary" justify="space-between" (ionChange)="updateLocation()" [(ngModel)]="globalService.storedLocationShare">
        {{ "locationShare" | translate }}
      </ion-toggle>
    </ion-item>

    <ion-item lines="none" (click)="openSetting()">
      <ion-icon name="options" color="primary" ></ion-icon>
      <ion-label class="ion-text-start" color="primary">{{ "preferences" | translate }}</ion-label>
    </ion-item>
    </ion-list>

### Code Reproduction URL

https://github.com/FranciskoNeves/IonToggleIonIconConflict

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0
   Ionic Framework               : @ionic/angular 7.8.1
   @angular-devkit/build-angular : 17.3.1
   @angular-devkit/schematics    : 17.1.3
   @angular/cli                  : 17.1.3
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 5.7.4
   @capacitor/android : 5.7.4
   @capacitor/core    : 5.7.4
   @capacitor/ios     : 5.7.4

Cordova:

   Cordova CLI       : 12.0.0 (cordova-lib@12.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v18.19.0
   npm               : 10.2.3
   OS                : Windows 10

**Comment by brandyscarney** [comment]
Thanks for the issue! I was able to reproduce this using your example. This is also happening with the `ion-checkbox` and `ion-radio` components. As a workaround, you should be able to apply the following CSS:

```
ion-item ion-icon {
  flex-shrink: 0;
}
```

Here is a demo: https://codepen.io/brandyscarney/pen/vYMrZGe
