### ISSUE TITLE
bug: Cannot change ion-fab-button background using the provided css variables

### ISSUE THREAD

**Issue by djbanana1** [ionic-team/ionic-framework#29318]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

If i add the ion-fab-button:

<ion-fab>
  <ion-fab-button>
    <ion-icon name="add"></ion-icon>
  </ion-fab-button>
</ion-fab>

I am not able to change it's background style using the provided variable:
ion-fab-button {
  --background: #b7f399;
  --background-activated: #87d361;
  --background-hover: #a3e681;
  --background-focused: #87d361;
}

It seems that they are not used in the fab-button:

![image](https://github.com/ionic-team/ionic-framework/assets/58427793/ece30460-0f5b-412b-92cc-12d9e317ca1b)

### Expected Behavior

When setting the mentioned css from above, i would expect the background color to change.

### Steps to Reproduce

1. Add the ion-fab-button in the code
2. Add the style properties in a global file
3. Background is not changing

### Code Reproduction URL

Not existing

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.8.4
   @angular-devkit/build-angular : 17.1.2
   @angular-devkit/schematics    : 17.1.2
   @angular/cli                  : 17.1.2
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 5.6.0
   @capacitor/android : 5.6.0
   @capacitor/core    : 5.6.0
   @capacitor/ios     : 5.6.0

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.11.0 (/Users/lucaderivaz/.nvm/versions/node/v20.11.0/bin/node)
   npm    : 10.2.4
   OS     : macOS Unknown
   Xcode  : Xcode 15.2 Build version 15C500b

### Additional Information

I also updated it to the latest v7.8.4 and it didn't fix the problem

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out. As noted in the issue template, all bug reports require a reproduction URL that the team can run. This allows us to effectively root-cause issues.

Thank you for using Ionic!
