### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by salvisb** [ionic-team/ionic-framework#29344]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I'm aware that it's possible to import the Ionic framework from a CDN (https://ionicframework.com/docs/intro/cdn#ionic-framework-cdn), which provides an excellent opportunity for using Ionic UI components with Vanilla JavaScript or any other front-end framework of choice. However, I'm hesitant to use a CDN in production. Would the maintainers consider publishing a standalone version of the framework on NPM? Or perhaps it's already published, and I simply can't find it? Thanks!

### Describe the Use Case

Ability to use Ionic UI Components with different front-end stacks.

**Comment by liamdebeasi** [comment]
Hey there,

We publish [`@ionic/core` ](https://www.npmjs.com/package/@ionic/core) which you can use. The "JavaScript" tab on the playgrounds show how to use this package. Example: https://ionicframework.com/docs/api/alert. I am going to close this, but let me know if you have any questions.
