### ISSUE TITLE
feat: Export files in `utils` in distribution

### ISSUE THREAD

**Issue by oliveryasuna** [ionic-team/ionic-framework#29367]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be useful if developers could use methods/code in `utils`.

### Describe the Use Case

There are many use cases for the various symbols under this folder.

My particular use would be functions in `overlays.ts`, as I am writing a custom overlay component.

### Additional Information

Thanks for considering!

**Comment by liamdebeasi** [comment]
Can you please clarify which specific utils you need as well as use cases?

**Comment by oliveryasuna** [comment]
> Can you please clarify which specific utils you need as well as use cases?

Hi @liamdebeasi. I mentioned this in my issue:

> My particular use would be functions in `overlays.ts`, as I am writing a custom overlay component.

**Comment by sean-perkins** [comment]
@oliveryasuna can you provide information around the specific utilities or behaviors you are looking to leverage from Ionic Framework's internals?

We do not consider these APIs public, so we are able to make changes and "breaking changes" across patch/minor releases. By making APIs public, we have additional restrictions we have to be aware of and can limit our effectiveness to addressing bugs.

If we can better understand the behavior you are having issues implementing in your custom overlay, we can explore alternate paths to solving that, such as exposing APIs to have our utilities apply to custom overlays without you needing to call them directly.
