### ISSUE TITLE
bug: ionic8 Conflict between font color and theme color in new dark mode

### ISSUE THREAD

**Issue by lvzhenbo** [ionic-team/ionic-framework#29361]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

The primary background font is black

### Expected Behavior

Generally speaking, the black and white font should be the same as v7, with a light background black font or a dark background light font

### Steps to Reproduce

Import dark themes according to the instructions of v8 version

### Code Reproduction URL

https://github.com/lvzhenbo/ionic8-dark

### Ionic Info

I don't think it's necessary to provide

### Additional Information

![image](https://github.com/ionic-team/ionic-framework/assets/32427677/a928616c-0daa-4250-ad8a-33817aed631c)
![Screenshot_2024-04-19-02-16-49-226_com tsdm39 app](https://github.com/ionic-team/ionic-framework/assets/32427677/ac2c112b-aab2-4fe5-a072-88c41328595a)
![Screenshot_2024-04-19-02-17-35-495_com tsdm39 app](https://github.com/ionic-team/ionic-framework/assets/32427677/c12273d4-61c4-4387-a2cb-617d90724395)

**Comment by sean-perkins** [comment]
Hello @lvzhenbo can you please clarify on what part of the experience is incorrect or unexpected?

The color palette of Ionic Framework v7 was not AA color compliant. Apple's own implementation of using white text on a primary (blue) background also does not pass AA color compliance. The color palette of Ionic Framework v8 is AA color compliant to provide a more readable and accessible experience to users. 

Developers can choose to customize these colors as they see fit.

**Comment by lvzhenbo** [comment]
Ok, I've searched for the question and learned that it was an intentional change, thanks for the answer!
