### ISSUE TITLE
bug: Auto foucs in ios not work (ionic vue)

### ISSUE THREAD

**Issue by Sujuforny** [ionic-team/ionic-framework#29365]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x, v8.x

### Current Behavior

When I route to new page and the page have input box .I wanna set auto focus on this input box 

### Expected Behavior

It focus on the input box but keyboard not up (only ios)

### Steps to Reproduce

 click to new page and set focus

### Code Reproduction URL

https://github.com/Sujuforny/autoFoucsIOS.github.io.git

### Ionic Info

@ionic/vue:6+,

### Additional Information

 IDK

**Comment by liamdebeasi** [comment]
Thanks for the report. Please see https://ionicframework.com/docs/developing/managing-focus for information on how you can manage focus as well as the limitations that `autofocus` has on iOS.
