### ISSUE TITLE
bug: iOS - Tap on status bar doesn’t scroll to top

### ISSUE THREAD

**Issue by socialmedialabs** [ionic-team/ionic-framework#29376]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x, v8.x

### Current Behavior

When tapping the status bar in Safari on iOS or iPadOS (nor Simulator) the content would not scroll to the top. Nothing happens at all.

Tested on iOS/iPadOS 17.4.1

### Expected Behavior

Tapping on the status bar of an Apple mobile device should always scroll the content of a page to the top.

### Steps to Reproduce

1. With an Apple mobile device go to either of the following urls
https://ionicframework.com/docs/usage/v8/infinite-scroll/basic/demo.html
https://ionicframework.com/docs/usage/v8/header/translucent/demo.html
2. Scroll to the bottom of each page
3. Tap the status bar (nothing happens)

### Code Reproduction URL

https://ionicframework.com/docs/usage/v8/infinite-scroll/basic/demo.html

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16 (/home/ubuntu/.nvm/versions/node/v21.6.1/lib/node_modules/ionic)

Capacitor:

   Capacitor CLI   : 6.0.0
   @capacitor/core : 6.0.0

Utility:

   cordova-res : not installed
   native-run  : 2.0.1

System:

   NodeJS : v21.6.1 (/home/ubuntu/.nvm/versions/node/v21.6.1/bin/node)
   npm    : 10.2.4
   OS     : Linux 6.5

### Additional Information
I am using Ionic Vue
_No response_

**Comment by DwieDima** [comment]
@socialmedialabs did you apply `statusTap: true` for your config?

```typescript
import { IonicVue } from '@ionic/vue';
import { createApp } from 'vue';

createApp(App).use(IonicVue, {
  statusTap: true
});
```

https://ionicframework.com/docs/developing/config

**Comment by socialmedialabs** [comment]
That's exactly what I have:
```javascript
const getConfig = () => {
  return {
    // mode: 'ios'
    hardwareBackButton: false,
    innerHTMLTemplatesEnabled: true,
    statusTap: true,
    swipeBackEnabled: false,
  }
}
```
and then
```javascript
const app = createApp(App)
  .use(pinia)
  .use(IonicVue, getConfig())
  .use(router)
```

(the `swipeBackEnabled` option has no effect either, btw)

**Comment by liamdebeasi** [comment]
This is to be expected in a web browser. The status bar tap enabled by `statusTap: true` relies on the Capacitor status bar plugin which only functions in a Capacitor application.

In a web browser, iOS handles the status bar scroll to top when scrolling on the `body` element. Since your Ionic app scrolls on the `ion-content` element and not `body`, tapping the status bar will not scroll the `ion-content` to the top. iOS does not expose any additional APIs for us to control this unfortunately.
