### ISSUE TITLE
feat: Expose ion-input/ion-searchbar value as a signal in Angular

### ISSUE THREAD

**Issue by JulienLecoq** [ionic-team/ionic-framework#29370]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like the value property of ion-input, ion-searchbar and similar components to be exposed as signals instead of raw values. This would allow to enhance reactivity and performance in Ionic apps built with Angular by working smoothly with the OnPush change detection and the future Signal based change detection.

I myself created wrapper around Ionic components to have such fields exposed as signals.

### Describe the Use Case

Allows to easily listen to changes, and create computed values from inputs.
Allows to easily use OnPush change detection, for example this, becomes possible and is reactive if used inside templates:

```ts
isEmpty() {
    this.myInput().value() === "" || this.myInput().value() === undefined || this.myInput().value() === null
}
```

### Describe Preferred Solution

Just expose a field which would hold the current input value as a signal.

**Comment by liamdebeasi** [comment]
Thanks for the report. I am going to close this since this behavior is already achievable in Ionic Framework. Developers should use the [`model` signal](https://angular.io/api/core/model) to have reactive signals with Ionic component values:

```html
<ion-searchbar [(ngModel)]="searchbarValue"></ion-searchbar>
```

```js
import { model } from '@angular/core';

...

searchbarValue = model('123');
