### ISSUE TITLE
bug: bundle size increase with IonicModule and lazy loaded web components in v8.0.1

### ISSUE THREAD

**Issue by StefanNedelchev** [ionic-team/ionic-framework#29393]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.0.1

### Current Behavior

Some extra modules seem to have been included in man JS chunk which results in drastically higher bundle size. This happened just by updating Ionic  from 8.0.0 to 8.0.1 without any code changes. My project is not converted to Ionic Standalone components yet.

initial chunk files after a prod build (8.0.1):
![Screenshot from 2024-04-24 18-49-33](https://github.com/ionic-team/ionic-framework/assets/15238282/6a84dd8f-57f2-4ed0-bffa-14644bb5f716)

webpack bundle analysis (the outlined module with red is the extra stuff that we never had before)
![after](https://github.com/ionic-team/ionic-framework/assets/15238282/05852501-663c-4667-8fd2-fff053bdc824)

### Expected Behavior

Main JS chunk size to remain the same or at least with a minimal impact

initial chunk files after a prod build (8.0.0):
![Screenshot from 2024-04-24 18-50-53](https://github.com/ionic-team/ionic-framework/assets/15238282/97ca3d19-9b44-499c-a131-4fa5ae396b32)

webpack bundle analysis
![Screenshot 2024-04-24 at 18-56-03 sleda 24 Apr 2024 at 18 55](https://github.com/ionic-team/ionic-framework/assets/15238282/b4f20747-ea29-433a-9345-c3d647bf998c)

### Steps to Reproduce

1. Initialize a brand new project with the CLI by selecting Angular and Modules (instead of standalone Ionic components) as a framework and use v8.0.0 (manually pin down the ionic version to 8.0.0 if necessary).
2. Do a production build with `ionic build --prod` and check out the size of the output main.js file
3. Bump the ionic version to 8.0.1 and repeat step 2

### Code Reproduction URL

https://angular-ctnsgh-ifi6by.stackblitz.io

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.0.1
   @angular-devkit/build-angular : 17.3.5
   @angular-devkit/schematics    : 17.3.5
   @angular/cli                  : 17.3.5
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.0.0
   @capacitor/android : not installed
   @capacitor/core    : 6.0.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.12.2 (/usr/bin/node)
   npm    : 10.5.2
   OS     : Linux 6.5

**Comment by sean-perkins** [comment]
Hello @StefanNedelchev, I am unable to reproduce your described issue with a new starter and comparing the compiled bundle output between v8.0.0 and v8.0.1.

|v8.0.0|v8.0.1|
|---|---|
|![CleanShot 2024-04-24 at 13 14 46](https://github.com/ionic-team/ionic-framework/assets/13732623/b12c4875-a6a6-4926-9b60-85b2f8351e08)| ![CleanShot 2024-04-24 at 13 14 02](https://github.com/ionic-team/ionic-framework/assets/13732623/0921173a-ff6d-4222-ba25-86cf881c3392)|

Can you please review your reproduction steps and provide a reproduction that can reproduce the issue?

Thanks!

**Comment by StefanNedelchev** [comment]
> Hello @StefanNedelchev, I am unable to reproduce your described issue with a new starter and comparing the compiled bundle output between v8.0.0 and v8.0.1.
> v8.0.0 	v8.0.1
> ![CleanShot 2024-04-24 at 13 14 46](https://private-user-images.githubusercontent.com/13732623/325319827-b12c4875-a6a6-4926-9b60-85b2f8351e08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODIxNzIsIm5iZiI6MTcxMzk4MTg3MiwicGF0aCI6Ii8xMzczMjYyMy8zMjUzMTk4MjctYjEyYzQ4NzUtYTZhNi00OTI2LTliNjAtODViMmY4MzUxZTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE4MDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZWJhYTBhZjM4ZmU1OTk0ODIyNGMwMzMzZWI3Mzk5M2MxNDBhYmQ3MmMwZjQzNjAxMWQwNjUzMDU0MDBkODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3-7ZQFWf7Et9NyS1x1c2sLvBzQV5JOVLX1lpoggbfas) 	![CleanShot 2024-04-24 at 13 14 02](https://private-user-images.githubusercontent.com/13732623/325319658-0921173a-ff6d-4222-ba25-86cf881c3392.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODIxNzIsIm5iZiI6MTcxMzk4MTg3MiwicGF0aCI6Ii8xMzczMjYyMy8zMjUzMTk2NTgtMDkyMTE3M2EtZmY2ZC00MjIyLWJhMjUtODZjZjg4MWMzMzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE4MDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxM2VjM2YyMDVkMWY1NDU5MWRkZDMxNTIzYmRiZTVhZmIxNzc1NGE2ZjlmNWUyMTA3Y2IxNmUzZGM5NDdhZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2wNfq5mkZD_wSGwfB57-bsWpt6LtfO_NsAOALs2yl7I)
> 
> Can you please review your reproduction steps and provide a reproduction that can reproduce the issue?
> 
> Thanks!

@sean-perkins  Thanks for the response. You are right, there seems to be one key thing that I didn't (know is important to) mention - the project uses IonicModule instead of standalone Ionic components. Here's how it is on a clean Ionic Sidemenu project with IoncModules

8.0.0
![Screenshot from 2024-04-24 21-11-18](https://github.com/ionic-team/ionic-framework/assets/15238282/2f41961a-3094-4653-9323-fb156c1df025)

8.0.1
![Screenshot from 2024-04-24 21-13-12](https://github.com/ionic-team/ionic-framework/assets/15238282/246a6f7e-3a79-4381-a3c5-6bc7be7f9322)

**Comment by sean-perkins** [comment]
Thanks @StefanNedelchev I am able to reproduce with the lazy loaded web components (`IonicModule`). I've narrowed this to a recent dependency bump to v4.17.0 of Stencil. 

I'm working with the Stencil team to root cause the changes causing this and work towards a fix.

**Comment by StefanNedelchev** [comment]
@sean-perkins thanks for the quick reaction and thanks for still supporting IonicModule because unfortunately some users like me will keep using it until #28574 gets resolved.
