### ISSUE TITLE
@ionic/react-router  not compatible with latest version of   ERROR in ./node_modules/@ionic/react-router/dist/index.js 890:18-28 export 'withRouter' (imported as 'withRouter') was not found in 'react-router-dom

### ISSUE THREAD

**Issue by superm123** [ionic-team/ionic-framework#29415]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

When upgrading  getting the following error message:
ERROR in ./node_modules/@ionic/react-router/dist/index.js 890:18-28
export 'withRouter' (imported as 'withRouter') was not found in 'react-router-dom' (possible exports: AbortedDeferredError, Await, BrowserRouter, Form, HashRouter, Link, MemoryRouter, NavLink, Navigate, NavigationType, Outlet, Route, Router, RouterProvider, Routes, ScrollRestoration, UNSAFE_DataRouterContext, UNSAFE_DataRouterStateContext, UNSAFE_ErrorResponseImpl, UNSAFE_FetchersContext, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, UNSAFE_ViewTransitionContext, UNSAFE_useRouteId, UNSAFE_useScrollRestoration, createBrowserRouter, createHashRouter, createMemoryRouter, createPath, createRoutesFromChildren, createRoutesFromElements, createSearchParams, defer, generatePath, isRouteErrorResponse, json, matchPath, matchRoutes, parsePath, redirect, redirectDocument, renderMatches, resolvePath, unstable_HistoryRouter, unstable_usePrompt, unstable_useViewTransitionState, useActionData, useAsyncError, useAsyncValue, useBeforeUnload, useBlocker, useFetcher, useFetchers, useFormAction, useHref, useInRouterContext, useLinkClickHandler, useLoaderData, useLocation, useMatch, useMatches, useNavigate, useNavigation, useNavigationType, useOutlet, useOutletContext, useParams, useResolvedPath, useRevalidator, useRouteError, useRouteLoaderData, useRoutes, useSearchParams, useSubmit)

### Expected Behavior

Work with no probs

### Steps to Reproduce

Upgrade to react 18

### Code Reproduction URL

https://github.com/superm123/fjm

### Ionic Info

Using latest ionic props
[package.json](https://github.com/ionic-team/ionic-framework/files/15148745/package.json)

**Comment by liamdebeasi** [comment]
Can you make your repo public?

**Comment by superm123** [comment]
Maybe just give me a username or two and i will give you access

**Comment by liamdebeasi** [comment]
Can you make the repo public so the entire team has access? The reproduction case should contain only the code required to reproduce the issue, and any secret code should be removed.

**Comment by emitategh** [comment]
I'm facing the same issue, any news?

**Comment by superm123** [comment]
I personally think its just just the latest react router is not compatible
with react dom router 6

Just not got around to make a working example for them

Op Di. 14 Mei 2024 om 12:58 het Emi ***@***.***> geskryf:

**Comment by brandyscarney** [comment]
Hello, `@ionic/react-router` is not compatible with React Router 6. There is an open issue for this if you'd like to subscribe to it for updates: https://github.com/ionic-team/ionic-framework/issues/24177

If you are running into issues using `@ionic/react-router` with React Router 5, please open a new issue with a minimal reproduction that we can use to reproduce the issue. Thank you!
