### ISSUE TITLE
bug: occasional page animation issues

### ISSUE THREAD

**Issue by aparajita** [ionic-team/ionic-framework#29420]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Very occasionally, when navigating from a child route of a tab to another tab, an error occurs in the Ionic animation code.

### Expected Behavior

The animation code could do more sanity checking.

### Steps to Reproduce

This is impossible to reproduce, as it occurs very infrequently. But I have sentry reports that show exactly where in the Ionic code the error occurred. Hopefully this will be of some use.

The app has a tab interface. Some tabs have child routes. The two errors that occurred when navigating from a tab's child route to the top level of another tab.

### Code Reproduction URL

https://willsub.sentry.io/share/issue/a9efbebd5d4b400cab811a3020860031/

### Ionic Info

Ionic:

   Ionic CLI : 7.2.0 (/Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/node_modules/.pnpm/@ionic+cli@7.2.0/node_modules/@ionic/cli)

Capacitor:

   Capacitor CLI      : 5.7.5
   @capacitor/android : 5.7.5 (/Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/node_modules/.pnpm/@capacitor+android@5.7.5_@capacitor+core@5.7.5/node_modules/@capacitor/android)
   @capacitor/core    : 5.7.5 (/Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/node_modules/.pnpm/@capacitor+core@5.7.5/node_modules/@capacitor/core)
   @capacitor/ios     : 5.7.5 (/Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/node_modules/.pnpm/@capacitor+ios@5.7.5_@capacitor+core@5.7.5/node_modules/@capacitor/ios)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v21.7.1 (/Users/aparajita/Library/pnpm/nodejs/21.7.1/bin/node)
   npm    : 10.5.0
   OS     : macOS Unknown

### Additional Information

You can view the two sentry errors here:

https://willsub.sentry.io/share/issue/a9efbebd5d4b400cab811a3020860031/
https://willsub.sentry.io/share/issue/492895752f0b4618872aac1c08ca3d8b/

**Comment by liamdebeasi** [comment]
Thanks for the report. Unfortunately, we'll need a reproduction in order to verify if this is a bug or not. Are you able to start with your application and remove code until the issue no longer happens? That should help with making a minimal reproduction.

**Comment by aparajita** [comment]
Sorry, it's quite impossible to reproduce, as it must be a race condition.
