### ISSUE TITLE
bug: angular standalone  modal controller from compoent class getting error

### ISSUE THREAD

**Issue by lajith111** [ionic-team/ionic-framework#29430]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

ERROR NullInjectorError: R3InjectorError(Environment Injector)[_ModalController -> _ModalController]: 
  NullInjectorError: No provider for _ModalController!
    at NullInjector.get (core.mjs:1654:27)
    at R3Injector.get (core.mjs:3093:33)
    at R3Injector.get (core.mjs:3093:33)
    at ChainedInjector.get (core.mjs:15723:36)
    at lookupTokenUsingModuleInjector (core.mjs:5730:39)
    at getOrCreateInjectable (core.mjs:5778:12)
    at Module.ɵɵdirectiveInject (core.mjs:11050:19)
    at NodeInjectorFactory.TabsPage_Factory [as factory] (tabs.page.ts:26:22)
    at getNodeInjectable (core.mjs:5984:44)
    at createRootComponent (core.mjs:15998:35)

### Expected Behavior

should modal controller should work in component class

### Steps to Reproduce

ng s

### Code Reproduction URL

(https://stackoverflow.com/questions/78411880/upgrading-to-ionic-8-standalone-component-error-alert-controller)

### Ionic Info

Ionic 8.0.1 & standalone component

### Additional Information

As per suggestion https://github.com/ionic-team/ionic-framework/issues/28385#issuecomment-1789437096

i have added custom element but same error i am getting

**Comment by liamdebeasi** [comment]
Thanks for the issue! This issue is being closed due to the lack of a code reproduction. If this is still an issue with the latest version of Ionic, please create a new issue and ensure the template is fully filled out. Please be sure to include a runnable sample rather than only a code snippet or an error message.

Thank you for using Ionic!
