### ISSUE TITLE
bug: ion-radio labelPlacement doesn't apply class radio-label-placement-end

### ISSUE THREAD

**Issue by HaidarVladyslav** [ionic-team/ionic-framework#29440]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

```html
<ion-list>
  <ion-radio-group>
    <ion-list-header>Currency</ion-list-header>
    <ion-item>
      <ion-radio labelPlacement="end" value="eur">Euro</ion-radio>
    </ion-item>
  </ion-radio-group>
</ion-list>
```

and the element looks like this 
```html
<ion-radio labelplacement="end" value="eur" class="ios in-item radio-justify-space-between radio-alignment-center radio-label-placement-start" role="radio" aria-checked="false" tabindex="-1">Euro</ion-radio>
```

but when I change **labelPlacement** to **label-placement** - class is applied and label moves to the right 

```html
<ion-radio _ngcontent-ng-c1617513983="" label-placement="end" value="eur" class="ios in-item radio-justify-space-between radio-alignment-center radio-label-placement-end" role="radio" aria-checked="false" tabindex="-1">Euro</ion-radio>
```

### Expected Behavior

labelPlacement apply correct class to position label to the correct side
btw, I think that other option don't work too, I mean **stacked** and **fixed** 

### Steps to Reproduce

I think I can provide package json

```json
{
  "name": "name",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.2",
    "@angular/common": "^17.0.2",
    "@angular/compiler": "^17.0.2",
    "@angular/core": "^17.0.2",
    "@angular/forms": "^17.0.2",
    "@angular/platform-browser": "^17.0.2",
    "@angular/platform-browser-dynamic": "^17.0.2",
    "@angular/router": "^17.0.2",
    "@capacitor/app": "6.0.0",
    "@capacitor/core": "6.0.0",
    "@capacitor/haptics": "6.0.0",
    "@capacitor/ios": "6.0.0",
    "@capacitor/keyboard": "6.0.0",
    "@capacitor/status-bar": "6.0.0",
    "@ionic/angular": "^8.0.0",
    "ionicons": "^7.2.1",
    "rxjs": "~7.8.0",
    "swiper": "^11.1.1",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.0",
    "@angular-eslint/builder": "^17.0.0",
    "@angular-eslint/eslint-plugin": "^17.0.0",
    "@angular-eslint/eslint-plugin-template": "^17.0.0",
    "@angular-eslint/schematics": "^17.0.0",
    "@angular-eslint/template-parser": "^17.0.0",
    "@angular/cli": "^17.0.0",
    "@angular/compiler-cli": "^17.0.2",
    "@angular/language-service": "^17.0.2",
    "@capacitor/cli": "6.0.0",
    "@ionic/angular-toolkit": "^11.0.1",
    "@types/jasmine": "~5.1.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.57.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jsdoc": "^48.2.1",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~5.1.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.2.2"
  },
  "description": "An Ionic project"
}

```

if you can't repro it - please, let me know - will push code to git, because it's just my training and there is nothing private

### Code Reproduction URL

https://github.com/HaidarVladyslav/ionic-bug-radio-label-placement

### Ionic Info

repo added, I think you can reproduce
Thank you.

**Comment by sean-perkins** [comment]
Hello @HaidarVladyslav,

This is not an issue with Ionic Framework. 

In your reproduction case the `IntroPage` is not importing the `IonRadio`, `IonRadioGroup`, `IonList`, `IonListHeader` and `IonButton` components. As a result the elements you are referencing are using the web component output of Ionic Framework, not the Angular component wrappers we provide to match Angular's developer experience. 

Adding these components to the `imports` array will resolve your problem.

Thanks!

**Comment by HaidarVladyslav** [comment]
@sean-perkins oh, thank you so much. Interesting that it works with this **label-placement**. Could you please tell why?
