### ISSUE TITLE
bug: ion-radio does not keep checked-state after updating the underlaying object

### ISSUE THREAD

**Issue by mariusbolik** [ionic-team/ionic-framework#29442]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Initially, the `ion-radio-button` is checked correctly. But after updating the objects that contain the data that is used to display the ion-radion-buttons, the checked-state gets lost, even though the `value` property stays the same. Seems that this bug appears on Angular standalone projects.

Perhaps this error could be related to the following issue: https://github.com/ionic-team/ionic-framework/issues/29414
It could also be that this error can be found in other components, such as `ion-accordion`.

### Expected Behavior

The active ion-radio-button should be highlighted when it's value matches the value of it's containing ion-radio-group - as was the case before standalone components.

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/angular-vquurr-ec7ark?file=src%2Fapp%2Fexample.component.html
2. Click the "Update Data" Button

### Code Reproduction URL

https://stackblitz.com/edit/angular-vquurr-ec7ark?file=src%2Fapp%2Fexample.component.html

### Ionic Info

   Ionic CLI                     : 7.2.0
   Ionic Framework               : @ionic/angular 8.0.1
   @angular-devkit/build-angular : 17.3.6
   @angular-devkit/schematics    : 17.3.6
   @angular/cli                  : 17.3.6
   @ionic/angular-toolkit        : 11.0.1

**Comment by thetaPC** [comment]
Thank you for the issue!

I was able to replicate it and wrote up a fix for it. Feel free to test out the dev build:

`npm install @ionic/angular@8.1.1-dev.11714760012.1eab947e`

**Comment by thetaPC** [comment]
Thanks for the issue! This has been resolved via PR https://github.com/ionic-team/ionic-framework/pull/29457 and will be available in an upcoming release of Ionic.
