### ISSUE TITLE
feat: Ionic V8: Ion-Input Label Size CSS Custom Properties

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic-framework#29461]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

In ionic V8 new boiler template for ion-input where label is defined as part of ion-input, its now difficult to control the size of the label input. Requesting new CSS Custom Properties to set the size of the label.

```
<ion-input
[style.--label-size.px]="16"
  fill="outline"
  id="custom-input"
  label="Label Too Small"
  labelPlacement="floating"
></ion-input>
```

### Describe the Use Case

There are situations where the label size can be way too small especially when using floating outline label. 

For good accessibility being able to control the size of label would be great. 

<img width="409" alt="Screenshot 2024-05-04 at 5 22 11 pm" src="https://github.com/ionic-team/ionic-framework/assets/10624315/7608d230-d27e-4849-88cf-d0d6f0f0dfed">

### Describe Preferred Solution

new css property 
--label-size

Please consider impact to floating outline label. Currently the JS notch function is a fixed scale. For proposed change this would need to be based on the label-size

### Additional Information

Ionic Version 8

**Comment by brandyscarney** [comment]
Could you please provide an exact example of what you're trying to do so we can make sure the use case is covered? For example, what are you trying to set the label size to, and how does it look incorrect? Including code and screenshots of the problem are helpful. Thank you!
