### ISSUE TITLE
bug: Angular standalone datetime is missing formatOptions property

### ISSUE THREAD

**Issue by moh4sa** [ionic-team/ionic-framework#29464]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Can't bind to 'formatOptions' since it isn't a known property of 'ion-datetime'.

### Expected Behavior

works as expected on docs

### Steps to Reproduce

add `[formatOptions]="{
      time: { hour: '2-digit', minute: '2-digit' },
      date: { day: '2-digit', month: 'long' },
    }` property to `<ion-datetime> </<ion-datetime>`

### Code Reproduction URL

 https://github.com/moh4sa/dateTimeIssue
### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.1.0
   @angular-devkit/build-angular : 17.3.6
   @angular-devkit/schematics    : 17.3.6
   @angular/cli                  : 17.3.6
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.0.0
   @capacitor/android : 6.0.0
   @capacitor/core    : 6.0.0
   @capacitor/ios     : 6.0.0

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.9.0 (/usr/local/bin/node)
   npm    : 10.7.0
   OS     : macOS Unknown

**Comment by sean-perkins** [comment]
@moh4sa please double check the reproduction link provided. It links to a blank node example. 

When creating or linking a reproduction, please verify you are importing either the `IonDatetime` component if using standalone components or the `IonicModule` if using modules. This is required for binding camel case properties with Ionic's components in Angular.

**Comment by sean-perkins** [comment]
Hello @moh4sa, really appreciate the reproduction 🙏 this is a bug. I'll open a PR to address this.
