### ISSUE TITLE
I

### ISSUE THREAD

**Issue by Chulo66** [ionic-team/ionic-framework#29460]

**Comment by sean-perkins** [comment]
@Chulo66 if you are a real account, please avoid creating spam issues. This is your second incident within our community and you have multiple across other interactions with other projects. 

Repeated behavior will result in restricted access to submitting issues or viewing Ionic's open source projects.

Thanks!

**Comment by Chulo66** [comment]
Hello Ionic-Team/Ionic-Framework can you assist me with this? What’s
happening? Sorry I’m just start so if something is happening is not
intentional or can not be me, maybe something in my phone… any thoughts on
this? Thank you sorry again
