### ISSUE TITLE
bug: HTML Elements added via [innerHTML] to ion-label are hidden

### ISSUE THREAD

**Issue by JonathanIlk** [ionic-team/ionic-framework#29493]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Setting the HTML content of an `<ion-label>` inside an ìon-item` using angulars `[innerHTML]` attribute leads to the elements inside being hidden by default, because a `hidden=""` attribute is added to all the HTML elements inside.

![grafik](https://github.com/ionic-team/ionic-framework/assets/25324376/ecc1685b-fe5a-47d1-9f21-6ddef51f46ef)

![grafik](https://github.com/ionic-team/ionic-framework/assets/25324376/3fb34ca3-ae9a-4de5-a1cc-f9922bd6534e)

Btw: The link to the contributing Guidelines is broken (https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue)

### Expected Behavior

Elements added via the `[innerHTML]` attribute should be visible.

In **Ionic 7** this still works.

### Steps to Reproduce

1. Create an `<ion-list>` with an `<ion-item>` for which the `<ion-label>` contents are set via `[innerHTML]`.
2. Make sure the inner HTML contains a **HTML element** (e.g. `<span>`)
3. `ionic serve`
4. -> The **HTML element** is hidden

```
    <ion-list>
      <ion-item>
        <ion-label [innerHTML]="'<span>Span with Innerhtml</span>'">
        </ion-label>
      </ion-item>
    </ion-list>
```

### Code Reproduction URL

https://stackblitz.com/edit/angular-7f1suk?file=src%2Fapp%2Fexample.component.html

### Ionic Info

Ionic:

   Ionic CLI : 7.2.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.18.0
   npm    : 10.2.0
   OS     : Windows 10

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

I'm closing this issue since @sean-perkins responded with an answer via [Discord](https://discord.com/channels/520266681499779082/520358571720966154/1239590897201578096):

> You will need to [use](https://stackblitz.com/edit/angular-dmwvmp?file=src%2Fapp%2Fexample.component.html) the DomSanitizer API  to either by-pass or sanitize the HTML contents.
>
> This is to prevent malicious contents from being injected into your application from untrusted strings. 
>
> Previously Ionic Framework had it's own sanitization implementation. However, we decided to move away from it since it was not actively maintained to the standards required from official libraries and framework solutions that are specialized around that problem.

In case the link doesn't work:
```ts
// example.component.ts

import { Component, inject } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

@Component({
  selector: 'app-example',
  templateUrl: 'example.component.html',
  styleUrls: ['example.component.css'],
})
export class ExampleComponent {
  sanitizer = inject(DomSanitizer);
}
```

```html
<!-- example.component.html -->

<ion-label
  [innerHTML]="
    sanitizer.bypassSecurityTrustHtml('<span>Span with Innerhtml</span>')
  "
  >Label</ion-label
>
```
