### ISSUE TITLE
bug: Placeholder doesn't clear in input

### ISSUE THREAD

**Issue by SevenSystems** [ionic-team/ionic-framework#29500]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x, Nightly

### Current Behavior

Right on the homepage: Input placeholder text doesn't clear when input focused:

![2024-05-14_13-29](https://github.com/ionic-team/ionic-framework/assets/33262262/c623cffb-9a1e-4ed3-9153-bb1a56e06fed)

intrr@yoga:~$ chromium --version
Chromium 124.0.6367.155 built on Debian 12.5, running on Debian 12.5

Also happens in an Incognito window.

### Expected Behavior

t

### Steps to Reproduce

t

### Code Reproduction URL

https://ionicframework.com/

### Ionic Info

t

**Comment by SevenSystems** [comment]
Upon further investigation, this might actually be a layout issue and the text 'Name' is more intended as a label than as a placeholder. Still, it gives a bad first impression right on the demo page!

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

I'll have to close this issue as this is happening in a different repo. I'll be opening an internal ticket to track it though!
