### ISSUE TITLE
bug: InputInputEventDetail is not exported from ionic react

### ISSUE THREAD

**Issue by filifunk** [ionic-team/ionic-framework#29518]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

The type `InputInputEventDetail` is not importable to be used in an onIonInput component.

### Expected Behavior

We should be able to import like this:

`import type { InputInputEventDetail } from '@ionic/react`

That way the user should be able to use that as a type.

### Steps to Reproduce

1.  Use Ionic/React and TypeScript. 

2.  Use an IonInput component and then use onIonInput parameter.  

4. Use an event function.  When hovering over the event it says that it is of type `IonInputCustomEvent<InputInputEventDetail>`.  

5. Try to type it as `<InputCustomEvent<InputInputEventDetail>>`.  The error is Cannot find name `InputInputEventDetail`

6. Try to import the type:

`import type { InputInputEventDetail } from '@ionic/react'`

The error will be `Module '@ionic/react' has no exported member 'InputInputEventDetail'`

### Code Reproduction URL

https://ionic-react-first-app-5u1acp.stackblitz.io

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 8.1.0

Capacitor:

   Capacitor CLI      : 6.0.0
   @capacitor/android : 6.0.0
   @capacitor/core    : 6.0.0
   @capacitor/ios     : 6.0.0

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v20.12.2 (/usr/local/bin/node)
   npm    : 10.5.0
   OS     : Linux 5.14

  ───────────────────────────────────────────────

     Ionic CLI update available: 7.1.1 → 7.2.0
         Run npm i -g @ionic/cli to update

  ───────────────────────────────────────────────

### Additional Information

![image](https://github.com/ionic-team/ionic-framework/assets/68165894/41d5a70f-e0d0-4d2e-b236-078fc25950e8)

**Comment by thetaPC** [comment]
Thank you for the issue!

The repro URL isn't loading for me. Can you verify that the following snippet is the code that is causing you an issue?

```tsx
import React from 'react';
import { IonInput } from '@ionic/react';
import type { InputInputEventDetail, IonInputCustomEvent } from '@ionic/react'

function Example() {
  return (
    <IonInput label="input" value="53703" onIonInput={(e: IonInputCustomEvent<InputInputEventDetail>) => console.log(e)}></IonInput>
  );
}
export default Example;
```

**Comment by thetaPC** [comment]
I can verify that the issue exists! We'll be reviewing your PR soon!

**Comment by thetaPC** [comment]
Thanks for the issue! This has been resolved via PR https://github.com/ionic-team/ionic-framework/pull/29512 and will be available in an upcoming release of Ionic.
