### ISSUE TITLE
feat: statistic   example use card 

### ISSUE THREAD

**Issue by mohammad19974** [ionic-team/ionic-framework#29521]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

build statistic  example use  ion-card component

### Describe the Use Case

used. In displaying user data

**Comment by sean-perkins** [comment]
@mohammad19974 please provide significantly more detail, examples and use cases so the team can evaluate your feature request. 

With the provided information, the feature could be an infinite number of possibilities. 

Thank you!

**Comment by mohammad19974** [comment]
<img width="464" alt="Screenshot 2024-05-20 at 22 18 49" src="https://github.com/ionic-team/ionic-framework/assets/74828773/0345a644-9089-4acf-985f-119e4c255806">
@sean-perkins  like this 
up , down and  no data (key stats card)

**Comment by sean-perkins** [comment]
Hello @mohammad19974 after speaking with the team, we recommend you build this component as a custom component. The statistic card you referenced is not part of the Cupertino or MD2/3 specifications that Ionic Framework is built around. 

We have a few examples on the docs to get you started: https://ionicframework.com/docs/api/card#basic-usage

Alternatively you can use another component from another package that offers the experience you are looking for. Ionic Framework does not prevent you from mixing and matching UI components.

Thanks!
