### ISSUE TITLE
bug: Issue in Ion Title on Angular Nested Routes

### ISSUE THREAD

**Issue by satheshsat** [ionic-team/ionic-framework#29527]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

When created a nested routes with sidemenu. ion title in toolbar is hidden and toolbar in content section was moved below.

![image](https://github.com/ionic-team/ionic-framework/assets/114899099/02d91121-261f-4fc3-98e6-fac226bf53ec)

### Expected Behavior

Toolbar title should be displayed as it is. Ion Tiltle displayed below toolbar

### Steps to Reproduce

1. install ionic with sidemenu
2. Create seperate page
3. Move sidemenu to created page
4. set the browser to mobile view
5. click the url in browser and press enter to refresh
6. Run the code

### Code Reproduction URL

https://github.com/satheshsat/ionic

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (C:\Users\user\AppData\Roaming\nvm\v18.20.2\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 8.1.2
   @angular-devkit/build-angular : 17.3.7
   @angular-devkit/schematics    : 17.3.7
   @angular/cli                  : 17.3.7
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.0.0
   @capacitor/android : not installed
   @capacitor/core    : 6.0.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v18.20.2 (C:\Program Files\nodejs\node.exe)
   npm    : 10.5.0
   OS     : Windows 10

**Comment by sean-perkins** [comment]
@satheshsat the application should only have a single `ion-app` instance, which is in the `app.component.html`:

```diff
+<ion-app>
  <ion-router-outlet></ion-router-outlet>
+</ion-app>
```

Please refer to our [starters](https://github.com/ionic-team/starters) and [best practices for routing](https://ionicframework.com/docs/angular/navigation). Currently your navigation is configured for a web application with nested routes. This is not recommended and will not behave as expected for a mobile experience.
