### ISSUE TITLE
ion-alert got blurred after focus on input

### ISSUE THREAD

**Issue by ibroid** [ionic-team/ionic-framework#29524]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

![image](https://github.com/ionic-team/ionic-framework/assets/56104889/137361cd-5632-451c-98ef-5cd22832751c)

### Expected Behavior

![image](https://github.com/ionic-team/ionic-framework/assets/56104889/72063d9e-39f0-4159-bed2-cd0363767240)

### Steps to Reproduce

1. Trigger the alert
2. Focus on input

### Code Reproduction URL

https://github.com/ibroid/antrian-online

### Ionic Info

Ionic:

   Ionic CLI       : 6.20.8
   Ionic Framework : @ionic/react 8.1.2

Capacitor:

   Capacitor CLI      : 5.7.0
   @capacitor/android : not installed
   @capacitor/core    : 5.7.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v18.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : not installed
   OS     : Windows 10

### Additional Information

I just starting project with ionic, but i struggling after encountered this bug. 1 hour of searching got me nothing. please help.

**Comment by sean-perkins** [comment]
Hello @ibroid the team will need a few things to assist further:

1. The reproduction provided appears to be private, can you make that public? If you have sensitive code in your existing repository, please provide a new reproduction that is public without that information included. 
2. Can you provide a few comments on what you are expecting with your interactions and how it is a bug? With the screenshots, it is difficult to determine the issue you are reporting. If you are _not_ reporting a bug or feature request, the Discord is where support related cases are handled.

Thanks!

**Comment by ibroid** [comment]
Sure @sean-perkins i will change to public repository. 
Yes it is a bug, well theres no special style or logical complexity in my source code. just like i say before its just a starter ionic app.
However my point is to make an interact with user to inform their data, so the app can store it. To make this happen i try to use a ion-alert component with default input in it. Just copy and paste the code without any modification. When pop up modal show up, i try to focus (click) the input component, and suddently the modal was blurred. idk why. i try many css modification but its not working.

**Comment by ibroid** [comment]
the proble is in my google chrome browser. idk why, theres no spicious extension. 
so i will close this is issue.
iam sorry to waste your time XD and thank you for your attention sir @sean-perkins
