### ISSUE TITLE
bug: ngx-translate attribute breaks inside ion-label

### ISSUE THREAD

**Issue by nlsnightmare** [ionic-team/ionic-framework#29567]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

When using an ion-label with ngx-translate's translate directive the translated content appears multiple times inside the element.

### Expected Behavior

The translated string should only appear once.

### Steps to Reproduce

1. Create an ionic 8 project
2. install and setup ngx-translate
4. add the following code inside a component:
```html
<ion-label translate="some.key" />
``` 

### Code Reproduction URL

https://stackblitz.com/edit/angular-9b1hwe?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.2.0
   @angular-devkit/build-angular : 17.3.8
   @angular-devkit/schematics    : 17.3.8
   @angular/cli                  : 17.3.8
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 4.8.2
   @capacitor/android : 4.8.1
   @capacitor/core    : 4.8.2
   @capacitor/ios     : 4.8.2

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.1) : 1.7.4

System:

   NodeJS : v18.20.3 (/usr/bin/node)
   npm    : 10.8.0
   OS     : Linux 6.1

### Additional Information

This used to work in ionic 7.

**Comment by brandyscarney** [comment]
Thanks for the issue! I am not able to run your code reproduction, but I was able to modify one of our playgrounds and it seems to be working there: https://stackblitz.com/edit/angular-ctz1qf-wwiejz?file=src%2Fapp%2Fexample.component.html

Could you please modify this example to show the problem if this does not solve it for you?
