### ISSUE TITLE
bug: scrollbar is not switching sides in rtl in mobile Safari 

### ISSUE THREAD

**Issue by folsze** [ionic-team/ionic-framework#29569]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

On mobile safari, the scrollbar appears on the right still, even when setting

`direction: rtl;`

NOTE: it works on web safari. Only on mobile safari it does not.

https://stackoverflow.com/questions/7347532/how-to-position-a-div-scrollbar-on-the-left-hand-side

### Expected Behavior

On mobile safari, the scrollbar should appear the left, when setting

`direction: rtl;`

https://stackoverflow.com/questions/7347532/how-to-position-a-div-scrollbar-on-the-left-hand-side

it should look like here, which is safari web:

<img width="402" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/81622754/b45dd95e-fb2b-4eeb-8e9c-79450d3d8246">

### Steps to Reproduce

just scroll on tab 1 page. 

On safari web the scrollbar appears on the left as expected

BUT: On safari mobile the scrollbar appears on the right still...

### Code Reproduction URL

https://github.com/folsze/ionic-scrollbar-on-the-left-does-not-work

### Ionic Info

[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /usr/local/lib/node_modules/@ionic/cli/lib/project/index.js
       - /usr/local/lib/node_modules/@ionic/cli/lib/index.js
       - /usr/local/lib/node_modules/@ionic/cli/index.js
       - /usr/local/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 7.2.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.2.0
   @angular-devkit/build-angular : 17.3.8
   @angular-devkit/schematics    : 17.3.8
   @angular/cli                  : 17.3.8
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : not installed
   @capacitor/android : not installed
   @capacitor/core    : 6.0.0
   @capacitor/ios     : 6.0.0

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v16.20.2 (/Users/felixolszewski/.nvm/versions/node/v16.20.2/bin/node)
   npm    : 8.19.4
   OS     : macOS Unknown

### Additional Information

this is some slightly related disucssion I found:
https://github.com/ionic-team/ionic-framework/issues/5035#issuecomment-303702086

**Comment by brandyscarney** [comment]
Thanks for the issue! It looks like this is an issue in mobile Safari as I am able to reproduce it using divs outside of Ionic Framework: https://codepen.io/brandyscarney/pen/abrJZXx

You may want to look through reported bugs and report this to WebKit if one doesn't exist: https://bugs.webkit.org/
