### ISSUE TITLE
我对这个框架比较感兴趣但是我有一个疑问

### ISSUE THREAD

**Issue by LJR198** [ionic-team/ionic-framework#29597]
ionic这个框架是个跨平台的框架，支持 Vue React Angular,我是今天在掘金上看到的这个框架的介绍，但是我有个疑问，ionic有自己的移动端的UI组件库，但是我如果不想使用ionic的组件库，用 Vant组件库或者React的移动端组件库，可以使用吗？

**Comment by snowwolfjay** [comment]
为什么你要这样? 跨平台的实现是基于Capacitor的.... Ionic的跨平台属性指的是 ： 在不同的平台有很好的兼容性表现，例如安卓是安卓的风格，ios是IOS的风格（都是基于官方的设计语言）。混着用当然可以，但是没必要吧？
