### ISSUE TITLE
bug: Defining an icon in Action Sheet button properties does not render icon

### ISSUE THREAD

**Issue by magz99** [ionic-team/ionic-framework#29600]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x, v8.x

### Current Behavior

The `ion-action-sheet` component does not seem to render the icon provided in the `ActionSheetButton` properties. It happens both when the action buttons are passed as `[buttons]` property or via the `ActionSheetController`.
The `icon` value passed into the `ActionSheetButton` properties is an Ionicon name.

The `<ion-icon>` element will be rendered, but no icon is displayed.

<img width="487" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/1427502/c6f0d130-0d95-4582-97e2-d71fa980c742">

### Expected Behavior

The icon should be displayed within the `ion-icon` element that is rendered in the Action Sheet.

<img width="486" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/1427502/0fe54b40-d9eb-47f6-8e1c-4fda7f1411bc">

### Steps to Reproduce

1. Create the ActionSheetButton array, and one of the buttons will have `icon` defined.
2. For the `icon` value, use any of the Ionicons values. Example: `icon: 'add-circle-outline'`
3. Pass the button array to an action sheet element in the template:
```html
<ion-action-sheet
  trigger="open-action-sheet"
  class="my-custom-class"
  header="Example header"
  subHeader="Example subheader"
  [buttons]="actionSheetButtons"
></ion-action-sheet>
```
4. Observe the action sheet when it's opened, the icon will not be displayed

### Code Reproduction URL

https://stackblitz.com/edit/angular-mnydcf?file=src%2Fapp%2Fexample.component.html

### Ionic Info

I am using a stackblitz example taken from https://ionicframework.com/docs/api/action-sheet#theming

**Comment by Julien-Marcou** [comment]
You can fix it by doing this where you are using the action sheet:

```ts
import { addIcons } from 'ionicons';
import { addCircleOutline } from 'ionicons/icons';

class YourComponent {
  constructor() {
    addIcons({
      addCircleOutline: addCircleOutline,
    });
  }
}
```

But as you should only need to do this when you are using angular/standalone, this is probably a bug ^^

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

I'm closing this as a duplicate since we are tracking this bug through https://github.com/ionic-team/ionic-docs/issues/2892. It's related to StackBlitz. The bug doesn't occur outside of StackBlitz.

**Comment by magz99** [comment]
Got it thank you.
I tried in a non-standalone project and see the icon!
