### ISSUE TITLE
bug: ionic start failing to initialise new app 

### ISSUE THREAD

**Issue by snisar** [ionic-team/ionic-framework#29602]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Installed node and ionic on new Windows 11 laptop. Tried multiple attempt to start a new project, always fails with errors below. Uninstalled, cleaned cache, nothing has worked. Installed Angular CLI and created a new Angular only app with no issues.

ionic info

`Ionic:

   Ionic CLI : 7.2.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v22.2.0
   npm    : 10.7.0
   OS     : Windows 10`

ionic start

`c:\work>ionic start
? Use the app creation wizard? No

Pick a framework!

Please select the JavaScript framework to use for your new app. To bypass this prompt next time, supply a value for the
--type option.

? Framework: Angular

Every great app needs a name!

Please enter the full name of your app. You can change this at any time. To bypass this prompt next time, supply name,
the first argument to ionic start.

? Project name: Demo

Let's pick the perfect starter template!

Starter templates are ready-to-go Ionic apps that come packed with everything you need to build your app. To bypass this
prompt next time, supply template, the second argument to ionic start.

? Starter template: blank
? Would you like to build your app with NgModules or Standalone Components?
 Standalone components are a new way to build with Angular that simplifies the way you build your app.
 To learn more, visit the Angular docs:
 https://angular.io/guide/standalone-components

 Standalone
√ Preparing directory .\Demo in 2.05ms
√ Downloading and extracting blank starter in 2.57s
> ionic integrations enable capacitor --quiet -- Demo io.ionic.starter
> npm.cmd i --save -E @capacitor/core@latest
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'c:\\work\\Demo\\node_modules\\@typescript-eslint',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'c:\work\Demo\node_modules\@typescript-eslint\eslint-plugin\node_modules'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'c:\\work\\Demo\\node_modules\\@typescript-eslint\\eslint-plugin\\node_modules'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'c:\\work\\Demo\\node_modules\\@angular',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'c:\work\Demo\node_modules\@angular\compiler-cli'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'c:\\work\\Demo\\node_modules\\@angular\\compiler-cli'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'c:\\work\\Demo\\node_modules\\@ionic',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'c:\work\Demo\node_modules\@ionic\core\dist\collection\components'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'c:\\work\\Demo\\node_modules\\@ionic\\core\\dist\\collection\\components'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path c:\work\Demo\node_modules\nx
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node ./bin/post-install
npm error c:\work\Demo\node_modules\nx\src\native\native-bindings.js:244
npm error     throw loadError
npm error     ^
npm error
npm error Error: The specified module could not be found.
npm error \\?\C:\Users\saqui\AppData\Local\Temp\nx-native-file-cache-07bd7ee\19.2.2-nx.win32-x64-msvc.node
npm error     at Module._extensions..node (node:internal/modules/cjs/loader:1544:18)
npm error     at Module.load (node:internal/modules/cjs/loader:1249:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1065:12)
npm error     at Module._load (c:\work\Demo\node_modules\nx\src\native\index.js:66:25)
npm error     at Module.require (node:internal/modules/cjs/loader:1271:19)
npm error     at require (node:internal/modules/helpers:123:16)
npm error     at Object.<anonymous> (c:\work\Demo\node_modules\nx\src\native\native-bindings.js:66:29)
npm error     at Module._compile (node:internal/modules/cjs/loader:1434:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1249:32) {
npm error   code: 'ERR_DLOPEN_FAILED'
npm error }
npm error
npm error Node.js v22.2.0

npm error A complete log of this run can be found in: C:\Users\saqui\AppData\Local\npm-cache\_logs\2024-06-09T09_22_52_408Z-debug-0.log
[ERROR] An error occurred while running subprocess npm.

        npm.cmd i --save -E @capacitor/core@latest exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

Installing dependencies may take several minutes.

  ──────────────────────────────────────────────────────────────────────

      Ionic Enterprise, platform and solutions for teams by Ionic

                  Powerful library of native APIs
                 A supercharged platform for teams

         Learn more: https://ion.link/enterprise

  ──────────────────────────────────────────────────────────────────────

> npm.cmd i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'c:\\work\\Demo\\node_modules\\@angular',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'c:\work\Demo\node_modules\@angular\compiler-cli\node_modules\@babel'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'c:\\work\\Demo\\node_modules\\@angular\\compiler-cli\\node_modules\\@babel'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path c:\work\Demo\node_modules\nx
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node ./bin/post-install
npm error c:\work\Demo\node_modules\nx\src\native\native-bindings.js:244
npm error     throw loadError
npm error     ^
npm error
npm error Error: The specified module could not be found.
npm error \\?\C:\Users\saqui\AppData\Local\Temp\nx-native-file-cache-07bd7ee\19.2.2-nx.win32-x64-msvc.node
npm error     at Module._extensions..node (node:internal/modules/cjs/loader:1544:18)
npm error     at Module.load (node:internal/modules/cjs/loader:1249:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1065:12)
npm error     at Module._load (c:\work\Demo\node_modules\nx\src\native\index.js:60:27)
npm error     at Module.require (node:internal/modules/cjs/loader:1271:19)
npm error     at require (node:internal/modules/helpers:123:16)
npm error     at Object.<anonymous> (c:\work\Demo\node_modules\nx\src\native\native-bindings.js:66:29)
npm error     at Module._compile (node:internal/modules/cjs/loader:1434:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1249:32) {
npm error   code: 'ERR_DLOPEN_FAILED'
npm error }
npm error
npm error Node.js v22.2.0

npm error A complete log of this run can be found in: C:\Users\saqui\AppData\Local\npm-cache\_logs\2024-06-09T09_25_21_819Z-debug-0.log
[ERROR] An error occurred while running subprocess npm.

        npm.cmd i exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

c:\work>`

### Expected Behavior

ionic start generates new app without error

### Steps to Reproduce

1. install latest node version
2. install ionic cli globally
3. ionic start to init a new app

### Code Reproduction URL

https

### Ionic Info

c:\work>ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 7.2.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v22.2.0
   npm    : 10.7.0
   OS     : Windows 10

**Comment by sean-perkins** [comment]
Hello @snisar have you debugged the error that is being printed out in your terminal:
```
Error: EPERM: operation not permitted
```

This would signal that the CLI is not be ran with permissions for certain operations. Running with elevated permissions may resolve your problems.
