### ISSUE TITLE
bug:  ionic capacitor run ios -l --external

### ISSUE THREAD

**Issue by helloshaohua** [ionic-team/ionic-framework#29626]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

ionic capacitor run ios -l --external
? Which device would you like to target? iPhone 14 Pro (simulator) (5BF8D10D-D9B8-4B0F-ADF0-A17DE9A41D75)
> capacitor sync ios
[capacitor] ✔ Copying web assets from dist to ios/App/App/public in 446.94ms
[capacitor] ✔ Creating capacitor.config.json in ios/App/App in 2.88ms
[capacitor] ✔ copy ios in 571.14ms
[capacitor] ✔ Updating iOS plugins in 34.53ms
[capacitor] ✔ Updating iOS native dependencies with pod install in 6.03s
[capacitor] [info] Found 7 Capacitor plugins for ios:
[capacitor]        @capacitor/app@6.0.0
[capacitor]        @capacitor/camera@6.0.1
[capacitor]        @capacitor/filesystem@6.0.0
[capacitor]        @capacitor/haptics@6.0.0
[capacitor]        @capacitor/keyboard@6.0.1
[capacitor]        @capacitor/preferences@6.0.1
[capacitor]        @capacitor/status-bar@6.0.0
[capacitor] ✔ update ios in 6.27s
[capacitor] [info] Sync finished in 6.906s
[ERROR] No external network interfaces detected. In order to use the dev server externally you will need one.

        Are you connected to a local network?

### Expected Behavior

ionic serve --external
> vite --host=0.0.0.0 --port=8100
[vite]   ➜  Local:   http://localhost:8100/
[vite]   ➜  Network: http://192.168.0.116:8100/

### Steps to Reproduce

ionic capacitor run ios -l --external

### Code Reproduction URL

https://ionicframework.com/docs/cli/commands/capacitor-run

### Ionic Info

ionic capacitor run ios -l --external

### Additional Information

<img width="644" alt="image" src="https://github.com/ionic-team/ionic-framework/assets/53924395/37c67e0f-e3e9-438c-bccc-02d0423a18ab">

The documentation says that it is possible to use --external Host dev server on all network interfaces (i.e. --host=0.0.0.0) but it is not possible

**Comment by helloshaohua** [comment]
upgrade node version to [Node v18.12.0 (LTS)](https://nodejs.org/en/blog/release/v18.12.0) no problom!

**Comment by sean-perkins** [comment]
Closing as it seems you have resolved your issue. If the problem persists, please open an issue or PR to the ionic docs/ionic cli.

Thanks!
