### ISSUE TITLE
feat: Support for React framework(s) given that Create React App is deprecated

### ISSUE THREAD

**Issue by doug1e** [ionic-team/ionic-framework#29630]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Support to at least one of the React frameworks as Create React App is no longer supported by the React team.

### Describe the Use Case

Create React App and Ionic worked perfectly fine and enabled us to use almost all of code with minimal change. However, the Create React App option is removed from the React documentation as the React team wants developers to pick a framework instead. However, Ionic still uses Create React App approach which makes it difficult to look forward as I am not sure how Ionic wants to handle this change.

### Describe Preferred Solution

Preferably Ionic support for at least one of the popular frameworks

### Describe Alternatives

I see people using Expo but I prefer the Ionic way coding using CSS, etc.

**Comment by sean-perkins** [comment]
@doug1e Ionic is compatible with CRA or newer alternatives like Vite. Ionic starters use vite by default. Where are you seeing examples of Ionic still using CRA?

**Comment by jadejr** [comment]
@sean-perkins : i'd guess because this page https://react.dev/learn/start-a-new-react-project only talks about the frameworks  in the main content and vite (and others) are only mentioned when you click "Show Details" under "Can I use React without a framework? "

**Comment by sean-perkins** [comment]
I'm going to close this issue as Ionic React favors Vite instead of CRA. If you see outdated documentation, please report it on the ionic-docs repository or submit a PR to resolve. 

Thanks!
