### ISSUE TITLE
feat: gguf bundling

### ISSUE THREAD

**Issue by HansUXdev** [ionic-team/ionic-framework#29649]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The feature request is to enable the bundling of GGUF files within Ionic Framework applications, allowing developers to run local language models directly on iOS and Android devices using transformers.js. This feature aims to enhance privacy, reduce latency, and provide offline functionality for AI-driven applications.

### Describe the Use Case

Many applications today rely on cloud-based language models, which can lead to privacy concerns, increased latency, and dependency on an internet connection. By bundling GGUF files and utilizing transformers.js, developers can ensure that their apps can run language models locally on the user's device, improving performance and user privacy. This is particularly beneficial for applications requiring real-time language processing, such as voice assistants, chatbots, and personalized content generation.

### Describe Preferred Solution

The preferred solution is to integrate a GGUF file bundle option in the Ionic Framework's build process, along with the transformers.js library. This feature should include:

Model Pre-Packaging: Allow developers to bundle the GGUF files directly within the app during the build process. This ensures that end users have the language model included in their app download, eliminating the need for a separate model download post-installation. This integration simplifies the user experience, ensuring that all necessary components are available immediately upon installation. Users can instantly utilize the app's AI features offline without waiting for further downloads, providing immediate access to enhanced functionalities and reducing the risk of user error during the installation process.

Transformers.js and hugging face Integration: Utilize the transformers.js library to facilitate the loading and inference of the bundled models. This library supports running transformer models directly in the browser or in Node.js, making it a versatile tool for mobile app development.

Documentation and Examples: Provide comprehensive documentation and examples that guide developers through the process of bundling GGUF files within an Ionic application, initializing the local model, and using transformers.js for model inference on both iOS and Android platforms.

Efficient Deployment: Optimize the model loading and inference process to ensure smooth performance on mobile devices, leveraging device capabilities such as CPUs and GPUs for better efficiency.

### Describe Alternatives

Cloud-Based Models: Using cloud-based models can provide the latest updates and improvements but at the cost of user privacy and increased latency.
Other Local Model Formats: While formats like TensorFlow Lite and ONNX could be considered, GGUF provides a streamlined approach specifically designed for running efficient, compressed models on-device.
Alternative Libraries: Instead of transformers.js, other JavaScript libraries for model inference could be used, but transformers.js is widely adopted and supports a variety of models.

**Comment by sean-perkins** [comment]
Hello @HansUXdev, Ionic Framework is a UI component library. It has no opinionation around how you bundle auxiliary files within your application. That is a concern of the tools and frameworks you author an application using Ionic with.
