### ISSUE TITLE
bug: Vue ionic plugin has no type

### ISSUE THREAD

**Issue by Sukaato** [ionic-team/ionic-framework#29659]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

while using `.use(IonicVue, {})` on creating vue app, the config object of IonicVue has type and does not provide autocomplete.

### Expected Behavior

Has typed Vue plugin to have autocompete

### Steps to Reproduce

- create vue application
- add @ionic/vue
- add in main.ts `.use(IonicVue, {})`

See le config object has no autocomplete

### Code Reproduction URL

 https://github.com/Sukaato/vue-ionic-plugin-type

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0
   Ionic Framework : @ionic/vue 8.2.2

Capacitor:

   Capacitor CLI      : 6.1.0
   @capacitor/android : not installed
   @capacitor/core    : 6.1.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v22.3.0 (D:\software\NodeJS\node.exe)
   npm    : 10.7.0
   OS     : Windows 10

**Comment by reslear** [comment]
same problem 
<img width="691" alt="Screenshot 2024-06-26 at 21 51 16" src="https://github.com/ionic-team/ionic-framework/assets/12596485/42bd651c-eab5-4f45-bf38-3803501c08d4">

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

I can replicate this and agree that we should update the code to add it. I'll look at your PR this week!

**Comment by thetaPC** [comment]
Thanks for the issue! This has been resolved via your [PR](https://github.com/ionic-team/ionic-framework/pull/29637) and will be available in an upcoming release of Ionic.
