### ISSUE TITLE
ion-back-button over ion-toast

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionic-framework#29650]
The cloned ionic back button should be inside ion-app to handle z-index. Problem is that otherwise the ion-toast will be below the ion-back-button

https://github.com/ionic-team/ionic-framework/blob/ff214bd5f3da947d861d5d0b81575791c391a9b8/core/src/components/header/header.utils.ts#L28

https://stackblitz.com/edit/angular-aorbc6-mfnz2i

**Comment by danielehrhardt** [comment]
https://stackblitz.com/edit/angular-aorbc6-mfnz2i
navigate to the next page and then navigate back with the swipe back feature

**Comment by thetaPC** [comment]
@danielehrhardt please clarify the issue. I am able to navigate to the next page with the button and I can also swipe back to the previous page without issues.

**Comment by danielehrhardt** [comment]
> @danielehrhardt please clarify the issue. I am able to navigate to the next page with the button and I can also swipe back to the previous page without issues.

The Back button is over the Toast:
![image](https://github.com/ionic-team/ionic-framework/assets/19570043/325a62e7-d48f-4db7-b5c8-5af536b6997d)

**Comment by thetaPC** [comment]
@danielehrhardt What's the reason for setting `duration: 50_000000` instead of a smaller value? If you need a message to persist, using a toast component is not recommended. Toasts are designed to display only briefly.

**Comment by danielehrhardt** [comment]
> @danielehrhardt What's the reason for setting `duration: 50_000000` instead of a smaller value? If you need a message to persist, using a toast component is not recommended. Toasts are designed to display only briefly.

yes sorry, it was in the hurry to create a reproduction

**Comment by thetaPC** [comment]
I can confirm that the `ion-toast` component covers the contents within the `ion-header`. In order for this to not happen, the `ion-toast` needs to be anchored to the header.

```ts
// page-one.component.ts

// add an ID to `ion-header`
<ion-header [translucent]="true" id="header">
```
```ts
// app.component.ts
const toast = await this.toastCtrl.create({
  // add `positionAnchor` and use the ID from the header as the value
  positionAnchor: 'header'
});
```
You can learn more about `positionAnchor` under the ["Relative Positioning" page](https://ionicframework.com/docs/api/toast#relative-positioning) on the Ionic Framework docs.

**Comment by danielehrhardt** [comment]
> I can confirm that the `ion-toast` component covers the contents within the `ion-header`. In order for this to not happen, the `ion-toast` needs to be anchored to the header.
> 
> ```ts
> // page-one.component.ts
> 
> // add an ID to `ion-header`
> <ion-header [translucent]="true" id="header">
> ```
> 
> ```ts
> // app.component.ts
> const toast = await this.toastCtrl.create({
>   // add `positionAnchor` and use the ID from the header as the value
>   positionAnchor: 'header'
> });
> ```
> 
> You can learn more about `positionAnchor` under the ["Relative Positioning" page](https://ionicframework.com/docs/api/toast#relative-positioning) on the Ionic Framework docs.

I see you closed the Issue, but i do not really understand why. This is a bug, no element should be outside of ion-app or? For me there is no reason to push elements outside of ion-app. Maybe you can explain why?

**Comment by thetaPC** [comment]
Thank you for bringing this to our attention. We’ve carefully reviewed the issues you mentioned and would like to provide some clarity:

1. Back Button Transition: The back button requires a specific z-index to ensure smooth and proper transitions between pages. This is an integral part of the functionality.
2. Toast (Snackbar) Placement: We adhere to the [Material Design guidelines](https://m2.material.io/components/snackbars#placement), which do not recommend placing the toast (snackbar) on top of a header. This helps maintain a consistent and user-friendly interface.

We hope this clarifies why we won't be making any changes in this area.

**Comment by danielehrhardt** [comment]
> Thank you for bringing this to our attention. We’ve carefully reviewed the issues you mentioned and would like to provide some clarity:
> 
> 1. Back Button Transition: The back button requires a specific z-index to ensure smooth and proper transitions between pages. This is an integral part of the functionality.
> 2. Toast (Snackbar) Placement: We adhere to the [Material Design guidelines](https://m2.material.io/components/snackbars#placement), which do not recommend placing the toast (snackbar) on top of a header. This helps maintain a consistent and user-friendly interface.
> 
> We hope this clarifies why we won't be making any changes in this area.

1. If you put the ion-back-button element into the ion-app it works and you still can use z-index to ensure smooth transitions
2. It's a Animation iOS i am talking about, nothing related to the Material Design guidelines. 

It's your framework, but it's a bug and easy to fix.
