### ISSUE TITLE
bug: ion-datetime with locale="fa-ir" problem.

### ISSUE THREAD

**Issue by rraammiinn** [ionic-team/ionic-framework#29682]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

when you wana select a month it selects next month.

### Expected Behavior

you know it.

### Steps to Reproduce

you know it too.

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework

### Ionic Info

version : latest
framework : vue

**Comment by sean-perkins** [comment]
Feel free to resubmit the issue with the template filled out and a reproduction provided. Thanks!
