### ISSUE TITLE
bug: Can't Install CLI latest version (8)

### ISSUE THREAD

**Issue by alitalaee** [ionic-team/ionic-framework#29710]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Hello ionic team... 
I am using ionic version 7.2.0 now and i tried to upgrade it to latest version (8). not only for a project instead with CLI but when i tried below code 
`npm i -g @ionic/cli@latest`

it is installed 7.2.0 version again. so checked [npm.org ](https://www.npmjs.com/package/@ionic/cli) and it show latest is 7.2.0 from 6 month ago.. 

<img width="1084" alt="Screenshot 1403-04-24 at 17 56 02" src="https://github.com/user-attachments/assets/f13a6ed5-d61e-4bcb-a621-57416fe370f9">

**How Can I install ionic version 8 on my mac?**

### Expected Behavior

I want to install latest version of ionic 

### Steps to Reproduce

Upgrade to latest ionic 

### Code Reproduction URL

https://ionicframework.com/

### Ionic Info

version 7.2.0

**Comment by EinfachHans** [comment]
You are messing up the cli version and the framework version. These are two different projects
