### ISSUE TITLE
bug: loadingController message is not working with IonicSafeString, always return undefined --> ionic V8.X.X

### ISSUE THREAD

**Issue by phyr0s** [ionic-team/ionic-framework#29714]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

using IonicSafeString in loadingController service returns "undefined"

### Expected Behavior

Render de html in the message 

### Steps to Reproduce

Just call loadingController and in message --> message: new IonicSafeString('test string'),

### Code Reproduction URL

https://stackblitz.com/edit/angular-ywh4p1-crdxpc?file=src%2Fapp%2Fapp.component.ts

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/.nvm/versions/node/v18.20.4/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.2.5
   @angular-devkit/build-angular : 16.1.4
   @angular-devkit/schematics    : 16.1.4
   @angular/cli                  : 16.1.4
   @ionic/angular-toolkit        : 11.0.1
   
   System:

   ios-deploy : 1.12.2
   ios-sim    : 8.0.2
   NodeJS     : v18.20.4 (/Users/.nvm/versions/node/v18.20.4/bin/node)
   npm        : 10.7.0
   OS         : macOS Unknown
   Xcode      : Xcode 15.4 Build version 15F31d

**Comment by juanpablo-santos** [comment]
I'm expecting the same issue :-/

**Comment by sean-perkins** [comment]
@phyr0s the `innerHTMLTemplatesEnabled` config option must be enabled to use the `IonicSafeString`.

Example: https://stackblitz.com/edit/angular-ywh4p1-nte49v?file=src%2Fapp%2Fapp.module.ts

**Comment by agm** [comment]
Please reopen to review standalone
