### ISSUE TITLE
bug: Overlays override id assigned through htmlAttributes

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#29712]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Split from: https://github.com/ionic-team/ionic-framework/issues/29704

In Ionic v8, overlays are overriding the `id` specified in the `htmlAttributes` with the incremental overlay ID assigned by Ionic Framework. 

Applies to: modal, popover, action-sheet, loading, picker-legacy and toast.

### Expected Behavior

Ionic's overlay should not assign the incremental overlay ID if the overlay already has an ID assigned to it by either the `id` attribute directly or the `htmlAttributes`. 

### Steps to Reproduce

1. Create a new overlay, giving it a custom ID through `htmlAttributes`
2. Observe that the overlay does not have the custom ID

This applies to all overlays **except** `ion-alert`, which has been resolved: https://github.com/ionic-team/ionic-framework/pull/29708

For the reproduction URL we can either use the original reproduction and replace the alert with another overlay or assign `htmlAttributes` with an `id` property to any other overlay to observe the problem. 

### Code Reproduction URL

N/A

### Ionic Info

N/A - reproduces in Ionic v8+.

**Comment by mikelhamer** [comment]
I'm going to pick this up and start work!
