### ISSUE TITLE
bug: ion-datetime displays in ISO time when I set max min or default value

### ISSUE THREAD

**Issue by siddhant-dev** [ionic-team/ionic-framework#29720]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I'm passing my locale as en-IN and also setting a default value of `new Date().toISOString() ` but the date time component shows time in ISO Time zone only 
Example if it is 9:30AM in INDIA then the time picker defaults to 4:00AM.  refer the screenshot below

![image](https://github.com/user-attachments/assets/f35101ae-d939-413e-a80a-d782f744cfd6)

### Expected Behavior

It should so time picker in my the locale that we are passing to the component. 

### Steps to Reproduce

[https://stackblitz.com/edit/angular-bhw5wk?file=src%2Fapp%2Fexample.component.html](Stackblitz project )

I have recreated this using the IONIC DOCS example in v7 but I can confirm this happens in v8 as well. 

### Code Reproduction URL

https://stackblitz.com/edit/angular-bhw5wk?file=src%2Fapp%2Fexample.component.html

### Ionic Info

IONIC v7

**Comment by siddhant-dev** [comment]
I have workaround for this if anyone needs it 

``` typescript
  export const ionicDateFix = (inputDate: string = new Date().toISOString()) => {
  const date = new Date(inputDate);
  const hour = date.getHours();
  const min = date.getMinutes();
  const temp = inputDate.split('T');
  return `${temp[0]}T${prefixZero(hour)}:${prefixZero(min)}:00`;
};

const prefixZero = (val: number) => (val < 10 ? `0${val}` : `${val}`);
```

**Comment by sean-perkins** [comment]
@siddhant-dev please refer to the documentation around timezones: https://ionicframework.com/docs/api/datetime#time-zones

Ionic Framework uses the `locale` for localizing month and day names according to the language or region provided. Ionic does not manipulate the provided value to a given time zone. That is a responsibility of the implementer.

**Comment by siddhant-dev** [comment]
thanks @sean-perkins  for information. 
I completely missed this...
