### ISSUE TITLE
bug: Breaking of react types with ionic elements

### ISSUE THREAD

**Issue by VandykenNicholas** [ionic-team/ionic-framework#29755]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

IN INTELLIJ

<img width="558" alt="Screenshot 2024-08-06 at 2 02 31 PM" src="https://github.com/user-attachments/assets/96424a25-650a-4895-b316-43a287c9ae56">

In React 8, the types do not generate for Ion Elements

### Expected Behavior

The type to not be unknown, and have type interface help while coding.

### Steps to Reproduce

IDE:INTELLIJ

1.ionic start myapp --type=react
2. Add <Ion${anything ionic element}>
3. Hover 

### Code Reproduction URL

https://github.com/ionic-team/starters/tree/main/react/official/blank

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 8.2.6

Capacitor:

   Capacitor CLI      : 6.1.1
   @capacitor/android : 6.1.1
   @capacitor/core    : 6.1.1
   @capacitor/ios     : 6.1.1

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v21.7.2 (/opt/homebrew/Cellar/node/21.7.2/bin/node)
   npm    : 10.5.0
   OS     : macOS Unknown

**Comment by thetaPC** [comment]
This issue was fixed in [v8.2.8](https://github.com/ionic-team/ionic-framework/releases/tag/v8.2.8)! Please update to the latest version to receive the fix.
