### ISSUE TITLE
bug: ModalController componentProps support for input signals

### ISSUE THREAD

**Issue by magnacartatron** [ionic-team/ionic-framework#29767]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Currently one can pass in component props via the Ionic ModalController when in standard @Input format.
Props are not passed in to new input signals from Angular 18.

### Expected Behavior

Ideally we should be able to pass signals to component props 

### Steps to Reproduce

Create a modal controller instance for a component with new input signals.
Observe no props get passed through.

### Code Reproduction URL

no thanks, ionic wants access to private repos

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/alexbusse/.nvm/versions/node/v20.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.2.5
   @angular-devkit/build-angular : 18.1.1
   @angular-devkit/schematics    : 18.1.1
   @angular/cli                  : 18.1.1
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.0.0
   @capacitor/android : not installed
   @capacitor/core    : 6.0.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.14.0 (/Users/alexbusse/.nvm/versions/node/v20.14.0/bin/node)
   npm    : 10.7.0
   OS     : macOS Unknown

### Additional Information

I tried creating the stackblitz but requires me linking my GitHub account to ionic where you have access to private repos.

**Comment by dev-charles15531** [comment]
You should try to learn more on how to reproduce code on stackblitz.
The fact you authenticate with github does not mean ionic get access to your repo.

People find it easier helping you when you reproduce code.

**Comment by sean-perkins** [comment]
@magnacartatron Ionic does not want access to your private repos. The issue template is simply asking for a public example that the team can look at to verify the issue and debug it if necessary. This can be a blank application (we actually prefer that!). 

As mentioned by Charles, stackblitz is a great way to provide reproduction cases. You can authenticate with your github account to save examples.

Are you making use of the opt-in config option `useSetInputAPI` when using the input signals?

Without a reproduction I am unsure which syntax you are using, but you can pass it to either the `IonicModule.forRoot` or `provideIonicAngular`.
