### ISSUE TITLE
feat: Add a lines property to ion-select so that we can customise the lines of the ion-item within the ion-select

### ISSUE THREAD

**Issue by JulienLecoq** [ionic-team/ionic-framework#29777]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add a lines property to ion-select so that we can customise the lines of the ion-item within the ion-select.

### Describe the Use Case

In my mobile application, every ion-item inside an ion-list use the lines property to "full". I wish I could have the same setting for the ion-select so that ion-select, especially using the interface ``Popover`` looks more like my other ion-lists.

### Describe Preferred Solution

Just add the lines property similar to the one on ion-list, see: 

- https://ionicframework.com/docs/api/list#lines
- https://ionicframework.com/docs/api/list#list-lines

**Comment by brandyscarney** [comment]
Thanks for the issue! The `ion-select` can still be used inside an `ion-item` to take advantage of the full lines: [CodePen Example](https://codepen.io/brandyscarney/pen/MWMzMNE?editors=1010).

If this doesn't accomplish what you need, could you please provide a reproduction example of the problem for us? Thanks!
