### ISSUE TITLE
feat: Show various perspectives depending on the circumstances

### ISSUE THREAD

**Issue by angularsspace** [ionic-team/ionic-framework#29811]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I am looking for a solution to display a different component if my ngFor loop returns null.

```
 <ion-select interface="popover" [ngModel]="selectedKidId">
      <ion-option *ngFor="let kid of kids" [value]="kid.id">{{kid.name}}</ion-option>
    </ion-select>
  </ion-item>
```

Currently, this code displays a list of kids' names. However, I want to show a different view calling a separate component that I have created in case there are no kids in the list. Is there a way to achieve this?

Thank you

kids.ts

```
export class KidsPage {
  selectedKidId: string
  kids: Kid[] = []
  loveAmount: number

  constructor(
    public navCtrl: NavController,
    public navParams: NavParams,
    public modalCtrl: ModalController,
    private kidProvider: kidProvider,
  ) {
  }

  ionViewDidLoad() {

    this.fetchKids()
  }

  fetchKids() {
    this.kidProvider.getkid().subscribe(
      ({ data }) => {
        this.kids = data['mykids']
        if (this.kids.length > 0) {
          this.selectedKidId= this.kids[0].id
        }
      },
      (error) => {
        console.log(`fetchKids failed: ${JSON.stringify(error)}`)
      })
    this.kidProvider.subscribeToKids()
  }
```

### Describe the Use Case

https://angulars.space/questions/show-various-perspectives-depending-on-the-circumstances

**Comment by sean-perkins** [comment]
Hello @angularsspace this isn't the appropriate place to ask support related questions. Please refer to our discord or forums for such questions.

Thanks!
