### ISSUE TITLE
bug: ionChanged is not fired on ion-search        

### ISSUE THREAD

**Issue by arpho** [ionic-team/ionic-framework#29822]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Currently, the ionChange event is only fired from ion-searchbar when ENTER is pressed 

### Expected Behavior

ionChange event if fired when a key is pressed

### Steps to Reproduce

Use the Ionic Version 7 search bar
Type in it
ionChange events are not fired on keystrokes, but only on enter/submit 

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework/issues/26828

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/home/giuseppe/.nvm/versions/node/v20.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.8.6
   @angular-devkit/build-angular : 15.2.9
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 15.2.9
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.1) : 1.6.0

System:

   NodeJS : v20.15.1 (/home/giuseppe/.nvm/versions/node/v20.15.1/bin/node)
   npm    : 10.8.2
   OS     : Linux 6.5

### Additional Information

Ionic:

   Ionic CLI                     : 7.2.0 (/home/giuseppe/.nvm/versions/node/v20.15.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.8.6
   @angular-devkit/build-angular : 15.2.9
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 15.2.9
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : not installed
   @capacitor/core    : 3.5.1
   @capacitor/ios     : not installed

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 2.0.1) : 1.6.0

System:

   NodeJS : v20.15.1 (/home/giuseppe/.nvm/versions/node/v20.15.1/bin/node)
   npm    : 10.8.2
   OS     : Linux 6.5

**Comment by rasheeek** [comment]
Not a bug, check the documentation, You should use (ionInput) instead

**Comment by brandyscarney** [comment]
Thank you for the issue. This is the expected behavior. Please see the [Searchbar events documentation](https://ionicframework.com/docs/api/searchbar#events) for `ionChange`:

> The `ionChange` event is fired for `<ion-searchbar>` elements when the user modifies the element's value. Unlike the `ionInput` event, the `ionChange` event is not necessarily fired for each alteration to an element's value.
> 
> The `ionChange` event is fired when the value has been committed by the user. This can happen when the element loses focus or when the `"Enter"` key is pressed. `ionChange` can also fire when clicking the clear or cancel buttons.
> 
> This event will not emit when programmatically setting the value property.

To listen for changes to the `valu`e as it occurs, you should use `ionInput`.
