### ISSUE TITLE
bug: No reliable way to make ion-button programatically focusable

### ISSUE THREAD

**Issue by FabianGutierrezOpengov** [ionic-team/ionic-framework#29830]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

# Preexisting mentions
https://github.com/ionic-team/ionic-framework/issues/21439

# Issue

This have been asked before, but it seems the workaround provided here will clash with the internal `button` tag inside the component and makes button require two tab presses to move their focus to the next element. 

this in my humble opinion looks like an A11Y issue as we're nesting interactive elements.

### Expected Behavior

adding tabindex="0" should allow element to be programatically focusable but not make it to require 2 tabs to be jumped over

### Steps to Reproduce

check sample given at https://github.com/ionic-team/ionic-framework/issues/21439

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework/issues/21439

### Ionic Info

@angular-devkit/build-angular : 17.1.1
   @angular-devkit/schematics    : 17.1.1
   @angular/cli                  : 17.1.1
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI   : 6.1.2   @capacitor/core : 6.1.2
Utility:

   cordova-res : not installed
   native-run  : 2.0.1

System:

   NodeJS : v20.11.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.2.4
   OS     : Windows 10

**Comment by brandyscarney** [comment]
I spoke with the team and we decided to document the above usage. I've created an issue for this here: https://github.com/ionic-team/ionic-docs/issues/3815. Let me know if there are any issues with this. Thank you!
