### ISSUE TITLE
feat: make useIonModal hook type safety

### ISSUE THREAD

**Issue by dviravr** [ionic-team/ionic-framework#29831]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

make the `useIonModal` type-safety like ModalOptions

### Describe the Use Case

when I want to open a modal with react hook - useIonModal, there isn't type check on the component props

### Describe Preferred Solution

add a generic type to the hook
`export declare function useIonModal<T extends ComponentRef = ComponentRef>(component: T, componentProps?: ComponentProps<T>): UseIonModalResult<T>;`

**Comment by sean-perkins** [comment]
Closing as a duplicate of #28680.

https://github.com/ionic-team/ionic-framework/pull/29158 would be a good PR to reference if you are interested in submitting a PR for this.
