### ISSUE TITLE
feat: support srcset on ion-img

### ISSUE THREAD

**Issue by trydofor** [ionic-team/ionic-framework#29851]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

this feature https://github.com/ionic-team/ionic-framework/issues/18185 has been closed with no comments.

but the fixed-size image with variable density is needed for mobile development. e.g.

```htm
<img 
alt="A cat"
src="cat.jpg"
srcset="cat-2x.jpg 2x, cat-3x.jpg 3x"
>
```

please add the following props to ion-img

* width?: number
* height?: number
* srcset: string

or, let me know if there are any drawbacks to this idea.

### Describe the Use Case

the image is a fixed size in pixels, but for screens of different density.

**Comment by sean-perkins** [comment]
@trydofor the `ion-img` component doesn't serve any advantages to developers today over the `img` element. Developers should use the `img` tag directly. 

It is a component that has had low prioritization for deprecation/removal, but is unlikely to support newer features.

**Comment by trydofor** [comment]
Thanks for the answer, I will close this issue, use `img` instead.
