### ISSUE TITLE
bug: support react-router newer version like v6 (to avoid Vulnerability reporting)

### ISSUE THREAD

**Issue by kientrant1** [ionic-team/ionic-framework#29855]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

There is one vulnerability report when using react-router v5. It relates to **path-to-regexp** in react-router v5 - https://github.com/advisories/GHSA-9wv6-86v2-598j. However, currently, @ionic/react-router only support with react-router v5 - https://github.com/ionic-team/ionic-framework/blob/main/packages/react-router/package.json. So, there is no change to upgrade it.

### Expected Behavior

As I see, in react-router v6, the lib **path-to-regexp** has been removed. So, this issue may be resolved following that. Please help to review and see if @ionic/react-router can support the newer version of react-router - v6. 

### Steps to Reproduce

Just run "npm audit" and see blow report

`path-to-regexp  <=0.1.9 || 0.2.0 - 7.2.0
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
No fix available
node_modules/express/node_modules/path-to-regexp
node_modules/path-to-regexp
  react-router  4.0.0-0 - 5.3.4
  Depends on vulnerable versions of path-to-regexp
  node_modules/react-router
    @ionic/react-router  *
    Depends on vulnerable versions of react-router
    Depends on vulnerable versions of react-router-dom
    node_modules/@ionic/react-router
    react-router-dom  4.0.0-beta.1 - 5.3.4
    Depends on vulnerable versions of react-router
    node_modules/react-router-dom`

### Code Reproduction URL

https://github.com/ionic-team/ionic-framework/blob/main/packages/react-router/package.json

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0
   Ionic Framework : @ionic/react 7.8.3

Capacitor:

   Capacitor CLI      : 5.7.5
   @capacitor/android : 5.7.5
   @capacitor/core    : 5.7.5
   @capacitor/ios     : 5.7.5

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v20.15.0
   npm               : 10.7.0
   OS                : Windows 10

**Comment by brandyscarney** [comment]
Thanks for the issue! Closing as a duplicate of https://github.com/ionic-team/ionic-framework/issues/24177
