### ISSUE TITLE
bug: Ionic cap run fails with error "Invalid target ID: ?"

### ISSUE THREAD

**Issue by JulienLecoq** [ionic-team/ionic-framework#29886]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

When running: `ionic cap run iOS`, my device is shown with an id: `?`. Because of that, when selecting the device, it throws an error at the end of the running step.

<img width="687" alt="Screenshot 2024-09-20 at 10 46 53" src="https://github.com/user-attachments/assets/01b7dfc2-0cec-4744-9289-f096e751c951">

<img width="858" alt="Screenshot 2024-09-20 at 10 53 19" src="https://github.com/user-attachments/assets/05b7bbbd-81d6-43c6-a006-0f410120342c">

### Expected Behavior

The device id should be known and no error should be thrown.

### Steps to Reproduce

1. Create a new Ionic project.
2. Run: `ionic cap run ios`

### Code Reproduction URL

https://github.com/JulienLecoq/bug_ionic_cap_run_ios

### Ionic Info

[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'
       
       Require stack:
       - /Users/julien_lecoq/.nvm/versions/node/v20.14.0/lib/node_modules/@ionic/cli/lib/project/index.js
       - /Users/julien_lecoq/.nvm/versions/node/v20.14.0/lib/node_modules/@ionic/cli/lib/index.js
       - /Users/julien_lecoq/.nvm/versions/node/v20.14.0/lib/node_modules/@ionic/cli/index.js
       - /Users/julien_lecoq/.nvm/versions/node/v20.14.0/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/julien_lecoq/.nvm/versions/node/v20.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.3.1
   @angular-devkit/build-angular : 18.2.5
   @angular-devkit/schematics    : 18.2.5
   @angular/cli                  : 18.2.5
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : not installed
   @capacitor/core    : 6.1.2
   @capacitor/ios     : 6.1.2

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.14.0 (/Users/julien_lecoq/.nvm/versions/node/v20.14.0/bin/node)
   npm    : 10.7.0
   OS     : macOS Unknown

**Comment by manhtruongwang** [comment]
You can plugged in the device to bypass the error

**Comment by JulienLecoq** [comment]
Yes but I don’t want to. It’s been years since I’m using Xcode to bypass that issue to run the app remotely.
So if this can be solved, I would be very happy!

**Comment by tanner-reits** [comment]
@JulienLecoq I'm not sure that this would be an issue with Ionic Framework. This sounds like an issue related to Capacitor, please open an issue there or with the Ionic CLI
