### ISSUE TITLE
bug: ionFocus event in ion-select is fired when the popover disappears

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#29904]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

The ionFocus event in ion-select is fired when the popover disappears.

https://ionicframework.com/docs/api/select#events

PS: I discovered this while trying to manually fix this issue... -> https://github.com/ionic-team/ionic-framework/issues/19296

### Expected Behavior

It should only be triggered on focus.

### Steps to Reproduce

https://stackblitz.com/edit/angular-gmxghz?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

### Code Reproduction URL

https://stackblitz.com/edit/angular-gmxghz?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

### Ionic Info

```
Ionic:

   Ionic CLI                     : 7.2.0 
   Ionic Framework               : @ionic/angular 8.3.0
   @angular-devkit/build-angular : 18.2.4
   @angular-devkit/schematics    : 18.2.4
   @angular/cli                  : 18.2.4
   @ionic/angular-toolkit        : 12.1.1

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : not installed
   @capacitor/core    : 6.1.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v20.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.8.1
   OS     : Windows 10
```

**Comment by tanner-reits** [comment]
@Marius-Romanus This is expected behavior ([source code](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/select/select.tsx#L317)). When the overlay is active, we create a focus trap in the overlay to prevent focusing elements behind the popover, so when the popover closes, we need to re-focus the select since that was the last focused element before the popover was opened.
