### ISSUE TITLE
feat: Programmatically focus an ion-button

### ISSUE THREAD

**Issue by mortifia** [ionic-team/ionic-framework#29919]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be really useful to programmatically focus an ion-button (without having two focus states on the same element at different levels).

References:

[GitHub Issue](https://github.com/ionic-team/ionic-framework/issues/21439#issuecomment-644740507)
[MDN Web Docs on ShadowRoot.delegatesFocus](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus)
Now, all browsers support delegatesFocus."

### Describe the Use Case

avoid to config  ion-button two times (on click and on keyup.enter)

**Comment by brandyscarney** [comment]
Thanks for the issue! This can be done by calling `setFocus` on the `ion-app`: https://ionicframework.com/docs/api/app#programmatic-focus

Does this solution work for your use case?
