### ISSUE TITLE
bug: regression: IonRouterOutlet ref is always undefined

### ISSUE THREAD

**Issue by aeharding** [ionic-team/ionic-framework#29924]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

In ionic 8.2.6, I could get the ref (React) like the following:

```
const ref = useRef();

requestAnimationFrame(() => {
  console.log(ref.current);
});

return <IonRouterOutlet ref={ref} />
```

Which prints:

<img width="258" alt="image" src="https://github.com/user-attachments/assets/b4dd4c62-2369-425c-9d09-be68a7068647">

In Ionic 8.3.2, this prints:

<img width="474" alt="image" src="https://github.com/user-attachments/assets/e8ba1214-724c-4efd-977d-4f72b86a4d1e">

### Expected Behavior

8.2.6 behavior

### Steps to Reproduce

1. Clone https://github.com/aeharding/bugged-outlet
2. Checkout branch `8.2.6`. Install, `ionic serve`
3. Observe expected output in console
4. Checkout branch `8.3.2`. Install, `ionic serve`
5. Observe bugged output (all `undefined`)

### Code Reproduction URL

https://github.com/aeharding/bugged-outlet

### Ionic Info

```
Ionic:

   Ionic CLI       : 7.2.0 (/Users/aeharding/.nvm/versions/node/v22.1.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 8.3.2

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : not installed
   @capacitor/core    : 6.1.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v22.1.0 (/Users/aeharding/.nvm/versions/node/v22.1.0/bin/node)
   npm    : 10.7.0
   OS     : macOS Unknown
```

**Comment by thetaPC** [comment]
Thank you for submitting the issue!

I was able to replicate it and a fix will be available soon!
