### ISSUE TITLE
feat: add `--justify-content` variable to button component

### ISSUE THREAD

**Issue by craigbehnke** [ionic-team/ionic-framework#29935]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add a css variable to pierce the button component's shadow dom and allow for custom justification of the button's contents.

### Describe the Use Case

This would work well for supporting buttons in lists, where all of the existing text is aligned to one side and where the button should be full-width to support easier clicking & tapping.

### Describe Preferred Solution

Add a `--justify-content` css variable to the button definition. This variable should be used in the `span.button-inner` component, with the fallback being the current behavior of 'center'.

[Here's the location in code where this should be added](https://github.com/ionic-team/ionic-framework/blob/bbcbf5c425c74d99c46e01a233be348909f13633/core/src/components/button/button.scss#L204)

### Describe Alternatives

The only alternative to get the desired behavior is to create a button component from scratch, which would result in having to miss out on many other features already included in the IonButton.

**Comment by brandyscarney** [comment]
Thanks for the issue! You can achieve this by wrapping the button content in a div and styling that however you'd like: https://codepen.io/brandyscarney/pen/MWNEEvO?editors=1000

Is this what you are looking for?

**Comment by craigbehnke** [comment]
Yep, that worked. Thank you!
