### ISSUE TITLE
feat: add custom icon override for menu button

### ISSUE THREAD

**Issue by craigbehnke** [ionic-team/ionic-framework#29934]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Add a configuration option for the IonMenuButton component to allow developers to override the icon used.

### Describe the Use Case

Creating an override option would allow developers to more easily create an application with more than one menu/sidebar, without either
1. Having 2 buttons look identical
2. Needing to create a menu button component of their own

### Describe Preferred Solution

Create a config option for the menu button that overrides the default icons.

So this:
```tsx
const menuIcon = config.get('menuIcon', mode === 'ios' ? menuOutline : menuSharp);
```
would become something like this:
```tsx
let menuIcon = config.get('menuIcon', mode === 'ios' ? menuOutline : menuSharp);
if (customIcon) {
  menuIcon = customIcon;
}
```
[link to existing code](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/menu-button/menu-button.tsx)

### Describe Alternatives

I could create a clone of the component that uses a custom icon, but this would cause the

**Comment by brandyscarney** [comment]
Thanks for the issue! You can achieve this by wrapping a button with an icon inside an `ion-menu-toggle`:

```html
<ion-menu-toggle>
  <ion-button>
    <ion-icon name="heart" slot="icon-only"></ion-icon>
  </ion-button>
</ion-menu-toggle>
```

Code preview: https://codepen.io/brandyscarney/pen/zYgEpwo?editors=1010

Does this solution match what you’re looking for? If not, could you please elaborate on how you intend to use `ion-menu-button`?

**Comment by craigbehnke** [comment]
That works! 

I think it might be a good idea to include that in the documentation somehow; currently the only area in the doc website that even suggests that this is possible is [the section regarding the available slots for the `ion-menu-toggle` component](https://ionicframework.com/docs/api/menu-toggle#slots), which is still obscure if you're trying to solve this problem using `ion-menu-button`. It seems like including this as a capability on the `ion-menu-button` page might help more people down the line.

Feel free to close this if you disagree with this capability being included in the docs, but I'll keep it open for you to decide. Either way, my problem is now solved!

**Comment by brandyscarney** [comment]
Thanks for the quick response! We have a demo for `ion-menu-toggle` on the [menu documentation](https://ionicframework.com/docs/api/menu#menu-toggle) but it only shows a button with text. Do you think it would be helpful to include one with an icon in the header?
