### ISSUE TITLE
bug: Inconsistent Behavior of ion-card Title and Subtitle in Ionic 7

### ISSUE THREAD

**Issue by souravion** [ionic-team/ionic-framework#29946]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

I just noticed that the title and subtitle in ion-card have changed in Ionic 7. In my app, I use ion-card with a title and subtitle. Now, in Ionic 7, the title appears at the top of the card and the subtitle below it, while in iOS, it displays the other way around.

If I have a short title and a long subtitle, the layout may not look good on iOS. Is this a change that Ionic made intentionally, or is it a bug?

### Expected Behavior

The expected behavior should be the same as on Android, because in a hybrid platform, we maintain a single code base. If the behavior differs across platforms, it becomes difficult to manage the code.

### Steps to Reproduce

https://ionicframework.com/docs/v7/api/card

### Code Reproduction URL

https://github.com/souravion/test-app/tree/main

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.5
   Ionic Framework               : @ionic/angular 6.7.5
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.3.11
   @angular/cli                  : 13.3.11
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : 6.1.2
   @capacitor/core    : 6.1.2
   @capacitor/ios     : 6.1.2

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v18.18.2
   npm    : 9.8.1
   OS     : Windows 10

**Comment by brandyscarney** [comment]
Thank you for the issue! This design choice was intentional to match the cards used in the App Store:

<img width="50%" src="https://github.com/user-attachments/assets/51920fe6-e811-49d3-b3fe-66c7d2c40e11" alt="Apple App Store Card">

If you would like the title to be first for both `ios` and `md`, you can change the order using CSS:

```css
ion-card-header {
  flex-direction: column;
}
```

Example: https://codepen.io/brandyscarney/pen/OJKxOwQ?editors=1100

**Comment by souravion** [comment]
Hi @brandyscarney Thank you for the clarification! I appreciate the explanation regarding the design choice to align with the App Store card layout.

I will implement the suggested CSS change to ensure consistency across platforms. However, I hope future versions can consider a more unified approach to component layouts, as differing designs can complicate development in a hybrid environment.

Thanks again for your help!
