### ISSUE TITLE
feat(ion-modal): change .ion-handle top position 

### ISSUE THREAD

**Issue by rbalet** [ionic-team/ionic-framework#29966]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

I'd like to be able to change the ion-handle top position from 5px to 8px.

### Describe the Use Case

Just UI decision

### Describe Preferred Solution

being able to have a css variable available `top: var(--ion-handle-top, 8px)`

### Describe Alternatives

Let me know the variable name and I can make a pull-request

**Comment by tanner-reits** [comment]
@rbalet You should be able to do this using the exposed `handle` CSS part (all modal parts can be found in the [docs](https://ionicframework.com/docs/api/modal#css-shadow-parts)).

```css
.my-modal::part(handle) {
  top: 8px;
}
```
