### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by gasci** [ionic-team/ionic-framework#29984]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

```
Blocked aria-hidden on a <body> element because it would hide the entire accessibility tree from assistive technology users. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. 
```

### Expected Behavior

This Chrome error shouldn't be shown

### Steps to Reproduce

Just start the app

### Code Reproduction URL

https://web.docorbit.com/auth

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 8.3.4

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : 6.1.2
   @capacitor/core    : 6.1.2
   @capacitor/ios     : 6.1.2

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v22.9.0 (/opt/homebrew/Cellar/node/22.9.0_1/bin/node)
   npm    : 10.9.0
   OS     : macOS Unknown

**Comment by tanner-reits** [comment]
@gasci Can you please add some context about the issue and the error you're seeing? Also a more descriptive issue title would be appreciated 🙂
