### ISSUE TITLE
bug: Swipeable Segments - segment not connecting to segment-view in Angular

### ISSUE THREAD

**Issue by Hesesses** [ionic-team/ionic-framework#30000]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Swipeble segments' segment buttons not working with variables:

```
<ion-segment mode="md" [value]="value">
  @for (button of buttons; track button.label) {
    <ion-segment-button [value]="button.value" [contentId]="button.value">
      <ion-label>{{ button.label }}</ion-label>
    </ion-segment-button>
  }
</ion-segment>
```

If I add manually segment-button with the content-id of the first segment view (general) it works:
```
<ion-segment mode="md" [value]="value" (ionChange)="onChange.emit($event)" [scrollable]="true">
  <ion-segment-button [value]="" content-id="general" style="margin-right:0px"></ion-segment-button>
  @for (button of buttons; track button.label) {
  ....
  ```
  
  If I add the same like this [contentId]= it doesnt work:
  ```
  <ion-segment mode="md" [value]="value" (ionChange)="onChange.emit($event)" [scrollable]="true">
  <ion-segment-button [value]="" [contentId]="'general'" style="margin-right:0px"></ion-segment-button>
  @for (button of buttons; track button.label) {
  ```
  
  Note: ion-segment-views are swipeable, swiping doesnt change active status of segment buttons or clicking segment-buttons doesnt change the view.

### Expected Behavior

Swipeable tabs would work when using variables for content-id / [contentId]

### Steps to Reproduce

Play around with the code on "current behaviour"

### Code Reproduction URL

no url

### Ionic Info

Ionic:

   Ionic CLI                     : 7.2.0 (/Users/.../.nvm/versions/node/v18.20.4/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 8.4.0
   @angular-devkit/build-angular : 17.3.11
   @angular-devkit/schematics    : 17.3.11
   @angular/cli                  : 17.3.11
   @ionic/angular-toolkit        : 11.0.1

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : 6.1.2
   @capacitor/core    : 6.1.2
   @capacitor/ios     : 6.1.2

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v18.20.4 (/Users/.../.nvm/versions/node/v18.20.4/bin/node)
   npm    : 10.7.0
   OS     : macOS Unknown

**Comment by marcoagsa** [comment]
I’m experiencing the same issue reported and have created an example on StackBlitz to help demonstrate it: 
[stackblitz Example](https://stackblitz.com/~/github.com/marcoagsa/ionicSegmentViewExample?file=src/app/home/home.page.html.) 
Could you please take a look and let me know if there’s any solution or workaround available?

Thank you for your assistance!

<img width="968" alt="Captura de ecrã 2024-11-12, às 22 48 52" src="https://github.com/user-attachments/assets/703a1e6d-ef27-4750-88cb-6aa6062e6627">

**Comment by Hesesses** [comment]
Any updates on this?

**Comment by vadimwe** [comment]
The same problem:
Wrong content if activeView is "request". Does not matters contentId or [contentId] or content-Id used

```
<ion-segment [(ngModel)]="activeView" [value]="activeView">
      <ion-segment-button contentId="send_content" value="send">
        Send
      </ion-segment-button>
      <ion-segment-button contentId="request_content" value="request">
        Request
      </ion-segment-button>
</ion-segment>

<ion-segment-content id="send_content">...</ion-segment-content>
<ion-segment-content id="request_content">...</ion-segment-content>
```
